### ISSUE TITLE
Macro support

### ISSUE THREAD

**Issue by AndersenJ** [VSCodeVim/Vim#100]
It may take a long time before anyone can get to this, which is fine, but it would be great if this plugin eventually supported Vim macros.

**Comment by johnfn** [comment]
I'm going to get started on this now.

**Comment by johnfn** [comment]
I was totally wrong about that but the very talented @rebornix started working on it instead: https://github.com/VSCodeVim/Vim/pull/894

**Comment by rebornix** [comment]
It's already in master. You can see this feature once we have another release.
