### ISSUE TITLE
In Normal Mode, command+a select all and can not type x to delete

### ISSUE THREAD

**Issue by Laily123** [VSCodeVim/Vim#1000]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----
### What did you do?
In normal mode, type `command+a` select all content and then type `x` to delete.

### What did you expect to happen?
delete all the content I selected

### What happened instead?
just cancel the select status, and delete nothing.

### Technical details:

* VSCode Version: 1.6.1 
* VsCodeVim Version: 0.4.0
* OS: OSX 10.11.6

**Comment by johnfn** [comment]
This must be because we're not registering the cmd-a action so we don't update VimState internally. Should be easy to add a stub Cmd-a action that sets selection to the entire document.

**Comment by Laily123** [comment]
@johnfn Thank you !
