### ISSUE TITLE
Multicursor-insert inserts on empty lines

### ISSUE THREAD

**Issue by Phrohdoh** [VSCodeVim/Vim#1003]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

`ctrl-v`
`I// <esc>`
### What did you expect to happen?

First non-whitespace chars on non-empty lines only would be `//`.
### What happened instead?

`//` was also inserted on the empty line.
### Technical details:
- VSCode Version: 0.19.1
- VsCodeVim Version: 0.4.0
- OS: macOS Sierra (10.12)

![vscode-vim-multicursor-insert](https://cloud.githubusercontent.com/assets/4861023/19783737/ae021d0a-9c58-11e6-9988-64e1a2e7ce7d.gif)

**Comment by johnfn** [comment]
Interesting. This isn't a hard one to fix.

**Comment by Phrohdoh** [comment]
@johnfn Would you expand on that a bit, please?
Someone may come along with the desire to fix this (unless you are working on this already).

**Comment by johnfn** [comment]
Sure, it sounds like our visual cursor insert action needs to iterate only over lines that have content in them, rather than all lines. Should be a very small change. :)
