### ISSUE TITLE
.vimrc?

### ISSUE THREAD

**Issue by chantisnake** [VSCodeVim/Vim#101]
Can you read default vimrc?

**Comment by jpoon** [comment]
No .vimrc. Instead, configurations will go into the `settings.json`. Readme has been updated on the settings we have and how to configure.

**Comment by schickling** [comment]
I think it is not just me when I say that this (missing) feature is critical in order to bring existing VIM users to VSCode.

**Comment by zhaochy1990** [comment]
Is .vimrc supported at 2017?

**Comment by johnfn** [comment]
@schickling Sorry for the slow response, but it doesn't have to be just you! We implement features in order of demand, sorting features by number of thumbs-up reactions and going down the list. So feel free to hop over to #463 and thumbs it up; that will make us prioritize it.

**Comment by johnfn** [comment]
Holy crap, I just realized it was Feb 23, 2016, not Feb 23, 2017.
