### ISSUE TITLE
Substitute interactive mode doesn't work

### ISSUE THREAD

**Issue by NikosEfthias** [VSCodeVim/Vim#1010]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

since `ctrl+d` does not work proper trying to use the substitute for multi-place edits
Put the exact keys you pressed.
:%s/someWord/anotherWord/gc
### What did you expect to happen?

ask me to confirm before replacing the matches
### What happened instead?

c flag is ignored and everything is just replaced
### Technical details:
- VSCode Version:1.6x
- VsCodeVim Version: .4
- OS: ubuntu 16.4

**Comment by rebornix** [comment]
We didn't implement `c` flag yet but it's quite easy.

**Comment by NikosEfthias** [comment]
looking forward to it :)

**Comment by truelson** [comment]
Yes please! This is a vital part of my workflow

**Comment by betogil** [comment]
Can you inform us when the feature is implemented, please?

**Comment by Chillee** [comment]
@betogil Which parts in particular are the most important?

**Comment by betogil** [comment]
I'd like to know when search and replace by visual mode is implemented.
e.g. in vim command line type '<,'>s/old_word/new_word/gc
The editor should ask as well.

**Comment by bocajnotnef** [comment]
Bit frustrating that the roadmap says confirm works, but here it's an acknowledged bug...

**Comment by bowmanmike** [comment]
It looks to me like using replace with the `c` flag breaks the replace altogether. Any update on this?

VSCode 1.17.2, MacOS High Sierra, VSCode Vim 0.10.2

**Comment by KyleSu** [comment]
Are there any updates on implementing the `c` flag?

**Comment by Chillee** [comment]
@bowmanmike I assume you're using neovim integration? If so, what's happening is that neovim then provides a prompt (which we have no method of accessing), and we detect that and cancel the ex command.

@KyleSu Not really. There's basically 2 potential approaches to obtaining this feature. First, we could implement it in VSCode somehow, using our own custom implementation and UI. Alternately, we could try to get it from neovim somehow. However, there are 2 obstacles to the neovim approach. First, we're unable to get data from neovim when it's in the interface and second, we're unable to get the confirmation prompt.

**Comment by KyleSu** [comment]
@Chillee So if it were to be implemented you would choose to take the first approach, but that's not high on the list of priorities. Does that sound about right?

**Comment by Chillee** [comment]
@KyleSu Well currently, I'm pursuing stuff related to the second approach here: https://github.com/chillee/vscodeneovim, which means that its implementation is largely dependent on the whims of the neovim developers.

However, if I had to implement it now, I would choose the first approach. Therefore, since I'm  currently focused on the neovim rewrite, this issue is not high on my list of priorities.

**Comment by KyleSu** [comment]
@Chillee That makes sense. As much as I'd like to see it soon, neovim integration is a bigger deal. Thanks for the info!

**Comment by u2berggeist** [comment]
Possibly dumb question, but could it the `-c` tag simply be implemented through VS Code's built in find-and-replace functionality? As in if the `-c` tag is displayed, pass along the inputs to the built in VS Code version (so the find value, the replace value, the particular section to look at, etc), then provide key mappings to connect the standard Vim commands to the VS Code equivalents when in this mode?

**Comment by xconverge** [comment]
Interesting, this is now only fixed for the case where you are NOT using the neovim integration.

**Comment by ecbrodie** [comment]
@xconverge @Chillee I just filed #3371 to record the lack of functionality with Neovim integration enabled as an issue.
