### ISSUE TITLE
Hitting backspace don't move cursor to previous indent line

### ISSUE THREAD

**Issue by rajinder-yadav** [VSCodeVim/Vim#1018]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Insert new line, hit tab, the backspace.

Cursor only move back a single space.

Expect should just back to previous indent column.

FYI: Verified vscode without plugins, work as expected.

### Technical details:

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.1
* OS: Linux

**Comment by johnfn** [comment]
More or less fixed on master and will be out in 0.4.7. 

There is a problem where VSCode may give us back the wrong tab size. We're going to need this issue to be resolved before this one is perfect: https://github.com/Microsoft/vscode/issues/16466

**Comment by johnfn** [comment]
Should now be perfect. Will be out in 0.4.9.
