### ISSUE TITLE
'=' seems not work

### ISSUE THREAD

**Issue by poppinlp** [VSCodeVim/Vim#1019]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Select some code and press '='.

### What did you expect to happen?

Format the selected code.

### What happened instead?

Nothing.

### Technical details:

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.1
* OS: Windows 10

**Comment by jpoon** [comment]
We had this at one point, https://github.com/VSCodeVim/Vim/commit/c0a061109913e9e0f593a3f3c4b3afc99c0415f6. Trying to track history of what happened to this command.

**Comment by rebornix** [comment]
@poppinlp it's a regression though :( Code updated related APIs in 1.7 Insiders so I aligned with it. But we still haven't released Code 1.7 Stable yet, that's why you can't see it.

**Comment by rebornix** [comment]
We've already released 1.7, twice :(
