### ISSUE TITLE
Select partial content seems not work with `ctrl + u` and `ctrl + d`

### ISSUE THREAD

**Issue by poppinlp** [VSCodeVim/Vim#1021]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Use `shift + v` to select one line
2. Scroll up by `ctrl + u` or scroll down by `ctrl + d`

### What did you expect to happen?

Select the content between the first line in step 1(include) and the destination after scroll(include).
Just like what vim do.

### What happened instead?

Jump to destination without selecting.

### Technical details:

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.1
* OS: OS X EI Capitan

PS: Select content works well with `gg`, `shift + g` and `lineNumber + shift + g`.

**Comment by rebornix** [comment]
Thanks for reporting. It's kind of dup of #907.
