### ISSUE TITLE
va{ & va} doesn't select closing brace

### ISSUE THREAD

**Issue by jeffschwartz** [VSCodeVim/Vim#1023]
### What did you do?
In normal mode I entered `va{`. 

### What did you expect to happen?
Both opening and closing braces along with enclosed content to be selected.

### What happened instead?
The enclosed content and only the opening brace was selected. The closing brace was not selected.

### Technical details:
* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.1
* OS: Mac OS X 10.9.5

Cursor within enclosing braces and then keying `va{:`
![screen shot 2016-11-01 at 9 14 01 am](https://cloud.githubusercontent.com/assets/271288/19890874/b37776e0-a013-11e6-81d8-def351d8d1b9.png)

Result of keying `va{`. Note that only the opening brace was selected along with the enclosed content, and that the closing brace was not selected:
![screen shot 2016-11-01 at 9 14 25 am](https://cloud.githubusercontent.com/assets/271288/19890880/b997e140-a013-11e6-9b8a-c7376d5d0728.png)

**Comment by jeffschwartz** [comment]
Has someone looked into this yet? It is a trifle but very annoying bug.

**Comment by xconverge** [comment]
I was able to reproduce it, it is strange because it works in some cases

{
test
test}

works but 

{
test
test
}

does not

**Comment by xconverge** [comment]
this was caused by #1014 

also relates to #1022 

The way our visual cursor works is annoying here, should be able to find something that works for all of these cases though

**Comment by jeffschwartz** [comment]
This is still broken with v0.4.2.

**Comment by jeffschwartz** [comment]
Just to confirm, it works now yeah LOL. Thank you to all the maintainers and contributors to this project. Outstanding!!!

**Comment by xconverge** [comment]
No problem @jeffschwartz, feel free to continue to report what you find! We are looking for stability and every little bit helps!
