### ISSUE TITLE
Add ctrl-c as alternative to Esc

### ISSUE THREAD

**Issue by alnorris** [VSCodeVim/Vim#1026]
Vim allows Ctrl-c to change to Normal mode, would be great to implement this in VS Vim, especially since the new Macbook Pros won't have an Esc!

* VSCode Version: 1.6.1
* VsCodeVim Version: Latest
* OS: El Capitan

**Comment by jpoon** [comment]
You can refer to our [roadmap](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md) but we do support `ctrl+c`. You'll need to configure useCtrlKeys option (https://github.com/VSCodeVim/Vim#usectrlkeys) to true to allow overriding the default VS Code key bindings.
