### ISSUE TITLE
Unable to remap <Space>

### ISSUE THREAD

**Issue by apazzolini** [VSCodeVim/Vim#1028]
### What did you do?

I attempted the following mappings:

```
"vim.otherModesKeyBindings": [
	{
		"before": ["<backspace>"],
		"after": ["1", "0", "k"]
	},
	{
		"before": ["<space>"],
		"after": ["1", "0", "j"]
	}
]
```

### What did you expect to happen?

I expected space to be remapped to 10j and backspace to 10k

### What happened instead?

Backspace was properly mapped, but space continues to just move right one letter

### Technical details:

* VSCode Version: 1.7.0
* VsCodeVim Version: 0.4.1
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
Try `"before": [" "],`

This is a bug though. We should interpret `<space>` to be the same as `" "`.

**Comment by apazzolini** [comment]
Ah, yes I can confirm that worked. I don't know why I didn't even think to try a literal `" "`. Thanks!

**Comment by johnfn** [comment]
Probably because it's `<Space>` in Vim 😉
