### ISSUE TITLE
Ctrl-A/X targeting the wrong number in some cases

### ISSUE THREAD

**Issue by stefanoio** [VSCodeVim/Vim#1030]
### What did you do?

On `margin: 1em 2em;` in normal mode with the cursor positioned after the `1` and before the `2` press Ctrl-a or Ctrl-x.

### What did you expect to happen?

The affected number should be the `2`.

### What happened instead?

The affected number is the `1`.

### Technical details:

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.1
* OS: macOS Sierra 10.12.1

**Comment by xconverge** [comment]
Thanks for reporting this @stefanoio 

I will try to figure something out!
