### ISSUE TITLE
:normal command doesn't work

### ISSUE THREAD

**Issue by dgaleazzo** [VSCodeVim/Vim#1032]
### What did you do?

I tried to use '<,'> normal command but it doesn't work.

- record a line macro with qa
- v to other lines
- :'<,'>normal @a

### What did you expect to happen?

Apply macro into lines selected

### What happened instead?

Nothing

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: Mac OS X 10.11.6

**Comment by Chillee** [comment]
So, as this [PR](https://github.com/VSCodeVim/Vim/pull/1725) introduces support for the `:normal` command, I'm going to close this issue with the merging of that PR, despite the fact that this exact case (`:normal` with a macro) isn't solved yet.

I've opened up another issue here to track this issue in particular: https://github.com/VSCodeVim/Vim/issues/1733

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).
