### ISSUE TITLE
:e autocomplete

### ISSUE THREAD

**Issue by dgaleazzo** [VSCodeVim/Vim#1033]
### What did you do?

:e <Tab>

### What did you expect to happen?

Autocomplete FS paths.

### What happened instead?

Nothing.

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: Mac OS X 10.11.6

Hoping it is possible to implement.

**Comment by rebornix** [comment]
dup of https://github.com/VSCodeVim/Vim/issues/745
