### ISSUE TITLE
[End of line] - mouse selection skip last character

### ISSUE THREAD

**Issue by gplume** [VSCodeVim/Vim#1034]
------
Since 4.0.1 when I select a block or just a line with the mouse, last character is skipped from selection (both visually and in clipboard).
Before 4.0.0 and for me, the end of line behavior (clicking with the mouse randonly at the end of a line) would select an inexistant space character and I thought the problem was solved with the new version 4, but I've just read that only 4.0.1 solved the problem. Perhaps it was due to my settings.json options : 
```
"editor.cursorBlinking": "solid",
 "vim.useSolidBlockCursor": true
```
Thanks for great work, I'm almost using vscode 100% of time now!

**Comment by mgood** [comment]
Yeah, I think this may be a bug with PR #1006. It looks like it was intended to fix an issue with the Vim commands to move to the end of the line, but it seems to have an issue when selecting with the mouse.

I encountered this double-clicking the last word on a line to replace it. The selection omitted the last character of the word, so my replacement left that last stray character on the line.

**Comment by uglyboxer** [comment]
By any chance was there a reversion to this behavior?  I'm seeing it now with:

VSCode 1.37.1
VSCodeVim 1.10.2

**Comment by J-Fields** [comment]
@uglyboxer I'm not seeing it. Could you tell me what platform you're on and maybe show a video of the bug you're seeing?

**Comment by uglyboxer** [comment]
@J-Fields  I'm on MacOSX 10.14.6 (Mojave)

![copypaste](https://user-images.githubusercontent.com/12128540/64211805-34396300-ce5c-11e9-8c9e-3fe1017c5237.gif)

**Comment by J-Fields** [comment]
@uglyboxer Thanks, I'm able to repro. Rather than re-opening this (as it'll probably get buried) could you open a new issue and link to this one?

**Comment by uglyboxer** [comment]
Will do!
