### ISSUE TITLE
Vertical split should open current document in new panel by default

### ISSUE THREAD

**Issue by chrahunt** [VSCodeVim/Vim#1035]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Entered `:vsp` when viewing a file.

### What did you expect to happen?

Another editor panel to open vertically to the right of the current editor panel with a view of the same document I had focused when executing `:vsp`.

### What happened instead?

A blank editor panel appeared to the right of the current document.

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: Windows 10

**Comment by rebornix** [comment]
oh really? So basically you want to `vsp` behaves the same way as Code instead of Vim.

cc @johnfn @xconverge

**Comment by FSMaxB** [comment]
@rebornix: Vim opens a new view of the same buffer if you do a vertical split. It behaves exactly like VSCode does in this case. (at least in my case with vim8 and no vimrc).

**Comment by chrahunt** [comment]
It is also the case in Vim 7, maybe earlier but it's what I have on hand:

![gif proof](https://cloud.githubusercontent.com/assets/2312275/20163113/f95dfd0e-a6c7-11e6-8565-d0e7f095d349.gif)

**Comment by rebornix** [comment]
@FSMaxB @chrahunt thanks for your detailed input and help! I didn't take this into consideration. If there is no file name for `vsp`, the behavior is like invoking Code's splitting window and it may be easy to fix.
