### ISSUE TITLE
A<BS> moves cursor immediately to 0th column

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1039]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Type `A<BS>` on a line with text in it. The cursor ends up at the beginning of the line.

**Comment by xconverge** [comment]
Also can't repro this...

**Comment by johnfn** [comment]
@xconverge are you on 0.4.1?

**Comment by octref** [comment]
Just saying this is a bit showstopper and made me to disabled Vim globally today.

I feel this kind of non-major bug would reduce the credibility of this extension. It shouldn't creep into releases. Hope you guys can setup a smoke test similar to VSCode (https://github.com/Microsoft/vscode/wiki/Smoke-Test).

**Comment by johnfn** [comment]
@octref we're just unpaid volunteers, working on the extension when we have time! We try to do the best we can. (well, except for @rebornix I guess :P)

**Comment by xconverge** [comment]
@johnfn yes and code 1.7.1

**Comment by xconverge** [comment]
@johnfn @octref This does not happen on 1.7.1 but does happen on insiders

**Comment by octref** [comment]
Well maybe @rebornix could set it up. It's just a short manual test that takes a few minutes, and would catch this kind of bug before releasing it to all VSCodeVim users. Personally I wish 0.4 is still on my machine. (OTOH hope VSCode could introduce an easier way to download old version of extensions).

**Comment by xconverge** [comment]
All VSCodeVim users who are using the stable release SW are fine.

**Comment by octref** [comment]
@xconverge Thanks a lot. I thought this is also on Stable...That would be really bad. Glad to know it's only on Insider. I just grabbed myself 0.4 and is using it.

**Comment by johnfn** [comment]
@octref We do have a rather large suite of tests. Unfortunately, enumerating regressions of all sorts (which is the only conceivable way to catch bugs such as this one) is a rather extensive process that only grows as we add more features. 

But we always welcome new PRs :)

Ah, good catch @xconverge.

**Comment by rebornix** [comment]
IMHO it's a regression in Code Insiders https://github.com/Microsoft/vscode/issues/15139

**Comment by rebornix** [comment]
It's already fixed. Sorry for the regression in our side.
