### ISSUE TITLE
Can't backspace twice at end of line

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1040]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

`iblah<BS><BS>` doesn't work. I expected `bl`.

**Comment by xconverge** [comment]
in insert mode?

I can't repro this...

**Comment by xconverge** [comment]
@rebornix is this fixed too?

**Comment by rebornix** [comment]
I don't see this in insider and stable right now.
