### ISSUE TITLE
Allow esc/ctrl-c to exit IntelliSense in snippet filling

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#1041]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

Currently while you are filling a snippet, `<ESC>` or `<C-c>` would quit insert mode instead of exiting IntelliSense (not selecting any suggestion and hide the panel).

If I have more places to fill in the snippet, and IntelliSense doesn't provide anything I want, I have to exit filling the snippet and manually jump to the next place.

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: OS X 10.11.6

**Comment by rebornix** [comment]
I was expecting ppl to report this kind of feedback. It was our initial design to do so but later on a bunch of users came and said hey can we just escape the insert mode anytime I press `Esc` instead of having to press `Esc` twice when the intellisense popup is there. Then we did that but unluckily we annoyed another group of users.

@johnfn @xconverge need your $0.04

**Comment by xconverge** [comment]
a config option

**Comment by johnfn** [comment]
I found the double esc to exit out of the autocomplete and then insert mode to be astonishingly annoying. This is mostly because if you pay attention, the autocomplete window is almost always open when you're typing. 

We could make it a config option, I guess.

**Comment by octref** [comment]
I wouldn't want ESC to quit intelliSense for all scenarios either. I just want to remain in snippet-filling mode. If ESC quits snippet and I cannot go to the next place for edit, snippet becomes much harder to use.

**Comment by johnfn** [comment]
Ah yeah, ESC should absolutely not exit editing the snippet.

**Comment by leecz** [comment]
same problem, and when i press <esc> twice, the curson move to forward character. i use React Standard Style code snippets test , rcc snippet.

**Comment by elkdanger** [comment]
I have a similar issue with intellisense (but not in a snippets scenario, so I'm not sure if another discussion needs to be opened or not - you decide), but when I'm in insert mode and an intellisense window pops up as I'm typing, my natural reaction is to close the popup using the escape key, which I would expect (rightly or wrongly) for the popup to be closed (if one is open) and a further press would then drop me out of insert mode.

Like I said, not quite the same issue, but it _feels_ like we're talking about the same thing. Please correct me if I'm wrong.

**Comment by gri6507** [comment]
Like the last response, I am not 100% sure, but I believe I am experiencing the same issue. While I am in INSERT mode, and I start typing, IntelliSense pops up. If I don't care to use any ItelliSense suggestion, I naturally hit ESC, which closes the IntelliSense window, but also exits the INSERT mode. I would rather remain in INSERT mode. Can this be a configuration option in the extension? Alternatively, is there another keyboard shortcut for closing the IntelliSense window?

**Comment by johnfn** [comment]
We can add this in as a setting, but I predict with 95% confidence that this will drive you guys just as insane as it drove me. 😉

**Comment by johnfn** [comment]
@rebornix actually I think this may not be possible because I need to use parenthesis in `when` clauses in the package.json file and that doesn't seem possible:

e.g.

`        "when": "editorTextFocus && !inDebugRepl && (vim.escClosesSuggestPanel && suggestWidgetVisible || !vim.escClosesSuggestPanel)"`

Alternatively, is there a way to retrieve the value of `suggestWidgetVisible` in TypeScript?

**Comment by rebornix** [comment]
`when` clause and context are just setting things right now, I'll see if it makes sense to expose them through extension host.

**Comment by johnfn** [comment]
@rebornix yeah they either need to be exposed or we need at least parenthesis in the clause for this one to be fixed.

**Comment by lucastheisen** [comment]
Is there a way to close the intellisense popup right now?  I am sure I can be trained to use it if I know what it is...  Right now, I have to reach over to the mouse to click somewhere and then get back to what I was doing when a popup blocks what I need to see.  Its _REALLY_ frustrating, and not very vim like to have to reach for the mouse...

**Comment by muhajirframe** [comment]
Facing the problem, any fix?

**Comment by Chillee** [comment]
@lucastheisen @muhajirframe Use `<shift+esc>`

**Comment by Chillee** [comment]
I'm going to close this issue after adding it to the README:
https://github.com/VSCodeVim/Vim#there-are-annoying-intellisensenotificationspopups-that-i-cant-close-with-esc-or-im-in-a-snippet-and-i-want-to-close-intellisense

**Comment by mcshaman** [comment]
Is there a way to map this to a different key command? I avoid using ESC for Vim.
