### ISSUE TITLE
Delete to a mark is broken

### ISSUE THREAD

**Issue by arlencox** [VSCodeVim/Vim#1042]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

```
this is a
multiline
test
of a simple
text file
```

Test 1:
Cursor at `l` in `multiline`.  Command: `mm`
Cursor at `s` in `simple`.  Command: `d'm`

Test 2:
Cursor at `s` in `simple`.  Command: `mm`
Cursor at `l` in `multiline`.  Command: `d'm`

### What did you expect to happen?

Test 1:
I expected lines 2, 3, and 4 to be deleted.

Test 2:
I expected lines 2, 3, and 4 to be deleted.

```
this is a
text file
```
### What happened instead?

Test 1:
```
this is a
simple
text file
```

Test 2:
```
this is a
multif a simple
text file
```

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: Mac OS X 10.11.6

**Comment by johnfn** [comment]
Thanks for the bug report, @arlencox! It should be fixed on master now, and will be released in 0.4.7.
