### ISSUE TITLE
cursor position at wrong place

### ISSUE THREAD

**Issue by hpsoar** [VSCodeVim/Vim#1043]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

After Ctrl+V, I move the cursor and did some selection, see the picture below.

<img width="238" alt="screen shot 2016-11-07 at 5 40 05 pm" src="https://cloud.githubusercontent.com/assets/1549522/20053130/1e83d32c-a512-11e6-8f15-0d0516334ba5.png">

then, I press `s` to do substitution. 
In this case, the cursor should be placed at the beginning of line 3, while the fact is as the picture below.

<img width="267" alt="screen shot 2016-11-07 at 5 40 16 pm" src="https://cloud.githubusercontent.com/assets/1549522/20053096/f30ea046-a511-11e6-9f03-885186f4ef53.png">

* VSCode Version:
* VsCodeVim Version: v0.4.1
* OS: Mac
 10.11.6 (15G31)

**Comment by hpsoar** [comment]
After that, if I input some text, the text is inserted at the right place.
The only problem is that the cursor is not placed at the right position.

**Comment by xconverge** [comment]
This is true for A and I as well, should be able to take a look. did @rebornix ask you to assign him? Otherwise I could look at it

**Comment by hpsoar** [comment]
@rebornix did not ask me to assign him. I don't know who assigned it.

**Comment by hpsoar** [comment]
modeHandler, vimState.currentMode === VisualBlockInsertMode, thus execute the following code
Line 1400: selections = [ new vscode.Selection(stop, stop) ];

don't know how to fix this, should just change `stop` to `start` or a new Mode is needed?

**Comment by rebornix** [comment]
@xconverge I assign it to myself. It's GitHub's bug :)  But I did that for testing, so @xconverge go ahead

**Comment by xconverge** [comment]
ah ok yea I saw "@rebornix rebornix was assigned by hpsoar 13 hours ago"

I am almost done fixing this
