### ISSUE TITLE
Prepublish build fails

### ISSUE THREAD

**Issue by boweiliu** [VSCodeVim/Vim#1045]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Pulled Vim/master, loaded it up in VScode, hit "debug -> Launch extension".

### What did you expect to happen?
It launches extension.

### What happened instead?
Build fails with error:

### Technical details:
```> vim@0.4.1 vscode:prepublish $HOME/code/Vim
> node ./node_modules/vscode/bin/compile -p ./
src/configuration/configuration.ts(118,63): error TS2339: Property 'update' does not exist on type 'WorkspaceConfiguration'.
```

* VSCode Version: Version 1.8.0-insider (1.8.0-insider) a3e85d60a32f91efccfe6161c3a4673ad909496e
* VsCodeVim Version: master, hash `ec44882de8abb84d8982f8c1f1b9c9b695d855c5`
* OS: OSX 10.10.5

**Comment by jpoon** [comment]
@boweiliu does this compile against non-insider?

**Comment by rebornix** [comment]
@boweiliu have you run `npm install` to fetch the latest vscode modules we are using?

**Comment by jpoon** [comment]
@boweiliu Please re-open if you think this is still broken, but the suspicion is that you are missing the dependencies. You can try either `npm install` or `grunt init`
