### ISSUE TITLE
gv should re-select last visual selection

### ISSUE THREAD

**Issue by tyrellj** [VSCodeVim/Vim#1046]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

gv should re-select last visual selection.

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: Windows 10

**Comment by rebornix** [comment]
Thanks @tyrellj it's a dup of #986.
