### ISSUE TITLE
Ability to clear search

### ISSUE THREAD

**Issue by OliverJAsh** [VSCodeVim/Vim#1053]
I have an active search which I would like to clear using a keyboard shortcut, ideally escape. Is this possible? In Vim:

```
nnoremap <silent> <esc><esc> :noh<cr>
```

**Comment by FSMaxB** [comment]
First there has to be `noh` before anything can be mapped to it. #1047 

And in Vim `nohl` doesn't clear the search btw. it only disables the highlighting. If you press `n` after `:nohl`, the next search result get's displayed and all the highlights are back again.

**Comment by OliverJAsh** [comment]
Thanks for the fast response (and the great extension).

That makes sense. I guess I was asking for the ability to clear highlighting, not the search.

**Comment by FSMaxB** [comment]
@OliverJAsh I'm not a developer of this extension.

**Comment by chrahunt** [comment]
This looks like a duplicate of #1047?

**Comment by xconverge** [comment]
@johnfn @rebornix this looks like it can be closed

**Comment by Awpteamoose** [comment]
:noh has been implemented, but I'm still not sure if it's possible to bind ex commands to hotkeys.

**Comment by johnfn** [comment]
Remapping is being tracked here: #1166
