### ISSUE TITLE
How to close vim mode ?

### ISSUE THREAD

**Issue by leecz** [VSCodeVim/Vim#1055]
i want to enable or disable vim mode easily.

**Comment by johnfn** [comment]
This can be done from within VSCode. Just go to the extensions menu and click "Disable".

**Comment by FSMaxB** [comment]
Although that requires a restart of VSCode.

**Comment by johnfn** [comment]
Take that up with the VSCode team 😉

**Comment by leecz** [comment]
谢谢你们！
thanks! 
这个插件非常棒，它让我从 vim 转到 VScode了！
this extension is so nice！I started to use VScode now.

**Comment by artusvranken** [comment]
Any chance thi will get supported? I'm looking for a quick shortcut to enable/disable the extension. Manually opening the extension page and toggling the state makes for an impacting context switch while working.

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim#vimdisableextension

**Comment by artusvranken** [comment]
Ok, thank you.

So for people that don't know how to do this: You can [open the Command Palette by pressing F1](https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf). A text field will open where you can enter commands. Enter `toggleVim` to disable/enable Vim mode.

**Comment by jpoon** [comment]
You can bind that command to whatever key you'd like:

```
{
  "command": "toggleVim",
  "key": "ctrl+k ctrl+v"
}
```

**Comment by lqueryvg** [comment]
@jpoon  thanks, that's helpful.
But the big problem with that (and this is on any application and any platform...) is choosing a key mapping to use. It's too easy to choose a mapping which conflicts with something else, either in the application or the platform itself (layer vim on top of that and..., oh...).
I couldn't see an easy way to list all in-use key mappings in VS code.
Now that would be useful feature.

**Comment by federicopessina** [comment]
In VSCode you can just go to where NORMAL, INSERT, VISUAL mode is displayed, at the bottom of VSCode window, and left-click on it. It will display -- VIM:DISABLED --
