### ISSUE TITLE
Deleting a line randomly jumps the cursor

### ISSUE THREAD

**Issue by changm** [VSCodeVim/Vim#1057]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1) Go to a line
2) Push dd to delete a line
3) Push j to go down one line

### What did you expect to happen?

After pushing j, the cursor should go down one line from the current location.

### What happened instead?

My cursor jumped down 60 lines instead.

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: OS X 10.12 Sierra

**Comment by johnfn** [comment]
I definitely can't reproduce this. I need more info!

**Comment by changm** [comment]
It takes a while. It seems to happen intermittently. e.g. If I restart VS Code, it'll work as expected for like 30 minutes. Then once the bug happens, it always happens.

**Comment by johnfn** [comment]
hmm... that's tough to reproduce.

**Comment by changm** [comment]
Is there a debug build or any logging I could try to help you? I know, intermittent bugs are hard :(.

**Comment by rebornix** [comment]
@changm did you ever have a chance to put the cursor to 60 previously before you run `dd`? For example, using F12 or search to navigate the code and then type `dd` somewhere, and then when you type `j`, our internal cursor position cache is somehow not updated.

**Comment by changm** [comment]
@rebornix Yup! That did it! Thanks

Better STR:
1) Push cmd-F to search for something that exists.
2) Push enter to search for something
3) push esc to get out of the search menu
4) push dd to delete a line
5) push j, skip lots of lines.

**Comment by rebornix** [comment]
@changm sorry to bother you again. I played with latest version 0.4.2 but could not reproduce this issue. Do you mind giving the latest bits a try or provide a single file with minimal content that can help reproduce?

**Comment by changm** [comment]
@rebornix Thanks for the fix! 0.4.2 seems to have fixed the issue for me. Thanks for working on this!

**Comment by changm** [comment]
This is happening again. I'm not quite sure what the STR are again, but it's jumping again. I tried the STR from a couple of comments ago, but that doesn't seem to reliably reproduce it. This also seems to happen across instances whereas before it wouldn't. As in, If i close VS Code then reload it, the problem still appears.

**Comment by johnfn** [comment]
Yikes, that sounds really bad. @rebornix , could this have anything to do with settings?? @changm could you tell us the contents of your user settings json file when you're running into this bug?

**Comment by rebornix** [comment]
@johnfn I don't see anything that might be related to settings. But I'm changing a little bit of the setting stuff and hope that mitigate potential issues.

**Comment by kascote** [comment]
I have the same problem.

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.2
* OS: Linux Ubuntu 16.04

**Comment by kascote** [comment]
I can't yet found a way to reproduce the problem in a clean way. I recorded a little video to show the problem if that help to figure the issue.

http://netflux.com.ar/vsvim_bug.mp4

after copy a block, use **dd** to remove a line, then press **j** and the cursor jump to the line where the block was copied.

**Comment by xconverge** [comment]
@kascote just to check and get some more info, do you use j/k or the arrow keys at all times, I assume j/k at all times in the video based on what you wrote?

**Comment by kascote** [comment]
@xconverge  yes, always use j/k

**Comment by splinefish** [comment]
One way to reproduce this is by splitting the editor and open the same file in both panes.
1. Add 10 rows of text
2. Place the cursor on pane2 to line 9
3. Switch to pane1, go to line 4 and hit dd to delete it.
   The line will get correctly deleted but moving the cursor/hitting escape or entering another
   command such as another dd will have the cursor jump to the same cursor position as pane2.

**Comment by johnfn** [comment]
I finally managed to repro this! Open up the same file in both panes of a split pane editing session, then dd somewhere. Boom, messed up cursor!

**Comment by yihongang** [comment]
Yeap ran into this which lead to searching for an issue which lead me here. Same file split pane + dd + j and I'm lost.

**Comment by johnfn** [comment]
(My bad, @splinefish. Completely missed you said the exact same thing. I'm just oblivious.)

**Comment by changm** [comment]
@johnfn Since you were able to reproduce this, any chance this will get fixed soon? Thanks!

**Comment by johnfn** [comment]
I will get to it the next day I have free time I work on the app. In the mean time, you are certainly welcome to do it :wink: :wink:

**Comment by johnfn** [comment]
Hey, I found some time! Fixed this issue in v0.6.0. :)

**Comment by astrocox** [comment]
I'm seeing what seems like this exact error in v1.0.8 (MacOS 10.13.6, VSCode 1.31.0). The cursor jumps to the other editor's last cursor location after deleting a line with `dd` when the same file is open in two editor splits. Any chance it's resurfaced?

**Comment by cpick** [comment]
@astrocox I'm also seeing this behavior; it looks like it's been re-reported in #3455.

**Comment by abratio** [comment]
One way to reproduce this is by splitting the editor and open the same file in both panes.

+1

I'm seeing this, for the latest vscode 1.32.1 and vim 1.1.0. Is that a hard problem to fix it?

**Comment by maxgitt** [comment]
I was about to file a bug report for the same issue. Suppose you have the same file open in two panes, and that pane 1 has a cursor on line 20 and pane 2 has a cursor on line 50. 

If you are editting in pane 1 and call `dd` and then any of `hjkl`, the cursor in pane 1 will jump to line 50 to match that of pane 2. This has caused me to delete a number of unintended lines because the cursor continues to jump around in pane 1 without me realizing the issue.

**Comment by pdworzynski** [comment]
I have this exact issue in v1.4.0 (MacOS 10.14.4, VSCode 1.33.0).

**Comment by jakeypoo** [comment]
Seeing this issue -- split editor, pane 2 is jumping randomly to the file position in pane 1.
VS Code Version: 1.33.1
Win 10 
VScodevim Version: 1.4.0

**Comment by MacMaru** [comment]
Idem, have been `bugged` by it for a while, then came across this thread. No split editor needed, cursor jumps to end of file after dd, pretty disruptive. Cannot remember seeing that in another project. Current project vue+prettier+eslint, previous project where it didn't happen was angular+typescript.

VS Code v 1.33.1 MacOS v10.13.6

**Comment by shahryart** [comment]
Also seeing this issue.
VS Code v 1.32.3
Mac OS v10.14.3
VSCodeVim : v1.4.0

**Comment by mojason-81** [comment]
Having this issue as well.  Just noticed it today.  Seems related to having the same file open in split pane perhaps.
VS Code v1.33.1
Win 10
VSCodeVim v1.4.0

**Comment by hliu4atomos** [comment]
Closed the split pane and the issue immediately stopped.
----
confirmed...

**Comment by hoolihans** [comment]
The bug also happens when you hit 'v', 'd' and any key, or 'v', 'x' and any key, or 'J' and any key. I found a workaround. When you delete a line, you can cancel the jumping effect by hitting 'ctrl-]'. A box appear with 'no definition found' and you can move as normal. The thing is, you have to hit 'ctrl-]' each time you delete a line or you join.
Extension (VsCodeVim) version: 1.7.0
VSCode version: 1.33.1
OS: macOS 10.14.4

**Comment by cvakiitho** [comment]
Ugh, can confirm this is repro, can we have a reopen? This is extreeeemly annoying. 
@johnfn any chance you are still around to save our souls? :)

**Comment by AlanRice93** [comment]
Ran into this issue today (seemingly out of nowhere). @cvakiitho add those settings to my `settings.json` did the trick

**Comment by AlanRice93** [comment]
That fix I mentioned previously seemed to make the problem harder to reproduce but it eventually came back. I seem to have finally fixed it by removing my `~/.cache/VsCodeVim` file. Guessing it was in a nasty state?

**Comment by cvakiitho** [comment]
Imo it can still happen with the fix, when you dd <wait> d, but it is significantly less annoying :)

**Comment by Howell5** [comment]
same issue happed when the same file is open in two editor splits
vscode 1.36.1 
vim 1.8.12
macOs 10.14.5 (18F132)
