### ISSUE TITLE
>#k and <#k ignore the current line when in the left-most column.

### ISSUE THREAD

**Issue by Sean1708** [VSCodeVim/Vim#1058]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Start with a file containing the following lines:

```
line 1
line 2
line 3
line 4
```

and the cursor on the `l` of `line 3`.

Press `>2k`.

### What did you expect to happen?

The first three lines to be indented such that the file now looks like:

```
    line 1
    line 2
    line 3
line 4
```

### What happened instead?

Only the first two lines were indented, so file looked like:

```
    line 1
    line 2
line 3
line 4
```

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: Ubuntu 16.04.1 LTS

**Comment by johnfn** [comment]
Fixed and will be out in 0.4.7. Nice catch @Sean1708!
