### ISSUE TITLE
<Ctrl-W> <Arrow-Key> doesn't work

### ISSUE THREAD

**Issue by wizeman** [VSCodeVim/Vim#1060]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`<Ctrl-W> <Right-Arrow>`

### What did you expect to happen?

Switch to the right window pane, just like `<Ctrl-W> <L>`

### What happened instead?

Nothing.

### Technical details:

`<Ctrl-W> <L>` works fine, but I use the arrow keys instead.
This works for me in vim but it's not working with this extension.

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.2
* OS: Linux

**Comment by soyuka** [comment]
I did this, works well:

```
    {"key": "ctrl+h", "command": "workbench.action.focusPreviousGroup", "when": "editorTextFocus"},
    {"key": "ctrl+l", "command": "workbench.action.focusNextGroup", "when": "editorTextFocus"}
```

**Comment by brentluna** [comment]
@rebornix Is there anyway to map <ctrl-w> h/j/k/l to navigate panes? Also, would love to find a way to have h/j/k/l to navigate the sidebar project tree. Thanks

**Comment by jpoon** [comment]
> Also, would love to find a way to have h/j/k/l to navigate the sidebar project tree. 
https://github.com/VSCodeVim/Vim/issues/754

**Comment by brentluna** [comment]
@jpoon I actually just updated VS code after posting this and saw that they enabled explorer key mappings. It doesn't have anything to do with the plugin, but this is how I just got the funcitonality I was looking for. 
`{
    "key": "j",
    "command": "list.focusDown",
    "when": "filesExplorerFocus"
},
{
    "key": "k",
    "command": "list.focusUp",
    "when": "filesExplorerFocus"
},
{
    "key": "l",
    "command": "list.expand",
    "when": "filesExplorerFocus"
},
{
    "key": "h",
    "command": "list.collapse",
    "when": "filesExplorerFocus"
},
{
    "key": "enter",
    "command": "list.select",
    "when": "filesExplorerFocus"
}
`
