### ISSUE TITLE
Selecting a text and <Ctrl-C> doesn't copy it to clipboard

### ISSUE THREAD

**Issue by joa-quim** [VSCodeVim/Vim#1061]
As the subject says. Right-clicking on the highlighted text and selecting "Copy", that is using the hard way, does work.

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.2
* OS:  Win 10

**Comment by jpoon** [comment]
Have you tried https://github.com/VSCodeVim/Vim#usesystemclipboard?

**Comment by joa-quim** [comment]
No. But this used to work till I updated to 0.4.2, which break it.
And for example, Ctrl-F for searching doesn't either (and it used to work)

**Comment by johnfn** [comment]
Is it possible you just turned on useCtrlKeys?

**Comment by joa-quim** [comment]
Not impossible ofc, but not voluntarily since I have no idea on how to do it. BTW, my limitation surely, I find the instructions on the Git page rather incomprehensible.
Further checking show me that now all Ctrl-XXX are grayed it out when seen from the "File, Edit, View" menus.

**Comment by joa-quim** [comment]
Ok, I can see that in "Default Settings" ```"vim.useCtrlKeys": true``` but wasn't me who set it (I can't even find how to change that)

**Comment by johnfn** [comment]
@rebornix is it possible we override useCtrlKeys somehow via #913?

> Further checking show me that now all Ctrl-XXX are grayed it out when seen from the "File, Edit, View" menus.

Er... There's no possible way we did that. :P

**Comment by rebornix** [comment]
@johnfn I think that may be because that initialization of each options trigger setters which finally write to the file. Terrible mistake, I'll look into it.

**Comment by Deracination** [comment]
vim.useCtrlKeys is set to true in Default Settings, so getting Ctrl-C/Ctrl-V copy/paste working again requires editing settings.json and adding "vim.useCtrlKeys" : false

This new default appeared with update to 0.4.2

**Comment by ImaginaryDevelopment** [comment]
yeah this was working just fine until an update. then I had to find my way here to figure out what was going on and where to change it.

**Comment by xconverge** [comment]
Then you should not have thumbsdowned the answer... I assume @Deracination was right? That should be a thumbsup and a sadface, not a thumbsdown :)

**Comment by asolopovas** [comment]
Same here.
I have this in my config but it still lock my ctrl+c and ctrl v
    "vim.useCtrlKeys": false,

**Comment by ImaginaryDevelopment** [comment]
where does it say thumbs up means it is right? yes it is right, thumbsdown because they changed the default. Also the only two faces say laugh or confused, not sad.

**Comment by xconverge** [comment]
Thumbs up/down is actually +1 and -1, in this repository, we typically use it for prioritizing issues, getting feedback, "voting", etc. Not a big deal, I want your issue fixed as well. I just wanted to let you know that the github reactions are confusing and have no rules, but that is typically how the thumbs up and thumbs down are used. The thumbs down to me says that you disagree with the comment. Anyways, sorry for the extra noise on this issue.

**Comment by xconverge** [comment]
@rebornix this should be fixed now that the settings are back to normal

**Comment by rebornix** [comment]
@xconverge thanks for verification.

**Comment by mattklein999** [comment]
14 days later, just updated to 0.4.9 and the default is back to "vim.useCtrlKeys": true.
