### ISSUE TITLE
[enhancement] Go to last edit location

### ISSUE THREAD

**Issue by soyuka** [VSCodeVim/Vim#1063]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
`g;`
### What did you expect to happen?
`go to last edit location`
### What happened instead?
nothing
### Technical details:

* VSCode Version: 1.8.0-insider
* VsCodeVim Version: 0.42
* OS: debian/osx

**Comment by johnfn** [comment]
Thanks for the feature request, @soyuka!

**Comment by soyuka** [comment]
I love you, just typed this as a "reflex" and it worked \o/. Didn't saw that it was fixed. Many thanks!

**Comment by bschlenk** [comment]
Is there any way to map '' (double apostrophe) to this? I'm used to using this command in vim to jump back and forth between the current and previous locations.

**Comment by jpoon** [comment]
This should work:

```
"vim.otherModesKeyBindingsNonRecursive": [
   {
       "before": ['"'],
       "after": ['g', 'i']
   }
]
```

We've gotten a lot of questions about rebinding, if this helps you, please help improve our documentation.
