### ISSUE TITLE
Please support CTRL-O {command}

### ISSUE THREAD

**Issue by ghuiii** [VSCodeVim/Vim#1065]
### What did you do?
![image](https://cloud.githubusercontent.com/assets/5203798/20452674/8a838342-ae4a-11e6-83af-ecd1581b36fe.png)
I enabled `useCtrlKeys` ,Because I want to to use the `Ctrl-O` (escapes user to do one normal-mode command, and then return to the insert mode.)

### What did you expect to happen?
Execute {command} and return to Insert mode
### What happened instead?
Just like pressed the `Enter` Key instead of what I expected.

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.2
* OS: 10.12.1 (16B2555)

**Comment by xconverge** [comment]
whoa I had no idea this existed! Thanks for reporting it!

**Comment by ghuiii** [comment]
great!!!
Thanks @johnfn

**Comment by johnfn** [comment]
All credit belongs to @xconverge 😉

**Comment by ghuiii** [comment]
When will release a new version to the market? So I can update it
