### ISSUE TITLE
Incremental search has broken.

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1072]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

I'm not quite sure how, when or why, but searching with `/asdf` is no longer highlighting the first match before I press enter.

**Comment by mahmoudhossam** [comment]
Setting `vim.hlsearch` to `true` doesn't help either.

**Comment by xconverge** [comment]
Setting vim.hlsearch to true DOES work for me...

Make sure you set your user settings and the workspace settings then restart vscode...

**Comment by johnfn** [comment]
hlsearch works fine for me as well, but does not enable incsearch.

**Comment by xconverge** [comment]
incsearch works correctly for me on windows 10, vim 0.4.3 vscode 1.7.1

**Comment by johnfn** [comment]
Fixed.
