### ISSUE TITLE
<g> <Arrow-Up/Down> doesn't work

### ISSUE THREAD

**Issue by wizeman** [VSCodeVim/Vim#1073]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I pressed `<g> <Arrow-Down>` while the cursor was at the beginning of an extremely long line of code, i.e., a line that has word-wrapped and therefore spans multiple lines in the code editor, even though it's still kept as a single line in the original file.

### What did you expect to happen?

I expected to happen the same as if I had pressed `<g> <j>`, i.e., I expected the cursor to go to the next "visual" line, but stay in the same actual line of code.

### What happened instead?

Nothing.

### Technical details:

This is similar to issue #1060.

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.2
* OS: Linux

**Comment by xconverge** [comment]
thanks, this will be super easy
