### ISSUE TITLE
Switch mode turns off word wrap.

### ISSUE THREAD

**Issue by icewind** [VSCodeVim/Vim#1075]
Steps to reproduce
* Open md document with a long strings
* Enable Word Wrap (⌥ + Z)
* Switch mode from normal to insert or vice versa.

VScode: 1.7.1
VSCodeVim: 0.4.3
OS: MacOS 10.11.3

**Comment by xconverge** [comment]
I can enable word wrap, then press i and esc multiple times, and disable word wrap correctly.

Can you provide a gif or something showing what is happening? Thanks!

**Comment by icewind** [comment]
Today I got update for vscodevim. Now it is working fine. Thanks for your work!
