### ISSUE TITLE
cursor stuck by typing `ctrl+w ctrl+w`

### ISSUE THREAD

**Issue by wangsongiam** [VSCodeVim/Vim#1079]
### What did you do?

typed `ctrl+w ctrl+w` for several times, then start editing

### What did you expect to happen?

switch editorGroup and back to where I left in the last editorGroup I used, then free to move my cursor by `hjkl` 

### What happened instead?

if I tried couple times for switching, the cursor would be stuck and return no action from`hjkl`, or it would go back to another place that is not where I left.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: *[please ensure you are on the latest]* 0.4.3
* OS: 10.11.6

**Comment by xconverge** [comment]
@rebornix It looks like #753 still exists as well, this might be related?

**Comment by wangsongiam** [comment]
@xconverge yes, that should be the same issue

**Comment by xconverge** [comment]
If you toggle developer tools, when this happens, there are rangeerrors when calling readLineAt, I think that it has to do with #753 and not the actual implementation of ctrl+w ctrl+w, I believe this would occur with using only ctrl+w l and ctrl+w h as well

**Comment by wangsongiam** [comment]
alright, I tried this solution with buildin command in vscode,  it worked smoothly so far.
{ "key": "ctrl+w h",        "command": "workbench.action.focusPreviousGroup" },
{ "key": "ctrl+w l",           "command": "workbench.action.focusNextGroup" },

**Comment by xconverge** [comment]
Ok, I will try to see if we can get to the root cause so that you don't have to use a workaround in the future!
