### ISSUE TITLE
character position does not always persist on commands "j","k"

### ISSUE THREAD

**Issue by corymickelson** [VSCodeVim/Vim#108]
When applying motions commands in normal mode, such as to the end of a line: "$", beginning of a word: "w", or to the first character of a line "0" followed by the up or down commands "j", "k", the character position is off be the change from the previous command ("$", "0", "^", "w", "b", etc).

let's use these two lines below for clarification, and success criteria: 

Alpha one test
Bravo two

If I am on "A" and I apply command "e", that will take me to the "a" character at the end of the word "Alpha", now if apply command "j" to move down a line I should land on the "o" character on "Bravo" but instead I land back on the "B" character in "Bravo". 

If the line I am moving to has a populated character at that position, such as the previous example moving from "a" in "Alpha" down to "o" in "Bravo" I should land on the character directly below me.

If lets say I am on the last "t" in "test" I should, if I apply command "j" ,  be moved to the last character in the line below me "o", since the line below does not contain any character directly below the  "t" in "test"
```
Alpha one test
    |        |
    |       /
    |     /
Bravo two
```
I hope that makes since, if not let me know and I will try to further clarify

**Comment by corymickelson** [comment]
So, at first glance it appears that the prevColumn is not always being set when executing commands that move the cursor multiple positions. I will start on this, if anyone here believes I am going about this wrong please let me know how you believe it should be solved. Thanks

**Comment by corymickelson** [comment]
Created pull request to fix this and add "e", "0" to move to beginning of line, and fix "^" to move to first character of current line

**Comment by jpoon** [comment]
@corymickelson Thanks! Awesome work!
