### ISSUE TITLE
It seems UseCtrlKeys doesn't work in lastest version 0.4.3

### ISSUE THREAD

**Issue by sharkrice** [VSCodeVim/Vim#1080]
### What did you do?
UseCtrlKeys set true
Press Ctrl+c to copy something or Ctrl + f to find something.

### What did you expect to happen?

copy something or start find something

### What happened instead?

active normal mode or scroll page forward

### Technical details:

* VSCode Version:1.7.2
* VsCodeVim Version: 0.4.3
* OS: win10

**Comment by johnfn** [comment]
useCtrlKeys means use the vim ctrl keys. So this is expected behavior.
