### ISSUE TITLE
Bracket pairs don't get deleted when you delete the first bracket

### ISSUE THREAD

**Issue by Probotect0r** [VSCodeVim/Vim#1084]
### What did you do?
https://gyazo.com/f6e305ea0d7afce408329e6ebf72402d
This happens for character pairs like [], {}, '', etc.

### What did you expect to happen?
Both characters in the pair to deleted.

### What happened instead?
Only one character was deleted.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.3
* OS: Windows

**Comment by xconverge** [comment]
https://github.com/Microsoft/vscode/issues/17490

**Comment by johnfn** [comment]
Dang @xconverge you are going ham on vscode issues

**Comment by xconverge** [comment]
@johnfn this can be closed due to #1267
