### ISSUE TITLE
Starting mouse selection at the end of the line unselects the last character

### ISSUE THREAD

**Issue by iivvoo** [VSCodeVim/Vim#1087]
### What did you do?

Click mouse at end (past last character) and drag left/top to make a multi-line selection

### What did you expect to happen?

The entire line up to the end to be selected

### What happened instead?

The last character gets unselected

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.3
* OS: Ubuntu 16.04.1 64bit

**Comment by xconverge** [comment]
Thanks for reporting this, I think it is still an issue on master

**Comment by johnfn** [comment]
RIP @xconverge

**Comment by xconverge** [comment]
I am still thinking of how it can be done! If we knew we were still holding the mouse button down it would be easy!

**Comment by johnfn** [comment]
@xconverge I'm just messing with you. The "end of line character" bug will truly never die. 😉
