### ISSUE TITLE
setting to open files in Insert mode by default

### ISSUE THREAD

**Issue by atiqorin** [VSCodeVim/Vim#1088]
Not always I need VSCode to open in normal mode. If I need to edit a .config file for example I don't want to go into insert mode by pressing 'i' then edit the file. For me when I will be developing only then I would use normal mode.

**Comment by cesaraaron** [comment]
I was about to open an issue like this :thumbsup:

**Comment by zjengjie** [comment]
I need this too or how can I bind mouse click to 'i'?
I found that most time open file with vscode I was holding mouse or I need a mouse click to the file(if use command line I prefer use origin vim), and I have to press a 'i' to paste/copy or edit the file.

**Comment by johnfn** [comment]
Added in a0bec1456443af29838715d7a3e5ffad07bb31eb.

**Comment by abdelali-hamza** [comment]
i have a problem , when i open a new file in vs code , it is always inn insert mode , how can i remove that ? ( MacOs)

**Comment by georgipetrov98** [comment]
> i have a problem , when i open a new file in vs code , it is always inn insert mode , how can i remove that ? ( MacOs)

I am wondering about this too ^^
