### ISSUE TITLE
Marks: go to the position before the last jump

### ISSUE THREAD

**Issue by AWaselnuk** [VSCodeVim/Vim#1089]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---

I'm opening this issue as per your instructions on the roadmap. Hoping to bump this feature up a bit. 

It might be because I'm a Vim newb who hasn't unlocked the full potential of marks, but I find myself constantly pressing `' '` and nothing happens.

**Comment by bijoutrouvaille** [comment]
It would be lovely to have also support for the double-tick variant ``, on which many, like myself, are dependent. Double apostrophe jumps back to the beginning of line. The double-tick jumps back to the same place in line.

**Comment by Chillee** [comment]
@bijoutrouvaille Is there any difference between <C-o> and ``?

**Comment by bijoutrouvaille** [comment]
Yes, to augment my failed attempt at explaining it above, the general difference is that the backtick remembers the column number of the marked line, while with the apostrophe the "cursor is positioned on the first non-blank character in the line," i.e. the beginning of line. Both are useful.
`:help mark-motions`

**Comment by Chillee** [comment]
Oh shit Github formatting messed up my comment. I meant to say
```
@bijoutrouvaille Is there any difference between <C-o> and ``?
```

**Comment by bijoutrouvaille** [comment]
Yep. C-O is a "back" command that moves back one item on the jumplist. The double tick simply alternates between last two positions.

**Comment by halindrome** [comment]
FWIW I was unaware of C-O... and I have been using vi(m) since 1985!

**Comment by brandonbloom** [comment]
I've written patches to address this issue. If you're willing and able. Please test/vote/whatever. Thank you.
