### ISSUE TITLE
Word boundaries broken

### ISSUE THREAD

**Issue by siddharth-krishna** [VSCodeVim/Vim#1090]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In normal mode, used commands that operate on words, like `b, w, e, *, #`, on words in Camel/Pascal case. Earlier, the entire compound word was treated as one word, but now it gets broken up in a strange manner.

For example, if the word is `aBigWord.` and the cursor is on the `.`, then pressing `b` repeatedly takes the cursor to `o, W, i, B, a` instead of directly to `a`.

Searching for occurrences of the same word using `*/#` also work this way. If the cursor is on `W`, it jumps to the next occurrence of `Word`, but if the cursor is on `o`, it jumps to the next occurrence of `ord`. Especially for programming, I think it is much more useful to jump to the next occurrence of `aBigWord`.

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.3
* OS: OS X

**Comment by johnfn** [comment]
I can't reproduce this one. b takes me straight to the start of the word. Same is true of `*`; I don't see that behavior either...

**Comment by siddharth-krishna** [comment]
Apologies, it looks like it was caused by a setting in my `settings.json` file:
```
    "vim.iskeyword": "/\\()\"':,.;<>~!@#$%^&*|+=[]{}`?-_",
```

I added a `_` to the end of it because I wanted vim to treat _ as a word separator (i.e. pressing `b` on `a_long_word` if cursor is on `d` should take it to `w` instead of `a`). But I think I don't understand how this setting works..

**Comment by johnfn** [comment]
I'm a bit confused why adding an underscore would cause our word boundaries to get messed up.

**Comment by johnfn** [comment]
I got it. This is the best bug ever.

We internally treat `iskeyword` as a regex, using `_.escapeRegex` from lodash to escape it before running it. However, `_.escapeRegex` does not escape dashes, so the final three characters in your regex, `?-_` are treated as a character range which includes all upper case letters because of how the ASCII table is arranged. 

Should be easy to write our own escapeRegex function which also escapes dashes.

**Comment by siddharth-krishna** [comment]
Wow, that's an interesting bug. Thanks for the fix!
