### ISSUE TITLE
vim.scroll setting doesnt' work

### ISSUE THREAD

**Issue by wangsongiam** [VSCodeVim/Vim#1093]
### What did you do?

added the `"vim.scroll": 5,`to  `settings.json`; restarted vscode

then tried `ctrl-u` `ctrl-d` for some scrolling
### What did you expect to happen?

scroll 5 lines at a time

### What happened instead?

it still scrolled 20 lines a time

### Technical details:

* VSCode Version: the latest
* VsCodeVim Version: the latest
* OS: 10.11.6

**Comment by johnfn** [comment]
We actually don't support this any more; it was a holdover from the old days when we couldn't implement `<C-d>` etc due to vscode api issues.

If you want something similar, you could try remapping `<C-u>` to, say, `5k`.

**Comment by johnfn** [comment]
This works for me:

```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<C-u>"],
            "after": ["5", "k"]
        },
        {
            "before": ["<C-d>"],
            "after": ["5", "j"]
        }
    ],
```

**Comment by wangsongiam** [comment]
alright, thanks

**Comment by linmodev** [comment]
@johnfn But it is not working properly, when the continuous press U or D key will flash screen
