### ISSUE TITLE
VIM emulation - Ctrl-o in insert mode does not work as expected

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#1097]
_From @lzybkr on November 29, 2016 0:8_

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|vim|vscodevim|0.1.10|

---

Steps to Reproduce:

1. Edit a document, make sure you are in insert mode
2. Hit Ctrl-o [see docs](http://vim.wikia.com/wiki/Use_Ctrl-O_instead_of_Esc_in_insert_mode_mappings)
3. Open file dialog opens
expected
3. I can enter a single normal mode command then continue in insert mode

_Copied from original issue: Microsoft/vscode#16191_

**Comment by xconverge** [comment]
Is this reproducible?

Is this vscode vim 0.4.4+?

Is use ctrl keys enabled?

**Comment by xconverge** [comment]
Seems to work fine for me, if this bug was filed when using vscode vim 0.1.10 that would explain it...

**Comment by lzybkr** [comment]
Yeah, looks like I had the old extension on that system, and it works fine in the latest.  Go ahead and close.

**Comment by johnfn** [comment]
😄  thanks @xconverge for checking and @lzybkr for confirming!
