### ISSUE TITLE
implement forward commands

### ISSUE THREAD

**Issue by corymickelson** [VSCodeVim/Vim#110]
/** Ooops, more correctly called "find" motion, as "F" searches in a backwards pattern, while "f" searches in a forward pattern**/

f + character to move forward to. 
example
```javascript
function something () {
    var anObj = {
        prop: value
    };
    var anArray = [ "string", { prop: val, prop1: [1, 2, 3] } ];
}
```
if we are at the top, anywhere on the function line, and press ( f {  ), the cursor should move to the first matching character, which happens to be at the end of the first line, but to complete this functionality if you press ";" while on the { on the top line, you should now move to the next occurrence of that character, which happens to be on the next line down, and press ";" again and you should move to the { in the array a couple lines below.

Not sure how to implement a command that requires user input, but will take a look and see what I can do. Does anyone else have any interest on working on this one?

Will take a look at how atom implements this feature.

**Comment by jpoon** [comment]
:+1:

**Comment by jpoon** [comment]
Will use this to track this feature: https://github.com/VSCodeVim/Vim/issues/187
