### ISSUE TITLE
Visual mode stops working

### ISSUE THREAD

**Issue by Ashod** [VSCodeVim/Vim#1101]
### What did you do?

Edited normally for several hours.

### What did you expect to happen?

Commands in Visual Mode to continue working as expected.

### What happened instead?

Every once in a while all Visual Mode commands stop working.

For example, Shift+v then arrows doesn't select, but enter insert mode!
/ doesn't enter search. etc.

The only way to break out of this mess is to ignore the Visual Mode and edit in insert mode, then it starts working again, but only for a short while, until it breaks again.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.2
* OS: Ubuntu

**Comment by xconverge** [comment]
Is this the same as #1054

**Comment by Ashod** [comment]
@xconverge Yup. Especially your comment: "It only happens after some amount of time though".

So it's not that it's completely broken (as the title implies) but it works only intermittently.

Feel free to close as duplicate if necessary.

**Comment by johnfn** [comment]
Closed as duplicate. This is really annoying though, please let me know if there's anything you can do to trigger this more reliably @Ashod!
