### ISSUE TITLE
Easy Motion 2 Char Search Not Supported

### ISSUE THREAD

**Issue by CheesePizza100** [VSCodeVim/Vim#1102]
### What did you do?
Was playing around with easy motion and was super excited (!!!!) for 2 character search. Since the feature is not supported it is easy to see in action.

Put the exact keys you pressed.
\\+s then the first character will work as expected and matching letters will appear on the screen. the second character you enter will jump to that position on the screen.

### What did you expect to happen?
The two letter sequence to be highlighted on the screen with the key sequences to jump to.

### What happened instead?
Matches were shown on the screen that matched the first keypress.  The second keypress caused the cursor to jump to the match it found.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 4.0.4
* OS: Windows 10 64 bit

**Comment by johnfn** [comment]
Pinging @Metamist as he's the guy who worked on easymotion support. :)

**Comment by leemhenson** [comment]
I'd go a stage further and suggest it would be better to support n-character search instead (https://github.com/easymotion/vim-easymotion#n-character-search-motion). I took a little look at the current code and I guess the implementation of `compareKeypressSequence` here https://github.com/VSCodeVim/Vim/blob/master/src/actions/actions.ts#L30 would need to be updated. At present, it looks like there's no scope for describing a match against an array, e.g. `<character>[]` or something.

It occurs to me that "debounced-timer-based arbitrary-length keystroke collection" might be something that would be useful for other functionality, but would also complicate the existing impl a fair bit. It would be great if a maintainer could suggest whether this would be something that would be likely or unlikely to be accepted....

**Comment by eromoe** [comment]
It show `Search for 1 character:`  either `<Leader><Leader>w` or `<Leader><Leader>s`. Can not search for n character with hightlight

**Comment by Chillee** [comment]
@MaxfieldWalker This issue should be able to be closed now, right?

**Comment by MaxfieldWalker** [comment]
@Chillee Yes, this issue was resolved with PR #1967!

**Comment by Chillee** [comment]
Nice!
