### ISSUE TITLE
in visual mode type e ,not end of the word

### ISSUE THREAD

**Issue by suyuanhan** [VSCodeVim/Vim#1107]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

for example "Hello world"(without quotas)
I cursor start in H,and press v(switch to visual mode),then press e(point to 'o'),
but what I found is it just select "Hell" ,not include "o",you can type many Hello world ,can see the high line)

### What did you expect to happen?

Select Hello

### What happened instead?

Select Hell

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.4
* OS: windows 7

**Comment by xconverge** [comment]
What do you mean is not selected? If you press y and then p it pastes the whole word, right?

I think you are seeing #616

**Comment by johnfn** [comment]
The only time I know of that this makes a difference with is using ctrl/cmd-c to copy text you've selected - in that case, you'll lose the last character.

If that's the problem, go and thumbs up #616 :) 

If not, let me know.

**Comment by cafreeman** [comment]
This also comes up when selecting multiple instances of a word. `v e` followed by `cmd+d` will end up searching for the the highlighted word *minus* the last letter (`Hell` instead of `Hello`).

Definitely comes up a lot when doing multi-cursor stuff.
