### ISSUE TITLE
[cd]it inside of tag which includes another empty tag

### ISSUE THREAD

**Issue by DanEEStar** [VSCodeVim/Vim#1108]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

See this test case which works in Vim:

```
    newTest({
      title: "Can do cit inside of a tag with another non closing inside tags",
      start: ["<blink>hello<br>wo|rld</blink>"],
      keysPressed: "cit",
      end: ["<blink>|</blink>"],
      endMode: ModeName.Insert
    })
```

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: current master in time of writing
* OS: Mac

I am working on a solution by the way...

**Comment by johnfn** [comment]
@DanEEStar Could you open up a PR just so everyone knows what you're working on? Feel free to mark it [WIP].

**Comment by johnfn** [comment]
(This one actually seems fairly complex. It looks like it involves parsing HTML. So if you want to work on something easier, feel free...)
