### ISSUE TITLE
Show command in status bar as it's being entered (showcmd)

### ISSUE THREAD

**Issue by tomasiser** [VSCodeVim/Vim#1109]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

In original vim, there is a `showcmd` setting that shows partially entered commands in the status line. So for example, the command `ci"` requires 3 keystrokes until it can be executed, but pressing the keys is basically invisible to the user. With `showcmd` enabled, vim displays the first `c` and then `ci` as they're being entered. Pressing ESC cancels the command and resets the status line as expected.

**Comment by johnfn** [comment]
Thanks for the request! I just added this and it should be out in 0.4.7.
