### ISSUE TITLE
Remapping navigation keys no longer work

### ISSUE THREAD

**Issue by RacingBird** [VSCodeVim/Vim#1116]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Remapped ["j"] to ["j", "z", "z"] by adding the following to my settings.json file:
```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["j"],
            "after": ["j", "z", "z"]
        }
```
### What did you expect to happen?

When pressing 'j' in 'other' (non-insert) mode, the cursor should move down  and the editor should be vertically centered around the cursor.

### What happened instead?

The cursor "froze" and all navigation keys (j, k, 0, arrow-keys, etc.) no longer have any effect.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.7
* OS: Windows 7

**Comment by johnfn** [comment]
Thanks for the bug report. This has been fixed on master and will be out in 0.4.8 shortly.
