### ISSUE TITLE
Selecting to end of word, then pasting to clipboard, then loses the last character

### ISSUE THREAD

**Issue by dracan** [VSCodeVim/Vim#1118]
### What did you do?

`ve` then `ctrl+c`

### What did you expect to happen?

Highlight to end of current word, then put the highlighted text into the Windows clipboard.

### What happened instead?

It did as expected, except the last character of the word was missing from the text in the clipboard.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.4
* OS: Windows 10

**Comment by xconverge** [comment]
This is a duplicate of #616

**Comment by dracan** [comment]
Ah okay, will close, and add a comment in there then instead.
