### ISSUE TITLE
VSCodeVim keeps overwriting editor.cursorBlinking to "blink" in my User settings

### ISSUE THREAD

**Issue by cerk** [VSCodeVim/Vim#1119]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Nothing. vscodevim overwrites my settings.json file to that editor.cursorBlinking is always "blink" even when I want it to be something else. If I overwrite settings.json manually, it appears vscodevim writes the "blink" settings back in approximately 5 to 10 seconds.

Put the exact keys you pressed.

### What did you expect to happen?
I don't want vscodevim to overwrite my editor.cursorBlinking setting.

### What happened instead?
vscodevim overwrites my editor.cursorBlinking setting.

### Technical details:
If I disable vscodevim, then this behavior stops. So it appears vscodevim is the source of the problem. This just started happening on the latest update.

* VSCode Version: 1.7.2
* VsCodeVim Version: *[please ensure you are on the latest]* 0.4.7
* OS: Windows 10

**Comment by rebornix** [comment]
I didn't even know that we are changing `cursorBlinking` somehow :(

**Comment by cerk** [comment]
I am not sure you are. I am just reporting what I am seeing. Can anyone else reproduce?

The easiest way to reproduce on my end is to make sure "vim.useSolidBlockCursor" is "false", and then try editing "editor.cursorBlinking" to "solid." A few seconds later, it changes to "blink" without me doing anything.

If "vim.useSolidBlockCursor" is "true", I was able to get "editor.cursorBlinking" to change to "blink", but I cannot reproduce what I did now.

Note that before today, I had "vim.useSolidBlockCursor" as "false" and I never had this problem before. I will start using "vim.useSolidBlockCursor" as "true".

**Comment by rebornix** [comment]
Just found it has something to do with `useSolidBlockCursor` as we don't update any Code configuration with a clean install/user setting.

**Comment by johnfn** [comment]
The reason for this is if you turn on useSolidBlockCursor like in Vim, we _have_ to override cursorBlink because in Normal Mode the cursor doesn't blink and in Insert Mode it does. @rebornix I couldn't find any other way to do this other than to set it globally, but maybe you know of a different way?

It makes sense that if you have useSolidBlockCursor off, we just respect your current cursorBlink setting, though, so I can fix that part of this bug.
