### ISSUE TITLE
repeat inserted character/word (e.g., 5i=[esc]) not supported

### ISSUE THREAD

**Issue by ladevan** [VSCodeVim/Vim#1122]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

I pressed `5i=[esc]`

### What did you expect to happen?
what to get =====, what to do a quick input for reStructuredText title tag. XD
### What happened instead?
Nothing
### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.8
* OS: Windows 8.1

**Comment by xconverge** [comment]
This will be in the next release
