### ISSUE TITLE
`yyp` paste garbled text when the line contains only Chinese characters and 'vim.useSystemClipboard' is on

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#1125]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. edit vscode config to enable 'vim.useSystemClipboard' and restart vscode
2. create a new file with below content

```
通过将设置放入设置文件中来覆盖设
```

3. open the file and `yyp` on the line

### What did you expect to happen?

the file content becomes
```
通过将设置放入设置文件中来覆盖设
通过将设置放入设置文件中来覆盖设
```

### What happened instead?

the file content becomes
```
通过将设置放入设置文件中来覆盖设
惽?\緥n>eeQ緥n噀鯪-Neg唹講緥
```

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9
* OS: windows 10 professional build 1607

**Comment by xconverge** [comment]
This is fixed for macOS and linux but not windows yet unfortunately! Related https://github.com/sindresorhus/clipboardy/issues/11
