### ISSUE TITLE
Do not want blinking cursor in insert mode

### ISSUE THREAD

**Issue by cerk** [VSCodeVim/Vim#1127]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
When I enter insert mode, the cursor blinks.

### What did you expect to happen?
I want the cursor to change shape, but not to blink.

### What happened instead?
The cursor blinked when I entered insert mode.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: *[please ensure you are on the latest]* 0.4.9
* OS: Windows 10

This was behavior was recently changed due to this closed issue:
https://github.com/VSCodeVim/Vim/issues/1105

I cannot stand blinking cursors. Please allow the option to never see a blinking cursor.

**Comment by johnfn** [comment]
This is configurable by a VSCode setting now.

First, remove any line in your config that looks like this:

`    "vim.useSolidBlockCursor": true,`

Now, add this line to your config.

`    "editor.cursorBlinking": "solid",`

You should now have a solid cursor everywhere.

**Comment by cerk** [comment]
Thank you! I had added vim.useSolidBlockCursor recently due to another issue and that was my issue.
