### ISSUE TITLE
Normal mode mappings reverting to unmapped actions (with weird timing)

### ISSUE THREAD

**Issue by Cody157** [VSCodeVim/Vim#1128]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

```json
    "vim.otherModesKeyBindings": [
        {
            "before": [ "`" ],
            "after": [ "^" ]
        },
        {
            "before": [";"],
            "after": [":"]
        },
        {
            "before": ["<space>"],
            "after": ["/", "esc"]
        }
    ],
```

### What did you do?

Put the exact keys you pressed.
`;`

### What did you expect to happen?
Enter vim command line

### What happened instead?
Performed unmapped `;`, that is, repeated the last t, T, f, or F command I used.
This isn't specific to my `;` mapping either, same thing happens with remapped `<space>` (where it performs its original function of "move cursor right").

This does not happen if I have hit any(?) key before and within about a second of the mapped key. That is `;;` will perform unmapped `;` action and then open the vim command line. Or 'l;' will move the cursor right then open command line (showing that it's not specific to double clicking). But something like `;` <wait a second> `;` will just perform unmapped `;` action twice.

### Technical details:

I jumped straight from I think 0.4.4 to 0.4.9 on my VsCodeVim Version, so I don't know when this started.

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9
* OS: OS X El Capitan Version 10.11.6

**Comment by johnfn** [comment]
I can't repro this. Remapping ; to : seems fine to me.

Can you paste in your entire settings.json just for fun?

**Comment by gstewart** [comment]
I'm seeing this with the **otherModesKeyBindingsNonRecursive** example from the README too.

This should bind `:` to show the command palette
```json
"vim.otherModesKeyBindingsNonRecursive": [
  {
    "before": [":"],
    "after": [],
    "commands": [
      {
        "command": "workbench.action.showCommands",
        "args": []
      }
    ]
  }
]
```
If I press any other *vim handled* key (except a mode changing key like `i` or `a` for obvious reasons), and then press `:`, it will show the *command palette*. If I don't do anything for a few seconds and then press `:`, it will show the *Vim command line* instead.

This seems to be directly related to the `vim.timeout` value. I set `vim.timeout` to `5000` for a test. If I press a key (`Esc` for example), and press `:` within 5 seconds, it will show the *command palette*. If I wait beyond 5 seconds before pressing `:`, it will show the *Vim command line*.

It does have to be another *vim handled* key. If I use something like `ctrl+/` and then `:`, it won't do it.

The same is happening with the `j->gj` and `k->gk` mappings I have in **otherModesKeyBindingsNonRecursive**.

**Comment by johnfn** [comment]
Ohhhhhhhhhh, the bug was in my settings.json, not yours! Thanks @gstewart, it's totally the timeout. I should fix this shortly.

**Comment by Cody157** [comment]
I see. Thanks @gstewart for figuring more out about this and thanks @johnfn for the temporary solution! I've never notice the `vim.timeout` setting, so I doubt I could've made the connection.

**Comment by johnfn** [comment]
@Cody157 It's another recent addition 😉

**Comment by johnfn** [comment]
Fixed on master!
