### ISSUE TITLE
Keyboard shortcuts that worked in the past do not work any longer

### ISSUE THREAD

**Issue by cerk** [VSCodeVim/Vim#1129]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
This is part of my keybindings.json:

    { "key": ", w", "command": "workbench.action.files.save",
                    "when": "editorFocus && !inDebugRepl && vim.mode == 'Normal Mode'"
    },

When I press the comma key followed by the "w" key, I want to write the current file to disk.

### What did you expect to happen?
Before, this keyboard shortcut would work, now it does not. I know this keyboard shortcut was working in 0.4.5 vscodevim. I don't know if it worked since then.

### What happened instead?
The comma appears to be "eaten" by vscodevim and the "w" key command is issued. The keyboard shortcut never activates.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: *[please ensure you are on the latest]* 0.4.9
* OS: Windows 10

It is possible I am not understanding the best way to do this type of keybinding and make it play nice with vscodevim. If there are suggestions, I am open to advice. However, it was working in past vscodevim versions but no longer works.

**Comment by johnfn** [comment]
Honestly, this remapping should never have worked before 0.4.8 because `,` is a VSCodeVim action. However, as of 0.4.8, you can actually make this a VSCodeVim remapping by using `<leader>`.

```
"vim.leader": ",",

"vim.otherModesKeyBindingsNonRecursive": [
   {
       "before": ["<leader>", "w"],
       "after": [],
       "commands": [
           {
               "command": "workbench.action.files.save",
               "args": []
           }
       ]
   }
]
```

**Comment by cerk** [comment]
Thank you once again!
