### ISSUE TITLE
leader: Can't use <space> in "vim.leader" setting

### ISSUE THREAD

**Issue by hastebrot** [VSCodeVim/Vim#1132]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Defined `<space>` as leader key in my `User/settings.json`. Restarted. And tried some easymotion combinations (e.g. `<leader> <leader> s <char>`).

~~~json
{
  "vim.leader": "<space>",
  "vim.easymotion": true
}
~~~

Background: Having the space key as leader key is inspired by evil mode (vim mode) in the Spacemacs Emacs distribution.

### What did you expect to happen?

The space key should do nothing, but it should work for easymotion commands.

### What happened instead?

The space key jumped to the next cell in the text editor.

When I use `" "` instead of  `"<space>"` as `vim.leader` it works as expected.

### Technical details:

* VSCode Version: 1.8.0-insider (`2016-12-06T16:09:29.346Z`).
* VsCodeVim Version: 0.4.9.
* OS: Ubuntu 16.04 LTS.

**Comment by hastebrot** [comment]
Also note. My intention is to later use `<space>` or `<leader>` to define new key bindings for other modes.

~~~json
"vim.otherModesKeyBindingsNonRecursive": [
  {
    "before": [ "<space>", "o" ], 
    "after": [],
    "commands": [
      { "command": "workbench.action.quickOpen", "args": [] }
    ]
  }
]
~~~

Currently when I use `"<space>"` as `vim.leader` the whole command does not work. Also somehow combination only works once.

- <kbd>space</kbd> <kbd>o</kbd> &mdash; opens the quick open widget.
- <kbd>space</kbd> <kbd>o</kbd> <kbd>esc</kbd> <kbd>space</kbd> <kbd>o</kbd> &mdash; opens the quick open widget, closes it, and does nothing.
- <kbd>space</kbd> <kbd>o</kbd> <kbd>esc</kbd> <kbd>esc</kbd> <kbd>space</kbd> <kbd>o</kbd> &mdash; opens the quick open widget, closes it, and opens it again.

**Comment by vadimi** [comment]
I'm also trying to use something like that and it's not working:

```
"vim.otherModesKeyBindingsNonRecursive": [
{
    "before": ["<space>", "f", "s"],
    "after": [],
    "commands": [
        { "command": "workbench.action.files.save", "args": [] }
    ]
}
```

**Comment by johnfn** [comment]
@vadimi Could you also try using `" "` instead of `"<space>"` and see if that works?

**Comment by vadimi** [comment]
@johnfn tried that too on macOS and Windows 7 - no luck.

**Comment by jnachtigall** [comment]
I cannot even use  `"vim.leader": " ",`

This gives me `Unknown configuration setting`:

![2016-12-19 10_50_26-settings json - bmfsfj-frontend-resources - visual studio code](https://cloud.githubusercontent.com/assets/3307404/21308183/0e084e3c-c5d9-11e6-9bca-64439a89523b.png)

Also there's no default `vim.leader` in the default settings.json in my case. Current stable VSCode and current version of VSCodeVim.

**Comment by chulander** [comment]
> I cannot even use `"vim.leader": " ",`
> 
> This gives me `Unknown configuration setting`:
> 
> ![2016-12-19 10_50_26-settings json - bmfsfj-frontend-resources - visual studio code](https://cloud.githubusercontent.com/assets/3307404/21308183/0e084e3c-c5d9-11e6-9bca-64439a89523b.png)
> 
> Also there's no default `vim.leader` in the default settings.json in my case. Current stable VSCode and current version of VSCodeVim.

i used <space> and it works fine along with @hastebrot snippet.

**Comment by bytesizedpcs** [comment]
I have used all snippets available and nothing works.

When setting `"vim.leader": " "` or `"vim.leader": "<space>"` all `<leader>` presses end up hanging VSCode, causing me to have to restart the entire editor.

**Comment by tecfu** [comment]
Doesn't work for me either. I'm going to create a new issue, as it seems this was never actually fixed. 

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic
```

**Comment by leedre** [comment]
You can set your custom leader key by setting in vscodevim's setting
File > Preferences > Settings > Enter "@ext:vscodevim.vim leader"

![Screenshot 2021-12-14 232118](https://user-images.githubusercontent.com/28940227/146123168-480cdc4d-b1ba-4578-9933-32fb02a2f597.png)
