### ISSUE TITLE
"Back to last edit" command

### ISSUE THREAD

**Issue by sumanx** [VSCodeVim/Vim#1133]
In VIM there is a command enable us to switch between current position and last edited position, for example I edited line 10, and press j to line 100, then I type ` twice, I will back to line 10, and type that again, I will at line 100 again.

I use this command very often and hope it could be added into VSCodeVim.

**Comment by xconverge** [comment]
Do you mean ```g;``` and ```g,``` to navigate the changelist? I am working on those now but dont see anything about ``` ` ``` to do the same thing

**Comment by sumanx** [comment]
Not ``g;``, like this question: http://stackoverflow.com/questions/5052079/move-cursor-to-its-last-position

**Comment by xconverge** [comment]
Ah ok, it looks like according to the roadmap it is still low priority

https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#marks-and-motions

Thanks for filing the issue!

For what its worth, g; and g, should be implemented soon, so this one should have the infrastructure in place to exist very easily at that point

**Comment by sumanx** [comment]
Oh that's good, thank you! ``g;`` is ok before "marks-and-motions".

**Comment by johnfn** [comment]
I think everything that is incomplete is marked as low priority on the roadmap so take that with a grain of salt 😉

**Comment by Chillee** [comment]
This should be already implemented, so I think this issue should be closed?

**Comment by spinningarrow** [comment]
I think this is the same/similar to #1089

**Comment by xconverge** [comment]
Yep, fixed in #1089
