### ISSUE TITLE
Wrong cursor placement after indenting multiple lines

### ISSUE THREAD

**Issue by mklinga** [VSCodeVim/Vim#1135]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Select multiple lines with linewise-select (shift+v)
Indent them with `<` or `>`
Press `k` or `j`

### What did you expect to happen?

Indent the lines, and move the cursor one line up/down from the first line of the selection.

### What happened instead?

The lines were indented correctly, but the cursor movement after the indentation started from the last line of the (cleared) selection instead of the first, despite the cursor showing on the first line of the selection after they have been indented.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9
* OS: macOS Sierra

**Comment by mklinga** [comment]
Just a side note - this was a regression on the v0.4.9, on the version v0.4.8 and prior the cursor position was correct.

**Comment by johnfn** [comment]
I know why this is: https://github.com/VSCodeVim/Vim/commit/648dbf96115c93cafc107cf07f1cd7aea0fab006

Easy bug fix to whoever wants it. Otherwise I'll get to it in the next few days. 😄

**Comment by xconverge** [comment]
This seems to be all good now?

**Comment by mklinga** [comment]
Still seeing the issue with version 0.4.10.

I did some digging and found out that the culprit is the following line on my config:
```
"vim.useSolidBlockCursor": true,
```

If I remove that line from the config, the cursor positioning is always correct, but with the solidBlockCursor enabled it gets the position wrong.

**Comment by sashee** [comment]
Still seeing this issue in 0.6.2.

Disabling ```vim.useSolidBlockCursor``` fixes it.

**Comment by jpoon** [comment]
I believe this is fixed by https://github.com/VSCodeVim/Vim/pull/1402. Please re-open if that's not the case.
