### ISSUE TITLE
Highlighting until last last non-blank character and performing an action.

### ISSUE THREAD

**Issue by johnfreier** [VSCodeVim/Vim#1136]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----
When highlight until the end of a light and then trying to remove or change it, it does not work.

### What did you do?
In the middle of a line of characters I press the following keys.
keys: v, g, _, x

### What did you expect to happen?
I expect it to highlight until the end of the line and then delete all the highlighted characters.

### What happened instead?
Nothing

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9
* OS: OSX 10.11.6

**Comment by xconverge** [comment]
Thanks! I was able to reproduce this, highlight to beginning of line does work though v, _, x

**Comment by johnfreier** [comment]
Yes there is a slight difference. `v, g, _`, highlight until the last non-blank character.  `v, $` highlights until the end of the line, including the line break.
