### ISSUE TITLE
Sidebar move/select with homerow -- feature request --

### ISSUE THREAD

**Issue by monkoose** [VSCodeVim/Vim#1138]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Didn't find anything about this in open issues.
Would be cool to create/navigate/select/delete files with good keybindings at least in Explorer tab. Something like NERDTree.
And :e in ex-mode dont support path completions(so its hard to navigate) and if you want to create a file it still ask for confirmation that can be enabled only with the mouse. (Something like advanced create file plugin in Atom).

Do not complaining here. You are doing great work guys.

**Comment by johnfn** [comment]
This is actually tracked by this issue: https://github.com/VSCodeVim/Vim/issues/754

Definitely go and thumbs up the relevant VSCode issues / add comments where necessary! 😄
