### ISSUE TITLE
Multi cursor doesn't work with visual mode for selection.

### ISSUE THREAD

**Issue by CountZukula** [VSCodeVim/Vim#1140]
### What did you do?
In the text line 
`test1 test2 test3` 
i put the cursor at the start. Then went into visual mode (v), selected the first `test` using 4*`l`. 
Then pressed CTRL+D (disabled CTRL keys for the VIM plugin) twice to select the next two occurrences of `test`. After that, any VI command would only execute on the first `test1`.

### What did you expect to happen?
Pressing `c`, for example, should remove all selected `test` occurrences, giving three cursors to type from.

### What happened instead?
Pressing `c`, with the three `test` instances selected, and then typing `hello`, results in: 
`hello1 teshellot2 teshellot3`. The first test `c` worked as expected: test was deleted and I got a cursor in which hello was typed. The second and third didn't delete, but gave only the cursor to type in.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9
* OS: Linux Mint 17

**Comment by xconverge** [comment]
Can you try the same test using gc instead of CTRL+D?

gc does the same thing, goes to next occurrence

It works correctly for me using gc and just want to get some more info from you

**Comment by CountZukula** [comment]
That seems to work fine, although I would expect `i` to clear the selection and start editing at all cursors at that point. `x` and `c` work as i would expect! Thanks, this makes everything livable again :).

**Comment by johnfn** [comment]
The reason `i` doesn't clear the selection is because you're in visual mode, and `i` works just like it would normally work in visual mode. Try `<esc>` `i`

**Comment by CountZukula** [comment]
Well, using CTRL+D for the multiple selection and then pressing ESC means that I drop out of visual mode, but I also lose the multiple cursors. This completely besides the point that pressing `i` in visual mode doesn't really do anything in the real VIM, which I mistook.

**Comment by johnfn** [comment]
Interesting. Cmd-d Cmd-d Cmd-d followed by ESC does not drop me out of multi-cursor mode. Are you saying that's what happens for you?

**Comment by CountZukula** [comment]
Exactly:

`test1 test2 test3`
press `v`, highlight `test`. Then 3* ctrl+d. I see visual mode enabled. Then `esc`, i drop to normal mode and the cursor is on the second `t` of `test1`. No other cursors enabled. Before I press `esc` i do see the multiple cursors blink, with all `test` instances selected. After pressing `esc`, no selection is present (as expected) and only the first cursor survives. 

I installed these two extensions: Guides 0.5.1 and Vim 0.4.9, with only this in my user settings:

`
{
    "vim.useCtrlKeys": false
}
`

**Comment by johnfn** [comment]
Okay, that's exactly why. We can't override ctrl-d without useCtrlKeys set to true. If you want to keep it false, try using `gc` instead of ctrl-d.
