### ISSUE TITLE
Enable key bindings in insert mode

### ISSUE THREAD

**Issue by dala00** [VSCodeVim/Vim#1142]
In insert mode, ctrl+c, ctrl+x, ctrl+f are not working.

I think they should work as default behavior of VSCode in insert mode.
(as copy, cut, search)

I changed package.json setting like this.
https://github.com/dala00/Vim/commit/e36694b2ab898726f257221d9b22d598688c9711

Is it better to PR this ?
or any problems exists ?

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9

**Comment by dala00** [comment]
note:
ctrl-v(paste) was already treated

**Comment by johnfn** [comment]
The real problem here is we accidentally enabled `useCtrlKeys`. 

If you want these shortcuts enabled, just put `"vim.useCtrlKeys": false` in your user settings json file.

**Comment by dala00** [comment]
No, I need vim.useCtrlKeys:true in 'command mode'.
Vim's original behaviors are very nice.

But in 'insert mode', I don't understand what ctrl+x, ctrl+f are doing.
I think they should work as default behavior of VSCode.

By setting of package.json@0.4.9, ctrl+v has vim.mode condition.
I think this is right.
and I want f ,x are same as v.

Atom's extension is like this. Very good to use.

(I'm sorry, ctrl+c is good now. My commit is wrong)

**Comment by dala00** [comment]
Sorry, should not change ctrl+x.
Only ctrl+f is good to work as search in insert mode.

**Comment by yogan** [comment]
I want to have pretty much the same behaviour that @dala00 described – `vim.useCtrlKeys` set to `false` on purpose, but still some non-vim `<ctrl><sth>` keybindings in insert mode.

I found that this works pretty well: putting the original mapping (not the one the extensions adds, with the `vim.useCtrlKeys` condition) in your user specific `keybindings.jsons`. So for example, I have those entries there:
```    { "key": "ctrl+b",            "command": "workbench.action.toggleSidebarVisibility" },
    { "key": "ctrl+f",            "command": "actions.find",
                                     "when": "editorTextFocus && !inDebugRepl" },
```

**Comment by jpoon** [comment]
@dala00 so, effectively what you are asking for is you want to use VSCode's find when in insert mode? If so, can you re-adjust the title of this issue to clarify?

**Comment by johnfn** [comment]
There is a way to selectively turn off keys that we handle now!

e.g.

```
    "vim.handleKeys":{
        "<C-a>": false,
        "<C-f>": false
    }
```

Thanks to @xconverge as usual!

**Comment by dala00** [comment]
Oh, great. thanks.

**Comment by dala00** [comment]
I solved this issue by adding this setting to keybindings.json

```json
    {
        "key": "ctrl+f",
        "command": "actions.find",
        "when": "editorTextFocus && vim.active && vim.use<C-f> && vim.mode == 'Insert' && !inDebugRepl"
    },
```

thx

**Comment by samrocksc** [comment]
Just wanted to drop a quick update in here: 

```JSON
{
    "key": "shift+k",
    "command": "editor.action.showHover",
    "when": "vim.active && vim.mode != 'Insert'"
  }
```

This is how I got it to simulate my CoC config
