### ISSUE TITLE
Broken image link on VSCode extensions page

### ISSUE THREAD

**Issue by alnorris** [VSCodeVim/Vim#1149]
<img width="390" alt="screen shot 2016-12-11 at 12 15 03" src="https://cloud.githubusercontent.com/assets/882627/21079997/9d7567ba-bf9b-11e6-8b89-e599b6e49d07.png">

* VSCode Version: 1.7.2
* VsCodeVim Version: latest
* OS: OSX El Capitan

**Comment by xconverge** [comment]
Are you sure that is the latest version of the plugin?

The wording is a bit different now with no image

https://marketplace.visualstudio.com/items?itemName=vscodevim.vim
