### ISSUE TITLE
Support for Tags is missing.

### ISSUE THREAD

**Issue by mswift42** [VSCodeVim/Vim#1150]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

I miss support for Browsing programs with tags.

For a definition of Tags see here: [Vim Wikia: Browsing programs with tags](http://vim.wikia.com/wiki/Browsing_programs_with_tags).

The entry of the Roadmap states, that tag support is low priority, because vscode has very good support for tags, and citing the keybinding `ctrl+shift+t`. Unfortunately, I have no idea what ctrl+shift+t is supposed to do, it doesn't work on my box, and googling for it showed no results.

The one thing I'm really missing is, hovering over a method name, pressing Ctrl+] to go to its definition, and pressing Ctrl+o to go back where is was previously.

**Comment by johnfn** [comment]
You should be able to use gd to go to the definition of any symbol, so long as vscode is smart enough to know where it is.

**Comment by johnfn** [comment]
My bad, ctrl-shift-t was the wrong key binding. You want whatever the binding is for go to symbol. On my box it's cmd-t in a single file and cmd-shift-o across the entire project.

**Comment by mswift42** [comment]
Yes, I can use gd to go to a definition. But how do I get back ? using vim, pressing Ctrl+o returns you to the position you invoked the command. Here I would have to switch tabs and find my original position in the file  manually.

**Comment by johnfn** [comment]
Until we implement that, you can use ctrl dash, which is a VSCode command to return you to wherever the cursor used to be. 😄

**Comment by mswift42** [comment]
Do you have the name for this command ?

**Comment by johnfn** [comment]
https://code.visualstudio.com/docs/customization/keybindings 

Apparently it is `workbench.action.navigateBack`.

**Comment by mswift42** [comment]
Thanks, (on Linux it was Ctrl+Alt+-) after Remapping to ctrl+o, works (so far) like a charm.

**Comment by johnfn** [comment]
Wonderful. We should really add ctrl-o in just as a direct map to `workbench.action.navigateBack`. That seems like an easy change.

**Comment by mswift42** [comment]
Definitely, I also vastly Ctrl+] over gd, because its quicker to type.

**Comment by Chillee** [comment]
I want to note that I don't think this is really a feature. Vim has `gd`, `gD`, and `<C-]>`, all which do subtly different things. However, I'm pretty sure that most people who press any of these commands really just want `go to definition`. All that we need to do is add `<C-]>` to the command for `gd`, I think.

**Comment by sikthought** [comment]
Is this an issue that can be closed:

https://github.com/VSCodeVim/Vim/blob/36725f165be291ac92722facd8542740e5672ce6/src/actions/commands/actions.ts#L2075

**Comment by jpoon** [comment]
Thanks for pointing this out @sikthought. Closing!
