### ISSUE TITLE
Add option to set delete to an other clipboard then yank and paste

### ISSUE THREAD

**Issue by callamaris** [VSCodeVim/Vim#1152]
Hi,

in vim, i usually set yank and paste to the default os clipboard and delete to another one.

This way, i can delete something without overwriting the content of my os clipboard. But if i need to, i can explicitly use the content of my delete clipboard or yank the text before deleting it.

Please add an option for this.

**Comment by johnfn** [comment]
Have you tried using our mapping to map `d` to something like `"ad`?

**Comment by jpoon** [comment]
This should be supported.

**Comment by wmaurer** [comment]
@johnfn I tried to map using the following:
```
    "vim.otherModesKeyBindings": [
        {
            "before": ["d"],
            "after": ["\"ad"]
        }
    ],
```

... but then when I enter `dw` it's not deleting. Could you tell me what am I doing wrong in the mapping config above? Thanks.
