### ISSUE TITLE
Visual mode multi-line selection fails after some time

### ISSUE THREAD

**Issue by Helcaraxan** [VSCodeVim/Vim#1153]
### What did you do?

After starting Visual Code I am able to use VimMode under normal conditions. However, after some usage I am no longer able to use any type of visual mode (simple, full-line or block) to select content over multiple-lines in order to delete / copy-paste / modify.

I have not been able to identify any specific key-sequence or usage-pattern that triggers this behavior. It just appears after using Visual Code for some time. Somewhere between 1 min with 1 / 2 successful multi-line selects & 20 minutes with many successful selects.

Visually it looks like the following sequence when using 'Shift+v', 'down', 'down', 'dd' :
![vimcode_1](https://cloud.githubusercontent.com/assets/896592/21133644/ce7b3854-c111-11e6-97aa-45cc27cf625e.png)
![vimcode_2](https://cloud.githubusercontent.com/assets/896592/21133646/d01ee4d0-c111-11e6-847d-c28d646ae0ff.png)
![vimcode_3](https://cloud.githubusercontent.com/assets/896592/21133647/d14754c8-c111-11e6-978e-00ced4fee75c.png)

This issue has appeared somewhere between 1 and 3 weeks ago. Don't remember exactly. A restart of Visual Code fixes it... but I don't like the fact of having to restart my editor every 5 minutes.

### Technical details:

* VSCode Version: 1.7.2 (commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f)
* VsCodeVim Version: 0.4.9
* OS: Ubuntu 16.04.1 LTS - Xubuntu spin.

**Comment by johnfn** [comment]
You're using arrow keys, not hjkl, right?

This is Visual Studio Code bug (!) that will be fixed in the next version of the IDE. #1054

**Comment by Helcaraxan** [comment]
Yes arrow keys and it does indeed looks like its the linked issue. Had searched for existing issues but had not stumbled upon that one. Apologies for the duplicate.

**Comment by johnfn** [comment]
No worries! You were probably confused because we already closed it. :)
