### ISSUE TITLE
Cursor behaves erratically when keeping HJKL pressed

### ISSUE THREAD

**Issue by CherryDT** [VSCodeVim/Vim#1154]
When holding a HJKL key, the cursor always keeps erratically jumping backwards again, sometimes not properly moving forward at all. It works when I repeatedly press the key instead.

Here is a demonstration (unfortunately with low FPS, in reality it jumps around even faster):

http://g.recordit.co/VEEwNwcPOj.gif

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9
* OS: Windows 10 Pro Build 14393.479

**Comment by anderejd** [comment]
I have similar problems but for me the cursor moves one step and then stops when holding down h, j, k or l. And for the l-button (lower case L) there is a bonus action, a small popup appears at the top right edge of the Explorer component (see screenshot):

<img width="654" alt="screen shot 2017-01-14 at 19 59 08" src="https://cloud.githubusercontent.com/assets/3704611/21957338/6edd85cc-da94-11e6-8071-80bb9dcb08dc.png">

vscode: 1.8.1
os: macOS Sierra 10.12.2
VSCodeVim: 0.4.10

**Comment by jacky841102** [comment]
same issue as @anderejd on macOS Sierra 10.12.1, VSCode 1.8.1, VSCodeVim 0.4.10

**Comment by quentin-chen** [comment]
same issue.

When holding hjkl for a while, all the keyboard cannot be used any more.

**Comment by Chillee** [comment]
Have you guys tried the solution here?

https://github.com/VSCodeVim/Vim#mac-setup

**Comment by anderejd** [comment]
@Chillee Yeeees it works! Thanks man! :D

**Comment by JohnMorris4** [comment]
Mine is a little different issue but about the same...  I can be doing some code markup and the cursor will drop to the bottom of the window of some other place within the document so then I have to start over again.  I have had the same exact problem both on Ubuntu Linux and Windows 10. And no I am not running one os inside the other

**Comment by cottrell** [comment]
Cursor is jumping around erratically at misc key presses.

**Comment by J-Fields** [comment]
Pretty sure this is resolved
