### ISSUE TITLE
Multi-line visual line mode selection doesn't always work with cursor keys

### ISSUE THREAD

**Issue by iivvoo** [VSCodeVim/Vim#1155]
### What did you do?

Use shift-V to select a line, use cursor down to select the line below

### What did you expect to happen?

Both lines to be selected

### What happened instead?

Sometimes (!) the entire selection gets lost. Selection with j/k always works as expected.
Extending the selection using cursor keys sometimes fails in the left side and works in the right side (and probably vv.) and moving the editor from left to right makes cursor-key selection work again in that editor. Even with the same file open on both sides

### Technical details:

* VSCode Version: 0.4.9
* VsCodeVim Version: 1.7.2
* OS: Ubuntu 16.04 64bit

**Comment by johnfn** [comment]
This is a visual studio code bug that will be fixed in the next version of the IDE, thanks to @xconverge. See #1054 for more. :)
