### ISSUE TITLE
Repeat command (.) is scoped to a file

### ISSUE THREAD

**Issue by vikramthyagarajan** [VSCodeVim/Vim#1156]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Put the exact keys you pressed.
Open 2 files in the same workbench.
1. Delete a line using dd
2. Run the repeat command (.) in the same file. It works
3. Go to the next file and run the repeat command (.)
4. Nothing happens

### What did you expect to happen?

The last command I performed (dd) is repeated

### What happened instead?

Nothing. The repeat command only works within the scope of the file the action was performed in.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.9
* OS: MacOS Sierra 10.12.1

**Comment by xconverge** [comment]
@johnfn can close now!

**Comment by johnfn** [comment]
Thanks @xconverge 😀
