### ISSUE TITLE
cursor shown incorrectly when switching file

### ISSUE THREAD

**Issue by m3l7** [VSCodeVim/Vim#1159]
let's say I am currently on file1 in insert mode.
I switch to file2 and go to normal mode.
Switching back to file1, the cursor is shown as normal mode even if I'm in insert mode.

Using vscode 1.8, vscode-vim 0.4.9, arch linux

**Comment by johnfn** [comment]
How are you switching between files? For me, clicking around seems to preserve modes correctly.

**Comment by m3l7** [comment]
I tried with both clicking in the file tree and with workbench.action.quickOpen menu

I didn't have this problem in vscode vim 0.4.1

**Comment by johnfn** [comment]
Thanks for the report, @m3l7. This is being tracked by #1173.
