### ISSUE TITLE
Multi-Cursor selection

### ISSUE THREAD

**Issue by gugahoa** [VSCodeVim/Vim#1160]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Inside a file like this:
```
foobar
foobaz
foobar
```
Place your cursor on foobar and type `gc`, alternatively:
Select foobar with `viw` and type `gc`

### What did you expect to happen?
Select both foobar and place cursor at the last letter of the word

### What happened instead?
foobaz is selected and the cursor is placed one letter before the last

### Technical details:

* VSCode Version: 1.8.0
* VsCodeVim Version: 0.4.9
* OS: Arch Linux 64bits

**Comment by johnfn** [comment]
Yikes, that's definitely a bug. Thanks for the report.

**Comment by gugahoa** [comment]
Just came back from vacation and tested again against 0.4.10, still happening

**Comment by johnfn** [comment]
Yeah, we'll close this issue if we get it fixed. (usually) 😉

**Comment by lukywong** [comment]
@gugahoa +1 same issue.

**Comment by gugahoa** [comment]
It's fixed in 0.6.16 with vscode 1.11

**Comment by xconverge** [comment]
We didn't fix this...are you sure it is fixed?

**Comment by johnfn** [comment]
Yeah, it's not fixed.

**Comment by gugahoa** [comment]
Oh, sorry. It seems I didn't follow all the steps correctly, just tried again and it really is not working :'(

**Comment by alexgorbatchev** [comment]
v0.8.4

![vscodevim](https://cloud.githubusercontent.com/assets/65633/26732856/e5240b48-476d-11e7-9c04-7297384921ac.gif)

**Comment by Chillee** [comment]
Closed through https://github.com/VSCodeVim/Vim/pull/1862
