### ISSUE TITLE
Multi-Cursor deletion

### ISSUE THREAD

**Issue by gugahoa** [VSCodeVim/Vim#1161]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

```
line 1
line 2
line 3
```

With multi-cursor place a cursor at line 1 and 2, anywhere and press `dd`

### What did you expect to happen?
line 1 and line 2 to be deleted

### What happened instead?
line 1 and line 3 were deleted

### Technical details:

* VSCode Version: 1.8.0
* VsCodeVim Version: 0.4.9
* OS: Arch Linux 64bits

**Comment by johnfn** [comment]
This is actually a known limitation of our current multi cursor stuff, but you're totally right that this should be fixed.

**Comment by gugahoa** [comment]
It's solved
