### ISSUE TITLE
:tabe {file} is relative to current file

### ISSUE THREAD

**Issue by gugahoa** [VSCodeVim/Vim#1162]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In a folder with `file1` in the workspace root and `file2` inside `{workspaceDir}/dir1` open `file2` and press :tabe file1

### What did you expect to happen?
`file1` to be opened in another tab

### What happened instead?
Plugin looked for `file1` inside `dir1` instead of `{worspaceDir}`

### Technical details:

* VSCode Version: 1.8.0
* VsCodeVim Version: 0.4.9
* OS: Arch Linux 64bits

**Comment by jpoon** [comment]
Yes, `:tab` should be operating at the "workshape" level which will correspond to `vim` implementatin.
