### ISSUE TITLE
Keybindings configuration is only active for 1 second after any other keystroke

### ISSUE THREAD

**Issue by StreakyCobra** [VSCodeVim/Vim#1163]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### Short description

When I customize VSCodeVim config in order to invert `j` <-> `t` and `k` <-> `s`, a strange behavior occurs: The remapping works partially: it is active only for 1 second after any other key press. True story :flushed:

### What did you do?

I'm trying to remap `j` <-> `t` and `k` <-> `s` in normal mode because of my special keyboard layout (`bépo`):

![bepo](http://download.tuxfamily.org/dvorak/wiki/images/Carte-bepo-simple.png)

This would allow me to find down/up under the same fingers than `j` and `k` on `qwerty` keyboards.

_**Reproduction Steps**_

* Install VSCode 
* Start VSCode (fresh install, no config file left)
* Install VSCodeVim
* Paste the following content in the user's `settings.json`:

    ```json
    // Place your settings in this file to overwrite the default settings
    {
            "vim.otherModesKeyBindingsNonRecursive": [
            {
                "before": [
                    "t"
                ],
                "after": [
                    "j"
                ]
            },
            {
                "before": [
                    "s"
                ],
                "after": [
                    "k"
                ]
            },
            {
                "before": [
                    "j"
                ],
                "after": [
                    "t"
                ]
            },
            {
                "before": [
                    "k"
                ],
                "after": [
                    "s"
                ]
            }
        ]
    }
    ```

* Close VSCode
* Start VSCode again and open any file with a lot of lines, click in the middle of the page so you can go up/down without reaching a border.
* Wait 2 seconds, and try to press `s` which is now supposed to act like `k` and go one line up. Notice that instead it acts like *substitute*, the normal function bound to `s`, so we may suppose the remapping is **not** working… Buuuuut
* Now instead of pressing `s` directly press another key **quickly** before, like `esc` or `h` or `l`, as in `esc s`. Notice it is going one line up as expected, so the mapping is working. You can even try to do quickly `esc s s s t t t t t s t s t s …` and see that it's working as expected (i.e. navigating between the lines), but then do a pause for 1 second and try pressing `s` or `t` again: they went back to their default behaviors.
* The reverse is also true, `j` pressed directly after another keystroke act as *jump to*, but if you wait 2 seconds and press `j` again it will go one line down

### What did you expect to happen?

I expect the keybindings configuration to be persistent more than 1 second :smile:

### What happened instead?

The keybindings configuration is only active for 1 second after any other keystroke.

### Technical details:

* VSCode Version: 1.8.0
* VsCodeVim Version: 0.4.9
* OS: Archlinux (up to date) x86_64

**Comment by johnfn** [comment]
This is certainly a bug, but it's being triggered by the `vim.timeout` setting. So as a temporary workaround, you could put `"vim.timeout": 100000` into your user settings file. 😉

**Comment by StreakyCobra** [comment]
> So as a temporary workaround, you could put "vim.timeout": 100000 into your user settings file.

Awesome, the workaround makes it useable at least :-)

So now that I know the problem is `vim.timeout`, I searched issues again and #1128 seems to report the same problem, so you have already fixed this in master, am I right?

**Comment by StreakyCobra** [comment]
I cloned the repository locally to try with latest `master` changes and it *seems* to be solved. 

I said *seems* because I just started to try VSCode and never tried to debug an extension, so I'm not sure I did it right :-) Anyway, feel free to close this issue if you think it's fixed on master.

**Comment by StreakyCobra** [comment]
( Sorry for the spam :roll_eyes: )

I played a little bit more on the `master` branch version, and if I add the following settings that is proposed on the extension home page to my settings:

```json
        {
            "before": [
                ":"
            ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.showCommands",
                    "args": []
                }
            ]
        }
```

If I do:

- `:` to open the palette, then `ESC` to close it, then `k` to go one line up, `k` acts again wrongly as `substitute`.

But instead if I do:

- `Ctrl + Shift + P` to open the palette, then `ESC` to close it, then `k` to go one line up, `k` acts correctly.

So there should be a problem there too. I know that I'm in a borderline case with a weird keyboard layout and I don't really need `:` to open the palette, so if you don't want to investigate this I'll understand :-)

**Comment by StreakyCobra** [comment]
Both issues seems to be solved in the last release, so closing this issue. Thanks for all the work on this plugin, it's amazing.
