### ISSUE TITLE
After update to 0.4.9, I have several issues with visual mode and backspace

### ISSUE THREAD

**Issue by corretge** [VSCodeVim/Vim#1164]
### What did you do?

Update the extension, and work as usual.

### What did you expect to happen?
Works fine

### What happened instead?
- When I enter in Visual Mode, Instead a blue block, sometimes I had a darkgrey cursor at first line. All operations has this one line scope.
- Sometimes backspace doesn't works well.

### Technical details:

* VSCode Version: Versió 1.8.0 (1.8.0) 2016-12-13T17:36:16.206Z
* VsCodeVim Version: 0.4.9
* OS: Mac OSX

**Comment by xconverge** [comment]
Backspace in what mode, insert?

**Comment by xconverge** [comment]
And can you post a screenshot of your visual mode? I think the highlight color is based on the theme you have loaded

**Comment by johnfn** [comment]
Can you explain what you mean by backspace not working well please?

**Comment by samirotiv** [comment]
When the line is empty, and I hit backspace, the line does not get deleted.

**Comment by xconverge** [comment]
Are you in insert mode? <bs> works for me... Is this reproducible for you?

**Comment by corretge** [comment]
Sorry! I changed job and computer. After reinstall all from scratch with vimcode 0.4.10 all works fine.

But if you can reproduce:
- Backspace in insert mode.
- Blue is the background color of a selected block. 
- DarkGrey icon (wow! I meant cursor) is the color of the cursor at last position of the block when you enter in visual mode. The problem was that I was not able to have blocks more than one line.
