### ISSUE TITLE
Select Inner '(' not working properly

### ISSUE THREAD

**Issue by SrMordred** [VSCodeVim/Vim#1165]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.
-----
```
func_callback(()=>{
//cursor here
});
```
press _vi(_ 
It selected from "()" to "here"  instead of to "}"

* VSCode Version:1.8
* VsCodeVim Version: 0.4.9
* OS: Window 10

**Comment by gugahoa** [comment]
It's the same issue that's causing #1160. The selection ends one char too short.

**Comment by xconverge** [comment]
Similar to #1023 the fix should be in a similar area

I will take a look

**Comment by xconverge** [comment]
I broke this in #1013
