### ISSUE TITLE
Remap : commands

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1166]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

Something like this:

```
 "vim.otherModesKeyBindings": [{
      "before": ["ctrl+n"],
      "after": [":nohlsearch"]
    }]
```

**Comment by xconverge** [comment]
@Awpteamoose can you let me know what command you would want to remap to make the plugin usable? I just want to make sure it is covered when this gets implemented

**Comment by xream** [comment]
Can we remap easymotion commands?

**Comment by Awpteamoose** [comment]
This is what I use to clear the highlights off search results:
```vimscript
noremap <silent><esc> <esc>:noh<CR><esc>
```

**Comment by xconverge** [comment]
@xream no that is not the scope of this ticket This ticket is just to remap commands that use the vim command line :
