### ISSUE TITLE
Fat cursor during Normal mode

### ISSUE THREAD

**Issue by BKaraargirov** [VSCodeVim/Vim#117]
It is possible for my VS code to be bugged, but when I am in Normal mode the cursor is the same as is in insertion mode. I think its quite more comfortable when there is a visual distinction in the cursor as well, and not only in the information bar at the bottom.
It would be nice to have this feature - if not by default, at least in the configuration level.

**Comment by jpoon** [comment]
Thanks. We are tracking that issue with https://github.com/VSCodeVim/Vim/issues/19
