### ISSUE TITLE
<2 doesn't unindents one level, not two indent levels

### ISSUE THREAD

**Issue by iivvoo** [VSCodeVim/Vim#1170]
### What did you do?

Make a selection on a block that's indentent multiple times (e.g. 16 spaces with a indentlevel of 4 spaces)
Type <2 to unindent the block 8 spaces

### What did you expect to happen?

The block to unindent 2 levels, 8 spaces, resulting in a two level indent

### What happened instead?

Only one level was unindented. As if < was typed. Any number seems to be ignored.

### Technical details:

* VSCode Version: 1.8.0
* VsCodeVim Version: 0.4.9
* OS: Ubuntu 16.04 64bit

**Comment by xconverge** [comment]
Good catch!
