### ISSUE TITLE
Go to definition (gd) does not update vimstate cursor correctly if you jump to another file 

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#1171]
Since each file has it's own modeHandler, if you do gd and it goes to a different file that already has a mode handler, then press j or k, it will jump away to the files previous modeHandler position.

If the file you are jumping to does NOT already have a modehandler then it will work fine, but this can only happen once for that  file.

Relates to #1162, #1081, etc

**Comment by johnfn** [comment]
Yeah, however I don't think this is a consequence of separate mode handlers. After all, mode handlers should handle a different position per file, so that when you c-w h c-w l it remembers the old one.

**Comment by xconverge** [comment]
ah yea it is a selection changed type thing then?

**Comment by johnfn** [comment]
Precisely. It's a particularly annoying thing because when you do gd, you need to somehow let VSCodeVim know not to update the cursor on the current mode handler but instead to wait for the next mode handler and then update the cursor on that one. That's why it's so annoying.

**Comment by johnfn** [comment]
Woot.
