### ISSUE TITLE
VSCodeVim doesn't switch to block cursor in normal mode consistently.

### ISSUE THREAD

**Issue by Chillee** [VSCodeVim/Vim#1173]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Occasionally, VSCodeVim has some issues with switching back to the block cursor. I'm only able to consistently reproduce it in the settings.json file, but I think it might happen elsewhere as well.

#Steps: 
Open the settings.json file for VSCode. Under the Default Settings pane, choose to edit the "files.autoSave" option, and select one of the 4 popup options.
![image](https://cloud.githubusercontent.com/assets/6355099/21282973/1d030d26-c3c9-11e6-8945-2ed0c54a254a.png)

Now, notice that although I'm in Normal Mode, the cursor is a line instead of a block.
![image](https://cloud.githubusercontent.com/assets/6355099/21282992/4583e568-c3c9-11e6-80ad-84ebc20d426d.png)

Entering insert mode and then exiting back out to normal mode fixes the cursor temporarily, but switching to a different file and then back to the settings.json file causes the same issue again.

However, deleting the line added by editing files.autoSave (and the comma) fixes the entire issue.

Although I'm only able to consistently reproduce this issue in the settings.json file, I have ran into this issue on other files as well.

### Technical details:

* VSCode Version: 0.4.9
* VsCodeVim Version: 1.8.0
* OS: Linux Mint 17.2

**Comment by xconverge** [comment]
Can you test on VsCode insiders? I was about to report an issue to the vscode github, but I can't reproduce this on insider version, only with 1.8.0 stable...

**Comment by xconverge** [comment]
related https://github.com/Microsoft/vscode/issues/17472

**Comment by Chillee** [comment]
I'm able to reproduce the issue on the Insiders release as well.

**Comment by johnfn** [comment]
Very strange, I can't reproduce this.

**Comment by xconverge** [comment]
also related 1159

**Comment by johnfn** [comment]
Okay, managed to repro this one immediately when I upgraded Visual Studio Code. Clearly a VSC bug 😉
