### ISSUE TITLE
Test runner

### ISSUE THREAD

**Issue by corymickelson** [VSCodeVim/Vim#118]
Anyone know how to properly test motion commands as in test/motion.test.ts? I see the comment in the gulp file that tests with dependencies on vscode do not run, but is there a way to get this to work? Would be nice to have all tests run before merging PR

**Comment by corymickelson** [comment]
Never mind, I am a couple commits behind. See testing has already been addressed, closing comment.

**Comment by jpoon** [comment]
You can launch tests using VS Code: https://code.visualstudio.com/docs/extensions/testing-extensions. Tests are also run on Travis (CI). The gulp command that you are referring to has been removed.
