### ISSUE TITLE
[Linux] Print info/warning if xclip not installed and useSystemClipboard is true

### ISSUE THREAD

**Issue by jnachtigall** [VSCodeVim/Vim#1180]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I use [Visual Studio Code Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) on Windows and Linux. I have `useSystemClipboard` set to `true`. Took me quite some time to find out that copy'n'paste did not work on Linux whereas it worked on Windows. I saw the documentation in the README.md: `Note: Linux users must have xclip installed`

### What did you expect to happen?
There should be an info/warning popup under Linux if `useSystemClipboard` is enabled and xclip is not installed. Like: 

```
Please install xclip. 
You have enabled useSystemClipboard in your settings which requires the xclip executable on Linux
```

### What happened instead?
Nothing. I only found out by accident instead of being told proactively what to do.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.2
* OS: Ubuntu 16.04 (Linux)

**Comment by johnfn** [comment]
Truth. Honestly, we should be spamming the user with all sorts of dialogs about the stuff they're doing. 😁
