### ISSUE TITLE
map 'gf' to fn+f12 (go to declaration)

### ISSUE THREAD

**Issue by sathishvj** [VSCodeVim/Vim#1184]
### What did you do?
normal mode: gf

### What did you expect to happen?
Equivalent of 'fn+f12' on my mac.
I need to press 'fn' to access the function keys on my map

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.9
* OS: mac

**Comment by xconverge** [comment]
Can you use 'gd' ?

**Comment by sathishvj** [comment]
That works!  But how could I have found that out on my own?  Is there a doc of actions, especially the different ones?

**Comment by xconverge** [comment]
Between the readme and the the roadmap you can see what is implemented

https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md

gf is go to file under cursor

Also, you could do something like this if we don't support it yet! (rebindings have some documentation in the README)

 "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["g", "f"],
            "after": [],
            "commands": [
                {
                    "command": "editor.action.goToDeclaration",
                    "args": []
                }
            ]
        }
    ]

**Comment by sathishvj** [comment]
awesomeness. thank you!

**Comment by johnfn** [comment]
gd is a Vim action! It means go to definition.
