### ISSUE TITLE
`%` work wrong with comment inside

### ISSUE THREAD

**Issue by poppinlp** [VSCodeVim/Vim#1192]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Press `%` at a `{`.

### What did you expect to happen?

Cursor goto the paired `}`.

### What happened instead?

If there's comment inside which includes`}` or `{`, the cursor will get wrong place.
It looks like the vim extension treats `}` or `{` in comments as code.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: OS X EI Capitan 10.11.6

**Comment by johnfn** [comment]
Can you please provide the full text that caused `%` to fail?

**Comment by johnfn** [comment]
Nevermind, you're referring to this, which is a known bug: https://github.com/VSCodeVim/Vim/issues/651

**Comment by poppinlp** [comment]
Yep, that's my trouble...and that really bother using sometimes...
Wish for a fix. THX.

**Comment by johnfn** [comment]
@poppinlp PRs are welcome! :) 

It's a bit of an annoying one as you actually need to parse the code in order to tell what is to be treated as a matching symbol and what is not...
