### ISSUE TITLE
'caw' at first word on line

### ISSUE THREAD

**Issue by dpbackes** [VSCodeVim/Vim#1193]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In normal mode with the cursor at the beginning of the first word of a line, pressed 'caw'

### What did you expect to happen?

The first word would be deleted and insert mode would be entered with my cursor in the same position it started in.

### What happened instead?

All characters between position 1 and the end of the first word on the line are deleted. Insert mode is entered starting on position 1 of the line. See gif below:

![](http://g.recordit.co/UeDuA56zWO.gif)

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: Mac OSX

**Comment by dpbackes** [comment]
I'll add that it appears having the dot after the word is also significant.

I've done some digging and it appears to be that it's hitting [this line](https://github.com/VSCodeVim/Vim/blob/78c03109d99e0d90f7a8752c4a3cd338bcfcecb0/src/actions/actions.ts#L4989) instead of going into the `else`. Getting rid of the conditional and always executing `start = position.getWordLeft(true);` fixes the issue but causes problems with `daw` and `vawd` on words that have trailing spaces.

I'll keep looking as I have time but maybe someone with a better understanding of what's going on will be able to recognize the issue more quickly.

**Comment by johnfn** [comment]
Weird bug; the dot is significant like you suggested.
