### ISSUE TITLE
Setting vim.leader is not taking effect.

### ISSUE THREAD

**Issue by elithrar** [VSCodeVim/Vim#1194]
### What did you do?

Set `"vim.leader": "<space>",`

```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Fira Mono",
    "editor.fontSize": 14,
    "go.gopath": "/Users/matt/.go",
    "vim.useSystemClipboard": true,
    "vim.useCtrlKeys": true,
    "vim.useSolidBlockCursor": true,
    "vim.easymotion": true,
    "vim.incsearch": true,
    "vim.leader": "<space>",
    "editor.cursorBlinking": "solid"
}
```

### What did you expect to happen?

The spacebar to work as the leader (and to show in the status bar below).

### What happened instead?

Nothing. No <leader> indication in the status bar. Unsetting it—to allow the default—seems to break the default as well, until reloading the window.

### Technical details:

* VSCode Version: Version 1.8.1 (1.8.1)
* VsCodeVim Version: *[please ensure you are on the latest]* 0.4.10
* OS: macOS 10.12.1 (Sierra)

**Comment by xconverge** [comment]
I assumed you restarted vscode after changing this?

**Comment by litemerafrukt** [comment]
Exact same problem for me (vim.leader is not taking effect). (I have reloaded vscode to see if changes take effect)

#### Tech Spec:
* VSCode: 1.8.1
* VsCodeVim: 0.4.10
* OS: os x 10.11.6 El Capitan

**Comment by elithrar** [comment]
> I assumed you restarted vscode after changing this?

Restarting (proper, not just a window reload) seemingly fixed it on one machine. My other Mac, with the same (synced) settings.json and keybindings.json, does not recognize <space> as vim.leader.

**Comment by xconverge** [comment]
Great, we are not currently setting without a restart, I think there might be an issue for that already

**Comment by smunchkiss** [comment]
ee428b0eead68bf0fb99ab5fdc4439be227b6281
