### ISSUE TITLE
di` does not delete between `

### ISSUE THREAD

**Issue by sathishvj** [VSCodeVim/Vim#1198]
### What did you do?
di`

### What did you expect to happen?
cut characters between `

### What happened instead?
nothing

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: mac

**Comment by xconverge** [comment]
Can you add the full line of text you are trying and where the cursor is with |

I can do t|est`test`, and pressing di` I get test`|`

**Comment by sathishvj** [comment]
Ok, apparently it is one specific situation.  I really thought I'd tested it under other text, but I think I'm definitely wrong.  

text with | as cursor, in normal mode: `abc|def\`
press: di`
expected change: `|`
seen change: `abc|def\`
i.e. no change

When there is a \ (backslash) before the ending ` (backquote), it does not work.  I checked on vim 7.4 and the behavior is the same; so there is parity there.  

I still believe it is a bug (in both places), but if you think not, you may close it.

**Comment by xconverge** [comment]
can you try and edit your comment to avoid the github auto formatting, it uses that character to denote code sections :)

This is true for all characters actually " > ) } etc.... I fear that this would have unintended consequences that diverge from how vim works and someone would open an issue at a later point, so personally I think it should be closed

There is a comment in our code that says this which leads me to believe it is for a reason/to match vim:
```    // Search forwards from start, looking for a non-escaped char```

**Comment by johnfn** [comment]
Thanks for confirming, @xconverge. The expected behavior of di` is to ignore escaped backticks in Vim.
