### ISSUE TITLE
EasyMotion not usable in visual mode

### ISSUE THREAD

**Issue by Toadsworth** [VSCodeVim/Vim#1199]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`v<leader><leader>whd`

### What did you expect to happen?

1. Going into visual mode.
2. Selecting from my cursor till the word with the easymotion highlight of character h.
3. Deleting the entire selection.

### What happened instead?
The leader key does nothing after I'm in visual mode. This probably means EasyMotion doesn't work in visual mode. I didn't get it working with messing arround in settins.json.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: Ubuntu 16.10

**Comment by iliekturtles** [comment]
This may be a leader issue rather than specific to EasyMotion. I have some `"vim.otherModesKeyBindingsNonRecursive"` bindings that work find in NORMAL MODE but the bindings with `<leader>` fail in VISUAL MODE and VISUAL LINE MODE:

```
{ "before": ["d"], "after": ["\"", "1", "d"] },
{ "before": ["<leader>", "d"], "after": ["d"] },
```

**Comment by xconverge** [comment]
this is a little complicated since it needs to adjust visual selections properly and return to the correct  visual mode (the previous visual state is stored currently for use with gv, however, it needs to be restored then adjusted with the new easymotion position)

**Comment by hughfenghen** [comment]
If you modify the default shortcut of EasyMotion, then you also need to modify the shortcut key in visual mode.
```js
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "s"
      ],
      "after": [
        "<leader>",
        "<leader>",
        "s"
      ]
    }
  ],
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": [
        "s"
      ],
      "after": [
        "<leader>",
        "<leader>",
        "s"
      ]
    }
  ],
```

**Comment by hanezu** [comment]
> If you modify the default shortcut of EasyMotion, then you also need to modify the shortcut key in visual mode.
It works! Thanks.
