### ISSUE TITLE
Installation error - self signed certitificate

### ISSUE THREAD

**Issue by unix-bigot** [VSCodeVim/Vim#1203]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.
-----
### What did you do?
clicked the install button
### What did you expect to happen?
installation
### What happened instead?
error self signed certificate in certificate chain
### Technical details:
per  joaomoreno  in this forum https://github.com/Microsoft/vscode/issues/13171
direction is :  If an extension reaches out to the Internet but fails to do so due to a proxy... you'll have to file an issue with that extension.
* VSCode Version: 1.8.1
* VsCodeVim Version: *[please ensure you are on the latest]* 0.4.10
* OS: windows 7 64 bit

**Comment by xconverge** [comment]
Is this the vscodevim extension? Can you disable all other extensions and try with only vscodevim? I am not sure where the specific trace I should be looking at that points to this extension is...

**Comment by unix-bigot** [comment]
Yes, it is. There are no other extensions. This is my initial install of vscode and my first attempt at installing an extension listed in the extension section within the vscode app.

**Comment by johnfn** [comment]
Sorry, there's no way that this has anything to do with VSCodeVim!

**Comment by jpoon** [comment]
VSCode downloads vim extension from their marketplace. The extension itself doesn't reach out to the internet for anything. 

If you are still seeing this issue, please re-open; but I can't see how this is caused by the vim extension....
