### ISSUE TITLE
modifies key bindings but not reflected on UI

### ISSUE THREAD

**Issue by Jimmy-Z** [VSCodeVim/Vim#1204]
for example in the menu
![image](https://cloud.githubusercontent.com/assets/85773/21581952/65a938ce-d081-11e6-9d3a-f6d819daae81.png)
or the command line
![image](https://cloud.githubusercontent.com/assets/85773/21581957/9079d4a0-d081-11e6-918b-707ea95eae0f.png)
Ctrl-T is not working anymore but still shown, close this if I should fire this to vscode instead

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: Windows 10

**Comment by johnfn** [comment]
This does in fact sound like a vscode bug!
