### ISSUE TITLE
one file two pane is unusable, cursor reset to 

### ISSUE THREAD

**Issue by Jimmy-Z** [VSCodeVim/Vim#1205]
### What did you do?

split a file view to two pane, edit two positions of the file

### What did you expect to happen?

two pane should act independently

### What happened instead?

sometimes the cursor in active pane will reset to where the cursor is in the inactive pane, sorry I don't know how to trigger this reliably, it happens sometime.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: Windows 10
* extensions enabled: this and eslint.

**Comment by johnfn** [comment]
Yeah, this is probably our biggest current bug, because there's a lot of weird behavior that goes on when you have the same file open in 2 panels.

**Comment by tom5760** [comment]
A pretty easy way to reproduce this:
1. Open a new window, type some lines in the new untitled file.
2. Type `:vs` to open the same file into a second pane.
3. Move the cursors to two different places in both panes.
3. Hit `d` three times.  The first two will delete a line, and the third `d` will move the cursor to where it is in the other pane.

**Comment by Chillee** [comment]
The behavior here seems to have been fixed?

**Comment by johnfn** [comment]
Yeah this is an old one that's been fixed for a while. :)
