### ISSUE TITLE
Visual Block Mode: Tab does not indent

### ISSUE THREAD

**Issue by elithrar** [VSCodeVim/Vim#1210]
### What did you do?

Highlighted a column of text in Visual Block mode - e.g.

![screen shot 2017-01-02 at 10 24 44 am](https://cloud.githubusercontent.com/assets/18544/21594290/b3bf44aa-d0d5-11e6-899a-d2cbad54b311.png)

(Ctrl+V + jjjj + tab - incidentally I'd expect 4j to work too, but it doesn't)

### What did you expect to happen?

All rows to be indented.

### What happened instead?

Only indented the first row.

Double-tapping space works.

### Technical details:

* VSCode Version: Version 1.8.1 (1.8.1)
* VsCodeVim Version: 0.4.10
* OS: macOS Sierra - 10.12.2

**Comment by xconverge** [comment]
This is not how Vim works, > is the command you are looking for

**Comment by elithrar** [comment]
You're right - I'd gotten so used to neovim/vim-sensible (which looks to correct this).

Given that - is there a way to replicate in VS Code?

**Comment by johnfn** [comment]
You could probably use our remapping feature to remap `<tab>` to something like `i<tab>`.

**Comment by krinoid** [comment]
FYI, native VSC shortcuts for indent are `⌘+]` and `⌘+[` (`CTRL` instead of `CMD` on Windows/Linux) and it works in visual mode.

**Comment by jbiskofski** [comment]
Until recently I was using Atom with VIM mode and the tab, shift+tab shortcuts indented/outdented as I expected. If you want this behavior you can add this to your vscode keybindings.json

```
 {
     "key": "tab",
     "command": "tab",
     "when": "editorTextFocus && !editorTabMovesFocus"
 },
 {
     "key": "shift+tab",
     "command": "outdent",
     "when": "editorTextFocus && !editorTabMovesFocus"
 }
```
