### ISSUE TITLE
Configure automatic line wrapping?

### ISSUE THREAD

**Issue by jmreicha** [VSCodeVim/Vim#1211]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
### What did you do?

Go to the end of a line and press the right arrow key (or l) in normal mode.

### What did you expect to happen?

By default I don't expect the line wrapping to work but a config option to enable whichwrap style behavior would be great.

### What happened instead?

Automatically move up or down a line with arrow keys in normal mode, if configured.

### Technical details:

* VSCode Version: 1.8
* VsCodeVim Version: latest
* OS:  Win 10

**Comment by xconverge** [comment]
are you referring to this?

http://vim.wikia.com/wiki/Automatically_wrap_left_and_right

**Comment by jmreicha** [comment]
@xconverge Really sorry I missed your comment, yes that is exactly what I'm looking for.

**Comment by Drakulix** [comment]
I would like to tackle this an provide a pull request, if somebody could point me into the right direction. The original patchset is not linked in #839.

**Comment by dtinth** [comment]
The workaround that I am using is to disable Vim extension’s handling of Left and Right keys when inside Insert Mode:

```js
{ "key": "left",                  "command": "cursorLeft",
                                     "when": "textInputFocus" },
{ "key": "right",                 "command": "cursorRight",
                                     "when": "textInputFocus" },
{ "key": "left",                  "command": "extension.vim_left",
                                     "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'" },
{ "key": "right",                 "command": "extension.vim_right",
									 "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'" },
```

**Comment by brtsos** [comment]
I added a whichwrap option to ideavim plugin. 

https://github.com/JetBrains/ideavim/pull/168

**Comment by Ahsan40** [comment]
> 
> 
> The workaround that I am using is to disable Vim extension’s handling of Left and Right keys when inside Insert Mode:
> 
> ```js
> { "key": "left",                  "command": "cursorLeft",
>                                      "when": "textInputFocus" },
> { "key": "right",                 "command": "cursorRight",
>                                      "when": "textInputFocus" },
> { "key": "left",                  "command": "extension.vim_left",
>                                      "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'" },
> { "key": "right",                 "command": "extension.vim_right",
> 									 "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'" },
> ```

Hi, it's late but I need the configuration you mentioned. But don't know where to paste. I tried to add this in `settings.json` but didn't work. Is there any way to add this config to `settings.json`?

**Comment by J-Fields** [comment]
No workarounds should be necessary - just configure [whichwrap](https://vimhelp.org/options.txt.html#%27whichwrap%27) to your liking

**Comment by yongming-qin** [comment]
> > The workaround that I am using is to disable Vim extension’s handling of Left and Right keys when inside Insert Mode:
> > ```js
> > { "key": "left",                  "command": "cursorLeft",
> >                                      "when": "textInputFocus" },
> > { "key": "right",                 "command": "cursorRight",
> >                                      "when": "textInputFocus" },
> > { "key": "left",                  "command": "extension.vim_left",
> >                                      "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'" },
> > { "key": "right",                 "command": "extension.vim_right",
> > 									 "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'" },
> > ```
> 
> Hi, it's late but I need the configuration you mentioned. But don't know where to paste. I tried to add this in `settings.json` but didn't work. Is there any way to add this config to `settings.json`?

The text should be added in settings.json. But it should be added in the template from the Vim extension page. For example of the insert mode,
```
"vim.insertModeKeyBindings":[
THE TEXT
]
```
