### ISSUE TITLE
List recent commands in command bar

### ISSUE THREAD

**Issue by jmreicha** [VSCodeVim/Vim#1212]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Type `:` to pull open command bar

### What did you expect to happen?

It would be nice to have recently typed commands available in the command bar

### What happened instead?

No previous commands are listed

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: latest
* OS: Win 10

**Comment by johnfn** [comment]
Oh, this is clever!

**Comment by xconverge** [comment]
I am going to try and do this one today, should be easy and cool :)

**Comment by xconverge** [comment]
xconverge is sad, can't be done right now

https://github.com/Microsoft/vscode/issues/23633

**Comment by xconverge** [comment]
related #779

**Comment by jpoon** [comment]
Closing this in favor of #779.
