### ISSUE TITLE
Press backspace to remove the last Chinese character,however it remove the last but one

### ISSUE THREAD

**Issue by sharkrice** [VSCodeVim/Vim#1213]
### What did you do?

backspace

### What did you expect to happen?

remove the last Chinese character

### What happened instead?

remove the last but one Chinese character

[Imgur](http://i.imgur.com/CYYKf7l.gifv)

### Technical details:
* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: win10

**Comment by Tyzual** [comment]
same problem
VSCode version: 1.9.1
VsCodeVim version: 0.5.2
OS: macOS 10.12.3

**Comment by nshen** [comment]
same win7

**Comment by Chillee** [comment]
This seems like it's fixed to me. I'm gonna close this issue. Please report it if it's still an issue.

**Comment by jpoon** [comment]
Seems fixed?
