### ISSUE TITLE
insert after paste-before broken

### ISSUE THREAD

**Issue by elijahdorman** [VSCodeVim/Vim#1215]
Steps to reproduce:

Example text could be `some random words`

1 go to first word and `yiw`
2 go to BOL with `^`
3 paste word before with `P`
4 cursor is now over the `e` of the pasted `some` as expected (`som|esome`)
5 `i` to insert after, but we wind up at the `s` as if we had done `a` instead (`some|some`) 

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: OSX 10.11.6

**Comment by johnfn** [comment]
I can't reproduce this. I get up to step 4 just fine, but when I press i, it works as expected.

**Comment by foxbunny** [comment]
Can't reproduce on Win 10 64-bit, VS Code 1.8.1.

**Comment by Chillee** [comment]
I can't reproduce on VSCode 1.12, vscodevim 0.7.0 either.
