### ISSUE TITLE
Search/replace constrained to a visual block selection is not constrained

### ISSUE THREAD

**Issue by benlakey** [VSCodeVim/Vim#1219]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Given this text:

```
foo first
foo second
bar
foo third
```

1. Use shift-v and down arrow to visual-block select the first 2 lines with "foo" in them.
2. Enter command:   `:%s/foo/bar`

### What did you expect to happen?

The search/replace should have been constrained to only the 2 lines visually selected. The last line with `foo` in it should not have been altered.

### What happened instead?

All instances of `foo` in the file were replaced. The search/replace was not constrained to the visual selection.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
That doesn't seem correct to me. The command to constrain it to the 2 lines you've selected is `'<,'>s/selection/foo/`, not `:%s/foo/bar/`.

**Comment by benlakey** [comment]
Correct, but in vim if you start entering a command while visually selected it will insert the prefixed `'<,'>` for you. Sorry if that wasn't clear in the original post.

**Comment by johnfn** [comment]
When I press : in visual line mode, I see `'<,'>`. (Unfortunately it starts out selected. That's tracked by #1207.)

**Comment by benlakey** [comment]
Odd that I don't see that same behavior. Is it possibly something in master that isn't in 0.4.10 ?

**Comment by johnfn** [comment]
Nah, I run 0.4.10.

Do you see it visual mode when using `:`?

**Comment by benlakey** [comment]
Ah I see the issue. It is indeed there but because I start typing so quickly after hitting `:` I never see the pre-selected text you mentioned above, making it seem like it wasn't there. My issue is indeed the same as #1207 then. I'll go ahead and close this.

**Comment by johnfn** [comment]
:) cool. Yeah, that is an annoying bug. :/

**Comment by benlakey** [comment]
For anyone who found this issue and was similarly tripped up by the above stuff, check out the new neovim command integration bits:

https://github.com/VSCodeVim/Vim#neovim-integration

**Comment by alk-mandrianarijaona** [comment]
Hello, I still have an issue searching text inside visual mode. After selecting a block, I type `:` and `'<,'>` is displayed. I then type a search query like `'<,'>/foo` and `Enter` but nothing happens.
