### ISSUE TITLE
Support camelCaseMotion Script

### ISSUE THREAD

**Issue by JKillian** [VSCodeVim/Vim#1220]
As someone who used to use VIM to do a lot of TypeScript work, the VIM camelCaseMotion script (either [this version](https://github.com/bkad/CamelCaseMotion) or [this version](https://github.com/vim-scripts/camelcasemotion)) was very useful. Being able to easily move through and change identifiers in a way that corresponds with how they're structured is really helpful. I'd love it if VSCodeVim integrated support for something similar to allow for camelcase motions!

**Comment by johnfn** [comment]
One thing you can try is to define `iskeyword` in your settings.json to be like

`    "vim.iskeyword": "/\\()\"':,.;<>~!@#$%^&*|+=[]{}`?-QWERTYUIOPASDFGHJKLZXCVBNM",`

(e.g. the original setting plus all capital letters.) This will make Vim treat capital letters as word _separators_ though, which may not be what you want.
