### ISSUE TITLE
Pressing ctrl+k ctrl+s does not execute default behavior

### ISSUE THREAD

**Issue by jrob** [VSCodeVim/Vim#1221]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Pressed `ctrl+k ctrl+s`.

### What did you expect to happen?

I expected `workbench.action.openGlobalKeybindings` to execute as per the defaults.

### What happened instead?

The command `workbench.action.files.save` which is mapped to `ctrl+s` is executed.

### Workaround

Add the default mapping for `ctrl+k ctrl+s` (see below) to the end of your user keybindings.json.

```json
{ "key": "ctrl+k ctrl+s",         "command": "workbench.action.openGlobalKeybindings" }
```
### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: Windows 10

**Comment by rebornix** [comment]
Can you try disable Vim extension and see if Code has the same issue? AFAIK, we don't map any command to `ctrl+s`. cc @xconverge

**Comment by jrob** [comment]
With a fresh clean install of both vscode and the extension, the keybinding windows is not opened as expected. After disabling vim the key bindings are opened as expected.

**Comment by xconverge** [comment]
[Reference](https://github.com/VSCodeVim/Vim#windows-setup)

We grab ctrl+k, one way you can fix this is with the handleKeys setting

```
    "vim.handleKeys": {
        "<C-k>": false
    }
```

For reference, on my windows machine I use this for some other neat reasons:

```
    "vim.handleKeys": {
        "<C-f>": false,
        "<C-w>": false,
        "<C-n>": false
    }
```

Please feel free to reopen this if this does not help you solve the problem!
