### ISSUE TITLE
I can't get the ZZ example on the main page to work with current VS Code.

### ISSUE THREAD

**Issue by cmaughan** [VSCodeVim/Vim#1222]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I added the example from the readme to handle ZZ

### What did you expect to happen?

ZZ would save and close the file

### What happened instead?

Nothing.  Other commands, such as replacing jk for <ESC> work fine.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: Latest
* OS: Win 10

**Comment by johnfn** [comment]
You're right, it's not working currently. :/

**Comment by Nogbit** [comment]
Missing buffers so much and all the commands to go with them....would love this to work to close files from the keyboard.

**Comment by alexriedl** [comment]
A possible alternative until this gets fixed is:
`    { "key": "shift+z shift+z", "command": "workbench.action.closeActiveEditor",
                                  "when": "editorTextFocus && vim.mode == 'Normal'" },`

Only difference is it does not save the file before trying to close it.

**Comment by xconverge** [comment]
@johnfn  @jpoon  this can be closed now due to #1145

**Comment by jpoon** [comment]
Mmmk. Thanks!
