### ISSUE TITLE
Unavailable to yank the asian characters.

### ISSUE THREAD

**Issue by exawon** [VSCodeVim/Vim#1223]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

<kbd>yy</kbd> and <kbd>p</kbd> in the line included the asian characters.

### What did you expect to happen?

To be duplicated the line.

### What happened instead?

Inserted an empty line below the line.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: Mac OS Sierra

**Comment by johnfn** [comment]
Can you provide an example line that doesn't work, please?

**Comment by exawon** [comment]
Press <kbd>yy</kbd> and <kbd>p</kbd> on `This is 한글.`

**Comment by jpoon** [comment]
This works fine for me? I'm on VSCodeVim 0.5.2.

Closing this issue for now. Feel free to re-open if you are still seeing this error.

**Comment by exawon** [comment]
Not working for me with VSCodeVim 0.5.3 + VSCode 1.8.1.

**Comment by jpoon** [comment]
Still seems fine to me. Feel free to re-open if that's not the case.
