### ISSUE TITLE
sectional search and replace

### ISSUE THREAD

**Issue by dmgudeman** [VSCodeVim/Vim#1225]
### What did you do?
I highlighted a section of code in visual mode

:'<'>%s/name/email/   
:'<,'>%s/name/email/g

### What did you expect to happen?
the "name" text in the section would be replace with "email"
### What happened instead?
nothing
### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: macOS Sierra 10.12.2

**Comment by johnfn** [comment]
You probably want the following:

`:'<'>s/name/email/`

The `%` is a range which means "entire document". `'<'>` is a range which means "my selection". :)
