### ISSUE TITLE
matching brace not deleted on backspace or ex:`x`

### ISSUE THREAD

**Issue by Walt-D-Cat** [VSCodeVim/Vim#1228]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do? 
Type any of the following keys <, (, {,  [ and the backspace or escape then `x`

Put the exact keys you pressed.

### What did you expect to happen?
The first brace character places a matching closing brace, without the extension, removing the left brace removes the closing brace if there are no intervening characters (including space). 
### What happened instead?
The closing brace remains.
### Technical details:

* VSCode Version: 0.4.10
* VsCodeVim Version: *[please ensure you are on the latest]* 1.7.1
* OS: windows 10 & ubuntu 16.10

**Comment by johnfn** [comment]
I don't think that `x` should remove the other matching key. It certainly doesn't on my copy of Vim.

Backspace should though!

**Comment by Walt-D-Cat** [comment]
Fair enough ... the `x` is behaviour handled by an extension in my vim, and it's mostly backspace (especially when miss-typing between `[` and `{` ).

**Comment by xconverge** [comment]
@johnfn this can be closed due to #1267

**Comment by xconverge** [comment]
@johnfn @jasonpoon
