### ISSUE TITLE
Ctrl+C does not put you in command mode

### ISSUE THREAD

**Issue by segmentationfaulter** [VSCodeVim/Vim#123]
In vim you can use Ctrl+C as the key combination to switch to command mode from any other mode, but it is not supported with your extension, please support it. Thank you

**Comment by lf94** [comment]
+1 this is a major feature for me. It pains me to have to use ESC all the time when Ctrl+C is an easier reach.

**Comment by AntonAderum** [comment]
This is an easy thing to implement I would guess, but maybe it should have a setting attached to it so that people can keep the "Ctrl+c / Ctrl-v" functionality if they want to?

**Comment by markrendle** [comment]
I'd have a hard time if Ctrl+C suddenly stopped being Copy.

**Comment by johnfn** [comment]
If you're using Vim mode, you definitely should not be using ctrl-c as copy. That's what `y` is for!

**Comment by jpoon** [comment]
As per Vim docs:

```
CTRL-C          Quit insert mode, go back to Normal mode.  Do not check for
                abbreviations.  Does not trigger the |InsertLeave| autocommand
                event.
```

```
CTRL-C                  Interrupt current (search) command.  Use CTRL-Break on
                        MS-DOS |dos-CTRL-Break|.
                        In Normal mode, any pending command is aborted.
```

**Comment by AntonAderum** [comment]
It should be default to abort, however I think it's a good idea to at least give the option to the user to disable ctrl-c to be abort. I think can add value to some users.

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/issues/139
