### ISSUE TITLE
Toggle activity bar visibility will change `normal` mode to `insert` mode

### ISSUE THREAD

**Issue by spacegoing** [VSCodeVim/Vim#1230]
Whenever I toggle activity bar visibility, the editor will change `normal` mode to `insert` mode. There are also other events will trigger this behavior like changing the default setting.

**Comment by johnfn** [comment]
What do you mean by "toggle activity bar visibility"?

**Comment by spacegoing** [comment]
@johnfn I use `cmd+shift+p` to open command palette and executed `toggle activity bar visibility` command

**Comment by johnfn** [comment]
Ah, I see. That doesn't actually have any effect on the mode for me...

Could you share your settings.json please?

**Comment by spacegoing** [comment]
@johnfn Many thanks for your help. You can see my config at https://github.com/spacegoing/GitConfig/tree/master/vscode
