### ISSUE TITLE
Auto-deletion of brackets

### ISSUE THREAD

**Issue by sebwild** [VSCodeVim/Vim#1231]
Hi, 
VIM plugin breaks standard VSCODE feature that automatically deletes closing bracket, paranthesis, etc. when opening one is deleted. 
Can we implement a setting that lets user choose whether auto-deletion of brackets should still be enabled?
Thanks,
Seb

**Comment by sebwild** [comment]
![as-is](https://cloud.githubusercontent.com/assets/12811637/22044856/18deb102-dd17-11e6-8b3c-9e8973ef98f0.gif)

as is...

**Comment by sebwild** [comment]
![to-be](https://cloud.githubusercontent.com/assets/12811637/22044860/21a80932-dd17-11e6-8bed-b17a6749cc6b.gif)

option for to be..

**Comment by emckay** [comment]
Did you find a way to fix this? `Ctrl` + `backspace` will delete both brackets, but I'd prefer to not have to use `ctrl`.

**Comment by xconverge** [comment]
@johnfn this can be closed

**Comment by johnfn** [comment]
Thanks @xconverge :)
