### ISSUE TITLE
tag movement commands are single line only

### ISSUE THREAD

**Issue by jimmymain** [VSCodeVim/Vim#1232]
### What did you do?
Attempted to yank/copy/delete inside a tag. 
```
<outer>
    <tag>data</tag>
</outer>
```
keys pressed: `dit`

### What did you expect to happen?
when the cursor is placed at the closing `>` of `<outer>` in gvim (line 1) the contents of outer are completely removed. In other words the tag movement commands in gvim are **multi line**.

It would appear that the tag commands in vsvim are always single line only.

### What happened instead?
nothing.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: Windows 10 x64

**Comment by johnfn** [comment]
This will be fixed in our next release!
