### ISSUE TITLE
Relative line move with remapped hjkl keys not supported

### ISSUE THREAD

**Issue by bdauria** [VSCodeVim/Vim#1233]
### What did you do?
I remapped hjkl keys to ctsr, since I'm using a [french dvorak](https://bepo.fr/wiki/Accueil) keyboard. Relative moves work only with the default hjkl mapping 

### What did you expect to happen?
Relative line moves to follow the ctsr mapping. 

### What happened instead?
The only way to move from lines relatively is to use the default mapping: for instance 5j instead of 5t

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.10
* OS: MacOS

**Comment by johnfn** [comment]
Are you saying that if you remap h to say c then 5c does not do 5h?

**Comment by bdauria** [comment]
correct.
