### ISSUE TITLE
Relative hjkl does not work in Visual Block Mode

### ISSUE THREAD

**Issue by Phrohdoh** [VSCodeVim/Vim#1234]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`CTRL-v` to enter visual-block mode.
`21j` to attempt to move 21 lines down.

### What did you expect to happen?

I would have 22 characters selected (the first char in <my_line>..<my_line+21>).

### What happened instead?

I only had two chars selected.

Instead of moving 21 lines down I was only moved one line down.

### Technical details:

* VSCode Version: 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281)
* VsCodeVim Version: 0.4.10
* OS: macOS

**Comment by xconverge** [comment]
@johnfn this can be closed due to #1258 fix
