### ISSUE TITLE
Va{ does not work

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1235]
This is actually kind of crucial because it allows you to operate at function level.

**Comment by xconverge** [comment]
I can't reproduce this, any tips?

**Comment by johnfn** [comment]
Just type Va{ in the middle of a function body. 

va{ works fine.

Va{ is broken.

**Comment by xconverge** [comment]
woops didnt see it was linewise

**Comment by smjure** [comment]
Tthis one does not work for me like in vim or nvim, e.g.:
`myFunctionName(arg1,arg2)`
If positioned at `F` in normal mode, by pressing `va(` i'd expect to select `(arg1,arg2)`, but nothing happens. How can I fix this? Thank you 🙏🏽
