### ISSUE TITLE
Substitute/Find and Replace with Relative Line Numbers

### ISSUE THREAD

**Issue by justinr636** [VSCodeVim/Vim#1237]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Example text:

    This line will change.
    This line will not change.
    This line also will not change.

### What did you do?

    :s/will/did/g3

### What did you expect to happen?

The word 'will' should be replace with 'did' on the line I issued the command and the subsequent next two lines.

    This line did change.
    This line did not change.
    This line also did not change.

### What happened instead?

The line from which I issued the command was changed, but none of the subsequent lines were affected.

    This line did change.
    This line will not change.
    This line also will not change.

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.4.11
* OS: Windows 10

**Comment by psylum** [comment]
Related, it would be nice if this form of the syntax also worked:
```
:.,.+3s/will/did/g
```

**Comment by offero** [comment]
Same issue for visual selection as well. `:<,>s/will/did/g`

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).
