### ISSUE TITLE
Unable to yank in 0.5.0

### ISSUE THREAD

**Issue by asvetliakov** [VSCodeVim/Vim#1239]
Windows 10
VScode 1.8.1
VscodeVim 0.5.0

1. Execute surround command, for example ```cs"'```
2. After that on any line:
* Pressing ```yy``` doesn't yank and switches you to surround input mode
* Pressing ```y``` in visual selection mode switches you to surround input mode

**Comment by johnfn** [comment]
Oh, you're absolutely right. Let me fix this right now.

**Comment by johnfn** [comment]
Should be fixed on v0.5.1, just released. Thank you for the report.

**Comment by asvetliakov** [comment]
How fast! Thanks
