### ISSUE TITLE
It would be awesome to have the in-editor Changelog show something for this plugin

### ISSUE THREAD

**Issue by sgronblo** [VSCodeVim/Vim#1240]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Notice that there is a new version of Vscodevim.vim in the left plugins pane. Click the plugin. Click the Changelog tab.

### What did you expect to happen?

I expected the latest changes to be shown so I know if some new feature I care about has been added to the plugin.

### What happened instead?

I get a message instead saying "No Changelog available."

### Technical details:

* VSCode Version: Version 1.8.1 (1.8.1)
* VsCodeVim Version: 0.5.1
* OS: MacOS 10.12.2

**Comment by johnfn** [comment]
We actually maintain our changelog here: https://github.com/VSCodeVim/Vim/releases

I wonder if there's a way to hook that up to vscode's changelog thingy? Let's see.

**Comment by johnfn** [comment]
Alright, added! Thanks for the tip - I didn't know about that tab at all.
