### ISSUE TITLE
Quotes - doesn't delete both empty quotes in Insert mode.

### ISSUE THREAD

**Issue by bargeruns** [VSCodeVim/Vim#1241]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In insert mode, type `'` or `"` to insert a pair of quotes. Then, press backspace to delete the quotes.

### What did you expect to happen?

_Both_ quotes should be deleted - this is the editor-default behavior, as well as the behavior when using the amVim extension.
### What happened instead?

Only one quote is deleted, so you have to either switch to Normal mode or use forward-delete to delete the trailing quote. This can make a simple typing mistake into an annoyance and interrupt flow.
### Technical details:

* VSCode Version: 1.9.0 (Insider)
* VsCodeVim Version: 0.5.1
* OS: Mac OS 10.12.3

**Comment by xconverge** [comment]
@johnfn this can be closed due to #1267
