### ISSUE TITLE
problem with the Chinese input 

### ISSUE THREAD

**Issue by FeifeiyuM** [VSCodeVim/Vim#1243]
* VSCode Version:  1.8.1 
* VsCodeVim Version: *[please ensure you are on the latest]* 0.5.2
* OS:  debian 8

> cursor do not moves correclty when input two or more words of Chinese at once    
> but when input Chinese words one by one,  the cursor moves correctly    
ex:  | represents cursor 
before input: 我的|
after input: 我的|朋友， cursor is at origin

**Comment by mhowto** [comment]
Same problem in my vscode.

- VSCode Version: 1.9.0
- VSCodeVim Version: 0.5.2
- OS: ArchLinux

**Comment by jetz** [comment]
duplicate #1027
