### ISSUE TITLE
surround should be repeatable with .

### ISSUE THREAD

**Issue by titussanchez** [VSCodeVim/Vim#1244]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

`ysw)` then went to another word and pressed `.`

### What did you expect to happen?

The next word should have be surrounded with parentheses

### What happened instead?

Nothing

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.5.2
* OS: OSX 10.10.5 / Windows 10

**Comment by Chillee** [comment]
You know what's cool is that vim-surround doesn't even have this feature.

**Comment by xconverge** [comment]
I found it really painful to not have it implemented, it is SO useful

**Comment by Chillee** [comment]
vscodevim > vim :smirk:

**Comment by andschwa** [comment]
@Chillee that's not true; I just tested and the repeat works just fine with vim-surround.

**Comment by Chillee** [comment]
Hmm, it doesn't seem to work for me...

`ysiw(` kinda works, but I still need to type the extra `(` every time.

`ds(` and `cs('` don't seem to repeat at all.

I'm using vim 8.0.56. Do you happen to have vim-repeat installed?
