### ISSUE TITLE
Make easymotion use `searchHighlightColor` for motion placer

### ISSUE THREAD

**Issue by jbmorgado** [VSCodeVim/Vim#1245]
easymotion functionality has some visual hints for the jump to letter that are of a different **font** than the one being used and that show **colours** that don't fit in the theme being used.

Allow it to use the `searchHighlightColor` for the _background of the letter_ at least and _use the font of the rest of the text_ if possible.

See the print screen for context:
<img width="308" alt="screen shot 2017-01-24 at 17 37 19" src="https://cloud.githubusercontent.com/assets/11217179/22259079/d20193f4-e25b-11e6-851b-c49effa4168c.png">

**Comment by hongymagic** [comment]
Would also be good to use the same font { size, lineHeight, weight } settings

**Comment by xconverge** [comment]
so setting the font and backgroundColor is cake....

unfortunately I don't have access to font color of the theme. Any ideas on how to choose the text color? I can try to compute a contrasting color based on searchHighlightColor for now?

**Comment by xconverge** [comment]
I need someone to test this or give me the colors and combos that they use :)

**Comment by xconverge** [comment]
@jbmorgado what do you use for your searchHighlightColor? just want to test

**Comment by xconverge** [comment]
Ok I decided to make the font size family and weight change for everyone, that makes a lot of sense

For using searchHighlightColor, you will need to add 
```    "vim.easymotionChangeBackgroundColor": true```
to your configuration. 

I think some people may like the one key red/two key orange thing so that was my reasoning for this. I could not do both and have it be readable in all cases. FWIW I think it looks much better and will have this option turned on :)

**Comment by xconverge** [comment]
FYI this changed in the latest release with more customization. This can be found in the readme

ie. I use this now

```
    "vim.easymotionMarkerBackgroundColor": "rgba(181,137,0, 1.0)",
    "vim.easymotionMarkerForegroundColorOneChar": "black",
    "vim.easymotionMarkerForegroundColorTwoChar": "black",
    "vim.easymotionMarkerFontFamily": "Source Code Pro",
    "vim.easymotionMarkerHeight": 16,
    "vim.easymotionMarkerYOffset": 12,
    "vim.easymotionMarkerWidthPerChar": 9,
```
