### ISSUE TITLE
Highlighted character jumps around when highlighting text.

### ISSUE THREAD

**Issue by pushkin-** [VSCodeVim/Vim#1247]
In the output window or editor, highlight some text (in normal mode)
![gif](https://cloud.githubusercontent.com/assets/6374473/22253248/77f23476-e216-11e6-9efd-f8025b82bc53.gif)
The cursor/selected char lags behind and sometimes jumps to the right when highlighting left.

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.5.2
* OS: Windows 10

**Comment by xconverge** [comment]
if you turn of useSolidBlock cursor this doesn't happen...just a workaround for now..

**Comment by jpoon** [comment]
I believe this is fixed by https://github.com/VSCodeVim/Vim/pull/1402. Please re-open if that's not the case.  cc @Chillee
