### ISSUE TITLE
Feature request: Support Ctrl+O Ctrl+I in command mode to navigate cursor locations

### ISSUE THREAD

**Issue by rhys-vdw** [VSCodeVim/Vim#1253]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

I've just made the switch from Vim to VSCode and am missing this one dearly! Is it feasible? I guess a stack of cursor positions would have to be maintained.

I have no experience writing VSCode plugins but I'm open to tackling this.

### What did you do?

Press either <kbd>Ctrl</kbd>+<kbd>O</kbd> or <kbd>Ctrl</kbd>+<kbd>I</kbd> in command mode.

### What did you expect to happen?

[Jump to previous/next cursor location](http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations).

### What happened instead?

Nothing. Apparently this is unsupported.

**Comment by grncdr** [comment]
VSCode itself has support for this, with `Ctrl`+`-` and `Ctrl`+`_` (`Ctrl`+`Shift`+`-`). I don't know if it's possible for the plugin to remap/add mappings for those, but you can definitely add your own mappings for them.

**Comment by rhys-vdw** [comment]
@grncdr cool! Well I can just remap them myself I guess.

**Comment by searene** [comment]
@grncdr Could you give some more explanations? `ctrl`+`-` is used to zoom out here(I'm using linux), and I didn't find a workable shortcut to jump to the previous position, including `alt`+`Left`(which I found online).

**Comment by grncdr** [comment]
@searene if you open up your keybindings.json (not sure where this is located on Linux, but on Mac it's `Code > Preferences > Keyboard Shortcuts` and search for `"command": "workbench.action.navigateBack"` that should tell you what the keybinding is. If there isn't a keybinding defined, you can add one in this file.

**Comment by searene** [comment]
@grncdr Amazingly it worked, thank you! In case it's helpful for others, this is my `keybindings.json`

```json
[
    { "key": "ctrl+o",
      "command": "workbench.action.navigateBack"
    },
    { "key": "ctrl+i",
      "command": "workbench.action.navigateForward"
    }
]
```

**Comment by beefsack** [comment]
@searene's suggestion works fairly well for me, can we look at making this default behavior when using the plugin?

**Comment by johnfn** [comment]
Didn't realize this issue has become so popular! It has to be one of the lowest-effort issues - I'll probably do it soon, if no one else gets to it.

**Comment by johnfn** [comment]
Added!
