### ISSUE TITLE
Inconsistencies with visual mode deletion

### ISSUE THREAD

**Issue by ctidd** [VSCodeVim/Vim#1256]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. While in normal mode, use mouse to select any amount of text, triggering visual mode selection.
2. Press `delete` key (not backspace).

### What did you expect to happen?

I'd expect the same as if I had used `d` to delete the text after selecting it:

Selected text is deleted, and editor returns to normal mode.
Cursor is displayed as block cursor, indicating normal mode.

### What happened instead?

Selected text is deleted, and editor remains in visual mode.
Cursor is bar cursor, indicating visual mode.

### What did you do?

1. Select text as before.
2. a) Press `delete` or `d`, then press a vertical movement key: `arrow up`, `arrow down`, `j`, or `k`.
    b) Press `delete`, then press a horizontal movement key. (Horizontal movement works as expected for deletion with `d`.)

### What did you expect to happen?

Moving the cursor originates movement from its currently displayed location.

### What happened instead?

Movement occurs relative to the character position of what was the end of the selection before deleting it. This leads to a horizontal jump when moving the cursor vertically (after either `delete` or `d`), or a sudden visual mode selection when moving the cursor horizontally (only after `delete`).

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.5.2
* OS: Ubuntu 16.10

**Comment by Chillee** [comment]
Sorry, I don't understand what the second issue is? Or at the very least, I can't replicate it.

**Comment by ctidd** [comment]
Here's an example of a specific case of the second issue:

1. Double click on a word.
2. Press `k`.

Expected: Cursor moves upward from current position (after deleting the text).
What happened: Cursor moves upward relative to the position it occupied prior to deleting the text.

![example](https://cloud.githubusercontent.com/assets/1337110/25560362/50992834-2d17-11e7-9a48-412a043fdc03.gif)
