### ISSUE TITLE
Horizontal Split with `:split`

### ISSUE THREAD

**Issue by mitchlloyd** [VSCodeVim/Vim#1257]
It appears that VSCode [now supports horizontal splits](https://github.com/Microsoft/vscode/issues/1749). Does that mean it is now possible to work on supporting `:split` (previously discussed here: https://github.com/VSCodeVim/Vim/issues/622)?

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

**Comment by johnfn** [comment]
I don't think that VSCode actually supports this now, because you can only horizontal split *or* vertical split, not both.

Unless you guys really don't care about that?

**Comment by mitchlloyd** [comment]
Ah I misunderstood how the feature works in VSCode. Implementing `:split` with this limitation might just be confusing. 

Thanks for the great extension!

**Comment by trev-dev** [comment]
https://github.com/VSCodeVim/Vim/issues/622#issuecomment-420032365
