### ISSUE TITLE
Implement jumplist?

### ISSUE THREAD

**Issue by splodingsocks** [VSCodeVim/Vim#1260]
Please let me know if this is already supported and I just missed it, but I searched around the docs and the issues and didn't find a peep.

One thing I miss from Vim is the jumplist, where cursor positions were remembered, and navigable with `ctrl-i` and `ctrl-o`. The same functionality is available in Atom with this package:

https://atom.io/packages/cursor-history

Thanks!

**Comment by grncdr** [comment]
See https://github.com/VSCodeVim/Vim/issues/1253 for a workaround

**Comment by splodingsocks** [comment]
thanks! Sorry I wasn't able to find that myself :)
