### ISSUE TITLE
normal mappings don't always override defaults

### ISSUE THREAD

**Issue by kitsu** [VSCodeVim/Vim#1261]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

After adding key bindings for shift-H and shift-L the default behaviors still happen occasionally.

User settings excerpt:
```javascript
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["L"],
            "after": ["$"]
        },
        {
            "before": ["H"],
            "after": ["^"]
        },
        ...other bindings...
```
For example just pressing `L` correctly moves to end of line, but pressing `dL` deletes until end of window/document. It works correctly in visual mode, and most of the time in normal mode, but fails almost always as a movement in a command.

I also have other bindings problems, but I think they are unrelated.

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.5.2
* OS: Win7

**Comment by epilande** [comment]
Any update on this issue? I'm seeing this as well when I'm in visual mode, `vL` should select from cursor to end of line, but instead, it selects from the cursor to end of the screen which is the default behaviour of `L`.

**Comment by kitsu** [comment]
I just had to mess with my config again after otherModes was removed:angry:. After duplicating my bindings in both `vim.normalModeKeyBindingsNonRecursive` and `vim.visualModeKeyBindingsNonRecursive` I found that my `L` and `H` binding completely stopped working.

When I moved them to the Non-nonRecursive sections the normal mode binding started working, but only when not used in an action (i.e. `L` by itself moves to end of line, but `dL` deletes using stupid default `L` behavior that is useful to no one ever). Visual mode is a complete loss.

How did you implement keybind overrides but not honor them in commands? Vim bindings define a syntax. It is not reasonable to have to rebind every possible combination when a command or movement is changed!

**Comment by expelledboy** [comment]
So my thought was something along these lines

```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["L"],
            "after": ["$"],
        },
        {
            "before": ["H"],
            "after": ["^"],
        },
        {
            "before": ["v", "L"],
            "after": ["v", "$"],
        },
        {
            "before": ["v", "H"],
            "after": ["v", "^"],
        },
    ],
```

But it doesnt work...

**Comment by AeroCross** [comment]
> When I moved them to the Non-nonRecursive sections the normal mode binding started working, but only when not used in an action (i.e. L by itself moves to end of line, but dL deletes using stupid default L behavior that is useful to no one ever)

I gave this a go in `vim` and turns out that even there `dL` would do the default, so it is not necessarily VS Code Vim.

Try it out. In `vim`:

```
nnoremap L $
```

Then go to a line and input `dL` won't work as you expect. This is because `d` is an operator which in turn puts you in "Operator Pending Mode" which makes available a different set of bindings. Check `:help omap:` and go to the `omap-info` section for more information.

What I do find interesting is that if we go to `visualModeKeyBindingsNonRecursive` it _should_ work but alas it doesn't, for some reason. The equivalent in vim would be `vnoremap L $` which **does** work, so there's something fishy going on with Visual Mode specifically.

**Comment by AeroCross** [comment]
From what I can read that's because `noremap` means "Map to Normal, Visual, Select, and **Operator Pending** modes". Operator Pending mode isn't available to VS Code Vim.

`nnoremap` is only for normal mode, which _is_ available to VS Code Vim. That would explain why that doesn't work.
