### ISSUE TITLE
ctrl-e and ctrl-y don't work when in visual mode

### ISSUE THREAD

**Issue by TyOverby** [VSCodeVim/Vim#1264]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

When in visual mode, press ctrl-e or ctrl-y

### What did you expect to happen?

I expected the window view to change (just like ctrl-e or ctrl-y in normal mode)

### What happened instead?

nothing

### Technical details:

* VSCode Version: 1.9.0
* VsCodeVim Version: 0.5.2
* OS: Windows

**Comment by xlaech** [comment]
Is this a feature you would like to see due to your experience with VSCodeVim or do you know this feature from a specific vim version?

I can not reliably reproduce such a behaviour in vim/macvim 8.0. 

With ctrl-y i get additional yanking and with ctrl-e i also start selecting to the file, while scrolling (and then further).
Pressing ctrl-y after this will also change the selection.

@xconverge @johnfn What is the expected behaviour for this function?

**Comment by xconverge** [comment]
I looked at this one, I am able to get it to move the window, however there are cursor issues,

we have the actions already defined in actions.ts, however only for normal mode I believe

**Comment by TyOverby** [comment]
@xlaech: ctrl-e / ctrl-y are present in every version of vim that I've used in the last 5+ years.

**Comment by xlaech** [comment]
@xconverge Would it make sence to just tag the action for visual mode as well?
@TyOverby So in your vim the shortcuts just move the window in visual mode, or do they also select?

**Comment by TyOverby** [comment]
@xlaech: they move the window.

**Comment by xconverge** [comment]
@xlaech that is the start, however it then does not behave correctly in visual mode. It does not expand the selection as it should, it just shifts the cursor

**Comment by xlaech** [comment]
Ok i tested the behavior now on mac, linux and windows - just to make sure i get it right.

Here is what i suggest to implement:
In visual mode
- remember the starting cursor position
- When ctrl-e is pressed 
    - move view down 1 line
    - add 1 line to the end cursor position
- When ctrl-y is pressed
    - move view up 1 line
    - remove 1 line to the end cursor position

Suggestions?

**Comment by xconverge** [comment]
go for it, try it out! I am not sure how well we handle cursorPositions that are off of the screen though

**Comment by TyOverby** [comment]
@xlaech Why are you adding and removing lines to cursor position?  ctrl-e / ctrl-y only move the window.

**Comment by xconverge** [comment]
not in visual, it also adjusts the selection. He was referring to our codebase "end cursor position" and "start cursor position"

**Comment by TyOverby** [comment]
Sorry, maybe I'm really confused.  Here's a screencast of vanilla vim scrolling the window without modifying the selection

https://asciinema.org/a/0wyichgyxfmvglkqa6xnnx18h

**Comment by xconverge** [comment]
do ctrl e a few more times so that the cursors are off the screen, that is the issue

**Comment by TyOverby** [comment]
Oh, ok.  Yeah, I'm pretty sure that's an implementation issue with Vim; cursors (and therefore selections) aren't allowed outside the viewable window.

I've seen vim emulators choose to replicate this behavior and emulators that disable it.  I guess you could go either way, though I'd prefer not reimplementing the bug :D

**Comment by xlaech** [comment]
Hm i think we should wait for @johnfn to tell us his opinion.

I personally would kind of find it helpful for the shortcuts to just scroll. I can already select with hjkl :)
On the other side, most vim implementations seem to use it with selection, which might be easier for most vim users.

**Comment by johnfn** [comment]
First off, I definitely see c-e and c-y in visual mode. 

The cursor staying on the screen is just another example of the sticky cursor, something we never bothered to implement which forces the cursor to always be on the screen. It's tracked here: #873. Example of sticky cursor in Vim: if you scroll the page down with the mouse in vanilla vim the cursor eventually sticks on the top of the screen. 

I say we go ahead and allow c-e and c-y in visual mode and don't bother with the sticky cursor.

**Comment by johnfn** [comment]
Awh, we're actually blocked by VSCode here. 

https://github.com/Microsoft/vscode/issues/16248

**Comment by xlaech** [comment]
Than, we will have to wait :)

**Comment by TyOverby** [comment]
Any update on this?

**Comment by Chillee** [comment]
I believe this was fixed at some point. Please comment if this was not.

**Comment by TyOverby** [comment]
@Chillee: Confirmed to be fixed

Thanks to whoever fixed it!

**Comment by Chillee** [comment]
Hmm, maybe you shouldn't thank me so fast yet...

What's the impact if `<C-e>` doesn't bring your selection past the edge of the window? As in, if you have text selected, `<C-e>` won't be able to scroll such that the selection is outside of the window boundary.
