### ISSUE TITLE
jump-to-line doesn't work in visual mode

### ISSUE THREAD

**Issue by TyOverby** [VSCodeVim/Vim#1265]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

When in visual mode, type the following `:10` (jump to line 10) 

### What did you expect to happen?

I expect to jump to line 10 and expand the visual selection to include line 10

### What happened instead?

The cursor moves to line 10, but the selection *shifts* (not expands)

### Technical details:

* VSCode Version: 1.9.0
* VsCodeVim Version: 0.5.2
* OS: windows

**Comment by rufusroflpunch** [comment]
I can recreate this issue.

**Comment by rufusroflpunch** [comment]
However, I tested this behavior in vim, and in vim it doesn't expand the selection either. In fact, vim actually just switches back to normal mode.

**Comment by TyOverby** [comment]
Oh wow.  I wonder if one of my vim plugins does this for me.

I'll close this issue out of embarrassment.
