### ISSUE TITLE
Search for current word is inexact

### ISSUE THREAD

**Issue by rhys-vdw** [VSCodeVim/Vim#1266]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

The following four commands are incorrectly implemented:
- <kbd>*</kbd> Forwards exact word search
- <kbd>#</kbd> Backwards exact word search
- <kbd>g</kbd><kbd>*</kbd> Forwards partial word search
- <kbd>g</kbd><kbd>#</kbd> Backwards partial word search

### What did you expect to happen?

Exact word searches should search for exact words. eg. Pressing <kbd>*</kbd> on the string "he" should not highlight "hello".

Partial word searches should search within words for the search string.

[Vim wiki reference](http://vim.wikia.com/wiki/Searching#Searching_for_the_current_word)

### What happened instead?

Exact searches do partial search.
Partial search commands are not implemented.

### Technical details:

* VSCode Version: 1.9.0
* VsCodeVim Version: 0.5.2
* OS: OSX

**Comment by johnfn** [comment]
I definitely can't reproduce this - * works as it should on my machine. Can you please provide the entire text document that you used to reproduce this, along with your settings.json file?

**Comment by xconverge** [comment]
I can reproduce this

```
t|e
test
testtest
```

then press *, only te should be found, pressing n should do nothing

**Comment by rhys-vdw** [comment]
Yes, @xconverge is right, although there's a stray pipe character in the code block.

```
press * or # on the following line:
test
testtest
```

**Comment by johnfn** [comment]
Believe it or not, both of your examples work perfectly fine in my configuration. 

Could I have either of your settings.json files?

**Comment by xconverge** [comment]
@rhys-vdw we use pipe char in examples to show cursor position ;)

**Comment by xconverge** [comment]
@johnfn can you turn hlsearch on for this test, it isn't necessary since n and N shouldn't move but helps visualize it

It is because when a search is created it doesn't specify "full word" search for * and # and only looks for a matching string

**Comment by rhys-vdw** [comment]
I believe I have found the [problematic line of code](https://github.com/VSCodeVim/Vim/blob/ee9bdca48c9b375952a39b2a498fcc31724317b4/src/actions/actions.ts#L1586).

Current line:

```js
vimState.globalState.searchState = new SearchState(SearchDirection.Forward, vimState.cursorPosition, currentWord);
```

But unless I'm missing something - it should look like this:

```js
vimState.globalState.searchState = new SearchState(SearchDirection.Forward, vimState.cursorPosition, `\\b${currentWord)\\b`, { isRegex: true });
```

**Comment by rhys-vdw** [comment]
@xconverge My config doesn't have anything interesting in it:

```json
// Place your settings in this file to overwrite the default settings
{
    "rust.checkOnSave": true,
    "editor.autoClosingBrackets" : false,
    "editor.lineNumbers": "relative",
    "editor.rulers": [80, 100],
    "editor.fontFamily": "Hasklig",
    "editor.fontSize": 12.8,
    "editor.codeLens": true,

    "vim.hlsearch": true,
    
    "ruby.lint": {
        "rubocop": true,
        "ruby": true //runs ruby -wc
    },

    "files.associations": {
        "*.js.erb": "javascript",
        "*.jsx": "javascript"
    }
}
```

**Comment by xconverge** [comment]
yep that looks like one way of fixing it to me!

**Comment by xconverge** [comment]
are you going to submit a PR or do you want someone else to?

**Comment by rhys-vdw** [comment]
I'd like to.

**Comment by rhys-vdw** [comment]
I'll submit it this evening.

**Comment by xconverge** [comment]
Great, good find!
