### ISSUE TITLE
Feature Request: vim-sneak

### ISSUE THREAD

**Issue by elithrar** [VSCodeVim/Vim#1268]
https://github.com/justinmk/vim-sneak

Easymotion is great, but can be complex. vim-sneak is a popular alternative super-useful for short-distance searching and navigation.

(I don't expect this to be included short-term, but am considering this a way to track popularity)

**Comment by johnfn** [comment]
By all means, but keep in mind it's unlikely I will add this, as adding every plugin is just too much scope. (Unless it turns out to be our most requested feature like surround :wink:)

**Comment by LiyinZ** [comment]
Would love to have this much simpler to use than easymotion!

**Comment by Chillee** [comment]
I'm thinking about implementing this since this actually looks like something I would really like (plus it doesn't seem tooo hard if we leverage a lot of already existing functionality).

However, I was wondering: what would be the minimum needed functionality for this to be useful?
