### ISSUE TITLE
`x` at end of line doesn't work

### ISSUE THREAD

**Issue by jpoon** [VSCodeVim/Vim#127]

**Comment by jpoon** [comment]
Fixed with https://github.com/VSCodeVim/Vim/issues/127

**Comment by chevex** [comment]
Is this fix in the live plugin? I'm experiencing this issue but maybe it's just not released yet?

**Comment by jpoon** [comment]
Looks like a regression with the latest release :(

**Comment by jpoon** [comment]
Ok, pushed an update. This should be fixed in 0.0.15.

I noticed a couple of other regressions with the delete operators -- sorry -- I'll try a fix as soon as I can.

**Comment by chevex** [comment]
Confirmed to be working as expected now. Thanks!

**Comment by tunz** [comment]
I think it does not work in 0.0.16 version of OS X vscode. Is it fixed?
