### ISSUE TITLE
ds{ deletes last letter of word

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#1271]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`ds{` on `{ hello }`

### What did you expect to happen?

`hello`

### What happened instead?

`hell`

### Technical details:

* VSCode Version: 1.9
* VsCodeVim Version: 0.5.2
* OS: OS X 10.11.6

**Comment by xconverge** [comment]
I am unable to reproduce this..hmm

**Comment by johnfn** [comment]
Really? It's pretty easy for me to reproduce.

**Comment by xconverge** [comment]
ah i didn't have the whitespace!
