### ISSUE TITLE
Putting over selection in visual mode does not yank deleted selection

### ISSUE THREAD

**Issue by rhys-vdw** [VSCodeVim/Vim#1280]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Attempted to swap two words by using cut/paste in visual mode:

```
|from to
```

Commands: `dewvep0P`

### What did you expect to happen?

```
t|o from
```

### What happened instead?

```
fro|m from
```

### Technical details:

* VSCode Version: 1.9.0
* VsCodeVim Version: 0.5.2
* OS: OSX

**Comment by rhys-vdw** [comment]
Tried to fix this myself by swapping the order of 'delete' and 'put' invocations, and enabling yank on delete, but it leaves the cursor in a bad position (at the start of pasted text instead of the end).

https://github.com/rhys-vdw/Vim/commit/5a03cf2e427df91210919822931a0a83d705d58f

Could somebody advise me how to achieve this idiomatically?

**Comment by xconverge** [comment]
ah this is a good catch, yea at least it wasn't yanking when deleting over the previous register in current master

I think you are on the right track, can you just set  vimState.cursorPosition = at the end?

I think this is happening because the delete is pushing a transform that sets the cursor position that is not quite right, not sure...

**Comment by rhys-vdw** [comment]
Just had another play around with this. I guess the problem is that I don't know what to set the cursor position to.

**Comment by rhys-vdw** [comment]
I'll try to revisit this in the coming days, I'm sure it will keep annoying me. :)

**Comment by xconverge** [comment]
You can get the register length before doing anything?

**Comment by johnfn** [comment]
@rhys-vdw, I'm sorry I missed your questions earlier. The most reliable way to bug me in the future is to ping me on Slack. I try to be fairly responsive. :)

**Comment by rhys-vdw** [comment]
Thanks @johnfn. I'm a bit busy to work on this PR for now.

**Comment by bschlenk** [comment]
+1 This prevents my usual way of swapping key/values in js objects.
