### ISSUE TITLE
Autocomplete doesn't work in Java after VSCode January update

### ISSUE THREAD

**Issue by atiqorin** [VSCodeVim/Vim#1283]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Open or create a java file. Type any of these while coding     (,[,{,",' 

### What did you expect to happen?

The above mentioned characters should auto complete.

### What happened instead?

Doesn't autocomplete. Disabling VSCodeVim solves this autocomplete issue.

### Technical details:

Issue came after VSCode January update

* VSCode Version: 1.9.0 (27240e71ef390bf2d66307e677c2a333cebf75af)
* VsCodeVim Version: 0.5.2
* OS: macOS Sierra 10.12.3 and Windows 10 x64

**Comment by xconverge** [comment]
if I create an untitled file and do ( it inserts ) automatically... does that work for you?

**Comment by atiqorin** [comment]
If I open an untitled file then (,{ and [ autocompletes. But " and ' does not.

**Comment by atiqorin** [comment]
It works in javascript file. So I updated issue title as I am facing it in java files only. I have not tested if it works in other languages or not.

**Comment by johnfn** [comment]
By autocomplete, you mean you type one " and it types another one, right?

**Comment by atiqorin** [comment]
yes. type one " or ', it types another " or ' like parenthesis and braces

**Comment by atiqorin** [comment]
Ok. Just now I discovered the main issue. When both "Language support for Java by Red Hat" and VSCodeVim are enabled at the same time this issue occurs. Disabling any one of these two extensions makes autocomplete working again. For the time being I am just disabling "Language support for Java by Red Hat". So VSCodeVim has issue with this extension. Let me know if I should close the issue or it is something VSCodeVim will look into.

**Comment by johnfn** [comment]
We'll certainly look into it, but you should probably also file the issue with "Language support for Java by Red Hat" :)

**Comment by xconverge** [comment]
https://github.com/redhat-developer/vscode-java/issues/144

This looks suspicious...

**Comment by xconverge** [comment]
Also looks like they just released a new version with a fix. Can you check it and close this issue once you see it fixed?

**Comment by atiqorin** [comment]
Yay. It is fixed. But still I am feeling stupid now. Why did disabling VSCodeVim and Enabling Rad Hat was fixing the issue is way over my head. Thanks all. Closing issue.
