### ISSUE TITLE
Normal mode "p" command does not paste from system clipboard

### ISSUE THREAD

**Issue by pfmoore** [VSCodeVim/Vim#1284]
### What did you do?

In normal mode, ```p```

### What did you expect to happen?

Paste from the system clipboard (I have ```useSystemClipboard``` set to ```true```)

### What happened instead?

Nothing. Sometimes (it doesn't seem to always happen, but I can't quite reproduce why/when) I get an error, "Error pasting, if useSystemClipboard is true and you are using Linux, please install xclip."

I'm not on Linux, and there's no further detail in the error console.

### Technical details:

* VSCode Version: 1.9.0
* VsCodeVim Version: 0.5.2
* OS: Windows 7 Pro SP1

**Comment by xconverge** [comment]
Have you tried different file types?

We are simply using https://github.com/xavi-/node-copy-paste for the system clipboard

I personally have not had any issues with it on macOS, Ubuntu, or Win10...hmmm

**Comment by pfmoore** [comment]
Yes, I've tried multiple file types (XML, text, Python) and I've tried copying from another application (highlight text, Ctrl-C) and from within Code (yw). The first time I use "p" I get nothing. Subsequent times I get the error noted. I don't know if there's anything significant about the first time.

Ctrl-V in insert mode works fine, it's only the "p" command in normal mode that's broken.

I don't know if it helps, but I grabbed the VBScript file from the copy/paste library you pointed at and ran it manually using CScript. I got the error message

```
C:\Work\Scratch\t.vbs(32, 3) ADODB.Stream: Arguments are of the wrong type, are out of acceptable range, or are in conflict with one another.
```

Frankly, this looks like a really bizarre way of accessing the system clipboard, though. I know very little about node.js, but is there really no better way?

**Comment by pfmoore** [comment]
With a bit further digging, this seems to happen if

```
text = objHTML.ParentWindow.ClipboardData.GetData("Text")
```

returns an empty string. My clipboard isn't empty, so maybe the approach of creating a htmlfile object and getting its parent window's clipboard doesn't always work correctly?

BTW, I realise that if this is the issue, it's in a 3rd party library and not in your code, but not being able to paste in normal mode is a pretty significant issue for me, so I'm pretty concerned that it gets fixed...

**Comment by seanhaneberg** [comment]
I also saw this behavior. I noticed that it seemed to occur *after* I would access a non-default buffer (like typing `"0p` ). 

Since it persisted across restarts, I theorized that it had to do with that `"0p` command being in the vim history.

I didn't have time to confirm the theory through debugging the history code, but I did notice that if I set the vim.history to 0, the pasting behavior returns back to normal.

I hope that gives you guys a more consistent repro and a workaround! :-)

**Comment by gwojan** [comment]
I have just noticed that ```yyP``` gives me an error message or does nothing at all. 

```yyoCtrl+v``` basically does what I expect. However, pasting in Insert mode is not something my fingers are really trained to do.

**Comment by jpoon** [comment]
Haven't been able to get a repro of this :/

VSCode Version: 1.11.2
VsCodeVim Version: 0.6.17
OS: OSX

**Comment by pfmoore** [comment]
The issue I'm getting is in Windows, and is specifically related to the Windows code path in the clipboard library used. So I'm not surprised it's not reproducible on OSX.

**Comment by xconverge** [comment]
I switched libraries but he just made another fix for windows so stay tuned for the next update

**Comment by xconverge** [comment]
https://github.com/sindresorhus/clipboardy/pull/13

**Comment by pfmoore** [comment]
Confirmed, seems to be working fine now. Thanks!

**Comment by xconverge** [comment]
Awesome!
