### ISSUE TITLE
`cc` doesn't clear whitespace on a blank line

### ISSUE THREAD

**Issue by rhys-vdw** [VSCodeVim/Vim#1285]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Press `cchello<esc>` and on this line (using `$` to show line ending)

```
|        $
```

(the same problem does not seem to exist for `0C`)

### What did you expect to happen?

```
hell|o$
```

### What happened instead?

```
hell|o        $
```

### Technical details:

* VSCode Version: 1.9.0
* VsCodeVim Version: 0.5.2
* OS: osx sierra

**Comment by rhys-vdw** [comment]
Might be worth looking at #727 at the same time.

**Comment by johnfn** [comment]
This must be because we try to preserve indentation. Thanks for the bug report!

**Comment by rhys-vdw** [comment]
Thanks @johnfn!
