### ISSUE TITLE
Korean characters overlap each other

### ISSUE THREAD

**Issue by Anongh** [VSCodeVim/Vim#1287]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?
I entered Korean characters in insert mode.

### What did you expect to happen?
I expected a situation where the cursor would move to the right without overlapping when entering the letters as usual.

without Vim;
![without vim](https://cloud.githubusercontent.com/assets/22952514/22779832/adbac226-eeff-11e6-91f1-9b7c6b113215.gif)

### What happened instead?
During typing, the letters overlap each other.

with Vim:
![with vim gif](https://cloud.githubusercontent.com/assets/22952514/22779835/b027a2fe-eeff-11e6-9c86-add5dfb68704.gif)

### Technical details:

* VSCode Version: 1.9.1 (The same problem has occurred since 1.8)
* VsCodeVim Version: 0.5.2
* OS: Windows 8.1

**Comment by xconverge** [comment]
@rebornix any ideas on this one?

**Comment by misoguy** [comment]
I'm interested in fixing this issue and have been digging around.
It seems like when a type is made in Korean(Chinese), the following code is invoked
>registerCommand(context, 'compositionStart', async (args) => {
and listens to 'replacePreviousChar' to compose the texts and changes the state when 'compositionEnd' is invoked.
When those handlers are deleted it works like the screenshot above without vim but it comes with some side effects...(The one that I could see is bugs in normal mode)
I'll try to dig more but any guide or hint would be much appreciated!

**Comment by rebornix** [comment]
@misoguy thanks for taking a look at this issue. Please note that we bind our specific handlers for composition to fix problems with CJK IME in Normal Mode. So whatever modification we make to this piece of code, we don't want to have regression.

**Comment by 5pecia1** [comment]
The same issue occurred.

VSCode Version: 1.52.0 
VsCodeVim Version: 1.18.5
OS: Mac Darwin x64 19.6.0
