### ISSUE TITLE
WARN: "command 'extension.vim_escape' not found" after VSCode 1.9.1 upgrade

### ISSUE THREAD

**Issue by mattheyan** [VSCodeVim/Vim#1288]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Nothing (editor first load) -or- press `ESCAPE`

### What did you expect to happen?

Normal mode

### What happened instead?

`WARN: command 'extension.vim_escape' not found`

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.2
* OS: Windows 8.1 Pro

------

The error above describes the `ESCAPE` key binding, but it seems that vim pretty much stopped working with the VSCode 1.9.1 upgrade.

I manually re-installed VSCode 1.9.0 and that got me around the problem for now. Of course, VSCode is going to upgrade when it shuts down...

Thanks,
Bryan

**Comment by kitsu** [comment]
Temporary fix: disable auto-update:
https://code.visualstudio.com/docs/supporting/faq#_how-do-i-opt-out-of-vs-code-autoupdates
If you edit you config before exiting it will prevent a pending update!

**Comment by mattheyan** [comment]
Thanks @kitsu !  :-)

**Comment by xconverge** [comment]
The upgrade worked for me I am running win10 with 1.9.1 and latest vscodevim

**Comment by xconverge** [comment]
I would guess this was more of a vscode issue not loading a plugin correctly after an update than our plugin specifically

**Comment by mattheyan** [comment]
That’s interesting that it worked for someone else. FWIW, I did multiple restarts and uninstalled/reinstalled the plugin and it still didn’t work. :-/

**Comment by mattheyan** [comment]
I have another machine that's also prompting to upgrade. I'll let you know if I have the same problem there, and can troubleshooting further if needed.

**Comment by mattheyan** [comment]
No problem on the other machine *scratches head*. I'll give it another shot on the first machine when I get to a stopping point with my current work.

**Comment by jpoon** [comment]
@mattheyan Yeah, I think this is a VSCode issue. I've had this happen a couple of times (mainly earlier in the year when VSCode was in it's infancy). The remedy I've had is to uninstall the plugin, clear the extensions folder (on Windows it is here for me: C:\Users\jason\.vscode\extensions), reinstall.

If you end up finding a repro, please file the issue against VSCode.

**Comment by kitsu** [comment]
Okay, I got brave and tried it and it worked fine updating from 1.8 to 1.9.1 on Win7 with latest VSCodeVim.
YMMV I guess, good luck!

**Comment by mattheyan** [comment]
I saw the issue occur again while working, without a VSCode upgrade. This time a restart fixed it. I may have to try @jpoon's suggestion. Thanks guys!

**Comment by ahjsrhj** [comment]
@jpoon reinstall the extensions is works for me, thanks!

**Comment by spacegoing** [comment]
@jpoon reinstall didn't work for me. Even after I cleaned the repo.

**Comment by molysama** [comment]
Same problem on 1.10.2. Reinstall the extensions is not work

**Comment by rebornix** [comment]
@molysama @spacegoing do you have extension auto update turned on?
