### ISSUE TITLE
Visual Selection of Text lines

### ISSUE THREAD

**Issue by bruparel** [VSCodeVim/Vim#129]
The visual selection mode does not seem to work.  I tried 'v' shift-v in the command mode to highlight characters and lines but did not work for me.  Is that functionality missing?  The documentation mentions visual mode several times so I am assumed that it works.  If it is not available yet then what is the alternate way of selecting text in executing vim commands on the selected text?

**Comment by jpoon** [comment]
Hey @bruparel. Thanks for filing the issue.

As we haven't yet implemented an pertinent commands or motions for visual mode (yank, paste, etc), I decided to remove the mode entirely in the last release.

**Comment by bruparel** [comment]
@jpoon Thanks Jason.  I really appreciate your work.  For an "old" VIM user, this is a great gift.  Please keep up the good work.

**Comment by jpoon** [comment]
Fixed with https://github.com/VSCodeVim/Vim/pull/144

**Comment by bruparel** [comment]
@jpoon This is awesome :)  How do I update my VIM plugin?  By regular update extensions command?

**Comment by jpoon** [comment]
https://code.visualstudio.com/Docs/editor/extension-gallery

**Comment by jpoon** [comment]
@bruparel yeah, those things are not implemented yet.

**Comment by jpoon** [comment]
@trivoldus28 all kudos goes to @johnfn for his work.
