### ISSUE TITLE
Relative line number wasn't updated in Visual Line mode up direction('k' key)

### ISSUE THREAD

**Issue by Yukaii** [VSCodeVim/Vim#1290]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

<kbd>V</kbd> + <kbd>k</kbd>

### What did you expect to happen?

This is what vim does:

![vscode-vim-visual-line-mode-bug3](https://cloud.githubusercontent.com/assets/4230968/22862768/f8fbe608-f16f-11e6-94d5-875d3515bfe1.gif)

### What happened instead?

![vscode-vim-visual-line-mode-bug2](https://cloud.githubusercontent.com/assets/4230968/22862789/5aae5124-f170-11e6-8fa9-004a0a7a9f84.gif)

### Technical details:

* VSCode Version: 0.5.3
* VsCodeVim Version: 1.9.1
* OS: macOS 10.12.3

### Config that might be related

```json
  "vim.useCtrlKeys": true,
  "vim.useSystemClipboard": true,
  "vim.hlsearch": true,
  "vim.ignorecase": false,
  "vim.easymotion": true,
  "editor.cursorStyle": "block",
  "editor.lineNumbers": "relative",
```

**Comment by xconverge** [comment]
interesting just tested with vanilla vscode and mouse selections and it works correctly, so this should be doable
