### ISSUE TITLE
Ex commands not working as in gvim when operating over a selection

### ISSUE THREAD

**Issue by bbycroft** [VSCodeVim/Vim#1292]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

make a selection, e.g. select 3 lines: `Vjj`
open the command window with colon: `:`
do a replacement: `s/hello/world/g`
press enter to apply the replacement: `<Enter>`

### What did you expect to happen?

As in gvim, I'd want this to run the search/replace action across the 3 line selection.

### What happened instead?

Only the line that the cursor is on has search/replace run on it.

#### Cause

When the command window is opened the selection operator `'<,'>` is highlighted, so as soon as I start typing the replacement command, it overwrites that selection operator so only executes on one line.

#### Workaround

The workaround is to tap Right-Arrow after opening the command window to position the cursor correctly, but that's not so great for muscle memory, and doesn't match gvim.

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: Windows 10

**Comment by johnfn** [comment]
Unfortunately limited by vscode here: #792
