### ISSUE TITLE
Insert-Normal Mode moves cursor by one

### ISSUE THREAD

**Issue by xlaech** [VSCodeVim/Vim#1293]
### What did you do?

In Insert Mode i pressed `<C-o>` to go to Insert normal Mode.
The Commands i use in there work, but when i come back to normal mode, the cursor has moved one character to the left.

### What did you expect to happen?

I expected the cursor to stay at the old position (checked the behavior in vim 8.0)

### What happened instead?

The Cursor moved one character to the left.

### Technical details:

* VSCode Version: 1.9
* VsCodeVim Version: *0.5.3*
* OS: Mac OS X Sierra 10.12.3

**Comment by xconverge** [comment]
Ooo good one, this makes c-o pretty weird to use! I will try to get to this tonight, should be easy

**Comment by xconverge** [comment]
Also note of the edge case of the first char on the line...this currently acts correctly for the first character

**Comment by xlaech** [comment]
I just checked out the code myself and realized, that the bug is much more general. It is caused whenever i leave the insert mode with Esc. Since ctrl-o will call new `CommandEscInsertMode().exec(position, vimState);` @actions.ts, it triggers the bug.

**Comment by xconverge** [comment]
That isn't a bug though, that is the intended behavior of <Esc> when in insert...

**Comment by xlaech** [comment]
Oh... I see. I just checked in vim 8.0. So i would love to fix the bug (already got it working locally), but i want to keep your style of coding.

1) is `position.getLeft().add(new PositionDiff(0, 1));` the right way to go?
2) would this be important enough to overload the method?

**Comment by xlaech** [comment]
Ah i see. I can just pass in another parameter :)
Is it ok if I create a pull request?

**Comment by xconverge** [comment]
@xlaech Yes of course! just tag this issue in your commit message with "fixes #1293"

I think it is even easier though. Can't we just do this only for Ctrl+o

new CommandEscInsertMode().exec(position.getRight(), vimState);

instead of new CommandEscInsertMode().exec(position, vimState); as long is it is not the first character?

**Comment by johnfn** [comment]
Wonderful, @xlaech! Always glad to see more people contributing. 

You can also feel free to ping me on our slack channel for faster responses. I'm on vacation currently, but I'll try my best to help when I can!

**Comment by xlaech** [comment]
Ok. thank you.
