### ISSUE TITLE
deleting with D on visual selection doesn't work as expected

### ISSUE THREAD

**Issue by kitwestneat** [VSCodeVim/Vim#1294]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Given this text where the brackets indicate a visual selection:
Line before
hell[man's
lma]o world
Line after

Hit D (shift+d) to delete selected lines

### What did you expect to happen?

Lines with selection to be completely deleted:
Line before
Line after

### What happened instead?
vscodevim acted as if lowercase d was pressed:
Line before
hello world
Line after

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: Fedora 25

**Comment by kitwestneat** [comment]
I tested a bunch of other visual commands: X, C, S, R, p, I, and A also work differently than vim

**Comment by kitwestneat** [comment]
Thanks for the patch, it fixes the "D" issue for me.

**Comment by johnfn** [comment]
What patch?

**Comment by kitwestneat** [comment]
xlaech's commit (https://github.com/xlaech/Vim/commit/add6df8d462673f610151d3a89eca1910c2e5aa7)

**Comment by jpoon** [comment]
@kitwestneat so this is fixed now? Can we close?

**Comment by kitwestneat** [comment]
@jpoon the D issue is fixed, but X, C, S, R, p, I, and A also don't work correctly in visual mode. I don't use these keys normally, so it's not a big deal for me. I thought I'd let you all know though in case anyone wanted to take it on.

**Comment by xconverge** [comment]
Can you create a new issue for that? Are they all off the same way or weird quirks with each?

**Comment by kitwestneat** [comment]
X is off in the same way, if I remember right the others are more like weird quirks. I'll go through them again and record specifically what's wrong.

Would you prefer a single ticket or multiple tickets?

**Comment by xconverge** [comment]
a single ticket is fine, multiple would be great but in reality doesn't really matter, but atleast the ticket wont be closed until all are fixed

**Comment by kitwestneat** [comment]
cool, I opened them as 1304 -1308. I realized that I and A's behavior is only defined in Vim for visual block mode and only if visualextra is compiled in. The actual Vim behavior for those keys in regular visual select mode is kind of strange, so it doesn't make sense to me to emulate it, and so I skipped them.
