### ISSUE TITLE
Surround replacement of quotes adds unwanted whitespace

### ISSUE THREAD

**Issue by hmps** [VSCodeVim/Vim#1298]
Since commit https://github.com/VSCodeVim/Vim/commit/75e2cae798c384c48e9a94c7075117dd7bbff05c extra whitespace is added when using Surround to add / modify quotes.

-----

### What did you do?
`"Hello |World"`
Press: `cs"'`

### What did you expect to happen?
`"Hello World"` => `'Hello World'`

### What happened instead?
`"Hello World"` => `' Hello World '`

### Technical details:
In commit https://github.com/VSCodeVim/Vim/commit/75e2cae798c384c48e9a94c7075117dd7bbff05c, quotes were added to `PairMatcher` with `nextMatchIsForward` set to true. This causes the logic in `GetStartAndEndReplacements` (actions.ts) to add the whitespace.

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: macOS 10.12.3

**Comment by xconverge** [comment]
perfect investigation, I am not sure the best way to fix this but it is easily fixable. Will see what @johnfn thinks about the fixes in my pr

**Comment by hmps** [comment]
Hehe, that was a simple fix. Thank you so much for fixing that so promptly @xconverge!

⭐

**Comment by xconverge** [comment]
@hmps yea there were quite a few other improvements done to surround so it should be pretty solid now, I will take another pass in the future if there are more small things found
