### ISSUE TITLE
Slow paste with useSystemClipboard

### ISSUE THREAD

**Issue by chris-b1** [VSCodeVim/Vim#1299]
### What did you do?
Copying and pasting a line a of text  - `yy` then `p`.  Any file type.

When not using the system clipboard (`"vim.useSystemClipboard": false`) - the paste is nearly instant.

When `"vim.useSystemClipboard":true` the paste is significantly slower - on the order of 1 second.

From looking through past issues, it looks like https://github.com/xavi-/node-copy-paste is used to access the system clipboard, so possibly is an upstream issue?

Thanks.

### Technical details:

* VSCode Version:  1.9.1
* VsCodeVim Version: 0.5.3
* OS: Windows 7 64 bit

**Comment by chris-b1** [comment]
Thanks - that command is fast, but it looks like the issue is with the pasting code upstream.

```js
var ncp = require("copy-paste");

ncp.copy("Some text to the clipboard", function () { console.log("done") })  // fast

> ncp.paste()  // slow
'Some text to the clipboard'
```

I haven't looked deeply but they are using some vbscript to grab and parse data from the clipboard which is probably the slow link.

https://github.com/xavi-/node-copy-paste/blob/9897be123ca03e4946325270dcc80a5736a36cc7/platform/fallbacks/paste.vbs

**Comment by jpoon** [comment]
Great detective work @chris-b1.

**Comment by jpoon** [comment]
@xconverge's work to move to a different library should help with this: https://github.com/VSCodeVim/Vim/pull/1487
