### ISSUE TITLE
request "true" command/normal mode for VS Code

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#13]
Tracking this here. I suspect handling key strokes they way we're doing now doesn't cut it. There must be an explicit "command/normal" mode where key presses are not inserted as characters in the buffer.

Also, we need a block caret.

I don't think these things will block us for now, but I'm adding this issue to track this.

- [x] request command mode for VS Code
- [ ] request block caret

**Comment by jpoon** [comment]
Duping this against #19
