### ISSUE TITLE
c deletes first element of line

### ISSUE THREAD

**Issue by xlaech** [VSCodeVim/Vim#1302]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Use change (c) together with a selection until the first symbol of a line

e.g.:
["test|haha", "jojo"]
press "vj0c"

This also effects #1300 

### What did you expect to happen?

the selection without the first j of the second line get deleted and insert mode is entered

### What happened instead?

The j also got deleted

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: Windows 10

**Comment by Chillee** [comment]
@xconverge Is this actually a bug? Nvim seems to do the exact same behavior as what's reported in the bug.

**Comment by johnfn** [comment]
@Chillee I'm so confused. I was sure this was a legitimate bug, but now I can't seem to reproduce the behavior that OP says is correct!

**Comment by xlaech** [comment]
@johnfn If you checkout before the commit it works? oO

**Comment by johnfn** [comment]
Oh no I mean, I can't reproduce the behavior in Vim.

**Comment by xlaech** [comment]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 23 2017 19:48:19)
MS-Windows 32 Bit Konsolen-Version

Here i can do this
["ab|cdefg","abcdefg"]
-> vj0c
["ab|abcdefg"]

Before the patch the result would have been:
["abbcdefg"]

What do you get?

**Comment by Chillee** [comment]
For me, on both VIM version 8.0.427 and NVIM 0.1.7 on arch, I get ["ab|bcdefg"].

**Comment by xconverge** [comment]
VIM 8.0.586 on Win10x64 I get  ["ab|bcdefg"] as well. @xlaech can you try with vim -u to not load any of your settings

**Comment by xlaech** [comment]
I will try on thursday.
@Chillee I get the same on mac
