### ISSUE TITLE
Visual Mode Issues: C command

### ISSUE THREAD

**Issue by kitwestneat** [VSCodeVim/Vim#1305]
### What did you do?

Visually selected this text and pressed C, brackets represent the visual selection:
Line before
hell[man's
lma]o world
Line after

### What did you expect to happen?

In Vim, the selected lines are removed and the editor is placed in insert mode:
Line before

Line after

### What happened instead?

Nothing -- text was unaffected, and editor stayed in visual mode.

### Technical details:
* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: Fedora 25

**Comment by Chillee** [comment]
Fixed in https://github.com/VSCodeVim/Vim/issues/1322
