### ISSUE TITLE
Request - Keyboard pt-PT (QWERTY)

### ISSUE THREAD

**Issue by dagadbm** [VSCodeVim/Vim#131]
Hello guys,

Will you be impementing a pt-PT QWERTY keyboard any time soon?

Regards,

dagadbm

**Comment by jpoon** [comment]
I don't believe anybody is actively working on this.

**Comment by rosedo** [comment]
fr-FR (AZERTY) would need a lot of mappings! Why doesn't it just inherit the keyboard at least for insert, or use virtual keys or whatever works.

**Comment by jpoon** [comment]
Closing this issue as VSCode has made some great headway in handling international keyboards: https://github.com/VSCodeVim/Vim/issues/432. We've actually removed our own keyboard mapper in favor of letting VSCode handle the dirty work. 

If you don't think that is the case, please re-open this issue.
