### ISSUE TITLE
collapsed code is reopened when cursor tries to move down.

### ISSUE THREAD

**Issue by haasDev** [VSCodeVim/Vim#1310]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

press `zc` then `j`

### What did you expect to happen?

cursor to move down to line after collapsed code.

### What happened instead?

cursor moved to end of line just before ellipse and reopened code I had just collapsed.

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: Windows 10

**Comment by xconverge** [comment]
duplicate of #1004

**Comment by xconverge** [comment]
@johnfn I would close this since it is tracked in the other
