### ISSUE TITLE
This extension breaks the `Add Next Occurrence` command and shortcut

### ISSUE THREAD

**Issue by RodrigoRoaRodriguez** [VSCodeVim/Vim#1311]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do? (Version 1)
`test test`
In insert mode selected `test` with the mouse, then pressed cmd-d and finally backspace.

### What did you do? (Version 2)
`|test test`
In insert placed cursor at start (represented here as a pipe), then pressed cmd-d twice and finally backspace.

### What did you expect to happen?
`| |`
Two cursors (represented here as pipes)

### What happened instead?
`| test`
With this extension enabled`cmd-d` does nothing in insert mode.

### ~~What did you do? ~~
~~`test test`~~
~~In insert mode selected `test` with the mouse, select `Add Next Occurrence` in the menu bar and then press backspace.~~ 

### ~~What did you expect to happen?~~
~~`| |`~~
~~Two cursors (represented here as pipes)~~

### ~~What happened instead?~~
~~`| test|`~~
~~With this extension enabled `Add Next Occurrence` adds a second bugged cursor to the right that does not behave like the first one (inconsistent behavior between attempts in spite of same sequence of keypresses).~~

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: MacOS 10.12

Needless to say, all of the above work properly and consistently with the extension disabled.

**Comment by RodrigoRoaRodriguez** [comment]
Update:
For 
* VSCode Version: 1.10
* VsCodeVim Version: 0.6.13

The second issue described(the _Add Next Occurrence_ command) has been fixed but the first one (the shortcut being ignored) still applies.

**Comment by Chillee** [comment]
Does this issue still occur for you? I can't replicate it.

**Comment by RodrigoRoaRodriguez** [comment]
Update:
* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.18

This issue still applies for insert mode but does no longer seem to apply for normal mode.

**Comment by wildeyes** [comment]
Can confirm ctrl-d works in normal mode.
