### ISSUE TITLE
Clicking in Insert Mode changes view

### ISSUE THREAD

**Issue by xlaech** [VSCodeVim/Vim#1319]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Go into insert mode ["i"]
2. Type anything ["udiatrnedutraine"]
3. Click anywhere in the code

Put the exact keys you pressed.

### What did you expect to happen?

The cursor moves and stays in insert mode

### What happened instead?

The cursor did move and the program state stayed in insert mode.
But the cursor as well as the statusbar changed to normal mode.

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: Windows 10

**Comment by xconverge** [comment]
I can't repro this..

**Comment by xlaech** [comment]
Found the error. It was my own fault.
Had a setting: "vim.bindCtrlCommand = false" in my global config.

Don't remember why i put it there in the first place... but now it works 👍
