### ISSUE TITLE
Use VSCode native block cursor setting

### ISSUE THREAD

**Issue by markrendle** [VSCodeVim/Vim#132]
Adding this as a place-holder because there should be a new release of VSCode this weekend which provides a block cursor style out of the box.

**Comment by jpoon** [comment]
:dancers:

**Comment by jpoon** [comment]
I saw that the PR got merged but how does one use it and toggle between the different cursor styles?

**Comment by tma-isbx** [comment]
This sample project has the details: https://github.com/alexandrudima/vscode-vim
