### ISSUE TITLE
VisualMode selection off by one

### ISSUE THREAD

**Issue by xlaech** [VSCodeVim/Vim#1321]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

As i was writing the tests for my fix of #1308, my tests failed on a line difference in the selection.
Trying out a few things i realized that the selection in visual mode over multiple lines is of by one at the end (compared to other vim versions).

Is this on purpose or a bug?

Example

fir|st line
second line

Press: vj

### What did you expect to happen?

In vim 8.0 on windows this will select:
"st line\r\nse"

### What happened instead?

it selected
"st line\r\nsec"

### Technical details:

* VSCode Version: 0.5.3
* VsCodeVim Version: 1.9.1
* OS: Windows 10

**Comment by xlaech** [comment]
Maybe it is an Implementation issue.

In bash for windows (which is based on ubuntu) it select the "c"

**Comment by johnfn** [comment]
I don't see this behavior.

If the block cursor selects the "r" in `first line`, then vjy copies "st line\r\nsec" in my copy of Vim.

**Comment by xlaech** [comment]
Hm... I just double checked. Which version are you using? I get the different behavior in 

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2016 17:05:36)
MS-Windows 32 Bit Consol-Version
```

**Comment by tail** [comment]
Tested NVIM 0.1.7 and VIM 7.4 both on Ubuntu 16.04 without any configs and this is what I see:

![example](https://dl.dropboxusercontent.com/u/153/scrot/2017-02-23_220452_DgyECqsd.png)

which matches the behavior in the plugin currently and of the test:

      start: ["fir|st line", "second line"],
      keysPressed: "vjx",
      end: ["fir|nd line"],

**Comment by johnfn** [comment]
@xlaech, could you take a picture of what happens when you do the same thing as @tail?

**Comment by xlaech** [comment]
Yep. I am now on a mac, where i get the same behaviour as tail. I make a screenshot tomorrow on the windows pc.

**Comment by xlaech** [comment]
After selecting the cursor blinks on the c of "second".
Any action with the selection will not use the c.

![vim-selection-blick-off](https://cloud.githubusercontent.com/assets/8291938/23345568/aa6f4a10-fcd3-11e6-8261-8c77f4ce55d4.png)
![vim-selection-blick-on](https://cloud.githubusercontent.com/assets/8291938/23345569/aa709528-fcd3-11e6-8f38-6cb4afc70076.png)

For example after yanking the selection and pasting it a few lines down i get this:
![vim-selection-yank-paste](https://cloud.githubusercontent.com/assets/8291938/23345592/0373044e-fcd4-11e6-871a-d53c16a893a8.png)

**Comment by xconverge** [comment]
I am still not following at all, and I think you have some cursor discrepancies with our notation

When you say ```fir|st line```, that is not the same selection that you have in your screen shots

If in normal, and you press i, that is where the cursor is and is represented by a bar, the beginning of the block is the cursor position represented by |

Are you sure you don't have something funky in your .vimrc that does this? if the cursor is blinking on the c, it includes/yanks the c for me

tested on gvim, macvim, vim that comes with git bash...

**Comment by xlaech** [comment]
You name it... I don't now where, but when i started vim without any .vimrc

`vim - u NONE`

I got the expected behavior.

PS: I just accidentally did another selection :)

**Comment by xconverge** [comment]
Well it's definitely something only in your windows one ;)
