### ISSUE TITLE
Key bindings in Markdown Preview

### ISSUE THREAD

**Issue by joeyaiello** [VSCodeVim/Vim#1326]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Opened a raw Markdown file
2. `Ctrl+Shift+V` to open a preview rendering of that Markdown file
3. Hit `j` (or `khl`)

### What did you expect to happen?

I expected the preview rendering to scroll down (or up/left/right)

### What happened instead?

Nothing

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: Windows 10 Anniversary Update

**Comment by rebornix** [comment]
Markdown preview is embedded in a webview and it's actually pure HTML Dom. It's not line based as the editor and probably we should scroll by block elements, but Code should allow us to send commands to the webview to archive that.

**Comment by jpoon** [comment]
Please file a feature request against VSCode. The vim extension does not have any ability to interact with the MD preview.
