### ISSUE TITLE
Markdown preview jumps after every keystroke (insert mode).

### ISSUE THREAD

**Issue by b0wter** [VSCodeVim/Vim#1328]
### What did you do?
I created a new file and saved it with the markdown file extension. Then I opened the preview in a split pane and started entering text.

### What did you expect to happen?
Regular behaviour of the markdown preview: always focussing the part of the text that I am currently editing.

### What happened instead?
After every keystroke (in the insert mode) the preview jumps to the first line of the markdown file. Entering another character makes the preview jumps to the correct section of the text for a split second and then focusing the first line of the document again.

### Technical details:
I've updatet the plugin today. I've previously never encountered this issue despite using markdown heavily.
Disabling the vim plugin makes the preview behave correctly.
I've tested this with new files and older files that used to work flawlessly.

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.1.10
* OS: Windows 7

**Comment by jpoon** [comment]
@b0wter can you update to the latest VsCodeVim?

**Comment by b0wter** [comment]
Thanks. I've had to reinstall the extension and everything works flawlessly now. I have no idea why vs code wouldn't offer me to update to the latest version.
Thanks for your help and a great extension :)
