### ISSUE TITLE
Bug in exact word match

### ISSUE THREAD

**Issue by rhys-vdw** [VSCodeVim/Vim#1334]
I introduced a bug in #1277. Exact search now uses a regex, but fails to escape the string first.
I will fix this error eventually, but I'm a bit busy right now, so feel free to beat me to it. Should just be a regex escape on [this line](https://github.com/VSCodeVim/Vim/pull/1277/files#diff-7addcd1a8a241060a73b1fe4abb39960R1580) and corresponding test.

-----

### What did you do?

Press `*` or `#` on a word composed of non-word characters (eg. `.`, `$` or `^`).

### What did you expect to happen?

Find next word-character word and search for that, if there is no such word then search for the non-word-character word under the cursor.

(see https://github.com/VSCodeVim/Vim/issues/1334#issuecomment-283816936)

### What happened instead?

Searches for end of line (regex `$`).

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: OSX Sierra

**Comment by johnfn** [comment]
Believe it or not that's not how Vim works. It looks to me like when you have a cursor over a non-word (e.g. $), it searches forward until it finds a word, and then does * on that word instead. 

(I tried your proposed solution, but it actually doesn't work either because \b does not consider the start of $ to be a word boundary, since $ isn't a word. Bleh! Weirdness all around.)

**Comment by rhys-vdw** [comment]
Ah, interesting! Actually it seems Vim's behaviour is a bit more nuanced than that.

![vim-dollar](https://cloud.githubusercontent.com/assets/822105/23531285/dcc8f474-fff9-11e6-8cb4-60d05c1e3f86.gif)

![vim-dollar-dollar-dollar](https://cloud.githubusercontent.com/assets/822105/23531739/124da836-fffc-11e6-84aa-2fc45c3fa4a1.gif)

![vim-chars](https://cloud.githubusercontent.com/assets/822105/23531757/322d258c-fffc-11e6-97fb-4f6d44a3865c.gif)


If the `$` (or any number of `$`s) is the last "word" in the line it will search for it. Otherwise it will just to the next word and search for it. Weird. I don't know how faithfully this behaviour should be followed.

Currently (thanks to my changes). These things happen:

| character | regex | behavior |
|----|----|----|
| `^` | `\b^\b` | Matches start of line |
| `$` | `\b$\b` | Matches end of line |
| `.` | `\b.\b` | Matches any character between words (typically `.` or ` `) |

Does this seem like an accurate summary?

- The "current word" should not include non-word-character strings (`"$" or "^"`) unless they are the last string in a line. It should however include all characters of a string of non-word characters.
- The exact word match regex should escape the "current word" regex in case it contains special characters.
- The word boundaries should not be `\b`, but should be something like: `[\W^]search_term[\W$]`

I believe addressing those issues would resolve this completely.

**Comment by J-Fields** [comment]
This has been fixed
