### ISSUE TITLE
surround adding spaces when changing from double to single quote

### ISSUE THREAD

**Issue by daveremy** [VSCodeVim/Vim#1336]
### What did you do?

Press `cs"'` inside

    "Hello world!"

### What did you expect to happen?

I expect it to change it to:

    'Hello world!'

### What happened instead?

however it changes to:

    ' Hello world! '

### Technical details:

* VSCode Version:  1.9.1
* VsCodeVim Version: 0.5.3
* OS:  Windows 10

**Comment by xconverge** [comment]
This was already fixed on master and will be in the next release
