### ISSUE TITLE
vi" (as well as others), not selecting the last character

### ISSUE THREAD

**Issue by josiahbgrace** [VSCodeVim/Vim#1337]
### What did you do?

<img width="1025" alt="screen shot 2017-02-27 at 12 37 32 pm" src="https://cloud.githubusercontent.com/assets/3061661/23379037/3284197e-fcea-11e6-8267-20982863a148.png">

**Pressed**
vi"
vi)
vi}

### What did you expect to happen?

select inside of all of the matching characters

### What happened instead?

selected everything except the last character

### Technical details:

* VSCode Version: Insiders 1.10
* VsCodeVim Version: *0.5.3*
* OS: El Capitan

**Comment by josiahbgrace** [comment]
In the screenshot, I ran the vi* command, and the pasted the result below it. Hopefully that is clear.

**Comment by johnfn** [comment]
But the last character *is* selected. If you do e.g. y, d etc there's no effective difference.

**Comment by josiahbgrace** [comment]
Hm, I guess that's a good point. I frequently use standard "cmd+c" and "cmd+v" as part of my workflow (because of alfred clipboard history XD), so the vi* commands not selecting the last character is pretty frustrating. But I understand if this is intended behavior.

**Comment by johnfn** [comment]
You can turn our use system clipboard setting to on, and then y will copy directly to the clipboard. 

But yeah, cmd-c not working is definitely a bug.

**Comment by josiahbgrace** [comment]
Wow, that was quick. Thank you! This will help me out a ton. Also, in general, this is a fantastic extension 😀

**Comment by johnfn** [comment]
Thank you! 😄
