### ISSUE TITLE
:sort not supported

### ISSUE THREAD

**Issue by jordan-heemskerk** [VSCodeVim/Vim#1341]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Run the command `:sort`

### What did you expect to happen?

The entire file is sorted alphabetically. See [Sort lines](http://vim.wikia.com/wiki/Sort_lines).

### What happened instead?

Nothing.

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: Windows 10

I use this feature a lot and it would be super helpful to have in VSCode. I'll try to make a Pull Request, but I've never worked in TypeScript before.

**Comment by johnfn** [comment]
Have you considered using something like https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines?

If that doesn't work for you, then by all means make a PR. :)

**Comment by jordan-heemskerk** [comment]
Gave it a shot, let me know what you think.
