### ISSUE TITLE
Travis build fails on other branches

### ISSUE THREAD

**Issue by misoguy** [VSCodeVim/Vim#1343]
### What did you do?
Saw the build failing on another branch

### What did you expect to happen?
Travis to test build only on master branch or only on branches that are on the safelist

### What happened instead?
Seems like Travis CI builds on every branch on the repo

**Comment by misoguy** [comment]
Not really sure if this was intended so i'll just make a short PR including master into the safelist

**Comment by johnfn** [comment]
This is intentional so that when you create a PR we know if it's passing or failing before we merge it. :)
