### ISSUE TITLE
Issue with merge conflicts in Git view and vim plugin - Cannot edit files

### ISSUE THREAD

**Issue by mmckeaveney** [VSCodeVim/Vim#1344]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
- Went to the Git view of VSCode after picking up some merge conflicts
- Choose a file with a merge conflict
- Unable to edit files when the vim plugin is enabled

### What did you expect to happen?
- I should be able to edit files as normal

### What happened instead?
- I could not edit or even move the cursor.
- This was resolved when I reloaded VSCode without the plugin.

### Technical details:
I'd be happy to submit a PR if someone could point me in the right direction :) 

* VSCode Version: 1.9.1
* VsCodeVim Version: *0.5.3*
* OS: Mac OSX El Capitan - 10.11.5

**Comment by jpoon** [comment]
Can't repro. Opened a file `code --diff <file1> <file2>` and through the git diff viewer. Able to edit with the vim extension running.
