### ISSUE TITLE
v_D command is not supported

### ISSUE THREAD

**Issue by ladace** [VSCodeVim/Vim#1345]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Delete lines in visual mode.
`v <down> D`

### What did you expect to happen?

Delete two entire lines that are highlighted.

### What happened instead?

Only highlighted text are deleted.

### Technical details:

* VSCode Version: 1.9.1
* VsCodeVim Version: 0.5.3
* OS: OSX 10.12.3

**Comment by johnfn** [comment]
This is fixed in master and will be released very soon.
