### ISSUE TITLE
Last character missing when using ve -> copy to clipboard

### ISSUE THREAD

**Issue by sgronblo** [VSCodeVim/Vim#1347]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

<cursor here>hello

Press v e to for selecting to the end of the word in visual mode. Press cmd-c to copy the text to clipboard. Press esc to get out of visual mode. Go to another line in VSCode. Press cmd-v to paste the copied contents.

### What did you expect to happen?

I expect the whole `hello` text to be pasted when pressing cmd-v.

### What happened instead?

Only `hell` is pasted. If you use y to yank the visual selection and then use p to paste it inside of VSCode `hello` is correctly pasted. But sometimes you want to copy to the clipboard for pasting into other applications.

### Technical details:

* VSCode Version: Version 1.10.0 (1.10.0)
* VsCodeVim Version: 0.5.3
* OS: MacOS Sierra 10.12.3

**Comment by johnfn** [comment]
There is actually a fix for this in master. I just need to get it to work on all platforms, which is a pain.

**Comment by johnfn** [comment]
And now I have it working but the internet in Indonesia is so bad I've been unable to push it. Hah. 

Some day soon you will have a beautiful working copy again.
