### ISSUE TITLE
I cant write ;

### ISSUE THREAD

**Issue by imacnu** [VSCodeVim/Vim#135]
In spanish keyboard not is posible write ; instead visual code whir this extension write <

**Comment by magbeat** [comment]
The same happens with a german keyboard layout.

**Comment by jpoon** [comment]
Related to https://github.com/VSCodeVim/Vim/issues/128

**Comment by frarees** [comment]
@imacnu can you try #169?

**Comment by frarees** [comment]
@imacnu fix included in the lastest published version (v0.0.12).

**Comment by imacnu** [comment]
Yeeeeeees it works. Thank you so much!!
