### ISSUE TITLE
Setting vim.leader in settings.json does not work: "Unknown configuration setting"

### ISSUE THREAD

**Issue by jnachtigall** [VSCodeVim/Vim#1353]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

I wanted to change `vim.leader` to " " (space) in my settings.json. However, the settings takes no effect. In fact, VSCode tells me that it is an invalid setting.

![vimleader](https://cloud.githubusercontent.com/assets/3307404/23544652/18bfd5da-fff8-11e6-8fed-9989dd727ac1.png)

### Technical details:

* VSCode Version: 0.4.2
* VsCodeVim Version: 1.10.1
* OS: Windows 10

**Comment by jnachtigall** [comment]
Works with 0.6.0 (which just showed up a minute ago)

**Comment by johnfn** [comment]
That's weird because I don't remember fixing it, but hey! 😁

**Comment by jnachtigall** [comment]
@johnfn haha, procastination solves all kinds of problems ;)
