### ISSUE TITLE
Ctrl+C do not leave Insert mode

### ISSUE THREAD

**Issue by digaev** [VSCodeVim/Vim#1354]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Go to Insert mode and press ctrl+c.

### What did you expect to happen?

Leave Insert mode.

### What happened instead?

Stayed in Insert mode.

### Technical details:

* VSCode Version: 1.10.1
* VsCodeVim Version: 0.6.0
* OS: Fedora Workstation 25

**Comment by johnfn** [comment]
Sorry about that. Just pushed out a new version with a fix.
