### ISSUE TITLE
Copying backwards in insert mode doesn't work.

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1355]
?????

Somehow, the selection is removed before I can get to it?

**Comment by yhdleung** [comment]
This bug is quite annoying.

I cannot copy with `Ctrl + C` on the selections from right to left, or upward using the keyboard (e.g. `Shift + Left/Up Arrow`, or `Shift + Home`), when this extension is turned on.
User setting : `"vim.useCtrlKeys": false`

Copying works fine if selected by mouse.

**Comment by oliverguenther** [comment]
Can confirm. This appears to be a recent regression (or caused by a VS code update), I only experience this recently.

**Comment by prashantv** [comment]
Running into the same issue, I captured my desktop+keyboard to show the bug:
![copy-left-bug](https://cloud.githubusercontent.com/assets/140159/25035351/f2746088-20a1-11e7-8f3e-b92cb7ca9044.gif)

When I select text going left, copy and paste (using the keyboard), it doesn't work. However if I select the text going right, copy+paste works fine.

**Comment by khalidadil** [comment]
This is an issue for me as well.

![screen recording 2017-04-17 at 12 55 pm](https://cloud.githubusercontent.com/assets/2343076/25098198/3b5e7be4-236d-11e7-9c39-e4728c7f734e.gif)
