### ISSUE TITLE
Not respecting the cusor-style value

### ISSUE THREAD

**Issue by harryio** [VSCodeVim/Vim#1356]
### What did you do?
Changed custor style to line-thin in user settings.

### What did you expect to happen?
The cursor to be thinned down in insert mode.
### What happened instead?
Cursor width remained the same; upon disabling VSCodeVim entirely, the expected behaviour is exhibited by vscode.
### Technical details:

* VSCode Version: 1.10
* VsCodeVim Version: latest
* OS: Linux

**Comment by xconverge** [comment]
fixed in master
