### ISSUE TITLE
Better support for _ register

### ISSUE THREAD

**Issue by ryanmcnamara** [VSCodeVim/Vim#1357]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

with the text
```
asdf
qwer
```
press keys `yyj"_ddkp`

Expected content:
```
asdf
asdf
```
Actual content:
```
asdf
qwer
```

It doesn't appear that the plugins supports registers

**Comment by johnfn** [comment]
We do support registers - my guess is that we don't support that particular register, so we default to the normal register.

**Comment by ryanmcnamara** [comment]
Oh I see! My mistake, I just didn't try any others.

**Comment by iliekturtles** [comment]
For reference: [Black hole register](http://vimdoc.sourceforge.net/htmldoc/change.html#quote_)

**Comment by jpoon** [comment]
Seems like this is as designed?

**Comment by ryanmcnamara** [comment]
@jpoon not sure what you mean, the "_" register should not insert into the default register (it should be a black hole).
My misunderstanding was just about register support in general, the "_" register is still not properly supported

**Comment by jpoon** [comment]
Ah, sorry. I mis-read this all :/

**Comment by xconverge** [comment]
How about that ;) It popped up on my feed so why not :)
