### ISSUE TITLE
Multi line remove with backspace is only removing first occurrence

### ISSUE THREAD

**Issue by sethstha** [VSCodeVim/Vim#1358]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Selected multiple lines using `ctrl + d` or using cursor and pressed backspace

### What did you expect to happen?
To remove all the selected occurrence.
![withdelete](https://cloud.githubusercontent.com/assets/2367137/23577565/dcf1b9bc-00ea-11e7-8dad-8fe6cea58353.gif)

### What happened instead?
Only removed first occurrence
![withbackspace](https://cloud.githubusercontent.com/assets/2367137/23577564/d58958b0-00ea-11e7-99e1-9315dc7a2280.gif)
If then used `ctrl + z` to undo and backspace it will remove the entire line of first occurrence.

### Technical details:

* VSCode Version: 1.10.1
* VsCodeVim Version: 0.6.0
* OS: Windows 10

**Comment by sethstha** [comment]
Update: if someone is facing the same issue, you can simply use `ctrl+backspace` or `delete`

**Comment by andradei** [comment]
I hope this behavior is implemented soon. This is a great plugin.
