### ISSUE TITLE
Unable to dismiss the parameter info intellisense without using the mouse.

### ISSUE THREAD

**Issue by shaunluttin** [VSCodeVim/Vim#1360]
### What did you do?

While editing C# code with OmniSharp, I typed a class name and a method name. As expected, the intellisense showed the method's parameter info. I pressed escape to return to normal mode and began to use the directional keys to navigate my code.

### What did you expect to happen?

I expected the parameter info to go away.

### What happened instead?

The parameter info box followed my cursor around the page and displayed the parameter info for whatever method the cursor was inside. The workaround for dismissing the parameter info box is either 1. to mouse click somewhere on the page or 2. to move the cursor to a location that has no parameter info.

### Technical details:

* VSCode Version: 1.11.0-insider
* VsCodeVim Version: 0.6.2
* OS: Windows 10

**Comment by xconverge** [comment]
Is this still happening? I am using insider and don't see this

**Comment by johnfn** [comment]
I see it. You have to type `methodName(x` where x is some random character. Then the parameter info won't go away. 

It's pretty annoying.

**Comment by bill-mybiz** [comment]
A couple additional points: 
* This happens for me when using TypeScript, VsCode 1.11.2, VsCodeVim: 0.6.18, OS: Ubuntu 16.04. 
* When disabling the extension, the escape key does dismiss the info as expected.
  * I have caps lock mapped to escape.
  * Neither caps lock nor escape proper dismiss it.

**Comment by cobbweb** [comment]
I use `shift+esc` to close annoying messages, seems to work here too and keeps me in insert mode. VSCode is telling me this is a default mapping.

**Comment by Chillee** [comment]
I think @cobbweb 's solution is good enough for this. I think we should close this and maybe add it to the README or something.
