### ISSUE TITLE
Debugger overrides cursor style

### ISSUE THREAD

**Issue by ruskakimov** [VSCodeVim/Vim#1363]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
1. Set breakpoint
2. Launch debugger
3. Step though the code
4. Cursor style is changed to the **default thin one**.

### What did you expect to happen?
Vim-style cursor at all times.

### What happened instead?
Cursor changes to the **default thin one**, when you step through the code with debugger.

### Technical details:

* VSCode Version: 1.10.1
* VsCodeVim Version: 0.6.2
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
I use the debugger all the time, and I never see the thin cursor. That's weird!

**Comment by xconverge** [comment]
I am going to close this since I have not seen it and a lot has changed since it was filed. Please reopen if you are still seeing it! Thanks!
