### ISSUE TITLE
when ctrl + c presses, Error copying to clipboard!

### ISSUE THREAD

**Issue by newforrestgump001** [VSCodeVim/Vim#1365]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Put the exact keys you pressed.

### Technical details:

* VSCode Version:
* VsCodeVim Version: *[please ensure you are on the latest]*
* OS:

**Comment by johnfn** [comment]
Can you please fill out the template? At least the technical details part.

Also, did the error tell you to set `overrideCopy` to false? If so, did you do so? If so, what happened?

**Comment by newforrestgump001** [comment]
Thank you very very much, after setting overrideCopy to false, 
everything goes well.

Thanks,

Jack

**Comment by johnfn** [comment]
Glad to hear it! Could you please let us know what OS you are on?

**Comment by newforrestgump001** [comment]
Thanks, I worked on Ubuntu 16.04.
