### ISSUE TITLE
Randomly Deleting Multiple Characters Unexpectedly under Insert Mode

### ISSUE THREAD

**Issue by iFwu** [VSCodeVim/Vim#1370]
### What did you do?
When change to another splited editor panel (which is in Insert Mode) , deleting the end of line may cause deleting another line unexpectedly.
It happens randomly when enabled vim plugin. I don't know how to reproduce this problem exactly.

### What did you expect to happen?
Just delete the character before cursor.

### Technical details:

* VSCode Version: 1.11.0-insider (1.11.0-insider)
* VsCodeVim Version:  latest
* OS: macOS 10.12.3 (16D32)

**Comment by xekri** [comment]
It seems like bug with VSCode itself, closed.

**Comment by jpoon** [comment]
If you get a repro, please share. I don't see this so at this point it's pretty hard to debug.

**Comment by Chillee** [comment]
I'm actually pretty sure I've seen this before.
