### ISSUE TITLE
Support search and replace using last search term

### ISSUE THREAD

**Issue by rhys-vdw** [VSCodeVim/Vim#1373]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Vim supports a shorthand for search and replace. If you leave the match pattern empty it should do a literal match against your last search. This is handy because you can use `*` or `#` on an identifier to skip writing it precisely in the `%s` pattern.

### What did you do?

document:
```
hello hello
```

keys:
```
/hello<enter>:%s//goodbye/g
```

### What did you expect to happen?

document:
```
goodbye goodbye
```

(matches previous search term `hello`)

### What happened instead?

document:
```
goodbyehgoodbyeegoodbyelgoodbyelgoodbyeogoodbye goodbyehgoodbyeegoodbyelgoodbyelgoodbyeogoodbye
```

(matches empty string)

### Technical details:

* VSCode Version: 1.10.1
* VsCodeVim Version: 0.6.2
* OS: OSX Sierra

**Comment by xconverge** [comment]
Ah this should be easy, since we have the search history already ( doing /<enter>, or /<updown> etc)

**Comment by rhys-vdw** [comment]
Yeah, I figured as much. It's a handy feature to have.

**Comment by rhys-vdw** [comment]
Thanks @xconverge! 👍
