### ISSUE TITLE
It would be really awesome if c-w h and c-w l would navigate between other panes

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1375]
Like if I could navigate to search results, or the terminal in the bottom.

**Comment by mightyiam** [comment]
Because that's how it works in vim. And I don't always wanna have to know the specific key binding of jumping to a specific thing.

**Comment by xconverge** [comment]
https://code.visualstudio.com/updates/v1_11#_navigate-between-views

**Comment by mightyiam** [comment]
Perhaps assign something reasonable to these by default?
