### ISSUE TITLE
Issue with visual line select mode and 'gj'

### ISSUE THREAD

**Issue by rufusroflpunch** [VSCodeVim/Vim#1377]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
### What did you do?

1. Enter visual line selection mode: `V`
2. Use `gj`  to move between wrapped lines.

### What did you expect to happen?

The selection to extend as many lines as required.

### What happened instead?

The selection doesn't extend past three lines.

![example gif of bug](http://i.giphy.com/xUPGcKBfdlzYeuoyDC.gif)

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.2
* OS: macOS Sierra

**Comment by johnfn** [comment]
As a temporary solution, you can remap `j` to `gjo`. 😉  But I think @xconverge has a better solution coming soon.

**Comment by xconverge** [comment]
related https://github.com/Microsoft/vscode/issues/23045

I should be able to work through this with what we have so far right now though, but it might not be pretty

**Comment by xconverge** [comment]
Also we need to make sure the when we expand and shrink the selection, it works similar to how V with j and k work.

Currently, it seems like if you do V then gk gk gk gk, when you do gj, it will expand from the bottom, instead of shrinking the selection by 1 line
