### ISSUE TITLE
Count commands do not honor `otherModesKeyBindingsNonRecursive` settings

### ISSUE THREAD

**Issue by davesque** [VSCodeVim/Vim#1378]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I have the following settings:

```
{
    "vim.otherModesKeyBindingsNonRecursive": [
        {"before": ["n"], "after": ["j"]},
        {"before": ["e"], "after": ["k"]}
    ]
}
```

I then issue `12e` in normal mode in an editor window.

### What did you expect to happen?

I expect for the cursor to move up 12 lines.

### What happened instead?

The cursor moves to the next word ending 12 times.

### Technical details:

* VSCode Version: Current insider
* VsCodeVim Version: Latest
* OS: OS X

**Comment by xconverge** [comment]
This is the same as #1359 I believe

**Comment by xconverge** [comment]
looks to be fixed on master from that pr merged in
