### ISSUE TITLE
Executing a macro that runs many operators creates many undo points

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1382]
It should only create one.

**Comment by xconverge** [comment]
We have a isReplayingMacro so this should be easy

**Comment by xconverge** [comment]
Adding this to modeHandler.ts gets close...however we want to create 1 undo point whenever we initiate a macro replay (only 1 undo point whether we do @1, or 5@1 to replay macro)
```
    ranRepeatableAction = ranRepeatableAction && !vimState.isReplayingMacro;
```
