### ISSUE TITLE
The 'jump to n percentage of file' function seems not working

### ISSUE THREAD

**Issue by DrakeXiang** [VSCodeVim/Vim#1385]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Put the exact keys you pressed.
50%

### What did you expect to happen?
Jump to the middle of current file

### What happened instead?
The cursor is no where near the middle of file

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: v0.6.3
* OS: windows 10.0.14393

**Comment by johnfn** [comment]
If you just type `50%` you're going to be repeating the percentage motion 50 times.

I assume you did that in the exec window?

**Comment by johnfn** [comment]
Oh wow nevermind. Looks like that's a special case of the percentage motion. 

Learn something every day. :D

**Comment by johnfn** [comment]
This has been added in 0.6.4.
