### ISSUE TITLE
Change log link to release text.

### ISSUE THREAD

**Issue by jesterKing** [VSCodeVim/Vim#1395]
Please add change log links to the (future) release texts as well, i.e.

https://github.com/VSCodeVim/Vim/compare/v0.6.4...v0.6.5, or with link text [Change log](https://github.com/VSCodeVim/Vim/compare/v0.6.4...v0.6.5)

That makes it so much easier to find out what has changed between the releases.

**Comment by johnfn** [comment]
Which release texts are you referring to?

**Comment by jesterKing** [comment]
The release descriptions here: https://github.com/VSCodeVim/Vim/releases

These are the release texts linked to from the vs code extension changelog section in vs code.

**Comment by johnfn** [comment]
You mean my little descriptions aren't helpful??? 😛 

The whole point of me writing them up was so we couldn't have to refer you to the v0.6.4...v0.6.5 thing which is just a barrage of commit messages that no one except maybe me, @rebornix and @xconverge can read.

**Comment by jesterKing** [comment]
You can add me to the list :-)

Those not interested can just not click the link. I prefer to have easy access to the commit history.

**Comment by jpoon** [comment]
This isn't currently supported by Travis (https://github.com/travis-ci/travis-ci/issues/6423) so we'll have to do it manually every time we do a release :(

**Comment by jpoon** [comment]
We're doing this manually. Closing this issue.
