### ISSUE TITLE
Adding new line below or above cursor without entering insert mode

### ISSUE THREAD

**Issue by jnachtigall** [VSCodeVim/Vim#1396]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Often I'd like a add a new line below or above code. Similar to http://stackoverflow.com/a/16136133/1129950 or [vim.unimpared]( https://github.com/tpope/vim-unimpaired) (with `[<Space> and ]<Space> add newlines before and after the cursor line`). 

After talking in slack (I just saw it know after the weekend) I guess for VSCodeVim my best chance might be this: In normal mode `<leader> o` adds a line below cursor putting me in Insert mode. And  `<leader> O`  does the same above the cursor.

I added this to my `settings.json`:
```
  "vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": [ "<leader>", "o" ],
      "after": ["o", "<Esc>", "k"]
    }
  ],
  "vim.leader": " ",
```

### What did you expect to happen?
After reading the docs I thought that this would work...

### What happened instead?
...but pressing Space+o does not jump back to the exact same position as before, but instead to the beginning of the line.

I think in case this is something that we can get working, then it could be something for the README, like there is an example for `ZZ` already.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.5
* OS: Windows 10

**Comment by ecbrodie** [comment]
@jnachtigall @rebornix this is still an issue on my VS Code installation. It is actually a big pain and often leads me running back to JetBrains IDEs to edit code because their VIM emulation supports my bindings on Enter and Shift-Enter to add newlines before or after the current line without entering Insert Mode.

**Comment by jpoon** [comment]
the configuration that @jnachtigall shared seems to work now? Please re-open this issue if that is not the case.

**Comment by oresttokovenko** [comment]
@jpoon Interesting I just found this thread because I had the same requirement for a vim motion in vs code vim but it doesn't seem to work for me

```
   "vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": [ "<leader>", "o" ],
      "after": ["o", "<Esc>", "k"]
    },
    {
      "before": [ "<leader>", "O" ],
      "after": ["O", "<Esc>", "j"]
    }
    ],
```

**Comment by erikw** [comment]
@jpoon please re-open the issue. This is still not working. The cursor jumps back to the the beginning of the original line, not at the same column.

```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [ "<leader>", "o" ],
      "after": ["o", "<Esc>", "k"]
    }
  ],
```


I've tried all kinds of different alternatives to get back to the original position without success, includng

```
"commands": ["editor.action.insertLineAfter", "workbench.action.navigatePreviousInEditLocations"]
-or-
"commands": ["editor.action.insertLineAfter", "workbench.action.navigateBack"]
-or-
"after": ["o", "<Esc>", "g;", "g;"]
-or-
"after": ["o", "<Esc>", "<CR>o"]
-or-
"after": ["o", "<CR>u", "<Esc>", "<CR>o"]
```
