### ISSUE TITLE
Support for \L, \U, \l, \u in regex replacements

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [VSCodeVim/Vim#1401]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
regex replacement with and without a selection included
all key combos tried listed here https://superuser.com/questions/1189693/how-does-one-lowercase-regex-replace

In VsVim I've tried `:s/(\w)/ +`

 - `\L1`
 - `\l1`
 - `\L$1`
 - `\L$1\e`
 - `\L$1\e`
 - `\L\1`

### What did you expect to happen?
first word character found would be come lowercase

based on http://www.regular-expressions.info/replacecase.html and/or http://vim.wikia.com/wiki/Switching_case_of_characters

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.6
* OS: Windows 10

**Comment by Chillee** [comment]
The regexes linked [here](http://vim.wikia.com/wiki/Switching_case_of_characters) work with the new PR https://github.com/VSCodeVim/Vim/pull/1725

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).
