### ISSUE TITLE
Changing the open tab changes cursor to non-block

### ISSUE THREAD

**Issue by rufusroflpunch** [VSCodeVim/Vim#1404]
### What did you do?

In normal mode with a block cursor, I switched tabs (both with hotkeys and with clicking on the tab).

### What did you expect to happen?

I expected the cursor to remain in block mode.

### What happened instead?

The cursor switched back to non-block cursor (while still remaining in normal vim mode).

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.6
* OS: macOS sierra

**Comment by yustnip** [comment]
The same on Ubuntu 16.04.2 (VS Code: 1.10.2, VsCodeVim: 0.6.6). When I click on the tab title the cursor changed to non-block mode.

**Comment by johnfn** [comment]
Fixed in 0.6.7.
