### ISSUE TITLE
Motion keys {h,j,k,l} don't move more than one position upon holding down

### ISSUE THREAD

**Issue by frewsxcv** [VSCodeVim/Vim#1407]
### What did you do?

At the top of a multi-line file, hold down `j`.

### What did you expect to happen?

Cursor would move one line at a time towards the bottom

### What happened instead?

Cursor moves one line, then stops.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.5
* OS: macOS 10.12.3

**Comment by johnfn** [comment]
Does this solve your problem? https://github.com/VSCodeVim/Vim#j-k-and-others-dont-repeat-when-i-hold-them-down

If so, could we have made it more visible somehow?

**Comment by frewsxcv** [comment]
Yeah, that fixed it, I figured it was related to that macOS feature. Ideally that macOS 'press and hold' feature would be enabled whenever one is on insert mode, but that doesn't sound like a very easy task.

I unfortunately don't have any great ideas right now regarding how to make that more visible. 

Thanks again for the help!

**Comment by Yathi** [comment]
Hi! I have the same issue. And I am unable to find the fix. The link in @johnfn 's comment just takes me to the root github page.

**Comment by Chillee** [comment]
@Yathi Here's thew new link! https://github.com/VSCodeVim/Vim#mac-setup

**Comment by joshuawootonn** [comment]
New link:https://github.com/VSCodeVim/Vim#mac

**Comment by josnin** [comment]
> New link:https://github.com/VSCodeVim/Vim#mac

last item didn't work for me 
```bash 
$ defaults delete -g ApplePressAndHoldEnabled
# it shows
2024-05-04 11:19:41.062 defaults[51428:2003847] 
Domain (kCFPreferencesAnyApplication) not found.
Defaults have not been changed.
```

this works for me
```bash
defaults write -g ApplePressAndHoldEnabled -bool false
```
