### ISSUE TITLE
How can i create custom keybindings?

### ISSUE THREAD

**Issue by notiv-nt** [VSCodeVim/Vim#1409]
How can i bind action `shift+4` (move to end of line) on `n` key? Or remap any keys for any actions?

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.10
* OS: Win 10 Pro

**Comment by johnfn** [comment]
Please refer to our README which has a ton of helpful examples. If you can't figure it out from there, let me know!
