### ISSUE TITLE
Keybindings not working in 10.0.2

### ISSUE THREAD

**Issue by theduke** [VSCodeVim/Vim#1410]
VsCode: 10.0.2
Vim: 0.6.10

I tried to map `<leader>s` to save file and `<leader>q` to close file.

When I enter `<space>`, the status bar shows `<leader>`, but after pressing `q` or `s` nothing happens at all. (`<leader>` disappears from status line, nothing else changes).

Note that I tried both with `<leader>` and `leader`, since the README is ambigous here.

Settings: 

```json
{
    "vim.easymotion": true,
    "vim.incsearch":  true,
    "vim.useSystemClipboard": true,
    "vim.leader": " ",
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<leader>", "s"],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.files.save",
                    "args": []
                }
            ]
        },
        {
            "before": ["leader", "q"],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.files.closeActiveEditor",
                    "args": []
                }
            ]
        }
    ]
}
```

**Comment by bmorgan5** [comment]
I am also having this problem after upgrading to 0.6.10

**Comment by johnfn** [comment]
Found it.

Did you know that `Number(" ") === 0`? Because how dumb is that right?

**Comment by johnfn** [comment]
By the way, it's now `"workbench.action.closeActiveEditor"`.

**Comment by theduke** [comment]
BTW: what is the proper way to bind leader? `<leader>` or `leader`?

**Comment by johnfn** [comment]
Use `<leader>`.

**Comment by jim-at-jibba** [comment]
Hey,

VSCode: 1.11.2 
vscodevim: 0.6.20

I am still having issues changing `vim.leader`

```
"vim.statusBarColorControl": true,
    "vim.statusBarColors": {
        "normal": "#005f5f",
        "insert": "#5f0000",
        "visual": "#5f00af",
        "visualline": "#005f87",
        "visualblock": "#86592d",
        "replace": "#000000"
    },
    "vim.leader": ","
```

The leader key is registered but when I usie it nothing happens.

Thanks
