### ISSUE TITLE
delete all lines containing <string> doesn't work 

### ISSUE THREAD

**Issue by kaloramik** [VSCodeVim/Vim#1412]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Put the exact keys you pressed.
: opens up the Vim Command mode

I typed 
```
g/pattern/d
```

### What did you expect to happen?
I would have expected all lines containing pattern to be deleted
### What happened instead?
the screen moves to the end of the file, but lines containing pattern still exist 

### Technical details:

* VSCode Version: 1.10.2 (1.10.2)
* VsCodeVim Version: 0.6.11
* OS: Mac

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).
