### ISSUE TITLE
multiclip does not work in vim mode

### ISSUE THREAD

**Issue by stephencheng** [VSCodeVim/Vim#1414]
### What did you do?
installed multiclip, it works well without vim mode being enabled, but does not work when it is enabled.

The plugin page:
https://github.com/stef-levesque/vscode-multiclip

It's great plugin but seems not working with vim plugin. And is it possible that this feature could be implemented in vim as plugin? just like easy motion or surround?

Put the exact keys you pressed.

### What did you expect to happen?

shift+cmd+v in insert mode, expect it will paste and cycle through clipboard, but it says nothing to paste

### What happened instead?

 it says nothing to paste

### Technical details:

* VSCode Version:
1.10

* VsCodeVim Version: *[please ensure you are on the latest]*
0.6.11

* OS: 
osx latest

**Comment by johnfn** [comment]
> And is it possible that this feature could be implemented in vim as plugin?

Vim (and therefore VSCodeVim) already has support for multiple clipboards! "ay to copy to the `a` register, "by to copy to the `b` register, etc. Then "ap to paste from the `a` register, etc.

**Comment by bdauria** [comment]
I'm actually using multiclip with VsVim as well and it works correctly on my side. The thing I did though is to remap the copy and list commands:

```
            "before": ["<leader>", "y"],
            "after": [],
            "commands": [{
                "command": ¬† "multiclip.copy"
            }]
        },
        {
            "before": ¬†["<leader>", "p"],
            "after": ¬†[],
            "commands": ¬†[{
                "command": ¬† "multiclip.list"
            }]
```

**Comment by stephencheng** [comment]
@bdauria 
Thanks. great to know there is a turn around.

Couple of questions:

1. do I put your settings in keybindings.json? it does not seem work for me.
2. so in order to use it, I will have to use Leader + y to copy to multclip and Leader+p to paste ?
I do list the multibuf but shows nothing.

Could you brief how do I do same thing like yours?

Thanks

**Comment by stephencheng** [comment]
@bdauria 

I figure it out now:

    "vim.otherModesKeyBindings": [
        {
            "before": [
                "<leader>",
                "y"
            ],
            "after": [],
            "commands": [
                {
                    "command": "multiclip.copy"
                }
            ]
        },
        {
            "before": [
                "<leader>",
                "p"
            ],
            "after": [],
            "commands": [
                {
                    "command": "multiclip.list"
                }
            ]
        }
    ]

**Comment by stephencheng** [comment]
@bdauria 

Seems there is still a bug with vim. It did work, but only works if I select(visually) the whole line and copy the whole line.

For the use case, if I use v to select a few words, it won't register it to multiclip. Does it happen to you?

**Comment by stephencheng** [comment]
a few test cases:

1. as reported above, hit Leader+y won't copy to multiclip, it does only when select whole line
2. this piece of setting from vim plugin interfere with cmd+c, which multiclip did remapping to copy

    {
        "key": "cmd+c",
        "command": "extension.vim_cmd+c",
        "when": "editorTextFocus && vim.overrideCopy && !inDebugRepl"
    },

I did remapping back to normal in user settings to override it:
    {
        "key": "cmd+c",
        "command": "multiclip.copy",
        "when": "editorTextFocus"
    }
then cmd+c works to do multiclip copy, however two problems:

a. if i hit cmd+c, it does not escape from visual mode
b. it changes the behavor of problem one, now if you hit Leader+y, it does copy the whole line to multiclip no mater what words you select

**Comment by stephencheng** [comment]
To summarise:

1. need to fix "extension.vim_cmd+c" or add a new command supporting copy to multiclip and escape to normal mode from visual selection

2. fix the multi.copy does not work correct selection but the whole line

Thanks

**Comment by johnfn** [comment]
We currently override the copy command; you can turn this off by doing `"vim.overrideCopy": false` in your settings file.

I quite honestly can't say why \y won't trigger a multiclip action. You can test with other actions other than multiclip.copy to confirm that \y works in the general case. If you do this and do confirm that (as I think you will!), it seems like it'd be a bug more associated with multiclip than VSCodeVim.

**Comment by stephencheng** [comment]
\y did trigger multiclip action but only copy the whole line, that's the bug
I use two different configs:

cmd+c => multiclip.copy
\y         => multiclip.copy

But  \y behaves differently, I think it's more likely to be vim plugin's problem, I feel that when I use v to select in visual mode, some how it didn't or couldn't use the selection, that's where the problem stems from.

**Comment by johnfn** [comment]
Oh, I see.

I have no clue how VSCodeVim could be causing multiclip to copy an entire line. All we do is call the multiclip.copy function. We don't adjust selections or anything.

**Comment by noelzubin** [comment]
this works for me 
```
    "vim.handleKeys": {
        "<C-c>": false,
        "<C-v>": false,
    },
```

**Comment by berknam** [comment]
This doesn't seem to be an issue anymore. I've tested it with multiclip and it seems to be working fine, either by removing the overrideCopy or by using the mentioned remaps.

Closing this since it doesn't appear to be an issue anymore, but if any of you are still having problems with this feel free to comment and we will reopen if needed.
