### ISSUE TITLE
How does format work in vim plugin?

### ISSUE THREAD

**Issue by stephencheng** [VSCodeVim/Vim#1415]
In real vim, I use = to do formatting, it works for every different type of file, eg: rb, shell, python, java .... etc.

I am just wondering how to achieve the same thing?

I did hit =, it seems it works for js file, but not the others? Does it depend on the format (or lint) supporting from other plugins?

How do I make the vim plugin work the same as real vim?

**Comment by johnfn** [comment]
We use VSCodeVim's formatting support. If VSCodeVim can't format it, neither can we!

**Comment by xconverge** [comment]
He meant if vscode can't format it then we can't ;)

**Comment by johnfn** [comment]
Haha thanks @xconverge  . Best typo ever.
