### ISSUE TITLE
c[change] d[elete] with f" don't work

### ISSUE THREAD

**Issue by dlespiau** [VSCodeVim/Vim#1417]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritised.

-----

### What did you do?

Wanted to delete a string (say. `"hello world!\n"`) with the cursor on the first `"` with `df"`/`cf"`.

Put the exact keys you pressed.

`df"`

### What did you expect to happen?

change/delete until the first occurrence of " after the cursor.

### What happened instead?

Nothing!

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Linux

**Comment by johnfn** [comment]
`df"` works perfectly for me. Do you have any custom keybindings set?

**Comment by dlespiau** [comment]
Oh my, `df"` does work perfectly for me now! I think I may have been confused by my keyboard layout (I have switch between US and UK depending on if my laptop is docked or not).

Sorry for the noise!
