### ISSUE TITLE
Wrong cursor position entering normal mode

### ISSUE THREAD

**Issue by prog666** [VSCodeVim/Vim#1418]
### What did you do?

Add this to config:
```
 "vim.insertModeKeyBindings": [
        {
            "before": [
                "d",
                "f"
            ],
            "after": [
                "<Esc>"
            ]
        }
    ]
```

### What did you expect to happen?

to work keys same as in vim and same as <Esc>

### What happened instead?

put cursor in the middle of text and press df, it enters normal mode, but places cursor one position further than <Esc>

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: macOS

**Comment by prog666** [comment]
this helps
```
"vim.insertModeKeyBindings": [
        {
            "before": [
                "d",
                "f"
            ],
            "after": [
                "<Esc>",
                "h"
            ]
        }
    ]
```

**Comment by xconverge** [comment]
Ah good catch! 

Remapped keys to esc (I use jj) do not leave the cursor in the same place as just esc when leaving insert mode.

**Comment by johnfn** [comment]
This must be because I reverse the keystrokes but don't reverse the cursor position.

I think the correct way to do this would be to record where the cursor was when you started to type jj, then put it back there once we've erased jj in the remapper.

**Comment by prog666** [comment]
found out that my hack working bad if you are at the end of the line

**Comment by prog666** [comment]
so is there any workaround for this? I'm trying to start using vscode instead of vim again and stuck with this same bug
