### ISSUE TITLE
`gj` and `gk` visual lines movement operations don't preserve column place.

### ISSUE THREAD

**Issue by drewsilcock** [VSCodeVim/Vim#1419]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Press `gj` to move down one visual line, onto a blank line.
2. Press `gj` again to move down on visual line, onto a line with content.
3. Observe that the column position has not been preserved.

Gif of normal `j`, `k` movement: ![normal movement](https://thumbs.gfycat.com/YellowishMenacingBison-size_restricted.gif)

Gif of visual line movement, with reported behaviour: ![visual line movement](https://thumbs.gfycat.com/GivingGentleHummingbird-size_restricted.gif)

### What did you expect to happen?

For the column position to be preserved when moving across paragraphs, as per Vim and normal `j`, `k` movement.

### What happened instead?

Column position was not preserved across paragraphs.

### Technical details:

* VSCode Version: 1.10.2
* VSCodeVim Version: 0.6.11
* OS: Windows 10 Pro

**Comment by xconverge** [comment]
This is a tough one

I couldn't figure out a way to get the start and end column positions of the wrapped line.

I tried this:

```
const posLine = vimState.editor.selection.active.line;

await vscode.commands.executeCommand("cursorMove", {
	to: "wrappedLineStart"
});

const startCol = vimState.editor.selection.active.character;

await vscode.commands.executeCommand("cursorMove", {
	to: "wrappedLineEnd"
});

const endCol = vimState.editor.selection.active.character;
const lineLength = endCol - startCol;

vimState.cursorPosition =
	new Position(posLine, Math.min(lineLength + startCol, vimState.desiredColumn + startCol));
```

but moving the cursor 3 times for every 1 time we want to move it makes no sense from a performance standpoint.

I think that we need to get wrappedLine info via the vscode API but I could not find it currently...

Then we could skip using cursor move and do the same sort of moves we do as j and k, however we would use the wrappedLine start and end column instead of 0 and end of line

**Comment by kevinjalbert** [comment]
I previously reported this (https://github.com/VSCodeVim/Vim/issues/1323) no idea what should be done with duplicates.

**Comment by xconverge** [comment]
Ah shucks sorry! One should be closed (newer one typically) but I commented on this one sorry!

**Comment by drewsilcock** [comment]
That's my bad really - I should've noticed that there was already an issue in for this. (I had a cursory look through but didn't spot it.) The other one has more thumbs up, I'll leave it up to you if you want to close this in favour of the older issue.

**Comment by xconverge** [comment]
@johnfn can you close this as dupe and I will add my comment to #1323

**Comment by johnfn** [comment]
Your wish is my command 😁  ✨
