### ISSUE TITLE
`''` not working

### ISSUE THREAD

**Issue by prog666** [VSCodeVim/Vim#1420]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

''

### What did you expect to happen?

cursor goes to previous location as it does in vim

### What happened instead?

nothing

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS:  macOS Sierra

**Comment by tjfryan** [comment]
Same issue happens with ``

**Comment by xconverge** [comment]
Fixed in #1993
