### ISSUE TITLE
Cursor displays as in insert mode (pipe) after search

### ISSUE THREAD

**Issue by prog666** [VSCodeVim/Vim#1421]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Cmd + Shift + F
Search for anything
double click on result.

### What did you expect to happen?

I expect cursor to be square-shaped, as it should be in normal mode

### What happened instead?

Cursor displays as it is `Insert mode` (`|`), but it is normal mode

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: macOS

**Comment by xconverge** [comment]
Is there any chance that you could try vscode Insider version? This was a bug in vscode that we tried to mitigate

If it still happens in insiders then we can try to mitigate it more, but if it is fixed, then we may just wait for the next vscode release... @johnfn

**Comment by johnfn** [comment]
Yeah, I kinda just want to close my eyes and hope this goes away when everyone migrates to 1.10. 😉  (As I am sure that it will...)

**Comment by xconverge** [comment]
This should be fixed, please reopen if it is still an issue
