### ISSUE TITLE
gUU and guu doesn't work

### ISSUE THREAD

**Issue by bogdan0083** [VSCodeVim/Vim#1423]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Pressed gUU or guu keys in normal mode. The same for gUgU and gugu.

### What did you expect to happen?

The whole line should be in uppercase (gUU) or in lowercase (guu).

![guu](https://cloud.githubusercontent.com/assets/7077307/24301206/8b58aeb0-10e1-11e7-9206-626ee068e752.gif)

### What happened instead?

Nothing.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Windows 10 Pro

Thank you!

**Comment by xconverge** [comment]
@johnfn how do we do gU as an operator AND gUU as a command without the operator being triggered?

**Comment by johnfn** [comment]
You can do it the johnfn-hack way (which is how I did dd yy cc), which is that U is a motion that only gets triggered if there's a `gU` operator already on the stack. 😁

**Comment by xconverge** [comment]
works for me

**Comment by xconverge** [comment]
Ah actually doesn't work for guu, because u already exists as a command

**Comment by johnfn** [comment]
That's okay, you can just double hack and say that u doesn't trigger if a gu is already on the stack.

**Comment by johnfn** [comment]
In fact I think we even have a "must be first key" bit of functionality... somewhere...
