### ISSUE TITLE
Allow users to delegate certain keys back to vscode

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#1424]
I am proposing a way to allow users to delegate certain key combinations back to vscode.

This will only include modifier key combos that we map.

I will add a setting like:

```
vim.handleKeys{
    <C-f>:false,
    <C-a>: false
}
```

The default for all of our mappings will be true.

This config option will be checked for every key when we go to register them.

In VsVim the screen looks like this:

![image](https://cloud.githubusercontent.com/assets/4219348/24305837/9af6d970-107b-11e7-9b9e-141fa3eb9999.png)

**Comment by xconverge** [comment]
@johnfn @rebornix Any thoughts?

**Comment by rebornix** [comment]
I really like the idea. Just my 2 cents here

1. About how we modify the `when` clause, as we are adding more to it, we may want to merge all vim related entries to a single one in a keybinding entry. For example
    ```
    {
                "key": "ctrl+k",
                "command": "extension.vim_ctrl+k",
                "when": "editorTextFocus && vim.useCtrlKeys && vim.mode != 'Insert' && !inDebugRepl"
    },
    ```

    Right now we are passing `useCtrlKeys` and `mode` back to Code's context and asking Code to do the math. But we still want to put `disableTemporarily` and your `handleKeys` in the table, so maybe we can merge them into a single `vim.CtrlK` boolean and update it when necessary.

2. One thing I'm not sure about if we want to let ppl know about `scope` as ppl may want to use `ctrl+c` in Insert Mode but not others. The VSVim options don't have a good way to specify the scope/vim-mode/etc, do they?

**Comment by xconverge** [comment]
1. I think that is a great idea. I think my first commit will have it as a separate entry in "When". Then a followup commit can combine all of our logic and whens into a single vim.ctrlK
2. I think we can ignore scope for now, lets  just do an all or nothing

**Comment by johnfn** [comment]
Love it, I just wish we had a better interface than JSON - like VSVim does.

**Comment by xconverge** [comment]
oooooo well :)

**Comment by johnfn** [comment]
What's important is: don't get rid of `useCtrlKeys`. Basically have useCtrlKeys flip all these to true, and then have these settings override individual keys.

**Comment by xconverge** [comment]
no I am not getting rid of that option, I am however getting rid of that from the package.json though

**Comment by johnfn** [comment]
Perfect. And yeah assuming VSCode ever rolls out some sort of gui thing, we'll be ready. :)

**Comment by xconverge** [comment]
Great feature request! Fixed on master
