### ISSUE TITLE
Remapped EasyMotion command to "s" key has a small bug

### ISSUE THREAD

**Issue by bogdan0083** [VSCodeVim/Vim#1426]
### What did you do?

Remapped "s" key to EasyMotion find char:

![](http://image.prntscr.com/image/33116cd955c9410dad9acf1ab8ce4d27.png)

### What did you expect to happen?

To search for "s" character when "ss" combination is used.

### What happened instead?

It doesn't search for "s" char but works fine for any other char. 

I guess it happens because it always triggers EasyMotion command instead of seeking for character.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Windows 10 Pro

Thank you!

**Comment by xconverge** [comment]
This is fixed now do to the fact that it is now "normalModeKeybindings" vs what it used to be "otherModeKeyBindings"

So the remapping runs when you press s, however it then changes to easymotion mode, so the keybinding is no longer applied, and you can safely press s and it will not remap it.
