### ISSUE TITLE
Inner tag "it" not working when tag has other tags in it

### ISSUE THREAD

**Issue by jrenton** [VSCodeVim/Vim#1430]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I wanted to replace the content of an inner tag `p` by using the command `cit` on:
```html
<p>
  <strong>Title</strong> Some more content
</p>
```
1) If your cursor is anywhere between the p tags, `Title` is removed from the `strong` tag, when all of the content in the `p` tag should have been removed.

2) If you are inside of the p tags themselves and type `cit`, nothing happens, when all of the content within the `p` tag should be removed.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Windows 10

**Comment by xconverge** [comment]
Can you go thumbs up #1108 and #1300 please, thanks!
