### ISSUE TITLE
Incorrect behavior when editing with multiple cursors

### ISSUE THREAD

**Issue by osenvosem** [VSCodeVim/Vim#1432]
I make several cursors with Cmd+alt+shift+keyDown, type`-` and ` then move cursors to the end with Cmd+keyRight and try to type ` again, but it inserted to the place when the cursor was before moving.

![yy8ufbmown](https://cloud.githubusercontent.com/assets/6762673/24328502/30e04024-11f4-11e7-9fa4-9ddeec70f93b.gif)

**Comment by johnfn** [comment]
Definitely a bug, but the work around would be to simply use `$` to go to the end of line.

**Comment by osenvosem** [comment]
@johnfn yes, also one can use "Esc, Shift+A" and insert a character, which is a bit simpler.
