### ISSUE TITLE
Ctrl+c in insert mode does not copy text, and unexpectedly switches to normal mode

### ISSUE THREAD

**Issue by jrenton** [VSCodeVim/Vim#1437]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`Ctrl+c` in insert mode.

### What did you expect to happen?

I expect normal VS Code features to work in insert mode, in this case for the selected text to be copied, and to remain in insert mode.

### What happened instead?

Nothing was copied, normal mode was entered.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Windows 10

**Comment by johnfn** [comment]
This is normal Vim behavior. If you want it turned off, you can set `vim.useCtrlKeys` to false.

**Comment by jrenton** [comment]
@johnfn I tested this on the latest version of Vim, and it is not normal Vim behavior.

**Comment by johnfn** [comment]
Sure it is! http://vimdoc.sourceforge.net/htmldoc/insert.html 

> CTRL-C		Quit insert mode, go back to Normal mode.

You must have some extensions installed. :)

**Comment by mnsr** [comment]
I know this is a late reply, but if you to specifically only disable CTRL+C from this extension, put the following in your settings.json:

```
"vim.handleKeys":{
  "<C-c>": false
}
```

**Comment by cycold** [comment]
If mac you can replace C(Ctrl) with D(command)
```
"vim.handleKeys":{
  "<D-c>": false
}
```

**Comment by victorhcm** [comment]
> ```
> "vim.handleKeys":{
>   "<C-c>": false
> }
> ```

Is it possible to disable `<C-c>` in insertion mode only (`i_CTRL-C`), such that it still works in normal mode? 
For instance, it would copy in insertion mode and still abort a `:command` in normal mode.

**Comment by Sentero-esp12** [comment]
For some reason setting this in `settings.json`: 
`"vim.useCtrlKeys": false` doesn't solve the problem. `Ctrl+c` still activates the normal mode.

**Comment by Ssicayoon** [comment]
> For some reason setting this in `settings.json`:
> `"vim.useCtrlKeys": false` doesn't solve the problem. `Ctrl+c` still activates the normal mode.

The same problem.

**Comment by anancds** [comment]
> I know this is a late reply, but if you to specifically only disable certain keys (in this case CTRL+C) from this extension, put the following in your settings.json:
> 
> ```
> "vim.handleKeys":{
>   "<C-c>": false
> }
> ```

this solves my problem ,thanks

**Comment by FJBDev** [comment]
I keep reading this in this thread `" it is not normal Vim behavior"`
It might be normal behavior in Vim but coming from Visual Studio and using the [VsVim ](https://marketplace.visualstudio.com/items?itemName=JaredParMSFT.VsVim)extension doesn't require to go through hoops to use use Ctrl+C, X, V

This fixed it for me in settings.json:

```
{
	"vim.handleKeys": {
		"<C-c>": false,
		"<C-x>": false,
		"<C-v>": false
	}
}
```

**Comment by ianjamieson** [comment]
In `settings.json` I have added:

```
"vim.overrideCopy": false,
```

From the `readme` it says:

> Override VS Code's copy command with our own, which works correctly with VSCodeVim. If cmd-c/ctrl-c is giving you issues, set this to false and complain [here](https://github.com/Microsoft/vscode/issues/217).

**Comment by szfkamil** [comment]
> In `settings.json` I have added:
> 
> ```
> "vim.overrideCopy": false,
> ```
> 
> From the `readme` it says:
> 
> > Override VS Code's copy command with our own, which works correctly with VSCodeVim. If cmd-c/ctrl-c is giving you issues, set this to false and complain [here](https://github.com/Microsoft/vscode/issues/217).

This fixed it for me coming from VSCode. Also, the settings changed a bit since @FJBDev [posted](https://github.com/VSCodeVim/Vim/issues/1437#issuecomment-780168258) the link for instructions. You should open  `Preferences` and then: 

![CleanShot 2023-05-07 at 13 16 24@2x](https://user-images.githubusercontent.com/82778513/236674310-dd2e4c80-564e-4171-ac41-8261df806afe.png)

**Comment by santhoshvempali** [comment]
**I faced same issue**

**I SOLEVED IT BY**

- > disabling vm extension in vscode

- > uninstaling vm extension

**Comment by backslash-enn** [comment]
I'll just make this slightly more clear for anybody stopping by

By default, while in insert mode Vim uses the Ctrl+C command to switch to normal mode. But you may want to retain the original use of Ctrl+C (copying text). To do this you may have heard that you must set the `vim.useCtrlKeys` setting to false. But many of us have found that this still does not fix the problem! If that's you, here's how you solve it:

1. Open the settings by pressing Ctrl+, (or in the top-left corner click File->Preferences->Settings)
2. Enter this string into the settings search bar: "vim command override". You will see a handful of settings below
3. Uncheck the checkbox for the "Vim: Override Copy" setting
4. Uncheck the checkbox for the "Vim: Use Ctrl Keys" setting

![image](https://github.com/VSCodeVim/Vim/assets/18175176/a0a59333-453c-4ddc-be38-85232b04382f)

What's important to note is that you must set **both** the "Vim: Use Ctrl Keys" **and** the "Vim: Override Copy" settings to false. Just doing one or the other will not fix the problem

**Comment by kyleqihua** [comment]
> I'll just make this slightly more clear for anybody stopping by
> 
> By default, while in insert mode Vim uses the Ctrl+C command to switch to normal mode. But you may want to retain the original use of Ctrl+C (copying text). To do this you may have heard that you must set the `vim.useCtrlKeys` setting to false. But many of us have found that this still does not fix the problem! If that's you, here's how you solve it:
> 
> 1. Open the settings by pressing Ctrl+, (or in the top-left corner click File->Preferences->Settings)
> 2. Enter this string into the settings search bar: "vim command override". You will see a handful of settings below
> 3. Uncheck the checkbox for the "Vim: Override Copy" setting
> 4. Uncheck the checkbox for the "Vim: Use Ctrl Keys" setting
> 
> ![image](https://private-user-images.githubusercontent.com/18175176/333823868-a0a59333-453c-4ddc-be38-85232b04382f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjM3NDgsIm5iZiI6MTczMjA2MzQ0OCwicGF0aCI6Ii8xODE3NTE3Ni8zMzM4MjM4NjgtYTBhNTkzMzMtNDUzYy00ZGRjLWJlMzgtODUyMzJiMDQzODJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAwNDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNGZjMmVlYmJjMGY0NDBjNTQyYzU5MzFkYThiNDg4MmRlZDcxZTQ2NmQ2ODg1NGI5NzRhOTY5NzI3MzE5NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ghoY_jy29ZLPb57_l-I5IJFcK8GvMu1aLSGWbyBwHN0)
> 
> What's important to note is that you must set **both** the "Vim: Use Ctrl Keys" **and** the "Vim: Override Copy" settings to false. Just doing one or the other will not fix the problem

thanks. this solved my problem
