### ISSUE TITLE
Change configuration updates to monitor relevant changes instead of all changes

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#1438]
Currently we map onDidChangeConfiguration to update all key contexts, all vim options, and several editor options.

This may cause performance issues.

We should be able to filter out if we received relevant config changes and only update those parts of our configuration.ts file instead of everything, everytime.

Related: https://github.com/Microsoft/vscode/issues/23325

**Comment by xconverge** [comment]
@rebornix Your concerns were right, I am starting to get scared a little bit by this too, hopefully we can get the vscode change in before it becomes a big problem for us!

**Comment by johnfn** [comment]
It's still only any time the user saves their config file, right? That's not too often...

**Comment by xconverge** [comment]
Nope, anytime the cursor changes.

**Comment by rebornix** [comment]
@xconverge whenever we change the cursor, it's saved to the config file and then we get a config change event.

**Comment by xconverge** [comment]
@rebornix are you sure about that? When I checked that event wasn't getting fired...

**Comment by rebornix** [comment]
@xconverge I'm stupid, I removed this piece of stupid logic myself. Yes right now when we change the cursor, we only touch the cache in current editor without touching the config file. False alarm.

**Comment by Chillee** [comment]
So can this issue be closed? It doesn't really seem like this needs to be fixed.

**Comment by snewell92** [comment]
@rebornix You are not stupid! <3<3<3<3<3

**Comment by Chillee** [comment]
I'm gonna close this issue, as it doesn't seem like this is a real issue. Please reopen if this is an actual issue.
