### ISSUE TITLE
`command + c` then `command + v` lead to messy words

### ISSUE THREAD

**Issue by myrfy001** [VSCodeVim/Vim#1440]
### What did you do?

In insert mode, `command + c` then `command + v` lead to messy words being pasted.
if I disable this plugin, the vs code works fine with `command + c / v` to copy or paste
Also, it works fine before, and this problem happened when I updated to 0.6.11 today.

### What did you expect to happen?

`创建索引和别名`

### What happened instead?

`ÂàõÂª∫Á¥¢ÂºïÂíåÂà´Âêç`

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version:  0.6.11
* OS: OSX 10.12

**Comment by xconverge** [comment]
Can you look at https://github.com/VSCodeVim/Vim/issues/1392 please
