### ISSUE TITLE
Empty clipboard after selecting and copying text using Shift + Home

### ISSUE THREAD

**Issue by Yohanna** [VSCodeVim/Vim#1442]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. While in Insert mode, position the cursor at the end of a text e.g. After the `d` letter in "Hello World"
2. Press `Shift+Home` to select till beginning of text.
3. Copy the selection using `Ctrl+C`
4. Paste the selection on a new line

### What did you expect to happen?

The text "Hello World" gets pasted.

### What happened instead?

* Nothing happens. The clipboard is now empty and nothing gets pasted.

### Note
* Apparently this only happens when using `Ctrl+C` to copy text. Selecting the text the same way as in step 1 & 2 and then copying it by right clicking on the text and selecting `Copy`, pastes the text as expected.

* Also, possibly related to #1441 

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Windows 10

**Comment by jpoon** [comment]
To keep our issue list sane, closing this issue as it hasn't gained much traction.

**Comment by Yohanna** [comment]
Actually, it looks like this issue has been fixed for some time now anyway :)
