### ISSUE TITLE
[Feature request] Cut and Paste universal buffer.

### ISSUE THREAD

**Issue by rajinder-yadav** [VSCodeVim/Vim#1443]
I would like this project to make cut and paste work like it does without the Vim plugin, right now with the plugin it uses a separate paste buffers and many times I have gotten to the point thing get so messed that I just stop using this plugin.

I want so I can cut and paste item between other windows outside of vscode. This needs to work flawlessly, right now that is not the case.

## Scenario 1 

For example, I highlight an area of text, and I press 'y' to yank the select text to the buffer. I then click on a another window, a text pad app. I press Ctrl+v and the copied text from vscode is pasted into the text app window.

## Scenario 2

I copy text from the browser, switch into vscode and paste it by pressing 'p' paste.

## Scenario 3

I copy text from vscode by visual highlighting it, then press 'd' to delete text and copy into the paste buffer. I  switch to an external text app and paste the deleted text using Ctrl+V

**Comment by johnfn** [comment]
I think you want `    "vim.useSystemClipboard": true,`? It sets the system clipboard to be the default clipboard for yanking and putting.

**Comment by Syltaen** [comment]
alternatively, you can use `"+y` and `"+p` to copy and paste from the system clipboard

`"` is used to define the buffer to use for `y` and `p`
and `+` is the system clipboard

**Comment by xconverge** [comment]
I am going to close this for now since I think you were just missing the [useSystemClipboard](https://github.com/VSCodeVim/Vim#usesystemclipboard) setting

Feel free to reopen if I misunderstand something
