### ISSUE TITLE
: with visual region selected should not highlight command line text

### ISSUE THREAD

**Issue by leemhenson** [VSCodeVim/Vim#1444]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`V` to select the current line in visual mode.
`:` to show the vim command line.

### What did you expect to happen?

Vim command line to be shown with `'<,'>` in it, and cursor to be located at the end of the line ready for me to enter the command I want to apply to the selected region.

### What happened instead?

Vim command line was shown with `'<,'>` in it, but the whole of the text was selected so the next keypress I made caused it to be overwritten. This means I have to manually move the cursor to the end of the line to enter my command.

<img width="438" alt="showcommandline" src="https://cloud.githubusercontent.com/assets/515/24403831/8db2b2fa-13b6-11e7-87b6-5e59df118758.png">

### Technical details:

* VSCode Version: Version 1.11.0-insider (1.11.0-insider)
* VsCodeVim Version: 0.6.11
* OS: Mac OS 10.12.3

**Comment by xconverge** [comment]
Can you go thumbs up https://github.com/VSCodeVim/Vim/issues/792 please, thanks! Unfortunately it is a limitation of the vscode API for now

**Comment by leemhenson** [comment]
Ah, sorry! I missed that one.

**Comment by johnfn** [comment]
No worries. Github's issue page is so hard to manage that I just wait for @xconverge find the dupe most of the time. 😉

**Comment by xconverge** [comment]
We can all hang out and chat in this issue if you want though, the other one can be for business and issue solving, this can be the fun one

**Comment by leemhenson** [comment]
To be fair, mine does have a picture.

**Comment by johnfn** [comment]
True, and the overall formatting is much more aesthetically pleasing.
