### ISSUE TITLE
Undo/redo broke between 0.6.5 and 0.6.11

### ISSUE THREAD

**Issue by soyuka** [VSCodeVim/Vim#1445]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Sadly I'm not sure what version I had before the last update (I think it was 0.6.5), I'm now running on 0.6.11. Note that this update broke my `capslock` binding (overriden through xmodmap) and I had to add:

```
    {
       "key": "capslock", "command": "extension.vim_escape"
    },
```
 
Now, I'm using the following bindings to switch between tabs:

```
    {
        "key": "shift+h",
        "command": "workbench.action.previousEditorInGroup",
        "when": "editorTextFocus && vim.mode == 'Normal' && !inDebugRepl"
    },
    {
        "key": "shift+l",
        "command": "workbench.action.nextEditorInGroup",
        "when": "editorTextFocus && vim.mode == 'Normal' && !inDebugRepl"
    },
```

Now, undo/redo is working fine until I change the tab. 

I know that this looks like #977, but if I use the non-vim keybindings (ie `ctrl+z`), I'm able to undo! 
 
* VSCode Version: `code-insiders_1.11.0-1490704208_amd64`
* VsCodeVim Version: 0.6.11
* OS: debian jessie

**Comment by johnfn** [comment]
How exactly does undo/redo break?

**Comment by soyuka** [comment]
I was able to undo/redo after changing tabs before.

**Comment by soyuka** [comment]
Okay definitely related to vscode-insiders. I switched to code-1.10 and no issues. Will open an issue there ;).
