### ISSUE TITLE
Can't find file under cursor

### ISSUE THREAD

**Issue by chanlvh** [VSCodeVim/Vim#1446]
### What did you do?

Command + click on path string or "g f" (vim) when cursor is on the string

### What did you expect to happen?

File with that path is opened in a separated window

### What happened instead?

can't file symbol (cmd+ click)
Can't find file (g f in vim normal mode)

### Technical details:

I did check, the file is there. path is relative to the project's root directory. File opened normally with cmd+p

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: OSX
* Language developing: Javascript

**Comment by rebornix** [comment]
@chanlvh if `cmd+click` doesn't work, then it means it has nothing to do with Vim :)
