### ISSUE TITLE
g-d and g-D doesn't work.

### ISSUE THREAD

**Issue by Josef-Vonasek** [VSCodeVim/Vim#1447]
I have open scheme file ( I use only syntax highlighter for scheme, nothing more) and g-d shortcut doesn't do anything.

Example
```scheme
(define (foo x) x)
```

**Comment by johnfn** [comment]
gd, like go to definition? gd works perfectly fine for me, and I use it all the time. My guess is that vscode's scheme plugin does not support going to definition yet, so you should go nag them.
