### ISSUE TITLE
EasyMotion up/down (j/k)

### ISSUE THREAD

**Issue by mightyiam** [VSCodeVim/Vim#1448]

**Comment by xconverge** [comment]
@mightyiam Can you give some more details on what this is?

**Comment by mightyiam** [comment]
`leader, leader, j`, for example, puts a target at each line below.
![screenshot_2017-03-30_19-56-53](https://cloud.githubusercontent.com/assets/635591/24516372/0d3f5d02-1583-11e7-8e3e-f0de00d9710c.png)

I use it all the time.

**Comment by xconverge** [comment]
Woops I think I messed this up slightly, it needs to go to first non whitespace char, I made it go to first char on the line. Will fix it soon!

**Comment by xconverge** [comment]
fixed correctly on master now

**Comment by mightyiam** [comment]
Thank you, @xconverge!
