### ISSUE TITLE
gq incorrectly handles triple-slash doc-comments

### ISSUE THREAD

**Issue by rnewman** [VSCodeVim/Vim#1449]
### Steps

Type a line like the following, in Rust:

```
/// One two three four five six seven eight nine ten. One two three four five six seven eight nine ten. One two three four five six seven eight nine ten.
```

Visually select the entire line: `0v$`

Reformat line: `gq`.

### Expected:

With 100-column wrap:

```
/// One two three four five six seven eight nine ten. One two three four five six seven eight nine
/// ten. One two three four five six seven eight nine ten.
```

### Actual:

With 100-column wrap:

```
// / One two three four five six seven eight nine ten. One two three four five six seven eight nine
// ten. One two three four five six seven eight nine ten.
```

### Technical details:

* VSCode Version: 1.11.0-insider
* VsCodeVim Version: 0.6.11
* OS: macOS 10.11.6.

**Comment by johnfn** [comment]
This _might_ be an incredibly easy bug for anyone who wants to contribute to pick up. 

(or it could be incredibly hard...)

**Comment by jonhoo** [comment]
Hmm, I'm not sure this is actually fixed? The initial problem is, but now the first of the resulting wrapped lines is indented one space too few:
```rust
    /// Mark this node as sharded by a value that stems from the given column of the given source awdkjd
```
after `Vgq` turns into
```rust
   /// Mark this node as sharded by a value that stems from the given
    /// column of the given source awdkjd
```

**Comment by Chillee** [comment]
Yeah I realized I fucked it up in #1684. I fixed the bug in a pr, but there's a couple more gq related bugs I want to fix(plus it's finals week for me, so I haven't had too much time).
