### ISSUE TITLE
Implement gqq

### ISSUE THREAD

**Issue by rnewman** [VSCodeVim/Vim#1450]
```
gq{motion} % format the line that {motion} moves over
{Visual}gq % format the visually selected area
gqq        % format the current line
```

**Comment by rnewman** [comment]
(And, of course, things like `5gqq` to format the next five lines.)

**Comment by andschwa** [comment]
Specifically for me, `gq}` is broken. While I can visually select some lines and run `gq` and that works, I can't just go to the top of my comment and run `gq}`, even though the cursor moves appropriately, the wrapping does not happen. The roadmap states that `gq{motion}` is implemented, but it appears broken.

**Comment by jonhoo** [comment]
Until this is implement, you can also emulate this with:
```json
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": [
                "g",
                "q",
                "q"
            ],
            "after": [
                "V",
                "g",
                "q"
            ]
        }
    }
```

**Comment by Chillee** [comment]
@andschwa That's because gq was implemented as a command, and only operators support applying them over a region.

Thus, I just implemented it as an operator :smile:
