### ISSUE TITLE
`ci"`, `dsb` are not repeatable with `.`

### ISSUE THREAD

**Issue by andschwa** [VSCodeVim/Vim#1456]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Code:
```
"foo"
"bar"
```
Actions:
1. Place cursor inside `"foo"`, type `ci"blah<ESC>`.
2. Place cursor inside `"bar"`, type `.`

### What did you expect to happen?

`"bar"` to be replaced with `"blah"` like `"foo"` was.

The same bug appears with a scenario like:

```
(foo)
(bar)
```
Actions:
1. Place cursor inside `"foo"`, type `dsb`.
2. Place cursor inside `"bar"`, type `.`

While `(foo)` goes to `foo` as expected, `(bar)` does not.

### What happened instead?

Nothing, or sometimes `.` repeats the last movement, but it's not consistent.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Windows 10

**Comment by johnfn** [comment]
This works perfectly fine for me. Mind providing your user settings json file?

**Comment by xconverge** [comment]
Yes for surround see https://github.com/VSCodeVim/Vim/issues/1244

**Comment by andschwa** [comment]
`ci"` isn't reproing now... if it happens again I'll let you know, for now I'll close in favor of the existing surround issue. Thanks!
