### ISSUE TITLE
Toggle zen mode conflicts with vim commands

### ISSUE THREAD

**Issue by lucastheisen** [VSCodeVim/Vim#1457]
### What did you do?

From the `View` menu, I clicked `Toggle Zen Mode`.  This put me in Zen mode as expected, but in Zen mode, all the menus are gone.  There are 2 keyboard shortcuts that should get out of zen mode:

- `Ctrl K + Z`
- `<esc><esc>`

Neither works while in a code panel.  The only way I was able to get out of Zen mode was to close all open code editor tabs until I saw the help page (show all commands, go to file, ...) then use `<esc><esc>`

### What did you expect to happen?

Dunno, not sure what _should_ be expected, and its fairly easy to see how it could be a conflict...

### What happened instead?

Stuck in Zen mode (not very Zen to get stuck like that)

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: *[please ensure you are on the latest]* 0.6.11
* OS: Windows 10 (1607)

**Comment by xconverge** [comment]
😆  hmm will need to think about something for this... for now you could probably map another key combination to leave zen mode through vscode

**Comment by johnfn** [comment]
I'm going to close this as I believe that making a new keybinding within VSCode is a completely reasonable solution to this problem. Feel free to reopen if you disagree.

**Comment by lostmygithubaccount** [comment]
is it not ironic that because I'm using a VIM extension in VSCode I'm now Googling around to find old threads about how to exit an editor view...? maybe I can setup `:q!` as the keybinding
