### ISSUE TITLE
Inserting keywords on pressing arrow keys in visual mode

### ISSUE THREAD

**Issue by zhelanov** [VSCodeVim/Vim#1458]
### What did you do?

**Ctrl+V** (enter visual mode), select a few lines, type **I**, type # (just to comment these lines), press Up / Down arrow (for example)

### What did you expect to happen?

Just go to a line above / below

### What happened instead?

On selected lines appears _<up>_ and _<down>_

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.11
* OS: Windown 7 x64

**Comment by johnfn** [comment]
I think some formatting got messed up here?

**Comment by xconverge** [comment]
I can reproduce this, just go to visual block, press I, then use the arrow keys

**Comment by johnfn** [comment]
That's because *_you shouldn't be using the arrow keys*_ :wink:

**Comment by johnfn** [comment]
We don't make it impossible to use vim wrong. We just make it cause all sorts of annoying bugs. :grin:
