### ISSUE TITLE
'viw' cannot select a whole word

### ISSUE THREAD

**Issue by viewsafe** [VSCodeVim/Vim#1459]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

pressed the keys : viw

### What did you expect to happen?
should be select a whole word
### What happened instead?
last letter have not been seleced
### Technical details:

* VSCode Version:
* VsCodeVim Version: *[please ensure you are on the latest]*
* OS:

**Comment by johnfn** [comment]
In which way does it effect you that the last letter is not selected?

**Comment by viewsafe** [comment]
normal modle, pressed viw,

**Comment by johnfn** [comment]
No but like if you press y you still yank the whole word, no?

**Comment by viewsafe** [comment]
for example, if you press viw in the middle of the word 'print', it just shows 'prin' been selected, but yes, it still yank the whole word 'print',  however, I don't want to yank a word to somewhere, I just want to select that whole word.

**Comment by johnfn** [comment]
What exactly are you using that selection for if not yanking?

**Comment by viewsafe** [comment]
I want to select that whole word then other plug-in can add quote or brackets to that whole word.

**Comment by johnfn** [comment]
Oh I understand.

Did you know that VSCodeVim includes the _AWESOME_ and _*AMAZING*_ surround.vim?!? So if you want to surround a word that you've selected with viw, you can simply type ysiw", which will surround a motion with quotes???

**Comment by viewsafe** [comment]
it's cool, I don't know that :+1:

**Comment by viewsafe** [comment]
by the way, do you know how can I jump out a quote or brackets by using VIM?

**Comment by johnfn** [comment]
On the same line, % (enough times) will work.

On different lines, I added a motion `af` to VSCodeVim, which might help. See https://github.com/VSCodeVim/Vim#awesome-features-you-might-not-know-about. Just keep pressing af till you get where you want, then press ESC.

**Comment by viewsafe** [comment]
thank you. but %  seems not very smart to jump out layer by layer . for example [((abc))], I will stay the 2nd af method.

**Comment by johnfn** [comment]
Yeah, in that case af will be better for you. v then af af af and you should be good to go. :)

**Comment by johnfn** [comment]
Another option in the [(((abc)))] case is `va]<esc>`

**Comment by johnfn** [comment]
And of course `\]<enter>`

**Comment by johnfn** [comment]
Or `f]`

**Comment by viewsafe** [comment]
That's great. Thank you. I've learned a lot from you tonight :100:

**Comment by xconverge** [comment]
Closing this because this is working as designed. Feel free to reopen if you have more to add to it, thanks!
