### ISSUE TITLE
multiline editing does not work

### ISSUE THREAD

**Issue by luxueyan** [VSCodeVim/Vim#146]
The vscodevim extension was installed, but the mutil edit can't work ,

**Comment by johnfn** [comment]
I'm not sure what this means. Are you referring to visual block mode?

**Comment by jpoon** [comment]
VSCode also comes with [Multi-cursor](https://code.visualstudio.com/Docs/editor/editingevolved) which doesn't seem to work after installing this extension.

**Comment by luxueyan** [comment]
No!When it is at command mode,i press the shortkey "command+d"  for multiline selecting. Then i need change the content,i press "i" to insert mode, i dose not work! Only the first cursor update. 

ps: mac os system

**Comment by hexinatgithub** [comment]
Yes, there is a problem with this plugin, I type the for and use VSCode build-in snippet, the multi edit cann't work.Like this:
```
for(var index = 0; index < array.length; index++) {
  var element = array[index];
}
```
then build-in snippet will select all index, and you can multi edit, but when you type only the first cursor update, and rest are gone.
```
for(var bug = 0; < array.length;++) {
    var element = array[];
}
```

**Comment by hexinatgithub** [comment]
And the other situation is that when you type **for**,use the snippet
```
for (var index = 0; index < array.length; index++) {
	var element = array[index];
	
}
```
and type tab skip set index, and will select the array, then you change the array, only the first will change, and then you type enter, the rest will change, but the word will placed before cursor, and the most import is that, the inserted word will replaced the characters before cursor, like follow code, it will replaced ` = ` with `bug`.
```
for (var index = 0; index < bug.length; index++) {
	var elementbug[index];
} 
```

**Comment by ericwooley** [comment]
VI with multi cursor mode is extremely powerful.

This bug is pretty much the only thing keeping me from switching from atom.

**Comment by jkevingutierrez** [comment]
+1

**Comment by johnfn** [comment]
Closing in favor of #417.
