### ISSUE TITLE
Make a big loud link to the roadmap in the readme

### ISSUE THREAD

**Issue by mightyiam** [VSCodeVim/Vim#1466]
I might even do it myself.

**Comment by johnfn** [comment]
By all means, go ahead! 😉 

Admittedly, our roadmap is currently a bit out of date...

**Comment by xconverge** [comment]
https://github.com/VSCodeVim/Vim#vim---

its here in the summary of what the plugin does... I think it makes sense where it is...

**Comment by xconverge** [comment]
@cobbweb refactored the entire readme to be better and more clear!
