### ISSUE TITLE
Insert mode cursor is now the block instead of the pipe

### ISSUE THREAD

**Issue by Phrohdoh** [VSCodeVim/Vim#1470]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`i`

### What did you expect to happen?

The cursor would be the pipe (`|`).

### What happened instead?

The cursor is a block.

### Screenshot

Look at lib.rs:11

![screen shot 2017-04-04 at 5 40 22 pm](https://cloud.githubusercontent.com/assets/4861023/24682216/1f5c6118-195e-11e7-87ee-28e5f3893956.png)

### Technical details:

* VSCode Version: 1.10.2 (8076a19fdcab7e1fc1707952d652f0bb6c6db331)
* VsCodeVim Version: 0.6.13
* OS: macOS 10.12.3

**Comment by xconverge** [comment]
What did you do to get in this state? Can you get it to be a line again? This is a vscode bug that is fixed on insiders I believe

**Comment by Phrohdoh** [comment]
I did exactly what I said in the OP, just pressed `i` to enter insert mode.

I'm actually hitting a lot of bugs since upgrading to 0.6.13 perhaps they are vscode issues too.

**Comment by xconverge** [comment]
What is your editor.cursorStyle set to

**Comment by xconverge** [comment]
and if it is not, can you set it to line. We just enabled this feature this release, so that you can use line-thin, block-outline, underline, underline-thin if you want. We used to just automatically set it to line but some users wanted to use other cursors for insert mode.

**Comment by Phrohdoh** [comment]
Ok, `"editor.cursorStyle": "line",` is exactly what I wanted.

**Comment by xconverge** [comment]
No problem! I am guessing you had set it to block at some prior time and then never noticed? If you have any issues with it changing back or anything like that... reopen an issues! Also please post anything else you find with the release that you think is new either here or in slack!
