### ISSUE TITLE
Include total # of search results in / find

### ISSUE THREAD

**Issue by fandy** [VSCodeVim/Vim#1471]
Right now `cmd + f` VSCode search is superior to `/` because it displays the match count. It'd be nice to know whether I should keep traversing by showing a match count in the status bar.

A better solution is to just open the VScode find drawer, which lets you edit the search query with arrow keys. Press `ctrl + n`/ `ctrl + N` to exit the drawer and traverse the results.

![image](https://cloud.githubusercontent.com/assets/19108762/24683141/5580a5e4-196b-11e7-89a2-6e371e819a14.png)

Does this seem like a valuable feature? If so I can get a PR in.

**Comment by xconverge** [comment]
I think adding number of results makes sense...if users want you can delegate ctrl+f back to vscode and use the find window as well

**Comment by xconverge** [comment]
VIM does not display the number of results anywhere, does it?

**Comment by fandy** [comment]
Not unless you use a plugin, but I think this should be an essential feature as there's no reason for me to use it over `cmd + f` right now.

**Comment by fandy** [comment]
Ah today I learned! Alright cool I'll try to get a pull request up later this week.

**Comment by Platzer** [comment]
@johnfn, what should `qq\foo<enter>dwq` do? 🤔

**Comment by johnfn** [comment]
Makes a macro that searches for and deletes a word and saves it to the q register. :)
