### ISSUE TITLE
insertModeKeyBindings don't apply in Replace mode

### ISSUE THREAD

**Issue by AlexanderEllis** [VSCodeVim/Vim#1472]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I have 'jj' mapped to 'esc' for insertModeKeyBindings.  I pressed 'R' and started to type.  When I press jj, the letters jj replace the letters under the cursor.  I then press escape to leave Replace mode.

### What did you expect to happen?

I expected to undo the second replacement and leave Replace mode after the second 'j'.

### What happened instead?

It continued to replace letters.

### Technical details:

* VSCode Version: 1.10.2
* VsCodeVim Version: 0.6.13
* OS: OS X El Capitan 10.11.6

I noticed that the insertModeKeyBindings only apply to Insert Mode [here](https://github.com/VSCodeVim/Vim/blob/master/src/mode/remapper.ts#L158), which makes sense, but in vim, I believe :imap also applies to replace mode.

I played around with the code a little and noticed that if I added ReplaceMode to the InsertModeRemapper remappedModes and the [check for removing the last character](https://github.com/VSCodeVim/Vim/blob/master/src/mode/remapper.ts#L99), it would correctly be triggered when in Replace mode.  I believe the issue there is that the historyTracker undoAndRemoveChanges will remove the character where the first j was entirely, since it relies on the removing what it thinks is the last insert using the historyTracker currentHistoryStep.

I'd be more than happy to take a stab at this, but I wanted to float it around to see if anyone else had any ideas/guidance for this.  Thanks!

**Comment by ssfrr** [comment]
This would be great to see addressed. I use `ctrl+[` instead of `esc` to go from insert mode to normal mode, but it doesn't work in replace mode, so I often end up typing a bunch more characters in because I think I'm in normal mode.

**Comment by bad5ect0r** [comment]
Still having issues with this. I have the following in my `vim.insertModeKeyBindings`:

 ```
   "vim.insertModeKeyBindings": [
        {
            "before": ["j", "j"],
            "after": ["<Esc>"]
        }
    ],
```
It works in insert mode, but replace mode does not recognize that I am trying to get out of replace mode.
