### ISSUE TITLE
Latest update changed insert cursor

### ISSUE THREAD

**Issue by haf** [VSCodeVim/Vim#1473]
### What did you do?

Pressed `i`

### What did you expect to happen?

The cursor should change from a block cursor to a caret cursor.

### What happened instead?

The cursor remained a block cursor.

### Technical details:

* VSCode Version: 1.10.2
* OS: OS X

**Comment by juliankmazo** [comment]
ohh god, I'm having the same issue. Is so frustrating 😜 . I thought it was a setting but I can't find how to change it.

**Comment by xconverge** [comment]
What is your editor.cursorStyle set to? In the latest update, we now respect this setting. This was done so that users could use line, line-thin, underline, underline-thin as their insert mode cursor natively instead of us just always forcing it to line.

Try setting editor.cursorStyle to line

**Comment by dahjelle** [comment]
That fixed it for me! Thanks, @xconverge !

(It looks like "line" is the default setting, so I just removed the setting from my config entirely.

Thanks!

**Comment by juliankmazo** [comment]
ahh, this is so weird. So, I looked for `editor.cursorStyle` and it was set to `line` in the default config. So I rewrite it again in my user settings an it worked. Looks like the update at first glance does not recognize the default config so you have to rewrite it in order to fix it. Now I delete it from my user settings and it works as expected.

**Comment by xconverge** [comment]
Leaving this open a bit so that others may see it, will close it in the next few days

**Comment by subvertallchris** [comment]
I also needed to explicitly state `line` to resolve this, despite the default.

**Comment by haf** [comment]
Thanks everybody for your help. Removing the config solves it.
