### ISSUE TITLE
z. command  (redraw, current line at center of window) does not work

### ISSUE THREAD

**Issue by jschiefer** [VSCodeVim/Vim#1475]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Opened a file larger than one window's worth. Positioned the caret to the bottom of the window by pressing `L`. Then pressed `z.`

### What did you expect to happen?
I expected the text in the window to scroll up, such that the line that contains the caret would be in the center of the window.

### What happened instead?

Nothing happened. 

### Other observations
- The roadmap says that both the `z.` and `zz` commands (redraw, current line at center of window) were implemented.
- In fact, the `zz` command works as expected.

### Technical details:

* VSCode Version: 1.11.0
* VsCodeVim Version: 0.6.13
* OS: Linux Mint 17.3 x86_64

**Comment by johnfn** [comment]
So to make sure I understand, you are saying that z. is just a synonym for zz that we're missing?

**Comment by jschiefer** [comment]
They are a little different. According to the vim documentation, [zz](http://vimdoc.sourceforge.net/htmldoc/scroll.html#zz) keeps the caret in the same column it is currently in, whereas [z.](http://vimdoc.sourceforge.net/htmldoc/scroll.html#z.) positions the caret to the first non-blank character in the line.

It just so happens is that `z.` is the one that has been in my motor memory for a long time...

**Comment by jschiefer** [comment]
Awesome, thank you!

**Comment by rich1383** [comment]
Is there a way to add a keyboard shortcut for "z<cr>" - another motor memory I cannot stop typing (puts current cursor line at top of window)?

**Comment by johnfn** [comment]
@rich1383 no new version is even needed (though one will probably be forthcoming anyways) - that's the beauty of remapping! Simply add this to your settings.json

```

                "before": ["z", "\n"],
                "after": ["z", "t"]
```

**Comment by rich1383** [comment]
Thanks - I didn't know about zt or zb.  One more motor memory resolved!

**Comment by rich1383** [comment]
Not sure how to ask a question on this project:  I was wondering if there is a chance to get the "ga" command added?  Very useful for identifying binary character under the cursor (command mode) in ascii, hex, octal, decimal; such as tabs, trademark symbol, etc.

**Comment by johnfn** [comment]
@rich1383 the way to ask for a new feature is normally to open up a new issue, like the one you are currently on. :) Opening up a new issue makes it easier for us to find features to add.
