### ISSUE TITLE
Copy error if the line has Chinese character 

### ISSUE THREAD

**Issue by Pythians** [VSCodeVim/Vim#1476]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

## If the line has Chinese character
- IN VISUAL MODE
Can't use `y` or `cmd + c` to copy the select text, all registers are empty

- IN NORMAL MODE  
Use `Y` or `ym` to copy, the text only copy to '0' register
Can't use `y` to copy a Chinese character   

- IN INSERT MODE
Can't use `cmd + c` to copy the select text

### Technical details:

* VSCode Version: 1.11.0
* VsCodeVim Version: *0.6.13*
* OS: macOS 10.12.3 (16D32)

**Comment by xconverge** [comment]
What happens? Is this the same as #1392

**Comment by Pythians** [comment]
Not only Chinese, Japanese, Korean and Arabic have this issue, perhaps more languages have this problem

**Comment by Pythians** [comment]
I've seen #1392  
#1392  focuses on paste, this issue focuses on copy and probably is at the root of a problem

**Comment by xconverge** [comment]
Can you try this again with the latest release? 0.6.17

**Comment by Pythians** [comment]
All the problems are fixed !
_Great work !!_
