### ISSUE TITLE
The multi-cursor shortcut 'gc' won't work

### ISSUE THREAD

**Issue by DrakeXiang** [VSCodeVim/Vim#1477]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Tried to use multi-cursor function on a word but didn't work. This function was handy before the latest update.

Put the exact keys you pressed.
gc 
### What did you expect to happen?
The word should be selected

### What happened instead?
vscodeVim entered insert mode

### Technical details:

* VSCode Version: 1.11.0
* VsCodeVim Version: 0.6.14
* OS:  windows 10.0.14393

**Comment by binarious** [comment]
Multi-cursor doesn't work for me at all with vscode 1.11.0 and vim 0.6.14. Not even CMD+D (on Mac).

**Comment by xconverge** [comment]
cmd+alt arrows to add cursors and alt clicking to add cursors works correctly..

**Comment by xconverge** [comment]
@johnfn @rebornix any ideas on this one? We can't win if we use stable only and we cant win if we use insiders 😆

**Comment by johnfn** [comment]
I'm confused. They seem to work fine for me - cmd-d, gc, all on the latest version (1.10.0). What am I missing?

**Comment by binarious** [comment]
@johnfn 1.10.0 is not the latest version: https://code.visualstudio.com/updates/v1_11

**Comment by johnfn** [comment]
Oops - I am on 1.11, my mistake.

**Comment by binarious** [comment]
No worries. I have disabled all other plugins and erased my settings.json. Still not working. Anything else we can try?

**Comment by xconverge** [comment]
I can reproduce this as well

**Comment by juandaco** [comment]
Not working for me either

**Comment by rich1383** [comment]
None of the documented shortcuts work for me on my Mac (v1.11).  However, a right-click over the desired object does give you the "Change All Occurrences" choice, which is documented as <cmd>F2 (I have to also add the <fn> key) - this also works.

**Comment by xconverge** [comment]
I am taking a peek at this right now, hoping it is solvable and not a regression on vscode side

**Comment by johnfn** [comment]
I'm really mystified by this because I can't repro at all. @xconverge halp

**Comment by xconverge** [comment]
messaging you on slack instead of here

**Comment by johnfn** [comment]
Okay wow this issue was entirely due to my own stupidity. Sorry guys. Thanks @xconverge.
