### ISSUE TITLE
add selection to next find match (CMD+D) broken on macOS

### ISSUE THREAD

**Issue by binarious** [VSCodeVim/Vim#1478]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Move cursor on a word, press `i` and `CMD + D` (multiple times).

### What did you expect to happen?

Another cursor should be added to the next occurrences of that word.

### What happened instead?
The words have been highlighted, but no cursor was added.

![out](https://cloud.githubusercontent.com/assets/200375/24747270/11e77f36-1abc-11e7-8ebe-a81c215314bc.gif)

### Technical details:

* VSCode Version: 1.11.0
* VsCodeVim Version: 0.6.14
* OS: macOS 10.12.4

**Comment by johnfn** [comment]
Sorry guys. This issue was due entirely to my own stupidity. Props to @xconverge for realizing how dumb I was. 

It should be fixed now.

**Comment by binarious** [comment]
Thank you for the quick fix! It now works in Normal Mode, but nothing happens in Insert Mode. Is this intentionally?

**Comment by xconverge** [comment]
That is tracked in another issue and is not implemented yet
