### ISSUE TITLE
Pressing 'x' multiple times freezes interface

### ISSUE THREAD

**Issue by AJMiller** [VSCodeVim/Vim#1480]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Held down the 'x' key to delete multiple letters

### What did you expect to happen?

Expected the editor window to delete the letters

### What happened instead?

Keyboard input freezes up for 3-6 seconds before performing delete action. Any keys pressed during the frozen time will be executed rapidly when the keyboard unfreezes. Mouse movements work fine and cursor can be moved with mouse, only vim keybindings are frozen.

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.14
* OS: macOS 10.12.4

**Comment by johnfn** [comment]
Does this happen every time you hold down x?

**Comment by AJMiller** [comment]
@johnfn yes it consistently happens even if I press 'x' twice in a row quickly. Disabling the vim plugin makes VSCode work normally with no interruptions

**Comment by AJMiller** [comment]
this issue appears to be resolved with the update pushed this am (0.6.15). If it regresses, I'll reopen.
