### ISSUE TITLE
Is there any way to remap the easymotion keys?

### ISSUE THREAD

**Issue by edasaki** [VSCodeVim/Vim#1481]
In vim I have the "Search Character" set to just s since I never really use the actual s in insert mode.

Is it possible to change the binding in vscodevim? I use the search a lot but pressing the leader twice is a bit tiring sometimes.

And kind of vaguely related, is it possible to change the red/orange font colors? I want to keep the black background but the red/orange is a bit hard to read for me.

**Comment by johnfn** [comment]
> And kind of vaguely related, is it possible to change the red/orange font colors? I want to keep the black background but the red/orange is a bit hard to read for me.

It sounds like you're talking about theming VSCode, which is totally separate from VSCodeVim! Check here https://code.visualstudio.com/docs/getstarted/themes

**Comment by edasaki** [comment]
Oh sorry I realized that totally wasn't clear haha.

I was talking about the popups from the easymotion plugin

![](http://i.imgur.com/nOGu0kA.png)

Is that also handled by VSCode themes? Since it seems like it's something that would be decided by vscodevim

**Comment by johnfn** [comment]
OHH, those themes! My bad! Yeah huh.. those should probably be re-themeable, sure.

To be honest, the unfortunate truth about extensions (e.g. EasyMotion) is that they're mostly community supported, as it's just too much effort for me to maintain both Vim and an extension ecosystem. You _may_ be able to convince @xconverge if you ask really nicely, but that guy is pretty busy too haha. :P

**Comment by xconverge** [comment]
@edasaki we DO allow you to change the color

from here https://github.com/VSCodeVim/Vim#how-to-use-easymotion

"If you set vim.easymotionChangeBackgroundColor to true you can use the searchHightlightColor as the background color for the text decorations, however you then lose the red/orange indicators on whether it is a one key or two key combination since the font color needs to stay readable."

**Comment by xconverge** [comment]
I analyze the colors and then set the font to either white or black based on the search highlight color you use

**Comment by FelikZ** [comment]
> Is it possible to change the binding in vscodevim?

```json
{
        "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["s"],
            "after": ["leader", "leader", "s"]
        }]
}
```

**Comment by edasaki** [comment]
Thank you so much @FelikZ , that worked!

And thank you too @xconverge! That's fine for me

**Comment by xconverge** [comment]
There is 1 related bug that is somewhat funny though :) #1426, feel free to thumbs up it if it impacts you

Thanks

**Comment by pavilion** [comment]
This doesn't work... has the command changed? :smile:

**Comment by niamleeson** [comment]
@pavilion https://github.com/VSCodeVim/Vim/issues/2755

**Comment by smzm** [comment]
> This doesn't work... has the command changed? smile

Test this code. 

```json
"vim.normalModeKeyBindingsNonRecursive": [
    {
        "before": ["s"],
        "after": ["leader", "leader", "s"]
    }
]
```

**Comment by mwanchap** [comment]
@rndware 
> What would the binding syntax be if you want to search by two chars?

```
"vim.normalModeKeyBindingsNonRecursive": [
    {
        "before": ["f"],
        "after": ["leader", "leader", "2", "s"]
    }
],
```
