### ISSUE TITLE
Auto indent in matching brace not working in scss files

### ISSUE THREAD

**Issue by jmahony** [VSCodeVim/Vim#1482]
### What did you do?
Created a scss file:
```scss
1
2 .my-class {
3         color: red;
4           background-color: blue;
5 }
6
```

Placed cursor at beginning of line 5.

Pressed
`={` in Normal mode

### What did you expect to happen?
The indentation of line 3 and 4 to be corrected to 2 spaces. This works in `js` files.

### What happened instead?
Cursor was moved to start of line 1

### Technical details:
* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.15
* OS: Window 10

**Comment by johnfn** [comment]
Also I like how the `={` action is your reaction to it not working. 

😞

**Comment by jmahony** [comment]
haha 😄 

Nope, VSCode auto indent doesn't seems to be working either. I guess this can be closed then.

Thanks for your help!
