### ISSUE TITLE
double click selection highlights extra character in visual mode

### ISSUE THREAD

**Issue by vogler** [VSCodeVim/Vim#1488]
Double clicking inside `"foo"` in insert mode selects `foo`, but in normal mode it results in the selection `foo"` being shown. Acting on the selection works as expected, it's just not displayed correctly.
Follow-up of #641.

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.15
* OS: macOS 10.12.5

**Comment by xconverge** [comment]
This is fixed on master, thanks
