### ISSUE TITLE
Unable to unmap / unbind ctrl+shift+2

### ISSUE THREAD

**Issue by FelikZ** [VSCodeVim/Vim#1489]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Trying to unbind `ctrl+shift+2` that is [mapped by default](https://github.com/VSCodeVim/Vim/blob/ca9af90834145c2249a15e24f6bbfb4a4d60ad9e/package.json#L225):

```json
            {
                "key": "ctrl+shift+2",
                "command": "extension.vim_ctrl+shift+2",
                "when": "editorTextFocus && vim.use<C-shift+2>"
            },
```

Like this:

```json
    {
        "key": "ctrl+shift+1",
        "command": "workbench.action.terminal.focusPrevious"
    },
    {
        "key": "ctrl+shift+2",
        "command": "-extension.vim_ctrl+shift+2"
    },
    {
        "key": "ctrl+shift+2",
        "command": "workbench.action.terminal.focusNext"
    },
```

I also tried to disable this in settings:

```json
    "vim.handleKeys": {
        "<C-shift+2>": false,
        "<C-shift-2>": false,
        "<C-@>": false,
    }
```

### What did you expect to happen?

When I press `ctrl+shift+2` I navigate next terminal tab (or any other action)

### What happened instead?

Nothing, while `ctrl+shift+1` works fine.

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.15
* OS: Ubuntu

**Comment by xconverge** [comment]
I just tested this on windows and it works:
```
    {
        "key": "ctrl+shift+1",
        "command": "workbench.action.terminal.focusPrevious"
    },
    {
        "key": "ctrl+shift+2",
        "command": "workbench.action.terminal.focusNext"
    }
```

and 

```
    "vim.handleKeys": {
        "<C-shift+2>": false
    }
```

**Comment by FelikZ** [comment]
@xconverge maybe its linux only, or my setup specific. Still reproduced for me. Do not see a way to debug.

**Comment by xconverge** [comment]
I can try on Linux tonight and let you know

**Comment by FelikZ** [comment]
@xconverge "Keyboard Shortcuts" manager, detects `ctrl+shift+2` correctly, so its not system-wide blocking hotkey (fyi)

**Comment by xconverge** [comment]
Confirmed that the exact settings I have above work on Ubuntu...I put only those 2 in keybindings.json and then added the .handleKeys setting...

**Comment by FelikZ** [comment]
@xconverge thanks for spending time on it, really appreciated! Any way to debug hotkeys in vscode?

I had an idea that it might be caused by, for example, VIM extension, but its not. I disabled it and still same results.

I am using [Sync Settings](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) plugin that stores configuration as a [gist](https://gist.github.com/FelikZ/ff1bc6ca989418e7dc1b343c25f52d19).

This is how my [keybindings](https://gist.github.com/FelikZ/ff1bc6ca989418e7dc1b343c25f52d19#file-keybindings-json) and settings looks like.

If its possible for you to try this ones? I tryied this on OSX and it reproduced there as well for me with this configuration.

**Comment by xconverge** [comment]
You are missing         "<C-shift+2>": false in handleKeys

**Comment by FelikZ** [comment]
@xconverge as [I said here](https://github.com/VSCodeVim/Vim/issues/1489#issue-220606170) I tried to add this before, but it does not help, so I removed it. Will try again soon, will push changes to settings repo.

**Comment by xconverge** [comment]
All I am saying is that from the settings you sent me, it won't work. If you use the exact settings I posted it works on Linux for me.

**Comment by FelikZ** [comment]
@xconverge tested more of it. Works as expected on OSX and Windows but not Linux yet.
Tried to re-bind `ctrl+shift+2` to `ctrl+shift+3` - then it works.
So something really wrong with exactly those combination for me on linux.
I added "<C-shift+2>": false in handleKeys, but it works without it on osx and win, so it has no effect.

I disabled all extensions, all user settings and all use keybindings except `ctrl+shift+1/2` - still does not work.

The only way I see to solve it is to debug somehow keypresses (`ctrl+shift+2` is 100% handled by vscode, since I see it in keyboard shortcuts manager)

**Comment by xconverge** [comment]
I tested it on Ubuntu though...

**Comment by FelikZ** [comment]
Empty user settings:
```json
{
}
```

Keybindings:
```json
[
    {
        "key": "ctrl+shift+1",
        "command": "workbench.action.terminal.focusPrevious"
    },
    {
        "key": "ctrl+shift+2",
        "command": "workbench.action.terminal.focusNext"
    }
]
```

- All plugins are disabled
- vscode version:
```
Version 1.11.2
Commit 6eaebe3b9c70406d67c97779468c324a7a95db0e
Date 2017-04-13T08:01:14.464Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
- vscode windows reloaded after plugins disabled
- Ubuntu:
```
$ uname -a
Linux tk9 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xconverge** [comment]
Please put 
```
 "vim.handleKeys": {
        "<C-shift+2>": false
    }
```

**Comment by xconverge** [comment]
I'll try again later.. sorry for being frustrating...

We bind Ctrl+shift+2 so the handle keys is necessary, I will try to see why it wasn't necessary on the other OSes.

**Comment by FelikZ** [comment]
@xconverge it appears to be not a `VSCodeVim` issue, since this keybinding does not work even if I disable ALL plugins including `VSCodeVim`.

**Comment by xconverge** [comment]
Hmmm, strange! I tested on Ubuntu with no issues

**Comment by FelikZ** [comment]
@xconverge I would create another issue in vscode issues and this one can be closed for now. (will refer this issue there)
