### ISSUE TITLE
The cursor will move to the end of line when select lines

### ISSUE THREAD

**Issue by haolly** [VSCodeVim/Vim#1496]
--------

### What did you do?

put the cursor on the start of line A, press key **V**, and then **j** to select lines below,
the lines below A are selected, but the cursor goes to the end of line when I press **j**,
this is annoying, especially when the line is long than the screen with, because this makes the whole screen 
shift to right, this is not the behavior in vim

### What did you expect to happen?
the cursor is on the same column when press **j**

### What happened instead?
the cursor is moved to the end of line

### Technical details:

* VSCode Version: 1.11.0
* VsCodeVim Version: 0.6.15
* OS: windows 10

**Comment by johnfn** [comment]
This is not the behavior of vim only because Vim word wraps. Toggle word wrap with the command palette and you will not get this behavior.

**Comment by haolly** [comment]
Let's assume the * is cursor, when press `Vj`, the cursor should be  * in the second line,
not in the position of  #, whether the word wrap is set or not
`------*------------------`
`------*------------------#`

**Comment by johnfn** [comment]
Agreed- unfortunately vscode does not allow cursors to be in the center of a selection presently.
