### ISSUE TITLE
Remap of caps-lock to escape no longer working.

### ISSUE THREAD

**Issue by Alex-Addy** [VSCodeVim/Vim#1497]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?
With the new version of VSCode or VSCodeVim my remapping of the escape key is no longer being respected. I remapped the caps lock key to escape using the gnome tweaks tool and up until updating to the newest version I could use this remapping to return to normal mode.

### What did you expect to happen?
When I press my keyboards caps-lock key I should leave Insert or Visual mode and return to Normal mode as if escape had been pressed.

### What happened instead?
The key press is ignored and my mode does not change.

### Technical details:
The remapping is still working as it still works in other applications and even in vim in a terminal. It also works as expected to cancel the hint dialog brought up by `gh`. The remapping set by "vim.insertModeKeyBindings" still works along with the original Esc key. My caps-lock is not toggled either, the key press is just ignored.

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.6.15
* OS: Linux 4.4.0-47-generic x86_64

**Comment by xconverge** [comment]
This is a duplicate, can you see this issue, there is a vscode workaround I think

https://github.com/VSCodeVim/Vim/issues/1479

**Comment by Alex-Addy** [comment]
I see, it appears my issue searching fu is weak.

**Comment by navdeepio** [comment]
facing this issue on vscode 1.12.2-1 on arch linux, has the fix been shipped?

**Comment by Chillee** [comment]
@navdeepio I don't think they've fixed it on the vscode side yet.

**Comment by cassepipe** [comment]
2020, still a problem

**Comment by awalvie** [comment]
can confirm, still a problem
