### ISSUE TITLE
run all tests in CI server(s)

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#15]
The idea is to do this in the CI server(s):

- install code
- install vim ext
- start vs code
- run tests in vs code
- redirect test output to file
- read output from file and determine success/failure

**Comment by jpoon** [comment]
Re: https://github.com/Microsoft/vscode/issues/118

**Comment by guillermooo** [comment]
I think that being able to redirect the tests output to a file would be enough; no need to mock out the whole VS Code API from the cli. If I got you right.

**Comment by jpoon** [comment]
@guillermooo it's more so that tests execute within the context of VSCode so it requires a window.

**Comment by guillermooo** [comment]
GUIs run fine en Appveyor and you can get Travis to run GUIs too.

See: https://github.com/randy3k/UnitTesting/blob/master/sbin/travis.sh#L78

We test Sublime Text just fine in both CI services.

**Comment by jpoon** [comment]
Sweet! Didn't know you can have windowed processes on Travis or Appveyor. Definitely would be a better solution to just running a subset of the tests as we are now. I think we are blocked on this until https://github.com/Microsoft/vscode/issues/118.

**Comment by jpoon** [comment]
With Dec. update, possible to run tests with Travis CI (https://code.visualstudio.com/Docs/extensions/testing-extensions)

Caveats:
* Does not work on Windows (e.g. AppVeyor)
* activeTextEditor is null => any UI tests which insert/delete will fail :(
