### ISSUE TITLE
im extension should also follow the command dynamicly register and release patern. otherwise other extension could not use the 'type' command

### ISSUE THREAD

**Issue by metasong** [VSCodeVim/Vim#1500]
when installed vscodevim and jumpy or acejump or metago. there will be problems to use other extensions
for example with metago, if you press alt+; and then press the charactor, and type the codes you will go to that location. but currently because vim already registed the 'type' command and never dispose it when not used.
```
registerCommand(context, 'type', async (args) => {
    taskQueue.enqueueTask({
      promise: async () => {
        const mh = await getAndUpdateModeHandler();

        if (compositionState.isInComposition) {
          compositionState.composingText += args.text;
        } else {
          await mh.handleKeyEvent(args.text);
        }
      },
      isRunning: false
    });
  });
```
this cause others could not register this 'type' command and release it when not used.

the vim extension should also follow the dynamicly register and release patern. otherwise other extension could not use the 'type' command

**Comment by rebornix** [comment]
First of all, this is by-design, Code only allows one single handler for `type` https://github.com/Microsoft/vscode/issues/13441.

Secondly, I don't get the idea of `release it when not used`, if we dispose the handler when not used, next time when users want to use Vim, they have to run a command or restart VS Code to bind the handler again, which is not reasonable.
