### ISSUE TITLE
ctrl+m or ctrl+j to insert <enter> with insert mode.

### ISSUE THREAD

**Issue by millionbonus** [VSCodeVim/Vim#1505]
### What did you do?
1. In setting.json turn on the ctrl keys support with `"vim.useCtrlKeys": true`
2. In text editor pressed `i` to go to insert mode.
3. pressed `ctrl+m` or `ctrl+j`.

### What did you expect to happen?
Insert a new line break(\<enter\>) in to text editor.

### What happened instead?
Nothing happened.

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: 0.16.5
* OS: windows 10

**Comment by johnfn** [comment]
okay i mean we can totally add that but i gotta know: why dont you just use enter??

**Comment by millionbonus** [comment]
As a vimer. 
I use hjkl instead of arrow keys.
I use `ctrl+[` instead of `<esc`>. (and keep index finger on `j`) 
I use `ctrl+m` instead of `<enter>`. (just move index finger little bit to `m` then back to `j` very quick)  
Just because those keys are too far for my little finger.

**Comment by rebornix** [comment]
This can be covered by https://github.com/VSCodeVim/Vim/issues/1543

**Comment by millionbonus** [comment]
Can also this behavior apply in '`/`' and '`?`' searching?

**Comment by millionbonus** [comment]
A workaround is that setting a keybinding `<ctrl-m>` to inert snippet `\n` 
```json

    {
        "key": "ctrl+m",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && !inDebugRepl && vim.mode == 'Insert'",
        "args": {
          "snippet": "\n"
        }
    },
    {
        "key": "ctrl+j",
        "command": "editor.action.insertSnippet",
        "when": "editorTextFocus && !inDebugRepl && vim.mode == 'Insert'",
        "args": {
          "snippet": "\n"
        }
    }
```

However, it still can't use those combination in command line.

**Comment by can3p** [comment]
Is there a technical reason why this can't be done? From the first sight it's not, since Ctrl-[ works both in command line and in insert mode

**Comment by can3p** [comment]
Can we resurrect this issue? I've implemented ctrl+m support in a linked pull request

**Comment by kktt007** [comment]
> As a vimer.
> I use hjkl instead of arrow keys.
> I use `ctrl+[` instead of `<esc`>. (and keep index finger on `j`)
> I use `ctrl+m` instead of `<enter>`. (just move index finger little bit to `m` then back to `j` very quick)
> Just because those keys are too far for my little finger.

cool, can u show your shortcuts list here. i want to reference. Because it seems you are good at this.

**Comment by thegabriele97** [comment]
I solved with this keybind

```json
    {
        "key": "ctrl+j",
        "command": "editor.action.insertLineAfter",
        "when": "editorTextFocus && !inDebugRepl",
    },
```
