### ISSUE TITLE
It seem that there is a bug for "Insert mode". It has same appearance with the Normal mode.

### ISSUE THREAD

**Issue by newforrestgump001** [VSCodeVim/Vim#1508]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Put the exact keys you pressed.

### Technical details:

* VSCode Version:
* VsCodeVim Version: *[please ensure you are on the latest]*
* OS:

**Comment by xconverge** [comment]
can you make sure editor.cursorStyle is set to "line"

**Comment by newforrestgump001** [comment]
Yes, I have checked, the cursorStyle is already set to "line", but 
"insert mode" still have the same appearance with "normal mode".

**Comment by xconverge** [comment]
Sorry but can you update your original issue to include version numbers, os, etc. The template is there to help get an answer! :)

Is this in any file type?

**Comment by newforrestgump001** [comment]
The version number is v0.6.15, newest version.

This occurs when I edit cpp file. Thanks!

**Comment by xconverge** [comment]
Can you copy paste your entire settings.json file? Does restarting vscode help?

**Comment by newforrestgump001** [comment]
Please check settings.json in the attachment.

The problem keeps for several days, restartng vscode doen't help. Thx!

**Comment by icewind** [comment]
I have this issue too, but I thought it is intentional.
As for me, I like it. It is more like real vim(no line cursor).

**Comment by newforrestgump001** [comment]
I often input extra i when I am in insert mode, which is not what I want.

The cursor is blink block, so I think it is in normal mode.

There is no such issue for v0.6.14.

**Comment by xconverge** [comment]
I don't see your attachment.

Can you try this, try setting editor.cursorStyle to underline, and then back to line

**Comment by newforrestgump001** [comment]
It works, thank you very much!
