### ISSUE TITLE
vscodevim breaks occurrences highlighting when using keyboard navigation

### ISSUE THREAD

**Issue by jacobdufault** [VSCodeVim/Vim#1511]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Click a symbol in a document. The symbols with the same name (references to that symbol) get highlighted. In command mode, press `h` or a some command to move the cursor around. Symbols are no longer highlighted.

If vscodevim is disabled, symbols are still shown when moving with the arrow keys. With vscodevim enabled, even moving with arrow keys is broken.

Before:

![image](https://cloud.githubusercontent.com/assets/356714/25034890/b2255364-209e-11e7-83f9-9509c149ab46.png)

After:

![image](https://cloud.githubusercontent.com/assets/356714/25034895/ba493d1c-209e-11e7-9ba8-2cddb48598d5.png)

### What did you expect to happen?

Symbol references stay highlighted.

### What happened instead?

Symbol references are not highlighted.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.15
* OS: Win10

**Comment by J-Fields** [comment]
Closing in favor of #3044
