### ISSUE TITLE
Curosr moves to wrong a position when input word which has more than one letters with InputMethod.(Ubuntu)

### ISSUE THREAD

**Issue by holmeszyx** [VSCodeVim/Vim#1512]
### What did you do?

Curosr moves to wrong a position when input word which has more than one letters with InputMethod in Vim insert mode.

If I input one letter (or one chinese character), the cursor is move to the end, it is ok.
But if I input many letters (or chinese characters) once, the cursor still on the begin of all the letters I just inputted.

e.g:
Use "|" to instead cursor. And it is already has content "abc" in the editor, and the cursor is after letter "c".
like this,  "abc|"

1. right thing
 if input one letter "T":
```
"abcT|"
```
if input one chinese "的":
```
"abc的|"
```
2. the wrong, when use InputMethod
 if input a word which has many letter, "Text":
```
"abc|Text"
```
if input chinese word "神马":
```
"abc|神马"
```

Put the exact keys you pressed.

### What did you expect to happen?

Whatever I input , the cursor alway position on the end of I inputted content.
Like the last example above.
I expect this
```
"abc神马|"
```

### What happened instead?
No instead. I just input only one chinese character or don't use any InputMehod

### Technical details:

* VSCode Version: Now I use Version `1.11.2`. but it happen on every version
* VsCodeVim Version: *[please ensure you are on the latest]*. `0.6.15` the latest one
* OS: Ubuntu 16.04.2 LTS, kernel 4.4.0-72-generic . 
InputMethod is Fcitx

**Comment by Chan-Chun** [comment]
yep! my vim has the same problem

**Comment by rebornix** [comment]
@holmeszyx @Chan-Chun can you try to disable VIm and see if you can reproduce this with vanilla VS Code?

**Comment by holmeszyx** [comment]
@rebornix It seems to has been fixed, when I update VIM to 0.6.17 and VsCode to 1.11.2.
All inputs are right, whether in VIM Insert Mode or origin Vscode whith VIM disabled.

I will try update the Vim and  VsCode on other computers to confirm the result.

**Comment by holmeszyx** [comment]
@rebornix yeah! This bug did not happen in VIM 0.6.17.

**Comment by s-s-k** [comment]
@rebornix my vim has the same problem.
* VSCode version : 1.12.1
* vim version: 0.7.0
I tried to disable vim and there is no problem.

**Comment by Chillee** [comment]
Same issue as this I think: https://github.com/VSCodeVim/Vim/issues/1027

**Comment by Chillee** [comment]
As multiple people have reported this issue as fixed, I will close this issue. Please report it if it's still a problem.
