### ISSUE TITLE
blank line regex doesn't work

### ISSUE THREAD

**Issue by simahao** [VSCodeVim/Vim#1517]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?
I want to delete all blank line,cmd is :g/^$/d

### What did you expect to happen?
Delete all blank line by regex.
### What happened instead?
It doesn't work.
### Technical details:

* VSCode Version:1.11.2
* VsCodeVim Version: 0.6.15
* OS: win7

**Comment by Chillee** [comment]
This is probably more due to use not implementing `:g` than it is the regex.
https://github.com/VSCodeVim/Vim/issues/828

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).
