### ISSUE TITLE
No new blank line when `c' after `V'

### ISSUE THREAD

**Issue by lsdsjy** [VSCodeVim/Vim#1518]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Vjc

### What did you expect to happen?
The current line and the line below should be removed and a new blank line should be inserted.

### What happened instead?
The two lines are removed but no newline was inserted.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.15
* OS: Windows 10
(All the above are up to date.)

**Comment by rebornix** [comment]
@lsdsjy can you provide a gif to help trouble shoot? I can't reproduce this issue.

**Comment by lsdsjy** [comment]
@rebornix 
![gvim](https://cloud.githubusercontent.com/assets/1356263/25301298/a3645128-2755-11e7-8b47-cf6ea9f1c11f.gif)
![vscvim](https://cloud.githubusercontent.com/assets/1356263/25301299/a3673e2e-2755-11e7-8b2a-60772f24d3da.gif)
