### ISSUE TITLE
repeat inserted character/word (e.g., 5i...[esc]) multiline support

### ISSUE THREAD

**Issue by Platzer** [VSCodeVim/Vim#1523]
### What did you do?

`5i` - insert multiline text `line1<enter>line2` - `<esc>`

### What did you expect to happen?

```
line1
line2line1
line2line1
line2line1
line2line1
line2
```

### What happened instead?

```
line1
line2line1line2line1line2line1line2line1line2




```

![vscode_vim_5i_multiline](https://cloud.githubusercontent.com/assets/3358663/25116056/a3a66016-240a-11e7-8d67-176b180cba96.gif)

Implemented with PR #1495, see also Issue #1122. BTW.: Nice work @xconverge 👏.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: *0.6.16*
* OS: Win 7 x64

**Comment by xconverge** [comment]
I didn't think this report would be so quick :/ thanks for reporting it!

**Comment by xconverge** [comment]
@rebornix this is where the content change method falls apart I think... Any ideas?

**Comment by rebornix** [comment]
@xconverge it only happens when the line break is set to `CRLF`. It seems the content change only uses LF but I didn't verify yet. If so then it's a Code issue.

**Comment by xconverge** [comment]
I still will need to replay back for each cursor to support this ticket, but if it is a code issue and not working as designed for the contentChange I can wait on that

**Comment by Chillee** [comment]
So does this bug only occur on windows systems (considering the clrf req)?

**Comment by Platzer** [comment]
Working in vscode `1.13.0` on windows!

**Comment by xconverge** [comment]
Freebie! @rebornix :)
