### ISSUE TITLE
move line not worked

### ISSUE THREAD

**Issue by codelegant** [VSCodeVim/Vim#1524]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

```
1  First line
2  Second line
3  Third line
```
`:3 m 1`

### What did you expect to happen?
```
1  First line
2  Third line
3  Second line
```

### What happened instead?
nothing happened

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.16
* OS: win10 1607

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).
