### ISSUE TITLE
Search/replace causes double replacement with capture group

### ISSUE THREAD

**Issue by casey-speer** [VSCodeVim/Vim#1525]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

With a list of words, one per line:
```
div
span
input
script
```
Press `:` to enter command mode, type `%s/(.*)/'$1',/g`, hit enter. 

### What did you expect to happen?
The list of words is transformed to:

```
'div',
'span',
'input',
'script'
```

### What happened instead?
The list is transformed to:
```
'div','',
'span','',
'input','',
'script''',
```

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.16
* OS: MacOS 10.11.6

**Comment by xconverge** [comment]
related

#991

**Comment by Chillee** [comment]
With the new PR , this issue is fixed as long as you use
`%s/.*/'$1',/g`

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).
