### ISSUE TITLE
:g command doesn't work as expected

### ISSUE THREAD

**Issue by casey-speer** [VSCodeVim/Vim#1526]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Given a list of words/phrases, one per line:
```
<tag>
<moretag>
not a tag
<tagtag>
```
type `:` to enter command mode, type `g!/</d`.

### What did you expect to happen?
The lines not matching `<` are deleted:
```
<tag>
<moretag>
<tagtag>
```

### What happened instead?
Nothing:
```
<tag>
<moretag>
not a tag
<tagtag>
```
### Technical details:

* VSCode Version: 1.11.12
* VsCodeVim Version: 0.16.6
* OS: 10.11.6

**Comment by casey-speer** [comment]
Not sure if other uses of `:g` are working, this is `:g/xxx/d` and `:g!/xxx/d` are the ones I use most frequently.

**Comment by xconverge** [comment]
#828

**Comment by jpoon** [comment]
Closing this in favor of #828
