### ISSUE TITLE
command not found after opening settings.json

### ISSUE THREAD

**Issue by chaseadamsio** [VSCodeVim/Vim#1527]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?
opened VS Code, then opened settings and attempted to type in my settings.

### What did you expect to happen?

To be able to type as I would in any other file with the vim extension enabled.

### What happened instead?

In some cases, I get the following:

![image](https://cloud.githubusercontent.com/assets/1024544/25153883/1fd26e9a-2443-11e7-9a92-adc58df74b48.png)

Multiple "command not founds"

In other cases (maybe where I have multiple windows for vscode open), I get no error messages and am unable to input data. Attached gif:

![screenflow](https://cloud.githubusercontent.com/assets/1024544/25154190/779728fe-2444-11e7-97e2-eb1fe1f66d3d.gif)

Then I tried to go to other files to edit and continued to get the same errors until I restarted Code. 

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: *0.6.16*
* OS: OSX El Capitan 10.11.6

**Comment by xconverge** [comment]
This looks more like a vscode issue... I have noticed sometimes the cursor does not update correctly in the settings window only, but besides that have not seen anything like this @rebornix

**Comment by xconverge** [comment]
Can you just close settings.json... The problem may be if the api is slightly limited now we do make changes on the fly to settings.json I believe

**Comment by xconverge** [comment]
#1500 may be the problem

**Comment by chaseadamsio** [comment]
Everything is working with latest code and vim extension. Not sure what changed, but it works and that's enough for me.
