### ISSUE TITLE
"daw" op should delete the world along with the space"

### ISSUE THREAD

**Issue by reminia** [VSCodeVim/Vim#1528]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?
The content is as below: 

> Cursor is in the end

Press daw 
### What did you expect to happen?

The cursor need to be on the end 'e' of 'the' word

### What happened instead?

Cursor on the space before end.

### Technical details:

* VSCode Version: 1.11.1
* VsCodeVim Version: *0.6.16*
* OS: macOS Sierra

**Comment by Chillee** [comment]
My pull request should fix this issue.

**Comment by rebornix** [comment]
`vaw` has the same issue. Whenever implementing word related commands, we always take prefix/suffix whitespace into account as that's when you are surprised with Vim commands. I didn't know how I miss this one ...

**Comment by xconverge** [comment]
Fixed on master
