### ISSUE TITLE
Counted replace broken

### ISSUE THREAD

**Issue by uebayasi** [VSCodeVim/Vim#1530]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

iabc<ESC>02sAB<ESC>

### What did you expect to happen?

ABc

### What happened instead?

ABABc

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.16
* OS: Mac OS X

**Comment by xconverge** [comment]
This is fixed on master, thanks for the report though! Will try to get a release out asap with the fix
