### ISSUE TITLE
column not set properly after goto definition

### ISSUE THREAD

**Issue by jacobdufault** [VSCodeVim/Vim#1532]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Find a symbol. Press `gd` to jump to the definition. Hit `j` and then `k`. Notice that the cursor is now at column 0.

### What did you expect to happen?

The cursor remains at the original column of the definition.

### What happened instead?

The cursor column got set to 0.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.16
* OS: Ubuntu-like

**Comment by Chillee** [comment]
I tried taking a look at this issue, but I'm running into some issues.

https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L537 is the line of code that seems like it should be handling this, but at that point, vscode.window.activeTextEditor, vimState.editor, etc. all seem to be just initialized, and don't represent the current state at all.

@xconverge Is there some kind of function we should be using to get the current editor?
