### ISSUE TITLE
`d' in visual mode

### ISSUE THREAD

**Issue by lsdsjy** [VSCodeVim/Vim#1537]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

vld

### What did you expect to happen?
Just the first character would be deleted.

### What happened instead?
Two characters are deleted.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.17
* OS: Windows 10 Creators Update
(All the above are up to date.)

**Comment by cobbweb** [comment]
Pretty sure this is expected behaviour, and you'll get the same result in real vim. If you want to delete the character under the cursor, just use: `vd` (no `l`). Does that help, or is there more to this?

**Comment by lsdsjy** [comment]
@cobbweb Sorry. I used Vim in Win32 console for a long time and I just found that Vim in Win32 Console behaves differiently compared with other platforms(`vld' deletes only one character). This issue should be closed. My apology.

**Comment by johnfn** [comment]
thanks for looking out @cobbweb and no worries!
