### ISSUE TITLE
Tab show indent the space according to user setting

### ISSUE THREAD

**Issue by haolly** [VSCodeVim/Vim#1538]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Press **tab**

### What did you expect to happen?
indent 4 space according to my user setting
### What happened instead?
indent 8 space
### Technical details:
suppose "@" is cursor,
```
AAAAAAAA
    AAAAAAAA
        AAAAAAAA@
```
the cursor is at the end of line 3, press enter, the indent will be 8 space, but when you press **backspace", and then "tab", you will ** never ** be able to put the cursor with 4 space indent, which is not the same as vim I'm used to 

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.16
* OS: windows 8

**Comment by rebornix** [comment]
If you disable Vim, you'll find that's the same case for vanila VS Code. I'll say it's not a Vim issue.
