### ISSUE TITLE
Reg command show Promise object instead user input

### ISSUE THREAD

**Issue by cboudereau** [VSCodeVim/Vim#1539]
### What did you do?

-- Record a macro
qq
/fHello
<Enter>
caw
Bye

--Export a macro thanks to reg command
:reg:q
Code show the info : ":q [object Promise]" instead 
--- Registers ---
":   req q
"q   /Hello
cawBye

### What did you expect to happen?
--- Registers ---
":   req q
"q   /Hello
cawBye

### What happened instead?
:q [object Promise]
### Technical details:

* VSCode Version:1.11.2
* VsCodeVim Version: 0.6.17
* OS: Windows 10

**Comment by xconverge** [comment]
@Chillee I think this may still have a few issues, if I do the exact example here, :reg shows the right thing, :reg q seems to only show it up until the first space though
