### ISSUE TITLE
Cannot open a new untitled file with CTRL-N

### ISSUE THREAD

**Issue by Platzer** [VSCodeVim/Vim#1541]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Press `<ctrl-n>`

### What did you expect to happen?

a new untitled file should pop up (default VSCode behavior)

### What happened instead?

nothing

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: *0.6.17*
* OS: Win 7 x64

**Comment by xconverge** [comment]
This setting will fix it
```
"vim.handleKeys":{
        "<C-n>": false
    }
```

**Comment by xconverge** [comment]
I also add C-f to this on my Windows machine to use the built in search sometimes

**Comment by Platzer** [comment]
@xconverge thanks, totally missed that, sry... 😁

**Comment by xconverge** [comment]
No problem!
