### ISSUE TITLE
^E stops scrolling down when the cursor reaches the top of the page

### ISSUE THREAD

**Issue by newhook** [VSCodeVim/Vim#1544]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Pressed ^E

### What did you expect to happen?

When the cursor is at the top of the page the doc should scroll down.

### What happened instead?

It didn't scroll down.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: *[please ensure you are on the latest]*
* OS:  macOS

**Comment by Chillee** [comment]
I'm 90% sure this is an upstream issue.

We simply call the relevant editorScroll command here: https://github.com/VSCodeVim/Vim/blob/master/src/actions/actions.ts#L1074

It's also related to issue #1348

**Comment by nwaywood** [comment]
Something I noticed that may help debug this issue, it seems to work fine if the file length is smaller than the viewport. The issue only occurs when the file is longer than the viewport...

**Comment by Chillee** [comment]
From playing around with it, I think it's a VSCode issue relating to incorrect checks about whether the cursor is "off" the screen or not.

**Comment by o-lim** [comment]
I don't think this is a VSCode issue, but rather an issue with this extension. When the cursor reaches the top of the window, it should continue to scroll by moving the current cursor position down one line as well as scroll down one line. Similarly for ^Y, when the cursor reaches the bottom of the window, it should continue to scroll by moving the cursor position up one line as well as scroll up one line. This is exactly how VIM works.

If you want to scroll the editor without moving the cursor position when it reach the top/bottom of the window, then maybe `revealCursor` should be set to `false`.

**Comment by Chillee** [comment]
Is this fixed in VSCode 1.12? I can't replicate it now.

**Comment by nwaywood** [comment]
@Chillee can confirm. It appears to be fixed in 1.12 for me as well 🎉

**Comment by o-lim** [comment]
This works now for me too when using VSCode 1.12

**Comment by Chillee** [comment]
@johnfn I think this one can be closed now.
