### ISSUE TITLE
Specifying CTRL keys to allow

### ISSUE THREAD

**Issue by edasaki** [VSCodeVim/Vim#1545]
Is there any way to specify which CTRL keys to allow and which ones to disallow (without manually changing keybinds?)

For example if I want ctrl-u and ctrl-d to be vim, but want ctrl-c to stay as just normal copying

**Comment by johnfn** [comment]
Yes. You are looking for:

```
    "vim.handleKeys":{
        "<C-c>": false,
    }
```
