### ISSUE TITLE
'r' key does not put you in replace mode.

### ISSUE THREAD

**Issue by segmentationfaulter** [VSCodeVim/Vim#155]
In vim, you can use 'R' to switch to replace mode and 'r' to replace a single character, both of these keys don't work.

**Comment by jpoon** [comment]
As per the current README, it's not something we support at the moment.

**Comment by johnfn** [comment]
Lower case `r` now works.

**Comment by johnfn** [comment]
@rebornix finished this one!

**Comment by offero** [comment]
It's currently not working for me. IDK why.

VS Code 1.16.1
vscodevim 0.10.1
