### ISSUE TITLE
How to turn off info bar on saving a file?

### ISSUE THREAD

**Issue by segmentationfaulter** [VSCodeVim/Vim#156]
I save my code very frequently and info bar appears every time telling me that code is saved. It gets very annoying because I save almost ten times/mintue. Is there a way to turn it off on saving code?

**Comment by jpoon** [comment]
What info bar? Can you share a screenshot?

Visual Studio Code autosaves in the background by default. This can be configured using `files.autoSave`.

**Comment by sWW26** [comment]
I think they're asking how can they disable this notification.

![image](https://cloud.githubusercontent.com/assets/6764717/13286911/0757961a-dafc-11e5-8a48-ce84924803e1.png)

**Comment by segmentationfaulter** [comment]
@sWW26 exactly, it is very annoying if you save too frequently.
