### ISSUE TITLE
In Surround mode, b outputs as "("

### ISSUE THREAD

**Issue by azngeoffdog** [VSCodeVim/Vim#1563]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

```
1  test

vwStbutton>
```

### What did you expect to happen?

```
1  <button>test</button>
```

### What happened instead?

```
1  <(utton>test</(utton>
```

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.16
* OS: MacOS Sierra (10.12.4)

**Comment by xconverge** [comment]
Ah shucks you are right! b and r are shortcuts for those others when surrounding, but should NOT be when entering tag information.
https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L127

It is correct if you do vwSb or vwSr, but not for tags!

related #1562
