### ISSUE TITLE
`statusBarColors` modifies workspace `settings.json`

### ISSUE THREAD

**Issue by mgood** [VSCodeVim/Vim#1565]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Enabled `"vim.statusBarColorControl": true`

### What happened instead?

The status bar color changes as expected, but it also saves those changes to my workspace `.vscode/settings.json`. My team keeps this file checked into Git for shared project settings, so these changes show up in my Git status and I have to be sure not to commit them.

A warning in the docs could help other users avoid the confusion about where these changes are coming from.

A more complete fix might require new APIs in VSCode for extensions to control the color without writing them to the settings file. A direct API call would probably also be more responsive. There is a noticeable delay between changing modes and the color updating that I found slightly distracting.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.18
* OS: Mac Sierra

**Comment by xconverge** [comment]
Yea this is unavoidable right now.. I would advise to gitignore the setting file locally if it bothers you or disable the feature.

I am not sure vscode will ever expose this to the API. I will add something to the readme

**Comment by xconverge** [comment]
Updated the readme for now! Thanks for reporting [readme](https://github.com/VSCodeVim/Vim/blob/master/README.md#status-bar-color-settings)

**Comment by jpoon** [comment]
Why don't you put it in your user settings? https://code.visualstudio.com/docs/getstarted/settings#_settings-file-locations

**Comment by xconverge** [comment]
I am not sure, that is just where it seems to go... Seeing as how the feature is experimental, I figure I will wait it out a bit from vscode side...

**Comment by rebornix** [comment]
@xconverge I'm interested in why we have to put it in workspace? workspace settings are shared in teams so making changes to it leads to unwanted git changes, sometimes we don't want to git ignore it.

**Comment by xconverge** [comment]
I didn't mean to, I just used the same calls we use elsewhere for config. I couldn't figure out how to make it go to user

**Comment by rebornix** [comment]
@xconverge thanks for the info. I just updated the code to make sure it only affects user setting.

**Comment by xconverge** [comment]
Ah well that was easy...not super intuitive of the API but that works! Thanks

**Comment by jing2si** [comment]
VSCode **v1.12.1** not work, need update 'settings.json' like this
```
{
  "workbench.colorCustomizations": {
    "statusBar.background": "",
    "statusBar.debuggingBackground": "",
    "statusBar.noFolderBackground": ""
  },
}
```

**Comment by zelphir** [comment]
#1654
