### ISSUE TITLE
After installing this extension, caps lock stops working.

### ISSUE THREAD

**Issue by segmentationfaulter** [VSCodeVim/Vim#157]
I have installed VSCode (version 0.10.8) on Ubuntu 15.10 via umake, after installing this extension, caps lock is not honored in main code editing area. The caps lock starts working again after I uninstall this extension.

**Comment by jpoon** [comment]
Doesn't seem to work on Windows either.

**Comment by jpoon** [comment]
@segmentationfaulter Thanks for filing the issue. Seems like the bug lies within VSCode, issue filed with them to track.
