### ISSUE TITLE
yank command is surround mode with tag prompt (yl, yw, yy, etc)

### ISSUE THREAD

**Issue by azngeoffdog** [VSCodeVim/Vim#1570]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Seems like the yank command is doing something rather odd

`1  test`

`yyp`

### What did you expect to happen?

```
1  test
2  test
```

### What happened instead?

`1 test`
`-- SURROUND INPUT MODE -- <p`

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.18
* OS: MacOS Sierra (10.12.4)

**Comment by xconverge** [comment]
Awesome, easy for me to reproduce

This happens after an aborted surround

ysaw<Esc>
then yy

**Comment by xconverge** [comment]
Let me know if you think that you were able to get into this state in a different way (besides aborting a surround halfway through)
