### ISSUE TITLE
Search doesn't match new lines

### ISSUE THREAD

**Issue by serpico7456** [VSCodeVim/Vim#1575]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

/\n

### What did you expect to happen?

New lines in the document should have been highlighted

### What happened instead?

Nothing. 

Searching for new lines using \n works in standard VS Code search with regex turned on.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.18
* OS: macOS 10.12.3

**Comment by Chillee** [comment]
This is actually fairly difficult to do with the way that search is current implemented. We implement search line by line here: https://github.com/VSCodeVim/Vim/blob/master/src/state/searchState.ts#L98

and although it wouldn't be too difficult to simply add matching for newlines, extending search to support newlines arbitrarily and searches across lines will take a bit more work.

**Comment by Chillee** [comment]
So I worked a bit on this, and as you guys can see, it only matches the "asdf"'s with a newline in front of it.

http://i.imgur.com/IZr9iTk.jpg

However, currently VSCode doesn't seem to provide any proper way of showing that the "newline" has been highlighted. Similarly, if you only search for newlines, you'll find that you can't actually see what you've searched for.

Is this functionality good enough?
