### ISSUE TITLE
REQUEST: Setting to disable the vim mode text in the status bar

### ISSUE THREAD

**Issue by Andrew-SK** [VSCodeVim/Vim#1576]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
Is there a setting to disable the vim mode text in the status bar? (-- NORMAL MODE --)

Now that I have set up vim mode dependent status bar colors (working great btw :-) ) I don't have need for the current mode to be displayed in text.

**Comment by xconverge** [comment]
Interesting, you are hardcore, will add though

**Comment by xconverge** [comment]
And search state color
