### ISSUE TITLE
Cannot provide custom keybinding for 's' key in normal mode

### ISSUE THREAD

**Issue by jacobdufault** [VSCodeVim/Vim#1579]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

I'd like to overwrite the default behavior for the `s` key in normal mode (ie, currently it enters insert mode but instead I'd like it have it do a number of semantic operations based on the second entered key).

For example, this configuration does not currently do anything:

```js
"vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": ["s", "r"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.referenceSearch.trigger",
          "args": []
        }
      ]
    }
}
```

### What did you expect to happen?

Reference search runs when pressing `sr` in normal mode.

### What happened instead?

I enter insert mode when pressing `sr` in normal mode.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.18
* OS: Win10

**Comment by rebornix** [comment]
Shares the same root cause as https://github.com/VSCodeVim/Vim/issues/1582 .
