### ISSUE TITLE
Shortcut to keep preview table open

### ISSUE THREAD

**Issue by haolly** [VSCodeVim/Vim#1580]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

ctrl +k + enter

### What did you expect to happen?
the preview table will keep open

### What happened instead?
the preview table keep opened but insert a new line at the cursor

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.18
* OS: windos 10

**Comment by jpoon** [comment]
What's the "preview table"? Is this the markdown preview table?

**Comment by haolly** [comment]
@jpoon
It's preview mode, sorry for confuse
see https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode

**Comment by Chillee** [comment]
It works fine for me if usectrlkeys is set to false.

Otherwise, we capture all ctrl commands. You can use this to bind it properly:

https://github.com/VSCodeVim/Vim#vscodevim-settings

**Comment by haolly** [comment]
set ctrl-k in vim.handleKeys to false solved this issue when useCtlKeys set to true

**Comment by Chillee** [comment]
I'm going to close this issue, as I think this stuff is correctly handled through `vim.handleKeys`.
