### ISSUE TITLE
CTRL-w w doesn't move between groups

### ISSUE THREAD

**Issue by charliesbox** [VSCodeVim/Vim#1585]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

ctrl-w w

### What did you expect to happen?
Move to the next group

### What happened instead?
nothing

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: *[please ensure you are on the latest]*
0.6.20
* OS: 
OS X 10.12.4

**Comment by Chillee** [comment]
What do you mean by group? Like, next split?

**Comment by charliesbox** [comment]
@Chillee yeah :)

**Comment by Chillee** [comment]
Is ctrl+w l the functionality you're looking for?

**Comment by charliesbox** [comment]
yeah, my bad. I say it cause I don't use ctrl + l in vim, just ctrl + w w.

Maybe I can map it, but it would be cool to have it out of the box :)

However, there's a weird behavior: if I have 2 splits, and press ctrl + w l, a new split is created. When it reaches 3 splits, the loop between them works as expected.

**Comment by Chillee** [comment]
Yeah ctrl+w l and r are implemented  (so I guess they aren't really good substitutes). I'll take a look at implementing ctrl+w w.

**Comment by charliesbox** [comment]
@Chillee that would be awesome! thanks

**Comment by Chillee** [comment]
I think PR #1504 is actually already implementing that functionality.
