### ISSUE TITLE
Not to Open the folding when I move cross with j/k

### ISSUE THREAD

**Issue by fxliang** [VSCodeVim/Vim#1587]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

when I use j/k to move cross the folded codes, it automatically open the folding, that's not right.

when I use vim,  the similar action is OK.

what's more, when I try to fold a function with zc, it not works.

I am writing C code.

sorry for my poor english.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.20
* OS: Windows 10 professional 64bit

**Comment by Chillee** [comment]
This is one of our biggest bugs #1004. There's some real limitations in the VSCode API that prevent us from fixing it properly.

There is a PR in the works that should hopefully fix this issue. #1552

**Comment by fxliang** [comment]
thanks, hope it works.

**Comment by Chillee** [comment]
@xconverge I believe this one is also a duplicate.
