### ISSUE TITLE
Ctrl+A and Ctrl+X when cursor placed after only number

### ISSUE THREAD

**Issue by sebnyberg** [VSCodeVim/Vim#1588]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Editing a JSON file with the following content
```Javscript
{
   id: 1,
   someOtherId: 1
}
```
Press `j` + `$` to bring the cursor to end of the first line, then press `Ctrl` + `A`

### What did you expect to happen?

Nothing, the cursor was not in the correct position (before or over the last number in the current line).

### What happened instead?

```Javascript
{
    id: 1,
    id: 2,: 1, 
}
```

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: 0.6.20
* OS: Windows 10

**Comment by Chillee** [comment]
Bizarre. That's definitely a bug. Thanks!
