### ISSUE TITLE
Cannot do "search/find" in command mode

### ISSUE THREAD

**Issue by raghav135** [VSCodeVim/Vim#159]
Hi,

When I am in command mode, how do I search?

ctrl+f does scroll
/ automatically moves to insert mode..

Can you kindly enable "/" to do search?

**Comment by chevex** [comment]
+1

**Comment by jasondearth** [comment]
+1

**Comment by raghav135** [comment]
Hi,

Thanks for fixing it.

But there seems to be an issue.

it is opening "search in files" instead of "search current file".

This is really not usable :(

This is the only issue because of which i am unable to use this plugin.

Regards,
Srinivasa Raghavan.

**Comment by chevex** [comment]
I've been meaning to stop by here and say this same thing, so +1 on the feedback. Definitely expected to open the search in file dialog rather than the search through files sidebar tab.

**Comment by objcchobo** [comment]
+1 here. I'm working with many files and 'find in files' takes too long. Thanks!
