### ISSUE TITLE
Linewise visual mode `:sort` not supported

### ISSUE THREAD

**Issue by apexskier** [VSCodeVim/Vim#1592]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

<kbd>V</kbd><kbd>3</kbd><kbd>j</kbd>
`:sort⏎`

### What did you expect to happen?

The highlighted lines would be sorted with the sort command.

### What happened instead?

The entire file was sorted with the sort command.

### Technical details:

* VSCode Version: 1.11.2
* VsCodeVim Version: *0.6.20*
* OS: macOS 10.12.3

related to https://github.com/VSCodeVim/Vim/pull/1342

**Comment by Chillee** [comment]
We'll probably wait for the api call linked in #792 to pop up before we fix this.

**Comment by rebornix** [comment]
#1342 already added the function for range sorting, however we didn't take selection into account. It's an easy fix.
