### ISSUE TITLE
Can't comment with Ctrl+k, Ctrl+c on Visual Mode

### ISSUE THREAD

**Issue by Matheus-de-Souza** [VSCodeVim/Vim#1606]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

I enter on visual mode, select the code I want to comment and type ctrl+k, ctrl+c and nothing happens.
Uncomment doesn't work either.

If I am on the insert mode e select the text pressing shift, I can comment/uncomment the code with the vscode keybindings.

### What did you expect to happen?

Comment the lines/area I've selected.

### What happened instead?

Nothing.

### Technical details:

* VSCode Version: 1.11.11
* VsCodeVim Version: lastest
* OS: Windows

**Comment by johnfn** [comment]
This is because we bind c-k and c-c. 

You can unbind these keys and let VSCode do what it wants with them with our handy dandy handleKeys preference:

https://github.com/VSCodeVim/Vim#vimhandlekeys
