### ISSUE TITLE
Why is yank not supported?

### ISSUE THREAD

**Issue by neptunian** [VSCodeVim/Vim#161]
Yank = yy?

**Comment by slumtrimpet** [comment]
Yes please :+1:

**Comment by biozal** [comment]
plugin is really great but highly miss yank

**Comment by smibe** [comment]
Need yank and paste. this is a killer feature for me. I would be glad to help implementing this

**Comment by Wayt** [comment]
definitely need it

**Comment by mccart** [comment]
yank and paste is must have...

**Comment by arcseldon** [comment]
Show-stopper.

**Comment by jpoon** [comment]
Fixed in https://github.com/VSCodeVim/Vim/pull/208 and in version 0.0.16

**Comment by mccart** [comment]
I have vscodevim 0.0.16 installed in vscode.
yyp does nothing - uhmmmm...

**Comment by jpoon** [comment]
Yeah, my apologies, I overzealously closed this issue. The PR and latest release implemented 'c' and 'p' but not 'yy'.

**Comment by johnfn** [comment]
We now have a pretty solid implementation of yank and put in master! Hoping to get a new version of VSCodeVim out in the next week or two. In the mean time, feel free to clone the repository, test it out and report bugs. 😄
