### ISSUE TITLE
Add support for Surround with repeated commands

### ISSUE THREAD

**Issue by EgZvor** [VSCodeVim/Vim#1618]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

FEATURE REQUEST:

- **VSCode Version**: 1.11.2
- **VsCodeVim Version**: 0.6.20
- **OS**: Windows 10

**What happened**:

Exact keys you pressed.
`yss)`

**What did you expect to happen**: 
Vim-surround behaviour.
```
def main()
    my_function()
```
to
```
def main()
    (my_function())
```

**Comment by xconverge** [comment]
https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L60
```
As a special case, *yss* operates on the current line, ignoring leading
whitespace.

  Old text                  Command     New text ~
      Hello w*orld!         yssB            {Hello world!}
```
