### ISSUE TITLE
Unknown configuaration setting when visualstar

### ISSUE THREAD

**Issue by Arelav** [VSCodeVim/Vim#1622]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**:
1.11.2
- **VsCodeVim Version**: 
0.6.20
- **OS**: 
macOS 10.12.4

**What happened**:
Unknown configuaration setting when visualstar is true.
See the [screenshot](https://www.evernote.com/l/AAUNNle7b6VOCrHdWUuPBcwWiJJhOI_EA1g)

**What did you expect to happen**: 

**How to reproduce it**:

**Comment by cobbweb** [comment]
I think this is because `"vim.visualstar"` hasn't been release yet?

**Comment by johnfn** [comment]
You're chomping on the bit @Arelav! We haven't released that yet! Give us a day or so. 😄

**Comment by Arelav** [comment]
Oh! Thanks for explanation.
