### ISSUE TITLE
Search for visual mode selected text

### ISSUE THREAD

**Issue by bigLarry** [VSCodeVim/Vim#1623]
In vim I can search for a visually selected string using a number of techniques including what can be found here:

http://vim.wikia.com/wiki/Search_for_visually_selected_text

Is there a way to do the same thing in VSCode with the Vim extension?

**Comment by Chillee** [comment]
haha as I told you on SO, we don't have a way to search for visually selected text. If you're trying to search for the word you're currently on, you can try *. However, currently, we don't have support for pasting into register, which those commands seem to require.

**Comment by johnfn** [comment]
We have visualstar landing in our next release, which is exactly what you want. It allows you to press * or # in visual mode and search for that selection.

**Comment by Chillee** [comment]
Oh, I seem to have really misunderstood what visual star was.
