### ISSUE TITLE
macro playback does not insert tab

### ISSUE THREAD

**Issue by seatownrocks** [VSCodeVim/Vim#1634]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version: 1.11.2**:
- **VsCodeVim Version: 0.6.20**: 
- **OS: Windows 10 Home**: 

**What happened**:
Tab is not inserted on macro replay. Record a macro that goes to beginning of a line, enters insert mode, inserts one tab, exits insert mode, moves down one line. Replay the macro.

`qa0i<tab><esc>jq@a`

**What did you expect to happen**: 
1. Cursor moves to beginning of line
2. Enters insert mode
3. Inserts one tab
4. Exits insert mode
5. Moves down one line

**How to reproduce it**:
Record macro:
`qa0i<tab><esc>jq`

Replay macro:
`@a`

**Comment by Chillee** [comment]
This is probably the same thing as #612.
