### ISSUE TITLE
ctrl + c in insert mode does not copy line.

### ISSUE THREAD

**Issue by atiqorin** [VSCodeVim/Vim#1639]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT** (choose one):

**Environment**:

- **VSCode Version**: 1.11.2
- **VsCodeVim Version**: 0.6.20
- **OS**: Windows 10

**What happened**:

In VS Code without VSCodeVim, when I press ctrl + c it copies the line if nothing is selected.
After enabling VSCodeVim this funtionality is gone. I am using useCtrlKeys: false and startInInsertMode: true. As a workaround to quickly copying line I started using useSystemClipboard: true. Now I have to yank the line and then paste it.

**What did you expect to happen**: 
It would be handy if the usual VSCode shortcut also work
**How to reproduce it**:
Go in insert mode. Put the cursor in a line with some text. Do not select the text and press Ctrl + c. The line is not being copied as regular VSCode do it.

**Comment by jpoon** [comment]
The behaviour you are looking for can be accomplished using `vim.handleKeys`: https://github.com/VSCodeVim/Vim/blob/master/README.md#windows-setup

We're happy to take doc changes if you have ideas on how to make this more readable/discoverable.

**Comment by bonniesimon** [comment]
> 
> 
> The behaviour you are looking for can be accomplished using `vim.handleKeys`: https://github.com/VSCodeVim/Vim/blob/master/README.md#windows-setup
> 
> We're happy to take doc changes if you have ideas on how to make this more readable/discoverable.

I tried to disable the "overrideCopy". But still copy is not working. 
Why is this happening ?
