### ISSUE TITLE
BUG: ctrl-e / ctrl-y stop working when cursor is at top/bottom of file

### ISSUE THREAD

**Issue by nwaywood** [VSCodeVim/Vim#1645]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.11.2
- **VsCodeVim Version**: 0.6.20
- **OS**: macOS 10.12.3 (Sierra)

**What happened**:

I press `ctrl-e` when the cursor is at the top of the file, or I press `ctrl-y` when the cursor is at the bottom of the file

**What did you expect to happen**: 
The viewport to continue scrolling the viewport, moving the cursor with it.

Instead, when the cursor reaches the edge (top or bottom) of the viewport. The cursor seems to stop the viewport from scrolling as to not have the cursor out of view.

**How to reproduce it**:
Open a large enough file so that it is long enough to fill more than one viewport (approx 50 lines for font size 13). Place the cursor at line 5 (for example) and start pressing `ctrl-e` repeatedly. `ctrl-e` will work as expected for the first 4 presses until it reaches line 5 where the cursor is, here `ctrl-e` stops scrolling because the cursor is at the top of the file.

The same thing happens for `ctrl-y` with the cursor at the bottom of the file

**Comment by Chillee** [comment]
Duplicate of 

https://github.com/VSCodeVim/Vim/issues/1544

**Comment by nwaywood** [comment]
ah sorry I search the issues but I searched `ctrl e`, `ctrl-e` etc and didn't find it because they used `^e` in the title. Sorry, closing issue
