### ISSUE TITLE
registered data cannot paste.

### ISSUE THREAD

**Issue by byenghee** [VSCodeVim/Vim#1646]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**:1.11.2
- **VsCodeVim Version**: 0.6.20
- **OS**: window10

**What happened**:
try to paste data on registers.
but I cannot paste data. I remember this sequence works before at some previous version.
but not works with latest vim version.

reg //check registered datas
"0p //paste 0 indexed data.

**What did you expect to happen**: 
data pasted.

**How to reproduce it**:
always happen

**Comment by Chillee** [comment]
It seems to work fine for me, on same versions of vscodevim and vscode running on Arch.

**Comment by byenghee** [comment]
thanks for info. I notice my keyboard layout not matched with current keyboard. I was pushing wrong key.
so close issue now.
