### ISSUE TITLE
set { "vim.statusBarColorControl": true } does not work in vscode 1.12.1

### ISSUE THREAD

**Issue by jing2si** [VSCodeVim/Vim#1650]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.6.20
- **OS**: Windows 10

**What happened**:
`"vim.statusBarColorControl": true` does not work.
Need update 'settings.json'.
```
{
  "workbench.colorCustomizations": {
    "statusBar.background": "",
    "statusBar.noFolderBackground": "",
    "statusBar.debuggingBackground": ""
  }
}
```

**Comment by xconverge** [comment]
this is fixed on master, will push a release now
