### ISSUE TITLE
workbench.colorCustomizations override in main settings.json

### ISSUE THREAD

**Issue by zelphir** [VSCodeVim/Vim#1654]
Great work, but after updating to the latest release I've noticed that every time that you switch mode the whole `workbench.colorCustomizations` in the main `settings.json` is overridden, that means that if you have custom settings (like me) they are gone!

**Comment by jpoon** [comment]
@xconverge any ideas?

**Comment by xconverge** [comment]
Yea, we should read the existing colorCustomizations in configuration.ts at initialization, then we can only change the entries we want if the setting is active and use the stored configuration from configuration.ts

**Comment by zelphir** [comment]
@xconverge @jpoon any update on that?

**Comment by jpoon** [comment]
I don't believe either of us are working on it at the moment, but we are happy to take PRs.

**Comment by zelphir** [comment]
@jpoon what's wrong with saving the settings in the workspace instead of the user settings?

**Comment by Chillee** [comment]
@zelphir Haha. Funny that you ask.

https://github.com/VSCodeVim/Vim/issues/1565

**Comment by zelphir** [comment]
@Chillee did you have any chance to take a look at it? I think this setting should stay in the `.vscode` folder and not in the user settings. Removing the `true` from [this line](https://github.com/VSCodeVim/Vim/blob/eae183596104d820ca2f87a1934d7a03097dd32c/src/mode/modeHandler.ts#L1984) will fix it (it will move the colors back in the `.vscode` settings). Or alternatively the `modeHandler` should be able to update only this block

```javascript
{
   'statusBar.background': `${color}`,
   'statusBar.noFolderBackground': `${color}`,
   'statusBar.debuggingBackground': `${color}`,
}
```

Without overriding all the other settings.

**Comment by autoferrit** [comment]
Any updates on this fix. This issue alone is making it so I can use it as i have many colors customized. Is there a workaround?

**Comment by zelphir** [comment]
@Chillee Any update on this one?

**Comment by jpoon** [comment]
Fixed with https://github.com/VSCodeVim/Vim/pull/2122
