### ISSUE TITLE
gf doesn't work with filepath:linenumber paths

### ISSUE THREAD

**Issue by ssboisen** [VSCodeVim/Vim#1655]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
**BUG REPORT:**

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.0
- **OS**: macOS Sierra 10.12.4

**What happened**:

When placed in NORMAL mode ontop of a filepath and trying to open another file using `gf` it doesn't work if the filepath is followed by :linenumber as one might see in a build or test error-log.

The file opened includes the :linenumber and you thus get an "Unable to open" error from VS Code.

It works in VIM.

**What did you expect to happen**: 

It should open the file, preferably on the line number in question though that's not the behaviour of VIM (VIM just opens on last location in file)

**How to reproduce it**:
In NORMAL mode place cursor on top of valid file path with `:32` afterward and press gf.

Example:
`my/path/to/a/file.txt:32`

**Additional**:

I've tracked down the problem to the Position motion implementation which has a regex defined for filenames [here](https://github.com/VSCodeVim/Vim/blob/b1a9f8483bc91abd9ceba31768429d665b1ab333/src/common/motion/position.ts#L104). It doesn't include colon due to windows support obviously. Perhaps the solution is to have a special handling in the [CommandOpenFile](https://github.com/VSCodeVim/Vim/blob/5e49c3917774da8679b4dcfa5f90461bf884bccc/src/actions/commands/actions.ts#L1844-L1869) class or event better in [getFilePathRight](https://github.com/VSCodeVim/Vim/blob/b1a9f8483bc91abd9ceba31768429d665b1ab333/src/common/motion/position.ts#L503-L505)?

**Comment by Chillee** [comment]
Thanks for the feature request and suggesting where to look! I decided that I think the best way to do it is by using a regex to separate out the line numbers, like so: https://github.com/VSCodeVim/Vim/pull/1708/files#diff-ab811cd6f8cfa81bd0cb8223c86e72bfR1862

[link to the regex](https://regex101.com/r/o1MJt5/1)

If you have any suggestions, I'd be happy to hear them.
