### ISSUE TITLE
Surround plugin appears broken in 0.7.0

### ISSUE THREAD

**Issue by jgoz** [VSCodeVim/Vim#1657]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.0
- **OS**: Mac OS Sierra

**What happened**:

Given:
```
(some |text)
```

Action: `cs({`

Result: entered SURROUND INPUT MODE, but nothing changed

**What did you expect to happen**: 

```
{some |text}
```

**How to reproduce it**:

Reproducible with `ds` and `cs`, but `ys` appears to work still.

**Comment by 0xR** [comment]
I find it interesting that this issue is closed while it seems like it is an actual issue that will be fixed in the future. If it remained open until it is fixed it would be easier to see that it is not yet fixed.

**Comment by Chillee** [comment]
@0xR It has been fixed on master. We just haven't pushed out a new release yet.

**Comment by 0xR** [comment]
Ok cool, I didn't see a comment, so I didn't know
