### ISSUE TITLE
could not save the file which only trim the new line at the end of file

### ISSUE THREAD

**Issue by haolly** [VSCodeVim/Vim#1661]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**:1.12.1
- **VsCodeVim Version**: 0.7.0
- **OS**: win10

**What happened**:
nothing

**What did you expect to happen**: 
save the file
**How to reproduce it**:
open a file with vim, which automatic add new line at the end of file, then open it in vscode, then use command **:w** to save the file. nothing happed, but, **ctrl-s** does save the file

**Comment by jpoon** [comment]
What's `automatic add new line at the end of the file`?

I tried manually adding a new line, then `:w` and it saved fine.

**Comment by haolly** [comment]
Sorry， maybe it's my vim's weird behavior,

**Comment by jpoon** [comment]
Re-open if you feel that this is a real issue.
