### ISSUE TITLE
vim.remap command seems not working.

### ISSUE THREAD

**Issue by millionbonus** [VSCodeVim/Vim#1662]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**What happened**:
A new remapping options feature "vim.remap" was mentioned in [change log](https://github.com/VSCodeVim/Vim/releases/tag/v0.7.0) . Then I tried it with the setting keybinding as same as issue #1543.
```
{
        "key": "F3",
        "command": "vim.remap",
        "when": "editorTextFocus",
        "args": {
            "value": ["a", "b", "c", "<Esc>"]
        }
}
```
As issue #1543 described. `F3` can enter Insert Mode, insert `bc` and quit Insert Mode. However it seems not working.

**How to reproduce it**:
1. Changed keybindings.json as below:
```
[ 
    {
        "key": "F3",
        "command": "vim.remap",
        "when": "editorTextFocus",
        "args": {
            "value": ["a", "b", "c", "<Esc>"]
        }
    }
]
```
2. Restart vscode.
3. Click text area to ensure that editor was getting focus.
4. Press `F3`

**What did you expect to happen**: 
Press `F3` in text area can enter Insert Mode, insert `bc` and quit Insert Mode.

**What happened instead?**
Nothing happened.

**Environment**:
- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.0
- **OS**: Windows 10

**Comment by xconverge** [comment]
closing in favor of #1543

**Comment by FrankFrankWei** [comment]
Does vim.remap work now? I've tried this but this command does not work too.

**Comment by solson** [comment]
This *does* work today. I just figured out I can use the following in `keybindings.json` to use `ctrl+/` to clear search highlights:

```json
    {
        "key": "ctrl+/",
        "when": "editorTextFocus && vim.active && !inDebugRepl",
        "command": "vim.remap",
        "args": {
            "commands": [
                {
                    "command": ":nohlsearch"
                }
            ]
        }
    }
```

The trick is that the `args` must take this shape (as defined [here](https://github.com/VSCodeVim/Vim/blob/b85eb6eb486abf3df9fc23139edd7730ebb8a353/extensionBase.ts#L27-L30)):

```ts
interface ICodeKeybinding {
  after?: string[];
  commands?: { command: string; args: any[] }[];
}
```

The example use of `"value"` was either outdated or pseudocode — instead we use `{ "after": ["d", "d"] }` to bind to the vim keys `dd` or `{ "commands": [...] }` to bind to vim commands, as in my example.
