### ISSUE TITLE
Allow simplified keybinding syntax in settings.json

### ISSUE THREAD

**Issue by jacobdufault** [VSCodeVim/Vim#1667]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**FEATURE REQUEST**

Right now, adding a keybinding to `vim.otherModesKeyBindingsNonRecursive` is very verbose (especially when adding 5-6 of them). For example,

```json
"vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": ["g", "r"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.referenceSearch.trigger",
          "args": []
        }
      ]
    }
]
```

Some extra fields can be emitted and this can be collapsed to

```json
"vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": ["g", "r"],
      "commands": [
        {
          "command": "editor.action.referenceSearch.trigger"
        }
      ]
    }
]
```

but that is still very verbose. It'd be really nice if there was support for a "command" property which would make it less verbose, ie,

```json
"vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": ["g", "r"],
      "command": "editor.action.referenceSearch.trigger"
    }
]
```

Thanks!

**Comment by jpoon** [comment]
This is already supported. For instance, this works:

```
"vim.otherModesKeyBindingsNonRecursive": [
    {
        "before": ["Z", "Z"],
        "commands": [
            {
                "command": ":wq",
            },
        ]
    }
],
```
