### ISSUE TITLE
Tag matching self closing tag issue

### ISSUE THREAD

**Issue by vilisper** [VSCodeVim/Vim#1668]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Environment**:

- **VSCode Version**:1.12.1
- **VsCodeVim Version**: 0.7
- **OS**: 

**What happened**:
can not match match self closing tag.

**What did you expect to happen**: 

**How to reproduce it**:
In editor text like:
```html
<div>
<div a=1/>
{{cursor here}}
</div>
```
and then use cit command.

Maybe solution:
in tagMatcher.ts 
TAG_REGEX may always not match TAG_REGEX CLOSE_FORWARD_SLASH 
change to:
static TAG_REGEX = /\<(\/)?([^\>\<\s]+)[^\>\<]*?(\/?)\>/g;

and in
 if (match[TagMatcher.CLOSE_FORWARD_SLASH]) {
match = TagMatcher.TAG_REGEX.exec(corpus);  //<- add this line maybe
        continue;
      }

**Comment by Chillee** [comment]
Vim doesn't appear to handle self closing tags on my computer either,

**Comment by vilisper** [comment]
I edit the comment.

**Comment by Chillee** [comment]
I see. So we should be ignoring self closing tags. I think your solution looks pretty good to me, I'll try it.
