### ISSUE TITLE
Test - Renable "Can 'D'elete the characters under multiple cursors until the end of the line"

### ISSUE THREAD

**Issue by jpoon** [VSCodeVim/Vim#1673]
~1. Mode Normal can handle p with selection:~
Ended up disabling the test. Works if you run through the commands manually.

1. Can 'D'elete the characters under multiple cursors until the end of the line

   Debugged it to this command failing in `class ActionOverrideCmdAltUp` 

   ```
       await vscode.commands.executeCommand('editor.action.insertCursorAbove');
   ```

~3. comment operator block comment with motion:~

Fixed by increasing timeout to 10s

**Comment by jpoon** [comment]
Related work: https://github.com/VSCodeVim/Vim/pull/1672

**Comment by Chillee** [comment]
If you run the tests manually, they all work, so it has something to do with the testing framework.

**Comment by jpoon** [comment]
Nope. They fail locally for me (exept the last one)

**Comment by Chillee** [comment]
As in, when I run them manually (without the testing framework), they work.

**Comment by jpoon** [comment]
> without the testing framework

What do you mean? When I do I test run locally through VS Code, I see the 2 tests that I mentioned above fail as well.

**Comment by Chillee** [comment]
I manually put the text into a blank file, press the keys that the tests says, and look at the results.

**Comment by jpoon** [comment]
I feel like this might be legitimately broken. @Chillee what happens when you try to use multi-cursor: `cmd+alt+down/up`?

**Comment by Chillee** [comment]
I might be the wrong person to comment on that, since I've always used `ctrl+shift+down/up`. It's probably related to https://github.com/VSCodeVim/Vim/issues/1652.

I'm also not using a mac.

**Comment by jpoon** [comment]
Phew, I don't ever use it so wasn't sure if I was just doing it wrong. But yep, legitimately broken.

**Comment by Chillee** [comment]
I suspect it's a mac only issue related to recent vscode update.

**Comment by jpoon** [comment]
Ah, works on Windows/Linux for you?

**Comment by Chillee** [comment]
I could never get vscode to capture alt-commands properly (probably due to my window manager), so I can't confirm that.

**Comment by jpoon** [comment]
`master` has all the tests passing. Re-purposing this issue to re-enable the test on the next VSCode release.
