### ISSUE TITLE
Surround not working on 0.7.0

### ISSUE THREAD

**Issue by Peluko** [VSCodeVim/Vim#1678]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.0
- **OS**: Windows 10

**What happened**:

Press ```cs"'``` on normal mode when cursor into double quoted string. After this key sequence nothing happens and VsCodeVim remains on SURROUND INPUT MODE until ```esc``` is pressed.

**What did you expect to happen**: 

Change double quoted string to single quoted string

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/1657

**Comment by admosity** [comment]
Was just about to comment that it was fixed on master. Pulled the latest master and was confused that it was working...

**Comment by jpoon** [comment]
@admosity to clarify, you were confused that it **was** working? Or did you mean to say **not working**?

**Comment by Chillee** [comment]
I think he means that he was just about to comment "this is fixed on master."

**Comment by jpoon** [comment]
Ha. Ok, just wanted to double-check. Pushed 0.7.1, and this is fixed there.
