### ISSUE TITLE
ctrl-w, ctrl-w no longer cycles panes

### ISSUE THREAD

**Issue by chrisolsen** [VSCodeVim/Vim#1679]
**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.0
- **OS**: Windows 10

**What happened**:
ctrl-w, ctrl-w only moves to the next right pane, once it gets to the right most pane it doesn't cycle back to the start.

**Comment by jpoon** [comment]
This has been fixed in 0.7.1. Thanks @Chillee (https://github.com/VSCodeVim/Vim/commit/3ae5212f060b729f095871f8fad96c9699e0a8b3).
