### ISSUE TITLE
Jittery cursor motion related to performance

### ISSUE THREAD

**Issue by Peluko** [VSCodeVim/Vim#1682]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.1
- **OS**: Windows 10

**What happened**:

Motion by keeping pressed a key is jittery with random back jumps. For example, I've recorded the motion while scrolling a file from bottom to top. At the start of the video I press and hold cursor up key and I don't release it until the end of the video:
![vscodevim-perf-motion](https://cloud.githubusercontent.com/assets/412867/25898308/ea0174a0-358b-11e7-830d-160b5efead4b.gif)
This happens with any motion command (cursor keys, hjkl, ebw...). Note the last jump, from line 1 to line 50 and then back to line 1 and jump again to line 48.

This effect is somewhat related to performance. It happens when the CPU has some work load. I've observed that it;s only noticeable when global CPU load is over 50/60%, more noticeable as the CPU load increases. Disabling VSCodeVim and moving with cursor keys works fine even when CPU is at 100% (not very responsive due to cpu load, but no jittering).

While scrolling with VsCodeVim enabled, I can see two VSCode processes with 20/25% CPU load each one. While scrolling with VsCodeVim disabled, VSCode only goes to 10/15% CPU.

I've observed this behaviour also on OSX.

**Comment by jpoon** [comment]
Sounds similar to https://github.com/VSCodeVim/Vim/issues/1154. Can you try  https://github.com/VSCodeVim/Vim#mac-setup and see if that helps?

**Comment by xconverge** [comment]
I dont think mac-setup will help, especially since he is on windows ;)

@johnfn I suspect the task queue still, I really do... I have seen this type of behavior every once in awhile still as well

**Comment by Peluko** [comment]
No, mac-setup definitely won't work for Windows 10 ;)

**Comment by Chillee** [comment]
I've been looking at this issue intermittently, and I suspect that this piece of code might be the cause (the issue is related too): https://github.com/VSCodeVim/Vim/issues/1340#issuecomment-299928065

**Comment by Peluko** [comment]
During the last weeks I've noticed that I didn't had any problem with this issue. Code is running smoothly with VSCodeVim enabled. I was curious and looking for what might have changed during this time I've found this: #1842 
Well this could have been the cause for all my problems, as they have vanished now.

Closing this issue.

**Comment by Chillee** [comment]
Very possible. I'm very sorry that we made such a stupid mistake that screwed up our performance so badly :p
