### ISSUE TITLE
Easymotion "Start of word Forwards/backwards" doesn't work for large files

### ISSUE THREAD

**Issue by atiqorin** [VSCodeVim/Vim#1683]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT** :

**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.1
- **OS**: Windows 10

**What happened**:
For lagrge files Start of word backwards < leader > < leader > b  and Start of word forwards < leader > < leader > w does not work properly. See screenshots.

**What did you expect to happen**: 
I expect to go to a word backwards.

**How to reproduce it**:
copy the following line more then 82 times:
< add key="GuId" value="{436B2A9D-06C7-4627-ACE3-E0C6D0D4451F}"  / >

Go to last line and press < leader > < leader > b with easy motion on.
The option to jump back to near words from end of line higher then 81 (eg. 88)  is not present. I can only go back to words in line 81. See attached screenshot:

![image](https://cloud.githubusercontent.com/assets/19419058/25907515/4867ffb0-356d-11e7-9065-26370550109b.png)

Same happens for search of words forwards. Cannot go forward immediately for the same file from line 2. Only able to go to line 7.

![image](https://cloud.githubusercontent.com/assets/19419058/25908546/136a4a4a-3570-11e7-8a4d-40b1f10f749c.png)

**Comment by xconverge** [comment]
the way we fixed #1627 causes this

I think it is an improvement from the previous behavior you reported, and is now a feature request

Thanks for reporting it! What does easymotion in vim do? does it change to 3 characters ever?

@rebornix

**Comment by rebornix** [comment]
We switched from showing undefined to nothing. I'm not familiar with the behavior of easymotion :(

**Comment by Chillee** [comment]
Isn't the problem that we're starting from the wrong place? I don't think it's a problem that we don't show the entire file, so long as we show stuff near the cursor.

**Comment by atiqorin** [comment]
@xconverge nope I've never seen it change to 3 characters ever.

**Comment by Chillee** [comment]
Actually, I can't reproduce this issue.

**Comment by atiqorin** [comment]
I initially reported it for Windows. It happens in Mac also. @Chillee , use the following line for reproducing the issue. Paste it more than 81 times and it should be reproduced.

< add key="GuId" value="{436B2A9D-06C7-4627-ACE3-E0C6D0D4451F}" / >

On the screenshot my cursor is at the very last line.

![image](https://cloud.githubusercontent.com/assets/19419058/26281064/ad330048-3db0-11e7-9dae-893822286c03.png)

**Comment by atiqorin** [comment]
Here's another screenshot showing forwards search:

![image](https://cloud.githubusercontent.com/assets/19419058/26281099/fa9d5a4e-3db1-11e7-9649-3c4e13774f70.png)

**Comment by MaxfieldWalker** [comment]
@atiqorin @Chillee I cannot reproduce this issue on the latest version of extension. 

For your information, characters to be used for marker names are like `hklyuiopnm,qwertzxcvbasdgjf;`, and the marker names are generated by these 28 characters, so at most 784(=28^2) marker names are available.

![issue](https://user-images.githubusercontent.com/7913793/30008906-b3483b9a-915e-11e7-91b2-cb299b292e51.png)

**Comment by Chillee** [comment]
It seems like this has already been fixed? Please reopen this issue if it's still a problem.

**Comment by chanshing** [comment]
An improvement could be to limit the scope of the markers to the current view? I see that currently it tries to mark the entire file from the beginning.
