### ISSUE TITLE
[feature request]disselect "'<,'>" in command mode with selection

### ISSUE THREAD

**Issue by StevenChenSE** [VSCodeVim/Vim#1687]
As title states, when people hit ":" with selection in visual mode, they definitely want to do replacement, so please do not by default sellect the "'<,'>", and be consistent with vim behaviour.

**Comment by Chillee** [comment]
That was impossible before the latest vscode release. However, this is currently fixed on master.

https://github.com/VSCodeVim/Vim/pull/1659

**Comment by xconverge** [comment]
Fixed on master
