### ISSUE TITLE
Status bar color shared between VS Code windows

### ISSUE THREAD

**Issue by ErikGulliksen** [VSCodeVim/Vim#1689]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG, cosmetic only.

**Environment**:

- **VSCode Version**:  1.12.1
- **VsCodeVim Version**: 0.7.1
- **OS**: Windows 7

**What happened**: With multiple VS Code instances, each with a separate workspace, changing the mode will update the status bar colour of all instances.

Switching instances will reset the Status bar back to the intended for that instance as soon as I focus the edit pane, but will stay on the incorrect status bar color if I have other elements focused (such as the Terminal).

**What did you expect to happen**: 
The status bar color to keep the state of each window.
There does not seem to be any functional impact of this, but it can be distracting to tab into a window and for the first few instants believe I am in the wrong VIM mode.

**How to reproduce it**:
Have two VS Code instances in separate workspaces, both with a file open in NORMAL mode.
Enter INSERT mode in one instance and observe the status bar color update in both instances.

**Comment by mikew** [comment]
I'm guessing that the API used to change the color of the status bar affects all VSCode windows and cannot be controlled by a plugin.

**Comment by jpoon** [comment]
Likely a consequence of this: https://github.com/VSCodeVim/Vim/issues/1654

**Comment by Chillee** [comment]
@jpoon that change makes this bug more likely to happen, but it can still happen even if we didn't make that change, as long as you are in the same workspace.

**Comment by jpoon** [comment]
We should be able to support different colors in different workspaces. Obviously, if you have open editors in the same workspace, they'll share the same color. However, due to #1654, as we override the workspace configs, you'll get the same color across all your instances.

Sounds like a dupe? and I'm going to close it as such. If I am mis-interpreting your scenario or mis-understanding the bug, feel free to re-open.
