### ISSUE TITLE
When I enter a chinese text into a file，the focus will jump to the beginning of that string！

### ISSUE THREAD

**Issue by Lysanleo** [VSCodeVim/Vim#1694]

**Comment by Lysanleo** [comment]
if the vim plugin be diabled, the proble will not happen

**Comment by Lysanleo** [comment]
[#1027](https://github.com/VSCodeVim/Vim/issues/1027)This helps a lot！！！:D

**Comment by Chillee** [comment]
Same issues as this I think: https://github.com/VSCodeVim/Vim/issues/1027

**Comment by Chillee** [comment]
I'm adding a possible fix for this issue in the next release. Please try out the release and report whether it's fixed or not. It will be version 0.8.4

**Comment by Lysanleo** [comment]
@Chillee THX!!!!!!!!!! I'll try!

**Comment by Chillee** [comment]
@Lysanleo I pushed out the new release, so try it out and tell me how it is!

**Comment by Lysanleo** [comment]
@Chillee It seems to be fixed!

**Comment by Chillee** [comment]
@Lysanleo That's great to hear! Hopefully I can get some more feedback from some other people, and then we can finally close this issue.

**Comment by Lysanleo** [comment]
@Chillee I will feedback new proble if I get some new vs-vim probles!!THX A LOT!!!!!!

**Comment by Chillee** [comment]
As multiple people have reported this issue as fixed, I will close this issue. Please report it if it's still a problem.

**Comment by Lysanleo** [comment]
@Chillee I got a new problem just now. When I type some chinese characters and enter backspace to delete the last character，the vs-vim will lend to delete the first character instead of the last one.
The gif:[https://ws1.sinaimg.cn/large/aa8ba704gy1fgcezgdxdkg211y0lcwi2.jpg](url)

**Comment by Chillee** [comment]
Sounds liks https://ws1.sinaimg.cn/large/aa8ba704gy1fgcezgdxdkg211y0lcwi2.jpg
