### ISSUE TITLE
Vim visual mode background color confusing on character under cursor

### ISSUE THREAD

**Issue by ecbrodie** [VSCodeVim/Vim#1697]
**Environment**:

- **VSCode Version**: 1.12.1
- **VsCodeVim Version**: 0.7.1
- **OS**: MacOS 10.12.4

**What happened**:

- Write a word into any VSCode window
- Highlight that word in visual mode (ie, `bve` or `viw`)
- Notice that each highlighted character has a different background color than the rest of the characters in the document, as expected
- Observe the behaviour of the flashing cursor on the last character of the word. The background color of that character does not match the other highlighted characters.
- Here's the issue in action:
![vscode_vim_issue](https://cloud.githubusercontent.com/assets/1844664/26036054/b4287aec-38a4-11e7-946f-5cae43ed7005.gif)

**What did you expect to happen**: 

- When the cursor flashes off, the background color of the character under the cursor matches the other highlighted characters. This makes me confused whether this particular character is actually being highlighted.

**How to reproduce it**:

- 100% reproducible by using the vim motions mentioned above

**Comment by jpoon** [comment]
Yep. Dupe.
