### ISSUE TITLE
Support for join lines (:j)

### ISSUE THREAD

**Issue by wieczyk** [VSCodeVim/Vim#1698]
Vi has command `":j"` for joining current line with next one (where all leading whitespaces are eliminated). It would be nice to have it in this plugin. I am using this command very often when I am using vim.

Other vim-emulators like Vim-mode in QtCreator or vimStyle (alternative plugin) support the command.

Additionally the command could accept integer parameter which tells how many next lines should be joined.

**Comment by Chillee** [comment]
We already have support for `J` (in normal mode). It's not exactly the same, but it works well enough for me.

**Comment by wieczyk** [comment]
How to use it?

**Comment by wieczyk** [comment]
Ok, shift + j, the uppercase J.

**Comment by wieczyk** [comment]
Is it possible somehow to map to `:j`?

**Comment by Chillee** [comment]
No. `:j` is an Ex-command, so I don't think there's any way to remap that right now.

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).

**Comment by wieczyk** [comment]
Thanks
