### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by adriaanp** [VSCodeVim/Vim#17]
Was going to do an extension myself, would love to contribute.

Are you guys starting from a reference project or from scratch? I was thinking of porting the atom vim-mode extension to vscode.

**Comment by jpoon** [comment]
@adriaanp that would be awesome! I've been using it as an inspiration for the command/insert mode work, but haven't been porting it directly.

**Comment by adriaanp** [comment]
Any idea on what I can work and focus on?

**Comment by jpoon** [comment]
We should probably get a bit more organized and make a task list of things we need to do. 

I've been working on the basics of the different modes and a bit of the navigation keys within command mode: https://github.com/VSCodeVim/Vim/pull/16. No work yet has been done with the visual mode. @guillermooo has been working on the command console (e.g. `:wq`).

Feel free to party :tada: on whatever you think we're missing or most pressing.

**Comment by ahmedshuhel** [comment]
@jpoon I would like to contribute too. I tried `atom/vim-move` earlier and found it to be unusable most of the time. I don't know why, may be because atom is slow in general. If your experience is same, we have to be careful about it.

**Comment by jpoon** [comment]
Feel free to implement your favorite VI command.

I just merged the toggling between various modes: command, insert, visual with the following keybindings:
* Command Mode: h,j,k,l (navigation)
* Insert Mode: a, A, i, I, o, O

We also need to make everything more testable. That might mean setting up a pattern for testing VSCode UI (ie. where the current cursor is, the status bar item) or mocking everything out.

**Comment by gosukiwi** [comment]
Not sure where to put this, but I find Visual Blockwise Mode quite important. I know the implementation should be hard, atom's vim-mode doesn't support it. 

Any plans for adding that feature?

**Comment by DennyScott** [comment]
Hey guys, I've been working on a previous vim project for vsc, but your guys project looks really promising! I've ported over most of the selection mode over from atom-vim, what state is selection mode in currently? I can try integrating them :).

**Comment by jpoon** [comment]
@DennyScott we have nothing atm for selection mode. Most of the effort has been with command mode and handling the various commands `:wq` etc.

**Comment by jpoon** [comment]
We have a [contributing.md](https://github.com/VSCodeVim/Vim/blob/master/CONTRIBUTING.md) so please refer to that on how to get started.
