### ISSUE TITLE
Change-Inner support

### ISSUE THREAD

**Issue by WonSong** [VSCodeVim/Vim#170]
Does VSCodeVim have plan to support change-inner commands like ```ciw```, ```ci"```?
Didn't see it listed in the project status page. Thanks!

**Comment by Tarmean** [comment]
[I'd widen this to general text objects, to be honest. ](vimdoc.sourceforge.net/htmldoc/motion.html#object-select)

**Comment by jpoon** [comment]
We'll use issue https://github.com/VSCodeVim/Vim/issues/179 to track this.
