### ISSUE TITLE
Incorrect work with "Programmers Dworak" keybord layout

### ISSUE THREAD

**Issue by T0toro** [VSCodeVim/Vim#171]
The part of keys works as on "QWERTY" and part as on "Programmers Dworak".

Tested on:
* Ubuntu 15.10
* Mac OS X 10.10

**Comment by jpoon** [comment]
We don't have a dvorak keyboard at the moment.

**Comment by T0toro** [comment]
I use the ordinary keyboard with "Dvorak" layout.

**Comment by T0toro** [comment]
Not work special symbols in "Dvorak" and "Programmers Dvorak"  layout instead of them printing "QWERTY" symbols.

Then i have write symbol "." instead of them i receive symbol "e", this happens also to other special symbols:
- ";": "z"
- ".": "e"
- ",": "w"
- and etc.

**Comment by dayyan** [comment]
I believe what @T0toro is saying is that parts of the dvorak keyboard work correctly and parts don't.

In my case and probably his: the QWERTY keys incorrectly are still QWERTY in dvorak when using this plugin.

Looking forward to the enhancement, thanks @jpoon!

**Comment by sectioneight** [comment]
Are you still running into this? I've been using Dvorak and haven't had any troubles recently.

**Comment by johnfn** [comment]
My guess is this was fixed on the vscode side. Closing for now - if any of you guys have problems, feel free to reopen.
