### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by Chillee** [VSCodeVim/Vim#1713]
I don't want to take a nap every time I run unit tests.

**Comment by jpoon** [comment]
As a part of https://github.com/VSCodeVim/Vim/pull/2351, I'm planning to support being able to run tests inside a Docker container so at least it doesn't take over the current Code instance.

**Comment by jpoon** [comment]
Made the travis tests go faster with #2351. Additionally, you can go `gulp test` to run tests inside a container so it doesn't affect your open instance of Code.
