### ISSUE TITLE
Multicursor paste is broken

### ISSUE THREAD

**Issue by jonwalstedt** [VSCodeVim/Vim#1715]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**:  0.7.1
- **OS**: Windows 10

**What happened**:
When using `gc` to select and place a cursor at several instances of a word and then press `p` to replace the selected word nothing happens. 

`4gc p`

**What did you expect to happen**: 
I expect the four next instances of the word currently under my cursor to be selected and get their own cursor. When perssing p I expect each instance of the word to be replaced by whatever i previously copied using y.
 
**How to reproduce it**:
open a new document and type:

```
word

test
test
test
test
```

place the cursor in the middle of `word` first test and press `gcy` to select and copy then move down to the first `test`and press `4gc` to select and add a cursor on each test then press `p` to paste the copied `word`, nothing happens. I expect each `test` to be replaced by `word`

**Comment by Chillee** [comment]
Something recently has broken this. I'm not sure what

**Comment by J-Fields** [comment]
This seems to work now, closing.
