### ISSUE TITLE
Missing last character when transfering word from doc to native search bar.

### ISSUE THREAD

**Issue by omega-ult** [VSCodeVim/Vim#1719]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:Win7/Win10/Mac

- **VSCode Version**:1.12.2
- **VsCodeVim Version**: 0.7.1
- **OS**: Win

**What happened**:Using visual mode to select word(usually "viw"), press ctrl+shift+f to perform a global search by native VSCode, the output word appears at search bar will lose last character, for example,  [word] (in doc) -> [wor] (in search bar).

**What did you expect to happen**: I think it should place whole word in search bar.

**How to reproduce it**: It always happends, at any docs.

**Comment by Chillee** [comment]
@xconverge aagghh. Another selection/off-by-one issue... :( We have a lot of issues related to this: https://github.com/VSCodeVim/Vim/issues/1711

**Comment by omega-ult** [comment]
Thanks for your support, can't wait to see your new version!

**Comment by Chillee** [comment]
Closed through https://github.com/VSCodeVim/Vim/pull/1862
