### ISSUE TITLE
Mapping jk to esc in input mode

### ISSUE THREAD

**Issue by steinso** [VSCodeVim/Vim#172]
`    { "key": "j k", "command": "extension.vim_esc", "when": "editorTextFocus" },`

I have used this to map jk to Esc, however this also prevents J from working in command mode, due to VS Code waiting for the next chord.

The problem seems to be that JK is mapped to ESC when "editorTextFocus", which does not distinguish between normal and input mode. This makes JK mapped in command mode as well.

Is it possible in VSCode to create a custom context, to only allow certain keybindings in input and normal mode? Something like: 
`    { "key": "j k", "command": "extension.vim_esc", "when": "extension.vim_inputmode" },`

This would only allow the keybinding to work when in insert mode, and would not work in commandmode. (This could also simplify the logic of modeHandler.ts, as they key handling could go directly to the function and not have to go through the handler.)

Or is there a workaround that is possible to use?

**Comment by jpoon** [comment]
> Is it possible in VSCode to create a custom context, to only allow certain keybindings in input and normal mode?

Nope.

There's a discussion going on to request this https://github.com/Microsoft/vscode/issues/3600 and a bunch of VIM-related issues on VSCode (https://github.com/Microsoft/vscode/labels/VIM)

**Comment by arjunkathuria** [comment]
Any progress ? i'd really like this.

**Comment by johnfn** [comment]
@arjunkathuria I'm taking a plane ride tomorrow. I historically get a lot of work done on planes. 

😉

**Comment by arjunkathuria** [comment]
Yay! 😁

**Comment by johnfn** [comment]
@arjunkathuria Alright, it took two plane rides, but I got it done 😉 

Check the README - I wrote down how to map jj to esc there. We'll be rolling out v0.1 in the next couple of days, which will have remapping support. 😄

**Comment by arjunkathuria** [comment]
@johnfn You're the Man. ;)

**Comment by johnfn** [comment]
@arjunkathuria 😄 

Feel free to pull the latest code down from master and start testing it out if you have a chance. I'd like to get some beta tester eyes on this if possible!

**Comment by steinso** [comment]
@johnfn This is great! I have tried it out, and noticed a couple of issues; sometimes it will leave a leftover j after leaving input mode with jj or jk. This does not always happen, but it happens when i use 'x' to remove a letter, and then use jk afterwards.

Another problem, possible the same issue, happens if I use auto complete, and immediately exit input mode with jk, then it will basically undo the autocomplete.
