### ISSUE TITLE
Support search whole word

### ISSUE THREAD

**Issue by haolly** [VSCodeVim/Vim#1723]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

** FEATURE REQUEST** :

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.7.1
- **OS**: win 10

` \<word\>` should be able to search the whole word

**Comment by Chillee** [comment]
Sorry, I'm confused. What is this supposed to do? 

Isn't /<word> the search command?

**Comment by haolly** [comment]
@Chillee  sorry for confused, there is an example on SO, http://stackoverflow.com/questions/15288155/how-to-do-whole-word-search-similar-to-grep-w-in-vim

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).

**Comment by haolly** [comment]
With the release 0.8.1, still not work

**Comment by Chillee** [comment]
@haolly You need to install neovim, set `vim.enableNeovim` to true, and set the path to the neovim executable to get the new functionality.

**Comment by haolly** [comment]
@Chillee  I have set `vim.enableNeovim` to true, and add the install path of Neovim to system path,
and it still not work. the nvim could be open in the integrated console correctly, btw

**Comment by Chillee** [comment]
@haolly To be clear, this functionality currently only works in the command line, like with 
`:s/\<foo\>/bar`.

I assumed you meant that as that's what your link led to.

**Comment by haolly** [comment]
@Chillee  Sorry,  I just realized the Neovim Only works in Ex mode
Normal search with slash `/\<foo\>`  have not supported

**Comment by apvanzanten** [comment]
Is there any way to get this feature without attaching neovim? That seems a lot of overhead for such a simple feature.

**Comment by J-Fields** [comment]
@apvanzanten https://github.com/VSCodeVim/Vim/issues/3996
You can use `\bword\b`

**Comment by apvanzanten** [comment]
@J-Fields Cool. Thanks! :)
