### ISSUE TITLE
whole file delete/copy

### ISSUE THREAD

**Issue by untoreh** [VSCodeVim/Vim#1732]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: Version 1.12.2
- **VsCodeVim Version**:  0.7.1
- **OS**:  linux x64

**What happened**:
`%d` does not copy the buffer to system clipboard with `"vim.useSystemClipboard": true`
 `%y` does not work either way

**What did you expect to happen**: 
buffer to be copied to system clipboard.

**How to reproduce it**:
delete a file `%d` , `p` paste it again with `"vim.useSystemClipboard": true`. It works specifying a register, so to copy to system clipboard have to forcefully do `%d*`
yank a file with `%y`, try to `p` paste it, this does not work in any way I have tried

**Comment by Chillee** [comment]
This PR should now fix your issue:

https://github.com/VSCodeVim/Vim/pull/1725

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).

**Comment by untoreh** [comment]
`%y` seems to replace tabs with spaces, does not happen with `vggG$y` which I assume does not use nvim
