### ISSUE TITLE
`:norm[al]` command with a macro doesn't work

### ISSUE THREAD

**Issue by Chillee** [VSCodeVim/Vim#1733]
Copied from https://github.com/VSCodeVim/Vim/issues/1032

### What did you do?

I tried to use '<,'> normal command but it doesn't work.

- record a line macro with qa
- v to other lines
- :'<,'>normal @a

### What did you expect to happen?

Apply macro into lines selected

### What happened instead?

Nothing

### Technical details:

* VSCode Version: 1.7.1
* VsCodeVim Version: 0.4.1
* OS: Mac OS X 10.11.6

**Comment by benglass** [comment]
Overall the vim emulation is really great! Much better than in Mono, but this feature would be ideal as it is one of my more commonly used ex commands

```
:10,15 norm @q
```

:+1:

**Comment by djmittens** [comment]
is this feature still in development? are there any alternatives i can use to apply a macro to several lines?

**Comment by JungangHighschool** [comment]
So... no `norm[al]` command with macro yet?

**Comment by khanakia** [comment]
I would like to have this as well.
