### ISSUE TITLE
Can't bind ctrl+g

### ISSUE THREAD

**Issue by ksrb** [VSCodeVim/Vim#1738]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: Version 1.12.2 (1.12.2)
- **VsCodeVim Version**: 0.7.1
- **OS**:  Mac OSX 10.11.6 (15G1421)

**How to reproduce it**:
settings.json:
```json
        {
            "before": [
                "<C-g>"
            ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.showCommands",
                    "args": []
                }
            ]
        }
```

**What happened**:

1. Press <kbd>ctrl + g</kbd>
2. Nothing happens

**What did you expect to happen**: 
The command window to show up.

**Comment by ksrb** [comment]
I'm pretty sure that this is basically a duplicate of https://github.com/VSCodeVim/Vim/issues/1452. In which case please close.

**Comment by jpoon** [comment]
Yep, same issue as #1452.
