### ISSUE TITLE
Add option for vim regex or javascript regex 

### ISSUE THREAD

**Issue by Chillee** [VSCodeVim/Vim#1739]
Since we're about to be in the (somewhat) unique position of having implemented `:s` twice, once in typescript, and once using neovim integration, we'll have the ability to let users switch between javascript and vim regex. Any thoughts on whether this is something we should support?

**Comment by tjfulle** [comment]
I work 50% of my time on a local workstation in VSCode and 50% on remote HPC machines in vim.  Having the option to use the vim regex engine in VSCode would be very convenient.  See #2043

**Comment by jpoon** [comment]
Closing this issue out given the old age of the bug and the lack of activity on it.
