### ISSUE TITLE
Pasteboard(or register) will be rewrite if paste something on visual mode

### ISSUE THREAD

**Issue by omega-ult** [VSCodeVim/Vim#1743]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**:1.12
- **VsCodeVim Version**: 0.7.1
- **OS**: Win7

**What happened**:If you copy something to pasteboard like "aY, then select some new stuff in visual mode, then "ap, that's exact what you want, but if you do it again, "ap, the word selected in last visual mode will be pasted.

**What did you expect to happen**: In last version, things go well, what I keep in register[a] will be pasted, instead of replaced one.

**How to reproduce it**:Always happen.

**Comment by Chillee** [comment]
It's a result of this: https://github.com/VSCodeVim/Vim/issues/1280

It seems that we shouldn't be yanking to the specified register.

**Comment by omega-ult** [comment]
Well, I gotta change my method.

**Comment by Chillee** [comment]
No, it's a valid bug. I was just noting the cause.

**Comment by DrakeXiang** [comment]
this behavior appeared since a few versions back, I thought it would be fixed soon since it's so buggy, now I'm still experiencing it, nobody use this function like this ???

**Comment by Chillee** [comment]
@DrakeXiang The behavior seems to be correct for me,

**Comment by DrakeXiang** [comment]
@Chillee Ok, turns out this is the correct behavior in vim, didn't know that... so this is painful if you have to paste multiple times

**Comment by Chillee** [comment]
@DrakeXiang Yeah :(

The right thing to do is to copy into a register with `"ay`. You can then paste without overwriting that register by selecting the text you're trying to replace and doing `"ap`. You can then simply use dot repeat to repeat that multiple times.

**Comment by chibicode** [comment]
@Chillee this will be solvable by mapping `p` to `"_dP` only in visual mode. However that's not currently possible, so I made a new issue:

https://github.com/VSCodeVim/Vim/issues/2705

**Comment by DrakeXiang** [comment]
Seems the issue has come back...

**Comment by peterlindsten** [comment]
@chibicode Thanks for the workaround. This should be standard though?

**Comment by jeromecovington** [comment]
This is the expected behavior in vim. I have to override in in vimrc usually. I'm glad I know how to override it in vscode now as well, thanks!

**Comment by xh3b4sd** [comment]
Using the configuration from @chibicode does not work for me. Pasting overwrites the register still and consecutive pastes do not apply the initially yanked content. Any advice on this?

**Comment by xh3b4sd** [comment]
Maybe more info from my side. I figured I can select and paste the right content multiple times with `ve` and then `p` again, over and over again. My muscle memory wants to do that by simply repeating the last paste command I did using `.`. And this does not work. Any way to get this sorted?

**Comment by J-Fields** [comment]
@xh3b4sd This is expected behavior. From `:help`:

>The previously selected text is put in the unnamed register.  If you want to
put the same text into a Visual selection several times you need to use
another register.  E.g., yank the text to copy, Visually select the text to
replace and use "0p .  You can repeat this as many times as you like, the
unnamed register will be changed each time.

**Comment by xh3b4sd** [comment]
I understand that. My question is how I can just repeat the last paste. I am used to only type `.` again and the whole functionality is replicated. This is super easy and useful but I can't figure how to do that in vsCode. The complexity of `ve"0p` all over again kills my workflow and is so much more typing.

**Comment by stargoo** [comment]
@chibicode 's workaround is okay, but I found that it doesn't work with multiline operations too well, as the document will scroll to the last yank.  This is jarring to say the least.  `"0p` can be a pain, but you can still use `p` if you like.  The rebind fixes the multiline jumping, but note that it will not work with the repeat, `.` key.  

```
"vim.visualModeKeyBindingsNonRecursive": [  
{  
            "before": [  
                "p",  
            ],  
            "after": [  
                "p",  
                "`",  
                "[",  
                "v",  
                "`",  
                "]",  
                "h",  
                "y",  
                "<Esc>"  
            ]  
        }  
    ],  
```

**Comment by proxseas** [comment]
Any updates to this? It would be fantastic if there was a config setting that would prevent the yank register from being overwritten when you paste over something in visual mode.

**Comment by msomeone** [comment]
"vim.visualModeKeyBindingsNonRecursive": [
        { "before": ["p"], "commands": [ "editor.action.clipboardPasteAction"] },
        { "before": ["y"], "commands": [ "editor.action.clipboardCopyAction", "extension.vim_escape"] }
    ],

**Comment by J-Fields** [comment]
`P` in Visual mode pastes without overwriting the register

**Comment by hliebert** [comment]
This works.

```
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": [
                "p"
            ],
            "after": [
                "P"
            ],
        }
]
```

**Comment by ShimmyTheDev** [comment]
If anyone needs it, this is my solution:
```json
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": [
                "p"
            ],
            "commands": [
                "editor.action.clipboardPasteAction",
                "extension.vim_escape"
            ]
        }
    ],
```
