### ISSUE TITLE
Enable Vim plugin discovery problems

### ISSUE THREAD

**Issue by ysdlm** [VSCodeVim/Vim#1744]
After using the Vim plug-in in Vscode, the editor's own copy-and-paste cut shortcut key is disabled.

### Environment:
VSCode Version: 1.13.0
VsCodeVim Version: 0.7.1
OS: Windows 10

**Comment by Chillee** [comment]
That's because `ctrl-c` is actually a keybinding in vim. If you want to enable it again, either use the [handleKeys](https://github.com/VSCodeVim/Vim#vimhandlekeys) setting, or set useCtrlKeys to false.
