### ISSUE TITLE
Improve easymotion labels style.

### ISSUE THREAD

**Issue by eulerdisk** [VSCodeVim/Vim#1746]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

It would be great to have the easymotion labels with the same style of editor characters (same font, font size, width per char etc.. but obviously with different fg/bg colors,) in order to get an exact overlap, like Vim on terminal.
Currently easymotion label's style is customizable but it's very hard to get it right, especially if you change font family/size.

**Comment by xconverge** [comment]
If they are customizable, what is hard to get right? How should this be improved?

I assume you saw this in the readme..

```
vim.easymotionMarkerBackgroundColor	The background color of the marker box.
vim.easymotionMarkerForegroundColorOneChar	The font color for one-character markers.
vim.easymotionMarkerForegroundColorTwoChar	The font color for two-character markers, used to differentiate from one-character markers.
vim.easymotionMarkerWidthPerChar	The width in pixels allotted to each character.
vim.easymotionMarkerHeight	The height of the marker.
vim.easymotionMarkerFontFamily	The font family used for the marker text.
vim.easymotionMarkerFontSize	The font size used for the marker text.
vim.easymotionMarkerFontWeight	The font weight used for the marker text.
vim.easymotionMarkerYOffset	The distance between the top of the marker and the text (will typically need some adjusting if height or font size have been changed).
```

**Comment by eulerdisk** [comment]
Because when you change font family/size you have to reconfigure everything "by eye": height/font size/font family/width per char/Y offset. All these parameters should be calculated automatically by the extension is such a way that the label char covers 1:1 the char "below".
The only thing I want to configure is bg/fg colors.
[with the option to customize everything, as it is now]

**Comment by net** [comment]
To add on to this, there's no way to position the marker box itself. `easymotionMarkerYOffset` only adjusts the positioning of the text inside the marker box. For me, the marker box is too high. It doesn't adequately cover the text or allow for marker text to be fully visible when positioned correctly.

**Comment by xconverge** [comment]
Has this been fixed recently?

#2017 may have fixed it

**Comment by eulerdisk** [comment]
@xconverge nope.

**Comment by prurph** [comment]
:+1: on this--it would be great to have the box be larger and the label centered within it. The current settings don't let you tweak this and the labels appear at the very bottom of the box, which isn't (IMO) large enough and therefore doesn't actually cover the background text well, making it hard to read.

I poked around in the dev console but there isn't a consistent class being used by these `:after` pseudo-elements that could easily be overriden, so it seems like it would have to be baked into the plugin itself.

**Comment by malevinson** [comment]
I just opened a related issue [https://github.com/VSCodeVim/Vim/issues/2751](url).

Basically an X offset would be helpful. Like vim.easymotionMarkerYOffset but for X.
