### ISSUE TITLE
Bug: "gq" does not work with jsdoc-style comments

### ISSUE THREAD

**Issue by danvk** [VSCodeVim/Vim#1750]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.7.1
- **OS**: (any)

**What happened**:

![gq-vscodevim](https://cloud.githubusercontent.com/assets/98301/26468329/044f90ba-4164-11e7-9950-4c37c2c7ee50.gif)

Creating a visual selection and hitting `gq` works great with C++-style `//` comments but doesn't work with javadoc / jsdoc-style comments. The extra `*` gets pulled to the previous line. vim handles this correctly.

**Comment by johnfn** [comment]
It works fine if you select the entire block.

For a proper fix, I think this is as easy as adding "*" as a single line comment type.
