### ISSUE TITLE
After v.0.8.0 update tab completion no longer works

### ISSUE THREAD

**Issue by kevinokal** [VSCodeVim/Vim#1752]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.0
- **OS**: OSX 10.11.6

**What happened**: After updating to v0.8.0, tab completion with the vim plugin no longer works. The autocomplete menu will still appear but pressing tab for completion will insert a tab rather than autocomplete the word.

**What did you expect to happen**: the word to autocomplete :(

**How to reproduce it**: try to use autocomplete! this was happening regardless of filetype as well.

thanks!

**Comment by emaren84** [comment]
Same thing happens to me :(
At least Enter key works for autocompletion.

**Comment by kevinokal** [comment]
thanks! i didn't know you could enter for autocompletion!

**Comment by Chillee** [comment]
Yep, I can reproduce it.  I'll try to fix this now and roll out a bug fix update.

**Comment by Chillee** [comment]
Just fixed in master. Will try out to roll out a patch as soon as possible.

**Comment by Chillee** [comment]
Alright. Problem officially fixed in version 0.8.1!
