### ISSUE TITLE
Jump to line stops working with v0.8.0

### ISSUE THREAD

**Issue by Ashod** [VSCodeVim/Vim#1754]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: v0.8.0
- **OS**: Ubuntu 16.04

**What happened**:
Upgraded to v0.8.0 and reloaded.
Typed :123 <enter>
(The file is over a thousand lines long.)
Tried on different files, same result; nothing happens.

Note: typing '123G' works.

**What did you expect to happen**: 
Jump to line 123

**How to reproduce it**:
Upgrade to v0.8.0, load file, type colon<line-number><enter>

**Comment by andywhite37** [comment]
Great plugin!  I would love to have this feature back/fixed.

**Comment by xconverge** [comment]
I will say...if you have neovim installed and use the new neovim integration stuff, this command (and nearly all : commands seem to work...) That being said, valid bug for sure!

**Comment by andywhite37** [comment]
Yeah, using the neovim support worked for this.  Sorry, I wasn't sure what the neovim support actually entailed, but it makes sense now.

**Comment by Ashod** [comment]
Thanks for the quick fix. I was almost certain this worked with neovim, so didn't bother to even check (how else would anyone not see such a common regression?). But obviously we shouldn't assume everyone has (or will have) neovim.
