### ISSUE TITLE
otherModesNonRecursive doesn't stop action from being recursive in visualBlock mode

### ISSUE THREAD

**Issue by Chillee** [VSCodeVim/Vim#1758]
https://github.com/VSCodeVim/Vim/issues/1751#issuecomment-304162819

**Comment by iliekturtles** [comment]
Thanks for looking into this.

For reference I'm trying to have VsCodeVim setup so that registers are only updated for destructive commands (`c`, `C`, `d`, `D`, `s`, `S`, `x`, `X`) when `<leader>` is used, otherwise the destroyed text should go to the blackhole register (not implemented when I setup these bindings).

**Comment by Chillee** [comment]
Just to make sure, these keybindings didn't work at all (in visual block mode) before the most recent update, right?

**Comment by iliekturtles** [comment]
The key bindings do work in 0.7.1 in normal, visual, and visual block modes. The `<leader>` variants didn't work in normal mode -- they would delete without updating the system clipboard or only partially execute the desired action and the next movement would apply the action.

**Comment by Chillee** [comment]
@iliekturtles And you're sure that the keybindings actually applied in visual block mode? They didn't just do the normal `c` command?

I'm asking because if the above statement is wrong, then my understanding of where the bug is is incorrect.

**Comment by iliekturtles** [comment]
@Chillee In 0.7.1 `c` when in visual block mode (usually) works. The editor removes the existing text and enters edit mode. Most of the time it doesn't affect the system clipboard, although in a couple tests it cleared the system clipboard. The `<leader>` variant doesn't work in visual block, but does in block.

**Comment by Chillee** [comment]
Closed in favor of https://github.com/VSCodeVim/Vim/issues/1869
