### ISSUE TITLE
line move not working

### ISSUE THREAD

**Issue by byenghee** [VSCodeVim/Vim#1761]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:MS Windows 10

- **VSCode Version**:1.12.2
- **VsCodeVim Version**: v0.8.2
- **OS**: Windows10

**What happened**:
fail to move specific line with line move command after updating.
it was working previous version(not sure which version where it work)
":" 100  /*enter into command  line with ":" and enter line number to move*/

**What did you expect to happen**: 
have to move specific line
**How to reproduce it**:
always happen

**Comment by cideM** [comment]
Same here on Ubuntu 16.04 same version as OP

**Comment by Chillee** [comment]
I assume you guys don't have neovim enabled, right?

**Comment by Chillee** [comment]
Although this was a bug and a regression in terms of functionality, I would still recommend trying out the neovim integration. In the future, it's unlikely that new Ex-commands (besides the ones already existing) will be supported.
