### ISSUE TITLE
New version (0.8.2) Breaks Emmet integration

### ISSUE THREAD

**Issue by jvbianchi** [VSCodeVim/Vim#1763]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

New version (0.8.2) Breaks vscode Emmet integration. The Tab completion stopped working after I updated to this version.

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.2
- **OS**: Mac OSX

**How to reproduce it**:
go to HTML file:
```html
#page>div.logo+ul#navigation>li*5>a{Item $} // try to press tab but nothing happens
```

**Comment by 13hoop** [comment]
+1
same here

**Comment by Chillee** [comment]
I got it to reproduce. I'll push out a new release today fixing the issue.
