### ISSUE TITLE
Multiline delete doesn't allow for "d[# of lines]d" syntax

### ISSUE THREAD

**Issue by XenosInAHat** [VSCodeVim/Vim#1764]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.3
- **OS**: Windows 7

**What happened**:
I tried to do a multi-line delete in Normal mode by typing "d5d". The delete didn't occur. However, "5dd" works, so I'll just use that until a fix is implemented.

This seems to have been introduced in a 0.8.X version because it worked correctly until I updated VsCodeVim from (I think) 0.7.1.

**What did you expect to happen**: I expected 5 lines to be deleted.

**How to reproduce it**:
1. Open a file with several lines of code.
2. Type "d5d" (or any other number, really) while in Normal mode. Note that the lines do not get deleted.

**Comment by Chillee** [comment]
Somebody reported this in our slack. It has to do with our refactor of our repeated actions. 

I normally use 5dd (and that's what our tests are based on), so I missed it.
