### ISSUE TITLE
Reflow (`gq`) removes spaces when joining lines

### ISSUE THREAD

**Issue by jacobdufault** [VSCodeVim/Vim#1765]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.13-insiders
- **VsCodeVim Version**: 0.8.3
- **OS**:  Linux

**What happened**:

With this text, select both lines and type `gq`.
```
// aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
// b
```

**Expected**
```
// aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa b
```

**Actual**
```
// aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab
```

**Comment by jacobdufault** [comment]
Length of the first done doesn't matter, this also breaks:

```
// a
// b
```

**Comment by xconverge** [comment]
related #1684
