### ISSUE TITLE
Visual block mode doesn't navigate with gj/gk

### ISSUE THREAD

**Issue by Cody157** [VSCodeVim/Vim#1772]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.3
- **OS**: Windows 7 Professional SP 1

**What happened**:
Trying to navigate visual block mode with `gj` and `gk` resulted in no vertical movement or selection.

`<ctrl-v>gj`

**What did you expect to happen**: 
The selection should now include the same block in the following line.

This happens regardless of whether it's navigating between multiple distinct lines, or a single, long word-wrapped line.

**Comment by nivv** [comment]
This seems to work for me, also I've re-mapped `j` to `gj` and `k` to `gk` like below:

```json
    "vim.otherModesKeyBindings": [
        {
            "before": ["j"],
            "after": ["g", "j"]
        },
        {
            "before": ["k"],
            "after": ["g", "k"]
        }
    ]
```

**Comment by Cody157** [comment]
@nivv - Are you sure you're testing this with visual block mode, and not either plain visual or visual line modes? Both of those work for me, but visual block doesn't. I had the same keybindings, which is how I found the problem, and had to disable them to use visual block mode at all.

It's worth noting this used to work just fine, I don't know exactly what version it was where the problem started though.

This also on a different computer with some version updates,
**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.8.6
- **OS**: OS X El Capitan Version 10.11.6

**Comment by Chillee** [comment]
Yeah this is a consequence of some changes we made to visual block mode to fix some other bugs (I think).

I don't think it should be too hard to fix.

**Comment by oliver-newman** [comment]
Has there been any progress on this? I'm making the switch from vim to VS Code and I love it so far, but this fix would be really nice to have. I'd be willing to work on it myself if it really is fairly easy and if anyone can provide some starting guidance, because I have minimal experience with applications of this sort and zero experience with TypeScript.
