### ISSUE TITLE
Navigation doesn't work after enabling neovim integration

### ISSUE THREAD

**Issue by andriy-f** [VSCodeVim/Vim#1773]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.3
- **OS**: OpenSUSE 42.2
- **neovim** : 0.1.4

**What happened**:

After enabling neovim in settings ( "vim.enableNeovim": true) navigation is not possible in editor window, i.e. arrow keys and hjkl doesn't work, cursor doesn't move

**What did you expect to happen**: it's happenig every time I enable neovim support

**How to reproduce it**: set "vim.enableNeovim": true in settings, open any file and try to navigate with hjkl or arrows

**Comment by xconverge** [comment]
can you try updating neovim to 0.2.0? I did this and it worked for me

**Comment by RomainEndelin** [comment]
Hi. Just for information, I was having the same issue as @andriy-f, and upgrading neovim to 0.2.0 fixed it 👍

**Comment by andriy-f** [comment]
Updating to neovim v 0.2.0 (from editors repo) fixed this issue. But since default neovim version is still 0.1.4, maybe add some info about minimum neovim version and/or version check to vscodevim?

**Comment by Chillee** [comment]
@andriy-f that sounds like a good idea. We'll do that. Thanks!
