### ISSUE TITLE
Incessant nagging: "We have now added Neovim integration"

### ISSUE THREAD

**Issue by pvaibhav** [VSCodeVim/Vim#1774]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT** (choose one):

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.3
- **OS**: macOS 10.12.5
- **Neovim Version**: 0.2.0
- **Neovim location**: `/usr/local/bin/nvim`

**What happened**:

After installing latest version, when I open any file, I get the following drop-down message at the top of VScode window:
> We have now added neovim integration for Ex-commands. Enable it with vim.enableNeovim in settings

Clicking "Never show again", or even actually enabling Neovim integration, does not get rid of the message.

**What did you expect to happen**: No message about the new feature after any of the below steps were taken:

**How to reproduce it**:

I've tried the following:

- Clicked "Never show again", opened another file: still same message.
- Quit VScode and restarted it, opened a file: still same message.
- Added `"vim.enableNeovim": true,` to my settings.json, open a file: still same message
- Added `"vim.neovimPath": "/usr/local/bin/nvim",`, open a file: still same message
- Quit VScode and reopen a file: unfortunately still same message.

Thanks for the otherwise fantastic work!

**Comment by jpoon** [comment]
@Chillee, in addition, I like what VSCode does: redirects people to their changelog.

**Comment by Chillee** [comment]
@pvaibhav Do you have `vim.disableAnnoyingNeovimMessage": true` in your settings?

**Comment by pvaibhav** [comment]
Oh dear god you were not joking.. yeah setting that to true gets rid of the message. Thank you.

Still think this shouldn't be required.

**Comment by Chillee** [comment]
@pvaibhav That's somewhat of a bug, for whatever reason. Pressing `Never show again` should automatically set that setting to true for you.

**Comment by pvaibhav** [comment]
Shouldn't this issue be kept open until the bug is fixed?

**Comment by Chillee** [comment]
I haven't seen anybody else report it, so I assumed it was something specific to your setup.

**Comment by al3x-edge** [comment]
Just as a note, I ran into this issue as well so it wasn't only one person but maybe rare.  Ended up setting the flag myself.  Got a VS code update.  And then got a "Your install is corrupt" message.  Restarted the app between steps.  Everything seems fine now.
