### ISSUE TITLE
Is there a way to repeat a CLI command?

### ISSUE THREAD

**Issue by edasaki** [VSCodeVim/Vim#1775]
For example, can we repeat a :s/foo/bar/g without retyping it?
I've looked around but haven't been able to find anything about this (maybe I've missed it)

**Comment by Chillee** [comment]
https://github.com/VSCodeVim/Vim/issues/779 is a duplicate of this.

**Comment by edasaki** [comment]
Gotcha - is there a command for this in the meantime (something we could bind to a key ourselves)? If not I may try to add it and PR

**Comment by Chillee** [comment]
Unluckily, it's not really possible right now. VSCode doesn't allow us to modify the box that pops up for Ex commands.

It would be possible if we decided to move Ex-commands to the bottom status bar, but that doesn't seem worth it to me right now.

**Comment by edasaki** [comment]
I mean like, what if we just made some keybind that runs the last command without any sort of interface popup?

So I type :s/foo/bar/g
Press enter to do the replace
go to some other line
press some key combination to rerun the same command again on that line

**Comment by Chillee** [comment]
Oh, hmm. That's definitely possible. That would not be a core vim feature though.

**Comment by oschr** [comment]
It actually is a core vim feature, namely typing @: in vim repeats the last command (to be more precise, the last command is saved in the special : register)

**Comment by reminia** [comment]
+1

**Comment by J-Fields** [comment]
This should come for "free" with #2193 and #3605
