### ISSUE TITLE
hjkl not working anymore

### ISSUE THREAD

**Issue by johnchristopher** [VSCodeVim/Vim#1778]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.3
- **OS**: win 7 64b

**What happened**: `hjkl` not working anymore after latest update unless I explicitly declare ` "vim.enableNeovim": true` or ` "vim.enableNeovim": false` in user settings.json once. After that I can delete that line and the keys keep on working.
edit: disregard that. The issue comes and goes randomly but once the keybindings has stopped working I have to restart the whole editor.

**What did you expect to happen**: Keybindings to keep working :) ?

**How to reproduce it**: Update the plugin ?

**Comment by Chillee** [comment]
About your edit, does the issue happen when `enableNeovim ` is set to false? Somebody else reported the same issue in the slack, and they said that it went away when disabling neovim.

**Comment by johnchristopher** [comment]
I have been working the whole day with other extensions disabled and haven't experienced the bug again. I am pretty sure PHP Intellisense Crane is the cluprit (or the combination of that plugin and vsvim).

I remember now that from time to time I experienced that behaviour but chalked it up to VSCode not being a 1.0 at the time.

**Comment by Chillee** [comment]
Hmm. Come to think of it, I've had this bug before too... I think this might be a VSCode issue (or possibly one of the other extensions I'm using).

**Comment by jpoon** [comment]
Relatively old issue. I haven't personally come across this issue nor has there been any recent issue/messages on slack about it so I'm going to presume this has been fixed.

To keep our issue list sane, I'm closing this issue, but feel free to re-open.
