### ISSUE TITLE
Backwards delete using "X" doesn't allow count prefixes

### ISSUE THREAD

**Issue by mikeagrammar** [VSCodeVim/Vim#1780]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**: macOS Sierra 10.12.5

**What happened**:

Press a count prefix then "X" in Normal mode within a word.

**What did you expect to happen**: 

Should delete the count prefix of characters before the cursor.

**How to reproduce it**:

Press a count prefix then "X" in Normal mode within a word.

This is a really awesome project, and I'd like to contribute if at all possible - 

I've had a look at the ActionDeleteLastChar class as defined in ~/actions/commands/actions.ts and added the runsOnceForEachCountPrefix property (set to true), however this does not create the expected behaviour.

I believe there is an issue with the DeleteOperator.delete class / method defined within ~/actions/operator.ts, but I'm not too sure where to start - any help / advice would be awesome.

**Comment by Chillee** [comment]
@milquetoastable If you want to talk about contributing, I'd suggest checking out our slack!

This issue has to do with how our current transformations are done. It doesn't handle backwards transformations like this automatically.
