### ISSUE TITLE
After a recent update y#y no longer working

### ISSUE THREAD

**Issue by Goblinlordx** [VSCodeVim/Vim#1781]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.3
- **OS**: OSX 10.12.5

**What happened**:
  After a recent update now yanking multiple lines no longer works.

If I press `y5yp`

**What did you expect to happen**: I expect 5 lines (starting at line which cursor is on) to be yanked and then a copy put starting at the line below the line which the cursor is on.

**How to reproduce it**:
Follow the steps above?

**Comment by Chillee** [comment]
Version 0.8.4 should fix this: This PR should have fixed it: https://github.com/VSCodeVim/Vim/pull/1766

**Comment by Goblinlordx** [comment]
0.8.4 not showing up as available in VSCode.  Is it not actually released yet?

**Comment by Goblinlordx** [comment]
Odd... it says in market place it is -0.8.4 but it isn't showing an update is available.  Anyways... thanks.

**Comment by Chillee** [comment]
Try restarting VSCode. A new update won't show up until VSCode is restarted.

Failing that, just try uninstalling and reinstalling the extension.
