### ISSUE TITLE
"Tab" doesn't move the selected line

### ISSUE THREAD

**Issue by yustnip** [VSCodeVim/Vim#1785]
**Environment**:
- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**: Ubuntu GNOME 17.04

**What happened**:
In normal mode I select a line then press "Tab" key and nothing happens.

**What did you expect to happen**: 
The selected line has to move forward.

**How to reproduce it**:
Select a line and press "Tab".

**In addition**
When I press "Shift+Tab" the selected line moves back (as expected).

**Comment by jpoon** [comment]
Do you mean for this to happen insert mode? I think `tab` is a nop in normal mode, well, at least on my VIM instance.

**Comment by yustnip** [comment]
*Do you mean for this to happen insert mode?*

I don't mean that `Tab` has to change mode. It just has to move selected line(s) forward.

**Comment by jpoon** [comment]
My point is that in using vanilla vim, `tab` in normal mode doesn't do anything for me. So, is this a special rebinding you have or maybe I'm just not aware of this feature in VIM....

**Comment by yustnip** [comment]
Thanks for the answer. I've understood your point.

**Comment by jpoon** [comment]
Closing this issue then as a won't fix then?
