### ISSUE TITLE
Support ranges relative to current line number

### ISSUE THREAD

**Issue by alexbrillant** [VSCodeVim/Vim#1786]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 

BUG REPORT

I would like to be able to execute commands on ranges relative to the current line number : 

-7,-4  [command]
-1,+4  [command]
+1,+5 [command]

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**:  Osx 10.12.4

**What happened**:

VScodeVim doesn't execute commands with relative ranges.

Exact keys you pressed.: 
:-7,-4m.

**What did you expect to happen**: 

move from 7th line above current line to 4th line above current line to the current line. 

**How to reproduce it**:

Try to execute any ex command with a relative range like -5,+5[command]

**Comment by Chillee** [comment]
Do you guys have neovim enabled?

**Comment by Chillee** [comment]
If you guys have neovim enabled, I should have fixed this issue in #1810.

**Comment by alexbrillant** [comment]
Awesome
