### ISSUE TITLE
Extreme delay when writing.

### ISSUE THREAD

**Issue by Josef-Vonasek** [VSCodeVim/Vim#1789]
1. Hit any letter (e.g. A), hold it for two seconds.
2. Release the letter.
3. Letter A is going to be printed on screen for another ~0.5 seconds.

This is happening only if I have vim emulation enabled, once I disable it everything is fine.

I have tried different vim emulation `amVim` and it also had this problem...

- VSCode Version: Code 1.12.2 (19222cdc84ce72202478ba1cec5cb557b71163de, 2017-05-10T13:20:36.315Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|project-manager|alefragnani|0.18.0|
|vscode-database|bajdzis|1.2.0|
|quicktips|bbenoist|0.2.4|
|syntax-julia|be5invis|0.0.4|
|path-intellisense|christian-kohler|1.4.2|
|stuck-overflow|dgerrard|0.1.9|
|matlab|Gimly81|0.5.0|
|mdmath|goessner|1.2.9|
|beautify|HookyQR|1.0.2|
|haskell-linter|hoovercj|0.0.6|
|output-colorizer|IBM|0.1.1|
|hoogle-vscode|jcanero|0.0.4|
|language-haskell|justusadam|2.1.1|
|vscode-rust|kalitaalexey|0.3.14|
|mips|kdarkhan|0.0.1|
|markdown-shortcuts|mdickin|0.8.1|
|cpptools|ms-vscode|0.11.1|
|autotrim|NathanRidley|1.0.6|
|phoityne-vscode|phoityne|0.0.12|
|prolog|rebornix|0.0.4|
|scheme|rebornix|0.0.2|
|vscode-icons|robertohuertasm|7.8.1|
|sharecode|RolandGreim|0.4.1|
|code-settings-sync|Shan|2.8.1|
|vscode-table-formatter|shuworks|1.1.1|
|vscode-hexdump|slevesque|1.3.0|
|haskero|Vans|1.3.1|
|vim|vscodevim|0.8.4|
|vscode-wakatime|WakaTime|1.1.7|
|debug|webfreak|0.20.0|
|markdown-pdf|yzane|0.1.7|
|markdown-all-in-one|yzhang|0.6.1|;

**Comment by Chillee** [comment]
How fast is your key repeat?

**Comment by Josef-Vonasek** [comment]
30 characters per second

**Comment by Chillee** [comment]
@Josef-Vonasek It's probably because of how fast your key repeat is.

**Comment by Josef-Vonasek** [comment]
Did you solve it? 

15. 11. 2017 6:02 AM, 6:02 AM, Jason Poon <notifications@github.com> napsal/a:

**Comment by jpoon** [comment]
As Chillee mentioned, this is likely your key repeat delay (https://bltt.org/adjust-windows-keyboard-repeat-rate/).
