### ISSUE TITLE
When inserting new line above current line indention is based on line above

### ISSUE THREAD

**Issue by slifin** [VSCodeVim/Vim#1790]
When using the O command it seems like the vim plugin takes the indentation of line above the current line and uses that to create the new line

![2017-05-31 12 02 24](https://cloud.githubusercontent.com/assets/198857/26629184/160bd37e-45f9-11e7-8440-47222d485eb1.gif)

The behaviour I was used to from the sublime plugin Vintageous is that it would use the line I was on originally's indentation and use that indentation for the new line.

**Comment by Chillee** [comment]
We're simply using the VSCode API call `Add line above` now.

**Comment by Chillee** [comment]
I don't think we should fix this; I think any changes made should be done upstream.

**Comment by jackfranklin** [comment]
@Chillee I came here to post this bug - is it worth raising one on the main VSCode repo to see what they think? I'm happy to do that :)

**Comment by Chillee** [comment]
@jackfranklin Yeah I'd appreciate that. Link back here if you do so.

The issue is that they should be changing `Insert Line Above` (`ctrl+shift+enter`) to have the desired behavior.

**Comment by jackfranklin** [comment]
@Chillee sure thing, reported: https://github.com/Microsoft/vscode/issues/28505

**Comment by J-Fields** [comment]
We're using VSCode's API for this; nothing to be done
