### ISSUE TITLE
Cursor position wrong after `<C-o>p` in Insert mode

### ISSUE THREAD

**Issue by lioneltay** [VSCodeVim/Vim#1791]
Ctrl-o let's you use a command in normal mode then returns you to insert mode. However when using this with paste, it seems to put the cursor before the last character pasted making it annoying to continue typing. The default behaviour in vim puts the cursor after the last character pasted.

Example:

clipboard: 'hello there'

Commands: `iwhy <Ctrl-o>p Bob!` results in

why hello ther Bob!e

**Comment by raulo-sam** [comment]
You can execute command `<C-o>gp` for fixed this problem for now.
