### ISSUE TITLE
%s/str1/str2/ does not work

### ISSUE THREAD

**Issue by vvug** [VSCodeVim/Vim#1793]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

This is a BUG report.

**Environment**:

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**: Debian GNU/Linux

**What happened**: When trying to substitute a string with `s/str1/str2`, `%s/str1/str2/g` or similar command nothing happens. The string is not replaced. Searching for `str1` with `/str1` does work.

I have `"vim.enableNeovim": true` and `"vim.neovimPath": "/usr/bin/nvim"`, which is the actual path to the neovim binary (version 0.1.7).

**Comment by Chillee** [comment]
Try upgrading to version 0.2.0

**Comment by vvug** [comment]
I can't at the moment, it's not Debian packaged and I don't have time to compile it myself. I will close this for now, and reopen it if 0.2.0 doesn't fix it.
