### ISSUE TITLE
Visual block mode copy, paste

### ISSUE THREAD

**Issue by 9to6** [VSCodeVim/Vim#1796]
--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**:1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**: osx 10.12.5(16F73)

**What happened**:

Hello.
I think it's bug.
When I use VisualBlock mode(Ctrl+v),
I selected a word(just a word), press *y* and paste this where I want to insert using (p or P).
Then, you can see insert that word with newline.

**What did you expect to happen**: 

When I insert that word, remove whitespace as newline.

**How to reproduce it**:

Always.
Ctrl+v , select a any word, copy that word using y, paste using a key(p or P)
You can see insert whitespace(new line).

**Comment by Yakkuru** [comment]
I have the same bug, I copy and replace the whole line a lot and it always inserts a newline above.
how to reproduce: 
select the whole line with V copy with y 
select another line with V and replace with p.

**Comment by xxsong5** [comment]
same issue to me.  and how can i fix it

**Comment by idoo** [comment]
yep, very annoying bug

**Comment by tbole** [comment]
Any news on this one?

**Comment by StaverDmitry** [comment]
+1 Pretty confusing behavior, I even trained my muscle memory to instantly delete the excess line

**Comment by GradeyCullins** [comment]
kill me

**Comment by jhsu** [comment]
@9to6 probably because you can visual block select multiple lines. This possibly could create array from the iterator and then joining instead of appending to every line. Do we need a new line at the end if that's done?

**Comment by 9to6** [comment]
@jhsu Yup. I fixed it.

People who feel be annoyed by this bug should check this PR.
And you can build this plugin on local.

https://github.com/VSCodeVim/Vim/pull/2976

**Comment by brayden-jo** [comment]
I have a same problem. When will this bug be fixed. 

```
ctrl+v, copy multiple lines 
move to destination
ctrl+v, and then p (copy)
```

**Comment by J-Fields** [comment]
Likely in the next release

**Comment by XDongiang** [comment]
I havea same problem . I have update my vscode to the latest version.

**Comment by XDongiang** [comment]
> Likely in the next release

The bug is still !

**Comment by J-Fields** [comment]
> > Likely in the next release
> 
> The bug is still !

Hasn't been a release 🙂 I've been busy recently but have a branch where this is just about working, so I still intend to get it out soon.

**Comment by XDongiang** [comment]
> > > Likely in the next release
> > 
> > 
> > The bug is still !
> 
> Hasn't been a release  I've been busy recently but have a branch where this is just about working, so I still intend to get it out soon.

Thank you!
Looking forward to the new version !

**Comment by CaptainDario** [comment]
I encounter the same problem.
When will the new release be published?

**Comment by AntonOfTheWoods** [comment]
@J-Fields , thanks very much for this plugin!!! If you don't have time to cut a release, could you at least give us some instructions on how to apply this patch in a way that isn't going to completely bork our systems? It seems you also have duplicate bug reports, so there may come a point where the amount of time spent answering these is larger than the time to cut a release... No?
