### ISSUE TITLE
:w fails silently for read-only files

### ISSUE THREAD

**Issue by porglezomp** [VSCodeVim/Vim#1801]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

- **VSCode Version**: 1.12.2
- **VsCodeVim Version**:  0.8.4
- **OS**: Windows 7 Enterprise, Service Pack 1

**What happened**:

I'm using perforce, so I have lots of read-only files and I occasionally accidentally try to edit one that's still write protected. When I try to save it with `:w` saving fails silently.

**What did you expect to happen**: 

If I save with Control+S normally, then it brings up a popup offering solutions. `:w` should behave the same way.

**How to reproduce it**:

Attempt to save a file that's set as read-only.

**Comment by jpoon** [comment]
We do show it on the status bar, but due to this https://github.com/VSCodeVim/Vim/issues/2525, you don't actually see it. As the root case is the same, closing this and we'll use #2525 to track.
