### ISSUE TITLE
CMD-C removes Highlight immediately (should remain)

### ISSUE THREAD

**Issue by eduncan911** [VSCodeVim/Vim#1804]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.12.2 (1.12.2)
- **VsCodeVim Version**: 0.8.4
- **OS**: macOS 10.12.5

**What happened**:

* Mouse selected text block.
* Press CMD-C to copy. (no other keys or mouse movement, just CMD-C)
* Selection disappears.

This is inconsistant with all other editors with VIM plugins that I used (Sublime, Atom).  Even Visual Studio 2010/2012/2013 and 2015 with a VIM plugin installed ALL leave the selection highlighted after selecting CTRL-C to copy.

Note, I am NOT talking about **Yank** (which is kind of the same thing).  **Yank** is expected to remove the Highlight after copying.

There is a difference between YANK and CTRL-C/CMD-C for copying in workflows.  For one, CMD-C/CTRL-C shouldn't remove the highlight.

**What did you expect to happen**: 

Like all other editors in the world, once you select a block of text with a mouse, and CTRL-C (WIndows) or CMD-C (macOS) to copy it, it should remain highlighted.

**How to reproduce it**:

* Highlight any amount of text with Mouse.
* Press CTRL-C or CMD-C.  selection should remain.

**Comment by eduncan911** [comment]
Really tried using the plugin for two solid weeks (switching to VScode).  But man, this is far too annoying and messes with my Zen.  

Today, I had to disable the plugin.  And already, within 1 hour, I miss VIM.

**Comment by xconverge** [comment]
When does this happen? In insert mode? This works the same way as MacVim for me, when in insert, if I use the mouse to select an area and press Cmd+c it copies and loses the selection...

**Comment by eduncan911** [comment]
Happens in `INSERT` mode only with CMD-C.  

You know, while testing this across Terminal, iTerm2, Xfce-terminal, Gnome Terminal and my various `i3-sensible-terminal` (the varied list)... It's appearent I need to tweak my `.vimrc` a bit more to be compatible with Clipboards across macOS and Arch, QubesOS, Debian and Fedora.

(yeah, I just tested this out across all of these devices... it isn't consistent with my `.vimrc`)

Let me work on that and I'll come back and re-open this issue if it still exists.

**Comment by xconverge** [comment]
Hey, we are here to get your zen back so feel free to request whatever you want! The worst that would happen is we DONT do it :)
