### ISSUE TITLE
How to make a keybinding only work in visual mode?

### ISSUE THREAD

**Issue by ikzk** [VSCodeVim/Vim#1805]
For example, I use the following config to expand selection in visual mode:
```
{
            "before": [
                "<leader>",
                "v"
            ],
            "after": ["a", "f"]
}
```
However, in normal mode it will trigger an "a" which enters insert mode. How to fix this annoying behavior? Thanks.

**Comment by Chillee** [comment]
I believe that currently this is impossible. We only have support for insert mode key bindings and other mode keybindings.

**Comment by ml653** [comment]
Definitely would love to have this feature!

**Comment by ypresto** [comment]
Also normal mode plz..!
I want to use below remapping so I vote to this feature..!

```
  "vim.normalModesKeyBindingsNonRecursive": [
    {
      "before": ["S"],
      "after": ["y", "s", "i", "W"]
    }
  ]
```

(by using `otherModesKeyBindingsNonRecursive` for this, it will spoil "S" in visual mode...)

**Comment by jpoon** [comment]
PR here https://github.com/VSCodeVim/Vim/pull/2726. But we are debating what we would do with `otherModesKeybindings`:

1) leave the behaviour the same so it handles normal/visualmode keybindings
2) rename it to `normalModesKeybinding` and have it only handle normal mode.
