### ISSUE TITLE
Can't highlight last character of a line.

### ISSUE THREAD

**Issue by khisakuni** [VSCodeVim/Vim#181]
I am unable to highlight the last character of a line without having trailing spaces. This is the case both when trying to move to the last character, and trying to select the last character in visual mode.

**Comment by bradphelan** [comment]
When I'm on the last character of a line and hit __x__ it doesn't delete the character. If I'm on the second last character and hit __x__ it does delete the character. I guess it's the same bug.

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/pull/182

**Comment by KennethAshley** [comment]
I'm still having this issue.
