### ISSUE TITLE
Laggy paste

### ISSUE THREAD

**Issue by ryanlaws** [VSCodeVim/Vim#1812]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

- **VSCode Version**: 1.13.0
- **VsCodeVim Version**: 0.8.4
- **OS**: Windows 8.1 Pro

**What happened**: Pasting yanked text has a 2 second delay. I'm not sure why this is so slow but it adds up. It's better in more recent versions, whereas in old versions it was more like 5+ seconds and pretty much unusable. I can paste with the system clipboard in insert mode but that's pretty un-Vim-like.

**What did you expect to happen**: Instantaneous paste.

**How to reproduce it**: Yank some text and then paste.

**Comment by Chillee** [comment]
@ryanlaws For any amount of text? What about yanking? Are you pasting from the system clipboard?

**Comment by ryanlaws** [comment]
@Chillee Any amount of text, even with one character. The amount of lag seems to be the same regardless of length.

**Comment by michaelHL** [comment]
Just like this...

![](http://i.imgur.com/8LrUXxf.gif)

**Comment by Chillee** [comment]
@michaelHL The issue you're encountering seems a little bit different: https://github.com/VSCodeVim/Vim/issues/1647

It's possible that it's actually only a problem with paste though...

**Comment by ryanlaws** [comment]
A couple more data points, hope these are helpful:
- I can reproduce this repeatedly by simply pasting. The yanking step is actually unimportant, as long as the clipboard is not empty.
- I do not have this issue whatsoever on OS X El Capitan.

**Comment by Chillee** [comment]
@ryanlaws Would it be possible for you to post some kind of gif?

**Comment by ryanlaws** [comment]
@Chillee Sure, hope this makes it a bit clearer.
![vscodevim-issue1812](https://user-images.githubusercontent.com/164690/27393134-444ffae8-565d-11e7-8a92-3eb037325ea3.gif)

**Comment by Chillee** [comment]
@ryanlaws Are you pasting from the system clipboard?

**Comment by ryanlaws** [comment]
@Chillee Yes. Yanked to it using VSCodeVim, then pasted from it.

**Comment by Chillee** [comment]
What happens if you paste from a register.

**Comment by ryanlaws** [comment]
@Chillee pasting from a register is instantaneous!

**Comment by Chillee** [comment]
@ryanlaws This is sounding like a bug with our clipboard library. @xconverge Any ideas?

**Comment by xconverge** [comment]
Nope, I know that it works fine on Win 10, but have not tested 8.1.

If you are up for it @ryanlaws, can you try https://github.com/sindresorhus/win-clipboard

Download the binaries and try to run them from command line as shown in the README? I expect these will be slow and help us identify the issue with that library specifically...

**Comment by ryanlaws** [comment]
@xconverge I downloaded the binaries as described in the README and paste.exe from cmd.exe, but its output was basically instantaneous.

**Comment by ryanlaws** [comment]
Also, I noticed today that with system clipboard, yanking seems to be taking a comparable amount of time for some projects. I'm not sure what this is a factor of - size of documents, number of documents in project, number of projects/instances open, etc.

**Comment by xconverge** [comment]
Can you try the same thing on a file with converted line endings? If you have LF change to CRLF, etc. You can do this in the bottom right of the editor of vscode. Thanks for trying the windows copy paste binaries!

**Comment by deanproxy** [comment]
I may be wrong, but I think this is a problem due to key repeats being very slow to catch up after a key press is released.  If you press and hold a key with vim mode on, it takes a little bit for the commands to stop after you have released that key.  If you turn off vim mode, the key repeats work as expected.  

This behavior exists for me when pasting more than one line by holding down a key as well as when performing any key repeats. It's especially annoying when I'm deleting many characters at a time and just hold down x.  It ends up repeating that key a while after I release the key and deletes many more characters than I intended.

**Comment by xconverge** [comment]
fixed in #3261
