### ISSUE TITLE
Using vim command/':' in settings.json should stay focused in editor

### ISSUE THREAD

**Issue by ksrb** [VSCodeVim/Vim#1813]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT:**

**Environment**:

- **VSCode Version**: Version 1.13.0 (1.13.0) - edited
- **VsCodeVim Version**: 0.7.1
- **OS**:  Mac OSX 10.11.6 (15G1421)

**What happened**:
In `settings.json` pressing command key/<kbd>:</kbd> and then <kbd>escape</kbd>/<kbd>⎋</kbd> will focus the cursor in the `Search Settings` bar.

![jun-08-2017 15-37-01](https://user-images.githubusercontent.com/3750409/26953866-c617ff04-4c61-11e7-9cc4-b1764ff917f4.gif)

**What did you expect to happen**: 

Focus back in the settings file on the right.

**Comment by ksrb** [comment]
Basically this is rather frustrating as I'm trying to edit `settings.json` and whenever I try to use `:w` it focus on the `Search Settings`.

**Comment by xconverge** [comment]
Are you sure you are on 1.12? I just tested and couldnt get it to happen on 1.12, I then updated to 1.13 and it happens...

**Comment by xconverge** [comment]
I also see 1.13 release notes in your gif...

**Comment by ksrb** [comment]
Ops copied and pasted from anther issue 😅, yeah it was 1.13.

**Comment by xconverge** [comment]
Ok, so this is new...I am not sure we will be able to fix it, I think it is most likely a vscode side thing...

**Comment by ksrb** [comment]
Yeah it's a vscode issue I filed a bug on their side https://github.com/Microsoft/vscode/issues/28741.

**Comment by xconverge** [comment]
I think this is fixed in a recent vscode update....?

**Comment by ksrb** [comment]
It's fixed.

**Comment by xconverge** [comment]
Thanks for following up quickly! I am just trying to clean up a bit around here :)
