### ISSUE TITLE
Macros don't delete auto-inserted () correctly

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1815]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

Make a macro, insert (, delete ( so ")" is left, finish macro.

Notice that replaying the macro actually inserts a "(" rather than a ")"

Exact keys to reproduce:

`qqi(<esc>xq@q`

**Comment by Chillee** [comment]
Oh hmm... This might be my bad, if this is a recent regression.

**Comment by johnfn** [comment]
I have no idea if it's recent, but I doubt it!

Only just realized some macro bugs were stemming from this behavior.
