### ISSUE TITLE
Incremental search in multi cursor mode is messed up

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#1822]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

If you do /abc in multi cursor mode, pressing Enter is not sufficient to get out of the incremental search mode. You actually have to press Esc, which resets you back to the original position.

**Comment by tomasruizr** [comment]
Multi cursor in normal mode seems to be ok. but...
I'm having issues with multi cursor in mac when in **insert mode**! is not working as expected.
It loses the ability to select text.
Cmd+d shortcut does not work as expected.
Is there something that I can do to solve it?
My setup:
Mac El Capitan 10.11.6
VSC 1.22.2
Vim: 0.11.5

Is there a better thread to ask?

Thanks

**Comment by lmartins** [comment]
Same thing here as @tomasruizr described, the default behaviour in insert mode provided by the `CMD + D` seems to be broken, doesn't keep the selection and sometimes places the cursors in unexpected positions.

**Comment by sql-koala** [comment]
I think this is fixed now, probably by #5845.
Based on some tests, I would say MC + search works, at least for reasonable cases. Nice.
