### ISSUE TITLE
[Bug] Copy text destroys special characters

### ISSUE THREAD

**Issue by peterjuras** [VSCodeVim/Vim#1825]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug

**Environment**:

- **VSCode Version**: 1.13.0
- **VsCodeVim Version**: 0.8.5
- **OS**: macOS 10.12.5

**What happened**:

Copying text using CMD + C with umlauts and special characters destroys the text. "Grün" results in 
"Gr√ºn".

The normal Copy from the right-click context menu works as expected without errors.

**What did you expect to happen**: 

It should have the full default behavior from VSCode without **any** changes.

**How to reproduce it**:

1. Write text that contains a special character in an editor window with the vscodevim extension running (Examples: Grün Bananenbällchen DÖNER)
2. Select the text with mouse or with the keyboard in insert mode and press CMD + C
3. Paste the text inplace or somewhere else -> The special characters are replaced
(4. Try the same thing with the right click context menu -> Everything is fine)

**Comment by xconverge** [comment]
I assume you have set system clipboard to true?

**Comment by peterjuras** [comment]
No, but I tried it again with systemClipboard enabled and I still have the issue.

**Comment by xconverge** [comment]
can you confirm your vscodevim version? I think you gave the wrong version number

I can copy paste those words all fine with no issues, hmm

**Comment by peterjuras** [comment]
Sorry, I looked at the wrong extension for the version number. I'm using 0.8.5 and updated the original post.

I have additional keyboard issues, for example indenting lines by pressing TAB is not working in visual mode (netiher single nor multiple lines). Pressing TAB in insert mode works however.

It might be that my keyboard layout is destroying things, I am using US International. I also start Visual studio code from the command line.

These issues have started a while ago, but I sadly can't remember when but it is quite frustrating :/

**Comment by xconverge** [comment]
Can you try to see if the issue exists when NOT launched from command line?

Also, isn't > and < for indent and outdent? Tab does not indent for me in gvim..

**Comment by peterjuras** [comment]
The special character errors appear to not happen when I start it outside of the command line. Do you have an idea of what creates this behavior and how I can prevent it from happening from the command line?

**Comment by Chillee** [comment]
@peterjuras I remember this error from somewhere else...

Found it. Do you happen to use tmux?

https://github.com/VSCodeVim/Vim/issues/1660#issuecomment-299756709

**Comment by peterjuras** [comment]
Thanks for your quick reply, I tried it however it did not fix the issue.

Also, there is another weird issue with Copy and Paste, which might be related or unrelated:

- When I first copy text in insert mode using CMD + C, it only copies the first character.
- If I then copy it in visual mode (CMD + C) then it copies everything.
- If I copy in insert mode again afterwards it will copy everything.

This happens regardless of command line or a direct start.

See this gif: http://imgur.com/LE0udTE
![gif](https://i.imgur.com/LE0udTE.gif)

**Comment by xconverge** [comment]
I suspect a locale with utf8 support is not being set correctly when launching from command line... I remember some issues related to command line stuff in the past

@jpoon Do you remember something like this?

**Comment by gomesalexandre** [comment]
**Environment**:

VSCode Version: Version 1.16.1 (1.16.1)
VsCodeVim Version: 0.10.1
OS: macOS 10.12.1

Hi, have the same issue here unfortunately.
It happens either when launched from command-line or launching the app directly. 

When copying using either y or CMD+c, it destroys the characters 
_Dobírka_ becomes _Dob√≠rka_, for example. 

When using Edit -> Copy, I have no issues whatsoever

**Comment by xconverge** [comment]
Do you have any issues when not launching from cmd line?

**Comment by gomesalexandre** [comment]
@xconverge  Thanks for the quick answer 
Indeed, it happens in both cases, command-line and launched directly
I've tried to change system clipboard to true with no luck, same issue

**Comment by jpoon** [comment]
Tried to get a repro on my own machine, but no avail. Are you still seeing this?

**Comment by jpoon** [comment]
Still dnot able to get a repro.
