### ISSUE TITLE
jump to line in command-mode doesn't work.

### ISSUE THREAD

**Issue by psylum** [VSCodeVim/Vim#1826]
**Environment**:

- **VSCode Version**: 1.13.0
- **VsCodeVim Version**: 0.8.5
- **OS**: Microsoft Windows 7

**What happened**:

When using the _command-mode_ entry to jump to a line, the editor does nothing.

**What did you expect to happen**: 

Normal vim will jump to the given line number when you enter that as the only entry in a command-mode command.

**How to reproduce it**:

1. Open any file with 6+ lines.
1. Press `gg` to jump to beginning of the file.
1. Press `:5<CR>`.

I'd expect the editor to jump to line 5 after hitting enter.
Note that doing `5gg` and `5G` both work as expected.
Naturally this should work for any valid line number, I just used an concrete example for clarity.
Also note that I have `"vim.enableNeovim": false,` but i wouldn't expect that to be necessary for this feature.

**Comment by Chillee** [comment]
If you care about this feature, why not just enable neovim?

**Comment by xconverge** [comment]
This is a regression I think? I use this all the time... I think it should definitely be supported by us...

**Comment by josiahcampbell** [comment]
This also is a regression in macOS 10.12.5.

**Comment by Chillee** [comment]
Perhaps not my most popular opinion...

Nevertheless, it is a regression that's my fault, and it is now fixed on master.

**Comment by xconverge** [comment]
No worries! Appreciate the quick fix!

**Comment by psylum** [comment]
Appreciate the fast response!
