### ISSUE TITLE
Mac Sierra useSystemKeyboard breaks some basic keybindings (dd and cw yw) etc.

### ISSUE THREAD

**Issue by sreimer15** [VSCodeVim/Vim#1830]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version*1.13.0*:
- **VsCodeVim Version*0.8.5*: 
- **OS* Mac OSX Sierra 10.12.5*: 

**What happened**:
In this version of mac, when I change vim.useSystemClipboard to true in settings, it breaks most functionality.
cw => stays in normal mode and merely displays cw in the status bar
dd => stays in normal mode and displays dd in the status bar
 cw dd yw in normal mode

**What did you expect to happen**: 

**How to reproduce it**:
Turn on vim.useSystemClipboard on these versions and commands don't work. If you turn it back off then all the commands work fine.

Thank you for any help you can be!

**Comment by xconverge** [comment]
I use all of the same versions AND useSystemClipboard and cannot reproduce this... :/

**Comment by sreimer15** [comment]
I think this was a personal issue, regarding mapping keys to the terminal because it was also messing with some of my tmux commands. After I restarted and updated my computer the problem went away. Thank you!

**Comment by a-eid** [comment]
@sreimer15  I'm having the same problem, although added to your is that vscode doesn't copy or paste text at all ( when launched from the terminal ( I also use tmux) )
