### ISSUE TITLE
Strange visual selection with keys remapped to ^ and $

### ISSUE THREAD

**Issue by Silox** [VSCodeVim/Vim#1835]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Environment**:

- **VSCode Version**: 1.13.0
- **VsCodeVim Version**: 0.8.5
- **OS**: Windows 10, creators update

**What happened**: In my config, in `otherModesKeyBindingsNonRecursive` I mapped `H` to `^` and `L` to `$`. When I enter viasual mode (press `v`) and press `L` afterwards, it selected to the end of the visible screen. Same for `H` which selects to the start of the visible screen.

When I press `v` and then `^` or `$`, the correct action happens: it selects until the start or the end of the line.

**What did you expect to happen**:   I expect that when I enter visual mode (press `v`) and press `L` afterwards, it selects to the end of line.  Same for `H` which I expected to select to the beginning of the line. 

**How to reproduce it**:

1. Add the following to your settings:
```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["H"],
            "after": ["^"]
        },
        {
            "before": ["L"],
            "after": ["$"]
        }
    ],
```
2. Enter visual mode: press `v`
3. Press `H` (or `L`)

**Important**: This worked fine for a few months until it stopped a few weeks ago. I went trough the changelog and the only thing that could be related is the `Fixes visual block mode respect keybindings @Chillee #1709` in the Neovim Nutty release. But I'm not sure. Outside of visual mode (in normal mode for example), the work as expected.

It gets even stranger: When I enter visual mode, press a navigation key (e.g. `l`) once to move one space and then press `L`, it selects as expected until the end of the line.

**Comment by Chillee** [comment]
Huh. You're right.

When I first saw this bug report, I thought it was just a limitation of our remapper (for example, `dH` with that mapping has never worked properly). But I just checked it on a v0.7.0, and it seems to work fine.

How interesting. I personally use this keybinding, so I'll try to figure out what's wrong soon.

**Comment by Chillee** [comment]
Ok, so this is a bug that was revealed as the result of fixing another bug.

https://github.com/VSCodeVim/Vim/commit/cbcc982d209b7e5784a1d615d92ae31d35bfaa86

is the commit that caused it.

**Comment by benjaminwood** [comment]
I too have been impacted by this bug. In my case I had remapped `hjkl` to `jkl;`. Same symptom though, switch to visual mode and the remappings do not take effect until at least one key has been pressed.

**Comment by jwmann** [comment]
I have this same exact issue.

Except since `vim.otherModesKeyBindingsNonRecursive` was removed, it's more like this:
```
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["j"],
            "after": ["g", "j"]
        },
        {
            "before": ["k"],
            "after": ["g", "k"]
        },
    ],

**Comment by uri** [comment]
These bindings seem to work if you pause for 2-3 seconds after entering visual mode.

With 

```json
{
            "before": ["H"],
            "after": ["^"]
}
```

<kbd>v</kbd> *pause for 3 seconds* <kbd>H</kbd> produces the the correct behavior

**Comment by charlietran** [comment]
I'm still experiencing this bug, but this workaround from https://github.com/VSCodeVim/Vim/issues/2842 fixes it for now:

```
  "vim.normalModeKeyBindings": [
    ...
    {
      "before": ["v"],
      "after": ["v", "l", "h"]
    }
    ...
]
```

**Comment by jakalada** [comment]
<img width="347" alt="スクリーンショット 2019-06-22 15 03 13" src="https://user-images.githubusercontent.com/79089/59960158-e66cba00-94fe-11e9-9e73-27d430ff024f.png">

I change `Vim Configuration > Timout` to `0`, This issue is solved. But, it is not a good solution.

**Comment by thisisrandy** [comment]
Any movement on this? The workaround that @charlietran references breaks text object motions, e.g. viw, so it isn't really viable
