### ISSUE TITLE
Feature Request: Make cgn work after /

### ISSUE THREAD

**Issue by johncrisostomo** [VSCodeVim/Vim#1838]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Make search using `/` and then `c` + `g` + `n` work for easy consecutive replace using `.`
This is what I use for search and replace many in vim.

**Comment by xconverge** [comment]
Duplicate of #1955, both issues have the same amount of thumbs ups, closing this one in favor of the other one due to content of the report. Thanks for reporting though!
