### ISSUE TITLE
Make vim.statusbarcolors only affect the mode string.

### ISSUE THREAD

**Issue by darkermatter** [VSCodeVim/Vim#1839]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Currently the extension changes the colour of the whole status bar. It would be great to have an option to just change the mode string.

**Comment by xconverge** [comment]
What do you mean? Do you mean only change the color there or the actual text?

**Comment by darkermatter** [comment]
Something like this:

![vim-mode](https://user-images.githubusercontent.com/5037324/27145719-09cc449c-5137-11e7-96a1-b99ba4673b3c.jpg)

**Comment by darkermatter** [comment]
I did a quick patch to ```out/src/mode/modeHandler.js```:
```
setStatusBarText(text) {
    if (!ModeHandler._statusBarItem) {
        ModeHandler._statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
    }
    ModeHandler._statusBarItem.text = text || '';
    if (this._vimState.currentModeName().toLowerCase() === 'insert' || this._vimState.currentModeName().toLowerCase() === 'replace') {
        ModeHandler._statusBarItem.color = 'red';
    }
    else if (this._vimState.currentModeName().toLowerCase().startsWith('visual')) {
        ModeHandler._statusBarItem.color = 'orange';
    }
    else {
        ModeHandler._statusBarItem.color = 'white';
    }
    ModeHandler._statusBarItem.show();
}
```

From reading the VS Code API docs, you can only set the foreground colour. :-(

**Comment by jpoon** [comment]
Closing this issue given the age of the bug and the lack of activity.
