### ISSUE TITLE
Commands preceded by number only perform commands once

### ISSUE THREAD

**Issue by kevinkucharczyk** [VSCodeVim/Vim#184]
For example, I would like to use **5A** to append some text five times - which, according to the readme, is supported. However, the 5 is being ignored and my text is only appended once.

Another example is trying to move forward an x amount of words via **6w** (for 6 words). Again, the number is ignored and I'm only moving one word.

I'm on Windows 7 and VS Code 0.10.10.

**Comment by jpoon** [comment]
Not something we support right now but it is on our roadmap.

**Comment by johnfn** [comment]
I'm pleased to say that we support this now! Repeating movements pretty much works. Repeating commands works in theory, but in practice still has a few bugs to be ironed out.
