### ISSUE TITLE
Append text at the end of the line (N times)

### ISSUE THREAD

**Issue by erlais** [VSCodeVim/Vim#1843]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.0-insider
- **VsCodeVim Version**: 0.8.6
- **OS**: Windows 10

**What happened**: Appending for example 3afoo appends foo three times correctly. One would expect similar behavior with 3Afoo when appending to end of line. But the count part is not doing anything. It works in Vim. Same issue with insert

**What did you expect to happen**: 3Afoo to append foofoofoo to end of line

**How to reproduce it**: 3Afoo

**Comment by xconverge** [comment]
This should be an easy one, I think ```I``` should be covered as well, so add I and A
