### ISSUE TITLE
Multicursor/intellisense/autocomplete/snippets broken

### ISSUE THREAD

**Issue by Chillee** [VSCodeVim/Vim#1847]
If you're getting very bad multicursor behavior, first check that it is only in files that have either word wrapped lines or folds. If so, the cause is this:

https://github.com/Microsoft/vscode/issues/28853

Snippets with multicursors have some issues everywhere.

**Comment by gutenye** [comment]
@Chillee Is there a workaround? Downgrade to version 1.12 will fix it?

**Comment by poiati** [comment]
Hello,

I'm still unable to use multicursor and apparently the issue https://github.com/Microsoft/vscode/issues/28853 was closed.

**Comment by iantanwx** [comment]
Multicursor is also not working for me.

Given the following snippet:

```
	"Insert Action Set": {
		"prefix": "action_set",
		"body": [
			"export const ${1:ACTION_NAME} = createActionType('${1:ACTION_NAME}', ${PREFIX});",
			"export const ${1:ACTION_NAME}_ERROR = createActionType('${1:ACTION_NAME}_ERROR', ${PREFIX});",
			"export const ${1:ACTION_NAME}_SUCCESS = createActionType('${1:ACTION_NAME}_SUCCESS', ${PREFIX});"
		],
		"description": "Inserts a set of action, action_success, action_error blocks"
	}
```

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/1946
