### ISSUE TITLE
NeoVim "Never Show Again" dismissal is not working

### ISSUE THREAD

**Issue by mbueti** [VSCodeVim/Vim#1848]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.8.6
- **OS**: macOS Sierra 10.12.5

**What happened**:

When launching any new VSCode instance:
-I receive the notification that neovim bindings are available.
-I dismiss with "never show again", as I do not have neovim installed
-On next app launch, I receive the notification again
-Lather, rinse, repeat since the neovim extension rollout

**What did you expect to happen**: 
I expect to never see the notification again

**How to reproduce it**:

**Comment by Chillee** [comment]
@mbueti Agh. A couple of people have reported this issue, but I can't reproduce it. Can you see if setting `vim.disableAnnoyingNeovimMessage' stops this issue for you?

**Comment by mbueti** [comment]
@Chillee Looks like that does the trick! Appreciate the quick response (and self-aware setting name)!

**Comment by Chillee** [comment]
@mbueti We'll be removing the option soon, luckily.

**Comment by jpoon** [comment]
This has been removed entirely with https://github.com/VSCodeVim/Vim/pull/2138/commits/4178379f3a7faa47b1a9207f2ec71d3c9998a143.
