### ISSUE TITLE
Jumping to previous item, CTRL-O scrolls the window when in-sight

### ISSUE THREAD

**Issue by erihanse** [VSCodeVim/Vim#1850]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**What did you expect to happen**: 
Only cursor jumping to the last location, without the window centering on the cursor. 
This makes it sometimes hard to keep track of where you are. 
**How to reproduce it**:

**Comment by Chillee** [comment]
I think that until we implement our own jump list, we can't fix this.

**Comment by axs221** [comment]
Is this still an issue? I'm not seeing the behavior, <C-o> centers on the cursor for me. I am working on  https://github.com/VSCodeVim/Vim/issues/1933 to implement our own jump list regardless, but maybe this issue here can be closed if it is working as expected.

**Comment by J-Fields** [comment]
No longer an issue, as far as I can tell.
