### ISSUE TITLE
Neovim Integration not work on Windows

### ISSUE THREAD

**Issue by ChannelOne** [VSCodeVim/Vim#1853]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**:  0.8.6
- **OS**:  Windows 10 Creators Update

**What happened**:

An error occur: **Unable to setup neovim instance! Check your path.**

Here is my config

```
    "vim.neovimPath": "C:\\Neovim",
    "vim.enableNeovim": true
```

I have tried changing `neovimPath` to the `bin` folder, but it doesn't work neither.

**Comment by xconverge** [comment]
you have to point it to the .exe specifically

**Comment by ChannelOne** [comment]
@xconverge Thx, it's works. Somebody should add it in the document.

**Comment by xconverge** [comment]
If you mouse over vim.neovimPath I had updated the tooltip help in the latest release.

**Comment by ChannelOne** [comment]
@xconverge  Yeah, maybe, I haven't noticed that. But a vim user seldom use his mouse , right?🙃

**Comment by xconverge** [comment]
```gh``` will show you ;)

**Comment by christianburger** [comment]
I took hours to find out a neovim executable is needed for this, that's really bad documentation...
Why not mention this right at the first line? I never new there was a neovim thing in the first place.

**Comment by Chillee** [comment]
@christianburger  Where do you expect us to place this documentation? It's right in the settings.

**Comment by tdunnington** [comment]
I have to agree with @christianburger here.

My expectations when installing a VsCode plugin is that I find the plugin I want, click the install button, click reload, and it works.

What I got here was click install, click reload, and then get an error about Neovim executable paths. What is neovim? Did I need to install that before I installed this plugin? How was I supposed to know that?

I see no documentation anywhere that says this plugin has an external dependency on another application. And that's what @christianburger is getting at: how was I supposed to know that I needed to install something else to make this work?

**Comment by Chillee** [comment]
@tdunnington You shouldn't be getting any kind of error about a "neovim executable" unless you enable neovim. 

If you don't touch the settings, the typical flow should be as you're used to.

**Comment by tdunnington** [comment]
@Chillee gotcha, I see now!

There was a setting in my setting file to enable neovim. I'm not sure why it was there other than I must have had this plugin installed before at one point. I don't know why that setting was in my config. But I just removed it and WHALA, plugin works as expected. Thanks sir!

**Comment by intothevoid** [comment]
I had the same issue. The 'neovim enable' setting was true (I didn't set it myself). The error about the neovim path just showed up after I installed the vim integration plugin. Anyways, I see now neovim is only needed for a subset of features and I can simple disable it instead of jumping through hoops to getting it installed and setting up the path.
