### ISSUE TITLE
Searching via '/' does not highlight search results in scrollbar

### ISSUE THREAD

**Issue by suan** [VSCodeVim/Vim#1856]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.8.6
- **OS**: OSX 10.12.5

**What happened**: Searching via '/' does not highlight search results in scrollbar, even though I have `vim.hlsearch` set to `true`

**What did you expect to happen**: Search results should have the yellow highlight on the scrollbar, just like what happens when you use VSCode's native (Ctrl+F) search

**How to reproduce it**: Just search using `/`

**Comment by Chillee** [comment]
I *suspect* this is a VSCode upstream issue, but give me some time to do some investigation before opening an issue.

We use decorations to handle the highlighting, and those aren't showing up in the scrollbar.

**Comment by xconverge** [comment]
I am actually not sure how to do this really, @rebornix any ideas?

**Comment by jpoon** [comment]
Doesn't look like this capability is exposed by VSCode. @suan, can you file an upstream feature request with VSCode?

**Comment by wangliangster** [comment]
dam, seems use ":s/" or just "/" is ok, instead of using ":/", which is old habbits in vim
