### ISSUE TITLE
Substitute pattern with newline

### ISSUE THREAD

**Issue by samsong8610** [VSCodeVim/Vim#1861]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.8.6
- **OS**: fedora 25 4.11.3-200.fc25.x86_64

**What happened**:

I have comma separated line like `a,b,c`. I want to split each char into a line using:
```
V
:s/,/\r/g
```
But the actual output is
```a\rb\rc```

It works in vim 8.0

**What did you expect to happen**: 
Each part separated by comma is in a line. Expected output is:
```
a
b
c
```

**How to reproduce it**:

**Comment by xconverge** [comment]
I think this is caused by https://github.com/Microsoft/vscode/issues/29238

**Comment by Chillee** [comment]
@samsong8610 Is this with or without neovim integration?

**Comment by xconverge** [comment]
Actually it seems to work WITH neovim integration, it does not work WITHOUT neovim integration

**Comment by samsong8610** [comment]
@Chillee It is without neovim integration.

**Comment by Chillee** [comment]
@xconverge Neovim integration just allows us to run the command within neovim. So if it works in Neovim it should work in VSCode (with a couple exceptions).

@samsong8610 I'd suggest adding the neovim integration if you want this feature. Although we'll keep this open and may fix it, things that work with neovim integration will tend to have lower priority.
