### ISSUE TITLE
can't remap U/shift + u

### ISSUE THREAD

**Issue by endlist** [VSCodeVim/Vim#1865]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  Bug Report

**Environment**:

- **VSCode Version**:  1.13.1
- **VsCodeVim Version**: 0.8.6
- **OS**: Mac Sierra

**What happened**:

Mapped `U` (shift+u) to `<C-r>`

```js
"vim.handleKeys": {
    "<S-u>": false
},
"vim.otherModesKeyBindingsNonRecursive": [{
    "before": ["<S-u>"],
    "after": ["<C-r>"]
}]
```
Wrote something, undid it with `u`, attempted to redo it with `U`, nothing happens.  I tried variations like using "shift+u" or just "U" instead of "<S-u>", but seeing the same results.

I'm currently attempting to work around this using a leader mapping, but it's unintuitive for me, and I'd prefer my old shortcut.

**What did you expect to happen**:  Redo is mapped to U.

**How to reproduce it**:  Add mapping, attempt to press keys.

**Comment by xconverge** [comment]
I think that this is what you are looking for, don't use the handle keys, this removes the vim plugin  from getting that key and delegates it back to vscode

```
"vim.otherModesKeyBindingsNonRecursive": [{
    "before": ["U"],
    "after": ["<C-r>"]
}],
```

Feel free to reopen if I missed the mark here! :)

**Comment by endlist** [comment]
Weird...  I just tried this again and now it does work, but as noted in my original post, it didn't then.  Not sure what changed, but thanks!

**Comment by jvican** [comment]
Hey guys, is it possible to add this to the docs or even add it by default? I think lots of vim users are used to using `<S-u>` as the synonym for <C-r>`.

**Comment by jpoon** [comment]
@jvican feel free to submit a PR :)
