### ISSUE TITLE
keybinding question

### ISSUE THREAD

**Issue by super0mario** [VSCodeVim/Vim#1866]
when I change the 'b' key, I can't map 'i','w','y',v' anymore to other keys. 
Is there another way to do it?

     "vim.otherModesKeyBindingsNonRecursive": [
     {
        "before": ["b"], 
        "after": ["v","i","w","y"]
    }

**Comment by Chillee** [comment]
@super0mario This works. It kinda looks like you're also doing `b` at the same time because `y` puts you at the beginning of your range.

**Comment by super0mario** [comment]
it actually works... I think I should've reloaded vscode or something... my bad.

**Comment by xconverge** [comment]
Wow the things you guys bind never ceases to amaze me
