### ISSUE TITLE
InsertModeKeyBinding is not applied for repeated keys

### ISSUE THREAD

**Issue by nonylene** [VSCodeVim/Vim#1867]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**:  0.8.6
- **OS**: mac OS X El Capitan

**What happened**:

I remapped `3` to `#` by `insertModeKeyBindingsNonRecursive`. When I press `3` key once, this remapping works well. However, if I hold down `3` key, `3` is inserted repeatedly except the first character.

```
#333333333...
```

**What did you expect to happen**: 

`#` is inserted repeatedly.

```
#########...
```

**How to reproduce it**:

1.  Add below configuration to`settings.json`

```json
    "vim.insertModeKeyBindingsNonRecursive": [
        {
            "before": [
                "3"
            ],
            "after": [
                "#"
            ]
        }
     ]
```

2. Hold down `3`  key on INSERT mode.

**Comment by Chillee** [comment]
These keybindings continuously confuse me. Regardless, I think I know why this bug exists.

**Comment by nonylene** [comment]
I replace numbers and symbols (`Shift-{num}`) while typing code. This makes it faster to write :)

**Comment by nonylene** [comment]
This issue is not occured on the current version (VSCode 1.36.1, VsCodeVim 1.8.1). Thanks!
