### ISSUE TITLE
Cannot bind d and dd at the same time.

### ISSUE THREAD

**Issue by Recognition101** [VSCodeVim/Vim#1870]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.8.7
- **OS**: 10.12.5

I went back and tested each version, looks like this issue was introduced in VsCodeVim 0.8.0.

**What happened**:

My key binding file that worked in previous versions of VSCodeVim no longer works.

**What did you expect to happen**: 

My binding file should have still worked.

**How to reproduce it**:

Try to bind the following:

```
{
    "before": ["d"],
    "after": ["\"", "_", "d"]
}, {
    "before": ["d", "d"],
    "after": ["\"", "_", "d", "d"]
}
```

With this binding, pressing a combination like `dl` should let you delete without yanking to the clipboard. This works. However, pressing `dd` should let you delete a line without yanking to the clipboard. Previously, this worked. As of updating about a month ago, it no longer works.

**Comment by Ethefor** [comment]
Right, I experienced the same problem.

**Comment by tlattimore** [comment]
I am also experiencing the same problem. Naturally, the temporary solution is just us `^d$` the line. But it would be nice to have this back.

**Comment by wongjiahau** [comment]
I am also experiencing a similar problem where I cannot bind `dh` to `d^`. 
```js
    "vim.otherModesKeyBindingsNonRecursive": [{
            "before": ["d", "h"],
            "after": ["d", "^"]
        }]
```
I have this setting above but where I pressed `dh` , it will execute `dd`, instead of `d^` which is set in the setting.

Moreover, binding `dl` to `d$` also has the same problem as above.

**Comment by DeX3** [comment]
Experiencing exactly the same issue
