### ISSUE TITLE
Selecting with mouse or double clicking on a word to select it should NOT go into visual mode

### ISSUE THREAD

**Issue by gotofritz** [VSCodeVim/Vim#1871]
Unlike what #290 says, selecting with mouse should NOT go into visual mode.

We are still using VS Code, not Vim - if I use the mouse it means I DON'T want to use Vim commands. If I wanted to only use Vim commands, then I would use Vim.

At least make it configurable so we can toggle the behaviour on / off in the preferences!

Thanks.

**Comment by Chillee** [comment]
Sounds reasonable, but out of curiosity, what are the downsides of going into visual mode?

**Comment by gotofritz** [comment]
Because some of us, those whose vim foo is not yet so strong, prefer to dip in and out of vim.

Note that you can still use the cursor in insert mode, and if you are in insert mode and use LEFT + SHIFT + ALT you select the whole word - remaining in insert mode. Then if you type letters you will replace the selection with what you typed. Basically VS Code behaves as if VSCodeVim was not installed when you use the cursor keys. Vim purists will probably consider it a bug, but for us beginner it's a god send. I suggest the mouse could be treated the same way. If I use the mouse it means I am not doing Vim stuff, basically. If I want visual mode I use the keyboard. 

The problem is that (1) it wasn't expected, but even now that I know (2) it have to frantically click escape - i escape - i escape i until it gets back to insert mode. 

Maybe it's just because I was used to Vintageous in Sublime. VSCodeVim is generally much better, but I think vintageous gets the balance of Vim + non-Vim right. Sometimes it's good to take a step back and just let VS Code be VS Code IMHO (CMD-D is another area where VSCodeVim gets in the way).  A config settings to allow the mouse to be ignored would be great.

Thanks for all the great work, either way.

**Comment by galenjiang** [comment]
I think it is reasonable, this make me can not multi select something to use normal operation.

**Comment by galenjiang** [comment]
Many wired operation cause by it,  selected by mouse, and can not delete normally by backspace and so on.

**Comment by knownasilya** [comment]
Same here, this has changed in the recent release I think. Basically, if you hit 'i' you are in insert mode, now if you go to select text and try to do some non-vim stuff it used to just work. Now it no longer works at all. I have to disable vim mode to use the mouse. This is a pretty big bug.

**Comment by Chillee** [comment]
Alright I hear you guys. I'll make it an option in the settings.

**Comment by heeton** [comment]
@Chillee Thanks, an option is ideal

**Comment by coryshaw1** [comment]
I sometimes use my mouse too select while in Insert Mode, and when I'm in Insert Mode and select a text block, it switches me back to Visual Mode. An option to disable this forced Visual Mode would be ideal, especially while in Insert Mode.

**Comment by knownasilya** [comment]
Agree totally @coryshaw1

**Comment by knownasilya** [comment]
Woot

**Comment by jfoo1984** [comment]
is this setting released already?

**Comment by sethstha** [comment]
@jfoo1984 
Not yet, Will be released on next update. Not sure when they are going to push an update. But this is what I have been waiting for so long.

**Comment by gotofritz** [comment]
Any news on the when the next update is going to be? Or is there a way to start using it before it's released? The plugin is unusable AFAIC since this change was introduced. Thanks!

**Comment by Chillee** [comment]
@gotofritz `i` isn't supposed to work in either visual mode or Visual Line mode. `I` currently works in visual mode but not visual line mode, so I guess that's a valid bug.

If you really want to try it now, I guess you can download the source repository and create a .vsix to load in.

The next update will probably be this weekend (hopefully). We currently have an issue with our Travis build system which would prevent a release.

**Comment by gotofritz** [comment]
If anyone else found this plugin unusable since the mouse change, a different plugin, vimStyle, does the same job but without interfering with the mouse. AND without interfering with CMD-D.

**Comment by Chillee** [comment]
@gotofritz if we're on the topic of other extensions I'd suggest amvim over vimstyle.

**Comment by wo52616111** [comment]
@Chillee thanks, amVim is pretty good for me, without interfering with the mouse and `<cmd-D>`, although it's not as powerful as VSCodeVim, I'll use it until the problem about interfering with `<cmd-d>` in VSCodeVim was fixed.

In addition, if someone want to try the setting `vim.mouseSelectionGoesIntoVisualMode ` now (before the setting released), see [Packaging VSCode Extensions](https://code.visualstudio.com/docs/extensions/publish-extension#_packaging-extensions).

**Comment by knownasilya** [comment]
Ping

**Comment by Chillee** [comment]
Sorry for taking so long on pushing a release.

But VsCodeVim v0.10.0 is out now, and it has the fix.
Set `    "vim.mouseSelectionGoesIntoVisualMode": false` to fix this issue!

**Comment by coryshaw1** [comment]
Great to hear! From what I can tell, the new setting is working as expected. Thanks for the update!

**Comment by gotofritz** [comment]
Brilliant stuff - thanks for all your hard work!

**Comment by christiangenco** [comment]
Setting `"vim.mouseSelectionGoesIntoVisualMode": false` totally works, but it's strangely only working for me while my settings are open.

Here's [a screen recording showing the bug](https://youtu.be/9JUkdspipQw).

When the user settings window isn't open, when I click on a line VSCode looks like it's in normal mode (the cursor appears as block and `--NORMAL--` status in the bottom bar are set), but if I type a character the character gets inserted as in `--INSERT--` mode (and the status immediately changes).

Opening the user settings window makes it behave correctly.

What on earth is going on? 😭

**Comment by kjgoodrick** [comment]
@christiangenco I am also experiencing the same behavior. I opened it as a new issue [here](https://github.com/VSCodeVim/Vim/issues/2410).

**Comment by johnking** [comment]
This option
 is very helpful for me. Thanks a lot!
