### ISSUE TITLE
[Windows] yanking with "vim.useSystemClipboard: true" copies to " and not + register

### ISSUE THREAD

**Issue by gerdneuman** [VSCodeVim/Vim#1872]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**: Windows

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10

**What happened**:

`vim.useSystemClipboard": true` is set.

`yaw` (or similar `y[motion]` command) yanks (copies) the text to the `"` (select) register which is pretty much useless in Windows. By default it should yank to the `+` (clipboard) register

At the moment I have to use `"+yaw` if I want to yank anythink to the system clipboard.

Here's my settings.json:
```
// Platzieren Sie Ihre Einstellungen in dieser Datei, um die Standardeinstellungen zu überschreiben.
{
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "files.trimTrailingWhitespace": true,
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "j",
        "j"
      ],
      "after": [
        "<Esc>"
      ]
    }
  ],
  "vim.otherModesKeyBindingsNonRecursive": [
    // ZZ to save and close current file
    {
      "before": [
        "Z",
        "Z"
      ],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.files.save",
          "args": []
        },
        {
          "command": "workbench.action.closeActiveEditor",
          "args": []
        }
      ]
    }
  ],
  "vim.useSystemClipboard": true,
  // "vim.useSolidBlockCursor": true,
  "vim.easymotion": true,
  "vim.leader": " ",
  "vim.foldfix": true,
  "window.zoomLevel": 0,
  "editor.cursorStyle": "block",
  // "vim.useCtrlKeys": false,
  "vim.handleKeys": {
    "<C-a>": false,
    "<C-f>": false
  },
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "workbench.iconTheme": "vs-seti",
  "editor.minimap.enabled": true,
  "editor.cursorBlinking": "solid",
  "editor.fontSize": 16,
  "vim.disableAnnoyingNeovimMessage": true
}
```

**Comment by Chillee** [comment]
Huh that doesn't sound like correct behavior.

I don't think `"` is the select register, that's just the default register.

It sounds like it's just failing to copy to the system clipboard at all. Have you tried restarting VSCode since changing the setting?

**Comment by gerdneuman** [comment]
Seems to work today, very strange. Closing.
