### ISSUE TITLE
2o addes Multi Cursor to inserted empty lines

### ISSUE THREAD

**Issue by con-ssc** [VSCodeVim/Vim#1873]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**: Windows

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10

**What happened**:
Hitting `2o` inserts 2 lines and puts multicursor on it

**What did you expect to happen**: 
Hitting `2o` to insert 2 empty lines and put one cursor on the last line.
**How to reproduce it**:
Enter `Normal Mode` and hit `2o`

**Comment by Chillee** [comment]
The current behavior is the same behavior as in vim. As such, I don't think we should change it.

**Comment by con-ssc** [comment]
I guess it is not.
gVim 2o
![2017-06-27_10-02-01](https://user-images.githubusercontent.com/8189808/27577095-ba7bb4f2-5b1f-11e7-95a4-30d98ffcb7e4.gif)
vscode with vim 2o
![2017-06-27_10-03-04](https://user-images.githubusercontent.com/8189808/27577134-e1c0c778-5b1f-11e7-9f91-37b2db18eff3.gif)

**Comment by Chillee** [comment]
If you try typing in gvim and then press `<esc>`, you'll see that it repeats what you typed `<count>` times. For example, this is the result after I typed `5ofoo<esc>`
![](http://i.imgur.com/vpjtCmu.jpg)
