### ISSUE TITLE
Save As with `:w <filename>`

### ISSUE THREAD

**Issue by ghost** [VSCodeVim/Vim#1876]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**FEATURE REQUEST** 

The normal `:w` only works with files that have already been saved. If I open a new undefined file and want it to save as in the currently active folder `:w filename.txt` does nothing. It would be nice if this would just follow the usual save as procedure.

**Comment by skosch** [comment]
Not to dismiss this idea at all, but in the meantime, for those looking to save files under an explicit name there already is `:sav <filename>` as well.

**Comment by con-ssc** [comment]
Ah, very good. That would already suffice for me.

**Comment by skosch** [comment]
**RETRACTION – I eat my words!** :disappointed_relieved:   `:sav` does *not* work either (although I promise it does in vim!) ... the only thing that seems to do it for new files is to type `:w` without a filename, hit enter, and use the "Save File" dialog that pops up.

This really would be nice to have!

**Comment by con-ssc** [comment]
Oh okay. Well that I knew already was the reason for the issue :P

**Comment by skosch** [comment]
... or rather, the real bug is that `:sav <filename>` does indeed save the file, but the tab's path isn't set to the filename, so subsequent `:w`'s don't do anything.

**Comment by asyks** [comment]
Any update on this? Not having `:sav <filename>` support is somewhat crippling.
