### ISSUE TITLE
Make :e open up a file dialog if no file name is passed in

### ISSUE THREAD

**Issue by Chillee** [VSCodeVim/Vim#1877]
As @xelra said on the neovim gitter, 

> Well, when I specified a filename it did try to open a file based on the current working directory and offered to create it. For that I'd actually expect it to directly create it. And for without specifying a filename I expected a dialogue to browse for a file.

**Comment by westim** [comment]
I believe the API to enable this is not yet implemented in VSCode, but is [In-Progress on the September Iteration Plan](https://github.com/Microsoft/vscode/issues/34160) and should be released early October:

![image](https://user-images.githubusercontent.com/11410900/30591994-127e6278-9d13-11e7-9a2b-ae2ff79208ef.png)

After it's promoted to stable, it should be as easy as calling this API in the right place:

```Typescript
vscode.commands.ExecuteCommand('vscode.window.showOpenDialog');
```

**Comment by miguelsaldivar** [comment]
Can I try working on this using openTextDocument as suggested by @jpoon?

**Comment by jpoon** [comment]
I haven't seen any updates from @DanEEStar so he may have abandoned the PR? Feel free to take it on though @miguelsaldivar

**Comment by DanEEStar** [comment]
@miguelsaldivar I updated my pull-request. But I think here https://github.com/VSCodeVim/Vim/blob/14deb22e73dbe5bd537aded294a5874553715fd1/src/cmd_line/commands/file.ts#L98 is also a possibility to use `openTextDocument` ?!
