### ISSUE TITLE
After yy, vscode loses redo chain

### ISSUE THREAD

**Issue by jeiea** [VSCodeVim/Vim#1881]
- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10 RS1

**What happened**: After yy, vscode loses redo chain.

**What did you expect to happen**: Redo normally.

**How to reproduce it**:
Delete one line, undo deletion, copy one line and redo deletion.
dduyy ctrl+y

**Comment by Chillee** [comment]
@jeiea We have `<ctrl-r>` bound to redo. `<ctrl-y>` is scroll up in vim unless you're using Windows bindings or something.

**Comment by jeiea** [comment]
I had misunderstood the problem. It seems vscodevim has separate undo chain with vscode's. I expected vsvim's behavior. It uses unified undo chain, so u and ctrl+z have same effect.
Can it be feature request?

**Comment by jeiea** [comment]
@Chillee In my vscode setting `ctrl+y` is normal undo. `ctrl+z ctrl+y` works well with vscodevim.

**Comment by Chillee** [comment]
@jeiea That would be this issue: https://github.com/VSCodeVim/Vim/issues/1490 I'm gonna close this in favor of that issue.
