### ISSUE TITLE
Support binding letter sequence to ESC in OtherModes

### ISSUE THREAD

**Issue by pciazynski** [VSCodeVim/Vim#1883]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**:  0.9.0
- **OS**: Ubuntu 16.04

**What happened**:
I try to bind `jk` to `<ESC>`:
```javascript
"vim.otherModesKeyBindingsNonRecursive": [       
  {
    "before": [ "j", "k" ],
    "after": [ "<Esc>" ]
  }
]
```
but this doesn't work. jk does nothing in Visual Mode.

**What did you expect to happen**: 
Because I have binding `jk` to leave Insert Mode I would like also have possibility to escape Visual Mode with `jk`, but this doesn't work.

**How to reproduce it**:
Paste above snipper into your `settings.json`, go to Visual Mode and press `jk`. Unfortunately nothing happen, we will stay in Visual Mode.

**Comment by DevonMorris** [comment]
Where could one go to start working on this?
