### ISSUE TITLE
Going to a line marks a document as changed

### ISSUE THREAD

**Issue by Valve** [VSCodeVim/Vim#1887]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
If I open a document and go to a certain line the document is marked as "changed".

- **VSCode version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: macOS Sierra 10.12.5

**What happened**:

`:` - this opens Vim command line
'48' - this jumps the cursor to the line 48

File is marked as "changed": 
<img width="726" alt="screen shot 2017-06-29 at 14 15 19" src="https://user-images.githubusercontent.com/27387/27685114-73716662-5cd5-11e7-8835-7ca198a98839.png">

**What did you expect to happen**: I didn't make any changes to the file, so the file shouldn't be marked as "Changed".

**How to reproduce it**: go to any line with `:` and then line number.

**Comment by Chillee** [comment]
This is pretty annoying (I'm assuming you're using neovim integration). When we use neovim as an API for the Ex-commands, we pipe text to the neovim buffer and then back. Piping data back is what I'm assuming is causing the "this file is not saved" thing.

**Comment by brandoncc** [comment]
Would it be feasible to cache the "dirty?" value before piping to neovim, then apply the same value after piping? Or are there some piped neovim events which would actually change the document?

**Comment by Chillee** [comment]
It's very possible that a neovim event would change the document. For example, a find and replace. 

However, now that I've done a lot more neovim integration work in https://github.com/VSCodeVim/Vim/pull/1897, I'm pretty sure i know how to fix this.

**Comment by J-Fields** [comment]
This doesn't seem to be an issue any more. Let me know if you're still experiencing this and I'll re-open.
