### ISSUE TITLE
Goto line number doesn't work

### ISSUE THREAD

**Issue by timshannon** [VSCodeVim/Vim#1889]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**:
Version 1.13.1
Commit 379d2efb5539b09112c793d3d9a413017d736f89
Date 2017-06-14T18:18:03.540Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0
- **VsCodeVim Version**: 0.9.0
- **OS**: Linux / Ubuntu 17.04 64-bit

**What happened**:
`:10`

Nothing happened except the file gets marked as unsaved. Might be the same issue as #1887 but it wasn't clear in that issue whether or not it actually jumped to the proper line.  Mine does not.

**What did you expect to happen**: 
The cursor should move to line 10
**How to reproduce it**:
Open up any file with more than 10 lines, and type `:10`

**Comment by Chillee** [comment]
So it should jump to the proper line.

Just wondering, are you using neovim integration or not? If so, do any of the other Ex-commands work?

**Comment by timshannon** [comment]
Ah, you're right.  I disabled neovim support and it's working now.

I need to read up on nvim support with this extension.  I assumed it would work fine, because nvim is in my path, and was literally coming from nvim to vscode.

**Comment by Chillee** [comment]
@timshannon It should just work if you have nvim in your path, so I'm not completely sure what's going on.

**Comment by timshannon** [comment]
Yeah confirmed nvim is in my path, and it looks live vscode is starting nvim fine in embedded mode

```
ps aux | grep nvim
drc-tsh+ 27994  0.0  0.0  54988 12176 tty2     S+   14:40   0:00 nvim -u NONE -N --embed
drc-tsh+ 28036  0.0  0.0  14244  1080 pts/1    S+   14:40   0:00 grep --color=auto nvim
```

Hm, not sure what the problem is at this point.  I'm running neovim 0.1.7

**Comment by Chillee** [comment]
@timshannon Oh you might need to use neovim 0.2.0. I think we have it in our settings.json, but we should be running our own check.

**Comment by timshannon** [comment]
Ack, looks like neovim 0.2.0 is blocked currently for debian (https://github.com/neovim/neovim/issues/6767)

Thanks, I'm closing this ticket.

**Comment by Chillee** [comment]
Ah that sucks :(

**Comment by brando90** [comment]
so there is no way to goto line using the standard way with vim? e.g. `:10`

**Comment by brando90** [comment]
> Ah that sucks :(

did you ever figure it out?
