### ISSUE TITLE
Selection and change repete not working

### ISSUE THREAD

**Issue by inaki6martinez** [VSCodeVim/Vim#1892]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**:1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Linux

**What happened**:

I have seen that if I make a selection in visual mode and then change it using "c" is not repeated when I use ".". The repetition command just writes, no changes it. 

**What did you expect to happen**: 
I have the name test_variable, is use "v" select "variable", use "c", write "function" and exit from insert mode. If i use "." to repeat in another "variable" it should be changed to "test_function"

**How to reproduce it**:
test_functionvariable

**Comment by iwinmin** [comment]
I had same issue, and the last version is working.

**Comment by Chillee** [comment]
I'm pretty this PR fixes this issue. https://github.com/VSCodeVim/Vim/pull/1890

**Comment by inaki6martinez** [comment]
Thanks!
