### ISSUE TITLE
Stuck in one mode

### ISSUE THREAD

**Issue by con-ssc** [VSCodeVim/Vim#1893]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10 x64

**What happened**:
Sometime while typing or autocompleting the extension is stuck in the current mode and not accepting any inputs. Also the "Toggle mode" from the command palette doesn't respond.
I can't force to reproduce that error but I also cannot resolve it except with reload window.

**What did you expect to happen**: 

**How to reproduce it**:

**Comment by Archsx** [comment]
I got the same problem after I update my vscode , can't insert anything or exit insert mode.so I have to uninstall vim extensions. How can I solve the problem?

**Comment by Chillee** [comment]
@Archsx Can you open up dev tools and tell me what you see?

**Comment by Archsx** [comment]
Sorry.It seems to be nothing wrong with vim. I just add '"git.enabled": false' to the settings.json.and the problem was 
solved.   @Chillee .

**Comment by joemsak** [comment]
Solution by @Archsx seemed to work for a bit but the exact same problem described in this issue came right back in a few minutes.

**Comment by jpoon** [comment]
@joemsak anything in the dev console?

**Comment by joemsak** [comment]
@jpoon thanks for your response. I will check the dev console the next time this happens. It doesn't happen often but once it starts it won't stop happening until I restart my computer

**Comment by joemsak** [comment]
@jpoon it's happening now, here is the full console dev log... does this help?
[-1529618060153.log](https://github.com/VSCodeVim/Vim/files/2125485/-1529618060153.log)

**Comment by joemsak** [comment]
Looks like my pi-hole is blocking a connection (192.138.1.20) but this was happening before I had a pi-hole DNS or even a raspberry pi device at all on my local network

**Comment by joemsak** [comment]
I restarted vs code and it's happening again, here is hopefully a more concise dev console log I'm not sure if the contents will help you or not though

I'm going to have to disable the vim extension until there is a workaround or fix for this :(

[-1529618253532.log](https://github.com/VSCodeVim/Vim/files/2125495/-1529618253532.log)

**Comment by jpoon** [comment]
Did you set up the extension to do verbose logging?

**Comment by joemsak** [comment]
No, sorry, I will now. Sorry, I'm not intimately familiar with the internals of VS code extensions, I'm only here because I'm having the same problem as an end-usre

**Comment by joemsak** [comment]
Sorry, can you help me find that setting?

**Comment by msorens** [comment]
Happened to me today for the first time. Exiting then restarting VSCode seemed to fix it.

**Comment by joemsak** [comment]
Hey this just happened again and even though I set the extension to verbose logging mode there doesn't appear to be anything in the console related to vim

All I can say is it sometimes happens if you try to start inserting at the beginning of an existing line and what you type is opening an HTML tag

For example in a `.vue` file in the `<template>` section I started typing a P tag:

```html
<h4>Program Update email from us</h4>
<You can stop
```

it freezes upon adding the `<` and I can't type anything anywhere in the file or use `esc` to go to normal mode

I was able to reload the extension and type a `p` so it looks like this:

```html
<h4>Program Update email from us</h4>
<pYou can stop
```
but it froze on me again

I can't tell if the console has anything useful but just in case I have attached a screenshot
![screen shot 2018-07-25 at 10 21 59 am](https://user-images.githubusercontent.com/98936/43210397-a0e49792-8ff4-11e8-91f6-558d53bed443.png)

**Comment by joemsak** [comment]
Okay I just uninstalled the extension

"Auto Close Tag" by Jun Han and 2 closely related extensions by the same author, and this problem *appears* to have gone away

**Comment by colepeters** [comment]
I had to do as @joemsak suggested above, but I also had to disable 'Auto Rename Tag' (also by Jun Han).

**Comment by joemsak** [comment]
Btw, I have not had this problem again since my comment above.

**Comment by jpoon** [comment]
Closing as this sounds like an issue with a different extension.

**Comment by hangtwenty** [comment]
[Just wanted to note that I've had this problem with my vim mode sometimes, and I just disabled one of the above extensions and/or another HTML auto close or auto complete extension. Fixed my issue. So if you're having this issue more recently, it could still just be another "disable some extensions" thing. HTML seems to be where it causes a problem the most [for me, anyways].]

**Comment by Archsx** [comment]
Thanks anyway!  I’ve solved my problem as I said before. For me , it is git auto update issue.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Michael Floering<mailto:notifications@github.com>
发送时间: 2020年11月29日 16:03
收件人: VSCodeVim/Vim<mailto:Vim@noreply.github.com>
抄送: Archsx<mailto:suxun1202@live.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [VSCodeVim/Vim] Stuck in one mode (#1893)


[Just wanted to note that I've had this problem with my vim mode sometimes, and I just disabled one of the above extensions and/or another HTML auto close or auto complete extension. Fixed my issue. So if you're having this issue more recently, it could still just be another "disable some extensions" thing. HTML seems to be where it causes a problem the most [for me, anyways].]

―
