### ISSUE TITLE
easy motion mapping key problem

### ISSUE THREAD

**Issue by super0mario** [VSCodeVim/Vim#1894]
when I press 'm', 'e' , it's not looking for e. 
it's doing 'V', 'd'.

"vim.otherModesKeyBindingsNonRecursive": [{
      "before": ["e"],
      "after": ["V", "d"]
    },

    {
      "before": ["m"],
      "after": ["leader", "leader", "s"]
    }
  ],

**Comment by jpoon** [comment]
To keep our issue list sane, I'm closing this issue as it hasn't gotten much traction.
