### ISSUE TITLE
Ctrl-C in Visual Mode should copy to clipboard

### ISSUE THREAD

**Issue by philipmat** [VSCodeVim/Vim#1896]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

The default behavior of gVim on Windows is to copy the selected text when using `Ctrl-C`. Effectively:

    vnoremap <C-C> "+y

Could we please get the same behavior in VSCodeVim?

Note that:
1. `Ctrl-C` behavior in insert mode is correct (takes you out of insert mode)
2. On MacOS `Cmd-C` behaves as intended, that is it copies the selected text to `+`.

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10

**What happened**:

Selected text in visual mode then pressed `Ctrl-C`.

**What did you expect to happen**: 

Selected text to be copied to the `+` register and with `"vim.useSystemClipboard": true` to be in the system clipboard as well.

**How to reproduce it**:

- Select text in visual mode 
- Press `Ctrl-C`
- Execute `:reg` and notice that the previously selected text is not in the `+` register.

**Comment by Compa0** [comment]
Agree, I can't paste to another program when using shortcut of copy or cut.

**Comment by jpoon** [comment]
Apparently fixed as of v0.10.0. Please re-open if that is not the case.

**Comment by yifanchen** [comment]
Anyone is aware of #3229?
