### ISSUE TITLE
Block cursor in command mode

### ISSUE THREAD

**Issue by snowiow** [VSCodeVim/Vim#19]
Hi, I'm interested in implementing this feature and studied the API. I didn't find anything and asked on the official issue tracker of [vscode](https://github.com/Microsoft/vscode/issues/200), but no answer so far. Does someone of you know, how I can get it done, to manipulate the cursor shape?

**Comment by jpoon** [comment]
Related: https://github.com/VSCodeVim/Vim/issues/13

Thanks so much for helping look into this! I couldn't find anything in the vscode documentation either; but you could potentially *fake* it but selecting the current character to mimic the block cursor.

**Comment by snowiow** [comment]
Ok, I was already afraid of something like that. After reading [their approach](https://code.visualstudio.com/docs/extensions/our-approach) it looked like it isn't allowed at all for the moment, because they are going a very conservative way of extension possibilities. Hope they allow more in the future though. So long this fake selection, seems to be the only possibility.

**Comment by adriaanp** [comment]
Would the [DecorationRenderOptions](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationRenderOptions) with cursor property not style the cursor when setting a TextEditorDecorationType on the editor?

**Comment by adriaanp** [comment]
Never mind after a quick test, that is the actual mouse cursor styling

**Comment by drewcassidy** [comment]
Excuse my lack of experience with javascript and web-based stuff, but didnt someone say in #18 it was possible to render things directly to the canvas? would that work to draw the block cursor?

**Comment by markrendle** [comment]
Looks like the best way to do this right now is to define a single-character range in the textEditor with the backgroundColor style set, and move it with the cursor.

**Comment by jpoon** [comment]
Also just tried setting mimicking the block as a selection:

```
                let position = new vscode.Position(0, 0);
		let selection = new vscode.Selection(position, position.translate(0, 1));
		vscode.window.activeTextEditor.selection = selection ;
```

It sorta works but you still see the cursor, so....suboptimal -- css styling may be the way to go.

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/pull/102
