### ISSUE TITLE
BUG REPORT - scrolling with <C-u> / <C-d> does not move cursor as expected.

### ISSUE THREAD

**Issue by AntonOsika** [VSCodeVim/Vim#1900]
**Environment**:

- **VSCode Version**: 1.13
- **VsCodeVim Version**: 0.9.0
- **OS**: macOS 10.12.5

**What happened**:
Line 1 was visible, the cursor was on line 50. I pressed `<C-u>` CTRL-u to scroll up. 
Nothing happened (the cursor stayed at the bottom of the screen).

**What did you expect to happen**: 
The cursor to move up towards line 1 as it does in vim!

**How to reproduce it**:
Go to the beginning of the file, move the cursor to line 50, and press `<C-u>` (nothing happens).

**Comment by Chillee** [comment]
Related to https://github.com/VSCodeVim/Vim/issues/1348. I'm going to close this issue in favor of that one (it's a lot more popular and older).

Thanks!
