### ISSUE TITLE
[FEATURE REQUEST] Multi-line yank

### ISSUE THREAD

**Issue by ecbrodie** [VSCodeVim/Vim#1902]
**FEATURE REQUEST**

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: macOS 10.12.5

**What happened**:

I tried to yank a range of lines like I normally would in VIM:

```
:10,20y
```

**What did you expect to happen**: Lines are yanked to the paste buffer and I can paste it using `p`.

**How to reproduce it**: Run the yank command listed above. The lines will not be added to the paste buffer. You can check this through the `p` command or even checking `:reg`.

The workaround is to yank through a visual-mode selection or copy/pasting with the mouse. Definitely annoying to use the VIM emulator without this feature, though.

**Comment by obibring** [comment]
Would really like to see this feature. It's a huge productivity boost.

**Comment by kdenz** [comment]
Would love to have it too!

**Comment by minezinger** [comment]
I really hope to have the feature, block-copy of marked area
> :'a,'by

**Comment by jspking** [comment]
This is one of my favorite combo set. Whenever I need to copy a range of code, I have to use mouse. Please add this combo.

**Comment by web-display** [comment]
for example 3,17y, you can do this: 17-3+1=15.  step one: <y15y>. step two: <p>. done!!!

**Comment by vtvh** [comment]
With NeoVim enable you should be able to execute that. 
`"vim.enableNeovim": true`
https://i.imgur.com/tT3xrVQ.png
https://i.imgur.com/6hBJVt6.png

**Comment by J-Fields** [comment]
Implemented in 05dd48b6adc992ede8ff3bb5b2a45ca7955ccde6, will be in next release
