### ISSUE TITLE
[BUG] Doesn't let me edit a file without extension

### ISSUE THREAD

**Issue by thinkxl** [VSCodeVim/Vim#1903]
**Environment**:

- **VSCode Version**: 1.13.1 (1.13.1)
- **VsCodeVim Version**: 0.9.0
- **OS**: macOS Sierra 10.12.5

**What happened**:

I opened this file https://github.com/thinkxl/html/blob/master/source and couldn't edit it.

I disabled extension by extension to find which one was the culprit.

Here is a gif of the behavior:

![](https://imgsthinkxl.s3-us-west-1.amazonaws.com/SgWpDJ12.gif)

The weird thing is that this is happening only on this file.

**Comment by Chillee** [comment]
That's bizarre... I don't get the same issues when pasting this file into a document and then editing it...

I doubt it's an issue with the file extension though. I can edit files without file extension just fine.

I guess it's a similar cause to this? https://github.com/VSCodeVim/Vim/issues/1461

**Comment by thinkxl** [comment]
@Chillee I think so, I had to use Vim directly to edit it, when I opened it, it stopped for like 30 seconds before I could type anything.

**Comment by jpoon** [comment]
Just tried opening the file in code 1.19.3 and it opened fine. One thing I noticed is there was a lag when inputting text which is the same as the bug reported here: https://github.com/VSCodeVim/Vim/issues/2216. 

I'm going to close this issue as it seems to have fixed itself with at least Code 1.19.3 and VsCodeVim 0.10.13.
