### ISSUE TITLE
Visual mode indents can't be repeated with .

### ISSUE THREAD

**Issue by jamesgecko** [VSCodeVim/Vim#1905]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: macOS 10.12.5

**What happened**:

I selected some text and indented it. When I tried to repeat the indent with `.`, nothing happened.
Key sequence: `vw>...`

This doesn't work when selecting multiple lines either; the `>` indents the selection, but `.` doesn't repeat it.
Key sequence: `vjj>...`

**What did you expect to happen**: 

After the initial indent action, pressing `.` should continue to indent line with selected text.

Note that using full line selection with `V` _does_ behave as expected.
`Vw>...` and `Vjj>...` both work fine.

**Comment by xconverge** [comment]
This was just fixed and the issue closed, it will be in the next release

#1886
