### ISSUE TITLE
Undo/Redo updates UI multiple times per change.

### ISSUE THREAD

**Issue by jordwalke** [VSCodeVim/Vim#1906]
When doing undo/redo, the changes are replayed line by line over several frames. There should be a single screen update per undo/redo, as if it happens with a single edit to the document, not multiple little edits very fast.

**Comment by Chillee** [comment]
@jordwalke We're aware of this issue, and there's several issues tracking this already. https://github.com/VSCodeVim/Vim/issues/1714 and https://github.com/VSCodeVim/Vim/issues/1727 being the most relevant ones.

It's likely that we'll end up fixing this through leveraging neovim integration.

Thanks!

**Comment by jordwalke** [comment]
Oh wow, if you can use NeoVim's undo tree!

(Sorry, I searched for existing issues and didn't find those two existing ones).

**Comment by Chillee** [comment]
Yep! That's the hope! Use Neovim undo tree, use neovim plugins, use neovim everything.

**Comment by Chillee** [comment]
https://github.com/VSCodeVim/Vim/pull/1897 is the pr you want to follow for the progress on that.
