### ISSUE TITLE
Using the `=` binding wedges the editor

### ISSUE THREAD

**Issue by raggi** [VSCodeVim/Vim#1907]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

**Environment**:

- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:13:05.928Z)
- OS Version: Darwin x64 16.6.0
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|dart-code|DanTup|1.4.2|
|vscode-markdownlint|DavidAnson|0.9.1|
|xml|DotJoshJohnson|1.9.2|
|language-gas-x86|basdp|0.0.1|
|python|donjayamanne|0.6.7|
|vscode-rust|kalitaalexey|0.4.2|
|Go|lukehoban|0.6.62|
|vscode-todo-parser|minhthai|1.8.10|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.12.0|
|Ruby|rebornix|0.12.1|
|vim|vscodevim|0.9.0|
|clang-format|xaver|1.5.0|;

**What happened**:

In a document, I press = while in normal mode to format the current line (or selection). Instead of formatting anything, the editor becomes locked in the `=` mode and no longer responds to other commands. The mode seems to be in-escapable.

**What did you expect to happen**: 

The line is formatted.

**How to reproduce it**:

Open a document. Move to a non-empty line. Press `=`.

**Comment by Chillee** [comment]
Could you try running the format document command?

**Comment by raggi** [comment]
Running format document and/or format selection after does not fix the issue, it's still wedged in `=` mode. Nothing seems to release it from this state. Toggling vim mode off and back on removes the indication of the `=` from the bottom left, but the editor is still wedged, accepting no input in vim mode.

**Comment by Chillee** [comment]
I mean, what happens when running format selection regularly. Does it do what you want?

**Comment by raggi** [comment]
Yes it does.

**Comment by raggi** [comment]
Is there any way you can recommend that I can temporarily disable this feature/key mapping? I have muscle memory when I'm on my constrained laptop keyboard that I am having a hard time training out, and having to reload the window means the cpp language server sets my legs on fire.

**Comment by xconverge** [comment]
```
"vim.otherModesKeyBindingsNonRecursive": [
    {
        "before": ["="],
        "after": []
    }
],
```

**Comment by raggi** [comment]
I was mistaken that this was a multi-language issue - it's a problem specific to two extensions. I'll open bugs with them.

**Comment by xconverge** [comment]
Thanks @raggi feel free to reopen this or other issues if anything else comes up!
