### ISSUE TITLE
:u undid multiple steps at once. neovim did not help.

### ISSUE THREAD

**Issue by qvks** [VSCodeVim/Vim#1915]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**: Windows

**What happened**: All changes since last save undone together when :u is pressed. Same issue when enabling neovim. 

**What did you expect to happen**: One last step being undone

**How to reproduce it**: Make multiple changes and try to undo

**Comment by Chillee** [comment]
`:u` in command mode and not normal mode?

**Comment by qvks** [comment]
Just figured out this was due to another conflicting plugin. Sorry about that.
