### ISSUE TITLE
A problem in "ctrl + [" shortcut

### ISSUE THREAD

**Issue by Krchi** [VSCodeVim/Vim#1916]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: lastest
- **VsCodeVim Version**: lastest
- **OS**: 10.10

**What happened**:
when use InputMethod's panel, the fist **"ctrl + ["** close the panel, and also back to normal mode, but it works well when use **<**esc**>**

**Comment by Chillee** [comment]
So you're saying that you want `ctrl+[` to close the panel and go back to normal code after one press?

**Comment by Krchi** [comment]
@Chillee 
just like esc, only close the panel, but now it close the panel and back to normal

**Comment by MaxfieldWalker** [comment]
@Krchi What is "InputMethod's panel"?

**Comment by Chillee** [comment]
@MaxfieldWalker I think it refers to inputting foreign characters.

**Comment by MaxfieldWalker** [comment]
@Chillee I see!

**Comment by Krchi** [comment]
@MaxfieldWalker Thank you, i use `squirrel`, 
![Uploading 9月-03-2017 14-27-52.gif…]()
at first, i use `esc`, then i use `ctrl [`, you can see that the action makes vsc back to normal at  once.

**Comment by MaxfieldWalker** [comment]
@Krchi OK. What happens when you do the same thing on another text editor like TextEdit.app?

I think the problem is whether `ctrl + [` is handled or ignored by your ime.

**Comment by Krchi** [comment]
@MaxfieldWalker i has this thinking too, but it's ok in idea with ideavim

**Comment by MaxfieldWalker** [comment]
@Krchi Unfortunately, I can't find what the problem is. However, I will keep you informed.

**Comment by Krchi** [comment]
@MaxfieldWalker May be i found what wrong with it, 
`119     - { when: composing, accept: Control+[, send: Escape }`
It's one line in ime's configure file, ime send `esc` and vsc can't ignore real type.

**Comment by MaxfieldWalker** [comment]
@Krchi That makes sense. So, this behavior is not because of the extension but your IME configuration, right?

**Comment by Krchi** [comment]
@MaxfieldWalker yes, but i think when enter special language, the software couldn't act with typed key. Maybe i should reflect in vsc's page.
