### ISSUE TITLE
"Format selection" formats the whole document

### ISSUE THREAD

**Issue by mklinga** [VSCodeVim/Vim#1917]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report 

**Environment**:

- **VSCode Version**:

Version 1.13.1 (1.13.1)

- **VsCodeVim Version**: 

0.9.0

- **OS**: 

MacOS Sierra

**What happened**:

Selecting some lines with `Shift-V` and pressing `=` reformats the whole document instead of just the selected lines.

**What did you expect to happen**: 

Expected the command to *only* format the lines selected.

**How to reproduce it**:

Select some lines with `Shift-V` and press `=`.

**Comment by Chillee** [comment]
Could you try it in different languages?

**Comment by mklinga** [comment]
Hey, this seemed to be due to having `Semistandard Format` plugin installed. Disabled that and the "format selection" now works perfectly.

Thanks for the wonderful plugin!
