### ISSUE TITLE
Backspace in search popup doesn't exit search mode

### ISSUE THREAD

**Issue by viraptor** [VSCodeVim/Vim#1921]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.0
- **VsCodeVim Version**: 0.9.0
- **OS**: MacOS

**What happened**:

Started search and wanted to exit out of that mode the same way vi allows. (deleting the search terms and the initial `/`)

**What did you expect to happen**: 

Search bar to disappear and getting back to normal mode. (vim behaviour)

**How to reproduce it**:

`/xx<backspace><backspace><backspace>`

**Comment by J-Fields** [comment]
This was fixed a little while ago.
