### ISSUE TITLE
`ci>` (Change in angular brackets) does not work

### ISSUE THREAD

**Issue by mqudsi** [VSCodeVim/Vim#1925]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

This is probably more of a feature request than a bug report, but depending on how you look at missing "standard" VIM actions, it could be seen differently.

The "change in" command in VSCodeVim does not currently support `>` as a target, i.e. with the cursor in the middle of the word "target" in the text below:

    <element>target</element>

Typing `ci>` does not cause the text "target" to be removed and enter insert mode.

**Comment by Chillee** [comment]
I don't think this is a standard vim feature (at least it doesn't work on my version of vim).

I think you're looking for the tag target, ie: `cit`. That does what you're trying to do.

**Comment by xconverge** [comment]
Closing due to @Chillee comment, feel free to reopen if you still have an issue with this!

**Comment by mqudsi** [comment]
I'm sorry, I confused `ci>` to change `<something>` with `ci>` to change `>something<`

The former works as expected.
