### ISSUE TITLE
Cursor location after exiting insert mode with Esc mapping

### ISSUE THREAD

**Issue by lnicola** [VSCodeVim/Vim#1927]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: `1.14.0`
- **VsCodeVim Version**:  `0.9.0`
- **OS**: Windows 10

**What happened**:
With the sample mapping of `jj` to `<Esc>`, cursor location after leaving insert mode with `jj` isn't right. Type some text and press `ajj` or `ijj`, noting the cursor location; compare with `<Esc>`.

**What did you expect to happen**: 
Same behaviour as `vim`, that is, the cursor should should remain on the previous position after `ajj` and move left after `ijj`. `vim` inserts the first `j`, but doesn't move the cursor until the timeout.

**How to reproduce it**:
`ihello<Esc>hhajj`

**Comment by slavugan** [comment]
yes this behavior always make my fingers confused

**Comment by J-Fields** [comment]
I believe this is fixed (just tried it out and couldn't reproduce). Let me know if you're still experiencing this.

**Comment by lnicola** [comment]
@J-Fields yup, that's true, thanks!
