### ISSUE TITLE
disable auto change to normal mode after I selected something in insert mode ?

### ISSUE THREAD

**Issue by mengxingshike2012** [VSCodeVim/Vim#1929]
I'd like to set  config of  startInInsertMode to true; but after I do some selection, it will auto change to vim normal mode again, which I dont' want. I think there should be a config option, but I failed to find out. Would anyone like to help, thanks.

**Comment by mcpeng** [comment]
Yeah, we need a config option for that, sometimes I use mouse to make a selection for deleting... 🤔

**Comment by Chillee** [comment]
This is a duplicate of https://github.com/VSCodeVim/Vim/issues/1871

I'll try to push a release sometime soon.
