### ISSUE TITLE
Need yank and paste command.  Thanks.

### ISSUE THREAD

**Issue by rockus123** [VSCodeVim/Vim#193]
yy - yank (copy) a line
2yy - yank 2 lines
y = yank = copy
Press P to paste before the cursor, or p to paste after.

**Comment by jpoon** [comment]
Thanks for filing this issue! We're working on it. In the meantime, I'm going to close this issue as a duplicate in favor of https://github.com/VSCodeVim/Vim/issues/161 as that was filed first :smile:

**Comment by arcseldon** [comment]
Show-stopper.
