### ISSUE TITLE
Cursor moving bugs

### ISSUE THREAD

**Issue by Compa0** [VSCodeVim/Vim#1930]
In normal mode, "h", "l" , left arrow, and right arrow don't move the cursor across lines.

Also, when one line is too long, the line will be displayed into multiple "lines", however, "j", "k" , up arrow, and down arrow don't work on these "lines" but directly jump to another line with line number.

When Vim is disabled, these issues are gone.

If anyone meet the same problem, please leave a comment, thank you for your help.

**Comment by xconverge** [comment]
this is standard vim behavior...

for the 2nd "issue" you are looking for gj and gk which navigate wrapped lines

**Comment by Compa0** [comment]
Alright, thank you very much.
