### ISSUE TITLE
Visual Surround mode adding spaces with brackets

### ISSUE THREAD

**Issue by wmaurer** [VSCodeVim/Vim#1934]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT
In visual surround mode, when surrounding with brackets spaces are added.

**Environment**:
- **VSCode Version**: 1.14.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10

I have the following text:
foo bar

Cursor is on 'f'

**Exact keys you pressed**:
v2eS(

**What happened**:
( foo bar )

**What did you expect to happen**: 
(foo bar)

Strangely, this only happens when surrounding with brackets ({[ but not with " or '.

**Comment by xconverge** [comment]
This  is how surround works. if you do ([{ it adds a space, if you do )}] it does not. So what you want to do is ```v2eS)```

https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L125

```
"If either ), }, ], or > is used, the text is wrapped in the appropriate pair
of characters.  Similar behavior can be found with (, {, and [ (but not <),
which append an additional space to the inside.  Like with the targets above,
b, B, r, and a are aliases for ), }, ], and >. "
```

 Feel free to reopen if I misunderstood

**Comment by wmaurer** [comment]
Aha! Thanks very much!
And thanks for the link to the vim-surround docs.
VSCodeVim is awesome, thanks ;-)
