### ISSUE TITLE
Collapsed block was expanded when press J on the first line.

### ISSUE THREAD

**Issue by lilei** [VSCodeVim/Vim#1936]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 BUG REPORT

**Environment**:

- **VSCode Version**:   1.14.1
- **VsCodeVim Version**:  0.9.0
- **OS**:  windows 10

**What happened**:

I collapse a code block from line 11 to line 20.
and  on the line 11 ,I press J or arrow down
then the code block was expaned.
**What did you expect to happen**: 
The code block keep collapsed and the cursor jump to line 21
**How to reproduce it**:
1. Collapse a code block
2. On the vim mode,press J on when the cursor was on the first line of the collapsed block.

**Comment by Chillee** [comment]
Unluckily, I doubt this is something we can change. Folds are largely outside of our control, and even our current fix for moving across folds is unbelievably hackish.

**Comment by danawoodman** [comment]
According to https://github.com/Microsoft/vscode/issues/16858 they're saying it is the extension's issue. What would need to happen to get it to work?

**Comment by danawoodman** [comment]
Looks like this is fixed in https://github.com/VSCodeVim/Vim/pull/1552? Add `"vim.foldfix": true` to your `settings.json` fixes it for me

**Comment by Chillee** [comment]
@danawoodman ah I thought he meant `<shift-j>`. That actually does work properly. If so, this is a duplicate.

I haven't closed the other relevant fold issue as our current solution is unbelievably hacky (and not in a good way).

**Comment by transtone** [comment]
you need `gj` to replace `j`. 

this tips is in the README file's `Key remapping` chapter.

**Comment by drahnieR** [comment]
> `DO NOT` use vim.foldfix.
> 
> you need `gj` to replace `j`.
> 
> this tips is in the [README](https://github.com/VSCodeVim/Vim/blob/master/README.md) file's `Key remapping` chapter.

using this mapping, commands like 100j becomes nightmare...
`vim.foldfix` works faster but still far away from the original setting.

@Chillee ideas on reopening this issue?
