### ISSUE TITLE
Substitute command with escaped `/` in replacement string doesn't work as expected

### ISSUE THREAD

**Issue by potmpark** [VSCodeVim/Vim#1937]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.0
- **VsCodeVim Version**: 0.9.0
- **OS**: Linux(4.11.10-1-MANJARO)
- **configuration**:
 ` "vim.enableNeovim": false,`

**What happened**:
Try to add the close tag `</td>` to a line with content `<td>some data` using substitute command `s/$/<\/td>`,
the result is `<td>some data<td>`

**What did you expect to happen**: 
The result should be `<td>some data</td>`
**How to reproduce it**:
1. Have a line with `<td>some data` as its content, and move the cursor to it
2. In normal mode, press `:` to open the command line
3. input `s/$/<\/td>`, press `Enter`

**Note**: In vim or in vscode with neovim enabled, this command all work as expected.

**Comment by xconverge** [comment]
FYI we are starting to slow down on fixing issues/implementing commands WITHOUT neovim.

If you install neovim and enable the flag, this and many other commands will work perfectly.

Will leave the issue open in case someone wants to fix it, but wanted to be honest with you and get you up and running if this is a large pain point for you or your workflow!

**Comment by intijk** [comment]
> If you install neovim and enable the flag, this and many other commands will work perfectly.

Could you @xconverge  give me more detail of the "flag"?

**Comment by prmichaelsen** [comment]
It sounds like devs just want everyone to get on neovim

**Comment by jpoon** [comment]
@intijk https://github.com/VSCodeVim/Vim#neovim-integration

@prmichaelsen why re-write the wheel especially as neovim does a fairly decent job.
