### ISSUE TITLE
Surround: Keep HTML attributes when changing tags

### ISSUE THREAD

**Issue by wmaurer** [VSCodeVim/Vim#1938]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

Feature request:
I'd like to be able to use surround to change a tag, but keeping the existing attributes.
This functionality exists in the official vim-surround:
https://stackoverflow.com/a/31098722/664533
https://github.com/tpope/vim-surround/pull/131

e.g.

`<h2 class="foo>b*ar</h2>`

`cstth3>` - changes h2 to h3, removes attributes - current behaviour
`cstth3` ENTER - changes h2 to h3, keeps class attribute

Apart from that, VSCodeVim surround is great!

**Comment by knpwrs** [comment]
Asciinema recording of the desired behavior: https://asciinema.org/a/miZYWNYNIYFQTcDDifXgMtBW6

**Comment by dum3ng** [comment]
I think this is a very useful feature when editing html and jsx code. 
But after years this has not been added. 
Hope you can add this feature someday.

**Comment by esetnik** [comment]
I would love this too. In my opinion tag replacement should by default preserve attributes. It's rare for me that I want to replace tags and simultaneously wipe the attributes.
