### ISSUE TITLE
Hangs / freezes / unresponsive when repeating keys (like jj)

### ISSUE THREAD

**Issue by silesky** [VSCodeVim/Vim#1942]
## BUG REPORT

**Environment**:
- OSX
- VSCode Version 1.14.2 (1.14.2)
- vscodevim v0.9.0
- neovim integration turned off

**What happened**:
- When I repeat keys, VSCodeVIM will freeze up, making it impossible to type or enter any commands until I disable to extension. Seems very similar to https://github.com/VSCodeVim/Vim/issues/729.

**Exact keys you pressed**:
- jj

**What did you expect to happen**: 
- expected the editor to actual respond to input

**How to reproduce it**:
- preference -> keyboard and turn 'key repeat' to fast and 'delay until repeat to short'
- repeat jj

**Comment by Chillee** [comment]
Could you open up dev tools when this happens and report what you see?

**Comment by silesky** [comment]
I'm closing this because I was unable to reproduce this.
here's some info about the problem
 - it was in the middle of a very hairy merge conflict
 - I had jj bound to 'go to normal mode'
if it reoccurs, I will re-open this and provide more debugging info.
