### ISSUE TITLE
vim.substituteGlobalFlag is not seen as setting

### ISSUE THREAD

**Issue by Glamhoth** [VSCodeVim/Vim#1944]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.2
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10 Pro x64

**What happened**: VsCode sees "vim.substituteGlobalFlag": true as unknown configuration setting.

**What did you expect to happen**: I expect this setting to work as it's written in docs.

**How to reproduce it**: Add this line to settings.json file.

**Comment by philipmat** [comment]
I think it's because there hasn't been a release which contains the code for `substituteGlobalFlag`.

PR #1909 was merged roughly around 7/10, but the latest version, v0.9.0, was released 6/24.

**Comment by Glamhoth** [comment]
Okay, thanks for the answer!
