### ISSUE TITLE
Visual Block Mode - strange behavior with $

### ISSUE THREAD

**Issue by erm0l0v** [VSCodeVim/Vim#1945]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.2
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 8.1 x64

**How to reproduce it**:
Given text (Cursor on letter `D`):
```
Dog
Angry Bird
Cat
```
When pressed keys: `Ctrl+v` `$` `2` `j` `A` `;` `Esc`

**What happened**:
Then got text:
```
Dog;
Angr;y Bird
Cat;
```

**What did you expect to happen**: 
Then got text:
```
Dog;
Angry Bird;
Cat;
```

**Comment by Chillee** [comment]
This seems to be an issue with how we're handling block selection in visual block. We need to take into account desiredColumn for every column we're iterating down.

**Comment by erm0l0v** [comment]
Yes, in original vim if user moved to end of the line using key `$` visual block mod  select each lines till end.
