### ISSUE TITLE
Completion error with multiple cursor

### ISSUE THREAD

**Issue by papey** [VSCodeVim/Vim#1946]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.2 - cb82febafda0c8c199b9201ad274e25d9a76874e
- **VsCodeVim Version**: v0.9.0 Hundredth Hazelnut (Jun 24, 2017)
- **OS**: GNU/Linux

**What happened**:

Bug/error when completing go code

`for<tab>`

gives me : 

```
for index := 0; index < count; index++ {
	
}
```

with multiple cursors around "index"

pressing "backspace", to change value of "index" gives me : 

```
for ex < count; index++ {
	
}
```
**What did you expect to happen**: 

changing the index value to something I want. If I put VSCodeVim off, everything is ok.

**How to reproduce it**:

Ensure Plugings : 

1. go - 0.6.63 - 26th July, 2017
2. VSCodeVim
3. Open a .go file
4. Expand a "basic" for snippet

I'm not sure if it's related to VSCodeVim or go snippets. Again, if I turn VSCodeVim off, everything is ok.

**Comment by Chillee** [comment]
I believe one workaround for this currently is by using `<ctrl-backspace>` instead of backspace to delete.

**Comment by Hariama** [comment]
Has there been any update on this issue? Multiple dupes have been closed, but the sole solution as of yet still seems to be the workaround of using `<del>` or `<ctrl-backspace>`.

**Comment by crown3** [comment]
I can reproduce the above problem, the above temporary solution is also valid.

**Comment by jory18** [comment]
I can reproduce the problem too. Currently on Version 1.40.2
