### ISSUE TITLE
Repeat operator skips the delete part of commands such as cw

### ISSUE THREAD

**Issue by realh** [VSCodeVim/Vim#1949]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**: GNOME 3

- **VSCode Version**: 1.14.2 (Commit cb82febafda0c8c199b9201ad274e25d9a76874e)
- **VsCodeVim Version**: 0.9.0
- **OS**:  Debian Linux unstable (amd64)

**What happened**:

The repeat operator (`.`) doesn't work as expected when repeating an operation which is a compound of a deletion and insertion such as the `c` or  `s` operations. For example, with the cursor at the start of a word, type `cw`, insert some text, `Esc` back to normal mode, then move the cursor to another word and press `.`. VSCodeVim repeats the insertion, but fails to delete the word first.

**Comment by Chillee** [comment]
I can't replicate this.

It appears to work fine for me.

`|foo bar`
`cwfun<Esc>w.` results in `fun fun` for me

**Comment by realh** [comment]
Strange, it's working properly for me now too. I'll let you know if I find a way to reproduce it.

**Comment by Chillee** [comment]
Alright I'm going to close this issue for now. Please reopen it if you find a repro case :)
