### ISSUE TITLE
{counter}$ is not work

### ISSUE THREAD

**Issue by metasong** [VSCodeVim/Vim#1950]
the counter value is overlooked

**Comment by Chillee** [comment]
I don't think `<count>$` does anything.

**Comment by metasong** [comment]
$  or <End>		To the end of the line.  When a count is given also go
			[count - 1] lines downward |inclusive|.
			In Visual mode the cursor goes to just after the last
			character in the line.
			When 'virtualedit' is active, "$" may move the cursor
			back from past the end of the line to the last
			character in the line.


but in our plugin it's always in the end of the same line

**Comment by Chillee** [comment]
@metasong Sorry, you are correct. This is a valid feature request.
