### ISSUE TITLE
Selecting text backwards in insert mode only selects first character

### ISSUE THREAD

**Issue by rohitpaulk** [VSCodeVim/Vim#1951]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**:

- **VSCode Version**: 1.14.2
- **VsCodeVim Version**: 0.9.0
- **OS**: macOS Sierra

**How to reproduce it**:

- Enter insert mode
- Type out a few characters
- Select those characters, by pressing `shift + left arrow` multiple times. 
- Copy using `cmd + c`
- Paste elsewhere using `cmd + v`.

![vimselect](https://user-images.githubusercontent.com/3893573/28972083-f866541c-794b-11e7-9039-297a228cd794.gif)

**What happened**:

- With the vim extension active, only the first character of the selection is copied. 
- Without the vim extension active, the entire selection is copied.

**What did you expect to happen**: 

I'd expect the entire selection to be copied, just like when the vim extension isn't active.

**Comment by chunkeater** [comment]
Same issue on both Mac and Windows since months ago.. I need to retrain my workflow to not to backwards copy, which is pretty disruptive.  Any workarounds (without uninstalling VscodeVim) will be helpful, or information on the source code portions to be fixed and I could help. thank you! :)

**Comment by tomasiser** [comment]
The issue was fixed in insert mode, but not in normal mode. Should a new issue be made about it?

**Comment by flowkraD** [comment]
Is this still a bug or is it fixed now? If it's not fixed, I'll love to work on this!
