### ISSUE TITLE
"L" scrolls down a line unexpectedly

### ISSUE THREAD

**Issue by Liquidmantis** [VSCodeVim/Vim#1956]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Environment**:

- **VSCode Version**: 1.15.0-insider
- **VsCodeVim Version**: 0.9.0
- **OS**: macOS 10.12.6

**What happened**:  Pressing L jumps to the bottom but also scrolls a line, and can be repeated.

**What did you expect to happen**:  To jump to the bottom of the screen with no scrolling.

**How to reproduce it**:  Press L.  Even when already at the bottom you can continue to scroll with repeated presses of L.

**Comment by Chillee** [comment]
@Liquidmantis Sorry I didn't reply to your slack comment in a timely fashion, but this is actually a duplicate of this issue: https://github.com/VSCodeVim/Vim/issues/1393

**Comment by Liquidmantis** [comment]
@Chillee No worries at all!  I just figured I'd throw out an issue so it didn't get lost.   Sorry for creating a dupe!  I'll just close this one and +1 the other.
