### ISSUE TITLE
ci< "plugin" disabled by default?

### ISSUE THREAD

**Issue by xlaech** [VSCodeVim/Vim#1959]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
**Environment**:
- **VSCode Version**: 1.14.2
- **VsCodeVim Version**:  0.9.0
- **OS**: Windows 10

**What happened**:

In:      `<div>some| awesome text</div>`
Press: ci<

**What did you expect to happen**: 

As it worked earlier:
`<div>|</div>`

I rememeber that this was the implemenation of a vim addon. Did we remove it?

**Comment by Chillee** [comment]
`ci<` has never worked in that way. You're looking for `cit` I believe.

Reopen the issue if that's not what you want.
