### ISSUE TITLE
"/" not searching current file but it searches "project files"

### ISSUE THREAD

**Issue by raghav135** [VSCodeVim/Vim#196]
Hi,

Currently when i press "/" in escape mode, it does "search in all files" instead of search in "current file".
Can you kindly look into this?

Kind Regards,
Srinivasa Raghavan.

**Comment by tnngo2** [comment]
It is also the most annoying issue to me.
I've just created a pull to fix it.
https://github.com/VSCodeVim/Vim/pull/205

Hope it will be merged to master soon.

**Comment by raghav135** [comment]
+1

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/pull/205. Will push out a new release soon.
