### ISSUE TITLE
Navigation keys problem with certain file

### ISSUE THREAD

**Issue by kraml** [VSCodeVim/Vim#1965]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Environment**:

- **VSCode Version**: 1.14.2 x86, 1.15 x86, 1.15 x64
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10 1703, x64

**What happened**:
When [this file](http://pci-ids.ucw.cz/v2.2/pci.ids) is opened, very possibly the movement key hjklwb etc. and even arrow key no longer works, so can't navigate in the file. There is a small chance that after opened this file the hjkl key still works, but after done a / search, the problem would happen almost 100% of the time.

When the problem occurred, VCCode is still responsive, other functions such as UI, command palette, extension window, open new file etc. all works without noticeable problem or slow down. No high CPU utilization observed by Process Explorer.

Another abnormality observed is after closed VSCode it does not fully exist cleanly, there are extension processes left running. VSCode could exist cleanly only if VSCode was started without ever opening that file. Once it has opened the file, it cannot exist cleanly.

**What did you expect to happen**: movement key works normally.

**How to reproduce it**:
Just open [this file](http://pci-ids.ucw.cz/v2.2/pci.ids).

**Comment by jpoon** [comment]
Can't repro on VSCodeVim v0.10.1 and Code 1.17.1

**Comment by kraml** [comment]
Yes it works for me too now. Probably it was due to old Code version or extension conflict during that time. Can be closed now.
