### ISSUE TITLE
<Esc> is recursively mapped for "vim.insertModeKeyBindingsNonRecursive"

### ISSUE THREAD

**Issue by FallenMax** [VSCodeVim/Vim#1968]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT 

**Environment**:

- **VSCode Version**: 1.15.0 
- **VsCodeVim Version**: 0.9.0
- **OS**: macOS Sierra 10.12.6

**What happened**:

`<Esc>` is infinitely mapped for setting  "vim.insertModeKeyBindingsNonRecursive"

**What did you expect to happen**: 

`<Esc>` is mapped only once for setting "vim.insertModeKeyBindingsNonRecursive"

**How to reproduce it**:

1. Open "user setting", add:
```
 "vim.insertModeKeyBindingsNonRecursive": [
    {
      "before": ["<Esc>"],
      "after": ["x","<Esc>"]   // <- 'x' is arbitrary character
    }]
```
2. Open a blank document
  - press `i` (to enter `Insert Mode`)
  - press `a`, `<Esc>`
      + Expected: 'ax' (then exits to Normal Mode)
      + Actual: 'axxxxxxxxxx...'  (keep inputing 'x, not exiting, need close file to cut it off )
  - Note:
      + VSCodeVim is likely to crash after doing this

![aa](https://user-images.githubusercontent.com/2012170/29375484-c53a2e3c-827a-11e7-9655-c8d9a2263a7f.gif)

**Comment by rosshambrick** [comment]
A work-around for this:
```
    "vim.insertModeKeyBindingsNonRecursive": [
        {
            "before": [ "<Esc>" ],
            "after": [ "x", "ctrl+[" ]
        }
     ],
```
if you also use `ctrl+[` you could also add a complementary mapping.

**Comment by jpoon** [comment]
There was a regression with this merge commit way back when: https://github.com/VSCodeVim/Vim/commit/d09722bacde1ea227fc757cf8646226ad39d6454#diff-1a1dc9b353e552d9f1994be988780695. Planning to fix it with this PR https://github.com/VSCodeVim/Vim/pull/2208
