### ISSUE TITLE
[Question] Modify C-e and C-y commands?

### ISSUE THREAD

**Issue by nwaywood** [VSCodeVim/Vim#1971]
I have the following in my `.vimrc`:

```vimscript
" scroll the viewport faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
```

Is it possible to emulate this behavior is VSCode? I have successfully emulated this behavior in Atom by defining custom functions in the init script. But afaik there is nothing like that in VSCode.

Thanks in advance

**Comment by Chillee** [comment]
@nwaywood Have you taken a look at our remapping functionality? I see no reason why it wouldn't work.

**Comment by nwaywood** [comment]
@Chillee Hi yes you are right! For some reason I assumed this wouldn't work but it does

```
 // scroll the viewport faster
        {
            "before": ["<C-e>"],
            "after": ["3", "<C-e>"]
        },
        {
            "before": ["<C-y>"],
            "after": ["3", "<C-y>"]
        },
```

Thanks :)
