### ISSUE TITLE
Key binding to insert single character

### ISSUE THREAD

**Issue by zakandrewking** [VSCodeVim/Vim#1972]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

I would like to create a key binding to insert a single character. The solution in vim is described here:

http://vim.wikia.com/wiki/Insert_a_single_character

Is this currently possible? It requires more logic than the current key bindings allow -- unless I missed some features. Thanks!

**Comment by jpoon** [comment]
Should be do-able using normalModeKeyBindings https://github.com/VSCodeVim/Vim#quick-example
