### ISSUE TITLE
pane switching is broken in newest vscode-insiders

### ISSUE THREAD

**Issue by danwalterlink** [VSCodeVim/Vim#1973]
BUG REPORT

**Environment**:
newest code-insider-build [1.16.0]

- **VSCode Version**:code-insiders 1.16.0
- **VsCodeVim Version**: 0.9.0
- **OS**: WIN-10E 1511: OS_BUILD 10586.1007

**What happened**:

pane switching breaks extension functionality on new pane:

when working in split-window view, switching the pane only switches the cursor display. the line-highlighting and cursor movement, as well as any input remains within the old pane.

(also the extension host terminates unexpectedly... but I can't reproduce it consistently. It just randomly happens on startup. Tested the extensions though; I'm sure it's this one.)

 Obviously expected to switch panes, as it did all previous versions [kudos and thx, btw. love the extension -- my coworkers hate me for it xD ]

**Comment by hugin-munin** [comment]
scratch that... just tried another vim plugin: that's broken too. surely an issue with pane-switching in vscode itself.
Sorry for bothering you.

**Comment by hugin-munin** [comment]
well.. seems all vim plugins are broken.. not sure how to handle the reporting. but this will be an incoming issue in the future I believe, so I reopened it for visibility's sake.

have a nice day!

**Comment by Chillee** [comment]
Thanks for the heads up! I'll check it out and try to fix it before the next release.

**Comment by jpoon** [comment]
Seems ok now.
