### ISSUE TITLE
Hold H/J/K/L will only move one line/col

### ISSUE THREAD

**Issue by j0exu** [VSCodeVim/Vim#1975]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T17:15:57.756Z)
- OS Version: Darwin x64 16.7.0

Extension|Author (truncated)|Version
---|---|---
vim|vsc|0.9.0

**What happened**:
If you press & hold H/J/K/L, the cursor only move one line/col

**What did you expect to happen**: 
The cursor should keep moving until I release the key.

**How to reproduce it**:
1. Open a file.
2. Press and hold hjkl.

**Comment by Chillee** [comment]
Could you take a look at the solution in the faq? This is a pretty common issue Mac users run into. 

Thanks!

**Comment by neybar** [comment]
@Chillee Thanks for the tip.  To save time for others:
[https://github.com/VSCodeVim/Vim#mac-setup](https://github.com/VSCodeVim/Vim#mac-setup)

**Comment by Widdershin** [comment]
Would it be possible to enable this by default?

I assume that doing so is either impossible or would have negative impact in some cases, otherwise it seems like a good idea.

What are those considerations? I couldn't find them in a quick search of the issues.

**Comment by Chillee** [comment]
@widdershin that's a good point. I don't know if we can set it automatically (at least, I know sublime text vim mode has this issue too), but at the very least, we can expose this easier. 

It's easy for project maintainers to just say read the faq, but it's true that first impressions matter, and some people will attribute not setting stuff up properly to poor project quality.

**Comment by j0exu** [comment]
Ops. Sorry. I didn't read FAQ at all. 

But I agree this needs to be turned on by default if possible. I felt so confused after install...

**Comment by Widdershin** [comment]
Perhaps we could convert this issue into one to consider ways to
proactively notify users to enable it, or investigate setting it
automatically.

**Comment by Chillee** [comment]
Could you open up another issue specifically targeted towards that?
