### ISSUE TITLE
Weird cursor shape on tab

### ISSUE THREAD

**Issue by sohnryang** [VSCodeVim/Vim#1976]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**Environment**:

- **VSCode Version**: 1.16.0-insider
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10 Pro Insiders Build 16257

**What happened**:

The cursor in normal mode is displayed fatty on tab character.

![2](https://user-images.githubusercontent.com/15506585/29565136-ac40aad2-877f-11e7-9684-ac31e9bb875f.PNG)

**What did you expect to happen**: 

The cursor should not be as fatty as it seems to be.

**How to reproduce it**:

Open any file, and place the cursor over a tab character.

**Comment by sohnryang** [comment]
This also happens on macOS Sierra.

**Comment by Chillee** [comment]
This is an inherent limitation of the vscode block cursor.

**Comment by sohnryang** [comment]
Then is it not available to fix this for now?

**Comment by Chillee** [comment]
Yes.
