### ISSUE TITLE
Vim Find using / forward slash not working

### ISSUE THREAD

**Issue by rawcane** [VSCodeVim/Vim#1979]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Well it's a bug report if it has been implemented and is not working or a feature request if it has never been implemented (but it's fundamental Vim functionality).

**Environment**:

- **VSCode Version**: 1.15.1
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10 Home version 1703 build 15063.540

**What happened**:
Using forward slash to find is not working. I think it worked once but then it stopped after I tried to use it on the user settings file and I cannot get it to work again.

**What did you expect to happen**: 
Find pattern.

**How to reproduce it**:
I cannot get it to work again so I cannot break it. It is possible it never worked.

**Comment by Chillee** [comment]
? It works for me.

http://i.imgur.com/voxYBsX.jpg

**Comment by rawcane** [comment]
Chillee - thanks yes it does work in most instances. I had got confused by 2 things:
a) I had the status bar hidden so could not see that I was still in search mode and searching for things like jjjjjjjjjjjjjjkkkkkkkkkkkkkkkklllllllllllllhhhhhhhhhhhh
but also
b) when trying to navigate the settings file there is some strange behaviour once you move the cursor out of the current section. So actually n keeps working and will eventually cycle through back to the original section. However if you use any of hjkl to navigate while the cursor is in one of the collapsed sections then all the keys stop working including n and /
Now I understand these things I can use it fine - sorry for the non issue (though not sure if b) is expected behaviour?

**Comment by Chillee** [comment]
@rawcane The settings file has all sorts of weird issues when you're trying to navigate in it. It's fundamentally not really a text file. For example, if you try to navigate up and down with j and k, you'll get stuck in some places.

It's weird. I recommend not really using the vim plugin on the left side of the settings file. It should still work fine on the right.
