### ISSUE TITLE
:wq

### ISSUE THREAD

**Issue by srepollock** [VSCodeVim/Vim#198]
WriteQuit command not supported. It would be nice if we could edit them

**Comment by jpoon** [comment]
This should actually already be implemented -- there may be a bug.

**Comment by jpoon** [comment]
`w` is implemented but not yet `wq`. Not a bug, just actually not implemented :)

**Comment by srepollock** [comment]
Sent a pull request now

**Comment by jpoon** [comment]
Closed with PR #354. Thanks @srepollock.
