### ISSUE TITLE
Bug: Can't navigate in autocompletion with "Ctrl+j" and "Ctrl+k".

### ISSUE THREAD

**Issue by Nexmean** [VSCodeVim/Vim#1980]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.15.1 - 41abd21afdf7424c89319ee7cb0445cc6f376959
- **VsCodeVim Version**: 0.9.0
- **OS**: Manjaro 17.0.2 Gellivara

**What happened**: Can't navigate in autocompletions with `<C-j>` and `<C-k>`. Instead of navigation opens terminal panel, but after removing of this shortcut navigation still don't works. Before, in Code 1.14 or below and VsCodeVim 0.6.* this worked fine.

**What did you expect to happen**: 

**How to reproduce it**: 

My VsCode config:
```json
{
    "window.menuBarVisibility": "toggle",
    "workbench.colorTheme": "Nord",
    "workbench.iconTheme": "material-icon-theme",

    // vim
    "vim.disableAnnoyingNeovimMessage": true,
    "vim.leader": " ",
    "vim.easymotion": true,

    // editor
    "editor.fontFamily": "'Fira Code', 'Droid Sans Mono', 'Courier New', monospace, 'Droid Sans Fallback'",
    "editor.fontLigatures": true,
    "editor.renderWhitespace": "boundary"
}
```
No other configurations or keymap plugins.

**See related gifs below:**
When I'm pushing `<C-j>` :
![ctrl-j](https://user-images.githubusercontent.com/3821520/29709743-e7a54e0e-89d0-11e7-8812-66a2364fa73c.gif)

When I'm pushing `<C-k>` :
![ctrl-k](https://user-images.githubusercontent.com/3821520/29709744-e7aee342-89d0-11e7-84ed-a4e830bb7510.gif)

Thank you for very good extension. I really love it.

**Comment by Chillee** [comment]
Somebody brought up this issue on the slack, and the fundamental issue is this line: 
https://github.com/VSCodeVim/Vim/blob/master/package.json#L145

I'm not sure, why it's there. 
@xwvvvvwx Do you happen to remember?

**Comment by xwvvvvwx** [comment]
@Chillee oh it's been a while, so I'm not sure I can say much useful...

I think all I did was make it so that all the control keybindings respected the `useCtrlKeys` setting?

**Comment by valentjedi** [comment]
Want this too, since use arrow keys is not an option in any way :)

**Comment by Enzodtz** [comment]
Hey, don't know if I should open an issue with this, but is it possible to do the same thing in the quick fixes (or refactor) menu? I use it a lot with Flutter. I tried to remap all `down` (arrow down) commands on default `keybindings.json` to `ctrl+j` but couldn't get it... Thanks
