### ISSUE TITLE
easymotion: ability to limit the characters that appear

### ISSUE THREAD

**Issue by simonwjackson** [VSCodeVim/Vim#1981]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

id like to use only (or at least prioritize) the home row keys for easy motion

```vimrc
let g:EasyMotion_keys="asdfghjkl;'"
```
Source: https://github.com/easymotion/vim-easymotion/blob/e4d71c7ba45baf860fdaaf8c06cd9faebdccbd50/doc/easymotion.txt#L405

**Comment by Chillee** [comment]
@MaxFieldWalker Any plans on implementing this?

**Comment by MaxfieldWalker** [comment]
It seems that the keys to be used for jumping are defined [here](https://github.com/VSCodeVim/Vim/blob/v0.9.0/src/actions/plugins/easymotion/easymotion.ts#L35-L42) in VSCode Vim.

I think it is not so difficult to make them customizable.
Would you like me to do it?

**Comment by omega-ult** [comment]
So I found it only shows very limited jump anchors when I do '<leader><leader>b' or '<leader><leader>w', even in a whole page, no more than 26, is that a bug?

**Comment by MaxfieldWalker** [comment]
@omega-ult I confirmed the bug. I will fix it soon.
