### ISSUE TITLE
Automatically enable KeyRepeat on MacOS

### ISSUE THREAD

**Issue by Widdershin** [VSCodeVim/Vim#1983]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

Following on from #1975.

The aim of this issue is to either enable key repeat by default on MacOS, or to more proactively notify MacOS users that they can set this option.

As I said in #1975, even though this is well documented, not all users think to check the documentation, and instead assume this is a bug.

From the [README](https://github.com/VSCodeVim/Vim#mac-setup):

> If key repeating isn't working for you, execute this in your Terminal. 
>
> defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false         # For VS Code
> defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false # For VS Code Insider
>
> We also recommend going into System Preferences -> Keyboard and cranking up the Key Repeat and Delay Until Repeat settings to improve your speed.

There are a few questions here:

 * Does this impact all MacOS users?
 * Can we programatically set this option on MacOS?
 * Would there be any downside to doing so?
 * If not, can we more proactively notify impacted users that they can easily fix this issue.

If anyone can answer any of those questions, please comment in here.

**Comment by jpoon** [comment]
I don't believe our extension will have the authority to change macos user defaults. Can you cross-post this issue to VSCode?

**Comment by Widdershin** [comment]
Done @jpoon 😄

**Comment by fourcolors** [comment]
The docs aren't working for me. I'm running Sierra latest. Repeat isn't working

**Comment by xconverge** [comment]
@fourcolors did you restart vscode.

**Comment by babakness** [comment]
@xconverge If you have a global setting you need to delete that first, ie `defaults delete -g ApplePressAndHoldEnabled`

**Comment by jpoon** [comment]
It's in the README: https://github.com/VSCodeVim/Vim#mac-setup

**Comment by jpoon** [comment]
The upstream issue was closed https://github.com/Microsoft/vscode/issues/19764. Am also going to close this issue as it doesn't look like it'll be resolved.

**Comment by hangtwenty** [comment]
> It's in the README: https://github.com/VSCodeVim/Vim#mac-setup

Updated link (the anchor changed) --

https://github.com/VSCodeVim/Vim#mac

**Comment by hangtwenty** [comment]
Pasting the snippet from the README since this thread was the first result on the search engine:


### Mac

To enable key-repeating execute the following in your Terminal and restart VS Code:

```sh
$ defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false         # For VS Code
$ defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false # For VS Code Insider
$ defaults delete -g ApplePressAndHoldEnabled                                      # If necessary, reset global default
```

We also recommend increasing Key Repeat and Delay Until Repeat settings in _System Preferences -> Keyboard_
