### ISSUE TITLE
Using C-e / C-y to scroll page is very laggy and unresponsive

### ISSUE THREAD

**Issue by circlecrystal** [VSCodeVim/Vim#1985]
It seems the vscode keeps scrolling up/down even if I release the <C-e> / <C-y> keystroke.

(It`s very easy to reproduce this issue.)

**Comment by seansisson** [comment]
I'm also having this issue. I'm fairly new to this project as well as VS Code, but I would be happy to contribute to fixing this issue!

**Comment by Chillee** [comment]
@seansisson I'm pretty sure that merely removing this line https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L1916 would fix the issues with `<C-e>`.

I'm not sure if that would cause other problems though...

**Comment by alecthomas** [comment]
@Chillee If you're not already aware, the same thing also occurs with CTRL-U/CTRL-D, though it is generally less noticeable. But when you CTRL-D through an entire file, VSCode becomes unresponsive until all buffered keystrokes complete.

**Comment by agreco** [comment]
I have the same issue, `<C-{e,y,d,u}>`, when scrolling/paging through a file becomes laggy, and as **alecthomas** has pointed out becomes "_unresponsive until all buffered keystrokes complete._"

**Comment by Chillee** [comment]
This is fixed by this PR: https://github.com/VSCodeVim/Vim/pull/2428

**Comment by agreco** [comment]
Works a treat! Thanks people!!
