### ISSUE TITLE
dw moves cursor to end of line

### ISSUE THREAD

**Issue by dpbackes** [VSCodeVim/Vim#199]
Using `dw` moves the cursor to the end of the line. 

In this example, the cursor should finish over the first `a`

![deletword](https://cloud.githubusercontent.com/assets/3519540/14412093/fc6b5ca8-ff1f-11e5-9495-cca8b75f7518.gif)

**Comment by ozkar99** [comment]
I am still having this issue, with build 0.0.15, i see the PR is already merged maybe fixed in next release?

**Comment by jpoon** [comment]
@ozkar99 yes, haven't had the chance to push a release out yet -- fixed in the main but not yet released. :soon:

**Comment by ozkar99** [comment]
@jpoon allright, thats awesome to hear :+1:
