### ISSUE TITLE
Pasting in visual mode doesn't update the default buffer's contents

### ISSUE THREAD

**Issue by nikklassen** [VSCodeVim/Vim#1991]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**This a BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.15.1
- **VsCodeVim Version**: 0.10.0
- **OS**: Mac OS X 10.12.6

**What happened**:

When "pasting over" a selection in visual (or visual line) mode, the text that is removed by that paste isn't put in the default buffer.

**What did you expect to happen**: 

The removed text should now be the contents of the default buffer.

**How to reproduce it**:

Starting with the text
```
hello
world
```
Do
1. dd
2. V
3. p
4. P

This results in

```

hello
hello

```

In Vim the results are

```
world
hello
```

Note: there are extraneous newlines in the VSCode output, but I believe this is a separate issue.

**Comment by Chillee** [comment]
@nikklassen I believe this is an issue specific to visual line mode, not visual mode, right?

**Comment by nikklassen** [comment]
I observed this behaviour in both visual line and visual mode.

**Comment by Chillee** [comment]
Ok, to be more exact, this is an issue specific to having the text being pasted be linewise.

**Comment by nikklassen** [comment]
Sorry, yes. That is correct. The expected behaviour is observed if the text was yanked using a visual selection or a motion like `ye`. This issue only occurs with `yy` or yanks done from visual line mode.

**Comment by innerdaze** [comment]
I'm seeing the same result in vim as we're getting in VSCode. I get this in both:
```
hello
hello
```

**Comment by Chillee** [comment]
@innerdaze I can't reproduce what you're saying in vim. I get the expected
```
world
hello
```
