### ISSUE TITLE
useCtrlKey does not take effect

### ISSUE THREAD

**Issue by yqrashawn** [VSCodeVim/Vim#1998]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:
Tested in fresh installed vscode
vscode vim extension is the only extension I've installed
And bellow is my setting.json.
```json
{
    "vim.useCtrlKeys": true
}
```

- **VSCode Version**:1.15.1
- **VsCodeVim Version**: 0.10.0
- **OS**: macOS 10.12.3 (16D32)

**What happened**:  
Ctrl keys won't work even I have `"vim.useCtrlKeys": true,` in setting. e.g.. `<C-d> <C-u>`

**What did you expect to happen**: `<C-d>` and `<C-u>` as vim does.

**How to reproduce it**:
Open vscode, drop a text file in it, press `<C-d>`

**Comment by Mike-Now** [comment]
Also `<C-[>` indents line instead of executing the `GoToDefinition`  action.

**Comment by yqrashawn** [comment]
My bad. Karabiner-Elements'  default complex modification "Emacs key bindings" does not exclude vscode.
