### ISSUE TITLE
Can't move cusor in when there are plugins in .vimrc

### ISSUE THREAD

**Issue by huangjj27** [VSCodeVim/Vim#2006]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**This is a BUG REPORT**:

**Environment**:

- **VSCode Version**:   1.15.1
- **VsCodeVim Version**: 0.10.0
- **OS**: CentOS 7.3
- **IM framework**: [fcitx](https://vim.sourceforge.io/scripts/script.php?script_id=3764)

**What happened**:

When a begin my vs code with vim mode, I can't move the cursor at all with any key-pressing nor input anything. However, after I disable this plugin, I could input in both English and Chinese. ~~With some effort, I finally figure out that it is vim with **plugins** that causes the problem!~~Try with other plugin, vundle for example, it reproduces.

**What did you expect to happen**: 

I could switch to English IM environment and press I, it should change to Insert mode

**How to reproduce it**:

1. install fcitx.vim(just use the `.so` version without python)
2. start vs code with vim mode 
3. change the IM to native English environment that OS support
4. press I or any legal vim key

**Comment by huangjj27** [comment]
After reinstall fcitx with the following commands, the bug fix and work smoothly:
`sudo yum install fcitx-qt* fcitx-gtk* -y`

**Comment by Chillee** [comment]
I assume you're doing something with the neovim integration for Ex-commands?

**Comment by huangjj27** [comment]
@Chillee I think you're right! I copy a `.vimrc`from github, and it has many plugins, in which `neomake`, `neovim` and `neocomplete` is also available. I have disabled `neovim` but the other reamain enabled before your mention. Now they are all disabled, Thanks!

**Comment by Chillee** [comment]
@huangjj27 To be clear, our neovim integration is currently only limited to Ex-commands.
