### ISSUE TITLE
What's the quick way uncomment ?

### ISSUE THREAD

**Issue by symphony2014** [VSCodeVim/Vim#2008]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**:
- **VsCodeVim Version**: 
- **OS**: 

**What happened**:

**What did you expect to happen**: 

**How to reproduce it**:

**Comment by Chillee** [comment]
`gc` as an operator is the binding for the commentary plugin we've implemented. Alternatively, the default vscode bindings is `<Ctrl-/>`.
