### ISSUE TITLE
Easymotions characters are placed behind text

### ISSUE THREAD

**Issue by ppasieka** [VSCodeVim/Vim#2009]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.15.1
- **VsCodeVim Version**:  0.10.0
- **OS**: Windows 10

**What happened**:

Easymotions characters are displayed behind text. It's annoying because instead go fast to some place 
you have to stop and focus on easymotion character

![image](https://user-images.githubusercontent.com/2170707/30155146-603363ca-93bc-11e7-8665-d63ee786300f.png)

**What did you expect to happen**: 

Display easymotion characters on top of text

**How to reproduce it**:

use any of easy motion

**Comment by Chillee** [comment]
I can't replicate this. Could you give some information on what other plugins you have installed, the file you're doing it in , etc?

**Comment by ppasieka** [comment]
This is fragment of *.vue file and I use Vetur extension. I didn't mention that before but I have altered default settings to something like that:
```
  "vim.easymotionMarkerFontSize": "24",
  "vim.easymotionMarkerWidthPerChar": 15,
  "vim.easymotionMarkerHeight": 20,
  "vim.easymotionMarkerYOffset": 18
```
default font size was to small for me

It is not a big deal..  I created this issue hoping that maybe changing z-index will fix it

**Comment by esetnik** [comment]
I can confirm the same issue

**Comment by MaxfieldWalker** [comment]
@ppasieka Thanks for your report. I confirmed the strange label rendering, and found how to fix it!

![image](https://user-images.githubusercontent.com/7913793/30236739-a1d08f1a-955b-11e7-8aa4-a57b40c82d1c.png)
