### ISSUE TITLE
:m command doesn't work

### ISSUE THREAD

**Issue by firel246** [VSCodeVim/Vim#2010]
I've read on a vim-related website that you can move a line with ":m".
_:m 12 | move current line to after line 12_

However it does not work at all. Nothing is happening.
Should these commands be somehow mapped or enabled?

**Comment by Chillee** [comment]
These only work if you have neovim integration for ex commands enabled.

**Comment by bufke** [comment]
It doesn't work with "vim.enableNeovim": true either as far as I can tell.

**Comment by Chillee** [comment]
Are you sure you have neovim installed with version 0.2.0?
