### ISSUE TITLE
Backreference does not work

### ISSUE THREAD

**Issue by leonardhsin** [VSCodeVim/Vim#2011]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.16.0
- **VsCodeVim Version**: 0.10
- **OS**: Windows 10

**What happened**:
On this line of code:
`printf(_UNICODE("Text and %d I want to preserve."), 20);`
I executed this command:
`s/_UNICODE(\([^)]*\))/\1/g`
The line of code became:
`printf(\1, 20);`

**What did you expect to happen**: 
The line of code should become:
`printf("Text and %d I want to preserve.", 20);`

**How to reproduce it**:
See **What happened**.

**Comment by Chillee** [comment]
So basically, we use javascript regex usually, unless you have neovim integration for Ex commands enabled. If so, then you can use vim regex for Ex commands, and this example works.

**Comment by leonardhsin** [comment]
Backreference is a vim regex feature, one shouldn't need neovim to use it.

**Comment by Chillee** [comment]
@leonardhsin Yes, but as VSCodeVim is a vim *emulation*, we need to implement vim features in whatever language we can write plugins in. That would be javascript.

The only way to use vim regex is to communicate with neovim on the backend.
