### ISSUE TITLE
Switch to Normal mode after pressed Ctrl+c and Visual mode after double clicked

### ISSUE THREAD

**Issue by mashiroplanc** [VSCodeVim/Vim#2013]
**BUG REPORT**

**Enviroment:**
Window 10 ver 1703 (Build 15063.540)
Visual Studio Code ver 1.15.1
VSCodeVim ver 0.10.0

**Issue:**
I added `"vim.useCtrlKeys": false,` to my User settings, did i miss something?
+ Vim switch to Normal mode after I pressed Ctrl + C
+ Everytime I double clicked a word, Vim switch to Visual mode

**My Setting**
![image 002](https://user-images.githubusercontent.com/30903885/30241584-67a7b35e-95b0-11e7-948c-9467f1d3e890.png)
![image 003](https://user-images.githubusercontent.com/30903885/30241586-6be03306-95b0-11e7-82b7-4481bcfcf567.png)

**Comment by Chillee** [comment]
Huh. `useCtrlKeys` does seem to have some issues. I'll take a look at that.

**Comment by xconverge** [comment]
if you set vim.overrideCopy to false in your settings does this still happen?

**Comment by martinsurgery** [comment]
For me, setting both `vim.useCtrlKeys` and `vim.overrideCopy` to `false` was necessary to prevent the vim extension from capturing **Ctrl+C**.

**Comment by mashiroplanc** [comment]
Sorry for late reply, it fixed when set both ` "vim.useCtrlKeys": false, "vim.overrideCopy" :false,`

**Comment by Chillee** [comment]
I think overrideCopy actually isn't necessary anymore. I believe the entire reason we needed it in the first place was because of our whole "off by one" thing with the visual selection.

**Comment by xconverge** [comment]
@Chillee yep you are correct
