### ISSUE TITLE
[Not Sure] Copy using Windows Clipboard looses CR/LF

### ISSUE THREAD

**Issue by GaryFurash** [VSCodeVim/Vim#2022]
Using: Windows 7, Neovim (latest), "vim.useSystemClipboard": true

If you select text and yank, then paste into a windows doc, it pastes it as if there were no CRLF at the end of the lines, even if the document you are editing had CRLF. Thanks!

**Comment by jpoon** [comment]
Don't see this repro on my Win10 machine.
