### ISSUE TITLE
Wrong cursor position after highlight + replace

### ISSUE THREAD

**Issue by chhschou** [VSCodeVim/Vim#2026]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.16.1
- **VsCodeVim Version**: 0.10
- **OS**: ubuntu 16.04

**What happened**:

Highlight and replace (`v`, move with `l`, then `c`) the cursor ends up in the wrong place.
```javascript
const { name, coord, wind, main, something } = weather
```
This occurs when highlight content inside the curly braces (from start of `name` to end of `something`), after pressing `c` the cursor ends up between `e` and `r` on the 'weather' in the line above. The aforementioned cursor position is consistent when using `d` or `x`, not just an issue with `c`.

**What did you expect to happen**: I expect the cursor to be placed at the beginning of the highlight 

**How to reproduce it**: Repeatable with the above code in a .js file

**Comment by nerdo** [comment]
I was unable to reproduce this using the same exact version numbers, but I believe there is an issue regarding cursor positions that is related to a similar experience I had.

My issue is difficult to reproduce, but it has to do with multiple selection and attempting to make a change.

Often, I will select multiple occurrences of a word with CMD + D, and hit backspace or x, depending on what mode I'm currently in.

One would expect the highlighted words to be deleted, but sometimes more text gets deleted from some of the occurrences.

For example, if I have this text:

`hello world, the hell is going to handbaskets`

and I highlight hell, hit CMD + D, and attempt to delete, I might be left with this text:

`orld, the is going to handbaskets`

I don't expect anyone to be able to reproduce it from this example alone. As I said, I have been unable to pinpoint the exact sequence that causes it, but something like this is causing weird text selection/change issues to occur.

**Comment by chhschou** [comment]
@nerdo Hopefully I've improved the example a bit now. I still encounter this daily on ubuntu. Shortcut key for selecting multiple occurrences on Linux with vscodevim. I find `:%s/find/replace/g` mostly adequate for me.

**Comment by J-Fields** [comment]
@chhschou Can you still reproduce?

**Comment by chhschou** [comment]
> @chhschou Can you still reproduce?

Migrated to vscode neovim so can't answer.

**Comment by chhschou** [comment]
Close as it is probably no longer relevant.
