### ISSUE TITLE
Support for ' ' (Jump to previous cursor position)

### ISSUE THREAD

**Issue by Zundrium** [VSCodeVim/Vim#2031]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

In NeoVim or classic Vim I can jump back to my previous cursor position using `' '`. Which is usefull when I used Go to Definition (`g d`) and want to jump back. 

Is it possible to implement this feature?

**Comment by westim** [comment]
VSCodeVim supports this behavior with the commands `C-o` and `C-t`. Whether the extension should also support `''` is up to the project owners.

**Comment by cbosco** [comment]
@westim Is this enabled by default? I'm on 0.10.1 of the plugin and just updated VSCode on Mac, but not seeing this shortcut work in normal mode.

Sorry for beginner question but is there something to reconfigure?  I've tried reinstalling the plugin after restarting VSCode (after update).

**Comment by westim** [comment]
@cbosco No worries, all questions allowed.

I'm also not showing the correct behavior on my Mac on latest versions, and it seems that the extension owners are also not seeing the correct behavior. See the comments on PR #1993 from 2 days ago. It seems that we are waiting on an API command to be fully implemented in VSCode before this will work. You could pull a dev build of VSCode, but I recommend you simply wait until the next official release.

**Comment by xconverge** [comment]
Leaving this open until we get the new release

**Comment by brandonbloom** [comment]
The "Go Last" command is now available in VS Code vim, but my changes from https://github.com/VSCodeVim/Vim/pull/1993 seem to no longer work quite right due to some issue with vimState.editor being undefined. I'll see if I can fix it.

**Comment by jpoon** [comment]
@brandonbloom any updates to your investigation?

**Comment by brandonbloom** [comment]
Fix in the pipeline: https://github.com/Microsoft/vscode/issues/36544

**Comment by ohjames** [comment]
With the latest vscode and vscodevim I see this is kind of working but in a very buggy way... I often get taken back to the second or third most recent jump instead of the most recent jump, sometimes I end up on the line before or two lines before also.

**Comment by brandonbloom** [comment]
@ohjames I've experienced that a bit too, but it's going to vary a fair bit based on what operations you're doing. The VSCodeVim code has to specify when to make navigation stops and is probably pretty buggy there, but maybe easy to fix specific cases bothering you.

**Comment by Chillee** [comment]
I believe this issue has also been fixed. Please comment if it hasn't.

**Comment by ohjames** [comment]
@Chillee definitely hasn't been fixed, no better than it was last year.

**Comment by danagain** [comment]
This still doesn't work for me
