### ISSUE TITLE
[Mac] cmd+` doesn't switch between window

### ISSUE THREAD

**Issue by jmfrancois** [VSCodeVim/Vim#2034]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**this a BUG REPORT**

**Environment**:

- **VSCode Version**: 1.16.0
- **VsCodeVim Version**: 0.10.1
- **OS**: MacOS (sierra)

**What happened**:

cmd+` is a global macos shortcut that give the ability to switch between windows of the same App

When I type cmd+` a ` caracter appear in the editor
 
**What did you expect to happen**: 

When I type cmd+` I expect to get the focus on the next VSCode window

**How to reproduce it**:

Open two VSCOde instance with vim plugin installed
try to switch using the global shortcut cmd+`

**Comment by jiripospisil** [comment]
I use the shortcut all the time and it works fine. Are you sure it's because of this plugin?

**Comment by Chillee** [comment]
Considering that this has gotten quite a bit of likes..., I'm inclined to believe this might be an actual issue? I don't use a Mac, so can one of you guys check this out? @xconverge @johnfn

**Comment by xconverge** [comment]
We don't register Cmd+` though do we? I will play around with it to see if I can reproduce it tonight

**Comment by xconverge** [comment]
I see the same behavior as @jiripospisil 

I am unable to reproduce this unfortunately...

**Comment by jmfrancois** [comment]
I have found more details. It works only when the focus is on the side bar.
if the focus is on the text it just write the `

**Comment by xconverge** [comment]
still not able to reproduce it... can you post your settings.json please?

**Comment by jmfrancois** [comment]
```
// Place your settings in this file to overwrite the default settings
{
    "editor.fontFamily": "Fira Code",
    "editor.fontSize": 12,
    "editor.fontLigatures": true,
    "editor.lineNumbers": "relative",
    "editor.rulers": [80],
    "editor.renderWhitespace": "all",
    "eslint.enable": true,
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.DS_Store": true
    },
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/node_modules/**": true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/build": true,
        "**/lib": true
    },
    "vim.disableAnnoyingNeovimMessage": true,
    "workbench.editor.enablePreview": false,
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "extensions.ignoreRecommendations": true
}
```

**Comment by jmfrancois** [comment]
Sorry it is not a vim plugin issue, but vscode issue:
https://github.com/Microsoft/vscode/issues/10021

**Comment by jmfrancois** [comment]
fixed by update the shortcuts with the two following (using native one)
<img width="755" alt="screen shot 2017-09-29 at 09 34 30" src="https://user-images.githubusercontent.com/19857479/31005540-6f85c3ba-a4f9-11e7-9198-d1ec92bcbab9.png">

**Comment by shutterfreak** [comment]
> fixed by update the shortcuts with the two following (using native one)
> <img alt="screen shot 2017-09-29 at 09 34 30" width="755" src="https://user-images.githubusercontent.com/19857479/31005540-6f85c3ba-a4f9-11e7-9198-d1ec92bcbab9.png">

It isn't working on VS Code 1.43.0 on MacOS Catalina. What this setting does, is:
1. Type a backtick in the **current** window
2. Switch to the **next** window

I think the "cmd-`" chord is being overzealously swallowed by a library component. This is also the case when typing in a text form in Safari though...

**Comment by jt3k** [comment]
Current working combination:

```json
  {
    "key": "cmd+`",
    "command": "workbench.action.quickSwitchWindow"
  },
  {
    "key": "cmd+`",
    "command": "workbench.action.quickOpenSelectNext",
    "when": "inQuickOpen"
  },
```

**Comment by shutterfreak** [comment]
All of a sudden it works. Now on version 1.48.0
