### ISSUE TITLE
insert mode move cursor

### ISSUE THREAD

**Issue by DBkevin** [VSCodeVim/Vim#2035]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**:
- **VsCodeVim Version**: 
- **OS**: 

**What happened**:

**What did you expect to happen**: 

**How to reproduce it**:
how to move the cursor in insert mode , and automatically fill the dropdown menu up and down select.Please

**Comment by Chillee** [comment]
Sorry, I'm confused. Use the arrow keys?

**Comment by DBkevin** [comment]
"vim.insertModeKeyBindings": [
        {
            "before": ["j","j"],
            "after": ["<Down>"]
        }
    ] 
this OK
But 
  "vim.insertModeKeyBindings": [
        {
            "before": ["<c-j>"],
            "after": ["<Down>"]
        }
    ] NO

**Comment by xconverge** [comment]
we do not map ctrl+j in insert mode so this is not currently possible, sorry
