### ISSUE TITLE
Keybindings with space don't seem to work

### ISSUE THREAD

**Issue by treed** [VSCodeVim/Vim#2039]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.16.1
- **VsCodeVim Version**: 0.10.1
- **OS**: Ubuntu Linux 14.04

**What happened**:

I tried to add several keybindings that use the space bar as a sort of leader. I tried using "space", "<space>", " " followed by various keys. As an example:

```
        {
            "before": ["<space>", "p"],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.showCommands",
                    "args": []
                }
            ]
        },
```

Rather than activating the command, it appears to just accept space and p as independent things.

**What did you expect to happen**: 

I expected it to invoke the command.

**How to reproduce it**:

Try putting the above example in your config, and activating it.

As a workaround, if I map leader to " ", then I can use leader. When I've done this in the past in vim, however, plugins tend to trample all over my own bindings, so I use this method instead. If VSCodeVim doesn't trample as badly, then this workaround will probably be fine, but this still feels like a bug worth investigating.

**Comment by Chillee** [comment]
@treed I assume you're talking about vim plugins trampling over your own leader bindings within vim? If so, I doubt it'll be as much of an issue. I don't think we provide any default leader bindings except those for easymotion (and I don't think those apply if easymotion is turned off).

**Comment by treed** [comment]
Yeah, I haven't had any trouble with trampling while using leader here, which is good, but it still seems like a problem worth looking into, if not particularly high priority.

(Sorry I didn't reply sooner, I thought I had.)

**Comment by jpoon** [comment]
Ultimate reasoning is explained here https://github.com/VSCodeVim/Vim/issues/2584#issuecomment-397560658. 

Going to close this issue and use #2584 to track.

**Comment by jpoon** [comment]
I took a closer look at the code. I was wrong, we do normalize all the keys. This key mapping works....

```
  "vim.insertModeKeyBindings": [
    {
        "before": ["<space>", "p"],
        "commands": [
            {
                "command": "workbench.action.showCommands",
            }
        ]
    },
  ],
```
