### ISSUE TITLE
Regex for exact word inconsistent with vim

### ISSUE THREAD

**Issue by tjfulle** [VSCodeVim/Vim#2043]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Environment**:

- **VSCode Version**: 1.16.1
- **VsCodeVim Version**: v0.10.1
- **OS**: Darwin (Mac OS X El Capitan, 10.11.6)

**What happened**: To [forward] search for the exact word "`exact word`" in vim, the following key combinations are executed:

```
/\<exact word\>
```

With VSCodeVim, the regex `\<exact word\>` instead searches for `<exact word>` (with the literal "`<`" and "`>`").  Changing the regex from `\<exact word\>` to `\bexact word\b` does exact word search as expected, but is not consistent with vim.

**What did you expect to happen**: Understanding the difference between different regex engines in `VSCode` and `vim`, I *expect* the search engine to search for `<exact word>`.  I would *like* the search engine to search for `exact word`.

**How to reproduce it**: Search for any exact word in a document with `\<exact word\>`.  Instead of searching for `exact word`, the search engine will search for `<exact word>`.

**Related**: #1739

**Comment by tjfulle** [comment]
In the previous example I used forward search, but the issue occurs in any search context (forward/backward search, search and replace, etc)

**Comment by J-Fields** [comment]
Closing in favor of #3996
