### ISSUE TITLE
<CapsLock> mapped to <Esc> cant return to normal mode from insert mode

### ISSUE THREAD

**Issue by lancelock** [VSCodeVim/Vim#2047]
**Environment**:

- **VSCode Version**:   1.16.1
- **VsCodeVim Version**:   0.10.1
- **OS**:  archlinux  4.13.3-1
- **DE**:  gnome  3.24.2

**What happened**:

i have change the key "CapsLock" as a additional "Esc" in my system, but i cant use "CapsLock" to return to normal mode from insert mode. is this a bug?

it works well in other editors, such as vim、 emacs、sublime-text and intellij idea.
i use then in vim-mode too

**Comment by Chillee** [comment]
@lancelock I'm actually surprised we haven't put this in the README yet, but look at the solution detailed here: https://github.com/VSCodeVim/Vim/issues/1479

**Comment by lancelock** [comment]
thanks

i have use this config "keyboard.dispatch": "keyCode", and it works

so what is the different between "keycode" and "code"? is there any weakeness on "keycode", why it is not recommend?

**Comment by Chillee** [comment]
@lancelock That's something that was done on the VSCode side. I can't speak to the advantages/disadvantages.

**Comment by lancelock** [comment]
@Chillee ok, thank you
