### ISSUE TITLE
:y doesn't yank a line in command mode

### ISSUE THREAD

**Issue by aaronstaves** [VSCodeVim/Vim#2052]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: Version 1.16.1 and 1.17.0-insider 
- **VsCodeVim Version**: 0.10.1
--

- **OS**: OS X - 10.12.6

**What happened**: hitting `:y<enter>` doesn't yank a line

**What did you expect to happen**: hit `:y<enter>` to yank a line and put it in the buffer

**How to reproduce it**: hit `:y<enter>` while on any line, then hit p.  The line is not pasted or put into the buffer.

**Comment by xconverge** [comment]
Did you try with neovim support enabled?

**Comment by Chillee** [comment]
This should only work with neovim support enabled, I believe.

**Comment by aaronstaves** [comment]
hup, looks like that works.  Thanks for the info!

**Comment by jplew** [comment]
@aaronstaves did you get it working with registers? I can yank into the default register like this no problem:

    :40,50y

However, when I try to yank into register `x` nothing happens:

    :40,50y x
    :reg
    //register x is still empty

Is it possible to pass a register argument to yank?
