### ISSUE TITLE
C-o cursor jumps and is not always working

### ISSUE THREAD

**Issue by hinogi** [VSCodeVim/Vim#2059]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**: 

- **VSCode Version**: 1.17.0
- **VsCodeVim Version**: 0.10.1
- **OS**: Win 10

**What happened**:
C-o sometimes only works on a second time.
C-o moves the cursor one position back.

**What did you expect to happen**: 
C-o don't need a second attempt.
C-o cursor should stay at the same position.

**How to reproduce it**:
Press C-o

**Comment by J-Fields** [comment]
Should be fixed in 1.21.7
