### ISSUE TITLE
Incorrect cursor position after `vi{`

### ISSUE THREAD

**Issue by dcervenkov** [VSCodeVim/Vim#2063]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.17.0
- **VsCodeVim Version**: 0.10.1
- **OS**: Linux 4.13

**What happened**:

Consider a code snippet such as
```c++
void func() {
    int foo;
    int bar;
}
```
when one places the cursor inside the `{}` and presses `vi{` part of the code is selected and the cursor is moved to the `}` line.

**What did you expect to happen**: 

Cursor should be moved to the `int bar;` line - that's what vim does.

**Comment by Chillee** [comment]
@dcervenkov This is more of a visual bug than anything else. Unlike vim, VSCode does not have any semblance of being able to place your cursor on the newline. So, we need to put the cursor on the line after the selection.

**Comment by dcervenkov** [comment]
@Chillee Good point about the cursor on the newline. However, I don't think it's just a visual bug - if the whole block is indented to start with, pressing `h` after `vi{` does nothing. Secondly, trying to indent the inner part using `>>` indents the `}` line as well.
