### ISSUE TITLE
Visual Mode Search Selections

### ISSUE THREAD

**Issue by esetnik** [VSCodeVim/Vim#2066]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
BUG REPORT:

**Environment**

- **VSCode Version: 1.17.1**
- **VSCode Vim Version: 0.10.1**
- **OS: macOS 10.13 (17A405)**

**What happened**:
`v` `/` `f` `o` `o`

**What did you expect to happen**: 
Should select from the current cursor position to the first instance of `foo`. Instead we enter `--SEARCH IN PROGRESS --Searching for:` and cancel visual mode.

**How to reproduce it**:
Create a file with some text:
```
This is some test copy copy
This is some test copy copy
This is some test copy copy
Foo foo foobar
```

Enter visual mode with `v` then use `/` to search in visual mode. See examples provided by https://stackoverflow.com/a/7407095

**Comment by Chillee** [comment]
I see. It works non-incrementally if you enter visual mode from that.

**Comment by tyru** [comment]
This seems to work now.

**Comment by jpoon** [comment]
Yep, just tried it on `master` and it looks to work now.
