### ISSUE TITLE
star * (shift+8) doesn't move to next occurrence correctly

### ISSUE THREAD

**Issue by foresightyj** [VSCodeVim/Vim#2068]
I am a long term sublime text vintage user. I used to move to the next occurrence of a word (case-sensitive and word boundaries also considered). But vscodevim gives me surprises that, if I am currently on a lower-cased `date` and pressing `*` also moves to capitalized `Date`, and further presses always give me capitalized `Date`. Screen capture below:

![star](https://user-images.githubusercontent.com/1296736/31476109-55ae2fd4-af37-11e7-9827-8f43a96b88e0.gif)

See that it moves past the `date` in `console.log` and stays with capitalized `Date` thereafter.

Did I miss any configuration?

**Comment by xconverge** [comment]
I think this is a dupe of #1800

**Comment by foresightyj** [comment]
Yeah. You are right.
