### ISSUE TITLE
Normal key can't working when enable system clipboad.

### ISSUE THREAD

**Issue by imkerberos** [VSCodeVim/Vim#2074]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.17.1
- **VsCodeVim Version**: 0.10.1
- **OS**: Windows7 x86 32bit

**What happened**:

When enble useSystemClipboard, more normal edit command can't work, example: dw, x etc.

**What did you expect to happen**: 

Use the default command when enable useSystemClipboard.

**How to reproduce it**:

Install windows7 x86 version, vscode and vscode-vim plugin. Turn on useSystemClipobard in VSCode settings.

**Comment by xconverge** [comment]
Sorry I do not think they provided the clipboard library for windows 32 bit

https://github.com/sindresorhus/clipboardy/issues/30
