### ISSUE TITLE
cs{[ over multiple lines

### ISSUE THREAD

**Issue by Strafos** [VSCodeVim/Vim#2080]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

BUG REPORt

- **VSCode Version**: 1.17.0
- **VsCodeVim Version**: 0.10.1
- **OS**: Ubuntu 16.04

**What happened**:
Try to change brackets using surround
```
int main() { 

}
```

cs{[ between the two braces causes nothing to happen. The braces stay the same.
**What did you expect to happen**: 
```
int main() [ 

]
```
**How to reproduce it**:
Put cursor between the brackets and type cs{[ in normal mode.

**Comment by Chillee** [comment]
What happened for you?

**Comment by Strafos** [comment]
@Chillee edited issue

**Comment by azngeoffdog** [comment]
Giving another example to better illustrate the problem:

```
int main() {
|
}
```
Where my cursor is I first type `cs{[`

```
int main() [
|
 ]
```
However, I am unable to execute a follow up `cs[{` operation as I get the following:

```
int main() [
|
 ]

-- SURROUND INPUT MODE -- {
```
`cs]}` works however and gets the following, but I still won't be able to do left bracket operations for some reason.

```
int main() {
|
 }
```
