### ISSUE TITLE
Skip word separator in word motion [Feature Request]

### ISSUE THREAD

**Issue by wongjiahau** [VSCodeVim/Vim#2084]
# What is the current situation?  
Let say I have an initial state like this : ( `^` symbolizes the cursor ) 
```
spongebob.speak("bye")
^
```
And I want the cursor to land on `b` : 
```
spongebob.speak("bye")
                 ^
```
To achieve that using word motion, I need the following command:
```
wwww
```
With EasyMotion : 
```
\\wk
```
Using `f` :
```
f"l
```
Using search :
```
/bye<CR>n
```
So in general, I need at least **THREE** keystrokes to get me to the **SECOND** word.

# What I wanted? 

Isn't it more intuitive if I can achieve the same result by pressing only **TWO** `w` ? 
Why should I press at least **THREE** keystrokes to get to the to get to the *SECOND* word?

Therefore, I wanted the word motion to skip those word separators which are symbols such as comma, period, white-space etc.

# Suggestion
Of course, changing the default word motion is not a good thing, therefore I suggest VSCodeVim team to expose a new setting  which looks as follows :
```js
// Skip word separator when using word motion such as [w], [e], [b]
"vim.skipWordSeparatorInWordMotion": false
```

## Feedback

* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Comment by Chillee** [comment]
@wongjiahau Are there any existing vim plugins that have functionality similar to what you're looking for?

**Comment by wongjiahau** [comment]
@Chillee Sadly, I can't find one. Maybe I shall wait for your NeoVim integration to be completed then I can do all those hacks with my vimrc 😄

**Comment by Chillee** [comment]
@wongjiahau haha that's what I was thinking. I think  `help iskeyword` is the setting you're looking for with your vimrc

**Comment by wongjiahau** [comment]
@Chillee I've tried that one before, but I just can't tune it to the behaviour I expected. Wait for your good news bro

**Comment by J-Fields** [comment]
`iskeyword` is definitely what you want, and it's already supported, so closing this issue

**Comment by meeeee3** [comment]
How to use iskeyword to achieve what he said ? 
If i want to jump the cursor from 
```
spongebob.speak("bye")   to   spongebob.speak("bye")
^                                       ^
```
by only one command (w) ?            


By default if i pressed w, the cursor will stop at . 
and if i add :set iskeyword-=, add pressed w, the cursor will stop at 
```
 spongebob.speak("bye")
                ^ 
```
which is also not i want
