### ISSUE TITLE
Search for end of line ($) returns end of file

### ISSUE THREAD

**Issue by auxym** [VSCodeVim/Vim#2086]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Environment**:

- **VSCode Version**: 1.17.2
- **VsCodeVim Version**: 0.10.2
- **OS**: Win10

**What happened**: When I try searching for end of line anchor (`/$`), vscode goes straight to the end of the file, and pressing `n` to go to the next occurance does nothing (indicating only one occurance). 

**What did you expect to happen**: In vim, *all* end of lines positions are found. This is especially visible with the `hlsearch` option.

**How to reproduce it**: Open any file, type out a few lines, hit `/$`.

**Comment by Chillee** [comment]
@auxym More accurately, it seems like it causes some kind of bug with the search entirely.

As a temporary solution, `/\n` should work just fine, although there is a bug with the decorator (highlighting) not showing up.

**Comment by parkovski** [comment]
I _think_ the fix for this is just to add the `m` flag to the search regexes, but when I tried last some of the tests didn't pass and while it didn't seem like this would touch those particular tests, I didn't look into it any further.
