### ISSUE TITLE
Remapping a key to "C" in normal mode not working

### ISSUE THREAD

**Issue by lobre** [VSCodeVim/Vim#2089]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.17.1
- **VsCodeVim Version**: 0.10.2
- **OS**: Linux (Elementary OS)

**What happened**:

I wanted to remap "L" to "C" in normal mode in order to replace from current character until the end of the line by using "L".

Here is the mapping. This is the only mapping I have in my config.

```
"vim.otherModesKeyBindingsNonRecursive": 
    [
        { "before": ["L"], "after": ["C"] }
    ]
```

**What did you expect to happen**: 

I expected to enter insert mode after having cleared until end of the line. Nothing has happened instead.

**Comment by xconverge** [comment]
wow this IS super weird...

you can use this in the meantime...

```
    "vim.otherModesKeyBindingsNonRecursive": 
    [
        { "before": ["L"], "after": ["D", "a"] }
    ],
```

**Comment by berknam** [comment]
Closing this since it is no longer an issue.

@J-Fields Can we close all of this old issues that still mention `"vim.otherModesKeyBindings"`? None of them should be an issue anymore, and if they are they should be reopen/recreated with updated information.

**Comment by J-Fields** [comment]
> Can we close all of this old issues that still mention "vim.otherModesKeyBindings"? None of them should be an issue anymore, and if they are they should be reopen/recreated with updated information.

Fine by me
