### ISSUE TITLE
need support for ["g","d"] mapping

### ISSUE THREAD

**Issue by cnlg** [VSCodeVim/Vim#2090]
Use the keyboard key ["g","d"] to highlight the words that are pointing at the current mouse, and use the keypad n to search down,  shift + n to search up.

**Comment by Chillee** [comment]
@cnlg You should be using `*` to do that. Try rebinding `gd` to `*`.

**Comment by cnlg** [comment]
Thank!

**Comment by Chillee** [comment]
@cnlg `gd` is a lot better in vscode than it is in vim. `gd` in vim should be `go to definition`, but it doesn't work well.

**Comment by cnlg** [comment]
understood，VScode how to use shortcut keys to switch between status bars？

**Comment by untoreh** [comment]
would be great if gd poppet up the find all reference `S+F12` when the cursor is on the definition

**Comment by liangzuobin** [comment]
How to custom ["g", "d"] plz? I want to use it with 'goto-symbol-stack'. After some actions I can't go back to the original position with the default `go to definition`.

**Comment by liangzuobin** [comment]
```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["g", "d"],
            "after": [],
            "commands": [
                {
                    "command": "extension.goto-symbol-stack.goToSymbolDeclaration",
                    "args": []
                }
            ]    
        },
        {
            "before":["<C-t>"],
            "after":[],
            "commands": [
                {
                    "command": "extension.goto-symbol-stack.goPrevOnStack",
                    "args": []
                }
            ]
        }
    ]
```
