### ISSUE TITLE
scroll-cursor commands (zt, zb) don't work

### ISSUE THREAD

**Issue by stapelberg** [VSCodeVim/Vim#210]
Vim has handy commands for scrolling without moving the cursor, e.g. `zt`, which scrolls the screen so that the line with the current cursor is placed as the first line. E.g., I often do actions like `/main(<CR>zt`, so that I can see as much of the main function as possible.

Would it be possible to implement `zt`, `zb` and `zz`?

Thanks!

**Comment by johnfn** [comment]
zz has been done. zt and zb are impossible until https://github.com/Microsoft/vscode/issues/2771 😞

**Comment by jpoon** [comment]
On 0.2.0:

1) `zz` works
2) `zt` and `zb` don't work. We do have `CommandTopScroll` and `CommandBottomScroll` which are called but the window does not update.

**Comment by rebornix** [comment]
@jpoon I moved the master bits to extensions folder and tried, both `zt` and `zb` work perfectly. I don't know whether we did anything wrong with compiling, this is really weird.

**Comment by jpoon** [comment]
@rebornix Hmm..yeah, I see the same thing. Works in master, doesn't work in released version. Super strange. As there's been a fair amount of changes since 0.2.0, shall we release a new version and see if that magically resolves this issue?

**Comment by rebornix** [comment]
@jpoon If you generate a visx and install it manually, it works as well. Let's wait and see next version!

**Comment by johnfn** [comment]
This appears to be done for me. :)
