### ISSUE TITLE
Case sensitive search option - \c / \C

### ISSUE THREAD

**Issue by parkovski** [VSCodeVim/Vim#2100]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

In Vim, putting `\c` anywhere in the search term makes it case insensitive, and `\C` forces case sensitivity. I know about smartcase, but I prefer defaulting to case sensitive searches and using `\c` to make them insensitive, and miss having this feature in VSCode.

**Comment by rishabh-bhatnagar-xebia** [comment]
How was the case sensitivity implemented?
By default, if I use * or f or / or ?
it is searching in case insensitive mode.

**Comment by tgs** [comment]
You can trigger case sensitivity by putting `\C` anywhere in your regex (although I do wish I could make it the default)

**Comment by rickgm** [comment]
If you set vim.ignorecase to false (defaults to true) in your settings.json then your searches will default to case sensitive.

**Comment by rickgm** [comment]
> You can trigger case sensitivity by putting `\C` anywhere in your regex (although I do wish I could make it the default)

If you set vim.ignorecase to false (defaults to true) in your settings.json then your searches will default to case sensitive.

**Comment by samos123** [comment]
Thanks @rickgm ! I still think it would be helpful to default to what's the default in vim.

**Comment by danawoodman** [comment]
@rickgm you made my day thank you 🙇‍♂️
