### ISSUE TITLE
Can't search using caret ^ (Regex starts-with)

### ISSUE THREAD

**Issue by kitsu** [VSCodeVim/Vim#2101]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**:

VSCode 1.17.2 VSCVim 0.10.2 on Win64

**What happened**:

Trying to search with matches starting at the beginning of line using `/^text` results in no matches.
My specific use case was searching for the next level-two header in a Markdown file using `/^##\s`.

My workaround of `/[^#]##\s` does work, but leaves the cursor before the match causing multiple matches of the same text. Searching with the cursor-to-end feature `/[^#]##\s/e` doesn't work either.

**Comment by geordanr** [comment]
It looks like the `^` and `$` anchors are being applied to the entire file, not on a line-by-line basis.

**Comment by parkovski** [comment]
They are. I have a fix for this, just need to add tests.

**Comment by J-Fields** [comment]
Fixed via #2123
