### ISSUE TITLE
CommandOpenFold: Don't set `direction: 'up'`

### ISSUE THREAD

**Issue by aeschli** [VSCodeVim/Vim#2103]
Until now, the VSCode command 'editor.unfold' did not have a `direction` parameter.
I added it recently for consistency purposes.
It looks like VIM sets it to 'up', but actually means 'down'

https://github.com/VSCodeVim/Vim/blob/11be4a4a9a2bc2d569c6fa8f9ef67448a7d19920/src/actions/commands/actions.ts#L1655

Please also check the use of 'editor.fold'. Direction 'up' means folding the current region and all parent regions. 'Down' means current region and all child regions.

**Comment by jpoon** [comment]
Thanks @aeschli. Also noticed the docs were a little out of date for fold/unfold.
