### ISSUE TITLE
Undo in a file in a split window undoes too many actions

### ISSUE THREAD

**Issue by geordanr** [VSCodeVim/Vim#2109]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Environment**:

- **VSCode Version**: 1.17.2
- **VsCodeVim Version**: 0.10.2
- **OS**: Ubuntu 17.10, Windows 10

**What happened**:

Switching to a split window and performing an undo undoes all the previous actions in the other split.

**What did you expect to happen**: 

Only the most recent action should have be undone.  Instead, that action, plus all the actions that occurred in the other split, were undone.  In the example below, only the insertion of `garply` should have been undone; instead, that plus all the other insertions in the other split (`bar` and `baz`) were undone.

**How to reproduce it**:

1. Open a new, untitled file
2. `Ctrl-\` to split the window
3. Insert text and return to normal mode: `ifoo^[`
4. Switch to other split: `^W^W`
5. Perform multiple actions (e.g. multiple text inserts): `obar^[obaz^[`
6. Switch back to first split: `^W^W`
7. Insert text: `ogarply^[`
8. Undo: `u`

**Comment by kdheepak** [comment]
I've had the same issue and I believe this is related #565. Any thoughts from core team members?

**Comment by kdheepak** [comment]
I meant to say #928.

**Comment by jpoon** [comment]
Yep. Closing this in favor of #928 .
