### ISSUE TITLE
How do I implement fast moving between Windows

### ISSUE THREAD

**Issue by cnlg** [VSCodeVim/Vim#2110]
Like this,

![vim](https://user-images.githubusercontent.com/16307285/32316464-4875be8a-bfeb-11e7-80d3-463fac9cf49a.gif)

**Comment by westim** [comment]
I believe you're looking for the Switch Editor commands. [They have keyboard shortcuts by default in VSCode](https://code.visualstudio.com/docs/getstarted/userinterface).

These commands can be found under the **Go** menu item:

![screen shot 2017-11-02 at 6 29 05 pm](https://user-images.githubusercontent.com/11410900/32353550-406c0d14-bffc-11e7-918b-92598bb8fa3b.png)

**Comment by cnlg** [comment]
@westim Thank you very much

**Comment by Chillee** [comment]
Going to close this issue. Thanks @westim !
