### ISSUE TITLE
Start in Disabled mode

### ISSUE THREAD

**Issue by n-peugnet** [VSCodeVim/Vim#2113]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**FEATURE REQUEST** :

**Environment**:

- **VSCode Version**: 1.17.2
- **VsCodeVim Version**: 0.12.2
- **OS**: Windows

I wish it was possible to start in disabled mode.
For exemple by adding a parameter `vim.startDisabled` false by default.

**Comment by jpoon** [comment]
You can disable extensions through VSCode -- https://code.visualstudio.com/docs/editor/extension-gallery#_disable-an-extension.

**Comment by n-peugnet** [comment]
I'm talking about the disabled mode of vscodevim
![capture](https://user-images.githubusercontent.com/23519418/32381321-b27ded9e-c0b2-11e7-9ed9-2f9c79528f4e.PNG)
which can be activated with the command `toggleVim`

**Comment by taimoorgit** [comment]
Add this line to your `settings.json`:

```
"vim.disableExtension": true
```

The cursor might show as vim or as normal and vice versa but it does work as intended. I use CTRL + SHIFT + P to enable vim if I need it.

**Comment by gmarsano** [comment]
> Add this line to your `settings.json`:
> 
> ```
> "vim.disableExtension": true
> ```
> 
> The cursor might show as vim or as normal and vice versa but it does work as intended. I use CTRL + SHIFT + P to enable vim if I need it.

Thanks! this is the answer.

**Comment by Anniywell** [comment]
Why not support it?
