### ISSUE TITLE
The movements `` and '' do not work.

### ISSUE THREAD

**Issue by ohjames** [VSCodeVim/Vim#2118]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

This is a FEATURE REQUEST

From the vim manual:

```
''  ``                  To the position before the latest jump, or where the                                                                       
                        last "m'" or "m`" command was given.
```

A non exhaustive list of "jump" commands:
 * `/blah` when `blah` matches
 * ???

**Comment by westim** [comment]
Duplicate of #2031.

**Comment by ohjames** [comment]
Thanks
