### ISSUE TITLE
Latest Neovim (0.2.1) is not working with the extension

### ISSUE THREAD

**Issue by sajaysurya** [VSCodeVim/Vim#2120]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.17.2
- **VsCodeVim Version**: 0.10.2
- **OS**: 4.13.11-1-ARCH linux

**What happened**:
opened a file, couldn't move cursor. Tried using both arrow keys and "h,j,k,l". However, everything works with neovim disabled

**What did you expect to happen**: The cursor to move, with neovim enabled.

**How to reproduce it**: open a file and try moving the cursor, with neovim (0.2.1) enabled.

**Comment by jpoon** [comment]
neovim has moved to 0.3.1. as there hasn't been any updates to this issue, I'm going to presume that this has been resolved. in an effort to keep our issue list sane, closing this issue.
