### ISSUE TITLE
Inconsistent cursor behaviour on block indent

### ISSUE THREAD

**Issue by lonelyelk** [VSCodeVim/Vim#2126]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Environment**:

- **VSCode Version**: 1.18
- **VsCodeVim Version**: 0.10.2
- **OS**: macOS Sierra 10.12.6

**What happened**: When indenting in normal mode using `>3>` or `>2j` the code is indented and the cursor stays at the same line. When indenting `>2k` the indentation is correct but the cursor jumps up 2 lines.

**What did you expect to happen**: The same cursor behaviour in both cases – cursor stays where it was before I started issuing the command.

**How to reproduce it**: Open a file with several lines. Move to the centre of the file. Press `>2j`, `>2k`. Observe cursor move second time and not the first.

**Comment by J-Fields** [comment]
Strangely, this seems to be how vim behaves 🤷‍♂. Closing unless someone demonstrates otherwise.
