### ISSUE TITLE
`>` character cannot be inserted

### ISSUE THREAD

**Issue by txomon** [VSCodeVim/Vim#2127]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**: 

- **VSCode Version**: 
Version 1.17.2
Commit b813d12980308015bcd2b3a2f6efa5c810c33ba5
Date 2017-10-16T13:57:00.652Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- **VsCodeVim Version**: 
0.10.2
- **OS**: 
Linux

**What happened**:
Character `>` cannot be inserted between `>`

I pressed `>`
**What did you expect to happen**: 
To insert a `>`
**How to reproduce it**:
Having the following as text:
```
>>>>>>>>>>>>>>>>>>>>>
```

Having the cursor in the middle, in insert mode, and pressing '>' key won't insert a new character.

I'm impressed I'm the first one reporting this 💃

**Comment by Chillee** [comment]
@txomon This is default VSCode behavior, believe it or not. If you want to disable this "feature", then set `editor.autoClosingBrackets` to false.
