### ISSUE TITLE
movement key bindings not fluent

### ISSUE THREAD

**Issue by edjroz** [VSCodeVim/Vim#2128]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?**: Bug
**Environment**:

- **VSCode Version**:1.18.0
- **VsCodeVim Version**: 0.10.2
- **OS**: Mac OS high sierra 10.13.1

**What happened**: holding movement key bindings moves only one position

**What did you expect to happen**: I believe it should like vim keep going down if you leave the j key pressed or any direcitonal key 

**How to reproduce it**: Press and hold any directional key binding unlike vim it will only move 1 position

**Comment by westim** [comment]
Did you try these steps from the README?

https://github.com/VSCodeVim/Vim#mac-setup

**Comment by edjroz** [comment]
Thanks for the suggestion, I just installed plugin from the text editor didn't check for configurations, now its working.
