### ISSUE TITLE
Yanking

### ISSUE THREAD

**Issue by GaryFurash** [VSCodeVim/Vim#213]
How do you copy text? I've tried yy but no luck.

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/pull/208 implemented 'c' and 'p'. 'yy' still needs to be implemented.

**Comment by jpoon** [comment]
Using https://github.com/VSCodeVim/Vim/issues/161 to track.

**Comment by GaryFurash** [comment]
Thank you!
