### ISSUE TITLE
Unable to enter command mode after updating to VSCode version 1.18.0

### ISSUE THREAD

**Issue by chris-schmitz** [VSCodeVim/Vim#2130]
**Environment**:
VSCode version: Version 1.18.0 (1.18.0)
VSCodeVim version: 
OS: Mac OS 10.12.6

**What happened**:
I updated to the newest version of VSCode last night and now I'm unable to enter command mode via the escape key. 

I tried:
- Restarting VSCode
- Uninstalling and re-installing the extension
- Deleting VSCode and downloading a new version
- Disabling all vim options in my user preferences
- Restarting my computer

So far nothing has changed.

**What did you expect to happen**: 
I expected to enter command mode and be able to navigate around.

**How to reproduce it**:
It happened right after I dated my VSCode version last night.

**Comment by chris-schmitz** [comment]
Sorry. After more troubleshooting it looks like it's some kind of extension conflict. 

I created a new user on my computer and launched VSCode to try to exclude any pre-existing settings. I installed only this Vim extension and it worked as expected. 

I then switched back to my user and disabled all installed extensions and then enabled only vim. This too worked as expected. 

right now I'm going through and enabling the rest of the extensions a group at a time and clearing out ones I don't really need. If I come across the one that causes the conflict I'll post it here, but otherwise I'll close out this issue to keep your list clean.

**Comment by andreich1980** [comment]
@chris-schmitz Have you found the conflicted extension?

**Comment by lambertwang** [comment]
I may have encountered this issue recently. VS Code updated and Vim was not allowing me to exit insert mode. I disabled all of my extensions one-by-one (other than Vim). Vim was fixed after disabling the C/C++ extension. After, I was able to re-enable all of my extensions without issue.
