### ISSUE TITLE
Selection mode mappings don't work

### ISSUE THREAD

**Issue by Mike-Now** [VSCodeVim/Vim#2131]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
**Environment**:
- **VSCode Version**: 1.17.2
- **VsCodeVim Version**:  0.10.2
- **OS**: Fedora 25

**What happened**:
The whole document was selected.
Keys pressed:
L
**What did you expect to happen**: 
The selection should extend only to the end of the line.

**How to reproduce it**:
Enter these mappings in your user settings:
```
{
 "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": [ "H" ],
            "after": [ "^" ]
        },
        {
            "before": [ "L" ],
            "after": [ "$" ]
        }]
}
```
Open a text file with multiple text lines. Enter visual selection mode. Press L.

**Comment by Silox** [comment]
I reported a similar (same?) issue a while ago: https://github.com/VSCodeVim/Vim/issues/1835

A workaround (albeit annoying to get in your fingers) is to press `k` or `l` first. Once you've moved the cursor, the commands should work.

**Comment by jwmann** [comment]
Having the same issue.
Really wish there was a `vim.visualSelectKeyBindingsNonRecursive` :(

**Comment by Mike-Now** [comment]
Some time have passed :) The following mappings work for me currently:

```{json}
{  
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": ["H"],
      "after": ["^"]
    },
    {
      "before": ["L"],
      "after": ["$"]
    },
  ]
}
```
