### ISSUE TITLE
"d" deleting in visual block mode does not work as expected

### ISSUE THREAD

**Issue by issei126** [VSCodeVim/Vim#2134]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**:  1.17.2
- **VsCodeVim Version**: 0.10.2
- **OS**:  Mac OS Sierra 10.12.6

**What happened**:

I selected charactors in visual block mode and pressed `d`,
then selected charactors is deleted but not is yank.

**What did you expect to happen**: 

I expect selected and deleted charactors to be yank too. 

**How to reproduce it**:

example text
```
abcdefg
^
```
^ is caret position.

then press

`2l<C-v>2d`

text is
```
abfg
  ^
```

above charactors is I expected.

then press 
`jp`

I expect 

```
abfg
cde
```

but not paste

**Comment by tyru** [comment]
Now `d` seems to also yank the text.
So this seems to be fixed now.

By the way, some nitpicks here:

> `2l<C-v>2d`

Maybe the key what you want to say is `2l<C-v>2ld` ?

> then press
> `jp`
>
> I expect

Maybe correct (same as original Vim) behavior is `abfcdeg`.

**Comment by tyru** [comment]
oops, sorry. I was mistaken.
This problem is not fixed yet.

**Comment by J-Fields** [comment]
Is this still an issue? I can't reproduce.

**Comment by issei126** [comment]
> Is this still an issue? I can't reproduce.

No, I can't reproduce too.
This may be fixed. Thx !
