### ISSUE TITLE
<ctrl-v> mode, after I run "c" command , And then run "p" , it seem "p" command missing the Modify data.....Did I Got Wrong ?

### ISSUE THREAD

**Issue by hebarguan** [VSCodeVim/Vim#2135]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**:
- **VsCodeVim Version**: 
- **OS**: 

**What happened**:

**What did you expect to happen**: 

**How to reproduce it**:

**Comment by J-Fields** [comment]
If I understand the question (which I'm not positive I do), this should be fixed.
