### ISSUE TITLE
I think CTRL-d should be half-page-down

### ISSUE THREAD

**Issue by sachin21** [VSCodeVim/Vim#214]
> I think CTRL-d should be half-page-down

Original Vim do have a its binding.
Why not use `CTRL-d`?

**Comment by johnfn** [comment]
I think so too.

Unfortunately, this is one of the few things not possible with the current VSCode API. 😞

**Comment by sachin21** [comment]
I see. That’s too bad :-(

**Comment by sumanx** [comment]
How about down/up about 20 lines instead, before the API ready? 😃

**Comment by rebornix** [comment]
@sachin21 @sumanx We are adding these missing APIs in VS Code so you can expect this feature in early August.

Once these APIs are released in VS Code Insider Build, I'll add these commands immediately and let you guys know the update.

**Comment by johnfn** [comment]
I am actually okay with a 20 line stopgap measure. This appears to be a widely-desired command.

**Comment by rebornix** [comment]
@johnfn sounds good to either, 20 is almost half page when you use rMBP. I'll add it real quick. Once we have accurate API then I'll tweak them.
