### ISSUE TITLE
vim.handleKeys doesn't work  in linux

### ISSUE THREAD

**Issue by jojonki** [VSCodeVim/Vim#2146]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**a BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.18.0
- **VsCodeVim Version**:  0.10.3
- **OS**: Ubuntu 16.04

**What happened**:
Today I updated VS Code to v1.18.0. Then I noticed `<C-w>` didn't work. I added `<C-w>` for ignoring key to vim. I also updated Mac's VS code, it worked correctly, e.g. close a window. 

My user settings are following and `<C-t>` worked. So I assume this is a problem of `vim.handleKeys`.

- User settings
```
{
    "vim.insertModeKeyBindings": [
      {
        "before": ["j", "j"],
        "after": ["ctrl", "t"]
      }
    ],
    "vim.otherModesKeyBindingsNonRecursive": [
      {
        "before": ["J"],
        "after": ["j", "j", "j", "j", "j", "j", "j", "j", "j", "j"]
      },
      {
        "before": ["K"],
        "after": ["k", "k", "k", "k", "k", "k", "k", "k", "k", "k"]
      },
      {
        "before": ["L"],
        "after": ["$"]
      },
      {
        "before": ["H"],
        "after": ["^"]
      }
    ]
    ,
    "vim.searchHighlightColor": "rgba(25, 50, 255, 0.3)",
    "python.linting.pylintEnabled": true,
    "python.linting.pylintArgs": [
      "--extension-pkg-whitelist=numpy"
      ],
      "vim.disableAnnoyingNeovimMessage": true,
      "python.pythonPath": "/home/jonki/anaconda3/bin/python",
      "window.zoomLevel": 0,
      "vim.handleKeys": {
        "<C-a>": false,
        "<C-b>": false,
        "<C-c>": false,
        "<C-f>": false,
        "<C-u>": false,
        "<C-w>": false,
        "<C-x>": false
      },
      "workbench.iconTheme": "vscode-icons",
      "terminal.integrated.shellArgs.linux": ["-1"]
    }
```

**What did you expect to happen**: 
When type `<C-w>`, the window should be closed.

**How to reproduce it**:
Update VS Code version on Ubuntu. And use some `vim.handleKeys` to false.

**Comment by jpoon** [comment]
See my comment here https://github.com/VSCodeVim/Vim/issues/2145. Going to close it in favor of 2145

**Comment by jojonki** [comment]
Thank you. It looks a same bug.
