### ISSUE TITLE
:vs launches file dialog

### ISSUE THREAD

**Issue by rharriso** [VSCodeVim/Vim#2148]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**: . 

- **VSCode Version**: 1.18.0
- **VsCodeVim Version**:  0.10.3
- **OS**:  macOS 10.12.6, ubuntu 17.10

**What happened**:

`:vs` opened a file dialog

**What did you expect to happen**: 

Open new pane to the side

**How to reproduce it**:

**Comment by Zyst** [comment]
This also happens if you use `:vsp`.

**Comment by jpoon** [comment]
Consequence of this change https://github.com/VSCodeVim/Vim/pull/2067.

**Comment by rharriso** [comment]
So, is this expected behavior? 

It seems like a bug to me.

**Comment by jpoon** [comment]
@rharriso Yeah, it's a bug. We should be able to open a new pane with `:vs` and `:vsp`.

**Comment by Zyst** [comment]
Is there an ETA on when this will hit release? I feel sad every time I type :vsp and get the file dialog.

**Comment by jpoon** [comment]
@Zyst https://github.com/VSCodeVim/Vim/releases/tag/v0.10.5
