### ISSUE TITLE
`:qall` does nothing

### ISSUE THREAD

**Issue by rharriso** [VSCodeVim/Vim#2149]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: latest
- **VsCodeVim Version**:  0.10.3
- **OS**: macOS and Ubuntu

**What happened**:

`:qall` does nothing

**What did you expect to happen**: 

Close all the open panes.

**How to reproduce it**:

**Comment by rharriso** [comment]
Can you guys republish an older version? 0.10.3 is turbo broken.

**Comment by xconverge** [comment]
FYI you can get the .vsix from https://github.com/VSCodeVim/Vim/releases

**Comment by jpoon** [comment]
This works for me on 0.10.4

**Comment by rharriso** [comment]
@jpoon, confirmed working on 0.10.4
