### ISSUE TITLE
The cursor not displayed at the end of the line (插入模式鼠标点击行尾,但是光标出现位置错误)

### ISSUE THREAD

**Issue by phpstudyOne** [VSCodeVim/Vim#2151]
我今天更新了 vim-code(0.10.4) 的插件之后出现了这个问题 .

1. 打开一个文本.
2. 按 a 进入插入模式.
3. 鼠标单击一行的行尾.

预期结果:光标显示在该行行尾.
实际结果:光标显示在该行行尾的前一个字符处.

![image](https://user-images.githubusercontent.com/11455285/32819240-14e8b230-ca03-11e7-877b-9e7f1415e503.png)

**Comment by jpoon** [comment]
Yeah, I don't read Chinese :)

**Comment by xconverge** [comment]
Google translate seems to nail it

```
I got this problem after I updated the plugin for vim-code (0.10.4) today.

Open a text.
Press a to enter insert mode.
Mouse click on the end of a line.
Expected result: The cursor is displayed at the end of the line.
Actual results: The cursor is displayed at the previous character at the end of the line.
```

I can't reproduce it, but it seems likely that this happens, I know that we prevent clicking past EOL and move the cursor back

**Comment by Zuckjet** [comment]
@xconverge  thank your reply.though this issue uses chinese ,you still read it through google translate.

**Comment by phpstudyOne** [comment]
@xconverge  you can see this image : ![image](https://raw.githubusercontent.com/phpstudyOne/rihui/master/apache_service_setting/images/aaaa.gif)

**Comment by jpoon** [comment]
Don't see this repro-ing anymore on 0.10.9

**Comment by karlhorky** [comment]
I'm still having this issue on `0.11.4` with VSCode `1.22.2` on macOS High Sierra `10.13.4`.

**Comment by karlhorky** [comment]
Hm, just wanted to record a screencast and come back to add it in a comment but the issue seems to have gone away. What I did in the meantime was:

- disabled all extensions
- restarted VSCode
- re-enabled all extensions
- restarted VSCode
- issue was still there, so I opened a new project to record the screencast
- issue now gone (also in original workspace)

lol what? Anyway, if it comes back I'll try to record it.

**Comment by karlhorky** [comment]
Oh ok, it does seem to have something to do with whether a file was open in the editor already when it started (started an existing project that has files open on the command line with `code .`). I'll take a recording...

**Comment by karlhorky** [comment]
Ok, here's the screencast:

![untitled](https://user-images.githubusercontent.com/1935696/39005994-f8c95f7c-4401-11e8-8c6b-3245a97d837d.gif)

**Comment by karlhorky** [comment]
To be clear, this only happens on files that are already open in a project (previously open the last time the editor closed). As soon as files are opened fresh (even the same files), the bug goes away.

**Comment by karlhorky** [comment]
To be clear, this only happens on files that are already open in a project (previously open the last time the editor closed). As soon as files are opened fresh (even the same files), the bug goes away.

Maybe another clue is that the cursor position was also at the end of the line when the file was opened?

cc @Chillee
