### ISSUE TITLE
How to make selection after doubleclicking in normal mode more VSCode style?

### ISSUE THREAD

**Issue by hunhejj** [VSCodeVim/Vim#2153]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Environment**:

- **VSCode Version**: 1.18.0
- **VsCodeVim Version**: 0.10.4
- **OS**:  Windows 10

**What happened**: I double click a word in normal mode. The word will be selected _together with the trailing character_. If I then copy the selection, it will copy that next character too.
Rather I would like to use VSCode style, i.e. doubleclicking the word, then ctrl+c --> pasting it from the clipboard would insert exactly the word. In VIM this was the case when using mswin. I think this is more a question of cursor / selection type, i.e. with mswin repeating 'i' and then 'esc' the cursor remains at the same position.

What settings do I have to set to get this behavior?

**Comment by tyru** [comment]
This seems to be fixed now.
