### ISSUE TITLE
Wrong behavior when copy/paste non ASCII text

### ISSUE THREAD

**Issue by nemonweb** [VSCodeVim/Vim#2154]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.18.0 and up
- **VsCodeVim Version**:  0.10.3
- **OS**: macOS 10.12.6

**What happened**:
Wrong behavior when copy/paste non ASCII text

example:
![nov-15-2017-16-31-05](https://user-images.githubusercontent.com/4689898/32838816-4502a08c-ca23-11e7-8dbb-668a08cde9e1.gif)

config:
```
  "vim.useSystemClipboard": true,
  "vim.overrideCopy": true,
```

**What did you expect to happen**: 

should copy `привет` like `привет`

**How to reproduce it**:
copy/paste non ASCII text

**Comment by mashiroplanc** [comment]
I just tried your word and there are no problems, If you want to use default VSCode keys binding, try
```
"vim.useCtrlKeys": false, 
"vim.overrideCopy" :false,
```
Btw, you don't need to set `overrideCopy: true` because it is default value
If you want to use `useCtrlKey: true`  https://github.com/VSCodeVim/Vim#vimhandlekeys

**Comment by nemonweb** [comment]
fixed by setting 
```
"vim.overrideCopy": false
```
