### ISSUE TITLE
connected variables can not be modified properly with snippet function

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#2157]
_From @mkitby on September 24, 2017 13:51_

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:38:23.027Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
gitignore|cod|0.5.0
arm|dan|0.1.2
python|don|0.7.0
cpptools|ms-|0.12.4
snippet-creator|nik|0.0.4
vim|vsc|0.10.1

---

Steps to Reproduce:

1. Add the following snippet to c.json

```
"Header Include-Guard": {
    "prefix": "once",
    "body": [
        "#ifndef __${1:NAME}_H__\r",
        "#define __${1:NAME}_H__\r",
        "\r",
        "$0\r",
        "\r",
        "#endif /* __${1:NAME}_H__ */"
    ]
}
```

2. Create an c language file, and insert the snippet, then the cursor would be end of three NAME strings.  Press the Backspace key once, the first __NAME_H__will be changed to __, and the other two strings will be kept unchanged.

by the way, the issue is gone if I disable the vim extension.

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#34904_

**Comment by rebornix** [comment]
_From @jrieken on September 25, 2017 6:57_

> Create an c language file, and insert the snippet, then the cursor would be end of three NAME strings. Delete the NAME string and enter new name.

And then?

**Comment by rebornix** [comment]
_From @vscodebot[bot] on October 4, 2017 15:51_

This issue has been closed automatically because it needs more information and has not had recent activity. Please refer to our [guidelines](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) for filing issues. Thank you for your contributions.

**Comment by rebornix** [comment]
_From @mkitby on October 5, 2017 8:58_

 @jrieken, I already added more information.

**Comment by rebornix** [comment]
_From @jrieken on October 5, 2017 10:59_

Yeah, our bot doesn't recognise modifications to the summary // cc @chrmarti

**Comment by rebornix** [comment]
_From @jrieken on October 5, 2017 11:1_

Please refine your steps as this doesn't reproduce for me

![oct-05-2017 13-01-30](https://user-images.githubusercontent.com/1794099/31224220-5572b874-a9cd-11e7-9df8-108fb64fe30e.gif)

**Comment by rebornix** [comment]
_From @mkitby on October 6, 2017 6:42_

@jrieken 

As I said, the issue is gone if I disable the vim extension. So did you install vim extension?

Seems I should post this to https://github.com/VSCodeVim/Vim?

![vscode_bug](https://user-images.githubusercontent.com/15389150/31266038-7f3d5cd6-aaa4-11e7-9752-c5f5d7ac573b.gif)

**Comment by rebornix** [comment]
_From @jrieken on October 6, 2017 7:21_

> As I said, the issue is gone if I disable the vim extension. 

Sorry, I missed that. However, it also makes this an issue for VIM because the vim extension incepts *every* type event and it is its responsibility to send it back to the editor.

**Comment by JKillian** [comment]
I'd argue that this would be a nice bug to get fixed, as it makes it very hard to use some sorts of snippets. For example, here's me pressing "Backspace" after starting a snippet (notice only the first instance of my variable changes)

![2018-06-14 15 48 12](https://user-images.githubusercontent.com/1400151/41434640-71d3c592-6fea-11e8-8837-fb4cdbc47e94.gif)

As a workaround though, I found that if you press the arrow keys before doing any editing actions, things work correctly

**Comment by J-Fields** [comment]
This has been fixed
