### ISSUE TITLE
difference between mac and windows

### ISSUE THREAD

**Issue by loryxia** [VSCodeVim/Vim#2160]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

MacOS High Sierra

- **VSCode Version**:
- **VsCodeVim Version**: 
- **OS**: 

**What happened**:

In windows,  the cursor is move continues when i hold hjkl keys ...
but in mac, the cursor move once when i click hjkl keys once, why?

**What did you expect to happen**: 

I need continues movement when i just hold one key of these hjkl... in Mac.
I need same behavior with windows in mac.

**How to reproduce it**:

**Comment by westim** [comment]
Did you see these instructions?

https://github.com/VSCodeVim/Vim#mac-setup
