### ISSUE TITLE
Keys specified in vim.handleKeys aren't being handled

### ISSUE THREAD

**Issue by kmckelvin** [VSCodeVim/Vim#2162]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: 0.10.4
- **OS**: Linux (Ubuntu 17.10). Also experiencing it on macOS 10.13.1

**What happened**:

Using these configuration options:

```
    "vim.useCtrlKeys": false,
    "vim.handleKeys": {
        "<C-o>": true,
        "<C-i>": true,
        "<C-r>": true
    },
```

When using `<C-o>`, `<C-i>` or `<C-r>`, the keys are handled by VSCode. E.g. `<C-o>` displays the File Open dialog.

**What did you expect to happen**: 

Using keys marked as `true` in the `vim.handleKeys` section should be handled as vim bindings. `<C-o>` and `<C-i>` should navigate the jump list. `<C-r>` should redo.

**How to reproduce it**:

Set `useCtrlKeys` to false, and handle specific key bindings

```
    "vim.useCtrlKeys": false,
    "vim.handleKeys": {
        "<C-o>": true,
        "<C-i>": true,
        "<C-r>": true
    },
```

Press `<C-o>`. The File Open dialog is shown.

I've confirmed this last worked in 0.10.2 by installing the vsix file. The behaviour breaks in 0.10.3.

**Comment by Arxzin** [comment]
same issue here.

**Environment**
- **VSCode Version**: 1.19.1
- **VsCodeVim Version**: 0.10.7
- **OS**: Windows 10, Version 1709, Build 16299.192

**Comment by jpoon** [comment]
Ah, we're only handling the negation of `handleKeys`. Should be an easy fix.

**Comment by jpoon** [comment]
Proposal: Remove `useCtrlKeys` altogether. The functionality of `useCtrlKeys` and `handleKeys` overlaps.

This will be a breaking change as people will need to update their configs, but the configuration of the keys will be more obvious.

**Comment by gwojan** [comment]
I have `Normal` mode `Space` mapped to `Ctrl+f` and `Shift+Space` mapped to `Ctrl-b` via `Keyboard Shortcuts` and this fix appears to break those mappings...

**Comment by jpoon** [comment]
Can you share your user settings?

**Comment by gwojan** [comment]
@jpoon Sure... Included is `settings.json` and `keybindings.json`.

[settings.zip](https://github.com/VSCodeVim/Vim/files/1607247/settings.zip)

**Comment by jpoon** [comment]
```
            "<C-F4": false,
            "<C-K": false,
            "<C-f": true,
            "<C-N": false
```

this is malformed.

**Comment by gwojan** [comment]
Care to elaborate? 😉 I figured as much, however, that really isn't my concern at the moment. the `Space` and `Shift+Space` mappings are pretty much muscle memory at this point...

**Comment by Arxzin** [comment]
```
"vim.useCtrlKeys": false,
    "vim.handleKeys": {
        "<C-u>": true,
        "<C-d>": true,
        "<C-i>": true,
        "<C-o>": true,
        "<C-r>": true
}
```
After the fix yesterday everything else (in my use-case) works fine, except C-d

if make ```"vim.useCtrlKeys": true```, C-d works.

**Environment**
- **VSCode Version**: 1.19.1
- **VsCodeVim Version**: 0.10.8
- **OS**: Windows 10, Version 1709, Build 16299.192

**Comment by jpoon** [comment]
It's likely this line (https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L288), but it's not obvious to me right now why we had to remap it.

**Comment by jpoon** [comment]
Interesting. The easiest thing would be to remove the <D-d> key entirely. I don't use multi-cursor all that much so not sure if this would break a lot of people.

**Comment by Arxzin** [comment]
You are right, the reason of that remapping is vague, I assumed it.

Yes, it's not logical to have useCtrlKeys and handleKeys working together, remove that useCtrlKeys is fine, but then users have to config every ctrl keys into handleKeys ( did it yesterday), a little bit inconvenient, some people just want to enable/disable several keys while leaving rest of keys unchanged.

Maybe rename useCtrlKeys to useCtlKeysByDefault? It sounds better, lol.
 
Also, I'm new to github, messing around everything resulting into these repeating commits, they are already being hard reset, but still appearing in this page, is there a way to remove these redundant commits, or make them disappear on this page?

**Comment by jpoon** [comment]
Oops, sorry missed your comment. My thinking is that we can remove `useCtrlKeys`, and instead have a set of default `handleKeys`. 

My knowledge gap right now is why we needed the `<D-d>` remapping that you pointed out to in your PR.
