### ISSUE TITLE
Ctrl+Space mapping

### ISSUE THREAD

**Issue by Dudelmoser** [VSCodeVim/Vim#2164]
Hey guys,

I would like to map `<Space>` to `/` and `<C-Space>` to `?`

The second one isn't working. I assume special characters wrapped inside \<\> must be used in a different way. Is there any documentation on this and how would I realise my search backwards mapping?

Thanks in advance

**Comment by arjaron** [comment]
Judging by other issues & docs the correct mapping should be <c-space>. But it isn't working, as I've tried using it as well for "gcc". I came here to look for a solution...

**Comment by J-Fields** [comment]
`nnoremap <C-space> gcc` will work in the next update
