### ISSUE TITLE
Key binding issue :: Weird behavior mapping <Esc> key

### ISSUE THREAD

**Issue by recsubbu** [VSCodeVim/Vim#2174]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Environment**:

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: 0.10.5
- **OS**: OSX 10.12.1

**What happened**:
Would like to map `<Esc>` such that it does 2 things:
a. Change from insert to normal mode & 
 b. Save the current file

User settings file:

`
"vim.insertModeKeyBindingsNonRecursive": [
        {
            "before" : ["<Esc>"],
            "after" : ["<Esc>"],
            "commands": [
                {"command": "workbench.action.files.save", "args": []}
            ]
        }
    ]
`

Now, when I press `<Esc>` it changes to normal mode and saves file, but introduces 15-20 seconds delay before I could start typing again.

**What did you expect to happen**: 

Same values for "vim.otherModesKeyBindings": works fine as expected. Only insertMode has this delay.

**How to reproduce it**:

While testing this, noticed that, if I change 
` "after" : ["<Esc>"],` to something like
`"after" : ["h", "<Esc>"],`

I could see that it is actually recursing. (Editor window is full of "hhhhhhhh...." running in a text-loop).

A non-recursive keybinding is showing recursive behavior.  Thanks.

**Comment by recsubbu** [comment]
It is this [n]vim setting am trying to get it work with vscode.

`inoremap <esc> <esc>:silent w<cr>`

**Comment by berknam** [comment]
Closing since this is no longer an issue. If you're still experiencing this, please create a new issue with updated info.
