### ISSUE TITLE
High CPU usage when opening any file

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#2176]
_From @dqw on November 24, 2017 3:31_

- VSCode Version: Code 1.18.1 (929bacba01ef658b873545e26034d1a8067445e9, 2017-11-16T18:32:36.023Z)
- OS Version: Windows_NT x64 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.1.0
Bookmarks|ale|0.18.0
beautify|Hoo|1.1.1
intellij-idea-keybindings|k--|0.2.16
Go|luk|0.6.67
vscode-icons|rob|7.18.1
vim|vsc|0.10.5

---

Steps to Reproduce:

1.Open any file，the CPU usage  over 75%
2.Close all file， the CPU usage down to 10%
3.@rebornix When I disabled vim extension，the problem solved

Reproduces without extensions: No
![1](https://user-images.githubusercontent.com/1411456/33202656-51ce024a-d138-11e7-8fd4-d9b65787da25.png)
![4](https://user-images.githubusercontent.com/1411456/33202747-9a409380-d138-11e7-8675-fbe0653dfc90.png)
![2](https://user-images.githubusercontent.com/1411456/33202662-5603d042-d138-11e7-8989-0865bf277366.png)
![3](https://user-images.githubusercontent.com/1411456/33202665-5c2787fc-d138-11e7-8e3e-60d9530dd0f3.png)

_Copied from original issue: Microsoft/vscode#39074_

**Comment by mrsimo** [comment]
I'd like to mention that besides high CPU usage, working with VSCode gets quite slow. Keypresses get delayed and you need to wait before a word finishes typing.

**Comment by Chillee** [comment]
@mrsimo I think there's an extension profiling thing. Could you try this and see if you see anything interesting?

https://code.visualstudio.com/docs/extensions/debugging-extensions#_profiling-your-extension

Also, does this replicate with all settings at default?

**Comment by mrsimo** [comment]
Hey! The performance went back to normal with the Insiders build. Just tried that and with all my settings it's not causing any high CPU load.

Back to the standard VSCode, removing all my settings also seems to fix the issue. Curiously, if I apply them again, it doesn't increase the load. I need to stop VSCode and open it again (with my settings) for it to use high CPU. In case it helps, these are my settings: https://gist.github.com/mrsimo/4f54bd620c4fbfe9e7e90aa052c91909

I did the extension profiling thing, here's what it generated when recorded for about 10s: https://monosnap-albertllop.s3.amazonaws.com/CPU-20171129T202207.cpuprofile

Here's a screenshot of the top of another profile:

![95a2c725-3e94-47aa-8a0f-1b90e0 2017-11-29 20-25-45](https://user-images.githubusercontent.com/19203/33394726-85547748-d543-11e7-893e-9b42ba226c56.png)

Cheers!

**Comment by jpoon** [comment]
This is likely the cause: https://gist.github.com/mrsimo/4f54bd620c4fbfe9e7e90aa052c91909#file-gistfile1-txt-L15. 

See https://github.com/VSCodeVim/Vim/issues/2124

**Comment by mrsimo** [comment]
Yes, that seems to be it. Thanks!

**Comment by dqw** [comment]
The problem was resolved after updated to the latest version of vscode. This issue can be closed. Thanks. @rebornix
