### ISSUE TITLE
Cannot create a new file or folder in explorer viewlet that contains the letter "o"

### ISSUE THREAD

**Issue by nicksnyder** [VSCodeVim/Vim#2177]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: Version 1.19.0-insider (1.19.0-insider) 3c470706ded48fc75c05f86bc4f9c7b0f4d6c708
- **VsCodeVim Version**: 0.10.5
- **OS**: macOS High Sierra 10.13.1

**What happened**:

I can't create a file or directory with the letter "o" in it. As soon as I type "o", the file is created as if I hit "enter".

![screen recording 2017-11-27 at 09 16 am](https://user-images.githubusercontent.com/754768/33279681-573ca448-d354-11e7-81b5-6f7be7be0c14.gif)

Disabling the extension fixes the problem.

**What did you expect to happen**: 

I should be able to.

**How to reproduce it**:

1. While in a workspace, right click on a folder and select "New file".
2. Type "hello"

**Comment by Mikodin** [comment]
To add to this, press K will move up, and pressing o expands it if you are creating a folder.

It seems like this bug was introduced when VSCode insiders went up to 1.19

**Comment by rodrigoelp** [comment]
Is affecting multiple characters such as `j k o` as far as I can see...

**Comment by Chillee** [comment]
Luckily, this wasn't our fault! This was due to a regression on the VSCode side. https://github.com/Microsoft/vscode/pull/39102#issuecomment-347780232

Sounds like it should be fixed in the next release of the insiders build.

**Comment by jpoon** [comment]
Actual upstream issue is https://github.com/Microsoft/vscode/issues/39211

**Comment by nicksnyder** [comment]
Works for me on insiders again. I am going to close this issue since it was an upstream bug.

**Comment by dulowski-marek** [comment]
It worked for a while but now it fails again.

Build: __1.19.0-insiders__
Commit __d8989c__ 
Date __2017-12-08__

**Comment by rodrigoelp** [comment]
Just so you guys know... it is happening again (with `o`, `j`, `k`)

With `o` is a little more annoying because it exits the name editing mode.

**Comment by jpoon** [comment]
On Insiders? If so, you should file an issue against VSCode or update the existing issue.

**Comment by rodrigoelp** [comment]
Yes, on insiders 1.19.0 (951f5a20fc820e32a65ca05bb87af86f65027470)

The problem to raise it in vscode is that it does not happen when the vscodevim extension is disabled.

**Comment by texasbruce** [comment]
Still broken as of today in the latest release

**Comment by dring1** [comment]
Running into this issue as well - everything appears to be up to date for non-insiders
```
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:47:13.351Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32
```
