### ISSUE TITLE
pasting after a normal mode delete with range only pastes first character

### ISSUE THREAD

**Issue by psylum** [VSCodeVim/Vim#2178]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**: 1.18.1 (x64)
- **VsCodeVim Version**: 0.10.5
- **OS**: Windows 7 Enterprise (x64)
- **settings.json**: "vim.enableNeovim": false,

**What happened**:

If you use a numeric range with x in normal mode, pasting from the default register only pastes the first character. This is not seen using visual mode with x or normal mode ranged 'd' deletions.
Exact reproduction steps listed below.

The following is seen in the developer console:
```
[Extension Host] Text transformations are overlapping. Falling back to serial
           transformations. This is generally a very bad sign. Try to make
           your text transformations operate on non-overlapping ranges.
```

**What did you expect to happen**: 

I expected the full range of characters deleted by the x command to be pasted.

**How to reproduce it**:

Create a new file and enter insert mode and add the following text
```
hello

```
then escape to normal mode and type `gg5xjp`
I expected 'hello' to be pasted on the 2nd line in the file.
Actual results: only 'h' is pasted on the 2nd line in the file.

**Comment by J-Fields** [comment]
Closing as this seems to have been fixed
