### ISSUE TITLE
VsCodeVim not working on Windows10

### ISSUE THREAD

**Issue by winklerrr** [VSCodeVim/Vim#2180]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Environment**:

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: 0.10.5
- **OS**: Windows 10 Pro, 64 Bit

**What happened**:

- Installed VS Code
- Installed VsCodeVim extension
- Restarted Computer
- Started VS Code and opened a file 
- VsCodeVim extension seems to be unloaded => no vim commands possible

**What did you expect to happen**: 

VsCodeVim extension should be loaded successfully and ready to use

**How to reproduce it**:

Don't know...

**Comment by winklerrr** [comment]
I solved the problem by:
- removing all extensions and then uninstalling VS
- reinstalling VS
- reinstalling VsCodeVim as first extension

Now it works...
Don't know what the problems was - maybe because the first time I installed the official Python plugin before VsCodeVim but not sure.

Regards, winklerrr

**Comment by Chillee** [comment]
That's confusing... Nice to hear you fixed it though!
