### ISSUE TITLE
Search by filename using '/' in explorer list

### ISSUE THREAD

**Issue by davidhpark** [VSCodeVim/Vim#2181]
Is there any way to search by filename using '/' while in the explorer list? The use of 'j' and 'k' (as well as <c-d> and <c-u>) are nice, but being able to access files directly through '/' would be more convenient.

**Comment by westim** [comment]
As a workaround, Visual Studio Code has a similar "Go to File" command using <kbd>Ctrl</kbd> + <kbd>P</kbd>: https://code.visualstudio.com/docs/getstarted/keybindings#_navigation

**Comment by davidhpark** [comment]
Ah, thank you. That works for me.
