### ISSUE TITLE
The editor cannot be used while compiling

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#2187]
_From @haf on April 22, 2017 9:55_

- VSCode Version: 1.11.2
- OS Version: 10.11.6

Steps to Reproduce:

1. Edit an F# project for a long time using the `vscodevim` plugin
2. Start a compilation
3. While compiling, switch to VSCode
4. The edit-mode doesn't work.

Steps to Reproduce 2:

1. Edit an F# project for a long time using the `vscodevim` plugin
2. Press CMD+S, to save
3. Try to press `i` for insert; the cursor doesn't change.

Can I enable tracing and timing information to be output to the developer console, somehow? This is really disruptive for my flow. ;)

_Copied from original issue: Microsoft/vscode#25183_

**Comment by rebornix** [comment]
_From @jpoon on April 25, 2017 18:55_

What happens with all extensions disabled?

**Comment by rebornix** [comment]
_From @haf on April 25, 2017 21:26_

I don't know, because then I can't use the editor to do any work. This problem only happens once in a while. I can extract any information you want when it does happen though.

**Comment by rebornix** [comment]
_From @haf on April 28, 2017 14:1_

PIng

**Comment by rebornix** [comment]
_From @haf on April 28, 2017 14:16_

Maybe I can run a command that tells us what addon takes the mutex on the buffer? Any way of debugging this? I strongly suspect that ionide is the culprit, but it's not the easiest thing to debug...

**Comment by rebornix** [comment]
_From @haf on May 3, 2017 10:17_

Ping

**Comment by jpoon** [comment]
More information is needed. I'm going to close this issue for the time being, but if you have more details, please share and re-open.

**Comment by haf** [comment]
@jpoon Yes; closing it is fine; it's an old issue that has resolved itself.
