### ISSUE TITLE
recording macros don't display in bottom bar with mssql extension

### ISSUE THREAD

**Issue by hmendozap** [VSCodeVim/Vim#2188]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Environment**:

- **VSCode Version**: 1.18.1 Stable
- **VsCodeVim Version**: 0.10.5
- **OS**: Windows

- **mssql Extension Version**: 1.2.1

**What happened**:

Recording of macro, by pressing q and a to store macro `@a`, is not displayed inside a sql file

![capture_vscode_bug_norecording](https://user-images.githubusercontent.com/7848378/33493567-111c2f58-d686-11e7-8453-d505b89713ac.PNG)

**What did you expect to happen**: 

To have info that I was recording a macro like this: 
![capture_vscode_bug](https://user-images.githubusercontent.com/7848378/33493549-07fc6fd2-d686-11e7-9a90-731c7ca2eb57.PNG)
![capture_vscode_bug_recording](https://user-images.githubusercontent.com/7848378/33493554-0c5612cc-d686-11e7-9ec1-f88065bd5cee.PNG)

**How to reproduce it**:
Enable mssql extension. Edit a sql file, try to create a macro by pressing q

**Comment by jpoon** [comment]
Is it because of lack of real estate? what happens when you zoom out?

**Comment by jpoon** [comment]
Closing as there hasn't been much traction with this issue.
