### ISSUE TITLE
Bug - cannot create or rename a new file or folder in Explorer tab - typing broken

### ISSUE THREAD

**Issue by aCuteLittleBox** [VSCodeVim/Vim#2189]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Environment**:

- **VSCode Version**: 1.19.0
- **VsCodeVim Version**: v0.10.5
- **OS**: Linux (Solus 3 Budgie, version 3.26.2)

**What happened**:
When using the 'New File' button in the Explorer tab, typing any of: g, o, j, or k will cause vim to jump in and attempt to interpret a command. Any new file created with this button cannot use those letters because of this.
Typing "g" will cause vim to wait for a motion, however any proper or improper command will do nothing, while o seems to do nothing but not print the character and j and k behave like the arrow keys, described below.

Arrow keys also do not work properly, meaning when trying to change a file name inside VSCode you must delete the entire filename since this is highlighted automatically when you right click and select "Rename file". Instead, the arrow keys seem to be highlighting other files and folders in the list.

If you try creating a new file such as "average.cpp", the file will be named "avera.cpp" and the message "The key combination (G, E) is not a command" will appear in the bottom left. (see screenshot)

This also happens when creating or renaming folders.

**What did you expect to happen**: 
I expected to be able to type unrestricted, and to be able to use the arrow keys to move through the filename.

**How to reproduce it**:
open up the Explorer tab, hit the 'New File' or 'New Folder' button, and try typing any word containing any or all of: g, o, j, or k. Also hit the arrow keys and notice the cursor does not move. Look for different files and folders being highlighted in the background.

![screenshot from 2017-12-01 15-30-19](https://user-images.githubusercontent.com/33563447/33506361-d105dffa-d6ac-11e7-915f-a4fb8578f6b2.png)

**Comment by jpoon** [comment]
Possible duplicate of: https://github.com/VSCodeVim/Vim/issues/2177 which was caused by a regression with VSCode.

**Comment by markovicdenis** [comment]
Had this error too (insiders build), but it seems like it got fixed with new update.

**Comment by aCuteLittleBox** [comment]
if it's fixed in a later build, then I'll just close the issue and wait for the update. Thanks :)
