### ISSUE TITLE
ctrl+v and G and $ does not select the end of all lines

### ISSUE THREAD

**Issue by shinokada** [VSCodeVim/Vim#2190]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Environment**: macOS High Sierra 10.13.1

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: v0.10.5
- **OS**: macOS High Sierra 10.13.1

**What happened**:

ctrl+v and G and $

**What did you expect to happen**: 

Select the end of all lines

**How to reproduce it**:

I have to move the cursor to the end of the longest line.

**Comment by tyru** [comment]
This seems to work now.

**Comment by jpoon** [comment]
Yep, can't repro this on `master`.
