### ISSUE TITLE
Count prefix does not affect repeat with `.`

### ISSUE THREAD

**Issue by jsermeno** [VSCodeVim/Vim#2192]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**: macOS Sierra 10.12.6

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: 0.10.5
- **OS**: macOS Sierra 10.12.6

**What happened**: Repeat with `.` happens once regardless of count prefix.

**What did you expect to happen**: Repeat with `.` and a `n` count prefix should repeat `n` times. 

**How to reproduce it**: `ia<esc>5.` should produce `aaaaaa`. Instead `ia<esc>5.` currently produces `aa`.

**Comment by ryuheechul** [comment]
Yeah I'm experiencing the same issue and hoping to discover a way to work on it or workaround

**Comment by yyn19951228** [comment]
I would like to try to fix this issue
