### ISSUE TITLE
Macro doesn't support commands

### ISSUE THREAD

**Issue by EdenGottlieb** [VSCodeVim/Vim#2193]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:

- **VSCode Version**:
1.18.1
- **VsCodeVim Version**:
0.10.5
- **OS**: 
Mac OS X High Sierra
**What happened**:

qa (start recording at a)
:s/stringToReplace/newString/g
<ENTER>

Then, @a to try and run the macro. 
**What did you expect to happen**: 
I expected it to run the macro (replace all stringToReplace with newString).

Actual: The command window opened, empty, and nothing else happened. 
**How to reproduce it**:
Do what I said.

I tried finding matching issues but couldn't find any, please reference me to them if this is a duplicate.

Thanks a lot!

**Comment by J-Fields** [comment]
@jpoon this seems to have been fixed
