### ISSUE TITLE
Enabling vscodevim causes 30% spike in CPU usage

### ISSUE THREAD

**Issue by neilbalch** [VSCodeVim/Vim#2195]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Environment**: Acer E5-575 Laptop, (i5-6200) Windows 10

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: 0.10.5
- **OS**: Windows 10

**What happened**: Installing the extension causes the VS Code process to use 50% CPU time up from ~5-8% before installing vscodevim.

**What did you expect to happen**: CPU usage shouldn't rise significantly because of enaling this extension.

**How to reproduce it**: Go to the Extensions tab and install or enable vscodevim.

This doesn't make much sense because I have been using vscode and vscodevim on my machine for at least 4 months and this has never happened before. I have also tried uninstalling vscode and deleting every vscode related file in `Program Files`, `AppData` and the `.vscode` directory in the user folder and then re-installing. Nothing changes this behavior. Disabling vscodevim after installation results in CPU usage returnign to normal, and re-enabling it makes CPU usage rise again.

I have no idea what might be causing this to happen. Any more info required I will give. I really like vscodevim, when it works that is.

**Comment by BahJIy** [comment]
This too happens on my Linux box.

**VSCode Version:** 1.81
**VSCodeVim Version:** 0.10.5
**OS:** Arch Linux 4.13

It appears like the status bar color setting maybe causing the issue. Disabling the color control seems to restore VSC CPU usage quicker. 
With the status bar color disable, CPU usage seems normal after the initial load. With status bar color enable, I have to go to the setting.json page, let VSC process for a bit and then it will restore normal CPU usage, else the CPU will continue to have high usage.

**Comment by jpoon** [comment]
We have a bunch of existing issues about perf and it's mainly around the status bar color or neovim. Closing this in favor of https://github.com/VSCodeVim/Vim/issues/2124.
