### ISSUE TITLE
Support for omap-param plugin

### ISSUE THREAD

**Issue by fly1n** [VSCodeVim/Vim#2196]
I found omap-param plugin was pretty useful to do parameter level edit. Can you add support for this plugin?

**Comment by J-Fields** [comment]
Could you link to the plugin you're referring to?

**Comment by fly1n** [comment]
https://github.com/LucHermitte/lh-cpp/blob/master/plugin/omap-param.vim

**Comment by J-Fields** [comment]
#2338
