### ISSUE TITLE
Renaming files in file tree blocks navigational keys

### ISSUE THREAD

**Issue by MrYakobo** [VSCodeVim/Vim#2200]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

BUG REPORT

**Environment**:

- **VSCode Version**: 1.19.0
- **VsCodeVim Version**: v0.10.5
- **OS**: Solus 

**What happened**:
File/folder was not renamed, input was blocked upon pressing navigational keys.

**What did you expect to happen**: 
Rename the chosen file/folder to hjklggG

**How to reproduce it**:
F2 in filetree
hjklggG

----

Comment: It seems like navigating in the file tree would be a good idea, but during input (renaming, creating new file etc) navigational keys (hjkl,gg,G) should be disabled.

**Comment by jpoon** [comment]
Can't repro this. I go to the file explorer, can navigate with either j or k. Press 'enter' to rename file to whatever. Press 'enter' to finish rename. Then can continue to navigate with j or k.

**Comment by aig787** [comment]
- VSCode Version: Code - Insiders 1.19.0-insider (951f5a20fc820e32a65ca05bb87af86f65027470, 2017-12-12T10:28:32.976Z)
- OS Version: Darwin x64 17.3.0

Running into the same issue.

Steps to repro:
Right click file in file tree, select rename. Try to name it anything with navigation keys and the edit file name box stays but highlight changes based on the navigation key.

**Comment by roganartu** [comment]
- VSCode Version: 1.19.0 (1.19.0) (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T09:46:55.436Z)
- VSCode Vim Version: 0.10.5
- OS Version: macOS 10.13 (17A405)

This only started happening for me recently afaik. I can repro it both by right-click renaming and by navigating to the file and hitting enter.

File renaming works as expected after disabling the vscode vim extension.

**Comment by marktellez** [comment]
It is happening for me as well. If I try to name a new file

```
index.jsx
```

The j doesn't go into the filename because it is navigating down. When in file/directory create, the navigate keys should be disabled for navigation.

**Comment by jpoon** [comment]
This has been fixed with https://github.com/VSCodeVim/Vim/pull/2213, and with 1.19 being released, this bug has become visible. We need to push out a new release.

**Comment by jpoon** [comment]
Build in-progress. Assuming everything is green -- new release is imminent.

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/releases/tag/v0.10.6

**Comment by aig787** [comment]
Thanks @jpoon!

**Comment by jpoon** [comment]
All credit goes to @joaomoreno. My bad for not releasing the fix before the VSCode update.

**Comment by brentvatne** [comment]
this is still a problem for me with vscode 1.19.3 and vscodevim 0.10.13. same repro steps a the reports above
