### ISSUE TITLE
Macros slow down with each iteration

### ISSUE THREAD

**Issue by daveriedstra** [VSCodeVim/Vim#2202]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Environment**:

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**:  0.10.5
- **OS**: Windows 10

**What happened**:
medium-length q macros lose speed with each iteration, making them (painfully/hilariously) difficult to use after about 10-15 repeats. Exact keys: `qd` _some editing_ `8@d`

**What did you expect to happen**: 
the macro should play back with the same speed each iteration

**How to reproduce it**:
- record a macro
- replay it over 10+ lines

example over 8 iterations (really noticeable in final 2):
![vscodevim-macro](https://user-images.githubusercontent.com/3504098/33684225-692e082e-da82-11e7-9ddc-10d7f1b8db9a.gif)

**Comment by artvinn** [comment]
Having the same issue in

- VSCode Version: 1.20.0
- VsCodeVim Version: 0.10.13
- OS: macOS High Sierra (10.13.2)

**Comment by J-Fields** [comment]
There have been a number of performance improvements over the last several months, especially when repeating actions & executing macros. Has anyone noticed that this is still a problem?

**Comment by J-Fields** [comment]
I think this has improved over time to the point that it's no longer an issue, and the next release should be even more consistent - please let me know if anyone still notices this.
