### ISSUE TITLE
different key bindings for normal and visual mode

### ISSUE THREAD

**Issue by phush0** [VSCodeVim/Vim#2205]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**FEATURE REQUEST**:

Add different key bindings for normal and visual mode to simulate:
`nnoremap` and `vnoremap` in VIM

**Comment by jpoon** [comment]
PR here #2726. But we are debating what we would do with otherModesKeybindings:

    leave the behaviour the same so it handles normal/visualmode keybindings
    rename it to normalModesKeybinding and have it only handle normal mode.

(2) would be a breaking change as everyone's configs would need to get updated. Would love to hear your opinions.

I'm also going to use #2705 to track so will close this issue.
