### ISSUE TITLE
Joining multiple lines with `gJ` deletes all lines past 2nd line

### ISSUE THREAD

**Issue by jsermeno** [VSCodeVim/Vim#2207]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**: macOS Sierra 10.12.6

- **VSCode Version**: 1.18.1
- **VsCodeVim Version**: 0.10.5
- **OS**: macOS Sierra 10.12.6

**What happened**: Joining multiple lines with `gJ` deletes lines all but the first two lines. For example, the input
```
a
b
c
d
e
```
with the keys `5gJ` will produce the output `ab`.

**What did you expect to happen**: For the input
```
a
b
c
d
e
```
and the keys `5gJ` I expected the output `abcde`.

**How to reproduce it**: An empty file with the input above and the keys above.

**Comment by chris-morgan** [comment]
This is still an issue, and is not the only problem with `gJ` with count: it also operates upon one too many lines, e.g. `2gJ` should be the same as `1gJ` or `gJ`, but in actual fact causes line three to disappear.
