### ISSUE TITLE
Vim shortcuts leak to sidebar

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#2209]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT** (choose one):

**Environment**:

- VSCode Version: Code - Insiders 1.19.0-insider (d8989c95964ce06c64ffebc2fb400a0327bd447d, 2017-12-08T10:09:06.896Z)
- OS Version: Darwin x64 17.3.0

**What happened**:
When trying to create/rename files/folders I cannot type o or h,j,k,l because the cursor will move in the background or skip out of the action completely just like being in the editor

**What did you expect to happen**: 

**How to reproduce it**:

**Comment by jpoon** [comment]
Is it the same issue as this? https://github.com/VSCodeVim/Vim/issues/2177

**Comment by bm-stschneider** [comment]
Yes it is.

**Comment by jpoon** [comment]
I'm not running insiders atm so can't confirm, but looks like it's been resolved upstream so will close this issue.
