### ISSUE TITLE
All configuration of the vim plugin is automatically reset

### ISSUE THREAD

**Issue by cnlg** [VSCodeVim/Vim#2218]
Steps to Reproduce:

1.Configure vim in settings.json and save it
2.Open two vscod windows
3.Feel free to edit the file
4.Often, all configurations of vim are automatically reset

**Comment by jpoon** [comment]
1) Please fill the issue template
2) Cannot repro. We also don't manage the saving and loading of the config file -- this is managed by VS Code. What about the other non-vim configs?

**Comment by jpoon** [comment]
Closing as I haven't heard back. Feel free to re-open with the needed information.
