### ISSUE TITLE
Cannot create a GoLang file(.go) from the explorer.

### ISSUE THREAD

**Issue by sus007** [VSCodeVim/Vim#2219]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
> BUG REPORT

**Environment**:

- **VSCode Version**: 1.19.0-insider
- **VsCodeVim Version**: 0.10.5
- **OS**: Windows 10 Pro Insider Preview

**What happened**:
> While trying to create a GoLang file from the explorer with Vim Plugin enabled, typing `.go` (*file extension for Go file*) triggers 'g' navigation command of Vim disallowing me to create a `.go` file.

**Comment by jpoon** [comment]
Sounds like a dupe of https://github.com/VSCodeVim/Vim/issues/2200
