### ISSUE TITLE
Escape replace mode with <C-[>

### ISSUE THREAD

**Issue by deybhayden** [VSCodeVim/Vim#2221]
https://github.com/VSCodeVim/Vim/blob/113dd77978b739ec27e34fe8fcdb87706a0be2e1/src/actions/commands/actions.ts#L529

Hey there, is it reasonable to add `<C-[>` to the `CommandEscReplaceMode.keys` array? Don't know if it's just an oversight of if there's a Vim or VS Code reason not to.

**Comment by jpoon** [comment]
Oversight. Feel free to submit a PR.
