### ISSUE TITLE
* command is messing up with capital letters

### ISSUE THREAD

**Issue by autlunatic** [VSCodeVim/Vim#2222]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **Version 1.18.1**:
- **0.10.5**: 
- **Ubuntu 16.04 LTS**: 

"*" command does find the same words which a capital letter and from there on it is matching the exact word:

e.g. pressing * on the first test of the following text finds Test pressing again finds the next Test and test is not found anymore

```
this is a test for Test the * command in vscodvim 
the problem is when i press * on the first test it finds Test and from there on it only finds Test
```
the same problems exists if i have an tEst instead of Test it finds this one too

**What did you expect to happen**: 
jumping to the next word test and not Test

**How to reproduce it**:
the text provided in the code section is a text where you can easily reproduce just press * on the first "test" vscode will jump to Test and won't find the test in the second line

**Comment by autlunatic** [comment]
Maybe this is already solved - it works when i turn off smartCase option

**Comment by jpoon** [comment]
Seems like its working as intended then.
