### ISSUE TITLE
Vim Extension won't Load

### ISSUE THREAD

**Issue by lbollar** [VSCodeVim/Vim#2226]
Mac 10.12.6
vscode 1.19.0
vim 0.10.6

I had to do a reinstall of vscode due to a corrupt installation and I cannot get vscode to recognize the vim extension. I have tried deleting extensions folder and installing again and reloading but it just doesn't activate when I start vscode. I wonder if this might be a permissions issue. 

Happy to provide more details, just not really sure where to start looking for problems.

**Comment by takano-ex** [comment]
Same with me, just after updating VSCode to 1.19.0

Mac 10.13.1
VSCode 1.19.0
VSCodeVim 0.10.6

**Comment by jpoon** [comment]
Are you seeing this with just the VIM extension? Only suggestion is to try to delete the extensions folder -- ~/.vscode/extensions and try reinstalling.

**Comment by takano-ex** [comment]
@jpoon Thanks! Solved by deleting the extensions folder and re-installing VSCodeVim (and then other extensions as needed), in my case.

**Comment by kriscoleman** [comment]
I was having a hell of a time with this - I really didn't want to delete my entire extensions folder and have to reinstall/configure everything again... 

I tried uninstalling and reinstalling the vim extension only, and this seemed to work. 

I anticipate I'll encounter this issue again and have to uninstall/reinstall the extension. This pattern suggests to me that there is a bug somewhere in this extension.

**Comment by jpoon** [comment]
You don't need to delete the *entire* extensions folder. Just ~/.vscode/extensions/vscodevim will do. The upstream fix (https://github.com/Microsoft/vscode/issues/40260) was included in VS Code 1.20+ so please ensure you are on the latest version of VS Code.

**Comment by tekdroid** [comment]
The suggested solutions didn't work for me. I had to revert to 1.0.7 to get it to work. 1.0.8 and 1.1.0 do not work at all for me.

IMHO this is not resolved. I'm still experiencing the issue on the newest version of the plugin.
