### ISSUE TITLE
vim 0.10.6 not work

### ISSUE THREAD

**Issue by VinceFanZ** [VSCodeVim/Vim#2227]
vscode version: 1.19.0
OS: macOS 10.13.2 

not work

**Comment by Nexmean** [comment]
Have you tried to reinstall it? Sometimes plugins in VS Code stop working after updating, to fix it you shoud reinstall plugin.

**Comment by VinceFanZ** [comment]
ok , thx!

**Comment by jpoon** [comment]
In the future, please fill out the template. Debugging issues like "it does not work" is pretty difficult...
