### ISSUE TITLE
Feature request: Use h and l in sidebar to expand/fold folder

### ISSUE THREAD

**Issue by kkorus** [VSCodeVim/Vim#2230]
It's nice that I can navigate in sidebar using vim commands like `j,k, gg, G` but I wish I could expand/fold folders using `h,l`.

**Comment by kkorus** [comment]
It could solved using list commands:
![image](https://user-images.githubusercontent.com/2054009/34071866-5bb2687a-e275-11e7-80b2-ae38d6b8e00c.png)
So I think it solves my issue, but it would be nice if it would be by default in plugin.

**Comment by jpoon** [comment]
Feel free to submit a PR. Should be a fairly straightforward fix to add this to our package.json
