### ISSUE TITLE
HTML Files - Insertion Point moves to the end of the file

### ISSUE THREAD

**Issue by triggar** [VSCodeVim/Vim#2236]
When using some commands in VS Code Mac (Version 1.19.0) the insertion point moves to the end of the file.

This is occurring in HTML files and not TS files in the same session in VS Code

Commands that I've seen this happen with:
- cw (change word)
- i (insert mode)
- w (write file)
- ESC

When in Insert mode the cursor does not move until you exit 
When using cw the cursor moves after about 1sec and the insertion point moves to the end of the file - words typed are added to the end of the file.

**Comment by jpoon** [comment]
Please fill in the template. Specifically the instructions for creating a repro.

```
**What happened**:

<!--
Exact keys you pressed.
-->

**What did you expect to happen**: 

**How to reproduce it**:
```

**Comment by triggar** [comment]
**WHAT HAPPENED**
When using some commands in VS Code Mac (Version 1.19.0) the insertion point moves to the end of the file.

This is occurring in HTML files and not TS files in the same session in VS Code.

It seems to be when you stop typing for more than 1 sec - then the cursor jumps.

**What did you expect to happen**: 
When editing and saving I expect the insertion point to remain at the current location until I move it.

**How to reproduce it**:
Create a simple HTML file:
`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Title of the document</title>
</head>

<body>
Content of the document......
</body>

</html>`

Use cw or ct< or other command  to change the title of the page.
The insertion point jumps from where you are editing to the end of the file.
Seems to be  happening in most editing modes

**Comment by jpoon** [comment]
Negative. Not repro-ing with 1.19.0 and vim extension 0.10.6. Can you share HTML file?

**Comment by triggar** [comment]
I've attached a Screen Recording of it happening - hopefully it makes sense.
Also is the html file I'm using for this test.

[VimTest.html.zip](https://github.com/VSCodeVim/Vim/files/1574307/VimTest.html.zip)



[VimPluginProb.mov.zip](https://github.com/VSCodeVim/Vim/files/1574305/VimPluginProb.mov.zip)

**Comment by triggar** [comment]
Sorry - looks like this is happening with the VSCodeVIM plugin disabled.

Any ideas? I'd appreciate it.

Cheers,
Rob

**Comment by triggar** [comment]
Ok - seems like the auto formatting in VSCode was causing it.   I've switched off the format while typing and format on save. Seems to have fixed it.
Thanks for your time!
