### ISSUE TITLE
Bug Report: can't use quote character in vim.insertModeKeyBindings

### ISSUE THREAD

**Issue by matt-James** [VSCodeVim/Vim#2239]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- VSCode Version: Version 1.19.1 (1.19.1)
- OS Version: 10.13.1

Steps to Reproduce:

1. Add a mapping to vim.insertModeKeyBindings that uses a quotation mark (escaped by \) eg. "_d
2. Binding doesn't seem to work

Reproduces without extensions: Yes/No

<img width="247" alt="vscode" src="https://user-images.githubusercontent.com/34668096/34316393-6bba74a0-e749-11e7-8bfb-e751f270761c.png">

**Comment by jpoon** [comment]
Can you try using single quotes? 

```
 "after": ['\_d']
```

**Comment by matt-James** [comment]
@jpoon No luck. JSON doesn't work with single quotes. Looks like Vim must be including the escape \ as part of the sequence so vim doesn't recognize the "_d binding. Any thoughts are appreciated. 

I want to use "_d to stop the behavior of dd saving to the clipboard and overwriting my yanks. In Vim yanks get saved to the 0 registry so you can access yanks with 0p. Alternately does anyone know how to make the 0p command work in VSCode Vim. It doesn't look like VSCode Vim has access to registries. Is this assumption correct?

**Comment by jpoon** [comment]
Wait a minute, I read this issue wrong the first time around. This accepts an array of characters...

```
  "vim.insertModeKeyBindings": [
    { 
      "before": ["d", "f"],
      "after": ["\"", "_", "d"],
    }
  ]
```
