### ISSUE TITLE
"S" (capital s) does not behave properly when on prefixing whitespace

### ISSUE THREAD

**Issue by kyleholzinger** [VSCodeVim/Vim#2240]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

This is a bug report
**Environment**:

- **VSCode Version**: 1.19.1
- **VsCodeVim Version**: 0.10.6
- **OS**: macOS

**What happened**:

In vim when you click `S` (capital s) in normal mode, it should clear the line and place your character into insert mode at the appropriate indentation level. This works properly when you click `S` somewhere in the middle of the line, but if you click `S` anywhere inside of the prefixing whitespace of a line, it does not go to the proper indentation level. Here's an example:

```javascript
const a = {
  b: 10,
| c: 40
}
```
Say my cursor is where that `|` is (that's not an actual character, I just wanted to represent the cursor). If you click `S`, it _should_ clear that line and place you in insert mode at indentation level 1, however what happens currently in VSCodeVim is it will clear the line and go into insert mode, however not go to the appropriate indentation level. If my cursor is say, on the `4` instead of on the `|`, when you click `S` it will indeed clear everything from `c` onwards and put you into insert mode at the correct indentation level, however.

P.S. Sorry if this is a duplicate of another issue! It was relatively difficult to search through the others, as I can't simply just search for `S` 😂

**Comment by aldanor** [comment]
Are there any updates to this? We can't be the only two who noticed it...

**Comment by kyleholzinger** [comment]
You'd think so, I'm surprised more people aren't bothered by this

**Comment by kyleholzinger** [comment]
Looks like it was in this commit https://github.com/VSCodeVim/Vim/commit/32e61212. Closing! 🎉 🎆 🙏
