### ISSUE TITLE
c+number+gg is not working as excepted

### ISSUE THREAD

**Issue by cckowin** [VSCodeVim/Vim#2245]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.19.0
- **VsCodeVim Version**: 0.10.6
- **OS**: windows 7

**What happened**:

edit a fie like this in normal mode, cursor is at `^`
````
1 hello
  ^
2 hello
````
after use command `c2gg`, it become this
````
1 |
2 hello
````

**What did you expect to happen**: 
what i wish is just like vim, like this
````
1 |
````

**How to reproduce it**:

**Comment by J-Fields** [comment]
Seems this now changes up to the start of the given line, which still isn't quite right. I'll try to take a look when I get the chance.

**Comment by J-Fields** [comment]
This has been fixed.
