### ISSUE TITLE
how change `0` to `^`?

### ISSUE THREAD

**Issue by gatspy** [VSCodeVim/Vim#2246]
**Environment**:

- **VSCode Version**: `1.19.1`
- **VsCodeVim Version**: `0.10.6`
- **OS**: osx `10.12.6`

**What happened**:
i want to change `0` goto the first non-blank character of the line .
The following settings have no effect.

```json
    {
      "before": [
        "0"
      ],
      "after": [
        "^"
      ]
    }
```

**Comment by jpoon** [comment]
Just tried this and it works.

```
    "vim.insertModeKeyBindings": [
        {
            "before": [ "0" ],
            "after": [ "^" ]
          }
    ]
```

**Comment by gatspy** [comment]
In my `User Settings` file, made the following settings, but no effect.

```json
"vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": [
        "0"
      ],
      "after": [
        "^"
      ]
    }
]
```
