### ISSUE TITLE
Text width ignored when wrapping

### ISSUE THREAD

**Issue by viraptor** [VSCodeVim/Vim#2247]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Environment**:

- **VSCode Version**: 1.19
- **VsCodeVim Version**: 0.10.6
- **OS**: MacOS / high sierra

**What happened**:

Set the text width to 72:
`:set tw=72`
Select some lines:
`V (down) (down)`
Wrap them:
`gq`

Lines got wrapped to 80 characters.

**What did you expect to happen**: 

Lines wrapped to 72 characters.

**Comment by jpoon** [comment]
It is set in memory, but never actually written to the user settings. Only repros for configs that are *not*  `overlapSetting` as for those configs, they come with a setter that saves the configs.

**Comment by jpoon** [comment]
Quasi-fixed with https://github.com/VSCodeVim/Vim/pull/2243/commits/56bb40971f6e0a94d5fac59548f40173d86e0caa. Displaying error message on failed cmd's instead.
