### ISSUE TITLE
Mac buffer not available 

### ISSUE THREAD

**Issue by idoo** [VSCodeVim/Vim#2255]
** BUG REPORT** (choose one):

**What happened**: 
mac/vim buffer are separated

**What did you expect to happen**:
When I press `CMD+C` and then press `p` I expect that content that has been copied by `CMD+C` would be pasted after I pressed `p`
Same happens, when I'm trying paste content that has been copied outside VSC

**How to reproduce it (as minimally and precisely as possible)**:
select text, `CMD+C`, `p`

**Environment**:

- Extension (VsCodeVim) version: 0.10.6
- VSCode version: 1.19.1
- OS version: MacOS

**Comment by jpoon** [comment]
Have you played around with these settings:

https://github.com/VSCodeVim/Vim#vimoverridecopy
https://github.com/VSCodeVim/Vim#vimusesystemclipboard

**Comment by idoo** [comment]
@jpoon thank you `"vim.useSystemClipboard"` fully solved my pain
