### ISSUE TITLE
[Suggestion] find and til to search across lines

### ISSUE THREAD

**Issue by zhiwei-nu** [VSCodeVim/Vim#2256]
Right now `find` and `til` motions only work for a single line (doesn't search more than the current line for the character), will there be support for searching across lines?

**Comment by jpoon** [comment]
Can you fill out the issue template and give an example?

**Comment by zhiwei-nu** [comment]
@jpoon alright!

**What happened**:
![image](https://user-images.githubusercontent.com/27188482/34513199-f9846ffa-f0a1-11e7-9ac1-f719a5bee19a.png)
pressing `Shift + f` then `E` here does nothing, because `f` and `t` does not search across lines. 

**What did you expect to happen**:
the cursor should move up to the line above, onto the `E` at `Enrollment` like so:
![image](https://user-images.githubusercontent.com/27188482/34513259-6c27886c-f0a2-11e7-968f-650d33fa2c31.png)


**How to reproduce it (as minimally and precisely as possible)**:
just use `f` or `t` to jump to characters across lines

**Environment**
- Extension (VsCodeVim) version: latest
- VSCode version: latest

**Comment by jpoon** [comment]
I'm not familiar with what `shift+f` is supposed to do. I tried your sample code and instructions with vanilla vim 8.0 and it does nothing. Can you link to the vim help?

**Comment by zhiwei-nu** [comment]
@jpoon just discovered that this behavior doesn't exist in vanilla vim, thanks for pointing it out! 

`F` searches for a character backwards while `f` searches forward. In spacemacs' vim mode it works across multiple lines and I wrongly assumed that it's the behavior in vanilla vim

In any case, since this is a deviation from normal Vim feel free to close it, I'll stick to vim-easymotion for now. Thanks for the great work!

**Comment by jpoon** [comment]
> since this is a deviation from normal Vim feel free to close it

closing it as such
