### ISSUE TITLE
auto change to normal mode

### ISSUE THREAD

**Issue by colinlabs** [VSCodeVim/Vim#2259]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
vscodevim is auto change to normal mode when i use mouse select some text

**What did you expect to happen**:
not change to normal mode

**How to reproduce it (as minimally and precisely as possible)**:
always reproduce in my environment

**Environment**:
- Extension (VsCodeVim) version:  0.10.6
- VSCode version: 1.19.1
- OS version:  MAC 10.13.2 and 10.12.6
  
![look at gif](https://user-images.githubusercontent.com/10361796/34523546-e64df31c-f0d2-11e7-9fd9-c057ebf627c0.gif)

**Comment by colinlabs** [comment]
my settings:
```  
    "vim.leader": "<space>",
    "vim.easymotion": true,
    "vim.incsearch": true,
    "vim.useSystemClipboard": true,
    "vim.useCtrlKeys": true,
    "vim.hlsearch": true,
    "vim.mouseSelectionGoesIntoVisualMode": false,
```

**Comment by jpoon** [comment]
Current Behaviour: mode does not change following a cursor select
Expected Behaviour: change to visual mode

**Comment by colinlabs** [comment]
1. **inserver mode** select text change to normal mode, can not copy text
2. **visual mode** also

**Comment by jpoon** [comment]
Interesting, I can't repro this anymore with 0.10.8. Please re-open if you see otherwise.

**Comment by colinlabs** [comment]
@jpoon  sorry, in my environment(both MAC 10.13.2 and 10.12.6)，always see this, can't copy and select text.

**Comment by colinlabs** [comment]
1. uninstall vscode and clean folder **.vscode**
2. remove folder **.vimrc**
3. reinstall latest version
4. install **vscodevim** extension
5. MAC 10.12.6 always appear this,  in 10.13 appear sometimes.
