### ISSUE TITLE
Default bindings for insert mode clobber normal mode bindings that enter insert mode

### ISSUE THREAD

**Issue by Lindenk** [VSCodeVim/Vim#226]
Entering a mode through a keybinding is currently handled by the mode to be changed to rather than the mode the key is pressed from. This is causing an issue when keybindings used to enter insert mode are overridden by normal mode bindings.

For instance, consider the following configuration:

```json
{
    "vim.insertModeKeybindings": {
        "e": "InsertAtCursor"
    },
    "vim.normalModeKeybindings": {
        "i": "MoveUp"
    }
}
```

The expected behavior is that the `e` key will enter insert mode at the current cursor position and the `i` key will move up a line, when in normal mode. However, because the default binding for the `i` key is never overritten in the _insert mode_ keybindings, when doing a check to see if insert mode should be entered, the `i` key will trigger an insert, specifically a `InsertAtCursor` action, and never make it to the normal mode actions.

Ideally, any keybindings for keys pressed from within a mode should be handled by that mode.

**Comment by bradyholt** [comment]
Yes, this breaks `ciw` in normal mode as well because the moment you type the `i` you are put into insert mode immediately.

**Comment by johnfn** [comment]
We now have a new way of doing remapping.
