### ISSUE TITLE
Inside range off by one character when final line is indented

### ISSUE THREAD

**Issue by royaldark** [VSCodeVim/Vim#2270]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**What happened**:

Given a snippet like this:

```
  ([
  ])
```

Press `di(` while inside the parentheses. This gives the following:

```
  (  ])
```

**What did you expect to happen**:

Should give the following:

```
  ()
```

**How to reproduce it (as minimally and precisely as possible)**:

The bug seems to happen only when all of the following conditions are true:

1. Have parens, brackets, etc. which are a target for `i` commands
2. Range must be split across multiple lines
3. Final line of range consists solely of whitespace, a single non-range character, and the closing range character

That is, the following do NOT reproduce the issue:
```
  ([])
```

```
  ([
])
```

```
([
])
```

```
([
4])
```

But the following DO:

```
  ([
  ])
```

```
([
  ])
```

```
  ([
      4
  ])
```

```
  (a
  b)
```

**Environment**:

- Extension (VsCodeVim) version: 0.10.7
- VSCode version: 1.19.1
- OS version: Ubuntu 17.10

**Comment by jpoon** [comment]
Thanks for trying to repro all these bugs @tyru  :)
