### ISSUE TITLE
At a certain point VSCodeVim "forgets" all remappings for every new tab opened

### ISSUE THREAD

**Issue by ohjames** [VSCodeVim/Vim#2271]
This is a bug

**What happened**:
Since a recent update I'll open a tab and none of my key remappings will work. From this point on every new tab will fail to support my remappings. At this point I have to "Reload Window" to make VSCodeVim work again. This has started happening very frequently.

**What did you expect to happen**:
VSCodeVim should not forget my mappings.

**How to reproduce it (as minimally and precisely as possible)**:
Set up some mappings and use the latest VSCodeVim for a while, judging by how frequently this is happening to me it'll eventually happen to you too.

- Extension (VsCodeVim) version: 0.10.8
- VSCode version: 1.19.1
- OS version: Arch Linux

**Comment by ohjames** [comment]
Everytime this has happened to me it's been after loading a file via "ctrl-P", but most of the time that seems to work fine.

**Comment by jpoon** [comment]
Nope, still can't repro using `ctrl+p`

**Comment by ohjames** [comment]
I use ctrl-p hundreds of times per day and this issue only happens about twice per day, it's not easy to trigger.

**Comment by jpoon** [comment]
When you find a consistent repro, please share. As at this point, it's difficult to debug.

**Comment by ohjames** [comment]
@jpoon I've found out how to "consistently" reproduce it now.

1. use :qa to close all tabs
2. use ctrl-P and open a new file
3. check if your key mappings still work, at this point there is a roughly 10% chance they won't

Repeat 1-3 until it fails. I tried it 30 times and 3 of the times my keybindings were gone.

**Comment by ohjames** [comment]
This got trigger just now when I was switching tabs. It's the first time I've noticed that, and it still triggers several times per day when opening a new file using ctrl-P.

**Comment by ohjames** [comment]
Can you remove "status/needs-more-info".

**Comment by jpoon** [comment]
I've tried your new repro steps, still can't repro this on my end.

**Comment by ohjames** [comment]
I'm using the latest extension and Code yep, I'll see if I can see `--NORMAL--` in the status bar next time it happens, which most likely will be tomorrow. Maybe it's related to the specific key bindings I'm using somehow. I use ctrl-l for tabprev and ctrl-u for tabnext, and a bunch of stuff for colemak.

**Comment by ohjames** [comment]
Okay just happened again, and yeah it said `--NORMAL--` in the status bar.

**Comment by jpoon** [comment]
Unfortunately, we don't have enough information to figure out what's going on particularly as I can't get a repro working on my end.

We've added more logging to the extension to help debug issues like this: https://github.com/VSCodeVim/Vim#vimdebuglogginglevel. Please turn this on and you'll see stuff like:

```
debug: ModeHandler: handling key=0.
index.js:25
debug: Remapper: normalModeKeyBindingsNonRecursive. before=0. after=<:wq>. 
index.js:25
debug: Remapper: normalModeKeyBindingsNonRecursive. match found. before=0. after=<:wq>. command=undefined.
index.js:25
debug: ModeHandler: handling key=<:wq>.
```

I'm going to close this issue for now in an attempt to get a more manageable backlog. Feel free to open if this is still happening. Next time this happens, please take a look at that log to see if there's anything pertinent.

**Comment by ohjames** [comment]
Okay, it's still happening to me on a daily basis with the config I pasted.

**Comment by ohjames** [comment]
Maybe it's also dependent on the extensions used with it? I think the issue got worse for me when I installed the tslint plugin (which fixes the file on save). If it's a timing issue the plugins that run on file open/save could introduce some latency and potentially affect VsCodeVim.

**Comment by ohjames** [comment]
Finally stopped happening a few weeks back. May have been related to an underlying problem with VS Code.
