### ISSUE TITLE
:e needs to create nonexistent files automatically

### ISSUE THREAD

**Issue by Dudelmoser** [VSCodeVim/Vim#2274]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**What happened**:
Typing ":e example.txt" opens a popup asking whether I want to create a new file.

**What did you expect to happen**:
I expect the new file to be created automatically, especially cause the popup cannot be controlled via keyboard.

**How to reproduce it (as minimally and precisely as possible)**:
Enter a file name that doesn't exist in that path.

**Environment**: Windows

- Extension (VsCodeVim) version: 0.10.8
- VSCode version: 1.19.1
- OS version: Windows 10 v1709

**Comment by jpoon** [comment]
<img width="928" alt="screen shot 2018-01-10 at 02 07 03" src="https://user-images.githubusercontent.com/85374/34789918-e2d86042-f5f4-11e7-9001-2a673fa70f35.png">

Is this the pop-up you are referring to?

**Comment by jpoon** [comment]
It's a debate between behaving like pure-vanilla VIM or leveraging some niceties from VS Code. I feel like the current behaviour is a bit more friendly, but I'll leave it up to community to decide.

**Comment by Dudelmoser** [comment]
Well, the whole point of using a VIM emulator is not having to use the mouse and staying on the home row as much as possible. I'm not sure if there's a keyboard shortcut I don't know of to actually confirm this dialog, but even then it's most likely one that doesn't fit into the VIM scheme. I mean typing :e <path> to open/create a file isn't something someone without a VIM background would guess anyway, so why not stick to the original behaviour. I personally have used VIM only for a few months now and it already bothers me to a point where I considered installing extra addons just to create files that way...

**Comment by Dudelmoser** [comment]
By the way: are there any plans to add the ability to change the current working directory like `:cd <path>`? This addon is so darn useful and there are those tiny things (that should be really easy to implement) that make a huge difference in some scenarios. I would also love the ability to remap keys using `:map` and `:noremap` (plus their mode-specific equivalents), which should be easy if VS Code allows extensions to access the user settings file.

**Comment by Dudelmoser** [comment]
I forgot to ask: Is there at least a way to confirm the currently used pop-up with keyboard only?

**Comment by Zentzy** [comment]
I was also wondering why ":e example.txt" did not create the new file just then, as soon as I typed it in. It would make so much more sense, because normally, when I type it in, I am already sure that I want a new file to be created. Also VIM is about doing everything a tiny bit faster, by just using the keyboard, why bring in an element, that is not controllable via the keyboard, this is just disturbing the workflow.

**Comment by sdemura** [comment]
> I forgot to ask: Is there at least a way to confirm the currently used pop-up with keyboard only?

While I would love `:e <thing>` to make a new thing, I haven't found a way to confirm the dialog with keyboard only. Incredibly frustrating to have to use the mouse to confirm that dialog...
