### ISSUE TITLE
Disable "Vim: Not implemented or not a valid command" pop-up

### ISSUE THREAD

**Issue by davidvuong** [VSCodeVim/Vim#2276]
Whenever I make a typo when issuing a vim command, this little pop-up appears:

<img width="934" alt="screenshot 2018-01-10 22 32 16" src="https://user-images.githubusercontent.com/1312550/34770798-56ea5286-f656-11e7-9db6-fb1ddac2c017.png">

> "Vim: Not implemented or not a valid command"

It locks up the screen and buffers key events temporarily. When I click "close", the buffer is flushed and everything I typed between the error to when I click "close" gets applied to my current document.

It's a very annoying because it breaks my flow whenever I make a typo (something as simple as `:w` vs `:ww`). I'm not sure if this is in the realm of VS Code or VSCodeVim but *is there a way to disable this pop-up*?

**Comment by jpoon** [comment]
Fixed earlier: https://github.com/VSCodeVim/Vim/commit/63be67e27dd7c5e387eaa146d9d86e9766a87e19

**Comment by bsaf** [comment]
Thank you @jpoon
