### ISSUE TITLE
cgn does not work

### ISSUE THREAD

**Issue by tw1t611** [VSCodeVim/Vim#2279]
**FEATURE REQUEST**

**When typing cgn, the editor does not react on the previous searched word**:

If you search a word in vim (/, ?) you can change the selection and goto the next word found.
The found selection can then be replaced with the previous change. *Change goto next*

1. Search a word with /
2. Type cgn (does not change word)
3. Type n (does work)
3. Type . (should repeat change)

- Extension (VsCodeVim) version: 0.10.8
- VSCode version: 1.19.1

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/1955
