### ISSUE TITLE
ctrl + c or ctrl + shift + c should copy to system buffer in insert mode

### ISSUE THREAD

**Issue by tw1t611** [VSCodeVim/Vim#2280]
**FEATURE REQUEST**

**ctrl + c or ctrl + shift + c should work in insert mode**:

Does not copy text to system buffer.

- Extension (VsCodeVim) version: 0.10.8
- VSCode version: 1.19.2
- OS: Ubuntu

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim#vimoverridecopy
https://github.com/VSCodeVim/Vim#vimusesystemclipboard
