### ISSUE TITLE
Prompt: Not implemented or not a valid command

### ISSUE THREAD

**Issue by DaGuich** [VSCodeVim/Vim#2281]
**BUG REPORT**:

**What happened**:
I'm typically typing very fast and it happens that there are typos in my command. Like when I'm trying to save a file I'm frequently writing :W instead of :w 

Now there's a prompt that says: "Vim: Not implemented or not a valid command" and no command works anymore. So I have to use my mouse and click the close button.

**What did you expect to happen**:
In previous versions this typo didn't result in a prompt. 

**How to reproduce it (as minimally and precisely as possible)**:
Type :W (upper case) instead of :w (lower case)

**Environment**:

- Extension (VsCodeVim) version: 0.10.8
- VSCode version: 1.19.2
- OS version: Linux 4.13.0-21-generic #24-Ubuntu x86_64 GNU/Linux

**Suggestion**:
Maybe add a configuration option to suppress those prompts when the user don't like them.

**Comment by michalbrzozowski** [comment]
+1

I agree. This is super annoying, and not only do you need to use the mouse to click away the warning you also need to re-focus the page you where editing (at least on windows)

**Comment by bsaf** [comment]
@michalbrzozowski you also need to mouse-click away the warning on macOS.

**Comment by jpoon** [comment]
Dupe https://github.com/VSCodeVim/Vim/issues/2276. See comments there.
