### ISSUE TITLE
v0.10.9 upgrade breaks vim

### ISSUE THREAD

**Issue by defjosiah** [VSCodeVim/Vim#2287]
**BUG REPORT** (choose one):

**What happened**:
Upgraded to v0.10.9, extension doesn't work, can't go into normal mode, and commands like "toggle vim" raise an exception `"toggleVim" doesn't exist`.

**What did you expect to happen**:
That the extension would continue to work.

**How to reproduce it (as minimally and precisely as possible)**:
Fixed by downloading .10.8 and installing from .vsix. So I imagine it's just upgrading that does it.

**Environment**:

- Extension (VsCodeVim) version: v0.10.9
- VSCode version: ca023a700f35212071dfe9544272719cbbf80e4c (insiders 1.20.0)
- OS version: High Sierra v10.13.2

**Comment by jpoon** [comment]
@defjosiah, I'm running latest build of the extension on 2 different machines. Don't see this issue. Can you uninstall the extension, delete the vscodevim extension folder (~/.vscode/extensions/vscodevim), and reinstall?

**Comment by jpoon** [comment]
Closing as I haven't heard anything back.

**Comment by peterjuras** [comment]
I have the same problem (I think). Suddenly vim is no longer working, the extension is enabled but there is no insert/normal/visual mode indicator at the bottom of a file and vim is just not working in general. It is as if the extension would not be installed at all.

The toggleVim command is also not found (the command entry in the palette is there though)

**Comment by peterjuras** [comment]
well reinstalling helped, probably related to https://github.com/Microsoft/vscode/issues/40260

**Comment by jpoon** [comment]
Yep, if that's the case, it's likely an upstream issue as the extension doesn't control the install/reinstall process.

**Comment by dragonfax** [comment]
I had the same issue. Uninstalling and reinstalling the plugin fixed it for me.

**Comment by rhys-vdw** [comment]
Same issue fro me, I had to delete the extension file itself (as advised [here](https://github.com/VSCodeVim/Vim/issues/2287#issuecomment-357376528)) rather than delete via the extensions UI. After reinstall all is working as expected.

**Comment by jpoon** [comment]
This is the upstream issue -- https://github.com/Microsoft/vscode/issues/43813

**Comment by m0ru** [comment]
deleting the extension-folder worked for me. thx :)

**Comment by noelevans** [comment]
Updating this morning to the latest version gets the extension working for me
