### ISSUE TITLE
Can't remap Ctrl key to Esc

### ISSUE THREAD

**Issue by fandy** [VSCodeVim/Vim#2291]
I'm trying to remap Ctrl to Esc, and think there may be some conflict because I am unable to exit insert mode with Ctrl. Either that or I am using the wrong label, which I cannot find documentation for.

```
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "<Ctrl>"
      ],
      "after": [
        "<Esc>"
      ]
    }
  ],
```

**Comment by jpoon** [comment]
This is something that's not currently supported. I recall a discussion on a VSCode issue where ultimately this is an issue with Electron as the key event (Ctrl) is not event sent to the Electron app until there is a modifer.
