### ISSUE TITLE
v0.10.10 Crtl+d not work any more

### ISSUE THREAD

**Issue by shpontex** [VSCodeVim/Vim#2292]
Crtl+d not work any more
- Extension (VsCodeVim) version: 0.10.10
- VSCode version: 1.19.2
- OS version: High sierra 10.13.2

**Comment by pablopunk** [comment]
Same here!

**Comment by fairyhunter13** [comment]
I don't know why Ctrl+d just change --NORMAL-- to --VISUAL-- in my editor. It seems from my assumption that this key is not referring to scrolling of page, instead it refers to multi-cursor mode.

Extension (VsCodeVim) version: 0.10.10
VSCode version: 1.19.2
OS version: Windows 10 x64bit Professional

**Comment by Nodman** [comment]
Handler for <C-d> was refactored a bit in #2269.
To bring back old behavior add to settings:
```
"vim.handleKeys": {
    "<C-d>": true,
  },
```

Could someone please explain why this is the new default behavior for <C-d> ?

**Comment by Nodman** [comment]
Feels like there is extra negate operator in condition in ```src/mode:292```
```
if (key === '<C-d>' && !(Configuration.handleKeys['<C-d>'] === true)) {
```

**Comment by jpoon** [comment]
This was by-design. It was to fix this issue https://github.com/VSCodeVim/Vim/issues/2162. tldr; 3 different behaviours can be controlled by `<C-d>`,  and this PR https://github.com/VSCodeVim/Vim/pull/2269 in the lastest release changes it to what we felt was a bit more sane:

|                             | useCtrlKeys = true                     | useCtrlKeys  = false                |
|--------------------- | ------------------------------|-----------------------------|
| handleKeys = true | VSCodeVim move page half down | VSCodeVim move page half down
| handleKeys = false | remap to ```<D-d>``` | remap to ```<D-d>```
| undefined               | VS Code default behavior | VS Code default behavior

Essentially, the `useCtrlKeys` is not longer taken into account for `<C-d>`. Personally, I'd like to remove `useCtrlKeys` in a later release as the functionality can also be configured with `handleKeys`.

Apologies for not following semvar semantics, should have bumped up the minor as it sorta breaks people's settings.

**Comment by typeoneerror** [comment]
@jpoon thanks for the explainer! I don't think following semver fixes vsix autoUpdating though. VS Code needs a rethink for being able to specify versioning per extension, I think, so this wasn't really your bad. Patch or minor, a note in release notes about what user's need to change to adopt would be the best route for now. Thanks again for your work!

**Comment by jpoon** [comment]
> Patch or minor, a note in release notes about what user's need to change to adopt would be the best route for now.

At least with instituting `semvar` notation, users should be aware that if there is a major/minor release there could be some breaking changes. Yeah, should have added this to the release notes. If you know any good tooling to generate changelogs/release notes that would be awesome

**Comment by jpoon** [comment]
I'm going to push an update adding this to the release notes. It includes another fix with macros + status bar, but the update is really about messaging this change.

**Comment by scottlu** [comment]
Not to belabor this topic but shouldn't vim.handleKeys['<C-d>'] = true be the default? I think this is what most vim users would expect.

**Comment by Graham42** [comment]
@scottlu I've opened a PR for this here https://github.com/VSCodeVim/Vim/pull/2314
