### ISSUE TITLE
Macros have stopped working since 0.10.9

### ISSUE THREAD

**Issue by Nvveen** [VSCodeVim/Vim#2296]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report
**What happened**:
Macros fail to initiate when entering 'q[a-z]'
**What did you expect to happen**:
To have vim-mode macros work like they used to.
**How to reproduce it (as minimally and precisely as possible)**:
Update to 0.10.9 or 0.10.10

**Environment**:
Arch Linux.

- Extension (VsCodeVim) version: 0.10.10
- VSCode version: 1.19.2
- OS version:

**Comment by redpixr** [comment]
Can confirm this one, nothing happens at all when I'm try to record using 'q[a-z]'

**Comment by jpoon** [comment]
Hm, if you know a specific version that broke this, that would help pinpointing the bug.

**Comment by Nvveen** [comment]
The specific release version is 0.10.9 which breaks it.

**Comment by jpoon** [comment]
Don't see anything obvious -- https://github.com/VSCodeVim/Vim/compare/v0.10.8...v0.10.9. Will need to find some time to step into the code.

**Comment by jpoon** [comment]
I see macros are working on 0.10.10. We have UTs for them too. What are the keys you are pressing?

**Comment by jpoon** [comment]
So macros ARE workings, it just what is displayed on that Status Bar is utterly wrong. So if you disregard the status bar and type whatever your macro is, it'll work.
