### ISSUE TITLE
Repeat key bindings broken

### ISSUE THREAD

**Issue by parkovski** [VSCodeVim/Vim#2297]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**What happened**:
I have `<leader>-t` and `<leader>-T` mapped to next and previous editor. Not sure exactly which version changed this, but it was recent. I used to be able to type `2<leader>t` and move two pages to the right. Lately it's been ignoring the number and only moves one page at a time.

**What did you expect to happen**:
The previous behavior.

**How to reproduce it (as minimally and precisely as possible)**:
Add this to your `vim.otherModesKeyBindings` config, and type `2<leader>t`
```json
    {
      "before": ["leader", "T"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.previousEditor"
        }
      ]
    },
    {
      "before": ["leader", "t"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.nextEditor"
        }
      ]
    }
```
**Environment**:

- Extension Name: vim
- Extension Version: 0.10.10
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.19.2

**Comment by rben01** [comment]
I'm seeing this with all custom bindings -- they don't get repeated.

**Comment by berknam** [comment]
Closing since this is no longer an issue.
