### ISSUE TITLE
Ctrl-D switches into VISUAL mode

### ISSUE THREAD

**Issue by typeoneerror** [VSCodeVim/Vim#2298]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**What happened**:

Ctrl+d switches into VISUAL MODE

**What did you expect to happen**:

Scroll the window "buffer" down.

**How to reproduce it (as minimally and precisely as possible)**:

Ctrl+d

**Environment**:

- Extension Name: vim
- Extension Version: 0.10.10
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.19.2

** VIM settings***

```
  "vim.hlsearch": true,
  "vim.ignorecase": false,
  "vim.leader": "<Space>",
  "vim.otherModesKeyBindings": [
    // Open line under current line
    {
      "before": ["leader", "o"],
      "after": ["o", "esc"]
    },
    // Clear line
    {
      "before": ["leader", "c", "o"],
      "after": ["c", "c"]
    },
    // Clear search
    {
      "before": ["leader", "/"],
      "after": [],
      "commands": [
        {
          "command": ":nohlsearch"
        }
      ]
    },
    // Duplicate line
    {
      "before": ["leader", "d"],
      "after": ["y", "y", "p"]
    }
  ],
  "vim.textwidth": 100,
```

**Comment by jpoon** [comment]
See my comment in #2292.
