### ISSUE TITLE
<C-d> half page down isn't working on v0.10.10

### ISSUE THREAD

**Issue by epilande** [VSCodeVim/Vim#2301]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: VSCode automatically updated this extension to **v0.10.10**. I tried pressing `<C-d>` to scroll half page down, but instead, it selects the text under the cursor and goes into multi cursor mode. This bug only exists in **v0.10.10**, I downgraded the vim extension to **v0.10.9** and `<C-d>` works perfectly.  

**What did you expect to happen**: `<C-d>` to scroll half page down. 

**How to reproduce it (as minimally and precisely as possible)**: Update vim extension to **0.10.10**, press `<C-d>`

**Environment**:

- Extension (VsCodeVim) version: **0.10.10**
- VSCode version: 1.19.2
- OS version: 10.13.1

**Comment by taeold** [comment]
@epilande Oh it appears to me now that this is intentional https://github.com/VSCodeVim/Vim/pull/2269

**Comment by Nodman** [comment]
Please take a look #2292

**Comment by jpoon** [comment]
Yes, this is by-design. Take a look at my comments in the issue linked by @Nodman.

**Comment by epilande** [comment]
Ahh.. 
Need to add this to config:
```
"vim.handleKeys": {
    "<C-d>": true,
},
```

I would've imagined this to be the other way around where we disable it instead of having to enable it. 

And sorry for opening this issue...I should've searched recent issues first.

Anyways, thanks guys for those links!
