### ISSUE TITLE
vim.useCtrlKeys seems not working

### ISSUE THREAD

**Issue by xujihui1985** [VSCodeVim/Vim#2303]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT
**What happened**:
vim.useCtrlKeys seems not working after upgrade to 0.10.10

**What did you expect to happen**:
c-d should map to pagedown 
**How to reproduce it (as minimally and precisely as possible)**:
upgrade to 0.10.10 and it's working after I downgrade to 0.10.9

**Environment**:

- Extension (VsCodeVim) version: 0.10.10
- VSCode version: latest
- OS version: macos latest

**Comment by jpoon** [comment]
Please use the search feature to see if we have similar bugs filed. https://github.com/VSCodeVim/Vim/issues/2301

**Comment by xujihui1985** [comment]
sorry for duplicate issue, thanks
