### ISSUE TITLE
ctrl-d while in normal mode enters 'VISUAL MODE' or 'Multiple Cursor Mode' by default

### ISSUE THREAD

**Issue by gregtandiono** [VSCodeVim/Vim#2305]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
When I press `ctrl-d` during `normal mode`, I enter `visual mode` (or multiple cursor mode). I have `vim.useCtrlKeys` enabled.

**What did you expect to happen**:
It should scroll half page down

**How to reproduce it (as minimally and precisely as possible)**:
Open vscode with vscodevim enabled, and try holding down `ctrl-d`

**Environment**:

- Extension Name: vim
- Extension Version: 0.10.10
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.19.2

**Comment by jpoon** [comment]
See https://github.com/VSCodeVim/Vim/issues/2292
