### ISSUE TITLE
<C-d> and <C-l>

### ISSUE THREAD

**Issue by CQPosts** [VSCodeVim/Vim#2308]
- Extension Name: vim
- Extension Version: 0.10.10
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.19.2

`Ctrl+d` enters Visual mode.  Want it to scroll half page.

`Ctrl+l` does nothing.  Want it mapped to `:nohl`.

This was working before the latest update.

Here's my vim settings:

    "vim.easymotion": true,
    "vim.incsearch": true,
    "vim.useSystemClipboard": true,
    "vim.useCtrlKeys": true,
    "vim.hlsearch": true,
    "vim.insertModeKeyBindings": [
        {
            "before": ["j","k"],
            "after": ["<Esc>"]
        }
    ],
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<leader>","d"],
            "after": ["d", "d"]
        },
        {
            "before":["<C-l>"],
            "after":[],
            "commands": [
                {
                    "command": ":nohl"
                }
            ]
        }
    ],
    "vim.leader": ",",
    "vim.handleKeys":{
        "<C-a>": false,
        "<C-f>": false
    },

**Comment by dshook** [comment]
Yes so much on Ctrl-D. I was wondering if I broke it somehow with another extension but I couldn't find it and it's driving me crazy haha.

Is there any workaround to restore it?

**Comment by jpoon** [comment]
See https://github.com/VSCodeVim/Vim/issues/2292. FYI, search existing issues before filing a new one.

**Comment by CQPosts** [comment]
@jpoon Thanks for the tip - must be a bad searcher :p.  Ctrl-d works as expected now.  But I can't get `<C-l>` to work as expected.
