### ISSUE TITLE
C-d no longer scrolls down

### ISSUE THREAD

**Issue by pwrobinson** [VSCodeVim/Vim#2309]
I noticed that after the latest update, pressing C-d in normal mode activates a multi-cursor rather than simply scrolling down as it used to. 

These are my key mappings:
    "vim.otherModesKeyBindingsNonRecursive":[
        {
            "before": ["$"],
            "after": ["g","$","h"]
        },
        {
                "before": ["^"],
                "after": ["g","^"]
        },
        {
            "before": ["0"],
            "after": ["g","0"]
        },
    {
        "before": ["j"],
        "after": ["g","j"]
    },
    {
        "before": ["k"],
        "after": ["g","k"]
    }
    ],

- Extension Name: vim
- Extension Version: 0.10.10
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.19.2

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 423,
		"activateCallTime": 8,
		"activateResolvedTime": 117,
		"activationEvent": "*"
	}
}
```

**Comment by jpotterm** [comment]
See https://github.com/VSCodeVim/Vim/issues/2292

**Comment by jpoon** [comment]
What @jpotterm said.
