### ISSUE TITLE
Unexpected behavior with easymotion and `.` as repeat command

### ISSUE THREAD

**Issue by jtr109** [VSCodeVim/Vim#2310]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**What happened**:

When I use `.` to repeat the change behavior after I changed a word with `ciw` and use `<leader><leader>w` to `easymotion` to another word, all keyboard behavior not work. (By the way, I think the command has been send to vscode because of the blink of cursor freezing for a while.)

**What did you expect to happen**:

The repeat command `.` should not store the behavior of easymotion and just repeat the behavior before.

**How to reproduce it (as minimally and precisely as possible)**:

```html
<div>test</div>
```

Put your cursor on the first `div` and change it into `span` with `ciw` in normal mode. Then use easymotion to move the cursor to `div` in the end tag. Then press `.`. The end tag will not change as expection. And now, the cursor cannot be moved with `hjkl` and input also not work.

**Environment**:

- Extension (VsCodeVim) version: 0.10.10
- VSCode version: 1.19.2
- OS version: macOS High Sierra Version 10.13.2 (17C88)

**Comment by clessg** [comment]
I'm also experiencing this bug.

**Comment by diminutivesloop** [comment]
This is still an issue.

**Comment by xconverge** [comment]
fixed in #3112

**Comment by xconverge** [comment]
FYI, unrelated but @jtr109 have you tried using the surround functionality? you could have done ```cst<span>``` in your example
