### ISSUE TITLE
extension.vim_ctrl+d changed?

### ISSUE THREAD

**Issue by w4-sjcho** [VSCodeVim/Vim#2312]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
extension.vim_ctrl+d, which used to scroll half page down, doesn't work anymore. Instead, some kind of find selection feature is working.

**What did you expect to happen**:
Scroll half page down.

**How to reproduce it (as minimally and precisely as possible)**:
Add some keymap to "extension.vim_ctrl+d". (e.g. "cmd+9")

It used to work like "ctrl+d" in vim (scroll half page down), but it is now triggering the find popup.

**Environment**:

- Extension (VsCodeVim) version: 0.10.11
- VSCode version: 1.19.2
- OS version: macOS 10.12.6(16G1114)

**Comment by WeAthFoLD** [comment]
Same here.

* Extension version: 0.10.11
* VSCode version: 1.19.2
* OS version: Windows 10

**Comment by w4-sjcho** [comment]
User settings:
```
    "vim.handleKeys": {
        "<C-d>": true
    }
```

Was able to recover the old behavior by adding this.

Is there a reason behind this configuration? Why not just support ctrl+d when user explicitly maps vim_ctrl+d?

**Comment by Nodman** [comment]
This is new behavior, take a look at @jpoon post in #2292 for more details

**Comment by Graham42** [comment]
This seems to be causing a lot of confusion. Perhaps this config
```
    "vim.handleKeys": {
        "<C-d>": true
    }
```
Should be default. Users who install a vim plugin are going to expect `<C-d>` to work like vim.

**Comment by jpoon** [comment]
@Graham42 Yes, I've been wanting to add that, but have been busy with work. If anybody wants to add it, the change should be relatively simple and involve a `default` property here: https://github.com/VSCodeVim/Vim/blob/master/package.json#L515

**Comment by Graham42** [comment]
I can do that.

**Comment by typeoneerror** [comment]
FYI, I also needed to add things like "<C-e>" to `handleKeys`. I'm adding as I encounter unexpected behaviour with the new update.
