### ISSUE TITLE
del doesn't seem to work in insert mode

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#2317]
<ul>
	<li>VSCode Version: Code - Insiders 1.20.0-insider (d21e6a3e388897a2250cb10ae897b6481e0bd61d, 2018-01-19T07:10:59.044Z)</li>
	<li>OS Version: Darwin x64 17.3.0</li>
	<li><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.14
EditorConfig|Edi|0.11.1
beautify|Hoo|1.1.1
material-icon-theme|PKi|3.2.1
code-settings-sync|Sha|2.8.7
vscode-file-peek|abi|1.0.1
Bookmarks|ale|0.18.0
numbered-bookmarks|ale|0.11.0
vscode-processes|and|0.0.4
vscode-intelephense-client|bme|0.8.5
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-eslint|dba|1.4.4
gitlens|eam|7.5.6
vscode-html-css|ecm|0.2.0
tslint|eg2|1.0.24
vscode-npm-script|eg2|0.3.3
prettier-vscode|esb|1.1.2
php-debug|fel|1.12.1
sass-lint|gle|1.0.1
vscode-firefox-debug|hbe|0.17.0
vscode-dimmer|hoo|2.1.0
smarty|imp|0.2.0
docthis|joe|0.6.0
puppet-vscode|jpo|0.8.0
twig-language-2|mbl|0.3.0
vscode-scss|mrm|0.6.2
debugger-for-chrome|msj|4.0.0
color-highlight|nau|2.3.0
vscode-journal|paj|0.5.0
vscode-code-outline|pat|0.0.12
webstorm-icons|pms|0.0.1
vscode-yaml|red|0.0.7
sass-indented|rob|1.4.6
sockscode-vscode|shy|1.0.1
flowmaker|spe|1.1.0
vim|vsc|0.10.11

(1 theme extensions excluded)

</details></li>
</ul>

---

**BUG REPORT**

**What happened**:
Del key does not work in insert mode.

**What did you expect to happen**:
Del should delete the character after the cursor

**How to reproduce it (as minimally and precisely as possible)**:
Enter insert mode with `i`, try to delete a character with del key.

**Comment by jpoon** [comment]
Maybe related to #730. Do you have multiple tabs open?

**Comment by bm-stschneider** [comment]
Funny, I reported the <tab> thing to the vscode repo :) no it also happens if only one tab is open.

**Comment by J-Fields** [comment]
@bm-stschneider can you still reproduce this?

**Comment by bm-stschneider** [comment]
nope
