### ISSUE TITLE
An ASCII ESC was inserted while pressing ESC

### ISSUE THREAD

**Issue by FrontMage** [VSCodeVim/Vim#2318]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
Sometimes after editing, I press `ESC` multiple times just to get back to normal mode, but this time an ASCII character `^[` which is the `ESC` character was inserted to my file.
Even worse, vscode renders it as a space character but with only half the width. This causes my javascript file report a syntax error.

**What did you expect to happen**:
Well, I expect to get back to normal mode and nothing more.
**How to reproduce it (as minimally and precisely as possible)**:
Sometimes happens, not sure why yet.

**Environment**:
MacOS

- Extension (VsCodeVim) version:0.10.11
- VSCode version:Version 1.19.2 (1.19.2)
- OS version:10.13.2 (17C205)

**Comment by sbilstein** [comment]
I am seeing a similar issue with `<tab>` being inserted when I press tab.

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/831
