### ISSUE TITLE
. is breaking

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#2319]
Bug report.

**What happened**: 

I pressed `.` and nothing happened.

**What did you expect to happen**: 

It to repeat my last insertion.

**How to reproduce it (as minimally and precisely as possible)**:

I have no clue. Seems to happen when vscode is open for a while. Once it starts happening for a file, it persists in that specific file, even if you close and reopen the tab (!), but it might not happen for other tabs (!!).

**Environment**:

Vim 0.10.11
VSCodeVim Insiders
OS: MacOS 10.13.1

**Comment by Chillee** [comment]
Perhaps it's related to our history system and our problem with undos?

I can't help but think that all of our undo problems might be related to this change.... https://github.com/VSCodeVim/Vim/pull/1833

**Comment by johnfn** [comment]
@Chillee this is a really recent problem. My guess is it landed no earlier than v0.10.6 as I use . all the time.

**Comment by daveriedstra** [comment]
I've started seeing this recently as well. `.` will repeat deletions but not insertions, eg, if I repeat `cw`, the deletion is performed but not the insertion (just as if it was only repeating `dw`).
