### ISSUE TITLE
Broken with new release

### ISSUE THREAD

**Issue by delgermurun** [VSCodeVim/Vim#2322]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**What happened**: Suddenly stopped working. So I checked repo. Seems like new version released. Couldn't switch into normal mode.

**Environment**: Mac OS

- Extension (VsCodeVim) version: 0.10.12
- VSCode version: 1.19.2 
- OS version: MacOS 10.13.2

**Comment by rogerwelin** [comment]
experienced the same issue

**Comment by r6203** [comment]
I'm running into this issue as well.

I tried to downgrade the extension by manually install an older release.

v0.10.11 works but only when reloading vscode the first time (after manually installing it).

After the 2nd reload of the editor (by installing another extension or opening and closing the editor), vim stops working.

**Comment by pyrox18** [comment]
Having the same problem as well. The mode indicator in the status bar is missing, which might indicate that the extension isn't running at all. I'm using v0.10.12 of the extension, VS Code v1.19.2 and macOS 10.13.2.

**Comment by masiqi** [comment]
same issue on my macOS

**Comment by ChenXiyu** [comment]
getting this issue as well

**Comment by qianliu013** [comment]
the same issue on my win10

**Comment by jlelong** [comment]
The Developer Tools Console says that the extension is not loaded with the message
`Cannot read property 'overrideCopy' of undefined`.

**Comment by Retroxs** [comment]
the same issue on my ubunutu16.04 ,cant toggle vim mode

**Comment by takano-ex** [comment]
Same with me here.
Deleting `~/.vscode/` folder and re-installing VSCode doesn't fix the issue.

OSX 10.13.2
VSCode 1.19.2
VSCodeVim 0.10.12

**Comment by ferraniki** [comment]
Same issue on my Ubuntu 17.10

**Comment by razagill** [comment]
Already reported on #2321 , @jpoon is airborne right now, will fix it as soon as he lands (in apprx. 2hours)

**Comment by jlelong** [comment]
@r6203 you need to set `extensions.autoUpdate` to false to stick to a former version of an extension.

**Comment by baurine** [comment]
just happened to me when I restart the mac.

**Comment by jon301** [comment]
If you're in a hurry and can't wait for the fix : downgrade to vscode-vim 0.10.11

- set "extensions.autoUpdate" to false in your user settings
- uninstall vscode-vim 0.10.12
- download vscode-vim 0.10.11 VSIX file : https://github.com/VSCodeVim/Vim/releases
- in vscode, ctrl+shift+p > Install from VSIX > Choose vscode-vim 0.10.11 VSIX file

This worked for me.

**Comment by soupdiver** [comment]
Just installed on a fresh Linux Mint 18 install.
When trying to toggle vim mode I get an error saying `command 'toggleVim' not found`. It's maybe related

**Comment by boydy12** [comment]
![image](https://user-images.githubusercontent.com/13649815/35269763-d9c4ed10-0024-11e8-88e4-6622e18a4a8f.png)
I think some more testing is required?

**Comment by Inndy** [comment]
Same issue here.

- Extension (VsCodeVim) version: 0.10.12
- VSCode version: 1.20.0-insider
- OS version: macOS 10.13.2

**Comment by stormpat** [comment]
Same here. Thanks to @jon301 for the quick fix. 👍

**Comment by mpseidel** [comment]
@jon301 thanks for the quick fix - I live on that extension - thanks guys for all the work you put into it ❤️

**Comment by TomLingham** [comment]
Yup, it broked......... `toggleVim` "command not found" when trying to enable manually, and no other errors apart from that. Mac OS.

**Comment by sus007** [comment]
And here I was...about to do a clean install of the **`VSCode`**. 😁

**Comment by JasonAsmk** [comment]
I almost had a panic attack 😄  . Shit happen sometimes. Chill guys they gonna fix it ❤️  . Till then use  @jon301 's workaround.

**Comment by valleybay** [comment]
This was such a mindfuck. Even though I realised it was broken, I was constantly pressing h,j,k,l, <esc> etc. It really is impossible to live without VIm. Thanks for the fix ❤️

**Comment by chiuan** [comment]
experienced the same issue

**Comment by harlequiin** [comment]
Same issue on 
VSCodeVim 0.10.12
VSCode 1.19.2
Debian 9.0.3 

Woulda saved myself alot of trouble (reinstalling vscode, extensions etc.) if I saw this thread an hour ago lol

**Comment by StoyanIvanovI** [comment]
Wish I found that after nuking my VSCode install and wrecking my sync setup.

**Comment by jpoon** [comment]
Dupe issue of https://github.com/VSCodeVim/Vim/issues/2321. I just got to my hotel room, https://github.com/VSCodeVim/Vim/pull/2324 is incoming and as soon as that passes build/test, I'll push a new release out. Sorry for the inconvenience. 

As @jon301  mentioned, if you want to run a different version of the extension, all of the versions are available https://github.com/VSCodeVim/Vim/releases. Download the one you want and drag+drop onto VSCode.

**Comment by pgoodjohn** [comment]
0.10.13 works perfectly on macOS!
Thanks for the super quick fix 🙌

**Comment by weiaicunzai** [comment]
same here , no mode bar, nothing, just like this vim extension was not installed at all, Im using ubuntu 16.04 and vscode Version 1.19.2
PS: update my vscode doesnt help , plz fix this

**Comment by bigface008** [comment]
v0.10.13works in the right way. Thanks for the fix!:+1:

**Comment by jpoon** [comment]
@pgoodjohn, thanks for validating. Not sure why the tests didn't catch that as this type of error should hit most of the tested code paths.

Now, time to explore the streets of Barcelona! 🇪🇸

**Comment by mirsking** [comment]
It occur again after upgrading to v1.1.0 release.

**Comment by pgoodjohn** [comment]
> It occur again after upgrading to v1.1.0 release.
> Downgrade to v1.0.8 fix this.

I'm running 1.1.0 everything is fine

**Comment by mirsking** [comment]
> > It occur again after upgrading to v1.1.0 release.
> > Downgrade to v1.0.8 fix this.
> 
> I'm running 1.1.0 on VSCode 1.31.1 on MacOS and everything is fine

I'm running vscode 1.31.1 on ubuntu18.04, and v1.1.0 is auto updated by vscode in background.

**Comment by tskj** [comment]
I'm having this issue on 1.1.0 on MacOS.

**Comment by max-frai** [comment]
Same problem on 1.33.1 and mode is stuck in normal with block cursor visualization.

**Comment by mariomeissner** [comment]
VSCode 1.33.1 and Vim 1.7.0, same problem.

**Comment by vv13** [comment]
> experienced the same issue

same problem on:
Extension (VsCodeVim) version: 1.12.0
VSCode version: 1.40.2
OS version: macOS 10.15.1

**Comment by calys** [comment]
Same here:

Extension (VsCodeVim) version: 1.12.0
VSCode Version: 1.40.2 (user setup)
OS: Windows_NT x64 10.0.17763

**Comment by Shahor** [comment]
Same here :( 
Just updated and the vim lpuging won't toggle on now.
This seems to happen regularly... :(

**Comment by faergeek** [comment]
For now the solution is:

![изображение](https://user-images.githubusercontent.com/3524621/70430779-91ad0380-1a8c-11ea-8608-3cb30a0fac98.png)

**Comment by jamesalbert** [comment]
Experiencing the same as @calys and @vv13. I downgraded to 1.11.3 and that worked for a bit, then it auto-updated to 1.12.0 and it's broken again. Same "Command 'togglevim' not found"

**Comment by JinSung-Hwang** [comment]
@jon301 
You are genius 
Thank you
