### ISSUE TITLE
The lastest VSCodeVim plugin on windows is not working.

### ISSUE THREAD

**Issue by bigface008** [VSCodeVim/Vim#2323]
Please forgive me......It's my first time to write an issue on github and my English is really horrible.
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT
**What happened**:
I installed the VSCodeVim plugin of version 0.10.12. After I reload VScode, the plugin stopped working. Whatever the key I pressed, the plugin doesn't seem to give a reaction(the editor remained in the insert mode, or the mode looks like with no plugin installed). I restart the plugin several times but the editor seems to have not installed the plugin.
**What did you expect to happen**:
The plugin works in the right way.
**How to reproduce it (as minimally and precisely as possible)**:
Install the latest version (v0.10.12) and reload VScode. That's all I know. 

**Environment**:

- Extension (VsCodeVim) version:0.10.12
- VSCode version:1.19.2
- OS version:windows10.0.16299

**Comment by flaport** [comment]
Same problem here. Does not work on Linux Either. 
0.10.11 works fine.

**Comment by jvbianchi** [comment]
Doesn't work on MacOs either.
**Environment:**
Extension (VsCodeVim) version: 0.10.12
VSCode version: 1.19.2
OS version: 10.12.6

**Comment by grenappels** [comment]
also does not work here.
VsCodeVim ver 0.10.12
VSCode ver 1.19.2
macOS ver 10.13.2

**Comment by jvbianchi** [comment]
duplicated of https://github.com/VSCodeVim/Vim/issues/2322
