### ISSUE TITLE
Add POSIX-compliant shortcuts

### ISSUE THREAD

**Issue by koutoftimer** [VSCodeVim/Vim#2326]
**FEATURE REQUEST**

You can find the list of shortcuts [here][1].

Currently, following shortcuts is not supported:

- `CTRL-X`
- `CTRL-J`
- `CTRL-M`

IHMO, I didn't recognize `CTRL-V` viable because of broking muscle memory of copy-paste action.

**Environment**

- Extension Name: vim
- Extension Version: 0.10.11
- OS Version: Linux x64 4.4.0-112-generic
- VSCode version: 1.19.1

   [1]: https://www.mkssoftware.com/docs/man1/sh.1.asp#Vi_Editing_Mode

**Comment by jpoon** [comment]
Have you tried https://github.com/VSCodeVim/Vim#key-remapping?

**Comment by koutoftimer** [comment]
@jpoon,
```
{
    "vim.insertModeKeyBindings": [
        {
            "before": [
                "<C-j>"
            ],
            "after": [
                "<Enter>"
            ]
        }
    ]
}
```

in workspace settings didn't work.
