### ISSUE TITLE
Evil mode

### ISSUE THREAD

**Issue by dotWaldemar** [VSCodeVim/Vim#2328]
How can I use evil mode or this`s not supported? I want default vim and in insert mode emacs! How I can do this?

**Comment by tmepple** [comment]
I'm not sure but are you looking for something like https://github.com/VSpaceCode/VSpaceCode?  If not then I think you can use their method of mapping key bindings to commands to customize whatever you want.

**Comment by aliev** [comment]
https://github.com/VSCodeVim/Vim

**Comment by jpoon** [comment]
From my Googling of what evil mode is. My understanding is that it's vim emulator for emacs? Not entirely sure how that would gel with this particular extension. There is an emacs keymap available https://marketplace.visualstudio.com/items?itemName=hiro-sun.vscode-emacs.
