### ISSUE TITLE
Keymapping doesn't work

### ISSUE THREAD

**Issue by frynio** [VSCodeVim/Vim#2329]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**What happened**: In vim to go to the first non-blank character in line you have to press `^` in normal mode. But I don't want that combination, so I would like to bind it to `zz`

**What did you expect to happen**: I expected it to work, but then I press `zz` it doesn't do anything, but now even the `^` key doesn't work

**How to reproduce it (as minimally and precisely as possible)**: I've put this in `settings.json`:

```
    "vim.otherModesKeyBindings": [
        {
            "before": [
                "^"
            ],
            "after": [
                "z",
                "z"
            ]
        }
    ],
```
Then I go to the editor, stop at some point on the line with code and try to press `zz` but it doesn't work.

**Environment**:

- Extension (VsCodeVim) version: Latest
- VSCode version: Latest
- OS version: Windows 10 x64

**Comment by xerron** [comment]
same bug!

` "vim.leader": "<space>",`

not set.

and 

```
"vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<leader>","d"],
            "after": ["d", "d"]
        },
        {
            "before":["<C-n>"],
            "after":[],
            "commands": [
                {
                    "command": ":nohl"
                }
            ]
        }
    ],
```

not work!!!

**Comment by jpoon** [comment]
https://github.com/vscodevim/vim#viminsertmodekeybindingsvimothermodeskeybindings

`before` => the commands that you typed.
`after` => what you want those `before` keys to actual represent.

In the case of our documented example in the README: 
```
    "vim.insertModeKeyBindings": [
        {
            "before": ["j", "j"],
            "after": ["<Esc>"]
        }
    ]
```

means, when we type `jj`, in Insert mode, the extension will interpret it as `<Esc>`.

**Comment by tecfu** [comment]
What about this? 

> 
> same bug!
> 
> "vim.leader": "<space>",
> 
> not set.

**Comment by jpoon** [comment]
What about it? 

```
"vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<leader>","d"],
            "after": ["d", "d"]
        },
]
```

Also works for me.
