### ISSUE TITLE
Ruby extension causing extreme lag

### ISSUE THREAD

**Issue by MythicalFish** [VSCodeVim/Vim#2330]
Was suddenly faced with extreme lag when in Insert mode, after some investigation I realized that it was caused by the Ruby extension.

Anyone else having this issue?

**Comment by jpoon** [comment]
Did you mean to file this under the Ruby extension?

**Comment by kevinjalbert** [comment]
@MythicalFish I also noticed this. The Ruby extension just updated, so that is likely the cause.

**Comment by kimroen** [comment]
For future travelers, the relevant issue on the ruby extension is this one: https://github.com/rubyide/vscode-ruby/issues/252
