### ISSUE TITLE
Flash on operate

### ISSUE THREAD

**Issue by raroman** [VSCodeVim/Vim#2333]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature request

**What happened**:

yanked with no visual feedback

**What did you expect to happen**:

yank with visual feedback

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/t9md/atom-vim-mode-plus/wiki/GIFs#flash-on-operate

Context I'm coming from Atom but have configured neovim to do the same. Trivial I realize but I really like this feature.

**Environment**:

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.19.3
- OS version: Mac 10.13.2

**Comment by eyaleizenberg** [comment]
@raroman Do you have some solution for this? It drives me nuts that when I yank I get no visual feedback.

**Comment by rtfeldman** [comment]
This is the only thing I've missed coming from Atom!

**Comment by nomad-software** [comment]
Please make this optional. I would prefer to not see any unnecessary highlighting a la Vim. This plugin is to provide Vim features not those from other editors.
