### ISSUE TITLE
tab to indent a block of code does nothing

### ISSUE THREAD

**Issue by cloudranger** [VSCodeVim/Vim#2342]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
When a block of code is highlighted, for example using SHIFT V, when you press TAB to indent it (shift 
it right), nothing happens.  You can however shift it left using SHIFT TAB

**What did you expect to happen**:
I expected my block of highlighted code to move to the right by one tab stop

**How to reproduce it (as minimally and precisely as possible)**:
SHIFT V
Cursor down to select a few lines
TAB

**Environment**:
   -  Extension Name: vim
   -  Extension Version: 0.10.13
   -  OS Version: Linux x64 4.4.0-38-generic
   -  VSCode version: 1.19.1

**Comment by jpoon** [comment]
That's not how you indent in vim. http://vim.wikia.com/wiki/Shifting_blocks_visually

**Comment by jpoon** [comment]
Also found this: https://github.com/VSCodeVim/Vim/issues/1210

**Comment by krinoid** [comment]
FYI, native VSC shortcuts for indent are `⌘+]` and `⌘+[` (`CTRL` instead of `CMD` on Windows/Linux) and it works in visual mode.

**Comment by zheneknew** [comment]
I fixed it by adding following code to vscode settings.json
```JSON
  "vim.normalModeKeyBindings": [
    { "before": ["<Tab>"], "commands": ["editor.action.indentLines"] },
    { "before": ["<Shift+Tab>"], "commands": ["editor.action.outdentLines"] }
  ],
  "vim.visualModeKeyBindings": [
    { "before": ["<Tab>"], "commands": ["editor.action.indentLines"] },
    { "before": ["<Shift+Tab>"], "commands": ["editor.action.outdentLines"] }
  ],
```
