### ISSUE TITLE
Feature Ask: `:sav`

### ISSUE THREAD

**Issue by nurhusni** [VSCodeVim/Vim#2343]
Every time I wanna save my code through Vim commands, either it's using :w or :sav commands, it never works, it keeps showing me the "not implemented" error. It makes me do it traditionally; click file and click save/save

The others command are working just fine (actually I just install VSCode and the extension today, so I just do some basic commands and haven't checked much, I don't know if there would be another issue with other commands). But it's just these save commands that never work. Do I miss something or is there any additional commands should I do to make it work?

**Comment by Chillee** [comment]
Are you sure `:w` doesn't work? `:sav` doesn't work for me, but `:w` works fine. Otherwise, the bug is the same as in here: https://github.com/VSCodeVim/Vim/issues/2346

**Comment by rodcloutier** [comment]
`:sav` seems to be supported when we integrate with NeoVim. But the behaviour is slightly different than Vim's: It does change the buffer to the new file created.
