### ISSUE TITLE
New feature request:  Global command

### ISSUE THREAD

**Issue by aamchi** [VSCodeVim/Vim#2346]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  Feature Request

**What happened**: 
Upon typing ":g/vpcid/ d" and hitting Enter/Return key, shows the message "E492: Not an editor command. g/vpcid/ d"

**What did you expect to happen**:
I expect all the lines that match the pattern specified between the slashes, to be deleted.  I would like the same functionality as the global command g and v (refer [http://vim.wikia.com/wiki/VimTip227](Power of g)).  This feature is especially useful when dealing with data files.

**How to reproduce it (as minimally and precisely as possible)**:
Enter the above command for a file with some text pattern that is present in the file.  And hit Enter/Return key.

**Environment**:

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.19.3
- OS version: macOS Sierra (v10.12.6)

**Comment by Chillee** [comment]
This isn't really a feature request, so much as it is a bug. :g should work with neovim integration (which is what causes the error messages), but it currently isn't for whatever reason.

**Comment by Chillee** [comment]
I'm having a lot of trouble replicating this in the debug instance, which is pretty frustrating. The bug shows up fine in my normal instance.

**Comment by Chillee** [comment]
Ah, my bad @jpoon . This was just a poor hack I did at the time that I never fixed.

I needed a way to fall back to neovim commands in the event that it didn't parse. Our parser was only set up to parse a subset of all possible Ex-commands, and it would have been a far more involved effort to allow for an "empty" state. The solution I came to then was to catch the error, and then try running the command through neovim.

This ensured that any action that we couldn't handle, neovim would try and handle.

**Comment by casey-speer** [comment]
This is still broken for me; is it expected to work now??

**Comment by casey-speer** [comment]
Ah never mind; I see I don't have neovim installed.

**Comment by storypixel** [comment]
for those who expected this to work but it doesn't, it's possibly because you need to have installed neovim (firstly) and then vscode-neovim extension (secondly) https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim

**Comment by J-Fields** [comment]
@storypixel No, this works with VSCodeVim as we support some integration with neovim. Set `vim.enableNeovim` and `vim.neovimPath` appropriately.

**Comment by leoauri** [comment]
The error message should indicate these settings rather than asking for PRs. I assumed for ages that such functionality is unimplemented.
