### ISSUE TITLE
Is it possible to have animated scroll?

### ISSUE THREAD

**Issue by eyaleizenberg** [VSCodeVim/Vim#2352]
For example using ctrl+d or ctrl+u ?

Thanks.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:

- Extension (VsCodeVim) version:
- VSCode version:
- OS version:

**Comment by J-Fields** [comment]
`editor.smoothScrolling`. It doesn't, however, play _perfectly_ nicely with `<C-d>` and `<C-u>` as the cursor will not stay in the same place in the viewport. IIRC this is due to us not knowing when the scrolling is finished, though you're free to take a closer look into this yourself.
