### ISSUE TITLE
PageUp/Down moves cursor but leaves selection unchanged

### ISSUE THREAD

**Issue by cdyson37** [VSCodeVim/Vim#2361]
Title says it all: in vim if I'm in visual mode, then page up/down will grow/shrink the selection. In vsc+vim the window is scrolled, but the selection stays the same. In fact, the selection appears to be unselected after a page up then page down, but tapping j or k causes it to be highlighted once more.

- Extension (VsCodeVim) version: 0.10.6
- VSCode version: 1.19.0
- OS version: Linux / CentOS 7.2

**Comment by jpoon** [comment]
Dupe #2374
