### ISSUE TITLE
Searching finds nothing when pasting from cmd

### ISSUE THREAD

**Issue by seishun** [VSCodeVim/Vim#2362]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: the string "foo" appeared in the status line, but it couldn't be found in the file

**What did you expect to happen**: the cursor moves to the next instance of "foo"

**How to reproduce it (as minimally and precisely as possible)**:

1. Open a text document that contains text "foo".
2. Type "foo" in a cmd window, then copy it by selecting and then right-clicking.
3. In VS Code, press `/`, then `Ctrl+R`, then `*`, then `Enter`.

**Environment**:

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.19.2
- OS version: Windows 7 64-bit

**Comment by jpoon** [comment]
> In VS Code, press /, then Ctrl+R, then *, then Enter.

Do you mean `Ctrl+V` here to paste the text? I just tried it, works fine for me. Although the "mode" displayed in the status bar changes to 'Normal' you can still use 'n' or '*' to go through the results.

**Comment by jpoon** [comment]
Closing as haven't heard back.
