### ISSUE TITLE
easymotion n-character search motion

### ISSUE THREAD

**Issue by prog666** [VSCodeVim/Vim#2363]
**FEATURE REQUEST**

Really nice replacement for usual search, would be nice to have it in vscode
https://github.com/easymotion/vim-easymotion#n-character-search-motion

**Comment by Chillee** [comment]
It should work. Have you tried the binding [here?](https://github.com/VSCodeVim/Vim#vim-easymotion)

`\\/<chars>`

**Comment by prog666** [comment]
oh, thanks. Only think left is making the rest of the code gray =)

**Comment by Chillee** [comment]
Yep, it definitely is possible, I made a prototype once for it. We're just currently not doing it.

Maybe it is something people want. Do you want to open up an issue for it?

**Comment by prog666** [comment]
I will try to implement this when i have time. I guess it's not really an issue to open an issue for it. Thanks for response.

**Comment by prog666** [comment]
But how do i map it to `/` key without the double-leader?

**Comment by prog666** [comment]
ok, this works
 ```json
        {
            "before": ["/"],
            "after": ["<leader>", "<leader>", "/"]
        }
```

but tab and N are not working in n-mode, so it cannot be used as a replacement for search

**Comment by Chillee** [comment]
@prog666 If you want tab and N to work in n-mode, can you open up a separate issue for that? I feel like the initial reason for this issue has been resolved.

**Comment by prog666** [comment]
but n-mode is useless without this features..
