### ISSUE TITLE
VSCodeVim will not work when Open large file

### ISSUE THREAD

**Issue by haolly** [VSCodeVim/Vim#2364]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**What happened**:
Could not edit file, could not move cursor

**What did you expect to happen**:
works OK
**How to reproduce it (as minimally and precisely as possible)**:
open some file bigger than 5.33MB

**Environment**:
win10,  code 1.19.3 , vscodeVim 0.10.1

Code works well when I disable this plugin, or when the file is small

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/2216

**Comment by listenerri** [comment]
vscode disables the extensions from accessing the current editor object (vscode.window.activeTextEditor), which causes the vim extension to not work properly

I created a related issue in the vscode repository: https://github.com/microsoft/vscode/issues/276277

That issue requires at least 20 upvotes to be addressed, if you feel this should be fixed/implemented, please express your thoughts in that issue
