### ISSUE TITLE
[Bug] Option 'vim.showcmd' has no effect

### ISSUE THREAD

**Issue by IsaacKhor** [VSCodeVim/Vim#2365]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**What happened**: When `vim.showcmd` is set to true, implicitly or explicitly, commands being written are not shown

**What did you expect to happen**: Incomplete commands shoud be shown on the status bar

**How to reproduce it (as minimally and precisely as possible)**: 
- Start new VSCode instance with fresh config
- Install VSCodeVim
- Open any file
- Type `20` or `c`
- Expected behaviour: the characters `20` or `c` shown in status bar
- Actual behaviour: status bar does not change

**Environment**:

- Extension Name: vim
- Extension Version: 0.10.13
- OS Version: Darwin x64 17.3.0
- VSCode version: 1.19.3

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 211,
		"activateCallTime": 2,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'document' of undefined"
		}
	]
}
```

**Comment by jpoon** [comment]
Damn, so many special cases of when/when not to update the status bar. I can repro, should be able to fix this soon.

**Comment by Dvbnhbq** [comment]
I'm experiencing the same issue, how such bugs are possible? Do you guys have some testers in there?
As an addition, `vim.showmodename` option works incorrectly, it doesn't show the mode name immediately after file was saved and until mode is changed to INSERT mode.

**Comment by jpoon** [comment]
@Dvbnhbq, I understand your frustration. However, do realize that we are a community of *volunteers*. Nobody is paid to maintain this extension, to fix bugs, or to add features. Please keep discussions on GitHub and our Slack cordial as per our [Code of Conduct](https://github.com/VSCodeVim/Vim/blob/master/CODE_OF_CONDUCT.md)

**Comment by jpoon** [comment]
I've taken a break from my vacation to fix this: https://github.com/VSCodeVim/Vim/pull/2386.

**Comment by Dvbnhbq** [comment]
@jpoon Hey! Sorry, I was not right saying that. I was like this is all Microsoft software...I'm really disappointed by them. I didn't realize that this is from volunteers. Once again, sorry for that. 
And thanks for your fix. Hope this works.

**Comment by Chillee** [comment]
@Dvbnhbq Although some of the people who've contributed to this extension are Microsoft employees, many are not. For example, I'm just a college student who contributes to this extension in between managing courses, research, and other extracurriculars.

**Comment by jpoon** [comment]
Disclaimer: I *am* a Microsoft employee, but I do this in my off-time. @Dvbnhbq  I'm curious what your experience with these other "buggy" Microsoft products you mentioned. A lot of the teams are now using GitHub to track issues, but if you have come across a specific issue I can see if I can track down the owner within the company.

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/pull/2386
