### ISSUE TITLE
gb and hlsearch conflict

### ISSUE THREAD

**Issue by Xyzor** [VSCodeVim/Vim#2369]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**What happened**:
When the `hlsearch` is enabled the `gb` stops after the second selection and the mod is `-- NORMAL-- MULTI CURSOR`.

**What did you expect to happen**:
To be able to select more items.

**How to reproduce it (as minimally and precisely as possible)**:
Enable `hlsearch` and try to use `gb` more than 2 times.

**Environment**:

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.19.3
- OS version: Ubuntu 16.04

**Comment by J-Fields** [comment]
I can't reproduce. Is this still an issue?

**Comment by Xyzor** [comment]
@J-Fields I just tried it again, and couldn't reproduce it.
