### ISSUE TITLE
cann't remap to tab?

### ISSUE THREAD

**Issue by Yuan-Hang** [VSCodeVim/Vim#2373]
Hi.
i want to map tab to gt, like `nmap <tab> gt' in vimrc, i have tried "tab", "Tab", "<tab>", and "<Tab>", but doesn't work at all. is there a way to do this?
```
"vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["g","t"],
            "after": ["tab"]
        },
 ]
```

**Comment by Chillee** [comment]
Sounds like you found the solution to your issues?

**Comment by Yuan-Hang** [comment]
@Chillee , you shuold use some like this:
```
"before": ["tab"]
"after": ["g", "t"]
```
