### ISSUE TITLE
How does one keep default movement keys while being on Dvorak?

### ISSUE THREAD

**Issue by taharathussain** [VSCodeVim/Vim#2377]
I want to use default (qwerty) vim movement keys h  j k l while being on dvorak keyboard. I don't use Vim from commandline, but I do use Vim emulator (VSCodeVim/Vim) in VSCode. 

Is there anyway to map keys to default qwerty's hjkl?

**Comment by Smike16** [comment]
Have the same problem. Anyone has keybindings for dvorak?
I don't want to do this https://github.com/Smike16/Sublime-Keymap/blob/master/sublime-keymap again =(

**Comment by jpoon** [comment]
You would have to come up with remappings for whatever are the `hjkl` keys on Dvorak = https://github.com/VSCodeVim/Vim#key-remapping.

**Comment by Smike16** [comment]
`{
    "vim.insertModeKeyBindings": [
        {
            "before": ["e", "u"],
            "after": ["<esc>"]
        }
    ],
    "vim.otherModesKeyBindings": [
        {
            "before": ["d"],
            "after": ["<left>"]
        },
        {
            "before": ["h"],
            "after": ["<down>"]
        },
        {
            "before": ["t"],
            "after": ["<up>"]
        },
        {
            "before": ["n"],
            "after": ["<right>"]
        }
    ],
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["'"],
            "after": ["q"]
        },
        {
            "before": [","],
            "after": ["w"]
        },
        {
            "before": [">"],
            "after": ["E"]
        },
        {
            "before": ["p"],
            "after": ["r"]
        },
        {
            "before": ["P"],
            "after": ["R"]
        },
        {
            "before": ["p"],
            "after": ["r"]
        },
        {
            "before": ["P"],
            "after": ["R"]
        },
        {
            "before": ["y"],
            "after": ["t"]
        },
        {
            "before": ["Y"],
            "after": ["T"]
        },
        {
            "before": ["g"],
            "after": ["u"]
        },
        {
            "before": ["G"],
            "after": ["U"]
        },
        {
            "before": ["c"],
            "after": ["i"]
        },
        {
            "before": ["C"],
            "after": ["I"]
        },
        {
            "before": ["r"],
            "after": ["o"]
        },
        {
            "before": ["R"],
            "after": ["O"]
        },
        {
            "before": ["l"],
            "after": ["p"]
        },
        {
            "before": ["L"],
            "after": ["P"]
        },
        {
            "before": ["/"],
            "after": ["["]
        },
        {
            "before": ["?"],
            "after": ["{"]
        },
        {
            "before": ["="],
            "after": ["]"]
        },
        {
            "before": ["+"],
            "after": ["}"]
        },
        {
            "before": ["o"],
            "after": ["s"]
        },
        {
            "before": ["O"],
            "after": ["S"]
        },
        {
            "before": ["e"],
            "after": ["d"]
        },
        {
            "before": ["E"],
            "after": ["D"]
        },
        {
            "before": ["u"
            ],
            "after": ["f"]
        },
        {
            "before": ["U"],
            "after": ["F"]
        },
        {
            "before": ["i"],
            "after": ["g"]
        },
        {
            "before": ["I"],
            "after": ["G"]
        },
        {
            "before": ["d"],
            "after": ["h"]
        },
        {
            "before": ["D"],
            "after": ["H"]
        },
        {
            "before": ["h"],
            "after": ["j"]
        },
        {
            "before": ["H"],
            "after": ["J"]
        },
        {
            "before": ["t"],
            "after": ["k"]
        },
        {
            "before": ["T"],
            "after": ["K"]
        },
        {
            "before": ["n"],
            "after": ["l"]
        },
        {
            "before": ["N"],
            "after": ["L"]
        },
        {
            "before": ["s"],
            "after": [";"]
        },
        {
            "before": ["S"],
            "after": [":"]
        },
        {
            "before": ["-"],
            "after": ["'"]
        },
        {
            "before": ["\\"],
            "after": ["|"]
        },
        {
            "before": [";"],
            "after": ["z"]
        },
        {
            "before": [":"],
            "after": ["Z"]
        },
        {
            "before": ["q"],
            "after": ["x"]
        },
        {
            "before": ["Q"],
            "after": ["X"]
        },
        {
            "before": ["j"],
            "after": ["c"]
        },
        {
            "before": ["J"],
            "after": ["C"]
        },
        {
            "before": ["k"],
            "after": ["v"]
        },
        {
            "before": ["K"],
            "after": ["V"]
        },
        {
            "before": ["x"],
            "after": ["b"]
        },
        {
            "before": ["X"],
            "after": ["B"]
        },
        {
            "before": ["b"],
            "after": ["n"]
        },
        {
            "before": ["B"],
            "after": ["N"]
        },
        {
            "before": ["w"],
            "after": [","]
        },
        {
            "before": ["W"],
            "after": ["<"]
        }
    ]
}
`

**Comment by Smike16** [comment]
Thanks @jpoon, this worked for me:
https://github.com/Smike16/Sublime-Keymap/blob/master/vscode.json

**Comment by taharathussain** [comment]
@Smike16 looks like it's for Sublime Text, but I want to make it work inside VSCode through the VSCodeVim extension.
Thank You!

**Comment by Smike16** [comment]
@taharathussain, I always used Sublime Text and created this repo https://github.com/Smike16/Sublime-Keymap.

Didn't want to create another repo for vscode. That's why I added dvorak support for vscode to the same repo here: https://github.com/Smike16/Sublime-Keymap/blob/master/vscode.json
