### ISSUE TITLE
Search and replace doesn't work with current line (.) and relative lines

### ISSUE THREAD

**Issue by Anheurystics** [VSCodeVim/Vim#2384]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: Using . to indicate current line and +<n>s in search and replace doesn't work

**What did you expect to happen**: It does the replacing from current line until the specified number of lines

**How to reproduce it (as minimally and precisely as possible)**: Set cursor to a line, and then try to replace any text in the line and the n next lines by typing :.,+ns/search/replace/g

**Environment**:

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.20.1
- OS version: Ubuntu 16.04.2 LTS

**Comment by captaincaius** [comment]
If nobody minds, I'll probably scratch my itch and take a stab at this, along with the shorthand in vim whereby if you hit 4:s, it'll go into command mode with :.,.+3s ready for you ;)
