### ISSUE TITLE
Not able to Search with newline or carriage return characters

### ISSUE THREAD

**Issue by BlessYAHU** [VSCodeVim/Vim#2387]
BUG REPORT

**What happened**:
On a multiline file I tried to use the following search and replace : '<,'>s/(.*\n)/test $1/g
This did not work.  Is my syntax wrong, or is \n not being recognized?  This search replace works without the \n

**What did you expect to happen**:
the word "test" should be prepended to each line selected.

**How to reproduce it (as minimally and precisely as possible)**:
1.  Open multiline file in VSCode.
2.  In visual mode, select at least two lines.
3.  go into search and replace mode (semicolon) and type in the following:  s/(.*\n)/test $1/g
this regex will find each line and replace it with the word "test" and with the matched line.  

The final serch replace should look similiar to this: '<,'>s/(.*\n)/test $1/g

4.  Hit enter

**Environment**:
Windows 10
Visual Studio Code v1.20.1
VSCodeVim 0.10.13

**Comment by sql-koala** [comment]
Yes, matching `\n` does not work with :s right now.
See #5185, same issue.

**Comment by J-Fields** [comment]
Closing in favor of #5185
