### ISSUE TITLE
`` not working with jump incurred by %

### ISSUE THREAD

**Issue by yaodis** [VSCodeVim/Vim#2389]
**BUG REPORT**:
\`\`(go to the position before the last jump) not working with `%`(find the next brace, bracket)

**What happened**:
```
return b(c())
```
in this snippet I want to delete outside function call `b()` and leave only `return c()`
plain vim command I use is starting cursor at `b` and press %x``xx in normal mode(verified in terminal vim)
but in VSCodeVim \`\` not working as intended

**What did you expect to happen**:
\`\` should bring cursor back to character `b`, but it does not

**Environment**:

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.20.1
- OS version: macOS 10.12.6

**Comment by J-Fields** [comment]
Seems to be fixed. Closing.
