### ISSUE TITLE
Can't map enter key

### ISSUE THREAD

**Issue by CodingJonas** [VSCodeVim/Vim#2390]
**What happened**:
Enter key in normal mode just goes to the next line.

**What did you expect to happen**:
I want to map the enter key to save the file in normal mode

**How to reproduce it (as minimally and precisely as possible)**:
This is the part of my settings file:
```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<Enter>"],
            "after": [], 
            "commands": [
                {
                    "command": "workbench.action.files.save",
                    "args": []
                }
            ]
        },
        ....
```
- Extension (VsCodeVim) version:
0.10.13

**Comment by fhdhsni** [comment]
Use `\n` instead of `<Enter>`

**Comment by jpoon** [comment]
Dupe of https://github.com/VSCodeVim/Vim/issues/2584

**Comment by jpoon** [comment]
Took another look at the code. I was mistaken. Submitted a PR to fix this.
