### ISSUE TITLE
`gqap` deletes whitespace in LaTeX

### ISSUE THREAD

**Issue by karljs** [VSCodeVim/Vim#2393]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
Ran `gqap` to wrap a paragraph of text in a tex file.  While the text was wrapped correctly, whitespace up until the next paragraph was incorrectly deleted.

**What did you expect to happen**:
Paragraph is wrapped at 80 characters and contents outside the paragraph are unmodified.

**How to reproduce it (as minimally and precisely as possible)**:
Create a tex file with a line longer than 80 characters, several blank lines, and then more text.  Move the cursor to the first line/paragraph and run `gqap`.

**Environment**:

- Extension Name: vim
- Extension Version: 0.10.13
- OS Version: Darwin x64 17.4.0
- VSCode version: 1.20.1

**Comment by willmtemple** [comment]
I have this bug as well. `gqap` doesn't work the same way as it does in Vim. It will join two paragraphs together for example:

```
This is a very long line that has more than 80 characters in it and I want it to wrap onto the next line when I put the cursor here and press `gqap` in VSCodeVim.

This is a second paragraph.
```

If I put the cursor in the first line and then use `gqap` the result is:

```
This is a very long line that has more than 80 characters in it and I want it
to wrap onto the next line when I put the cursor here and press `gqap` in
VSCodeVim.
This is a second paragraph.
```

The expected result is:

```
This is a very long line that has more than 80 characters in it and I want it
to wrap onto the next line when I put the cursor here and press `gqap` in
VSCodeVim.

This is a second paragraph.
```

This means that any time I use `gqap` in VSCodeVim (very frequently for editing Markdown documents!) I have to find the next paragraph break and manually insert a line.

**Comment by mgjv** [comment]
I would like to add my voice to this. Both gqap and gggqG delete lines at the end of a paragraph, basically making them no longer a paragraph. The intended behaviour is described in the vim documentation (online copy here: http://vimdoc.sourceforge.net/htmldoc/usr_25.html).

gqap is definitely in my top 5 of commands: especially in Markdown documents. I write a lot of documentation, and I like it to be formatted well. It would be great if this was fixed.
