### ISSUE TITLE
Cmd/Ctrl + C does not copy with syntax highlight

### ISSUE THREAD

**Issue by gnapse** [VSCodeVim/Vim#2398]
**BUG REPORT**

**What happened**

When copying code using `Cmd+C`, it does not copy in the clipboard the html version of what was copied, which is html rendering the code with the syntax highlight and everything, as it looks like while in the editor.

**What did you expect to happen**

I expect `Cmd + C` to copy not only the text version of the code, but also the syntax-highlighted version, as it occurs when this extension is not installed.

**How to reproduce it**

1. Open any file with syntax highlight, select a block of text and press `Cmd+C` or `Ctrl + C`.
2. Open a rich text editor, such as Microsoft Word, or Apple Pages, or Libre/Open Office.
3. Paste into a blank document what you just copied. See that what you got is plain text.

Try the first two steps above with this extension disabled, and on step 3 you'll get the syntax highlighted version of that code instead.

**Environment**

- Extension (VsCodeVim) version: 0.10.13
- VSCode version: 1.20.1
- OS version: macOS High Sierra

**Cross reference**

Also, for reference, follow this thread from [this comment](https://github.com/octref/polacode/issues/26#issuecomment-366969016) on, where I started discussing this issue assuming it was the problem of another extension, that it turns out expects you to be able to copy the syntax-highlighted version of the code. After digging a bit, I realized it was not that extension's fault, but this one instead.

**Comment by gnapse** [comment]
Hello? Is anybody out there?

**Comment by jpoon** [comment]
With #3261, this is now supported.
