### ISSUE TITLE
Arrow keys to navigate within soft-wrapped text block.

### ISSUE THREAD

**Issue by timtro** [VSCodeVim/Vim#2403]
Thanks in advance. I'm sorry if this has an easy fix. I did spend quite a bit of time trying to find a solution or a configuration option and I hope I didn't miss something trivial. I also poked around the Slack channel but must have joined at a slow time.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT maybe? Probably FEATURE REQUEST?
**What happened**: See https://github.com/Microsoft/vscode/issues/34448 . The arrow keys don't allow me to navigate among visual (soft-wrapped) lines in any mode. I have remapped `j` and `k` to `gj` and `gk` in non-insert modes, but in insert mode, I get around with the arrow keys.

**What did you expect to happen**: I expect (or at least wish) that navigation with arrow keys works as it does with vanilla VS Code. That is, I want to navigate up and down within soft-wrapped lines using the arrow keys (or at least have the option to enable it.)

**How to reproduce it (as minimally and precisely as possible)**: Type a long line with soft wrap, and then try to navigate within it.

**Environment**: Ubuntu, Xmonad based custom desktop environment using Xorg.
- Extension (VsCodeVim) version: v0.11.0
- VSCode version: 1.20.1
- OS version: 17.10.1

**Comment by timtro** [comment]
On the Slack channel, some helpful people pointed out that I should avoid using the arrow keys anyway, as there are almost always better ways to move about in normal-mode. I think that's largely true. Although I already use a lot of vim movement commands effectively, I'm compelled to work harder to build more effective habits when working in a very small neighbourhood of a file (where I would normally default to using arrows).

In the meantime, a suitable workaround is to rebind the keys. I tried this, of course, before posting the issue, but I didn't know well enough to apply `<C-o>` first:
```json
    "vim.insertModeKeyBindings": [
        {
            "before": ["<up>"],
            "after": ["<C-o>", "g", "k"]
        },
        {
            "before": ["<down>"],
            "after": ["<C-o>", "g", "j"]
        },
    ]
```

Thanks to @arussellk, @Nick and @chillee from the slack. https://vscodevim.slack.com/archives/C0ENQMTUM/p1520358214000115

**Comment by karlhorky** [comment]
Seems like I need to configure that without the angle brackets around `up` and `down`:

```
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "up"
      ],
      "after": [
        "<C-o>",
        "g",
        "k"
      ]
    },
    {
      "before": [
        "down"
      ],
      "after": [
        "<C-o>",
        "g",
        "j"
      ]
    },
  ],
```

**Comment by karlhorky** [comment]
Hm, looks like this isn't working anymore, with or without the angle brackets...

**Comment by metasong** [comment]
the easy workaround is uing the default <kbd>up</kbd> <kbd>down</kbd> of vscode's shortcut setting( <kbd> ctrl+k+s </kbd> ), it is overrided by vim after install `the vim extension`:
```
  {
    "key": "down",
    "command": "cursorDown",
    "when": "textInputFocus"
  },
  {
    "key": "up",
    "command": "cursorUp",
    "when": "textInputFocus"
  },
```

**Comment by karlhorky** [comment]
Thanks @metasong, I'll give it a try.

**Comment by karlhorky** [comment]
Cool, looks like that works @metasong, cheers!

So the settings to change in order to get <kbd>j</kbd>, <kbd>k</kbd>, <kbd>↑</kbd> and <kbd>↓</kbd> to skip only single lines with VS Code Vim:

**settings.json**

```json
{
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["j"],
      "after": ["g", "j"]
    },
    {
      "before": ["k"],
      "after": ["g", "k"]
    },
    {
      "before": ["down"],
      "after": ["g", "j"]
    },
    {
      "before": ["up"],
      "after": ["g", "k"]
    }
  ]
}
```

**keybindings.json**

```json
[
  {
    "key": "down",
    "command": "cursorDown",
    "when": "textInputFocus"
  },
  {
    "key": "up",
    "command": "cursorUp",
    "when": "textInputFocus"
  }
]
```

Ref: [my dotfiles]()

**Comment by karlhorky** [comment]
**Edit:** This doesn't actually work. It has a critical problem with it:

It escapes from autosuggest boxes. Here's a gif:

![kapture 2019-01-11 at 13 25 56](https://user-images.githubusercontent.com/1935696/51033806-d8f0f280-15a4-11e9-9db6-d55e708fbab9.gif)

<details>
<summary>Original broken keybindings. Do not use!</summary>
Cool, looks like that works @metasong, cheers!

So the settings to change in order to get <kbd>j</kbd>, <kbd>k</kbd>, <kbd>↑</kbd> and <kbd>↓</kbd> to skip only single lines with VS Code Vim:

**settings.json**

```json
{
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["j"],
      "after": ["g", "j"]
    },
    {
      "before": ["k"],
      "after": ["g", "k"]
    },
    {
      "before": ["down"],
      "after": ["g", "j"]
    },
    {
      "before": ["up"],
      "after": ["g", "k"]
    }
  ]
}
```

**keybindings.json**

```json
[
  {
    "key": "down",
    "command": "cursorDown",
    "when": "textInputFocus"
  },
  {
    "key": "up",
    "command": "cursorUp",
    "when": "textInputFocus"
  }
]
```

Ref: [my dotfiles](https://github.com/karlhorky/dotfiles/tree/master/settings/Library/Application%20Support/Code/User)
</details>

**Comment by karlhorky** [comment]
**Edit:** @metasong This doesn't actually work. It has a critical problem with it:

It escapes from autosuggest boxes. Here's a gif:

![kapture 2019-01-11 at 13 25 56](https://user-images.githubusercontent.com/1935696/51033806-d8f0f280-15a4-11e9-9db6-d55e708fbab9.gif)

<details>
<summary>Click here to show original broken keybindings (saved for posterity). Do not use!</summary>
Cool, looks like that works @metasong, cheers!

So the settings to change in order to get <kbd>j</kbd>, <kbd>k</kbd>, <kbd>↑</kbd> and <kbd>↓</kbd> to skip only single lines with VS Code Vim:

**settings.json**

```json
{
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["j"],
      "after": ["g", "j"]
    },
    {
      "before": ["k"],
      "after": ["g", "k"]
    },
    {
      "before": ["down"],
      "after": ["g", "j"]
    },
    {
      "before": ["up"],
      "after": ["g", "k"]
    }
  ]
}
```

**keybindings.json**

```json
[
  {
    "key": "down",
    "command": "cursorDown",
    "when": "textInputFocus"
  },
  {
    "key": "up",
    "command": "cursorUp",
    "when": "textInputFocus"
  }
]
```

Ref: [my dotfiles](https://github.com/karlhorky/dotfiles/tree/master/settings/Library/Application%20Support/Code/User)
</details>

**Comment by karlhorky** [comment]
@timtro Did you end up finding a better fix for this? Or alternatively, are you still using settings similar to [your original settings](https://github.com/VSCodeVim/Vim/issues/2403#issuecomment-370953547) or [my fixed settings](https://github.com/VSCodeVim/Vim/issues/2403#issuecomment-409202905)?

It would be cool to hear a more official / less hacky recommendation for how to moving among word wrapped lines.

Maybe an improved version of @metasong's keybinding somehow that doesn't escape autocompletes? It also felt like after a while, this keybinding would cause performance problems... Would need to test this more, if there was a solution. 

cc @jpoon @Chillee @arussellk

**Comment by karlhorky** [comment]
I think I may have come up with a fixed version of @metasong's keybindings, based on the `when` condition from the [extension keybindings](https://github.com/VSCodeVim/Vim/blob/6805ae4311e322e9d3ef0ca07a2811ee411944b4/package.json#L100-L109).

It looks like this:

```json
  {
    "key": "up",
    "command": "cursorUp",
    "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  {
    "key": "down",
    "command": "cursorDown",
    "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  }
```

This doesn't need any changes to settings.

I will start using this and see if there are any other problems (including performance issues) with it.

**Comment by timtro** [comment]
> @timtro Did you end up finding a better fix for this? Or alternatively, are you still using settings similar to [your original settings](https://github.com/VSCodeVim/Vim/issues/2403#issuecomment-370953547) or [my fixed settings](https://github.com/VSCodeVim/Vim/issues/2403#issuecomment-409202905)?
> 
> It would be cool to hear a more official / less hacky recommendation for how to moving among word wrapped lines.
> 
> Maybe an improved version of @metasong's keybinding somehow that doesn't escape autocompletes? It also felt like after a while, this keybinding would cause performance problems... Would need to test this more, if there was a solution.
> 
> cc @jpoon @Chillee @arussellk

Much less hacky: I switched back to (Neo)vim and (more importantly) stopped using the arrow keys to navigate so much. I just hit escape reflexively when I'm done editing and use h,j,k,l to move about.

I still use VS code from time to time—especially for markdown (thanks to markdown-preview-enhanced.)

**Comment by karlhorky** [comment]
Yeah, Neovim / Vim are options as well, but VS Code has just too much good stuff to switch completely :)

My [option above](https://github.com/VSCodeVim/Vim/issues/2403#issuecomment-456365357) works really well actually, and it's just copying over the conditions from the extension - so not all that hacky.

I've opened a pull request to document this method as current best practice: #3623

**Comment by karlhorky** [comment]
Now that the documentation PR is open, you can probably close this one @timtro.
