### ISSUE TITLE
Backward text selection using mouse does not include the last character of the selection area.

### ISSUE THREAD

**Issue by zhichenx** [VSCodeVim/Vim#2404]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Probably bug report

**What happened**:
After I update to 0.11.0, when I use mouse to backward select an area of text, the last character is not included.

**What did you expect to happen**:
The last character should be selected.

**How to reproduce it (as minimally and precisely as possible)**:
e.g., `abcd`
If I want to select the whole word `abcd`, I can put my mouse at the end of line or on the character `d`, backward move to `a`. But when I do it in Vim mode, `d` is not selected. However, if I use keyboard by moving cursor to `d` and pressing `vB`, the whole word is selected.

**Environment**:

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: macOS 10.13.3

**Comment by jpoon** [comment]
Can confirm this indeed looks like a regression. Does not repro with 0.10.13.

**Comment by timtro** [comment]
NB: I'm using `"vim.mouseSelectionGoesIntoVisualMode": false,` and I don't have the problem when using the mouse to highlight while in insert mode. I do with visual or normal modes.

**Comment by esetnik** [comment]
Can we get this fixed asap? it's totally broken mouse selections when vim is active.

**Comment by Chillee** [comment]
@jpoon I think I'm going to revert the refactor that caused this issue.

**Comment by jpoon** [comment]
Thanks for the fix @Chillee.
