### ISSUE TITLE
gf empties target file

### ISSUE THREAD

**Issue by iammerrick** [VSCodeVim/Vim#2408]
BUG REPORT

**What happened**: Use `gf` and it seems to delete the file and create a new file on top every time.

**What did you expect to happen**: I would go to the file if it exists and if it doesn't create the file.

**How to reproduce it (as minimally and precisely as possible)**: 

Create two files:
`somefile.js`
```
import hi from './hello'
```

and in `hello.js` place any content.

hover over "hello" and type "gf". It will empty the contents of hello.js.

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1 & 1.21-insiders
- OS version: OSX High Sierra

**Comment by jpoon** [comment]
Did this happen on previous versions of the extension? Might be a regression from this: https://github.com/VSCodeVim/Vim/pull/2392/

**Comment by iammerrick** [comment]
Thank you @jpoon ! This will be great!

**Comment by iammerrick** [comment]
@jpoon Is this worth cutting a release for? If someone isn't using version control this could potentially be a very devastating bug. :-)

**Comment by jpoon** [comment]
I've been super busy lately with work -- can you [@Chillee] cut a release after your PR is merged?

**Comment by Chillee** [comment]
@jpoon will try to do it tonight.

**Comment by iammerrick** [comment]
<3 Thank you!
