### ISSUE TITLE
dd, cc, x - Don't work anymore with vim.useSystemClipboard

### ISSUE THREAD

**Issue by simonwjackson** [VSCodeVim/Vim#2412]
**BUG REPORT** 

**What happened**:

Nothing

**What did you expect to happen**:
Deletion

**How to reproduce it (as minimally and precisely as possible)**:
```json
{
  "vim.useSystemClipboard": true
}
```

**Environment**:

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: Win10

**Comment by Chillee** [comment]
@simonwjackson I'm pretty sure this is because the clipboard library we're using is failing, causing the entire command to fail. For example, if you do `"_dd` it should work just fine.

**Comment by simonwjackson** [comment]
Thanks. Is this just a temporary fix?

**Comment by Chillee** [comment]
@simonwjackson It's not a temporary fix (it copies it to the blackhole register, bypassing the useSystemClipboard issue entirely).

Could you post the error in Help > Open Dev Tools when you try to copy? I'll file it in the clipboardy repository if that seems to be the issue,

**Comment by jpoon** [comment]
You say `doesn't work anymore`. Do you know what version it did work?

We updated the clipboardy package 3 months ago (https://github.com/VSCodeVim/Vim/blame/master/package.json#L594)

**Comment by simonwjackson** [comment]
@jpoon It was working on Windows 10 Anniversary edition. When I upgraded to the latest windows build, is when i started having issues.

I've noticed that when i press `dd` and look at the bottom of VSCODE (next to --NORMAL--), i can see the first `d` still there, as if its waiting for the next letter to be pressed.

**Comment by evenfrost** [comment]
@simonwjackson have you checked VSCode's Developer Tools? There should be an error as in my case.

**Comment by simonwjackson** [comment]
**console.ts:123**

```
[Extension Host] Error: The system cannot find the path specified.

	at Function.module.exports.sync (C:\Users\simon_jackson\.vscode\extensions\vscodevim.vim-0.11.0\node_modules\execa\index.js:303:26)
	at Object.copySync (C:\Users\simon_jackson\.vscode\extensions\vscodevim.vim-0.11.0\node_modules\clipboardy\lib\windows.js:14:26)
	at Object.exports.writeSync.input [as writeSync] (C:\Users\simon_jackson\.vscode\extensions\vscodevim.vim-0.11.0\node_modules\clipboardy\index.js:38:13)
	at Function.Copy (C:\Users\simon_jackson\.vscode\extensions\vscodevim.vim-0.11.0\out\src\util.js:29:20)
	at Function.putNormalRegister (C:\Users\simon_jackson\.vscode\extensions\vscodevim.vim-0.11.0\out\src\register\register.js:154:30)
	at Function.put (C:\Users\simon_jackson\.vscode\extensions\vscodevim.vim-0.11.0\out\src\register\register.js:62:26)
	at YankOperator.<anonymous> (C:\Users\simon_jackson\.vscode\extensions\vscodevim.vim-0.11.0\out\src\actions\operator.js:239:33)
	at Generator.next (<anonymous>)
	at C:\Users\simon_jackson\.vscode\extensions\vscodevim.vim-0.11.0\out\src\actions\operator.js:13:71
	at Promise (<anonymous>)
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:394
(anonymous) @ extensionHost.ts:211
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

**Comment by jpoon** [comment]
@simonwjackson interesting. for that case, seems like its an issue on extension upgrade that Windows users have reported lately. Can you try what was suggested here and see if that works: https://github.com/VSCodeVim/Vim/issues/2415#issuecomment-370246230?

**Comment by DoubleB123** [comment]
@evenfrost Your solution worked for me on Ubuntu 16.04

**Comment by simonwjackson** [comment]
#2226 solved it for me. Thanks!

**Comment by yifanchen** [comment]
I have an issue has been bugging me for a while. I hope I can get an explain here. When I have "Use System Clipboard" checked. `change` command will copy, e.g. If I do a `cw`, then the word get copied to the system clipboard which was not intentional.
