### ISSUE TITLE
Vim mode simply does not work (VSCode 1.20.1) 

### ISSUE THREAD

**Issue by sandman21dan** [VSCodeVim/Vim#2415]
**BUG REPORT**:

Vim mode seems to not get activated

**What happened**:
Vim mode does not get activated

**What did you expect to happen**:
Vim to start in normal mode

**How to reproduce it (as minimally and precisely as possible)**:
Simply using the windows version of VScode 1.20.1 and Vim mode 0.11.0

Are there any known compatibility issues?

Tried disabling many other extensions (First time I noticed Vim not working anymore was after installing the flutter extension)

**Environment**:
Windows

- Extension (VsCodeVim) version:
- VSCode version: 0.11.0
- OS version: Windows 10

**Comment by b0wter** [comment]
Same thing for me on Windows 10 after updating to 1.20.1. Tried reinstalling the addon, didnt help.

**Comment by jpoon** [comment]
Sounds like a dupe of https://github.com/VSCodeVim/Vim/issues/2226. If this *is* the issue, please report back to VSCode and update https://github.com/Microsoft/vscode/issues/40260.

**Comment by b0wter** [comment]
Thanks, the solution works for me.

**Comment by sandman21dan** [comment]
Solution in #2266 worked for me as well, just in case your wondering on Windows the .vscode folders sits on your username folder, i.e. C:\Windows\Users\user_name\.vscode\extensions

**Comment by tekdroid** [comment]
The suggested solutions didn't work for me. I had to revert to 1.0.7 to get it to work. 1.0.8 and 1.1.0 do not work at all for me.

**Comment by joe-niland** [comment]
@sandman21dan Extension directory in windows is at %USERPROFILE%\.vscode\extensions
