### ISSUE TITLE
Swapped keys (CAPS LOCK <-> ESCAPE) are not applied

### ISSUE THREAD

**Issue by rok-povsic** [VSCodeVim/Vim#2419]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report.

**What happened**:
I have CAPS LOCK and ESC swapped as escaping is more common for me than switching typing case. The swap works everywhere - in all programs, terminal etc., including VS Code menues - except when actually typing the text, using VS Code Vim, i.e. when trying to get out of the normal mode.

For example, what happens now is the following - when in insert mode:
- pressing the CAPS LOCK key - no effect,
- pressing the ESCAPE key - goes to normal mode AND current typing case is switched.

**What did you expect to happen**:

I'd expect  ESC and CAPS LOCK to be swapped same as everywhere else in the system.

**How to reproduce it (as minimally and precisely as possible)**:

Using Gnome Tweak Tool, enable the swap:
![image](https://user-images.githubusercontent.com/1495233/36961904-9dfa059c-204d-11e8-9758-1293b36385c0.png)

I've also tried using another swap keys approach, by modifying `/usr/share/X11/xkb/symbols/pc` (as per [this post](https://askubuntu.com/questions/325272/permanent-xmodmap-in-ubuntu-13-04/347382#347382?newreg=4eb097870a15490ebbe39d78412f9797)) with same result.

**Environment**:

- Extension (VsCodeVim) version: **0.11.0**
- VSCode version: **1.20.1**
- OS version: **Ubuntu 16.04, Gnome 3.18.2**

Thank you a lot. I greatly enjoy using VS Code & the Vim plugin.

**Comment by Chillee** [comment]
This is a bug on VSCode's end. View a workaround here: https://github.com/VSCodeVim/Vim/issues/1479#issuecomment-292452557
