### ISSUE TITLE
VSCodeVim becomes unusable intermittently 

### ISSUE THREAD

**Issue by kriscoleman** [VSCodeVim/Vim#2421]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: Without any rhyme or reason, sometimes vim will stop responding to keyboard input and become unusable. When this happens, it appears that vim input has broken completely. If you sit and wait, you might find text will start inputting at a very slow rate (10+ seconds per keystroke). 

**What did you expect to happen**: Vim to accept keyboard input without lag or breaking. 

**How to reproduce it (as minimally and precisely as possible)**: I am not sure, this happens to me intermittently. I have checked my console and logs for any extension errors and have not come up with anything. I have disabled other extensions, and it still happens. Closing and reopening VSCode will not solve the issue. I've noticed the only thing that works is to uninstall/reinstall vscodevim. 

One observation, is that I've only noticed this happen when I enter `insert` mode. Is there a cache or something within vscodevim that could be getting overloaded? 

I've had to completely remove it as this issue killed my productivity. 

**Environment**: VSCode on MacOs. Editing an Angular5 project. 

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: 13.11

**Comment by kriscoleman** [comment]
I recorded a video of this happening and posted it to the #users channel in the VsCodeVim slack. Here is the link: https://vscodevim.slack.com/files/U9JT0LJF4/F9JTNTRQS/vscodevim-slow.mov

**Comment by kriscoleman** [comment]
Upon more investigation, I realized I had not disabled all extension correctly. After disabling all extensions, it _seems_ to have gone away. I'll try to trace down the extension and report back if I find the culprit.

**Comment by kriscoleman** [comment]
I traced it down to `auto-rename-tag` extension, disabling it seems to be the culprit causing VIM to go unresponsive, in case anyone else encounters this issue.

**Comment by nineclicks** [comment]
@kriscoleman I believe you can close the issue if you don't think it has to do with this project anymore.

**Comment by Chillee** [comment]
@nineclicks I think I've seen multiple people run into issues with that extension. At the same time, however, there's probably something we can do about it. However, as there's already an issue tracking this particular conflict, I will close this issue.

https://github.com/VSCodeVim/Vim/issues/2214
