### ISSUE TITLE
Repeat with . ignores Delete key if first keystroke

### ISSUE THREAD

**Issue by nineclicks** [VSCodeVim/Vim#2423]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**What happened**:
Delete keystroke in insert mode is not repeated with . unless another keystroke comes before it

**What did you expect to happen**:
Delete keystroke is repeatable as first keystroke

**How to reproduce it (as minimally and precisely as possible)**:
type:
```
123test
123test
```
place cursor after first 123, change to insert mode and press the delete key 4 times to erase "test" then type "qwert". Exit insert mode, place cursor after second 123 and press . to repeat. "qwert" is inserted but "test" is not deleted.

Everything works normally as long as some other keystroke comes before the delete key.

**Environment**:

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: Windows 7 x64

**Comment by ldm0** [comment]
Working on it.
