### ISSUE TITLE
moving to matching braces not working correctly

### ISSUE THREAD

**Issue by 3rdey3** [VSCodeVim/Vim#2427]
**BUG REPORT**:

**What happened**:
when block contains string with closing bracket, cursor moves to the the closing bracket inside of string instead of actual end of block.

**What did you expect to happen**:
cursor should move to actual matching brace

**How to reproduce it (as minimally and precisely as possible)**:
Example 1 -

`public string Method(string abc, ")")`
`place cursor here --^`
`press %`
`public string Method(string abc, ")")`
`cursor moves here ----------------^`
`public string Method(string abc, ")")`
`cursor should move here ------------^`

Example 2 -
`if (true)`
`{ // <-- select this brace and press %`
`    Console.Write("}"); // <-- cursor moves to this curly brace`
`} // <-- cursor should move to this curly brace`

**Environment**:

- Extension (VsCodeVim) version: 0.11.0
- VSCode version: 1.20.1
- OS version: Windows 10 Build 1709 x64

**Comment by Chillee** [comment]
Same issue as this: https://github.com/VSCodeVim/Vim/issues/651 I believe.

Closing in favor of the older one.
