### ISSUE TITLE
Ctrl-w c doesn't close windows

### ISSUE THREAD

**Issue by Sushisource** [VSCodeVim/Vim#2429]
Hi! Couldn't find anything in the issue tracker about <kbd>Ctrl-w c</kbd>, mostly just confused people thinking <kbd>Ctrl-w</kbd> should immediately close a window. I love being able to use the <kbd>Ctrl-w</kbd> navigation, but not being able to close windows with it feels awkward, and you end up using some custom binding instead. Side note: `:bd` also doesn't close windows like I would expect.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature req

**What happened**: <kbd>Ctrl-w c</kbd> doesn't do anything

**What did you expect to happen**: <kbd>Ctrl-w c</kbd> should close the currently-open window.

**How to reproduce it (as minimally and precisely as possible)**: <kbd>Ctrl-w c</kbd> on any open editor.

**Environment**:

- Extension Name: vim
- Extension Version: 0.11.0
- OS Version: Linux x64 4.14.16-300.fc27.x86_64
- VSCode version: 1.20.1

Love the extension! Thanks!

**Comment by Sushisource** [comment]
So of course just after writing this I realized <kbd>Ctrl-w q</kbd> works just fine, which is a command I apparently never learned. Would still be nice to have <kbd>Ctrl-w c</kbd> I suppose, but no longer a super big deal. :man_shrugging:

**Comment by jpoon** [comment]
Actually, seems like we have another issue to track this request: https://github.com/VSCodeVim/Vim/issues/2379. Closing this as a dupe.
