### ISSUE TITLE
CTRL-N not creating new file

### ISSUE THREAD

**Issue by aaronshaver** [VSCodeVim/Vim#2440]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**What happened**:

CTRL-N doesn't open a new file while NOT in insert mode (I understand it is for auto-completion when in insert mode)

**What did you expect to happen**:

CTRL-N opens a new file

**How to reproduce it (as minimally and precisely as possible)**:

Type CTRL-N

**Environment**:

- Extension (VsCodeVim) version: 0.11.2
- VSCode version: Version 1.21.0 Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba Architecture x64
- OS version: Windows 10

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim#none-of-the-vim-ctrl-eg-ctrlf-ctrlv-commands-work

**Comment by aaronshaver** [comment]
Thanks! Darn, I would lose Visual Block Mode which I use. Well I'm glad to
know it's not a bug.

**Comment by jpoon** [comment]
You can configure the ctrlkeys individually. On my phone so can't link but the docs are in our read me
