### ISSUE TITLE
Suggest that set VScode Key precede over VSCodeVim Key.

### ISSUE THREAD

**Issue by wilon** [VSCodeVim/Vim#2441]
I tried SublimeText VIM model, and didn't feel discomfort to keys. But I try VSCodeVim, `cmd+c cmd+d`, all have bugs...

```
a
cmd+d 
cmd+d
cmd+d
Select some text by mouse
cmd+d 
cmd+d
cmd+d
```
↓                ↓
![VSCodeVimCmdDBUG](https://user-images.githubusercontent.com/7512755/37264772-56e0d5d0-25ea-11e8-88c8-6e3fd8ea38ea.gif)

Then I change keys like this https://github.com/VSCodeVim/Vim/issues/2325, But still do not work to me.

So I have to uninstall it. 😨

- OS version: MacOS

**Comment by jpoon** [comment]
Can you elaborate on:

> cmd+c cmd+d, all have bugs...

**Comment by wilon** [comment]
* `normal model` -> keypress `a` -> keypress `cmd+d` -> keypress `cmd+d` -> keypress `cmd+d`

* `normal model` -> keypress `a`  -> Select some text by mouse  -> keypress `cmd+d` -> keypress `cmd+d` -> keypress `cmd+d`

* `cmd+c` change to `normal model`, and I just want to copy something.

![](https://user-images.githubusercontent.com/7512755/37264772-56e0d5d0-25ea-11e8-88c8-6e3fd8ea38ea.gif)

**Comment by Chillee** [comment]
@wilon The difference is that we have the ctrl keys set to use vim by default. I think it's a matter of whether you're more used to using vim or using non-vim editors.

Try setting `useCtrlKeys` to false.
