### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by m0ru** [VSCodeVim/Vim#2444]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**What happened**: vscodevim crashes with `console.error` that it can't find lodash

```
Activating extension `vscodevim.vim` failed:  Cannot find module 'lodash'
```

![vscodevim crashes with `console.error` that it can't find lodash](https://user-images.githubusercontent.com/1730492/37373271-312240ae-2716-11e8-89fb-531aaa19087c.png)

**What did you expect to happen**: it to start

**How to reproduce it (as minimally and precisely as possible)**:

start vscode with the versions below. reinstalling the plugin and restarting vscode didn't help.

**Environment**:

- Extension (VsCodeVim) version: 0.11.2
- VSCode version: 1.21.0
- OS version: Windows 10 Education, 10.0.16299

![vscode 1.21.0](https://user-images.githubusercontent.com/1730492/37373321-6627b996-2716-11e8-943a-92493c9bd1d7.png)

**Comment by jpoon** [comment]
Please see https://github.com/VSCodeVim/Vim/issues/2436

**Comment by m0ru** [comment]
Thx :)
(and sry; forgot to remove the `is:open` flag when searching for lodash ^^")
