### ISSUE TITLE
Allow configuration similar to vim's "whichwrap"

### ISSUE THREAD

**Issue by Drakulix** [VSCodeVim/Vim#2446]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**What happened**:

When pressing left/right cursor keys, VSCodeVim will not move to the previous/next line after reaching first/last character in the line. Additionally there is no configuration option to allow this behavior.

There was an issue regarding this behavior on the Oct of 2016. https://github.com/VSCodeVim/Vim/issues/839

It resulted in fixing the navigation to match vim's default behavior. No options to change this was introduced and the commit in question of fixing this issue is not referenced.

I propose to make this configurable, as the original issue already states, that not expecting vim's default behavior in an IDE like VSCode is perfectly reasonable.

Because I cannot follow the original changeset modifying this behavior, it would be nice, if anybody could point me in the right direction. I would happily provide a pull request for this issue.

**Environment**:

- Extension (VsCodeVim) version: v0.11.2
- VSCode version: v1.12.0
- OS version: Fedora 27

**Comment by nomad-software** [comment]
I think this is a duplicate of https://github.com/VSCodeVim/Vim/issues/1211

**Comment by Drakulix** [comment]
@nomad-software 
Oh sorry, I did not find this issue. Its not a perfect duplicate, as #1211 is only referring to wrapping in Normal mode (but I think vim also applies this behavior in insert mode, if enabled, not sure though), but it is good enough. Going to close this.
