### ISSUE TITLE
How do i disable ctrl+alt+v?

### ISSUE THREAD

**Issue by janacm** [VSCodeVim/Vim#2450]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:

- Extension (VsCodeVim) version:
- VSCode version:
- OS version:

**Comment by dsschnau** [comment]
What does ctrl-alt-v do?

**Comment by janacm** [comment]
I use c-alt-v for a clipboard manager, but in VSCodeVim the key combination doesn't work. Is c-a-v not mapped to any VSCodeVim keybinding?

**Comment by Chillee** [comment]
@janacm I don't believe so. If you disable VSCodeVim, does it still work?

**Comment by jpoon** [comment]
Is this clipboard manager a VSCode extension? I don't believe we bind to `ctrl+alt+v`.

**Comment by bm-stschneider** [comment]
I think you can use this.
https://github.com/VSCodeVim/Vim#vimhandlekeys

**Comment by janacm** [comment]
@bm-stschneider I tried using vim.handleKeys, but how exactly do I specify the "alt" key? I tried this:

```
"vim.handleKeys": {
     "<C-A-v>": false,
     "<C-Alt-v>": false,
     "<C-alt-v>": false,
```

But no luck. How can I temporarily disable VSCodeVim? Or do I just un/reinstall

**Comment by bm-stschneider** [comment]
I guess Alt is M for Meta Key so maybe try that

**Comment by insominx** [comment]
How do you do this for cursor keys?  I've tried the following:
`"vim.handleKeys": {
        "down":false,
        "<down>": false,
        "<Down>": false,
    }`
to no avail.

**Comment by jpoon** [comment]
@janacm going through that `package.json` I can definitively say that we don't bind to `ctrl+alt+v`

**Comment by jpoon** [comment]
I don't understand. What are you expecting when you press `ctrl+alt+v`? This isn't a vim command that I am aware of. It's at least not a keycombo that we bind to.
