### ISSUE TITLE
Easymotion: Find character doesn't work with parenthesis

### ISSUE THREAD

**Issue by lbebber** [VSCodeVim/Vim#2455]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**What happened**:
`<leader><leader>f )` doesn't go to the next `)`

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:

- Extension (VsCodeVim) version: 10.11.2
- VSCode version: 1.21.1
- OS version: macOS 10.12.6

**Comment by SCLeoX** [comment]
Same issue. I think it is because somehow it decides to treat parenthesis as regex.

**Comment by alechstong** [comment]
same here on linux. To be more specific, it errors out when trying to match the following characters (the ones I found out):
round-braces ( )
box-braces [ ]
plus-sign +

I tried editing vim.jumptoanywhereregex, but I haven't managed to get it working.

**Comment by J-Fields** [comment]
This was fixed with https://github.com/VSCodeVim/Vim/pull/3911
