### ISSUE TITLE
Q: Vim command chaining

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#2459]
**Question**:
Would those chaining of vim commands work also? http://rayninfo.co.uk/vimtips.html

**Comment by J-Fields** [comment]
That appears to be a dead link at this point. Could you provide more info please?

**Comment by bm-stschneider** [comment]
puhh this is a pretty old one, I guess the link is now http://zzapper.co.uk/vimtips.html but I'm not sure what kind of chaining I meant. So you may also close this one.

**Comment by J-Fields** [comment]
Is this what you were referring to?
>" chain an external command
:.g/^/ exe ".!sed 's/N/X/'" | s/I/Q/    [N]

**Comment by bm-stschneider** [comment]
I really don't know after 1,5y, sorry
