### ISSUE TITLE
Ctrl-b Ctrl-b not working

### ISSUE THREAD

**Issue by costincaraivan** [VSCodeVim/Vim#2462]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature request. Or more like question (I don't want to log in to Slack, sorry, but I do already have a Github account).

**What happened**:

I pressed Ctrl-b Ctrl-b while VS Code Vim was activated. The side panel was closed.

**What did you expect to happen**:

The side panel would be closed and opened again. I.e. the second Ctrl-b did nothing.

As a side question to this: is there any VS Code Vim compatible way to get access to all the default VS Code shortcuts? (basically all the keyboard shortcuts visible in the menus). Or how can they be remapped to make them compatible with VS Code Vim?

**How to reproduce it (as minimally and precisely as possible)**:

Install VS Code, install VS Code Vim. Open any text file in VS Code. Press Ctrl-b twice.

**Environment**:
Windows.

- Extension Name: vim
- Extension Version: 0.11.2
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.20.1

**Comment by costincaraivan** [comment]
Nevermind, I found "vim.handleKeys" :smile:

**Comment by aksg87** [comment]
"vim.handleKeys": {
        "<C-d>": true,
        "<C-b>": true,
        "<C-j>": true,
    },

That doesn't seem to fix the issue for me. What worked for you? @costincaraivan 

Thanks!

**Comment by MyGamesM** [comment]
"vim.handleKeys": {
    "<C-b>": false
}

**Comment by matwilso** [comment]
Go to Settings, search for `Vim: Handle Keys`. Edit in settings.json

```
    "vim.handleKeys": {
        "<C-b>": false
    }
```

**Comment by scottstensland** [comment]
when enabling vim extension this setting should happen or at minimum show an alert to do this

**Comment by resting** [comment]
What does 
"vim.handleKeys": {
"": false
}
mean? Let vscode handle all bindings?
ctrl-b, ctrl-f works after I added it.
