### ISSUE TITLE
Selecting to end of line in normal mode selects onto next line

### ISSUE THREAD

**Issue by priort** [VSCodeVim/Vim#2471]
Firstly, thanks for the great plugin!
When in normal mode I select to end of current line with
v$
I would expect this to select up to and including the last character in the current line.
However, it also selects onto the next line.
So if I want to delete up to the end of the current line, the next line down gets brought up to the end of the current line. See gif attached.
In this example I go to somewhere in the middle of line 1 and do
v$
You can see that the selection carries on to line 2:
I then do 
d
and, instead of just the rest of line 1 being deleted, line 2 is also joined onto the start of line1.

- Extension (VsCodeVim) version: 0.11.2
- VSCode version: 1.21.1
![end-of-line-selection-bug](https://user-images.githubusercontent.com/13556648/37856799-5f276512-2eee-11e8-9065-2fb9b6b6b041.gif)

- OS version: Windows 10

**Comment by moyuanhuang** [comment]
I'm also having this issue, and it made me have to switch from `vscode + vim` to `nvim` 😢

**Comment by J-Fields** [comment]
This is expected behavior. Try `v$d` in vim - you'll see the newline gets deleted as well. It looks different because that's how VSCode renders your selection of the newline, and we can't affect that.

**Comment by priort** [comment]
@J-Fields That's grand, thanks for the explanation.
