### ISSUE TITLE
Set useCtrlKeys to false doesn't forbid C-c to switch to normal mode in insert mode

### ISSUE THREAD

**Issue by STayinloves** [VSCodeVim/Vim#2474]
**BUG REPORT**

**What happened**: 

Set `useCtrlKeys` to `false` doesn't forbid `C-c` to switch to normal mode when it's in insert mode.

**What did you expect to happen**:

In insert mode, if I have set `useCtrlKeys` to `false`, the `C-c` should not switch to normal mode. 

**How to reproduce it (as minimally and precisely as possible)**:

Just try it in insert mode.

**Environment**:

- Extension (VsCodeVim) version:0.11.2
- VSCode version:1.22.0-insiders
- OS version:win10

**Comment by xconverge** [comment]
FYI if you set this https://github.com/VSCodeVim/Vim#vimoverridecopy to false, you should be good to go

**Comment by STayinloves** [comment]
It works.
