### ISSUE TITLE
(BUG) Surround Plugin issues with: Brackets, Parentheses, and Braces

### ISSUE THREAD

**Issue by bhargavrpatel** [VSCodeVim/Vim#2475]
**Issue Type**: Bug

**What happened**
When I select a word in visual mode and attempt to surround using `S` and try to use any of Brackets, Parentheses, or Braces, it surrounds the word but inserts empty spaces on both sides of the word. You can see the bug in action on [this video](https://streamable.com/01jz0)

**What did you expect to happen**
Surround the word snugly like so: `(test)`, `[test]`, or `{test}`

**How to reproduce it (as minimally and precisely as possible)**:
Simply, Repeat the process in the video.
1. Select a word in Visual mode `V`
2. Press `S`
3. Press `[`, `(`,  or`{`

Exact keys pressed assuming cursor is on the first letter of the word. `VeS[`

**Environment**: 
- Operating System: Mac OSX
- Extension Name: vim
- Extension Version: 0.11.2
- OS Version: Darwin x64 15.6.0
- VSCode version: 1.21.1

**Comment by nrdhm** [comment]
Vim's behavior is the same. You can surround without white spaces using closing brackets. veS]

**Comment by bhargavrpatel** [comment]
Closing as a non-issue. Thanks @nrdhm
