### ISSUE TITLE
jj binding to Esc doesn't work!

### ISSUE THREAD

**Issue by lhfly5201314** [VSCodeVim/Vim#2477]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:

- Extension (VsCodeVim) version:0.11.2
- VSCode version:1.21.1
- OS version:Win 10

jj binding to Esc doesn't work!
I tried the :inoremap jj <esc> and :inormap jj <Esc>
didn't work,and I could not find a settings.json,
How could I active the jj binding in the 0.11.2 ??

**Comment by jpoon** [comment]
Please refer to our documentation: https://github.com/VSCodeVim/Vim#key-remapping
