### ISSUE TITLE
Visual mode replace with tab adds <tab> text

### ISSUE THREAD

**Issue by kroppt** [VSCodeVim/Vim#2499]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

**What happened**:
1. Visual highlight
2. Press `r` then press `tab`
3. Every character is replaced with the text `<tab>`

**What did you expect to happen**:
Every character is replaced with a tab

**How to reproduce it (as minimally and precisely as possible)**:
Every time when highlighting more than 1 character and replacing with tab.

**Environment**:

Tested on
- Extension (VsCodeVim) version: 0.11.3
- VSCode version: 1.21.0
- OS version: Linux kernel 4.14.31-gentoo 

and

- Extension (VsCodeVim) version: 0.11.3
- VSCode version: 1.21.1
- OS version: Linux kernel 4.15.14-gentoo 

and

- Extension (VsCodeVim) version: 0.11.3
- VSCode version: 1.21.1
- OS version: Windows 10

**Comment by peawyoyoyin** [comment]
hello. May I try this one?

**Comment by J-Fields** [comment]
Fixed by https://github.com/VSCodeVim/Vim/pull/4195
