### ISSUE TITLE
Search/replace (:%s/text/new text \t) to insert tab character (\t), inserts literal "\t" instead

### ISSUE THREAD

**Issue by Orionsg** [VSCodeVim/Vim#2501]
**BUG REPORT**

**What happened**:
I used the command in normal mode:

`:%s/text-a/text-b\t>/g`

Instead of of tab character the literal "\t" was inserted after "text-b".

**What did you expect to happen**:
A tab character should have been inserted after "text-b". 
I tested in a normal vim and it works.

**How to reproduce it (as minimally and precisely as possible)**:
Just use the example above

**Environment**:
- Extension Version: 0.11.3
- OS Version: Windows_NT x64 10.0.16299
- VSCode version: 1.21.1

**Comment by xconverge** [comment]
FYI you can switch to use neovim for these sorts of commands in the future

https://github.com/VSCodeVim/Vim#neovim-integration

**Comment by Orionsg** [comment]
Ok, thanks.

**Comment by jpoon** [comment]
Here's the offending line of code: https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/commands/substitute.ts#L96

Using your example, `this._arguments.replace` = `text-b\t`.

**Comment by jpoon** [comment]
Seems like @xconverge had a fix for this before: https://github.com/VSCodeVim/Vim/commit/efcd4eaf4f49c39b7bf8ef2d8d891d4586d30879

**Comment by Orionsg** [comment]
It seems there is a similar issue with searching using the new line character: \n, e.g. "/\n\n" for finding instance of two carriage returns, which works .
Is that a separate issue or the same?

**Comment by knetworx** [comment]
I have the same issue, and whenever I've attempted to use Neovim, it hasn't worked for me at all (for example, attempting to do this same thing with Neovim just gives me an error popup).

**Comment by knetworx** [comment]
I'm able to use NeoVim now, but still have this issue.

**Comment by Elias-Graf** [comment]
This is still an issue :(?. My query is `:%s/ - /\r\t- /gc` works perfectly under vim but not with the integration

**Comment by knetworx** [comment]
For posterity:
![Large GIF (574x310)](https://user-images.githubusercontent.com/3292803/82833079-e1805b00-9e71-11ea-8402-158eb4ca8cd2.gif)

VS Code Details:
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

vscodevim version: 1.14.5
