### ISSUE TITLE
How to change all occurrence within a region

### ISSUE THREAD

**Issue by pingshunhuangalex** [VSCodeVim/Vim#2502]
Just migrating from Atom. I wonder if there is a way to change all occurrences within a region (let's say a paragraph). Neither `c o p` nor `c o i p` works.

Can anyone shine some light on what's the best way to do the task below. Thanks.
![image](https://raw.githubusercontent.com/t9md/t9md/5d9edf78e0107e55eb343f9cfb1ed5f4b113dfb0/img/vim-mode-plus/advanced-tutorial/step-5.gif)

**Comment by Chillee** [comment]
There's a couple ways.

I like highlighting the paragraph and then doing `'<,'>s/text/abc/g`.

The keystrokes for doing that are:
`vip:s/test/abc/g`

Vim Mode Plus adds a lot of their own custom actions, some of which are pretty cool. Unluckily, one downside of doing that is that it makes it harder to move away from VMP to other variants of vim.

**Comment by chikamichi** [comment]
Hi :)

Any plans to support something similar to https://github.com/t9md/atom-vim-mode-plus/wiki/OccurrenceModifier at some point?
