### ISSUE TITLE
Keep selection highlighted (visual cue) when switching modes

### ISSUE THREAD

**Issue by pingshunhuangalex** [VSCodeVim/Vim#2503]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: When I select something in visual mode and switch it to normal mode, the selection seems to disappear (it's actually not)

**What did you expect to happen**: when switching among different modes, keep the highlighted selection part unless `<Esc>` is hit

**How to reproduce it (as minimally and precisely as possible)**: select a word using `v i w`, then switch to normal mode using `<Esc>`, you'll see the highlight for selection disappeared. However, if you use `gb`, it actually works which means the selection is still there.

**Environment**: Win10

Version 1.22.0-insider
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by jpoon** [comment]
Following your repro steps in vanilla vim, the selection is also lost so the behaviour of vscodevim is inline with vim. As such, closing this as a won't fix.
