### ISSUE TITLE
Fix / Support cutting into the black hole register with "C"

### ISSUE THREAD

**Issue by jiripospisil** [VSCodeVim/Vim#2504]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

A bug report? I'm not not sure if it's worked before.

**What happened**:

Cutting into the black hole register doesn't seem to work with `C`. Position your cursor at the very beginning of a line with some text and press:

`"_C`

It should cut the whole line and store in the black hole register (throw it away). Instead, it does nothing.  Interestingly `"_c$` works correctly.

**Environment**:

- Extension (VsCodeVim) version: v0.11.3
- VSCode version: 1.21.1
- OS version: macOS 10.13.4

**Comment by anonimitoraf** [comment]
I found that this fixes it: https://github.com/anonimitoraf/Vim/commit/1899aeee186129203c6b453f4685a913f35bf1c2

**Comment by sobjornstad** [comment]
I'm experiencing this as well. It doesn't work with any register, not just the black hole register.

**Comment by J-Fields** [comment]
The problem is here: https://github.com/VSCodeVim/Vim/blob/master/src/actions/commands/actions.ts#L2527
Not sure why `C` is enforced to be the first keystroke; `2C` works fine in vim, for instance.
