### ISSUE TITLE
'<,'> is not automatically inserted in command when a selection region exists

### ISSUE THREAD

**Issue by pingshunhuangalex** [VSCodeVim/Vim#2508]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: `'<,'>` is not automatically inserted in command when a selection region exists

**What did you expect to happen**: `'<,'>` should be automatically inserted in vim command when a selection region exists

**How to reproduce it (as minimally and precisely as possible)**:
1. make sure `:` is bound to `vim show command`
2. select a text region, let say `v i p`
3. hit `:` to call out vim command
4. use substitution -> `:'<,'>s/foo/bar/g` (what I actually got is `:s/foo/bar/g`)

**Environment**: Win10

Version 1.22.0-insider
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by ollien** [comment]
In the Neovim plugin, this doesn't happen, but the substitution takes no effect.

**Comment by pingshunhuangalex** [comment]
@ollien Do I have to get the neovim plugin to get this to work? Shouldn't this be included in just vim? Thanks.

**Comment by ollien** [comment]
@pingshunhuangalex I'm not sure. I more meant this to log more information about the issue than to suggest a fix. I would agree that both should have feature parity (especially considering the neovim plugin is experimental).

**Comment by pingshunhuangalex** [comment]
I can confirm this issue has been fixed in the latest version. Thanks guys.
