### ISSUE TITLE
Folded code unfolds if you move the cursor past it

### ISSUE THREAD

**Issue by jab** [VSCodeVim/Vim#2511]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

**How to reproduce it (as minimally and precisely as possible)**: Move the cursor to a code block you can fold (e.g. a function definition) and hit `zc` to fold it up. Then move the cursor past the fold using the down arrow key or j.

**What happened**: The fold opened, defeating the point of the fold you just made.

**What did you expect to happen**: The fold should stay closed until you actually open it (e.g. via `zo`, ⌥⌘], etc).

**Environment**:  VSCode 1.21.1, VSCodeVim 0.11.3, macOS 10.12.6

**Comment by xconverge** [comment]
Closing in favor of #1004, please thumbs up that issue instead, thanks!

**Comment by jab** [comment]
Just did, thanks. I’d found that issue before opening this one but it
wasn’t clear it was talking about the same thing, as this one seems to be
triggered by the cursor motion. But maybe fixing that issue would fix this
one too? Anyway thanks for the work on this project.
