### ISSUE TITLE
'$' end of range not working for delete

### ISSUE THREAD

**Issue by rangercej** [VSCodeVim/Vim#2514]
**BUG REPORT**

**What happened**
I can do `:%d`, `:1,.d`, `:4,5d` etc, however `:.,$d`  to delete everything from current position to end of file doesn't work. Some experimenting suggests that the '$' isn't recognised for end of file. Instead I get an error appear in the bottom right saying "Vim: RangeError".

However I can use '$' in substitute commands, for example `:.,$s/dog/cat/` works as expected. 

**What did you expect to happen**
Taking (for example) `:.,$d`, all lines from current position to end of file should have been deleted.

**Environment**
* VSCode  1.21.1
* Windows 10
* VSCodeVim 0.11.3

**Comment by Chillee** [comment]
This works when using neovim for ex commands.

**Comment by J-Fields** [comment]
This now seems to work
