### ISSUE TITLE
Menu -> Edit -> Paste cannot paste string to search bar from system clipboard.

### ISSUE THREAD

**Issue by flyingosprey** [VSCodeVim/Vim#2516]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
Menu -> Edit -> Paste cannot paste string to search bar from system clipboard.
The string is pasted to the text instead of search bar.

**What did you expect to happen**:
The string is pasted to search bar.

**How to reproduce it (as minimally and precisely as possible)**:
Press "/" to start search.
Try to paste string from system clipboard by using Menu -> Edit -> Paste

**Environment**:

- Extension (VsCodeVim) version: 0.11.3
- VSCode version: 1.21.1 x64
- OS version: Windows 10

**Comment by jpoon** [comment]
Use the keyboard shortcut instead.

**Comment by flyingosprey** [comment]
Thanks. At least, there is a workaround.

**Comment by jpoon** [comment]
One of the reason I personally use VIM is that I don't need to use the mouse anymore. As such, it's rarely the case people would go through the menu bar to copy and paste. For that reason, I'm closing this as a won't fix.
