### ISSUE TITLE
add tests for r

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#253]

**Comment by darrenweston** [comment]
I added the following test but it is failing with this:
  **AssertionError: 'onehreeT' == 'one\nThree'**   

` test("Can handle 'r' after 'dd'", async () => {
        await modeHandler.handleMultipleKeyEvents("ione\ntwo\nthree".split(""));
        await modeHandler.handleMultipleKeyEvents([
            '<esc>', 'k', 'd', 'd',
            'r', 'T'
        ]);

        assertEqualLines(["one\nThree"]);
    });`

**Comment by johnfn** [comment]
@darrenweston Wow, that's a particularly weird bug! Feel free to make a PR even if the tests fail (so long as they are actually testing something valid, obviously). I will fix them. 😄

**Comment by johnfn** [comment]
@darrenweston  ... although I actually just fixed that bug on master so you should be good to go.

**Comment by darrenweston** [comment]
Cool thanks.

**Comment by johnfn** [comment]
Thank you for taking the time to add some tests!! ❤️
