### ISSUE TITLE
Shrink selection (opposite of `af`)

### ISSUE THREAD

**Issue by michael-land** [VSCodeVim/Vim#2536]
I noticed that the combination \<a\>,\<f\> expand selection is quiet useful. 

Is there an  opposite operation to shrink selection?

**Comment by Glench** [comment]
It'd be great if this could get worked on!

**Comment by vxsl** [comment]
@xiaoyu-tamu was this feature added, since it was closed as "completed"? If so what is the command?

**Comment by barry-hall** [comment]
Just in case anyone else comes across this, I changed my keybindings to get the desired result. I set mine to `a b` thinking of it as "backward" instead of "forward" with `a f` but set it to whatever you like. 

```  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": ["a", "f"],
      "commands": ["editor.action.smartSelect.expand"]
    },
    {
      "before": ["a", "b"],
      "commands": ["editor.action.smartSelect.shrink"]
    }
  ],
```
