### ISSUE TITLE
vim.leader = "," doesn't work

### ISSUE THREAD

**Issue by rstacruz** [VSCodeVim/Vim#2541]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

- Bug

**What happened**:

- Setting `vim.leader` to a comma doesn't make leader keys work.

**What did you expect to happen**:

- To replace `\` with `,`.

**How to reproduce it (as minimally and precisely as possible)**:

- Here's an example that will run `showCommands` when pressing `\` `\`. However, if you change vim.leader to `,`, it won't show up when you do `,` `,`. (It works with other keys, eg, `;` or `.`.)

```js
  "vim.leader": "\\",
  "vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": ["leader", "leader"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.showCommands",
          "args": []
        }
      ]
    },
  ],
```

**Environment**:

- Extension Name: vim
- Extension Version: 0.11.4
- OS Version: Linux x64 4.15.15-1-ARCH
- VSCode version: 1.22.2

**Comment by rstacruz** [comment]
Solved my own issue! This happens if you have a chord with comma in `keybindings.json`. Remove any offending key bindings and it should work fine.

**Comment by styliii** [comment]
also am running into this problem. i removed all keybindings with a comma and still can't get it to work.

**Comment by chrisarcand** [comment]
For posterity, if you're looking to have a chord in `keybindings.json` anyway, you can use a `when` condition to instruct VSCode to intercept the chord only under the appropriate conditions. See my answer in a duplicate issue (https://github.com/VSCodeVim/Vim/issues/2257#issuecomment-480530435) describing what I do for ctrlp.vim-like functionality (that is, use gotoFile in VSCode) using `,` as a leader and having it still work when there are no buffers (editor groups) open.
