### ISSUE TITLE
2gJ removes characters

### ISSUE THREAD

**Issue by max-sixty** [VSCodeVim/Vim#2544]
BUG REPORT

**What happened**:
```
1234#
56
789
```
where `#` in the cursor.

Type `2gJ`:

```
9123456
```

**What did you expect to happen**:

```
123456789
```

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:

- Extension Name: vim
- Extension Version: 0.11.4
- OS Version: Darwin x64 17.4.0
- VSCode version: 1.22.2

**Comment by J-Fields** [comment]
See also #2207

**Comment by J-Fields** [comment]
Closing in favor of https://github.com/VSCodeVim/Vim/issues/2207
