### ISSUE TITLE
How to map <leader>t to CMD+P (mac)

### ISSUE THREAD

**Issue by nerdpad** [VSCodeVim/Vim#2552]
I want to open the file picker when I hit `<leader>t`.

Leader is mapped:  
"vim.leader": ","

VS Code default mapping for the command in question: 
{
  "key": "cmd+p",
  "command": "workbench.action.quickOpenNavigateNextInFilePicker",
  "when": "inFilesPicker && inQuickOpen"
}

What should be my config?

I have tried the following and few other combination and I can't get it to work.

```
  "vim.otherModesKeyBindings": [
    // file picker
    {
      "before": ["<leader>", "t"],
      "after": ["cmd+p"]
    }
  ]
```

Please let me know if this is even possible.

**Comment by dagadbm** [comment]
it is. don't map to vscode keybindinga but to commands. there is some examples of this in the readme

**Comment by nerdpad** [comment]
I have tried that also, and it doesn't work for me.

```
    // file picker
    {
      "before": ["<leader>", "t"],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.quickOpenNavigateNextInFilePicker"
        }
      ]
    }
```

**Comment by hmps** [comment]
This works for me:

```json
        {
            "before": [
                "<leader>",
                "t"
            ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.quickOpen",
                    "args": []
                }
            ]
        }
```

As far as I understand, the `workbench.action.quickOpenNavigateNextInFilePicker` is used to navigate to the next entry once the quick open pane is opened. The `workbench.action.quickOpen` can be used to open it.

**Comment by rbriank** [comment]
👍 This worked for me too.  FYI, I had to restart vsc to get it to pick up the change.

**Comment by nerdpad** [comment]
This works for me as well. Thank you for the suggestions. I just wish these shortcuts also worked without having to open a file (global in vscode).
