### ISSUE TITLE
ctrl+v not working even with "vim.useCtrlKeys": true

### ISSUE THREAD

**Issue by nfourteen** [VSCodeVim/Vim#2555]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: Pressing `ctrl+v` I get a `command 'workbench.view.git' not found` warning.

**What did you expect to happen**: Vim mode should change to visual block

**How to reproduce it (as minimally and precisely as possible)**: 
1. This is a fresh install v1.22.2 with minimal config (I just started using VS Code).
    - I added `"vim.useCtrlKeys": true` to User Settings just to be safe
    - current config can be found at the end
2. Project has no version control set up
3. While in the editor press `ctrl+v`

**Environment**:

- Extension (VsCodeVim) version: v0.11.4
- VSCode version: v1.22.2
- OS version: Mac 10.12

**Solution**:
I added the following to `keybindings.json` and visual block mode works as expected:

```
{
    "key": "ctrl+v",
    "command": "-workbench.view.git"
}
```

I'm assuming VS Code just added the `workbench.view.git` key binding, so this fix might just be to add a note to the docs as I was assuming by enabling `useCtrlKeys` would allow visual block mode to work with no problems.

**Current config**:
```
{
    "editor.fontFamily": "Source Code Pro",
    "editor.fontSize": 16,
    "editor.fontWeight": "400",
    "editor.colorDecorators": false,
    "editor.cursorBlinking": "solid",
    "editor.rulers": [
        80
    ],
    "editor.minimap.enabled": false,

    "telemetry.enableTelemetry": false, // don't send data to Microsoft
    "typescript.useCodeSnippetsOnMethodSuggest": true,

// VIM PLUGIN
    "vim.cursorStylePerMode" : {
        "normal": "block",
        "insert": "line",
        "replace": "block-outline"
    },
    "vim.leader": ",",
    "vim.useCtrlKeys": true,
// COLORS
    "workbench.colorTheme": "Solarized Dark",
    "workbench.colorCustomizations": {
        "editorCursor.foreground": "#eee8d5"
    },
}
```

**Comment by jpoon** [comment]
As far as I'm aware, that keybinding

```
{
    "key": "ctrl+v",
    "command": "-workbench.view.git"
}
```

is not something that vscodevim or vscode adds. It's also apparently been changed to `workbench.view.scm` (https://github.com/Microsoft/vscode/issues/28383). Especially as the default keybinding for `workbench.view.scm` is `ctrl+shift+g` so it would seem odd for either vscode or us to bind it to `ctrl+v` which would override the more common keybinding of paste.
