### ISSUE TITLE
Selecting, then clicking inside the selection, creates a duplicate cursor

### ISSUE THREAD

**Issue by jleclanche** [VSCodeVim/Vim#2557]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**How to reproduce it (as minimally and precisely as possible)**:

1. Have a file with a bunch of text in it and vscode-vim enabled in visual mode.
2. Select a block of text with the mouse
3. Click inside that block of text

There are now two cursors: One "thin" cursor where the mouse clicked, and the vim cursor where the selection ended. This is not reproducible if the click happens *outside* of the selected block.

**Environment**:

- Extension (VsCodeVim) version: 0.11.4
- VSCode version: 1.22.2
- OS version: Arch Linux

**Comment by jleclanche** [comment]
Config: 
```json
{
	"vim.enableNeovim": true,
	"vim.handleKeys": {
		"<C-k>": false
	},
	"vim.hlsearch": true,
	"vim.neovimPath": "/usr/bin/nvim",
	"vim.otherModesKeyBindings": [    ],
	"vim.searchHighlightColor": "rgba(150, 150, 255, 0.3)",
	"vim.statusBarColorControl": true,
	"vim.useSystemClipboard": true,
}
```

**Comment by berknam** [comment]
Closing since this doesn't appear to be an issue anymore.
