### ISSUE TITLE
Support vim set scrolloff ?

### ISSUE THREAD

**Issue by leeyongda** [VSCodeVim/Vim#2561]
## vscode-vim version (0.11.5)
## Vscode version (1.22.2)

**Comment by jpoon** [comment]
It'd be nice if folks filled out the template :)

related: https://github.com/Microsoft/vscode/issues/12048

**Comment by cjbassi** [comment]
Seems like a duplicate of #1427

**Comment by jpoon** [comment]
You are correct. Thanks @cjbassi. Closing as duplicate of https://github.com/VSCodeVim/Vim/issues/1427
