### ISSUE TITLE
How to use vim hlserach ?

### ISSUE THREAD

**Issue by leeyongda** [VSCodeVim/Vim#2562]
- Extension (VsCodeVim) version: 0.11.5
- VSCode version:  1.22.2
- OS version: macOS 10.13

**Comment by Chillee** [comment]
When `hlsearch` is on, searching for something with `/` will keep the highlights even after you've left search mode.

**Comment by leeyongda** [comment]
@Chillee 
vscode-vim support serach ?
Why can't you use it ？
## here settings.json
![wx20180425-105346](https://user-images.githubusercontent.com/11832476/39223895-033f50be-4877-11e8-80f2-78796335e7df.png)

Open Developer Tools: 
![wx20180425-104933](https://user-images.githubusercontent.com/11832476/39224045-b1bacfba-4877-11e8-8bed-8b4e37e4639e.png)

**Comment by jpoon** [comment]
You are in vim command mode. To search, be in normal mode and type `/<search-term>`
