### ISSUE TITLE
vim-commentary has a math problem

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#2567]
Issue Type: <b>Bug</b>

**What happened**:
Commented additional line.

**How to reproduce it (as minimally and precisely as possible)**:
type `gc2j`.
This should comment the current and the next line but it does comment not only the next but the 2 next lines. so it is actually a `gc3j`

Extension version: 0.11.5
VS Code version: Code - Insiders 1.23.0-insider (36e6cbb7667e7874748d8fbf2021b743d2d90afc, 2018-04-25T05:25:16.735Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_2175507|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by pschlette** [comment]
This seems like expected behavior to me. `d2j` in vim will delete 3 lines: the current line, the next line, and the line after that (which is the line the cursor would have landed on if you'd entered `2j`)

**Comment by J-Fields** [comment]
Yeah this is expected behavior. To comment the current and next lines only, use `2gcc` or `gcj`.

**Comment by bm-stschneider** [comment]
ok thank you.
