### ISSUE TITLE
undo in vim extension can't be redo-ed by the redo command of vscode

### ISSUE THREAD

**Issue by myzhang1029** [VSCodeVim/Vim#2574]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**:
The action of the `u` command cannot be redo-ed by `⇧⌘Z`(which is the redo key of vscode, which did nothing).

**What did you expect to happen**:
The affect of the `u` command should no longer take place.

**How to reproduce it (as minimally and precisely as possible)**:

1. Type any text with vim extension enabled
Result:
`test me`

2. Use the `u` command
Result:
`(blank)`

3. Try redo with vscode
Result:
`(blank)`
Which I expect to be:
`test me`

**Environment**:

- Extension (VsCodeVim) version: 0.11.5
- VSCode version: 1.22.2
- OS version: Darwin x64 17.5.0

**Comment by Nodman** [comment]
@myzhang1029 , I believe this is right behavior, because VSCodeVim uses its own stack for undo/redo actions. Any undo action made with VIM plugin is actually common edit operation, from VSCode point of view, so there is basically, nothing to redo at that moment

**Comment by rjhilgefort** [comment]
so.... what's the solution? I'm constantly accidentally undoing things and losing them forever.

**Comment by rjhilgefort** [comment]
`ctrl+r` wasn't working for me but I was able to bind redo to a different keybinding:

```json
    {
        "key": "shift+u",
        "command": "extension.vim_ctrl+r",
        "when": "textInputFocus && vim.mode != 'Insert'"
    },
```

**Comment by coppyC** [comment]
I rewirte the action on "u" and "<c-r>", now it work very well, it use the vscode undo and redo command.
setting.json
```json
    "vim.useCtrlKeys": true,
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["u"],
            "commands": ["undo"]
        },
        {
            "before": ["<C-r>"],
            "commands": ["redo"]
        }
    ],
```
and I expect the extension do it default.

**Comment by jorourke** [comment]
You are awesome @coppyC. thanks!

**Comment by meteorsh** [comment]
> `ctrl+r` wasn't working for me but I was able to bind redo to a different keybinding:
> 
> ```json
>     {
>         "key": "shift+u",
>         "command": "extension.vim_ctrl+r",
>         "when": "textInputFocus && vim.mode != 'Insert'"
>     },
> ```

It works for me. Thank you :thumbsup:

Now I can use `u` to undo and `U` to redo in VScode vim.

![image](https://user-images.githubusercontent.com/46078304/77853467-d5cc3b80-7216-11ea-97cd-c3463664918d.png)

**Comment by onyx158** [comment]
Thanks @coppyC  and I totally agree with you that this should be the default. This has been an infuriating issue where I've assumed I'd hit some disastrous combination of keys and lost work multiple times. I've even switched back to Atom a couple times due to this issue.

**Comment by UltimatePro-Grammer** [comment]
The only thing that worked for me:
```json
"vim.normalModeKeyBindings": [
  {
    "before":["U"],
    "commands":["extension.vim_ctrl+r"]
  }
]
```

**Comment by dijonkitchen** [comment]
I had a conflict with https://github.com/kasecato/vscode-intellij-idea-keybindings and just removed the Ctrl+r binding and VSCodeVim worked properly.

**Comment by daniele-casavo** [comment]
incredible still a problem for me on linux (manjaro) ... why?

**Comment by MuhammedOzdogan** [comment]
I'm using [Intellij IDEA Keybindings Plugin](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings) together with VSCodeVim plugin and I actually use `CTRL-r` or `CMD-r` for redoing not `SHIFT-u`

`CTRL-r` was already overridden by IntelliJ IDEA Keybindings plugin

![Frame 2](https://user-images.githubusercontent.com/26257939/230700852-8caffb63-6f9f-43ed-95dd-fe5394519260.png)

So you have to override it again, put this into the ` keybindings.json` file, and it will also override any plugin. The good thing is you can use the Find&Replace feature of VsCode when you are in INSERT mode.
```
[
	{
		"key": "ctrl+r",
		"command": "extension.vim_ctrl+r",
		"when": "textInputFocus && vim.mode != 'Insert'"
	},
]
```

**Comment by smanilov** [comment]
Sharing my solution as well, since it took me some time to arrive at it, although it combines multiple ideas from around the place:

To configure undo, add this to Code > User > settings.json:

```
{
    "vim.useCtrlKeys": true,
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["u"],
            "commands": ["undo"]
            // Redo in keybindings.json
        },
    ],
}
```

To configure redo, add this to Code > User > keybindings.json:

```
// Place your key bindings in this file to override the defaults
[
    {
		"key": "ctrl+shift+r",
		"when": "textInputFocus && vim.mode != 'Insert'",
		"command": "redo",
		// Undo in settings.json
	}
]
```

I couldn't combine both in either file.

The behavior is now what I expect coming from vim.

**Comment by Glitchy-Sheep** [comment]
Hey, just in case anybody encounters the same issue as I did:

**Ctrl + R won't work until the vim.use option is enabled.**

But then you can't copy text with Ctrl + C. This issue (lol) can be fixed by enabling the 'use system clipboard' option. After that, you can copy text with the Y key in normal mode."

![image](https://github.com/user-attachments/assets/678fe7e1-6c0a-44cc-84c8-bea46d0515af)

**Comment by dylan-chong** [comment]
hey guys, i dont think this issue should be closed.

the default behaviour of this plugin makes it super easy to accidentally screw up the entire file. i just moved big chunks of code around, hit undo and redo and the file is permanently garbafied and has to be manually fixed.

> @myzhang1029 , I believe this is right behavior, because VSCodeVim uses its own stack for undo/redo actions. Any undo action made with VIM plugin is actually common edit operation, from VSCode point of view, so there is basically, nothing to redo at that moment

@Nodman allowing the user to permanently screw up the file with mismatched undo stacks is *not* correct behaviour. the default behaviour should be to use the vscode undo stack, even though it doesn't match the vim behaviour. but at least you cannot screw up the file, and the undo stack actually functions correctly.
