### ISSUE TITLE
focus lost after ex command

### ISSUE THREAD

**Issue by joshgav** [VSCodeVim/Vim#2578]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT in latest Insiders builds.

**What happened**:

After executing an ex command, focus/cursor doesn't return to current pane.

**What did you expect to happen**:

After executing an ex command, focus/cursor should return to current pane, current position.

**How to reproduce it (as minimally and precisely as possible)**:

From normal mode `:w<enter>`.

**Environment**:

- Extension (VsCodeVim) version: 0.11.15
- OS version: Ubuntu 17.10 w/ all updates
- VSCode version:
Version 1.23.0-insider
Commit e545ae6b34aae3f05a923d5258adbb58805ca27f
Date 2018-04-27T05:11:37.547Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by rebornix** [comment]
@joshgav thanks, after digging into this issue, I found it's a regression of Code https://github.com/Microsoft/vscode/issues/48847

**Comment by jpoon** [comment]
Looks like this was fixed upstream.
