### ISSUE TITLE
Overselecting on '*'

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#2610]
Issue Type: <b>Bug</b>

It seems that hitting `*` does not work correctly on the occurence after the current under the cursor one.
In the example below I hit `*` and then `n` to cycle throught the occurences.

![kapture 2018-05-04 at 8 20 08](https://user-images.githubusercontent.com/30625381/39615008-1c68c652-4f74-11e8-9251-6862aeb323bc.gif)

Extension version: 0.11.5
VS Code version: Code - Insiders 1.24.0-insider (3899a50fd7961bd1cffd774622cf2a062510ea84, 2018-05-04T05:10:33.242Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron -psn_0_1630606|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by xconverge** [comment]
Fixed in #2611
