### ISSUE TITLE
Feature Idea Solution for color bar status

### ISSUE THREAD

**Issue by u2berggeist** [VSCodeVim/Vim#2612]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

More just an "FYI, here's a thing y'all should probably look at". VS Code just added [webview API](https://code.visualstudio.com/docs/extensions/webview) for extensions. By extension (pun most definitely intended), could fix the color bar status issues. Just a thought more than anything else. Might end up being a lot more work that it's worth (I'm not sure if you could literally just add a webview bar at the bottom of an otherwise normal editor window, or whether you'd have to build the editor from scratch), but I figured I'd let you guys know.

**Comment by jpoon** [comment]
Neat thought, but my take from that is it's primarily for the editor window.
