### ISSUE TITLE
Counter doesn't work for X command (del char before cursor)

### ISSUE THREAD

**Issue by Orionsg** [VSCodeVim/Vim#2616]
BUG REPORT

**What happened**:
In command mode, I press 2X to delete two characters before the cursor, but only one character is deleted.

**What did you expect to happen**:
Two characters to be deleted.
(It does work for the x command (i.e. delete multiple characters under the cursor)

**How to reproduce it (as minimally and precisely as possible)**:
Just press a number and "X" in command mode, only a single character before cursor is deleted.

**Environment**:
- Extension (VsCodeVim) version: v0.11.5
- VSCode version: 1.23.0
- OS version: Windows 10, 1709

**Comment by J-Fields** [comment]
I can't reproduce. @Orionsg is this still an issue?

**Comment by Orionsg** [comment]
@J-Fields It has been fixed in the newer version, so I will close the issue.
