### ISSUE TITLE
[FEATURE REQUEST] "q:" command

### ISSUE THREAD

**Issue by KamikazeZirou** [VSCodeVim/Vim#2617]
**FEATURE REQUEST**:
I would like to often run command from command-line history. 
So I request "q:" command that opens command-line window.
"q:" command may modestly relieve issue #779.

**Comment by xconverge** [comment]
Here is the reference material for this command:

http://vim.wikia.com/wiki/Using_command-line_history

**Comment by xconverge** [comment]
This was implemented in #2618
