### ISSUE TITLE
Keybinding that involve numbers

### ISSUE THREAD

**Issue by ajilk** [VSCodeVim/Vim#2619]
How would I go binding the CR to gg VSCodeVim style?
I have tried this:
```
"vim.otherModesKeyBindingsNonRecursive": [ 
        {  
            "before": ["CR"],
            "after": ["g","g"],
        }
    ],
```
But that does not seem to work as expected.
When I entered 23\<CR\>, I expected to go to line 23.
Instead it is ignoring the line number I provided and going to the beginning of the file.

**Comment by J-Fields** [comment]
This now works
