### ISSUE TITLE
Unable to use C-v mapping

### ISSUE THREAD

**Issue by kbarnes3** [VSCodeVim/Vim#2624]
- Extension Name: vim
- Extension Version: 0.11.6
- OS Version: Windows_NT x64 10.0.17666
- VSCode version: 1.24.0-insider

I have the following settings in my user settings:
```
    "vim.insertModeKeyBindings": [
        {
            "before": ["C-v"],
            "after": [],
            "commands": "editor.action.clipboardPasteAction"
        }
    ],
    "vim.handleKeys": {
        "<C-c>": false,
        "<C-f>": false,
        "<C-x>": false
    },
```
The intended behavior is that when I press C-v in insert mode, it pastes the clipboard content. This worked fine in 0.11.5, but broke immediately after updating to 0.11.6. I tested this on a second computer where this went from working as expected to not as soon as I updated. After this update, C-v does nothing apparent when in insert mode with these settings.

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 629,
		"activateCallTime": 6,
		"activateResolvedTime": 1783,
		"activationEvent": "*"
	}
}
```

**Comment by xconverge** [comment]
can you add "<C-v>": false

This was most likely missing before and we "fixed" it. You do lose block mode then...

**Comment by kbarnes3** [comment]
As you expected, adding that line made it so I could paste but prevents block mode from working. Unfortunately I use block mode as well as pasting, so I'd like to have some way of having both commands work at the same time.

**Comment by tyru** [comment]
Ah sorry, it seems I removed `vim.mode != 'Insert'` from `ctrl+v` by mistake...
Maybe restoring `vim.mode != 'Insert'` fixes this issue.
I'll look into it.
