### ISSUE TITLE
Is hanging.

### ISSUE THREAD

**Issue by gregcp1** [VSCodeVim/Vim#2629]
- Extension Name: vim
- Extension Version: 0.11.6
- OS Version: Darwin x64 14.5.0
- VSCode version: 1.23.0

 We have written the needed data into your clipboard. Please paste:

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 277,
		"activateCallTime": 4,
		"activateResolvedTime": 122,
		"activationEvent": "*"
	}
}
```

Got a file, has long lines, when I insert, the editor window hangs.
Can close file, and save, but cannot use the file.

**Comment by jpoon** [comment]
Can you share a copy of the file?

**Comment by jpoon** [comment]
Closing as we haven't heard anything back.
