### ISSUE TITLE
VIM 0.11.6 multi cursor bug with commands in normal mode

### ISSUE THREAD

**Issue by jsonMartin** [VSCodeVim/Vim#2632]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: When using multiple cursors in 0.11.6, issuing commands (such as `cw` to change word) causes all additional cursors to disappear after the original command. In prior versions, this worked perfectly by leaving the additional cursors where they were, to continue typing. `ciw` (change inner word) seems to work better with multiple cursors with 0.11.6, but `cw` does not work at all in multi-cursor mode. 

Here's what it looks like with the bug in the newest 0.11.6 release:
![screen-recording-2018-05-08-17-02-41](https://user-images.githubusercontent.com/4033621/39789148-0978631e-52e3-11e8-8890-dc9a16466bcf.gif)

**What did you expect to happen**: The added cursors should remain. I downgraded to 0.11.5 and this behavior works as intended there; this is what it looks like when it is working properly:
![screen-recording-2018-05-08-17-01-07](https://user-images.githubusercontent.com/4033621/39789177-313846d0-52e3-11e8-8b3c-fda26203aa3e.gif)

**How to reproduce it (as minimally and precisely as possible)**: Add extra cursors using the mouse to multiple words, and issue the `cw` command. Notice how all additional cursors are gone except the first one, and typing only will replace the contents of the first cursor's position.

**Environment**: Mac OS

- Extension (VsCodeVim) version: 0.11.6
- VSCode version: Latest Stable (not insiders)
- OS version: Mac OS

**Comment by jpoon** [comment]
This is the only relevant change that I found: https://github.com/VSCodeVim/Vim/commit/dbb842d3406e4852e2e26231c22a70857ee44dd3#diff-a7723f32fe6b05e135838f84e5c23c0f

**Comment by xconverge** [comment]
@jpoon reverting that change fixes it, so perfect find!

Will look to see if there is a solution to both...

**Comment by asilvadesigns** [comment]
You guys are awesome.
