### ISSUE TITLE
Changing into insert mode does not indent

### ISSUE THREAD

**Issue by c10b10** [VSCodeVim/Vim#2652]
Entering into insert mode by using a `change inner` command should place the caret at the proper indentation. Currently it is placed at the beginning of the line.

**Comment by FlyingFishBird** [comment]
I find the same issue.

**Comment by J-Fields** [comment]
If I understand correctly, this is a duplicate of https://github.com/VSCodeVim/Vim/issues/3934

**Comment by J-Fields** [comment]
Closed in favor of #3934
