### ISSUE TITLE
[Feature Request] Configure Sneak keymap

### ISSUE THREAD

**Issue by liamdiprose** [VSCodeVim/Vim#2655]
The sneak plugin offers similar functionality to find command (`f`). Some vim users believe sneak's usefulness eclipses the find command, and remap `f` to sneak [1]. 

For vim users that map this, it means a consistent key can be used [2], and returns the original map of the `s` key (the substitute command).

This is a request to add an option to the plugin's configuration to define a custom key to activate the sneak plugin. Users that rebind the key will have the original map of `s` returned to them. 

I have looked though the [source](https://github.com/VSCodeVim/Vim/blob/master/src/actions/plugins/sneak.ts#L12) and feel I could implement this myself, if I wasn't so busy. I will make a pull request in the future; if someone doesn't beat me to it.

---
[1] Vim-Sneak Readme: https://github.com/justinmk/vim-sneak#how-can-i-replace-f-with-sneak
[2] By default, Sneak uses `s` for moving, and `z` for text operations

**Comment by longdeqidao** [comment]
Look forward to this feature. I use `s` to delete and jump into insert mode a lot.

**Comment by Jayphen** [comment]
+1 I'd love to replace `f`

**Comment by notiv-nt** [comment]
+1

**Comment by mmqmzk** [comment]
Put this in your config:

```json
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "f"
      ],
      "after": [
        "s"
      ]
    },
    {
      "before": [
        "F"
      ],
      "after": [
        "S"
      ]
    },
    {
      "before": [
        "s"
      ],
      "after": [
        "c",
        "l"
      ]
    },
  ],
```

This works for me, replace `f` and `F` key as you like.

**Comment by J-Fields** [comment]
We have the `vim.sneakReplacesF` option, which does as you say

**Comment by liamdiprose** [comment]
Sweet, thanks for implementing the feature @J-Fields :tada:

**Comment by josephan** [comment]
Agree with above comment. Would be great if we can sneak 2 chars using f.
