### ISSUE TITLE
Plugin emulation for ReplaceWithRegister

### ISSUE THREAD

**Issue by fredlebel** [VSCodeVim/Vim#2660]
**FEATURE REQUEST**

Vim plugin [ReplaceWithRegister](https://github.com/vim-scripts/ReplaceWithRegister) is quite useful.  Would it be possible to emulate it?

**Comment by tyru** [comment]
This supports only visual-mode, but the following config replaces selected text with register content **without destroying register content**.

```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["g", "r"],
            "after": ["p", "g", "v", "y"]
        }
    ]
```

**Comment by modestotech** [comment]
> This supports only visual-mode, but the following config replaces selected text with register content **without destroying register content**.
> 
> ```
>     "vim.otherModesKeyBindingsNonRecursive": [
>         {
>             "before": ["g", "r"],
>             "after": ["p", "g", "v", "y"]
>         }
>     ]
> ```

Thanks for the advice, but how would this be used? Can't see how this mimics the ReplaceWithRegister plugin. If i copy something, I expect to write `gr{motion}` to delete {motion} and in its place insert what's in the register.

**Comment by J-Fields** [comment]
Pull request is up at #3887 (not my work)

**Comment by kizza** [comment]
Thanks for hooking these together @J-Fields (I should have done an issue search!).  I've updated the PR description to link to this issue :+1:
