### ISSUE TITLE
Feature request: indicate how many more or fewer lines in the status bar

### ISSUE THREAD

**Issue by eug48** [VSCodeVim/Vim#2667]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**What happened**:
The reporting of the number of lines added/deleted according to the 'report' option is not implemented. This is useful for example after putting some text & wanting to adjust its indentation - if one immediately knows eg 18 lines have been added, one can run 18>>

**What did you expect to happen**:
The status bar to show "{n} more lines", "{n} fewer lines" as appropriate

**How to reproduce it (as minimally and precisely as possible)**:
3dd
p

(PS: Thanks for this excellent extension!)

**Comment by J-Fields** [comment]
This has worked for a while now. When verifying this, I realized the number was off by one when pasting linewise, so that's now fixed.
