### ISSUE TITLE
[Feature Request] Support SQL Operations Studio

### ISSUE THREAD

**Issue by adamskt** [VSCodeVim/Vim#2677]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

* Feature Request

**What happened**:

Can't use the glory of Vim in [SQL Operations Studio](https://github.com/Microsoft/sqlopsstudio)

**Environment**:

SQL Operations Studio appears to be built using the same framework as VS Code.  It uses a similar "extension marketplace" paradigm to allow for external extensions.  Here is an example of a VS Code extension that's been ported to SQL Operations Studio https://github.com/kevcunnane/ssmskeymap

**Comment by jpoon** [comment]
Electron is becoming a fairly popular framework, but that does not mean VSCodeVim will work on those applications built on Electron as we heavily rely on VSCode's Extension API. This is not something that is in the scope of VSCodeVim.

**Comment by adamskt** [comment]
Actually, it was fairly easy to get it working, I just had to install the VSIX and bring in my settings.  If you want this extension to appear in the "Marketplace" within SQL Operations Studio, it looks like you just have to submit a PR to get it in [the manifest](https://github.com/Microsoft/sqlopsstudio/blob/release/extensions/extensionsGallery.json) and then add [llali](https://github.com/llali) as a reviewer.  (From "Publishing the Extension" [here](https://github.com/Microsoft/sqlopsstudio/wiki/Extension-Authoring)).
![image](https://user-images.githubusercontent.com/105415/40455241-f1c4ee9e-5ea0-11e8-98e4-30d8e24ad909.png)

**Comment by jpoon** [comment]
Interesting, so the SQL Operations Studio is built *on top of VS Code?* That's pretty neat.

**Comment by jpoon** [comment]
@adamskt go for it. What happens on new releases of this extension? Will they be propagated to SQL Operations studio?

**Comment by adamskt** [comment]
Done! https://github.com/Microsoft/sqlopsstudio/pull/1487  I'm not sure how it will work when they go to a GA release (I imagine it will just use the collection at https://marketplace.visualstudio.com/).  Currently, the manifest file is pointed at the github release (which I think is how it can find the VSIX).

**Comment by narcoclepsy** [comment]
hi @adamskt - thanks for submitting this! In the meanwhile while it is being processed, can you elaborate on how you were able to manually install the VSIX? When I attempted this I'm getting an error "extension/package.json not found inside zip, either via the GUI or the CLI method.

**Comment by narcoclepsy** [comment]
thanks! I'm now on board.

**Comment by adriangonzalez** [comment]
@adamskt Is press and hold working for you (j,k, etc)? I've tried setting the defaults using:
'''defaults write com.sqlopsstudio.oss ApplePressAndHoldEnabled -bool false'''
But it didn't work.

**Comment by adamskt** [comment]
@adriangonzalez I'm not running SqlOps Studio on a Mac, but I had an issue with it not honoring my OS (Ubuntu 18.04.1 LTS) remapping CAPSLOCK to ESC.  Changing the keyboard.dispatch setting to "keyCode" as mentioned [here](https://github.com/VSCodeVim/Vim/issues/1479#issuecomment-359266762) fixed that:

`"keyboard.dispatch": "keyCode"`

Hopefully this helps!

**Comment by adriangonzalez** [comment]
@adamskt Ouch! I love that remap and thanks for the reply.  I was able to get it working using the following:

defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

I couldn't think of any app where I needed the press and hold so the global setting seemed fine.

**Comment by ppegusii** [comment]
@adamskt @adriangonzalez @narcoclepsy 
Hey folks! Do you have this working on Azure Data Studio? When I try to install from VSIX, I get "Unable to install version '1.8.1' of extension 'vscodevim.vim-1.8.1' as it is not compatible with Azure Data Studio '1.5.2'."

Thanks for any suggestions.

**Comment by anonimitoraf** [comment]
@ppegusii It works fine for me for azure data studio 1.11.0 (linux) and vscode vim 1.10.2
