### ISSUE TITLE
"Bind ZZ to save and close the current file" deletes all contents then save and quit file, can't undo the damage

### ISSUE THREAD

**Issue by crunchysoul** [VSCodeVim/Vim#2682]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT
**What happened**:
Followed the instruction on readme page "Bind ZZ to save and close the current file:"
```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["Z", "Z"],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.files.save",
                    "args": []
                },
                {
                    "command": "workbench.action.closeActiveEditor",
                    "args": []
                }
            ]
        }
    ]
```

tried this binding, it delete all contents on that file, then save and quit it, which is really dangerous, can not undo the damage.
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:

- Extension (VsCodeVim) version:
- VSCode version:
- OS version:

**Comment by costolo** [comment]
The same is happening to me. 

**Environment:**
- Extension version: 0.12.0
- VSCode version: 1.23.1
- OS version: macOS High Sierra 10.13.14

**Comment by crunchysoul** [comment]
@costolo I'm sorry to hear that, when this happened, I lost all my personal vs code settings accumulated over time, well, luckily didn't experiment it on my working folder.

**Comment by jpoon** [comment]
Workaround https://github.com/Microsoft/vscode/issues/50942#issuecomment-394615481

**Comment by costolo** [comment]
Thanks @jpoon, mapping the command to :wq works just fine for my use case.
