### ISSUE TITLE
ds deletes whole line

### ISSUE THREAD

**Issue by tylerthehaas** [VSCodeVim/Vim#2692]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**What happened**: the line was deleted on ds

**What did you expect to happen**: for it to wait for a character to delete like vim-surround does.

**How to reproduce it (as minimally and precisely as possible)**:

press ds on any line and it will delete the line

**Environment**:

- Extension (VsCodeVim) version: 0.12.0
- VSCode version: Version 1.24.0-insider 
- OS version: osx sierra

**Comment by xconverge** [comment]
I cannot reproduce this, can you give me some reproduction steps? pressing ds changes to Surround Input Mode for me and waits for a character

**Comment by tylerthehaas** [comment]
I think vscode was in some sort of weird state. I have not been able to reproduce this either I'll go ahead and close.

**Comment by u2berggeist** [comment]
I've also just run into this issue. A simple restart fixed the issue. No idea what caused it.
