### ISSUE TITLE
Add support for new grid layout with splits

### ISSUE THREAD

**Issue by rodcloutier** [VSCodeVim/Vim#2696]
** Feature request **

Split command should support the upcoming grid layout feature from VsCode.

VsCode issue and PR:
* https://github.com/Microsoft/vscode/issues/14909
* https://github.com/Microsoft/vscode/pull/49599

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/pull/2697

**Comment by elviskahoro** [comment]
@rodcloutier @jpoon I typically use <C-w>+s or <C-w>+v to create split panes. It stopped working for me so wanted to double check that this wasn't happening for others.

:vs still works!

**Comment by jwtly10** [comment]
> @rodcloutier @jpoon I typically use +s or +v to create split panes. It stopped working for me so wanted to double check that this wasn't happening for others.
> 
> :vs still works!

This has also stopped working for me!
