### ISSUE TITLE
Macro doesn't memoryize `delete` key.

### ISSUE THREAD

**Issue by maxco2** [VSCodeVim/Vim#2702]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**What happened**:Macro doesn't memoryize `delete` key.

**What did you expect to happen**:Macro memoryize `delete` key.

**How to reproduce it (as minimally and precisely as possible)**:
Record a macro, enter insert mode,  hit `delete` key. Stop record.
Use this macro on a non-space word.

**Environment**:

- Extension (VsCodeVim) version:0.12.0
- VSCode version:1.23.0
- OS version:Windows 10

**Comment by jpoon** [comment]
Cause we don't register that command: https://github.com/VSCodeVim/Vim/blob/master/package.json#L82. So when you press `delete`, it goes straight to the editor and the extension has no record of it.
