### ISSUE TITLE
Paste with CTRL+V while in edit mode does not work

### ISSUE THREAD

**Issue by givanse** [VSCodeVim/Vim#2706]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**:
1. Got to any app and press CTRL+C to put some text in your clipboard.
2. Got to VSCode, press `i` to enter edit mode
3. press CTRL+V, nothing happens

**What did you expect to happen**:
while in edit mode, CTRL+V pastes the content of the clipboard

If I disable VSCode Vim, CTRL+V works as usual.

- Extension (VsCodeVim) version: 0.12.0
- VSCode Version: 1.23.1 d0182c3417d225529c6d5ad24b7572815d0de9ac x64
- OS Version: Windows 10 version 1803

**Comment by givanse** [comment]
SHIFT+CTRL+V works, however CTRL+V used to work too

**Comment by doovemax** [comment]
i have the same problme,when i open vim. C+v not used to work

**Comment by scalpelx** [comment]
You can set `vim.useCtrlKeys` to false, or set
```
"vim.handleKeys": {
    "<C-c>": false,
    "<C-v>": false,
}
```

**Comment by tyru** [comment]
hmm, "fixing" this problem by changing to the previous behavior makes VSCodeVim uncompatible to original Vim behvaior.
Should we "fix" this?
Or the `vim.handleKeys` config which @scalpelx commented should be documented as FAQ?

**Comment by hnra** [comment]
Any reason why this can't work?

```
"vim.insertModeKeyBindings": [
    {
        "before": ["<C-v>"],
        "after": [],
        "commands": "editor.action.clipboardPasteAction",
        
    }
]
```

Would be nice to have `<C-v>` as paste in insert mode without giving up visual block because of `useCtrlKeys` or `handleKeys`.
