### ISSUE TITLE
Substitute backslash inconsistency

### ISSUE THREAD

**Issue by jrwrigh** [VSCodeVim/Vim#2710]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**What happened**:
When using substitute, the backslash character is not handled correctly. Typing in `\\` will print out "\\" instead of only one "\"

This wasn't really a problem until I ran into a case where I have to separate in "\right". If I use `:s/[find pattern]/\right/gc` I end up with the return command being used. The output is therefore "ight" on the next line.

If I use `:s/[find pattern]/\\right/gc`, it will simply output "\\right" which isn't what I wanted either.

**What did you expect to happen**:
`:s/[find pattern]/\\right/gc` to replace "\right" into the corresponding matches.
 
Note: the `:` is simply there for effect. I'm not entering `:` into the command box that pops up.

**Environment**:

- Extension (VsCodeVim) version: 0.12.0
- VSCode version: 1.23.1
- OS version: Windows 10

**Comment by u2berggeist** [comment]
It's actually worse. The backslash isn't working correctly at all right now. It will include the backslash whenever it's used as an escape:

Example:

I want to replace ever instance of `row[` with `other[`. To do that, I type in `:s/row\[/other\[/gc`. The result has all instances of `row[` replaced with `other\[`. So I can't use any special characters at all. 

Let me know if you need anymore information.

**Comment by u2berggeist** [comment]
I forgot to add that I have to use the backslash to use the bracket character.

ie. if I use `:s/row[/other[/gc`

Then I get the following error:
> Vim: SyntaxError: Invalid regular expression: /row[/: Unterminated character class

**Comment by prmichaelsen** [comment]
This is still an issue for me.
`C:\Path\That\Needs\Escaping:s/\/\\/gc` yields `C:\\\\\\Path\That\Needs\Escaping`

**Comment by jpoon** [comment]
This *should* work through [neovim](https://github.com/VSCodeVim/Vim#neovim-integration) if you want to give that a try.

**Comment by prmichaelsen** [comment]
I'll give it a try and report back

**Comment by msdrigg** [comment]
It's 2021 and this is still an issue for me.
