### ISSUE TITLE
Invalid handling key presses on X server with remapped keys.

### ISSUE THREAD

**Issue by nmiculinic** [VSCodeVim/Vim#2714]
BUG REPORT

**What happened**:
I have remapped escape to caps and vice versa on the X server. It works as expected in Vscode, and in other applications (( like terminal neovim )). 

When I'm in insert mode, and press <CapsLock> it doesn't transition me into normal mode, despite being remapped to <Esc>. 

When I press <Esc> (( which is mapped to <Caps> )) it goes into normal mode, but everything else acts like I pressed <Caps> (( as it should )). 
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

* Have linux with X server
* enable caps:swapescape option with `setxkbmap -option caps:swapescape` command.

This look like an environment input key press discrepancy. 

**Environment**:
X server with 
`setxkbmap -option caps:swapescape`
option

- Extension Name: vim
- Extension Version: 0.12.0
- OS Version: Linux x64 4.16.5-1-ARCH
- VSCode version: 1.24.0

**Comment by xconverge** [comment]
https://github.com/VSCodeVim/Vim/issues/1479

Is this the same? Does the setting referenced here fix the issue for you?

**Comment by nmiculinic** [comment]
Yes, the fix https://github.com/VSCodeVim/Vim/issues/1479#issuecomment-359266762 solved my issue
