### ISSUE TITLE
Can the '/' search use the search box of vscode ctrl+F?

### ISSUE THREAD

**Issue by futurehome** [VSCodeVim/Vim#2716]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

**What happened**: When searching using '/', it's not easy to see what I'm inputting on the bottom bar.

**What did you expect to happen**: When searching using '/', it can display the search box of vscode like the pic below.
![image](https://user-images.githubusercontent.com/6230304/41141908-64f7eca4-6b26-11e8-9330-5cf40b8e51c7.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**: 

- Extension (VsCodeVim) version: Any
- VSCode version: Any
- OS version: Win7

**Comment by jpoon** [comment]
They are two different searches. If you use vscode's search bar, there is no support for operations like search and replace.

**Comment by futurehome** [comment]
I know it's different searches.
You can see from the pic below, it's difficult to notice when you input the key words.
![image](https://user-images.githubusercontent.com/6230304/41153648-eed628dc-6b49-11e8-8499-02aa2ff4053c.png)

**Comment by asilvadesigns** [comment]
@futurehome why not just remap "/" to the editor command find like this...
witin: `keybindings.json`
```
  {
    "key": "/",
    "command": "actions.find",
    "when": "editorTextFocus && vim.active && vim.mode != 'Insert'"
  },
```

**Comment by futurehome** [comment]
@asilvadesigns  Good idea, i'll have a try. Thanks.

**Comment by ecolss** [comment]
@jpoon @asilvadesigns 
when I press '/' to search something, there is no indicator window or bar showing the word I'm typing to search, why? what if I want to search "A", but I just make a typo "B", no indicator showing the word I'm trying to search at all? this is very annoying, isn't it?

**Comment by jpoon** [comment]
![image](https://user-images.githubusercontent.com/85374/41805950-9b068a2a-7667-11e8-881d-cbb27756c32c.png)

@ecolss it's at the bottom where you would generally see the VIM mode. ("mysearch")
