### ISSUE TITLE
Yanking/deleting multiline into default register then pasting over other multiline text copies that overwritten multiline text, instead of retaining original yanked text.

### ISSUE THREAD

**Issue by brokenalarms** [VSCodeVim/Vim#2717]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**What happened**:

Yank two lines of text (A). Paste it over another two lines (B). If you paste again, B is pasted instead of A.

**What did you expect to happen**: This is different to Vim, where you can yank once and paste over and over. This only happens when the selection you are pasting over is multiline.

**How to reproduce it (as minimally and precisely as possible)**: As above

**Environment**:

- Extension (VsCodeVim) version: 0.12.0
- VSCode version: 1.24
- OS version: macOS 10.13.4

**Comment by Chaoclypse** [comment]
I have the same problem as well.

**Comment by j3soon** [comment]
Same problem here.

**Comment by chibicode** [comment]
@brokenalarms @j3soon could you try this from README: https://github.com/VSCodeVim/Vim/#key-remapping

```json
{
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": [
                "p",
            ],
            "after": [
                "p",
                "g",
                "v",
                "y"
            ]
        }
    ]
}
```

**Comment by j3soon** [comment]
Thanks, @chibicode ! It worked very well!
Sorry for not reading the entire README beforehand.
I think this issue can be closed.

**Comment by jpoon** [comment]
Closing as it seems we have a workaround.
