### ISSUE TITLE
Vim mode randomly not functional - show warning

### ISSUE THREAD

**Issue by aewing** [VSCodeVim/Vim#2725]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Hybrid

**What happened**:
Vim mode randomly stops functioning or does not function on initial load.

**What did you expect to happen**:
I expect vim mode to always work when enabled, or to prevent input when it is not 'working'.

**How to reproduce it (as minimally and precisely as possible)**:
Start up an editor on a large project. Open a file and begin typing. You will notice that 'vim mode' does not immediately activate and you are able to modify your file as if it were disabled.

**Environment**:
macOS, Windows 10, and Ubuntu 18.04

- Extension (VsCodeVim) version: Newest
- VSCode version: Newest
- OS version: Newest

Suggestion:
Perhaps it would be possible to show an easily-identified visual indicator (beyond the cursor) to indicate to the user that the editor is doing something and vim mode will be back shortly. An option to disable input while vim mode is not active would be very helpful as well -- perhaps with the aid of another extension.

**Comment by jpoon** [comment]
Do you see anything in the console? `help->developer tools`.

We're in the process of improving our logging which you'll see in the next release. We should also add a section in our `readme` of instructions on how you can debug this extension.

**Comment by aewing** [comment]
There is nothing of interest in developer tools.
This is something that I have always observed with vim mode. It seems to occur regularly when the editor is first launched.

**Comment by jpoon** [comment]
We added more logging, can you set it to `verbose` and see what logs there are: https://github.com/VSCodeVim/Vim#vimdebuglogginglevel

**Comment by aewing** [comment]
I will try to look into this today -- I noticed the issue again yesterday.

**Comment by jpoon** [comment]
In an effort to keep our issue list sane, I'm closing this issue particularly as there hasn't been an update, and the issue filed is rather generic without specific repro steps.
