### ISSUE TITLE
Different splits of the same file should track the cursor position separately

### ISSUE THREAD

**Issue by Gskartwii** [VSCodeVim/Vim#2728]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**What happened**:
When I moved the cursor in a split A, and then tried to move the cursor in split B of the same file, the cursor in split B jumped to the same position that it had been moved to in split A.

**What did you expect to happen**:
Each split should track the cursor position separately, which is the case in vanilla VSCode and Vim.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open a file in the editor.
2. `:sp`.
3. Move around in the newly created split.
4. Switch to the other split using the keyboard or mouse.
5. Press any directional key.

This applies to both normal and insert mode.

**Environment**:

- Extension Version: 1.0.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.25.0-insider

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/2688
