### ISSUE TITLE
Easymotion - markers are cutoff on left side of page

### ISSUE THREAD

**Issue by malevinson** [VSCodeVim/Vim#2751]
**BUG REPORT**

**What happened**
I press my hotkeys for either jump to line or jump to word. Any markers on the very left edge of the page are cut off. The first 3 rows have a ";" that you can't even see.

![screen shot 2018-06-19 at 9 45 55 am](https://user-images.githubusercontent.com/1870326/41611922-35415e5e-73a6-11e8-8f2a-022db85296d9.png)

**What did you expect to happen**
I expected to see the full character of the marker (semi colon in this case), regardless of where on the page the word or line is.

**How to reproduce it (as minimally and precisely as possible)**
Try your hotkey for easymotion on a line that has a word at the first space in the line.

Here is another screenshot of me trying to hack a fix so this character is visible:
![semicolons](https://user-images.githubusercontent.com/1870326/41636451-757b1b88-7403-11e8-93e7-bd320e9721b1.png)

This can probably be fixed with a vim.easymotionMarkerXOffset (currently there is only a Y offset option).

**Comment by sandangel** [comment]
in my editor, the character is cut off from bottom, so the 'v' and 'y' look the same. Could we introduce some padding to the label? It would be great if the label has some style like box-shadow.

**Comment by malevinson** [comment]
Does changing `"vim.easymotionMarkerYOffset": 4` not fix that? Y offset is basically padding.

My issue is more fundamental because it involve the edge of the page.

**Comment by berknam** [comment]
@J-Fields I think this issue is already fixed.
