### ISSUE TITLE
editor.smoothScrolling breaks C-d / C-u

### ISSUE THREAD

**Issue by parkovski** [VSCodeVim/Vim#2754]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**What happened**: Pressed Ctrl-D, cursor does not stay in its position on screen. When it is at the top, the scroll happens but then the window bounces back.

**What did you expect to happen**: Scrolling to not bounce back.

**How to reproduce it (as minimally and precisely as possible)**: Enable `editor.smoothScrolling` and try out the new behavior of C-d / C-u.

Basically, I'm about 99% sure it comes down to [this line](https://github.com/VSCodeVim/Vim/pull/2723/files#diff-ab811cd6f8cfa81bd0cb8223c86e72bfR677) and the equivalent in the duplicate function for C-u. When smooth scrolling is active, the await resolves before the visible ranges have been updated, so the "new first line" is always equal to the old first line, which locks the cursor within the visible screen area. Cc @rebornix 

- Extension (VsCodeVim) version: 0.13.1
- VSCode version: 1.24.1
- OS version: Windows 10 b17692

**Comment by chiuan** [comment]
.... i have to disable  the editor.smoothscrolling

**Comment by AsukaSong** [comment]
Is there any progress being made on this?

**Comment by eddiemf** [comment]
Same issue here, looks like no progress is being made on this
