### ISSUE TITLE
EasyMotion keybinding as space nolonger works, moves my cursor forward

### ISSUE THREAD

**Issue by moxuz** [VSCodeVim/Vim#2755]
This used to work for me, I have my setup as

```
  // VIM
  "vim.disableExtension": false,
  "vim.easymotionMarkerFontFamily": "Menlo",
  "vim.easymotion": true,
  "vim.easymotionMarkerYOffset": 0,
  "vim.easymotionMarkerHeight": 16,
  "vim.easymotionMarkerFontSize": "16",
  "vim.otherModesKeyBindingsNonRecursive": [
    {
      "before": [" "],
      "after": ["leader", "leader", "leader", "b", "d", "w"]
    }
  ],

```
I used to be able to hit space and use easymotion, but I haven't used VSCode in a few months and it no longer works. At the moment it just moves my cursor forward by one character when I hit space.

Thanks 😄

**Comment by typeoneerror** [comment]
@moxuz 0.13.0 broke `otherModesKeyBindingsNonRecursive` and introduced `normalModeKeyBindingsNonRecursive` https://github.com/VSCodeVim/Vim#quick-example.

**Comment by jpoon** [comment]
For more info, https://github.com/VSCodeVim/Vim/blob/master/CHANGELOG.md#v0130-2018-06-18
