### ISSUE TITLE
Bug: Remapping Numbers (0-9)

### ISSUE THREAD

**Issue by davidnorthetal** [VSCodeVim/Vim#2759]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**What happened**:
I have the following user settings:
`"vim.normalModeKeyBindingsNonRecursive": [ {
	"before": ["0"],
	"after": ["^"]
} ],`

I type `0` in normal-mode and the same happens as it always does (it jumps to the very  beginning of the current line).

**What did you expect to happen**:
It should instead jump to the first charcter of the current line.

Changing the after from "^" to ":", which should focus the command-prompt instead also turns out to not do anything.

- Extension (VsCodeVim) version: 0.13.1
- VSCode version: 1.24.1
- OS version: Win10

**Comment by jpoon** [comment]
To clarify, the bug is

**Comment by xconverge** [comment]
For some reason this binding also makes my vscodevim experience INCREDIBLY slow, ~1 sec per keypress if holding j or k
