### ISSUE TITLE
Ctrl+D stuck on top of the window on visual mode

### ISSUE THREAD

**Issue by chibicode** [VSCodeVim/Vim#2766]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**What happened**: Turn on visual mode, and then hit Ctrl + D several times. The cursor gets stuck on top of the window. Not a problem in normal mode.

**What did you expect to happen**: It keeps scrolling down.

![kapture 2018-06-25 at 9 39 28](https://user-images.githubusercontent.com/992008/41825499-f8b1ca5e-785b-11e8-9ab0-cc271e688f31.gif)

Could be related to 
https://github.com/VSCodeVim/Vim/issues/2754
https://github.com/VSCodeVim/Vim/issues/1348

...but this is visual mode specific.

**Environment**:

- Extension (VsCodeVim) version: 0.13.1
- VSCode version: 1.24.1
- OS version: macOS 10.13.5

**Comment by michaelHL** [comment]
Same here, do not work on **normal mode** either.

**Comment by xconverge** [comment]
@rebornix I have a tiny fix for this, however C-d and C-u are still a work in progress when switching directions and a selection is active

**Comment by chibicode** [comment]
@xconverge @rebornix thank you! Looking forward to the new version.

**Comment by bfwg** [comment]
@xconverge I'm running into this issue again on the latest version(0.16.4).

**Comment by ParkJongdoo** [comment]
@jpoon  this issue occurred again on the latest version(16.6)
