### ISSUE TITLE
Surround aliases not working as targets

### ISSUE THREAD

**Issue by vogler** [VSCodeVim/Vim#2769]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

**What happened**:
`ds(` and `ds)` work on `foo (bar) baz`, but `dsb` does not. It seems like aliases only work for replacements (and not targets): `cs(B` works while `csbB` does not.

Also, the aliases should correspond to closing brackets instead of opening ones:
"The targets b, B, r, and a are aliases for ), }, ], and >"
https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L99

**Environment**:

- Extension (VsCodeVim) version: 0.13.1
- VSCode version: Code 1.24.1 (24f6262, 2018-06-13T17:41:50.128Z)
- OS version: Darwin x64 17.7.0

**Comment by xconverge** [comment]
This was an easy one, should be in the next release, and thanks for the link to the documentation, it made my job easier!
