### ISSUE TITLE
[neovim] Inconsistent behaviour when clicking files in the file tree

### ISSUE THREAD

**Issue by GeorgeTG** [VSCodeVim/Vim#2770]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT(?)

**What happened**:
Clicking on a file on the file tree has seemingly has random behaviour.
Some times a new tab will be opened and the rest the open tab(buffer) is replaced.

**What did you expect to happen**:
Either open a new tab or replace the currently open one consistently.
A modifier key should be used for the other functionality (much like vim nerd tree)

**How to reproduce it (as minimally and precisely as possible)**:
Enable neovim integration, open a large project folder and randomly click on files on the file tree.

**Environment**:

- Extension (VsCodeVim) version: 0.13.1
- VSCode version: 1.24.1
- neovim version: 0.3.0
- OS version: Archlinux @ 4.17.2-1

**Comment by jpoon** [comment]
We are only using Neovim for command-line operations. Do you see the same behaviour with neovim-disabled?

Generally, the new file will be open on the "active" tab. Holding alt and clicking on the file will open a new tab.

**Comment by GeorgeTG** [comment]
@jpoon Turns out that for some reason there were spurious clicks generated from my mouse, so sometimes while I was single clicking, a double click was sent.
