### ISSUE TITLE
Cursor not maintaining location on multiple split windows

### ISSUE THREAD

**Issue by lpabon** [VSCodeVim/Vim#2777]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

- VSCode Version:

```
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:47:35.732Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

- OS Version: Fedora 27

Steps to Reproduce:

1. Install plugin vim 0.14.0, Go 0.6.83
1. Open a golang file
1. Split the editor
1. One one window use `j` (using vim mode) to move down the file.
1. Then press `Ctrl+1` to go to the other window.
1. Press j, and notice that the cursor _continued_ down to the next line from the previous window instead of having its own location.

Does this issue occur when all extensions are disabled?: No

**NOTE**:
This is a regression. This was not happening a few months ago.

**Comment by jpoon** [comment]
Dupe https://github.com/VSCodeVim/Vim/issues/2688
