### ISSUE TITLE
 In visual mode `$` selects the line break too.

### ISSUE THREAD

**Issue by epeli** [VSCodeVim/Vim#2778]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

bug

**What happened**:

In visual mode `$` selects the line break too.

**What did you expect to happen**:

It should only select to the end of the line like the real vim.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to a middle of a line
2. Start visual mode with `v`
3. Move cursor to the end with `$`
  - Notice that the cursor moves to the start of next line but it should not
4. Yank the selection with `y`
5. Paste it some where with `p` and you should see extra line break to appear

**Environment**:

- Extension (VsCodeVim) version: 0.14.0
- VSCode version: 1.24.1
- OS version: macOS Sierra, Windows 10

**Comment by xconverge** [comment]
This matches default vim behavior on my machine..

**Comment by epeli** [comment]
Oh, shit. You're right I had it buried in my config for years... Embarrassing :)
