### ISSUE TITLE
Unable to Update or Install VSCodeVim on Windows 10 using the Extension Market place

### ISSUE THREAD

**Issue by atiqorin** [VSCodeVim/Vim#2783]
**BUG REPORT**:

**What happened**:
Unable to update or install VSCodeVim on Windows 10 using the Extension Market place
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

- Extension (VsCodeVim) version:
- VSCode version: v0.14.0
- OS version: Windows 10

**Comment by xconverge** [comment]
Can you try this? This is most likely an upstream vscode issue... The instructions here are for a full uninstall and reinstall of the extension

https://github.com/VSCodeVim/Vim/issues/2185#issuecomment-348047731

**Comment by atiqorin** [comment]
I completely uninstalled VSCode. Upgraded Node and npm, deleted extensions folder and tried to install VsCodeVim after reinstalling VSCode and still no luck.

**Comment by xconverge** [comment]
What happens?

**Comment by atiqorin** [comment]
It sometimes says failed to install. Then there is an option to download manually. Which gives an option to download the vsix file and install through that, which also fails. Most of the time it keeps getting installed and nothing happens.

**Comment by xconverge** [comment]
I would try looking for any clues in the develop tools window "Toggle Developer Tools". I would also point you to the vscode github issues because this is not going to be something we can solve here most likely.

**Comment by atiqorin** [comment]
@xconverge I see winston package is not installing thru npm and I believe this might be the issue.

**Comment by xconverge** [comment]
what is the specific error? Are you behind a proxy or anything?

**Comment by atiqorin** [comment]
Some how the .vscode folder became readonly for me. That is why node modules were not getting installed. After unchecking readonly it installed successfully. Thanks for your help.
