### ISSUE TITLE
":w<return>" in Ruby files just adds a newline instead of saving

### ISSUE THREAD

**Issue by knightstick** [VSCodeVim/Vim#2785]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**What happened**:
Whenever I'm editing a `.rb` file, and try to save using the command line `:w`, the "return" press fails to execute the command, and instead, just adds a newlilne. It behaves as expected in other file types. I've disabled (and reloaded) all extensions specific to ruby to see if that solves the issue, but it doesn't.

**What did you expect to happen**:
`:w` to save the file without changing the open document.

**How to reproduce it (as minimally and precisely as possible)**:
Open a `.rb` file and try a `:` command

**Environment**:
VSCode Version 1.24.1 (1.24.1), VSCodeVim 0.14.0

- Extension (VsCodeVim) version: 0.14.0
- VSCode version: 1.24.1
- OS version: macOS High Sierra 10.13.5

**Comment by takanabe** [comment]
Same here. and 
 think this is related to the recent changes to handle vim command at the status bar https://github.com/VSCodeVim/Vim/commit/29e90def42be39005fcebe7844e69cd897592e01

**Comment by knightstick** [comment]
@jpoon thanks for taking a look - by process of elimination, I've discovered that disabling the "Endwise" extension seems to fix the issue, so, happy to report it's not a bug with VSCodeVim.

Thanks again! 🎉
