### ISSUE TITLE
case insensitive/smart case search

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#279]
When you search with / or ?, by default vim does case insensitive search. If you type an upper case letter in the search string, Vim switches to case sensitive. It's a clever system that we should emulate; currently / and ? are permanently case sensitive, which is annoying.

**Comment by rebornix** [comment]
Just look into the description of searching and find following:

1. Search is case sensitive by default
2. User can make case insensitive by enabling `ignorecase`
3. If `ignorecase` is turned on, users can use `smartcase` to auto-detect the case and be smart.

**Comment by zwing99** [comment]
+1 for this feature!
Especially with ignorecase / smartcase as the proper .vimrc control equivalents.

Thanks!

**Comment by darianmorat** [comment]
The best approach in my opinion is the following:

 ```
"vim.ignorecase": false,  
  "vim.smartcase": false
```

So for example you have this text: 

`PAPER, Paper, paper`

using the '/paper' is gonna search just the one out of the 3 that you specifically want, and if you want to find all the matches, that would be just: 

`/paper\c `
