### ISSUE TITLE
shift + v not working  when I use o

### ISSUE THREAD

**Issue by polodev** [VSCodeVim/Vim#2800]
I am used to with full visual selection using `shift + v` and 'o' combine. In vs code I can't full select using `shift + v` is there any hack to get that. 
Thanks

**Comment by J-Fields** [comment]
Could you clarify? `V` should take you into visual line mode, where `o` does not work in either vim or VSCodeVim.

**Comment by J-Fields** [comment]
Closing as it's been months without elaboration
