### ISSUE TITLE
:tablast broken with vscode 1.25.0

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#2813]
Vscode 1.25 removed the command ```workbench.action.openLastEditorInGroup```

https://code.visualstudio.com/updates/v1_25#_removed-commands

We utilize this for :tablast

Replace with ```workbench.action.lastEditorInGroup``` and mark 1.25 as the minimum vscode version in package.json

**Comment by Roshanjossey** [comment]
Hi @xconverge, I'm taking a stab at this issue.

Should I commit changes in `package-lock.json`?

Thank you.

**Comment by jpoon** [comment]
Yes. If you made changes to package.Json, please commit changes to the lock file

**Comment by Roshanjossey** [comment]
@jpoon, thank you for your response.

Yes, I've made changes to `package.json`. There are other changes in dependency versions in `package-lock.json`.

I'll submit a pull request with my changes and let's discuss if we need to make anymore changes to that 😄.
