### ISSUE TITLE
TypeError shown on invalid search command.

### ISSUE THREAD

**Issue by Lamoreauxaj** [VSCodeVim/Vim#2823]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT (very minor)

**What happened**:
The search and replace commands :s and :%s throw a "TypeError: cannot read property '0' of null", when the command is incomplete and enter is pressed.

**What did you expect to happen**:
Note this is just my opinion and I just wanted to provide some input.
I feel that there should be error checking instead of an error that isn't actually applicable to the end user because it's specific to the property of the actual data type. I feel like this error should be checked in the implementation of these commands to prevent this error from ever appearing.
Also in actual Vim, the error would at least be applicable to the searching of the pattern stating that the pattern wasn't found instead of this kind of error.

**How to reproduce it (as minimally and precisely as possible)**:
Open vscode type :s<enter>. Yes this is an invalid command, my issue is only with the displayed error.

**Environment**:

- Extension (VsCodeVim) version: 0.14.2
- VSCode version: 1.25 Insiders
- OS version: Ubuntu 18.04

**Comment by xconverge** [comment]
What if we have it popup pattern not found? (The same as vim)
