### ISSUE TITLE
Zombie processes

### ISSUE THREAD

**Issue by chrisolsen** [VSCodeVim/Vim#2827]
With vscode closed I still have a huge list of nvim processes running. This issue was supposedly fixed in https://github.com/VSCodeVim/Vim/issues/2038 and https://github.com/VSCodeVim/Vim/issues/2558

![capture](https://user-images.githubusercontent.com/41582/42513181-87fabaf0-8413-11e8-9f55-b4cded9ac184.PNG)

**Environment (please complete the following information):**
- Extension Version: 0.14.2
- OS Version: Windows_NT ia32 10.0.17134 (windows 10 pro)
- VSCode version: 1.25.0

**Comment by xconverge** [comment]
I can't reproduce this, does it happen every time for you?

**Comment by chrisolsen** [comment]
It seems that Scoop, the Windows CLI installer may be causing the issues. When opening a file in vscode two nvim processes were being started for every file opened and when the file is closed only one nvim process is killed. After removing Scoop's `/shims` path from the env settings and adding the `scoop/.../neovim/bin` folder to the env values I no longer have the issue.

**Comment by xconverge** [comment]
interesting! thanks for doing the legwork
