### ISSUE TITLE
Option case-insensitive for vim-sneak

### ISSUE THREAD

**Issue by muhajirframe** [VSCodeVim/Vim#2829]
**Is your feature request related to a problem? Please describe.**
Feature Request
For example

I wanna go to word `Material`, It's easier to type `sma` rather than `sMa` isn't it?

**Describe the solution you'd like**
Option to make vim-sneak case-insensitive

**Comment by xconverge** [comment]
Reference: https://github.com/justinmk/vim-sneak/blob/5d81dcceee9894f433ab16b766db32dcbffef7af/doc/sneak.txt#L298

**Comment by muhajirframe** [comment]
Is it possible to do that with vscodevim @xconverge ?

**Comment by xconverge** [comment]
Sorry I was adding a reference to what the functionality is based on so that when this issue is addressed it can be addressed properly.

A quick and simpler fix might be a flag that just toggles case sensitivity for vimsneak no matter what other settings are set

**Comment by muhajirframe** [comment]
Hi @xconverge , Is it possible to use it now?

**Comment by muhajirframe** [comment]
Okay, thank you.

**Comment by xconverge** [comment]
The release is out so it can be used now by the way!

**Comment by jpoon** [comment]
In the future, GitHub actually shows the tags that commits are included in. For instance, https://github.com/VSCodeVim/Vim/pull/2837/commits/43fb74a4ac3705d56e787ce9ee5a3b0848a2f199 you'll see a `v0.15.1`.
