### ISSUE TITLE
Bug: Remapping of numbers (specifically 0) breaks consecutive counting started with non-remapped number-keys

### ISSUE THREAD

**Issue by davidnorthetal** [VSCodeVim/Vim#2831]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

I happen to notice that https://github.com/VSCodeVim/Vim/pull/2793 breaks the count feature, so once I remap 0 to ^, doing something like `20j` instead of going 20 lines down, it goes one line down after setting the cursor to the beginning of the current line.

You might argue that works as intended but it is not how Vim behaves, In my vimrc I have simply:
```
noremap 0 ^
noremap ^ 0
```

and `20j` still jumps down 20 lines fine. while `0` outside of a started count works as expected

----

in my user-settings I use:
```
    "vim.normalModeKeyBindings": [
        {
            // 0 => ^
            "before": ["0"],
            "after": ["^"]
        }
    ],
```

- Extension Name: vim
- Extension Version: 0.14.2
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.24.1

**Comment by dmastylo** [comment]
Experiencing this behavior as well; I find the 0 -> ^ remapping to be pretty popular and this bug is causing jumping to lines with a 0 in them impossible, as it's interpreting the 0 as a BOL movement.

**Comment by dmastylo** [comment]
Any chance eyes could be put on this? Have been using workarounds for this to navigate around my code for a while.

**Comment by davidnorthetal** [comment]
Pretty sure this has been fixed in one of the recent updates. Can not reproduce.

**Comment by dmastylo** [comment]
@davidnorthetal, just tried it on my instance and seems to be fixed. Thanks for the update! Now to unlearn the "wrong" method I muscle memory'd for the work around haha
