### ISSUE TITLE
Cursor is lost when entering Zen mode

### ISSUE THREAD

**Issue by lane-s** [VSCodeVim/Vim#2832]
**Describe the bug**
When entering Zen mode, the cursor is lost and can only be restored by clicking.

**To Reproduce**
1. Open a file with VSCode/VSVim
2. Navigate to a line
3. Enter Zen Mode

**Expected behavior**
The cursor should remain in place and be usable in Zen Mode without clicking the screen.

**Environment (please complete the following information):**

 - Extension (VsCodeVim) version: 0.14.2
 - VSCode version: 1.25
 - OS: OSX 10.12.5

**Comment by xconverge** [comment]
I get the same behavior when I run vscode with vscodevim disabled. Would you mind filing an upstream issue in the vscode repo for this? I poked around and cannot find an event or anything to register on to fix this from our side. Thanks!

**Comment by lane-s** [comment]
Sorry, should've checked that! Yeah I'll file an issue in the vscode repo.

**Comment by jpoon** [comment]
Closing this issue as it seems like it's more of a vscode thing.
