### ISSUE TITLE
Keybindings not triggering

### ISSUE THREAD

**Issue by b-m-f** [VSCodeVim/Vim#2833]
**Describe the bug**
Trying to trigger my keybindings throws an error .

```

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] TaskQueue: error running task. err=TypeError: Cannot read property 'slice' of undefined.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270
```

Keybindings that do not work
```
"vim.normalModeKeyBindings": [
        {
            "before": [
                "<leader>",
                "q",
            ],
            "commands": [
                ":wq"
            ]
        },
        {
            "before": [
                "<leader>",
                "v",
            ],
            "commands": [
                "workbench.action.splitEditorDown"
            ]
        },
        {
            "before": [
                "<leader>",
                "h",
            ],
            "commands": [
                "workbench.action.splitEditorRight"
            ]
        },
    ]
```

**To Reproduce**
1. Go to any file
2. Execute those shortcuts
3. See error in devtool

**Expected behavior**
Shortcuts should trigger

**Screenshots**

**Environment (please complete the following information):**

 - Extension (VsCodeVim) version: 0.14.2
 - VSCode version: 1.25.0
 - OS:  Max

**Additional context**

It works fine when starting the `extension` in the extension development host via the debugger.

This problem only appears when using the normal VSCode

**Comment by xconverge** [comment]
Ah unfortunately our README does not exactly match the latest released version the vscode marketplace

This feature was just updated this week https://github.com/VSCodeVim/Vim/pull/2807

So for now you can use the old style command syntax which can be seen in the README.md in vscode extension or marketplace https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

A new release should come out shortly supporting the new syntax but it is backwards compatible so it will not "impact" your bindings

**Comment by xconverge** [comment]
Please let me know if you continue to have issues! Closing for now since this is addressed in the next release

**Comment by xconverge** [comment]
The new release is out so your syntax should work now!

**Comment by wangsongiam** [comment]
I've got a similar error from recent updates. 

VScode: 1.30.2
Vim extension: 1.0.3
OS: MacOS

Settings
```json
  // mapping c-a to cursorLineStart in insert mode
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "<c-a>"
      ],
      "after": [],
      "commands": [
        {
          "command": "cursorLineStart",
          "args": []
        }
      ]
    }
  ],
```

Error
```
ModeHandler: error handling key=<C-a>. err=TypeError: Cannot read property 'slice' of undefined
```
