### ISSUE TITLE
Option for fine undo

### ISSUE THREAD

**Issue by x-ji** [VSCodeVim/Vim#2835]
**Is your feature request related to a problem? Please describe.**
Not necessarily. There seem to still be some issues with the current undo implementation (https://github.com/VSCodeVim/Vim/issues/2007) but that seems to be a separate issue.

**Describe the solution you'd like**
Vim's default undo behavior will undo all the changes performed in insert mode before switching back to normal mode. However, some users might be used to performing multiple actions in insert mode and would want the undo to be based on smaller units than the default.

Emacs' Vim emulation package, Evil mode, offers such a possibility with `(setq evil-want-fine-undo t)`. See [this](https://emacs.stackexchange.com/questions/3358/how-can-i-get-undo-behavior-in-evil-similar-to-vims) and [this](https://stackoverflow.com/questions/10474555/how-to-change-granularity-level-of-undo-in-emacs-evil-mode-with-undo-tree).

In Vim there are similar modifications such as [this](https://vim.wikia.com/wiki/Modified_undo_behavior) and [this](https://stackoverflow.com/questions/2895551/how-do-i-get-fine-grained-undo-in-vim).

VSCodeVim can offer an option to allow such fine undo behavior. This option will be disabled by default.

Actually this seems to be doable simply by performing the following keybindings in `"vim.normalModeKeyBindingsNonRecursive"`:
```
        {
            "before": [
                "u"
            ],
            "after": [],
            "commands": [
                {
                    "command": "undo"
                }
            ]
        },
        {
            "before": [
                "<C-r>"
            ],
            "after": [],
            "commands": [
                {
                    "command": "redo"
                }
            ]
        }
```

**Describe alternatives you've considered**

**Additional context**
This is probably not urgent as Vim doesn't offer it by default. But it would still be nice to have. Many Evil users are used to this behavior.

**Comment by J-Fields** [comment]
As of next release, we will support `<C-g>u>`, which can be used to customize when undo points are created in Insert mode
