### ISSUE TITLE
Immediately to normal mode when open a file!

### ISSUE THREAD

**Issue by trackless** [VSCodeVim/Vim#2838]
**Describe the bug**
I've found that when open a file, first is not normal mode but insert mode.
After a short blink it turned to normal mode.

when I use sublime previously，it has a configuration item to solve it 😁

**Comment by xconverge** [comment]
This has to do with the extension loading and being activated. It switches to normal without you doing anything, right?

**Comment by trackless** [comment]
Yep. 
Please refer to:
[Command Mode by default on file open](https://forum.sublimetext.com/t/command-mode-by-default-on-file-open/2386)
Thanks a lot.

**Comment by xconverge** [comment]
Yea but if it switches to normal after a few moments, then we are doing everything we can. Unfortunately there is a delay in initially starting the extension.

I am not sure a configuration item has anything to do with it unless I am misunderstanding

**Comment by trackless** [comment]
Yep. I have understood this logic flow. I am already very satisfied with your contribution.💯

**Comment by xconverge** [comment]
Please feel free to reopen or file a new issue if you have further issues!
