### ISSUE TITLE
Change surround tag with tag including a dot

### ISSUE THREAD

**Issue by UpsideDownRide** [VSCodeVim/Vim#2850]
When using cst on existing tag following behavior occurs:
```
<Example>
</Example>

cst<With.Dot>
```
Result:
```
<With.Dot>
</With>
```
Expected result:
```
<With.Dot>
</With.Dot>
```

**Comment by xconverge** [comment]
This is related to this change I believe:

https://github.com/VSCodeVim/Vim/pull/1680/files
