### ISSUE TITLE
Switching escape and capslock

### ISSUE THREAD

**Issue by oxodao** [VSCodeVim/Vim#2859]
**Describe the bug**
When the keyboard has a custom mapping, VSCodeVim do not use it.
I am switching my capslock and escape keys through the xkbmap command 

**To Reproduce**
1. Fresh install of VSCode + VSCodeVim
2. Run the command
`$ setxkbmap -option "caps:swapescape"`
3. Enter insert mode
4. Press caps lock, nothing happens
5. Press escape, caps lock is turned on and VSCodeVim exit insert mode

**Expected behavior**
Since the key is remapped to capslock, this key should work and not the original escape one.

**Environment (please complete the following information):**
 - Extension (VsCodeVim) version: 0.15.2
 - VSCode version: 1.25.1
 - OS: ArchLinux / Latest updates

**Additional context**
This is probably a reccurent problem since lots of vim users like to switch thoses keys because it's easier to use

**Comment by xconverge** [comment]
can you try this ```"keyboard.dispatch": "keyCode"```

https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

**Comment by oxodao** [comment]
This is indeed working, sorry for the trouble

**Comment by bhumit070** [comment]
how to undo this ?

**Comment by awvalenti** [comment]
I added `"keyboard.dispatch": "keyCode",` line to my `settings.json` and it worked. Thanks!

Since I use Brazilian keyboard, a few other keymappings needed to be remade.

@bhumit070, doesn't removing the added line undo it?
