### ISSUE TITLE
Not an editor command?

### ISSUE THREAD

**Issue by hristod** [VSCodeVim/Vim#2868]
**Describe the bug**
Recently the extension started to fail all the time. When I open the development console, I get an error like:

`/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] error: commandLine : error executing cmd=W. err=E492: Not an editor command.`

It happens every time I try an invalid command (like :W instead of :w).

**To Reproduce**
1. Go to any editor window
2. Enter ":W"
3. See error

**Expected behavior**
Extension should keep working

**Screenshots**

**Environment (please complete the following information):**

- Extension Name: vim
- Extension Version: 0.15.3
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.25.1

**Comment by jpoon** [comment]
On the latest extension version (0.15.3), you should be seeing that same error on the status line. The error means that the command you inputted is not an understood vim command. http://vimdoc.sourceforge.net/htmldoc/message.html#messages

We should probably fix the level on the log message as it shouldn't be an "error" level.

**Comment by xconverge** [comment]
I assume that you have enableNeovim set to true?

**Comment by hristod** [comment]
Yeah, I've got Neovim enabled. Shall I disable it?

**Comment by hristod** [comment]
I've disabled it for now, this seems to work well :) My version is NVIM v0.2.2

**Comment by xconverge** [comment]
If you are interested in reenabling it, you could try with 0.3.0+, however 0.2.2 should be more than ok!
