### ISSUE TITLE
Yanking from command mode is not supported 

### ISSUE THREAD

**Issue by dmastylo** [VSCodeVim/Vim#2869]
**Describe the bug**
Yanking from command mode is not supported:

`:.,162y`
`:142,162y`

**To Reproduce**
1. Enter command mode with ':'
2. Enter in any range of numbers with y following

**Expected behavior**
The range of lines should be yanked.

**Environment (please complete the following information):**

 - Extension (VsCodeVim) version: v0.15.3
 - VSCode version: Version 1.25.1 (1.25.1)
 - OS: macOS High Sierra

**Additional context**
Doing the same with "delete" does work:

`:,162d`
`:142,162d`

**Comment by hxuanhung** [comment]
@dmastylo btw, `:,162d` doesn't work for me.

**Comment by hxuanhung** [comment]
@LeahCim yes, I confirmed. Thank you.

**Comment by dmastylo** [comment]
Using the _Enable Neovim_ setting unfortunately causes things to be pasted with tabs instead of respecting the setting to convert those to spaces.

**Comment by J-Fields** [comment]
Closing in favor of https://github.com/VSCodeVim/Vim/issues/3219
