### ISSUE TITLE
All text objects

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#287]
- [x] `a(` and `i(`
- [x] `a"` and `i"`
- [x] `a'` and `i'`
- [x] `a<` and `i<`
- [x] `a[` and `i[`
- [x] `a{` and `i{`
- [x] `aw` and `iw`

Most of these are tedious but easy. The quoted ones are going to be a little harder, however.

**Comment by johnfn** [comment]
Thanks to @sectioneight for allowing me to tick off a number of these boxes! 😃

**Comment by sectioneight** [comment]
no prob! Iirc I didn't get square brackets yet. It should be a trivial change though.

**Comment by rebornix** [comment]
With https://github.com/VSCodeVim/Vim/pull/385, we have `aW`, `iW` as well.

**Comment by johnfn** [comment]
Already checked off 😉

**Comment by johnfn** [comment]
Thanks to @sectioneight for nailing all of these!

**Comment by hew** [comment]
Any plans to support `at`/`it` (tag)?

**Comment by johnfn** [comment]
We actually do support at/it. We do have an open bug about not supporting multiline tags, however. #1108
