### ISSUE TITLE
Unable to switch back to normal mode in insert mode

### ISSUE THREAD

**Issue by Jeffrey04** [VSCodeVim/Vim#2870]
**Describe the bug**
I am unable to switch back to normal mode after pressing ESCAPE in insert mode (default keybinding).

**To Reproduce**
1. Press `i` to start editing file
2. Press `Escape` to go back to normal mode
3. Stays in insert mode

**Expected behavior**
I expect the plugin would bring me back to normal mode.

**Environment (please complete the following information):**

 - Extension (VsCodeVim) version: 0.15.3
 - VSCode version: 1.25.0 (snap package version)
 - OS: Ubuntu 18.04

**Additional context**
I partially fixed the problem by changing this

```
{
    "key": "escape",
    "command": "extension.vim_escape",
    "when": "editorTextFocus && vim.active && !inDebugRepl"
}
```

to (removing `inDebugRepl` check)

```
    {
        "key": "escape",
        "command": "extension.vim_escape",
        "when": "editorTextFocus && vim.active"
    }
```

**Comment by xconverge** [comment]
Do you remap caps to escape or anything like that?

**Comment by Jeffrey04** [comment]
I don't remember having something like that, but will check again when i got home again later

**Comment by bohrshaw** [comment]
Setting `"keyboard.dispatch": "keyCode"` fixes this issue for me when I'm using a remote Linux desktop.
This may help: https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings

**Comment by mykter** [comment]
> Setting `"keyboard.dispatch": "keyCode"` fixes this issue for me when I'm using a remote Linux desktop.

thanks, fixed it for me (using vmware)

**Comment by jpoon** [comment]
Sounds like we have a resolution?
