### ISSUE TITLE
":m <any number>" produces "E492: Not an editor command"

### ISSUE THREAD

**Issue by keeed** [VSCodeVim/Vim#2882]
**Describe the bug**
:m command is not working as expected.

**To Reproduce**
1. Go to any line
2. Try moving a line using :m <any number>

**Expected behavior**
Line will be moved.

**Environment (please complete the following information):**

 - Extension (VsCodeVim) version: 0.15.6
 - VSCode version: 12.5.1
 - OS: Windows 10

**Comment by keeed** [comment]
@xconverge I tried adding adding vim.enableNeovim: true in my User Settings but is still getting the error.

Also, I'm not sure if this was working previously. It's my first time to try the :m command with vscodevim.

![image](https://user-images.githubusercontent.com/11542472/43174884-07916124-8fef-11e8-8c01-b219c9421300.png)

![image](https://user-images.githubusercontent.com/11542472/43174907-1886db30-8fef-11e8-859c-6ae57978f736.png)

**Comment by xconverge** [comment]
did you restart after enabling neovim support?

**Comment by keeed** [comment]
Yup, I restarted vscode but is still not working.

**Comment by fengbo123** [comment]
@keeed 
maybe you should set neovimPath
```
"vim.enableNeovim":true,
"vim.neovimPath": "c:/opt/Neovim/bin/nvim.exe",
```

**Comment by jpoon** [comment]
I too suspect its an error with your neovim settings or installation. Try adjusting `vim.debug.loggingLevel` to see if there are pertient logs. 

In an effort to keep our issue count sane, I am closing this issue.

**Comment by iam-jim** [comment]
I was having the same issue and I added neovim to the path too, it was not working. Turns out the path was not working because the sample path for windows given in the comment above the `vim:neovimPath` setting provides wrong info. 
 
`// Path to run neovim executable. For example, /usr/bin/nvim, or  C:\Program Files\Neovim\bin\nvim.exe
"vim.neovimPath": "nvim"`

The correct way should be `C:\\Program Files\\Neovim\\bin\\nvim.exe` using escape character, please update the document else it is going to confuse a lot of people.

**Comment by jpoon** [comment]
Feel free to submit a PR

**Comment by xconverge** [comment]
> 
> 
> I was having the same issue and I added neovim to the path too, it was not working. Turns out the path was not working because the sample path for windows given in the comment above the `vim:neovimPath` setting provides wrong info.
> 
> `// Path to run neovim executable. For example, /usr/bin/nvim, or C:\Program Files\Neovim\bin\nvim.exe "vim.neovimPath": "nvim"`
> 
> The correct way should be `C:\\Program Files\\Neovim\\bin\\nvim.exe` using escape character, please update comment else it is going to confuse a lot of people.

This is actually a bit weird

https://github.com/VSCodeVim/Vim/blob/3dd6b4846dc66872461e871a65815e226e562002/package.json#L607

That is how I have it written in package.json already for the reason you mentioned

**Comment by jpoon** [comment]
It gets presented in VS Code as: 

![image](https://user-images.githubusercontent.com/85374/50577803-160af700-0de5-11e9-8680-a3572cd2c101.png)

**Comment by rafaelbdb** [comment]
@fengbo123 Solved for me! Thanks a lot! This was the only command I needed to be perfect!

@jpoon Try to enable Neovim as fengbo discribed. The correct command is:
`:<starting_line>,<final_line>m <destination_line>[ENTER]`

**Comment by ajatdarojat45** [comment]
i faced same issue. 

so i have custom shortcut in nvim.init file. when i triggreded in vscode i face this error like image bellow.
<img width="863" alt="image" src="https://github.com/VSCodeVim/Vim/assets/23049322/67ae371e-6460-4359-bbae-09e83831373a">

this is my setting.json
<img width="863" alt="image" src="https://github.com/VSCodeVim/Vim/assets/23049322/105a2f0e-f7c1-4f24-b3c3-57f8ccd2b1d8">
