### ISSUE TITLE
'r' in insert mode not entered when typed quickly

### ISSUE THREAD

**Issue by kieferrm** [VSCodeVim/Vim#2888]
Issue Type: <b>Bug</b>

Was originially filed against VS Code by @wcauchois. Pls see: https://github.com/Microsoft/vscode/issues/54959.

Extension version: 0.15.6
VS Code version: Code - Insiders 1.26.0-insider (befea2253626b1918352df04477cae83eee618ac, 2018-07-24T05:11:44.849Z)
OS version: Darwin x64 16.7.0

**Comment by xconverge** [comment]
This is very interesting! I can reproduce it very easily

**Comment by xconverge** [comment]
this is awesome, fails for all of the functions in __proto__ for an Object

hasOwnProperty for example 🤣 

```
      if (keySlice in userDefinedRemappings) {
```
