### ISSUE TITLE
mapping jj to Esc and setting default keyboard does not seem to work

### ISSUE THREAD

**Issue by hakonamatata** [VSCodeVim/Vim#289]
Hi. having a little trouble with the setup. I have: 

settings.json
{
  "vim.keyboardLayout": "en-US (QWERTY)",
  "vim.insertModeKeyBindings": {
        "jj": "Esc"
    }
}

in the roaming\code\user folder. 

I would like the keyboard to be english when I code (normally I use a norwegian keyboard layout). 
Would also like to map jj to esc. This does not work

**Comment by johnfn** [comment]
@jpoon any ideas?

@hakonamatata I understand if this is too much work, but for the time being you could solve this really simply by copying `CommandEsc` in actions.ts into a new class like `CommandJJ`, and setting `keys = ["j". "j"]`, then building the extension.

**Comment by hakonamatata** [comment]
Thanks, I tried to add the new class: 

```
@RegisterAction
class CommandJJ extends BaseCommand {
  modes = [ModeName.Insert, ModeName.Visual, ModeName.VisualLine];
  keys = ["j"."j"]; // ERROR [ts] identifier expected

  public async exec(position: Position, vimState: VimState): Promise<VimState> {
    if (vimState.currentMode !== ModeName.Visual &&
        vimState.currentMode !== ModeName.VisualLine) {
      vimState.cursorPosition = position.getLeft();
    }

    vimState.currentMode = ModeName.Normal;

    return vimState;
  }
}
```

Like this? I get an where I specify the keys

**Comment by jpoon** [comment]
You actually put that configuration in your `package.json`. You can find that file wherever the plugin is installed:

https://code.visualstudio.com/Docs/extensions/install-extension

For instance, on my mac it's under:

> /Users/jason/.vscode/extensions/vscodevim.vim-0.0.20/package.json

**Comment by jpoon** [comment]
@hakonamatata actually, looks like remapping of commands is no longer supported with the latest version. We'll look at adding it back!

**Comment by jpoon** [comment]
As this is the same as https://github.com/VSCodeVim/Vim/issues/344, I'll close this one in favor of that.
