### ISSUE TITLE
surround emulation fails with underscore "_"

### ISSUE THREAD

**Issue by waltiam** [VSCodeVim/Vim#2893]
The _surround_ emulation fails to remove underscores.

**To Reproduce**
1. move cursor under a word
1. type `ysiw_` to add an underscore around the word
1. type `ds_` to remove the underscore just added

**Expected behavior**
I expected the underscore to be removed, but it is not.

**Environment**

 - Extension (VsCodeVim) version: 0.15.7
 - VSCode version: 1.25.1
 - OS: w10p -1803 - 17134.81

**Additional context**
The adding and removing other characters works.

**Comment by austintraver** [comment]
I'm also having this bug

**Comment by breemts** [comment]
the same bug happens with asterisk (*) 
e.g. `yss*` and than `ds*` 
also doesn't work with change. e.g. `cs*"`
works fine in normal vim

**Comment by rami3l** [comment]
Any news on this rather old issue?  
Encountered the asterisk problem today when editing `markdown`s...

**Comment by chicolucio** [comment]
Same here editing markdown
