### ISSUE TITLE
Pasting from a register in visual mode overwrites the wrong register

### ISSUE THREAD

**Issue by justinr636** [VSCodeVim/Vim#2895]
**Is this a BUG REPORT or FEATURE REQUEST? (choose one):**

BUG REPORT

**What happened:**

Pasting from a register in visual mode puts the highlighted/deleted text in the register you pasted from.

**What did you expect to happen:**

Pasting from a register in visual mode should not change the contents of the register I am pasting from.

**How to reproduce it (as minimally and precisely as possible):**

> <kbd>"</kbd><kbd>a</kbd><kbd>y</kbd><kbd>y</kbd>
> Yank a line (e.g. line no. 1) into register a
> 
> <kbd>2</kbd><kbd>j</kbd><kbd>V</kbd>
> Highlight a different line (e.g. line no. 3) in visual mode
> 
> <kbd>"</kbd><kbd>a</kbd><kbd>p</kbd>
> Paste from register a
> 
> <kbd>"</kbd><kbd>a</kbd><kbd>p</kbd>
> Pasting from register a again will paste the data you overwrote (line no. 3) instead of the original data you copied into the register (line no. 1)
> 
> Register a should be unchanged. The highlighted/deleted content should be placed in the " register.

**Environment:**

Extension (VsCodeVim) version: 0.15.7
VSCode version: 1.25.1
OS version: Ubuntu 18.04 LTS

**Comment by hetmankp** [comment]
I can confirm this is also causing me problems.

**Comment by MrSurly** [comment]
I'm also experiencing this.
