### ISSUE TITLE
Running :reg when clipboard is empty causes an error

### ISSUE THREAD

**Issue by aquova** [VSCodeVim/Vim#2898]
**Issue**
Attempting to view the contents of the registers with `:reg` while the clipboard is empty gives the error:

`Vim: Error: thread 'main' panicked at 'Error: Could not paste from clipboard: Error { repr: Os { code: 0, message: "The operation completed successfully." } }', src\libcore\result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

**To Reproduce**
1. Clear the system clipboard, via whatever means
2. Type `:reg`
3. See error

**Expected behavior**
The usual `:reg` menu should appear, with the `*` and `+` fields simply blank.

**Environment (please complete the following information):**

 - Extension (VsCodeVim) version: 0.15.7
 - VSCode version: 1.25.1
 - OS: Windows 7

**Comment by xconverge** [comment]
I will verify but this looks to potentially be an upstream issue with https://github.com/sindresorhus/clipboardy

**Comment by jpoon** [comment]
Can't repro. I see the menu with blank registers

![untitled](https://user-images.githubusercontent.com/85374/43572868-5743564e-95f5-11e8-9070-269a55c2d13c.png)

**Comment by jpoon** [comment]
Related: https://github.com/sindresorhus/clipboardy/issues/42

**Comment by acicovic** [comment]
FYI, I can reproduce this on Windows 10 and latest VSCode and VSCodeVim versions.

**Comment by xconverge** [comment]
No longer using upstream node module, so this should not be an issue
