### ISSUE TITLE
discussion: goals for first public version

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#29]
@jpoon 

Perhaps we can set a few goals for a first release? Without going into much detail, I propose:

* to implement 10-20 normal mode motions
* to implement 10-20 normal mode actions (among them, `.`)
* to implement 10-20 command line commands (among them, `:normal`)
* to implement support for mappings (at least global and for normal mode)
* to implement support for macros

Let me know what you think. This is by no means complete or maybe even feasible, but I'm just trying to get the ball rolling.

I'm I ignoring stuff like the neovim integration for now. FWIW, I'm not fond of the idea right now. But feel free to comment on that too.

**Comment by adriaanp** [comment]
I barely use any command line commands in other editors, not sure how other people are using it, if it's low maybe we don't need to focus too much on that area?

Otherwise looks like a good plan. :+1:

**Comment by guillermooo** [comment]
> I barely use any command line commands in other editors, not sure how other people are using it, if it's low maybe we don't need to focus too much on that area?

I think we should get `:normal` and `:map` to work well so that we know that our handling of key presses and the handling of the life cycle of commands is flexible enough.

Most of the parsing tools for the command line part is done, so we just have to implement commands and see how the command line mode fits in with the other pieces.

So even though I agree that implementing many `:` commands doesn't need to be a priority, getting a couple of basic ones right should be beneficial.

**Comment by jpoon** [comment]
Likewise :+1: 

Agreement with Neovim. We can reconsider it once we push out this initial version.

**Comment by jpoon** [comment]
How do you feel about shipping out a small version by this Friday (11/27)? I'm hoping that one we ship a small version we can get:

1. More feedback on what to commands to implement
2. Potential more community support

Completed:

* Mode
    * Visual Mode: `v`, `V`
    * Command: `Esc`, `Ctrl+[`
    * Insert: `i`, `I`, `a`, `A`, `o`, `O`
    * Current Mode displayed at the status bar

* Commands
    * `:` - Show command palette
    * Navigation: `h`, `j`, `k`, `l`
    * Indentation: `>>`, `<<`
    * Deletion: `dd`

In-Progress:

* Command Palette
     * Maybe implement a couple of basic commands like `:o`, `:wq`

**Comment by markrendle** [comment]
I'm very excited about getting this extension. You just have to check back through my Twitter timeline to see how often I've badgered the VSCode team about Vim mode support :)

I'd love to contribute to the project, although I can't promise a lot of time, I'm sure I could submit a few PRs for features here and there (along with the inevitable raising of "`c/\)` doesn't work" issues). 

So as well as making an initial release, it would be great if there were a wiki page or CONTRIBUTING.md or something that explains how to work on the package, use it in development/test/whatever mode, that sort of thing.

**Comment by Mpdreamz** [comment]
I can only echo what @markrendle said. Subscribed to this repos and following all conversations over email but would also love to out of lurkmode and help out even a little if I can. A contributing. md would be awesome :+1:

**Comment by guillermooo** [comment]
@jpoon Sure. I suppose we'll have to label it "alpha" or something like that. Also, should we not include a panic button if someone needs to disable the extension for some reason to continue working?

**Comment by jpoon** [comment]
Shall we push out a version with whatever we have in `master`? If you are working on something right now, we can wait.

**Comment by guillermooo** [comment]
@jpoon Go ahead; I won't have anything ready soon.

**Comment by jpoon** [comment]
:tada: Woohoo! Nice work! Shipped [v0.0.1](https://marketplace.visualstudio.com/items/vscodevim.vim)
