### ISSUE TITLE
Map :W to :w

### ISSUE THREAD

**Issue by elentok** [VSCodeVim/Vim#2903]
Hi,

First, thanks for the great work you're doing :+1: 

I was wondering if there's a way to define the `:W` command and map it to `:w`?

As I often don't lift my finger of the Shift key fast enough more than 50% of the time I write :W which fails silently and I don't notice I haven't saved.

In vim I use the following to set this up:

```  
command! W :w
```

Is there a way to do it with vscode-vim?

Thanks,
David.

**Comment by jpoon** [comment]
This should be what you are looking for https://github.com/VSCodeVim/Vim#key-remapping

**Comment by wakeless** [comment]
It really isn't clear in this documentation that this is actually there. These mappings are directly in Normal mode, but this issue is when you specifically type `:W` (note the colon)

**Comment by jpoon** [comment]
Have you tried creating a new `vim.normalModeKeyBindings` mapping before `W` to after `:w`?

**Comment by wakeless** [comment]
Yes:

![image](https://user-images.githubusercontent.com/224373/43879415-53ddb948-9be7-11e8-9e45-522435fb4f52.png)

![image](https://user-images.githubusercontent.com/224373/43879418-582519ce-9be7-11e8-8c9c-5d0441b60fab.png)

**Comment by evans** [comment]
@jpoon I agree with @wakeless. There isn't a clear way to remap `:` `W` to `:w`.

My first thought, doesn't work:

```
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [":", "W"],
      "commands": [":w"]
    },
]
```

A really common occurrence is to fat finger `:W` rather than `:w`. Coming from native vim it's super annoying, so I'd be happy to jump into the code if there isn't currently a supported way to do command mode remapping

**Comment by bsaf** [comment]
Not a direct solution, but I prefer remapping `:` to `;` in Vim – this means I am never pressing shift during save so never accidentally type `:W`.

```
"vim.normalModeKeyBindings": [
  {
     "before": [";"],
     "after": [":"]
   }
]
```

**Comment by xahon** [comment]
@bsaf This is not working at all

**Comment by mxlian** [comment]
Same here. Anyone found a solution yet?

**Comment by marcinbiegun** [comment]
Another solution would be to create another mapping pointing to the same command, e.g.:

```json
"vim.normalModeKeyBindingsNonRecursive": [
  {
    "before": [":","W"],
    "commands": [
      "workbench.action.files.save"
    ]
  }
]
```

Unfortunately this doesn't work.

**Comment by hristodd** [comment]
Anyone has a solution? It's very annoying :)

**Comment by xahon** [comment]
@hristodd sudo apt install vim

**Comment by marcinbiegun** [comment]
@hristodd I've started using `<leader> w` to save files.

```
    "vim.leader": "<space>",
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>","w"],
            "commands": [
              "workbench.action.files.save"
            ]
        },
        {
            "before": ["<leader>","q"],
            "commands": [
              "workbench.action.closeActiveEditor"
            ]
        }
    ]
```

**Comment by tommulkins** [comment]
Maybe this isn't a bug per se but I'm trying to add the command :e to vim.normalModeKeyBindingsNonRecursive and change its behavior from exiting to saving just like :w does.

Exiting in vs code just doesn't work and I often mistype "w" with "e"

I've tried numerous ways to handle this but haven't found a solution yet. Has anyone else tried mapping these keys like this to affect a "save action"?

**Comment by grahamsinger** [comment]
I was struggling with this too and was able to resolve by adding the following
```
 "vim.commandLineModeKeyBindings": [
        {
            "before": ["W"],
            "after": ["w"]
        },
    ]
```
One drawback to note is that it seems like any `W` typed in vim's command line will be changed to a `w` e.g. `/WORD` -> `/wORD` but since I use `"vim.incsearch": true` this doesn't seem to present a problem for me.

I'm using Version: `1.45.1`

**Comment by tommulkins** [comment]
> I was struggling with this too and was able to resolve by adding the following
> 
> ```
>  "vim.commandLineModeKeyBindings": [
>         {
>             "before": ["W"],
>             "after": ["w"]
>         },
>     ]
> ```
> 
> One drawback to note is that it seems like any `W` typed in vim's command line will be changed to a `w` e.g. `/WORD` -> `/wORD` but since I use `"vim.incsearch": true` this doesn't seem to present a problem for me.
> 
> I'm using Version: `1.45.1`

Thanks for this.  Using the following works for me:
```
 "vim.commandLineModeKeyBindings": [
        {
            "before": ["e"],
            "after": ["w"]
        },
    ]
```

**Comment by tommulkins** [comment]
> I was struggling with this too and was able to resolve by adding the following
> 
> ```
>  "vim.commandLineModeKeyBindings": [
>         {
>             "before": ["W"],
>             "after": ["w"]
>         },
>     ]
> ```
> 
> One drawback to note is that it seems like any `W` typed in vim's command line will be changed to a `w` e.g. `/WORD` -> `/wORD` but since I use `"vim.incsearch": true` this doesn't seem to present a problem for me.
> 
> I'm using Version: `1.45.1`

Correction: I had to do the following to achieve what I wanted (using "e" to save a file).

```
"vim.commandLineModeKeyBindings": [
    {
        "before": ["W"],
        "after": ["w"]
    },
    {
        "before": ["e"],
        "after": [""],
        "commands": [
          {
            "command": ":w",
            "args": []
          }
        ]
    },
  ]
```

**Comment by vnetserg** [comment]
For anyone else who is also struggling with this, I think this is the best solution (thanks to @grahamsinger for a starting point)
```
    "vim.commandLineModeKeyBindings": [
        {
            "before": ["W", "<CR>"],
            "after": ["w", "<CR>"]
        },
    ]
```
The only caveat is that you need to type ":W<enter>" fast for it to trigger, if you type ":W" and wait before hitting enter, it won't work. I think it's fine since I tend to type it very fast (hence the problem with failing to release shift).

**Comment by J-Fields** [comment]
Closing in favor of #4454

**Comment by airstrike** [comment]
> Not a direct solution, but I prefer remapping `:` to `;` in Vim – this means I am never pressing shift during save so never accidentally type `:W`.
> 
> ```
> "vim.normalModeKeyBindings": [
>   {
>      "before": [";"],
>      "after": [":"]
>    }
> ]
> ```

Sightly improved:

    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [":"],
            "after": [";"]
        },
        {
            "before": [";"],
            "after": [":"]
        }
    ],
