### ISSUE TITLE
Expand selection with inner tag selection command

### ISSUE THREAD

**Issue by eddiemf** [VSCodeVim/Vim#2907]
Hello everyone!

I come from Sublime Vintage mode context, and I was very used to type `vit` to select the inner content of a tag, which works in VSCode Vim, but when I typed `it` again and again in sublime it would keep expanding the selection up, which doesn't happen in VSCode Vim. 

Is there anyway to achieve this behavior? 

Thanks in advance!

**Comment by xconverge** [comment]
```af``` should achieve what you want, you can remap ```it``` to ```af``` in visual mode if you want as well

https://github.com/VSCodeVim/Vim#-vscodevim-tricks

**Comment by eddiemf** [comment]
Hello, @xconverge!

Actually it didn't really work, sometimes it goes crazy and selects a huge chunk of tags (maybe when there's php together), and with only HTML it simply does nothing. I've tested with the following snippet:

```
<div>
  <ul>
    <li>
      <p>Lorem ipsum, dolor sit amet orrupti debitis error!</p>
    </li>
  </ul>
</div> 
```
Hitting `vit` selects all the content inside the tag the cursor is in. Hitting `vaf` or `vit` + `af` does nothing at all :(

Also thanks for the link, didn't know about that one, will be very useful as I'm not the most vim power user.
