### ISSUE TITLE
Cursor jumps to different columns when moving vertically when Vim extension is enabled.

### ISSUE THREAD

**Issue by Maelstorm1973** [VSCodeVim/Vim#2913]
Issue Type: <b>Bug</b>

Extension problem with Vim 0.15.7.  When moving through rows of code which contain tabulated values, such as a large number of constants, the cursor jumps to different columns when moving line to line.  The lines have differing number of tabs.  Highly annoying since real vim in Unix doesn't do that.

Extension version: 0.15.7
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4018)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.97GB (12.17GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ctidd** [comment]
This is an issue I'm also interested in and occasionally check in to see the status of. The behavior impacts me most when writing Go, which by convention forces tab indentation.

To add more detail for the maintainers, this behavior is also mentioned in #2458. It's exhibited when moving up/down between lines indented with tab characters instead of spaces.

**Comment by Maelstorm1973** [comment]
Yeah.  I think I know what the problem is.  I have my tabs set to 4 spaces instead of 8.  What I think is happening is that Vim does not take that into account when positioning the cursor on the next line.  It seems to think of a tab as just another character.  So if the lines have differing numbers of tabs, then the cursor jumps around when navigating between lines.

**Comment by J-Fields** [comment]
Closing in favor of #3796
