### ISSUE TITLE
Throw away the mouse

### ISSUE THREAD

**Issue by trev-dev** [VSCodeVim/Vim#2922]
I left VSCode a long while ago to enjoy learning Vim. Coming back to VSCode lately, I find this plugin indispensable.

# So thank you!!

This may be a redundant request. As a matter of fact, it may already be doable with VSCode keybinds, but if it isn't, I'd like to be able to toss the mouse out. So far this means:

- Being able to use CTRL-W to move in _and out of_ the file explorer, also, in _and out_ of the terminal/problems drawer using something like CTRL-W l/CTRL-W k
- Being able to create (touch), delete, move and copy files from the explorer (nerd-tree like features)
- Being able to switch open files as though I were switching buffers (:bn :bp :b<n>) and possibly keybind these to a leader command.
- All the other things that I would have to grab a mouse for in VSCode that I wouldn't have to in Vim/Emacs. I'm sure I'll think of them later.

I appreciate your time!

I'll be exploring the native VSCode keybindings until then. Useful links/suggestions are most welcome.

**Comment by Ebuall** [comment]
There is no problem in switching between files, but it's vscode specific build in hotkey (ctrl+tab, ctrl+p should do the job).

On the other hand I found annoying, that extension uses notifications, you can't get rid of without a mouse. For example "not implemented" error or if you use ":e" to create a file it shows notifications with button "create file", that only reachable with a mouse.

**Comment by doubleagent** [comment]
I created these settings over the weekend and you may find them a good starting point.

https://github.com/doubleagent/vscode-settings

In particular keybindings.json has a number of things you're asking about (although I now see that I need to revisit the `"when"` clauses on virtually all of them - they need to be more restrictive).

**Comment by trev-dev** [comment]
Closing issue as it's a suggestion that we can work around on our own (more or less). Thanks for the input people!
