### ISSUE TITLE
Arrow key bindings not working with insertModeKeyBindings

### ISSUE THREAD

**Issue by karlhorky** [VSCodeVim/Vim#2924]
**Describe the bug**

The configuration for navigation with arrow keys across word wrapped lines from https://github.com/VSCodeVim/Vim/issues/2403#issuecomment-384317608 no longer works.

Bonus: The configuration does work with a separate, unrelated configuration.

**To Reproduce**

1. Install the plugin
2. Enable word wrapping (`"editor.wordWrap": "on"`)
3. Configure using the config in `broken.json` below
4. Notice that the <kbd>up</kbd> and <kbd>down</kbd> keys skip text past the wrap on  word wrapped lines (notice that both `ctrl+o` and `<C-o>` do not work)
5. Bonus: Configure using the config in `working.json` below
6. Bonus: Notice that the <kbd>up</kbd> and <kbd>down</kbd> keys navigate to every line, even text on word wrapped lines.

**broken.json**
```
{
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "down",
      ],
      "after": [
        "<C-o>",
        "g",
        "j"
      ]
    },
    {
      "before": [
        "up"
      ],
      "after": [
        "ctrl+o",
        "g",
        "k"
      ]
    }
  ]
}
```

**working.json**
```
{
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "j"
      ],
      "after": [
        "<Esc>"
      ]
    },
    {
      "before": [
        "down"
      ],
      "after": [
        "<C-o>",
        "g",
        "j"
      ]
    },
    {
      "before": [
        "up"
      ],
      "after": [
        "ctrl+o",
        "g",
        "k"
      ]
    }
  ]
}
```

**Expected behavior**

The configuration should work in both cases (not only with the extra <kbd>j</kbd> => <kbd>Esc</kbd> configuration key).

**Logs**

Broken:

```
Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] debug: Extension: activating vscodevim.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] debug: Extension: registering event handlers.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] debug: ModeHandler: handling key=<ExtensionEnable>.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=i.
2console.ts:136 [Extension Host] debug: ModeHandler: handling key=<up>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
2console.ts:136 [Extension Host] debug: ModeHandler: handling key=<up>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<up>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<up>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
2console.ts:136 [Extension Host] debug: ModeHandler: handling key=<up>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<down>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<down>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
```

Working:
```
Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] debug: Extension: activating vscodevim.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] debug: Extension: registering event handlers.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] debug: ModeHandler: handling key=<ExtensionEnable>.
shell.ts:482 [Violation] 'resize' handler took 196ms
[Violation] Forced reflow while executing JavaScript took 37ms
console.ts:136 [Extension Host] debug: ModeHandler: handling key=i.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<down>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=j. after=<Esc>. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. match found. before=<down>. after=<C-o>,g,j. command=undefined.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<C-o>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=j. after=<Esc>. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: ModeHandler: handling key=g.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=j.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<down>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=j. after=<Esc>. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. match found. before=<down>. after=<C-o>,g,j. command=undefined.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<C-o>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=j. after=<Esc>. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: ModeHandler: handling key=g.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=j.
wordHighlighter.ts:300 [Violation] 'setTimeout' handler took 82ms
mouseHandler.ts:94 [Violation] Handling of 'mousewheel' input event was delayed for 122 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.
[Violation] 'setTimeout' handler took 62ms
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<up>.
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=j. after=<Esc>. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<down>. after=<C-o>,g,j. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. before=<up>. after=<C-o>,g,k. 
console.ts:136 [Extension Host] debug: Remapper: insertModeKeyBindings. match found. before=<up>. after=<C-o>,g,k. command=undefined.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=<C-o>.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=g.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=k.
```

**Environment (please complete the following information):**

- Extension Name: vim
- Extension Version: 0.15.7
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.25.1

**Comment by karlhorky** [comment]
Note: the configuration also does not work with `<up>` and `<down>`, which cause other issues (such as also triggering when one types <kbd><</kbd><kbd>d</kbd><kbd>o</kbd><kbd>w</kbd><kbd>n</kbd><kbd>></kbd> in short succession)

**Comment by karlhorky** [comment]
cc @jpoon

**Comment by xmbhasin** [comment]
I reworked the remapper so that it more accurately matches keys to possible remaps (see xmbhasin/Vim@f3e4311). However, it seems to have revealed a deeper issue with the timing of the current mode change and the processing of remapped commands. With your remappings above for example, the <C-o> brings us out of insert mode but then the g and k keys continue to be processed near infinitely and will print a large string of `gk`s or `gj`s. Changing the remapping to <Esc> and then `gk` or `gj` will cause the editor to move lines up or down multiple times. 

This problem does not seem to present when using non-recursive bindings however. I'm not sure then how to proceed: should we remove recursive keybindings for insert mode and other modes if the same problem exists there when switching between modes mid remap, or should chase this bug futher?

**Comment by metasong** [comment]
the easy workaround is uing the default <kbd>up</kbd> <kbd>down</kbd> of vscode's shortcut setting( <kbd> ctrl+k+s </kbd> ), it is overrided by vim after install `the vim extension`:
```
  {
    "key": "down",
    "command": "cursorDown",
    "when": "textInputFocus"
  },
  {
    "key": "up",
    "command": "cursorUp",
    "when": "textInputFocus"
  },
```

**Comment by karlhorky** [comment]
Thanks for the tip @metasong, I'll give that a shot!

**Comment by karlhorky** [comment]
Cool, looks like it works @metasong! Documented the full list of working settings here: https://github.com/VSCodeVim/Vim/issues/2403#issuecomment-433620449

**Comment by karlhorky** [comment]
Thanks for the tip @metasong. I've given it a shot, but it has a critical problem with it:

It escapes from autosuggest boxes. Here's a gif:

![kapture 2019-01-11 at 13 25 56](https://user-images.githubusercontent.com/1935696/51033806-d8f0f280-15a4-11e9-9db6-d55e708fbab9.gif)

**Comment by karlhorky** [comment]
@xmbhasin I suppose the status of your work on this issue hasn't changed, right? Your commits reworked the remapper, but revealed another deeper issue? And then you had this open question.

>  I'm not sure then how to proceed: should we remove recursive keybindings for insert mode and other modes if the same problem exists there when switching between modes mid remap, or should we chase this bug further?

Can a maintainer weigh in here? Maybe @jpoon?

**Comment by karlhorky** [comment]
I think I may have come up with a fixed version of @metasong's keybindings, based on the `when` condition from the [extension keybindings](https://github.com/VSCodeVim/Vim/blob/6805ae4311e322e9d3ef0ca07a2811ee411944b4/package.json#L100-L109).

It looks like this:

```json
  {
    "key": "up",
    "command": "cursorUp",
    "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  },
  {
    "key": "down",
    "command": "cursorDown",
    "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
  }
```

This doesn't need any changes to settings.

I will start using this and see if there are any other problems (including performance issues) with it.

**Comment by karlhorky** [comment]
@jpoon this is indeed now working! Will close this issue.

For everyone else, the [original method](https://github.com/VSCodeVim/Vim/issues/2924#issue-346230214) of setting `vim.insertModeKeyBindings` with `<C-o>`, `g`,`j` is very slow:

![Kapture 2019-03-25 at 10 37 14](https://user-images.githubusercontent.com/1935696/54909488-a2135300-4eea-11e9-90d3-721c0c630ee0.gif)

Compare this to the speed of [rebinding the keybindings](https://github.com/VSCodeVim/Vim/issues/2924#issuecomment-456365495), which is as fast as VS Code normally is:

![Kapture 2019-03-25 at 10 38 38](https://user-images.githubusercontent.com/1935696/54909566-d25af180-4eea-11e9-827f-928b68fb0143.gif)

**Comment by yasirroni** [comment]
Okay, here is the step by step solution folks:

1. Open vscode's shortcut setting using `ctrl+k+s`.
2. In the search bar (In my case, it brings UI with search bar), enter `cursorUp`.
3. Righ click on `cursorUp` row, select the `Change When Expression`.
4. Change to `editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible`.
5. In the search bar (In my case, it brings UI with search bar), enter `cursorDown`.
6. Righ click on `cursorDown` row, select the `Change When Expression`.
7. Change to `editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible`.

**Comment by leoauri** [comment]
In case, like for me, vscode doesn't allow you to edit the when expression of a system keybinding, you can insert the following in `keybindings.json`:
```
    {
        "key": "up",
        "command": "cursorUp",
        "when": "textInputFocus || editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
    },
    {
        "key": "down",
        "command": "cursorDown",
        "when": "textInputFocus || editorTextFocus && vim.active && !inDebugRepl && vim.mode == 'Insert' && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
    }
```
