### ISSUE TITLE
QUESTION:  any plans to make an extension for Visual Studio IDE?

### ISSUE THREAD

**Issue by kimfucious** [VSCodeVim/Vim#2929]
Visual Studio IDE has always been seriously lacking vim key bindings.

The current extensions out there pale in comparison to the work you've done with VSCodeVim.

VSCodeVim is awesome!

Any plans on making an extension for Visual Studio?

**Comment by jpoon** [comment]
Thank you for the positive comments.

Visual Studio already has a great vim extension in https://marketplace.visualstudio.com/items?itemName=JaredParMSFT.VsVim. 

This extension is primarily for Visual Studio Code as we are heavily reliant on the extension APIs provided by Visual Studio Code.
