### ISSUE TITLE
% should match on strings & chars

### ISSUE THREAD

**Issue by doubleagent** [VSCodeVim/Vim#2935]
ie single quotes ('), double quotes ("), and perhaps even ticks (`)

**Comment by axs221** [comment]
What is your use case for matching on strings? Vim doesn't do that by default, just curious.

https://stackoverflow.com/questions/1444054/in-vim-is-there-a-plugin-to-use-to-match-the-corresponding-double-quote

You might be aware of the other options for jumping to those characters:

* `ci"` for cutting the contents inside the quotes
* `f"` or `F"` for jumping to next/previous double quote
* `/"` or `?"` obviously for searching for double quotes if on a different line
* `\\s"` for using vim-easymotion (if enabled) to jump to double quotes anywhere on screen
* `cs"'` (vim-surround) for changing from double quotes to single quotes.

**Comment by doubleagent** [comment]
It seems there are already other options for this.
