### ISSUE TITLE
Visual line causes named register to be overwritten with selection on paste

### ISSUE THREAD

**Issue by samkhal** [VSCodeVim/Vim#2939]
**Describe the bug**
When pasting from a named register, the selection is sometimes copied into that register. This seems to happen when the original selection used visual line mode.

**To Reproduce**

Start with the file
```
aa
bb
cc
```
With the cursor on the first character in normal mode.

Type `Vj"ayjjve"ap"ap`.

The result is
```
aa
bb

acca
bb
```
Register "a" now contains "cc".

**Expected behavior**
Output in vim:
```
aa
bb

aa
aa
bb
bb
```
Register "a" still contains "aa\nbb"

**Environment (please complete the following information):**

- Extension Name: vim
- Extension Version: 0.15.7
- OS Version: Linux x64 4.15.0-29-generic
- VSCode version: 1.25.1

**Comment by J-Fields** [comment]
Closing in favor of #2895
