### ISSUE TITLE
Investigate reducing startup activation time

### ISSUE THREAD

**Issue by zhaotongxue** [VSCodeVim/Vim#2947]
- Extension Name: vim
- Extension Version: 0.15.7
- OS Version: Windows_NT x64 10.0.15063
- VSCode version: 1.25.1

 We have written the needed data into your clipboard. Please paste:

![image](https://user-images.githubusercontent.com/6638644/43887188-9fc8efe0-9bf0-11e8-94d0-4932fe5fd658.png)
why soooooooooooooooooooo slow？？？！！！！

**Comment by chan-dev** [comment]
any updates on this one. Mine was more or less around 14499ms startup time.
