### ISSUE TITLE
VSCodeVim airline affecting color scheme

### ISSUE THREAD

**Issue by haveanicedavid** [VSCodeVim/Vim#2948]
**Describe the bug**
Airline color changes to the lower information bar happen regardless of configuration settings. `"vim.statusBarColorControl": false,` just locks the 'normal mode' color. 

This prevents information from being shown on certain themes (my screenshot is of the Material theme)

**Expected behavior**
Color scheme should be unaffected if airline setting is disabled

**Screenshots**
<img width="372" alt="screenshot 2018-08-09 14 36 17" src="https://user-images.githubusercontent.com/9052511/43924496-0b4cc796-9be2-11e8-97be-e53a455f8e37.png">

**Comment by jcraven-worksight** [comment]
I was seeing this too. Copying `"vim.statusBarColorControl": false` into my user settings fixes it.

**Comment by jpoon** [comment]
Can you share your configuration?

**Comment by haveanicedavid** [comment]
I just realized that something must have edited my config. The following was added under `workbench.colorCustomizations`: 
```
    "statusBar.background": "#005f5f",
    "statusBar.noFolderBackground": "#005f5f",
    "statusBar.debuggingBackground": "#005f5f"
```

Removing them from my config fixed the issue. Closing, thanks!

**Comment by Kynolin** [comment]
There's a warning about this feature in the main readme about how it functions and the resulting performance impact.

> ⚠️Experimental feature. Due to VSCode API limitations, this function modifies settings.json in the workspace resulting in latency and a constant changing diff in your working directory (see issue #2124).

If you enable vim.statusBarColorControl and save your settings file, you can observe the status bar color settings being added and altered as you switch between normal/insert/visual. When you disable vim.statusBarColorControl, the configuration lines do not get removed automatically which results in the unexpected status bar colors you experienced. I went through the same thing when I disabled this feature after trying it out myself.

**Comment by jpoon** [comment]
That is correct, we override vscode's statusbar configs as you switch modes to change the color of the status bar. We currently are not deleting those configurations as it's hard for us (the extension) to determine whether those were configurations that the extension configured vs. settings that the user supplied.
