### ISSUE TITLE
Can't bind key sequences (multiple leaders?) to actions in Normal Mode?

### ISSUE THREAD

**Issue by spiralsam** [VSCodeVim/Vim#2955]
Am I missing something? From the documentation, It's possible to bind jj to <Esc> in insert mode:
```
  "vim.insertModeKeyBindings": [
    {
      "before": ["j", "j"],
      "after": ["<Esc>"]
    }
  ],
```

But trying to bind jj to something in normal mode doesn't work:

```
  "vim.normalModeKeyBindings": [
    {
      "before": ["j", "j"],
      "after": ["w"]
    }
  ]
```
In VIM I usually bind numerous arbitrary characters as "leaders" like so (a and b in this random example)
```
noremap a <Nop>
noremap aa w
noremap ab b
...
noremap b <Nop>
noremap ba w
noremap bb b
...
```
But  as far as I can tell, VSCodeVim only allows one global leader set as "vim.leader". For the life of me, I couldn't get this binding capability to work for Normal mode.

**Comment by mystic01** [comment]
It's the same with 'h', 'h':
```
# OK
"vim.insertModeKeyBindings": [
    {
        "before": [
            "h",
            "h"
        ],
        "after": [
            "^"
        ]
    },
],
```
The following don't work.
```
# FAILED
"vim.normalModeKeyBindings": [
    {
        "before": [
            "h",
            "h"
        ],
        "after": [
            "^"
        ]
    },
]
```
```
# FAILED
"vim.normalModeKeyBindings": [
    {
        "before": [
            "h",
            "c"
        ],
        "after": [
            "^"
        ]
    },
]
```

However, 'g' 'g' works.
```
# OK
"vim.normalModeKeyBindings": [
    {
        "before": [
            "g",
            "g"
        ],
        "after": [
            "^"
        ]
    },
]
```

**Comment by mystic01** [comment]
For this issue, I traced the code. The basic reason is 'j' & 'h' are move command. They don't need to 'wait' the next key input. otherwise, the move motion would be slow. I also found a workaround. If you don't need some move command, just modify the code in "...\.vscode\extensions\vscodevim.vim-0.16.12\out\src\actions\motion.js"

```
let MoveDown = class MoveDown extends BaseMovement {
    constructor() {
        super(...arguments);
        // this.keys = ['j'];
        this.keys = ['j', 'j'];
        this.doesntChangeDesiredColumn = true;
    }
...
```
After this modification, when you type 'j', vim would wait next input key. so your new key mapping will work.

**Comment by sqlkoala** [comment]
> For this issue, I traced the code
"....vscode\extensions\vscodevim.vim-0.16.12\out\src\actions\motion.js"
> After this modification, when you type 'j', vim would wait next input key. so your new key mapping will work.

Hi @mystic01 ,
I have a similar situation (a mapping problem that I want to solve by editing the code). I did my changes to motion.js? That alone does not work, do need to build/compile the extension? What did you do? Thanks.
