### ISSUE TITLE
save (:w or :wq) with SSHFS and LiveShare guest don't work properly

### ISSUE THREAD

**Issue by kangzhang** [VSCodeVim/Vim#2956]
I'm using VS Code with a remote workspace (via an extension that integrates with our dev-server) and saving files with ":w" always gives me error. It seems our private extension overloaded the "save" action in VS Code but the VIM extension is bypassing the editor's save API. 

**Describe the solution you'd like**
We can have an additional flag in settings to bypass the local file write. A check of the setting can be added at here: https://github.com/VSCodeVim/Vim/blob/82abec31c996b381a4a544932a9cbaa89e80ea3b/src/cmd_line/commands/write.ts#L52

**Comment by jpoon** [comment]
Contributions are welcome.

**Comment by zhuzisheng** [comment]
Is it safe to add the condition as below?

if (vimState.editor.document.isUntitled || vimState.editor.document.uri.scheme !== 'file')  {
  .....
}

I make this change in my local version.

**Comment by zhuzisheng** [comment]
there is another issue when editing remote files.
If the file is created remotely, edited and saved, the file is in dos format.
this may cause issues when the remote system is linux.

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/3304#issue-394823228 has a good repro

**Comment by zhuzisheng** [comment]
Hi jpoon,

Is it ok to remove fs module's file access checking before saving the file?
The fs module can only support "file" scheme/uri, which is in its documents.
