### ISSUE TITLE
Moving the cursor to somewhere outside of the viewport should center the cursor vertically

### ISSUE THREAD

**Issue by hhu94** [VSCodeVim/Vim#2960]
**Describe the bug**
A couple of examples of the situation described in the title:
- When jumping to a mark outside of the viewport, the cursor line is placed at either the first or second from last line in the viewport.
- When searching for a string with `/` and the next occurrence is outside of the viewport, the cursor line is placed at either the first or second from last line in the viewport.

**To Reproduce**

1.  Set a mark at line `x` in a file with `ma`.
2.  Navigate to another part of the file such that the line `x` is outside of the viewport.
3.  Jump to the mark with `'a`.

**Expected behavior**
The cursor line `x` should be vertically centered.

**Screenshots**
![marks](https://user-images.githubusercontent.com/7145349/44133289-e756d1b6-a013-11e8-837b-f075c778ceac.gif)

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 0.16.0
- VSCode version: 1.25.1
- OS: Windows 10

**Comment by naseer** [comment]
Checking if there's an update or a workaround for this bug.

**Comment by naseer** [comment]
Looks like `zz` is the binding I was looking for :)
Still would be nice if the cursor was centered by default after the search.

**Comment by jwmann** [comment]
@naseer I'm not sure what `zz` is supposed to do but in Vim the `M` key will move the cursor to the vertical middle of the screen.

**Comment by J-Fields** [comment]
Digging into this a bit more. In vim, if you put the cursor at the top of the viewport with `H` (`scrolloff=0`), `14k` does not center the viewport around the new cursor position, but `15k` does.
It takes `18j` at the bottom to center, but I think that's because of the status line, etc.

**Comment by pnalchajian** [comment]
The above commit (4434) seems to behave unexpectedly around heavily folded code. If I'm traversing lines (simple cursor movements like jk) in a non-folded section of code, the cursor works just fine. When I'm doing the same amidst many folds, cursor navigation behaves almost like a scrollOffset is set (keeping the cursor in the center always).

**Comment by J-Fields** [comment]
@pnalchajian Please file a separate issue

**Comment by yar00001** [comment]
Same issue that @pnalchajian mentioned. Not sure if he has created a new issue for this or not.
