### ISSUE TITLE
yank+paste partial line will add a line feed

### ISSUE THREAD

**Issue by felipeek** [VSCodeVim/Vim#2961]
**Describe the bug**
Whenever I yank (y) and paste (p) a partial line, the result will come with undesirable line feeds

**To Reproduce**

1. Use CTRL+V to go to VISUAL BLOCK mode
2. Select part of the line, like two or three words in the middle of the line
3. Yank (press y)
4. Press p to paste

**Expected behavior**
The pasted text should match exactly what was copied - in this case with no line feeds. Instead, line feeds are added

**Screenshots**
![image](https://user-images.githubusercontent.com/3253502/44184921-b935cb00-a0e7-11e8-8925-115e9f7605ff.png)

Screenshot shows what happens when the text "r32 r" is selected with VISUAL BLOCK, and then y and p are pressed. In the left, the result using the plugin and in the right the result using vim itself.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.0
- VSCode version: 1.26.0
- OS: Arch Linux

**Additional context**

**Comment by jpcampbell** [comment]
This is probably one of the few issues that I run into daily.  It should act like the "D" command, but with the visual part being cut only.   And then it should paste within the same line.
