### ISSUE TITLE
Open File with :e deletes file content

### ISSUE THREAD

**Issue by micdahl** [VSCodeVim/Vim#2963]
**Describe the bug**
When I open an existing file with `:e filename`, the content of the existing file is removed.

**To Reproduce**

1.  Open Folder with at least 2 existing files.
2.  Open one file through clicking on it.
3.  Open an other file with `:e filename`.
4.  Get editor window without content and existing file is overwritten without content.

**Expected behavior**
Existing file is opened without removing its content.

**Environment:**

- Extension (VsCodeVim) version: 0.16.0
- VSCode version: 1.26
- OS: macOS High Sierra (10.13.6)

**Additional context**
I think this is a very serious issue, as it causes data loss.

May originate from [this commit](https://github.com/VSCodeVim/Vim/commit/dc49c05f5bf636d42341d82f8f56036d6b79f8b8)? The bug must be relative new, as I haven't observed this behavior in the past.

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/pull/2969
