### ISSUE TITLE
Mapping ciw to cw does not work as expected

### ISSUE THREAD

**Issue by tom-rb** [VSCodeVim/Vim#2975]
**Description**

Basically I want:

```
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["c","w"],
            "after": ["c", "i", "w"]
        },
        {
            "before": ["v","w"],
            "after": ["v", "i", "w"]
        },
]
```

What happens is that, after pressing `cw`, the sequence of keys sent is `cciw` and I end up with a whole line being changed (cc) and then the characters iw are inserted.

After pressing `vw` it just ignores mapping and behave as `vw` instead of the desired `viw`.

**To Reproduce**

1.  Configure the mapping as indicated in the description above
2.  In normal mode, trigger `cw`
4.  See error: whole line substituted by iw.

**Expected behavior**
After pressing `cw` I expected that only the word under cursor is deleted and insert mode is activated.

**Environment**

- Extension Name: vim
- Extension Version: 0.16.0
- OS Version: Linux x64 4.4.0-133-generic
- VSCode version: 1.26.1

**Workaround**

By using the following mapping I can get the expected behavior for `cw`:
```
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["c","w"],
            "after": ["i", "w"]
        },
]
```
I can't use the same workaround for mapping `vw` to `viw`.

**Comment by jpoon** [comment]
What's the output when trying https://github.com/VSCodeVim/Vim#debugging-remappings?

**Comment by tom-rb** [comment]
For config `"vim.normalModeKeyBindingsNonRecursive": [ { "before": ["c","w"], "after": ["c", "i", "w"] } ]`:

```
console.ts:136 [Extension Host] debug: ModeHandler: handling key=c.
console.ts:136 [Extension Host] debug: Remapper: normalModeKeyBindingsNonRecursive. before=c,w. after=c,i,w. 
console.ts:136 [Extension Host] debug: ModeHandler: handling key=w.
console.ts:136 [Extension Host] debug: Remapper: normalModeKeyBindingsNonRecursive. before=c,w. after=c,i,w. 
console.ts:136 [Extension Host] debug: Remapper: normalModeKeyBindingsNonRecursive. match found. before=c,w. after=c,i,w. command=undefined.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=c.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=i.
console.ts:136 [Extension Host] debug: ModeHandler: handling key=w.
```

**Comment by tom-rb** [comment]
Besides the workaround I've mentioned, nope.

**Comment by Spirarel** [comment]
Bummer. Thanks anyway
