### ISSUE TITLE
v/

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#298]

**Comment by jpoon** [comment]
What is `v/`?

**Comment by johnfn** [comment]
Doing a slash search in visual mode should select till the first match.

**Comment by jpoon** [comment]
I know this issue came first, but this https://github.com/VSCodeVim/Vim/issues/1520 is a lot more descriptive. Let's use that to track.

**Comment by johnfn** [comment]
Makes sense. This is basically impossible to search. It's from the old days when the issues were mainly reminders to myself. 😄
