### ISSUE TITLE
A standalone status bar for vim

### ISSUE THREAD

**Issue by intijk** [VSCodeVim/Vim#2981]
**Is your feature request related to a problem? Please describe.**
Status bar for existed vscode already too crowded, hardly to check vim status bar within crowded characters.

**Describe the solution you'd like**
Have a independent status bar for vim is a better choice. Atom did it correct and good, and allow to implement better features like status bar text and animation.

**Describe alternatives you've considered**
I tried to turn off other plugin's status bar display, but I don't have this option, the only choice is to remove other plugins, I don't want to do that.

**Comment by jpoon** [comment]
At this point, VSCode only exposes APIs to add a new item to the existing status bar (https://code.visualstudio.com/api/references/vscode-api#StatusBarItem). In order to support this, please file an issue against VS Code for the ability to add a new status bar

**Comment by J-Fields** [comment]
Yeah, this is not possible with the current API, and I suspect it won't be any time soon. We'll support a separate status bar if VSCode ever offers this as a contribution point.
