### ISSUE TITLE
`da{` misbehavior

### ISSUE THREAD

**Issue by luiszun** [VSCodeVim/Vim#2982]
When using delete a block, with braces "da{" and the cursor is not on the opening brace, but a tab or space before, it will delete 

To reproduce:
- Get some code that includes curly braces.
- Go to the line of an opening one
- Go a few spaces back
- Execute "da{" in normal mode

Expected (Expected this, even if the cursor was few spaces off like the next gif):

![vimexpected](https://user-images.githubusercontent.com/12754867/44493786-33051180-a61e-11e8-9e4e-05cf4b83f912.gif)

Actual:
![vimactual](https://user-images.githubusercontent.com/12754867/44493822-56c85780-a61e-11e8-8108-0d5695d6fc98.gif)

**Comment by luiszun** [comment]
Would you accept a PR for this?

**Comment by J-Fields** [comment]
@luiszun Yes, I believe so. Seems behavior should be "if the opening inner brace is on the same line, separated by only whitespace, use the inner brace".
