### ISSUE TITLE
`:vsp file_name` cannot open file_name, although this file does exist

### ISSUE THREAD

**Issue by TriLoo** [VSCodeVim/Vim#2983]
**Describe the bug**

When I used `:vsp file_name` to open two files vertically, the **vim *Extension)** output that my  `file_name` does not exist. However, this file does exist and is in the same folder with the opened file.

BTW, I have tryied to reinstall my vscode or reinstall the `vim` extension, but doesn't work. Any advices ?

**To Reproduce**

I don't know how to reproduce this error in other computers.

**Expected behavior**

I want to use `:vsp file` to open my second file vertically in vim mode.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v0.16.0
- VSCode version: 1.26.1
- OS: Ubuntu 14.04

**Comment by jpoon** [comment]
Fixed with https://github.com/VSCodeVim/Vim/pull/2969, but not yet released.
