### ISSUE TITLE
When closing a window with `:q` VS Code now selects the tab "before" the one you were previously on

### ISSUE THREAD

**Issue by ohjames** [VSCodeVim/Vim#2984]
1. Load 3 files, each in its own tab.
2. Move to the second tab, then the third tab.
3. Type `:q<enter>` to close the tab.

I would now expect the second tab to be selected, and this worked up until recently. Now the first tab will be selected instead. It always chooses the tab "one to the left of" the tab it should be selecting.

**Comment by MirKml** [comment]
My common use case from big Visual Studio vsvim extension, PHPStorm etc:
I'm inside tab with file1.
go to definition -> 'gd' -> opens new tab with line with definition
\:q for close tab with definition
original opened tab - with file1 is opened.

This doesn't work in vscodevim, after \:q for window with definition, other (maybe previously selected) tab is opened. Very annoying.

Maybe is related to previously closed bug #917.

**Comment by ohjames** [comment]
Weirdly it does select the correct tab immediately after closing, but within a few millisecond it switches to the tab to the left. Living with this for a few months is starting to get really annoying haha. I really miss vim, it couldn't do what VS Code can but I only hit two bugs in a decade. With VS Code you discover new bugs every day.

**Comment by ohjames** [comment]
Deleting this line of code fixes the bug:

https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/commands/quit.ts#L48

Not sure what it's supposed to be doing, but it surely can't be worth the consequences it's causing.
