### ISSUE TITLE
Is there any way or could a way be added to conside _ a word break?

### ISSUE THREAD

**Issue by vlurgio** [VSCodeVim/Vim#2985]
**Is your feature request related to a problem? Please describe.**
So when you do something like jump by word with w or change a word with cw if you have a variable name like my_first_variable it erases the entire word instead of just my or first for example. Whereas something like my-first-word does not. Is there any way to add an option to consider _ a word break?

**Comment by jpoon** [comment]
How is something like this generally configured in vanilla vim?

**Comment by vlurgio** [comment]
It seems you use ```bash set iskeyword-=_``` in your .vimrc

**Comment by vlurgio** [comment]
Theres also a plugin called camelcasemotion which allows you to treat camelcase and underscores as word boundaries which would be even better.

**Comment by jpoon** [comment]
We support `iskeyword`. Please also see this: https://github.com/VSCodeVim/Vim/pull/3305

**Comment by pkrefta** [comment]
@jpoon Shall I report that `iskeyword` is ignored in easymotion in separate issue ?
