### ISSUE TITLE
word/line highlight when yy or shift + * is pressed

### ISSUE THREAD

**Issue by jasjuang** [VSCodeVim/Vim#2991]
**Is your feature request related to a problem? Please describe.**
Currently when I try to yank a word or line, there is no visual cue on the editor showing that the word/line is being yanked. Same as when I am trying to search a word with `shift+*`. It would be nice to have some sort of visual cue when these actions are performed.

I understand that in vanilla vim there isn't any visual cue either when the above actions are performed, but as someone coming from sublime + vintageous and contemplating switching the VSCode, this nice feature was available in sublime + vintageous (they did it with one rectangle box flash around the word/line) and it will be a huge plus to have this in VSCode.

**Comment by nomad-software** [comment]
Please make this optional. I would prefer to not see any unnecessary highlighting.
