### ISSUE TITLE
Visual mode doesn't start selection from intended location

### ISSUE THREAD

**Issue by irvall** [VSCodeVim/Vim#2995]
**Describe the bug**
Selection of text in visual mode doesn't start at the end of current line despite using `$` symbol.

**To Reproduce**

Copy paste some lines of code to select, e.g.:

```
let Answer =
    input
    |> Array.groupBy id
```

Go to the last line, click `$` + `v` and use navigation buttons to select all three lines.

**Expected behavior**
Selection starts after "i" instead of "d" in `id` which it should.

**Screenshots**

![Bug](https://i.imgur.com/W3cKVhp.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.0
- VSCode version: 1.26.1
- OS: macOS High Sierra 10.13.6

**Comment by J-Fields** [comment]
Fixed by https://github.com/VSCodeVim/Vim/commit/b5333d18edab6ac5ec76fdcfbefa7d9451d9d282
