### ISSUE TITLE
String replacement command shows wrong message upon confirmation

### ISSUE THREAD

**Issue by iFailatGitHub** [VSCodeVim/Vim#2996]
**Describe the bug**
Whenever I use the string replacement command (%s) with the confirmation option (c), it shows the string to replace instead of the replacement string.

**To Reproduce**

1. Create a new file with foo within the contents
2. Type `:%s/foo/bar/c` under Vim, then hit enter
![command](https://user-images.githubusercontent.com/16273400/44638857-96f75380-a9eb-11e8-992f-804256cc27c7.png)
3. Get the wrong confirmation message
![incorrect message](https://user-images.githubusercontent.com/16273400/44638897-ad9daa80-a9eb-11e8-8c59-b999ea304118.png)

**Expected behavior**
The command is supposed to show "Replace with bar..." (the replacement string) instead of "Replace with foo..." (the string to replace)

**Environment (please complete the following information):**

- Extension Name: vim
- Extension Version: 0.16.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.26.1

**Additional context**
The %s command still works normally, as far as I know.

**Comment by J-Fields** [comment]
This has been fixed.
