### ISSUE TITLE
Moving out of viewport centers the viewport when it shouldn't

### ISSUE THREAD

**Issue by bluetech** [VSCodeVim/Vim#2998]
**Describe the bug**
Moving up or down outside the viewport doesn't reveal the lines smoothly one by one, instead it centers the viewport vertically on the new cursor position.

This regressed in version 0.16.1, due to https://github.com/VSCodeVim/Vim/pull/2962 which is a fix for https://github.com/VSCodeVim/Vim/issues/2960 (cc @hhu94 @jpoon who were involved in these).

**To Reproduce**

1.  Open a file with more than a screenful of lines.
2.  Go to the middle of the file.
3.  Press `k` until reaching the top of the viewport, cross over.
4.  See that the screen jumps in a non-continuous manner.

**Expected behavior**
It should scroll smoothly. Unlike what the issue says, this is how `vim` behaves by default (verified with `vim --clean`).

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.1
- VSCode version: 1.26.0
- OS: Linux

**Comment by hhu94** [comment]
Repro'd successfully. I'll fix it sometime this week if no one else does.

**Comment by jpoon** [comment]
We should revert this PR. I unfortunately don't have very much free time to do this, but there should be a button on GH you can click to submit a PR for a revert.

**Comment by hhu94** [comment]
I submitted #3009. I'll try to submit a PR that addresses #2960 in a more localized manner. @jpoon Could you also reopen #2960 once you accept the revert PR?

**Comment by bluetech** [comment]
The problem is fixed in 0.16.2, thanks!
