### ISSUE TITLE
 Bug: Selection lost when indenting block of text in visual mode

### ISSUE THREAD

**Issue by chris-kahn** [VSCodeVim/Vim#3002]
Expected behaviour: when in visual mode with text selected, and I press `shift+,` or `shift+.` (< and > respectively), the text line or block should change indentation by one level, and remain selected so that I can continue pressing < or > to indent.

Actual behaviour: while the text does indent by one level, the selection is lost after pressing < or >. This renders the feature pretty much useless.

**Comment by willcassella** [comment]
This is how real Vim behaves. If you want the selection again, you can use `gv`.

**Comment by johnfn** [comment]
As everyone else said, this is how normal Vim works. If you want to keep re-indenting, just use `.`.
