### ISSUE TITLE
breaks use of snippet placeholders

### ISSUE THREAD

**Issue by mvolkmann** [VSCodeVim/Vim#3005]
When entering the variable parts of a snippet, the placeholder for the current part should be automatically replaced by whatever is typed. This works when the Vim extension is disabled. When it is enabled, the entered text just goes after the placeholder and the placeholder remains. The end result is that you really can't use snippet placeholders when the Vim extension is enabled.

This only seems to happen when the placeholder variable is referred to again on another line. For example,

```json
  "test": {
    "prefix": "test",
    "body": ["line 1 ${1:my-placeholder}", "placeholder = ${1}"]
  },
```

**Comment by nealot** [comment]
Just a wild guess but it might be related to https://github.com/VSCodeVim/Vim/issues/843?
