### ISSUE TITLE
Keymapping bindings inconsistently cased

### ISSUE THREAD

**Issue by austin-whittington** [VSCodeVim/Vim#3012]
**Describe the bug**
Some keymapping bindings are lowercase, which means remapping them requires trying both cases (Vim default is uppercase) to see what works (or checking the logs). The ones I saw were `<home>`, `<insert>` and `<end>` but I didn't exhaustively search.

**To Reproduce**
1.  Turn on debug logging (vim.debug.loggingLevel).
2. Observe mode handler debug messages when pressing:
  a. Home and End
  b. Escape and Delete

**Expected behavior**
Messages containing:
 a. `<Home>` and `<End>` (the logs yield `<home>` and `<end>`)
 b. `<Esc>` and `<Del>` (these show as expected)

**Environment**

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 10.0.14393
vim|vsc|0.16.2

**Comment by jpoon** [comment]
Pretty easy if somebody wants to tackle this. The logic is all here: https://github.com/VSCodeVim/Vim/blob/master/src/configuration/notation.ts#L31

**Comment by bionboy** [comment]
Should this be closed? @jpoon
