### ISSUE TITLE
CTRL-[ does not quit the command-line editing mode

### ISSUE THREAD

**Issue by harunou** [VSCodeVim/Vim#3019]
**Describe the bug**
CTRL-[ does not quit the command-line editing mode

**To Reproduce**
1. Press ":" to start the command-line editing mode;
2. Press "CTRL-[" - nothing happens;

**Expected behavior**
Pressing CTRL-[ quits the command-line editing mode

- Extension (VsCodeVim) version: 0.16.2
- VSCode version: 1.26.1
- OS: Linux Mint

**Comment by jesseminn** [comment]
Having similar issue here. Sometimes `ctrl - [` just stop working, thus I have to press `ESC` instead, but I don't know how to reproduce this issue...

**Comment by harunou** [comment]
Resolved as of ver. 0.16.9

**Comment by bool3max** [comment]
Finally fixed... it was driving me mad. Great work everyone.
