### ISSUE TITLE
Reverse search using '?' after '*' fails to search

### ISSUE THREAD

**Issue by Deracination** [VSCodeVim/Vim#3031]
Searching using '*' I expect a subsequent '?' to search backwards. Instead this opens the '/' prompt and waits for input.

**To Reproduce**
1.  Open a file
2.  Position cursor on a word and press '*' to search forward for the next instance.
3.  Press '?'
4.  The '/' is opened in the status bar

**Expected behavior**
I expect '?' to search backward because '*' has already defined the search

**Extra information**
If I search forwards using '/' instead of '*' then '?' does search backwards as expected. It seems like'*' and ('/' and '?') are using different variables to hold the search criteria?

- Extension (VsCodeVim) version: 0.16.3
- VSCode version: 1.26.1
- OS: Windows 10

**Comment by axs221** [comment]
The reproduced behavior sounds like expected behavior, maybe I am missing something. Even though it shows a `/` in the status bar, it will search backwards after entering a term and pressing `Enter`. `?` will open a search prompt to enter a new search term, not reuse what was searched when pressing `*`. That is independent of the `*` action performed prior. This matches vanilla Vim behavior.

If you want to search backwards after pressing `*`, it seems like you would either press `#` to search backward on the word under cursor, or just press `N` to search backward on the current search term.

**Comment by Deracination** [comment]
Not quite the same. Pressing '*' searches forwards for the token under the cursor. I expect pressing '?' to then search backwards for that token but it instead opens the '/' status bar waiting to me to type in a search. In vim the vanilla behaviour is that pressing '?' searches backwards using the token from '*', the same as '#'

**Comment by J-Fields** [comment]
This isn't how vim behaves (I just tested with `vim --clean`). @Deracination is it possible you've remapped this in your .vimrc?

**Comment by Deracination** [comment]
I just checked without a .vimrc and the '*' and '?' keys work as I described with vim 7.4 (linux) and gvim 8.0 (windows). BTW, neither of those versions have a '--clean' option. Which version are you testing with?

**Comment by J-Fields** [comment]
I'm using version 8.1 on windows. [Here's](http://vimdoc.sourceforge.net/htmldoc/pattern.html#?) documentation for `?`, which does say that hitting `<CR>` after `?` will use the previous search term - is this what you're referring to? It does appear that VSCodeVim doesn't quite emulate this correctly, as it uses the last search term used via `/` or `?` (it won't use something you searched for with `*`).
In any case, I don't see any documentation that suggests `?` without entering anything else will do a backward search, and haven't been able to reproduce this behavior in vim.

**Comment by Deracination** [comment]
Sorry I wasn't clear. Yes, the expected behaviour is that typing '?<enter>' should repeat the current search backwards (whether from '/' or '*'). I didn't intend to suggest that '?' by itself did anything. I think I forgot the '<enter>' because that reverse search is so ingrained into muscle-memory now.

**Comment by J-Fields** [comment]
I see - thanks for clarifying. This does seem to be a bug. I'll take a look at fixing it when I get a chance.

**Comment by J-Fields** [comment]
This came down to `*` and `#` not getting adding to the search history, so when you did `?<CR>`, it didn't use the term you just searched.
