### ISSUE TITLE
Support vscode's color copy

### ISSUE THREAD

**Issue by hausdorff** [VSCodeVim/Vim#3038]
vscode supports copying text with syntax coloring in tact. This extension prevents that. I have to disable the extension when copying from vscode.

**Comment by jpoon** [comment]
(Hi @hausdorff! Hope you've been doing well)

VSCode doesn't expose an API for clipboard access. As a result, we've had to fend for ourselves and are currently using https://github.com/sindresorhus/clipboardy which doesn't support copying rtf/html. Doing some brief research, this looks promising: https://github.com/lgarron/clipboard-polyfill

**Comment by hausdorff** [comment]
@jpoon! I did not know you were part of this project! :) You may be interested to know that I think it emphatically does not suck.

Anyway, that's a major bummer. It might be possible to simply copy the (formatted) text and dump it into the clipboard on copy. I'm not sure if you think this is too much of a hack to go with?

**Comment by Chillee** [comment]
@hausdorff You should be able to run the `copy with syntax highlighting` command through the command palette. I think that's an appropriate compromise.

**Comment by hausdorff** [comment]
@Chillee That solution does not suck! I'm happy to close this issue, then, until the case where vscode implements a clipboard API.

**Comment by jpoon** [comment]
With https://github.com/VSCodeVim/Vim/pull/3261, this is now supported.

**Comment by DemianParkhomenko** [comment]
Can syntax highlighting be copied using the 'yy' keys in visual mode?
