### ISSUE TITLE
When using vim extension, cursor navigation with keyboard doesn't trigger matching symbol highlights

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#3044]
_From @roblourens on March 30, 2018 0:55_

- Install Vim extension (I don't think an extension should be able to break this, so filing it here)
- Enter insert mode (or not)
- Move the cursor over a symbol in a TS file
- Matching symbols should be highlighted, but they are not
- If I click somewhere on the same symbol, then matches are highlighted

![mar-29-2018 17-52-34](https://user-images.githubusercontent.com/323878/38119907-04d2951a-337a-11e8-92e0-437ac9762707.gif)

_Copied from original issue: Microsoft/vscode#46978_

**Comment by rebornix** [comment]
_From @nerdmax on July 13, 2018 1:45_

+1

**Comment by rebornix** [comment]
_From @diescake on July 17, 2018 4:22_

+1

**Comment by rebornix** [comment]
_From @nerdmax on July 31, 2018 4:59_

I found a workaround! If you just want to highlight the current word, you can use `#` or `*` command to navigate previous or next matched word.

**Comment by rebornix** [comment]
@alexandrudima do you think adding a `CursorChangeReason` for cursor changes from `api` and allow word highlighter to retrigger when seeing changes from `api` would lead to too much word highlighting tasks?

**Comment by rebornix** [comment]
_From @forrestbaer on September 11, 2018 13:54_

+1

Would nice to at least get typical mouse cursor functionality with a keypress, so i hover over a word or linter error or whatever and hit a key and I get the same effect as if I had hovered in that location.

**Comment by rebornix** [comment]
_From @alexandrudima on September 12, 2018 13:45_

@rebornix Not sure 100% what you mean, but I think the problem here is that we lose the information that the cursor was moved due to a direct interpretation of a cursor navigation keypress (i.e. not like jump to definition or undo, etc)... Would be good if we would have a way to distinguish the vim case from the rest of the users of `TextEditor.selections`

**Comment by rebornix** [comment]
I added a command for triggering the word highlight `editor.action.wordHighlight.trigger` if there is no word highlighting available in the document (meaning the word highlighting feature is enabled but there are no decorations for current word). Our Vim ext can decide when to call this command to run the word highlighting.

**Comment by audkar** [comment]
Would it be possible to have auto trigger word highlighting after delay (if vim editing is idling)?

**Comment by J-Fields** [comment]
Just did a quick test running `editor.action.wordHighlight.trigger` at the end of `ModeHandler.updateView`, which works but is definitely overkill. Any reason we shouldn't just run this every time a motion is executed? We could make sure there's only one cursor and it's not on a whitespace character.

**Comment by ryanflorence** [comment]
The auto highlighting really messes with me, so I set `"editor.occurrencesHighlight": false`.

If I do Shift + 8 I can jump around to to each occurrence but they aren't highlighted. If I double click the things it still highlights.

Is this related? How do I get it to highlight on shift + 8 the same as double clicking?

**Comment by J-Fields** [comment]
@ryanflorence We use our own highlighting for `*` (same as searching). You can customize it with `vim.searchHighlightColor` and `vim.searchHighlightTextColor`
