### ISSUE TITLE
C-o, C-i strange jumping behavior.

### ISSUE THREAD

**Issue by killwing** [VSCodeVim/Vim#3047]
**Describe the bug**
C-o, C-i jumps not follow the correct sequence.

**To Reproduce**
e.g.: When browsing golang source files, C-o does not jump back to last position after do gd (go to definition) many times, but jumps to the position before last position. Meanwhile, C-i is not working anymore.

**Expected behavior**
C-o should jump back to last position after gd jumps.

**Screenshots**
None.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 0.16.4
- VSCode version: 1.27.1
- OS: OS X El Capitan

**Additional context**
Probably caused by the recent jump list improvement?

**Comment by shawnaxsom** [comment]
Hi @killwing, thanks for the report. What happens if you run the `View: Keep Editor` command on both the file being jumped from and the file being jumped to?

If that works fine, this is likely a duplicate of #3039, which has been fixed and merged for next release.

**Comment by killwing** [comment]
It works fine if editors are kept.
