### ISSUE TITLE
Vim: incsearch (vim.incsearch) flag incorrectly affects search highlight instead of incremental search

### ISSUE THREAD

**Issue by Bingularity** [VSCodeVim/Vim#3049]
Issue Type: <b>Bug</b>

1. open any text file
2. go to setting
3. seacrh for 'incsearch'
4. turn off Vim: Hlsearch
5. turn on Vim: Incsearch
6. go back to editor window and try to search some off-screen text
7. incremental search (search as we type) and highlight is still functioning and jump the cursor to the first matched text and highlight it.
8. goto setting, this time also turn off Vim: Incsearch
9. go back to editor window and try to search some off-screen text
10. incremental search is still functioning although highlighting is off now.

Extension version: 0.16.4
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|4.00GB (0.37GB free)|
|Process Argv|C:\Users\com\AppData\Local\Programs\Microsoft VS Code\Code.exe C:\Users\com\p\source\secap.code-workspace|
|Screen Reader|no|
|VM|100%|

</details>

**Comment by Bingularity** [comment]
Looks like those flags do take effect after a restart (Visual Code).

**Comment by Bingularity** [comment]
Sorry but they don't take effect after restarting Visual Studio Code.
The extension is vscodevim 0.16.4.

**Comment by Bingularity** [comment]
Sorry but they don't take effect after restarting Visual Studio Code.
The extension is vscodevim 0.16.4.

**Comment by HugeCrab** [comment]
I have encountered the same problem.

**Comment by justinjhendrick** [comment]
I'm seeing a similar problem. `"vim.incsearch": false` seems to make no changes to how search works. It seems that `incsearch` is always true, no matter what's in `settings.json`
