### ISSUE TITLE
keybinding <c-f> overwrite vscode's default behavior

### ISSUE THREAD

**Issue by myhere** [VSCodeVim/Vim#3050]
**Describe the bug**
This plugin's `<C-f>` binding overwrite vscode's default `<C-f>` behavior, but `<C-b>` is ok;

**To Reproduce**

1.  install Vim plugin
2.  restart vscode and open a file
3.  press `<C-f>` in「Insert」mode, it do nothing

**Expected behavior**
- `<C-f>` in「Insert」mode is supposed to execute「cursorRight」command, it's the vscode's default key binding.
- `<C-b>` works ok in all mode

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v0.16.4
- VSCode version: 1.27.2
- OS: MacOS 10.12.6

**Additional context**

**Comment by jpoon** [comment]
What platform are you on? This sounds like expected behaviour so far... did you take a look at `useCtrlKeys` and `handleKeys`: https://github.com/VSCodeVim/Vim#vscodevim-settings

**Comment by myhere** [comment]
hi, @jpoon , i'm on MacOS(just added above)

vscode have a default `<C-f>` key binding on mac(see screenshot below)，and the vim's `<C-f>` will overwrite the default binding.

but the `<C-b>` binding works correctly, because it have a `vim.mode != 'Insert'` condition check see: https://github.com/VSCodeVim/Vim/blob/8a136d180dc80e4d4650a61ac4878c6170d2aa58/package.json#L148

so i thinks it has nothing to do with `useCtrlKeys` and `handleKeys`~

![image](https://user-images.githubusercontent.com/515630/45547111-3b81ee00-b852-11e8-8acc-4623e43d03dd.png)

**Comment by myhere** [comment]
hi @jpoon,

please see the comment above and do i fix it correctly?

**Comment by jpoon** [comment]
Hey sorry. I just changed to a new job so haven't had time to look at this. 

I don't have my mac with me right now but what is `<C-f>` do while in insert mode in vanilla vim?

**Comment by myhere** [comment]
> I don't have my mac with me right now but what is `<C-f>` do while in insert mode in vanilla vim?

vanilla vim doesn't  have a  `<c-f>` mapping.

actually mac version VSCode map `<c-f>`  to `cursorRight`(see above screenshot). so i want to keep it when using VSCodeVim plugin.

**Comment by jpoon** [comment]
Ok, I just wanted to make sure we weren't overriding something there.

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/pull/3051
