### ISSUE TITLE
yanking all lines does not work

### ISSUE THREAD

**Issue by domduke12** [VSCodeVim/Vim#3061]
**Describe the bug**
command ":%y" show **E492: Not an editor command. %y**

**To Reproduce**

1.  Go to command mode
2.  command "%y"

**Environment (please complete the following information):**
- Extension Name: vim
- Extension Version: 0.16.4
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0-insider

**Additional context**
I have neovim enabled and restarted vs code after that.

**Comment by LeahCim** [comment]
I got it working by enabling _Neovim_ and setting _Neovim Path_ to where I installed neovim into (specifically to the nvim.exe file on Windows).

**Comment by uri** [comment]
Related #2869

**Comment by J-Fields** [comment]
Closing in favor of #2869
