### ISSUE TITLE
Ctrl+PgUp/Dn (prev/next editor tab) does not work in insert mode

### ISSUE THREAD

**Issue by Orionsg** [VSCodeVim/Vim#3062]
When in command mode Ctrl+PgUp/Dn will, as is quite normal in editors, go to the previous and next editor tabs. However, when in insert mode the function doesn't work -- nothing happens.

Note: One can use Ctrl+tab and Ctrl+Shift+tab to scroll through the editor tabs in insert mode. However, this does not necessarily change to the next/prev editor tab, but scrolls through them in some other order, probably the sequence in which they were opened. If tabs were opened in a previous VScode session (and thus automatically reopened in this session), they are sometimes not even reachable through Ctrl+tab / Ctrl+Shift+tab. Thus Ctrl+PgUp/Dn really should be fixed as it is irritating having to go out of insert mode to use the keyboard to go to prev/next editor tab to check something.

- Extension (VsCodeVim) version: 0.16.4
- VSCode version: 1.27.2
- OS: Windows 7 (32 bit)

**Comment by Aleksandern** [comment]
keybindings.json
```
[
    {
       "key": "ctrl+pageup",
       "command": "workbench.action.previousEditor",
    },
    {
       "key": "ctrl+pagedown",
       "command": "workbench.action.nextEditor",
    }
]
```

**Comment by Orionsg** [comment]
Thanks, works like a charm!

**Comment by exic** [comment]
Shouldn't this be a default?
