### ISSUE TITLE
Make <C-r><C-w> work in Ex mode to copy the current word under the cursor

### ISSUE THREAD

**Issue by elmewo** [VSCodeVim/Vim#3063]
**Is your feature request related to a problem? Please describe.**
I'd like to see \<C-r>\<C-w> work in Ex mode as in Vim so that I don't need to type every word I want to substitute.

**Describe the solution you'd like**
:%s/\<C-r>\<C-w>/foo
Here, \<C-r>\<C-w> copies the word under the cursor and pastes it into the ex command.

**Describe alternatives you've considered**

**Additional context**

**Comment by Orionsg** [comment]
I would also like that to be fixed. A workaround that I am using until is:

1. Set the setting "Use System Clipboard" to on.

2. When the cursor is on the word in Command mode, use "yiw" to yank the word (and thereby also copy it to the system clipboard).

3. When specifying the replace command ("%s/"), use the ctrl-v for pasting in the word from the system clipboard and fill in the rest of the replace command.

**Comment by J-Fields** [comment]
This now works

**Comment by MarcoPeraza** [comment]
This does not work currently.
