### ISSUE TITLE
Make \zs and \ze work in Vim search to only include substring of match

### ISSUE THREAD

**Issue by elmewo** [VSCodeVim/Vim#3073]
**Is your feature request related to a problem? Please describe.**
When using the Vim search you are usually able to include only a part of the match as search result. This is not possible in VSCodeVim, yet.
Example from Practical Vim:
`/\v\<\/?h\zs\d`
This finds all digits in html heading tags as in 
```
<h2>Heading number 1</h2>
<h3>Number 2 heading</h3>
<h4>Another heading</h4>
```
.

**Describe the solution you'd like**
I'd like to see the vanilla Vim regex engine behaviour here, because this is an essential feature for pattern search.

**Comment by jwmann** [comment]
`\zs` and `\ze` are literally my favourite components to vim regexp
Unfortunately I think they don't work because VSCodeVim uses regular Javascript for its regexp engine (according to #991), which iirc doesn't have the ability for `\zs` and `\ze`

**Comment by jwmann** [comment]
I found a way to do something similar to `\zs` and `\ze` 
Check this out for reference: https://javascript.info/regexp-lookahead-lookbehind

**Comment by J-Fields** [comment]
Closing in favor of #3996
