### ISSUE TITLE
Can't find whole words

### ISSUE THREAD

**Issue by sshock** [VSCodeVim/Vim#3075]
**Describe the bug**
I am unable to find whole words using  `\<` and `\>`, e.g., `\<myword\>`

**To Reproduce**

1.  Open any file.
2.  Type `/` to begin a search.
3.  Type`\<xxx\>` and hit enter, where xxx is a word you want to search for.

**Expected behavior**
Should highlight and then jump to the matching word.

**Environment**

- Extension (VsCodeVim) version: 0.16.5
- VSCode version: 1.27.2
- OS: macOS 10.13.3

**Comment by urbpeti** [comment]
The reason is VSCodeVim uses javascript regex where \< matches the character "<" literally (case sensitive)

**Comment by sshock** [comment]
Ok, I guess I can just start getting used to using \b and hope that works well enough.

**Comment by J-Fields** [comment]
Closing in favor of #3996
