### ISSUE TITLE
Make <c-u> go to the top of the page

### ISSUE THREAD

**Issue by PotatosFish** [VSCodeVim/Vim#3083]
# Is your feature request related to a problem? Please describe.
<c-u> doesn't move the cursor to the top of the file.

# Describe the solution you'd like
move the cursor to the top of the file when it is pressed

# Describe alternatives you've considered
maybe check the length the cursor can go when <c-u> is pressed. When it's less than half a page, just go to the top.

# Additional context
I am typing <c-u> after it is at line 3. It should go to line 1, but it stops
![whathappens](https://user-images.githubusercontent.com/16280574/46259584-db6d8780-c4a0-11e8-9c5c-d0bc03647eee.gif)

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/pull/3776
