### ISSUE TITLE
custom <Esc> key binding "jj" stoped working when entering insert mode from "cw"

### ISSUE THREAD

**Issue by Confidenceman02** [VSCodeVim/Vim#3088]
**Describe the bug**
Leaving insert mode with a custom key binding does not work if you entered insert mode from a "cw" command.

**To Reproduce**

1.
map `"jj"` to `<Esc>` with 
```
 "vim.insertModeKeyBindings": [
        {
            "before": ["j", "j"],
            "after": ["<Esc>"]
        }
    ]
```
2.  hit `"i"` to enter insert mode and write some text. Press `"jj"` to confirm it leaves insert mode.
3. go to the start of the text/word and hit `"cw"` to change the word.
3.  hit `"jj"`
4.  just keeps rendering the letter `"j"` and does not leave insert mode as it should.

**Expected behavior**
When entering insert mode with `"cw"` typing `"jj"`, if mapped to `<Esc>`, should indeed exit insert mode considering it works fine when hitting `"i"` then hitting `'jj"`.

**Screenshots**
![vscode](https://user-images.githubusercontent.com/25443812/46408528-ca00d580-c755-11e8-9219-7fd9a9f84474.gif)

**Environment (please complete the following information):**

- Extension Name: vim
- Extension Version: 0.16.6
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.27.2

**Additional context**

**Comment by shawnaxsom** [comment]
Thanks for the report! I was able to reproduce, and I will take a look. It sounds like this is related to #3078. We were sending vscode information about the Vim mode too often before that it was affecting performance, but this use case might be a loophole where it missed sending the Vim mode when it needs to.

**Comment by shawnaxsom** [comment]
Bug fix PR is up. Remappings should work in this case if an operator combination results in leaving normal mode. I added a test as well to make sure we don't have future regressions.

**Comment by rightaway** [comment]
@sarink When a new version is available how can I update from this custom version?

**Comment by damassi** [comment]
Also curious about how to update. I'm noticing that this custom remap breaks in a few different instances, not just `cw`.

**Comment by sarink** [comment]
To re-update, simply uninstall and reinstall, it's no big deal.
