### ISSUE TITLE
version 0.16.6 cause <tab> key insert string for unknown reason

### ISSUE THREAD

**Issue by xiaoyu-tamu** [VSCodeVim/Vim#3096]
**To Reproduce**

I don't know how to reproduce it.  It insert \<tab\> string when press tab key. BTW, Anyone knows how to install an older version?

<img width="1440" alt="screen shot 2018-10-04 at 6 58 04 pm" src="https://user-images.githubusercontent.com/33362998/46509402-08ef6380-c808-11e8-9666-5aafbd20140c.png">

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by vityas-off** [comment]
Same here
https://github.com/Microsoft/vscode/issues/59925

**Comment by ruffin--** [comment]
When I'm in this "state" in insert mode where `<tab>` is literally inserted, I also tend to lose the ability to use Home, End, Delete, and other "normal" button functions. Often to usually, escaping into command mode and going back into insert mode fixes this.

This is Vim version 1.0.39 
on Windows 10 build 15063.1356
VS Code 1.27.2

**Comment by shawnaxsom** [comment]
PR #3108 is up and will fix the issue by updating `vim.mode` (used by keybindings) whenever changing tabs.

In the meantime, workarounds are:

- Open new tabs while in normal mode whenever possible (assuming `vim.startInInsertMode` setting is `false`)
- Or press `<Esc>` if you do get into the bad state. Changing mode with a keypress in this manner will correct the issue.

**Comment by anka-213** [comment]
I still(/again?) have this issue spuriously. Should I open a new issue for it or is it easier to just continue here?

Specifically what happens is that in insert mode, pressing tab sometimes produces the text `<tab>` instead of 4 spaces or whatever was configured.
