### ISSUE TITLE
Previous searches are not saved across sessions

### ISSUE THREAD

**Issue by rishadomar** [VSCodeVim/Vim#3098]
I press slash and want to edit or use previous searches. 
In vi or other emulators I press slash then using the UP / DOWN keys I can navigate to previous search terms.

The solution I expect is to save previous search terms and allow me to navigate to them. I should be able to edit it and execute it.
![vi-search](https://user-images.githubusercontent.com/32675/46520863-d7b17a80-c87d-11e8-91e5-5c50473f0e69.jpg)

**Comment by xconverge** [comment]
You can...do you mean across sessions or just within one session? Do ```:``` commands work the way you expect?

We save search history that you can navigate, we just do not save it across sessions

**Comment by rishadomar** [comment]
Aha - you're right! Works fine in 1 session but I lose history across 
sessions.
And yes correct, : commands save history across sessions.

**Comment by xconverge** [comment]
Ok, let me rename this issue to be more clear, it is an enhancement that could be added, especially since we are already doing something similar for history
