### ISSUE TITLE
<C -c> stopped working this morning

### ISSUE THREAD

**Issue by kamry-bowman** [VSCodeVim/Vim#3110]
**Describe the bug**
<C-c> stopped working to leave Insert mode as of today. It previously worked. No changes were made to VSCode or Vim config. 

Vim settings are:
```
    "vim.useSystemClipboard": true,
    "vim.handleKeys": {
        "<C-b>": false,
    },
    "vim.useCtrlKeys": true,
```

**Expected behavior**
Expect <C-c> to exit Insert mode to Normal mode.
**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.7
- VSCode version: 1.27.2

**Comment by kamry-bowman** [comment]
A bit embarrassing.. Ctrl+C wasn't working generally in Windows 10. A restart fixed the problem throughout the OS including VS Code. Thanks for the quick response.

**Comment by shawnaxsom** [comment]
No problem, thanks for the resolution!
