### ISSUE TITLE
Support "bang" operations on selected code blocks

### ISSUE THREAD

**Issue by ijstokes** [VSCodeVim/Vim#3136]
**Is your feature request related to a problem? Please describe.**
With standard Vim I regularly use block-select to pick a group of lines and then pass them to a piped Unix filter, e.g. `:'<,'>!sort|uniq`.  As best I can tell, this isn't possible with the VSC Vim plugin today.

**Describe the solution you'd like**
Support "bang" (`!`) operations when in command mode

**Describe alternatives you've considered**
I don't know another way to do this.  Right now if it is important enough I cut and paste the content into an empty document in Vim, do the operation there, then cut and paste the content back in to Visual Studio Code.

**Comment by beaugunderson** [comment]
Hmm... Shift-V to select lines, then `:!sort` or `:!tac` used to work prior to 1.31.0 and now does not work for me. It now just refreshes all the text on screen.

**Comment by beaugunderson** [comment]
(It could also have broken in the recent VSCodeVim release; I'm not sure if it was VSCode upgrade that broke it)

**Comment by beaugunderson** [comment]
I uninstalled some extensions and reloaded and this works again... Could have been a conflict or it could have been that the behavior is just finnicky. Will comment again if it breaks again and a reload fixes it.

**Comment by sjackman** [comment]
Thank you for VSCodeVim! It's fantastic.

✅`:r!seq 10` works for me!
❌`!!date` does not work for me.
❌`:.!date` does not work for me.
❌`:'<,'>!sort` does not work for me (selecting a block with `V` and then `!sort`)

Should these work? Please consider this post a feature request if these are not currently implemented.

VSCodeVim 1.10.2
Visual Studio Code 1.38.1

**Comment by sjackman** [comment]
@tagniam Thank you very much for PR https://github.com/VSCodeVim/Vim/pull/4989!

✅`:r!date` always worked for me!
✅`:.!date` works for me after PR https://github.com/VSCodeVim/Vim/pull/4989!
✅`V:!sort` works for me after PR https://github.com/VSCodeVim/Vim/pull/4989!
❌`V!sort` does not work for me. (selecting a block with `V` and then `!sort` without first `:`)
❌`!!date` does not work for me.

**Comment by tagniam** [comment]
Hey @sjackman, I separated the filter operators like `V!` and `!!` into a separate PR, which is pretty much done now. I'll be submitting it asap. Thanks!

**Comment by sjackman** [comment]
Thank you very much, JR!

**Comment by catskul** [comment]
AFAICT, this is either broken again, or never completely fixed. I can find no working way to select and sort text using `!sort`

**Comment by tagniam** [comment]
Hey @catskul, yeah I think this was sorta broken by a recent commit, but I have a fix for it and I'll put up a PR soon.

In the meantime you can use `sort` without the bang to sort a selection.
