### ISSUE TITLE
Escape key stopped being registered so can't exit insert mode

### ISSUE THREAD

**Issue by nikitavoloboev** [VSCodeVim/Vim#3139]
Pressing `escape` key does nothing for me when in `Insert mode`. However my escape key works on macOS and I can dismiss command palette with escape too. 

I am not sure what happened that made this change. Is it possible to find out why this started happening?

**Comment by nikitavoloboev** [comment]
It seems like escape key is not being registered by VS Code Vim extension at all.

For example I just entered visual mode:

![2018-10-15 at 13 45](https://user-images.githubusercontent.com/6391776/46949134-a0fb1180-d080-11e8-9bc1-503036d53cd1.png)

And pressing `escape` doesn't exit from the visual mode either. I have a feeling like some keyboard hotkey was remapped in keyboard shortcuts but I don't know which.

**Comment by nikitavoloboev** [comment]
Reinstalling the extension worked and fixes it.

**Comment by twhiteman** [comment]
Just noting that I had the same issue (after the vscode 1.28.1 update) - re-installing the Vim extension solved the issue for me too.

**Comment by shawnaxsom** [comment]
This looks like a duplicate of #3143. I am working on a fix now. I mentioned a workaround here:

https://github.com/VSCodeVim/Vim/issues/3143#issuecomment-431040200
