### ISSUE TITLE
fold code block bug

### ISSUE THREAD

**Issue by hitzhangjie** [VSCodeVim/Vim#3140]
**Describe the bug**
press 'zc' to close the code block, like an import block or a function, press 'zo' to reopen the folded code block.
bug1: when moving to the end line of code block, press 'zo' cannot reopen the code block, you have to put the cursor in the beginning or the middle of the code block.
bug2: when fold the code block at the beginning, and the press j to move down, the code block will be reopen automatically, press 'zo' to trigger the reopen action will be better.

**To Reproduce**
create a snippet to zc / zo the code block, for example an import block or a function.

**Expected behavior**
when press 'zc' in the every line of the code block, should trigger the fold action.
don't unfold the code block automatically when moving cursor around it, use 'zc' to trigger that.

I use the latest vim extension and xcode, because I installed it just now.

**Comment by hitzhangjie** [comment]
vim.foldfix=true solve this problem.

**Comment by yasintz** [comment]
@hitzhangjie  thanks for answer
