### ISSUE TITLE
VIM stops working when another instance of Code starts

### ISSUE THREAD

**Issue by Edke** [VSCodeVim/Vim#3141]
**Describe the bug**
When starting another instance of Code, VIM extension does not work correctly, ie. changing modes does not work (ESC in insert mode or line visual mode and yank).

**To Reproduce**

1.  Start another instance of VIM
2.  Change to insert mode than exit using ESC

**Expected behavior**

All Vim shortcuts should work with any instances of Code

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.10
- VSCode version: 1.28.1
- OS: Archlinux (updated to latest)

**Comment by ben-pr-p** [comment]
I had this on 0.16.10 with or without another Code open. Downgrading to 0.16.9 fixed it

**Comment by Edke** [comment]
@ben-pr-p WOw, glad confirmed and I'm not lost in space :)

OK, now any tips how to install previous version ? is it possible to somehow specify version while 
`ext install vscodevim.vim` ?

**Comment by Edke** [comment]
Managed using these: https://github.com/prettier/prettier-vscode/issues/332#issuecomment-358255953

**Comment by ben-pr-p** [comment]
Yeah, you need extensions.autoUpdate to be false. Then, I edited `./.vscode/extensions.json` to be:

```
{
  "metadata": {
    "id": "d96e79c6-8b25-4be3-8545-0e0ecefcae03",
    "publisherId": "vscodevim.vim",
    "publisherDisplayName": "vscodevim"
  },
  "name": "vim",
  "publisher": "vscodevim",
  "version": "0.16.9"
}

```

and uninstalled, reinstalled, and reloaded.

**Comment by lorentzforces** [comment]
I also just encountered this issue in the following environment:

* Extension (VsCodeVim) version: 0.16.10
* VSCode version: 1.28.1
* OS: Win10 v1709

Don't have the setup to test/bisect right now, but since it's mode/editor switching it may have been introduced in 24412f6eef296e61176cb183aa826a9fc48b27f4

**Comment by mikew** [comment]
Seeing the same as @dusty, extension just plain doesn't work.

**Comment by shawnaxsom** [comment]
The error @dusty had was addressed in #3146. A fix was released last night with version 0.16.11. @mikew are you on 0.16.11?

**Comment by MaerF0x0** [comment]
Another potential symptom of the same.  I noticed that my backspace wasnt working in many commands and I couldn't `ESC` out of the command mode `:`  ...

**Comment by J-Fields** [comment]
Seems like this is fixed, so I'm closing. Someone holler if they're still seeing this.
