### ISSUE TITLE
Version 0.16.10 stuck in insert mode

### ISSUE THREAD

**Issue by lengingerlabs** [VSCodeVim/Vim#3143]
Escape or any of the other keys don't work. Downgrading to 0.16.9 fixes the problem.

**Comment by FlowTheSeagull** [comment]
Uninstalling and reinstalling the extension has fixed this for me

**Comment by gforceg** [comment]
Same issue here. Reinstalling did not help.

**Comment by gforceg** [comment]
@lengingerlabs how do you downgrade?

**Comment by lengingerlabs** [comment]
You can follow these instructions to downgrade:

https://tpodolak.com/blog/2017/04/09/downgrading-visual-studio-code-extension/

publisher: vscodevim
extension: vim
version: 0.16.9

Vscode seems to want a .vsix extension, so you may need to change the extension of the downloaded file.

**Comment by gforceg** [comment]
thanks. i got it

short version:
ctrl + shift + p => install from VSIX
enter this URL
https://vscodevim.gallery.vsassets.io/_apis/public/gallery/publisher/vscodevim/extension/vim/0.16.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

also, make sure that autoupdate extensions is not enabled in settings.

**Comment by xconverge** [comment]
Next time this happens can someone try restarting vscode twice? I had to restart vscode twice for some reason after the upgrade before things worked normally...

**Comment by typeoneerror** [comment]
@xconverge have restarted to fix numerous times throughout the day. pops up again eventually.

**Comment by a-eid** [comment]
I have more or less the same issue, I have to either reinstall vscode or the extension to get it to work.
but the issue always reappears. 

it gets stuck in search, insert or visual mode. 

I'm using version `0.16.10`.

**Comment by rzane** [comment]
Until this bug is fixed, opening VSCode and running `cmd+shift+p` selecting "Reinstall Extension" and choosing "VSCode Vim" seems to fix the issue. You have to remember to do this every time you open the editor, though.

**Comment by jpoon** [comment]
@xconverge https://github.com/VSCodeVim/Vim/issues/3143#issuecomment-430504105 stack trace points to bug introduced with https://github.com/VSCodeVim/Vim/pull/3116? Is it cause we are now reading from the same file if we have two editors open?

**Comment by CronosTs** [comment]
Same issue here. It's annoying as hell...

**Comment by shawnaxsom** [comment]
I might be able to take a look.

I found valid reproduction steps, and I think the stack trace from @ikazoy and #3116 are relevant given the steps to reproduce.

1. Close all vscode tabs
2. Restart vscode, opening the same project that has no persistent tabs
3. Open a file and enter insert mode
4. Press escape

It must not like the fact that it wasn't able to find a VSCode activeEditor textDocument on loading the file, maybe something to do with the persistence of the search history in #3116.

**Comment by shawnaxsom** [comment]
Spun up a fix in a quick PR with #3146. It seems to fix the issue without regressing #3116. This should be good as a permanent fix, not a stop-gap.
