### ISSUE TITLE
'j' doesn't repeat

### ISSUE THREAD

**Issue by alexanderkjeldaas** [VSCodeVim/Vim#3150]
**Describe the bug**
Holding down 'j' will only move one line down.

**To Reproduce**

1.  Press and hold 'j'
2.  Cursor moves to next line
4.  Nothing happens.

**Expected behavior**
The cursor should continue to move downwards.

**Screenshots**

**Environment (please complete the following information):**

- Extension Name: vim
- Extension Version: 0.16.11
- OS Version: Darwin x64 16.7.0
- VSCode version: 1.28.2

 We have written the needed data into your clipboard. Please paste:
```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 410,
		"activateCallTime": 5,
		"activateResolvedTime": 40,
		"activationEvent": "*"
	}
}
**Additional context**
Add any other context about the problem here.

**Comment by xconverge** [comment]
Do other keys repeat? Did you read the FAQ in the readme?

**Comment by xiaoxiaozhu5** [comment]
Same problem, also other key doesn't repeat(h,j,k,l)
Extension Name: vim
Extension Version: 0.16.12
OS Version: MacOS 10.12.6
VSCode version: 1.28.2

**Comment by jpoon** [comment]
Did you take a look at our readme? https://github.com/VSCodeVim/Vim#mac-setup.

Feel free to re-open if that is not the case but I'm fairly certain that the above will resolve it.
