### ISSUE TITLE
External Filter support

### ISSUE THREAD

**Issue by reviewher** [VSCodeVim/Vim#3154]
**Is your feature request related to a problem? Please describe.**
`:{range}!` is a common idiom for running an external filter like `awk` or `jq` for processing data.  Currently all commands fail with "Not an editor command"

**Describe the solution you'd like**
- `:! foo` would execute `foo` and pipe the result to the Output tab
- `:<range>!foo ` would execute `foo`, using the specified lines as stdin, and replacing those lines in the file with the output from the command.  stderr would be piped to Output.

**Describe alternatives you've considered**
An alternative is to run a parallel instance of vim and perform those operations on the vim instance, relying on the fact that both vscode and vim will detect if the file changed, but that's not exactly a great solution 

**Additional context**
See [`:help filter`](http://vimhelp.appspot.com/change.txt.html#filter) for more info on the family of commands

**Comment by jseely** [comment]
I would love to see this feature added, one of the most powerful features in Vim for regular use!

**Comment by noonien** [comment]
I also use this feature all the time in vim, to run all sorts of command-line filters on the code, `grep`, `sed`, `awk`, `jq`, small one-line perl scripts and even to upload parts of code to pastebins. 

This extension helped me give vscode a chance, but this feature is a must-have IMHO, along with `:w !{command}`
