### ISSUE TITLE
Cursor in different spot than where cursor appears and text gets deleted in different location

### ISSUE THREAD

**Issue by billrobclark** [VSCodeVim/Vim#3157]
**Describe the bug**
When switching from one app to VSCode when VIM was in insert mode and I delete some text sporadically text is deleted from a different location than where the cursor appears.  Also, the select next occurrence doesn't function as it should when the VIM extension is installed.

Disabling this extension everything work fine, so it's definitely something when this extension is installed.

**To Reproduce**
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: v0.16.11
- VSCode version: 1.28.2
- OS: MacOS Mojave, and it happened on High Sierra as well

**Comment by NavyAdmiral** [comment]
Can confirm this is an issue with VIM. I had to disable VIM because of this. Hopefully, it will be addressed soon.

**Comment by billrobclark** [comment]
Any update on this? Or possible settings that can be modified to prevent this from happening? The select next occurrence is also glitchy when Vim is installed. I'm using SimpleVim right now just so these bugs aren't happening and it's really not enjoyable to use, it's not Vim. Would really love any update on this or progress. Thank you.

**Comment by esetnik** [comment]
This is still happening to me too

**Comment by billrobclark** [comment]
I can't believe more aren't seeing this same issue. It's pretty painful honestly.

**Comment by esetnik** [comment]
Yeah, recently I had this bug happen again and I deleted a character from a variable name in a php project. Practically shipped that bug to production before I noticed.

**Comment by billrobclark** [comment]
It happens to me all the time, I use SimpleVim now which doesn't do it, but doesn't have hardly any of the features that this plugin has. It's one of the most annoying things to have happen. Can we please get some eyes on this issue? I haven't worked on any VSCode plugins, or I'd try to tackle it myself...which I may end up having to do I guess.

**Comment by karlhorky** [comment]
@billrobclark did you try out [amVim](https://marketplace.visualstudio.com/items?itemName=auiworks.amvim)? This seems to be an alternative.

I'm also having this issue. I have to undo all the time for this.

I have some settings configured, like `vim.mouseSelectionGoesIntoVisualMode`, `editor.wordWrap` and `window.clickThroughInactive`:

```
{
  "workbench.startupEditor": "newUntitledFile",
  "workbench.activityBar.visible": false,
  "editor.wordWrap": "on",
  "editor.minimap.enabled": false,
  "editor.cursorBlinking": "solid",
  "editor.renderIndentGuides": false,
  "prettier.eslintIntegration": true,
  "editor.formatOnType": false,
  "javascript.format.enable": false,
  "editor.formatOnSave": true,
  "files.autoSave": "onFocusChange",
  "editor.folding": false,
  "explorer.openEditors.visible": 0,
  "workbench.colorCustomizations": {
    "statusBar.background": "#303030",
    "statusBar.noFolderBackground": "#222225",
    "statusBar.debuggingBackground": "#511f1f"
  },
  "vim.useSystemClipboard": true,
  // Fix moving down full lines on word wrapped lines https://stackoverflow.com/a/46436056/1268612
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["j"],
      "after": ["g", "j"]
    },
    {
      "before": ["k"],
      "after": ["g", "k"]
    },
    {
      "before": ["down"],
      "after": ["g", "j"]
    },
    {
      "before": ["up"],
      "after": ["g", "k"]
    }
  ],
  "files.trimTrailingWhitespace": true,
  "editor.tabSize": 2,
  "workbench.editor.tabCloseButton": "off",
  "eslint.alwaysShowStatus": true,
  "flow.useNPMPackagedFlow": true,
  "workbench.editor.tabSizing": "shrink",
  "window.newWindowDimensions": "maximized",
  "workbench.editor.showIcons": false,
  "explorer.confirmDragAndDrop": false,
  "editor.glyphMargin": false,
  "window.clickThroughInactive": false,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "workbench.editor.closeEmptyGroups": false,
  "javascript.validate.enable": false,
  "vim.mouseSelectionGoesIntoVisualMode": false,
  "editor.formatOnSaveTimeout": 5000,
  "prettier.singleQuote": true,
  "[markdown]": {
    "files.trimTrailingWhitespace": false
  },
  "search.quickOpen.includeHistory": false
}
```

[dotfiles: settings.json](https://github.com/karlhorky/dotfiles/blob/7471dd67b1f973d98338c22eba2e2568a7d3550e/settings/Library/Application%20Support/Code/User/settings.json)

And also some other extensions installed:

```
code --install-extension PeterJausovec.vscode-docker
code --install-extension esbenp.prettier-vscode
code --install-extension kirozen.wordcounter
code --install-extension vscodevim.vim
code --install-extension sysoev.vscode-open-in-github
code --install-extension flowtype.flow-for-vscode
code --install-extension asvetliakov.snapshot-tools
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-vsliveshare.vsliveshare
```

[dotfiles: install script](https://github.com/karlhorky/dotfiles/blob/dca38a88de6e01f2a3408bd50c24f442b6327688/fresh_install/brew_install.sh#L85-L93)

**Comment by esetnik** [comment]
@jpoon can we get some eyes on this? It's still happening in v0.17.2

**Comment by billrobclark** [comment]
@karlhorky I haven't tried amVIm, but I will give it a go and see how it is. I'd really love for this issue to be addressed in this plugin though. This has been open for over 2 months.

**Comment by jpoon** [comment]
Are there repro steps that folks can share?

**Comment by billrobclark** [comment]
@jpoon it's pretty random, hard to give steps. It seems like when a file tab gets focused and you're in insert mode and you don't move the mouse at all and hit delete it deletes characters from a completely different location. But, it's definitely random I've tried to get repro steps, but it's too random.

**Comment by karlhorky** [comment]
For me it has happened with <kbd>backspace</kbd> in insert mode and if I remember correctly, also <kbd>x</kbd> in command mode.

Next time it happens I'll try to come up with more exact repro steps.

...If I remember correctly though, the original description of this issue is correct in that it has to do with switching back to VS Code from another app:

> When switching from one app to VSCode when VIM was in insert mode and I delete some text...

**Comment by karlhorky** [comment]
@thscott 👍 Yep, that does it for me too! Here's a gif:

![kapture 2019-01-23 at 17 50 49](https://user-images.githubusercontent.com/1935696/51622734-8665ed80-1f37-11e9-85ed-3498b7e7b3e3.gif)
