### ISSUE TITLE
quickfix/compiler error key binding

### ISSUE THREAD

**Issue by aciccarello** [VSCodeVim/Vim#3158]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use a vim command to list/navigate compiler errors.

**Describe the solution you'd like**
Commands can be mapped to actions on VS Code's problem window.

- `:copen` workbench.actions.view.problems
- `:cn[ext]` editor.action.marker.nextInFiles
- `:cp[revious]` editor.action.marker.prevInFiles
- `:ccl[ose]` focus problems panel and close

Within the problems panel allow j/k navigation

**Describe alternatives you've considered**
I've tried setting a custom key binding but the command parser errors out.
```json
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [":copen"],
            "commands": ["workbench.actions.view.problems"]
        }
    ]
```
https://github.com/VSCodeVim/Vim/blob/00bb9af44e0679706630f9d7ce5a43a552a67e15/src/cmd_line/parser.ts#L57-L59

A broader solution would be to allow custom command mappings without triggering an `E492` error.

**Additional context**

[Vim Quickfix documentation](http://vimdoc.sourceforge.net/htmldoc/quickfix.html)

**Comment by lorenzleutgeb** [comment]
I use `ge` as a mnemonic for "go to error":
```json
{
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["g", "e"],
            "commands": [
                "editor.action.marker.nextInFiles"
            ]
        }
    ]
}
```

However, I also attempted to have a command (`:errors`, `:problems` or similar) to map to `workbench.actions.view.problems` but was unable to configure this. I did not understand how to register a custom command in VSCodeVim. In Vim, this would be possible through the command [`:command`](https://vimhelp.org/usr_40.txt.html#40.2).
