### ISSUE TITLE
"jk","kj" remap to <esc>

### ISSUE THREAD

**Issue by bodgergely** [VSCodeVim/Vim#3159]
I am not able to remap multiple things to the same thing.
For example I want to be able to just tap on both keys('j','k') without paying attention to the order to exit insert mode.

The below does not assign BOTH jk and kj to ESC.
`
"vim.insertModeKeyBindings": [
        {
            "before": ["j", "k"],
            "after": ["<esc>"]
        },
        {
            "before": ["k", "j"],
            "after": ["<esc>"]
        },
    ]
`

I would like to be able to do:
`
imap jk <esc>
`
`
imap kj <esc>
`
Is there any chance of this feature being implemented?

For me this is a serious issue due to muscle memory...

**Comment by vinliao** [comment]
You might wanna try mapping it to "<Esc>" instead of "<esc>"

**Comment by jpoon** [comment]
What does https://github.com/VSCodeVim/Vim#debugging-remappings output? 

> You might wanna try mapping it to "<Esc>" instead of "<esc>"

That shouldn't matter. It should be case-insensitive, unless we have a bug (which is possible, but not probable).

In an effort to keep the issue count sane, I'm closing this issue. Feel free to re-open if the above docs don't prove helpful.
