### ISSUE TITLE
Is there a way to toggle the side and bottom bar?

### ISSUE THREAD

**Issue by vinliao** [VSCodeVim/Vim#3163]
**Is your feature request related to a problem? Please describe.**
Without using the vim plugin, the side and bottom bar can be toggled by using ctrl+b and ctrl+j respectively. The shortcuts doesn't seem to work when I'm using vim plugin.

**Describe the solution you'd like**
I want to toggle the side and bottom bar by using a keyboard shortcut. Especially after finish debugging.

**Describe alternatives you've considered**
Right now I'm closing the side and bottom panel by using the mouse, which defeats the entire purpose of using vim.

**Comment by epeli** [comment]
It's because you have `useCtrlKeys` set to true. Change it to false or rebind the toggle keys something else (which is what I did).

**Comment by J-Fields** [comment]
Yes. You can also use `when` clauses on keybindings to limit their scope.
