### ISSUE TITLE
map <C-h> to <C-o>h  is not working 

### ISSUE THREAD

**Issue by elsonwx** [VSCodeVim/Vim#3164]
I want to move when in vim insert mode.So I want to map `<C-h>` to `<C-o>h`, but it's not working.
```json
"vim.insertModeKeyBindings": [
    {
      "before": ["<C-h>"],
      "after": ["<C-o>","h"]
    }
  ]
```
the same as `<C-j>`,`<C-k>`,`<C-l>`

**Comment by jpoon** [comment]
Have you taken a look at https://github.com/VSCodeVim/Vim#debugging-remappings? 

In an effort to keep our issue count sane, I'm closing this issue. If the above docs don't resolve your issue, feel free to re-open.
