### ISSUE TITLE
editor.wordSeparators setting is ignored

### ISSUE THREAD

**Issue by alzedd** [VSCodeVim/Vim#3166]
I use to consider ```this_example``` two words, because a word separator for me is the underscore.
Tried to change **editor.wordSeparators** but it was completely ignored, since I found later that there is another setting **vim.iskeyword** that does basically the same.

Is there a way to add a setting to use the default editor.wordSeparators instead a duplicate setting?

**Comment by jpoon** [comment]
History Lesson: We had `vim.iskeyword` before `editor.wordSeparator` was introduced.

Although our ROADMAP (https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#options), states:

✅ | iskeyword (isk) | @,48-57,_,128-167,224-235 | keywords contain alphanumeric characters and '_'. If there is no user setting for iskeyword, we use editor.wordSeparators properties.
-- | -- | -- | --

That seems completely false looking at the code. Don't see anywhere where we are looking at the editor.wordSeparator config.

**Comment by pkrefta** [comment]
Thanks for your work @jpoon
