### ISSUE TITLE
$ (shift+4) does not go to end of line in javascript

### ISSUE THREAD

**Issue by shelmire** [VSCodeVim/Vim#3172]
**Describe the bug**
Using $ (shift+4) does not go to end of line in javascript, but does in other types of files.

**To Reproduce**
1. Install VSCodeVim.
2. Open Javascript file (.js, vs code has type as Babel Javascript).
3. Go to any line and type $.
4. You are now in insert mode and have inserted a $.

**Expected behavior**
The cursor should be at the end of the line, as it is in other types of files.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 0.16.12
- VSCode version: 1.28.2
- OS: Windows 10

**Additional context**
This can be resolved by explicitly adding the keybinding:

```
{
  "key": "shift+4",
  "command": "extension.vim_end",
  "when": "editorTextFocus && vim.active && !inDebugRepl && vim.mode != 'Insert'"
}
```
It is unclear why this does not work by default, however.

**Comment by jaredmcateer** [comment]
I was unable to reproduce this with just the VsCodeVim and Babel Javascript extensions. `$` takes me to the end of line without leaving normal mode as expected.

**Comment by shelmire** [comment]
I was able to reproduce this on my MBP. I narrowed it down to a conflicting extension, "Auto Add Brackets in String Interpolation". It is unclear why that extension causes the conflict, as it occurred in all contexts, and only in js, while the extension supported other languages. Anyway, I'm closing this since it's not caused by this extension (though maybe it will help another person).
