### ISSUE TITLE
Status bar colour - settings sync

### ISSUE THREAD

**Issue by sho-87** [VSCodeVim/Vim#3181]
Currently when switching modes the plugin will change the following for every mode change:

```
    "workbench.colorCustomizations": {
        "statusBar.background": "#5f00af",
        "statusBar.noFolderBackground": "#5f00af",
        "statusBar.debuggingBackground": "#5f00af"
    }
```

As discussed [here](https://github.com/shanalikhan/code-settings-sync/issues/553), this gets very messy when using auto upload in settings sync because the gist is updated all the time. Is there a way around this with this plugin, so the `settings.json` file isnt updated on mode change? Or is that currently the only way to set the statusbar colour in VScode?

**Comment by jpoon** [comment]
This is currently the only way to update the statusbar colour with VSCode hence the constant change in the `settings.json`.

Other related discussions: https://github.com/VSCodeVim/Vim/issues/2948

**Comment by ribeirompl** [comment]
Just a workaround for Settings Sync users, you can add a comment in the settings.json file to ignore a particular section. See [Settinds Sync Pragmas](https://github.com/shanalikhan/code-settings-sync/wiki/Sync-Pragmas).
