### ISSUE TITLE
Yank breaks after undo

### ISSUE THREAD

**Issue by mchong-teal** [VSCodeVim/Vim#3199]
**Describe the bug**
Yank -> undo -> paste results in pasting some state after undo, rather than pasting what was yanked.jjjj

**To Reproduce**

1.  Make a file with a bunch of lines
2.  Delete/add some lines
3.  Yank a line in the middle with YY
4.  Undo so that the line you copied is now different
5.  Paste the line you copied before the undo

**Expected behavior**
Paste should paste the line I copied.

**Screenshots**

**Environment (please complete the following information):**

- Extension Name: vim
- Extension Version: 0.16.12
- OS Version: Linux x64 4.15.0-36-generic
- VSCode version: 1.28.2

**Comment by J-Fields** [comment]
I'm not able to reproduce. If this is still an issue, can you re-create an exact reproduction example?

**Comment by J-Fields** [comment]
Closing as this is an old issue which I'm unable to reproduce. Let me know if you're still seeing this.
