### ISSUE TITLE
when use / searching, not support to match a whole word 

### ISSUE THREAD

**Issue by zhangshengping** [VSCodeVim/Vim#3200]
I want to search a whole word like "Hello".
I use the cmd `/\<Hello\>` ,but it not works.

**Describe the bug**

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by J-Fields** [comment]
You can use `\b` to detect a word boundary (in your example, `/\bHello\b`). This is how `*` is implemented. As far as I can tell, javascript's regex engine does not support `\<` and `\>`.

**Comment by J-Fields** [comment]
Closing in favor of #3996
