### ISSUE TITLE
Feature Request: Make <C-n> and <C-p> work like up and down arrow keys, in quick open. 

### ISSUE THREAD

**Issue by DevotionGeo** [VSCodeVim/Vim#3205]
## Feature Request.

VSCodeVim is a pure joy to use with VSCode. Thank you for this extension and its maintenance. 

I love to scroll through auto-completion options list by pressing Ctrl n and Ctrl p instead of taking my hand to the arrow keys (which often reside at different positions in different keyboards).

I'd love to have the same functionality (of using Ctrl n and Ctrl p instead of the arrow keys) while scrolling through quick open's files or command list. 

thank you!

**Comment by KryDos** [comment]
hey @DevotionGeo, your keybindings are pretty ok-ish. If you want to make them work as up and down arrow keys you may use `workbench.action.quickOpenSelectPrevious` or `workbench.action.quickOpenSelectNext`. 

Like this: 

```
    {
        "key": "ctrl+n",
        "command": "workbench.action.quickOpenSelectNext",
        "when": "inQuickOpen"
    },
    {
        "key": "ctrl+p",
        "command": "workbench.action.quickOpenSelectPrevious",
        "when": "inQuickOpen"
    }
```

This will prevent vscode from navigating to a selected file when ctrl is released.

**Comment by DevotionGeo** [comment]
Thank you @KryDos, that's what I needed!
