### ISSUE TITLE
Disable key ´ on normal mode

### ISSUE THREAD

**Issue by ruimfernandes** [VSCodeVim/Vim#3208]
**Describe the bug**
I've set an VS Code shortcut to `´` key. But when I press it, the shortcut works but vim does this weird thing. Is it possible to ignore that key behaviour when in normal mode?

![vimbug](https://user-images.githubusercontent.com/18558899/48490386-34a93480-e81d-11e8-99b7-34e36407ecf9.gif)

 

**To Reproduce**

1.  Normal mode
2.  Press ´

**Expected behavior**
Nothing happens when I press ´. 

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 0.16.12
- VSCode version: 1.29.0
- OS: macOS High Sierra 10.13.6

**Comment by jpoon** [comment]
The behaviour of two backticks is described by VIM as:

```
''  ``                  To the position before the latest jump, or where the
                        last "m'" or "m`" command was given.  Not set when the
                        :keepjumps command modifier was used.
                        Also see restore-position.
```

If you don't want vim to handle certain keys, see `vim.handleKeys` (https://github.com/VSCodeVim/Vim#vscodevim-settings)
