### ISSUE TITLE
Show vim commands during zen mode

### ISSUE THREAD

**Issue by emanpatricio** [VSCodeVim/Vim#3216]
I'm now always working in zen mode and kinda irritating every time I issue a :[comman] /[search] I can't see what I'm typing because of the status bar is not showing.

It will be great if we can show the vim command as an overlay in the screen.

**Comment by dsschnau** [comment]
If you turn 'Hide Status Bar' off in Zen mode settings, you can see the status bar in Zen mode (along with Vim stuff).

![Hide Status Bar Settings](https://i.imgur.com/BBsVKed.png)

![Zen mode editing with status bar](https://i.imgur.com/ezUkTO2.png)

**Comment by jpoon** [comment]
This is addressed on the FAQ section of our README: https://github.com/VSCodeVim/Vim#-faq.
