### ISSUE TITLE
Support yank from command line

### ISSUE THREAD

**Issue by Shaddy** [VSCodeVim/Vim#3219]
There are many `vim` useful commands such as temporal yank from a relative line.

`:-5y2`

Yank two lines from -5 lines above the current line. Currently, Vscodevim doesn't support any kind of such syntax. Would be possible to support it?

**Comment by esetnik** [comment]
Your example works fine for me in Vscodevim. I tested using the following:

```
this is a test file
this is another test


i'm on line 5
i'm on line 6

```

Starting with the cursor at line 6 and typing `:` (`<shift>+;`) to enter command line mode (you can see you're in it at the very bottom of the editor. Then type `-5y2<return`. The correct lines were yanked.

<img width="184" alt="screen shot 2018-11-28 at 9 59 11 am" src="https://user-images.githubusercontent.com/664434/49160287-6e396f80-f2f4-11e8-80cc-b3431d7c4d8a.png">

**Comment by Shaddy** [comment]
I use <shift>+":" (I use a ESP Keyboard layout) and when I do it, with or without "|" always throws this message.

![image](https://user-images.githubusercontent.com/247221/49303019-e8bae880-f4c8-11e8-9ea4-2a5ae2c50b09.png)

**Comment by janhesters** [comment]
Can confirm this doesn't work. Wanted to do `:9,11y<enter>`, but I get the same error:

<img width="214" alt="screenshot 2018-12-24 at 11 09 57" src="https://user-images.githubusercontent.com/31096420/50396805-84f4aa00-076c-11e9-96f0-88732e4308b8.png">

**Comment by jpoon** [comment]
I haven't tried this myself, but it should work with neovim?

**Comment by adeperio** [comment]
I just tried yank (yy) and also not getting any love for this. Is this on the roadmap for support? Also does anyone know if there is a list of supported/ unsupported vim features in this extension? Thanks!

**Comment by ecbrodie** [comment]
I'm running into this issue too, quite simple when I'm trying to yank a single line by number. I am using plain-old VIM, not neovim.

```
:7y
```

Will result in the error:

```
E492: Not an editor command. 7y
```

**Comment by runrig** [comment]
My most common form of yank/paste does not work:
1. Go to line, 'ma' to mark line as mark a.
2. Move down some number of lines.
3. Enter ":'a,. ya a" to say "from mark a to current line, yank into register a"
4. move to destination.
5. Enter: "ap  (paste contents of register a).

**Comment by J-Fields** [comment]
@runrig Does this work with neovim integration? Implementing commands which currently work with neovim is not a high priority at the moment.

**Comment by runrig** [comment]
No, it does not work with neovim.

**Comment by ioDiken** [comment]
Why was this closed if it still isnt functional? I'd love to be able to use `:y4`, and this works if its not a command - but I have a special use case where I only want to use vim commands without using vim as an editor.

**Comment by J-Fields** [comment]
@ioDiken Just opened #6995
