### ISSUE TITLE
vim插件导致工作区无法输入

### ISSUE THREAD

**Issue by Aonther** [VSCodeVim/Vim#3225]
Issue Type: <b>Bug</b>

1. 安装vim插件
2. 复制一个单词
3. 此时工作区执行任何操作都没有反应，只有快捷键操作

Extension version: 0.16.13
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by zhuzisheng** [comment]
Hi Aonther,

Can you try to upgrade the version first?
The latest version is 0.17.3.
I can't reproduce the same issue on the latest version.
you can try with the latest version and let me know whether the issue remains.

请先升级版本，当前最新版是0.17.3。
我无法在最新版本上重现你描述的问题。
升级后请告知在最新版本上是否还有同样的问题，以及如何才能复现。
