### ISSUE TITLE
g Ctrl+A column increment

### ISSUE THREAD

**Issue by 0b01** [VSCodeVim/Vim#3226]
In Vim 8, the first number in a selection can be incremented by pressing Ctrl-A. If the selection covers several lines, the first number in the selection on each line is incremented. Alternatively, numbers in a selection covering several lines can be converted to a sequence by typing g Ctrl-A. For example, start with the following line:

my_array[0] = 0;
Then copy it using Y6p (copy the line and paste it six times). The result is:

my_array[0] = 0;
my_array[0] = 0;
my_array[0] = 0;
my_array[0] = 0;
my_array[0] = 0;
my_array[0] = 0;
my_array[0] = 0;
With the cursor on the first 0 in the first line, start a blockwise select by pressing Ctrl-V (or Ctrl-Q if you use Ctrl-V for pasting). Move the cursor down to select the first column of zeros, then press g Ctrl-A. Using Vim 8, that will give:

my_array[1] = 0;
my_array[2] = 0;
my_array[3] = 0;
my_array[4] = 0;
my_array[5] = 0;
my_array[6] = 0;
my_array[7] = 0;
Vim 7 and earlier need a script or a macro to create a sequence.

**Comment by Oxyriser** [comment]
I have the same issue as well, any update on this?

**Comment by hagabaka** [comment]
[vscode-progressive-increment](https://github.com/narsenico/vscode-progressive-increment) provides this feature, and has been working for me. I think it would be possible to add a vim key binding to make it trigger on `g<C-a>` but I don't know how yet.
