### ISSUE TITLE
<C-w> copies word, seems all <C> command unexpectedly copies.

### ISSUE THREAD

**Issue by yifanchen** [VSCodeVim/Vim#3229]
**Describe the bug**
When setting "Use system clipboard" selected, <C-w> command copy the word, same thing with <d-d>.

**To Reproduce**

1.  Go to setting check "Use System Clipboard"
2.  Find a word and run <C-w>
3.  Hit `ESC`.
4.  Hit `p`.

**Expected behavior**
When setting "Use system clipboard" selected, <C-w> command should change the word not copy the word.

**Screenshots**

**Environment (please complete the following information):**

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 755,
		"activateCallTime": 7,
		"activateResolvedTime": 512,
		"activationEvent": "*"
	}
}
```

- Extension (VsCodeVim) version:
- VSCode version: 1.29.1
- OS:10.14.1

**Additional context**
This issue has been out there for a while, isn't it?

**Comment by yifanchen** [comment]
still an issue.

**Comment by yifanchen** [comment]
I've found a workaround to this issue:

**Comment by J-Fields** [comment]
@yifanchen Can you still reproduce this?

**Comment by yifanchen** [comment]
@J-Fields Yep, it persists.

**Comment by J-Fields** [comment]
By `<C-w>` do you mean `cw`? As in "change word"? By default in vim this does copy to the default register

**Comment by yifanchen** [comment]
@J-Fields Thanks for pointing it out. I didn't know that <C> does copy as well.
