### ISSUE TITLE
Motions bug

### ISSUE THREAD

**Issue by dxcqcv** [VSCodeVim/Vim#323]
I found 2 other bug, first, number+gg no work, like 5gg wanna go to line 5, but 5G is work;

and scond, the line number is great than go to line number, like 5G will go to line 6. sound like command from zero base but line number is from one base, I guess.

**Comment by johnfn** [comment]
Neat, I didn't know about number gg. I'll get to both of these later today.

**Comment by johnfn** [comment]
Done!

**Comment by dxcqcv** [comment]
GJ, and I found other bug about motions, backspace only can go to beginning of line, but cannot backspace to previous line, so weird.

**Comment by johnfn** [comment]
Yeah, I've got an issue open for that one: https://github.com/VSCodeVim/Vim/issues/320

Hope to get to it tomorrow!
