### ISSUE TITLE
'gf' on file fails, says file does not exist, but it does.

### ISSUE THREAD

**Issue by robjac** [VSCodeVim/Vim#3233]
**Describe the bug**

trying to `gf` on a relative path/file/import 
Fails every time for me. VscodeVim says the file does not exist, but it does. I can use the file directory and mouse to click the file to open.  

**Expected behavior**
gf on a path/file/import, should open an editor with the file my cursor was on.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**
Why is this still an issue -- it has been patched a few times. commits that fixed this have been merged. there are lots of closed tickets regarding this, and yet I'm still seeing frequent intermittency with gf.

**Comment by titouancreach** [comment]
Maybe it's related or not (if not, I can create an other ticket). 

The problem that I have with `gf` is that it didn't resolve javascript or typescript file.   
In javascript it's a common practice to import a file without specifying the extension of the file (.js, .jsx, .ts...).

```javascript
import {myModule} from './myFile'
```

 VSCode doesn't have any trouble to open the file when I "Ctrl+Click" on the filename. But when I type: "gf", it says the file doesn't exist. 

Would it be better to map the same behavior as Ctrl+click when `gf` ?

**Comment by bapidey678** [comment]
Why I should ./ before any file name? Just a little question, come'n.

**Comment by J-Fields** [comment]
> Why I should ./ before any file name? Just a little question, come'n.

@bapidey678 would you mind creating a separate issue?
