### ISSUE TITLE
渴求：在Normal模式下，屏蔽中文输入法. In Normal mode, Chinese input will break the vim experience! Please try to stop Chinese input while in Normal mode :)

### ISSUE THREAD

**Issue by Catzeromeio** [VSCodeVim/Vim#3237]
因为工作环境的需要，没有办法完全不使用中文，所以请求支持

**Comment by insideyiqi** [comment]
https://github.com/VSCodeVim/Vim#use-im-select

**Comment by Catzeromeio** [comment]
> https://github.com/VSCodeVim/Vim#input-method

可以了，非常感谢

**Comment by yifanchen** [comment]
在中文输入法的情况下，在 intergrated terminal 里面，切换（shift) 到中文，只能打出大写字母，你们有这个问题吗？
