### ISSUE TITLE
Remapping to external commands?

### ISSUE THREAD

**Issue by Astrantia** [VSCodeVim/Vim#3238]
How would I remap to F4 to make?
In vim you would do this like:  `nnoremap <F4> :make!<cr>`

**Comment by Astrantia** [comment]
@jpoon can this issue get addressed?

**Comment by jpoon** [comment]
Have you tried https://github.com/VSCodeVim/Vim#viminsertmodekeybindingsvimnormalmodekeybindingsvimvisualmodekeybindings?

**Comment by Astrantia** [comment]
@jpoon `make` would be an external command that vscode doesn't have a control over like git right? So how would I rebind a key for an external command `make` with args `build` as an example?

**Comment by jpoon** [comment]
You can try this: https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks

So either keybinding at the VSCode level (which should work according to their docs) or with VSCodeVim (which in theory should work as we just delegate it back to VSCode). 

Let me know what ends up working. Be good to update our docs with your findings.

**Comment by jpoon** [comment]
Being a bit more explicit of what I mean:

```
    "vim.<whatever-mode-you-want-to-rebind>": [
        {
            "before": [
                "<an-array-of-keys>"
            ],
            "commands": [
                {
                    "command": "workbench.action.tasks.runTask",
                    "args": "make",
                }
            ]
        }
    ]
```
