### ISSUE TITLE
Search mode deletes characters in document on backspace

### ISSUE THREAD

**Issue by rightaway** [VSCodeVim/Vim#3239]
**Describe the bug**

When you enter `/` to get into search mode and type a few characters, then press backspace to delete the characters to change the search term, instead of deleting the characters in the search term it deletes the characters in the document.

**Expected behavior**

It should delete the characters in the search term and not change the document at all.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.13
- VSCode version: 1.29.1
- OS: linux

**Comment by typeundefined** [comment]
I face the same issue at my machine.

-    Extension (VsCodeVim) version: 0.16.13
-    VSCode version: 1.29.1
-    OS: Windows 10

**Comment by karambaq** [comment]
Same:

- Extension (VsCodeVim) version: 0.16.13
- VSCode version: 1.29.1
- OS: MacOs Mojave 10.14

**Comment by goek-han** [comment]
Same:

- Extension (VsCodeVim) version: 1.0.2(21019-01-16)
- VSCode version: 1.30.2
- OS: Linux x64 4.15.0-43-generic (Ubuntu 18.04)

**Comment by haingdc** [comment]
same issue, Im in windows. So I use shift+backspace instead for workaround. Or add this to keybinding:
```
{
    "key": "backspace",
    "command": "extension.vim_shift+backspace",
    "when": "editorTextFocus && vim.active && vim.use<shift+BS> && !inDebugRepl && vim.mode == 'SearchInProgressMode'"
}
```

**Comment by J-Fields** [comment]
Hmm - I can't reproduce this. It does seem `<C-BS>` does something comparable, though.

**Comment by powellnorma** [comment]
For me, the fix was:

Ctrl+Shift+P -> "Preferences: Open Keyboard Shortcuts"
For `extension.vim_backspace`, set the key to "backsapce"

In json:

```json
{
	"key": "backspace",
	"command": "extension.vim_backspace"
}
```
