### ISSUE TITLE
For easy motion plugin, allow user to remap leader key.

### ISSUE THREAD

**Issue by 9527KGG** [VSCodeVim/Vim#3244]
**Is your feature request related to a problem? Please describe.**
In my default vim, I  remap easy motion key from \<leader\>\<leader\> to \<leader\>, which provides me better efficiency.

**Describe the solution you'd like**
Allow user to remap leader key. Basically, add support for "map *** \<Plug\>(easymotion-prefix)" as normal vim easy motion.

**Describe alternatives you've considered**
NA

**Additional context**
NA

Thanks.

**Comment by jpoon** [comment]
You can remap leader using `vim.leader` (see https://github.com/VSCodeVim/Vim#vim-settings).

To remap, `<leader> <leader>` to `<leader>`, you can try: https://github.com/VSCodeVim/Vim#key-remapping. 

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>"],
            "after": ["<leader>", "<leader>"],
        }
    ]
```

But this means you'll remap leader => 2x leader which might not be what you want?

**Comment by 9527KGG** [comment]
i see. Thanks.
