### ISSUE TITLE
Status bar in zen mode

### ISSUE THREAD

**Issue by XuJunran** [VSCodeVim/Vim#3245]
zen mode is a very very very nice thing.
But, I need the status bar to tell me sth while I'm working in zen mode.

Just give a choice to user -- show it or not, user decide.  Like in other mode.

**Comment by dsschnau** [comment]
Related issue: #3216

**Comment by dsschnau** [comment]
If you turn 'Hide Status Bar' off in Zen mode settings, you can see the status bar in Zen mode (along with Vim stuff).

![Hide Status Bar Settings](https://i.imgur.com/BBsVKed.png)

**Comment by XuJunran** [comment]
@dsschnau 3Q.
