### ISSUE TITLE
Insert standart vscode

### ISSUE THREAD

**Issue by rkunschke** [VSCodeVim/Vim#3248]
I would like the insert mode work more like in vanilla vscode. When i am in insert mode an copy pasting with strg+c and strg+v the vim extensions changes mode to visual mode. I would like a option to disable this so that i stay in insert mode when useing strg+c and strg+v etc...

**Comment by sw9** [comment]
I think the issue is that "Vim: Use Ctrl Keys" is not working correctly. Even when this setting is off, Ctrl-c still exits insert mode (in addition to copying the selected text). Also, Ctrl-d is still bound to scroll down in normal mode and delete indent in insert mode instead of multiple cursors.

**Comment by sw9** [comment]
If you add the following to your settings.json, I think it should accomplish what you want:

    "vim.handleKeys": {
        "<C-v>": false,
        "<C-c>": false
    },

**Comment by jpoon** [comment]
> When i am in insert mode an copy pasting with strg+c and strg+v the vim extensions changes mode to visual mode. I would like a option to disable this so that i stay in insert mode when useing strg+c and strg+v etc...

This is addressed on the FAQ section of our README: https://github.com/VSCodeVim/Vim#-faq.

>I think the issue is that "Vim: Use Ctrl Keys" is not working correctly. Even when this setting is off, Ctrl-c still exits insert mode (in addition to copying the selected text). 

To clarify, VSCodeVIM matches vanilla VIM in this regard. `ctrl+c` in insert mode takes you to normal mode. 

> Also, Ctrl-d is still bound to scroll down in normal mode and delete indent in insert mode instead of multiple cursors.

Again, this is addressed on the FAQ section of our README: https://github.com/VSCodeVim/Vim#-faq. Feel free to make improvements to our docs if they are not clear.
