### ISSUE TITLE
How to remap aI to ai?

### ISSUE THREAD

**Issue by Madd0g** [VSCodeVim/Vim#3249]
**Is your feature request related to a problem? Please describe.**
Since I don't use pythonic languages `<operator>ai` is pretty useless to me, but `<operator>aI` is cool, but harder to type, how do I replace one with the other?

**Describe alternatives you've considered**
I tried putting:
```
        {
            "before": ["a", "i"],
            "after": ["a", "I"],
        }
```
and `"before": ["<operator>", "a", "i"]`

Neither worked.

**Comment by jpoon** [comment]
What does the debug output say: https://github.com/VSCodeVim/Vim#debugging-remappings?

**Comment by jpoon** [comment]
Closing as I haven't heard back. Feel free to re-open with new information.
