### ISSUE TITLE
Can't copy the text to other editors

### ISSUE THREAD

**Issue by kwebi** [VSCodeVim/Vim#3251]
**Describe the bug**
Can't copy the text to other editors #3251

I want copy the text to other editors
So I entry the insert mode, and I press Crtl+C, and open another editor, and press Ctrl+V
but, the text is different from the copied text

I use the `Windows10` and vscode and the Vim Plug-in for the latest version

but the IDEA'vim plug-in does't have the bug

**Comment by xconverge** [comment]
Did you enable useSystemClipboard?

**Comment by jpoon** [comment]
Please take a look at the README and the FAQ. Try these settings:

```
    "vim.useSystemClipboard": true,
    "vim.useCtrlKeys": true,
```
