### ISSUE TITLE
Replace within selection doesn't work with NeoVim enabled

### ISSUE THREAD

**Issue by knetworx** [VSCodeVim/Vim#3262]
**Describe the bug**
Attempting to do a replace within the current selection pops up an error with NeoVim enabled.

**To Reproduce**

1.  Select a chunk of text using Shift+V.
2.  Initiate a search (i.e. `:'<,'>s/DC_/DT_/`)
3.  Execute the search
4.  See error popup that just says "Vim: true"

**Expected behavior**
The replace should execute successfully.

**Screenshots**
![screen shot 2018-12-13 at 11 42 54 am](https://user-images.githubusercontent.com/3292803/49963871-01b29900-fece-11e8-82ef-79ba76595ecc.png)
![screen shot 2018-12-13 at 11 42 43 am](https://user-images.githubusercontent.com/3292803/49963878-05462000-fece-11e8-9543-aad4dd9440d4.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.16.14
- VSCode version: 1.29.1
- OS: MacOS Mojave 10.14.1

**Additional context**
Disabling NeoVim integration allows the search to execute correctly.

**Comment by dyllandry** [comment]
I am experiencing a very similar issue. With neovim enabled, the replace within selection function will replace a region earlier in the file than where I have selected. For example selecting to replace occurrences of "foo" lines 5 to 6 will replace occurences of "foo" in lines 2 to 3 and then stop. Disabling neovim fixes this.

**Comment by jasonoverby** [comment]
I am also experiencing this issue, and disabling Neovim integration  fixes it for me, as well.

**Comment by J-Fields** [comment]
Pretty sure this is no longer an issue, so I'm closing. Holler if I'm wrong

**Comment by knetworx** [comment]
Yeah, looks to be fixed for me now.
