### ISSUE TITLE
Support digraphs

### ISSUE THREAD

**Issue by FelipeLema** [VSCodeVim/Vim#3267]
Insert digraphs using `Ctrl-K` and two keys in insert mode.

This is fully documented in [`:help digraph`](https://github.com/neovim/neovim/blob/master/runtime/doc/digraph.txt).

It's been implemented from scratch in [Evil (Emacs) package](https://github.com/emacs-evil/evil/blob/82c65dcfe23aff3d764cafc78124d92940c5bd59/evil-digraphs.el).

Don't really care about the implementation or adding custom digraphs.

**Comment by FelipeLema** [comment]
I would implement it myself, but I couldn't find a starting place (I tried looking for tests for "ctrl-r in insert mode" and (consequently) "registers", but no go).

**Comment by jpoon** [comment]
Closed by #3407
