### ISSUE TITLE
The Vim plugin can not edit except i/a/s

### ISSUE THREAD

**Issue by milley** [VSCodeVim/Vim#3270]
Issue Type: <b>Bug</b>

When i update my gocode library and the Go plugin, i can not use vim on Visual Studio Code, the version of the Go plugin like this:
name: Go
ID: ms-vscode.go
describe: Rich Go language support for Visual Studio Code
version: 0.8.0
publisher: Microsoft
vs url: https://marketplace.visualstudio.com/items?itemName=ms-vscode.go

I can use the keymap i,s,a to update the text,but can not delete use backspace on insert mode or use dd/x on normal mode.

Extension version: 0.16.14
VS Code version: Code 1.30.0 (c6e592b2b5770e40a98cb9c2715a8ef89aec3d74, 2018-12-11T22:29:11.253Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (10.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|

</details>

**Comment by jpoon** [comment]
I code with the `go` language extension all the time and cannot repro your issue. What happens when you just run the VIM extension?

**Comment by milley** [comment]
In the normal mode, the h/j/k/l can't move cursor.In the insert mode, after
push the i/a/s, it can edit the doc but when push esc, can't use u to
cancel the edit section.

Jason Poon <notifications@github.com> 于2018年12月30日周日 下午4:03写道：

**Comment by jpoon** [comment]
As mentioned in my earlier comment, What happens when you just run the VIM extension?

What do you see in the developer console? https://github.com/VSCodeVim/Vim#debugging-remappings

**Comment by milley** [comment]
I found when i install the follow plugins it does not work:
名称: Debugger for Java
ID: vscjava.vscode-java-debug
说明: A lightweight Java debugger for Visual Studio Code
版本: 0.16.0
发布者: Microsoft
vs 市场链接: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug

名称: Java Dependency Viewer
ID: vscjava.vscode-java-dependency
说明: Manage Java Dependencies in VSCode
版本: 0.3.0
发布者: Microsoft
vs 市场链接: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency

名称: Java Extension Pack
ID: vscjava.vscode-java-pack
说明: Popular extensions for Java development and more.
版本: 0.5.0
发布者: Microsoft
vs 市场链接: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack

名称: Java Test Runner
ID: vscjava.vscode-java-test
说明: Run and debug JUnit or TestNG test cases
版本: 0.13.0
发布者: Microsoft
vs 市场链接: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test

名称: Language Support for Java(TM) by Red Hat
ID: redhat.java
说明: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
版本: 0.36.0
发布者: Red Hat
vs 市场链接: https://marketplace.visualstudio.com/items?itemName=redhat.java

名称: Maven for Java
ID: vscjava.vscode-maven
说明: Manage Maven projects, execute goals, generate project from archetype, improve user experience for Java developers.
版本: 0.12.1
发布者: Microsoft
vs 市场链接: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-maven

**Comment by milley** [comment]
When i set the loggingLevel to debug, it's ok now.Change is to error also works fine, thx very much!
