### ISSUE TITLE
kill run away vim commands

### ISSUE THREAD

**Issue by gforceg** [VSCodeVim/Vim#3273]
**Is your feature request related to a problem? Please describe.**
I think that sometimes I fat-finger a key or two and vscodevim interprets that as "repeat everything I just typed until the sun turns black." I haven't run into this in plain old vim but I suspect it's user error and probably related to some minor differences between vim and vim inside of vs code.

![wild-vim-commandgif](https://user-images.githubusercontent.com/14267747/50169225-6133ee80-02aa-11e9-9601-a6dbbe6ec34f.gif)

**Describe the solution you'd like**
I'd like to be able to press 'escape' and immediately stop the currently executing vim command. If there is a way to do this with my fist then that would be preferrable and more satisfying.

**Describe alternatives you've considered**
Drinking.

**Additional context**
Thanks for the excellent plugin.

**Comment by jpoon** [comment]
We should have `ctrl+c` abort the current command. Alternatively, be patient, grab a drink and wait until it finishes. From http://vimdoc.sourceforge.net/htmldoc/pattern.html#CTRL-C:

```
CTRL-C			Interrupt current (search) command.  Use CTRL-Break on
			MS-DOS |dos-CTRL-Break|.
			In Normal mode, any pending command is aborted.
```

**Comment by jpoon** [comment]
Actually, realize we have a long standing https://github.com/VSCodeVim/Vim/issues/1309 so going this in favor of #1309
