### ISSUE TITLE
s and S Key Commands Not Working

### ISSUE THREAD

**Issue by caseysiebel** [VSCodeVim/Vim#3274]
in command mode the s and S key commands don't do anything. I expect that when I press s in command mode, the character under my cursor should be deleted and then I should be in insert mode at the cursor location. But currently it's not doing anything.

https://stackoverflow.com/questions/53821721/vs-code-vim-plugin-in-command-mode-the-s-and-s-key-commands-dont-do-anything

**Comment by jpoon** [comment]
Can't repro. These are most definitely supported commands: https://github.com/VSCodeVim/Vim/blob/master/src/actions/commands/actions.ts#L2345.

**Comment by jpoon** [comment]
Closing this issue, but feel free to re-open if I am mistaken from my above comment.

**Comment by ELLIOTTCABLE** [comment]
For anybody else running across this — I accidentally enabled the `vim.sneak` option when I first installed VSCode-Vim; make sure you didn't too!

Set `"vim.sneak": false` in your `settings.json`.

**Comment by caseysiebel** [comment]
@ELLIOTTCABLE THANK YOU!

**Comment by rethab** [comment]
Ran into this as well, because I just copied the default config from the README. As I suspect that most people don't use sneak, I think it might make sense to not include that in the example.

WDYT @jpoon ? I'd be happy to draft a PR.

**Comment by jpoon** [comment]
Feel free to create a PR @rethab

**Comment by rethab** [comment]
@jpoon : https://github.com/VSCodeVim/Vim/pull/4619
