### ISSUE TITLE
Delay clearing of selection special registers (`'<` and `'>`) until a new selection is made

### ISSUE THREAD

**Issue by realh** [VSCodeVim/Vim#3284]
**Is your feature request related to a problem? Please describe.**
I often apply a number of replace operations to the same block of text, using `:'<,'>s`. Each time I replace one set of matching strings the selection gets cleared, and so do the `<` and `>` registers. I have to select the text all over again before making the next change.

**Describe the solution you'd like**
I would like the registers to be preserved until I select a new range. This is what the original vim and neovim do, so although the selection is cleared after making the first change, the registers "remember" it and you can  perform further operations on the same range of text without having to select it again.

**Comment by J-Fields** [comment]
This was fixed at some point
