### ISSUE TITLE
ge doesn't go to the previous line

### ISSUE THREAD

**Issue by sw9** [VSCodeVim/Vim#3285]
**Describe the bug**
ge doesn't go to the previous line.

**To Reproduce**
1.  open a text file
2. be in normal mode 
3.  repeatedly type ge until you're at the start of a line
4.  you don't go to the line before

**Expected behavior**
ge goes to the end of the word of the line before

**Environment (please complete the following information):**
- Extension Version: `0.17.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.30.1`

**Comment by jpoon** [comment]
Unable to repro. These are most definitely supported commands: https://github.com/VSCodeVim/Vim/blob/master/src/actions/motion.ts#L1258

**Comment by sw9** [comment]
The issue isn't that it's not implemented, but that it isn't implemented correctly.

Make a new file with the following lines:

```
test1 test2 test3
test4 test5 test6
```

Move your cursor to test[6]. continuously press ge. In VS Code, the cursor will stop at [t]est4 no matter how many times you press ge. In vim however, it'll continue on the line before test[3].

**Comment by jpoon** [comment]
Feel free to contribute: https://github.com/VSCodeVim/Vim/blob/master/src/actions/motion.ts#L1258.
