### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by youmengtian** [VSCodeVim/Vim#3289]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `0.16.14`
- OS Version: `Linux x64 4.19.8-2-MANJARO`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/wangyi/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by seven-linglx** [comment]
> * Issue Type: `Performance`
> * Extension Name: `vim`
> * Extension Version: `0.16.14`
> * OS Version: `Linux x64 4.19.8-2-MANJARO`
> * VSCode version: `1.30.1`
> 
> ⚠️ Make sure to **attach** this file from your _home_-directory: `/home/wangyi/vscodevim.vim-unresponsive.cpuprofile.txt` ⚠️
> 
> Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

Hi, how to get this file (vscodevim.vim-unresponsive.cpuprofile.txt) ?

**Comment by jpoon** [comment]
The time you spend providing details in your issue will be proportional to the time we [maintainers] will spend in debugging your issue.

Please provide more details/repro steps/anything that will be helpful (ie. fill out the issue template).
