### ISSUE TITLE
v0.17.1 prints `<tab>` string for every tab keystroke 

### ISSUE THREAD

**Issue by n1te1337** [VSCodeVim/Vim#3298]
**Describe the bug**
After updating to version `v0.17.1` VSCodeVim now prints the `<tab>` string for every tab keystroke. Tried with a clean vscode install without any other extensions or custom settings and still getting the issue. 

**To Reproduce**
Press the tab key.

**Expected behavior**
Print indentation instead of the `<tab>` string.

**Screenshots**
<img width="422" alt="screen shot 2018-12-28 at 6 41 33 pm" src="https://user-images.githubusercontent.com/1946858/50507127-3b8bbe00-0ad0-11e9-9da4-277d038c7a8a.png">

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: `v0.17.1`
- VSCode version: `1.30.1`
- OS: `OS X 10.14`

**Comment by ovx** [comment]
Having the same problem; Is there a way how to downgrade to a lower version?

**Comment by bi-qiang** [comment]
+1

**Comment by jpoon** [comment]
Very interesting. Definitely a regression.

You can install a different version if you select the gear button on the extension menu.

**Comment by zjw552048** [comment]
1.get vim-0.17.0.vsix from https://github.com/VSCodeVim/Vim/releases.
2.File>preference>settings>features, close extensions: Auto Update.

**Comment by n1te1337** [comment]
No worries @jpoon, at least there is a workaround. Thanks a lot for your hard work.

**Comment by ErikSandstedt** [comment]
I'm getting the same problem. Just started this morning.

**Comment by jpoon** [comment]
Update on it's way: https://travis-ci.org/VSCodeVim/Vim/builds/472936016

**Comment by n1te1337** [comment]
@jpoon fix confirmed, everything working as expected in `0.17.2`

**Comment by jpoon** [comment]
Good to hear. Thanks for the follow-up @n1te1337
