### ISSUE TITLE
gC-A` does not work in visual mode

### ISSUE THREAD

**Issue by rbhanot4739** [VSCodeVim/Vim#3300]
Given below text 
`<a href="#">Link 1</a>` 
So in regular vim if I press following sequence of keys yy3pVgctrl-A, I get the following output 
```
<a href="#">Link 2</a> 
<a href="#">Link 3</a> 
<a href="#">Link 4</a>
```

However if I do the same in VSCode, nothing seems to happen and numbers literally do not increment. Please note C-A and C-X does work just fine in normal mode.
So the issue is VSCodeVim Plugin is not recognizing the `g` command. Is this a known bug or am i missing something.

**Comment by hagabaka** [comment]
This is the same as #3226
