### ISSUE TITLE
Status Bar Color did not changed with the mode

### ISSUE THREAD

**Issue by Shad02w** [VSCodeVim/Vim#3316]
**Describe the bug**
The status bar did not change based on the vim mode.

the following config has been added to my settings.json
```
"vim.statusBarColorControl": true,
    "vim.useSystemClipboard": true,
    "vim.hlsearch": true,
    "vim.statusBarColors": {
        "normal": "#005252",
        "insert": "#789f00",
        "visual": "#ff37d8",
        "visualline": "#ff3b3d",
        "visualblock": "#86592d",
        "replace": "#ef5939"
   }
```
![insert](https://user-images.githubusercontent.com/6605655/50572655-8a529400-0dff-11e9-95be-db352d7acf20.png)
![vl](https://user-images.githubusercontent.com/6605655/50572675-05b44580-0e00-11e9-8506-c67e6b1f09c2.png)
![nomarl](https://user-images.githubusercontent.com/6605655/50572676-06e57280-0e00-11e9-97af-5aba63f26f59.png)

Now the status bar only indicates the mode by text but not the color of the whole bar. I also tried to copy the configuration to my settings.json under the workspace, but still the same.

**Environment**

- Extension (VsCodeVim) version:0.17.3
- VSCode version: 1.30.1
- OS: Windows 10 1803

**Comment by Hariama** [comment]
I experience the same problem.

**Comment by francybiga** [comment]
Same for me
