### ISSUE TITLE
Key bindings break in 0.17.1

### ISSUE THREAD

**Issue by danawoodman** [VSCodeVim/Vim#3317]
**Describe the bug**
Version `0.17.1` broke one of my keybindings for folding code. Prior to `0.17.1`, it worked as expected.

**To Reproduce**

1.  Install version `0.17.0`
2.  Install Dakara Fold Plus extension
3.  Add following to your `settings.json`

```json
  "vim.normalModeKeyBindings": [
    {
      "before": ["<leader>", "m"],
      "after": [],
      "commands": [
        {
          "command": "dakara-foldplus.levelAtCursor",
          "args": []
        },
        {
          "command": "editor.unfoldRecursively",
          "args": []
        }
      ]
    }
```

4.  Press `<leader> m` on a set of code blocks. All blocks but the current one you have highlighted should work.
5. Install `0.17.1` and do the above and nothing happens.

**Expected behavior**

Should fold all blocks but one with cursor. Instead does nothing.

**Screenshots**

How it should work:
![](https://cl.ly/85d2a1500cd4/Screen%20Recording%202019-01-01%20at%2001.52%20PM.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: any version from `0.17.1` and newer
- VSCode version: `1.30.1`
- OS: Mac OSX Mojave

**Comment by danawoodman** [comment]
Sorry, but there are 530 open issues so I must have missed it on my search

**Comment by jpoon** [comment]
No worries. Found it. https://github.com/VSCodeVim/Vim/issues/3307
