### ISSUE TITLE
Replacing with Neovim 0.3.2 enabled fails and require a VSCode restart

### ISSUE THREAD

**Issue by GuillaumeRochat** [VSCodeVim/Vim#3323]
**Describe the bug**
Replacing with Neovim enabled changes indentation (changed from 4 spaces to tabs in my case) and makes vim unresponsive, requiring to restart VSCode. Also, the ex command stays in the status bar as if it wasn't executed.

**To Reproduce**

1.  Enable Neovim
2.  Open any file with space indents and perform a full replace such as `:s/potato/carrot/g`
3.  Notice that the indent changed to tabs.
4.  Notice that the ex command is still appearing in the status bar
5.  Notice that navigating in a file using vim keybind no longer works.

**Expected behavior**
The text is successfully replaced with no other side effects.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.17.3
- VSCode version: 1.30.1
- OS: Linux 4.20.0
- Neovim: 0.3.2

**Additional context**
It only started happening after I updated to the latest version of Neovim (0.3.2) so it may be related to #3290. Does not happen on Neovim 0.3.1

**Comment by jpoon** [comment]
What does the debug console say? With the next version we'll be displaying errors as info boxes so it'll be more apparent I'd there is a setup error.

**Comment by GuillaumeRochat** [comment]
@jpoon would that be the console in Help > Toggle Developer Tools? If so, nothing appears in that console. In the process explorer, I can see the `nvim -u NONE -i NONE -N --embed` command and it says it's using 0mb of memory.

**Comment by jpoon** [comment]
You need to turn on debug logging. Its off by default. On my phone but it's something like vim.debug.logging

**Comment by GuillaumeRochat** [comment]
I don't see anything not normal. I changed the setting `vim.debug.loggingLevel` to `debug` : 

```
console.ts:134 [Extension Host] debug: ModeHandler: handling key=<Esc>.
console.ts:134 [Extension Host] debug: Remapper: find matching remap. keys=<Esc>. mode=Normal.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=:.
console.ts:134 [Extension Host] debug: Remapper: find matching remap. keys=:. mode=Normal.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=%.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=s.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=/.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=p.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=o.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=t.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=a.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=t.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=o.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=/.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=p.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=o.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=t.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=a.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=t.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=o.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=/.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=g.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=
.
```
The last one is a linebreak.

Could it be that nvim never replies and it's a blocking call? Let me know if there is anything else I can check to help, until then I'll work with neovim 0.3.1

**Comment by xconverge** [comment]
I can reproduce this after I upgrade for 0.3.1 to 0.3.3
