### ISSUE TITLE
ModeHandler: error handling key=<C-a>, err=TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by kenorb** [VSCodeVim/Vim#3332]
**Describe the bug**

The following error popup.

**To Reproduce**

It's not clear to what file it relates to.

**Expected behavior**

No error.

**Screenshots**

![image](https://user-images.githubusercontent.com/266306/50727863-03f8c380-1119-11e9-97bc-60584b601cc3.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.0.0
- VSCode version: 1.30.0
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- OS: Ubuntu Linux x64 4.18.0-13-generic

**Comment by kenorb** [comment]
I don't know what keypresses I used, noticed the error after a while. If this happen again, I'll update.

**Comment by xconverge** [comment]
I can repro this if I am at the end of the document! ```G<c-a>```
