### ISSUE TITLE
Unhandled rejection when using quokka.js extension

### ISSUE THREAD

**Issue by danstewart** [VSCodeVim/Vim#3333]
**Unhandled rejection when using quokka.js extension**
When using the [quokka.js extensions](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode) I get a `Unhandled rejection` error when the new file opens and each time I type a character.

**To Reproduce**

1.  Install Quokka.js
2.  `ctrl+shift+p` -> Quokka.js: New JavaScript File
3.  See error

```
Unhandled rejection. Promise [object Promise]. Reason: AssertionError [ERR_ASSERTION]: { uri: [Getter], fileName: [Getter], isUntitled: [Getter], languageId: [Getter], version: [Getter], isClosed: [Getter] == { uri: [Getter], fileName: [Getter], isUntitled: [Getter], languageId: [Getter], version: [Getter], isClosed: [Getter].
```

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.0.0
- VSCode version: 1.30.1
- OS: Fedoras 29

**Additional context**
Everything seems to work fine, it just keeps throwing the error.

**Comment by jpoon** [comment]
See this for context around these error messages. https://github.com/VSCodeVim/Vim/issues/3332#issuecomment-451683970

In terms of this error, we are subscribing to I handled rejections on the process. My theory is that all the extensions are run on the same process so with the extension that you installed, it's not handling this promise rejection and therefore we are displaying it as an error. I think the fix here is to remove the logging of unahndled rejections at the process level. There shouldn't be any negative side effects with this message.
