### ISSUE TITLE
can't support the command that can Indent multiple lines of code

### ISSUE THREAD

**Issue by BigBigWolf-AI** [VSCodeVim/Vim#3340]
vscode version：1.30.1
vscodevim version：1.0.1
issue：I can't Indent multiple lines of code by enter the following command:
m,n>
example: I want to indent the code of line 8 to line 20, then I used to enter the following command in vim:
:8,20>
it works well in vim but in vscodevim it just can't work. why ? I  think the command is common used in vim, why vscodevim do not support it?

**Comment by xconverge** [comment]
I would advise you try the neovim integration

https://github.com/VSCodeVim/Vim#neovim-integration

We delegate all : commands to neovim when enabled and setup to have better command support

**Comment by BigBigWolf-AI** [comment]
if I don't try the veovim integration, could you please tell me  the fastest way to Indent multiple lines of code ?

**Comment by xconverge** [comment]
```:8\n12>>```

But I would strong encourage you to try the neovim integration. We have stopped adding/implementing command line commands and instead delegate to neovim so that we have nearly perfect implementations and coverage
