### ISSUE TITLE
Prevent visual selection from going to default register after replacing it with yanked text

### ISSUE THREAD

**Issue by PabloDinella** [VSCodeVim/Vim#3343]
**Describe the bug**
Sorry if the title is not clear, this is my situation:

I have a yanked text with `y`. I want to place it over a visual selection, so it replaces the selected text. After I do it, the replaced text goes to the register, as if I pressed `c` or `y` or something, but I justed pressed `p` while in a visual selection. The next time I press `p` over a visual selection the text the gets pasted is not what I yanked first.

I didn't get this behavior before, is this a new default option? How to disable it? Or is it a bug?

**To Reproduce**

1.  Yank some text `y`
2.  Visually select some other text `v`
3.  Paste the text `p`
4.  Repeat 2 and 3, the pasted should be the last replaced text

**Expected behavior**
Yanked text shouldn't change

**Screenshots**
![bug](https://user-images.githubusercontent.com/2482730/50788319-397be900-12a0-11e9-9936-d7533fbc3087.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.1
- VSCode version: 1.30.0
- OS: Linux

**Comment by xconverge** [comment]
I personally remap p to pgvy

I think that this behavior is how vanilla vim works

**Comment by PabloDinella** [comment]
@xconverge yea, didn't realize this is vanilla's vim behavior. I was certain that this was different... Ty for the tip.
