### ISSUE TITLE
:set hlsearch? makes plugin freeze out

### ISSUE THREAD

**Issue by g0sk0** [VSCodeVim/Vim#3344]
Queried the status of hlsearch.

**To Reproduce**

1.  type :set hlsearch?

**Expected behavior**
Expected to get an error message but I actually got a popup telling me hlsearch was disabled. Sadly the editor became unresponsive too, so I had to reload the plugin.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.01
- VSCode version: 1.30.1
- OS: Microsoft Windows 10 Pro version 1803

**Comment by xconverge** [comment]
Are you using neovim integration by any chance?

**Comment by xconverge** [comment]
FYI if you had clicked the little X on the popup, everything would have resumed with no problems :)

I still just moved the reporting of the query to the status bar anyways, since I didnt want to need to use my mouse to close the window (even if it didnt block), and this was simplest

**Comment by g0sk0** [comment]
Excellent! Never ever hovered over those info popups before, didn't even know they were interactive. Also if for some reason you let it time out in cca 10s, you are stuck. As of the nvim integration: no, not using it.
