### ISSUE TITLE
Error handling key <C-d>: Illegal value for line

### ISSUE THREAD

**Issue by sobjornstad** [VSCodeVim/Vim#3345]
**Describe the bug**
When pressing `<C-d>` near the bottom of a file after pressing `G`, sometimes an error message appears:

    ModeHandler: error handling key=<C-d>. err=Error: Illegal value for `line`.

**To Reproduce**

1. Open a file.
2.  Press `G` to move to the very bottom of the file.
3.  Press `<C-d>`.
4.  The screen scrolls down half a screen, but the error also appears.

This doesn't happen with `<C-f>`. It also requires you to have pressed `G` before; if I scroll down to the bottom of the file any other way, the error doesn't occur. However, if you do press `G`, you can then move the cursor up to half a screen higher before pressing `<C-d>` and the error will still happen -- your cursor doesn't have to be on the very last line of the file.

**Expected behavior**
No error message occurs when the operation completed successfully.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.1
- VSCode version: 1.30.1
- OS: Windows 10.0.15063

**Additional context**
As I use both `G` and `<C-d>` a lot and have never noticed this issue before today, I am suspicious this is a regression introduced in 1.0.0 or 1.0.1.

**Comment by lorentzforces** [comment]
I also heavily use both `G` and `<C-d>` extensively, and first encountered this issue today. I haven't kept track of updates, but I strongly suspect that this was introduced in 1.0.1 due to the timing.

**Comment by jpoon** [comment]
I'm on mobile so excuse brevity. The changelog is always a good place to take a look. 

In v1.0.0, we now present errors as notification windows. These were previously outputted to console and not very discoverable. If you wish to continue living in bliss/ignorance of extension errors it's configurable. See the readme.

**Comment by jpoon** [comment]
In regards to this issue, there were no code changes in that area so aside from the presentation of the error, the side effect of the action should be the same.
