### ISSUE TITLE
<C-r> does not redo (opens recent menu).

### ISSUE THREAD

**Issue by robinvd** [VSCodeVim/Vim#3346]
**Describe the bug**
<C-r> does not redo the last undo

**To Reproduce**
1.  Type anything
2.  undo by pressing `u`
3.  try to redo by `<C-r>`
4.  the recent file menu is opened.

**Expected behavior**
the text should reappear.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.
No debug output when `<C-r>` is pressed.

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.0.1`
- OS Version: `Linux x64 4.19.13-200.fc28.x86_64`
- VSCode version: `1.30.1`

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 347,
		"activateCallTime": 3,
		"activateResolvedTime": 197,
		"activationEvent": "*"
	}
}
```

- Extension (VsCodeVim) version:
- VSCode version:
- OS: fedora

**Additional context**
settings are completely empty, with only vim installed.

**Comment by xconverge** [comment]
Do any control key combinations work? <C-v> to enter block mode, <C-a>/<C-x> to increment/decrement a number, <C-d>/<C-u> to scroll window

Do you remap your ctrl key at an os level to function or super or anything like that?

**Comment by robinvd** [comment]
Seems to be fixed without any action on my part, closing

**Comment by robinvd** [comment]
Kept having the issue, but not always so did not want to reopen the issue. Finallly found what the issue was:

I'm using kde, and set my keyboard layout using kde, this does not seems to change it completly. Thus vscode would pick up my keybinding keypresses in the system layout (instead of the window manager layout). Thus ctrl-r (for me), would be read as ctrl-p and open the recents menu. vim would thus not log anything as vscode would pick it up. In colemac a lot of the keys are the same, so i have never noticed it on other keybindings.

Using `"keyboard.dispatch": "keyCode"` will fix this as documented somewhere on the [website](https://github.com/Microsoft/vscode/wiki/Keybinding-Issues#troubleshoot-linux-keybindings)
