### ISSUE TITLE
Control status bar color in other modes

### ISSUE THREAD

**Issue by olivermicke** [VSCodeVim/Vim#3350]
Currently, when I'm either in search mode or `Surround Input` mode, the status bar color will be bright red `#ff0000` which is really distracting. I've searched through lots of config files and couldn't find the reason why it's displayed that way.

**Describe the solution you'd like**
I'd like to be able to change the status bar color in search or surround input mode or know why it is suddenly red for me.

It didn't always show that red color for me in these modes but reinstalling the extension and changing my settings around didn't help (obviously I don't use said color code anywhere in my settings).

**Comment by xconverge** [comment]
Do you have any of these settings on or configured?

https://github.com/VSCodeVim/Vim/blob/master/README.md#vim-airline

You can also just turn that setting off just to be sure

**Comment by olivermicke** [comment]
Yes, I do. As soon as I active only ``

**Comment by olivermicke** [comment]
Yes, I do.

As soon as I set `"vim.statusBarColorControl": true`, the problem occurs.

Just for the record, these are all my settings related to the extension:

```
"vim.statusBarColorControl": true,
  "vim.statusBarColors.visual": "#b55d02",
  "vim.statusBarColors.visualblock": "#a02236",
  "vim.statusBarColors.visualline": "#9C195B",
  "vim.substituteGlobalFlag": true,
  "vim.statusBarColors.replace": "#6f1f45",
  "vim.statusBarColors.insert": "#6d8400",
  "vim.statusBarColors.normal": "#007575",
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["S-Tab"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.outdentLines",
          "args": []
        }
      ]
    },
    {
      "before": ["Tab"],
      "after": [],
      "commands": [
        {
          "command": "editor.action.indentLines",
          "args": []
        }
      ]
    }
  ]
```

**Comment by mhaaz** [comment]
What is happening should be related to a VSCode updated. I have a similar issue when "turning off" VSCodeVim (not disabling it, but using the hot toggle). It is caused because the vscode color settings for the status bar are set to "undefined" whenever you switch to a mode that has no specific settings, or when you turn off the extension. My guess is just recently VS Code itself decided that for undefined status bar color settings, it would now show this red instead of just keeping the last used color setting.

**Comment by jpoon** [comment]
Fixed with https://github.com/VSCodeVim/Vim/pull/3380
