### ISSUE TITLE
`Ctrl-d` at bottom of file displays ModeHandler error

### ISSUE THREAD

**Issue by cmvanb** [VSCodeVim/Vim#3354]
**Describe the bug**
Pressing `Ctrl-d` while at the bottom of a file displays a ModeHandler error.

**To Reproduce**

1.  Open any file
2.  Navigate to bottom of file
3.  In normal mode, press `Ctrl-d`
4.  See error: `ModeHandler: error handling key=<C-d>. err=Error: Illegal value for line.`

**Expected behavior**
I expect not to see an error popup when using `Ctrl-d` at the bottom of a file.

**Screenshots**
![modehandling-error](https://user-images.githubusercontent.com/3225873/50962982-c0f97000-14cb-11e9-91e8-33dfe76663bc.png)

**Environment (please complete the following information):**
- Extension Version: `1.0.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.30.1`

**Comment by xconverge** [comment]
This was fixed on master in #3347
