### ISSUE TITLE
editor.occurrencesHighlight

### ISSUE THREAD

**Issue by vogler** [VSCodeVim/Vim#3357]
Issue Type: <b>Bug</b>

When the extension is enabled, the feature `editor.occurrencesHighlight` stops working (at least for OCaml using `vscode-reasonml`).
The gif shows how it works without the extension, and then what happens after enabling it (ignore the Cmd+D's - that's another issue):
![output_org](https://user-images.githubusercontent.com/493741/51047969-161bab80-15ca-11e9-80d5-7d8c215c709d.gif)

Extension version: 1.0.1
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|-psn_0_6936221|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by vogler** [comment]
I could narrow the problem down:
If I click on a word with the mouse, it still works. If I use the keyboard to reposition the cursor, it doesn't (without the extension this works as expected).

**Comment by J-Fields** [comment]
Closing in favor of #3044
