### ISSUE TITLE
Mouse double click fails to select the word

### ISSUE THREAD

**Issue by jonathanding** [VSCodeVim/Vim#3360]
**Describe the bug**
It should select the word if double clicking the mouse. However, the word is selected and then after several milliseconds, the selection is cancelled automatically. Furthermore, if double clicking in INSERT mode, after the word is selected, it would enter NORMAL mode besides cancel the selection.

**To Reproduce**

1.  Open any document in editor, either in NORMAL mode or INSERT mode
2.  Mouse to double click on a word
3. The word under click is selected (e.g. UI highlights this word), but after several milliseconds, the selection is gone away (UI restores the original). And if step 1 is in INSERT mode, it would enter NORMAL mode as well.

**Expected behavior**
The word under double click should be always selected

**Environment (please complete the following information):**
Vim Settings: 
  Use System Clipboard: True
  Use Ctrl Keys: False
  Override Copy: True
  Surround: True

- Extension (VsCodeVim) version: 1.0.1
- VSCode version: 1.30.2
- OS: Windows 10

**Additional context**
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.16299
Extension|Author (truncated)|Version
---|---|---
scrollkey|74t|1.0.1
better-toml|bun|0.3.2
vscode-eslint|dba|1.8.0
theme-monokai-pro-vscode|mon|1.1.9
python|ms-|2018.12.1
cpptools|ms-|0.20.1
Go|ms-|0.8.0
debugger-for-chrome|msj|4.11.1
color-highlight|nau|2.3.0
vscode-docker|Pet|0.5.1
vscode-icons|rob|8.0.0
rust|rus|0.5.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.1.2
vim|vsc|1.0.1

**Comment by jpoon** [comment]
I suspect it's a conflict with another extension. I can't repro with just VIM installed.

**Comment by jonathanding** [comment]
I just found that this is caused by a dictionary app which captures the selection event to show the translation for me as well. It's not caused by this extension and not its bug. Thanks!
