### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hashhashu** [VSCodeVim/Vim#3366]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `0.16.6`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/hurly/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment]
Dupe of https://github.com/VSCodeVim/Vim/issues/3362
