### ISSUE TITLE
vw selects more then word.

### ISSUE THREAD

**Issue by skalinkin** [VSCodeVim/Vim#3368]
**Describe the bug**
In normal mode vw selects more then word. In simple case vw will select rest of the word plus space. some times it selects special characters or go and select to the first word on the next line. 

**To Reproduce**

1.  Go to any word in normal mode
2.  type vw
3.  Selection will be more then expected word. 
4.  at the same position try cw and removed section will not match what was highlighted

**Expected behavior**
I am expecting vw select exact same area that will be effected by dw, cw

**Screenshots**
![image](https://user-images.githubusercontent.com/2797342/51118527-a2062100-17de-11e9-8625-cb8aa79df208.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.1
- VSCode version: 1.30.1
- OS: Windows 10
![image](https://user-images.githubusercontent.com/2797342/51118615-cd890b80-17de-11e9-8443-1eea7f9aab5c.png)

**Comment by zhuzisheng** [comment]
I checked in Vim.
It seems VSCodeVim works the same as in Vim.

**Comment by johnfn** [comment]
This is how Vim works.

**Comment by wmaurer** [comment]
Indeed it is how Vim works.

For those interested, if you're at the start of a word, typing `ve` will select just the expected word, and not more.
Another useful trick is to select the word under the cursor (even if the cursor isn't at the start of the word) using `viw`.
