### ISSUE TITLE
Rename ModeHandler

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#337]

**Comment by jpoon** [comment]
Rename it to what?

**Comment by johnfn** [comment]
Something that indicates better that it does the core processing for all of VSCodeVim

**Comment by Chillee** [comment]
I think it's fine, and the alternative names I can think of (StateHandler?), aren't much better.

I'm gonna close this issue as it's something that'll likely never be done (and something I don't think we really need to do).
