### ISSUE TITLE
Slack invite link doesn't resolve

### ISSUE THREAD

**Issue by areinmeyer** [VSCodeVim/Vim#3370]
**Describe the bug**
Clicking on the link in the README that says `If you need to ask us any questions, join us on Slack` generates an error

**To Reproduce**

1.  Go to https://vscodevim-slackin.azurewebsites.net
2.  See page error out.

I've tried this link on and off for about a week and it's never resolved, so I don't think this is a random networking issue.

**Expected behavior**
I expected to see a form that would allow me to request a login or resolve to a login.  

Note that https://vscodevim.slack.com works, but there's no way to request a new account from that page.

**Comment by jpoon** [comment]
Looks like my free azure account is no longer free after leaving Microsoft. We need another place to host the slackin server.

**Comment by YamadaKY** [comment]
I want this too!
  '<,'> normal.
