### ISSUE TITLE
Search-replace with confirm not working with neovim

### ISSUE THREAD

**Issue by ecbrodie** [VSCodeVim/Vim#3371]
**Describe the bug**
This is an extension of #1010, with a focus on the Neovim integration. Search-replace with confirm does not appear to work with the Neovim integration enabled.

**To Reproduce**

Run a search replace command like so:

```
:%s/foo/bar/gc
```

When you press enter, nothing happens. If you took out the `c` flag, then the replace will work correctly.

**Expected behavior**
A prompt window appears in VS Code to receive input for the confirmation (ie, `y/n/...`).

**Environment (please complete the following information):**

I am using the latest of all versions as of writing:

- Extension (VsCodeVim) version: 1.0.1
- VSCode version: 1.30.2
- OS: MacOS 10.14.2

**Comment by ragavkumarv** [comment]
Hi @ecbrodie ,
I have tested it with the `c` flag, it works with and without neovim integration. But only tested with Windows 10 and VsCodeVim 1.1.0. Kindly recheck if it works now.

**Environment:**

* Extension (VsCodeVim) version: 1.1.0
* VSCode version: 1.31.0
* OS: Windows 10

**Comment by ecbrodie** [comment]
@ragavkumarv still doesn't work for me with neovim enabled. I get no prompt when I use the `c` flag. Works just fine with plain-ole VIM activated.

Please check again. Also, I'm not going to be using the neovim integration going forward because I find it to be pretty buggy. I can't guarantee that I'll be willing to verify a fix again.

**Comment by casey-speer** [comment]
+1 broken for me with neovim enabled

**Comment by toimelin** [comment]
I suffer the same issue with neovim enabled. If it works for other people, have they double checked that they are indeed using neovim and not plain old vim (ie. having the neovim executable properly set as well as having the bool setting flipped)?
