### ISSUE TITLE
status bar color unexpectedly changes to red

### ISSUE THREAD

**Issue by NAKAM3595** [VSCodeVim/Vim#3374]
Hi there.

**Describe the bug**
I'm using `statusBarColorControl`.  
When I use `: key action` (like `:w`) or `easymotion`, status bar changes to red.  
I never set this red for status bar.

**To Reproduce**
I set my `settings.json` like this.

>
    "vim.statusBarColorControl": true,
    "vim.statusBarColors.normal": "#0e4569",
    "vim.statusBarColors.insert": "#424d00",
    "vim.statusBarColors.visual": "#691b41",
    "vim.statusBarColors.visualblock": "#691b41",
    "vim.statusBarColors.visualline": "#691b41",
    "vim.statusBarColors.replace": "#770000",        //    <-- this red is not the problem red.

After I set above, this was automatically added.

>
    "workbench.colorCustomizations": {
        "statusBar.background": "#0e4569",
        "statusBar.noFolderBackground": "#0e4569",
        "statusBar.debuggingBackground": "#0e4569"
    },

**Expected behavior**
Don't change to red.

**Screenshots**
![78](https://user-images.githubusercontent.com/37441602/51211662-95f29e80-1959-11e9-834e-6ea7d3588d9e.png)
![79](https://user-images.githubusercontent.com/37441602/51211664-95f29e80-1959-11e9-82d8-55a7432e3537.png)
![81](https://user-images.githubusercontent.com/37441602/51211682-a4d95100-1959-11e9-9f74-12188f36b432.png)
![80](https://user-images.githubusercontent.com/37441602/51211683-a4d95100-1959-11e9-9a4c-844ff9947d58.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.0.1
- VSCode version: 1.30.2
- OS: windows10, ubuntu 16.04 (I found this problem in my Windows laptop, and the same happens in Linux Desktop PC.)

**Additional context**
It worked correctly few weeks ago.

This very annoys me.  
Does anyone have an idea?

Thanks.

**Comment by NAKAM3595** [comment]
Don't close this issue. Nothing seems to be better. It still changes to red.
I restart my PC. I uninstall and reinstall the extension.

**Comment by jpoon** [comment]
It's fixed in master. We haven't pushed out a release yet...

**Comment by NAKAM3595** [comment]
oh, that's why. I'm waiting for next update.

**Comment by Stratovarius93** [comment]
`  "vim.statusBarColors.easymotionmode": "#F5946E",
  "vim.statusBarColors.easymotioninputmode": "#F5946E",`
  
  Can you use this settings to set colors.
