### ISSUE TITLE
gT gt

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#338]
VSCode added tabs!!!

**Comment by sumanx** [comment]
If we can bind a VSCodeVim command with a VSCode build-in action,  a lot of feature like this one will be very easy. 

For example:
```
"vim.otherModesKeyBindings": [
       {
           "command": ["g", "t"],
           "editor": "workbench.action.nextEditor"
       }
  ]
```

Seems very easy but I'm new to VSCodeVim and VSCode. Maybe I should read the extension code first and try to contribute.

**Comment by johnfn** [comment]
@sumanx A nice idea, which deserves its own issue. I lean towards no, though. The way that we add new commands (in actions.ts) is so straightforward already that there's no need to add a separate way to do so. 

I bet if you take a look, you'll agree with me. 😃

**Comment by arussellk** [comment]
I'm going to give this a shot. Please add the in-progress label.

**Comment by jpoon** [comment]
@arussellk done.
