### ISSUE TITLE
Surround doesn't keep history steps properly

### ISSUE THREAD

**Issue by eduardoarandah** [VSCodeVim/Vim#3386]
When doing surround in multiple lines, the "undo" doesn't keep history right, it undoes multiple commands behind. 

Example: 
do `yss"` in multiple lines, then `u`

![asdf](https://user-images.githubusercontent.com/4065733/51364094-8f227380-1aa0-11e9-94ef-b71fe785633f.gif)

May be related to 
https://github.com/VSCodeVim/Vim/issues/3355

**Comment by bootress** [comment]
+1, I've also sporadically experienced `u` undoing multiple actions just like this, but haven't been able to get a consistent minimal reproducer.
