### ISSUE TITLE
'gd' is working correctly, but an error occurs.

### ISSUE THREAD

**Issue by tishibas** [VSCodeVim/Vim#3387]
**Describe the bug**
When pressing the command `gd` to jump to the local declaration in Golang, the following error sometimes appear in the bottom right. Jumping the local declaration is working correctly, so' I want to stop this notification.

```
ModeHandler: error handling key=d. err=RangeError.
```

**Expected behavior**

**Screenshots**
![2019-01-18 14 07 18](https://user-images.githubusercontent.com/3607303/51366813-f4bb4200-1b2a-11e9-915f-31c51d03be56.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.2
- VSCode version: 1.30.2
- OS: MacOS Mojave 10.14.2

**Comment by jpoon** [comment]
We've spent a fair bit of time with our documentation (readme, changelog, roadmap) so please peruse that first whenever you have any issues.

In v1.0.0, we now present errors as notification windows. These were previously outputted to console and was not very discoverable. If you wish to continue living in bliss/ignorance of extension errors it's configurable with the settings here: https://github.com/VSCodeVim/Vim#vscodevim-settings:

Setting | Description | Type | Default Value
-- | -- | -- | --
vim.debug.loggingLevelForConsole | Maximum level of messages to log to console. Logs are visible in the developer tools. Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error
vim.debug.loggingLevelForAlert | Maximum level of messages to present as VS Code information window.  Supported values: 'error', 'warn', 'info', 'verbose', 'debug'). | String | error

**Comment by jpoon** [comment]
In the latest release v1.0.3 we've 1) fixed the underlying `RangeError` bug and 2) added an option for temporarily suppressing these erro messages.
