### ISSUE TITLE
Unable to remap vv to V in normal mode

### ISSUE THREAD

**Issue by hatelove85911** [VSCodeVim/Vim#3388]
I put following in "vim.normalModeKeyBindingsNonRecursive", it doesn't work:
```
{
        "before": ["v", "v"],
        "after": ["V"]
}
```

vscode: 1.30.2
vscodevim: 1.0.2

**Comment by jpoon** [comment]
Underlying reason is due to https://github.com/VSCodeVim/Vim/issues/1821#issuecomment-458436120. As the root cause is the same, closing this as a dupe of #1821.
