### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cherryMonth** [VSCodeVim/Vim#3400]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.0.1`
- OS Version: `Linux x64 4.15.0-38-generic`
- VSCode version: `1.30.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/miku/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by johnfn** [comment]
"⚠️ Make sure to attach this file from your home-directory: /home/miku/vscodevim.vim-unresponsive.cpuprofile.txt ⚠️"

Well, there isn't much we can do without you actually attaching the file.
