### ISSUE TITLE
Yank lines in 1 window should be available for pasting in another window

### ISSUE THREAD

**Issue by rishadomar** [VSCodeVim/Vim#3401]
**Is your feature request related to a problem? Please describe.**
If I have 2 windows open. A copy of lines (using "y") does not make the lines available in another window.

**Describe the solution you'd like**
I'd really like the commands and buffers available across windows. For example, if I use repeat (dot) command in 1 window it should be available in another.

**Describe alternatives you've considered**
Copy/Paste not using "y" works

**Additional context**
None

**Comment by jpoon** [comment]
Fairly certain this works.

**Comment by mvolkmann** [comment]
Make sure the setting "Vim: Use System Clipboard" is checked.

**Comment by burningTyger** [comment]
While this does the job I'm not totally happy with it. I usually copy gui stuff with the system clipboard and using it for vim too interferes with that. it's somewhat unexpected behaviour for a vim user...
