### ISSUE TITLE
Weird visualmode entering

### ISSUE THREAD

**Issue by phaazon** [VSCodeVim/Vim#3404]
**Describe the bug**
When I press `v` to enter visual mode, I cannot use my special keybindings to move around (while I’ve set them with `before / after` and have to use the arrow keys to “really” enter the visual mode. It’s like it expects other characters (I remapped `h j k l` to `c t s r` because of my bépo layout).

**To Reproduce**

1.  Use this settings for the visual mode:

```
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["c"],
            "after":  ["h"]
        },
        {
            "before": ["t"],
            "after":  ["j"]
        },
        {
            "before": ["s"],
            "after":  ["k"]
        },
        {
            "before": ["r"],
            "after":  ["l"]
        },
    ],
```
2.  Open any text-based file.
3.  Enter `v` and try to move with the bindings.
4.  Also, the bindings correctly work in visual mode block (i.e. `shift v` or `ctrl v`).

**Expected behavior**
It should jump into the visual mode directly.

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.0.3`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.30.2`

**Comment by J-Fields** [comment]
I can't reproduce. @phaazon is this still an issue?

**Comment by laMudri** [comment]
I've found this intermittently when I try swapping `j` and `h`. I'll try to observe carefully how to reproduce it reliably.

**Comment by phaazon** [comment]
I’ll retry tomorrow,, but it’s likely still present, since I have other bugs with mode (such as the `c` mode which, when rebound, doesn’t behave correctly at all). I’ll provide more context / testing tomorrow.

**Comment by phaazon** [comment]
I don’t reproduce but I have another problem with `c`. Will open another issue.
