### ISSUE TITLE
Show mark label like VIM in visual studio

### ISSUE THREAD

**Issue by AbeGeMS** [VSCodeVim/Vim#3406]

**Comment by jpoon** [comment]
No idea what this means. Can you please complete the issue/feature request template, its there for a reason....

**Comment by AbeGeMS** [comment]
![image](https://user-images.githubusercontent.com/11433809/56861133-c0300f80-69d0-11e9-83cd-a16baa408303.png)
See the attach image. Which is get from visualstudio2017 (vsVim)

**Comment by bionboy** [comment]
@jpoon Could we reopen this feature given the new context? I can fill out a more comprehensive feature request.
