### ISSUE TITLE
issue with Chinese IME

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#341]
in insert mode, I want to input `## 查询`, to input the 2 Chinese characters, I need to switch to Chinese IME and type `iaxp `, but after I type all of these, the actual result becomes `#ch查询`: `#` and ` ` were removed and `ch` (IME expands `i` to `ch`) was added.

I think the issue is similar with an issue of amVim (another vim plug-in of VSCode), and maybe a bug of  VSCode instead of the plugin: 
https://github.com/aioutecism/amVim-for-VSCode/issues/101

OS: Windows 10 Professional
VSCode: 1.2.1
IME: Microsoft Pinyin (Double Pinyin Mode)

**Comment by johnfn** [comment]
Yikes; this sounds tough. It's most likely a VSC bug, but I'll investigate further when I have time.

**Comment by rebornix** [comment]
Per https://github.com/Microsoft/vscode/issues/8133#issuecomment-231368358 , we know that we can leverage `replacePreviousChar` to handle Chinese Input. 

Fixing this issue relies on history tracking. Like when we want to type in `安`, the key strokes should be `a`, `n` then `1`. And VS Code`s key replacement would be using `安` to replace `an`, while `a`, `n` and `1` will be translated to 

1. Switch to Insert Mode
2. Insert `n`
3. Replace `n` to `安`.

So the only catch is, how we make sure the first `a` is switching to Insert Mode or just inserting `a`. Free free to assign this task to me.

**Comment by rebornix** [comment]
@localvar I suppose typing Chinese in Insert Mode should be perfect now, do you mind giving it a try? 

There are still some problems with Normal Mode but the priority is not that high.

**Comment by localvar** [comment]
@rebornix which version includes the fix?
as of v0.1.1, seems it is ok now when using Full Pinyin （全拼） mode. But in Double Pinyin (双拼）mode, the issue still exists.

**Comment by rebornix** [comment]
@localvar oh I didn't test 双拼, let me give them a try and see what's the problem.

**Comment by rebornix** [comment]
@localvar I'm using OSX 10.10.5, VS Code's version is 1.4.0-Insider/1.3.0, and VSCodeVim is 0.1.1. Seems Double Pinyin is good. Can you provide repro steps, thanks in advance!

**Comment by localvar** [comment]
@rebornix, for example:

let's say the text I need to input is `## 查询`.
under double pinyin mode and insert mode, I type `## iaxp ` for it.
but the result is `ch查询`

OS: Windows 10 Professional
VSCode: 1.3.0
Vim: 0.1.1
IME: Microsoft Pinyin (Double Pinyin Mode)

**Comment by rebornix** [comment]
@localvar just got my Windows PC and tried Microsoft Double Pinyin and reproduced this bug. The funny thing is the Double Pinyin on OSX is good. I'll look into it and see whether it's still a @Code issue.

**Comment by localvar** [comment]
@rebornix, thanks very much, hope the issue could be fixed.

**Comment by localvar** [comment]
@rebornix 

amVim fix this issue and double pinyin is fine in windows. hope this could be a reference.

[fix replacePreviousChar under insert mode](https://github.com/aioutecism/amVim-for-VSCode/commit/f38d5c69ff49977f0d572ce942ddb61c20b9cbc3)

**Comment by rebornix** [comment]
@localvar , I went through the code and it turned out having nothing to do with the `replacechar` stuff. It's our logic of handling cusor which breaks Double Pinyin. I'll try if I can fix it real quick.

**Comment by localvar** [comment]
Thanks @rebornix

**Comment by rebornix** [comment]
@localvar please help give it a try once we release new version, let us know if there is any more problem in Insert Mode, thanks in advance!

**Comment by localvar** [comment]
@rebornix the issue was fixed, thanks for your work!
