### ISSUE TITLE
Multi-key keybinding - Array or String?

### ISSUE THREAD

**Issue by jonmast** [VSCodeVim/Vim#3414]
I'm not sure if this is a bug or a documentation issue, but I ran into issues trying to create a keybinding for `]e`. The examples in the documentation seem to indicate that the way to do this is with the keys in an array, so my first attempt looked like this:

```json
 "vim.normalModeKeyBindingsNonRecursive": [
    {
        "before": [
            [ "]", "e" ],
        ],
        "commands": [
            "editor.action.moveLinesDownAction",
        ]
    }
]
```

This did not work, but after some trial and error I discovered the following does work:
```json
 "vim.normalModeKeyBindingsNonRecursive": [
    {
        "before": [
            [ "]e" ],
        ],
        "commands": [
            "editor.action.moveLinesDownAction",
        ]
    }
]
```

So my question is - is this how the feature is intended to work? If so, which keys/modes does it apply to? The ReadMe only documents the array style, and that apparently does work for `<leader>` keybindings.

**Environment:**
- Extension Version: `1.0.3`
- OS Version: `Linux x64 4.20.3-arch1-1-ARCH`
- VSCode version: `1.30.2`

**Comment by jpoon** [comment]
If you are rebinding simple characters, both are fine. However, I would recommend the array style because if you take this example of wanting to rebind `space` to something else, if you declared it as a string like 
```
        "before": [
            [ "<space>" ],
        ],
```

We're going to read it like you want to rebind, `<`, `s`, `p`, `a` .... rather than the actual spacebar. Please also take a look at https://github.com/VSCodeVim/Vim#debugging-remappings

**Comment by jonmast** [comment]
@jpoon Thanks for the explanation, the array approach does seem more robust.

I tried debugging and there were no errors, the binding just doesn't seem to match. Here's the log:
```
[Extension Host] debug: ModeHandler: handling key=].
console.ts:134 [Extension Host] debug: Remapper: find matching remap. keys=]. mode=Normal.
console.ts:134 [Extension Host] debug: Remapper: normalModeKeyBindingsNonRecursive. before=],e. command=editor.action.moveLinesDownAction. args=.
console.ts:134 [Extension Host] debug: Remapper: find matching remap. keys=]. mode=Normal.
console.ts:134 [Extension Host] debug: ModeHandler: handling key=e.
console.ts:134 [Extension Host] debug: Remapper: find matching remap. keys=],e. mode=Normal.
console.ts:134 [Extension Host] debug: Remapper: normalModeKeyBindingsNonRecursive. before=],e. command=editor.action.moveLinesDownAction. args=.
console.ts:134 [Extension Host] debug: Remapper: find matching remap. keys=],e. mode=Normal.
```
