### ISSUE TITLE
Wanted to learn Vim

### ISSUE THREAD

**Issue by anishmittal2020** [VSCodeVim/Vim#3419]
I am an active VS Code user. Currently I use default keybindings for linux in Vs Code. Recently, I thought of learning VIM.

Do you suggest if I should change the keybindings to Vim in VSCode? Also, is there any documentation that could be useful that shows how the keybindings change?

**Comment by ryandrew14** [comment]
Learning Vim is not directly a VS Code related issue (so this isn't quite the place for this post). If you type the command `vimtutor` into your Linux shell, it will pop open a tutorial on how to use Vim's keybindings. One of the best ways to learn Vim is simply to do this tutorial, then turn it on and begin using it in everyday editing. Using it might be tough for the first day or two (you will need to search online for certain commands often), but if you keep slowly learning more commands, within a week or two you will notice a significant difference in editing speed.

Vim is incredibly helpful, as anyone who uses it will tell you. I would highly recommend learning it!

As for traditional documentation (and again, I would highly recommend `vimtutor` first), I find that the [Vim Tips Wiki](http://vim.wikia.com/wiki/Vim_Tips_Wiki) is pretty good while you're learning. Have fun!

**Comment by johnfn** [comment]
What @ryandrew14 said is basically correct.

I may be biased but I think VSCodeVim is a great place to learn Vim! :D
