### ISSUE TITLE
Release 1.0.4 doesn't contain listed changes

### ISSUE THREAD

**Issue by pikulev** [VSCodeVim/Vim#3429]
**Describe the bug**
I checked the Release 1.0.4 Source code (zip) and it doesn't contain changes related to the #3402 PR

![screenshot 2019-01-31 at 11 59 29](https://user-images.githubusercontent.com/1318721/52043389-9e012f80-2550-11e9-9f42-7e539753b0a6.png)

**Comment by jpoon** [comment]
Interesting, you're right. I don't know how that could have happened though as the tag was produced from https://github.com/VSCodeVim/Vim/pull/3427.

**Comment by jpoon** [comment]
Pushing a v1.0.5 release

**Comment by jpoon** [comment]
v1.0.5 looks right.
