### ISSUE TITLE
Bad interaction between 1.0.5 and jscode-java-pack

### ISSUE THREAD

**Issue by y0n3t4n1** [VSCodeVim/Vim#3431]
**Describe the bug**
With Java Extension Pack (0.5.0) and Vim for Visual Studio Code 1.0.5 enabled, you cannot edit Java files as the window won't respond to most of keystrokes.

Disabling Java Extension Pack AND enabling all its dependencies lets me use Vim for Visual Studio Code 1.0.5, so it's the best workaround at the moment.

Reverting to Vim for Visual Studio Code 1.0.4 also fixes the problem.

Disabling Vim for Visual Studio Code while Java Extension Pack enabled also lets you edit files, but it's not an option for an addicted vim user :)

**To Reproduce**

1. Install and enable Vim for Visual Studio Code 1.0.5 and Java Extension Pack 0.5.0
1. Open a java file (or open a new window and name it as a.java)
1. The cursor becomes narrow like it's in input mode, but the editor window won't respond to most of keystrokes (somehow ctrl-p works)

**Expected behavior**
You can edit Java files when both extensions are enabled.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**
- Java Extension Pack 0.5.0
- Extension (VsCodeVim) version: 1.0.5
- VSCode version: 1.30.2
- OS: macOS mojave

**Additional context**

**Comment by sambernet** [comment]
I have the same combination and in my case it **completely breaks text editing** with `vscodevim` enabled.

It looks like keyboard input is completely broken - no keypresses are doing anything within an editor window anymore. The workaround above (disabling java extension pack) does not change anything in my case. 

But I can confirm downgrading to `1.0.4` solves the problem for me as well.

Usually nothing happens, but at least one time an actual error message was displayed when entering an editor window and pressing `i` to switch to insert mode:
![image](https://user-images.githubusercontent.com/13965084/52069897-f69bf100-257f-11e9-98f1-5edecade3773.png)

**Comment by sambernet** [comment]
> 
> 
> Anything interesting in the console logs?

Didn't find anything relevant really.

But can confirm 1.0.7 works fine again for my setup 🎉
Thanks a lot!!
