### ISSUE TITLE
:%y marks file dirty

### ISSUE THREAD

**Issue by ma53** [VSCodeVim/Vim#3434]
**Describe the bug**
Using `:%y` to yank the entire contents of the file marks the file as dirty.

**To Reproduce**

1.  Open a new file.
2.  Insert any text and save.
3.  Do `:%y`.

**Expected behavior**
The file should not be marked as dirty since no changes are made.

**Environment (please complete the following information):**

- Extension Version: `1.0.3`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.30.2`

**Comment by jpoon** [comment]
Closing as dupe of https://github.com/VSCodeVim/Vim/issues/3201
