### ISSUE TITLE
Cannot bind ";" to "EnterCommand" or "tab" to MoveMatchingBracket

### ISSUE THREAD

**Issue by hellochar** [VSCodeVim/Vim#344]
Hey vscodevim, neither of these mapping seem to be doing anything:

settings.json: 
```
// Place your settings in this file to overwrite the default settings
{
    "vim.normalModeKeyBindings": {
        ";": "EnterCommand",
        "tab": "MoveMatchingBracket"
    },
}
```

`tab` still inserts a tab key and `;` still does nothing. Is there something I'm doing wrong here?

**Comment by johnfn** [comment]
@jpoon do you know about this?

**Comment by jpoon** [comment]
With our latest refactoring, this is no longer supported in the newer versions :(. We'll look to add it back though!

**Comment by johnfn** [comment]
Ah, sorry about that @hellochar.

I'll see if I can get remapping support working this weekend. 

Until then, you could rebuild a local version of VSCodeVim to suit your needs. Just put the following definitions into actions.ts:

```
@RegisterAction
class CommandShowCommandLine extends BaseCommand {
  modes = [ModeName.Normal];
  keys = [";"];

  public async exec(position: Position, vimState: VimState): Promise<VimState> {
    vimState.commandAction = VimCommandActions.ShowCommandLine;

    return vimState;
  }
}

```

I got that just by coping the current ":" command and switching ":" to ";". 

The tab key is unfortunately a little harder - I will need to investigate that more.

**Comment by johnfn** [comment]
This is now possible! Go to user settings and do the following

```
    "vim.normalModeKeyBindings": [
        {
            "before": [";"],
            "after": ["\n"]
        },
    ]
```

Unfortunately, we can't remap <tab> yet due to a limitation of the vscode API 😞
