### ISSUE TITLE
Cursor jumps up to the beginning of a file after saving.

### ISSUE THREAD

**Issue by agubarev** [VSCodeVim/Vim#3444]
Good day everyone,

FOREWORD: This is happening only when working with Go files and only when VIM plugin is installed.

Cursor jumps to the "import" line if I move the cursor after saving and if I move again it goes down a few lines; I'm not even sure it tries to return to its previous place, just jumps like a half screen down. This happens only when the OUTPUT tab is open (on the right side) with "Go Tests" printing its usual output. I guess it's interfering with the editor window somehow. First thing that comes to my mind is that the cursor position is reset on keypress after saving.

I've noticed this only yesterday as I've moved back to Linux(Ubuntu 18.10) from MacOS and I've copied only few of my snippets and user settings. Btw, I've worked on this Linux machine for quite a while before spending some time on MacOS, and everything worked perfectly.

I've tested by disabling, reinstalling, deleting all configuration. (including ~/.config/CODE), and also changed to all available go formatters but the problem still persists unfortunately.

**Comment by stephen-soltesz** [comment]
I am experiencing the same issue: VScode+Go+Vim plugins cause the cursor to relocate on save. I can confirm that the behavior change occurred between vim plugin versions 1.0.2 (expected behavior after save) and 1.0.3+ (cursor relocating). For now I've downgraded my version of the vim plugin as a workaround.

**Comment by agubarev** [comment]
> For now I've downgraded my version of the vim plugin as a workaround.

Hello, would you mind telling me how you downgraded?

**Comment by stephen-soltesz** [comment]
Basically, from the vscode extensions list, click on the Vim extension
settings "gear" icon, and select "Install Another Version...".

I've updated my comment on issue 3444 too.

**Comment by agubarev** [comment]
I've followed your example and downgraded gradually down to 1.0.2 (apparently things got broken above this version). Everything works fine atm, waiting for an update.

P.S. you guys are doing an amazing job and how you've managed to embed VIM so gently, and how it interoperates with VSCODE... thanks! 

AND huge thanks to the GO extension team for creating such a superb Golang support in VSCODE (since I know you're following this too ^^) One big THANKS to both teams :)

**Comment by noseglid** [comment]
I have this exact same issue.

Thanks to @agubarev I downgraded to 1.0.2 (`cmd-alt-p` -> `Extensions: Install Specific Version of Extension` -> `Vim` -> `1.0.2`)
Also add
```
"extensions.autoUpdate": false,
```

Or you'll get the latest version.

**Comment by agubarev** [comment]
> Thanks to @agubarev I downgraded to 1.0.2

Nah, thanks to @stephen-soltesz

**Comment by jpoon** [comment]
Can't repro... either with `:w` or a `ctrl+s`. The cursor stays where it should be. 

Nothing is apparent looking at the diff between the two versions. https://github.com/VSCodeVim/Vim/compare/v1.0.2...v1.0.3

**Comment by stephen-soltesz** [comment]
@jpoon can you confirm, what plugins are enabled during your test? There may be a subtle interaction between the Go & Vim plugins. I'm sure I or @agubarev or @noseglid could provide additional diagnostic information if we knew what would be helpful to provide. Does the vim plugin have a "debug" logging option, for example?

**Comment by jpoon** [comment]
> Does the vim plugin have a "debug" logging option, for example?

See the *.debug options. https://github.com/VSCodeVim/Vim#vscodevim-settings

**Comment by noseglid** [comment]
I've enabled the debug option, and all output I get is;
```
[Extension Host] ModeHandler: debug: handling key=j.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=j. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:134 [Extension Host] Remapper: debug: trying to find matching remap. keys=j. mode=Normal. keybindings=normalModeKeyBindingsNonRecursiveMap.
2console.ts:134 [Extension Host] Remapper: verbose: key=j. keySlice=j.
```

Here's a gif outlining how it goes. After the test has been run I need to move the cursor before the jump actually happens. So I press `j` or `k` and then it jump to "near the top". It seems a bit random where it actually ends up.
![jumpy](https://user-images.githubusercontent.com/933880/52260147-7a116580-2925-11e9-809b-0a74c9bf00df.gif)

**Comment by noseglid** [comment]
Awesome! This is resolved for me by `1.0.8` - Thanks for the very quick response!

**Comment by nosarthur** [comment]
I still have this problem with vim plugin 1.10.0, go plugin 0.11.4, and vs 1.37.1

**Comment by alxyzc** [comment]
It looks like the issue has been re-introduced in build 1.10.2.

**Comment by superdit** [comment]
this happen to me because some of these extensions "Apache Conf" & "nginx.conf", I remove them, and the problem solved

**Comment by superdit** [comment]
same problem happen to me on, vs 1.37.1, extensions: go plugin 0.11.4, live server 5.6.1, material icon theme 3.9.0

**Comment by freerider7777** [comment]
same problem VS 1.38.1 go plugin 0.11.6

**Comment by srinathh** [comment]
I'm having the same problem still VSCodeVIM version - 1.11.0, Go version 0.11.7. Happens on Windows, doesn't happen on Linux

**Comment by freerider7777** [comment]
Yes, very annoying... Workaround is mouse click in the place of cursor after save....

**Comment by vamseekm** [comment]
Still happening with ctrl+s shortcut. But not with :w in vim mode.

**Comment by emvau** [comment]
Still happening with CTRL+S on Windows 10, VS Code 1.44.2, go 1.14.2 & VSCodeVim 1.13.1

**Comment by Gawainli** [comment]
same problem on windows
vscode-1.44.2, vim extension-1.13.1, go extension-0.14.1

**Comment by weilicong** [comment]
It happen when file is CRLF, and will fix if switch to LF

**Comment by navarrothiago** [comment]
Just to give an updated, I have the same problem on Linux, Vscode v1.75, VSCodeVim v1.25.2, Go v0.38.0.
