### ISSUE TITLE
holding down navigation button 

### ISSUE THREAD

**Issue by jon-choi** [VSCodeVim/Vim#345]
(i'm on mac os x.)

**holding 'j' down to continue to scroll down doesn't work.** (nor does ctrl+d, which deletes the following character, even on insert mode).

is there a system setting i need to tweak or is that simply not supported?

for WebStorm for example:
`defaults write com.jetbrains.WebStorm ApplePressAndHoldEnabled -bool false` seemed to solve the problem.

Guessed with `com.Microsoft.VisualStudioCode`, but didn't seem to solve the issue. Help!

**Comment by johnfn** [comment]
This totally works for me, also OSX.

Could you do me a favor and try with a fresh install of VSC?

**Comment by johnfn** [comment]
Try this (found in the Vintageous documentation):

`defaults write com.sublimetext.3 ApplePressAndHoldEnabled -bool false`

**Comment by rebornix** [comment]
Run into the same situation. This works perfectly on Windows but no luck with OSX.

**Comment by johnfn** [comment]
@rebornix can you try running `defaults write com.sublimetext.3 ApplePressAndHoldEnabled -bool false` in your terminal on OSX? It'll actually make key repeats work systemwide, though you can disable it by running it again with `true`.

**Comment by rebornix** [comment]
I've tried that (even with admin privilege) and restart VS Code Insider but it still doesn't work. I noticed this on my rmbp the first day I used this extension but then I switched to Windows. Now I'm working on Mac again and it turned out to be a problem.

**Comment by johnfn** [comment]
Weird! And when holding down keys in other textboxes, it works fine?

**Comment by rebornix** [comment]
Oh wait, I can't even do this with Chrome, so it can be out of this extension or VS Code. But we still need a clear workaround or guidance about this.

**Comment by johnfn** [comment]
Ahh, okay.

I don't think a workaround is possible because VSC does not trigger events for key on/key off, only keystroke registered. 

We can definitely let users know about it though. We could have some sort of visible FAQ...

**Comment by rebornix** [comment]
I'm Okay to close this issue as it has nothing with both the ext or the editor. Currently I can only repeat keys in terminal, but I'll say it's my Mac's problem.

**Comment by johnfn** [comment]
👍

**Comment by johnfn** [comment]
OH duh, no wonder that command I gave didn't work. It's for Sublime Text. I'm a dumb.

I'm sure VSCode has an equivalent, but I have no clue what it is, or why it appears to be set for me.

**Comment by rebornix** [comment]
Finally figure out how to fix it. After running the command @johnfn provided, remember to reboot the system. It's documented here https://discussions.apple.com/thread/6058293?tstart=0

**Comment by johnfn** [comment]
Are you sure it was mine? it has `com.sublimetext.3` in it, which I assumed meant it was ST3 only.

**Comment by rebornix** [comment]
It should be `defaults write -g ApplePressAndHoldEnabled -bool false` but people should be careful about this global effect.

**Comment by danilojunS** [comment]
Compiling these awesome answers, this is what I did (for future reference for the lazy people like me).

1. Run the following command in the terminal (which will not have a global effect):
    ```
        defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
    ```
1. Restart the computer.
1. Open `VSCode` and hold down `j` like there is no tomorrow. 👌

**Comment by chulkilee** [comment]
For insider:

`defaults write com.microsoft.VSCodeInsiders  ApplePressAndHoldEnabled -bool false`

I just restarted vscode insider and it works.

**Comment by jpoon** [comment]
FYI, this is all in our readme https://github.com/VSCodeVim/Vim/blob/master/README.md#mac-setup

**Comment by Batur24** [comment]
@danilojunS Thank you! That's working!

**Comment by hshoja** [comment]
> Compiling these awesome answers, this is what I did (for future reference for lazy people like me).
> 
> 1. Run the following command in the terminal (which will not have a global effect):
>    ```
>        defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
>    ```
> 2. Restart the computer.
> 3. Open `VSCode` and hold down `j` like there is no tomorrow. 👌

still doesn't work for me.
