### ISSUE TITLE
OS-specific neovimPath in config

### ISSUE THREAD

**Issue by kristiandupont** [VSCodeVim/Vim#3458]
I have my vscode configuration file in git, shared among my macbook and my office pc. Whenever I synchronize, I need to change the path to neovim because it's operating system specific. It would be great to have settings similar to the built-in `"terminal.integrated.shell.windows"` and `"terminal.integrated.shell.osx"`, etc.

**Comment by tristan957** [comment]
Subscribing. I'll take this on in a PR at some point

**Comment by jpoon** [comment]
This is the code: https://github.com/VSCodeVim/Vim/blob/master/src/configuration/configuration.ts#L285

 The config could look like something like this: 

```
neovimPath.windows: "blah"
neovimPath.linux: "blah"
neovimPath.osx: "blah"
```

The challenge will be in doing this in a backwards-compatible manner.

**Comment by kristiandupont** [comment]
Awesome!

I might be missing something, but is backward compatibility hugely important in this case? People will discover quite quickly that the old setting doesn't work. If the error message specifies that this has changed I don't think it will cause anyone significant problems?

**Comment by tristan957** [comment]
I find that backwards compatibility in some of my other extensions has not been a problem. I just get the squiggles that say this is no longer a setting and I fix it

**Comment by J-Fields** [comment]
With `1.38.0`, VSCode introduced a new setting scope `machine-overridable`. I think we can use this to get this feature for free.

**Comment by J-Fields** [comment]
Since https://github.com/VSCodeVim/Vim/pull/4152, you should be able to set this on a per-machine basis
