### ISSUE TITLE
Error when jumping to undefined mark

### ISSUE THREAD

**Issue by hnefatl** [VSCodeVim/Vim#3468]
**Describe the bug**
Trying to jump to a mark that's not been set produces a popup error.

**To Reproduce**

1.  In a file, hit `'` or `` ` `` followed by a letter that's not been used as a mark.
2.  Error in popup dialog.

**Screenshots**
After input `'m`:

![image](https://user-images.githubusercontent.com/1362156/52413065-68bc8a80-2ad8-11e9-86e3-0580cca9837e.png)

**Environment**
- Extension (VsCodeVim) version: 1.0.8
- VSCode version: 1.31.0
- OS: Debian Stretch

**Comment by jpoon** [comment]
Left a comment on the PR, but also x-posting here:

As per http://vimdoc.sourceforge.net/htmldoc/motion.html we should be instead throwing an error `E20: Mark not set`

```
7. Marks					*mark-motions* *E20* *E78*

Jumping to a mark can be done in two ways:
1. With ` (backtick):	  The cursor is positioned at the specified location
			  and the motion is |exclusive|.
2. With '' (single quote): The cursor is positioned on the first non-blank
			  character in the line of the specified location and
			  the motion is linewise.
```
