### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Aiclear** [VSCodeVim/Vim#3471]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.0.8`
- OS Version: `Linux x64 4.19.16-1-MANJARO`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/xzyu/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment]
No attachment.
