### ISSUE TITLE
Tab completion for `:vnew` and `:tabnew`

### ISSUE THREAD

**Issue by alvaroaleman** [VSCodeVim/Vim#3479]
**Is your feature request related to a problem? Please describe.**

I am used to open files in Vim by going to command mode, then entering `:vn` or `:tabn`, then pressing tab to have the command completed. After that, I usually enter one or two letters of the filename, press tab again and vim shows all matches. I can cycle through them and press enter to open the file. If the file is a directory, vim completes with a trailing `/` and if I press tab again, it lets me cycle through the files in that directory.

**Describe the solution you'd like**

* `<escape>:vn<tab>` being completed to the `:vnew` command
* `<escape>:tabn<tab>` being completed to the `:tabnew` command
* Pressing tab after the `:tabnew` or `:vnew` command letting me cycle through the files in the current directory
* Pressing tab after the `:tabnew $LETTER` or `:vnew $LETTER` command where `$LETTER` can be an arbitrary number of letters that are valid as part of a filename letting me cycle through the available files or directories that start with `$LETTER`, pressing then `<enter>` opens the file

**Describe alternatives you've considered**

**Additional context**

**Comment by J-Fields** [comment]
Closing this issue as autocomplete support was added a while back.
