### ISSUE TITLE
Changes occur step by step.

### ISSUE THREAD

**Issue by apalugniok** [VSCodeVim/Vim#3486]
**Changes are done step by step rather than as one single change**
I've found it pretty annoying that when I make a change with `cgn`, `u` or `ctrl-r` the changes seem to be done step by step rather than as one single change from the initial state to the final. For example when using `cgn` the changed word seems to be automatically typed out (see gif below) rather than simply changing.
![cgn](https://user-images.githubusercontent.com/22132297/52666231-9acd5280-2f05-11e9-9a3d-d5321a571e84.gif)
A similar thing happens when undoing or redoing larger changes using `c`.

**The change should occur in a single step**
I would like/expect the extra t's typed to not show up when repeating the command, ideally the `const` would just change to `let`.

I'm loving the extension so far, thanks for all the hard work!

**Comment by J-Fields** [comment]
Related/duplicate: #1992

**Comment by J-Fields** [comment]
Closing as duplicate. Please make sure you give a thumbs-up to #1992, as the team prioritizes issues by reactions.
