### ISSUE TITLE
Yanking "clears" mode (or makes it disappear) from status bar until INSERT mode

### ISSUE THREAD

**Issue by dstj** [VSCodeVim/Vim#3488]
Issue Type: <b>Bug</b>

After yanking some text (a word, line, doesn't matter) from NORMAL mode, the mode disappears from the status bar at the bottom and won't reappear until we enter INSERT mode again. This makes recording macro quite annoying and error prone since we don't know what's going on.

**To Reproduce**
1. qq
2.  y (mode disappears)
3. p
4. q (it won't show)
5. i
6. ESC
7. q (now it shows).

**Expected behavior**
Step 5 and 6 shouldn't be necessary

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/467692/52748513-acb9fe80-2fb4-11e9-9c54-c7faf24db390.gif)

Extension version: 1.0.8
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|16.00GB (7.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|

</details>

**Comment by jpoon** [comment]
When you yank lines fewer than the config in vanilla vim, it actually shows nothing in the menu bar. ie, this behaviour is technically consistent with vanilla vim.

This extension is special however as we actually display `--NORMAL--` mode when vim actually does not.

**Comment by dstj** [comment]
I'd go for 2 then :). 

Vanilla VIM's behavior is awkward and when recording a macro, it's confusing as hell :)

**Comment by lucasrrt** [comment]
Actually, the main problem here is that the `Recording @q` is disappearing when there is a yank/delete (some text manipulation). In vanilla vim, There is no `--NORMAL--` message, but it's we can yank or delete without the `Recording @q` disappearing, as below:
![Jul-24-2019 15-51-35](https://user-images.githubusercontent.com/11685617/61820220-fdb70400-ae2a-11e9-8cb1-4efc20bb3ebb.gif)

**Comment by J-Fields** [comment]
Related: #3838

**Comment by J-Fields** [comment]
Closing in favor of #3838. I plan on doing a refactor of the status bar soon (it's rather janky), and will fix this in the process.
