### ISSUE TITLE
vim.searchHighlightColor does not work

### ISSUE THREAD

**Issue by Praful** [VSCodeVim/Vim#3489]
**Describe the bug**

When I set this `"vim.searchHighlightColor": "rgba(227, 122, 17, 0.8)"`, there is no change to the search highlight.

**To Reproduce**

1.  Go to Settings
2.  Find the Vim:Search Highlight Color 
3.  Change to `rgba(227,122,17,0.8)`
4.  Save settings.
5.  Open a file and search for a string using `\find`, where `find` is what you're searching for.
6.  There is no change in the highlight colour.

**Expected behavior**
The highlighted found word should be a different colour (the one specified) and not the default.

It would be even better if this extension used the system colours for highlighting search items: `editor.findMatchBackground`, `editor.findMatchHighlightBackground` and related options.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.8
- VSCode version: 1.31.1
- OS: Windows 10 1809

**Additional context**

**Comment by RoyLee** [comment]
I'm experiencing the same problem. I am on mac OS and am on VSCode version 1.31.1, and VsCodeVim extension version 1.0.8. Thanks!

**Comment by jpoon** [comment]
Since we moved to asynchronously loading the configuration, when this file is loaded the configurations will have their default values (https://github.com/VSCodeVim/Vim/blob/b4db97b6e3d2b910f664ab178cfb79167cb3f8e1/src/configuration/decoration.ts), as such, the configured values for the search highlight will never be reflected.
