### ISSUE TITLE
 The small delete register "- doesn't work

### ISSUE THREAD

**Issue by ShiruiQian** [VSCodeVim/Vim#3492]
**Describe the bug**
Charactars deleted by "nx" in one line shoud be stored in the small delete register "-.
But they are stored in the unnamed register "".

- Extension (VsCodeVim) version:1.0.8
- VSCode version:1.31.1
- OS:win7 64

**Comment by rickythefox** [comment]
From Vim docs:
> 3. Small delete register "-                             *quote_-* *quote-*
> This register contains text from commands that delete less than one line,
> except when the command specifies a register with ["x].
> {not in Vi}
