### ISSUE TITLE
handleKeys is not overriding VS Code Ctrl+R and Ctrl+F shortcuts

### ISSUE THREAD

**Issue by srodrigo** [VSCodeVim/Vim#3501]
**Describe the bug**
`vim.handleKeys` is not overriding VS Code Ctrl+R and Ctrl+F shortcuts.
It does work with Ctrl+A, so it looks like a problem with the two mentioned

**Expected behavior**
It should override all the specified shotrcuts from VIM.

This is the config used
 ```
    "vim.handleKeys": {
        "<C-a>": false,
        "<C-f>": true,
        "<C-r>": true,
        "<C-y>": false
    }
```

As mentioned above, setting C-a disables the Select All functionality on VS Code, but C-f and C-r are not overriding Find, and Replace.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.8
- VSCode version: 
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Additional context**

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim#-faq

**Comment by srodrigo** [comment]
@jpoon I'm not sure what am I supposed to find on that FAQ. The only thing related is this:

```
Problem:
> None of the native Visual Studio Code ctrl (e.g. ctrl+f, ctrl+v) commands work
Suggested solution:
> Set the useCtrlKeys setting to false.
```

which is actually the opposite example of the problem I'm having. I have useCtrlKeys set to true and some VIM commands are still not working.

Also, I provided a detailed explanation of which keys are not overriding the native VSC behaviour and which are (which should be enough indication of a potential bug), so I'm unsure about why this got closed.

From the documentation https://github.com/VSCodeVim/Vim#vscodevim-settings:

**vim.handleKeys**
```Delegate configured keys to be handled by VSCode instead of by the VSCodeVim extension. Any key in keybindings section of the package.json that has a vim.use<C-...> in the when argument can be delegated back to VS Code by setting "<C-...>": false. Example: to use ctrl+f for find (native VS Code behaviour): "vim.handleKeys": { "<C-f>": false }.```

So setting true for ctrl+f should make the plugin use the VIM command, not the native Find VSC command. That is *not* happening, so it looks like a bug to me. Same problem with ctrl+r (which is the one I really care about), it opens the Find and Replace command from VSC instead of the VIM redo command when `"<C-f>": true`. It doesn't make any difference whether they are set to true or false, but from the documentation, it looks like it should.

ctrl+v works as expected when set to true, disabling the VSC command in favour of the VIM one. So some ctrl+key work as expected, some don't.

**Comment by jackielii** [comment]
tried to rebind <C-s> with the following:

```
  "vim.insertModeKeyBindings": [
    {
      "before": ["<C-s>"],
      "after": [":w", "<Esc>"]
    }
  ],
```
doesn't work either

**Comment by nree** [comment]
I don't know why this is closed, seems to affect people...

It matters the mode you're in:

```
 "vim.handleKeys": {
        "<C-f>": true
    },
    "vim.useCtrlKeys": true,
```

This disable the VSC default keymap for find in __normal__ mode. Toggling the handleKeys to false, will get the find. Great working...

### __but__ whether true or false find will always open when in insert mode!

AFAIK this is true for most C- bindings, like <C-b> does it's thing in normal, and will hide vsc explorer in insert mode...

Please re-open issue, because the docs need to be updated and say Ctrl bindings can only be for normal mode, or this is a bug where it does not capture for insert mode.

**Comment by srodrigo** [comment]
I don't understand why this was close either.

**Comment by stephendb** [comment]
This is still a problem, Ctrl-R does not work just as all of the above people have indicated.

**Comment by stephendb** [comment]
"vim.useCtrlKeys": true works, I put it above handleKeys not that that should matter for json

**Comment by dozzman** [comment]
Also having this issue. Solved it by removing the Ctrl + R keybinding for 'Replace' which now defaults to the vim binding instead. Goto File > Preferences > Keyboard Shortcuts, pressing the Record Keys button in the search bar (keyboard icon) and type Ctrl + R to bring up those bindings and removing the 'Replace' binding entirely.

You may have to adjust the bindings some more depending on what your keymap looks like, you can also do the same for all other keys you're having issues with.

**Comment by herman-rogers** [comment]
Yes this is still broken as of Jan 2021 - no idea why it was closed as I read the FAQ and nothing relates to this. I can only assume that it wasn't read carefully. @dozzman solution work for me - once I removed the key binding I could redo via vim properly.

**Comment by joyous-coder** [comment]
> Yes this is still broken as of Jan 2021 - no idea why it was closed as I read the FAQ and nothing relates to this. I can only assume that it wasn't read carefully. @dozzman solution works for me - once I removed the key binding I could redo via vim properly.

I solve this problem.   You need to get into the key bindings setting and change other's  'when' condition . Add  `&& !vim.active`.   This will avoid the other key bindings work when you are in  vim mode.
Like this :
![image](https://user-images.githubusercontent.com/42910684/106476836-6ed87c80-64e2-11eb-9b58-52904d586c2c.png)

**Comment by jyungtong** [comment]
> > Yes this is still broken as of Jan 2021 - no idea why it was closed as I read the FAQ and nothing relates to this. I can only assume that it wasn't read carefully. @dozzman solution works for me - once I removed the key binding I could redo via vim properly.
> 
> I solve this problem. You need to get into the key bindings setting and change the others' 'when' condition . Add `&& !vim.active`. This will avoid the other key bindings work when you are in vim mode.
> Like this :
> ![image](https://user-images.githubusercontent.com/42910684/106476836-6ed87c80-64e2-11eb-9b58-52904d586c2c.png)

This safe my life as I don't need all ctrl keys to be disabled. I just want my CTRL + F back. That's it.

**Comment by LoudSoftware** [comment]
I may have found the root cause in my case. I used to use the IDEA keybinds extention. Disabling it makes ctrl-r work

**Comment by phanhaiquang** [comment]
In my case, I have global and workspace settings. The global setting is correct, but workspace setting is wrong. So that whatever I did, it makes no change. Fixing this setting conflict make it works. Just want to note here so that if someone got similar issue, then this gives a hint.
