### ISSUE TITLE
Support colon separated paths when setting vim.neovimPath

### ISSUE THREAD

**Issue by tristan957** [VSCodeVim/Vim#3504]
**Is your feature request related to a problem? Please describe.**
I sync my settings between a macOS machine with Homebrew, and a Linux machine. On Linux, my path is `/usr/bin/nvim`. On macOS, my path is `/usr/local/bin/nvim`. When I sync my settings from either machine, the path is no longer valid.

**Describe the solution you'd like**
I would like to set the path like so:
```
"vim.neovimPath": "/usr/bin/nvim:/usr/local/bin/nvim"
```

This may not be the right solution for Windows however since paths typically look like `C:\...`

**Describe alternatives you've considered**
I could create my own symlink, but that seems like a little too much.

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/3458 dupe
