### ISSUE TITLE
Ex command 'copy' throws "failed to handle key=.undefined" error

### ISSUE THREAD

**Issue by AndrewLeigh6** [VSCodeVim/Vim#3505]
**Describe the bug**
Using ex commands, such as copy, throws the following error:

![image](https://user-images.githubusercontent.com/26027525/53167485-f9629280-35cf-11e9-8c93-2f20231542af.png)

**To Reproduce**

1. Enter ex command :4copy.

**Expected behavior**
Code on line 4 is copied to the current line

**Screenshots**
Neovim enabled: 

![image](https://user-images.githubusercontent.com/26027525/53167268-61fd3f80-35cf-11e9-9cfe-eb1d454de527.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.8
- VSCode version: 1.31.1
- OS: Windows 10
- Neovim: 0.3.4

**Additional info**

Commands that work without neovim disabled, such as :%s/import/test/g, also now throw an error with neovim enabled:

![image](https://user-images.githubusercontent.com/26027525/53167761-cec50980-35d0-11e9-8cb4-7db34c8f8ba1.png)

**Comment by simahao** [comment]
+1

**Comment by JSE018** [comment]
+1

**Comment by AndrewLeigh6** [comment]
This is actually working for me now. Here are my settings: 
![image](https://user-images.githubusercontent.com/26027525/56671480-a16a0a00-66ac-11e9-9dd0-d70fd9fcb354.png)

I didn't change my neovim version or anything like that. All I did was change my neovim path, and made sure nvim.exe wasnt set to run as admin.
