### ISSUE TITLE
Reflow (gq) is inconsistently wrapping at the wrong column

### ISSUE THREAD

**Issue by Hubro** [VSCodeVim/Vim#3509]
**Describe the bug**
I'm having some issues understanding the behavior of the reflow command (`gq`).

Take this example - the `vim.textWidth` setting is at the default value (80) and I've reflowed this block of text (line 66 to 69) using `gq`:

![image](https://user-images.githubusercontent.com/597206/53281370-7ce2c780-3727-11e9-9629-28b0cddf2f59.png)

Notice line 68, the line is 81 columns wide.

Here's a different example - `textWidth` is still at the default value, and I've selected and reflowed lines 68 and 69:

![image](https://user-images.githubusercontent.com/597206/53281383-b9162800-3727-11e9-8c66-09252d9bd6e7.png)

The "xxxxxx" fits on line 68, but was wrapped to line 69 anyway. If I remove one "x" and wrap the lines again using `gq`, line 68 ends up being 79 columns wide, meaning that `gq` wrapped at line 79 in this situation.

Is this a bug, or am I misunderstanding some concept of this command?

**To Reproduce**

Install Vim 1.0.8 and Ruby 0.21.1 extensions, create a Ruby file (*.rb) and reproduce the screenshots above.

**Expected behavior**
I would expect `gq` to break at column 80 rather than inconsistently breaking at column 81 and 79 for no apparent reason.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.0.8
- VSCode version: 1.31.1
- OS: Manjaro 18.0.3

**Comment by carmenbianca** [comment]
I have an identical problem.

Given a textwidth of 80, the normal wrapping should be:

![Ekrankopio de 2019-04-25 11-59-44](https://user-images.githubusercontent.com/12065945/56727873-e005d000-6751-11e9-9904-5ffec093faac.png)

But when doing `gq`, the result is:

![Ekrankopio de 2019-04-25 11-59-52](https://user-images.githubusercontent.com/12065945/56727931-fc097180-6751-11e9-9492-a30f721b61e0.png)

Only when increasing textwidth to 83, do I get the expected result.

**Comment by Stigjb** [comment]
Same problem here. `gq` wraps to a maximum of 77 columns, even though textwidth is set to 80.

**Comment by AdamSLevy** [comment]
I can open a separate bug for this if it is unrelated, but `gq` also does not respect the correct indentation when using tabs.

**Comment by sbrocket** [comment]
+1 I also just noticed that reflow isn't working correctly
