### ISSUE TITLE
Code snippet  out of sync with multiple lines/variables

### ISSUE THREAD

**Issue by YuyQuan** [VSCodeVim/Vim#3518]
**Describe the bug**
When having multiple lines or multiple variables in a code snippet, renaming falls out of sync/the main cursor takes priority. Works when disabling extension.

**To Reproduce**
1. Add Cpp Snippet
```
	"Full Iterator Loop": {
		"prefix": "Full Iterator Loop",
		"body": [
			"std::${1:vector}<${2:type}>::iterator ${3:it};\nfor ( ${3:it} = ${4:object}.begin(); ${3:it} != ${4:object}.end(); ++${3:it})\n{\n}"
		]
	},
```
2. Insert snippet into project

**Expected behavior**
Variables renamed uniformly.

**Screenshots**
![tgqff2dpkx](https://user-images.githubusercontent.com/15720568/53304327-8197a080-3839-11e9-818f-136cc70219b7.gif)

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: v1.1.0
- VSCode version: 1.31.1
- OS: Windows 10 build 1809

**Additional context**
NA

**Comment by learning** [comment]
The same here

![screenshot](https://user-images.githubusercontent.com/354626/55868807-c8f2aa00-5bb7-11e9-80a2-2c0303fc51fa.gif)

**Comment by m4hi2** [comment]
I had to uninstall Vim extesion and install amVim to fix this issue.

**Comment by J-Fields** [comment]
This is fixed in master, will be in next release.
