### ISSUE TITLE
TaskQueue: Error running task. Invalid regular expression: 

### ISSUE THREAD

**Issue by fandy** [VSCodeVim/Vim#3519]
Not sure how to reproduce this, but I've tried reinstalling the extension multiple times. It started happening after reopening vscode:

```
TaskQueue: Error running task. Invalid regular expression: 
/([^\s`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?](?:(?:(?<=[A-Z_])[A-Z](?=[\sA-Z0-9`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]))+|(?:(?<=[0-9_])[0-9](?=[\sA-Z0-9`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]))+|(?:(?<=[_])[_](?=[\s`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]))+|[^\sA-Z0-9`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?_]*))|[`~!@#\$%\^&\*\(\)\-=\+\[\{\]\}\\\|;:'",\.<>/\?]+|$^/: Invalid group.
```

It completely crashes and I'm unable to toggle in and out of Vim mode to insert text.

**Comment by cart** [comment]
I'm hitting the same problem

**Comment by cart** [comment]
Updating to 1.31.1 fixed the issue for me

**Comment by larkwt96** [comment]
I also had the same problem, and updating VS Code to 1.31.1 also fixed the issue for me.

**Comment by fandy** [comment]
Looks like VSCode didn't auto update, so I ran:

```
sudo rm -Rf ~/Library/Caches/com.microsoft.VSCode.ShipIt
```

And was able to update after. Then it was fixed.

**Comment by cloudbring** [comment]
Just had the same issue on Windows 10 64bit and upgrading to 1.31.1 fixed it for me.
