### ISSUE TITLE
Non-blinking cursor in normal mode

### ISSUE THREAD

**Issue by gerardmrk** [VSCodeVim/Vim#352]
I am so, so sorry for creating an issue for this, but I was wondering if it's possible to make the cursor not blink when in "normal" mode (similar to the vim-mode package in Atom). It is weirdly unsettling to have it blink both in visual and normal, I tried getting used to it but to no avail. The default user settings does not give the option of toggling "visible" for normal either. Thanks in advance!

**Comment by johnfn** [comment]
Hehe, I dunno why you're sorry about making an issue 😃 

I should have fixed this with #361. Sadly, it's not perfect, as I don't believe VSCode currently offers a nonblinking native cursor, so we just hack it in ourselves. 

Turn it on by putting `"vim.useSolidBlockCursor": true,` into your user settings.

**Comment by timwis** [comment]
Just in case anyone else gets here from search, the above config option no longer works. Instead, you can use:

```
"editor.cursorBlinking": "solid"
```
