### ISSUE TITLE
command 'toggleVim' not found.

### ISSUE THREAD

**Issue by Bo-Fone** [VSCodeVim/Vim#3524]
**Describe the bug**
After auto-updating to VSCode 1.13.1 and VSCode Vim to 1.1.0. The extension stops working. It also gave me "command 'toggleVim' not found." notification when I tried to manually toggle it on. Then, rolling back to 1.0.8 or any version before still won't fix the issue. Rolling back a few more versions still gave me 'toggleVim' not found.

**To Reproduce**
1. Update VSCode to 1.13.1
2. Update VSCode Vim to 1.1.0

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.1.0
- VSCode version: 1.13.1
- OS: macOS 10.14.3

**Comment by Bo-Fone** [comment]
Completely uninstalling VSCode and reinstalling everything back solved the problem.

**Comment by noelevans** [comment]
I'm getting this too. It would be preferable not having to reinstall

**Comment by uloco** [comment]
Only downgrading to the previous version of _VSCodeVim_ fixed this issue for me. I think there is a but somewhere in the newest version ...

<img width="422" alt="image" src="https://user-images.githubusercontent.com/8818340/70442649-07b66800-1a97-11ea-9954-e47dbebb40dd.png">

**Comment by markronquillo** [comment]
how did you downgrade to a previous version?

**Comment by noelevans** [comment]
If you Google "vs code install previous version" you will find the official explanation. Press the cog icon (LHS) for vscodevim in the extension view

**Comment by mariolima** [comment]
Downgrading VSCodeVim to 1.11.3 fixed it for me.
### How to downgrade:
- Uninstall current VSCodeVim
- Download the .VSIX file from that release https://github.com/VSCodeVim/Vim/releases/tag/v1.11.3
- In vscode run command (Ctrl-P) "Extensions: Install from VSIX" and select the downloaded VSIX file.

**Comment by badenkov** [comment]
BTW, there is easier way to downgrading extension version.
Just go to extension bar, find Vim extension there, click on the cog icon and chose Install Another Version...

**Comment by wsrast** [comment]
@badenkov 's solution worked for me. Thanks everyone here for reporting this.

**Comment by daydaygo** [comment]
@badenkov  it works. nice job 👍

**Comment by mprenditore** [comment]
@badenkov thanks for the tip, having issue with "1.12.1" too.

**Comment by uloco** [comment]
Can someone please reopen this issue and close it when it's fixed? So we get notified and can install the latest version again afterwards. Would be nice :)
Perhaps @Bo-Fone

**Comment by originalix** [comment]
> Downgrading VSCodeVim to 1.11.3 fixed it for me.
> 
> ### How to downgrade:
> [#3524 (comment)](https://github.com/VSCodeVim/Vim/issues/3524#issuecomment-563290544)
> 
> * ~Uninstall current VSCodeVim~
> * ~Download the .VSIX file from that release https://github.com/VSCodeVim/Vim/releases/tag/v1.11.3~
> * ~In vscode run command (Ctrl-P) "Extensions: Install from VSIX" and select the downloaded VSIX file.~

Thank you. Downgrading VSCodeVim to 1.11.3 solved problem. 👍

**Comment by originalix** [comment]
@badenkov thanks you. it worked for me

**Comment by StuartFrost** [comment]
Upgrading to 1.12.2 (released 10th December) fixed this for me.

**Comment by alanlunspace** [comment]
Hi all,

Tried to uninstall `visual-studio-code` and reinstall it with brew cask.
Tried to remove `~/.vscode/extensions/vscodevim.vim-*` directories and reinstall Vim extension.
Tried Vim extension version **1.11.3** and **1.12.4** both do not work and `command 'toggleVim' not found` error is still shown.

Please kindly advice.

---
Version: **1.41.1**
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

---

Thank you in advanced.

**Comment by hosseinshaya** [comment]
i'm getting this error too

**Comment by uloco** [comment]
@hosseinshaya you should update to the latest version of this plugin. it's 1.23.2

**Comment by vitallish** [comment]
Had the same issue and had to uninstall "Indent To Bracket" extension
