### ISSUE TITLE
The extension don't work with Java Extension Pack

### ISSUE THREAD

**Issue by rectcircle** [VSCodeVim/Vim#3526]
Version Info:
OS: MacOS Mojave 10.14.3
VSCode: 1.31
VIM: 1.1.0
Language Support for Java(TM) by Red Hat: 0.39.0

Config:

```json
{
    "vim.autoSwitchInputMethod.defaultIM": "com.apple.keylayout.ABC",
    "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/local/bin/im-select",
    "vim.autoSwitchInputMethod.switchIMCmd": "/usr/local/bin/im-select {im}",
    "vim.autoSwitchInputMethod.enable": true,
    "vim.useSystemClipboard": true,
}
```

VIM without Java Extension Pack:
![image](https://user-images.githubusercontent.com/18106246/53395084-ec80dd00-39db-11e9-81d3-30f92cf97cc4.png)

VIM don't work with Java Extension Pack, Just like no installation.

commands:
![image](https://user-images.githubusercontent.com/18106246/53394461-57311900-39da-11e9-8eb5-688153774b6c.png)
![image](https://user-images.githubusercontent.com/18106246/53394475-5ef0bd80-39da-11e9-8297-a8152aa71284.png)

when I open Java project as a folder, I open a new file and press the backspace key
![image](https://user-images.githubusercontent.com/18106246/53394640-d0c90700-39da-11e9-899e-74e13a14a2d7.png)
![image](https://user-images.githubusercontent.com/18106246/53394648-d6bee800-39da-11e9-8753-3a2170bc8844.png)

I am sure I installed the vim extension
![image](https://user-images.githubusercontent.com/18106246/53394697-ffdf7880-39da-11e9-98c9-cfdae133b0d6.png)

**Comment by jpoon** [comment]
Firstly, make sure you are on latest vscode/vscodevim
Secondly, this will likely resolve such issues: https://github.com/VSCodeVim/Vim/issues/3473#issuecomment-466747968

**Comment by jeerychris** [comment]
i get the problem too, **vscode-vim version 1.4.0**, vscode version **1.32.3 portable**

i solve it by following steps:

1. uninstall java-pack extension
2. manually delete java-pack extension folder but other extension folders that actually support java develop, like redhat-java, debugger for java, etc.
3. delete `${vscode-data}/extensions/.obsolete` file
4. reload window

**NOTE**: <span style="background-color:yellow">delete `.obsolete` file will lead your uninstalled extensions recoverd, for specific extensions, you can edit it instead.</span>
