### ISSUE TITLE
When entering visual mode, vim.visualModeKeyBindingsNonRecursive don't take effect for about a second

### ISSUE THREAD

**Issue by ohjames** [VSCodeVim/Vim#3530]
**Describe the bug**
Add to `vim.visualModeKeyBindingsNonRecursive`:

```
  { "before": ["n"], "after": ["j"] }
```

In an editor window, enter visual mode and quickly push `n` several times, the first few `n` key-presses will do a "search next" then the next few will be remapped as desired.

It takes about a second before the remaps take effect after entering visual mode.

- Extension (VsCodeVim) version: 1.1.0
- VSCode version: 1.31.1
- OS: archlinux

This is not an issue in vim or neovim.

**Comment by sobjornstad** [comment]
I'm suspicious this may be related to #3221 (insert mode remapping doesn't work within a second of typing other characters in insert mode).

**Comment by ohjames** [comment]
@sobjornstad I have that issue too. I'm having a lot of issues with remapping... VsCodeVim isn't very useable unless you are using the default mappings unfortunately and it's been that way for two years.

**Comment by peitalin** [comment]
+1 same issue with the delay when switching to insert mode.
