### ISSUE TITLE
Searching across multiple lines doesn't work

### ISSUE THREAD

**Issue by pansila** [VSCodeVim/Vim#3532]
**Describe the bug**
`\_s` is used to search spaces or tabs or newlines in Vim, but it doesn't work in VSCodeVim

**To Reproduce**
Type commands `/\_s+` or `s/\_s+//` can't see highlights or substitutes.

**Expected behavior**
`\_s` shall match spaces or tabs or newlines 

- Extension (VsCodeVim) version: 1.1.0
- VSCode version: 1.13.1
- OS: Windows 7 64bit

**Comment by sql-koala** [comment]
Special case of: #3996
Workaround: `/[\n\s]+`
