### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by A28Rh** [VSCodeVim/Vim#3533]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.1.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/r.hiramitsu/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JKillian** [comment]
Hi @A28Rh, could you upload your `vscodevim.vim-unresponsive.cpuprofile.txt` file over in https://github.com/VSCodeVim/Vim/issues/3362? Without that file, it'd be tough for anyone to tell what issues you were encountering. Thanks!

**Comment by jpoon** [comment]
Ditto to what JKillian said. Closing as there's no information to act on.
