### ISSUE TITLE
Deletions aren't added to the change list

### ISSUE THREAD

**Issue by hhu94** [VSCodeVim/Vim#3538]
**Describe the bug**
Deleting text isn't added to the change list so when a deletion was the last change, `g;` doesn't go to where the deletion happened.

**To Reproduce**
1. Delete a character or a line with `x` or `dd`
2. Navigate to a different line in the file.
3. Use `g;`

**Expected behavior**
I expect the cursor to navigate back to where the deletion occurred.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.1.0
- VSCode version: 1.31.0
- OS: Windows 10

**Comment by J-Fields** [comment]
Closing as it seems this has been fixed. Let me know if you're still experiencing this and I'll re-open.
