### ISSUE TITLE
Support the / register

### ISSUE THREAD

**Issue by sobjornstad** [VSCodeVim/Vim#3542]
**Describe the solution you'd like**

In standard Vim, the most recently searched-for string is stored in the `/` register. This makes it easy to paste it into a regex or reverse the direction of your search (e.g., if searching forwards and you really want to search backwards, you can just use `?<C-r>/`).

**Describe alternatives you've considered**

The only current solution I've found is to retype the search expression, as you cannot even copy out of the status bar entry in VSCodeVim.

**Additional context**

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/blob/master/src/register/register.ts if anybody wants to take a gander at adding this.

**Comment by J-Fields** [comment]
I plan on tackling #3604, #3605, and #3606 (all problems with registers). I can do this in the same PR.
