### ISSUE TITLE
Unexpected <c-a> and <c-x> behavior with leading zeros

### ISSUE THREAD

**Issue by sklnd** [VSCodeVim/Vim#3545]
Issue Type: <b>Bug</b>

1.  Enter a number like 0200
2.  Move the cursor to the left of the last 0
3.  Use `<c-a>` in normal mode.
4.  The number is now 201, not 0201

Additionally , if I used `<c-x>` to decrement and the cursor is to the left of the last 0, the same bug appears. If the cursor is on the rightmost zero, 0200 is converted to 20-1, which is also quite unexpected. 0199 would match Vim behavior.

Extension version: 1.1.0
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.18.0-15-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700 Eight-Core Processor (16 x 1299)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|31.40GB (2.50GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by yifanchen** [comment]
Do you happen to have #3229 this issue when using <C> command, e.g. <C-w>?

**Comment by J-Fields** [comment]
Reproduced on Windows 10, VSCodeVim 1.2.0, VSCode 1.32.3.
Strangely enough, you don't have to be to the left of the number. One case I can reliably reproduce is this, starting on a blank line:
`i0200<esc><ctrl-a>h<ctrl-a>`
while this works just fine:
`i0200<esc>h<ctrl-a>`
