### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jeffschwartz** [VSCodeVim/Vim#3546]
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/2920874/vscodevim.vim-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.1.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/Jeff/vscodevim.vim-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JKillian** [comment]
@jeffschwartz would you mind posting over in https://github.com/VSCodeVim/Vim/issues/3362 and closing this issue out? Just will make it easier to track performance issues if all the reports are in the same thread.  Thanks!

**Comment by jeffschwartz** [comment]
Closing this out in favor of #3362
