### ISSUE TITLE
Scroll backwards breaks selection in visual mode

### ISSUE THREAD

**Issue by hiratasa** [VSCodeVim/Vim#3549]
**Describe the bug**
When pressing Ctrl-b in visual mode, the selection range shows strange behavior (as if start of selection changed).

**To Reproduce**

In a text file longer than screen height,

1. Go to the line below the screen height. (If screen height is 50 lines, go to a line below 50th line).
2. Press `v` to start visual mode.
3. Press `Ctrl-b` to scroll up.
4. At this point, selection behaves as if selection start has changed:
  - If you press `k` here, selection range is expected to extend upwards, but actually it narrows from the bottom.
  - If you press `Ctrl-b` once again, selection range is expected to extend upwards by one screen, but actually it narrows by one screen from the bottom (i.e. the selection range becomes only one line).

**Expected behavior**
Ctrl-b behaves same as original vim's behavior in visual mode.
(see above)

**Environment (please complete the following information):**

- Extension Version: `1.1.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.31.1`

**Comment by J-Fields** [comment]
I can't find the commit, but this was fixed a while back
