### ISSUE TITLE
SPC should move right in Normal mode but doesn't

### ISSUE THREAD

**Issue by georgevreilly** [VSCodeVim/Vim#355]
In Normal mode, ` ` (`<space>`)  should be the same motion as `l` and `<right>`. In v 0.0.28 on VSC 1.2.1, nothing happens.

**Comment by johnfn** [comment]
Thanks for the suggestion, @georgevreilly! This is an easy extension to add, so I marked it as help-wanted in case anyone wants to give it a shot, but I'll get to it soon if not!

**Comment by johnfn** [comment]
Done!
