### ISSUE TITLE
vim-auto-save

### ISSUE THREAD

**Issue by hamidzare71** [VSCodeVim/Vim#3550]
Hi I've used `vim-auto-save` feature in vim to save everything after Insert-mode exit(and every changes in normal-mode)
here I've set these in .vimrc file:

enable AutoSave on Vim startup
`let g:auto_save = 1`
do not display the auto-save notification
`let g:auto_save_silent = 1`
save every change when leave insert mode(normal mode)
`let g:auto_save_events = ["InsertLeave", "TextChanged"]`

I've found it here before: https://github.com/907th/vim-auto-save
could you please add this feature in VSCodeVim? or tell us how we can do it.
regard

**Comment by ChShersh** [comment]
Hi! Why is this issue has been closed? It doesn't look resolved. I really miss this feature as well. I've asked on SO about similar feature but looks like current workarounds are not that convenient:

* https://stackoverflow.com/questions/55486502/how-to-auto-save-file-in-vscode-on-esc-when-using-vim-extension

**Comment by stasberkov** [comment]
I also would like to have this feature. I.e. this is helpful when you edit angular application that is running in watch mode.
