### ISSUE TITLE
Bug: Tab button indentation not working.

### ISSUE THREAD

**Issue by wrightwriter** [VSCodeVim/Vim#3553]
- Extension (VsCodeVim) version: 1.1.0
- VSCode version:                          1.31.1
- OS:                                               Ubuntu 14.10
- Steps to reproduce:
Select a line of text with shift + v. Press tab.
- Expected behaviour:
Line gets intended by 1 tab.
- Actual behaviour:
Nothing happens. But shift+tab unindents.

- Things tried to fix with:
add 
```
"vim.handleKeys": {
    "tab": false,
    "t": false,
}
```
to no avail.

**Comment by J-Fields** [comment]
@wrightwriter this doesn't seem to be how vim behaves, am I wrong?

**Comment by J-Fields** [comment]
Closing as I don't believe this is how vim behaves. As a workaround, you could map `<tab>` to `>`
