### ISSUE TITLE
Vim navigate on quickfix

### ISSUE THREAD

**Issue by windwp** [VSCodeVim/Vim#3556]
**Describe the solution you'd like**
Open quick fix and use vim to navigate on the list. Now I can only use arrow key to navigate

**Comment by seonggukchoi** [comment]
In my experience, this extension be broken if you are using global search.
As temporary measure, you can try to restart VSCode.

**Comment by sluongng** [comment]
Quick Fix navigation works with C-p and C-n but not with the popular keybindings

```json
// Place your key bindings in this file to override the defaults
[
    {
        "key": "ctrl+j",
        "command": "workbench.action.quickOpenSelectNext",
        "when": "inQuickOpen"
    },
    {
        "key": "ctrl+k",
        "command": "workbench.action.quickOpenSelectPrevious",
        "when": "inQuickOpen"
    },
    {
        "key": "ctrl+j",
        "command": "selectNextSuggestion",
        "when": "editorTextFocus && suggestWidgetVisible"
    },
    {
        "key": "ctrl+k",
        "command": "selectPrevSuggestion",
        "when": "editorTextFocus && suggestWidgetVisible"
    },
    {
        "key": "ctrl+h",
        "command": "list.collapse",
        "when": "listFocus && !inputFocus"
    },
    {
        "key": "ctrl+l",
        "command": "list.expand",
        "when": "listFocus && !inputFocus"
    },
    {
        "key": "ctrl+j",
        "command": "list.focusDown",
        "when": "listFocus && !inputFocus"
    },
    {
        "key": "ctrl+k",
        "command": "list.focusUp",
        "when": "listFocus && !inputFocus"
    }
]
```


I think we can custom bind it with `quickFixWidgetVisible` condition but not quite sure whats the correct action/command to bind

Reference: https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by windwp** [comment]
@sluongng  Quick Fix navigation works with C-p and C-n is only work in Mac OS not window.

**Comment by PascalSenn** [comment]
This is not possible because they use a native popup.

I created a extension as a workaround:
https://marketplace.visualstudio.com/items?itemName=pascalsenn.keyboard-quickfix

It uses the quick open picker to display codeactions. 
It is possible to navigate through these with the keyboard

**Comment by windwp** [comment]
Thank @PascalSenn  I really want to have that extension.  
https://github.com/microsoft/vscode/issues/88076

**Comment by alanmrochadeveloper** [comment]
a good workaround that I found. Give a shot guys > https://github.com/microsoft/vscode/issues/55111#issuecomment-808639067
