### ISSUE TITLE
Custom keybind breaks search

### ISSUE THREAD

**Issue by k1sul1** [VSCodeVim/Vim#3558]
I've the following keybinding so I can jump between start / close tags easily, as <kbd>Shift</kbd> + <kbd>%</kbd> seems to only work for parentheses. I don't know if I did some magic to get <kbd>Shift</kbd> + <kbd>%</kbd> jump tag in normal Vim, or if it's a core feature, but I can't live without it anymore.

```
  {
    "key": "shift+m",
    "command": "editor.emmet.action.matchTag",
    "when": "editorTextFocus && vim.active && vim.mode != 'Insert'"
  },
```

This works as expected, but it prevents me from typing a capital M at least when I'm trying to search with `/`. I can change the condition to be `vim.mode == 'Normal'` and the search works again, but that stops this keybind from working in visual mode.

How should I define the condition in this case?  `vim.mode == 'Normal' || vim.mode === 'Visual' || vim.mode == 'Visual line' || vim.mode == 'Visual block'` looks and feels horribly verbose.

**Comment by jpoon** [comment]
Not possible. If you'd like something like that, please file an issue to vscode
