### ISSUE TITLE
VsCodeVim makes workbench.tree.indent not effective

### ISSUE THREAD

**Issue by aHxShUM** [VSCodeVim/Vim#3561]
**Describe the bug**
Change `workbench.tree.indent` value and it is only effective when **Vim** is disable.
It happens for every new launch but not after reload.

**To Reproduce**

1.  Go to 'Setting'
2.  Change `workbench.tree.indent` value, says 20
3.  Exit and open VSCode

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.1.0
- VSCode version: 1.13.1
- OS: Linux

**Comment by kalenpw** [comment]
Can confirm this is happening on Xubuntu 18.04 vscode version 1.31.1 vscode 1.1.0

**Comment by kalenpw** [comment]
It appears with version vscode 1.33.1 this is resolved 🎉
