### ISSUE TITLE
Command Mode Cancels Visual Selection

### ISSUE THREAD

**Issue by jkassis** [VSCodeVim/Vim#3569]
![visual mode cancelled](https://user-images.githubusercontent.com/3630156/54074014-7c2b5480-4242-11e9-9844-e98ce6026755.gif)

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.1.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 428,
		"activateCallTime": 1,
		"activateResolvedTime": 1095,
		"activationEvent": "*"
	}
}
```

**Comment by J-Fields** [comment]
@jkassis Are you still seeing this?

**Comment by jkassis** [comment]
no. lgtm.
