### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rgeorgiev583** [VSCodeVim/Vim#3571]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.1.0`
- OS Version: `Linux x64 5.0.0-0.1-MANJARO`
- VSCode version: `1.31.1`

Here are the stats from the CPU profiler: [vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/2948889/vscodevim.vim-unresponsive.cpuprofile.txt)

**Comment by jpoon** [comment]
TBH, I have no idea where to start to investigate these issues with the cpu profile.

**Comment by jpoon** [comment]
Dupe of https://github.com/VSCodeVim/Vim/issues/3362
