### ISSUE TITLE
:reg command insert text when select a register

### ISSUE THREAD

**Issue by windwp** [VSCodeVim/Vim#3572]
When I type a command `:reg` .It display all register data and It is nice But when I select a register it only display a alert message. Is there anyway to insert this text when I select.

**Comment by J-Fields** [comment]
No, there isn't. The relevant code is here: https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/commands/register.ts#L55.

I'm sure you know that `"ap` in normal mode and `<Ctrl-R>a` in insert mode each paste from the `a` register.

This would be a pretty straightforward change and seems useful to me. I wonder what @jpoon thinks.
