### ISSUE TITLE
ex command failed

### ISSUE THREAD

**Issue by simahao** [VSCodeVim/Vim#3575]
**Describe the bug**
After setting vim.enableNeovim:true，ex command still failed

**To Reproduce**

execute command
:g/^$/d
:%s/a/b/g

**Screenshots**
![image](https://user-images.githubusercontent.com/4537287/54115234-10561100-4427-11e9-80df-374285f78af7.png)
![image](https://user-images.githubusercontent.com/4537287/54115107-cff69300-4426-11e9-9eb2-6b0a03824a94.png)
![image](https://user-images.githubusercontent.com/4537287/54115170-f6b4c980-4426-11e9-8349-ab0962bcbb00.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.32.1
- VSCode version:1.1.0
- OS:win10

**Additional context**

**Comment by jpoon** [comment]
Likely a misconfigured neovim. What's your full console log? You should see messages such as this if it was successful. https://github.com/VSCodeVim/Vim/blob/master/src/neovim/neovim.ts#L45

**Comment by simahao** [comment]
![image](https://user-images.githubusercontent.com/4537287/64023457-e4605080-cb6a-11e9-8e22-bb2e046b4238.png)

**Comment by simahao** [comment]
I thought there are confilcts among java test runner（0.19.0），checkstyle for java（1.1.0），vscodevim（1.10.0）.

**Comment by simahao** [comment]
I thought there are some conficts among checkstyle for java(1.1.0), java test runner(0.19.0) and vim(1.10.0).

**Comment by J-Fields** [comment]
Closing as stale
