### ISSUE TITLE
cannot open or close directories with L key in file navigation 

### ISSUE THREAD

**Issue by leoparis89** [VSCodeVim/Vim#3576]
**Describe the bug**
Cannot open or close a directory with L key

**To Reproduce**
Go in file tree navigation.
Try to open or close a directory by pressing the L key

**Expected behavior**
Directory should toggle between open and closed state when you press L

**Environment**
- Extension (VsCodeVim) version: 1.1.0
- VSCode version: Version 1.32.1 (1.32.1)
- OS: mac OS 10.13.6

**Comment by kolpav** [comment]
I have same problem pressing `l` should be equivalent to pressing right arrow which works fine.

**Comment by cherninely** [comment]
I have same problem too. When i press L its just focus the folder and nothing else

**Comment by joaomoreno** [comment]
This is: https://github.com/Microsoft/vscode/issues/70681

**Comment by jiexi** [comment]
Is this fixed on Insider? or do we have to wait until 1.32.4?

**Comment by joaomoreno** [comment]
This is fixed both on VS Code insiders and stable.
