### ISSUE TITLE
Search PATH for nvim when enableNeovim is true and neovimPath is empty

### ISSUE THREAD

**Issue by anurse** [VSCodeVim/Vim#3584]
I believe this is a different request than https://github.com/VSCodeVim/Vim/issues/3458 but it is related. It could make sense to do both, so I opened a new issue.

I share my VSCode settings between machines and the neovim path is not always the same on each machine (OS differences as well as just the directory in which things are installed). However, I do always make sure `nvim`/`nvim.exe` is on my `PATH`.

I suggest VSCode Vim automatically search the `PATH` directories for `nvim`/`nvim.exe` when `vim.neovimPath` is empty (but `vim.enableNeovim` is enabled). That way as long as I ensure my `PATH` is up-to-date, everything just works between machines with no need to mess with config (or have OS-specific paths as suggested in #3458)

**Comment by anurse** [comment]
Right, but the point is that I had to specify a `vim.neovimPath` value even though I had `nvim` on my `PATH`. Since my settings were shared between Windows and Linux machines, it was impossible to specify  The idea here is that I wanted VsCodeVim to just use the `nvim` that I had already placed on my `PATH`. Perhaps it works now (this was posted a few months ago), I can give it another try.

**Comment by xconverge** [comment]
I am working on implementing it. I am trying to figure out how to find the binary using the PATH variable but it is a bit tougher than I thought it would be. I was looking FOR neovim in the path (on windows it exists). I will come up with a different way

**Comment by anurse** [comment]
I've seen this code done in other places with pseudo-code like this:

```
let nvimName = os is windows ? "nvim.exe" : "nvim";
for each possible_path in PATH
    let candidate = path.join(possible_path, nvimName);
    if candidate exists
        return candidate
return null
```

**Comment by xconverge** [comment]
Yea it is a slight tweak on what I already have, it should be fine https://github.com/VSCodeVim/Vim/pull/4161/files#diff-ac248970e734939d91aacba9676bf8b7

**Comment by anurse** [comment]
Looks great! I appreciate the fix!
