### ISSUE TITLE
Support gdefault option

### ISSUE THREAD

**Issue by zombiezen** [VSCodeVim/Vim#3594]
**Is your feature request related to a problem? Please describe.**
When using the `:s` command, I frequently want to replace all instances of a pattern on a line.

**Describe the solution you'd like**
In Vim, I would [`set gdefault`](http://vimdoc.sourceforge.net/htmldoc/options.html#'gdefault') in my .vimrc. However, doing the same thing in this extension does not appear to work.

**Comment by Vintharas** [comment]
There's a setting within the VSCodeVim preferences that enables that behavior:  `vim.substituteGlobalFlag`. You can find it through the default VSCode *preferences: user settings* window.

*verbatim from the README:*


Setting | Description | Type | Default Value
------------ | ------------- | ------------ | -------------
vim.substituteGlobalFlag | Similar to Vim's gdefaultsetting. /g flag in a substitute command replaces all occurrences in the line. Without this flag, replacement occurs only for the first occurrence in each line. With this setting enabled, the g is on by default. | Boolean | false

**Comment by zombiezen** [comment]
Thanks, that works for now. I am curious why this extension doesn't recognize `gdefault` directly.

**Comment by Vintharas** [comment]
Looks like they only support a subset https://github.com/VSCodeVim/Vim#vim-settings

**Comment by jpoon** [comment]
Hm, that's confusing. We should probably consolidate these two configurations or rename `substituteGlobalFlag` to `gdefault`.

**Comment by J-Fields** [comment]
As of the next release, `substituteGlobalFlag` will be deprecated in favor of `gdefault`
