### ISSUE TITLE
support for multiple windows / views / buffers

### ISSUE THREAD

**Issue by jkassis** [VSCodeVim/Vim#3595]
**Is your feature request related to a problem? Please describe.**
it seems that there is one and only one cursor position per file (not per window) and so when multiple windows are open to the same file, the cursor jumps to the last known position in window B while performing edits in window A. quite confusing.

**Describe the solution you'd like**
the vim plugin should support separate state and history for each window, not per file.

**Describe alternatives you've considered**
alternatively, the state syncronization could be improved, but this goes against the intent of having multiple windows open with views of the same file

**Comment by J-Fields** [comment]
This appears to be fixed; holler if it's not
