### ISSUE TITLE
digraphs cannot be inputted in different order

### ISSUE THREAD

**Issue by FelipeLema** [VSCodeVim/Vim#3599]
**Describe the bug**
Digraphs should be able to inputted in any order (as long as either key combination exists). They're note

**To Reproduce**
1. Open new file
2. Press <kbd>i</kbd> to change to insert mode.
3. <kbd>Ctrl</kbd>+<kbd>k</kbd> to start digraph input
4. Press <kbd>'</kbd>
5. Press <kbd>o</kbd>

**Expected behavior**
Should write `ó` like `nvim` does, but writes nothing (asumes it's wrong input).

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.1.0
- VSCode version: VSCodium 1.31.1
- OS: Windows

**Comment by jpoon** [comment]
cc @jbaiter

**Comment by jbaiter** [comment]
Thanks for reporting, I didn't know that this was possible in vim! Should be an easy fix, I'll see to it that I have a PR ready by this weekend.
