### ISSUE TITLE
VSC can't handle '<' key in key binding (package.json)

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#36]
Using Spanish (Spain) keyboard layout.

Tried `<` and `Shift+>`. The former doesn't get forwarded from package.json, but the latter does.

`<` gets inserted into the buffer every time. `>` doesn't (as the rest of the tested keys, in this situation).

**Comment by jpoon** [comment]
Issue against https://github.com/VSCodeVim/Vim/pull/32 and related to: https://github.com/VSCodeVim/Vim/issues/9

Do you have a picture of what a Spanish keyboard looks like?

**Comment by guillermooo** [comment]
It's the MS nomenclature if that helps.But nope, I don't have a picture handy.

**Comment by guillermooo** [comment]
@jpoon 

![layout](https://cloud.githubusercontent.com/assets/684948/11410641/51c0b206-93c9-11e5-885f-40575ee39537.png)

**Comment by jpoon** [comment]
where are the angle brackets? are they the same as the up/down/left/right arrow keys?

**Comment by guillermooo** [comment]
Ah, I thought the picture was good enough, but no, it's missing some keys. The `<` key (with that label) is to the left of `z`.

**Comment by guillermooo** [comment]
@jpoon This is more like it.

![layout](https://cloud.githubusercontent.com/assets/684948/11410723/ec0ce384-93c9-11e5-9a41-12cc369e83bd.png)

I have a physical German keyboard, my Windows UI and region I think is set to US English, and I use a Spanish (Spain) keyboard layout. Yay.

If I change the Windows UI to Spanish, I can get the picture above. (By UI language I mean the one you can change from the task bar. It's probably not the correct name for this setting.)

**Comment by guillermooo** [comment]
The settings mentioned above do not seem to have an influence on whether `<` is forwarded from the key binding.

**Comment by jpoon** [comment]
Let's use https://github.com/VSCodeVim/Vim/issues/47 to track issues with international keyboards.
