### ISSUE TITLE
vim-surround does not work with multiple cursors

### ISSUE THREAD

**Issue by haberdashPI** [VSCodeVim/Vim#3600]
vim-surround does not work when using multiple cursors

It reports the following error: 

"ModeHandler: unexpected selection mode. selectionMode=10"

**To Reproduce**
Open a new file, and insert the following text:

```
this is a test repeated
of vim-surround repeated
```

In normal mode, place cursor on the word "repeated"; use Cmd-D (or "gb") twice to select both instances of "repeated".

Then, type "bvysw)" (to go to beginning of the word ("b"), switch from visual to normal ("v"), and then use vim surround to add parentheses around the word ("ysw)")). 

**Expected behavior**
I would expect the following text to appear:

```
this is a test (repeated)
of vim-surround (repeated)
```

**Comment by admosity** [comment]
Dupe #1818
