### ISSUE TITLE
The original vim's redo command (Ctrl+Shift+R) doesn't work

### ISSUE THREAD

**Issue by SebasSBM** [VSCodeVim/Vim#3608]
**Describe the bug**
The original `vim` commandline editor permitted to undo with `u`, and redo with `Ctrl Shift R`. This plugin is unable to redo with `Ctrl Shift R`.

**To Reproduce**

1.  Empty file
2.  `i`, type "This sentence will be undone..."
3.  `u` to undo
3.  `Ctrl Shift R` to redo
4.  Didn't work, VSCode Menu --> Edit --> Redo
5.  Didn't work either

**Expected behavior**
Pressing the keys `Ctrl Shift R` should work to redo (the original Vim worked that way)... it would also be prefereable that the `u` and `Ctrl Shift R` original undo/redo functions (respectively) were integrated with Vs Code's undo/redo functionality.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.2.0
- VSCode version: 1.32.3
- OS: Linux Mint 17.2 Rafaela

**Comment by rickythefox** [comment]
Isn't it `Ctrl r` (no shift)?
http://vimdoc.sourceforge.net/htmldoc/undo.html#undo

**Comment by J-Fields** [comment]
I wasn't aware of it either, but seems like `ctrl+shift+r` works also

**Comment by SebasSBM** [comment]
@rickythefox, you are right! For some reason, I had it memorized as `ctrl+shift+R`... but, even in original Vim, ir also works with `ctrl+r`...

I also tested it in `VSCodeVim`, and it works as expected...

I'm sorry for opening an issue due to such a mistake of mine...
