### ISSUE TITLE
Backspace ends auto-suggestions

### ISSUE THREAD

**Issue by coreysharris** [VSCodeVim/Vim#3613]
**Describe the bug**
When the Vim extension is enabled, any auto-completion suggestions are terminated upon pressing backspace.  This happens for many language and completion providers.

**To Reproduce**

1. Open any file in a language with auto-completion support
2.  Type something to trigger suggestions
3.  Press \<backspace\>
4.  See the suggestions panel disappear.

**Expected behavior**
The behaviour is as expected when Vim is disabled: \<backspace\> does not kill the suggestions panel.

**Screenshots**

![vimBackspaceTS](https://user-images.githubusercontent.com/186528/54823520-6c7f2780-4ca8-11e9-85cc-291fc0a94819.gif)

![vimBackspacePy](https://user-images.githubusercontent.com/186528/54823532-730d9f00-4ca8-11e9-894a-2ebcd42c039b.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.2.0
- VSCode version: 1.32.3
- OS: macOS Mojave 10.14.3

**Comment by DCsunset** [comment]
Especially when editing `settings.json`, if I press backspace, the auto-suggestions will never appear, unless I remove the whole line.

**Comment by J-Fields** [comment]
Seems this can be fixed if we let VSCode handle `<BS>` in insert mode. Not sure if this causes any immediate problems (we couldn't customize whether it goes through EOL, but that seems relatively minor), I'll need to dig into this some more.
