### ISSUE TITLE
Search (/) is broken in multi-cursor mode

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#3618]
**Describe the bug**
Trying to do a search when you have multiple cursors just throws errors.

**To Reproduce**

1.  `alt-click` somewhere to create a second cursor
2.  Hit `/`
3.  Notice error message: `ModeHandler: unexpected selection mode. selectionMode=5`
4.  Hit another key
5.  Notice more error messages like: `TaskQueue: Error running task. Failed to handle key=j. Cannot read property 'start' of undefined.`

**Expected behavior**
I'm actually not sure what expected behavior in multi-cursor mode is, but it's probably not this 🙂 

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.2.0
- VSCode version: 1.32.3
- OS: Windows 10

**Comment by anotherKeith** [comment]
Multi-cursor behavior is implemented in VIM with a plugin.
Without the plugin, Alt-Click is a "select block" action.

**Comment by J-Fields** [comment]
Superseded by #5844
