### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vignesh0025** [VSCodeVim/Vim#3622]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.2.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.32.3`

[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3000505/vscodevim.vim-unresponsive.cpuprofile.txt)

**Comment by jpoon** [comment]
Dupe of https://github.com/VSCodeVim/Vim/issues/3362
