### ISSUE TITLE
Adding vim style 'Go to Symbol in Workspace' shortcut

### ISSUE THREAD

**Issue by mirkancal** [VSCodeVim/Vim#3624]
I can't use `Go To Symbol in Workspace` since vim extension is also using it's shortcut(Ctrl+T). In the vscodevim tricks section there a couple of shortcuts that starts with g, I wanted to add one for myself. Here's the code:

`{
    "key": "g s",
    "command": "workbench.action.showAllSymbols",
    "when": "vim.mode == 'Normal'"

  }`

Now I can't use `gh`, `gd` because the editor says:
`(G) was pressed. Waiting for the second key chord.`

How can I make it work?

**Comment by cemiloten** [comment]
Can you try adding this to your settings.json?

```
"vim.normalModeKeyBindingsNonRecursive": [
    ...
    
    {
        "before": ["g", "s"],
        "commands": ["workbench.action.showAllSymbols"]
    },

    ...
]
```
