### ISSUE TITLE
Problem with vim plugin on Ubuntu - inputMethod

### ISSUE THREAD

**Issue by es1o** [VSCodeVim/Vim#3625]
Hello I have a problem with vim plugin on ubuntu. It doesn't work because of error:

> Configuration: Unable to find /path/to/im-select. Check your 'vim.autoSwitchInputMethod.obtainIMCmd' in VSCode setting.

How can I fix that? I use VScode 1.32.3 and VSCodeVim 1.2.0

I don't know which inputMethod should I use, I didn't modify config, it stopped working after upgrade.

**Comment by jpoon** [comment]
As stated in the error message, check your `autoSwitchInputMethod` setting. https://github.com/VSCodeVim/Vim#input-method

**Comment by es1o** [comment]
@jpoon It is a lack of documentation. I don't understand what input method shall I use. Everything was work before update.
