### ISSUE TITLE
Feature request: activate easymotion by press <leader> only one time.

### ISSUE THREAD

**Issue by 9527KGG** [VSCodeVim/Vim#3632]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently, by default, to active easymotion, I have to type \<leader\>\<leader\>, 2 times.
I want to type \<leader\> 1 time to active easymotion, because I use it a lot

In Vim, I can add "map \<Leader\> \<Plug\>(easymotion-prefix)" to achieve the goal.

Please add this support to vscode vim. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

Thanks.

**Comment by 9527KGG** [comment]
I found that:

    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["leader", "w"],
            "after": ["leader", "leader", "w"],
        }
    ],   
is working.

But if I add more,
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["leader", "w"],
            "after": ["leader", "leader", "w"],
        }
    ],    
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["leader", "b"],
            "after": ["leader", "leader", "b"],
        }
    ],    
stop working.

Any suggestions?

**Comment by 9527KGG** [comment]
Just realized the correct way to workaround is:

"vim.normalModeKeyBindingsNonRecursive": [
{
"before": ["leader", "w"],
"after": ["leader", "leader", "w"],
}
{
"before": ["leader", "b"],
"after": ["leader", "leader", "b"],
}
],

Please add the direct support if possible

**Comment by J-Fields** [comment]
This is what remapping is for 🙂

**Comment by zhangxueyii** [comment]
This remapping works well for me. only one key `;` to replace the most used combination.

`    {
      "before": [
        ";"
      ],
      "after": [
        "leader",
        "leader",
        "/"
      ],
    },
`

**Comment by Axibord** [comment]
> 

Because you are overriding it by creating another key "vim.normalModeKeyBindingsNonRecursive", it's an array, just add the object to the array like so

```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["leader", "w"],
      "after": ["leader", "leader", "w"]
    },
    {
      "before": ["leader", "b"],
      "after": ["leader", "leader", "b"]
    }
]
```

**Comment by ic-it** [comment]
Add this maps into your .vimrc file

```vimscript
map <leader>s <leader><leader>s
map <leader>f <leader><leader>f
map <leader>F <leader><leader>F
map <leader>t <leader><leader>t
map <leader>T <leader><leader>T
# map <leader>w <leader><leader>w # Collides with camelcase plug
# map <leader>b <leader><leader>b # Collides with camelcase plug
map <leader>l <leader><leader>l
map <leader>h <leader><leader>h
# map <leader>e <leader><leader>e # Collides with camelcase plug
map <leader>ge <leader><leader>ge
map <leader>j <leader><leader>j
map <leader>k <leader><leader>k
map <leader>/ <leader><leader>/
map <leader>bdt <leader><leader>bdt
map <leader>bdw <leader><leader>bdw
map <leader>bde <leader><leader>bde
map <leader>bdj <leader><leader>bdj
map <leader>j <leader><leader>j
```

**Comment by aardvarkk** [comment]
This worked for me (in `settings.json), making it so a single tap of the space key acts as the required "double leader" for EasyMotion:

```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["space"],
      "after": ["leader", "leader"]
    }
  ]
```

**Comment by OsicKwon** [comment]
Anyone know why the remap below doesn't work regarding easymotion?
-----

    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>", "w"],
            "after": ["<leader>", "<leader>", "b", "d", "w"]
        }
    ],
