### ISSUE TITLE
I can't continuous movement the cursor ,and copy or delete more line.

### ISSUE THREAD

**Issue by sober-wang** [VSCodeVim/Vim#3634]
**Is your feature request related to a problem? Please describe.**
* I'm always terrible when I hold `hjkl` ,the cursor can't continuous movement（MacOS）
* the Vim plugins  can't copy or delete more line. e.g Esc -> :1,100y or 2,222d(All OS)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sober-wang** [comment]
CommandLine: Error executing cmd=173d. err=TypeError: Cannot read property 'type' of undefined.

**Comment by salmansheikh** [comment]
Yes, in OSX for some reason holding down the 'j' key doesn't continually go to the next line. I have to keep lifting my finger. I need to find a vim extension that supports that else this will really slow my navigation down.

**Comment by areinmeyer** [comment]
Have you followed the instructions here? https://github.com/VSCodeVim/Vim#mac 

Once I enabled that, holding down the movement keys `h,j,k,l` allowed for the repeated actions.

**Comment by sober-wang** [comment]
> Have you followed the instructions here? https://github.com/VSCodeVim/Vim#mac
> 
> Once I enabled that, holding down the movement keys `h,j,k,l` allowed for the repeated actions.

> Thanks. I can use `h,j,k,l` continuous movement the cursor.

**Comment by sober-wang** [comment]
Oh, god. I think the issue is no fix . 
I use Vim command ":1,7y" , that status bar is show "E492 Not an editor command 1,7y". 
I read   "VSCodeVim settings"  of  README.md file, I not find support Vim batch copy command setting.

**Comment by J-Fields** [comment]
@sober-wang `:1,7y` works with neovim integration.
