### ISSUE TITLE
Support :bd to close current buffer

### ISSUE THREAD

**Issue by paulgreg** [VSCodeVim/Vim#3638]
**Is your feature request related to a problem? Please describe.**
Under VIM, I’m used to type `:bd` to close the current file/buffer.
That command isn’t working under VSCodeVim : `Not and editor command bd`
To close the current buffer, only `:q` works which isn’t correct : `:q` under VIM close VIM (and all files/buffers opened)
`:bd` seems a better command to close the current file/buffer.

**Describe the solution you'd like**
I would like that `:bd` close the current file/buffer.
Ideally, `:q` should close VSCodeVim, like what VIM is doing (but I understood it’s quite a change for people used to)

**Describe alternatives you've considered**
No idea

**Additional context**
I think it’s important because VSCodeVim « learns » you to use `:q` to close current buffer which is not correct under vim. So, if you’re using VIM later on, you could close VIM by « habit ».

**Comment by jay-khatri** [comment]
@J-Fields Could I take a crack at this? From what I understand, I'll need to create a new `buffer.ts` in `commands/` and `/subparsers`.  

Also, just to confirm, in VScode, we're treating open tabs as buffers?

**Comment by jay-khatri** [comment]
bump

**Comment by J-Fields** [comment]
@jay-khatri Sure; that looks right. Yeah tabs VSCode tabs map to vim buffers.

**Comment by vedran** [comment]
@jay-khatri are you still doing this one? If not, I'm interested in taking it over. Thanks!
(cc @J-Fields)

**Comment by th-ad** [comment]
Traditionally, `:bd` would behave by closing all windows to a certain buffer. Because VSCode tabs map to buffers (not windows), would that not be the case here?

**Comment by th-ad** [comment]
@vedran Are you working on this right now? I have some ideas about how this feature should function. I would be happy to take it off your hands! (@J-Fields)

**Comment by jay-khatri** [comment]
@vedran @th-ad Haven't gotten a chance to get a PR out, its is up for grabs :).

**Comment by vedran** [comment]
@th-ad I haven't started on it yet, was planning to the following weekend. If you've already spent some time thinking about it, feel free to take it :)
