### ISSUE TITLE
catastrophic performance

### ISSUE THREAD

**Issue by plbowers** [VSCodeVim/Vim#3654]
Issue Type: <b>Bug</b>

After a recent upgrade (both the vim emulator and the vscode editor, I believe) my performance has absolutely tanked.

I am waiting 10 and 20 seconds for the buffer to catch up to my keyboard buffer. Previous to this update I was typing naturally and never noticed any lag at all.

Steps to reproduce? Press i or cw or A or etc to go into editing mode and start typing.

Extension version: 1.3.0
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Hultner** [comment]
I just started using vscode (with vscvim) and I've noticed this as well. I was assuming that vscode/vscodevim was just this slow but maybe it's just this version? I've also noticed that the entire editor sometimes changes color theme back to the default dark one when I queue up to many actions in vim, especially when I use recordings.

**Comment by plbowers** [comment]
I ran the process explorer and saw that my CPU usage went way high as soon as I tried to do anything in edit mode. I disabled the vim extension and the problem disappeared entirely.

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/pull/3662

**Comment by jpoon** [comment]
The performance degradation in the 1.3.0 has been resolved in the latest revision with #3662. As such, im goign to close this out.

**Comment by Hultner** [comment]
@jpoon Thanks, I'm so happy that this was a bug and not actual expected performance :D 

Huge thanks to you and the rest of the team behind VSCodeVim for the hard work making this a reality.

**Comment by jpoon** [comment]
All credit goes to @ajalab on that one.
