### ISSUE TITLE
can't choose next item

### ISSUE THREAD

**Issue by LittleFatHero** [VSCodeVim/Vim#3671]
I use the _**/process**_ command to find the key word 'process' in my source code file in normal mode. It did find the key word and highlight them but I can't use the key **_n_** to choose the next    
item that has been found.

**Comment by areinmeyer** [comment]
This works for me as I use the same method quite a bit.  Can you provide more details on your setup like versions of VS Code, Vim, and OS?  Any keybindings you have setup?  I'm on the latest versions of VS Code and Vim with Mac OSX.

**Comment by LittleFatHero** [comment]
I'm on the latest versions of VS Code and vim with  windows 10 .  
When I finished entering **_/process_** , It highlight all the item, as usual , I should hit the _**enter**_ key and then press the **_n_** key so that I could choose the next item that has been found. But When I hit the **_enter_** key , all the item that have been highlight have gone.
By the way , I did not set any keybindings, all is default!

**Comment by LittleFatHero** [comment]
I'm sorry. It did work. I can choose the next found item.  I just reboot my vscode. and it worked!
