### ISSUE TITLE
Remapped Escape key (in Gnome desktop) not working in VS Code, vim mode

### ISSUE THREAD

**Issue by uuujf** [VSCodeVim/Vim#3674]
Issue Type: <b>Bug</b>

I use Fedora 29, Gnome 3.30. To reproduce the problem, 
- Remap CapsLock as Esc via gnome-tweak-tool
- Use vim extension in VS Code
- You will find the CapsLock cannot function as Esc in VS Code, vim mode.
- The original Esc indeed works though.

Extension version: 1.4.0
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:08:57.775Z)
OS version: Linux x64 5.0.7-200.fc29.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 1983)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.54GB (3.25GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by avieor** [comment]
I am having the exact same problem as user uuujf above.

Extension version: 1.7.0
Visual Studio Code Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-48-generic

**Comment by lydell** [comment]
```json
"keyboard.dispatch": "keyCode"
```

https://github.com/Microsoft/vscode/issues/23991

**Comment by dagolinuxoid** [comment]
I think the issue can be closed since @lydell nailed it.
