### ISSUE TITLE
:[line number]d causes type error

### ISSUE THREAD

**Issue by Nader-gator** [VSCodeVim/Vim#3678]
when I execute the command `:[line number]d`, which should delete the entire line, `:75d` for example, vscode throws a type error. this type error happens both whether line 75 exists with code on it or not

here's my config file 

```json
"vim.easymotion": true,
    "vim.sneak": true,
    "vim.incsearch": true,
    "vim.useSystemClipboard": true,
    "vim.useCtrlKeys": true,
    "vim.hlsearch": true,
    "vim.insertModeKeyBindings": [{
        "before": ["j", "j"],
        "after": ["<Esc>"]
    }],
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>", "d"],
            "after": ["d", "d"]
        },
        {
            "before": ["<C-n>"],
            "commands": [":nohl"]
        },
        {
            "before": ["<leader>","s"],
            "after": ["<leader>", "<leader>", "<leader>","b","d","w"]
        }
    ],
    "vim.leader": "<space>",
    "vim.handleKeys": {
        "<C-a>": false,
        "<C-f>": false
    },
    "vim.easymotionMarkerYOffset": 5,
    // "vim.easymotionMarkerForegroundColorTwoChar":"blue",
    "vim.easymotionMarkerBackgroundColor":"gray",
    "vim.easymotionMarkerFontWeight":"bold"
```
<img width="542" alt="Screen Shot 2019-04-14 at 1 35 40 PM" src="https://user-images.githubusercontent.com/41534756/56096792-b8de1180-5eba-11e9-98f2-54a17ccfc53c.png">

- Extension (VsCodeVim) version: 1.4.0
- VSCode version: 1.33.1
- OS: MacOS 10.14.4

**Comment by areinmeyer** [comment]
Looks like you need `Enable neovim` (`vim.enableNeoVim: true`) set to true to use the `:[x]d` command.  Set to true that command works for me, but when it's set to false I get the same error as you did.

**Comment by Nader-gator** [comment]
yea that seems to resolve the issue
