### ISSUE TITLE
Surround: Implement whitespace configuration

### ISSUE THREAD

**Issue by Phrohdoh** [VSCodeVim/Vim#3681]
Say you have the following text:

```
Hello, welcome to Atlantis!
```

If your cursor is on `Atlantis` and you do <kbd>viwS_</kbd> you get `_Atlantis_`.

If you do <kbd>viwS[</kbd> you get `[ Atlantis ]`, notice the whitespace.

I often don't want this whitespace to be added for me (if I did I would have done <kbd>viwS </kbd>).

It would be nice if users could configure which surround keys added whitespace.

**Comment by esetnik** [comment]
The open surround key adds whitespace and the close surround key does not. E.g. <kbd>viwS[</kbd> adds with whitespace and <kbd>viwS]</kbd> does not. Also, a tip is that for your particular example you don't need to use visual mode. It might be preferable to use the `you surround` syntax <kbd>ysiw]</kbd> as mentioned in the docs.

**Comment by Phrohdoh** [comment]
Oh, very neat, thank you!

I'll close this in light of the fact that the desired functionality is already possible -- no need for unnecessary knobs.
