### ISSUE TITLE
Easy motion shows error when jumping to brackets and backslash

### ISSUE THREAD

**Issue by nnkken** [VSCodeVim/Vim#3685]
**Describe the bug**
When using easy motion, functions which allows jumping to specified symbols (e.g. `<leader><leader>f`, `<leader><leader>s`), some symbols (which have special meaning in regexp) are not supported and will generate error (about invalid regexp) when used.

When `()[?\` are used, error message are shown.

When `$` is used, position marks are shown at incorrect position (end of line).

When `^` is used, the Vim plugin is stuck and not responding to any inputs.

**To Reproduce**

1. turn easy motion on in settings
2. suppose we have text `(bracket) [square bracket] \backslash ?question_mark ^start $end`
3. input `<leader><leader>f(` or `<leader><leader>f)` or `<leader><leader>f[` or `<leader><leader>f\` or `<leader><leader>f?` or `<leader><leader>f^` or `<leader><leader>f$`

**Expected behavior**
symbols are shown at the corresponding position, or jump to the symbols directly when there is no other matches

**Screenshots**
![vscode-easy-motion](https://user-images.githubusercontent.com/6733599/56297686-607d6d00-6163-11e9-82df-fd37c70c1617.png)

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.4.0
- VSCode version: 1.33.1
- OS: Windows 10 Pro 64-bit

**Additional context**

**Comment by J-Fields** [comment]
This was fixed with https://github.com/VSCodeVim/Vim/pull/3911
