### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nthequilibrium** [VSCodeVim/Vim#3688]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.4.0`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.1`
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3094555/vscodevim.vim-unresponsive.cpuprofile.txt)

**Comment by jpoon** [comment]
Dupe of #3362
