### ISSUE TITLE
`dw` eats EOF

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#369]
When you run `dw` inside the last word of a line and have more lines behind current line in JavaScript or JSON files, `dw` will eat EOF and move following line after the cursor. I suppose it's a VS Code as it only happens with JavaScript, looks like some `autocomplete` stuff. But I still create an issue here and see @johnfn input and finally move it to VS Code repo issue list.

**Comment by johnfn** [comment]
Definitely not just JS/JSON files - I've seen it happen in all sorts of different files. (In any case, our 'word' handling is not language specific 😄 ) 

I'm sure this is just an edge case in `execActionForOperator` for "w". PRs welcome!

**Comment by rebornix** [comment]
Closed as Fixed.
