### ISSUE TITLE
Hive ctrl+G show which file is editing been supported?

### ISSUE THREAD

**Issue by g10guang** [VSCodeVim/Vim#3700]
**Is your feature request related to a problem? Please describe.**
I often jump to symbol definition when I am coding. With so many jump step, I don't know which path of file I am editing.

**Describe the solution you'd like**
Like Vim Ctrl+G shortcut to show which file I am editing, which is also supported by IdeaVim.

**Additional context**
![image](https://user-images.githubusercontent.com/18458140/56547449-1b689900-65b0-11e9-85ea-6e159357065a.png)
![image](https://user-images.githubusercontent.com/18458140/56547469-28858800-65b0-11e9-9bdd-03572ede6593.png)

Have it been supported yet?

**Comment by g10guang** [comment]
Any shortcut to show file path in vscode?

**Comment by J-Fields** [comment]
I'll look into supporting `Ctrl+G` when I get a chance, but the setting `breadcrumbs.enabled` gives you breadcrumbs which reveal the current file's path (relative to the workspace, but still). In addition, `Shift+Alt+C` copies the current file's absolute path to the clipboard.
