### ISSUE TITLE
vim.debug.suppress invalid

### ISSUE THREAD

**Issue by antoinegag** [VSCodeVim/Vim#3703]
**Describe the bug**
Clicking on "Suppress" when an error pops up from the extension reads that we should configure `vim.debug.suppress` but it does not seem to be recognized as a valid setting when added to my User `settings.json`

**Expected behavior**
`vim.debug.suppress` to be a valid setting or the modal to show the correct setting

**Screenshots**
![image](https://user-images.githubusercontent.com/25696312/56666743-723aa500-667a-11e9-81bc-0686481b32a8.png)

![image](https://user-images.githubusercontent.com/25696312/56666865-b037c900-667a-11e9-91e6-02629ef6111a.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.4.0
- VSCode version: 1.33.1
- OS: MacOS Mojave 10.14.4

**Additional context**
I think the setting has been replaced by `vim.debug.silent`

I've also noticed that `vim.debug.suppress` is mentioned in the doc, not sure if outdated or if I'm doing something wrong on my end.

**Comment by jpoon** [comment]
somebody submitted a PR for this https://github.com/VSCodeVim/Vim/pull/3591. feel free to take it over. it's an easy fix.

**Comment by antoinegag** [comment]
Forgot to look through the PRs my bad. Will check that out 😁
