### ISSUE TITLE
中文输入模式下，在 integrated terminal 里面，用 Caps Lock 键切换到英文，无法输入小写字母

### ISSUE THREAD

**Issue by yifanchen** [VSCodeVim/Vim#3705]
**Describe the bug**
中文输入模式下，在 integrated terminal 里面，用 Caps Lock 键切换到英文，无法输入小写字母。然为，在编辑器里面是表现正常。

**To Reproduce**

1. 打开 vscode 
2. 打开 integrated terminal
3. 输入法模式切换成中文（Mojave 右上角）
4. 用 Caps Lock 键切换到英文输入法，此时任何输入字母呈现大写状态。

**Expected behavior**

1. 打开 vscode 
2. 打开 integrated terminal
3. 输入法模式切换成中文（Mojave 右上角）
4. 用 Caps Lock 键切换到英文输入法，此时任何输入字母呈现小写状态。

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version: latest
- OS: Mojave

**Additional context**

**Comment by yifanchen** [comment]
![image](https://user-images.githubusercontent.com/2340896/56875288-6bdd6c00-6a72-11e9-91a0-6d6babea4a6e.png)

**Comment by thought7878** [comment]
感谢解决方案！

**Comment by yifanchen** [comment]
如果用 Sougou input 的话，还是存在上述问题。

**Comment by imaginezz** [comment]
我也遇到了相同的问题

**Comment by taozhang-tt** [comment]
为什么没有解决方案呢

**Comment by guoshuohui** [comment]
好烦啊，我也遇到这个问题，找不到任何解决翻案~

**Comment by failedUser** [comment]
Big sur 依然有这个问题，即便是我按照楼上的方式改了配置

**Comment by oneleo** [comment]
我個人使用的是嘸蝦米，但此時此刻都還仍有上述問題
