### ISSUE TITLE
cannot copy mutiple lines with :a,by command.

### ISSUE THREAD

**Issue by wxutopia** [VSCodeVim/Vim#3706]
**Describe the bug**
I can't use command :a,by to copy content from line a to line b.The error is: not an editor command.

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**
windows 10, vim 1.40, vscode 1.33.1.

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by leotohill** [comment]
me too (similar).  Trying :1,5co.  or :1,5t. .

**Comment by J-Fields** [comment]
This works with neovim integration.
