### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fsoft72** [VSCodeVim/Vim#3707]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.4.0`
- OS Version: `Linux x64 4.18.0-17-generic`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3123781/vscodevim.vim-unresponsive.cpuprofile.txt)

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/3702#issuecomment-486395642
