### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SamEga** [VSCodeVim/Vim#3711]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.4.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Sam\vscodevim.vim-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment]
Closing for same reasons as https://github.com/VSCodeVim/Vim/issues/3702#issuecomment-486395642
