### ISSUE TITLE
paste register of recorded macro will run the macro instead of pasting the content

### ISSUE THREAD

**Issue by swuecho** [VSCodeVim/Vim#3714]
**Describe the bug**

`"mp` will run the cmd in register <code>m</code> instead of paste the content in m

**To Reproduce**

1. record a macro

Press: `qm`: To start recording macro under m register.

Press: `ia`: insert `a' charactar.

Press:  `Esc`: go to cmd mode

Press: `q`: end the macro

2. paste the macro

vim in terminal on Mac:
press `"mp` will get `ia^[`

in vim mode of vscode, will insert `a`.

the difference is that `"mp` will run the cmd in register `m`in vscode and in native vim, the content of macro will be pasted

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.7.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.33.1`

**Comment by dstj** [comment]
I got the same problem with Windows 10, VSCode v1.34 and Vim v1.8.1.
This make fixing a typo in long macro quite hard...

**Comment by theiwaz** [comment]
Same, windows 10,VSCode 1.32.3, VIM 1.2.0

**Comment by chrahunt** [comment]
Related to #1658.
