### ISSUE TITLE
Implement save-on-esc (or save on leaving insert mode) feature

### ISSUE THREAD

**Issue by chshersh** [VSCodeVim/Vim#3717]
First of all, thanks for implementing this plugin! I really enjoyed using Vim keybindings in VSCode 🙂 However, I would like to propose possible feature.

**Is your feature request related to a problem? Please describe.**

When working with files as a `vim` user I constantly switch between _normal_ and _insert_ modes. When I switch back from _insert_ mode to _normal_ I don't want to lose my changes. I also don't want to save files manually. So I would like to have configuration flag that allows to enable _save-on-esc_ feature.

**Describe the solution you'd like**

When the <kbd>Esc</kbd> button is pressed, the content of the file should be saved on disc.

**Describe alternatives you've considered**

Alternative solutions are described in this SO question, but they provide poor UX:

* https://stackoverflow.com/questions/55486502/how-to-auto-save-file-in-vscode-on-esc-when-using-vim-extension

**Additional context**

I'm using Spacemacs currently, and there I can enable this feature without any problems. I would like to switch to VSCode and I'm really missing this feature 😢 

Also, similar issue: https://github.com/VSCodeVim/Vim/issues/3550

**Comment by J-Fields** [comment]
Is [VSCode's auto-save feature](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save) insufficient for your needs?

**Comment by chshersh** [comment]
@J-Fields Thanks for pointing to this feature! I see that the workflow is different, but I think this should cover my case.

**Comment by chshersh** [comment]
I've tried to use `auto-save` feature of VSCode for some time and noticed several inconveniences.

1. Saving on focus-change or window-change is not enough. I often work with one open file without switching.
2. I need to call some actions when file is saved, like running `stylish-haskell` over the content of the file. This tool also does the cleanup of trailing whitespaces. Because of that (since I'm saving on delay) I'm observing sporadic cursor movements when I type the space character at the end of the line before typing other words. Also, running multiple actions on save on delay too often consumes more resources.

So that's why I'm reopening the issue. I still think that save after leaving insert mode is quite useful and convenient. It also combines nicely with `auto-save`: I can have both auto-save on focus-change and on leaving insert mode.

**Comment by astier** [comment]
I would like to have the options to be able to save on the vim events `InsertLeave` and `TextChanged`.

**Comment by chshersh** [comment]
Is there a way to open a bounty for this issue? I'm gladly donate some money and support OSS to have this feature implemented 🙂

**Comment by jjablonski-it** [comment]
If i understand correctly you can set
```
"vim.insertModeKeyBindings": [
    {
      "before": ["<Esc>"],
      "after": ["<Esc>"],
      "commands": ["workbench.action.files.save"]
    }
  ],
```
in your json settings

**Comment by chshersh** [comment]
@jjablonski-it Thanks for your reply! I tried this approach, and it works smoothly for me now 🔝 
I've accepted the corresponding SO answer and I'm closing this issue as it seems resolved.

<hr>

Additionally, I want to provide some more context in case anyone has a similar problem. I also want to run executables on file-save (e.g. code formatters). Fortunately, the above trick still works. I'm using the [Run on Save](https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save) VSCode plugin. In my case, I have the following VSCode confg to run the `stylish-haskell` formatter on save:

```json
"runOnSave.commands": [
    {
      "match": "\\.hs$",
      "command": "stylish-haskell -c ${workspaceFolder}/.stylish-haskell.yaml -i ${file} || true",
      "runIn": "backend"
    }
  ]
```

**Comment by JoeRoddy** [comment]
@jjablonski-it @chshersh  Sorry if this is a stupid question, I'm a vim noob.

I have esc rebound to `jk` via my vimrc with `inoremap jk <ESC>`, which I find a lot more ergonomic for my fingers.

Do you know if there's any way to achieve a similar thing to what you were describing but with two keys (j, then k) instead of escape?

**Comment by briangwaltney** [comment]
`"vim.insertModeKeyBindings": [
{
      "before": ["j", "k"],
      "after": ["<Esc>"],
      "commands": ["workbench.action.files.save"]
    }
  ]`
  
  That should work to make the two key option do the same thing. The commands section is the important part. You can add that to whatever keybinding you've set.

**Comment by JoeRoddy** [comment]
Worked perfectly, thanks @briangwaltney ! :D

**Comment by ibanks42** [comment]
For some reason I had issues with this being slow with the Zig Language extension specifically, and my cursor would hang while waiting for `workbench.action.files.save` to call and finish.

I have adjusted it to call `:w` instead:

```json
"vim.insertModeKeyBindings": [
  {
    "before": [
      "j",
      "j"
    ],
    "after": [
      "<Esc>"
    ]
  },
  {
    "before": [
      "j",
      "k"
    ],
    "after": [
      "<Esc>",
    ],
    "commands": [
      ":w"
    ]
  }
],
```
