### ISSUE TITLE
pressing escape after git checkout initiated by a leader key renders VSCode unusable

### ISSUE THREAD

**Issue by benwainwright** [VSCodeVim/Vim#3718]
**Describe the bug**
I use a leader key to access "Git checkout". If I press "escape" to cancel, I can longer edit any text at all. It's as if it's remaining locked in leader mode.

**To Reproduce**
1. Add the following configuration to your seetings.json
```
  "vim.leader": "<space>",
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["<leader>", "c"],
      "commands": ["git.checkout"]
    }
```
2. Navigate to a project containing a git repository
3. Press `<space> c`
4. Press escape

Hey presto. VSCode is now effectively **completely broken**. I can no longer type ANY text into the editor.

**Expected behavior**
Being able to type text into the editor

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.7.0
- VSCode version: 1.33.1
- OS: MacOS 10.14.3

**Comment by uloco** [comment]
@benwainwright Hey, why did you close this? Did you find any solution to it? Had the same problem ... :/

**Comment by benwainwright** [comment]
I closed this because I've ditched VSCode in favour of real vim.

This plugin is not really usable in my view.

**Comment by uloco** [comment]
Ok, thanks. Sad to hear that 😞

**Comment by jacekbogdanski** [comment]
The issue is still present, @uloco did you find any solution?

**Comment by uloco** [comment]
I'm not using this keybinding :/
