### ISSUE TITLE
Set extensionKind in package.json to support Remote Development

### ISSUE THREAD

**Issue by mjbvz** [VSCodeVim/Vim#3720]
Hi, I'm on the VS Code team. We recently released support for [Remote Development](https://code.visualstudio.com/blogs/2019/05/02/remote-development) and I noticed that your may extension need a small change to ensure users have a good experience when using it remote workspaces.

## What is the issue?
To make remote development as transparent as possible to users, VS Code distinguishes two classes of extensions:

- **UI Extensions**: These extensions make contributions to the VS Code user interface and are always run on the user's local machine. UI Extensions cannot directly access files in the workspace, or run scripts/tools installed in that workspace or on the machine. Example UI Extensions include: themes, snippets, language grammars, and keymaps.

- **Workspace Extensions**: These extensions are run on the same machine as where the workspace is located. When in a local workspace, Workspace Extensions are run on the local machine. When in a remote workspace, Workspace Extensions are run on the remote machine. Workspace Extensions can access files in the workspace to provide rich, multi-file language services, debugger support, or perform complex operations on multiple files in workspace (either themselves or by invoking scripts/tools). 

You can find more details about this architecture [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-types).

**VS Code currently infers that your extension is a Workspace Extension. This means that users who have your extension installed must also install it to the remote in order to use it in remote workspaces.** I believe that your extension should probably be a UI extension instead. That way your extension will always be enabled for users who install it, even if they open a remote workspace.

## How do I fix this?
To tell VS Code that your extension is a UI extension, just add [`"extensionKind": "ui"`](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) to your extension's package.json.

UI Extensions always run on the user's local machine, even when they open a remote workspace. 

I'll submit a PR that does this. Please let me know if you have any questions or concerns about the issue. We've also put together [a guide](https://code.visualstudio.com/api/advanced-topics/remote-extensions#testing-and-debugging-your-extension) to help you test your extension in remote workspaces

*PS: As a temporary workaround for a few popular extensions, we've automatically added your extension to an internal whitelist so that is always treated as a UI extension*

**Comment by lilixiong2018** [comment]
Well, it seem it solve #3710.
