### ISSUE TITLE
C-o after goToDeclaration doesn't work

### ISSUE THREAD

**Issue by suo** [VSCodeVim/Vim#3726]
**Describe the bug**
If you use `gd` to go to a declaration, then press `C-o`, VSCodeVim will return to the previous location. If you press `C-o` a second time, it will go back.

**To Reproduce**

1.  Use `gd` on a symbol
2.  Press `C-o`. Observe nothing happening
3.  Press `C-o` again. The correct behavior should happen.

**Expected behavior**
I expect the first `C-o` to take me back.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.7.0
- VSCode version: 1.33.1
- OS: Mac

**Additional context**

**Comment by J-Fields** [comment]
Should be fixed in 1.21.7
