### ISSUE TITLE
Indent my code from line m to n with `:m,n>` command

### ISSUE THREAD

**Issue by LittleFatHero** [VSCodeVim/Vim#3733]
VSCode Verson: 1.33.1
VSCodeVim Version: 1.7.1
OS : windows 10 professional
Feature request：  
In vim, if I want to indent my code from line m to n, I can use the command ": m,n>" or "m,n<" in normal mode, it is very convenient. But in VSCodeVim, I can't use the command to do this. Is it that the VSCodeVim do not support the command "m,n>" ? If so, I hope that VSCodeVim can support the command, Thank You!
   By the way, what is the fastest way to indent my code from line m to n in VSCodeVim?

**Comment by J-Fields** [comment]
This works with neovim integration. To be honest, I'd be surprised if anyone jumps on fixing this w/o neovim any time soon.

**Comment by LittleFatHero** [comment]
> This works with neovim integration. To be honest, I'd be surprised if anyone jumps on fixing this w/o neovim any time soon.

How to enable neovim in vscode?

**Comment by J-Fields** [comment]
https://github.com/VSCodeVim/Vim#neovim-integration
