### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by princeofxane** [VSCodeVim/Vim#3741]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.7.1`
- OS Version: `Linux x64 4.4.0-145-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/prince/vscodevim.vim-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/3362
