### ISSUE TITLE
make ctrl+q into visual block on Windows 

### ISSUE THREAD

**Issue by lilixiong2018** [VSCodeVim/Vim#3743]
I find this setting on package.json:
        "key": "ctrl+q",
        "command": "extension.vim_winCtrlQ",
        "when": "editorTextFocus && vim.active && vim.use<C-q> && !inDebugRepl"

but I don't find any code about vim_winCtrlQ, and press key "Ctrl-q" doesn't seem to work on Windows.

**Comment by lilixiong2018** [comment]
I modify the modeHandler.ts, add these lines:
```
    if (key === '<C-q>' && process.platform === 'win32') {
      key = '<C-v>';
    }
```

after:
```
    // <C-d> triggers "add selection to next find match" by default,
    // unless users explicity make <C-d>: true
    if (key === '<C-d>' && !(configuration.handleKeys['<C-d>'] === true)) {
      key = '<D-d>';
    }
```

It works!

**Comment by J-Fields** [comment]
`:help ctrl-q` on Ubuntu tells me

> Same as CTRL-V.  But with some terminals it is used for control flow, it doesn't work then.

So should we forego the `win32` check and just map `<C-q>` to visual block?
