### ISSUE TITLE
How to make `h` back to previous line ?

### ISSUE THREAD

**Issue by eromoe** [VSCodeVim/Vim#3744]
Press `h` would move to previous line when it on the head of current line .
But I found it didn't behavior this in vscodevim. 
How could I solve this ?

**Comment by wright08** [comment]
Pressing 'h' does not bump up a line when on the first character in Vim. Perhaps a plugin you installed facilitated this behavior.

**Comment by eromoe** [comment]
Can I make vscodevim support this ?

**Comment by anotherKeith** [comment]
This is not a normal VIM behavior. 'h' moves the cursor one character to the left, but doesn't wrap to the previous line, just as 'l' move one character to the right until EOL is reached.

**Comment by J-Fields** [comment]
This is possible with the [whichwrap](http://vimdoc.sourceforge.net/htmldoc/options.html#'whichwrap') option in vim, which is also available in VSCodeVim. Look for the `vim.whichwrap` setting.
