### ISSUE TITLE
Undo command undos `insert` + `replace`

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#375]
Repro steps:

1. Create a new file
2. Insert three lines with the same content `abc`, then run `ESC`
3. Replace all `a` with `d`
4. Run `u` to undo

Expected: three lines with the same content `abc`
Actual: Empty

**Comment by johnfn** [comment]
How exactly do you do #3? What keystrokes do you press?

If I do `iabc\nabc\nabc<esc>ggrbjrbjrb`, undo works as I expect.

**Comment by Paxxi** [comment]
repro
1. create new file
2. write "yada yada yada"
3. use command sequence `0 cw lala<esc>u`

expected result: `yada yada yada`
actual result: ` yada yada`
hitting `u` again gives the expected `yada yada yada`

**Comment by johnfn** [comment]
@Paxxi I fixed that issue just now.

Not sure if that's the issue you were talking about, @rebornix. Feel free to open another issue if not.
