### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jeffschwartz** [VSCodeVim/Vim#3751]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.7.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.1`

[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3166506/vscodevim.vim-unresponsive.cpuprofile.txt)

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/3362
