### ISSUE TITLE
"A setting has changed that requires a restart to take effect" prompt randomly appearing when entering or exiting a mode

### ISSUE THREAD

**Issue by k1sul1** [VSCodeVim/Vim#3752]
**Describe the bug**
This happens dozens of times every day when I'm editing. Having multiple splits seems to make it happen more often but that might just be random. Sometimes when I exit a mode or enter one, I get that annoying prompt.

I have no idea what setting is getting changed and why. This problem has been present on two machines already, and I redid my config after switching machines.

Probably related to #3502.

**To Reproduce**

1. Spam <kbd>i</kbd> & <kbd>Esc</kbd> repeatedly

**Expected behavior**
No settings should change?

**Screenshots**
![setting has changed prompt in insert mode](https://user-images.githubusercontent.com/2719615/57533234-f3b25880-7345-11e9-9a76-1757172a79e1.png)

**Environment**

- Extension Version: `1.8.0`
- OS Version: `Linux x64 5.0.9-arch1-1-ARCH`
- VSCode version: `1.33.1`

**Context**

My settings: https://gist.github.com/k1sul1/2bf7ffb76b76b069a436826c4fe03f2f
Keybindings: https://gist.github.com/k1sul1/70ce9d90635caf01208834323fb5ad34
Enabled plugins: Docker, EditorConfig for VS Code, ESLint, Git Blame, language-stylus, Vim, YAML

**Comment by k1sul1** [comment]
I've even tried taking a backup of settings.json and diffing it with "new" settings.json after getting this prompt, and the files are always identical.

**Comment by RononDex** [comment]
I get the same error from time to time, and found a way to reproduce it:

With the mouse, select some text (holding down left mouse button), then select some random other text, ... Repeat a few times in rapid succession --> said error message appears and you have to restart vscode

**Comment by k1sul1** [comment]
But I haven't ever had to restart vscode. Matter of fact, my muscle memory has adapted so that I now always double tap escape to tell that prompt to fuck off.

**Comment by RononDex** [comment]
Made a video of the error occurring on my pc.
I noticed that it mostly occurs when cpu usage is already very high, so that mode change events take longer (my educated guess being, that error occurs if vim is still busy changing mode and already a new mode change is requested).
![20190516_103916](https://user-images.githubusercontent.com/2249071/57839596-4e750580-77c7-11e9-8b64-9e38fc0e5763.gif)

**Comment by k1sul1** [comment]
That might explain why it started occurring more and more as time went on, I got faster at spamming esc which triggers a mode reset (or whatever you want to call it). 

I've noticed that VSCodeVim is very slow, it's not slow enough to bother you 99% of the time, but if I hold backspace down, it will keep deleting characters long afrer I've released it. That's ok, it's not like I hold down backspace often anyway, there's visual mode for changing big chunks at once.

**Comment by RononDex** [comment]
The issue seems to have been fixed now? I can no longer reproduce it

**Comment by AprilArcus** [comment]
It still happens for me intermittently.

**Comment by basicBrogrammer** [comment]
I'm getting this issue too on mac. Is it related to the status line colors ? I'm gonna disable that for now to see if it stops.

**Comment by danstewart** [comment]
This has recently started happening to me too.

I think it's related to `vim.statusBarColorControl` - if I disable that I can't replicate.
Strangely I only ever notice the issue when working with python, maybe just a coincidence though.

**Comment by k1sul1** [comment]
The issue has been present for over two years without one word of help from a maintainer. Clearly they don't care, so I suggest you do the same as I, and stop using this. 

Closing this issue because GitHub STILL keeps bothering me with notifications despite having unsubscribed two years ago, after I stopped using this addon because it does not work.

**Comment by dgpt** [comment]
if anyone is experiencing this problem, please support this issue:
https://github.com/microsoft/vscode/issues/215608

I was able to solve this for my particular problem by running `wsl --shutdown` from powershell (I isolated my problem to the WSL extension, not the vim extension, but this is the first result in Google when you search this error).

This probably won't fix all cases, so adding more information to this error message is a good step in the right direction.
