### ISSUE TITLE
Navigation in the explorer pane vim way (j , k) doesn't work after window reload

### ISSUE THREAD

**Issue by DNonov** [VSCodeVim/Vim#3760]
**Describe the bug**

If you reload the window with closed explorer pane, vim way(j,k) navigation will stop working. However, you will be able to navigate with upArrow and downArrow.

**To Reproduce**

1.  Close explorer pane.
2.  Reload the window.
3.  Try to navigate down with "j" key and up with "k" key.
4.  Cannot navigate with "j" and "k" key.

**Expected behavior**

Be able to navigate in the explorer pane after it has been closed and the window has been reloaded.

**Environment**

- Extension (VsCodeVim) version: 1.8.0
- VSCode version: 1.31.1
- OS: Ubuntu 16.04

**Additional context**

 The quick fix I've found so far is to reload the window again with open explorer pane.

**Comment by unihon** [comment]
I also encountered the same problem.

Sometimes can use `hjkl` move in  explorer pane, but sometimes can't.

As shown below, the input will become the keyword for search.

![image](https://user-images.githubusercontent.com/42078581/62001443-491b2c00-b123-11e9-9933-ef3ee63240d2.png)

**Comment by DNonov** [comment]
@unihon I had the same issue and I fix it with:
``` "workbench.list.keyboarNavigation": "simple" ```
however, the issue from my first post is still present and can be reproduced, as is explained above.

**Comment by neta540** [comment]
The same issue is also affecting the peek references page. It is impossible to navigate references search results with j,k when vscode is opened with explorer bar closed. setting `"workbench.list.keyboardNavigation": "simple"` as suggested does not fix the peek references page. The behavior of it is changed, but it is still malefunctioned.

**Comment by DNonov** [comment]
@neta540  the settings mentioned above sadly doesn't work in your case, because it's related to the fuzzy search feature at the explorer pane, you still can open your explorer pane and reload the window though.

On fresh ```vs code``` instance, the first thing to do is to open the explorer pane and reload. So you can carry on without this bug.

**Comment by DNonov** [comment]
The problem was that, the extension export some keybindings to mimic vim behavior in the vs code UI:

``` JSON
      {
        "key": "j",
        "command": "list.focusDown",
        "when": "listFocus && !inputFocus"
      },
      {
        "key": "k",
        "command": "list.focusUp",
        "when": "listFocus && !inputFocus"
      },
```
but default setting in vs code related to list navigation is:

``` "workbench.list.automaticKeyboardNavigation": true ```

which makes the explorer pane useless, because while trying to navigate with ```j``` and ```k```
you're activating the search feature. So I used:

``` "workbench.list.keyboardNavigation": "simple" ```

to change the behavior of the feature. This partially solved the problem but introduced this bug-like behavior that I originally opened this issue for.

Finally, I switched off the list navigation:

``` "workbench.list.automaticKeyboardNavigation": false ```

and works just fine now.
