### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by devanshuDesai** [VSCodeVim/Vim#3761]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.1.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.30.1`

[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3171202/vscodevim.vim-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/3362
