### ISSUE TITLE
"Search forward" functionality is not case sensitive

### ISSUE THREAD

**Issue by ruimaciel** [VSCodeVim/Vim#3764]
**Describe the bug**
The "search forward" search functionality, which is available by moving the cursor on top of a word and pressing '*', is not case sensitive.

**To Reproduce**

1.  Switch VSCodeVim to normal mode (press 'Esc' key)
2.  Move cursor to the top of a word
3.  Press the '*' character to search for the word under the cursor
4.  Repeat the search by pressing 'n' 

Outcome: repeating the text search will loop over occurrences that don't match a case sensitive search.

**Expected behavior**
Repeating the text search is expected to loop only over case sensitive matches.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.8.0
- VSCode version: 1.33.1
- OS: Linux (Ubuntu)

**Comment by J-Fields** [comment]
It is case sensitive, but in the case that the word being searched is all lowercase, it incorrectly uses smartcase.

**Comment by J-Fields** [comment]
Related: #2673

**Comment by J-Fields** [comment]
Closing in favor of #1800
