### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cyberladysj** [VSCodeVim/Vim#3766]
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.8.0`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/sandy/vscodevim.vim-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/3362
