### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by roon83** [VSCodeVim/Vim#3774]
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3181111/vscodevim.vim-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vim`
- Extension Version: `1.8.0`
- OS Version: `Linux x64 5.0.5-arch1-1-ARCH`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/archer/vscodevim.vim-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jpoon** [comment]
https://github.com/VSCodeVim/Vim/issues/3362
