### ISSUE TITLE
Cursor is one column off after leaving multi-cursor mode

### ISSUE THREAD

**Issue by trkoch** [VSCodeVim/Vim#3775]
**Describe the bug**
When in multi-cursor mode, pressing escape twice to return to normal mode leaves cursor one column to the left.

**To Reproduce**

1. Given the text 
```
after_action
after_action
```
2. With cursor at `n`
```
after_actio>n<
after_action
``` 
3. Enable multi-cursor mode by pressing `cmd+d`
4. Leave multi-cursor mode py pressing `esc`, `esc`
5. Cursor is at
```
after_acti>o<n
after_action
``` 

**Expected behavior**
Ideally cursor should be were it was before entering multi-cursor mode.

With regards to the example given above, I expect the cursor to be at.
```
after_actio>n<
after_action
``` 

**Screenshots**
Cursor before leaving multi-cursor mode

![image](https://user-images.githubusercontent.com/73974/57849692-3c519200-77dc-11e9-855a-0c89c2303974.png)

Cursor after leaving multi-cursor mode

![image](https://user-images.githubusercontent.com/73974/57849756-6f942100-77dc-11e9-8976-116f949215cd.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.8.0
- VSCode version: 1.33.1
- OS: macOS

**Comment by trkoch** [comment]
A tracked down this line

https://github.com/VSCodeVim/Vim/blob/59261b7d606f2d2b57ae2d0a68796e50979ea141/src/actions/commands/actions.ts#L546

```diff
```

**Comment by trkoch** [comment]
> However, I'm pretty sure it is there for a reason?

When exiting insert mode, both VSCode and Vim shift the cursor one column to the left (e.g. `i, <esc>`) so I'm guessing that's why it's done here as well. However, I believe this to be an error and inconsistent with visual mode. When exiting visual mode, the cursor stays at the position. Since multi-cursor mode seems to be a variation of the visual mode (as indicated in the status bar), I suggest to match its reset behavior.

**Comment by stevenguh** [comment]
This fixed the bug for me, but I am not familiar with this part of code enough to if there is no regression.
```diff
diff --git a/src/actions/commands/actions.ts b/src/actions/commands/actions.ts
index e2480b2c..5a0dbc99 100644
--- a/src/actions/commands/actions.ts
+++ b/src/actions/commands/actions.ts
@@ -573,12 +573,12 @@ class CommandEsc extends BaseCommand {
     if (
       vimState.currentMode !== ModeName.Visual &&
       vimState.currentMode !== ModeName.VisualLine &&
-      vimState.currentMode !== ModeName.EasyMotionMode
+      vimState.currentMode !== ModeName.EasyMotionMode &&
+      !vimState.isMultiCursor
     ) {
       // Normally, you don't have to iterate over all cursors,
       // as that is handled for you by the state machine. ESC is
       // a special case since runsOnceForEveryCursor is false.
-
       vimState.cursors = vimState.cursors.map(x => x.withNewStop(x.stop.getLeft()));
     }
```

**Comment by trkoch** [comment]
Here is my workaround. I'm running with this patch applied for a while now and have not witnessed any issues.

```diff
diff --git a/src/actions/commands/actions.ts b/src/actions/commands/actions.ts
index 334fc82e..dea41157 100644
--- a/src/actions/commands/actions.ts
+++ b/src/actions/commands/actions.ts
@@ -577,7 +577,7 @@ class CommandEsc extends BaseCommand {
       // as that is handled for you by the state machine. ESC is
       // a special case since runsOnceForEveryCursor is false.

-      vimState.cursors = vimState.cursors.map(x => x.withNewStop(x.stop.getLeft()));
+      vimState.cursors = vimState.cursors.map(x => x.withNewStop(x.stop));
     }

     if (vimState.currentMode === ModeName.SearchInProgressMode) {
```

@stevenguh Your solutions seems less drastic than mine. Have you checked if unit tests still pass?

**Comment by karlhorky** [comment]
Are either of these solutions ready for a pull request?

cc @J-Fields @xconverge

**Comment by trkoch** [comment]
@stevenguh Does the PR work for you?
