### ISSUE TITLE
TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#378]
Run into this issue when running `npm test` in command line, the line that raised the error is https://github.com/VSCodeVim/Vim/blob/master/src/textEditor.ts#L66 . Currently only HistoryTracker will invoke it. Maybe we should delay the initialization after there is a document in the workspace.

**Comment by rebornix** [comment]
FYI @sectioneight @jpoon @johnfn, current false postivie build pass is due to this issue IMHO.

**Comment by johnfn** [comment]
Fixed. More problems with travis though unfortunately.
