### ISSUE TITLE
Keep package.json after update

### ISSUE THREAD

**Issue by vtsimbos** [VSCodeVim/Vim#3780]
Each time the extension is updated, i need to add to package.json the <shift+space> keybinding that i use. It would be nice if you keep the file untouched after the update. Thank you.

**Comment by trkoch** [comment]
Why do you need to update package.json. I might be missing something. You‘re supposed to add keybindings via your user settings and not by modifying the extension code.

**Comment by vtsimbos** [comment]
By default vim extension, doesn't recognize <shift+space> keystroke. I need to add 

`{"key": "shift+space","command": "extension.vim_shift+space",
"when": "editorTextFocus && vim.active && vim.use<shift+space> && !inDebugRepl"},`

 to .vscode\extensions\vscodevim.vim-1.8.0\package.json, to do so. 

When the extension gets updated, this get deleted, and when i press <shift+space> in vscode it says "command 'extension.vim_shift+space' not found". I need to add the  code above again.

I use Windows 10, VsCode v. 1.34.0, vim 1.8.0

**Comment by jpoon** [comment]
I would suggest you submit a PR to the project to add the keybinding.
