### ISSUE TITLE
d Command Removes Mode Text

### ISSUE THREAD

**Issue by WheatiesTM** [VSCodeVim/Vim#3781]
**Description**
Inputting the command 'd' in Normal mode removes mode text from the bottom status bar until the mode is changed.

**To Reproduce**
1.  Open any file, even an empty one.
2.  In normal mode, type 'd' followed by any character.
3.  Reenable mode text by entering any other mode using its appropriate command.

**Expected behavior**
A line of text is deleted and the bottom status bar continues to display --NORMAL-- along with any potential command text inputted.

**Screenshots**
![image](https://user-images.githubusercontent.com/15278208/57964111-a9a91400-78fd-11e9-91f8-222a943ba242.png)
![image](https://user-images.githubusercontent.com/15278208/57964119-e117c080-78fd-11e9-8fc5-98fd3f9d7b47.png)
![image](https://user-images.githubusercontent.com/15278208/57964123-effe7300-78fd-11e9-85b3-92211fd13174.png)

**Environment**
- Extension Name: `vim`
- Extension Version: `1.8.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

**Comment by J-Fields** [comment]
Related: #3838

**Comment by J-Fields** [comment]
Closing in favor of #3838
