### ISSUE TITLE
"ii" Insert Mode Mapping Unexpected Behavior

### ISSUE THREAD

**Issue by Eja26** [VSCodeVim/Vim#3786]
I like to have `ii` mapped to `Esc` in insert mode (my Colemak equivalent of `jj`), which works fine in vim, however it causes some unusual behaviour in VSCodeVim.

In VSCodeVim, if I press `i` to change to insert mode, it enters insert mode, but if I press `i` again (before the timeout), it returns to normal mode, and undoes the last edit I made.

Normally in vim, pressing `i` to enter insert mode, followed by `i` again allows me to continue in insert mode.

My best guess is that the `i` to enter insert mode is being counted as part of the `ii` insert mode mapping.

**My Config**

`"vim.insertModeKeyBindings": [{
            "before": ["i", "i"],
            "after": ["<Esc>"]
}]`

**Environment**

- Extension (VsCodeVim) version: 1.8.0
- VSCode version: 1.33.1
- OS: Any

**Comment by mauricecruz** [comment]
Think this issue is being tracked in #1821

**Comment by J-Fields** [comment]
`inoremap ii <ESC>` works for me. @Eja26 is this still an issue?

**Comment by Eja26** [comment]
I have just retested it, and it works for me too now - no longer an issue.
