### ISSUE TITLE
Save File Using leader leader

### ISSUE THREAD

**Issue by jrock2004** [VSCodeVim/Vim#3790]
**Describe the bug**
I want to keymap in normal mode that when I hit leader leader, that is saves the file

**To Reproduce**
```
"vim.leader": ",",
    "vim.insertModeKeyBindings": [
      {
        "before": ["<leader>", "<leader>"],
        "commands": [
          ":w<cr>"
        ]
      }
    ],
```

**Expected behavior**
I expect the file to be saved

![image](https://user-images.githubusercontent.com/655716/58202572-e9794e00-7ca5-11e9-94ba-1efa4ac614fd.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.8.1
- VSCode version: 1.34.0
- OS: Mac

**Comment by jrock2004** [comment]
Ah, I figured it out, Sorry

**Comment by CJPoll** [comment]
When you figure something out, it helps to share it for those of us who stumble onto your issue years later looking to solve the same or similar problems.
