### ISSUE TITLE
Make saving errors more obvious

### ISSUE THREAD

**Issue by lupino3** [VSCodeVim/Vim#3793]
**Is your feature request related to a problem? Please describe.**
When trying to save with `:w` a file which is read-only, an error is silently displayed in the status bar, which is hard to read and doesn't catch the attention of the 

When doing the same thing from the VSCode UI, a pop-up comes in the bottom-right, which makes the error way easier to detect and fix.

**Describe the solution you'd like**
I'd like to have the very same pop-up to appear when a saving error is detected by the Vim emulation layer.

**Describe alternatives you've considered**
1. Keeping things as they are -- not ideal IMHO
1. Different style for the status bar message -- I think it's better to use VSCode's native notification mechanism rather than inventing a new way of doing things.

**Additional context**
Note: I'd be happy to contribute an implementation of the feature, but I don't know a lot about the codebase. If someone could give me a couple of pointers, assuming the feature is not too hard to implement, I'll be happy to send a PR.

Thanks!

**Comment by jpoon** [comment]
Some history of this in the past:

* the current behaviour is more "vim-like"
* with the status window error, there was an issue that it can't be escaped with "esc" and requires a mouse click

**Comment by lupino3** [comment]
Yes, I agree that it's more vim-like, but Vim highlights errors (see attached screenshot), which brings us closer to option 2.
![error-vim](https://user-images.githubusercontent.com/200139/58346772-330b9980-7e5c-11e9-95cb-ea09e57485e4.PNG)

I would definitely prefer option 2 being implemented than no improvement over the current state, but I would also prefer my original suggestion, because I think it fits more with the fact that we are within an IDE and it makes some sense to interact with the user using native IDE primitives if they are not *too* intrusive.

Maybe we can find a way to dismiss the notification without use of the mouse?

**Comment by J-Fields** [comment]
You can clear all VSCode notifications with `notifications.clearAll`.

Probably, we should highlight error messages we display in the command line in red.

**Comment by J-Fields** [comment]
I'm about to close this by making errors show up in red. If this isn't satisfactory, feel free to open another issue and link to this one.

**Comment by lupino3** [comment]
Looks great, thanks!
