### ISSUE TITLE
Implement `:ret[ab]` command

### ISSUE THREAD

**Issue by chen615** [VSCodeVim/Vim#3803]
在 vim 模式下 没有实现 retab 命令

**Comment by J-Fields** [comment]
Google translate: "The retab command is not implemented in vim mode"

http://vimdoc.sourceforge.net/htmldoc/change.html#:retab

**Comment by ivanmaeder** [comment]
I think this can be closed @J-Fields

The [command](https://github.com/VSCodeVim/Vim/pull/7477) was released in [v1.23.0](https://github.com/VSCodeVim/Vim/blob/master/CHANGELOG.md#v1230-2022-06-27).
