### ISSUE TITLE
-- VIM DISABLE -- is is being overidden

### ISSUE THREAD

**Issue by mick-io** [VSCodeVim/Vim#3806]
**Describe the bug**
While `"vim.statusBarColorControl": true,` and vim mode is disabled via the `Vim: Toggle Vim Mode` command, highlighting text activates Visual Mode

**To Reproduce**

1. Set `"vim.statusBarColorControl": true,` in settings.json
2.  Toggle Vim Mode via `command` + `shift` + `p`
3.  highlight text within a source code file

**Expected behavior**
Vim mode should remain disabled

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.8.1
- VSCode version: 1.34.0
- OS: MacOS

**Comment by mick-io** [comment]
I think this was fixed. Can somebody else confirm that they're unable to reproduce?

**Comment by J-Fields** [comment]
I can't. Thanks Mick, closing the issue
