### ISSUE TITLE
Position cursor in 1 tab, then focus other tab and make motion

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#381]
The motion will jump because cursorPosition will be the position in the previous tab.

**Comment by Paxxi** [comment]
While thinking about a fix for this there's more that need per window state such as the undo history.

Switching tabs can also make the cursor non-responsive requiring a mouse click(haven't tried e.g gg when this happens)

**Comment by johnfn** [comment]
Yeah agreed. Initially I was special casing the undo history as per-tab only, but when I think about it more, probably everything should be that way.

**Comment by johnfn** [comment]
@Paxxi Done the proper way 😄
