### ISSUE TITLE
Visual-mode rebinding of Shift+L works incorrectly until a few seconds have passed

### ISSUE THREAD

**Issue by awr1** [VSCodeVim/Vim#3812]
Using the binding:
```js
"vim.visualModeKeyBindings": [{ "before" : ["L"], "after" : ["5", "<Right>"] },],
```
Perform `vL` quickly on an arbitrary document, notice that the selection goes to the very bottom, which is default behavior of `L`, which shouldn't be happening as it is remapped.

The correct behavior occurs only after you wait a few seconds after pressing `v`, and then press `L`.

**Comment by berknam** [comment]
@J-Fields This should have been fixed with PR #5000.
