### ISSUE TITLE
:o fails in remote SSH

### ISSUE THREAD

**Issue by ashgillman** [VSCodeVim/Vim#3815]
**Describe the bug**
When I connect to a remote SSH host using Remote-SSH, using :o and then hitting tab for autocomplete results in:

```
TaskQueue: Error running task. Failed to handle key=<tab>. ENOENT: no such file or directory, scandir '\path\goes\here'.
```

**To Reproduce**

1.  Connect to remote host with Remote-SSH
2.  Open a file
3.  :o ./<TAB>
4.  See error

**Expected behavior**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.8.1
- VSCode version: 1.35.0-insider
- Host OS: Windows 10
- Remote OS: Ubuntu 18.04

**Additional context**
Note that the SSH remote is Ubuntu, could be a contributing issue.

**Comment by stevenguh** [comment]
Tab completion for :e error out the same way with remote ssh session as well

**Comment by stevenguh** [comment]
https://github.com/VSCodeVim/Vim/pull/3639
FYI, this was the pull request for the feature in the first place

**Comment by stevenguh** [comment]
I looked more into this, and I think this is because the Vim extension is running on the local machine which doesn't have the access of the remote file system and failed at https://github.com/VSCodeVim/Vim/blob/master/src/actions/commands/actions.ts#L1979

**Comment by stevenguh** [comment]
I just tested the proposed API. It works any file connecting scheme like remote ssh.
https://github.com/microsoft/vscode/issues/48034
However, I found the the current code for file completion is actually in a bad shape, since it doesn't even work with windows as well.
