### ISSUE TITLE
visual mode extension using arrow keys

### ISSUE THREAD

**Issue by tmcl** [VSCodeVim/Vim#382]
Hi, I know this is a new project so thanks very much.

when I do this:
v [arrow]
or V [arrow]

I expect this:
enters visual mode (or visual linewise mode) and extends the selection in the direction of the arrow key

But in fact this happens:
enters visual mode (or visual linewise mode), but then cancels it, moving the cursor in the direction of the arrow key.

I can work around this by doing this:
(vV)(hjkl)

**Comment by rebornix** [comment]
We are monitoring `type` event of the keyboard while arrow keys are not emitted by VS Code. We need to register this key in the contribution but the only catch, can we stop its default behaviour, if not, we need some hacking to avoid duplicate movement.

**Comment by tmcl** [comment]
Okay, thanks for the explanation. Also apologies for the error in how my message rendered which might've made it more confusing for you to understand.

**Comment by rebornix** [comment]
I had a fix for this issue and you will be able to use arrows as expected with our next release ( this might happen in a few days )

**Comment by johnfn** [comment]
Of course, we'd be remiss as Vim users to not suggest you use hjkl rather than the arrow keys! But hey, we can support arrow keys too. 😉
