### ISSUE TITLE
:split Can't Open Files With Names That Include Spaces

### ISSUE THREAD

**Issue by raisin-loaf** [VSCodeVim/Vim#3824]
I feel like I'm missing something blindingly obvious here but I can't quite work it out.

**Describe the bug**
`:sp` command can't open a file if its name includes a space.

**To Reproduce**
Change directory to a folder that includes files with spaces in their names. Type `:sp` plus the first few characters of the file name, hit tab to complete (which happens correctly, including the spaces). Press enter and a notification pops claiming that `File: <path_to_working_directory>\<first_word_of_filename> does not exist`.

For example - `C:\Temp\My Test File.txt`
Resulting notification - `File: C:\Temp\My does not exist.`

I've tried enclosing the file name in single quotes, double quotes and just about anything else I think might work without success.

Files without spaces open just fine.

**Expected behavior**
A horizontal split will open showing the file specified.

**Environment**
- Extension (VsCodeVim) version: 1.8.1
- VSCode version: 1.35.0
- OS: Windows 10

All advice very gratefully received!

**Comment by stevenguh** [comment]
I am working in a fix that fixes https://github.com/VSCodeVim/Vim/issues/3815 could fix this as well
