### ISSUE TITLE
Frozen in 'Activating Extensions'

### ISSUE THREAD

**Issue by denniskempin** [VSCodeVim/Vim#3826]
Issue Type: <b>Bug</b>

- Open VSCode with Vim extension installed
- Open any file
- Try typing

Expected result: Can use insert mode and type, can use motion keys to move cursor in visual mode

Actual result: Arrow keys move cursor, every other key seems to be ignored.

Unfortunately I cannot find any logs that would show errors (none of the Output panes show any anything related). While this is happening, the status bar shows "Activating Extensions". 

Toggling Vim mode has no effect. Re-installing has no effect. I tried versions 1.8.1, 1.8.0 as well as version 1.7.1, all seem to have the same problem.

Disabling the Vim extension gets things back to normal.

Does someone have advice on how to get more debug info? I tried increasing the log level, but nothing significant shows up in the Output pane.

Extension version: 1.8.1
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:13:26.790Z)
OS version: Linux x64 4.19.28-2rodete1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 1197)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|25, 24, 23|
|Memory (System)|125.89GB (23.90GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by denniskempin** [comment]
My workstation must have been in a bad state somehow. A reboot fixed the issue. Sorry for the noise.

**Comment by harrygcoppock** [comment]
I had the same issue. When using Remote SSH. The reason was that system memory was full. Freeing up some space fixed the issue.

**Comment by zeenix** [comment]
> Until today, restarting vscode helped but today it stopped working as well.

Apparently you've to close **all** vscode windows. This sucks still though.
