### ISSUE TITLE
ModeHandler messages not coming through debug console

### ISSUE THREAD

**Issue by nbahmanyar** [VSCodeVim/Vim#3828]
**Summary**
After setting the logging level to "debug" in the `settings.json` file, restarting VS Code, and opening the developer console, I don't see  `ModeHandler` console messages which state that VsVim is handling various keys. Even after pressing keys which are clearly being handled by VsVim, I still don't see any `ModeHandler` messages.

**To Reproduce**

1.  Change logging level to "debug" in `settings.json`
2.  Restart VS Code
3.  Help > Toggle Developer Tools
4.  Click on the console tab within Developer Tools

**Environment:**

- Extension Version: `1.8.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.35.0`

**Comment by jpoon** [comment]
Precisely what setting are you adjusting in (1). Can you share screenshot? 

Here's mine:

![image](https://user-images.githubusercontent.com/85374/64471170-a6cb6c80-d102-11e9-9038-2e1bd5244404.png)

**Comment by jpoon** [comment]
Closing as was not able to repro and no further information provided by issue creator.
