### ISSUE TITLE
:warning:Extension issue

### ISSUE THREAD

**Issue by AlbertoMata** [VSCodeVim/Vim#3830]
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3281700/vscodevim.vim-unresponsive.cpuprofile.txt)
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.8.1`
- OS Version: `Linux x64 4.9.0-9-amd64`
- VSCode version: `1.35.0`

:warning:

**Comment by jpoon** [comment]
Dupe of https://github.com/VSCodeVim/Vim/issues/3830
