### ISSUE TITLE
cw without yank

### ISSUE THREAD

**Issue by mamolli** [VSCodeVim/Vim#3836]
**Is your feature request related to a problem? Please describe.**
When using vscodevim with clipboard mode, cw perhaps should not yank.
Since you can already have something in clipboard for regular "pastes".

**Comment by sinharaksh1t** [comment]
Just curious - why did you close this issue? Was this already resolved?

**Comment by mamolli** [comment]
I have fixed this by remapping and i think this behaviour is all in all consistent with vim.
That's all :)

**Comment by sinharaksh1t** [comment]
Yeah, that does make sense. Thanks for the clarification.
