### ISSUE TITLE
Macro 'Recording @a' in status bar disappears after delete command

### ISSUE THREAD

**Issue by th0rgall** [VSCodeVim/Vim#3838]
**To Reproduce**
In '--NORMAL--' mode in a file with some content:
1. Press `qa` to start recording a macro. The status bar now shows '--NORMAL-- Recording @a' as expected.
2. Press `dd` to delete a line. The status bar will now disappear and only reappear until an insertion command is issued.

**Expected behavior**
'Recording \@a' should stay in the status bar until the next `q` is pressed, like in VIM.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.8.1
- VSCode version: 1.35.1
- OS: macOS 10.14.5

**Comment by J-Fields** [comment]
The `Recording @X` text (and the mode text) comes from `ModeHandler._renderStatusBar`. Seems to me these should be moved into the more general `StatusBar.Set`, which would fix this issue.

**Comment by th0rgall** [comment]
Thanks!

**Comment by J-Fields** [comment]
Sure thing, @th0rgall! This was a big annoyance for me as well. Some other status bar improvements will be coming in the next version too! The fix required a pretty major refactor though, so let me know if you see any strange behavior.
