### ISSUE TITLE
Ctrl+w h will open up a new tab if there isn't one

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#384]
`Ctrl+w h` doesn't actually work like that in Vim.

**Comment by rebornix** [comment]
I suppose you are referring to Window, right? I'll take it :)

**Comment by johnfn** [comment]
I'm not quite sure what the terminology is. A new pane perhaps? 😛

**Comment by rebornix** [comment]
Not sure whether I used Vim wrongly but on my Mac and Linux VM, `<ctrl-w>+h` or `<ctrl-w>+l` won't create new tab/window if there isn't one. Is there any configuration setup in your vimrc?

BTW, we still need to implement `vsp {file}` and if the `{file}` is empty, create a new window and edit a new empty file.

**Comment by johnfn** [comment]
Hmm, I'm using VSC Insiders with the latest build and `    "workbench.editor.showTabs": true,` in my user settings file.

**Comment by rebornix** [comment]
This one can be closed now
