### ISSUE TITLE
<C-Up> and <C-Down> etc. key bindings don't work

### ISSUE THREAD

**Issue by hasufell** [VSCodeVim/Vim#3848]
config:
```
  "vim.normalModeKeyBindings": [
    {
      "before": ["<C-up>"],
      "after": ["6", "k"]
    },
    {
      "before": ["<C-down>"],
      "after": ["6", "j"]
    }
  ]
```

It doesn't matter whether `vim.useCtrlKeys` is used or `vim.handleKeys`. The above key bindings never work.

In contrast, stuff like `<C-j>` or `<C-k>` works.

I don't see any explanation in the readme or the issue tracker.

**Comment by ricciolino** [comment]
Yes, I need the same KeyBindings!!!
