### ISSUE TITLE
How to disable arrow key preventing moving up or down lines

### ISSUE THREAD

**Issue by musm** [VSCodeVim/Vim#3849]
In insert mode  pressing left at the start of the line does not move the cursor up a line, similar to the end of the line and pressing the right arrow (like when the extension is disabled). Is there any why to restore the original behavior?

**Comment by J-Fields** [comment]
`vim.whichwrap` controls this. `<` and `>` are left/right arrows in normal mode; `[` and `]` are left/right arrows in insert mode.
