### ISSUE TITLE
GoToDefinition make invalid history when use C# extension

### ISSUE THREAD

**Issue by yaegaki** [VSCodeVim/Vim#3865]
**Describe the bug**
GoToDefinition make invalid history when use C# extension.

**To Reproduce**

1.  Install [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp)
2.  Open C# project
3.  Move cursor to a symbol
4.  Type `gd`

**Expected behavior**
Make history correctly.

**Screenshots**
![GIF](https://user-images.githubusercontent.com/4941773/60678871-ce167b00-9ec0-11e9-8b48-3d201a4ab39f.gif)

This gif is run undo command after goToDefinition command.

**Environment (please complete the following information):**

- Extension Version: `1.8.1`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.36.0`

**Comment by xconverge** [comment]
I just wanted to comment and thank you for your report, investigation, and then fix. This was a nasty one and it is much appreciated!
