### ISSUE TITLE
using # and * to search through a word, repeated multiple times with different caps does not work as intended

### ISSUE THREAD

**Issue by wrightwriter** [VSCodeVim/Vim#3879]
**Description**

Let's say you have this document:
```
name
name
Name
name
name
```

With your cursor on the first one, you start pressing * repetitively. 

**Expected behavior**
Cursor cycles through all the words.

**Actual behaviour**
Cursor stops at word with uppercase N

**Environment (please complete the following information):**
- Extension (VsCodeVim) version : newest
- VSCode version: VSCode 1.36.0
- OS: Windows 10

**Comment by xconverge** [comment]
vim.ignorecase: false

This is a setting you can use. Please reopen if this doesn't solve your issue
