### ISSUE TITLE
1.8.2 update appears broken

### ISSUE THREAD

**Issue by fredemmott** [VSCodeVim/Vim#3894]
**Describe the bug**

Every vim action I've tried (e.g.`hjkl`, `:`, `/`, command-w v for window split) have standard visual studio code (e.g. inserting text) in 1.8.2. If I force downgrade to 1.8.1, everything works fine.

**To Reproduce**

1.  open visual studio code
2. open any file
3. install vscodevim
4. restart to complete installation
5. hit escape
6. type hjkl. Text `hjkl` inserted to document
7. hit escape again
8. type `:`. Text `:` inserted to document
9. downgrade to 1.8.1
10. repeat, get expected behavior below

**Expected behavior**

- typing `hjkl` should trigger cursor movement and not insert any text
- typing `:` should result in prompting for a vim command to input

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.8.2
- VSCode version: 1.36.1
- OS: MacOS Mojave 10.14.5

**Additional context**

Tried both with and without neovim support enabled, no difference.

**Comment by Liquidmantis** [comment]
For what it’s worth, I’m not seeing any issues with 1.8.2 and Code **Insiders**, on either MacOS or Windows.

**Comment by qcts33** [comment]
I'm having the same issue. There is also not normal or insert mode indicate. I have also tried the `toggle vim mode`, it tells me that "command 'toggleVim' not found"

**Comment by qcts33** [comment]
Update:
I tried to update to 1.8.2 again and the problem resolved it self. No idea what happened.

**Comment by carusog** [comment]
Same here. 

- I uninstalled
- Quitted VSC
- Re-opened VSC
- Re-installed it

And the problem was fixed. 

🤷‍♂

**Comment by sahuk** [comment]
I had the same issue on 1.9.0. @carusog 's workaround resolved it. I am running VS Code with the WSL-Remote plugin, could this make a difference?

> 
> * I uninstalled
> * Quitted VSC
> * Re-opened VSC
> * Re-installed it
> 
> And the problem was fixed.
> 
> # 🤷‍♂

**Comment by carusog** [comment]
> I had the same issue on 1.9.0. @carusog 's workaround resolved it. I am running VS Code with the WSL-Remote plugin, could this make a difference?

No Remote WSL here.

**Comment by fredemmott** [comment]
Uninstall then reinstall also worked for me.

**Comment by ottodokto** [comment]
VScodevim appears to not work when enabled locally, but will work if you force the extension to run on remote:
`"remote.extensionKind": {
        "vscodevim.vim": "workspace"
    },`

tested on vscodevim 1.9.0, vscode v1.36.1
