### ISSUE TITLE
bug to record macro 

### ISSUE THREAD

**Issue by Bluekezhou** [VSCodeVim/Vim#3898]
**Describe the bug**
It's difficult to record macro

**To Reproduce**
If I want to record a macro, I need follow steps:

1.  Enter i to enter insert mode
2.  Enter ESC to quit 
3.  Enter q
4.  Enter macro_name

**Expected behavior**
record macro without any precondition

**Environment (please complete the following information):**
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.8.2`
- OS Version: `Linux x64 4.15.0-55-generic`
- VSCode version: `1.36.1`

**Comment by J-Fields** [comment]
Sorry, I'm confused as to what you're requesting. To record a macro, you have to be in normal mode and type `q` and then a register key, just as in vim. What's the behavior you expect?

**Comment by Nohac** [comment]
I have the same problem. However, I noticed that it does start recording regardless, it's just that the mode you are in (normal mode, insert mode etc.) does not reappear in the status bar after any command (dd, yy etc.). So pressen `qq` to start recording after `dd` or `yy` does not show that you start a new macro.

**Comment by J-Fields** [comment]
I do think what's being described is #3838. Closing in favor of that.
