### ISSUE TITLE
make easymotion looks exactly the vim-easymotion way

### ISSUE THREAD

**Issue by gary-ruizhang** [VSCodeVim/Vim#3901]
vim-easymotion looks like replace the original letter to marker instead add one next to it. Below is a comparison between vim and vscode.

| editor | before | after |
| - | -| - |
|vim | <img width="1414" alt="Screen Shot 2019-07-17 at 11 17 46" src="https://user-images.githubusercontent.com/32344731/61390042-05553680-a888-11e9-979d-0e7f3260d0ec.png"> | <img width="1399" alt="Screen Shot 2019-07-17 at 11 18 09" src="https://user-images.githubusercontent.com/32344731/61390060-0ede9e80-a888-11e9-90f3-66bdbab25020.png"> |
| vscode | <img width="975" alt="Screen Shot 2019-07-17 at 11 22 05" src="https://user-images.githubusercontent.com/32344731/61390078-18680680-a888-11e9-9b70-cc55b8b44cd1.png"> | <img width="933" alt="Screen Shot 2019-07-17 at 11 22 24" src="https://user-images.githubusercontent.com/32344731/61390096-1f8f1480-a888-11e9-966f-dd2361f041d4.png"> |

**Comment by Liquidmantis** [comment]
Your VSCode looks particularly broken.  Seeing your shots of how good it is in Vim native encouraged me to poke around with the appearance configuration in VSC.  
I went from:
![image](https://user-images.githubusercontent.com/399056/61395449-b5c03c00-a882-11e9-90a3-b508fedb0b6d.png)

to:
![image](https://user-images.githubusercontent.com/399056/61395513-d5576480-a882-11e9-9426-a52e98c2ef7f.png)

with just a few minutes of effort and could probably tweak it some more, but that already **greatly** increased the usability for me.  Maybe now I won't have to depend on vim-sneak so much.

**Comment by J-Fields** [comment]
See also: #2938
