### ISSUE TITLE
Fail to substitute target string to backslash

### ISSUE THREAD

**Issue by iiifr** [VSCodeVim/Vim#3904]
Can't substitute target string to backslash correctly.

**Environment:**
VSCode Version: 1.36.1
VsCodeVim Version: 1.8.2
OS: Linux Mint

**What happened:**
If I had text like below:
```
aass;fff
;;ppod
{{;}}
```
and I want to replace `;` to `\` with command `:%s/;/\\/g`
After execution, the text become:
```
aass\\fff
\\\\ppod
{{\\}}
```
**What did you expect to happen:**
The text after substitution should be:
```
aass\fff
\\ppod
{{\}}
```
**How to reproduce it:**
* Type text:
```
aass;fff
;;ppod
{{;}}
```
* Execute command `:%s/;/\\/g`

**Comment by J-Fields** [comment]
This works correctly with neovim integration enabled.

**Comment by J-Fields** [comment]
Related: #1937

**Comment by iiifr** [comment]
ok. Thanks for your reply.

**Comment by J-Fields** [comment]
Duplicate of #2710
