### ISSUE TITLE
configurable key mapping for "jump to definition"?

### ISSUE THREAD

**Issue by smartding** [VSCodeVim/Vim#3909]
Currently, the "gd" command triggers "jump to definition", is it possible to assign a different key mapping for this?

**Comment by hiaux0** [comment]
@smartding 

For assigning another combination to "jump to definition" do:
```js
	"vim.normalModeKeyBindingsNonRecursive": [
		{ "before": ["<leader>", "a", "f"], "commands": [ {"command": "editor.action.revealDefinition"}]},
         ]
```

If you want to use "gd" to do sth else:
```js
	"vim.normalModeKeyBindingsNonRecursive": [
		{ "before": ["g", "d"], "after": ["v", "i", "w"] },
         ]
```

**Comment by smartding** [comment]
> @smartding
> 
> For assigning another combination to "jump to definition" do:
> 
> ```js
> 	"vim.normalModeKeyBindingsNonRecursive": [
> 		{ "before": ["<leader>", "a", "f"], "commands": [ {"command": "editor.action.revealDefinition"}]},
>          ]
> ```
> 
> If you want to use "gd" to do sth else:
> 
> ```js
> 	"vim.normalModeKeyBindingsNonRecursive": [
> 		{ "before": ["g", "d"], "after": ["v", "i", "w"] },
>          ]
> ```

thank you, didn't know there is a "revealDefinition" command

**Comment by hiaux0** [comment]
What I do to find command names is to open Vscode shortcuts 
![image](https://user-images.githubusercontent.com/30693990/62037447-15f49d80-b1f4-11e9-831e-10ec1588d22b.png)

And copy the command in question

**Comment by J-Fields** [comment]
Closing as this seems resolved.
