### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mcodyre** [VSCodeVim/Vim#3912]
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.8.2`
- OS Version: `Linux x64 5.1.16-200.fc29.x86_64`
- VSCode version: `1.36.1`
slow!!!!
:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by mcodyre** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 153,
		"activateCallTime": 1,
		"activateResolvedTime": 331,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}
```

**Comment by mcodyre** [comment]
I'm finding this extention seems to be slowing my system down a great deal...any ideas on how to improve it?

**Comment by briandridge** [comment]
I've been having the same issue. I've disabled all other extensions and when switching between normal, insert, or visual mode everything freezes for about a second.

**Comment by briandridge** [comment]
I installed the previous version and the problem went away.

**Comment by mcodyre** [comment]
Thanks I'll try that.

**Comment by briandridge** [comment]
After a few hours of work the transition between modes is very slow again...

**Comment by andycmaj** [comment]
#3957 3957

**Comment by J-Fields** [comment]
Performance has improved a lot over the last year+, so I'm assuming this is no longer an issue. If it is, please create a new issue, and I'll be happy to dig into details with you.
