### ISSUE TITLE
:wq does not close window if there are unsaved changes

### ISSUE THREAD

**Issue by zombiezen** [VSCodeVim/Vim#3922]
**Describe the bug**
When I try to use `:wq` to write and close a _modified_ file, it will write the file, but not close the window, failing with the error `E37: No write since last change (add ! to override).` in the status bar.

**To Reproduce**

1.  `code --wait foo.txt`
2.  Make a change (e.g. type in "foo")
3.  `:wq`

**Expected behavior**
The file is written and the window is closed.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `1.8.2`
- VSCode version: `1.36.1`
- OS: `Windows_NT x64 10.0.18362`

**Additional context**

Not sure if relevant, but I am using this in conjunction with the Remote Development - WSL extension.

**EDIT 2019-07-26:** Edited to clarify that this behavior only occurs for modified files.

**Comment by J-Fields** [comment]
Seems to me this only happens when the file does not exist. @zombiezen can you confirm?

**Comment by zombiezen** [comment]
On my machine, the existence or non-existence of the file does not affect the behavior. I just verified that running `touch foo.txt` before going through the reproduction steps produces the same results.

**Comment by J-Fields** [comment]
Interesting. I think I'm seeing a manifestation of the same bug because if I create a file via `code --wait test.txt`, I see the behavior you describe. But once it exists (if, for instance, I do `:w` before step 2 above), `:wq` works as expected.
My environment:
* Extension version: `1.8.2`
* VS Code version: `1.36.1`
* OS version: `Windows_NT x64 10.0.16299`

**Comment by stevenguh** [comment]
This has been a issue for a while since the remote ssh. I never thought much of it.
https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/commands/write.ts#L55
Once I added an await for the execute call, I no longer get the error after executing `:wq` with remote ssh.

**Comment by stevenguh** [comment]
Sure. But I have been get some unrelated test fails. I am wonder if this is a Windows problem.

**Comment by stevenguh** [comment]
Exactly my thought. But okay. I will get a PR going and see if it pass on CI. Thanks.
