### ISSUE TITLE
range yank does not work

### ISSUE THREAD

**Issue by hiphamster** [VSCodeVim/Vim#3931]
range yank appears not to work. When i do `:1,10y`

i get `E492: Not an editor command. 1,10y`

I'm a new vs code user, so perhaps I haven't configured vim extension properly

**Comment by areinmeyer** [comment]
Do you have neovim installed and configured properly?  See https://github.com/VSCodeVim/Vim#neovim-integration for instructions.  That's necessary for the range yank to work.

**Comment by hiphamster** [comment]
That was it! Thank you!
