### ISSUE TITLE
delete N characters under and after the cursor with Del key

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#394]
### Issue Summary

Now we only support `x` to delete characters while we can use `Del` on Windows/Linux platform to archive the target.

We only need to register this key in contribution and map it to `x` operator. I'd like to mark it as `easy` and `help_wanted`!

**Comment by rebornix** [comment]
Please note on Mac, `delete` key is actually a `backspace`

**Comment by roblourens** [comment]
Looks like this works? IIUC, `<del>` in normal mode deletes the character under the cursor, matching Vim. In Vim, `5<del>` has no effect where in VSCodeVim, `5<del>` deletes one character which is probably close enough :)

**Comment by rebornix** [comment]
Didn't notice we've already mapped `<del>` to `x` and @roblourens you are right, Vim is actually `<del>` and `x` differently. `x` can be prefixed with numbers but `<del>` can not.

The solution is also simple, create a separate command for `<del>`, inherit from `x` and set `canBePrefixedWithCount` as false.

**Comment by rebornix** [comment]
It's likely VS Code's default behavior. A proper fix is handling `<del>` in our code base, similar to what we do for `Escape` and `Backspace`, see [here](https://github.com/VSCodeVim/Vim/blob/master/package.json#L46). @roblourens let me know if you are interested in hacking it around or I can give it a quick fix :)

**Comment by roblourens** [comment]
Actually about to head out of town, so probably won't have a chance.

**Comment by rebornix** [comment]
@roblourens no worries I'll do it, thanks again for the information you provided!

**Comment by Chillee** [comment]
N<Del> in vim isn't actually a nop, it deletes the last character of the count.
