### ISSUE TITLE
Ctrl-P and Ctrl-N should be equivalent to Up / Down when entering a command or search

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#3942]
See title. I don't think this interferes too much with the VSCode's default Ctrl+P, and if it does for someone, they can disable it (via `handleKeys` or by changing the `when` clause of `extension.vim_ctrl+p`).

**Comment by rockneverdies55** [comment]
All the time I accidentally press ctrl-n and/or ctrl-p by muscle memory to move between search results and it drives me nuts when I find myself in a brand new file window instead.

So glad to see that this issue has been filed and already backed by a pull request. :-)

Can anyone tell appr. when it is expected to be released?

**Comment by rockneverdies55** [comment]
That is wonderful. Thanks a lot.

**Comment by gyuha** [comment]
😢
It is so inconvenient that this key is missing.
Is there a way to reuse it?

**Comment by yehorb** [comment]
This one should work to cycle through commands only in 'SearchInProgressMode' (enabled after pressing `/` in 'NormalMode') and in 'CommandlineInProgress' (enabled after pressing `:` in 'NormalMode'). For me, it works fine with search mode, and I can cycle through history with <C-p> and <C-n>. Really convenient, thanks for that. But it doesn't work with command mode. <C-p> and <C-n> keep their original meaning even after pressing `:`. I looked through `Default Keybindings (JSON)`, and the `"when"` clause generated for `"key": "ctrl+n"` and `"key": "ctrl+p"` looks a bit broken, especially the `vim.mode == ''CommandlineInProgress')'"` part.
```json
{ "key": "ctrl+n",                "command": "extension.vim_ctrl+n",
                                     "when": "(editorTextFocus || vim.mode == 'SearchInProgressMode' || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == ''CommandlineInProgress')'" },
{ "key": "ctrl+p",                "command": "extension.vim_ctrl+p",
                                     "when": "(suggestWidgetVisible || vim.mode == 'SearchInProgressMode' || vim.active && vim.use<C-p> && !inDebugRepl && vim.mode == ''CommandlineInProgress')'" },
```
I believe this is the cause of <C-p> and <C-n> not working for CommandlineInProgress. Though I don't use command mode often, it still should work as intended in 1.10. And it doesn't.
Can someone look into it and help me solve this issue?

**Comment by s97712** [comment]
My ctrl+n, ctrl+p suddenly not work, is it related to this?

**Comment by s97712** [comment]
It seem has some problem, ctrl+n, ctrl+p now can't work on edit mode.

**Comment by J-Fields** [comment]
@yehorb @s97712 #4011
