### ISSUE TITLE
`Ctrl-R` should allow pasting from a register when typing a command, as in insert mode

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#3950]
**Is your feature request related to a problem? Please describe.**
Not very often that I want to do this, to be honest. It's nice to have the option though.

**Describe the solution you'd like**
As in vim, `Ctrl-R` should act the same on the command line as in insert mode.

**Describe alternatives you've considered**
`Ctrl-V` currently works to paste from clipboard, but not from an arbitrary register.

**Comment by ThomasRLane** [comment]
I want to do this fairly often, to paste the filename of the file I'm editing into the :e command, and go to a similarly-named file.  Or, sometimes, when I edit a file under a path that leads far from the rest of what I'm editing, and then want to edit a different file in that same faraway directory.
