### ISSUE TITLE
Simple command aliases

### ISSUE THREAD

**Issue by sguillia** [VSCodeVim/Vim#3965]
Hi

I always type `:W` instead of `:w`

This is because I need to press Shift to type a colon and I type `w` before releasing Shift.

So in my `.vimrc`, I have added this:
```
command W w
command Wq wq
command Q q
```

On Vscode, I have this dozens of times a day:
```
E492: Not an editor command. W
```

Can we have command aliases too for Vscode Vim?

Thank you

**Comment by J-Fields** [comment]
Description of how this works: http://vimdoc.sourceforge.net/htmldoc/usr_40.html#40.2

**Comment by haifengkao** [comment]
[keyboard maestro](https://www.keyboardmaestro.com/main/) can give you a quick workaround
![螢幕快照 2019-10-04 下午6 20 46](https://user-images.githubusercontent.com/4080524/66200451-b1fac380-e6d3-11e9-942e-8b67dafa75b4.jpg)

**Comment by J-Fields** [comment]
Closing in favor of #4454
