### ISSUE TITLE
Key Remapping for Search Mode

### ISSUE THREAD

**Issue by ThomasRLane** [VSCodeVim/Vim#3966]
**Is your feature request related to a problem? Please describe.**
I am OK with the current regex that is implemented, but I'm used to typing \\< and \\> for the beginnings and endings of words (like when I'm searching code for the variable \\<i\\>, not for every 'i' character in the file).  I'd like to remap both of those key sequences to \\b, but there's no remapping during search.

**Describe the solution you'd like**
I would like at least simple remapping capability for the search line ('/' or '?').
I don't need it to also work on the command line (':'), but I would be OK with that if it were easier to implement.

**Describe alternatives you've considered**
I've considered remapping \\b on normal vim instead, but it has to be \\< at the beginning of a word and \\> at the end, so that doesn't work.  It would be better if I could do the remapping in VSCodeVim, since I could remap \\< to \\b and also remap \\> to \\b.  Otherwise, I'm going to be constantly typing the wrong thing when I switch environments (I don't really care what I need to type, but I want it to stay the same).

**Additional context**
I also used to do other things with command line remapping, but this is the main driver for me.

Suggested labels: [area/search] [area/remap][kind/feature]

**Comment by J-Fields** [comment]
> I've considered remapping `\b` on normal vim instead

How is this done in Vim?

**Comment by ThomasRLane** [comment]
In Vim, you can perform a command-mode remapping to change how keys act on the search line.
I think it's cmap or cnoremap, though it's been a while since I've used it.  In Vim, the remap also acts on the ':' command line.

**Comment by markonius** [comment]
Just wanna chime in. You can see all different Vim map modes [here](https://vim.fandom.com/wiki/Mapping_keys_in_Vim_-_Tutorial_(Part_1)#Mode-specific_maps). I'd really like to have `cnoremap`.

My daily annoyance: I've remmaped "go to next word" to ",", but I can't delete a word using "d,", I have to type "dw".

**Comment by J-Fields** [comment]
@markonius What's your mapping in vim to do that?
