### ISSUE TITLE
`:'<,'>normal .`   doesn't work

### ISSUE THREAD

**Issue by nateshmbhat** [VSCodeVim/Vim#3969]
:'<,'>normal .   doesn't work

Refer to **https://stackoverflow.com/questions/57415461/normal-doesnt-work-in-vscode-with-vim-plugin-how-do-i-fix-this** for details.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.9.0 (2019-07-29)
- VSCode version: 1.35.1
- OS: Pop os 19.04

**Comment by apgrc** [comment]
I get "Not a command editor" error using the normal command. It seems like it is not implemented. I would like to have to.

**Comment by jaimehrubiks** [comment]
Would like to have this too

**Comment by emgniddikur** [comment]
Does anyone know about this?

**Comment by mefengl** [comment]
this maybe help.
![20210202131840](https://user-images.githubusercontent.com/71683364/106555772-31fb9c80-6559-11eb-9256-81794b8ed9aa.png)
...maybe not

**Comment by mefengl** [comment]
you need to enable `Neovim` in vscodevim. Find more information in the extension's `Details`.
then, it's should be work. And to me, it seems like it did work, but always works terrible(or work but do notiong).

**Comment by nph278** [comment]
Hope this is implemented soon, the Neovim mode still doesn't always work.

**Comment by rohitkrishna094** [comment]
Any update on this? is this implemented in vscode vim as of today?

**Comment by ajaydwarkani** [comment]
Please have this fix. Thanks

**Comment by yaogengzhu** [comment]
has it been fixed ?

**Comment by darianmorat** [comment]
Keeping alive the post 👈
