### ISSUE TITLE
Multiple cursor backspace affect only one line when using snippets

### ISSUE THREAD

**Issue by Cyber0ni** [VSCodeVim/Vim#3976]
When I try to delete chars with backspace in same placeholders backspace affect only first one and also delete next chars (" =" in this example).
![Alt Text](https://i.imgur.com/jVr8XHv.gif)

I disabled all extensions and after this, all worked right and when only vim is enabled this error appear.
This is the snippet that I use:
```json
"For loop": {
	"prefix": "for",
	"body": [
		"for(${1:int} ${2:i} = ${3:0}; ${2:i} < ${4:count}; ${2:i}++) {",
		"\t${0:/*code*/}",
		"}" 
	],
}
```

- Extension (VsCodeVim) version: v1.9.0 (2019-07-29)
- VSCode Version: 1.37.0
- OS Version: Windows 10

**Comment by nerdmax** [comment]
+1
