### ISSUE TITLE
Variable highlighting not working

### ISSUE THREAD

**Issue by pgsandstrom** [VSCodeVim/Vim#3982]
**Describe the bug**
Before activating the vim extension, when navigating to a variable with the arrow keys, the variable and all of its uses are highlighted. When activating the extension this stops working. If I navigate to a variable by clicking on it, it still works. But navigating to it with either hjkl or the arrow keys no longer procudes a highlighting.

**To Reproduce**

1.  Activate the extension
2.  Navigate to a variable (any way except with mouse)
3.  Notice that it is not highlighted

**Expected behavior**
The variable and its uses should be highlighted.

**Screenshots**
Correct highlighting:
![correctHighlight](https://user-images.githubusercontent.com/1449130/63150602-82023e80-c007-11e9-85af-b563f92c0791.png)
Incorrect highlighting:
![incorrectHighlight](https://user-images.githubusercontent.com/1449130/63150611-8890b600-c007-11e9-86c3-86545500680e.png)

**Environment (please complete the following information):**

Extension version: 1.9.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.16299

**Comment by J-Fields** [comment]
Closing in favor of #3044
