### ISSUE TITLE
Add Visual Block mode

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#401]
Believe it or not, I don't think this is actually too hard - feel free to try and tackle it, if you want. I suspect the core logic in modeHandler will be less than 50 lines. The only tough part will be the places in the code where we've made the assumption that there's only one selection, but I don't think there are too many of those.

(Whoops; this already existed as #353. I'm silly.)

**Comment by justindarner** [comment]
Yes. I would love this feature to be added.

**Comment by choidamdam** [comment]
I use the <kbd>Ctrl</kbd><kbd>v</kbd> + <kbd>I</kbd>/<kbd>A</kbd>/<kbd>c</kbd> [combinations](http://stackoverflow.com/questions/9549729/in-vim-how-do-i-effectively-insert-the-same-characters-across-multiple-lines#answer-34552140) very frequently. It would be great if they work exactly same as real vim.

![vim example](http://i.stack.imgur.com/ce8e1.gif)

**Comment by johnfn** [comment]
It's happening!!!

**Comment by akagr** [comment]
You guys rock! I love visual block mode in vim and it was one of the things that still had me reaching out to vim every now and then. It's a little jittery right now but it works and solves my purpose. Much love!
