### ISSUE TITLE
<C-n> not working in 1.10.0

### ISSUE THREAD

**Issue by Cyborg572** [VSCodeVim/Vim#4011]
**Describe the bug**
In my settings I have `<C-n>` remapped to "g b", and have been using it like that for well over a year. Today it stopped working in the middle of editing a file, and I had to revert to version 1.9.0 to have it working again.

I noticed the when expression has changed in v1.10.0, to something more complicated.

**To Reproduce**

1.  Add the following to `settings.json`
2. ```
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-n>"],
            "after": ["g", "b"],
        }
    ],
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-n>"],
            "after": ["g", "b"],
        }
    ],
   ```
4.  Place your cursor in a word in normal mode
5. Press `<C-n>` a few times
6. Notice the cursor moves down a line each time

**Expected behavior**
The current word should be highlighted, followed by each repetition of the word for every keypress.

**Environment:**

- Extension (VsCodeVim) version: v1.10.0
- VSCode version: 1.37.1
- OS: macOs Mojave 10.14.6

**Comment by J-Fields** [comment]
Here's the `when` expression on the keybinding we contribute from `package.json`:
`(editorTextFocus || vim.mode == 'SearchInProgressMode' || vim.mode == 'CommandlineInProgress') && vim.active && vim.use<C-n> && !inDebugRepl`
And here's the `when` expression in `keybindings.json`:
`(editorTextFocus || vim.mode == 'SearchInProgressMode' || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == ''CommandlineInProgress')'`
Seems like it isn't parsing it correctly... are parentheses supported?

**Comment by ggsggs** [comment]
What is the solution then? Ctrl+N opens a new tab now, even deleting the VSCode keybinding for Ctrl+N does not bring back the expected behaviour.

**Comment by nerdmax** [comment]
Same issue happens on my Mac

**Comment by project-delphi** [comment]
frustrates me too! This has been my solution to the problem - another plugin :-)

https://github.com/jonsmithers/vscode-open-in-vim

**Comment by aabccd021** [comment]
any progress on this?

**Comment by J-Fields** [comment]
@aabccd021 This should be fixed - please create a new issue if you're seeing a similar problem

**Comment by yinrong** [comment]
any progress on this?

**Comment by Ali-E** [comment]
how was this fixed? i do not see a solution for ctrl + n?

**Comment by FlatMapIO** [comment]
any progress on this?
