### ISSUE TITLE
Allow for placeholders in rebindings

### ISSUE THREAD

**Issue by JohnnyUrosevic** [VSCodeVim/Vim#4012]
This would augment the rebinding capabilities in the extension to allow us to do some more complex rebinds.

Example:
```
        {
            "before": ["f", "<placeholder>"],
            "after": ["/", "<placeholder", "<enter>"]
        },
```
This would remap f <letter> to / <letter> enter. I came up with this idea as I was trying to rebind f to  single char sneak (s <letter> enter) to f, but couldn't find any current way to do this.

**Comment by J-Fields** [comment]
Thought about this a bit more and came down on the side of YAGNI. If we think greater flexibility would be worth the extra complexity we can do something like this in the future, but I'm just adding a flag to replace `f` with single-character sneak for now.
