### ISSUE TITLE
Ctrl+h ignores useCtrlKeys and handleKeys binds

### ISSUE THREAD

**Issue by caleywoods** [VSCodeVim/Vim#4019]
**Describe the bug**
`Ctrl+h` ignores `vim.useCtrlKeys` and `vim.handleKeys` binds

**To Reproduce**

1.) Open settings.json 

2.) Set `vim.useCtrlKeys = true,`

3.) Add this bind below the previous entry:
   
    "vim.handleKeys": {
        "<C-h>": true
    }
   
4.) Add these binds, they allow for more simple split navigation

    "vim.normalModeKeyBindings": [
        {
            "before": ["<C-h>"],
            "after": ["<C-w>", "h"]
        },
        {
            "before": ["<C-l>"],
            "after": ["<C-w>", "l"]
        }
    ]
  
5.) With a file open (settings.json works fine), enter the command `:vsp` to create a vertical split. You will now have two vertical splits open, both showing the same file.

6.) With the cursor in the leftmost split, `ctrl+l` will move you one split to the right.

7.) Now try `ctrl+h`. 

**Expected behavior**
Pressing `ctrl+h` should move the cursor one vertical split to the left per execution of the bind.

**Observed behavior**
The VSCode Find/Replace dialog box is displayed.

**Screenshots**
This is the state of the editor as a result of having the cursor in the right-most split and pressing `ctrl+h`.
![results](https://i.imgur.com/gOwwlz3.png)

**If remapping-related, please attach log output:**

 I enabled debug level logging and when opening the console and reloading VSCode I don't see the Remapper output when it's supposed to process any of the key bindings regardless of the mode or recursiveness but all my binds are functioning (except `ctrl+h`).

With the terminal open and pressing `ctrl-l` to move a split to the right, I do see the Remapper output as described and the cursor moves to the next split right. When pressing `ctrl+h` I get no Remapper output in the console and the Find/Replace dialog is displayed.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `1.10.0`
- VSCode version: `1.37.1`
- OS: `Windows 10 Pro x64 (10.0.17763)`

**Additional context**
In the screenshot I have the `handleKeys` defined before the `useCtrlKeys` but I've tried swapping it around and that had no effect.

**Comment by sndnyang** [comment]
My configuration works fine after adding your keybindings
My environment is the same...

**Comment by caleywoods** [comment]
@sndnyang I just tested this on a fresh install of Windows 10, VSCode, and VSCodeVIM and it IS working correctly. I did notice on the new installation that my previous way of opening splits (`alt+shift+{0-9}`) did not work but instead it needed `ctrl+{0-9}` so perhaps I have another extension that is causing a conflict on my main installation.

I will close this and if I can identify a culprit I will post it back here.

**Comment by caleywoods** [comment]
Update: Offending plugin located. It was [Sublime Text Key Mapping and Settings Importer](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings). Removing it made my installation work as expected with the key bindings in this issue.
