### ISSUE TITLE
Add setting to swap ; with : in Easymotion

### ISSUE THREAD

**Issue by nikitavoloboev** [VSCodeVim/Vim#4020]
**Is your feature request related to a problem? Please describe.**

Coming from https://github.com/VSCodeVim/Vim/issues/3816#issuecomment-526082341

I would love for a setting that would use `:` key instead of `;` in Easymotion plugin.

These ones:

![2019-08-29 at 17 22](https://user-images.githubusercontent.com/6391776/63958086-915e9e80-ca81-11e9-89f8-9456f59c7ca3.png)

I am open to sending a PR for this with some help in guiding the code of where I need to make the change.

Thank you.

**Comment by henrikrudstrom** [comment]
can you not just replace it in the EasyMotion keys setting? 
![image](https://user-images.githubusercontent.com/82979/64203778-85654900-ce94-11e9-858f-5cbda2a9a99e.png)

**Comment by nikitavoloboev** [comment]
Thanks @henrikrudstrom
