### ISSUE TITLE
How to re-map ":e" to ":w"?

### ISSUE THREAD

**Issue by tommulkins** [VSCodeVim/Vim#4026]
Maybe this isn't a bug per se but I'm trying to add the command `:e` to `vim.normalModeKeyBindingsNonRecursive` and change its behavior from _exiting_ to _saving_ just like `:w` does.  

Exiting in vs code just doesn't work and I often mistype "w" with "e"

I've tried numerous ways to handle this but haven't found a solution yet.  Has anyone else tried mapping these keys like this to affect a "save action"?

**Comment by J-Fields** [comment]
Possible duplicate of #2903?

**Comment by tommulkins** [comment]
> Possible duplicate of #2903?

@J-Fields  It is essentially very similar.  I will close this issue and comment in #2903 
Thanks!
