### ISSUE TITLE
When Overtype extension presents, VSCodeVim stops working.

### ISSUE THREAD

**Issue by denchat** [VSCodeVim/Vim#4046]
**Describe the bug**
When [Overtype](https://marketplace.visualstudio.com/items?itemName=adammaras.overtype) extension presents, vscodevim stops working.

**To Reproduce**
Install and enable both vscodevim and overtype extensions

**Expected behavior**
If vscodevim got suppressed by other extensions, in this case the overtype extension, it would be nice to inform users about that.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.10.2
- VSCode version: 1.38.0 64-bit
- OS: Windows 10 v1903 64-bit

**Additional context**

**Comment by J-Fields** [comment]
My guess is that extension is also overriding VSCode's handling for the `type` command, and only one extension can override it at a time.

Why not just use vim's replace mode (`R`)?

**Comment by denchat** [comment]
> Why not just use vim's replace mode (R)?

My point is at least there should be noted in README.md that Overtype interferes VSCodeVim. It must be better if VSCodeVim can detect that and inform users.

**Comment by J-Fields** [comment]
> My point is at least there should be noted in README.md that Overtype interferes VSCodeVim

Frankly I don't think this affects very many people, and those whom it does can likely find this ticket.

> It must be better if VSCodeVim can detect that and inform users.

That'd be awesome but it's not possible. We basically tell VSCode "please send keystrokes in the editor to me, thanks", and hand it a callback.

Anyway, I'm not positive that this is the cause, but if it is, it's an upstream issue.

**Comment by jpoon** [comment]
> My point is at least there should be noted in README.md that Overtype interferes VSCodeVim. It must be better if VSCodeVim can detect that and inform users.

As an extension, we don't have that ability. Each extension runs in it's own process and it has no knowledge of what other extensions you are running. 

You can take a look at the "contributions" section of the vscodevim extension marketplace to see what conflicting keybindings there are. Otherwise, I think this would be an upstream issue to have vscode present some sort of warning when multiple extensions are trying to handle the same key.
