### ISSUE TITLE
`S` (Shift+S) performs `0C` instead of `^C`

### ISSUE THREAD

**Issue by YongJieYongJie** [VSCodeVim/Vim#4049]
**Describe the bug**
In Vim, the `S` key (Shift+S) is equivalent to `^C` (i.e., moving the cursor to the **first non-blank character**, clearing to the end of the line, and entering `insert` mode).

However, in this extension, the `S` key is equivalent to `0C` (i.e., moving the cursor to the **first character**, clearing to the end of the line, and entering `insert` mode).

**To Reproduce**

1.  On any line, enter some text like below (note the four leading spaces):
```python
    def my_method():
```
2.  Position the cursor anywhere on the line.
3.  In `normal` mode, press `S` (Shift+S)
4.  See error: the whole line is deleted, and cursor is placed column `1`.

**Expected behavior**
Cursor should be at column `5`, after the four leading spaces.

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.10.2`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.37.1`

**Additional Information**
Same issue with `cc` in `normal` mode.

**Comment by J-Fields** [comment]
https://github.com/VSCodeVim/Vim/issues/3653
