### ISSUE TITLE
Cursor style does not change properly  when cursor mode has been changed

### ISSUE THREAD

**Issue by kogai** [VSCodeVim/Vim#4061]
**Describe the bug**

When I change the mode of the cursor from NORMAL to INSERT, styles of the cursor hasn't been changed.

**To Reproduce**

Can reproduce only on vscode-insiders(actually version is 1.39 or later)

1.  Open the file and focus to some text.
2.  Press an 'i' or 'a' key
3.  See what styles to a cursor applied

**Expected behavior**

Change styles of the cursor when mode has been changed.

**Screenshots**

![2019-09-10 11 02 00](https://user-images.githubusercontent.com/4057326/64578541-a9f08200-d3ba-11e9-95ca-75c5a185234b.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.10.2
- VSCode version: 1.39
- OS: macOS Mojave 10.14.5

**Additional context**

I don't know whether it's worth, vscode seems will become to be able to configure cursorStyle via editor's configuration.

https://github.com/microsoft/vscode/compare/release/1.38...master#diff-5a3a90617837271d84de842ed332110a

**Comment by J-Fields** [comment]
Reproduced on 1.39 insiders

**Comment by admosity** [comment]
Mine updated today and I had to set this option manually to get it working again:

```json
    "vim.cursorStylePerMode.insert": "line",
```

**Comment by tadams42** [comment]
I removed golbal VSCode editor setting `"editor.cursorStyle": "block"` from `settings.json` and now it works.

**Comment by jrwrigh** [comment]
Also running into issue. Rolling back to 1.11.3 worked for me (going back to 1.11.x to avoid the issues with #4342 )

**Comment by macintacos** [comment]
I removed the `"editor.cursorStyle": "block"` from my `settings.json`, and while that did work from going between normal/insert mode, my visual/replace modes aren't following the cursor style that's being explicitly specified. I have them in my settings like so:

```
  "vim.cursorStylePerMode.insert": "line",
  "vim.cursorStylePerMode.normal": "block",
  "vim.cursorStylePerMode.replace": "block-outline",
  "vim.cursorStylePerMode.visual": "block-outline",
  "vim.cursorStylePerMode.visualblock": "block-outline",
  "vim.cursorStylePerMode.visualline": "block-outline",
```

Used to work fine prior to 1.12.2.

**Comment by cvaldev** [comment]
I think this was resolved with #4468.

**Comment by J-Fields** [comment]
Should be. Someone holler if this isn't fixed in the next version (1.13.0)

**Comment by jrwrigh** [comment]
Can confirm that this is fixed in v1.13.0

**Comment by maxdzyubak** [comment]
Version `v1.25.2` don't works this settings:
```
"vim.cursorStylePerMode.replace": "underline",
"vim.cursorStylePerMode.visual": "underline",
```
My VSCode setup:
```
Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by victor-falcon** [comment]
I'm having problems in `v1.25.2` too

**Comment by dewald-els** [comment]
I'm still experiencing this :) often the cursor would be in Normal mode but it's actually in Insert mode.
