### ISSUE TITLE
Find and replace all occurances in current line does not work

### ISSUE THREAD

**Issue by bm-stschneider** [VSCodeVim/Vim#4067]
**Describe the bug**
`:s/is/isis/g`
=> A clear and concisise description of what the bug is.
expected
=> A clear and concisise description of what the bug isis.

**Comment by J-Fields** [comment]
My hunch is you've got `vim.substituteGlobalFlag` enabled. Can you confirm?

**Comment by bm-stschneider** [comment]
Ahh you got me :) Thank you.
