### ISSUE TITLE
Visual Selection and $ hotkey is going to the next line

### ISSUE THREAD

**Issue by RoyLee** [VSCodeVim/Vim#4069]
**Describe the bug**
In VIM, while in `visual selection` mode, the `$` hotkey moves to the end of the line. Using this extension it moves it to the next line.

**To Reproduce**
1.  Go to a line of code
2.  Go into visual selection mode
3.  Use the `$` key
4.  See that the visual selection ends up at the beginning of the next line.

**Expected behavior**
1.  Go to a line of code
2.  Go into visual selection mode
3.  Use the `$` key
4.  See that the visual selection ends up at the end of the current line.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.10.2
- VSCode version: 1.37.1
- OS: 10.13.6

**Comment by J-Fields** [comment]
See https://github.com/VSCodeVim/Vim/issues/3970. This is consistent with vim's behavior, up to the rendering, which we cannot control.
