### ISSUE TITLE
:%y does not work

### ISSUE THREAD

**Issue by sonicbhoc** [VSCodeVim/Vim#4071]
### Description
When I type `:%y`, I am told it is not an editor command. Using other ranges with `:%` does not work with `y` either.

### To Reproduce
In normal mode, type `:%y`.

### Expected behavior
The entire file is yanked.

### Environment
- Extension (VsCodeVim) version: 1.10.2
- VSCode version: 1.38.1
- OS: Windows_NT x64 10.0.17763

**Comment by J-Fields** [comment]
https://github.com/VSCodeVim/Vim/issues/3061
