### ISSUE TITLE
set cursorcolumn

### ISSUE THREAD

**Issue by chosun89** [VSCodeVim/Vim#4076]
No feature for `set cursorcolumn` yet (highlights the entire column as it does for row).

**Comment by J-Fields** [comment]
Hmm. This would definitely be done better upstream. We could do a half-assed job with decorations, but that would be slow and janky and wouldn't work at the end of a long line (since text needs to exist to decorate).

**Comment by chayan-blip** [comment]
Just in case someone needs it. 
First install this extension  **cursor-column-highlight**  by IuriiBarlukov
After that you can add following settings in vscode to get column and row highlighting
"workbench.colorCustomizations": {
        "editor.lineHighlightBackground": "#0000ff11",
        "editor.lineHighlightBorder": "#0000ff66"
    }
