### ISSUE TITLE
Command mode status bar is too small

### ISSUE THREAD

**Issue by liaohui5** [VSCodeVim/Vim#4077]
I want to be able to modify the style of the status bar. The status bar is actually too small. Very inconvenient when I use commands such as search or replace

**Comment by J-Fields** [comment]
This is not possible to do in a plugin - we can only specify the text and its color for our status bar item. Please file a ticket with VSCode (if there isn't one already).

**Comment by futurehome** [comment]
Why not using the vscode's command box as the input of vim command?

![image](https://user-images.githubusercontent.com/6230304/65843345-d23d2200-e363-11e9-82c3-7ad3a65f8310.png)

**Comment by emeren** [comment]
> Why not using the vscode's command box as the input of vim command?
> 
> ![image](https://user-images.githubusercontent.com/6230304/65843345-d23d2200-e363-11e9-82c3-7ad3a65f8310.png)

How can i turn on this command box in vscode ? i've only vim commands in statusbar..

**Comment by amqndin** [comment]
> > Why not using the vscode's command box as the input of vim command?
> > ![image](https://user-images.githubusercontent.com/6230304/65843345-d23d2200-e363-11e9-82c3-7ad3a65f8310.png)
> 
> How can i turn on this command box in vscode ? i've only vim commands in statusbar..

just put this in your normal mode keybindings object in settings.json
```json
    { "before": [":"], "commands": ["vim.showQuickpickCmdLine"] },
```

**Comment by liaohui5** [comment]
> > > Why not using the vscode's command box as the input of vim command?
> > > ![image](https://user-images.githubusercontent.com/6230304/65843345-d23d2200-e363-11e9-82c3-7ad3a65f8310.png)
> > 
> > 
> > How can i turn on this command box in vscode ? i've only vim commands in statusbar..
> 
> just put this in your normal mode keybindings object in settings.json
> 
> ```json
>     { "before": [":"], "commands": ["vim.showQuickpickCmdLine"] },
> ```

oh, it's perfect, thank u very much! 😄

**Comment by kschaab** [comment]
I thought I was going to be good and add this to the readme but it is already there.  Thank you so much!
