### ISSUE TITLE
`:vspl`

### ISSUE THREAD

**Issue by morbusg** [VSCodeVim/Vim#4078]
As Code already has vertical split mode, could it be possible to map `:vspl` to it? I’m loving this, so thank you very much!

**Comment by areinmeyer** [comment]
I think this is possible though requires a code change.  VSCodeVim does not distinguish between left or right splits but Code does have that available in the Command Palette.  Looks like it's a matter of adding the new mappings in the subparser for command line mode and then exposing the different Code commands to VSCodeVim.  

I have been wanting to tackle a feature for this project and could try it out.  Though I'm also about ready to move out of state.  I can give it a go but it may be a week or so before a PR is ready.

**Comment by areinmeyer** [comment]
So it seems that #4106 causes this to be more complicated than planned.  With that change, `:vspl` now is treated as `:vsplit`.  I'm not quite sure how to change the logic in the subparser.ts to make this work but keep #4106 still correct as well.  

I wonder if we should rearrange the logic to check for an exact match before the code iterates through the parsers to check for a match.  
Then `vspl` finds the `vspl` function, `vsplit` finds the vsplit function and `vs`and `vsp` still goes to vsplit as well. 
Sort of akin to an early return check?

**Comment by J-Fields** [comment]
@areinmeyer Sorry about that! Is `vspl` actually a different command than `vsp` in vim?

**Comment by morbusg** [comment]
Oh man, now I feel silly; `:vsplit` already works! (`:vspl` is just an alias in vim). Sorry about this.

**Comment by areinmeyer** [comment]
OK, what I was seeing is that VSCodeVim opens vertical splits to the right by default.  Vim by default opens on the left.  So I was thinking it was two different commands.  But you're right.  `vspl` is just an alias for `vsplit`.
