### ISSUE TITLE
Cannot map <C-d> to <Del> in insert mode

### ISSUE THREAD

**Issue by iiifr** [VSCodeVim/Vim#4082]
**Describe the bug**
Cannot map `<C-d>` to `<Del>` in insert mode

**To Reproduce**
- Add `{ "before": ["<C-d>"], "after": ["<Del>"] }` into `"vim.insertModeKeyBindingsNonRecursive"`
- Press `<C-d>` in insert mode to delete text

**Expected behavior**
Press `<C-d>` in insert mode then text will be deleted like pressing `<Del>`

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.10.2
- VSCode version: 1.38.1
- OS: Windows 10

**Comment by muellerto** [comment]
Why is this immediately classified as a bug after one day while [my case](https://github.com/VSCodeVim/Vim/issues/3863) is not after almost 3 months? I guess the two cases (and some more) have the same reason and can be solved together.

**Comment by sqlkoala** [comment]
Hi, I am quiet sure that this is not a mapping bug. From looking at the source (insert.js) `<del>`  is not implemented as a vim insert command, so it is not there to map to. I will create an issue for that.
