### ISSUE TITLE
directories are un-completable with tab-completion

### ISSUE THREAD

**Issue by brianjmurrell** [VSCodeVim/Vim#4085]
**Describe the bug**
Tab completion doesn't seem to work for anything but files (so limited to $PWD).

**To Reproduce**
1.  Open a file
2.  Enter ":n " to change the file in the workspace to another file
3.  Type in the first few letters of a directory
4. Press TAB to get the completion of the directory name

**Expected behavior**
Should complete the directory name and start actioning completions in that directory.  Like VIM does.

- Extension (VsCodeVim) version: 1.10.2
- VSCode version: 1.38.1
- OS: Linux

**Comment by J-Fields** [comment]
@stevenguh I know you worked on this recently. This seems to work on the latest master - can you confirm?

**Comment by stevenguh** [comment]
yes, should be fixed by #4032

**Comment by brianjmurrell** [comment]
Ahh.  Only merged 7 days ago.  I guess it will be a while until we see it in a release?

**Comment by stevenguh** [comment]
If we decided to do a release, I'd suggest we wait until #4089 is merged as well

**Comment by J-Fields** [comment]
I'll take a look and then if I have a chance this evening, I'll cut a release. There have been a good number of new features and bug fixes since the last release that we're probably overdue.
