### ISSUE TITLE
ViM extension makes VSCode super slow, typing is almost impossible.

### ISSUE THREAD

**Issue by MMaicki** [VSCodeVim/Vim#4088]
**Describe the bug**
When ViM extension is enabled VSCode is almost unusable, it gets super slow and laggy. After disabling the extension VSCode is running perfect. Problem occured in random moment while typing. Getting into insert mode is impossible after enabling extension.
I have seen similar bug reports from the past.

**To Reproduce**
Enable extension and try to type, file is only 30 lines big.

**Expected behavior**
Working fine as it was working before, like 10 minutes ago.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.10.2
- VSCode version: 1.38
- OS: Windows 7 Ultimate, latest update available at the moment.
- PC spec: 8GB ram, i5 3rd gen, 128GB SSD

**Comment by J-Fields** [comment]
Closing as there are several other established issues for these perf issues.
