### ISSUE TITLE
Make this project buildable

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#409]
@rebornix and I are running into issues when just cloning the project and trying to run it. We are missing some typescript definitions.

**Comment by jpoon** [comment]
Did https://github.com/VSCodeVim/Vim/pull/419 fix this?

**Comment by rebornix** [comment]
Amazingly awesome @jpoon , now I can run and compile automatically with low latency and no errors, our Getting Started experience is almost perfect.

**Comment by johnfn** [comment]
Awesome job @jpoon 😄
