### ISSUE TITLE
Cannot use ; and , to search forward and backward in f{char} F{char} t{char} and T{char}

### ISSUE THREAD

**Issue by jingkangy91** [VSCodeVim/Vim#410]
Do you need help or have a question? Ask us on Slack (https://vscodevim-slackin.azurewebsites.net/) 👫. 
Found a bug? Please fill out the sections below 👍.

### Issue Summary

A summary of the issue -- what blew up? what major feature are we missing? 
Cannot use ; and , to search forward and backward in f{char} F{char} t{char} and T{char}

### Steps to Reproduce

1. First I use "f{char}" to find a character,
2. then I cannot use ";" or "," to search forward or backward which is very convenient in Vim.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* VSCode Version: 1.3.0
* OS: Windows 10

**Comment by johnfn** [comment]
This is done! Thanks @aminroosta!
