### ISSUE TITLE
Support pulling word under the cursor into a search

### ISSUE THREAD

**Issue by ruimaciel** [VSCodeVim/Vim#4102]
VIM supports pulling the word under the cursor into a command line or search.  

In Vim, his functionality is activated by performing the following steps:

* moving the cursor onto a word

* enter search mode (i.e., hit the / key)

* press Ctrl-R, Ctrl-W

The result is having the word under the cursor copied into the search field.

It would be awesome if VSCodeVim also supported this feature.

**Comment by muellerto** [comment]
You know the `*` key?

**Comment by ruimaciel** [comment]
@muellerto yes I do. <Ctrl-R><Ctrl-W> does an entirely different thing, though.

**Comment by mikaoelitiana** [comment]
The difference I see is `*` searches for exact matching words and `<Ctrl-R><Ctrl-W>` matches anything containing the search word, is that what you mean @ruimaciel ?

**Comment by J-Fields** [comment]
@mikaoelitiana That's true, but it's more than that - you can incorporate the term under the cursor into a larger search or paste it into the command line for a `:s`, etc.

**Comment by ruimaciel** [comment]
> s and `<Ctrl-R><Ctrl-W>` matches anything containing the search word

No, that's not what `<Ctrl-R><Ctrl-W>` does.  The `<Ctrl-R>` family of commands insert the content from a source in the current cursor position.  In normal mode the `<Ctrl-R><Ctrl-W>` command pastes the object under the cursor in the command line.  

http://vimdoc.sourceforge.net/htmldoc/cmdline.html

This functionality is particularly helpful if a user wants to replace a string with a slight variation of it, such as adding a prefix/suffix.  For example, if a user wants to replace all occurrences of `foobar` with `foobar_bar` then he only needs to do the following:

1) place cursor on top of an occurrence of the pattern `foobar`

2) switch to normal mode

3) type `%s:<Ctrl-R><Ctrl-W>:<Ctrl-R><Ctrl-W>_bar:g`

4) press <Enter>
