### ISSUE TITLE
Support VSCode's View: Toggle Panel in vim mode.

### ISSUE THREAD

**Issue by ruimaciel** [VSCodeVim/Vim#4103]
VSCode supports toggling the workbench panel by hitting Ctrl-J. However, If VSCodeVim's Vim Mode is enabled then that keyboard shortcut is ineffective.

It would be nice if VSCodeVim enabled users to toggle VSCode's panel without having to toggle VSCodeVim.

**Comment by J-Fields** [comment]
You can always disable VSCodeVim's handling of `<C-j>` or set a custom hotkey for that command

**Comment by ruimaciel** [comment]
Yes, you are right.  However, that becomes a bit unwieldy because it involves at least a sequence of three keyboard shortcuts just to close a panel (disable vscode, toggle panel, enable vscode).

Personally, as I've adopted Qt Creator's shortcut to toggle VSCodeVim on/of (`ctrl-v`, `ctrl-v`) then the keyboard shortcut to toggle a panel is `ctrl-v`, `ctrl-v`, `ctrl-j`, `ctrl-v`, `ctrl-v`.

What would be really awesome was if VSCodeVim supported vim-style key mapping, thus letting users configure keyboard shortcuts for each mode. 

https://vim.fandom.com/wiki/Mapping_keys_in_Vim_-_Tutorial_(Part_1)

**Comment by J-Fields** [comment]
You can set a custom hotkey in VSCode's settings, use `handleKeys` to disable vim's handler, or our own remapping capabilities (`normalModeKeyBindingsNonRecursive`, etc.). There's no need to disable VSCodeVim.

**Comment by ruimaciel** [comment]
I was entirely unaware that `vim.handleKeys` existed.  Very nice!  I've followed your suggestion, updated my settings to delegate `<C-j>`to VSCode and everything works as expected. 

For future reference, here's the link to [VSCodeVim's settings documentation](https://github.com/VSCodeVim/Vim#vscodevim-settings).
