### ISSUE TITLE
Bind u to ctrl+z?

### ISSUE THREAD

**Issue by lydell** [VSCodeVim/Vim#4113]
Is there any way to make `u` do the same thing as the standard `ctrl+z`? I think the standard `ctrl+z` works better than the undo provided by this plugin.

I tried this:

```json
"vim.normalModeKeyBindingsNonRecursive": [
    {
        "before": [
            "u"
        ],
        "after": [
            "undo"
        ]
    }
]
```

And this:

```json
"vim.normalModeKeyBindingsNonRecursive": [
    {
        "before": [
            "u"
        ],
        "after": [
            "editor.action.undo"
        ]
    }
]
```

But those resulted in `u` doing nothing when pressed.

I’ve looked through the documentation and can’t figure this out. I hope it’s OK to ask here!

VSCode version: 1.38.1
VSCodeVim version: 1.11.0
OS: Ubuntu 19.04

**Comment by matrixersp** [comment]
Try this:
```json
"vim.normalModeKeyBindingsNonRecursive": [
   {
      "before": ["u"],
      "commands": ["undo"]
   }
]
```

**Comment by J-Fields** [comment]
https://github.com/VSCodeVim/Vim/issues/2007#issuecomment-529924611

**Comment by lydell** [comment]
Awesome, thanks!

I somehow missed all the time that the examples in the readme uses `"commands"` rather than `"after"`. Doh!
