### ISSUE TITLE
Extension issue: High key repeat stress the cpu/extension host

### ISSUE THREAD

**Issue by st-schneider** [VSCodeVim/Vim#4116]
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.11.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.39.0-insider`

The call stack just gets way to big if I just scroll down or up with j and k a bit. The delay is constantly building if to the point where the editor is still scrolling and I don't press any button because so many events queued up.
[CPU-20190930T141845.136Z.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/3671718/CPU-20190930T141845.136Z.cpuprofile.txt)

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 101,
		"activateCallTime": 3,
		"activateResolvedTime": 1795,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscodevim.vim",
				"_lower": "vscodevim.vim"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by anon176** [comment]
Same here. I find that not rendering indent lines and current lines helps a bit but even stock VSCode will use around 50% of my CPU when I'm just pressing down arrow with high key-repeat. VSVim adds around 20% more CPU usage not sure why.

**Comment by bm-stschneider** [comment]
Seem like the extension is checking suitable event on every visited line also going through all the maps and remaps and that adds up quickly

**Comment by J-Fields** [comment]
Closing as stale
