### ISSUE TITLE
Can't switch back from replace mode (R) to normal mode using mapped keys

### ISSUE THREAD

**Issue by matrixersp** [VSCodeVim/Vim#4118]
**Describe the bug**
If I use `R` to replace more than one character, I can't switch back to normal mode with the remapped keys `jk` ( I use `jk` to switch to back to normal mode instead of  `<esc>`).

**To Reproduce**

1.  Press `Shift + r`
2.  Type a sequence of characters
3.  Press `j` then `k`

**Expected behavior**
I expect if I can switch from Replace mode to Normal mode using `jk`.

**Screenshots**
![vscode-gif](https://i.imgur.com/K6KuLFY.gif)

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.11.0`
- OS Version: `Linux x64 4.15.0-62-generic`
- VSCode version: `1.38.1`

**Additional context**
I think it would be nice if we could do mapping for Replace mode, something like this:
```json
"vim.replaceModeKeyBindingsNonRecursive": [
    {
      "before": ["j", "k"],
      "after": ["<esc>"]
    }
  ]
```

**Comment by dsi3** [comment]
I would love this.

**Comment by berknam** [comment]
PR #4735 fixes this. It uses the `insertModeKeyBindings` and `insertModeKeyBindingsNonRecursive` which are analogous to Vims `imap` and `inoremap`. Insert mode mappings are used both on insert mode and replace mode. I don't think there is a need for specific mappings just for replace mode.

The problem in this issue will be fixed once that PR gets merged.
