### ISSUE TITLE
Cursor movement in wrapped lines changed from 1.10.2 to 1.11.0

### ISSUE THREAD

**Issue by jrwrigh** [VSCodeVim/Vim#4120]
**Describe the bug**
Using the `gj` and `gk` binding to [move by wrapped line instead of the file line](https://vim.fandom.com/wiki/Move_cursor_by_display_lines_when_wrapping) does not work correctly in version 1.11.0, but works fine when downgrading to 1.10.2.

Specifically, here are the issues I've experienced:
1) sometimes it will move up (`gj`) by file line, but down (`gk`) by wrapped line. Though this behavior is inconsistent and reverses itself sometimes.
2) when it does successfully move by wrapped line, it'll change the relative character position, sometimes moving to the last character in the wrapped line, sometimes the first, sometimes by a (seemingly) random number of characters in either direction. (Note: this is moving in a block of text where there are several wrapped lines for every file line)

**To Reproduce**
Go to file with lots of wrapped lines (or take a normal file and make the window really narrow) and move up and down with `gj` and `gk`. 

**Expected behavior**
It to move by one wrapped line and maintain the same lateral character position (assuming there is a character present in that lateral character position).

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.0
- VSCode version: 1.37.1
- OS: Manjaro 18.1 

Note: Manjaro currently doesn't have vscode 1.38.x on it's stable branch. This is why I'm a version behind the latest.

**Comment by J-Fields** [comment]
Can you confirm it works with no line wrapping? We fixed `gj`'s behavior over lines of different lengths in 1.11.0, but maybe we messed up its behavior when lines are wrapped

**Comment by jrwrigh** [comment]
When turning word wrapping off, `gj` and `gk` do work correctly (as in they do exactly what `j` and `k` would do) in 1.11.0.

**Comment by J-Fields** [comment]
Thanks for the confirmation, and sorry for the regression. This change was made via #3890. @hetmankp would you mind taking a look when you get a chance? I'll do the same.

**Comment by jrwrigh** [comment]
No worries. Downgrading the extension is simple enough, so it's not to difficult to work around right now.

**Comment by hetmankp** [comment]
Turns out fixing this is impossible because of the limitations of the VSCode API and the way VSCodeVim interacts with the editor cursors. I will submit a PR to more or less reverse the previous change with additional explanations for anyone looking into this in the future.

**Comment by hetmankp** [comment]
Not sure why the pull request wasn't automatically reference by GitHub but the PR to revert to the previous behaviour is found at #4127

**Comment by jrwrigh** [comment]
Looks like since this issue wasn't mentioned in the pull request itself it doesn't get referenced (even though you referenced it in the commit.

**Comment by hetmankp** [comment]
> Looks like since this issue wasn't mentioned in the pull request itself it doesn't get referenced (even though you referenced it in the commit.

Yes, you're right. It has to be mentioned in the body of the issue description and not the title.
