### ISSUE TITLE
Cannot rebind : to ;

### ISSUE THREAD

**Issue by noelfarrugia09** [VSCodeVim/Vim#4124]
**Describe the bug**
I cannot rebind : to ;

In vim I have the following code that rebinds the : with the ; key so that I avoid having to press shift all the time

```
" Map the : command to ; to avoid pressing shift
nnoremap ; :
```

I tried to achieve the same effect in VsCode by using the following in the settings.json file but it's having no effect:

```
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before":[":"],
            "after": [";"]
        },
    ]
```

Am I doing something wrong, or is this feature not supported yet?

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.0
- VSCode version: 1.38.1
- OS: macOs Mojave 10.14.6

**Comment by J-Fields** [comment]
`before` is what you type, `after` is the result - you've got it backward

**Comment by noelfarrugia09** [comment]
Thank you for your prompt reply.
