### ISSUE TITLE
Copy command broke in 1.11.0 release

### ISSUE THREAD

**Issue by tjb-wiley** [VSCodeVim/Vim#4126]
**Describe the bug**
On both my Mac and Ubuntu laptops, if I try to copy/paste code using the `co` command, like this:
```
:1,20co20
```
I get an error:
```
TaskQueue: Error running task. Failed to handle key= . nvim_buf_set_lines: Wrong type for argument 1, expecting Buffer.
Source: Vim (Extension)
```

**To Reproduce**

1.  Open any source file
2.  With "enable neovim" check in setting, try to copy/paste any lines

**Expected behavior**
Lines 1,20 should be copied after line 20 

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.0
- VSCode version: 1.38.1
- OS: MacOS 10.14.6

**Additional context**

Since this extension is using `neovim`, i upgraded it via brew to ensure that that didn't fix the issue. Even after upgrading from 0.3.4 -> 0.4.2, however, still get the same error.

![Screen Shot 2019-10-02 at 5 57 22 PM](https://user-images.githubusercontent.com/47123536/66085307-da9d8480-e53e-11e9-9376-b847cb6115a5.png)

**Comment by tjb-wiley** [comment]
I just confirmed that downgrading to `1.10.2` works, so that is a short-term workaround

**Comment by haifengkao** [comment]
same here. actually I get get this error by any command, e.g. `:nothiscommand`

**Comment by dreadwail** [comment]
Global file search/replace via `:s` is also busted with the same error message. Can confirm downgrading to `1.10.2` solves it as well.

**Comment by jpoon** [comment]
Going through the diff, we didn't change anything explicitly with neovim. The neovim npm package we rely on is at the same version and likewise no code change in the interface. May have been our migration to webpack?

**Comment by jpoon** [comment]
It was indeed the webpack change.

```
git revert 1f80b2d4cc4d4d108acb18d9fca8c49b8891b696
```

Seems to have fixed neovim.

**Comment by jpoon** [comment]
Ok, that didn't work. Reverting this commit and pushing a new version as that commit completely broke the extension if neovim was enabled.

**Comment by Hultner** [comment]
I see a mention of this working if we downgrade to `1.10.2`, how would one go about doing this?


This issue have been driving me mad, at first I thought it was my neovim so have just been using neovim directly since the issue appeared but yesterday I experience the exact same problem on a completely different computer/system and at that point I suspected it might be a bug in neovim. Did some searching and found this. As someone who's only installed plugins via the vscode interface I have no idea where to even start for enforcing an older plugin-version.

**Comment by Hultner** [comment]
> You have a couple of options:
> 
> * Download an old release from here and drag and drop into code: https://github.com/VSCodeVim/Vim/releases.
> * On the extensions menu in code, click the settings for vim extension and install a different version
> 
> > This bugs makes vscode unusable for me, I rely a lot on proper ex commands to work, I can't even do a simple sort in vscode at this point.
> 
> Contributions are welcome! It's definitely attributed to our move to using webpack. Unfortunately, I don't understand webpack enough to figure out what could be going wrong. Alternatively, we can go nuclear and revert the commit...

Would happily contribute but I'm not a webpack expert (merely even a consumer) and have never coded TypeScript so I would barely even know where to start without much guidance.

**Comment by trkoch** [comment]
My wild guess would be that some kind of build optimization is hitting us here. @jpoon Any luck diffing the compiled scripts before/after the move to webpack?

**Comment by jpoon** [comment]
No. Sorry, haven't had time. 

Let's move ahead with reverting the webpack commit. It'd be amazing if somebody could help submit a PR reverting the commit and testing that neovim indeed does work. I'll merge, and can release a new version of the extension.

**Comment by rickpr** [comment]
https://github.com/VSCodeVim/Vim/pull/4217

**Comment by jpoon** [comment]
Thanks. Merged and released over the weekend.

**Comment by Eddie-CooRo** [comment]
This still happens on v1.13.1 when trying to use `:g` command over a range specified by marks. for example:
`:'a,'bg/^/d`
