### ISSUE TITLE
":!<command>" doesn't work and fails with the message: "E492: Not an editor command"

### ISSUE THREAD

**Issue by zacharylawrence** [VSCodeVim/Vim#4135]
**Describe the bug**
":!<command>" doesn't work and fails with the message: "E492: Not an editor command"

**To Reproduce**
1. Visually select multiple lines
2. Type ":!sort"

**Expected behavior**
The lines visually selected are sorted

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.11.0
- VSCode version: 1.38.1
- OS: Windows Subsystem for Linux (Linux x64 4.4.0-17763-Microsoft)

**Comment by jpoon** [comment]
Huh? `:!` means execute on the shell. Did you mean to do `:sort`? `:sort` is something that is supported.

**Comment by mmynsted** [comment]
What would be needed to get bang commands to work? 
The [roadmap](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md) shows `:!{command}`  **execute {command} with a shell** as a low priority.
