### ISSUE TITLE
:sort u command does not remove duplicates

### ISSUE THREAD

**Issue by matt8288** [VSCodeVim/Vim#4142]
Issue Type: <b>Bug</b>

**Describe the bug**
:sort u does not remove duplicate lines but only sort lines alphabetically

**To Reproduce**
:sort u

**Expected behavior**
sort lines alphabetically and remove duplicates

**Environment (please complete the following information):**
Extension version: 1.11.0
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:30:08.229Z)
OS version: Linux x64 4.15.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|7.25GB (1.02GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joanrieu** [comment]
Fixed in https://github.com/VSCodeVim/Vim/commit/7befd31380bdb9ce1a2182936f4921b039b7b721
