### ISSUE TITLE
Create VSCodeVim/VimTutor for new developers

### ISSUE THREAD

**Issue by pedroapfilho** [VSCodeVim/Vim#4146]
**Is your feature request related to a problem? Please describe.**

I would like to have some kind of vimtutor for this extension. It would help a lot.

**Describe the solution you'd like**

We could create a VsCodeVim/VimTutor on this organization and create it as a CLI to integrate with VSCode and provide tutorials and practices, just like vimtutor does.

**Comment by J-Fields** [comment]
Hey @pedroapfilho - I like this idea a lot, but I think making it a separate CLI is overkill. In fact, isn't `vimtutor` just a text file? It's probably not too big to zip up and ship with the extension.

**Comment by J-Fields** [comment]
Just verified -- only 10 KB. I'm thinking we create a `vimtutor` command which would unzip the contents of vimtutor into a temporary file then open that file.

**Comment by pedroapfilho** [comment]
what if integrating and showing the user how to go to new files? VSCode things. We could at least open 2 different files into a folder, what do you think? So we can add things like: "Switch tab", "Go to this file", "Split the tab" and etc
