### ISSUE TITLE
Trying to map Y to y$

### ISSUE THREAD

**Issue by aquaductape** [VSCodeVim/Vim#4158]
```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "Y",
      ],
      "after": [
        [
          "y",
          "$"
        ]
      ]
    },
  ],
```
Nothing is copied to clipboard when using the new mapping. I'm expecting it to copy from cursor position to the end of line.

**Comment by aquaductape** [comment]
```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "Y",
      ],
      "after": [
        "y",
        "$"
      ]
    },
  ],
```

I accidentally nested the array with another array inside after

**Comment by meteorsh** [comment]
Hello, is it possible to use `y + h` to map `y + $`?

**Comment by J-Fields** [comment]
@meteorsh You mean `yh` does `y$`? If so, that's not currently possible - #3086 is the relevant issue

**Comment by meteorsh** [comment]
> @meteorsh You mean `yh` does `y$`? If so, that's not currently possible - #3086 is the relevant issue

Well, it sounds a bit sorry. Hope it can be possible in the future!
