### ISSUE TITLE
Feature request: Highlight text color

### ISSUE THREAD

**Issue by marconett** [VSCodeVim/Vim#4164]
**Is your feature request related to a problem? Please describe.**
There's no way to define a highlight text color that goes with the background color defined by `vim.searchHighlightColor`, making it hard to find a good `vim.searchHighlightColor` that works in contrast with every text color in your theme.

![Screenshot 2019-10-11 at 13 48 58](https://user-images.githubusercontent.com/3315507/66649213-e4557500-ec2d-11e9-847c-a3b3cbb59df6.png)

**Describe the solution you'd like**
Making it possible to define a `vim.searchHighlightTextColor` would eliminate any contrast issues. 

**Additional context**
see #1052

**Comment by J-Fields** [comment]
Yeah I agree - this is an easy win. We can do the same for the yank highlight as well.
