### ISSUE TITLE
Activating extension 'vscodevim.vim' failed: Cannot find module 'neovim'.

### ISSUE THREAD

**Issue by willbchang** [VSCodeVim/Vim#4173]
**Describe the bug**
I received the v1.11.1 update several minutes ago, after reloading VSCode VSCodeVim didn't work anymore. I'm not using neovim.

**To Reproduce**
1.  Open VSCode with V1.11.1 VSCodeVim enabled

**Expected behavior**
Can be used normally.

**Screenshots**
![Screen Shot 2019-10-14 at 4 17 27 PM](https://user-images.githubusercontent.com/14329786/66737292-2a187480-ee9e-11e9-8ef8-51a9c0343ece.png)
![Screen Shot 2019-10-14 at 4 15 36 PM](https://user-images.githubusercontent.com/14329786/66737223-f4738b80-ee9d-11e9-9cc1-9fb93a57b65e.png)

```json
  "vim.autoSwitchInputMethod.defaultIM": "com.apple.keylayout.US",
  "vim.autoSwitchInputMethod.enable": true,
  "vim.autoSwitchInputMethod.obtainIMCmd": "/usr/local/bin/im-select",
  "vim.autoSwitchInputMethod.switchIMCmd": "/usr/local/bin/im-select {im}",
  "vim.handleKeys": {
    "<C-d>": false,
  },
  "vim.overrideCopy": false,
  "vim.useCtrlKeys": true,
  "vim.useSystemClipboard": true,
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.11.1
- VSCode version: v1.39.1
- OS: macOS 10.15

**Comment by GoNZooo** [comment]
Seeing this as well. Deleting the extension folder and reinstalling does nothing to fix it.

**Comment by willbchang** [comment]
@GoNZooo Confirmed v1.11.2 fixed this issue.

**Comment by cmoog** [comment]
Seeing this issue again. Any chance it relates? @willbchang

**Comment by willbchang** [comment]
@cmoog  It still works on my computer.

**Comment by JosXa** [comment]
I am experiencing this problem on 1.14.5 on `code-server` (i.e. Chrome), but not on local machine.
