### ISSUE TITLE
Extension Version 1.11.1 not Working for me

### ISSUE THREAD

**Issue by edrose** [VSCodeVim/Vim#4174]
**Describe the bug**
I opened up VSCode this morning to start work and the extension didn't work at all. I had no vim cursor, and couldn't use any vim shortcuts without it typing directly into the text editor. Pressing <kbd>ctrl</kbd> + <kbd>p</kbd> and selecting `Toggle Vim Mode` gives the error "command 'toggleVim' not found". VSCode had also updated so I tried downgrading that to the last version and that didn't help. I also removed my VSCode config folder in case that was the issue and that didn't help either. In the end, installing the latest VSCode and downgrading the Vim extension to 1.11.0 fixed the extension for me.

Running "Developer: Show running extensions" does not list VSCode Vim in the list of running extensions.

**To Reproduce**
Install the latest VSCode version (1.39.1 right now) and the latest VSCodeVim version (1.11.1). The vim extension commands appear in the <kbd>ctrl</kbd> + <kbd>p</kbd> menu, but trigger errors when run. All keyboard input goes straight into text editor and no vim commands can be used.

**Expected behavior**
Expected Vim shortcuts and commands to work.

**Screenshots**
![Screenshot from 2019-10-14 09-18-18](https://user-images.githubusercontent.com/6173903/66737456-e4d75100-ee63-11e9-81fc-52e42fa1c57b.png)
Screenshot of the command not found error.

![Screenshot from 2019-10-14 09-23-28](https://user-images.githubusercontent.com/6173903/66737623-63cc8980-ee64-11e9-81a5-a708549bfc96.png)
Screenshot showing Vim installed and enabled, with vim commands available but not running in "Developer: Show running extensions".

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.1
- VSCode version: 1.39.1
- OS: Ubuntu 18.04

![Screenshot from 2019-10-14 09-21-32](https://user-images.githubusercontent.com/6173903/66737497-10f2d200-ee64-11e9-9739-8f0222ad6b13.png)

**Additional context**

**Comment by willbchang** [comment]
This issue has been fixed on v1.11.2. It's already on the marketplace. Please reload your VSCode. A new version should be installed.

**Comment by heyi** [comment]
thank to save my time

**Comment by edrose** [comment]
Cheers for the quick response. It's just popped up - reloaded and it works.
