### ISSUE TITLE
Transfer vim control to "peek definition/reference" popup window without having to click

### ISSUE THREAD

**Issue by ecotner** [VSCodeVim/Vim#4187]
**Is your feature request related to a problem? Please describe.**
I frequently find myself using the "peek reference" and "peek definition" shortcuts to inspect function definitions that I don't want to scroll up to or open a new file in order to view. However, when I do use these peek commands, if I want to scroll or edit the code in the popup, I need to click into the popup with my mouse, which is frustrating because it takes my fingers away from the home row.

**Describe the solution you'd like**
I would like if upon using one of the peek commands (especially "peek definition") I could immediately start scrolling or manipulating text in the popup rather than having to click into it with the mouse first.

**Describe alternatives you've considered**
As mentioned before, clicking into the popup transfers control to the popup, which I can then use vim commands in. It's not that bad but breaks my flow.

**Additional context**
When I say "popup", this is what I mean (which I get by using `Alt + F12`):

![Screen Shot 2019-10-17 at 10 15 28 AM](https://user-images.githubusercontent.com/10482181/67017035-23b91100-f0c7-11e9-8dff-f10f3fb2ba92.png)

**Comment by liubko** [comment]
is it possible to call "peek definition" with smth like `gp` or `<leader>p`, I tried this wat, but with no effect

```
  "vim.normalModeKeyBindingsNonRecursive": [
    {"before": ["<leader>", "p"], "after": ["editor.action.peekDefinition"]}
  ],
```

**Comment by max-sixty** [comment]
Duplicate of https://github.com/VSCodeVim/Vim/issues/2675?

**Comment by ecotner** [comment]
Ahh, you're right, this does look to be a duplicate. I'd argue my request is a bit clearer, but the other issue does have more visibility. I'll close this in favor of the other one.
