### ISSUE TITLE
hang several seconds after replace a block of text by paste

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#420]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### Issue Summary

VSCode hang several seconds after replace a block of text by paste(`ctrl + v`), and `u` takes several seconds to undo this paste

### Steps to Reproduce

1. make sure there are some lines of text in the clipper board
2. open a file with some text in it
3. select a block of text
4. `ctrl+v` to replace the selected text with the content of clipper board
5. VSCode hang several seconds
6. `u` to undo the paste
7. it takes another several seconds to complete

### Technical details:

* VSCode Version: 1.3
* VsCodeVim Version: 0.1.1
* OS: Windows 10 professional

**Comment by johnfn** [comment]
How much text are you pasting?

**Comment by localvar** [comment]
text in clipboard and be replaced are both about 50 lines. here 'hang' means I cannot type anything in that time

**Comment by localvar** [comment]
found the issue is not 100% reproducible, but it do happens to me several times.

**Comment by johnfn** [comment]
This is related to #427, so I'm closing in favor of that one. It's hard, but things are moving in the right direction.

**Comment by johnfn** [comment]
I was wrong; this is going to REALLY be fixed by #558.
