### ISSUE TITLE
Cannot search for words which include slashes

### ISSUE THREAD

**Issue by dianlujitao** [VSCodeVim/Vim#4200]
**Describe the bug**
Suppose the target word is `/usr/share`, to search for it in native vim I use `/\/usr\/share<Enter>`, but in vscodevim neither the preceding one nor `//usr/share<Enter>` does work.

**To Reproduce**
As above

**Expected behavior**
The word in text matches.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.11.2
- VSCode version:1.39.2
- OS:Linux x64 5.3.7-arch1-1-ARCH

**Comment by meowjesty** [comment]
I'm using vscodevim 1.0.4 (on Windows) and `/\/usr\/share<Enter>` works as expected.

**Comment by dianlujitao** [comment]
![ff](https://i.imgur.com/EucDChU.gif)

**Comment by J-Fields** [comment]
Yeah this does seem like a bug.

@meowjesty just wondering - why do you use such an old version?

**Comment by meowjesty** [comment]
@J-Fields because of #3455

**Comment by J-Fields** [comment]
@meowjesty That should be fixed by #4074. Might be worth giving the latest release a shot!

**Comment by dianlujitao** [comment]
@J-Fields Thanks for the fix!

**Comment by J-Fields** [comment]
Do note that a forward search for `/` and a backward search for `?` each require a backslash escape now (I don't think they did before this was broken). This is in line with Vim, at least on the default `magic` level.
