### ISSUE TITLE
Add :UnicodeName (aka ga)

### ISSUE THREAD

**Issue by i5513** [VSCodeVim/Vim#4204]
I cant know which char is under "�" symbol when I open a file with a different encoding.

I have a path which is not written with UTF8, and I need to access it. My workaround is cd xxx*

I could copy the code and create the oportune string to read the file

[int] [char] "�"  would give the unicode code that should be show when "ga" command is used

Thanks!

**Comment by J-Fields** [comment]
Documentation [here](http://vimdoc.sourceforge.net/htmldoc/various.html#ga)

**Comment by J-Fields** [comment]
@i5513 The basics of `ga` are now implemented in https://github.com/VSCodeVim/Vim/commit/75fbe5a3d3d847c7691a005885273ec2878bcb5e. I didn't cover all the edge cases, so let me know if this isn't sufficient for your use case, and we can re-open this ticket.
