### ISSUE TITLE
Selection mode moves cursor to next line

### ISSUE THREAD

**Issue by gpanneerselvam-prosper** [VSCodeVim/Vim#4214]
When I am trying to select line from current position in selection mode until end of line using ($), the cursor moves to the start of the next line in insertion mode (if a new line is present).

The cursor moving to the start of the next line
![Screenshot 2019-10-24 14 58 11](https://user-images.githubusercontent.com/23644531/67528734-05c35180-f66f-11e9-9e05-393efb0817dd.png)

The cursor ending at the end of the current line (happens only when there is no line break)
![Screenshot 2019-10-24 14 58 01](https://user-images.githubusercontent.com/23644531/67528735-06f47e80-f66f-11e9-98f7-f08fac5ef310.png)

Isn't **$** supposed to be only until linebreak? 

The other operations work fine, like yanking until linebreak _y$_  and deleting until linebreak _d$_

**Comment by J-Fields** [comment]
> the cursor moves to the start of the next line in insertion mode

Actually, this is how VSCode shows that your selection includes the newline character; you're not in insertion mode.

> Isn't $ supposed to be only until linebreak?

Strangely enough, not in visual mode - `$` includes the newline when used in visual mode. Try `d$` and `vd$` in (neo)vim and you'll see what I mean.
