### ISSUE TITLE
Changing prefix in easy-motion

### ISSUE THREAD

**Issue by CagriUysal** [VSCodeVim/Vim#4218]
Is there a way to use easy-motion with slightly altered prefix.
For example, instead of using below: 

` <leader><leader> s <char>`

I want to use,

`<leader> s <char>`

**Comment by turara** [comment]
I posted the setting in #4239.

**Comment by CagriUysal** [comment]
Thank you for solution.
But one unintended problem is, it interferes with all <leader> involved operations in vim.
For example: after setting your solution, I can't use <leader> <space> to unhighlight  search result.
What I want is to only map what I ask in the issue, but I guess there is no possible solution at the moment.

**Comment by turara** [comment]
Do you bind "leader [some key]" to ":nohl" command?
If what you want to do is to reduce one "leader" typing for all easymotion commands with one setting parameter or binding, I don't see any workrounds. But for specific commands, I think you can bind as follows:

```
"vim.normalModeKeyBindingsNonRecursive": [
  {
    "before": [ "leader", "s" ],
    "after": [ "leader", "leader", "s" ],
  }
]
```

**Comment by J-Fields** [comment]
@CagriUysal Has your issue been addressed?

**Comment by CagriUysal** [comment]
Yes, it have been.
