### ISSUE TITLE
Version 1.11.3 not work.

### ISSUE THREAD

**Issue by okamototomoyuki1988** [VSCodeVim/Vim#4220]
**Describe the bug**
After updating to version 1.11.3, the key change is not done.
It worked after reverting to version 1.11.2.
Also, after updating to version 1.11.3, it didn't work.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.11.3
- VSCode version:1.39.2
- OS:Windows 10 Pro x64 1903

**Comment by J-Fields** [comment]
> the key change is not done

Are you referring to a remapping or the extension generally?

**Comment by okamototomoyuki1988** [comment]
I'm sorry.
I started VSCode now and it worked.
It may be cured after rebooting the PC, but it is unknown why the plug-in did not work.
