### ISSUE TITLE
Expanding the snippet with multicursor is broken

### ISSUE THREAD

**Issue by ganow** [VSCodeVim/Vim#4223]
**Describe the bug**
I am using the VSCodeVim/Vim plugin with the C/C++ plugin by Microsoft. When I enter `for<tab>`, the plugin expands the for-loop snippet. The behavior of modifying the iterating variable for this snippet seems to be broken. When I type `j` to replace `i`, the iterating variable becomes `ij` instead of `j`. I also could not delete the text properly.

<a href="https://gyazo.com/15c3958ac18f74e195c987849d7ceada"><img src="https://i.gyazo.com/15c3958ac18f74e195c987849d7ceada.gif" alt="Image from Gyazo" width="884"/></a>

**To Reproduce**
1. Install the C/C++ plugin by Microsoft
2. Open a new C++ file
3. Type `for<tab>`
4. Type `<tab>` to select the iteration variable `i`
5. Try to modify the variable

**Expected behavior**
As I mentioned in the **Describe the bug** section.
Also, I verified that this behavior did not happen when I disable the Vim plugin.

**Screenshots**
As I mentioned in the **Describe the bug** section.

**Environment (please complete the following information):**
- VSCode (v.1.39.2)
- Vim plugin (v1.11.3)
- C/C++ plugin by Microsoft (v0.26.0)
- OS: macOS Mojave (v10.14.6)

**Additional context**
None.

**Comment by nerdmax** [comment]
+1

**Comment by listenerri** [comment]
+1

**Comment by cvaldev** [comment]
This behaviour happens on any snippet that uses multicursor, I don't believe it is linked to a particular language as I'm able to recreate it on pretty much every language I tried and even on my own custom global snippets.
