### ISSUE TITLE
VSCodeVim stopped working with 1.11.3

### ISSUE THREAD

**Issue by rdepke** [VSCodeVim/Vim#4225]
**Describe the bug**
The plugin is not active at all, after the update.

**To Reproduce**

1.  Use VSCode 1.39.2
2.  Update VSCodeVim plugin to 1.11.3
3.  Reload VSCode
4.  Plugin is not working anymore

**Expected behavior**
Plugin should work as before.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.3
- VSCode version: 1.39.2
- OS: Windows 10 1803

**Additional context**

**Comment by J-Fields** [comment]
Please restart your computer and uninstall/reinstall the extension and confirm that it's still an issue.

**Comment by rdepke** [comment]
Restarting the computer after upgrading the plugin fixed the issue. This never happend before, is there a known cause?

**Comment by J-Fields** [comment]
It seems to happen to a few people each release, I'm not sure why.
