### ISSUE TITLE
`editor.cursorSurroundingLines` cause text selection after clicking

### ISSUE THREAD

**Issue by ivanddm** [VSCodeVim/Vim#4233]
**Describe the bug**
I have been using the `editor.cursorSurroundingLines = 15` setting as I'm really used to a typewrite mode since I started using Vim.

When in `normal` or `insert` mode, if I click anywhere above or below the middle editor line, it will position the cursor where I click (as expected), however it will recenter the screen to the new cursor position (which is still fine) and will **select** (as in `visual` mode) everything in between the initial and new cursor positions. This is quite an annoying behavior as it makes me press `Esc` in order to deselect the text, every time I used the mouse to position my cursor.

**To Reproduce**

1.  Add to your settings `editor.cursorSurroundingLines = 15`
2.  Click anywhere on the editor above or below the middle line of the editor area
4.  See the error, which is a big chunk of text being selected.

**Expected behavior**
If I disable this extension, then clicking anywhere in the editor area, will not cause to recenter the screen to the new cursor position, and most importantly, it will not select any text.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.3
- VSCode version: 1.39.2
- OS: MacOS Mojave

**Comment by J-Fields** [comment]
Yeah, this is extremely annoying. I use `editor.cursorSurroundingLines = 5` to avoid this happening constantly, though I'd like to use 10 or 15. No totally sure why this is happening only when VSCodeVim is enabled, or if there's anything we can do about it.

**Comment by J-Fields** [comment]
This was fixed a while back
