### ISSUE TITLE
ctrl+b in insert mode should toggle sidebar

### ISSUE THREAD

**Issue by MaxTan** [VSCodeVim/Vim#424]
vscode shortcuts is not working after update

* VSCode Version:1.3.0
* VsCodeVim Version: 0.1.1
* OS: Windows 10 Professional

**Comment by ericmdantas** [comment]
Same here, both Windows 10 and 7.

**Comment by jpoon** [comment]
This seems similar to this discussion: https://github.com/VSCodeVim/Vim/issues/416

What do you expect to happen when you use `ctrl+f` and `ctrl+b`?

We've overridden these shortcuts to map them to the Vim way of doing things which is `ctrl+f` = downward scroll and `ctrl+b` = scroll upward

**Comment by ericmdantas** [comment]
Seems reasonable.

But the problem, at least for me, is that it doesn't work even when on "Insert mode". 

And one of the downfalls of using "/" instead of "ctrl + f", please correct me if I'm wrong, is that I don't get to search fo the next/previous elements using "n/N".

**Comment by johnfn** [comment]
Of course you can use n/N. What kind of Vim extension would this be without them?!? 😀

**Comment by ericmdantas** [comment]
Well, doesn't work for me :cry:

**Comment by johnfn** [comment]
What are your keystrokes?

`/abc<enter>nnn` works fine over here.

**Comment by ericmdantas** [comment]
Oh well, probably I've been forgetting about "enter" this whole time :confused: :laughing:

**Comment by johnfn** [comment]
😉 no worries!

**Comment by ericmdantas** [comment]
So, for me, only the "ctrl + b" is a bit annoying after the update.

**Comment by johnfn** [comment]
What are you expecting when you press ctrl+b? In which mode?

**Comment by ericmdantas** [comment]
I'm expecting that, when in "insert mode", the side bar toggles.

**Comment by johnfn** [comment]
Yeah, that sounds valid as it's not an insert mode binding! On the TODO list. :)

**Comment by johnfn** [comment]
Done!

**Comment by johnfn** [comment]
Good news for you guys, @MaxTan, @ericmdantas and anyone else - I've decided to disable ctrl+f by default, and enable it with a setting you can set in settings.json. Search away! (though really you should use `/` 😉 😉 )
