### ISSUE TITLE
cannot quit visual mode 

### ISSUE THREAD

**Issue by ps1118** [VSCodeVim/Vim#425]
VSCode Version:1.3.0
VsCodeVim Version: 0.1.1
OS: Windows 10 Professional

When I am in the visual mode, using j to move to choose 100 lines, then press y, and then press p in the proper position. In this way, pressing 'esc' cannot quit the visual mode.

Please help me.

**Comment by johnfn** [comment]
So the keys you are pressing are:

`v100jyp<esc>`?

If so, you already exited Visual Mode when you pressed `p`! No need to press `<esc>`. 😉

**Comment by ps1118** [comment]
Thank you.
