### ISSUE TITLE
Switching to command mode and back while typing

### ISSUE THREAD

**Issue by sevenmaxis** [VSCodeVim/Vim#4251]
![vim](https://user-images.githubusercontent.com/293438/68406593-c32f6800-018a-11ea-97a6-359a563d94c6.gif)

**Comment by belkka** [comment]
This is expected behavior in vim if you type <kbd>w</kbd><kbd>r</kbd><kbd>Esc</kbd><kbd>i</kbd><kbd>o</kbd><kbd>n</kbd>

**Comment by sevenmaxis** [comment]
> This is expected behavior in vim if you type wrEscion in insert mode

I don't type Esc key

**Comment by J-Fields** [comment]
@sevenmaxis Can you give the exact key sequence you're typing? Also, is this consistently reproducible or is it sporadic?

**Comment by sevenmaxis** [comment]
@J-Fields Hi,
There's no exact sequence I can notice, it happened sporadically.

**Comment by J-Fields** [comment]
@sevenmaxis Can you still reproduce?

**Comment by sevenmaxis** [comment]
after updates, I don't notice such problem anymore
