### ISSUE TITLE
easymotion letter selection are out of bound from the square box

### ISSUE THREAD

**Issue by gozes** [VSCodeVim/Vim#4252]
**Describe the bug**
vscode version: 1.39.0
pluging version: 1.11.3
theme: material theme
OS: MacOSX Mojave 10.14.6 

**To Reproduce**
launch esaymotion with any character selected  

**Expected behavior**
letter selection to be in the square box

**Screenshots**
![image](https://user-images.githubusercontent.com/632922/68412873-fec73380-0184-11ea-81aa-0475e8d812f5.png)

**Comment by J-Fields** [comment]
Have you tried using a monospace font?
