### ISSUE TITLE
VSCodeVim uses the default node debugging port

### ISSUE THREAD

**Issue by kapr1k0rn** [VSCodeVim/Vim#4264]
Not sure if this is a bug or intended, VSCodeVim uses port 9229, which is the default port for node app debugging. When debug a nestjs app with "nest start --debug --watch", I get the error "Starting inspector on 127.0.0.1:9229 failed: address already in use". Using "nest start --debug 9230 --watch", the error is gone.

**Comment by J-Fields** [comment]
Thanks for bringing this up, @kapr1k0rn. Is it recommended to use a different port?

cc @jpoon

**Comment by jpoon** [comment]
Vscodevim does not bind to a port. When you debug the extension vscode uses 9229 https://code.visualstudio.com/docs/nodejs/nodejs-debugging. See instructions from that link of how to change.

**Comment by kapr1k0rn** [comment]
> 
> 
> Vscodevim does not bind to a port. When you debug the extension vscode uses 9229 https://code.visualstudio.com/docs/nodejs/nodejs-debugging. See instructions from that link of how to change.

Sorry I did not describe the issue very clearly. 
1. When I start vscode with vscodevim enabled, I can not debug nodejs on port 9229. I am using nestjs, which gives a cli "nest start --debug --watch" for debugging, and I get the error "Starting inspector on 127.0.0.1:9229 failed: address already in use". I can see a vscode process using port 9229 in TCPView.
"nest start --debug 9230 --watch" works fine, which use port 9230 instead of 9229 for debugging.

2. When I start vscode with vscodevim disabled, there is no vscode process using port 9229 in TCPView, and "nest start --debug --watch" works fine.

I am using Windows 10 insider preview 1903, and vscode remote for wsl.
