### ISSUE TITLE
Searching backwards with offset is unaware of current word under cursor

### ISSUE THREAD

**Issue by spoike** [VSCodeVim/Vim#4266]
**Describe the bug**
Apparently searching backwards using an offset doesn't seem to take in account for the current search result under the cursor.

**To Reproduce**

1.  Search for a recurring word and use offset `e`. E.g. `/word/e`
2.  The cursor should now be at the end of the next result
3.  Repeat search backwards with `N`
4.  The cursor is still on the current result

**Expected behavior**
The cursor should go to the previous result with the cursor at the end of it

**Screenshots**
N/A

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.3
- VSCode version: 1.40.0
- OS: MacOS Mojave 10.14.6

**Additional context**
Doing the same steps in vim8 will move the cursor to the end of the previous result.

**Comment by J-Fields** [comment]
I'm assigning this to myself since I implemented the original feature and so I remember to actually fix this. If someone wants to give it a go before I get around to it, just give me a heads up.

**Comment by bdomanski** [comment]
Hi, me and @micklett are working on an open source project for one of our classes and would like to take a look at this! We would hope to have a pull request in the next week.

**Comment by J-Fields** [comment]
@bdomanski Amazing! I'll assign this issue to you - feel free to bug me if you've got questions about the code base.

**Comment by J-Fields** [comment]
Fixed by #4294
