### ISSUE TITLE
Constant inserting should be merged into one single Insert Operation in history

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#427]
### Issue Summary

When we enter Insert Mode and start typing, each character will be marked a single insert operation and saved in history tracker. Then if we do `undo`, these inserting operations will be reverted one by one. This is not how Vim does

### Steps to Reproduce

1. Open a file
2. Press `a` to enter Insert Mode
3. Type `abcdefhjkkl` then press `esc` and `u`

![undo](https://cloud.githubusercontent.com/assets/876920/16752975/6cda322a-4818-11e6-9195-660065594290.gif)

These characters should be removed immediately together instead of one by one.

### Technical details:

* VSCode Version: Insider 1.4.0
* VsCodeVim Version: Latest
* OS:  OSX

**Comment by johnfn** [comment]
Oh, I know all about this. I tried for a long time to get it right. I stopped because it's very difficult to do with 100% accuracy. Feel free to try to do it if you want; I'm hoping for a VSCode history API.
