### ISSUE TITLE
simple BaseMovement.execActionWithCount for command `d2i{` not working properly

### ISSUE THREAD

**Issue by hao-flexport** [VSCodeVim/Vim#4275]
**Describe the bug**
`BaseMovement.execActionWithCount` is used to do repeating actions for the canonical form: 
`action` - `count` - `modifier` - `boundary` (`action` and `count` can be switched)
`v`|`d`|`c` - ` `|`1`|`2`|`3`|... - `a`|`i` - `(`|`{`|`[`|`<`|...

It is working for modifiers `a`,
```
d2a{
c3a(
2da{
3ca(
```
but for `i` modifier with `count > 1`, it is not working.
```
d3i{ // simple the same as di{, with `count` not working
3di{
```

**To Reproduce**
The reason is the dilemma, the `d3i{` does not simply equal to `di{` by 3 times, for example:
```
{
  {
    {
      | <-- cursor here
    }
  }
}
```
After any times of `di{`, the cursor is still there.

**Expected behavior**
N/A.

**Screenshots**
N/A.

**Environment (please complete the following information):**
No matter.

**Additional context**
When `BaseMovement.execActionWithCount` is repeating invoking `MoveInsideCharacter.execAction`, extra context like `currentIndex` of `count` can be passed in for improving `Range` computation.

I am interested in fixing this issue, but don't know whether this could be the best practice. I will submit my PR for your suggestions.

**Comment by hao-flexport** [comment]
And I think `lastIteration` is for it, is it true?
https://github.com/VSCodeVim/Vim/blob/38c268a26dadbd0fed1ea297923e7640f358097c/src/actions/baseMotion.ts#L124
https://github.com/VSCodeVim/Vim/blob/38c268a26dadbd0fed1ea297923e7640f358097c/src/actions/baseMotion.ts#L163

**Comment by hao-flexport** [comment]
Both `MoveInsideCharacter` and `MoveTagMatch` have this issue.

**Comment by hao-flexport** [comment]
@J-Fields Anyone would respond to my PR? Need your help. Thanks!

**Comment by hao-flexport** [comment]
I think the PR has fixed this issue. Could anyone take a look and merge? @tail @LeonB @mikew @positron

**Comment by Xadoy** [comment]
> I think the PR has fixed this issue. Could anyone take a look and merge? @tail @LeonB @mikew @positron
I don't think your PR fixed the root cause. It looks like a work around for this specific case. If you try "v" to enter visual mode, then do "i{" twice. Which should work like "v" then "2i{", but by just reading your code I think your code only fix for the second case not the first one.
