### ISSUE TITLE
When write c/c++ code use the 'snippets'，tab switch the key words，backspace is not doing well with the Multi-cursor.But when i disable Vim emulation, it work fine.

### ISSUE THREAD

**Issue by cuiweiming** [VSCodeVim/Vim#4281]
**Describe the bug**

**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by cvaldev** [comment]
I think this is related to #4223, the behaviour can be reproduced using any snippet that uses multicursor regardless of language.
