### ISSUE TITLE
TaskQueue error when opening VimRemap...

### ISSUE THREAD

**Issue by Dimfred** [VSCodeVim/Vim#4284]
**Describe the bug**
When I try to open the `Vim: Remap any keycombination that VSCode supports...` menu entry, I get the error: `TaskQueue: Error running task. Cannot read property of 'after' of undefined`. 

**To Reproduce**

1.  Open navigation menu ( default CTRL+SHIFT+P )
2.  `Vim: Remap any keycombination that VSCode supports...`
3.  See error

**Expected behavior**
No error. Probably see the menu.

**Environment (please complete the following information):**
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.11.3`
- OS Version: `Linux x64 4.15.0-69-generic`
- VSCode version: `1.41.0-insider`

**Comment by J-Fields** [comment]
Labeling this as `user-error` is probably a bit too harsh, as this is very unclear, but this command isn't meant to be run directly. In the upcoming version, it's no longer available from the command palette.
