### ISSUE TITLE
'*' and '#' should search whole word

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#429]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### Issue Summary

`*` and `#` not searching whole word

### Steps to Reproduce

text as below

```
abc abcd abcde
```

1. `*` on `abc`
2. `n` will match `abc` in `abcd` and `abcde`

### Technical details:

* VSCode Version: 1.3.0
* VsCodeVim Version: 0.1.1
* OS: windows 10

**Comment by johnfn** [comment]
Totally true. I was holding off on doing this until we could handle word delimiters in `/` and `?`.

**Comment by octref** [comment]
@johnfn 
Hi Grant I'm interested in taking a shot at this. Do you mind elaborating on "handle word delimiters in / and ?" I can also try fixing that if it's not too complicated.

**Comment by johnfn** [comment]
@octref awesome! absolutely! 

In Vim, when you're searching with / or ?, you can actually use certain special delimiters to indicate you want to match a full word. For instance, /\&lt;foo\&gt; matches only the entire word foo, not foobar or barfoo. 

If you use * and # in vim you can tell this is how they work under the hood.

So I would suggest to implement that for / and ?, then rewrite * and # to use / and ? rather than reimplement them.

**Comment by jpoon** [comment]
Also, to take on another issue with our current implementation.

```
   |          "package": hello, world
```
where | represents where the cursor is.

Expected: / or ? of `<package>`
Actual: Does nothing

**Comment by octref** [comment]
@johnfn 

Sorry for not responding for so long...

If you do `:h pattern-multi-items` and `:h pattern-atoms`, there is a whole slew of patterns. I feel it would be weird to implement some of them but not all. And implementing them all is no small task.

Personally, I mostly use `/` without any patterns, and some * and # sparingly.
A search on issues also yield no one asking for special patterns.

Maybe we should guide people to use VSCode's built-in Find by Regex, which is also standard Regex, not like Vim's special flavor.

**Comment by johnfn** [comment]
This was actually finished a while back! :)
