### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by zsirfs** [VSCodeVim/Vim#4292]
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.11.3`
- OS Version: `Darwin x64 19.0.0`
- VSCode version: `1.40.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 806,
		"activateCallTime": 14,
		"activateResolvedTime": 3257,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscodevim.vim",
				"_lower": "vscodevim.vim"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

**Comment by J-Fields** [comment]
Not enough info here to go on, and it's an old issue, so I'm closing. Performance has improved quite a bit since this was filed, let me know if you still have issues.
