### ISSUE TITLE
zz doesn't maintain horizontal cursor position

### ISSUE THREAD

**Issue by schu34** [VSCodeVim/Vim#4296]
**Describe the bug**
in actual vim, the `zz` command maintains the cursor's horizontal position, even if it's past te end of the current line. but in vscode vim it gets reset when the cursor position is past the end of the current line

**To Reproduce**

1. initial state
```
this is a very long line of text
                               ^-cursor is here
this one is shorter
```
2. I press `j`, now
```
this is a very long line of text
                               
this one is shorter
                  ^-cursor is here
```
3. I press `zz`, nothing changes visibly in this example
4. I press `k`, now 

```
this is a very long line of text
                  ^-cursor is here                             
this one is shorter
```

**Expected behavior**
```
this is a very long line of text
                               ^-cursor should be here
this one is shorter
```

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.11.3`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.39.1`

**Additional context**
happy to work on this as long as everyone can agree its a bug :)

**Comment by J-Fields** [comment]
Can confirm this is a bug. We store the column that the cursor "wants" to go to (the last one, in this case) as `vimState.desiredColumn`. Not sure where that's getting changed.
