### ISSUE TITLE
Reflow (gq) treats line strangely

### ISSUE THREAD

**Issue by jrwrigh** [VSCodeVim/Vim#4303]
**Describe the bug**
When reflowing a line, instead of only moving text to a new line when necessary, it decides to move a large chunk to a new line, leaving the previous lines mostly sparse:

![VSCodeVim_gq](https://user-images.githubusercontent.com/20801821/69690649-c206a200-1089-11ea-9889-644ee36eb081.gif)

**To Reproduce**
1. Type in:
```
For flows of engineering interest, dealing with turbulence and it's
subsequent effects on engineering quantities is of prime importance.
Reynolds-Averaged Navier-Stokes turbulence models are often used for their
cost efficiency. However, linear RANS models are often not accurate for
separated flows (which are of significant engineering interest) and
non-linear models are not very robust and don't offer significant increases
in accuracy over their linear counterparts. Thus, Scale Resolving Simulations (SRSs) are looked to as what is required for accurate simulation
```
2. Highlight last line
3. Reflow (press <kbd>g</kbd><kbd>q</kbd>)

**Expected behavior**
In this particular case, nothing should happen as there isn't a way to rearrange the line in a better way.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.3
- VSCode version: 1.40.2
- OS: Windows 10

**Additional context**
This was in a LaTeX document with the LaTeX workshop extension running.

**Comment by jrwrigh** [comment]
The reflow actually worked correctly, however the width of my window was *just* off enough to make it seem like it could handle the full width.

Solution: Increase the window size.

**Comment by dossy** [comment]
@jrwrigh sorry for this OT question, but what did you use to create that animated GIF with the keystroke annotations?

**Comment by jrwrigh** [comment]
If I remember correctly, it was ScreenToGif
https://www.screentogif.com/

**Comment by dossy** [comment]
Ah, dang, Windows-only.  But, thank you!
