### ISSUE TITLE
Leading 0 Confuses <C-a>/<C-x>

### ISSUE THREAD

**Issue by HawkinsT** [VSCodeVim/Vim#4308]
**Describe the bug**
When trying to increment/decrement a number such as '00' or '000' or '0999' with a leading zero, the increment and decrement functions get confused and do not work as they should (and do in vim proper).

**To Reproduce**

1.  Type '07' in a document
2.  When in normal mode with '0' highlighted hit \<C-a\>
3.  The number should change to 010
4.  Hit 'u' to undo, so the number now reads '07' again
5.  Hit \<C-a\> again
6.  The number should now read '8'
7. Hit 'u' again and return to step 2 (ad infinitum)

Performing these steps again with the '7' highlighted will results in '010' and '08' alternately (for each time you do this). Furthermore, when seemingly counting in octal, it 'sort of' reverts to decimal mid-count with the pattern: 07 > 010 > 011 > 012 > 013 > 014 > 015 > 016 > 017 > 018 > 019 > 0110 > 0111 > ... > 0111110  etc.

**Expected behavior**
In vim, depending on whether 'oct' is included in 'nrformats', this should either lead to the number being incremented/decremented in octal (retaining one leading 0), or, as the default setting, the number should be incremented/decremented in decimal consistently, including the leading 0 (so the pattern goes 09 > 10 > ... > 100 etc.)

**Environment (please complete the following information):**

* VSCode version: `1.40.2`
* OS: `Windows_NT x64 10.0.18362.476 (Win 10 Pro)`

**Comment by J-Fields** [comment]
I'm pretty sure this is a duplicate, but I can't find the other issue right now. I've got a refactor of `<C-a>` in progress at https://github.com/VSCodeVim/Vim/pull/4122, once I get back to that I'll try to investigate this as well.

**Comment by HawkinsT** [comment]
Thanks, Jason. I did have a search for this issue but couldn't find it either.
