### ISSUE TITLE
Scrolling with <C-e> and <C-y> is very laggy

### ISSUE THREAD

**Issue by raiskila** [VSCodeVim/Vim#4309]
**Describe the bug**
When holding down (or quickly tapping) &lt;C-e&gt; or &lt;C-y&gt;, scrolling soon becomes very laggy and the editor only scrolls at a rate of about two lines per second. The keystrokes get queued up and after letting go of the keys the editor continues to scroll slowly and try to catch up.

&lt;C-u&gt; and &lt;C-d&gt; don't suffer from this problem. I noticed in the source that they don't use `vimState.postponedCodeViewChanges.push()` and instead call `vscode.commands.executeCommand()` directly. Maybe this has something to do with it?

Similar to #1943 and #1985

**To Reproduce**

1. Using the latest stable (or insider) version of VS Code on Mac, run `/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code --user-data-dir /tmp/something`.
2. Ensure only the latest VS Code Vim extension is installed.
3. Open a file and try &lt;C-e&gt; or &lt;C-y&gt;

**Expected behavior**
Performant scrolling

**Screenshots**
<img width="1611" alt="Screen Shot 2019-11-30 at 3 35 04 PM copy" src="https://user-images.githubusercontent.com/351598/69901394-a94c0400-1389-11ea-93b6-27a4a3a77915.png">

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.11.3
- VSCode version: 1.40.2 (or 1.41.0-insider)
- OS: macOS Catalina 10.15.1 (19B88)

**Comment by raiskila** [comment]
FYI: I fixed this for myself [like this](https://github.com/raiskila/VSCodeVim/commit/6281ad4920b7d4e36899abdaedd24e21915a52b5), however I don't know the ramifications of that change.

**Comment by J-Fields** [comment]
I hadn't noticed this before, but you're absolutely right. @raiskila would you mind submitting a PR? I'll need to dig into the code to see whether calling `editorScroll` immediately would cause issues, but it's at least a start. I really appreciate you investigating!

**Comment by raiskila** [comment]
I am now getting a problem with my "fix" where if the cursor is at the bottom of the screen, moving up with &lt;C-y&gt; doesn't work anymore. It seems like that may not be the correct way to fix the issue. Would you like me to create a PR anyway?

**Comment by J-Fields** [comment]
Yup, just mark it as "WIP" please. Thanks!

**Comment by sqlkoala** [comment]
For your info, maybe this helps:
I think problem emerged going from version 1.10.2 to 1.11.3. I use 1.10 (without this problem) and when I try 1.11 in another vscode then I notice the problem there, too.

**Comment by listenerri** [comment]
No progress?

**Comment by J-Fields** [comment]
This is fixed in master, will be in a release soon.
