### ISSUE TITLE
Mapping g to G not working when prefixed with line number

### ISSUE THREAD

**Issue by HiloCoder** [VSCodeVim/Vim#4318]
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["g"],
      "after": ["G"]
    }
}

The above mapping works when just hitting 'g' to move to the end of file.  However, when prefixing it with a line number, it still moves to end of file.   e.g.  '1g' should move to line 1 of the file

**Expected behavior**
Entering a line number followed by 'g' should move to that line number.

**Screenshots**
(console log when pressing 'g', works as expected)
console.ts:137 [Extension Host] ModeHandler: debug: handling key=g.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=g. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:137 [Extension Host] ModeHandler: debug: handling key=G.

(console log when pressing '1g', does not work as expected)
console.ts:137 [Extension Host] ModeHandler: debug: handling key=1.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=1. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:137 [Extension Host] ModeHandler: debug: handling key=g.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=1,g. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:137 [Extension Host] ModeHandler: debug: handling key=G.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.11.3
- VSCode version: 1.40.2
- OS:  Windows 10 Home

**Comment by HiloCoder** [comment]
The problem is in remapper.ts, lines 147 - 153.

 if (remapping.after) {
       const count = vimState.recordedState.count || 1;
       vimState.recordedState.count = 0;
       for (let i = 0; i < count; i++) {
      await modeHandler.handleMultipleKeyEvents(remapping.after);
       }
    }

When this is rewritten as below, things work as expected:

 if (remapping.after)
   await modeHandler.handleMultipleKeyEvents(remapping.after);

**Comment by BrianMWest** [comment]
I am experiencing this problem whenever there is a "0" in the line number. Typing "123G" takes me to line 123, but typing "120G" takes me to the beginning of the line when "0" is pressed (it appears to override the command and take precedence) and then move to the end of the file when "G" is typed. The same behavior happens when I type "102G", except that it takes me to line 2.

**Comment by J-Fields** [comment]
This has worked for a while now
