### ISSUE TITLE
Remove "Supported Keyboards" and respective IKeyMapper-implementations

### ISSUE THREAD

**Issue by AntonAderum** [VSCodeVim/Vim#432]
The IKeyMapper implementations was needed because vscode could not map non-US keyboard to the extensions keymapping. However this seems to no longer be the case.

I tried it out this morning and when i was running the sv-SE keymapper configuration all the mappings were wrong. (I know this isnt listed as supported in your README, but i was the one who did the sv-SE mapping and it did work before). When I debugged it, it turned out that when I for example pressed ">" it not longer sent "shift+oem_102" to the keymapper, but instead sent the correct character ">". 

When i tried running without "vim.keyboardLayout" set, it mapped all my keys correctly, even though I am on a swedish keyboard layout.

So it seems that vscode has been fixed to correctly map keys pressed on the keyboard to the correct key in vscode, thus making the custom IKeyMapper implementation both obselete and plain wrong since they now map things incorrectly. It's also confusing for new users that think that they need to use the Supported Keyboards.

* VSCode Version: 1.3.0
* VsCodeVim Version: 0.1.1
* OS: Windows 10

**Comment by johnfn** [comment]
@jpoon do you know more about this than me?

**Comment by jpoon** [comment]
Ooh, sweet. Going through the VSCode history, it seems like handling of international keyboards was greatly improved in January (https://github.com/Microsoft/vscode/issues/713) and they are using this internally to map the international keys: https://github.com/Microsoft/node-native-keymap.

Before we remove all the work we did to support these keyboards, we'll obviously need to do a bit more testing to make sure we don't break anything/anybody.

**Comment by AntonAderum** [comment]
Great. I can at least confirm that it works perfectly on Swedish (QWERTY) keyboard using no custom IKeyMapper-implementation.

**Comment by jpoon** [comment]
I unfortunately don't have an international keyboard to test, but just removed it -- hopefully didn't break anybody.
