### ISSUE TITLE
Not able to use "j" motion when Cursor Smooth Caret Animation set 

### ISSUE THREAD

**Issue by aneeskodappana** [VSCodeVim/Vim#4321]
**Describe the bug**
Not able to use "j" motion when Cursor Smooth Caret Animation set.
After enabling Cursor Smooth Caret Animation 'j' motion behave strangely. 

**To Reproduce**

1. Goto settings and enable Cursor Smooth Caret Animation 
2. Use a motion for example 'j'

**Expected behavior**
Normal h, j, k, l motion

**Environment**
VSCode 1.40.2
Vim 1.11.3

**Comment by J-Fields** [comment]
Could you elaborate? It seems to work fine to me.

**Comment by aneeskodappana** [comment]
Actually it happened when the first time I set the option. but currently, I am not able to reproduce it. sorry for the issue.
