### ISSUE TITLE
Implement ={motion} operator

### ISSUE THREAD

**Issue by MaG21** [VSCodeVim/Vim#4328]
In vim we have the `={motion}` operator, which basically auto indent (by default) `{motion}` lines.

A common action for some vim users is: to remove a line, paste it elsewhere and auto indent the newly added line ( `dd`, `p`, `==` )

Currently I'm unable to use this and instead I have to match current indentation using `>>` or `<<`.

**Comment by J-Fields** [comment]
This should work? What language/formatter do you have configured? Some which only work on whole files won't work with `=`.

**Comment by MaG21** [comment]
Looking at it closer, it does work on `.js` files, but it doesn't in `.vue` files (nor does it work inside `<script>` tag)

It doesn't seems to work on HTML files either, maybe my setup doesn't have a html formatter installed ?

**Comment by J-Fields** [comment]
Does the `Format Document` command work when run from the command palette?

**Comment by J-Fields** [comment]
https://github.com/VSCodeVim/Vim/blob/28c000ecf3ab0ab26af875ac0050dc4335c35a68/src/actions/operator.ts#L367

**Comment by MaG21** [comment]
> Does the `Format Document` command work when run from the command palette?

It does.

**Comment by J-Fields** [comment]
Actually, we use `Format Selection` - does that work?

**Comment by MaG21** [comment]
`Format Selection` throws: No commands matching.

Looking at VS Code doc, should `Format Selection` always be present?.  [Formatting](https://code.visualstudio.com/docs/editor/codebasics#_formatting)

Why is that possible? Should `VSCodeVim` test for existence of `Format Selection`?

**Comment by J-Fields** [comment]
Hmm, yeah we probably should make sure the command is available. I think it won't be available if a formatter isn't configured or the formatter that is configured doesn't support partial formatting.

**Comment by MaG21** [comment]
What if VSCodeVim configure its own formatter at installation time ? (provided there isn't a formatter already configured)

**Comment by J-Fields** [comment]
> What if VSCodeVim configure its own formatter at installation time ? (provided there isn't a formatter already configured)

This *really* doesn't seem like the responsibility of a vim-emulation plugin. Probably, we should fall back on `Reindent selected lines` if there's no formatter.

**Comment by MaG21** [comment]
> This really doesn't seem like the responsibility of a vim-emulation plugin

Makes sense, but I'm not so sure, it seems like something such a plugin must have in order to maintain the expected behavior. There's a trade-off here, maintaining single responsibility vs user experience. Being honest, people expect things to _just-work (tm)_.
