### ISSUE TITLE
Cannot type 'fd' in edit mode

### ISSUE THREAD

**Issue by willtalmadge** [VSCodeVim/Vim#4333]
**Describe the bug**
In edit mode I cannot type 'fd', upon typing d, the 'fd' is deleted.

**To Reproduce**
Create a new document
Enter edit mode
Type 'fd'
The document is still empty

**Expected behavior**
Should see 'fd' in the new document

- Extension (VsCodeVim) version: 1.11.3
- VSCode version: 1.40.0
- OS: macOS 10.15

**Comment by MaG21** [comment]
By edit mode, do you mean Insert Mode?

<img width="1012" alt="Screen Shot 2019-12-06 at 1 04 01 PM" src="https://user-images.githubusercontent.com/1760771/70341279-fd8f3200-1828-11ea-8136-ce066c5c0d59.png">

**Comment by J-Fields** [comment]
Can you double check that you don't have any insert mode remappings?

**Comment by willtalmadge** [comment]
> By edit mode, do you mean Insert Mode?
> 
> <img alt="Screen Shot 2019-12-06 at 1 04 01 PM" width="1012" src="https://user-images.githubusercontent.com/1760771/70341279-fd8f3200-1828-11ea-8136-ce066c5c0d59.png">

Yes, I meant insert mode, my bad.

**Comment by willtalmadge** [comment]
I just realized what it is. I'm using these key bindings https://github.com/VSpaceCode/VSpaceCode 
Thanks for you time. Closing this.
