### ISSUE TITLE
CTRL-* commands for page scrolling are not working correctly in 1.11.3 (latest)

### ISSUE THREAD

**Issue by dfsbbl** [VSCodeVim/Vim#4338]
**Describe the bug**
`<C-F>`, `<C-B>`, `<C-D>`, and `<C-U>` are not working correctly in 1.11.3. The latest version that these scrolling commands are working (from my test) is 1.11.0. When I install the 1.11.0 version of VSCodeVim alone and keep other extensions as they are, the problem disappears, so it is unlikely to be related to other extensions.

**To Reproduce**

1.  Check if your VSCodeVim version is 1.11.3 (latest);
2.  Open any text file longer than one screen (for me, I use c++ source files);
3.  Try using any of the scrolling commands;
4.  The cursor and screen movements are wrong.

**Expected behavior**
The scrolling commands work as described by the Roadmap.

**Environment (please complete the following information):**

- Extension (VsCodeVim) Version: `1.11.3`
- OS Version: `Linux x64 5.0.0-37-generic`
- VSCode version: `1.40.2`

**Additional context**
Other enabled extensions:

Extension | Author (truncated) | Version
-- | -- | --
cpptools | ms- | 0.26.2
material-icon-theme | PKi | 3.9.2
rewrap | stk | 1.9.1
code-spell-checker | str | 1.7.20
vim | vsc | 1.11.0

**Comment by J-Fields** [comment]
Could you elaborate incorrect on the behavior you're seeing? I did re-implement these recently to fix some edge cases.

**Comment by dfsbbl** [comment]
Sorry, I'm busy recently... I tested these keys in the newest 1.12.2 version and they are working correctly now!! Thank you for your continuous update!
