### ISSUE TITLE
v1.12.0 stop working

### ISSUE THREAD

**Issue by waitingsong** [VSCodeVim/Vim#4344]
Issue Type: <b>Bug</b>

It seems vscode donot load the extension.
The older versions works fine.

Extension version: 1.11.3
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.95GB (56.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|80%|
</details>

**Comment by waitingsong** [comment]
VSCode version: 1.35.0,  1.40, 1.40.2

**Comment by Eyjafjallajokull** [comment]
Downgrade to 1.11.3 fixed this for me.

**Comment by wonter** [comment]
refer to https://github.com/VSCodeVim/Vim/issues/4340

**Comment by waitingsong** [comment]
> refer to #4340

Yeah. I close this one.

**Comment by rebornix** [comment]
There are still some issues ppl are seeing now, let's track it in https://github.com/VSCodeVim/Vim/issues/4342#issuecomment-563338094.

**Comment by waitingsong** [comment]
works with 1.12.2.
