### ISSUE TITLE
v1.12.0 does not load at all on Linux

### ISSUE THREAD

**Issue by sztomi** [VSCodeVim/Vim#4345]
**Describe the bug**
Basically the same as https://github.com/VSCodeVim/Vim/issues/3753 (only opening a new issue because that one is closed and unlikely to get attention). Downgrading to 1.11.3 works. I'm not sure if this is the case on other platforms.

**To Reproduce**

1. Start vscode
1. Vim mode doesn't load at all - no logs that I could find to indicate any error. For all intents and purposes it is the same behavior as if it's not installed at all.

**Expected behavior**
The extension should load and operate like before.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.12.0
- VSCode version: v1.40.2
- OS: Linux

**Comment by waitingsong** [comment]
https://github.com/VSCodeVim/Vim/issues/4340

**Comment by sztomi** [comment]
thanks @waitingsong , closing this one as it's a duplicate.
