### ISSUE TITLE
  no work

### ISSUE THREAD

**Issue by xtzt** [VSCodeVim/Vim#4346]
the vscodevim of version 1.12.0 is not working!

**Comment by samsiu** [comment]
#4340

**Comment by LebranceBW** [comment]
+1. the version **1.12.0** for me don't work either. Going back to **1.11.3** could repair it.

**Comment by galois-advertising** [comment]
me too

**Comment by victorvarenic** [comment]
+ 1

**Comment by Vinnl** [comment]
Duplicate of #4340. Please do not add "me too" comments there - click the "Thumbs up" on the original issue.

**Comment by armoucar** [comment]
> +1. the version **1.12.0** for me doesn't work either. Going back to **1.11.3** could repair it.

Does someone know how to rollback temporally while current version is broken?

**Comment by tcfunk** [comment]
@armoucar click the gear next to the Vim extension, and select "Install another version"

**Comment by anonoh** [comment]
@armoucar 

Go to extensions tab, right click the Vim plugin and select "Installl another version"

![image](https://user-images.githubusercontent.com/27064280/70438552-61666480-1a8e-11ea-957f-acab2575e650.png)

**Comment by jesHrz** [comment]
not working +1, and roll back...

**Comment by EdwinYoon** [comment]
It does not work for me either.
When I started the vscode, it did not even start the vim
so reinstall the extension after I removed the extension from vscode and as well as from the "$HOME/.vscode/extensions"   

Then It starts vim but the key mappings are mess

**Comment by dcolthorp** [comment]
It's not working for me and the rest of my team on macos, code 1.40.2. (vim 1.12.0)

**Comment by pvinis** [comment]
I think we can stop commenting here. If someone can, please close this issue.

Link to duplicate issue: https://github.com/VSCodeVim/Vim/issues/4340
Current workaround: Install version 1.11.3
Steps to execute workaround: https://github.com/VSCodeVim/Vim/issues/4346#issuecomment-563233380

**Comment by rebornix** [comment]
Fixed in 1.12.1, sorry for the trouble.

**Comment by rebornix** [comment]
There are still some issues ppl are seeing now, let's track it in https://github.com/VSCodeVim/Vim/issues/4342#issuecomment-563338094.
