### ISSUE TITLE
Change mode in version 1.12.0

### ISSUE THREAD

**Issue by unixuser** [VSCodeVim/Vim#4348]
The ability to use esc key or ctrl+c to get out of insert mode is not working in version 1.12.0
Also I'm not sure if version 1.12.0 is still in beta but it did auto update my VSCode today.

I will post additional info in case it is just my system

OS:
  Operating System: Ubuntu 19.10
  Kernel: Linux 5.3.0-24-generic
  Architecture: x86-64

VSCode:
  Version: 1.40.2
  Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
  Date: 2019-11-25T14:54:40.719Z
  Electron: 6.1.5
  Chrome: 76.0.3809.146
  Node.js: 12.4.0
  V8: 7.6.303.31-electron.0
  OS: Linux x64 5.3.0-24-generic snap

**Comment by jkornblum** [comment]
1.12.0 also has effectively broke VIM plugin.
I can't get out of insert mode using my keymap or esc.

I'm running on MacOS 10.15.1 and VSCode 1.40.2

**Comment by nickbrust** [comment]
> The ability to use esc key or ctrl+c to get out of insert mode is not working in version 1.12.0
> Also I'm not sure if version 1.12.0 is still in beta but it did auto update my VSCode today.
> 
> I will post additional info in case it is just my system
> 
> OS:
> Operating System: Ubuntu 19.10
> Kernel: Linux 5.3.0-24-generic
> Architecture: x86-64
> 
> VSCode:
> Version: 1.40.2
> Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
> Date: 2019-11-25T14:54:40.719Z
> Electron: 6.1.5
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Linux x64 5.3.0-24-generic snap

Seeing the same thing on Windows, unable to ESC insert mode.

OS: 
OS Name: Microsoft Windows 10 Enterprise
Version: 10.0.17134 Build 17134
System Type: x64-based PC

**Comment by aaf-ww** [comment]
same

**Comment by austindd** [comment]
I am having a similar issue this morning. My key-bindings to switch from InsertMode to NormalMode are:
- "j" + "k" -> "<Esc>"
- "k" + "j" -> "<Esc>"
- "J" + "K" -> "<Esc>"
- "K" + "J" -> "<Esc>"

None of these keybindings have any effect, leaving me unable to switch modes. I may have to switch to a different extension today just to stay reasonably productive.

**Comment by mpingram** [comment]
For anyone looking for a quick fix, I reverted to 1.11.3 using the `Install Another Version...` menu which is working fine.
<img width="342" alt="Screen Shot 2019-12-09 at 11 12 54 AM" src="https://user-images.githubusercontent.com/18353462/70457045-fd837200-1a74-11ea-947f-bf21dcedef75.png">

**Comment by aaf-ww** [comment]
not for me for SOME REASON 😊

**Comment by austindd** [comment]
@mpingram Your solution to roll back the version works for me. Thank you for the tip! Hopefully they will get this cleared up soon.

**Comment by aaf-ww** [comment]
i'll bet someone's guilt is killing them

**Comment by someotherkyle** [comment]
Same issue with Win10 here, temporarily fixed with rollback to 1.11.3

**Comment by admosity** [comment]
Works now after updating to 1.12.2

https://github.com/VSCodeVim/Vim/issues/4342#issuecomment-563349104

**Comment by rebornix** [comment]
Should be fixed now.

**Comment by aaf-ww** [comment]
> Should be fixed now.

thank you!

**Comment by kenkl** [comment]
> Should be fixed now.

Thank you!

**Comment by unixuser** [comment]
I did not expect the update to be so soon. Thanks. 1.12.2 has fixed my issues.
