### ISSUE TITLE
What "vim.otherModesKeyBindings" should be, object or array?

### ISSUE THREAD

**Issue by sumanx** [VSCodeVim/Vim#435]
In readme.md, it is:

```
 "vim.otherModesKeyBindings": [
       {
           "before": ["j", "j"],
           "after": ["<esc>"]
       }
  ]
```

But in default settings, it is:
```
    // Keybinding overrides to use for normal mode.
    "vim.otherModesKeyBindings": {},
```

What is the right way to add a custom rule?

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.1
* OS: Mac OS X 10.11.4

**Comment by johnfn** [comment]
Fixed by #434. Thanks to @sectioneight 😀
