### ISSUE TITLE
VSCodeVim doesn't recognize <Esc>/<CapsLock> swap

### ISSUE THREAD

**Issue by acugroup** [VSCodeVim/Vim#4350]
I'm using LinuxMint 19 Cinnamon, and swapped Esc key and CapsLock key. But VSCodeVim doesn't recognize this. So when I press CapsLock key, nothing happens (should go to normal mode as does in regular Vim). But when I press Esc key, it goes to normal mode AND turns on caps lock key at the same time.

**Comment by awilkins** [comment]
Change the VSCode `Keyboard: Dispatch` setting to `keyCode` instead of `code`.

**Comment by acugroup** [comment]
It work. Thanks a lot!
