### ISSUE TITLE
Undo After Replace Causes Error: "Cannot read property 'getTime' of undefined."

### ISSUE THREAD

**Issue by HawkinsT** [VSCodeVim/Vim#4351]
**Describe the bug**
When successfully performing a replace command via :s/blah/bleh, immediately undoing this replacement will cause the error 'TaskQueue: Error running task. Failed to handle key=u. Cannot read property 'getTime' of undefined.'

**To Reproduce**

1.  Type 'blah' in a document
2.  Type :s/blah/bleh to replace 'blah' with 'bleh'
3.  Hit 'u' (default key binding) to undo this replacement

The undo will work as expected, but the stated error will appear. Furthermore, ':' or '/' will have to then be hit twice to bring the command prompt back up. This seems to happen with or without neovim integration. Error does not occur if the replacement is undone after entering insert mode and then going back to normal mode.

**Expected behavior**
The error doesn't occur.

**Environment (please complete the following information):**

* VSCode version: `1.40.2`
* VSCodeVim version: `1.12.2`
* OS: `Windows_NT x64 10.0.18362.476 (Win 10 Pro)`

**Comment by niconiahi** [comment]
happening to me as well. Would loved to have it fixed as it is super annoying not to be able to undo changes. Thanks!!!

**Comment by fedesilvaponte** [comment]
This is still happening to me.

**Comment by counterbeing** [comment]
Experiencing the same error with some differing versions of software.

VSCode version: 1.41.1
VSCodeVim version: 1.12.2
OS: Mac OS 10.15.2

**Comment by changhz** [comment]
this annoying error has been torturing me 😭😭
