### ISSUE TITLE
dd does not copy the deleted line to current register

### ISSUE THREAD

**Issue by yujinyuz** [VSCodeVim/Vim#4352]
**Describe the bug**

I usually do <kbd>ddkP</kbd> to swap the current line to the above line but it seems to be not working anymore.

**To Reproduce**

1. Create words with 2 lines
2. Put the cursor on the 2nd line then execute <kbd>ddkP</kbd>

**Expected behavior**
<kbd>dd</kbd> should work like before

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.2
- VSCode version: 1.40.2
- OS: macOS

**Additional context**
It's working on the 1.11.3

**Comment by HawkinsT** [comment]
On Windows this appears to be working fine with 1.12.2.

**Comment by J-Fields** [comment]
I can't reproduce this on windows either

**Comment by leshow** [comment]
I'm on linux and it works fine also 1.12.2

**Comment by yujinyuz** [comment]
Seems to be working fine now
