### ISSUE TITLE
insert mode bindings interfere with each other

### ISSUE THREAD

**Issue by wcroughan** [VSCodeVim/Vim#4353]
**Describe the bug**
I have the following line in my .vimrc file:
imap qr <Esc>
Until recently this has consistently worked. If I typed "qr" in insert mode, the qr would be deleted and I would return to normal mode. Today, about 80% of the time this works, but around 20% of the time this doesn't work. When it doesn't work, it simply types qr and stays in insert mode as if the imap didn't exist.

If it doesn't work, deleting the qr and typing it again usually fixes it (but sometimes fails about 20% of the time, and so on recursively...).

**To Reproduce**
1. Add line "imap qr <Esc>" in .vimrc
2. Edit a file (I'm editing a .cpp file with ~1800 lines)
3. In insert mode, begin typing something and then type "qr"

**Expected behavior**
The imap should be respected, resulting in a return to normal mode as if Esc had been pressed.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.2
- VSCode version: 1.40.2
- OS: Arch Linux ("lsb_release" gives 1.4)

Other extensions:
Configuration Editing
Node Debug Auto-attach
Emmet
Extension Authoring
Git
JSON Language Features
Merge Conflict
NPM support for VS Code
TypeScript and JavaScript Language Features
C/C++

**Comment by J-Fields** [comment]
Does this work if you configure the keybinding via the VSCode settings file rather than a .vimrc?

**Comment by wcroughan** [comment]
Agh my apologies, I set this up a while ago. The way I've implemented this is actually through the settings.json (User) file. I've pasted the whole file below, the first vim.insertModeKeyBindings is the one that's relevant here. 

So to be clear the title is incorrect, this is actually a case of vim.insertModeKeyBindings not working intermittently.

```
{
	"vim.useSystemClipboard": true,
	"vim.hlsearch": true,
	"vim.insertModeKeyBindings": [
		{
			"before": ["q", "r"],
			"after": ["<Esc>"]
		},
		{
			"before": ["t", "h", "r", "u", "n"],
			"after": ["t", "h", "r", "o", "w", " ", "\"", "U", "n", "i", "m", "p", "l", "e", "m", "e", "n", "t", "e", "d", "\"", ";", " ", "/", "/", "T", "O", "D", "O", " ", "i", "m", "p", "l", "e", "m", "e", "n", "t", "q", "r", "=", "0"]
		}

	],
	"vim.normalModeKeyBindingsNonRecursive": [
		{
			"before": ["<Space>"],
			"commands": [":nohlsearch"]
		}
	],
	"vim.visualModeKeyBindingsNonRecursive": [
		{
			"before": ["/", "/"],
			"commands": ["y", "/", "\\", "V", "<C-R>", "\"", "<CR>"]
		}
	],
	"workbench.startupEditor": "newUntitledFile",
	"editor.detectIndentation": false,
	"files.exclude": {
		"**/build": true,
		"**/output": true
	},
    "C_Cpp.clang_format_path": "/usr/bin/clang-format",
    "editor.formatOnType": true,
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true
}
```

**Comment by J-Fields** [comment]
Thanks for clarifying. Was this working for you in 1.11.3 (the previous version)?

**Comment by wcroughan** [comment]
OK after some confusing minutes debugging, it seems the way I originally described the bug was accurate.

I've figured out I actually was both loading my vimrc file (with imap) and loading the above settings.json mappings. I tried removing each one and found that using just the imap from vimrc file has the issue mentioned above, but the keymap through settings.json seems to work fine.

I've updated the post title once again, as it seems the bug as I originally laid it out really exists. But moving the setting to settings.json is a fine workaround for me.

And yes, the way I had it configured worked as I intended in the previous version.

**Comment by wcroughan** [comment]
OK it turns out the bug is not random, but is a function of the other vim.insertModeKeyBindings entry! The two bindings I have in my settings.json are triggered by typing "qr" and "thrun". Whenever one of them is possibly in progress, the other will not trigger. For instance, if I type "tqr", the "qr" binding will not be triggered because I started part of the "thrun" binding. Similarly, "thrqr" won't trigger the qr binding, and "qthrun" won't trigger the thrun binding.

Note I spoke too soon in the above post. This bug exists regardless of how the qr mapping is defined. I deleted the qr mapipng from settings.json and added it to the imported vimrc and the same interaction occurs between the qr and thrun bindings.

Sorry this started quite unorganized, but on the bright side I now have a fully reproducible non-random bug (on my machine at least). Please let me know what the best way to organize this is (i.e. should I rename this thread? Close this one and start a new one? Edit my first post to include the information here?).

**Comment by J-Fields** [comment]
Nice, thanks for investigating! If you could just edit the title, that'd be awesome

**Comment by ericharding** [comment]
Just thought I'd stop by and confirm that I see the same behavior and provide a second repro in case it's useful.  (I also thought it was random at first).  My settings.json includes the following and in recent versions I can't use "jj" following a space.
```    
"vim.insertModeKeyBindings": [
        {
            "before": [ "j", "j" ],
            "after": [ "<Esc>" ]
        }
        ,
        {
            "before": [ "leader", ";" ],
            "after": [],
            "commands": [
                { "command": "editor.action.commentLine" }
            ]
        }
    ],
```
