### ISSUE TITLE
vim.cursorStylePerMode is being ignored

### ISSUE THREAD

**Issue by yujinyuz** [VSCodeVim/Vim#4355]
**Describe the bug**
In my settings.json I have these settings enabled:

```
"vim.cursorStylePerMode.insert": "underline",
"vim.cursorStylePerMode.normal": "underline",
```

**To Reproduce**
1. Copy the settings and see that it's not working

**Expected behavior**
Should respect the settings.json file

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.2
- VSCode version: 1.40.2
- OS: macOS

**Additional context**

It's working with 1.11.3 version

**Comment by CVVPK** [comment]
I found the source of this bug, I could send in a PR with a fix for it.
