### ISSUE TITLE
not working anymore...

### ISSUE THREAD

**Issue by abucu** [VSCodeVim/Vim#4356]
Issue Type: <b>Bug</b>

don't know how it happened, but just cannot recover by reinstall, restart..

Extension version: 1.12.2
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:52:45.129Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chanshing** [comment]
This happened to me after the update. I installed an older version (button next to Install in the Extension tab) and it is working now.

**Comment by abucu** [comment]
> This happened to me after the update. I installed an older version (button next to Install in the Extension tab) and it is working now.

also tried n failed. but just installed an much older version, working now = =
