### ISSUE TITLE
vim无法使用

### ISSUE THREAD

**Issue by hezi1706** [VSCodeVim/Vim#4357]
Issue Type: <b>Feature Request</b>

启用vim扩展，重启后没有进入vim的任何一个模式

Extension version: 1.12.2
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

**Comment by J-Fields** [comment]
Have you tried re-installing the extension?

**Comment by hezi1706** [comment]
Thank you.
I had tried to re-installing, But it's did't work.
the problem is solved when I sented the message.&nbsp;

---原始邮件---
发件人: "Jason Fields"<notifications@github.com&gt;
发送时间: 2019年12月11日(周三) 凌晨1:31
收件人: "VSCodeVim/Vim"<Vim@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"hezi1706"<1029711691@qq.com&gt;;
主题: Re: [VSCodeVim/Vim] vim无法使用 (#4357)



Have you tried re-installing the extension?

**Comment by CG-man** [comment]
老哥, 他们的1.12.0这个版本是有问题的, 你可以更新到1.12.2这个版本就可以继续愉快的使用vim了

**Comment by hezi1706** [comment]
OK，谢谢啦



---原始邮件---
发件人: "樊冬"<notifications@github.com&gt;
发送时间: 2019年12月11日(周三) 下午2:54
收件人: "VSCodeVim/Vim"<Vim@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"hezi1706"<1029711691@qq.com&gt;;
主题: Re: [VSCodeVim/Vim] vim无法使用 (#4357)



老哥, 他们的1.12.0这个版本是有问题的, 你可以更新到1.12.2这个版本就可以继续愉快的使用vim了
