### ISSUE TITLE
Paste problem in visual mode

### ISSUE THREAD

**Issue by sumanx** [VSCodeVim/Vim#436]
When I press p to a selected word, try to replace it with copied text, it will append to the selected word, not replace it. 

In vim it should be replacing and moving the replaced text into clipboard.

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.1
* OS: Mac OS X 10.11.4

**Comment by johnfn** [comment]
Whoa; never knew about this feature, even though it seems very logical.

**Comment by johnfn** [comment]
Annnd done!

**Comment by sumanx** [comment]
Thanks!
