### ISSUE TITLE
Support `g?` operator (rot13)

### ISSUE THREAD

**Issue by hoodie** [VSCodeVim/Vim#4363]
vim [natively](https://vim.fandom.com/wiki/How_to_obscure_text_instantaneously) supports rot13 "encryption" using `g?`

would be super neat if VSCodeVim could support it too :grin: 

thank you

**Comment by J-Fields** [comment]
Cool, didn't know vim could do this. What do you use this for, if you don't mind me asking?

**Comment by hoodie** [comment]
IDK, my `~/.password.txt` for instance

**Comment by hoodie** [comment]
great work, I didn't expect this much effort for this rather frivolous issue, thank you very much

**Comment by J-Fields** [comment]
No worries - actually wasn't that much work, just a few annoying details and I'm sometimes too lazy to test locally before pushing 😛
