### ISSUE TITLE
When key 'p' typed, the cursor would blink many times and the pane would be frozen

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#4368]
- Extension (VsCodeVim) version: 1.12.2
- VSCode version: 1.40.2
- OS: Mac 10.13.6

_Originally posted by @hiroto78 in https://github.com/VSCodeVim/Vim/issues/4359#issuecomment-564333127_

**Comment by CVVPK** [comment]
It seems like this  is another case of a conflicting vimrc config. I was able to reproduce by using the vimrc found in @hiroto78 dotfiles repo (I know going through peoples' stuff is kind of creepy, sorry!).

Removing or commenting out the following lines solved it for me:

```
nmap p <Plug>(yankround-p)  
nmap P <Plug>(yankround-P)
```

**Comment by J-Fields** [comment]
Sweet. Thanks for investigating this @CVVPK!

**Comment by hiroto78** [comment]
Thank you for letting me know! It worked fine! @CVVPK
