### ISSUE TITLE
When in Visual Mode "s" should delete all selected text and enter Insert mode.

### ISSUE THREAD

**Issue by AntonAderum** [VSCodeVim/Vim#437]
### What did you do?

```public class TestyTest {```
If caret is at the start off the line, press  ```v``` and ```e```, visually selecting ```public```.
Then press ```s```

### What did you expect to happen?
I expected ```public``` to be deleted and to be put in the Insert-mode.
### What happened instead?
Nothing.
### Technical details:
Its clear looking at the Action.ts action for "s" that this isnt a bug as much as a missing feature. The only mode set for "s" is the Normal.

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.1
* OS: Windows 10.

**Comment by johnfn** [comment]
Thanks for the issue! I went and added this feature myself. 😄
