### ISSUE TITLE
Remapping ":"

### ISSUE THREAD

**Issue by airstrike** [VSCodeVim/Vim#4374]
I've looked around quite a bit trying to find a solution but came up empty. I'd like to remap `:` and `;` as I find `shift`+`;` to be significantly more annoying to repeatedly type than simply `;`

In vanilla vim, I use

    nnoremap ; :
    nnoremap : ;

And that does the trick. I don't believe I can do the same in VS Code today, so I'm opening this feature request.

**Comment by sqlkoala** [comment]
Hi, you can do this. With, 1.12 there is support for "parsing" a vimrc.
I would give a separate path for vscodevim like this:
![grafik](https://user-images.githubusercontent.com/30384885/70788539-662e5f80-1d91-11ea-8580-026b2c783ae0.png)
And then you can put these lines there.

Pre 1.12, you would do that in your settings.json. This is described here:
https://github.com/VSCodeVim/Vim
"Key Remapping"

**Comment by airstrike** [comment]
> Pre 1.12, you would do that in your settings.json. This is described here:
> https://github.com/VSCodeVim/Vim
> "Key Remapping"

I've read that article twice but still don't see how that's possible. Closest I got was by adding

    {
      "key": "shift+;",
      "command": "vim.showQuickpickCmdLine",
      "when": "editorTextFocus && vim.mode != 'Insert'"
    }

to my `keybindings.json` but `vim.showQuickpickCmdLine` isn't quite the same as the regular command line

**Comment by airstrike** [comment]
I can, however, confirm that using `nnoremap` in a vimrc file works, and indeed works better than the `keybindings.json` approach. Feels like that setting is buried under a bunch of other "more granular" ones, though.

The latter would incorrectly pop up the QuickpickCmdLine when doing e.g. <kbd>r</kbd><kbd>;</kbd> in normal mode to replace a single character with `;`
