### ISSUE TITLE
C+o not work

### ISSUE THREAD

**Issue by longhaiqwe** [VSCodeVim/Vim#4376]
Issue Type: Bug

C+o jump to older position messed up.
And I rolled back to 1.11.3 and everything worked fine.

Extension version: 1.12.2
VS Code version: Code 1.40.2
OS version: Win10

**Comment by J-Fields** [comment]
Can't reproduce (also on windows 10). Make sure there aren't any remaps which could be interfering in either settings.json or your .vimrc

**Comment by charlietran** [comment]
This is happening to me as well on MacOS Catalina. Ctrl+O jumps into another random file.

**Comment by longhaiqwe** [comment]
@J-Fields Thanks for you reply.
I tried removing all vim settings in settings.json and .vimrc, and the error still exists.

**Comment by zhengbli** [comment]
Happened to me on Linux with 1.12.2 as well. "gd" goes to the definition location, but then `<c-o>` jumps to a random file.

**Comment by jfrid** [comment]
Same for me. Ubuntu 18.04, VS Code 1.41.0, Vim plugin 1.12.2.

**Comment by rockindy** [comment]
I got the same problem. Ubuntu 18.04, VS Code 1.41.1, Vim plugin 1.12.3

I rolled back to 1.11.3 and it worked fine.

**Comment by Ciebiada** [comment]
Same issue here: OS X  10.15.2, VSCode 1.41.1, Vim plugin 1.12.3

**Comment by kevindevos** [comment]
MacOS Catalina 10.15.2 on plugin 1.12.4, i see that this happens when you switch to a file with cmd+p and it ends up opening a wrong file after i press Ctrl-o

**Comment by albuscrow** [comment]
Extension version: 1.12.4
VS Code version: Code 1.42
OS version: OSX

"gd" goes to the definition location, but then <c-o> jumps to a new tab named "tasks".

**Comment by J-Fields** [comment]
Fixed via #4581
