### ISSUE TITLE
Yank doesn't work on 1.12.x on Ubuntu

### ISSUE THREAD

**Issue by dplummer** [VSCodeVim/Vim#4377]
**Describe the bug**
The command `yyp` should copy the current line and paste it on the next line. As of `1.12.1` this (and any other `y` yank) does nothing. Turning on `useSystemClipboard` somewhat works, but `yyp` pastes on current line (which is a different issue, not this). In `1.11.3` yank worked.

**To Reproduce**

1.  Install VSCodeVim `1.12.1` or greater (1.12.0 just doesn't work) on Ubuntu 18.04
2.  Attempt to yank: `yy` or `yiw` in normal mode, or just `y` in visual mode
3.  Attempt to paste `p` from normal mode, or select text in visual and attempt to paste over
4. Expect paste, but nothing happens (or text is deleted if selected, since the register is empty)

**Expected behavior**
I expect `y` to yank the currently selected text or whatever move is suggested.

**Environment:**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.12.2`
- OS Version: `Linux x64 4.15.0-65-generic`
- VSCode version: `1.40.2`

`useSystemClipboard` is false

**Additional context**
Yank works as expected on Mac.

**Comment by J-Fields** [comment]
> Yank works as expected on Mac.

That's interesting. With the 1.12 release we've been seeing a lot of issues reported on mac & linux - I'd assumed these stemmed from the same source.

> but yyp pastes on current line (which is a different issue, not this)

What? Did this happen prior to 1.12? `yyp` should definitely paste a new line.

**Comment by dplummer** [comment]
> What? Did this happen prior to 1.12? yyp should definitely paste a new line.
I'm away from my linux desktop for the weekend, I'll get back to you on Monday about this, and open a new issue after verifying.

**Comment by yujinyuz** [comment]
This is quite similar to my issue https://github.com/VSCodeVim/Vim/issues/4352 but the yank works in macOS

**Comment by CVVPK** [comment]
Does this happen with `vim.vimrc.enable` set to `false`?

**Comment by dplummer** [comment]
This was fixed with 1.12.4 by https://github.com/VSCodeVim/Vim/commit/35e11ade5e30f5c5dbe4c8d70375ab78c4780df5. 

Toggling `vim.vimrc.enable` off then on again also fixes it.
