### ISSUE TITLE
Incremental search is laggy in large files

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#438]
If you try to search for something in our massive actions.ts file, or another large file, VSCodeVim lags. This is unsurprising because the current search approach is to parse the entire file on every keystroke.

"So don't write 2000 line files, johnfn"

Shush, that's not the point. The point is there are lots of easy win optimizations here. I did the dumbest thing that worked for the MVP. 😉

**Comment by roblourens** [comment]
I think that limiting the number of matches to 1000 should get you most of the way there (VSCode does this in its own search) and we can also cache the matches and only invalidate when `searchString` changes, or the doc version changes. I'll take a crack at it.

**Comment by rebornix** [comment]
@roblourens it's really awesome to have you here. Looking forward to your PR!
