### ISSUE TITLE
taskqueue: cannot read property 'getTime'

### ISSUE THREAD

**Issue by zachvalenta** [VSCodeVim/Vim#4381]
**Describe the bug**

Using the [VS Code Markdown](https://github.com/yzhang-gh/vscode-markdown) to bold/italicize and then immediately undoing w/ VS Code Vim (`u`) causes Vim to throw an error.

![70828293-1bc0d900-1db9-11ea-89c5-64139e902524](https://user-images.githubusercontent.com/11388735/70849892-8bcf6d80-1e52-11ea-94f9-ca4958f4846e.png)

I opened [an issue](https://github.com/yzhang-gh/vscode-markdown/issues/572) in the Markdown extension's repo because I'm unsure whether the locus of the error is Vim or the Markdown extension.

**To Reproduce**

1.  Use VS Code Markdown to bold/italicize word
2.  Use VS Code Vim to undo (`u`)
3.  See error `taskqueue: cannot read property 'getTime'`

**Expected behavior**

No error to be thrown

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.2
- VS Code Markdown: 2.6.1
- VSCode version: 1.41
- OS: macOS Mojave 10.14.3

**Comment by J-Fields** [comment]
This should be fixed in latest master. It'll be in a patch release soon.
