### ISSUE TITLE
Inserting a Hash/Number/Pound sign writes out "X\x08#" instead

### ISSUE THREAD

**Issue by mitsuhiko** [VSCodeVim/Vim#4387]
**Describe the bug**

When one tries to write `#` VScode will write out `X\x08#` into the file instead (note that `\x08` is the backspace character). Not sure when it regressed but it happened some time last week for me the first time.

**To Reproduce**

1.  Switch to insert mode
2.  Write `#`
3.  See `X#` in the buffer, deleting `#` places you behind an invisible backspace character.

**Expected behavior**
Just having `#` written.

**Screenshots**
![image](https://user-images.githubusercontent.com/7396/70892011-a3405f00-1fe8-11ea-8137-23717cf9f937.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.2
- VSCode version: 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959)
- OS: Darwin x64 18.7.0

**Comment by J-Fields** [comment]
Unable to reproduce on Windows 10

**Comment by faulkner** [comment]
The bug appears to have been introduced in 1.12.1 (downgrading to 1.12.0 fixes the issue for me).

**Comment by nfm** [comment]
I'm also experiencing this regression.

**Environment:**

- Extension (VsCodeVim) version: 1.12.2
- VSCode version: Version: 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0)
- OS: Linux x64 5.3.0-24-generic

Happy to help debug this issue, let me know if there's anything I can test out or more info I can provide that would be useful :heart:

**Comment by mitsuhiko** [comment]
I can confirm that I can't reproduce it on windows but I can on mac. Not sure if there is anything else I can help here. I had to downgrade to 1.11.13 which is the last plugin that works on mac for me.

**Comment by mitsuhiko** [comment]
Since I just got auto updated: confirmed still broken on 1.12.3.

**Comment by nfm** [comment]
I've just updated to 1.12.4 and it appears this is resolved for me now :+1:

**Comment by J-Fields** [comment]
@nfm Sweet. Nothing was done to directly fix this, so my hunch is `vim.vimrc.enable` being true by default was causing some issue. Would you mind turning it back on and seeing if you can reproduce this bug again?

**Comment by mitsuhiko** [comment]
Likely to be the cause. I can't test this right now but by vimrc like the one of many others has this in it: `inoremap # X^H#`. This is a hack to make smartindent not outdent hashes.

**Comment by J-Fields** [comment]
Yup, sounds like the culprit. I'm not too familiar with this - should VSCodeVim behave differently than it does with that remap? Or is this really just vim-specific, and we should have some way of ignoring certain remaps?

**Comment by mitsuhiko** [comment]
It should definitely not insert a backspace ascii char but delete the last char. That’s how vim behaves.

**Comment by J-Fields** [comment]
Oh right, I'd forgotten about what `^H` did in insert mode. Would you mind filing a new issue describing the remap misbehavior?

**Comment by nfm** [comment]
Nice sleuthing all :bowing_man: 

My `init.vim` does contain `inoremap # X^H#`.

I can confirm that if I set `"vim.vimrc.path": "~/.config/nvim/init.vim", "vim.vimrc.enable": true` then the errant behaviour reproduces under 1.12.4.

The remap is unnecessary in VSCode, it's just a workaround required for vim/neovim. Some way to ignore certain remaps could be nice, but isn't super important to me at least.

**Comment by mitsuhiko** [comment]
Created #4430. Closing this one as resolved.
