### ISSUE TITLE
[QUESTION] Copy `co` command

### ISSUE THREAD

**Issue by nrudnyk** [VSCodeVim/Vim#4390]
Is it possible to copy selected range of lines and paste at cursor or selected line?
I thought it should be something like below for copying lines 10 to 15 and paste at cursor:

`:10,15co.`
`:10,15 co .`

Am I missing something?

**Comment by J-Fields** [comment]
Try enabling neovim integration. I haven't tested, but it should work then.

**Comment by J-Fields** [comment]
If someone decides to implement this without neovim, `:t` should do the same thing as `:co[py]`

**Comment by subhakarks** [comment]
Hi @J-Fields `:t` works. Is there pointer to documentation on such commands?. TIA.

**Comment by J-Fields** [comment]
@subhakarks `:t` only works with neovim integration. You can always take a look at [the source](https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/subparser.ts#L33) to see what commands are natively supported.

**Comment by J-Fields** [comment]
Duplicate of #2472
