### ISSUE TITLE
Rebinding 'yy' (yank line) is not working

### ISSUE THREAD

**Issue by bodgergely** [VSCodeVim/Vim#4392]
**Describe the bug**
Unable to rebind the **yank line** command "yy" to "ff" (or any other key)
Since I have succefully remapped 'y' to 'f' I also expect the 'ff' to yank a line in normal mode.
**To Reproduce**
```
    "vim.visualModeKeyBindings": [
        {
            "before": [
                "f"
            ],
            "after": [
                "y"
            ]
        }
    ],
    "vim.normalModeKeyBindings": [
        {
            "before": [
                "f"
            ],
            "after": [
                "y"
            ]
        }
    ],
```

Now if you try using 'ff' to yank a line it will not work.

**Expected behavior**

'ff', just like 'yy' should yank a line.

**Environment (please complete the following information):**
VSCode version: 1.12.2
Linux 

- Extension (VsCodeVim) version:
- VSCode version: 1.12.2
- OS: Linux

**Comment by J-Fields** [comment]
`nnoremap ff yy` does what you want

**Comment by bodgergely** [comment]
@J-Fields Thanks a lot, worked!

**Comment by mdshahjalal5** [comment]
> `nnoremap ff yy` does what you want

I not understood what to do here
