### ISSUE TITLE
<space> + s does not execute command

### ISSUE THREAD

**Issue by artvinn** [VSCodeVim/Vim#4394]
**Describe the bug**
I use `<leader> + s` combo for saving the file in normal mode.

**To Reproduce**
1. Set the following mapping:
```json
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "leader",
        "s"
      ],
      "after": [],
      "commands": [
        {
          "command": "workbench.action.files.save",
          "args": []
        }
      ]
    }
  ],
```
2. Try saving file with `<space> + s`

**Expected behavior**
Should save a file. Instead, I see `:update` in the vscode bottom bar.

**Environment**

- Extension Version: `1.12.2`
- OS Version: `Linux x64 5.4.3-arch1-1`
- VSCode version: `1.41.0`

**Additional context**
Works correctly on macOS. Also works ok with `1.11.3`.

**Comment by artvinn** [comment]
Seems to be related to [this issue](https://github.com/VSCodeVim/Vim/issues/4359)

**Comment by sqlkoala** [comment]
Hi,
you need `"<leader>"` as before. I have the same mapping ;-)

**Comment by berknam** [comment]
@artvinn I think this is no longer an issue. Can you check it out and close it.

**Comment by artvinn** [comment]
Yep, works with latest version. Thanks.
