### ISSUE TITLE
keymap not works anymore in version 1.12.2

### ISSUE THREAD

**Issue by JunfengJia** [VSCodeVim/Vim#4396]
{
            "before": [
                "<space>"
            ],
            "after": [
                "<leader>",
                "<leader>",
                "s"
            ],
        },

It will insert junk string now.
expected:
launch easymotion find char.

**Comment by gee-forr** [comment]
I'm having the same problem with triggering easymotion... my easymotion trigger is `<leader><leader>w`, or `space`, `space`, `w`.

In  my case, it selects the entire line as if I was typing `V` in normal mode.

In the meantime, I've downgraded to `1.11.3`.

**Comment by visheshd** [comment]
Had to downgrade to 1.11.3 as well

**Comment by J-Fields** [comment]
@gee-forr @visheshd what platforms are you on?

**Comment by SpyTec** [comment]
@J-Fields same issue here, fedora 31

**Comment by gee-forr** [comment]
> @gee-forr @visheshd what platforms are you on?

I'm on macOS Catalina, running the latest VS Code, and at the time, the latest VSCode Vim.

Merry Christmas :)

**Comment by visheshd** [comment]
> @gee-forr @visheshd what platforms are you on?

I'm on macOS Catalina as well. Thanks for looking into it!

**Comment by J-Fields** [comment]
Thanks for the responses, all. I actually don't have access to a unix system at the moment, and it seems like this issue (as well as several other recent ones) are not reproducible on windows. If anyone could help track down what might be causing this, that would be awesome 🙂

**Comment by CVVPK** [comment]
Are any of these reproducible with `vim.vimrc.enable` set to `false`?

**Comment by SpyTec** [comment]
> Are any of these reproducible with `vim.vimrc.enable` set to `false`?

Seems to work just fine with `vim.vimrc.enable` set to `false`

**Comment by CVVPK** [comment]
@SpyTec is there by chance a line in your `vimrc` that remaps a plugin function. Something that looks similar to this:

```
nmap s <Plug>(easymotion-s2) 
```

**Comment by SpyTec** [comment]
> @SpyTec is there by chance a line in your `vimrc` that remaps a plugin function. Something that looks similar to this:
> 
> ```
> nmap s <Plug>(easymotion-s2) 
> ```

You'd be correct, I do have a mapping for easymotion in my `.vimrc`

**Comment by JunfengJia** [comment]
fixed In 1.12.4.
