### ISSUE TITLE
'dE' leaves the end-of-word character intact

### ISSUE THREAD

**Issue by justinsamsky** [VSCodeVim/Vim#440]
```dE``` deletes everything until the next end-of-word, but not the end-of-word character.
When the cursor is here ```[] word```, ```dE``` produces the following result: ```[d]```

```de``` works fine though.

* VSCode Version: 1.3.0
* VsCodeVim Version: 0.1.2
* OS: Ubuntu Linux 14.04

**Comment by johnfn** [comment]
Fixed!
