### ISSUE TITLE
Unable to remap keys via noremap in vimrc

### ISSUE THREAD

**Issue by jjoekoullas** [VSCodeVim/Vim#4403]
**Describe the bug**
Very simple vimrc doesn't appear to be getting applied.

.vimrc contents:
```
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
```

**To Reproduce**
On windows.
1.  Create file ~\.vimrc with the above contents
2.  Check vscode vim settings - confirm vimrc is enabled, confirm default vimrc path (no vimrc related settings in settings json)
3.  Restart vscode and open a file
4.  Use the arrow keys to navigate around in a file.

**Expected behavior**
Arrow keys are disabled when editing a file.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.12.1
- VSCode version: 1.41.1 (user setup)
- OS: Windows 10

**Additional context**
I'm a vim newbie - but this vimrc works when I open vim.

**Comment by J-Fields** [comment]
Yeah, we don't support `<NOP>` currently. Should be a pretty straightforward addition

**Comment by jjoekoullas** [comment]
If it's straight forward, I would really like to take a crack at submitting a PR for it.  Any chance you can point me to similar bugs/PRs that I can use as reference?

**Comment by jjoekoullas** [comment]
I'd guess https://github.com/VSCodeVim/Vim/blob/master/test/configuration/vimrcKeyRemappingBuilder.test.ts is a pretty good place to start.

**Comment by J-Fields** [comment]
Yeah a test there would be great. I think we also want a command (`actions.ts`) for `<NOP>` that does nothing. I think a change in `notation.ts` (and possibly elsewhere, I'm not sure off the top of my head) so we parse `<NOP>` as a single keystroke.

**Comment by jjoekoullas** [comment]
@J-Fields thanks for the pointers.

`<NOP>` to work out of the box and the issue looks like it was due to `noremap` not being supported.  See: https://github.com/VSCodeVim/Vim/blob/master/src/configuration/vimrc.ts#L46
