### ISSUE TITLE
'dNG' behaves differently than expected

### ISSUE THREAD

**Issue by justinsamsky** [VSCodeVim/Vim#441]
Given the following example text, cursor position ```[]``` and line numbers:

```
1. The weather today[]will be:
2. SUNNY
```

I expect ```d2G```to delete both lines completely and move the cursor to the start of the third line (if it exists). Instead, the result is:

 ```1. The weather today[U]NNY```

It looks like dNG moves the cursor to line N, deleting every character along the way, and deletes the first character of line N. Vim's normal behavior is to delete all lines from the cursor's initial position to line N, including the initial line and line N.

* VSCode Version: 1.3.0
* VsCodeVim Version: 0.1.2
* OS: Ubuntu Linux 14.04

**Comment by johnfn** [comment]
Fixed! Thanks for the report.

**Comment by justinsamsky** [comment]
Wow that was fast. Thank you very much. :)
