### ISSUE TITLE
The plugin VIM inputs ClosePair(')') if I type ) by myself 

### ISSUE THREAD

**Issue by dawnmy** [VSCodeVim/Vim#4411]
**Describe the bug**
The plugin VIM inputs `ClosePair(')')` if I type `)` by myself. The seems for `]`.

**To Reproduce**

1.  Go to any text file (.py, .txt, ... whatever)
2.  Type `)` or `]`
3.  You will have `ClosePair(')')` or `ClosePair(']')` input by the VIM plugin

**Expected behavior**
It should just input a `)` if I type `)`.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.2
- VSCode version: 1.41.1
- OS: macOS 10.15.1

**Additional context**
If I disable this plugin, no such issue occurs

**Comment by J-Fields** [comment]
I believe this was an issue with `vim.vimrc.enable` being true by default. Can you confirm this is fixed in `1.12.4`?

**Comment by dawnmy** [comment]
> I believe this was an issue with `vim.vimrc.enable` being true by default. Can you confirm this is fixed in `1.12.4`?

Thank you so much for the update. It has been fixed in version `1.12.4`
