### ISSUE TITLE
vimrc <space> does not remap

### ISSUE THREAD

**Issue by davidystephenson** [VSCodeVim/Vim#4412]
Issue Type: <b>Bug</b>

My `.vimrc` contains the line `noremap <space> :`.

I expect this to make the spacebar act as the colon when I am not in insert mode.
My goal is to use the spacebar to issue commands.

What actually happens is that the spacebar moves the cursor forward when in command mode.
The map is not applied.

How can I map space with my `.vimrc`?

Extension version: 1.12.2
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T15:04:31.999Z)
OS version: Linux x64 5.0.0-37-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|31.29GB (1.98GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by schu34** [comment]
does it work with `nnoremap <space> :` (double `n` at the beginning)?

**Comment by J-Fields** [comment]
Actually `noremap` is a thing, but we didn't support it when this issue was filed. Make sure you've updated the plugin and try it again @davidystephenson. Let me know if it's still a problem.

**Comment by davidystephenson** [comment]
Everything is now working correctly.
