### ISSUE TITLE
":vsp %<.h" to open the header file of the current file

### ISSUE THREAD

**Issue by starjesse** [VSCodeVim/Vim#4414]
When I was a Linux vim user, I always use ":vsp %<.h" to open the header file of the current file. For example, the current file is "foo.cpp", and the command above will open the file "foo.h". Correspondingly, the current file is "foo.h" and I use ":vsp %<.cpp" will open the file "foo.cpp".

But it doesn't work in vscode vim. Is there any solution of my requirement?

**Comment by J-Fields** [comment]
We don't support anything like this (what does the `%<` do?) but the C/C++ extension has a `C_Cpp.SwitchHeaderSource` command you can use.

**Comment by starjesse** [comment]
> We don't support anything like this (what does the `%<` do?) but the C/C++ extension has a `C_Cpp.SwitchHeaderSource` command you can use.

"%" means the current file name. "<" means remove the suffix of the file name. 
Let me see the usage of C_Cpp.SwitchHeaderSource.
