### ISSUE TITLE
How to quit multi-cursor mode?

### ISSUE THREAD

**Issue by arucil** [VSCodeVim/Vim#4416]
I enabled multi-cursor mode by accident, now when I move the main cursor on an HTML tag, there are one another cursor on the matching tag.  
I have tried hitting ESC in normal mode but the cursor just moved leftward by one character and there are still two cursors. Even restarting VSCode didn't pull me back to single-cursor mode.

**Comment by J-Fields** [comment]
`"html.mirrorCursorOnMatchingTag": false`
