### ISSUE TITLE
enable Vimrc seems to be on by default

### ISSUE THREAD

**Issue by ctobolski** [VSCodeVim/Vim#4419]
**Describe the bug**
The default value of vimrc is set to a boolean, though the default value is the string "false". I was trying to figure out why my leader key wasn't working. The conflict  apparently prevents my leader key from working. 

**To Reproduce**
1. In my .vimrc:
`nnoremap <Space> <Nop>`
2. In my settings.json
``` 
 "vim.leader": "<space>" ,
 "vim.normalModeKeyBindings": [
        {
            "before": [
              "leader",
              "a" 
            ],  
            "commands": [
              "workbench.action.showCommands"
            ] 
          }
    ] 
```
3. Start vscode, hit Space + a
4. Nothing happens

**Expected behavior**
Open the command palette

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.3
- VSCode version: 1.41.1
- OS: Linux (Ubuntu 18.04)

**Comment by J-Fields** [comment]
Fixed by #4420
