### ISSUE TITLE
The words that auto-completed (by press tab) will be deleted when press jj

### ISSUE THREAD

**Issue by eksea** [VSCodeVim/Vim#442]
Precondition:
bind jj to <esc>

Reproduce steps:
1. open a .js file
2. type "docu"
3. press tab key(vs code will complete the word "document")
4. press jj

expected result:
VSCodeVim exit insert mode

actual result:
VSCodeVim exit insert mode, meanwhile, "ment" is deleted

* VSCode Version:1.3.1
* VsCodeVim Version: *[0.1.2]*
* OS: windows 10

**Comment by johnfn** [comment]
And the award for weirdest bug goes to...

**Comment by johnfn** [comment]
Fixed!

**Comment by eksea** [comment]
cool, expecting the next version.
And thank you very much.
