### ISSUE TITLE
ctrl+b doesn't show side bar in normal mode

### ISSUE THREAD

**Issue by fauzanrh** [VSCodeVim/Vim#4426]
**Describe the bug**
ctrl+b doesn't open sidebar in normal mode

**To Reproduce**
[in normal mode]

1. Press CTRL-B go back a word

**Expected behavior**
Shows side bar

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 0.0.45
- VSCode version: 1.41.1
- OS: ubuntu 19.10

**Comment by J-Fields** [comment]
Could you clarify? `<C-b>` in normal mode should scroll a full page up, not go back a word or show the side bar. http://vimdoc.sourceforge.net/htmldoc/scroll.html#ctrl-b
