### ISSUE TITLE
Missing support for "change inside" and "delete inside"

### ISSUE THREAD

**Issue by sectioneight** [VSCodeVim/Vim#443]
First off, congrats on the progress with the plugin, given recent progress I'm finally able to use it for my day-to-day work.

I was looking at the Roadmap to try to figure out whether this was planned or not, but I don't see any mention of it. I'd like to figure out whether it's already planned or impossible with the current VSCode APIs. If it's possible, I'm interested in implementing it myself.

The most common ones I'm used to are `ci(`, `ci"`, `ciw`, and their "di" variants.

**Comment by sectioneight** [comment]
Note: there is currently support for "viw" and "vaw" for visual selection (but no `vi(` or 'vi"`), but those are the only mention of commands that behave like this as far as I can tell.

**Comment by johnfn** [comment]
Yay! Glad to hear it.

We have a mega-issue for this open here: https://github.com/VSCodeVim/Vim/issues/287

If you do want to take a whack at one of these, by all means go ahead! I'd suggest to make a separate issue for it, and tag it with 'in-progress' so that no one else implements it at the same time.

**Comment by sectioneight** [comment]
Sounds great. Tedious but easy sounds like a good place to start given that I'm new to the codebase and TypeScript (although I've done some node previously).

**Comment by johnfn** [comment]
Awesome! Feel free to hang out on slack if you want to ask me questions or something.

We already have `%` which is good at finding matching delimiters, so that will be a good place to start.
