### ISSUE TITLE
VSCodeVim disables 'Open Folder' shortcut (Ctrl+K Ctrl+O)

### ISSUE THREAD

**Issue by jyn514** [VSCodeVim/Vim#4431]
**Describe the bug**
I open different project folders a lot and I would like to use the keyboard shortcut (the manual way is File -> Open Folder). However, whenever I enable VSCodeVim, nothing happens when I press `Ctrl-K Ctrl-O`.

**To Reproduce**

1. Install VSCodeVim.
2. Open a new file and click on it to make sure it is in focus.
2. Press Ctrl-K then Ctrl-O.
3. Nothing happens.

Note that if the file is not in focus (you last clicked on another part of the UI) the shortcut works fine.

**Expected behavior**
The 'Open Folder' dialog pops up.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.12.4 (2019-12-27)
- VSCode version:
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
```
- OS: Linux x64 5.0.0-37-generic

**Comment by CVVPK** [comment]
As far as I know this happens because the extension disables the native `Ctrl` actions by default. You could set `vim.useCtrlKeys` to `false`. Or alternatively set this as a keybind in your settings:

```
"vim.normalModeKeyBindings": [
        {
            "before": [
                "<C-k>",
                "<C-o>"
            ],
            "commands": [
                "workbench.action.files.openFolder"
            ]
        },
        {
            "before": [
                "<C-o>"
            ],
            "commands": [
                "workbench.action.files.openFile"
            ]
        }
    ]
```

**Comment by J-Fields** [comment]
If you don't care about vim's `<C-k>` and `<C-o>`, you can hand those back to VSCode with `handleKeys` (or `useCtrlKeys`, as @CVVPK mentioned). Best of both worlds is to remap via our settings (or a .vimrc) or in VSCode's settings with an appropriate `when` clause to avoid the conflict.

**Comment by jyn514** [comment]
Adding a setting for handleKeys in settings.json fixed it, thanks!
```
  "vim.handleKeys": {
    "<C-a>": false,
    "<C-f>": false
  }
```
