### ISSUE TITLE
Bad behavior when using C-o in insert mode

### ISSUE THREAD

**Issue by neta540** [VSCodeVim/Vim#4453]
When using `C-o` in insert mode, followed by some "enter to insert mode" commands, we enter a buggy "insert mode" which requires to press `<Esc>` twice in order to exit it, instead of exiting it by pressing `<Esc>` only once.

**To Reproduce**
1. Enter insert mode.
2. Type any word.
3. While still in insert mode, press `C-o` followed by either `A`, `a`, `I`, `i`, `O`, `o`.
4. Press `<Esc>` **once**
5. *Still in insert mode* :disappointed:  

**Expected behavior**
After pressing `<Esc>`, the expected behavior is to enter normal mode.

**Environment**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: Linux x64

**Comment by CVVPK** [comment]
I looked a bit into this. It'd appear to me setting `VimState.returnToInsertAfterCommand` back to `false` after entering Insert Mode would fix it. I could make some changes and add some tests.
