### ISSUE TITLE
Mapping `:move` command in `.vimrc` is unrecognized

### ISSUE THREAD

**Issue by shiloa** [VSCodeVim/Vim#4455]
**Describe the bug**
I'm trying to map `:move` command to a keyboard shortcut in `.vimrc` so I could select one or more rows and move them up or down in the file.  Once the mapping was defined, using the shortcut provided the error:

```
E492: Not an editor command. move+
```

This is essentially remapping the original VSCode `Alt-Shift-Up/Down` to `Ctrl-k/j` or `Ctrl-Up/Down` via `.vimrc`.

**To Reproduce**

1. Install VsCodeVim on VSCode.
2. Enable experimental `.vimrc` support.
3. Create a new clean `.vimrc.test` file and place the following as its content. 

```vim
" key mapping to move line/selected lines using Ctrl-up/down 
nnoremap <C-Down> :move+<CR>==
nnoremap <C-Up> :move-2<CR>==
inoremap <C-Down> <Esc>:move+<CR>==gi
inoremap <C-Up> <Esc>:move-2<CR>==gi
vnoremap <C-Down> :move'>+<CR>gv=gv
vnoremap <C-Up> :move-2<CR>gv=gv

" same thing with j/k keys
nnoremap <C-j> :move+<CR>==
nnoremap <C-k> :move-2<CR>==
inoremap <C-j> <Esc>:move+<CR>==gi
inoremap <C-k> <Esc>:move-2<CR>==gi
vnoremap <C-j> :move'>+<CR>gv=gv
vnoremap <C-k> :move-2<CR>gv=gv
``` 
4. Point VSCodeVim to `.vimrc.test` file and restart the editor.
5. Open a test/code file.
6. Select one or more rows and attempt to move them up or down using either `Ctrl+Up`/`Ctrl+k` (up) or `Ctrl+Down`/`Ctrl+j`.

**Expected behavior**
Selected row or block (in visual mode) will move up/down through the file.  Should also work for a single row if the cursor is in normal or insert mode. 

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.
![image](https://user-images.githubusercontent.com/52377/71640503-fa565d00-2c93-11ea-9a0c-d45ee723fbf1.png)

**Logs**

For the original mapping:

```
ModeHandler: debug: handling key=<C-j>.
Remapper: debug: trying to find matching remap. keys=<C-j>. mode=Normal. keybindings=normalModeKeyBindingsMap.
Remapper: debug: trying to find matching remap. keys=<C-j>. mode=Normal. keybindings=normalModeKeyBindingsNonRecursiveMap.
Remapper: verbose: key=<C-j>. keySlice=<C-j>.
Remapper: debug: normalModeKeyBindingsNonRecursiveMap. match found. before=<C-j>. after=:,m,o,v,e,+,,=,=. command=undefined.
ModeHandler: debug: handling key=:.
ModeHandler: debug: handling key=m.
ModeHandler: debug: handling key=o.
ModeHandler: debug: handling key=v.
ModeHandler: debug: handling key=e.
ModeHandler: debug: handling key=+.
ModeHandler: debug: handling key=.
ModeHandler: debug: handling key==.
```

Also tried mapping just `:m`, same behavior:

```
ModeHandler: debug: handling key=<C-j>.
Remapper: debug: trying to find matching remap. keys=<C-j>. mode=Normal. keybindings=normalModeKeyBindingsMap.
Remapper: debug: trying to find matching remap. keys=<C-j>. mode=Normal. keybindings=normalModeKeyBindingsNonRecursiveMap.
Remapper: verbose: key=<C-j>. keySlice=<C-j>.
Remapper: debug: normalModeKeyBindingsNonRecursiveMap. match found. before=<C-j>. after=:,m,+,,=,=. command=undefined.
ModeHandler: debug: handling key=:.
ModeHandler: debug: handling key=m.
ModeHandler: debug: handling key=+.
ModeHandler: debug: handling key=.
ModeHandler: debug: handling key==.
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1 (commit: 26076a4de974ead31f97692a0d32f90d735645c0)
- OS: macOS Mojave 10.14.6

**Additional context**
None.

**Comment by J-Fields** [comment]
As a workaround, you can remap to `editor.action.moveLinesUpAction`

**Comment by YalandHong** [comment]
Maybe a dup of #2472. Currently VSCodeVim does not support `:m[ove]` command.

**Comment by Miigon** [comment]
I wonder if there is a technical reason why the `:copy` command is implemented but not the `:move` command?
