### ISSUE TITLE
Can not map to `python.sortImports` in vimrc

### ISSUE THREAD

**Issue by ChrisLee63** [VSCodeVim/Vim#4463]
**Describe the bug**
`nnoremap <leader>ci python.sortImports` does not work in vimrc

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: latest
- VSCode version: latest
- OS: windows 10

**Comment by 520Chris** [comment]
@J-Fields 
I am sorry to disturb you.
Is this a bug or just by design?

**Comment by J-Fields** [comment]
A bug. Does it work when you make that remap with our normal VSCode settings?

**Comment by 520Chris** [comment]
```
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<leader>",
                "d"
            ],
            "commands": [
                "python.sortImports",
            ]
        },
    ],
```
also does not work.

But it can work when I map `<leader>d` to `editor.action.formatDocument`.

**Comment by fihyer** [comment]
I also facing the same problem on mapping keys with `python.sortImports` command

```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>", "l", "s"],
            "commands": [
                "python.sortImports",
            ]
        },
    ],
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>", "l", "m"],
            "commands": [
                "python.refactorExtractMethod",
            ]
        },
        {
            "before": ["<leader>", "l", "v"],
            "commands": [
                "python.refactorExtractVariable",
            ]
        }
    ],
```

the first mapping not work, but the following two `python.refactor*` works.

I've tried assgin keyboard shortcuts to the `python.sortImports` command in "keybindings.json", 
```json
[
    {
        "key": "ctrl+l ctrl+s",
        "command": "python.sortImports"
    }
]
```
the shortcuts works fine, then I try remapping the "before" keys to "after" keys (the shortcuts in "keybindings.json")
```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<leader>", "l", "s"],
            "after": ["<C-l>", "<C-s>"]
        },
    ],
```
still not working

Any suggestions?
