### ISSUE TITLE
Mouse scrolls editor when Cursor Surrounding Lines is set

### ISSUE THREAD

**Issue by markonius** [VSCodeVim/Vim#4465]
**Describe the bug**
When VS Code setting "Editor: Cursor Surrounding Lines" is set, clicking near the top or the bottom of the editor scorlls the view, selecting text as it happens.

**To Reproduce**
1. Enable VSCodeVim
2. Set "Editor: Cursor Surrounding Lines" to some number
3. Click near the top or the bottom of the view in the editor (file must be scrollable)
4. Observe annoying scrolling

**Expected behavior**
Editor shouldn't scroll on click

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: Fedora 30

**Comment by cvaldev** [comment]
This doesn't seem to be reproducible 100% of the time, which leads me to believe it is possibly caused by a race condition between the extension trying to reveal a range and vscode revealing the same range.
