### ISSUE TITLE
Activating extension 'vscodevim.vim' failed: fs.existsSync is not a function.

### ISSUE THREAD

**Issue by anuragshirolkar** [VSCodeVim/Vim#4466]
**Describe the bug**
I'm running code server on google compute engine. I get an error popup saying

> Activating extension 'vscodevim.vim' failed: fs.existsSync is not a function.

and the extension never gets enabled.

**To Reproduce**
Runing [code server](https://github.com/cdr/code-server) on google compute engine with 1 cpu and 1 GB memory running ubuntu trusty. Issue occurs every time.

**Screenshots**
<img width="492" alt="Screen Shot 2020-01-03 at 11 27 36 PM" src="https://user-images.githubusercontent.com/4351301/71732510-5f6fa580-2e82-11ea-9ade-850b347552e8.png">

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: v1.12.4
- VSCode version: 1.39
- OS: Ubuntu trusty

**Comment by J-Fields** [comment]
Hmm, maybe we need to force VSCodeVim to run locally

**Comment by jpoon** [comment]
I'm new to https://github.com/cdr/code-server. Why do this when vscode officially supports https://code.visualstudio.com/docs/remote/remote-overview where vscodevim (and other extensions) work.

**Comment by anuragshirolkar** [comment]
Not my usual workflow. Was just trying it out of curiosity.

**Comment by jpoon** [comment]
Closing this as a won't do.
