### ISSUE TITLE
Visual selection and Shift+X does not delete the selection.

### ISSUE THREAD

**Issue by smekkley** [VSCodeVim/Vim#4474]
How to reproduce.
Shift + V to start line selection, try deleting the selection with shift X.
Normal X works. But it'd be help if shift+x also works like the default vim behaviour.

**Comment by J-Fields** [comment]
I can reproduce only for visual block mode (ctrl-V, not shift-V). Can you confirm this is what you meant?

**Comment by smekkley** [comment]
Yes. And thanks a lot for blazing fast commit.

**Comment by J-Fields** [comment]
No worries - it was a super easy fix, you might've been the first to notice this lol. Thanks for the bug report!
