### ISSUE TITLE
Tab Stops Ignored When Using Backspace 

### ISSUE THREAD

**Issue by cswartzvi** [VSCodeVim/Vim#448]
### What did you do?

While editing a file with `editor.useTabStops` enabled the extension seems to cause `backspace` to ignore the tab stops.

### What did you expect to happen?

With the extension disabled, vscode follows the tab stops upon deleting whitespace with `backspace`:

![vscode-backspace](https://cloud.githubusercontent.com/assets/1111348/16860782/259c7308-4a09-11e6-94b5-0b9726f9f124.gif)

### What happened instead?

However with the extension enabled the tab stops seem to be ignored:

![vim-ext-backspace](https://cloud.githubusercontent.com/assets/1111348/16860785/2d2ce35a-4a09-11e6-9995-0c60b0183800.gif)

I have been bypassing this issue by reverting the `backspace` keybinding to `deleteLeft` (you could also use `shift+backspace` which is set to `deleteLeft` as well). Sadly, I recently discovered that this does not play nice with the vim search feature as you cannot delete characters in your search string with `deleteLeft`.

### Technical details:

* VSCode Version: 1.3.0
* VsCodeVim Version: 0.1.2
* OS: Fedora 23

PS. I've been VERY impressed with the speed of improvement these last few weeks. You're doing a fantastic job!

**Comment by jpoon** [comment]
Whoa, what are you using the get those keystrokes outputted on the screen like that?

**Comment by cswartzvi** [comment]
It's a nice little program called [screenkey](https://www.thregr.org/~wavexx/software/screenkey/).

**Comment by rebornix** [comment]
Fixed and you can see the turnround in our new release.

**Comment by cswartzvi** [comment]
Again I say, fantastic job!
