### ISSUE TITLE
ctrl-e / ctrl-y scrolling is lagging substantially

### ISSUE THREAD

**Issue by FableRBX** [VSCodeVim/Vim#4485]
**Describe the bug**

Scrolling the view down/up with ctrl-e / ctrl-y is extremely laggy to the point where it's not really usable.

**To Reproduce**

1.  Scroll the view down or up with ctrl-e or ctrl-y
2.  Notice substantial document scroll latency

**Expected behavior**
Smooth seamless scrolling

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: Windows 10

**Comment by vsobotka** [comment]
I have the same issue. Has been fixed i nthe past as well #1943

**Comment by PymZoR** [comment]
Stumbled upon this issue while looking for a way to speed up scrolling with ctrl-e / ctrl-y.

**Comment by sqlkoala** [comment]
According to devs, this is fixed. See here
https://github.com/VSCodeVim/Vim/issues/4309

**Comment by FableRBX** [comment]
@sqlkoala This may have been fixed previously, but is a regression in the latest release.

**Comment by TomServo3k** [comment]
Issue #4309 says it was fixed in VsCodeVim version 1.11.3. However, I am using version 1.12.4 and the problem is very evident.

**Comment by sashaweiss** [comment]
Seeing this behavior still on `v1.12.4` as well. Any ideas on what caused this?

**Comment by umutbozdag** [comment]
Same for me with `v1.12.4`

**Comment by sqlkoala** [comment]
There merge to master by j-fields was on 29 Dec, two days after the last release 1.12.4.
https://github.com/VSCodeVim/Vim/pull/4433

So I think we have not seen it live yet and we just need to wait a few days.

**Comment by J-Fields** [comment]
Thanks @sqlkoala. Yeah, I'd meant to release a version over a month ago but life got in the way. There are a few things I want to polish up before the next release, but it's coming soon.

**Comment by J-Fields** [comment]
This should be fixed, holler if it isn't
