### ISSUE TITLE
TaskQueue: Error running task. Failed to handle key=<Esc>. .

### ISSUE THREAD

**Issue by oliyg** [VSCodeVim/Vim#4495]
**Describe the bug**
`TaskQueue: Error running task. Failed to handle key=<Esc>. .`

**To Reproduce**

1.  Press `v` `j` `j` select text
2.  Click on `CMD` + `x` cut the text
3.  Press `ESC`
4.  See error

**Expected behavior**
Switch VISUAL mode to NORMAL mode

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.12.4`
- OS Version: `Darwin x64 19.0.0`
- VSCode version: `1.41.1`

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Comment by rickdps** [comment]
Please, try reinstalling the plugin. It worked for me on Windows. I hope it helps.
