### ISSUE TITLE
Iskeyword does not respect language specific editor overrides

### ISSUE THREAD

**Issue by calebho** [VSCodeVim/Vim#4503]
**Describe the bug**
Suppose we have
```hack
$foo + $bar
^
|
cursor is here
```
When I press `w` I expect my cursor to go to
```hack
$foo + $bar
     ^
     |
```
Instead, it goes to
```hack
$foo + $bar
 ^
 |
```
In my `setting.json`, I have the following override for Hack (read: PHP):
```json
{
  "[hack]": {
    "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?"
  }
}
```
Note the absence of `$`. So it seems that `vim.Iskeyword` doesn't respect language overrides for `editor.wordSeparators`. A workaround could be to set the global `editor.wordSeparators` or `vim.Iskeyword`, but neither is ideal since I work in other languages as well where `$` should be included.

**To Reproduce**

1.  Open a PHP/Hack file
2. Edit the language specific settings for PHP/Hack to exclude `$` in `editor.wordSeparators`
3. Move cursor to the beginning of a variable
4. Press `w` to move cursor past the variable

**Expected behavior**
Cursor moves past variable

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1579026862
- OS: Mac OS 10.15.2

**Comment by diminutivesloop** [comment]
This would also be useful in css/scss where dashes are often used within identifiers. See also https://github.com/VSCodeVim/Vim/issues/2808#issuecomment-609862570.
