### ISSUE TITLE
Failed "f" Command in Visual Mode Resets Selection

### ISSUE THREAD

**Issue by harrisonmg** [VSCodeVim/Vim#4512]
**Describe the bug**
While in a visual selection and using "f" to move to the cursor to another character in the line, exhausting matches with ";" or "," will reset the selection to just the current character under the cursor.

**To Reproduce**
1.  Open a new file.
2.  Type the text "this is a test".
3.  Move the cursor to the beginning of the line.
4.  Type "v", "f", "i". The cursor will move to the first "i" in the line.
5.  Type ";". The cursor will move to the second and final "i" in the line. The selection will be from the beginning of the line to the final "i".
6.  Type ";" once more. The selection is now only the final "i".

**Expected behavior**
The selection is unchanged and the cursor does not move at step 6 above.

**Environment**
- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: Ubuntu 16.04

**Comment by J-Fields** [comment]
This works with `vim.sneakReplacesF` enabled

**Comment by harrisonmg** [comment]
@J-Fields For me, this causes the cursor to find the character in other lines as well, instead of stopping at the last match in the line.

**Comment by J-Fields** [comment]
Yeah, that's the intended effect. I don't mean it's a perfect replacement; just a workaround.
