### ISSUE TITLE
Add 'gx' support (open URL)

### ISSUE THREAD

**Issue by HawkinsT** [VSCodeVim/Vim#4518]
In vim, when the cursor is over a URL in normal or visual modes, the default behaviour of pressing 'gx' is to open the URL via netrw (it actually downloads a copy of the page and opens that). VSCode already has support for opening the URL under the cursor via Open Link (editor.action.openLink), with the exception of it opening the live webpage (which I'd say is generally the more desirable option).

Could this feature please be added as the default behaviour for gx (which is currently non-functional)?

**Comment by J-Fields** [comment]
I was unaware of this; seems to be documented [here](http://vimdoc.sourceforge.net/htmldoc/pi_netrw.html#netrw-gx)

**Comment by HawkinsT** [comment]
Me too until recently so sorry, I see from you link it also opens directories, which I wasn't aware of and would be more work to fully implement (since vscode doesn't automatically recognise these).

**Comment by dougpagani** [comment]
I just added a keybinding of `G` chord `D`, with the when expression:
```
editorTextFocus && vim.active && !inDebugRepl
```

Not sure if it has unintentional side effects, but it worked fine for me.

**Comment by johnyoonh** [comment]
This might help in the meantime: https://marketplace.visualstudio.com/items?itemName=Fr43nk.seito-openfile

**Comment by J-Fields** [comment]
I made `gx` just act as an alias for `editor.action.openLink` - if that's insufficient for someone's use case, please file a separate ticket
