### ISSUE TITLE
try to configure keybinding -> told key combination doesn't exist

### ISSUE THREAD

**Issue by chris-schmitz** [VSCodeVim/Vim#4520]
**Describe the bug**
When I configure a key binding and try to use it I'm told that the key combination doesn't exist.

**To Reproduce**

1.  Open user settings
2.  Add in the following configuration:

```
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "<leader>",
        "l"
      ],
      "commands": [
        "workbench.action.focusRightGroup"
      ]
    }
  ]
```

3.  Open two editor groups (split panes)
4. Make sure your left group is active
5.  Try to use the `cmd+k l` to switch to the right group
6. See error message in the bottom bar:
![Screen Shot 2020-01-28 at 9 59 05 AM](https://user-images.githubusercontent.com/2437424/73281444-9ef58d00-41b5-11ea-8a83-1eb8c345ac7a.png)

**Expected behavior**
I expected that the right editor group would become the focus. and I'd be able to start editing in it's active file

**Screenshots**
![key binding errors](https://user-images.githubusercontent.com/2437424/73281677-f3007180-41b5-11ea-8ff6-c66049e70650.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.41.1
- OS: Mac 10.14.6

**Comment by sqlkoala** [comment]
Hi, do have set "cmd+k" as your leader for vim?
Afaik, that is used for many regular/nonvim keybindings and I dont think its a good idea to use it as leader. You should be able to create your keybinding like this (normal vscode way):
![grafik](https://user-images.githubusercontent.com/30384885/73287301-5bbd0d80-41f9-11ea-9cf3-be0b69e59a66.png)

**Comment by chris-schmitz** [comment]
Oh! interesting let me check.

**Comment by chris-schmitz** [comment]
🤦‍♀ Ah, yeah the leader key in my vim config is `\`.

![Screen Shot 2020-01-28 at 11 38 10 AM](https://user-images.githubusercontent.com/2437424/73289724-d3bc1100-41c2-11ea-8f60-d75981903c8b.png)

I didn't realize that regular vscode had leader keys, and when I look at my keyboard shortcuts it's obvious :P 

![Screen Shot 2020-01-28 at 11 39 02 AM](https://user-images.githubusercontent.com/2437424/73289787-efbfb280-41c2-11ea-9417-8c4365b77d93.png)

Thanks for pointing this out!!! It's interesting, my pane navigation worked months ago. I assumed it was just something that the vim extension added in. I'm remembering now that it "stopped working" after a vscode update. In that update either my shortcut bindings must have been reset or that specific binding must have changed. 

Thanks again!

**Comment by sqlkoala** [comment]
Bitte, kein Problem ;-)
