### ISSUE TITLE
Consider using VSCode's type command to improve multicursor support 

### ISSUE THREAD

**Issue by cvaldev** [VSCodeVim/Vim#4522]
**Is your feature request related to a problem? Please describe.**
There are many issues with the extension's poor multicursor support, but one of the most annoying ones is that it breaks snippets and auto-completion. On single cursor mode the extension passes over the text to the `default: type` command through `TextEditor.insert()`, this way vscode has control over the text input and can do stuff like auto-completion, snippet mode, closing brackets, etc. 

Multiple cursors, however, are handled differently. `vscode.TextEditorEdit.insert()` is used instead, which doesn't allow vscode to do its regular stuff that it'd do on text insertion by default. 

**Describe the solution you'd like**
Use the `default: type` command to process text insertion on multicursor mode like it is used on single cursor mode.

**Describe alternatives you've considered**
Here is a rudimentary prototype of my suggestion that solves issues like #4281, #4515, #4223.

```ts
if (this.vimState.isMultiCursor
      && otherTransformations[0]?.type === 'insertTextVSCode'
      && otherTransformations.every(t => t?.type === 'insertTextVSCode')) {

        const { text } = otherTransformations[0];
        vscode.commands.executeCommand('default:type', { text });

} else {
// The regular way we handle `otherTransformations`
}
```
VSCode's `type` command handles replicating what happens at the first cursor on the other cursors, and unless I'm wrong we can't do things like place `x` at cursor[0] and `y` at cursor[1] so there is no need to create an edit for each individual cursor as long as we know they're all the same.

I believe a better solution would be to introduce a new transformation (`MulticursorInsert`) that can know the cursor position like `InsertTextTransformation`, but is processed similarly to an `InsertTextVSCodeTransformation`. 

**Additional context**
Before getting any further into it I'd like to know if this would be a welcomed change. I could submit a WIP PR if that's the case.

**Comment by alessod** [comment]
Another similar issue from 2017 https://github.com/VSCodeVim/Vim/issues/1946

**Comment by trkoch** [comment]
I too have observed a couple of issues and I'd really appreciate any improvements to the multicursor support. Can I help?

**Comment by J-Fields** [comment]
@cvaldev This seems very reasonable, though there could obviously be unforeseen consequences. A WIP pull request would be great, thanks as always for digging into these thorny issues!

> Can I help?

Pull requests are always welcome, and I'm happy to provide guidance where it's needed. I agree multicursor support is a bit lacking.
