### ISSUE TITLE
 Invalid neovimPath

### ISSUE THREAD

**Issue by danielo515** [VSCodeVim/Vim#4529]
Issue Type: <b>Bug</b>

Hello again 😄,
I just enabled neovim integration and I'm getting the following error:

```
Invalid neovimPath. spawn /usr/local/bin/nvim
ENOENT.
```

If I type that path on my console neovim just starts without problem so, what else can I do to fix it?
Regards

Extension version: 1.12.4
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by danielo515** [comment]
This was totally mi fault.
Today I was going to edit the config file to try a different path (the provided one is a symlink) and noticed there is a space between the first quote and the actual path, so it was `" /usr/local/bin/nvim"`. Removing that space made it work.
This is embarrassing, but hopefully will make other people check their whitespaces better.
Sorry about it.

**Comment by vegerot** [comment]
To be fair, typing ` nvim` in bash or zsh does work.  Would it not be just a simple "why not" feature to strip `neovimPath`?
