### ISSUE TITLE
provide visual feedback when <c-r> is pressed in insert mode

### ISSUE THREAD

**Issue by danielo515** [VSCodeVim/Vim#4531]
**Is your feature request related to a problem? Please describe.**
When you hit <c-r> in vim it, by default, shows a `"` in the place where you are to indicate that you should  select a register to paste from. 

**Describe the solution you'd like**
I want the same visual feedback in neovim.

**Describe alternatives you've considered**
As an alternative, something on the bottom bar could be displayed.

**Additional context**
This is what you see in vim:

![image](https://user-images.githubusercontent.com/2270425/73564146-45b08680-445f-11ea-9f41-61f42068333f.png)

**Comment by J-Fields** [comment]
Closing as this was implemented a while back

**Comment by danielo515** [comment]
What was te final solution?
