### ISSUE TITLE
Passing Esc to VSC

### ISSUE THREAD

**Issue by Twiggeh** [VSCodeVim/Vim#4534]
**Is your feature request related to a problem? Please describe.**
Probably configuration error, can't pass ESC to VSC, meaning I can't escape out of snippets :(

setting settings.json 
```
  "vim.handleKeys": {
    "<C-f>": false,
    "<C-w>": false,
    "<Esc>": false
  },
```
doesn't help. (I know it is not in the package.json)

**Describe the solution you'd like**
I would like to be able to pass esc back to vscode

**Describe alternatives you've considered**
Tabbing through the snippet & then going through every "filling in" step
Rebinding ESC to command "leaveSnippet" (currently what I am doing )

**Additional context**
-none-

**Comment by trkoch** [comment]
Have you tried `shift-esc` to cancel snippets?
