### ISSUE TITLE
Visual inside block (`vip`) not support?

### ISSUE THREAD

**Issue by iampkuhz** [VSCodeVim/Vim#4537]
hi, all. When I successively type 3 keys(v-i-p) in vscode vim mode, it doesn't viusal inside the paragraph as expected. How can I make this?

**Comment by J-Fields** [comment]
`vip` should work. What text are you trying it on?

**Comment by iampkuhz** [comment]
> `vip` should work. What text are you trying it on?

all text cannot work.

By the way, ` vi[`, `vi{`, `viw` all works fine.

Is it a shortcut confilict? how can I debug this?

**Comment by J-Fields** [comment]
Hmm. Do `cip` or `dip` work? Do you have .vimrc support enabled?

**Comment by iampkuhz** [comment]
both not work.
BTW, `ci[` and `di[` works fine. 

My vim in terminal works fine with `vip`.

**Comment by J-Fields** [comment]
Are you still seeing this issue @iampkuhz? If so, can you please provide your config?

**Comment by iampkuhz** [comment]
> Are you still seeing this issue @iampkuhz? If so, can you please provide your config?

hi, `vip` now works fine for me. thanks.
