### ISSUE TITLE
Ctrl+Backspace in Search/Command entry deletes document

### ISSUE THREAD

**Issue by B0sh** [VSCodeVim/Vim#4538]
When typing in a command with `/` or `:`, using `Ctrl+Backspace` deletes a whole word from your current position in the document. 

`Backspace` works correctly, but expected behavior is that `Ctrl+Backspace` should delete a whole word in the command. It's really tricky to fix your errors you just made if you did this too because you're still typing in the command and have to decide whether to abandon your command or back out and fix .

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.12.4`
- OS Version: `Windows_NT x64 10.0.16299`
- VSCode version: `1.41.1`

**Comment by J-Fields** [comment]
As a workaround, you can use `<C-w>`, but I agree - this has annoyed me in the past.
