### ISSUE TITLE
Search and replace problem

### ISSUE THREAD

**Issue by philipatc** [VSCodeVim/Vim#4540]
I've try the same regex statement is work in gvim but not on vim plugin

- I using visual mode to select the text
- then I try the command : `:'<,'>s/^\n//g`     # I want to replace the blank line with nil, aka remove the blank line
- VS Code show Tailing Character error

I'm not sure what happen, anyone had idea?

**Comment by sqlkoala** [comment]
Hi, I tried the search pattern. Problem is probably: `\n` is not implemented by vscodevim (my guess is that \n is not provided is js regex). This pattern `/^\r/` (r is CR) matches empty lines, but the replace does not work then.
But the proper way to do this is a global (g) like so (this requires neovim integration):
`:'<,'>g/^$/d`

**Comment by andrecasal** [comment]
Keep in mind that VS Code Vim only support JS Regex. It does not use the same Vim regex engine.

**Comment by systemovich** [comment]
Thanks @andrecasal ! It has been driving me crazy.

**Comment by J-Fields** [comment]
Related: #3996. It would be a very heavy lift that is probably not worth doing (at least in the near term)

**Comment by J-Fields** [comment]
Closing in favor of #3996
