### ISSUE TITLE
nnoremap

### ISSUE THREAD

**Issue by teyter** [VSCodeVim/Vim#4542]
I am trying to achieve the effect of this setting from vimrc in vscodevim

```
nnoremap : :

nnoremap ; :
```

This enables me to press the ; key to enter command mode in one key stroke as opposed to two  i.e. just ; rather than Shift + ;

I tried doing this in settings.json with this:

```    
"vim.normalModeKeyBindings": [
        {
            "before": [":"],
            "after": [":"]
        }
    ]

    "vim.normalModeKeyBindings": [
        {
            "before": [";"],
            "after": [":"]
        }
    ]
```

To no effect. Is there a way to achieve this?

**Comment by cvaldev** [comment]
I think this is what you're looking for:

```json
    "vim.normalModeKeyBindings": [
        {
            "before": [";"],
            "after": [":"]
        }
    ]
```

**Comment by teyter** [comment]
That did it. Much obliged.
