### ISSUE TITLE
Can we support textobj-parameter plugin please ??

### ISSUE THREAD

**Issue by skywind3000** [VSCodeVim/Vim#4543]
Can we support [textobj-parameter](https://github.com/sgur/vim-textobj-parameter) ??

It is the best textobj plugin which enables me to modify function arguments and any comma separated list items in a fast way.

Usage
-----

-   `i,` to inner parameter object

    ```vim
    function(param_a, param_b, param_c)
             |<--->|  |<--->|  |<--->|
    ```

-   `a,` to a parameter object including whitespaces and comma

    ```vim
    function(param_a, param_b, param_c)
             |<----->|
    function(param_a, param_b, param_c)
                    |<----->|
    function(param_a, param_b, param_c)
                             |<----->|
    ```

-   In addition, 'i2,' is similar to `a,` except trailing whitespace characters (especially for first parameter)

    ```vim
    function(param_a, param_b, param_c)
             |<---->|
    ```

It is something really hold me back from moving to vscode.

**Comment by J-Fields** [comment]
#2338

**Comment by J-Fields** [comment]
Closing in favor of #2338. There is an open PR for this feature (#4653), so hopefully it'll be in a near-future release.
