### ISSUE TITLE
vim esc

### ISSUE THREAD

**Issue by 1235452356** [VSCodeVim/Vim#4547]
In my computer, caps is coverted to esc, but in vscode clicking caps is invalid. 

my operating system is arch-lts, destop is deepin. modify command is 

gsettings set com.deepin.dde.keyboard layout-options '["caps:escape"]'

**Comment by aswathkk** [comment]
This is some issue wrt VSCode.
I was able to resolve this issue by adding `"keyboard.dispatch": "keyCode"` to VSCode settings and restarting it.
 Refer https://github.com/microsoft/vscode/issues/23991

**Comment by jpoon** [comment]
Thanks @aswathkk . Same issue as https://github.com/VSCodeVim/Vim/issues/4350.
