### ISSUE TITLE
CamelCaseMotion is not compatible with dot command

### ISSUE THREAD

**Issue by tranhl** [VSCodeVim/Vim#4552]
**Describe the bug**
Instead of repeating the last camel case motion (e.g. `<leader>w`), the dot command instead repeats the last command before the camel case motion.

**To Reproduce**
1. Create a new file
2. Type `camelCaseMotion` into file
3. Ensure cursor is at the start of the line
4. Press `<leader>w`
5. Press `.`

**Expected behavior**
Cursor is positioned on 'M' character.

**Screenshots**
Video of issue: https://streamable.com/m9chf

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.42
- OS: MacOS 10.14.4

**Comment by sqlkoala** [comment]
Hi, this is not a bug.
Vims dot command is supposed to repeat the last "text change" (insert/ delete/ change/paste).
It is not supposed to repeat the last motion.

**Comment by sqlkoala** [comment]
Btw, I understand the use case. It is "annoying" to press two keys to move through a word in camel steps.
The right way to integrate this with vim would be an option that ,/; repeat a camel step (IMO).

**Comment by tranhl** [comment]
Thanks for the clarification, I'll look into some alternative ways to handle this use case. Closing due to not being a bug.

**Comment by tranhl** [comment]
Good news, luckily it's possible to customize VSCode Vim's normal mode bindings to trigger camel case motions with a single key:

```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "w"
      ],
      "after": [
        "<leader>",
        "w"
      ]
    }
  ],
```

This is a feasible alternative, and does what I want.
