### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vbonesi** [VSCodeVim/Vim#4554]
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.12.4`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jpoon** [comment]
>  We have written the needed data into your clipboard. Please paste! 

Missing information.
