### ISSUE TITLE
Plugin does not work on VSCode 1.42.0

### ISSUE THREAD

**Issue by bajatin** [VSCodeVim/Vim#4555]
**Describe the bug**
The extension does not work at all.The status bar says `--NORMAL--` but the editor works like it would without the extension.Rolling back to previous versions or deleting the extension folder and reinstalling do not work.

**To Reproduce**

   1.    Install version 1.42.0 of VS Code 
   2.    Install the Vim plugin
   3.    Observe that Vim bindings aren't active
   4.    Run Toggle Vim Mode in the command palette. Observe that the error message         `command 'toggleVim' not found` appear.

**Expected behavior**
Vim bindings should work.

**Environment (please complete the following information):**
VSCode version : 1.42.0
Vim version : 1.12.4
OS:  Ubuntu 18.04

**Additional context**
The problem is same as #4340 and #4342 but rolling back or deleting extension folder does not work.

**Comment by shamil614** [comment]
I'm having the same problems

**Comment by shamil614** [comment]
Actually the problem for me seems to be another extension. 🤷‍♂ 
I changed the ElixirLS extension to `0.2.19` and Vim just worked.

**Comment by bajatin** [comment]
Oh it worked! It was just an indentation extension but removing it worked.
Thanks alot @shamil614
