### ISSUE TITLE
Bug: Multicursor - normal mode - yank word

### ISSUE THREAD

**Issue by sql-koala** [VSCodeVim/Vim#4562]
**Describe the bug**
There is a small bug in normal Mode for multicursor, in combination of yank a word (ye, yw). These keys exit multicursor mode.

**To Reproduce**

1.
Have a text like this:
```
foo bar baz
foo bar baz
```

2. create two cursors on any word
3. exit visual / selection using `v`, so you are in normal mode with multicursor
4. goto begin of a word and press `ye` or `yw`
5. multicursor mode is exited

**Expected behavior**
Mode should stay normal with multicursor and word correctly yanked.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: latest
- OS: win7 64

There is a workaround: (use yiw) and it is only with yanking (ce or de work), so it is not a big deal imho.
Can another user try a repro, please?

**Comment by ldm0** [comment]
Currently the multicursor mode is just not usable, it still needs implementation. :-/
