### ISSUE TITLE
Camel case motion breaks some leader+key+key combinations

### ISSUE THREAD

**Issue by Peluko** [VSCodeVim/Vim#4563]
**Describe the bug**
When ```"vim.camelCaseMotion.enable": true```, some leader+key+key combinations won't work. I use them for Spacemacs emulation. For example:

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<leader>",
                "b",
                "b"
            ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.showAllEditors",
                    "args": []
                }
            ]
        },
    ],
```
won't work, although

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<leader>",
                "b"
            ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.showAllEditors",
                    "args": []
                }
            ]
        },
    ],
```

Works flawlessly and

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<leader>",
                "p",
                "b"
            ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.showAllEditors",
                    "args": []
                }
            ]
        },
    ],
```
also works. It only happens with some leader plus two keys combinations. For example, any leader+b+key or leader+e+key combinations won't work, but leader+p+key or leader+t+key works perfectly.

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.42.1
- OS: Windows 10 Pro 1909

**Comment by sqlkoala** [comment]
Hi,
this is a more general case. AFAIK, vscodevim keybindings need to be 100% percent unambigous. Meaning: when camelcase-motion uses "leader b", then there can't be other two char keybindings that start with "leader b".
I don't know if there are plans to support that, but my guess is you would have to wait quiet some time.

**Comment by J-Fields** [comment]
> AFAIK, vscodevim keybindings need to be 100% percent unambigous

I believe this is correct. I've been meaning to dig into it for a while now, but I'm mostly unfamiliar with the relevant part of the code base.

**Comment by sqlkoala** [comment]
PS: notice it is not just 100% unambigous, but 100% percent :D

**Comment by Peluko** [comment]
Any easy way to remap camel case keys?

**Comment by babygau** [comment]
i got exactly the same problem. hope it will be fixed soon!
