### ISSUE TITLE
[Engineering] Tab Size or Spaces

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#457]
This is about the code we write. I'm seeing different styles about tab or space. In some files we are using two spaces indentation but in others we are using four spaces. Or even sometimes we see Tab instead of soft Tab. 

We have several more active contributors in this near week so I'm thinking that we might need put Tab/Space stuff into the Style Guide.

When we write VS Code, we use Tab instead of space but personally I prefer space. It's up you :)

**Comment by sectioneight** [comment]
I've also been tripped up on this in this project. Hopefully once settled we can also enforce this in travis :)

**Comment by jpoon** [comment]
Spaces for me. I even added a gulp `fix-whitespace` that should have been converting the tabs to spaces on -- I guess this isn't working?

**Comment by sectioneight** [comment]
I haven't noticed any hard tabs myself, but definitely inconsistency
between 2 and 4 spaces

**Comment by jpoon** [comment]
Unfortunately, TSLint does not yet have this capability (https://github.com/palantir/tslint/issues/581).

**Comment by johnfn** [comment]
Probably my fault! I'm not very sensitive to differences in spacing. PRs welcomed from anyone who wants to convert the project uniformly to 2 space tabs.

**Comment by rebornix** [comment]
Fixed by https://github.com/VSCodeVim/Vim/pull/460 and I add this config to Workspace setting then no one will get it wrong.

The funny thing is, we are using 2 space tab in action.ts but 4 space tab in almost all others.

**Comment by jpoon** [comment]
Added a couple more configs to the workspace setting: https://github.com/VSCodeVim/Vim/commit/33e529033baef0fbfd34984daad3ae4a0b13a865

**Comment by jpoon** [comment]
I think we're good here. Closing this issue. Thanks for the fix @rebornix.
