### ISSUE TITLE
can't select text 

### ISSUE THREAD

**Issue by xiaoouwang** [VSCodeVim/Vim#4572]
**Describe the bug**

Each time I select some text the selection just shrinks to the end position, it's really annoying.

**To Reproduce**

![keyboard](https://user-images.githubusercontent.com/16024291/75046578-a9a9f600-54c5-11ea-8ebb-bcd1e0a08220.gif)

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS: Mac

**Additional context**

**Comment by J-Fields** [comment]
Could you please confirm that this behavior still exists after disabling all other extensions?

**Comment by xiaoouwang** [comment]
> Could you please confirm that this behavior still exists after disabling all other extensions?

@J-Fields 
yes. Check the gif below.
![keyboard2](https://user-images.githubusercontent.com/16024291/75053637-eb409e00-54d1-11ea-876a-5a25cfcd5b96.gif)

**Comment by J-Fields** [comment]
Cool, I appreciate that! The selection is getting removed right when you release LMB and you're not pressing anything else? If you don't mind, could you show me your settings?

**Comment by xiaoouwang** [comment]
`  "vim.mouseSelectionGoesIntoVisualMode": false,
  "vim.gdefault": true,
  "vim.leader": "<space>",
  "vim.useSystemClipboard": true,
  "vim.hlsearch": true,
  "vim.statusBarColorControl": true,
  "vim.startInInsertMode": false,
  "vim.searchHighlightColor": "rgba(255,153,153,0.3)",
  "workbench.colorCustomizations": {
    "statusBar.background": "#005f5f",
    "statusBar.noFolderBackground": "#005f5f",
    "statusBar.debuggingBackground": "#005f5f"
  },
  "vim.sneak": false,
  "vim.incsearch": true,
  "vim.useCtrlKeys": true,
  // "vim.cursorStylePerMode.normal": "line",
  "vim.easymotion": true,
  "vim.foldfix": true,
  "vim.cursorStylePerMode.insert": "line-thin",
  "vim.cursorStylePerMode.visual": "block",
  "vim.debug.silent": false,
  "vim.sneakUseIgnorecaseAndSmartcase": true,`

I've played aroung all the possible combinations still it doesn't resolve the bug. :D

**Comment by xiaoouwang** [comment]
well the bug has mysteriously disappeared. The only thing that I did is an upgrade to Catalina 10.15.3

Hope it helps anyone having this same bug-like issue.

**Comment by jasonperhaps** [comment]
This is caused by eudic which will automatically capture the selected txt and will cause the problem as shown above. After shutdown eudic, text selection works normally.
