### ISSUE TITLE
Using backticks ` ( or ´) breaks surround

### ISSUE THREAD

**Issue by Twiggeh** [VSCodeVim/Vim#4574]
**Describe the bug**
Using any surround input removes a line or a paragraph after surround breaks,

**To Reproduce**

(If the vid is longer than 3 mins the issue starts at 1:48, if its smaller than 3 mins then the issue starts at the beginning :) )
[Video Tutorial](https://youtu.be/38W7yFDjm60)

1.  using ` or ´ in surround input mode breaks surround
2. ds, cs removes line

**Expected behavior**
Shouldn't work sometimes but all of the time

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.42.1
- OS: Win10 
- Keyboard: German Keyboard

**Comment by mladenuzelac** [comment]
And many more characters break CS and DS, any other than the standard one. 
I tried to change * to _ and I couldn't. It seems that only basic ones are supported.

**Comment by mysterybear** [comment]
can we get an option/setting for this?

**Comment by mladenuzelac** [comment]
> can we get an option/setting for this?

If you really need something like this you can set up neovim with Visual studio code and surround plugin for vim by tpope

**Comment by J-Fields** [comment]
I believe this should be resolved in the next release - if not, please let me know
