### ISSUE TITLE
map "o" to open file (like "l")

### ISSUE THREAD

**Issue by andrestone** [VSCodeVim/Vim#4575]
Hello, 

When navigating in the file explorer, I'm used to using "o" (like in nerdtree) to open files. Is there a way to set this behavior on VSCodeVim?

Thanks.

**Comment by sqlkoala** [comment]
This here in keybindings.json should to what you want:
```
    {
        "key": "o",
        "command": "explorer.openToSide",
        "when": "explorerViewletFocus && explorerViewletVisible && !inputFocus"
    },
```
As a general rule: when you want to control VSCode outside the editor window, you need to define vscode keybindings. The tricky part is that they do not interfere with vim (you achieve that with the when condition.)

**Comment by sqlkoala** [comment]
This is the command you need to define/modify:
![grafik](https://user-images.githubusercontent.com/30384885/75253139-429a8300-57de-11ea-9af1-adef969522df.png)

**Comment by andrestone** [comment]
Thanks!
