### ISSUE TITLE
Viewport position is not restored after a search is canceled or not found

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#4577]
1. `incsearch` should be enabled
2. `gg` in a long file
3. `L` to go to the bottom of the viewport
4. Type a search for a term only present at the bottom of the document (don't press enter)
5. Cancel the search with `<Esc>` (or keep typing such that nothing is found)
6. Notice the viewport's position is not the same as after step 3

**Comment by J-Fields** [comment]
This was fixed for a canceled search, but not a search not found

**Comment by rishadomar** [comment]
Just confirming if this is the same issue I'm experiencing:

1) Search for a text that is not found
2) Message displayed: E486: Pattern not found: <text here>
3) Pressing slash again SHOULD have taken me back to search again but instead the key is ignored.

By the way: great job with the showing of which string was not found! Previously, it didn't show which string it was so a typo in the string was difficult to spot.

**Comment by J-Fields** [comment]
@rishadomar No, that's a separate problem - would you mind filing an issue?
