### ISSUE TITLE
<C-v> in insert mode does not overwrite selected text

### ISSUE THREAD

**Issue by ShadyAlfred** [VSCodeVim/Vim#4589]
Sometimes I select stuff with mouse (yikes I know) to replace them with stuff I copied. But when I paste, the stuff gets appended instead of replacing my selection. The replacing works fine when I use the vim visual mode and hit `p`, but in inserting mode it doesn't. Is it possible to have the normal VS Code pasting command when selecting stuff in inserting mode?

**Comment by J-Fields** [comment]
>Sometimes I select stuff with mouse

Begone, heathen! 🙂 

Actually, `<C-v>` insert mode pastes for me, and I think it does out of the box. Could you confirm what OS you're on, and post your settings please?

**Comment by ShadyAlfred** [comment]
Yes, it works out of the box. The issue is when I highlight or select stuff in insert mode then paste, it doesn't replace the selection with the stuff I pasted, but appends them to my selection.

I'm using Windows 10 (yikes again 😂)

**Comment by J-Fields** [comment]
Ah! Sorry, I'd misread the original post. This isn't something I do, I guess, because I can easily reproduce this. I'll take a look now, since I suspect it'll be a quick fix.

**Comment by ShadyAlfred** [comment]
A fix could be switching to visual mode when selecting with the mouse, I have the setting `Mouse Selection Goes Into Visual Mode` checked, but when I select with the mouse in insert mode it stays in insert mode.

**Comment by J-Fields** [comment]
If that's your preferred behavior, feel free to file another issue, but in the next release it'll be fixed while staying in insert mode.

**Comment by ShadyAlfred** [comment]
No, it was just a suggestion if it was easier to implement. I didn't mean to cause much headache, sorry.

**Comment by J-Fields** [comment]
No worries, just wanted to make sure that wasn't your preference (I think it's also a reasonable approach)

**Comment by d9k** [comment]
```json
 "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": [
        "p",
      ],
      "after": [
        "\"",
        "_",
        "x",
        "P"
      ]
    },
    {
      "before": [
        "x",
      ],
      "after": [
        "\"",
        "_",
        "x",
      ]
    },
```

**Comment by Wikiwix** [comment]
@J-Fields It looks like the problem returned. In 1.29.0 I have exactly the behaviour described in this Issue.

**Comment by Lslightly** [comment]
@Wikiwix changing the `when` condition of `extension.vim_ctrl+v` command in keyboard shortcuts to `editorTextFocus && vim.active && vim.use<C-v> && !inDebugRepl && vim.mode != 'Insert'` might help.

**Comment by Lslightly** [comment]
> [@Lslightly](https://github.com/Lslightly) That helped. Thank you! Do you want to (as you came up with the fix) or should I prepare a PR?

<C-v> has [special meaning](https://unix.stackexchange.com/questions/366869/what-does-ctrlv-do-in-vim) in insert mode. But in current scenario, change the `when` condition might be more natural. I think modifying the documentation is enough.
