### ISSUE TITLE
Error after using ')' navigation at the end of the file.

### ISSUE THREAD

**Issue by ZaymonFC** [VSCodeVim/Vim#4591]
**Describe the bug**
Error after using ')' navigation at the end of the file.

**To Reproduce**
1. Press `)` to navigate till the end of the file.
2. Press `)` once more:

```
TaskQueue: Error running task. Failed to handle key=). This should never happen....
```

**Expected behavior**
No-op.

** Environment **
- Extension (VsCodeVim) version: 1.12.4
- VSCode version: 1.42.1
- OS: MacOS Catalina 10.15.3

**Comment by J-Fields** [comment]
Gotta love an error message like that. Thanks for the report
