### ISSUE TITLE
Extension doesn't work at all after update

### ISSUE THREAD

**Issue by madetara** [VSCodeVim/Vim#4599]
**Describe the bug**
I know "doesn't work at all" is a bad type of issue but that's exactly what happened after updating to 1.13.0. 
It seems like extension fails to load.

On 1.12.4 however everything works fine

**To Reproduce**

1.  Startup VS Code
2.  Update VIM extension to 1.13.0
3.  It fails to load

**Expected behavior**
It is expected to run

**Environment (please complete the following information):**

```
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by J-Fields** [comment]
Try uninstalling, deleting the extension folder, and reinstalling

**Comment by madetara** [comment]
It helped. Thank you!
