### ISSUE TITLE
Feature: Vim surround option to surround without spaces for bracket types

### ISSUE THREAD

**Issue by admosity** [VSCodeVim/Vim#4605]
**Is your feature request related to a problem? Please describe.**
When surrounding with bracket types `[`, `{`, `(`, `]`, `}`, `)` there is an extra space between. I work with some languages/frameworks (Angular) that factor in the spacing. 

**Describe the solution you'd like**
Have an option like `vim.surroundBracketSpace` that can be toggled for including or excluding the space.

**Describe alternatives you've considered**
I have to word back, remove the space, word forward, remove the space...

**Comment by HawkinsT** [comment]
This actually depends on if you use an open or close bracket. Open brackets give the extra space you're seeing.

**Comment by J-Fields** [comment]
Yep, as documented [here](https://github.com/tpope/vim-surround)

**Comment by admosity** [comment]
Wow. Sorry for opening this and thanks! My life has been changed for the better.
