### ISSUE TITLE
`dd` raises error when vim.startofline is false

### ISSUE THREAD

**Issue by MartyBeGood** [VSCodeVim/Vim#4607]
**Describe the bug**
'dd' (and possibly other deletion operations) raises an error and makes the editor hang when vim.startofline is set to false
VSCode(Vim) eats all keypresses after this error. Sometimes for ~2 seconds, sometimes until you reposition the cursor using the mouse.
This does not occur when `vim.startofline` is set to true (default)

Trace from Developer Console is:
```
console.ts:137 [Extension Host] TaskQueue: error: Error running task. Failed to handle key=d. Unknown PositionDiffType: 2.
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:582
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:582
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
```

**To Reproduce**

1. set `"vim.startofline": false` in settings
1. Open any file
2.  delete a line using 'dd'
3.  Observe the Issue

**Expected behavior**
line should be deleted, I should be able to continue editing as usual, No error should occur

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.13.0 (can't reproduce with <1.13.0)
- VSCode version: Tried with Code-OSS (arch repos) 1.41.1, VSCodium 1.42.1, VSCode (official) 1.42.1
- OS: Manjaro 19.0

**Comment by fk1blow** [comment]
this happens to me as well:
* OS: windows 10 x64
* VSCode version: official 1.42.1
* VsCodeVim: 1.13.0

the only thing i can do is to switch to another file/tap or wait for at least 2 seconds(sometimes even more)

**Comment by gnmonsour** [comment]
This may be trivial or a telling side-effect but I'd like to add with this behaviour the `Suppress Errors` action here: 
![image](https://user-images.githubusercontent.com/6868261/75905189-7135e080-5e12-11ea-8a3b-2aac6831d473.png)
has no impact suppressing subsequent error messages.

**Comment by J-Fields** [comment]
@gnmonsour No, that shouldn't be related. Could you file a new issue?

**Comment by J-Fields** [comment]
This error will be fixed in the next release. It doesn't behave like it should (the cursor goes to the very beginning of the line), but as far as I can tell, that was always a problem. I'll file a new issue.
