### ISSUE TITLE
Remap keys not working

### ISSUE THREAD

**Issue by ichirou2910** [VSCodeVim/Vim#4612]
I'm using VSCodium and VSCodeVim both latest stable version in Arch Linux

**Short report**: Global keyboard rebinding doesn't work on VSCodeVim.

**Full report**:
I swapped ESC and Caps Lock with this command line
`linux> setxkbmap -option caps:swapescape`
The swapping works just fine with Arch Linux in general and specifically VSCodium, but when it comes to Vim the swapping didn't work, which mean I still have to press ESC to return to Normal Mode, and that's eqivalent to Caps Lock to my machine.
The main reason I swapped them is to switch mode more comfortably. Is there any way to fix this problem?

**Comment by andrewharvey** [comment]
Can replicate on Debian too, first time I've ever seen the remapping not work, so perhaps this is incorrectly detecting the physical key location instead of the logical key based on the keyboard layout...

**Comment by andrewharvey** [comment]
sorry just realised this is a duplicate of #854 and #2859 and is actually a vscode issue https://github.com/microsoft/vscode/issues/23991 with a workaround at https://github.com/microsoft/vscode/issues/23991#issuecomment-292336504

**Comment by ichirou2910** [comment]
Thank you. I couldn't find those issues. I will close this now.
