### ISSUE TITLE
Vim not enabled at all

### ISSUE THREAD

**Issue by nickbrooking** [VSCodeVim/Vim#4615]
**Describe the bug**
Opened VSCode today and Vim mode not working at all. It's as if the extension is totally disabled.

**To Reproduce**
I assume just installing the latest version of VSCodeVim (1.13.0) is what caused it. It worked fine last week and I didn't change anything.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.13.0
- VSCode version: 1.42.1
- OS: Windows 10 Enterprise (1809)

**Comment by J-Fields** [comment]
Try uninstalling, deleting the extension folder, and reinstalling

**Comment by nickbrooking** [comment]
Thanks, that actually did resolve my issue. It is working properly now.

**Comment by J-Fields** [comment]
It happens to a few people every update, not sure why
