### ISSUE TITLE
Escape not returning to normal mode from insert mode

### ISSUE THREAD

**Issue by GetJoot** [VSCodeVim/Vim#4616]
Issue Type: <b>Bug</b>

1) Enable Vim exstension.
2) Open any text document.
3) Properly move cursor using Vim movement keys.
4) Enter Vim edit mode by pressing 'i' or 'a' etc., and type some text.
5) Press 'esc' to return to Vim movement mode.
6) Vim does not return to movement mode as expected, but remains in edit mode.

Steps 1-5 may work the very first time, but do not work as expected when repeated in the same document.

Extension version: 1.13.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 11|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by harmsk** [comment]
I am also having the same problem. Developer tools console in VS Code produces the following:
```
abstractExtensionService.ts:396 Activating extension 'vscodevim.vim' failed: Cannot find module 'winston-transport'
Require stack:
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/src/util/logger.js
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/src/cmd_line/commands/file.js
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/src/jumps/jumpTracker.js
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/src/state/globalState.js
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/src/mode/mode.js
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/src/common/motion/position.js
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/src/actions/operator.js
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/src/actions/include-all.js
- /home/harmsk/.vscode/extensions/vscodevim.vim-1.13.0/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js.
_logMessageInConsole @ abstractExtensionService.ts:396
```

Extension version: 1.13.0
VS Code Version: 1.42.1
OS: Linux x64 5.5.7-200.fc31.x86_64

**Comment by atcheson-aws** [comment]
I saw this behaviour on extension version 1.13.1 and rolling back to 1.13.0 fixed it.

**Comment by J-Fields** [comment]
Is anyone still experiencing this?

**Comment by GetJoot** [comment]
I am no longer experiencing this.  Thank you!

**Comment by J-Fields** [comment]
Closing the issue, holler if it's still a problem for you

**Comment by olegkamuz** [comment]
Same here. I have remapped esc with capslock long time ago(can't remember whether it is internal keyboard memory or in ubuntu itself, but xev in terminal capslock button gets me "keycode 66 (keysym 0xff1b, Escape)", and my capslock button works as esc flawlessly in original vim, in vim mode on pycharm and idea.

Extension version: 1.26.0
VS Code version: Code 1.82.1 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d,  2023-09-14T05:51:20.981Z)
OS version: Ubuntu x64 20.04.6
