### ISSUE TITLE
Screen scrolls with cursor if code is folded

### ISSUE THREAD

**Issue by siddharth-krishna** [VSCodeVim/Vim#4643]
**Describe the bug**
With the Vim extension enabled, if I have a file open where I've folded some block of code (that I can see on screen) and my cursor is below this folded block, then moving my cursor up and down lines also makes the screen move. The screen moves so that the cursor is always in the center. This happens in both insert and visual modes. However, this does not happen if my cursor is above the folded block of code, and it stops when the folded block moves out of view.

This causes the screen to jump around, and is quite distracting.

**To Reproduce**

1.  Open any file with blocks of code that can be folded, and that is long enough. For example, open a new file and copy the following block into it 100 times:
```
test
  test test
  test test test
  test test

```
2.  Scroll to the middle of the file, and then fold one of the blocks.
3.  Now place the cursor below the folded block, and try to move the cursor downwards.
4.  See error.

**Expected behavior**
I expect the cursor to move down, but the screen/view to stay the same. Instead, the screen/view scrolls down, and the cursor remains in the center of the screen.

**Environment**

- Extension (VsCodeVim) version: 1.13.0
- VSCode version: 1.43.0
- OS: Windows 10

**Comment by anhtukhtn** [comment]
I have this issue too. I have to switch to use simple Vim when waiting it's fixed

**Comment by tuledev** [comment]
Downgrade Vim to 1.12.4 fix the issue 
https://github.com/VSCodeVim/Vim/issues/4632
