### ISSUE TITLE
Make snazzy animated gifs for README

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#465]
Pretty much exactly like the ones in #448, except ideally they would be showing the functionality we have that works rather than the functionality we have that _doesn't_ work. 😉

**Comment by cswartzvi** [comment]
Hi, I was the one that created #448. I've been looking for a way to contribute to this awesome project, and as I only have a rudimentary knowledge of typescript at the moment, perhaps I could start here. What sort of functionality were you looking to showcase? General ideas like motions and text manipulations or everything currently supported in the roadmap (might make for a long read).

**Comment by johnfn** [comment]
@cswartzvi, that would be awesome!

I think we probably only need 2-3 animated gifs, just to grab people's attention. Generally speaking, the snazzier, the better. :wink: Maybe some of the following:

* using /abc to find "abc", then using cwblah&lt;esc&gt; to turn it into "blah" and then n.n. a few times to show off dot and n.
* select a few lines of text, delete and then paste them somewhere else

Or whatever else you can think of.

**Comment by jpoon** [comment]
I wasn't able to get [ScreenKey](https://github.com/wavexx/screenkey) to work on Mac. I did find an alternative: https://github.com/keycastr/keycastr

**Comment by jpoon** [comment]
Meh, minor impact. Closing issue.
