### ISSUE TITLE
Cancelled searches should be added to history

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#4650]
`/foobar<Esc>`, then `/<C-p>`. Notice "foobar" does not show up.

**Comment by vikashgaya916** [comment]
Hi, I would like to work on this issue, but I am complete newb to this. Can someone help me get started?

**Comment by J-Fields** [comment]
@vikashgaya916 `SearchState` hold the state associated with a search. `GlobalState.addSearchStateToHistory()` does what you'd expect. Seems like we need to call this whenever a search is canceled (`CommandInsertInSearchMode`).
