### ISSUE TITLE
Start vscode cannot be input

### ISSUE THREAD

**Issue by jxnczyp** [VSCodeVim/Vim#4654]
![image](https://user-images.githubusercontent.com/5689673/76718660-6e23e400-6772-11ea-8ac3-2b79ebdcdd4f.png)

**Comment by jxnczyp** [comment]
TaskQueue: Error running task. getLineLength() called with out-of-bounds line 48.

**Comment by jxnczyp** [comment]
TaskQueue: Error running task. Cannot read property 'document' of undefined.

**Comment by J-Fields** [comment]
Please provide more info (what did you do which caused these errors?)
