### ISSUE TITLE
Unable to bind <S-J>

### ISSUE THREAD

**Issue by matejdro** [VSCodeVim/Vim#4655]
**Describe the bug**
Shift + J does not appear to be bindable. No matter what I try to do, it always joins lines.

**To Reproduce**
Add binding:

```json
        {
            "before": [
                "<S-j>"
            ],
            "after": [
                "j"
            ]
        },
```

**Expected behavior**
VS should just move down a line (as binding commands), but instead, it executes default join.

- Extension Version: `1.13.0`
- OS Version: `Linux x64 5.5.8-1-MANJARO`
- VSCode version: `1.42.1`

**Comment by J-Fields** [comment]
`J`, not `<S-j>`

**Comment by matejdro** [comment]
`J` is also not working, I forgot to mention this in the original post.

**Comment by tecfu** [comment]
Since the syntax is vim is

```json
{
 "before": ["<S-j>"],
 "commands": []
}
```
but the working syntax is:

```json
{
 "before": ["J"],
 "commands": []
}
```

Let's add that to the documentation in a prominent place.

**Comment by matejdro** [comment]
As I mentioned, J is also not working, at least in my case.

**Comment by tecfu** [comment]
@matejdro What environment are you running? 

Here's a link to my [settings.json](https://github.com/tecfu/.vim/blob/server/settings.json). With this configuration, I've been able to bind to "J".

Here's my environment, I'm guessing you're on a Mac or Windows.
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-53-generic
Vim 1.14.5
```

**Comment by matejdro** [comment]
I've retested this and it started working. Not sure what exactly was wrong (could be something from my side or maybe you fixed it in the meantime). Thanks for the info.

**Comment by kyprifog** [comment]
This seems really unexepected, I would feel like the settings.json should at least try to resemble what is being done in a normal vimrc, <S-j> seems more "cannonical"
