### ISSUE TITLE
`/` ignored after failed search

### ISSUE THREAD

**Issue by rendaw** [VSCodeVim/Vim#4658]
**Describe the bug**
@rishadomar reported it at the link but I couldn't find a separate ticket yet and have the same issue, so opening here.  https://github.com/VSCodeVim/Vim/issues/4577#issuecomment-595271474

**To Reproduce**

1. Search for a text that is not found
2. Message displayed: E486: Pattern not found:
3. Press slash

**Expected behavior**
Pressing slash again SHOULD have taken me back to search again but instead the key is ignored.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.13.0
- VSCode version: 1.41.0
- OS: Linux

**Comment by skplunkerin** [comment]
This isn't  exclusive to typing "`/`" after failed search, it's actually "everything" is ignored. For example, after you fail a search, try doing any of the following, all of these are blocked (and there's probably more):

- `/`
- 
- 
- 
-

**Comment by skplunkerin** [comment]
This isn't  exclusive to typing "`/`" after failed search, it's actually "everything" is ignored. For example, after you fail a search, try doing any of the following, all of these are blocked (and there's probably more):

- `/` (start new search)
- `j`, `k`, `h`, `l` (go down, up, etc...)
- `gt`, `gT` (tab navigation)
- `ctrl+e`, `ctrl+y`, `ctrl+d`, `ctrl+u` (scrolling/jumping down/up)
- `u`, `ctrl+r` (undo, redo)
- etc...

**Comment by vlad2135** [comment]
Very annoying bug, please prioritize it's fix.

**Comment by rishadomar** [comment]
Eeek I didn't mean to click on [CLOSE]. How can I un-close?

**Comment by rendaw** [comment]
@rishadomar I think this is closed because the issue has been fixed (March 22).

**Comment by grigoryvp** [comment]
Yes, it's fixed in the latest version.
