### ISSUE TITLE
format selection == doesn't work with rust

### ISSUE THREAD

**Issue by guihao-liang** [VSCodeVim/Vim#4659]
**Is your feature request related to a problem? Please describe.**
I want to format the selected code with = key for rust lang.

**Describe the solution you'd like**
select code and use == to format code. In normal mode, just =G to format all. I hope `rustfmt` can be supported by vscodevim!

**Describe alternatives you've considered**
I'm using vscode plugin `rust-lang.rust` and I need to use `editor.formatOnSave` to format all codes.

**Comment by J-Fields** [comment]
This is likely a bug/limitation of the rust plugin. When `==` is pressed, we just select the line(s) and call `editor.action.formatSelection`, which is handled by the language server plugin. Can you try calling that command yourself and see what happens?

**Comment by guihao-liang** [comment]
> This is likely a bug/limitation of the rust plugin. When `==` is pressed, we just select the line(s) and call `editor.action.formatSelection`, which is handled by the language server plugin. Can you try calling that command yourself and see what happens?

Thanks for the prompt reply! Could you guide me on how to call that command? Thanks!

**Comment by J-Fields** [comment]
Open the command palette (`ctrl+shift+P` by default) and type "format selection"

**Comment by guihao-liang** [comment]
![image](https://user-images.githubusercontent.com/14238915/77120608-8015b900-69f6-11ea-9b6d-c2d6657f02ef.png)

Well, there no such operation. That's weird. Is it override by `rust-lang.rust`?

**Comment by guihao-liang** [comment]
I tried with a python file and I can find the `format selection` command option.

**Comment by J-Fields** [comment]
This probably means the rust formatter only supports formatting entire files (I know python's `black` formatter is the same way). I found https://github.com/rust-lang/rustfmt/issues/434 which led me to https://github.com/rust-lang/rustfmt/issues/3397. In any case, this doesn't seem to be the fault of VSCodeVim so I'll close the issue.

**Comment by Anstow** [comment]
In case others stumble upon this like I have. You can now get this to work using rust-analyzer and opting into the nightly version of rustfmt. You can do this in two steps. Firstly, install the nightly version of rustfmt
```$ rustup toolchain install nightly```
Secondly, enable this in the rust-analyzer plugin by adding the following to your settings.json:
```
{
    "rust-analyzer.rustfmt.rangeFormatting.enable": true,
    "rust-analyzer.rustfmt.extraArgs": [
        "+nightly"
    ]
}
```

**Comment by futscdav** [comment]
The option is now spelled `"rust-analyzer.rustfmt.enableRangeFormatting": true`
