### ISSUE TITLE
Consider using `TextEditor.document.version` rather than `mightChangeDocument`, etc.

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#4665]
Reading through the code in `SearchState._recalculateSearchRanges`, something caught my eye. We're using [TextDocument.version](https://code.visualstudio.com/api/references/vscode-api#TextDocument) to decide whether we need to recalculate the search ranges. Couldn't we just use this instead of messing around with `mightChangeDocument`? (I was unaware that this information was provided by VSCode's API until today). This might give a performance boost (as `mightChangeDocument` can naturally give false positives) while also reducing complexity.

Would love input from @cvaldev 

Relates to #4451

**Comment by cvaldev** [comment]
Thank you for bringing this up. I had a misunderstanding of how `TextDocument.version` worked, for some reason I had assumed it only changed on a save event. After re-reading the docs and playing with it for a bit, I agree with you that replacing `mightChangeDocument` with a version check could be a positive change.

Maybe we could add a version check as part of the `HistoryTracker._isDocumentTextNeeded()` logic?
