### ISSUE TITLE
Remap ciw cio <esc><esc>

### ISSUE THREAD

**Issue by diegonogueira** [VSCodeVim/Vim#4674]
I'm trying to remap those maps using settings.json or vimrc. No success :(

X = operator (c,d,v)

[X]iw -> ci<leader>w
[X]io -> ciw

esc esc -> :nohl<cr>

Thanks

**Comment by J-Fields** [comment]
I think the former will require operator-pending mode remapping (#3086)

Can you show the remaps you're trying to use? I believe the `:nohl` one is doable

**Comment by diegonogueira** [comment]
I'm trying to remap:

1) Change default (w/b) to camelcase motion:
All "w" command to: <leader>w

2) Create a new command operator "o" to full word ( default w behavior )

3) Esc Esc to remove highlight (nohl)

Example:

```
onoremap io iw
xnoremap io iw
````
