### ISSUE TITLE
Support for :delm[arks]

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#4682]
Documentation is [here](http://vimdoc.sourceforge.net/htmldoc/motion.html#:delmarks)

**Comment by someoneigna** [comment]
Hey, wanted to let you know I started working on it: https://github.com/VSCodeVim/Vim/compare/master...someoneigna:delmarks
 
Will update with the tests in a few hours. I'll surely need some remarks on the style of the project and TS-JS recommendations too. I'm all ears! 👍

**Comment by J-Fields** [comment]
Nice! Feel free to put a PR up even before it's 100% done
