### ISSUE TITLE
Copy the current line tag and its children with the command yat

### ISSUE THREAD

**Issue by calebeaires** [VSCodeVim/Vim#4685]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I want yank the entire html tag typing `yat` but instead copy the tag that starts on the current line and its children tags, it copy the entire parent html tag.

**Describe the solution you'd like**
type `yat` and copy the tag within the current line

```html
<div class="dont-copy-parent">

<!--  yat --> | <div class="want-copy-this">
                  <div>Content</div>
             </div>

</div>
```

Vim and neoVIM do this job

**Comment by gergelyth** [comment]
I think this is solved by considering the tag starting on the current line, when the cursor is in a position you described. Check out #4721
