### ISSUE TITLE
extension fails to load after recent update 

### ISSUE THREAD

**Issue by Glavnokoman** [VSCodeVim/Vim#4688]
**Describe the bug**
extension is apparently not loaded. Issuing 'ctrl+shift+p',  'toggle vim mode' results in "command 'toggleVim' not found" message. The plugin is enabled but does not show up in the 'show running extensions'.

**To Reproduce**
open visual studio code. see the vim extension not functioning

**Expected behavior**
vim extension functioning

**Screenshots**
**Environment (please complete the following information):**
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-25T01:43:18.461Z
Electron: 7.1.14
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.11-arch1-1
Vim: 1.13.1
all vim related settings are disabled.

**Additional context**
stopped working about a week ago, maybe less.

**Comment by J-Fields** [comment]
Uninstall, delete extension directory, reinstall

**Comment by Glavnokoman** [comment]
worked. Thanks!
