### ISSUE TITLE
1.13.1 adding doublequote to beginning of word freezes extension

### ISSUE THREAD

**Issue by MikeCongdon1** [VSCodeVim/Vim#4692]
**Describe the bug**
Shift A locks the extension host and I have to disable vim after clicking shift A in yml file.

**To Reproduce**

1. open kubernetes config yml file (not extension cloud code or anything).
2. find name: and add doublequote to beginning of name. 
3. Press shift-A to get to end of line.  -- or w.
3. Extension Server freezes.

**Expected behavior**
I expect adding doublequotes at beginning of word to not be a problem in yml files.
It appears that my workaround for now is to always add doublequote to end of word first.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.13.0  & 1.13.1
- VSCode version: 1.43.2 0ba0ca52957102ca3527cf479571617f0de6ed50  x64

- OS: Ubuntu 19.10

**Additional context**
This is while editing yml files primarily - with no space at end of line.

**Comment by J-Fields** [comment]
Your reproduction steps are a bit unclear to me. Would you mind showing a small file that you can reproduce on, and tell me the exact keystrokes?

**Comment by MikeCongdon1** [comment]
Certainly!
![image](https://user-images.githubusercontent.com/11522648/77774129-90dab600-7018-11ea-8e22-d63ee8fdd9cb.png)



Though, I actually dug more into this & it appears that it is exclusively with yml files.  (my .pl files still operate fine - even in the same instance of vscode)
So, I'm going to all it a performance issue with my yaml extension instead.
Apologies for misdirected bug & time wasted.
