### ISSUE TITLE
C++ for loop snippets now working well

### ISSUE THREAD

**Issue by NIRVANALAN** [VSCodeVim/Vim#4694]
**Describe the bug**

- Other extensions you installed (and if the issue persists after disabling them):
- Does this issue involve using SSH remote to run the extension on a remote machine?: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is 
**Steps to reproduce**

1. create a cpp files with main function
2. type for and generate a for snippet
3. press tab once to locate on the looper name(i by default)
4. use backspace to delete the looper variable
then it comes:
```
for (size_t 0; i < count; i++)
 {
/* code */
}
```
what it should be:
```
for (size_t  = 0;  < count; ++)
{
    /* code */
}

```
**Environment (please complete the following information):**

- Extension (VsCodeVim) version: latest
- VSCode version:
- OS and Version: Deepin 15.11
- VS Code Version: latest

** additional information
This snippet works well when VIM extension is disabled

**Comment by J-Fields** [comment]
Ha! Good timing. This has been a known issue for a long time, but just a few hours ago a fix was merged into master (https://github.com/VSCodeVim/Vim/pull/4570). It'll be in the next release.
