### ISSUE TITLE
cannot use "n" when searching

### ISSUE THREAD

**Issue by ps1118** [VSCodeVim/Vim#470]
When using "/" to search, I can not use "n" to find next, and "N" to find the previous. How should I do?

**Comment by jpoon** [comment]
@ps1118 can you elaborate on what you see instead? Specifically, what do you see in the bottom right corner (the status bar)? 

Are you running the latest version of VSCode and the extension?

**Comment by ps1118** [comment]
I just press "/" to search like in vim, but when I press 'n' or 'N', the charactor appears in the input area.

**Comment by ps1118** [comment]
It seems like ok, thank you.
