### ISSUE TITLE
Need to type `<Esc>` twice to get into command line mode

### ISSUE THREAD

**Issue by xcity** [VSCodeVim/Vim#4700]
**Describe the bug**
Every time, I need to type ESC twice to get into command line mode after search, insert, or something. Is it a config I can set to override this? 

**To Reproduce**
No specific action to trigger it, just go into insert mode or search mode. 

**Expected behavior**
One click of ESC to get into command line mode no matter which previous mode we are in. 

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by J-Fields** [comment]
Could you clarify? You insert something, press `<Esc>` to get back into normal mode, then hit `:` to go into command line mode, and it doesn't work?
