### ISSUE TITLE
TaskQueue: Error running task. Failed to handle key=:. Action 'q:' changed the document unexpectedly!.

### ISSUE THREAD

**Issue by FreeVTS** [VSCodeVim/Vim#4701]
**Describe the bug**
After calling the command history, I got the following message in vscode : "TaskQueue: Error running task. Failed to handle key=:. Action 'q:' changed the document unexpectedly!." Source: Vim (Extension)

**To Reproduce**
1. Vim must be in command mode.
2. Type 'q' following by ':' and the "command history" show up on top of the app.
3. Choose any of the command in the list
4. A popup message come from the bottom right of vscode with the error message.

**Expected behavior**
The same way as if I type ":his" i.e. the same behaviour without the error message

**Screenshots**

![vimextension](https://user-images.githubusercontent.com/26015006/77911882-91b15900-725f-11ea-9d21-1650001e26fb.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.13.1
- VSCode version: 1.43.2 (user setup)
- OS: Windows_NT x64 10.0.17763 (as described in the vscode about box)

VS code about box information :
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by J-Fields** [comment]
Thanks for the report! This relates to an optimization that will be removed in the next release (we found a better way to do it). Apologies for the error message in the meantime - I'm trying to get a new release out soon.
