### ISSUE TITLE
Save registers between restarts

### ISSUE THREAD

**Issue by acicovic** [VSCodeVim/Vim#4704]
**Is your feature request related to a problem? Please describe.**
When VSCode closes, VSCodeVim clears the registers.

**Describe the solution you'd like**
It would be nice to save the registers between restarts, or have a setting to control this behavior.

**Comment by acicovic** [comment]
Possibly related: #2380

**Comment by J-Fields** [comment]
Yeah, this is possibly a duplicate of #2380. I did attempt this at one point, but it got messy because we sometimes store plain text in registers, and sometimes store more complex data representing a macro, essentially.
