### ISSUE TITLE
By default bind <C-w>= to workbench.action.evenEditorWidths

### ISSUE THREAD

**Issue by crajun** [VSCodeVim/Vim#4706]
I've added the native Vim command to do the equivalent in VSCode via: 

`"vim.normalModeKeyBindingsNonRecursive": [
        { 
          "before": ["<C-w>", "="],
          "commands": ["workbench.action.evenEditorWidths"]
        },
]
`
Quickly manually tested opening and resizing all kinds of different splits both horizontal and vertical, and VSCode handled it all.

I'm not familiar with Typescript or how the PRs for default keybindings work, so I'll let someone else submit a PR for this.

**Comment by uloco** [comment]
This is already default ...
