### ISSUE TITLE
.vimrc cannot remap keys in replace mode

### ISSUE THREAD

**Issue by awesomehaze** [VSCodeVim/Vim#4707]
**Is your feature request related to a problem? Please describe.**

Using a .vimrc file, I am unable to remap keys for replace mode as one would in regular vim.
eg: inoremap a b works in insert mode, but not in its variant, replace mode.

**Describe the solution you'd like**
I would like support for remapping keys in replace mode from a .vimrc file.

**Describe alternatives you've considered**
I've considered using the built in settings to remap keys, but I would have to remap every key that I have a custom mapping for in my .vimrc.

**Comment by berknam** [comment]
@awesomehaze I believe this is now possible on the latest versions. Can you test it and see if it still is an issue?

*PS: remember that we don't actually parse the .vimrc file. We only go through it looking for remap lines. So if you have any remap inside a conditional `if` block that shouldn't be applied, we will still read it and try to apply it.*

**Comment by awesomehaze** [comment]
Seems to be fixed, thanks for the help!
