### ISSUE TITLE
ci' does not delete between single quotes and enter insert mode

### ISSUE THREAD

**Issue by michaeltarleton** [VSCodeVim/Vim#471]
### What did you do?

1. Placed the cursor on some text inside two single quotes (ie. 'testing test')
2. Pressed: ci'

### What did you expect to happen?

1. Delete what's inside the single quotes
2. Enter insert mode

### What happened instead?

Nothing

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.2
* OS: OSX

**Comment by michaeltarleton** [comment]
amVim extension works as expected

**Comment by johnfn** [comment]
This is already working on master (thanks @sectioneight). We'll have it out in the next release, which should be coming to a VSCode near you.

You can also try out master yourself, if you want..

**Comment by johnfn** [comment]
Annnnnd now we have version 0.1.3. I did say "soon", didn't I?

**Comment by sectioneight** [comment]
I implemented most, but not quotes yet :/

**Comment by michaeltarleton** [comment]
Thx guys for all your work on this project. Since quotes aren't done yet this should be reopened.

**Comment by sectioneight** [comment]
Yea, @johnfn please re-open and assign to me. I'll likely have time to tackle this this week.
