### ISSUE TITLE
Tab stretching out cursor in normal mode

### ISSUE THREAD

**Issue by nwaywood** [VSCodeVim/Vim#4712]
**Describe the bug**
This is what the cursor normally looks like:

![image](https://user-images.githubusercontent.com/3773641/78198178-79e20b00-74d3-11ea-85c8-273cf504d12b.png)

However, if the cursor is at the position of a tab character, it gets stretched out to the width of the tab:

![image](https://user-images.githubusercontent.com/3773641/78198222-967e4300-74d3-11ea-86f7-81d1d7206af1.png)

which is not how the cursor behaves in Vim

I'm not sure if this is a bug or a feature. But it it's a feature, is there a way to disable it?

Thanks

**Comment by J-Fields** [comment]
> I'm not sure if this is a bug or a feature

It's a feature of VSCode. I like it, but I can see why you don't.

> is there a way to disable it?

I don't think so. We definitely don't have control over it, though, so I'd open an issue in the [VSCode repo](https://github.com/microsoft/vscode) if I were you
