### ISSUE TITLE
Mapping `<shift-tab>` does not work, need `<shift+tab>`

### ISSUE THREAD

**Issue by maxnordlund** [VSCodeVim/Vim#4719]
**Describe the bug**
First let me thank you for this amazing extension. It made me switch from neovim to VS Code. I use it pretty much every day and only had minor issues with multiple-cursors (which I think should be expected and totally fine).

Today I found something a bit more vexing: To be able to use `<shift-tab>` in mappings, instead of `<shift+tab>`. Noticed the dash in the first, and the plus sign in the second mapping.

**To Reproduce**
Given an config like this:

```json
{
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "Tab"
            ],
            "commands": [
                "editor.action.indentLines"
            ]
        },
        {
            "before": [
                "<shift+tab>"
            ],
            "commands": [
                "editor.action.outdentLines"
            ]
        },
        {
            "before": [
                "<C-a>"
            ],
            "commands": [
                "cursorLineStart"
            ]
        },
        {
            "before": [
                "<C-e>"
            ],
            "commands": [
                "cursorLineEnd"
            ]
        }
    ]
}
```

Pressing `Shift+Tab` works like expected. But if you change it like so:

```json
            "before": [
                "<shift-tab>"
            ],
```

It stops working, without giving some sort of warning like if you miss the `s` in `commands`. Also not that `<C-?>` style mappings work fine and vanilla vim uses `<S-?>`/<`Shift-?>`.

**Expected behavior**
To be able to use dash in all mappings, or perhaps both dash and plus sign.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.13.1
- VSCode version: 1.43.2
- OS: MacOS X Catalina

**Additional context**
This really bit me and took a lot of time to debug. Ended up sprinkling `this._logger` calls in the extension before realizing my mistake/the bug.

**Comment by maxnordlund** [comment]
Just noticed that `<Tab>` does not work but `Tab` and `<tab>` does. I guess the normalization in `remapper.js` does not like it. The question is what should the behavior be?

**Comment by J-Fields** [comment]
Ah, sorry about this. We should probably be more aggressive in normalizing sane inputs to valid ones.

**Comment by tcd** [comment]
Any update on or workaround for this?

**Comment by berknam** [comment]
Interesting! I never noticed this but the "Shift+Tab" key combination was added to the 'package.json' file in order to be captured, but it was never added to the 'notation.ts' in order to be properly normalized. I suspect, from looking into the change log, this key combination was added in order to be used in command line mode only for the autocomplete. However, since we are capturing it it is being handled by the remapper as well, but it is not normalized so it always arrives as being `<shift+tab>`, that's why that is the only possible combination that works.

I will try to fix this soon.
