### ISSUE TITLE
In visual mode, $ will go to the next line not stay in the same line

### ISSUE THREAD

**Issue by w93163red** [VSCodeVim/Vim#4726]
**Describe the bug**
In visual mode, $ will go to the next line not stay in the same line. However, in the vim, it will stay at the end of line (last character at this line)
**To Reproduce**
1. go to visual mode
2. type `$`
**Expected behavior**
It should stay at the end of the line (last character of this line)
**Screenshots**
![image](https://user-images.githubusercontent.com/7308728/78853778-bb9c1580-79ed-11ea-9d2f-5bf3edc35def.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.13.1
- Version: 1.44.0
- Commit: 2aae1f26c72891c399f860409176fe435a154b13
- Date: 2020-04-08T08:23:56.137Z
- Electron: 7.1.11
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.4.0

**Comment by J-Fields** [comment]
What you're seeing is the EOL character being selected - that's how VSCode renders it. This is expected behavior.

**Comment by w93163red** [comment]
> What you're seeing is the EOL character being selected - that's how VSCode renders it. This is expected behavior.
 
Is there a setting to change that?

**Comment by J-Fields** [comment]
I don't believe so. A few have brought this up in the past; I'm not sure if any already filed a ticket in the VSCode repo, but that's probably your best bet.

**Comment by glarione** [comment]
use `g_` motion instead of `$`

so `cg_` or `vg_`
