### ISSUE TITLE
Enable `:set number` or `:se nu!`

### ISSUE THREAD

**Issue by keidarcy** [VSCodeVim/Vim#4732]
**Is your feature request related to a problem? Please describe.**
Lack of a quick way to toggle line number like `:se nu` and `:se nonu`.

**Describe the solution you'd like**
Just like what we do in vim

**Additional context**
Toggle with `"editor.lineNumbers": "off"` and `"editor.lineNumbers": "on"` in `settings.json`.

**Comment by J-Fields** [comment]
`:se number` and `:se nonumber` work, but I can see wanting the shorthand.

**Comment by xyyolab** [comment]
Oh, thanks! That's helpful!
Do you want to add this description to `ROADMAP` or `README`? I can't find it anywhere. If I miss something, sorry about that.
Btw, if you work on this, add `se rnu!` for relative number, please!

**Comment by J-Fields** [comment]
Duplicate of #5368, will be fixed in next release
