### ISSUE TITLE
.vimrc: Cannot map key to a command of an extension

### ISSUE THREAD

**Issue by mkrawiec** [VSCodeVim/Vim#4733]
**Describe the bug**
The functionality of mapping a key to a command in `.vimrc` works only for builtin commands. When an action is provided by a plugin, instead of executing it, the command is inserted literally. 

**To Reproduce**
This mapping will work:
    
    nnoremap <leader>sa workbench.action.findInFiles

This will not work:

    nnoremap <leader>conf vim.editVimrc
    nnoremap <leader>ren fileutils.renameFile

**Expected behavior**
User should be able to map any action to a key

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.13.1
- VSCode version: 1.44
- OS: Linux

**Comment by sqlkoala** [comment]
Hi, you could create the keybindings you want by adapting 4th example here:
https://github.com/VSCodeVim/Vim/blob/master/README.md#key-remapping
(I know this is more effort than the new, convenient style with .vimrc).

If you look at your example, there is now way to syntactically distinguish the right side "fileutils.renameFile" from a series of vim keystrokes/commands.
