### ISSUE TITLE
VSCodeVim seems don't support full text matching

### ISSUE THREAD

**Issue by oldmtn** [VSCodeVim/Vim#4736]
e.g.
If I want to search a text 'localStream', I will type a search word like:
/\<localStream\>
but it don't work.

**Comment by J-Fields** [comment]
I assume this is a difference between vim and JS regex? #3996

**Comment by sqlkoala** [comment]
Hi, yes this it is.
The js regex would be: ``\blocalStream\b``, (\b  is a word boundary, which is \\< or \\> in vim).

@oldmtn 
But you can use the js regex with vims search.

@J-Fields 
I was a bit suprised to see that vscodevim directly "pastes" the vim pattern into a js regex (more or less). It would be possible to "translate" a vim pattern to js regex, in cases like this ( where js regex offers a functional equivalent, just with different syntax).
VsVim does this,but it is some amount of work.

**Comment by oldmtn** [comment]
> Hi, yes this it is.
> The js regex would be: `\blocalStream\b`, (\b is a word boundary, which is \< or \> in vim).
> 
> @oldmtn
> But you can use the js regex with vims search.
> 
> @J-Fields
> I was a bit suprised to see that vscodevim directly "pastes" the vim pattern into a js regex (more or less). It would be possible to "translate" a vim pattern to js regex, in cases like this ( where js regex offers a functional equivalent, just with different syntax).
> VsVim does this,but it is some amount of work.

Thanks for you help.
'\blocalStream\b' is work for me.
