### ISSUE TITLE
Enable expression register "=	

### ISSUE THREAD

**Issue by qywangoh** [VSCodeVim/Vim#4738]
I would very like to have expression register "=  in VSCodeVim
It is especially useful when you are in insert mode, and do <C-r> = to do small calculations. 

Documentation can be found here
[http://vimdoc.sourceforge.net/htmldoc/change.html#quote=](http://vimdoc.sourceforge.net/htmldoc/change.html#quote=)

**Comment by J-Fields** [comment]
#4383
