### ISSUE TITLE
Can I load .vimrc from a WSL path?

### ISSUE THREAD

**Issue by Dinduks** [VSCodeVim/Vim#4740]
Hi,

This is more a question than an issue: I have my dotfiles installed in my WSL installation, and was wondering if it'd be possible to load them straight from there.

This is what my config looks like:

```json
{
    "vim.vimrc.enable": true,
    "vim.vimrc.path": "\\\\wsl$\\Arch\\home\\dinduks\\.vimrc",
}
```

The interesting thing is that I don't get the `No .vimrc found at ...` error, but the configuration doesn't seem loaded neither (my key remaps don't work).

This is my dotfiles: https://github.com/Dinduks/dotfiles/blob/master/vim/.vimrc

Thank you for any assistance!

**Comment by Dinduks** [comment]
I figured why it wasn't working: `~/.vimrc` is a symbolic link and Windows doesn't seem to be able to resolve them; I can't read the file using the symlink whether in Code or any other Windows app.  
Using the absolute path worked!

**Comment by choikangjae** [comment]
The absolute path's example is like this:
\\wsl$\Ubuntu\home\{username}\.vimrc

**Comment by afonsosalbrecht** [comment]
> The absolute path's example is like this: \wsl$\Ubuntu\home\{username}\.vimrc

that doens't work for me. 

I tried all the below paths and none of them are found by vscode:

`\\wsl.localhost\Ubuntu\home\{username}\.vimrc`
`\wsl$\Ubuntu\home\{username}\.vimrc`

**Comment by A0A** [comment]
Having the same issue; the path that explorer.exe gets me from Ubuntu  bash can't be resolved by vs code.

**Comment by Karel-van-de-Plassche** [comment]
Same issue, no luck

**Comment by gsacavdm** [comment]
I ran into the same issue where the WSL path wasn't recognized, i.e.  `\\wsl$\Ubuntu\home\gsacavdm\.vimrc.`

I worked around this by creating a soft link to it like so:
```
mklink "C:\Users\gsacavdm\.vimrc" "\\wsl$\Ubuntu\home\gsacavdm\.vimrc"
```

And then providing the `C:\Users\gsacavdm\.vimrc` based path to the vim extension.
