### ISSUE TITLE
Move to line not working as expected

### ISSUE THREAD

**Issue by sigfriedCub1990** [VSCodeVim/Vim#4751]
Issue Type: <b>Bug</b>

When using the command `:23` to move the cursor to the line the cursor moves to the line but stays at the first column of that line. Normally, in Vim, when you move to the line it places the cursor above the first character of the word in that line.

Extension version: 1.13.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.41GB free)|
|Process Argv|-psn_0_954601|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by J-Fields** [comment]
It should really obey `startofline`.
