### ISSUE TITLE
bug substitution with parenthesis

### ISSUE THREAD

**Issue by jerabaul29** [VSCodeVim/Vim#4754]
Writing the following substitution:

```:%s/ ))/))/gc```

Produces error:

```
CommandLine: Error executing cmd=%s/ ))/))/gc. err=SyntaxError: Invalid regular expression: / ))/: Unmatched ')'.
```

while this works fine in Vim.

**Comment by J-Fields** [comment]
I think this is due to the fact we use javascript's regex engine, not an emulation of vim's. #3996

**Comment by J-Fields** [comment]
This will work as expected if you enable neovim integration.
