### ISSUE TITLE
Remapping `,` doesn't work

### ISSUE THREAD

**Issue by NightMachinary** [VSCodeVim/Vim#4756]
I have tried `{ "before":[",", "l" ], "commands": ["language-julia.executeJuliaCodeInREPL"]}, `, but `,` still does its default thing. How do I remap it?

**Comment by sqlkoala** [comment]
Hi, right now you cant create two key mappings, where the first key is an operator (c/d/...) or a motion.
In other words, for two key mappings, you need to start with: g_, z_, or `<leader>`.
And yes, I understand the use case ;-)

See something similar here:
https://github.com/VSCodeVim/Vim/issues/4563
