### ISSUE TITLE
Unable to create insert mode mapping using a backslash

### ISSUE THREAD

**Issue by benfranklin79** [VSCodeVim/Vim#4759]
**Describe the bug**
An insert mode key binding which involves a backslash as specified as either an `after` or a `before` simply simply does not work.

**To Reproduce**
Steps to reproduce the behavior for the before case:

1. Add the following item into the array value for the key "vim.insertModeKeyBindings":

```json
{
    "before": ["<Bslash>"],
    "after": ["`"]
}
```

2. Reload visual studio code
3. Create a new empty file and enter into insert mode
4. Type the backslash character
5. Note that nothing happens

Steps to reproduce the behavior for the `before case`:

Simply repeat the above steps with the exception that for step 2 you add the following to the settings:

```json
{
    "before": ["`"],
    "after": ["<Bslash>"]
}
```

I've also tried the above cases with <Bslash> replaced with \\\\ with the same results.

**Expected behavior**
When in insert mode and I type the character specified in the before I expect the character specified in the after to be output to the screen.

**Environment (please complete the following information):**

** System Information **
CPUs | Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (8 x 2300)
-- | --
GPU Status | 2d_canvas: unavailable_softwareflash_3d: disabled_softwareflash_stage3d: disabled_softwareflash_stage3d_baseline: disabled_softwaregpu_compositing: disabled_softwaremultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: disabled_offrasterization: disabled_softwareskia_renderer: disabled_off_okvideo_decode: disabled_softwareviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: unavailable_softwarewebgl2: unavailable_software
Load (avg) | undefined
Memory (System) | 32.00GB (20.34GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
vscode-eslint | dba | 2.1.5
gitlens | eam | 10.2.1
EditorConfig | Edi | 0.14.5
terminal | for | 0.0.10
terraform | mau | 1.4.0
csharp | ms- | 1.21.17
python | ms- | 2020.3.71659
remote-wsl | ms- | 0.44.2
powershell | ms- | 2020.4.0
vsliveshare | ms- | 1.0.2000
code-settings-sync | Sha | 3.4.3
vim | vsc | 1.13.1

- VSCode version: 1.44.2
- OS: Windows_NT x64 10.0.14393

**Comment by sqlkoala** [comment]
Hi, when you "encode" the backslash like this: 
``"before": ["\\"]``
it should work.

**Comment by benfranklin79** [comment]
I've corrected the issue. I've have tried "\\\\" for `before` or `after` but I forgot to escape the backslash when I first wrote the issue, apologies.

**Comment by berknam** [comment]
I tried the following and it works for me:
```
"vim.insertModeKeyBindings": [
    {
        "before": ["\\"],
        "after": ["`"]
    }
]
```
Is this happening just with the backslash? Can you try using other key or try the remapping in normal mode, like this: 
```
"vim.normalModeKeyBindings": [
    {
        "before": ["\\"],
        "after": ["i", "`"]
    }
]
```
this works for me too.

**Comment by berknam** [comment]
Do you have backslash set as your leader?
