### ISSUE TITLE
Redo <C-r> is not working

### ISSUE THREAD

**Issue by ronakg** [VSCodeVim/Vim#4763]
**Describe the bug**
Default `Redo` keybinding `<C-r>` is not working. Statusbar message says `Already at newest change.`.

**To Reproduce**

1. Create a new empty file
2. Switch to insert mode
3. Write `This is a test`
4. Switch to normal mode
5. Press `u` a few times to undo the writing
6. Press `<C-r>` a few times to redo the writing

**Expected behavior**
The text should reappear on step 6.

**Screenshots**

**Environment (please complete the following information):**

VSCode Vim version: 1.13.1
```
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (5 days ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```
**Additional context**

**Comment by ronakg** [comment]
Anyone?

**Comment by J-Fields** [comment]
I'm unable to reproduce 🤷
Can you post your settings?

**Comment by ronakg** [comment]
My `settings.json` file is here - https://github.com/ronakg/dotfiles/blob/master/vscode/settings.json

**Comment by matrixersp** [comment]
It should work if you remove this:
```json
 {
            "before": [
                "u"
            ],
            "commands": [
                "undo"
            ]
        },
```

**Comment by ronakg** [comment]
You're right. Without that the file status stays dirty even when I undo all the changes I did to a file. Using VS Code's native `undo` doesn't have this problem.

Is there a workaround?

**Comment by J-Fields** [comment]
You can map `u` to VSCode's undo and `<C-r>` to VSCode's redo, but that comes with its own issues.

There are long-term plans to integrate the changes we make into VSCode's native undo stack, but that will require some pretty heavy re-architecting, so it likely won't be done very soon.

**Comment by ronakg** [comment]
Thanks. I'll try this for a few days and see which one annoys me less. Dirty file status or unexpected undo stack unwinding.

**Comment by texasbruce** [comment]
I can reproduce the same. @J-Fields 's workaround works but it is bug
