### ISSUE TITLE
Deleting by paragraph removes 1 line too many

### ISSUE THREAD

**Issue by tobia** [VSCodeVim/Vim#477]
### What did you do?

```
hello
█
world

vs code
```

Press `d}` (delete one paragraph)
### What did you expect to happen?

```
hello

vs code
```
### What happened instead?

```
hello
vs code
```
### Technical details:
- VSCode Version: 1.3.1
- VsCodeVim Version: 0.1.3
- OS: Mac OS X 10.11.5

**Comment by tobia** [comment]
Addendum: I think this is related to VSCodeVim treating `d}` as a character selection instead of a line selection, even when the cursor is at the beginning of the line. See this other bug:

    hello

    █orld

    vs code

Press `y}p` (copy following paragraph, paste after)

Expected:

    hello

    world
    █orld

    vs code

Actual:

    hello

    w█orld
    orld

    vs code

(in these 3 examples the cursor `█` is over a `w`, I hope that's clear enough)

**Comment by johnfn** [comment]
Interesting hypothesis, but if we were treating } as a line-wise operator, then d} _should_ delete that final line! You can test this hypothesis by doing V}d, which should have the exact same behavior if } is linewise. 

I think the real solution here is actually 2 parts:
1. Treat { and } as linewise motions (so pasting works)
2. In an operator context, { and } should go one character back.

**Comment by johnfn** [comment]
This has been fixed, apparently
