### ISSUE TITLE
Vim causes VS Code "Multiple Cursor or Selection" Malfunction

### ISSUE THREAD

**Issue by FremdSprach** [VSCodeVim/Vim#4770]
Issue Type: <b>Bug</b>

The Vim Extension causes a random cursor jumping or fluttering when the number of selected cursors goes up, in other words, the cursor's behavior becomes unpredictable.

Other extensions are disabled except for VIM to identify this problem.

Extension version: 1.13.1
VS Code version: Code - Insiders 1.45.0-insider (a250df703de955a38aed427a917bce8278ab3331, 2020-04-24T10:02:48.114Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by agreco** [comment]
I have to concur, I think this problem has persisted for a while now

**Comment by FremdSprach** [comment]
Duplicate of #4834
