### ISSUE TITLE
Failed to  do word substitution in "vscodevim.vim" extension

### ISSUE THREAD

**Issue by mikesongming** [VSCodeVim/Vim#4772]
Issue Type: <b>Bug</b>

my python script has a line:

"cv2_h, cv2_w = cv2.imread(img_name).shape[:2]"

I want to replace "img_name" to "filename" by vim command ":s /img_name/filename". However, vscode failed with the message "E35: No previous regular expression"

Extension version: 1.13.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 17.7.0
Remote OS version: Linux x64 4.9.184-linuxkit
Remote OS version: Linux x64 3.10.0-1062.4.1.el7.x86_64

**Comment by J-Fields** [comment]
This works if you omit the space (`:s/img_name/filename`), though we should allow a space there.

**Comment by mikesongming** [comment]
done
