### ISSUE TITLE
Command 'O' does not indent automatically with an incomplete line

### ISSUE THREAD

**Issue by MrHate** [VSCodeVim/Vim#4781]
**Describe the bug**
As the title goes.

**To Reproduce**
1.  Code an incomplete line in a C++ source file(and it is indented);
2.  Press 'O';
3.  See error.

**Expected behavior**
Create a new line with the same indentation.

**Screenshots**
![屏幕录制2020-05-02-18 59 26](https://user-images.githubusercontent.com/23498065/80862433-a68e6b80-8ca7-11ea-8ab0-eea0cc5fbb98.gif)

**Environment**
- Extension (VsCodeVim) version: 1.13.1
- VSCode version: 1.44.2
- OS: macOS Catalina 10.15.4

**Comment by J-Fields** [comment]
This is ultimately caused by the same issue as https://github.com/VSCodeVim/Vim/issues/1017#issuecomment-569801348. `O` basically just calls `editor.action.insertLineBefore`, and the resulting indentation is determined by the language extension.
