### ISSUE TITLE
Quick switch to recently used editor

### ISSUE THREAD

**Issue by MarcoIeni** [VSCodeVim/Vim#4785]
**Is your feature request related to a problem? Please describe.**
I would like to quickly switch to the last editor

**Describe the solution you'd like**
I would like to assign what `<ctrl-tab>` does to `<leader-tab>`

**Describe alternatives you've considered**
Currently in my settings.json I have:
```
        {
            "before": ["<leader>", "<tab>"],
            "commands": ["workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup"]
        },
```
but I have to press enter in order to go to the next tab.

**Additional context**
In vim if you press `<Ctrl+shift+6>` or `<Ctrl+6>` you edit the previous file. I think that these key bindings are not present in VSCodeVim, right?

**Comment by EdwinVanRooij** [comment]
I'm looking for this exact functionality. Have you found a solution / alternative yet?

**Comment by MarcoIeni** [comment]
No, I just use ctrl tab 😂

**Comment by J-Fields** [comment]
`<C-6>` has been implemented for a while now. There's a bug in the current release which will be fixed in the next.

**Comment by EdwinVanRooij** [comment]
I noticed the extension was last updated 2 months ago:

![image](https://user-images.githubusercontent.com/16732313/147085687-5b58fbc2-513d-4328-91c6-5c10da2e33e1.png)

Any idea as to when the fix to this issue will be released onto the marketplace?
