### ISSUE TITLE
Key binding bug in 1.14.0

### ISSUE THREAD

**Issue by gaogaotiantian** [VSCodeVim/Vim#4793]
**Describe the bug**
I upgraded to 1.14.0 today and my key binding "jj" -> "<Esc>" is not working properly. When I type "jj", it will return to the command mode, but it will insert a "j" (and some times two "j"s). My VSCode is relatively clean without many plugins. 

I'm using Win 10 + WSL. 

I reverted to 1.13.1 and this bug went away. 

**To Reproduce**

Add the key binding code in settings.json:

    "vim.insertModeKeyBindings": [
        {
            "before": ["j", "j"],
            "after": ["<Esc>"]
        }
    ]

Edit code, go to insert mode and use "jj"

**Expected behavior**
No "j" is inserted, go back to command mode.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.0
- VSCode version: 1.44.2
- OS: Windows 10.0.18362

**Additional context**

**Comment by J-Fields** [comment]
Fixed in 1.14.1 (which is currently in the release pipeline, should be available soon)
