### ISSUE TITLE
Visual Block Append puts cursor left of right most column if any rows are short.

### ISSUE THREAD

**Issue by zolrath** [VSCodeVim/Vim#4795]
**Describe the bug**
When performing a Visual Block `<C-v>` mode selection with multiple rows/columns containing at least one line that is empty or ends before the right of the block selection, the cursor is placed one column to the left of the right most column when Appending `<Shift-A>`. 

**To Reproduce**

1.  Enter a document
2.  Enter visual block mode `<C-v>`
3.  Select multiple rows and columns, ensuring at least one row contains fewer characters than the right most column of the selection.
4.  Press `<Shift-A>`
5. The cursor will appear one column to the left of the selection.

**Expected behavior**
I would expect the multi-cursors to appear to the right of the visual block selection.

**Screenshots**
![Block Selection Issue](https://i.imgur.com/qxLl3ee.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.1
- VSCode version: 1.44.2
- OS: Windows 10

**Comment by J-Fields** [comment]
Vanilla vim will add spaces to shorter lines, so that everything lines up. A broken attempt to do this causes this problem as well as #4796. That's the behavior I'll try to replicate, though it does have the unintended side effect of adding those spaces even if nothing is typed. That can be dealt with separately, however.

**Comment by J-Fields** [comment]
Actually, not sure that this is caused by the same problem, but whatever 🤷

**Comment by zolrath** [comment]
Awesome, thanks for the quick turnaround on the two bugs! 🎉
