### ISSUE TITLE
% should move to end of matching set, not beginning

### ISSUE THREAD

**Issue by infogulch** [VSCodeVim/Vim#480]
Typing `%` moves the cursor to the opening matching set, not the close.

Where `_x_yz` represents the cursor on `x` in `xyz`, and → means pressing `%`.

Vim:
* `_t_his is (a {inner} test)` → `this is (a {inner} test_)_`
* `this is (_a_ {inner} test)` → `this is (a {inner_}_ test)`

VSCodeVim:
* `_t_his is (a {inner} test)` → `this is _(_a {inner} test)`
* `this is (_a_ {inner} test)` → `this is (a _{_inner} test)`

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.3
* OS: Windows 10 64 bit

**Comment by sectioneight** [comment]
I'm fixing this now
