### ISSUE TITLE
Cursor does not move horizontally after hitting shift+v

### ISSUE THREAD

**Issue by bnovc** [VSCodeVim/Vim#4803]
This works in normal vim and is very useful for brace matching and selecting blocks

e.g. if you have 

a {
b
c
d
}

You hit shift+v on a, then $ to the { then % to match the other brace

**Comment by J-Fields** [comment]
I was under the impression that this was impossible, but actually, I don't think it is. We use a sort of hack to get visual mode to render correctly, and we should be able to do something similar to allow moving horizontally in visual line mode...
