### ISSUE TITLE
:set hlsearch not working

### ISSUE THREAD

**Issue by jiangmouren** [VSCodeVim/Vim#481]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?
I was trying to ":set hlsearch"
### What did you expect to happen?
I would my expect my search would be highlighted. 
### What happened instead?
Not highlighted.
### Technical details:

* VSCode Version:1.3.1
* VsCodeVim Version: 0.1.3
* OS: Windows 10

**Comment by rebornix** [comment]
I'm working on the vimrc parsing, see https://github.com/VSCodeVim/Vim/issues/463 and I'll implement `set` command as well.

But I'm not sure yet if VS Code allows us to do highlighting through API. Will drop more info here later.

**Comment by jiangmouren** [comment]
Great! Thanks for the quick respond.

**Comment by johnfn** [comment]
Oh, VSCode totally allows you to do that. Not only that, but I actually already show all matches when you are typing with /, I just remove them when you finish. 

Should be really easy to add as an option 😄

**Comment by rebornix** [comment]
The option will be handled by me.

The question is @jiangmouren can you confirm what @johnfn mentioned, tge highlight should already be there.

**Comment by jiangmouren** [comment]
Well the answer is Yes and No.

It is true when you do a search with "/something", the searched patterns
will be highlighted right away(before you hit "enter"). But when you hit
"enter", the highlights go away.

What I really want is like in vim, after you hit "enter", all matched
patterns will be highlighted and then you see where they are in the file
and navigate through them.

Thank you guys!

**Comment by rebornix** [comment]
@jiangmouren just obseved Vim's behavior, it's beyond my expectation. When you enable `hlsearch` and run search, those matched keys will be hightlighted always untill you disable `hlsearch`, no matter what mode you are in. Another catch is Vim's search is incremental, this means after you search for something, `<esc>` wont' quit the search mode. It means if you keep typing chars into the document, newly matched keys will be highlighted and be added to the navigation list.

This is how Vim does and is it a good idea to have it the same way? Actually I'm suprised that you can't even quit a search.
