### ISSUE TITLE
editor.action.showHover undefined

### ISSUE THREAD

**Issue by DeathPoem** [VSCodeVim/Vim#4810]
**Describe the bug**

"editor.action.showHover undefined" when useing "vim.normalModeKeyBindingsNonRecursive".
But, when I tried 'gh', [refdoc](https://github.com/VSCodeVim/Vim/blob/master/README.md#-vscodevim-tricks) , got the hover, without undefined message.  "editor.action.showHover" should be supported as [doc](https://code.visualstudio.com/docs/getstarted/keybindings?source=post_page-----53053bbb59dd----------------------) describe.

**To Reproduce**

1. settings.json as following
```
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "leader",
                "p",
                "d"
            ],
            "commands": [
                {
                    "command": "editor.action.peekDefinition"
                }
            ]
        },
       {
            "before": [
                "leader",
                "s",
                "h"
            ],
            "commands": [
                {
                    "command": "editor.action.showHover"
                }
            ]
        }
]
```
2. It works fine for leader+p+d, but result in "editor.action.showHover undefined" for leader+s+h.

**Expected behavior**

Hover shows like this.

**Screenshots**

![image](https://user-images.githubusercontent.com/13230384/81175581-59c3d100-8fd6-11ea-85ea-c342d8bdb53b.png)

![image](https://user-images.githubusercontent.com/13230384/81175542-4a448800-8fd6-11ea-9475-378f5907d436.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.1
- VSCode version: 1.44.2
- OS: windows10

Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Additional context**

slack thread: https://vscodevim.slack.com/archives/C0ENQMTUM/p1588760304119600

**Comment by J-Fields** [comment]
Is this still an issue for you?

**Comment by berknam** [comment]
This is still an issue. In reality the command runs properly, this is just an issue with the status bar because of this line:
https://github.com/VSCodeVim/Vim/blob/b1ab3119298504d6b7aba6e8be257d3d34bb85c6/src/configuration/remapper.ts#L521

That is after the command running on the `handleRemapping`. Since the above remaps don't define `args` this results in `editor.action.showHover undefined` where `commandString = "editor.action.showHover"` and `commandArgs` is undefined.
