### ISSUE TITLE
I map ['j', 'k']  to ['esc']. But every time I use Chinese input mode, there will be a bug. 

### ISSUE THREAD

**Issue by meteorsh** [VSCodeVim/Vim#4815]
**Describe the bug**
I have mapped ['j', 'k']  to ['esc']. But when I entered `ji` and  `ke` (a word in Chinese)in insert mode, VScode Vim suddenly changed from insert mode to normal mode under the Chinese input method. [Gif](https://img-blog.csdnimg.cn/20200411193412727.gif)

**To Reproduce**

1.  In insert mode, I want to type Chinese words, so I use Chinese input method.
2. But when type `ji`, `Space` and `ke`, the Vim changes to normal mode, which is so weird!

**Expected behavior**
I don't want to trigger the `jk` command in Chinese Input Mode. I just want trigger `jk` when I use ABC Input Mode.

**Environment (please complete the following information):**

- Operating system : macOS Majave Version 10.14.5
- Chrome : Version 80.0.3987.132
- VScode:  Version 1.43.1

**Comment by caidwang** [comment]
There's another bug when using Vim plugin with Chinese Input. I have mapped ['j', 'k'] to ['esc'] too. And when I enter `jihua` or other words starting with `j`, the editor replace the character ahead into `j` and finally get a normal word with j behind.

Before enter :
![2020-09-24 15-51-27 的屏幕截图](https://user-images.githubusercontent.com/20463134/94116975-3f539c80-fe7e-11ea-9925-b33fe49dc71d.png)

During enter:
![2020-09-24 15-51-38 的屏幕截图](https://user-images.githubusercontent.com/20463134/94116959-3b277f00-fe7e-11ea-8b59-f1381d6b2e6f.png)

After enter:
![2020-09-24 15-51-54 的屏幕截图](https://user-images.githubusercontent.com/20463134/94116924-31058080-fe7e-11ea-829b-8f219b799b75.png)

**Comment by fangbinwei** [comment]
I mapped `["j","j"]` to `["esc"]` , It's strange this problem occurs on macOS, but no problem on windows

**Comment by berknam** [comment]
I've created the PR #5271 which should fix this. If you can test it out and give me some feedback.

**Comment by caidwang** [comment]
> I've created the PR #5271 which should fix this. If you can test it out and give me some feedback.

I have tested two bugs above, and it works. Thx for contribution and wish this useful fix can be merged soon.

**Comment by berknam** [comment]
@meteorsh  @fangbinwei @caidwang Thank you for all your help troubleshooting this!
