### ISSUE TITLE
macros behave strange

### ISSUE THREAD

**Issue by caoxuCarlos** [VSCodeVim/Vim#4827]
**Describe the bug**

I was trying to let vscode vim to write a math block in LaTex for me:

```tex
$$
\begin{aligned}
&
\end{aligned}
$$
```

so that I can write math equations quickly.

but it turns out like this:

```tex
$$
&
\endaligned
\begin{aligned
$$
```

Actually it seems to behave slightly differently every time.

**To Reproduce**

1. `qm` begin to record a macro on `m` key
2. `i`  go to insert mode
3. `$$` input double $$
4. `jj` personal setting to quit insert mode
5. `yy` yank current line
6. `p` past $$ line
7. `O` create a line above and change to insert mode
8. `\begin{}` input string
9. `jji` quit insert mode and back to insert mode, so the cursor will be inside the brackets
10. `algined` input aligned in the bracket
11. `jj` back to normal mode
12. `yyp` yank current line and paste it below
13. `l` put cursor on 'b'
14. `cw` change word
15. `end` change begin to end
16. `jj` back to normal mode
17. `O`create a line above and change to insert mode
18. `&` input `&` symble
19. `jj` back to normal mode
20. `q` end recording

And `@m` to play the macro.

**Expected behavior**

I did this on terminal vim, it behave exactlly what I expected:

```tex
$$
\begin{aligned}
&
\end{aligned}
$$
```

**Screenshots**

Expected(in terminal):

![Expected(in terminal)](https://user-images.githubusercontent.com/48681480/81529109-b8030200-9390-11ea-8644-91ca5c9d1994.png)

Reality(in vscode):

![vscode](https://user-images.githubusercontent.com/48681480/81536661-842ed900-939e-11ea-8196-3bea38adf39c.GIF)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.1
- VSCode version: 1.45.0
- OS: Ubuntu 20.04 LTS

**Comment by sqlkoala** [comment]
I think it is possible that vscodevim handles some part of this very long macro incorrect.

For your use case, I think it is far better to define a snippet.
https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by caoxuCarlos** [comment]
Thank you so much @sqlkoala, I wanted the juice, you just solved thirst for me with the best water.

**Comment by berknam** [comment]
This is a bug in VSCodevim, I have already found the problem and will send a PR with a fix soon.

It's actually two different bugs because part of this problem is related to issues #4814 and #4817, which I'm trying to fix too.

**Comment by sqlkoala** [comment]
> Thank you so much @sqlkoala, I wanted the juice, you just solved thirst for me with the best water.

That's a very graphic description ;-) but I am glad I could help.
