### ISSUE TITLE
VIM forbids multiple cursors across pages

### ISSUE THREAD

**Issue by FremdSprach** [VSCodeVim/Vim#4834]
Issue Type: <b>Bug</b>

When VIM extension is turned on, VIM forbids multiple cursors across pages, one can only use multiple cursors in current page, after scrolling to some other pages, if a new cursor is created, the VIM extension would always re-locate the cursor to previous page that it remembers.

That's somewhat awkward and weird.

Extension version: 1.14.1
VS Code version: Code - Insiders 1.46.0-insider (2b472d1e4aaaecdda5ca96289869f90ae82de3a1, 2020-05-11T10:00:12.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by J-Fields** [comment]
To clarify, you mean when adding a cursor with `alt-click`, right?

**Comment by FremdSprach** [comment]
> To clarify, you mean when adding a cursor with `alt-click`, right?

yes, the key-binding is either `alt-click` or `ctrl-click` (configured with multiple.cursor.modifier).
it's the latter combination for my instance.

**Comment by FremdSprach** [comment]
VIM is used in one page occasions, while multiple-cursor function goes across pages, so they are parallel, or not consistent. Anyway, never mind.
