### ISSUE TITLE
Case toggling not working on single character

### ISSUE THREAD

**Issue by mikaoelitiana** [VSCodeVim/Vim#4835]
**Describe the bug**
Toggling case on a single character under the cursor does not work anymore.

**To Reproduce**

1.  Place a cursor on a single character, for example `E` in `Example`
2.  Press `~` on the keyboard

**Expected behavior**
`E` should be transformed to lower case `e` but nothing happen.  Expected behavior is also described at https://vim.fandom.com/wiki/Switching_case_of_characters

**Screenshots**
![case-toggle-issue](https://user-images.githubusercontent.com/674667/81692254-6a54cb00-945e-11ea-8ce8-9a2fb3ccf408.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.1
- VSCode version: 
```
    Version: 1.45.0
    Commit: d69a79b73808559a91206d73d7717ff5f798f23c
    Date: 2020-05-07T15:57:33.467Z (4 days ago)
    Electron: 7.2.4
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Darwin x64 19.4.0
```

** Additional context **

When applyed to a selection of multiple characters, the toggling works fine.

**Comment by J-Fields** [comment]
I'm not able to reproduce. Can you post your settings?

**Comment by mikaoelitiana** [comment]
@J-Fields I have reset my vscode-vim settings and I do not reproduce it anymore, it must have been something I configured wrong. Thanks
