### ISSUE TITLE
When use /  to search, I can't use ctrl-V/cmd-V to paste search string

### ISSUE THREAD

**Issue by mushuanli** [VSCodeVim/Vim#484]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?

in Win10, I use / to enter VIM's search mode,
then I use Ctrl-V to paste a string
but it paste to txt file, not into search line,
any solution?

### What did you expect to happen?
I can paste search string into search line

### What happened instead?
the search string paste to file, not to search line

### Technical details:

* VSCode Version: 1.31.
* VsCodeVim Version:  0.1.3
* OS: WIN10

**Comment by rebornix** [comment]
+1. I expected CTRL-V work in search mode as well. If no one is interested in this feature, I'll take it.

**Comment by johnfn** [comment]
@rebornix go ahead! It should not be too hard.

**Comment by xenophy** [comment]
I guess Mac OS X (El Capitan) too.  "/" after that "cmd + v" is not work. I looking forward to implement this!

**Comment by rebornix** [comment]
@xenophy thanks for the info, yes I just added this feature for `ctrl-v` as I was just on Windows at that time. `cmd+v` should be covered as well.

**Comment by daviskoh-hiatus** [comment]
still an issue

**Comment by J-Fields** [comment]
@daviskoh-hiatus What platform? This definitely works; you might have a misconfiguration.

**Comment by daviskoh-hiatus** [comment]
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```

`vscodevim: 1.11.0`

settings.json

```
{
    "workbench.colorTheme": "Dracula",
    "workbench.startupEditor": "newUntitledFile",
    "window.zoomLevel": 0,
    "editor.minimap.maxColumn": 76,
    "[typescriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "editor.formatOnSave": true,
    "terminal.integrated.copyOnSelection": true,
    "vim.useSystemClipboard": true,
}
```

changing any combination of:

```
"vim.useCtrlKeys": false,
"vim.overrideCopy": false,
```

does nothing.

Interestingly `ctrl-v` works but **not** `cmd-v`. I can type in search mode just fine.
