### ISSUE TITLE
Support sidescrolloff option

### ISSUE THREAD

**Issue by ronakg** [VSCodeVim/Vim#4840]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option that mimics the behavior of `scrolloff` and `sidescrolloff` settings in vim.

**Describe alternatives you've considered**
No alternatives

**Additional context**
None

**Comment by J-Fields** [comment]
`editor.cursorSurroundingLines` is equivalent to `scrolloff`. Last I checked horizontal scrolling was not part of the VSCode API so `sidescrolloff` is not currently possible.

**Comment by ronakg** [comment]
Thanks. Didn't know about `editor.cursorSurroundingLines`. I can live without `sidescrolloff` for now.
