### ISSUE TITLE
Fold fix all of a sudden breaking visual line

### ISSUE THREAD

**Issue by JoshTRN** [VSCodeVim/Vim#4848]
This just started happening to me yesterday and up until then it wasn't a problem. Maybe it has something to do with the VS code update, but when fold fix is enabled, when I start visual line mode, it won't let me exceed 3 vertical jumps when I hit 'k'.

I've commented out all other key-bindings and the problem persists, but when I comment out fold fix, it starts working.

**Comment by JoshTRN** [comment]
I also noticed, probably the same bug, but if I use '{' to jump in visual line mode, then press 'j' in attempt to go down to where I want, it brings me 1 lines below the initial starting point.

**Comment by JDevx97** [comment]
Just wanted to add a piece of information for anyone looking into this. Experiencing the same issue as listed by @JoshTRN.

Just noticed attempting a visual jump with `k` with a number ie `10k` will actually work but only once. Past that just returns to the initial line.

**Comment by Aoczs** [comment]
Exactly the same problem.
