### ISSUE TITLE
:<n> does not (visually) move cursor to line n

### ISSUE THREAD

**Issue by iivvoo** [VSCodeVim/Vim#485]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?

    :1 
    :10 
    :$

### What did you expect to happen?

The editor (and cursor) to jump to (resp) line 1, line 10 and last line

### What happened instead?

The cursor remained blinking at the current location (though the editor scrolls to the correct viewport). As soon as further control/navigation is done, the cursor updates properly

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: *0.1.3*
* OS: Ubuntu Linux 14.04

**Comment by rebornix** [comment]
It's likely because the selection is not updated correctly even though we modified vscode active editor's selection.

**Comment by rebornix** [comment]
Fixed via https://github.com/VSCodeVim/Vim/commit/4bb8540f417420dbd5811dc31e947870efc56082
