### ISSUE TITLE
Extend '%' function's pairings

### ISSUE THREAD

**Issue by karmaral** [VSCodeVim/Vim#4855]
**Is your feature request related to a problem? Please describe.**
I've been looking for a way to extend the % function to include '<' / '>', and potentially others. So far I haven't been able to figure out how.

**Describe the solution you'd like**
Perhaps an option like vim.addPairings or whatever name? I think it'd just be making this part of code accessible through the settings, but I'm unsure about how much work it'd actually take.

**Describe alternatives you've considered**
I tried enabling the .vimrc settings and adding `set matchpairs+=<:>` but it didn't work. I'm fairly new to vim tinkering so I might've missed something.

Is this feasible or is it too complicated? Perhaps if there's another way of achieveing it, I'd appreciate the pointers.

Thanks in advance!

**Comment by J-Fields** [comment]
I think you mean `matchpairs`, not `matchpairings`. I don't believe we currently support this option though.

**Comment by karmaral** [comment]
You're right! Edited, thanks. Is this a lot of trouble? I've never tinkered with vscode extensions but maybe I could give it a try.

**Comment by yunti** [comment]
I've been looking for this aswell, this would be a great addition.  

Related: you can assign the command `Emmet: Go to matching pair` to % which will match html tags.  However it won't match on < and > like vim does when it's added to match pairs.

In vim with < added to match pairs and the inbuilt matchit plugin switched on it will match on < and html tags. ie it will  jump to the > on eg `<div>` when on <, when the cursor is onanything else on the opening tag apart from < it will jump to the closing tag eg `</div>`.
This is an ideal solution and it would be excellent if vscode was consistent with vim here.

**Comment by J-Fields** [comment]
Simple `matchpairs` support should be pretty straightforward; seems like we'd just need to make [this map](https://github.com/VSCodeVim/Vim/blob/a76053611202051828acc000f223a1e1f44825d1/src/common/matching/matcher.ts#L13) configurable. @karmaral if you'd like to give it a shot, go for it. Otherwise I'll take care of it when I get the bandwidth. Full matchit support would be more involved, though we do have some support for matching tags (see `TagMatcher`)

**Comment by J-Fields** [comment]
Related: #1885

**Comment by karmaral** [comment]
Cool beans, will try!

**Comment by eric-burel** [comment]
For lost googlers trying to jump to the closing chevron of an HTML tag, see the `matchpair` preference and add `<:>` to the list.
![image](https://github.com/user-attachments/assets/1880f3b1-1e68-487c-8261-a8599185bf9c)
