### ISSUE TITLE
exclamation mark followed by movement command

### ISSUE THREAD

**Issue by jonasbradstreet** [VSCodeVim/Vim#4857]
In the original Vim program, when I hit !} I will have selected from the current cursor position to the end of the paragraph giving me ":,<# of lines to end of paragraph>!" In VS Code "Vim" ! appears to do nothing and following it with } just moves the cursor to the end of the paragraph.

Am I doing something wrong, or is this functionality not available?

**Comment by J-Fields** [comment]
Not currently available.

**Comment by jonasbradstreet** [comment]
Got it. Thanks for the response.

**Comment by J-Fields** [comment]
Re-opening as it's a reasonable request (and I wasn't aware of this feature until this issue)

**Comment by wesleyegberto** [comment]
I noted that when in visual mode the `!}` works.

**Comment by tagniam** [comment]
Seems to be a dupe of #4166?
