### ISSUE TITLE
Surround when in visual modes using `S` working incorrectly.

### ISSUE THREAD

**Issue by with-heart** [VSCodeVim/Vim#4862]
**Describe the bug**

Starting with 1.14.2, surrounding multiple lines using <kbd>S</kbd> is surrounding incorrectly. Rather than adding the surround input as new lines before and after the selected lines, it's inserting the text inside the existing lines.

**To Reproduce**

Use the following text, with cursor in place of of `|`:

```jsx
<di|v>
  <p>Hello</p>
  <p>World</p>
</div>
```

Use <kbd>Shift+V</kbd> to select all lines, press <kbd>S</kbd> to enter surround command, and type `<div>` to surround the entire selection with opening and closing `div` tags.

**Expected behavior**
Selected lines should be wrapped in new lines containing the opening and closing tags.

**Screenshots**

Correct behavior (1.14.1):
![Correct behavior](https://kapture-98k61ilpq.now.sh/Kapture%202020-05-15%20at%2011.19.18.gif)

Incorrect behavior (1.14.2):
![Incorrect behavior](https://kapture-pzapqucdv.now.sh/Kapture%202020-05-15%20at%2011.14.39.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.2+
- VSCode version: 1.45.0
- OS: MacOS Mojave

**Comment by J-Fields** [comment]
Surely caused by e5c0a94dced29c336c8f4ab4a611810b286672e5
