### ISSUE TITLE
Match count is inaccurate.

### ISSUE THREAD

**Issue by JoshTRN** [VSCodeVim/Vim#4863]
**Describe the bug**
When you use `/` to find, it gives you a doubling of the number or actual instances.

**To Reproduce**

1. Press `/` to initiate search and search a term in a file. 

**Expected behavior**

Accurate count of the number of strings searched.

**Comment by J-Fields** [comment]
I recently re-wrote the search logic because it was a hot mess. Seems somewhere along the way I messed it up, as some ranges are getting found twice. Thanks for the report, I'll take a look.
