### ISSUE TITLE
Folding visual selected lines (`zf`)

### ISSUE THREAD

**Issue by alac1984** [VSCodeVim/Vim#4865]
**Is your feature request related to a problem? Please describe.**
In Vim we can visual select some lines and create a custom fold with `zf` command. In VSCodeVim it doesn't work.

**Describe the solution you'd like**
I want to visual select a group of lines and create a fold with `zf` command, and after that open or close it with `za`. These folds need to be stored in some place, to obviously be reloaded everytime we open the code. If it could include a description of what is folded (a snippet of the code folded or even a custom description) it would be very appreciated.

**Comment by J-Fields** [comment]
VSCode doesn't allow arbitrary folding; foldable regions are defined either by the language server or by indentation (depending on config).

**Comment by jonboh** [comment]
It seems that this is now possible in VSCode 1.70.0 with "Create Manual Folding Ranges from Selection" and "Remove Manual Folding Ranges"
https://code.visualstudio.com/updates/v1_70#_fold-selection
