### ISSUE TITLE
`w` should/could respect `wordSeparators` settings

### ISSUE THREAD

**Issue by staltz** [VSCodeVim/Vim#487]
My `wordSeparators` settings doesn't have `$`.

```js
  // Characters that will be used as word separators when doing word related navigations or operations
  "editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;:'\",.<>/?",
```

### What did you do?

I edited my `settings.json` so that `wordSeparators` does *not* have `$`.
Then
The cursor in a file was here
```
foo$ + bar$
^
|
```
I used `w` in normal mode to skip to the next word.

### What did you expect to happen?

Cursor to be here
```
foo$ + bar$
     ^
     |
```

### What happened instead?

```
foo$ + bar$
   ^
   |
```

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.3
* OS: Mac OS X El Capitan

**Comment by rebornix** [comment]
@staltz thanks for reporting this issue, this one is interesting and inspiring. `editor.wordSeparators` is a VS Code concept but we have a similar setting called `iskeyword` in Vim as well. It's also a part of #463 . 

The configuration overlap between Vim and VS Code is becoming more and more important.

**Comment by johnfn** [comment]
Ooh, fascinating idea.

If anyone wants to take this one on, my suggestion would be to honor word separation settings in this order:

1. Vim-specific settings set in vimrc or settings.json, if there are any
2. VSCode-specific settings, if there are any
3. Our default word separators.
