### ISSUE TITLE
Unlike vim, `l` motion takes the cursor beyond the end of the line instead of stopping at last character of the line

### ISSUE THREAD

**Issue by ronakg** [VSCodeVim/Vim#4870]
**Describe the bug**

When I use `l` to move right on a line and it reaches the last character, it goes to next line instead of stopping at the last character. This behavior is different from vim and started happening recently. Possibly since the last update.

**To Reproduce**

1.  Just keep `l` pressed to go navigate right on the line. Keep going till the end till you hit last character and beyond.

**Expected behavior**

The cursor should stop at the last character on the line.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.3
- VSCode version: 1.45.1
- OS: macOS 10.15.4 (19E287)

**Additional context**
None

**Comment by J-Fields** [comment]
What do you have `vim.whichwrap` set to?

**Comment by ronakg** [comment]
That was the problem. Not sure why I had `h` and `l` in there. Thanks!
