### ISSUE TITLE
Remap in Visual Mode for `s` and `d` doesn't work for fast keypresses.

### ISSUE THREAD

**Issue by vettukal** [VSCodeVim/Vim#4883]
**Describe the bug**
Remaping `s` and `d` to empty in VisualMode does not work if they they are pressed quickly once entering inside VisualMode. 

**To Reproduce**

1.  Make Settings.json as follows:
```
{
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["s"],
            "after": []
        },
        {
            "before": ["d"],
            "after": []
        }
    ]
}
```
I have tested with **"vim.visualModeKeyBindings"** also. Same results

2.  From normal mode press: vs (s should be pressed quickly after v)
3.  This will make vim delete a char and enter insertMode, 
**Expected behavior**
expected behavior was to remain in V mode and do nothing.

**Notes:** 
Bug is not reproduced if you wait 2 seconds to press `s` after `v` from Normal Mode.
Bug is not reproduced if you do `v`,`l`,`s` from normal mode. (Enter V mode, press l and then press s) 
Bug doesn't exist for Normal mode key remaps

**Environment (please complete the following information):**
https://github.com/VSCodeVim/Vim/issues/new/?body=- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.14.4`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.45.1`

**Comment by jgosmann** [comment]
I'm experiencing the same bug, though I'm remapping <kbd>s</kbd> to <kbd>h</kbd>. In this case a character is deleted and I end up in insert mode, when pressing <kbd>vs</kbd> in short succession. If I wait in between key presses, it works as expected (entering visual mode and moving the cursor to the left).

Debug log:
```
[Extension Host] Remapper: debug: trying to find matching remap. keys=v,s. mode=Visual. keybindings=visualModeKeyBindingsMap.
[Extension Host] Remapper: debug: trying to find matching remap. keys=v,s. mode=Visual. keybindings=visualModeKeyBindingsNonRecursiveMap.
[Extension Host] Remapper: verbose: key=v,s. keySlice=vs.
[Extension Host] Remapper: verbose: key=v,s. keySlice=s.
[Extension Host] Remapper: verbose: key sequences need to match precisely. precedingKeys=v.
[Extension Host] ModeHandler: debug: handleKeyEvent('s') took 22ms
```

**Comment by berknam** [comment]
@jgosmann If you can test the PR #4735 version and give some feedback. It should fix that issue and some more.

**Comment by jgosmann** [comment]
I could make it work for me with some additional remappings, but might test the PR when I have a little bit of time.
