### ISSUE TITLE
{count}x deletes newline when {count}>1

### ISSUE THREAD

**Issue by claudiodsf** [VSCodeVim/Vim#4887]
**Describe the bug**
VSCodeVim behaviour differs from standard Vim when using `{count}x`: it deletes the newline, merging the current line with the next one.

**To Reproduce**
1. Write the following lines:
```
Lorem
Ipsum
```
2. Put the cursor at the end of the first line and, in command mode, type `2x`

3. The result is:
```
LoreIpsum
```

**Expected behavior**
In standard Vim, the expected result is:
```
Lore
Ipsum
```

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.14.4
- VSCode version: 1.45.1
- OS: macOS 10.15.4

**Comment by claudiodsf** [comment]
That was fast! 🤩
Thank you!

**Comment by J-Fields** [comment]
Thanks for the report 🙂
