### ISSUE TITLE
Question: why CommandFold is not registered for Normal mode?

### ISSUE THREAD

**Issue by aminroosta** [VSCodeVim/Vim#489]
https://github.com/VSCodeVim/Vim/blob/master/src/actions/actions.ts#L1104

All other fold commands have `modes = [ModeName.Normal];` except FoldCommand.
I think this is wrong? what do you think

**Comment by rebornix** [comment]
@aminroosta good catch, we should be able to use FoldCommand in normal mode. Want to give it a quick fix?

**Comment by aminroosta** [comment]
Yea sure, I will send a pr tomorrow.


Get Outlook for Android






On Thu, Jul 21, 2016 at 4:38 AM +0430, "Peng Lyu" <notifications@github.com> wrote:





@aminroosta good catch, we should be able to use FoldCommand in normal mode. Want to give it a quick fix?

---

**Comment by aminroosta** [comment]
Related PR #493
