### ISSUE TITLE
command 'toggleVim' not found

### ISSUE THREAD

**Issue by tidux** [VSCodeVim/Vim#4890]
Toggling the extension through the command palette throws an error.  It does show up as available in the list of installed extensions and I can change settings, but enabling Vim mode itself doesn't work.

- Extension (VsCodeVim) version: 1.14.4
- VSCode version: 1.45.1 (code-server 3.3.1)
- OS: Debian 10 aarch64

**Comment by J-Fields** [comment]
Try updating to 1.14.5. If that doesn't work, uninstall the extension, delete the extension folder, and reinstall.

**Comment by tidux** [comment]
The extension works on VS Codium but not https://github.com/cdr/code-server.  I have opened an issue with code-server.

**Comment by blinkybool** [comment]
Uninstalling the Overtype extension fixed this for me. Should probably be mentioned in documentation as an incompatible extension. very subtle.

https://marketplace.visualstudio.com/items?itemName=adammaras.overtype

**Comment by zshzebra** [comment]
> Uninstalling the Overtype extension fixed this for me. Should probably be mentioned in documentation as an incompatible extension. very subtle.
> 
> https://marketplace.visualstudio.com/items?itemName=adammaras.overtype

Thank you so much! I didn't even remember installing the extension.
