### ISSUE TITLE
Extension host terminated unexpectedly: Can't use <space> in "vim.leader" setting

### ISSUE THREAD

**Issue by tecfu** [VSCodeVim/Vim#4899]
**Describe the bug**
VS Code crashes with vim mode enabled and "vim.leader": "<space>"

```
{
    "vim.vimrc.enable": true,
    "vim.normalModeKeyBindings": [
    
    ],
    "vim.leader": "<space>"
}
```

**To Reproduce**

Paste settings shown above in settings.json

**Expected behavior**

Space bar is mapped as "leader" in Vim mode

**Screenshots**
N/A

- Extension (VsCodeVim) version:

1.14.5

- VSCode version:

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-51-generic

- OS:

Ubuntu 18.04.4

**Comment by tecfu** [comment]
Duplicate of https://github.com/VSCodeVim/Vim/issues/1132. Please do not close without fixing.

**Comment by sqlkoala** [comment]
Hi, setting leader to space works (or worked) in general.
Can you try an earlier release (like 1.14.1) as  a test?

**Comment by J-Fields** [comment]
Unable to reproduce. What's your `.vimrc` look like?

**Comment by tecfu** [comment]
For me, the problem seems to have been that my leader was bound both in my .vimrc and in my settings.json.

Therefore:

```
{
    "vim.vimrc.enable": true,
    "vim.leader": "<space>"
}
```

Creates a conflict IF .vimrc also has the same binding, in this case: "vim.leader": "<space>"

**Comment by leedre** [comment]
I set my new <leader> in vscodevim setting by entering @ext:vscodevim.vim leader in the command palette (control + ,)

![Screenshot 2021-12-14 231310](https://user-images.githubusercontent.com/28940227/146122227-3a9fb561-df07-4cda-8892-f3c8980ea134.png)
