### ISSUE TITLE
v ctrl+a for incrementing numeric list not working

### ISSUE THREAD

**Issue by red8888** [VSCodeVim/Vim#4905]
I dont think I remapped ctrl+a (which is why im making this a feature request)

https://stackoverflow.com/questions/9903660/vi-how-to-generate-a-number-sequence

visual block + g + ctrl+a is not creating a numeric list. It works outside of vscode with regular vim/gvim though

**Comment by J-Fields** [comment]
This was fixed here: 34125c37d103c3126710668f9f7d2e704fb53308
