### ISSUE TITLE
MoveLineEnd improvement 

### ISSUE THREAD

**Issue by notiv-nt** [VSCodeVim/Vim#4910]
## Problem 
Moving the cursor to the end of the line, now it also picks up line breaks. I think it should not

<details>
  <summary>Gif</summary>
  <img src="https://user-images.githubusercontent.com/10743009/83164652-24ae2880-a115-11ea-9f63-3d4bba92a9b5.gif" alt="">
</details>

## Others
Sublime's version does not include it.
<details>
  <summary>Gif</summary>
  <img src="https://user-images.githubusercontent.com/10743009/83164717-355e9e80-a115-11ea-97e7-22b5df35574a.gif" alt="">
</details>

Vim's (includes?)
<details>
  <summary>Gif</summary>
  <img src="https://user-images.githubusercontent.com/10743009/83165222-e107ee80-a115-11ea-8d19-cef250148e13.gif" alt="">
</details>

Solution:

```typescript
public async execActionWithCount(
  position: Position,
  vimState: VimState,
  count: number
): Promise<Position | IMovement> {
  const endPosition = position.getDown(Math.max(count - 1, 0)).getLineEnd();
  let pos: Position | null = null;

  if (endPosition.character === 0) {
    pos = new Position(endPosition.line, 0);
  } else {
    pos = new Position(endPosition.line, endPosition.character - 1);
  }

  return pos;
}
```

https://github.com/VSCodeVim/Vim/blob/aef04775d7f9a05b1dd82ad900016a4e8b2076e2/src/actions/motion.ts#L846-L852

I can make a PR, if it's necessary

**Comment by J-Fields** [comment]
Vim selects the EOL character when `$` is used in visual mode, so this is expected behavior, isn't it?

**Comment by notiv-nt** [comment]
@J-Fields I don’t know, it’s not convenient for me personally and I removed it from myself

**Comment by berknam** [comment]
Maybe what you want is to use the keys `g_` instead of `$`.

From Vim doc:
`g_` Moves to the last non-blank character of the line and [count - 1] lines downward |inclusive|.

Bear in mind that if you have trailing whitespace on the line it won't select that. If you really want to get to last character without the new line you have to remap some key to `$h`.

**Comment by J-Fields** [comment]
Yep, @berknam's absolutely correct. Closing
