### ISSUE TITLE
Substitution doesn't operate on whole block if newlines are inserted

### ISSUE THREAD

**Issue by viraptor** [VSCodeVim/Vim#4915]
**Describe the bug**
If I use `s/.../... \n .../` on a highlighted blocks, only half of the lines are changed. (suspicion - it iterates on original line range, without accounting for additions)

**To Reproduce**

1. Create a file with:
```
a: b
c: d
e: f
g: h
```
2. Highlight all lines (`ggVG`)
3. Run replacement (`:s/: /\n- /`)

**Expected behavior**
```
a
- b
c
- d
e
- f
g
- h
```
instead of current:
```
a
- b
c
- d
e: f
g: h
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.5
- VSCode version: 1.45.1
- OS: macos mojave

**Comment by sql-koala** [comment]
I noticed this too and was already looking at substitute.ts.

Reason is this: Implementation of `:s/` uses old methods to access the document, which are not really isolated.
Meaning: the insertion of first newlines moves the lines "e: f" and "g: h" out of the selection.

It is quiet easy to replace the old methods, but that also requires updating a lot of complicated tests, which is a f..cking pain.
