### ISSUE TITLE
Display lines based cursor moving not working properly in visual mode

### ISSUE THREAD

**Issue by AlseinX** [VSCodeVim/Vim#4919]
**Describe the bug**
Display line based cursor moving not working properly in visual mode.

**To Reproduce**

1.  Enable line wrapping and input some long lines to be wrapped into multiple lines.
2.  Press `v` to enter visual mode.
3.  Press `gj` to move down by display lines.
4.  Repeat `gj` to keep moving down by display lines.

**Expected behavior**
The cursor would move straight downward unless there are not enough characters to fill the line, just like what real vim would do.

**Actual behavior**
The first `gj` works properly, but the subsequent ones additionally move forward by 1 char after moving downward.

**Environment**
- Extension Name: `vim`
- Extension Version: `1.14.5`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

**Additional context**
`gk` has the same problem as well. The subsequent `gk`s also moves forward by 1 char after moving upward.

**Comment by J-Fields** [comment]
This was fixed back in 3f53243192502f8eb8199fe70a2d9b4903512fc2
