### ISSUE TITLE
How can I bind ; to :?

### ISSUE THREAD

**Issue by ScenK** [VSCodeVim/Vim#492]
Is that a configuration for binding ; to :?

**Comment by rebornix** [comment]
I think it's a remapping feature @johnfn is working on or already finished?

**Comment by jkurei** [comment]
You can add this to your settings.json:

```json
"vim.otherModesKeyBindings": [
        { "before": [";"], "after": [":"]}
]
```

The problem with this is `;` will be replaced with `:` in vim searches (`/`); I think that's a bug (https://github.com/VSCodeVim/Vim/issues/495). Of course, i don't think searching `;` is very common, but I actually have done it, so...

**Comment by rebornix** [comment]
@jkurei it's a little bit out of my Vim knowledge, does Vim have this feature as well and should it only work on Normal Mode?

**Comment by jkurei** [comment]
@rebornix yeah. In Vim you can map anything and specify in which modes you want it to work, but they don't work in the ex-commands line nor searches (unless, may be, you specify so? idk).

I have several of such bindings (in real Vim) and they never apply in searching. I have just tested out that the same goes for the remap @ScenK wants to do, just to be sure.

If you don't know the ex menu, It's kind of the grandfather of the Cmd+Shift+P menu that Sublime/Atom/VSCode use today, and it's usually accessed with the `:` key. 

If you wanna check this out, just add `map ; :` to `~/.vimrc`, and then run (or restart if already running) Vim. Now whenever you press `;`, it'll open the ex menu, just as `:` usually does.

**Comment by rebornix** [comment]
@jkurei yup I know ex menu and I'm implementing it, part of #463 . Now I'm clear enough with the binding scope. It is straight forward to stop key mapping in Search Mode but if we want to speciy mode, we need the same logic as VS Code does keybindings.

This bug is on my list :)

**Comment by johnfn** [comment]
As @jkurei pointed out, this does in fact already work. I suspect our README does not go into enough detail with key remappings, which is confusing people.

The search remapping bug is tracked in #495, and it should be a quick fix. 😃

**Comment by jima80525** [comment]
Just in case someone else finds this bug and tries to fix it, the solution shown above doesn't work (anymore?).  Here's what worked as of July 2019:
```json
"vim.normalModeKeyBindings": [
    { "before": [";"], "after": [":"]}
],
```
