### ISSUE TITLE
Incorrect Behavior: Deleting all lines in the file

### ISSUE THREAD

**Issue by jeeeem** [VSCodeVim/Vim#4926]
**Describe the bug**
Using the change command `cii` or `cai` will delete all lines on the file.  

**Expected behavior**
Nothing should really happen

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.14.5`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.45.1`

**Additional context**
I don't know if this is really a bug or just a feature  'cos I'm not really that expert on vim but I try to reproduce it on (n)vim but its not happening so I guess it is indeed a bug.

**Comment by J-Fields** [comment]
`i` is the indent text object, so `cii` should delete all the lines at the current indentation (the body of a python function, for instance). It's not in vanilla vim, but available via a plugin so we include it.

**Comment by jeeeem** [comment]
Oh that's what i thought. Thanks for quick response tho.
