### ISSUE TITLE
Custom binding doesn't trigger compound command

### ISSUE THREAD

**Issue by tecfu** [VSCodeVim/Vim#4928]
**Issue**

I've mapped `<leader>a` to` ^` in normal mode as follows: 

```
"vim.normalModeKeyBindings": [
       {
            "before": ["<leader>", "a"],
            "after": ["^"]
        }
}
```

I expect pressing the sequence `<leader>a` to thus replicate the behavior of pressing `^` when in normal mode. It does. Except for when I use it in a compound command sequence. Like `d<leader>a`. Which does nothing.

Conversely, `d^` will delete from the current cursor position to the beginning of the current line. This is what I expect `<leader>a` to do in normal mode after being bound to `^` in normal mode.

**To Reproduce**

1. settings.json

```
"vim.normalModeKeyBindings": [
       {
            "before": ["<leader>", "a"],
            "after": ["^"]
        }
}
```
2.  Restart VSCode
3.  Open a file, move the cursor to the end of a line of text. Press the following sequence: `d<leader>a`
4.  Nothing happens

**Expected behavior**

After pressing sequence: `d<leader>a`, line should be deleted

**Environment (please complete the following information):**

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-53-generic / Xubuntu 18.04
VSCode Vim Version: 1.14.5

```

**Comment by berknam** [comment]
What you need here is operatorPendingMode remapping which isn't supported yet but is going to be fixed with PR #4735. If you can test that PR and give some feedback.

**Comment by tecfu** [comment]
Thanks @berknam. Please see: https://github.com/VSCodeVim/Vim/pull/4735#issuecomment-640143532

**Comment by tecfu** [comment]
Resolved by PR https://github.com/VSCodeVim/Vim/pull/4735. Closing under assumption this PR will be merged.
