### ISSUE TITLE
Q: How do I switch to Normal Mode from Visual Mode inside Macros?

### ISSUE THREAD

**Issue by yelled1** [VSCodeVim/Vim#4929]
I have Macros as below:
        "execCurSel": [
            //"interactiveScala.executeInInteractiveScala",
            {"command": "workbench.action.terminal.sendSequence",
            "args": { "text": ":paste\u000D${selectedText}\u000D\u0004"}},
            "workbench.action.terminal.scrollToBottom",
            "cancelSelection",
            "vim.mode.Normal"]
The bottom quite does NOT work.
1) How do I do this?
2) Is there a API doc for this project?
Thanks,

**Comment by sqlkoala** [comment]
Hi, I think I have a similar use case. You can try to replace the last two commands with
"extension.vim_escape"

**Comment by yelled1** [comment]
Thank you. I would NOT have guess that one.
Works like a charm!

> Hi, I think I have a similar use case. You can try to replace the last two commands with
> "extension.vim_escape"

**Comment by yelled1** [comment]
For everyone's benefit this is what I have in settings.json:
    "macros": {
        "execCurLn": [ 
            "expandLineSelection",
            //"interactiveScala.executeInInteractiveScala",
            "workbench.action.terminal.runSelectedText",
            "workbench.action.focusActiveEditorGroup",
            "cancelSelection",
        ],
        "execCurSel": [
            //"interactiveScala.executeInInteractiveScala",
            {"command": "workbench.action.terminal.sendSequence",
            "args": { "text": ":paste\u000D${selectedText}\u000D\u0004"}},
            "workbench.action.terminal.scrollToBottom",
            "cancelSelection",
            "extension.vim_escape"
        ]
    },
