### ISSUE TITLE
vim.visualstar setting has no effect

### ISSUE THREAD

**Issue by ronakg** [VSCodeVim/Vim#4932]
**Describe the bug**
`vim.visualstar` setting has no effect. It's as if it's hard-coded to `false`.

**To Reproduce**

0. Set `vim.visualstar` to `true` in `settings.json`
1. Create a sample file with the text:

```
sample file with some text

sample file with some text

sample file with some text
```

2. Now keep the cursor on word `sample` on line 1.
3. Press `*`

**Expected behavior**
The word `sample` should get highlighted in the document and cursor should stay on the `sample` word on line 1.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.5
- VSCode version: 1.45.1
- OS: macOS 10.15.5 (19F101)

**Additional context**

**Comment by ronakg** [comment]
Never mind. My understanding of `vim.visualstar` is wrong.

**Comment by shawnghu** [comment]
@ronakg , can you explain what the correct understanding is? I have your same wrong understanding and I wish I knew what the problem was.
