### ISSUE TITLE
gw stopped working

### ISSUE THREAD

**Issue by dionyziz** [VSCodeVim/Vim#4937]
**Describe the bug**
Selecting a text in visual mode and pressing `gw` used to wrap the text. It no longer works.

**To Reproduce**

1.  Open a file
2.  Select some lines of text using visual line mode (shift V)
3.  Press gw

**Expected behavior**
The text is wrapped to 79 characters per line.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.5
- VSCode version: 1.45.1
- OS: macOS 10.15.4 (19E287)

**Comment by berknam** [comment]
Do you mean `gq`? `gw` is not currently implemented and I don't think it ever was. I didn't even know about `gw` until now 😄.
But `gq` seems to be working. If `gq` works for you then this should be a feature request to implement `gw`.

**Comment by J-Fields** [comment]
Yeah `gw` has never been supported - here's the relevant issue: #4523
