### ISSUE TITLE
Lag exiting insert mode: normal mode keystrokes are getting entered as text after ESC

### ISSUE THREAD

**Issue by willhaslett** [VSCodeVim/Vim#4941]
**Describe the bug**
Exiting insert mode is becoming slow. When in insert mode, pressing `caps lock`, which I have mapped to `esc` on my Mac, then typing a comma, which I have mapped to `:w<Enter>`, sometimes results in a comma being inserted into the document. If I try to save and move down one row, I sometimes get `,j` in my document.

The context is a Flutter app that doesn't have a lot more in it than the vanilla Flutter example app that Flutter ships with. I can imagine that the latency is not due to this package, but it seems like in no event should key presses after `esc` leak into insert mode text entry.

**To Reproduce**

1.  Edit any file in the project
2.  Enter insert mode
3.  Exit insert mode and type some normal mode keys
4.  You might get the normal mode keypresses appearing in the document

**Expected behavior**
Exiting to normal mode is snappy and normal mode key presses do not leak through.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.14.5
- VSCode version: 1.46.0
- OS: macOS Catalina (2020 MBP 16")

**Additional context**
Flutter. Small app. App runs fine.

**Comment by J-Fields** [comment]
What other extensions are you using? This is usually caused by a greedy extension

**Comment by willhaslett** [comment]
```
 ~/code/mt2/lib/db  code --list-extensions
bung87.rails
bung87.vscode-gemfile
Dart-Code.dart-code
Dart-Code.flutter
HanWang.android-adb-wlan
karunamurti.haml
ms-python.python
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
rebornix.ruby
ryuta46.multi-command
shd101wyy.markdown-preview-enhanced
sianglim.slim
vscodevim.vim
wingrunr21.vscode-ruby
yzhang.markdown-all-in-one
```

**Comment by willhaslett** [comment]
I just uninstalled `HanWang.android-adb-wlan`, which I'm not using, in case that's it.

**Comment by berknam** [comment]
This could be related to [this issue](https://github.com/Dart-Code/Dart-Code/issues/1800) from Dart. Can you try disabling dart-code and/or flutter and see if this is the problem or not?

**Comment by willhaslett** [comment]
Seems like they might both be hogs. When I disable both of them, snappy as expected. When either one of them is on, I get the latency. I suspect that it's related to intellisense. I think I'm seeing that it's when, for example, I put parens after a call and `esc` because the parens don't need anything in them. Like it's stuck searching for suggestions.

**Comment by J-Fields** [comment]
The problem is basically that extensions are all run on the same thread, separate from VSCode's UI thread. VSCodeVim intercepts virtually all keystrokes and essentially takes over, but since it's synchronous with the other extensions, it makes the app's performance sensitive to them.

It doesn't seem reasonable that the dart language plugin would be that laggy for a small project (I use typescript and C++ on fairly large projects, and rarely have performance issues), but I can't really offer guidance beyond that.

**Comment by willhaslett** [comment]
Got it, thanks. I'll follow the Dart extension issue.

**Comment by roshan** [comment]
I had this on Big Sur and I needed to [use Karabiner Elements as described by this comment on SuperUser](https://superuser.com/a/1224132).
