### ISSUE TITLE
Remapping `hjkl` to `ijkl` leads to memory leak

### ISSUE THREAD

**Issue by pyriand3r** [VSCodeVim/Vim#4943]
**Describe the bug**
I wanted to remap `hjkl` to `ijkl` and `i` to `h` to be able to use vscodeVim like i use vim. But when i map the keys like below, sometimes it works, but mostly produces a memory leak in vscode leading to a shutdown of the plugin.

The problem seems to be that the mapping leads to a remapping circle. For example when i press `h`:

h -> i
i -> k
k -> j
j -> h
h -> i
...

If i change the remapping of `j` to another letter than `h` the problem is gone.

**To Reproduce**

1.  Go to 'settings.json'
2.  Add normal mode key bindings:
    ```
    "vim.normalModeKeyBindings": [
        {
            "before": [
                "i"
            ],
            "after": [
                "k"
            ]
        },
        {
            "before": [
                "h"
            ],
            "after": [
                "i"
            ]
        },
        {
            "before": [
                "k"
            ],
            "after": [
                "j"
            ]
        },
        {
            "before": [
                "j"
            ],
            "after": [
                "h"
            ]
        },
    ],
    ```

3.  Save and open a file to edit
4.  Use `ijkl` to navigate through the code, use `h` to switch to edit mode. Sometimes you can use the config for a few minutes. Then the keys suddenly stop working.

**Expected behavior**
I would expect `ijkl` and `h` would work as intended for navigation in normal mode and switching to edit mode, without killing the plugin.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.5
- VSCode version: 1.45.1
- OS: Manjaro Linux | i3

**Additional context**

***Dev Tools Error Log***
 WARN UNRESPONSIVE extension host, 'vscodevim.vim' took 56% of 5549.29ms, saved PROFILE here: '/tmp/exthost-575d4e.cpuprofile' 
Array(4)
0: {id: "gc", total: 1703843, percentage: 31}
1: {id: "program", total: 602760, percentage: 11}
2: {id: "self", total: 102905, percentage: 2}
3: {id: "vscodevim.vim", total: 3133056, percentage: 56}
length: 4
__proto__: Array(0)
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by berknam** [comment]
You need to create those bindings with the non recursive keybindings, you need to use `"vim.normalModeKeyBindingsNonRecursive": []` otherwise you are creating a recursive mapping loop.

`"vim.normalModeKeyBindings": []` is the same as nmap in Vim
`"vim.normalModeKeyBindingsNonRecursive": []` is the same as nnoremap in Vim
`"vim.insertModeKeyBindings": []` is the same as imap in Vim
`"vim.insertModeKeyBindingsNonRecursive": []` is the same as inoremap in Vim
`"vim.visualModeKeyBindings": []` is the same as vmap in Vim
`"vim.visualModeKeyBindingsNonRecursive": []` is the same as vnoremap in Vim
`"vim.commandLineModeKeyBindings": []` is the same as cmap in Vim
`"vim.commandLineModeKeyBindingsNonRecursive": []` is the same as cnoremap in Vim

**Comment by berknam** [comment]
You can also use your .vimrc file with the options `"vim.vimrc.enable": true` and `"vim.vimrc.path": "path/to/vimrc"` and it will read those mappings from your .vimrc file.

**Comment by pyriand3r** [comment]
Hi, ah okay, missed that config field. sorry. 

I did not use my .vimrc file because it is said to be experimental support. 

I have changed my mappings to `NonRecursive`. Seems to work now. Thanks for the fast help!

**Comment by berknam** [comment]
Don't forget to add the visual mappings as well and that until the PR mentioned above is merged your mappings won't work with the operators like 'c', 'y', 'd'.
