### ISSUE TITLE
I am not allowed to set neovim path in wsl? Is there neovim support in wsl mode?

### ISSUE THREAD

**Issue by rohitkrishna094** [VSCodeVim/Vim#4947]
**Describe the bug**
I have vscode on both wsl and normal windows environment. I have installed WSL and vscode in wsl mode. I have followed instructions for **vscodevim** and **vscodeneovim** extension. I can see that **vscodeneovim** works fine if I open vscode from say right clicking in windows explorer. However if I change **neovim** path to /usr/bin/nvim, and open vscode in wsl, it doesn't work.

These are my settings
![image](https://user-images.githubusercontent.com/18495886/84622598-67a92380-aeab-11ea-8209-e555103c1f15.png)

In written format, these are my settings:

```
  "vscode-neovim.useWSL": true,
  "vscode-neovim.neovimPath": "/usr/bin/nvim",
  "vim.enableNeovim": true,
  "vim.neovimPath": "/usr/bin/nvim",
```
I have installed nvim in wsl following their docs. I ran `sudo apt-get install neovim` and after that I am able to open **nvim** from my wsl terminal. However, when I open vscode in wsl with above settings, I get an error saying

```
Configuration: Invalid neovimPath. The argument 'file' cannot be empty. Received ".
```

But from above settings you can clearly see that I added vim.neovimPath. However in the below image, you can see that vim.neovimPath's color is greyed out.

![image](https://user-images.githubusercontent.com/18495886/84622747-beaef880-aeab-11ea-8988-4cd3635dc35a.png)

It says that 

```
This setting cannot be applied in this window. It will be applied when you open local window.
```

More context:
These are my vscode-neovim settings
![image](https://user-images.githubusercontent.com/18495886/84623547-7ee91080-aead-11ea-809d-952245a3cce9.png)

**To Reproduce**

1. Install vscode in wsl mode
2. Install vscode-vim extension
3. Install nvim from command line depending on Linux distro.
4. Install vscode-neovim extension
5. Open vscode from wsl terminal.
6. Go to vscode-neovim settings and enter the path to nvim(something like /usr/bin/nvim). This should be path of executable not just some folder
7. Now in the same settings, enable useWsl(this is vscode-neovim setting)
8. Now go to vim(vscode-vim) settings.
9. Enable neovim
10. In the same settings, add nvim path where it says vim.neovimPath
11. Now reload the window(ctrl+shift+p and type reload)
12. Now you will get that error.
13. To confirm, go to settings json and you will/should notice that vim.neovimPath is greyed out and it says that it will only work in local vscode.

**Expected behavior**
I expect that I don't get the above error and neovim works as it does in my normal vscode(right clicking from windows, I guess this is called local vscode as opposed to wsl vscode which could be called remote vscode).

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.14.5
- Extension (vscode-neovim) version 0.0.50
- VSCode version:1.46.0
- OS: Windows

**Comment by J-Fields** [comment]
This should be fixed in the next release (see #4901), but you should be able to use `remote.extensionKind` to force VSCodeVim to run as a workspace extension for now

**Comment by jplew** [comment]
Hello @J-Fields, I regret I'm getting the same greyed out neovimPath setting in my settings.json, with an identical warning as OP: `This setting cannot be applied in this window. It will be applied when you open a local window`. 

The Vim extension complains as follows when I open a new window:

```
Configuration: Invalid neovimPath. The argument 'file' cannot be empty. Received ''.
```

Relevant part of my settings.json:

```
  "vim.enableNeovim": true,
  "vim.neovimPath": "/usr/bin/nvim",
  "remote.WSL.debug": true,
  "remote.extensionKind": {
    "vscode.vim": ["workspace"]
  }
}
```

The `remote.extensionKind` setting does not seem to make a difference, no matter what option I put, or if I omit it entirely.

I'm using VS Code 1.55.2 on Windows, with remote connection to WSL Ubuntu.

![image](https://user-images.githubusercontent.com/462836/115495215-c89c4780-a284-11eb-8eb9-d64c1353a2d4.png)

**Comment by dhvcc** [comment]
Still seeing this error. It's really frustrating

**Comment by transtone** [comment]
> Still seeing this error. It's really frustrating

you need install `vim` extension in your wsl.
