### ISSUE TITLE
TaskQueue: Error running task. Failed to handle key=q. t.actionsRun is not iterable.

### ISSUE THREAD

**Issue by danielo515** [VSCodeVim/Vim#4948]
Issue Type: <b>Bug</b>

This happens when I try to record a macro on latest vscode

Extension version: 1.14.5
VS Code version: Code 1.46.0 (a5d1cc28bb5da32ec67e86cc50f84c67cc690321, 2020-06-10T08:59:06.977Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|-psn_0_356439|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by berknam** [comment]
Can you give some more information, some steps to reproduce this?

**Comment by danielo515** [comment]
It was just recording a Macro. But it seems to work now. I'll close it and reopen if it happens.
Sorry for the trouble.

**Comment by J-Fields** [comment]
Yeah I've definitely seen this as well. Let me know if you figure out repro steps.

**Comment by berknam** [comment]
Ok I found a way a reproducing this and I've located the problems. If I have some time I can try to fix it.

But just so you now here are the steps:
- When you open VSCode for the first time and all the registers are cleared, if you try to run any of the empty registers like `@c` you get the error:
```
TaskQueue: Error running task. Failed to handle key=c. t.actionsRun is not iterable.
```
- If you try to append a macro to an empty one, like if you do `:reg` and see that some register like `b` doesn't exist, if you do `qB` to append to register `b`, after you do the actions and then press `q` again to stop recording you get the error:
```
TaskQueue: Error running task. Failed to handle key=q. Cannot read property 'concat' of undefined.
```

Can someone reopen this issue?

**Comment by berknam** [comment]
I've also noticed that when you try to run a macro for an empty register, after the error
```
TaskQueue: Error running task. Failed to handle key=c. t.actionsRun is not iterable.
```
the variable `vimState.isReplayingMacro` stays `true` which means that actions that would create an undo point don't do it anymore because it thinks it is still recording a macro and it stays this way until you restart VSCode or you run a successful macro.

The result of this is that every time you try to undo it will undo everything you did instead of just the last action. I believe this might be related to some issues that have happened of people losing a bunch of work after undo.

**Comment by J-Fields** [comment]
Nice catch! I think I've seen that bug in instances where that wouldn't apply, but if we could fix one way it can be triggered, that would be awesome.

**Comment by berknam** [comment]
@J-Fields I'm looking into this one.
