### ISSUE TITLE
KeyBindings having unintended effect on search text

### ISSUE THREAD

**Issue by jkurei** [VSCodeVim/Vim#495]
### What did you do?

I have, among other keyBindings, one to go to the beginning of the line with `B`:

```json
"vim.otherModesKeyBindings": [
  { "before": ["B"], "after": ["^"] },
  ...
]
```

I then tried to search the word Blocks with: `/Blocks`

### What did you expect to happen?

A Vim-style search of the word Blocks

### What happened instead?

A search of `^locks`

### Technical details:

* VSCode Version: 
* VsCodeVim Version: Latest? (I can't find this anywhere, but I installed it yesterday (07/19) and I can see no commits with code changes since then, plus VSCode doesn't show any updates).
* OS: OS X El Capitan

**Comment by johnfn** [comment]
Oh gosh, this bug is really silly. Easy fix for anyone who wants to pick it up 😄

**Comment by jkurei** [comment]
Took a screenshot to illustrate this, forgot to attach it 😔. 

<img width="327" alt="screen shot 2016-07-21 at 19 34 53" src="https://cloud.githubusercontent.com/assets/1428611/17053843/37ca349c-5004-11e6-9e37-97c4fb8dea9f.png">
