### ISSUE TITLE
Ex commands, searches, etc. don't show in status bar

### ISSUE THREAD

**Issue by vegerot** [VSCodeVim/Vim#4951]
**Describe the bug**
When starting to type an ex command `:` or start searching for something `/`, the in-progress search does not show in the status bar
**To Reproduce**
1.  Go to ' a file '
2.  type `/VSCodeVimRocks`
3.  Look at the bottom and VSCode and notice the lack of that text appearing

**Expected behavior**
The in-progress text should show at the bottom, similar to vanilla vim (below)

**Screenshots**
![image](https://user-images.githubusercontent.com/5297725/84906525-0e461d80-b080-11ea-9e43-49552213479f.png)
![image](https://user-images.githubusercontent.com/5297725/84907132-d390b500-b080-11ea-8bbe-4565ed398666.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: Latest
- VSCode version: Latest insiders
- OS: macOS

**Additional context**
Some of my vim preferences
```json
{
  "vim.camelCaseMotion.enable": true,
  "vim.changeWordIncludesWhitespace": true,
  "vim.easymotion": true,
  "vim.enableNeovim": true,
  "vim.highlightedyank.duration": 100,
  "vim.highlightedyank.enable": true,
  "vim.hlsearch": true,
  "vim.neovimPath": "/usr/local/bin/nvim",
  "VSCodeVimRocks": true,
  "vim.normalModeKeyBindings": [
  "vim.sneak": true,
  "vim.useSystemClipboard": true,
  "vim.vimrc.enable": true,
  "vim.visualModeKeyBindingsNonRecursive": [
  "vim.textwidth": 100,
  "vim.debug.loggingLevelForConsole": "warn",
  "vim.history": 5000,
  "vim.visualstar": true // if enabled, run the build task and wait for
}
```

**Comment by J-Fields** [comment]
Right click the status bar to make sure it's not hidden

**Comment by vegerot** [comment]
@J-Fields 🤦‍♀️ .  Well, that's embarrassingg.

**Comment by zzimbler-tagsafe** [comment]
@J-Fields 🙏🏼  - you da real mvp

**Comment by Jacfger** [comment]
@J-Fields you saved me hours of searching.
