### ISSUE TITLE
Visual mode, word backwards motion selects EOL on last word

### ISSUE THREAD

**Issue by sql-koala** [VSCodeVim/Vim#4966]
**Describe the bug**
In visual mode, if you use word backwards "b" from the last character of the last word, it will select the word and the EOL character. This is wrong ,-)

**To Reproduce**

1.  Have a file with "foo bar baz"
2.  Have cursor on "z", goto visual mode
3.  "b" for one word back
4.  "baz " will be selected with the EOL

**Expected behavior**
Only "baz" should be selected.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.4
- VSCode version: latest
- OS: windows

**Additional context**
There is an easy workaround (viw), but one has to remember that.

**Comment by J-Fields** [comment]
Seems like `vbd` doesn't delete the newline, though, can you confirm? This might be a visual bug

**Comment by J-Fields** [comment]
This happens with all backward motions in visual mode, it seems. My guess is that this is a bug related to our representation of a selection in visual mode, which is absolutely dumb. I'll take a closer look when I get a chance.

**Comment by berknam** [comment]
Weird that is what happens in version 1.14.4. But in version 1.14.5 it only selects `ba` and the showCmd shows `2` as if only two characters are selected, but if you delete it deletes the entire word so it should be just the representation. But something changed from 1.14.4 to 1.14.5.

**Comment by sql-koala** [comment]
> Seems like `vbd` doesn't delete the newline, though, can you confirm? This might be a visual bug

Yes, that's right.
The case where I noticed it is this: when you use a snippet with variable "$TM_SELECTED_TEXT", then this variable will include the newline. That causes unexpected results.

**Comment by J-Fields** [comment]
> Weird that is what happens in version 1.14.4. But in version 1.14.5 it only selects `ba` and the showCmd shows `2` as if only two characters are selected, but if you delete it deletes the entire word so it should be just the representation. But something changed from 1.14.4 to 1.14.5.

I think this depends on whether there is a next line or not, not the version. But good point
