### ISSUE TITLE
[Question] Is it possible to open a file in new tab from keyboard while in file explorer?

### ISSUE THREAD

**Issue by sangeet** [VSCodeVim/Vim#4976]
Hi,

When I'm on the sidebar file explorer (Ctrl+shift+E), then `hjkl` works just fine for browsing around, but I'm unable to find any way to open the link in a new tab. The default `Enter` works weirdly as in sometimes, it will open the file in a new tab and other times, it will just replace the currently open file (if unsaved).

Is there a way to change it such that :

1. Enter replaces the current open buffer in editor.
2. Another command such as `Ctrl+T` or `T` (similar to nerdtree) opens the file up in a new tab?

I'm fairly new to VSCode after been using vim for forever and hence have been having a hard time getting this thing right.

**Comment by sangeet** [comment]
I did find out the reason for above unpredictable behavior. When you press Enter on a file, then VSCode by default opens the file in preview mode and if you make no edits or changes to a file open in preview mode then upon pressing Enter on another file, it will simply replace that buffer.

To work around this, we have to tell VSCode to not open the files in editor mode. This can be done by adding the following setting to VSCode `settings.json` file : 

```json
"workbench.editor.enablePreview": false,
```

This will disable preview

**Comment by sql-koala** [comment]
Hi,
outside the editor window (where vim is controlling keys), what you need to look at are "regular" vscode keyboard shortcuts and the commands behind them.
There are two commands available that could do, what you are looking for:
![image](https://user-images.githubusercontent.com/30384885/86167697-4d13b300-bb17-11ea-8486-955c3ede4623.png)

**Comment by sangeet** [comment]
That's very helpful. Thank you very much. :)
