### ISSUE TITLE
undo doesn't work correctively after several times of <ctrl - />

### ISSUE THREAD

**Issue by hondoumachi** [VSCodeVim/Vim#4978]
**Describe the bug**
after several times of <ctrl - /> to comment code block, the undo doesn't work correctively. only some of the comment block will be uncommented.

**To Reproduce**

1. write a "hello world" with c++
2. use several times of <ctrl - /> to comment some code lines
3. use several times of `u` to undo
4. the comment blocks don't get uncommented correctively

**Expected behavior**
the commented block should be uncommented in the reverse order

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.14.5
- VSCode version: 1.46.1
- OS: windows 10

**Comment by trkoch** [comment]
I've also seen this.
