### ISSUE TITLE
unexpected operation with <ctrl - u> in visual mode

### ISSUE THREAD

**Issue by HyHuang1995** [VSCodeVim/Vim#4983]
**Describe the bug**
vscode 1.46.1
vim 1.14.5

<C-u> in visual mode can't work well.

**To Reproduce**
Steps to reproduce

1.  enter visual mode
2.  use <C-u> to scroll up
3.  See error

**Screenshot**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.5
- VSCode version: 1.46.1
- OS: ubuntu 18.04

**Comment by J-Fields** [comment]
This has been fixed on `master`. It'll be in the next release
