### ISSUE TITLE
Parameter hint window loses focus; key presses go to editor instead

### ISSUE THREAD

**Issue by adam-c-anderson** [VSCodeVim/Vim#4994]
**Describe the bug**
With VSCodeVim active, when the parameter hints window is visible, key presses go to the editor instead of to the parameter hints window as expected/desired. Specifically, this means that pressing the up/down arrows, which normally would scroll between different overloads of a method, instead move the cursor in the editor window, and pressing Esc doesn't make the parameter window disappear either.

This issue does not occur with VSCodeVim inactive.

**To Reproduce**

1.  Place the cursor between the parentheses of some method call with overloads (e.g. Console.WriteLine). Insert/Normal mode doesn't matter.
2.  Press ctrl+shift+space to open the parameter hint window
3.  Press an arrow key
4.  The cursor will move to another line, which will either cause the parameter window to show parameters for whatever the cursor is on now, or to close if the cursor is not on something it can show parameters for

To confirm that this is a VSCodeVim bug:

5. Toggle VSCodeVim off
6. Repeat steps 1-3 above
7. The next/previous method overload parameter list will appear in the parameters window

To confirm that this is a focus issue:

8. Toggle VSCodeVim on
9. Repeat steps 1-2 above
10. When the parameters window appears, click inside the window. The window's border will highlight.
11. Press an arrow key ONCE. The previous/next overload's parameter list will appear and the window's border will dim
12a. If you press an arrow key again, the cursor will move as in step 4 above.
12b. If you click on the parameters window again, the window will take focus and be able to receive another key press.

**Expected behavior**
The parameters window should continue receiving key presses to navigate between method overload parameter lists until Esc is pressed. The cursor in the editor window should not move when the arrow keys are pressed.

**Screenshots**

[Animation of problem](https://i.imgur.com/8dRwZDn.gifv)
[Animation of behavior with VSCodeVim off](https://i.imgur.com/k3Dp4iY.gifv)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.14.5
- VSCode version: 1.46.1
- OS: Windows 10 Pro v1909

**Additional context**

**Comment by adam-c-anderson** [comment]
@J-Fields I noticed no adjustments were made to handling the Esc key. Does pressing Esc to clear the window work the same as when VSCodeVim is disabled?

**Comment by J-Fields** [comment]
Yep, that was fixed a few weeks ago, should be in the next release https://github.com/VSCodeVim/Vim/commit/1b4a3edd9c17f5fa271fd5e777c1e7f3b0e71b41

**Comment by adam-c-anderson** [comment]
🙌 Awesome, that's great news! 🙌
