### ISSUE TITLE
Support numbered registers

### ISSUE THREAD

**Issue by cpetrov** [VSCodeVim/Vim#500]
One common use case is to yank a text [1], delete something and paste the yanked text. Currently the yanked text (1) will be overwritten by the deleted text in the unnamed register. Last yank should be stored in the numbered register `0`.

Another useful feature is accessing and cycling through last deleted/changed text by using registers >=1. Using e.g. `u.` works for cycling through these registers because of a special behavior of the repeat command, increasing the used register on each repeat. 

[Vim documentation: Numbered registers "0 to "9](http://vimdoc.sourceforge.net/htmldoc/change.html#quote1)
[Vim documentation: redo register](http://vimdoc.sourceforge.net/htmldoc/undo.html#redo-register)

**Comment by rebornix** [comment]
It's a quite valid feature request, thanks for reporting it @cpetrov

**Comment by johnfn** [comment]
Absolutely a valid request. Putting it on the roadmap for 0.3 because I feel like it's one of the lesser-used features of Vim. If more people thumbs it up then I'll bump it in priority (and you can always feel free to take a whack at it in the mean time!)

**Comment by philipmat** [comment]
Registers are actually one of the *most* used features in vim, both in user operation (yanking to named register is a way of handling multiple clipboards, macro recordings save content into registers, etc) and in vim programming, though you're probably not going to implement VimL :)

**Comment by johnfn** [comment]
@philipmat I don't doubt that they get a good amount of use - the problem is that *so many* features get a good amount of use. 

But hey, this is a democracy - if this gets more thumbs up, we'll definitely get to it sooner. :)
