### ISSUE TITLE
Vim navigation very delayed when opening VSCode's settings.json for the first time

### ISSUE THREAD

**Issue by macintacos** [VSCodeVim/Vim#5003]
**Describe the bug**

For some reason that I haven't been able to determine, if I'm on a "fresh window" of VSCode (meaning that this is the first time I've opened the window I'm in) and I open VSCode's `settings.json` file, Vim takes about 15 seconds to actually accept input. It's kind-of maddening at times. Note: for me, this only happens with opening VSCode's `settings.json` for some reason - no other file behaves this way. I can go for long coding sessions with no issues, and then when I go to open`settings.json` it locks up for a time. Everytime this happens, I have made sure that all of my extensions have been "activated", so I'm not sure what's getting hung up. Additionally, after it happens once, the issue goes away; I can close `settings.json` and reopen it later without any issues. It only happens on the first launch of the file.

I've made a screenshare demonstrating the issue, which you can view here: https://share.getcloudapp.com/QwulXGb1.

Can I get some pointers for how to debug this? I can't tell if it's this extension or some other extension that's _blocking_ this extension, or if it's just VSCode. I can't tell from the recording that I shared what is actually happening, perhaps someone here knows better how to interpret what I'm seeing?

**To Reproduce**

1.  Open a new VSCode window
2.  Load VSCode's `settings.json`
3.  Try any vim motions
4.  Note that VSCode doesn't accept your input until much later, after it is done "Activating Extensions" (doesn't seem to note which extensions its activating though?)

**Expected behavior**

When I open `settings.json`, I should immediately be able to do whatever vim motions that I desire.

**Environment (please complete the following information):**

VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:17:14.222Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (7.34GB free)|
|Process Argv|-psn_0_2023918|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (149)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
html-snippets|abu|0.2.1
scss-lint|ada|0.1.10
vscode-caniuse|aga|0.5.0
vscode-javascript-snippet-pack|aka|0.1.5
Bookmarks|ale|11.3.1
project-manager|ale|11.1.0
search-crates-io|bel|1.2.1
color-info|bie|0.5.1
emojisense|bie|0.7.0
github-markdown-preview|bie|0.0.2
markdown-checkbox|bie|0.1.3
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
markdown-yaml-preamble|bie|0.0.4
vscode-fish|bma|1.0.16
htmltagwrap|bra|0.0.7
vscode-tailwindcss|bra|0.4.1
better-toml|bun|0.3.2
markdown-jira|chi|1.1.0
npm-intellisense|chr|1.3.0
path-intellisense|chr|2.2.1
open-html-in-browser|cod|0.1.21
gitignore|cod|0.6.0
disableligatures|Coe|0.0.8
compulim-vscode-closetag|Com|1.2.0
vscode-svgviewer|css|2.0.0
postcss|css|1.0.4
perl-toolbox|d97|1.4.0
transformer|dak|1.6.0
scala|dal|0.0.5
vscode-markdownlint|Dav|0.36.1
vscode-eslint|dba|2.1.6
vscode-dash|dee|2.4.0
confluence-markup|den|0.1.8
vscode-deno|den|1.25.0
binary-plist|dni|0.4.0
githistory|don|0.6.5
listFiles|don|0.0.3
xml|Dot|2.5.0
gitlens|eam|10.2.2
vscode-html-css|ecm|0.2.3
EditorConfig|Edi|0.15.1
vscode-npm-script|eg2|0.3.12
LogFileHighlighter|emi|2.8.0
vscode-great-icons|emm|2.1.47
vsc-material-theme-icons|equ|1.1.4
prettier-vscode|esb|5.1.3
vscode-go-test-adapter|eth|0.1.3
vscode-open-in-github|fab|1.2.3
vimL|fal|0.0.3
markdown-table-formatter|fcr|2.0.4
file-icons|fil|1.0.24
vscode-firefox-debug|fir|2.9.0
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.8
code-runner|for|0.11.0
shell-format|fox|7.0.1
sort-json-array|fvc|2.0.3
nightswitch|gha|1.1.0
vscode-pull-request-github|Git|0.17.0
go|gol|0.15.0
gc-excelviewer|Gra|3.0.37
todo-tree|Gru|0.0.177
terraform|has|2.0.2
npm-dependency-links|her|1.1.0
headwind|hey|1.6.5
vscode-settings-cycler|hoo|1.0.1
snooty|i80|0.0.10
output-colorizer|IBM|0.1.2
smarty|imp|0.3.0
customize-ui|ioc|0.1.45
monkey-patch|ioc|0.1.8
path-autocomplete|ion|1.14.0
hungry-delete|jas|1.6.0
docthis|joe|0.7.1
json2csv|kha|0.0.1
vscode-gutter-preview|kis|0.26.2
vscode-format-context-menu|lac|1.0.4
git-indicators|lam|2.1.2
rpm-spec|Lau|0.3.0
vscode-fix-checksums|leh|1.1.0
expand-region|let|0.1.4
bash-ide-vscode|mad|1.10.2
rust-analyzer|mat|0.2.232
Lisp|mat|0.1.10
rainbow-csv|mec|1.7.0
ecdc|mit|1.3.0
HTMLHint|mka|0.8.0
mongodb-vscode|mon|0.0.4
vscode-docker|ms-|1.3.1
vscode-kubernetes-tools|ms-|1.2.1
python|ms-|2020.6.91350
cpptools|ms-|0.28.3
vscode-typescript-tslint-plugin|ms-|1.2.3
debugger-for-chrome|msj|4.12.8
vscode-paste-image|mus|1.0.4
color-highlight|nau|2.3.0
autodocstring|njp|0.5.3
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
vscode-nunjucks-formatter|oki|0.1.3
fix-json|oli|0.1.2
advanced-new-file|pat|1.2.2
markdown-checkbox|PKi|1.7.0
material-icon-theme|PKi|4.2.0
vscode-css-peek|pra|3.0.2
text-power-tools|qcz|1.12.0
subtle-brackets|raf|3.0.0
vscode-xml|red|0.13.0
vscode-yaml|red|0.8.0
explorer-exclude-vscode-extension|Red|1.2.0
shellman|Rem|4.6.0
vscode-sort-json|ric|1.18.0
bash-debug|rog|0.3.9
zsh-debug|rog|0.1.3
nunjucks|ron|0.3.0
partial-diff|ryu|1.4.1
multi-command|ryu|1.4.0
crates|ser|0.5.1
code-settings-sync|Sha|3.4.3
vscode-brewfile|sha|1.0.0
trailing-spaces|sha|0.3.1
mdx|sil|0.1.0
vscode-fileutils|sle|3.0.1
snipsnap-vscode|sni|1.1.0
guides|spy|0.9.3
rewrap|stk|1.12.0
control-snippets|svi|1.9.1
ayu|tea|0.20.1
shellcheck|tim|0.9.0
go-to-method|tri|0.2.0
sort-lines|Tyr|1.9.0
errorlens|use|3.1.1
vscode-lldb|vad|1.5.3
highlight-matching-tag|vin|0.9.9
vscodeintellicode|Vis|1.2.9
vscode-icons|vsc|10.1.1
vim|vsc|1.14.5
gistfs|vsl|0.1.4
vscode-todo-highlight|way|1.0.4
change-case|wma|1.0.0
better-align|wwm|1.1.6
clang-format|xav|1.9.0
vs-code-wiki|Yun|0.4.9
markdown-all-in-one|yzh|3.1.0
material-theme|zhu|3.8.3
html-css-class-completion|Zig|1.19.0
vscode-open-in-github|ziy|1.3.6

(11 theme extensions excluded)

</details>

**Comment by J-Fields** [comment]
> Extensions (149)

Oh ***boy***. Yeah it's likely that VSCodeVim is getting blocked by some of these starting up or doing some other costly operation. The extension host is unfortunately single-threaded which leads to issues like these.

First step would be to disable extensions which are likely problematic (anything related to settings & JSON, I'd guess), then try to repro again

**Comment by macintacos** [comment]
I get that I have a bunch of extensions, but in my general day to day usage VSCode gets along just fine. I'll just work through them I guess; I'll let you know if I have any luck.

**Comment by macintacos** [comment]
Also I'd like to clarify; performance is perfectly fine on all file types, including `jscon`/`jsonc`; just doesn't work with settings. I only have two settings-related extensions, and disabling them (and the other json-related extensions) has done nothing so far. Still digging.

**Comment by macintacos** [comment]
Narrowed it down to the Markdown Table Formatter plugin. Disabling that removes the lag entirely. Will close this issue and open one up in that repo.
