### ISSUE TITLE
delete multi-lines working unexpectedly. (command 'd[number]')

### ISSUE THREAD

**Issue by usstwxy** [VSCodeVim/Vim#501]
### What did you do?
using command 'd[number]' to delete [number] + 1 lines in normal mode, such as 'd5'

### What did you expect to happen?
6 lines start from the cursor will be deleted when press Enter key after input 'd5'

### What happened instead?
1. Only the characters after the cursor have been deleted in first line. **The whole first line should be deleted.** 
2. Only deleted 5 lines (including the half of first line).

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: *The last version*
* OS: Windows10

**Comment by johnfn** [comment]
Thanks for the bug report, @usstwxy. This one should not be too hard.

**Comment by chrahunt** [comment]
This may be related, `d[motion]` is also behaving unexpectedly.

     v cursor here
    aaa
    bbb
    ccc

press `dj`, result:

    abb
    ccc

expected:

    ccc

With VSCode 1.4.0, VSCodeVim 0.1.4, Windows 10.

**Comment by xconverge** [comment]
I will take a look since I use this a lot ;)
