### ISSUE TITLE
`dap` deletes more than one paragraph

### ISSUE THREAD

**Issue by escape0707** [VSCodeVim/Vim#5012]
**Describe the bug**
`dap` deletes more than one paragraph

**Expected behavior**
`dap` deletes one paragraph

**Screenshots**
![1](https://user-images.githubusercontent.com/11014745/87238780-90382500-c439-11ea-87a5-88df402ee4e9.gif)

**Environment (please complete the following information):**
- Extension Name: `vim`
- Extension Version: `1.14.5`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.0-insider`

**Comment by escape0707** [comment]
I think maybe this issue only appears when deleting one-line-paragraph.

**Comment by sql-koala** [comment]
Hi,
yes, I think the problem only "triggers" when the paragraph is one line.
In fact, for me, dap then deletes to EOF, so the must be a bug.

I think I have found it. Will try to submit a PR.
