### ISSUE TITLE
Easymotion marker's colors are very dark

### ISSUE THREAD

**Issue by numToStr** [VSCodeVim/Vim#5019]
**Is your feature request related to a problem? Please describe.**
Easymotion marker colors are kinda black which is very hard to see on a dark theme. IDK if it's my theme or it's a bug.

**Additional context**
### Screenshot
![Screenshot_20200714_110506](https://user-images.githubusercontent.com/24727447/87388178-e89a2e80-c5c1-11ea-9e56-29624ff7c417.png)

vscode: 1.47.0
vscode-vim: 1.15.0
theme: [Horizon](https://marketplace.visualstudio.com/items?itemName=jolaleye.horizon-theme-vscode)

**Comment by aquaductape** [comment]
I have the same issue as well

theme: Dark+
vscode-vim: 1.15.0
vscode: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:30:34.302Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-40-generic

**Comment by J-Fields** [comment]
There might be a way we can make the defaults work on more themes, but here are the settings you want to change. I use red against a dark background, which works nicely.

`vim.easymotionMarkerForegroundColorOneChar`
`vim.easymotionMarkerForegroundColorTwoChar`

**Comment by aquaductape** [comment]
I forgot the greyscale on text was intended, since the original vim easymotion has it as well ( vscode is my daily code editor, the terminal not so much ). I agree with red against dark background.

**Comment by J-Fields** [comment]
Yeah if you don't like the greyscale, you can disable `vim.easymotionDimBackground`
