### ISSUE TITLE
Request: Use editor font for the easymotion markers

### ISSUE THREAD

**Issue by numToStr** [VSCodeVim/Vim#5020]
**Is your feature request related to a problem? Please describe.**
Currently, easymotion uses `Consolas` font for the markers and It looks weird. And I need to manually change the font for the markers. It would be great if the markers use the `editor.fontFamily` setting for the font as default.

**Describe the solution you'd like**
Use `editor.fontFamily` setting.

**Additional context**
### Screeentshot
![Screenshot_20200714_111431](https://user-images.githubusercontent.com/24727447/87389209-f18bff80-c5c3-11ea-82e7-997649af023f.png)

vscode: 1.47.0
vscode-vim: 1.15.0
font: Fira-Code

**Comment by J-Fields** [comment]
Frankly I thought that was the default already. I don't really see the need for this setting and the associated font size one. I think I'll change the defaults to be `editor.fontFamily` and `editor.fontSize`, then deprecate both

**Comment by numToStr** [comment]
> I'll change the defaults to be `editor.fontFamily` and `editor.fontSize`, then deprecate both.
Yeah, It will be a right thing to do. Waiting for the release🤘🏻.
