### ISSUE TITLE
Shortcut asterisk (wildcard) key incorrectly includes extra tab

### ISSUE THREAD

**Issue by windless0530** [VSCodeVim/Vim#5026]
VSCode Version: 1.46.0
Vim Extension Version: 1.15.0
OS Version: macOS Catalina 10.15.5

When my cursor is on some word with tab ahead, the tab was also included in the match pattern, which makes all the other occurrences of the actual word I want to search unable to navigate or hightlight

![image](https://user-images.githubusercontent.com/4645959/87523190-30e84800-c6b9-11ea-9f69-8aee07df309a.png)

**Comment by kvelicka** [comment]
+1, seeing the same thing and this seems like a very recent behaviour change as this feature used to work exactly as expected before.

VSCode Version: 1.47.0
Vim Extension Version: 1.15.0
OS Version: Ubuntu 18.04

**Comment by J-Fields** [comment]
Yeah I recently changed the behavior of `*`. I'll take a look when I get a chance

**Comment by J-Fields** [comment]
Turns out someone wrote a dumb "whitespace" regex that only included space characters. Sorry about that - I should test more often with tabs. This'll be fixed in the next release

**Comment by J-Fields** [comment]
Should've been closed automatically by 1fe1c24fe8b45777583b85c13ffc981ab179ad52, not sure what's up with github today

**Comment by konradsa** [comment]
Could we get a minor release to push out this fix? I use this quite frequently, and find that bug very annoying. Thanks!

**Comment by J-Fields** [comment]
Yeah, sorry - was planning on it this weekend but was busy with other things. I'll try to get a release out later today.

**Comment by konradsa** [comment]
Just got 1.16.0 and seems to work correctly again, thanks for the quick fix.

**Comment by windless0530** [comment]
> Just got 1.16.0 and seems to work correctly again, thanks for the quick fix.

Me too.
