### ISSUE TITLE
gJ doesn't work in visual mode

### ISSUE THREAD

**Issue by jeiea** [VSCodeVim/Vim#5027]
# What I did

1. Open some plain text file having several lines
2. Press `<Esc>VjjgJ`

# What I expected
Selected 3 lines should be joined without space.

# What I got
Nothing happens

# Environment
MacOS 10.15.5
vscode: 1.47.1
vscodevim: v1.15.0

**Comment by lusingander** [comment]
Since `gJ` is broken to begin with, it seems to be difficult to fix this unless #5014 is merged.
When #5014 is approved, I’d like to fix this.
