### ISSUE TITLE
Usage with [remote:ssh] when installed remotely causes significant cursor movement issue(s)

### ISSUE THREAD

**Issue by TheUnixDude** [VSCodeVim/Vim#5028]
**Describe the bug**
When using Code with a [remote:ssh] host, and this plugin locally, all is good. Code recommends installing this plugin on the remote as well. Doing so causes cursor movement to become erratic and unusable.

**To Reproduce**
1. Configure a remote host via [remote:ssh].
2. Install the Vim extension to your local host.
3. Open a remote source file (C/C++ was my tested file format) and use the up/down keys to move through the code. All is as expected. Cursor movement is smooth and fluid.
4. Install the Vim extension on the remote (in addition to the local copy), as recommended in "Local - Extensions".
5. Reload, and perform the same exercise as step 3. When moving the cursor up by holding down the cursor up key, the cursor will move up 10 or so lines, then back down 8, then up about 12, then back down 6, etc.

**Expected behavior**
I expect there to be no change in usability.

**Screenshots**
No Screenshot (since that would be worthless), but I can provide a screen recording of the bug when I get some time later in the week.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.15.0
- VSCode version: 1.48.0 (Insiders)
- OS: Debian Bullseye, fully patched as of 15 July 2020 

Version: 1.48.0-insider
Commit: c828a5339bca7222fd8f56ab98361a98f736d185
Date: 2020-07-14T05:39:08.529Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Linux x64 5.7.0-1-amd64

**Additional context**

**Comment by J-Fields** [comment]
Why do you want to install it remotely?

**Comment by Jawsingale** [comment]
Having the same issue with very slow input with vim on vscode while using SSH.  If I do not install it remotely, the plugin will not work while using SSH,   if I do install it remotely, I can barely type the lag is so bad.  Not sure what is needed to help.

**Comment by TheUnixDude** [comment]
> Why do you want to install it remotely?

Good question. I'm not sure "want' is the right term, as I'm just a user of the tool. Why does VS Code think I need to install it remotely?

**Comment by J-Fields** [comment]
> Why does VS Code think I need to install it remotely?

I think because of a recent configuration change we made to make it easier to use a version of `nvim` installed in WSL, but it was probably a mistake. Try putting this into your `settings.json`:

```json
"remote.extensionKind": {
  "vscodevim.vim": ["ui"]
},
```

**Comment by Jawsingale** [comment]
This works, Just tested it out @J-Fields.  Thanks :D

**Comment by J-Fields** [comment]
Cool, thanks for confirming! I think we need to change the default back to `UI` and document somewhere how to change it for users of neovim on WSL. Assigning myself to this issue for that

**Comment by TheUnixDude** [comment]
@J-Fields Yep, I can confirm, too. I no longer see the little bar icon asking me to install the extension remotely.

**Comment by J-Fields** [comment]
> Want me to close this, or do you have a workflow for closing it after your change makes it upstream?

I'll close it once I make the changes. Thank you for the report!
