### ISSUE TITLE
CamelCase motion not working

### ISSUE THREAD

**Issue by matheusfillipe** [VSCodeVim/Vim#5031]
**Describe the bug**
Camel case navigation does not work. 

**To Reproduce**
When I first  activated it it was working fine but after I restarted vscode doesn't work. In visual mode the camel or snake cases are simply ignored and the whole word is jumped.

**Config Options**

```
    "vim.camelCaseMotion.enable": true,
    "vim.neovimPath": "/usr/bin/nvim",
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["\\","\\"],
            "commands": [
                "workbench.action.showCommands",
            ]
        },
        {
            "before": ["\\","d"],
            "after":["g","d"],
        },
    {
        "before": ["Z", "Z"],
        "commands": [
            ":wq"
        ]
    },

    {
        "before": ["Z", "Q"],
        "commands": [
            ":q"
        ]
    },

    {
        "before": ["Z", "S"],
        "commands": [
            ":w",
        ]
    },
        {
            "before": ["<leader>", "r"],
            "commands": [
                "editor.action.rename"
            ]
        },
        {
            "before": ["<leader>", "m"],
            "commands": [
                "bookmarks.toggle"
            ]
        },
        {
            "before": ["<leader>", "b"],
            "commands": [
                "bookmarks.list"
            ]
        }
    ],
    "vim.statusBarColorControl": true,
    "vim.statusBarColors.replace": "",
    "vim.enableNeovim": true,
    "vim.visualstar": true,
    "vim.vimrc.path": "$HOME/.vimrc",
    "vim.vimrc.enable": false,
    "vim.useSystemClipboard": true,
    "vsicons.associations.files": [
    
```

- Extension (VsCodeVim) version: 1.15.0
- VSCode version:  1.47.1
- OS: Arch Linux

**Comment by pingshunhuangalex** [comment]
Look like you are binding `<leader> b` to something else. Maybe that's the reason?

**Comment by matheusfillipe** [comment]
Thanks for replying! I did remove all the keybindings and it still didn't work.

**Comment by pingshunhuangalex** [comment]
Well, I can only confirm it works on my end. Maybe it's the neoVim you turned on. The keybinding above has lots of issues I think. You didn't change the `<leader>` key which means it's bind to `\` by default, then some of the binding uses `\\`, the others use `<leader>`. Maybe wait for a contributor to see if they have any insights for this.

**Comment by matheusfillipe** [comment]
Turned off neovim and didn't help. Also corrected the `<leader>` issue.

**Comment by berknam** [comment]
When you say it doesn't work does it mean that none of the camelCaseMotion movements work? Is it failing only on visual mode but works on normal mode? What are the keys you're typing to try to do the camel case motions?

**Comment by afonsosalbrecht** [comment]
This isn't working for me. 

Below is my config file:
```
    "editor.lineNumbers": "relative",
    "editor.autoClosingQuotes": "never",
    "editor.autoClosingBrackets": "never",
    "vim.argumentObjectClosingDelimiters": [],
    "vim.changeWordIncludesWhitespace": true,
    "vim.highlightedyank.enable": true,
    "vim.hlsearch": true,
    "vim.sneak": true,
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<Esc>"
            ],
            "commands": [
                ":nohl"
            ]
        }
    ],
    "vim.camelCaseMotion.enable": true,
    "vim.easymotion": true,
```

- Extension (VsCodeVim) version: v1.25.2
- VSCode version: 1.79.2
- OS: Windows 10

And there's not shortcuts binded to "b".
