### ISSUE TITLE
It is not possible to execute global + normal commands that end on an space

### ISSUE THREAD

**Issue by danielo515** [VSCodeVim/Vim#5039]
Issue Type: <b>Bug</b>

Imagine that you want to add a prefix to a set of lines, but such prefix ends with an space. On the current implementation the space is being ignored, so the prefix appears "fused" with the next word. I tested it on vim and it works, so it should be a problem of how the extension sends the normal command to vim.

So, if you have

```
a = () => {}
b = () => {}
```

And you run (note the space at the end)

`:g/.*=/norm Iconst `

you get 

```
consta = () => {}
constb = () => {}
```

instead of
 
```
con sta = () => {}
con stb = () => {}
```

Extension version: 1.15.0
VS Code version: Code 1.47.1 (485c41f9460bdb830c4da12c102daff275415b53, 2020-07-13T22:43:02.577Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.46GB free)|
|Process Argv|-psn_0_626841|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by berknam** [comment]
This happens because we trim the command before running it. I'm not sure why we do this.

For now you can work around this by doing this: `:g/.*=/execute "norm Iconst "` (there is a space between `t` and `"`)

**Comment by J-Fields** [comment]
Yeah we shouldn't be indiscriminately trimming like that. I've got a stash lying around with some refactors to our parsing logic. I'll polish that up and then handle this.

**Comment by danielo515** [comment]
Fixed? Wow thanks!

**Comment by J-Fields** [comment]
Yep, it'll be in the next release (trying to get that out before next week)
