### ISSUE TITLE
Surround and other plugins not working with Neovim Ex commands

### ISSUE THREAD

**Issue by austinclem1** [VSCodeVim/Vim#5045]
**Describe the bug**
Ex commands that use surround don't seem to work from VSCode.
For example, if I try to surround a word with quotes using the command line I would try:
`:norm ysiw"`
This command works as expected when I use it in nvim itself. I have the surround plugin active in VSCode and installed in Neovim.
I do have Neovim enabled in VSCodeVim and most other things seem to be working great.

Not sure how plugins are loaded in Neovim etc. (or how they work at all really). Could this have something to do with plugins not being active in whatever manner VSCode is executing Neovim?

Also I just tried using the sneak plugin in the same way to see what would happen.
I have the same keybindings set up in VSCode and Neovim, so `s` starts sneak rather than substitute in both editors from normal mode.
If I use `:norm sva` in nvim, it sneaks to the letters 'va'. If I use the same command from VSCode it starts substituting and then types the characters 'va', as it would if I didn't have sneak installed.

By the way, other :norm commands seem to work fine from VSCode i.e. `:norm d2w` does delete two words.

Thanks for your work everyone

**Environment:**

- Extension (VsCodeVim) version: 1.15.0
- VSCode version: 1.48.0-insider
- OS: Windows 10
- Neovim version: 0.5.0-594-ga02a267f8

**Comment by J-Fields** [comment]
This is because these plugins are emulated within VSCodeVim, not neovim

**Comment by berknam** [comment]
This could probably be done if we didn't spawn neovim with `-u NONE`. Do you know of any specific reason why we don't spawn neovim with the users configuration?

I can see that making the spawn and any call to neovim being slower. Maybe that was the reason?!

I think that if we spawn neovim with the users configurations this issue would work. Maybe this could be behind a configuration for the user to choose?

**Comment by austinclem1** [comment]
Sorry about closing and opening I just got the git app and hit the wrong button haha. Yeah spawning neovim with the user config sounds promising

**Comment by austinclem1** [comment]
After removing `-u NONE` on my machine I can now use surround and my other neovim plugins from commandline in vscode, doesn't seem slow or anything either. I guess we just need to figure out if there's some other reason it was set up to not use a config

**Comment by J-Fields** [comment]
Hmm, interesting. I don't know the original reason behind this (probably just to keep the behavior more consistent). I think removing `-u NONE` is reasonable, but this should probably be configurable.
