### ISSUE TITLE
Mapping $ not working as expected when used with selection commands

### ISSUE THREAD

**Issue by EddieCTian** [VSCodeVim/Vim#5059]
**Describe the bug**
In the settings.json file the commands are recognized, but are not executed properly in the editor when combined with selections. 

I have , (unmapped by default) mapped to $ (end of line) and using it in conjunction with selection commands does not produce the expected result

**To Reproduce**

1. Open the settings.json file
2. Type
```
"vim.normalModeKeyBindings": [
    {
        "before": [","],
        "after": ["$"]
    }
]
```
3. Return to command mode
4. Type 
```
v,
```
or 
```
c,
```
or any other selection-based command

**Expected behavior**
v, should select the text from the current cursor location to the end of the line, like v$, but does not. 
c, should delete the text from the current cursor location to the end of the line and change mode to insert, like c$, but does not. 

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.
```
/C:/Program_Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] Extension Startup: debug: Start
/C:/Program_Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:266 [Extension Host] Extension Startup: debug: Finish.
console.ts:137 [Extension Host] ModeHandler: debug: handling key=,.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=,. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:137 [Extension Host] Remapper: verbose: key=,. keySlice=,.
console.ts:137 [Extension Host] Remapper: debug: normalModeKeyBindingsMap. match found. before=,. after=$. command=undefined.
console.ts:137 [Extension Host] ModeHandler: debug: handling key=$.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=$. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:137 [Extension Host] Remapper: verbose: key=$. keySlice=$.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=$. mode=Normal. keybindings=normalModeKeyBindingsNonRecursiveMap.
console.ts:137 [Extension Host] ModeHandler: debug: handleKeyEvent('$') took 4ms
console.ts:137 [Extension Host] ModeHandler: debug: handleKeyEvent(',') took 4ms
console.ts:137 [Extension Host] ModeHandler: debug: handling key=v.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=v. mode=Normal. keybindings=normalModeKeyBindingsMap.
console.ts:137 [Extension Host] Remapper: verbose: key=v. keySlice=v.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=v. mode=Normal. keybindings=normalModeKeyBindingsNonRecursiveMap.
console.ts:137 [Extension Host] ModeHandler: debug: handleKeyEvent('v') took 9ms
console.ts:137 [Extension Host] ModeHandler: debug: handling key=,.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=,. mode=Visual. keybindings=visualModeKeyBindingsMap.
console.ts:137 [Extension Host] Remapper: debug: trying to find matching remap. keys=,. mode=Visual. keybindings=visualModeKeyBindingsNonRecursiveMap.
console.ts:137 [Extension Host] ModeHandler: debug: handleKeyEvent(',') took 2ms
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.47.2
- OS: Windows 10 home

**Additional context**

I haven't tested much else, but the error seems to occur for all movement-based remaps (such as w, e, b) when combined with a selection command.

**Comment by berknam** [comment]
NormalModeKeyBindings only apply in normal mode. When you press 'v' you enter visual mode, then it's the "visualModeKeyBindings" that apply. In VSCodeVim you have the following:

- "vim.normalModeKeyBindings": the same as "nmap"
- "vim.normalModeKeyBindingsNonRecursive": the same as "nnoremap"
- "vim.insertModeKeyBindings": the same as "imap"
- "vim.insertModeKeyBindingsNonRecursive": the same as "inoremap"
- "vim.visualModeKeyBindings": the same as "xmap"
- "vim.visualModeKeyBindingsNonRecursive": the same as "xnoremap"
- "vim.commandLineModeKeyBindings": the same as "cmap"
- "vim.commandLineModeKeyBindingsNonRecursive": the same as "cnoremap"

And after PR #4735 gets merged there will be:

- "vim.operatorPendingModeKeyBindings": the same as "omap"
- "vim.operatorPendingModeKeyBindingsNonRecursive": the same as "onoremap"
