### ISSUE TITLE
VSCodeVim not picking up some bindings from .vimrc

### ISSUE THREAD

**Issue by sangonzal** [VSCodeVim/Vim#5067]
**Describe the bug**
I'd like to remap `oo` to `o<Esc>k` and `OO` to `O<Esc>j`. I have this mapping set on a .vimrc file as

- `nmap oo o<Esc>k`
- `nmap OO O<Esc>j`

I've set  `"vim.vimrc.enable": true` in settings.json, and although it's picking up most of the .vimrc, its not picking up this mapping. I've also tried to set the binding on settings.json: 
```
    "vim.vimrc.enable": true,
    "vim.useSystemClipboard": true,
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["o", "o"],
            "after": ["o", "<Esc>", "k"]
        },
        {
            "before": ["O", "O"],
            "after": ["O", "<Esc>", "j"]
        }
    ],
```

**Expected behavior**
Expect to insert new line, and exit inset mode. 

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.47
- OS: Windows 10

**Additional context**
I'm new to both vscode and vim, so it might not be configured correctly on my part, but have not been able to find any documentation that has helped.

**Comment by sql-koala** [comment]
These kinds of mapping ( two keys, where the first is not: leader, g, z) don't work right now.
You will have to wait a bit for this PR:
https://github.com/VSCodeVim/Vim/pull/4735

leader+j and leader+k would work, I think thats in one of Tpope's config.

**Comment by sangonzal** [comment]
I see. Thanks for clarifying, I'll be on the lookout for when that PR gets merged.
