### ISSUE TITLE
TaskQueue error pops up when jumping to a definition via definition peek

### ISSUE THREAD

**Issue by pingshunhuangalex** [VSCodeVim/Vim#5082]
**Describe the bug**
With Vim extension turned on, when I jump to the definition (in another file) by double-clicking the definition peek(preview), a TaskQueue pops up...

**To Reproduce**

1.  Go to a JS file (I'm using React in my case)
2.  Press F12 to jump to the imported component
3.  The peek (definition preview) will show up when there are multiple destinations
4.  Double click one destination to go there
5.  The TaskQueue error pops up in the bottom right corner of the screen

**Expected behavior**
No error should pop up and vim should work as usual

**Screenshots**
![image](https://user-images.githubusercontent.com/17170199/88615745-e5309800-d0d5-11ea-92eb-b39f5e587a5a.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.48.0-insider
- VSCode version: 1.16.0
- OS: MacOS Catelina 10.15.6

**Comment by berknam** [comment]
I'm not able to reproduce this on Windows 10. Does this happen on every document for you or just those two? I think this might be related to the sizes of the documents. Is it possible to get access to those two documents you mentioned so one can try to reproduce that?

**Comment by pingshunhuangalex** [comment]
Hi @berknam 

Sorry, I can't reproduce it stably myself after I restart VS Code. All I can say is the bug has been on and off for at least months now, but I haven't found a reliable way to reproduce it.

The document (file) is definitely not big (<500 lines), but the project is huge. I can't really share anything cuz it's a company one, but yeah the repo is massive, and I'm using Mac (not sure if this makes a difference)

I'll wait to see if others ran into similar issues cuz I guess it's a bit hard for you to proceed if it's not reproducible. Thanks anyway.

**Comment by pingshunhuangalex** [comment]
@berknam I know how to stably reproduce it now.

The file just needs to be in preview mode (the file title is italic and you can quickly switch to other files). In this status, if I use F12 to jump to another file (still in preview mode), the error is guaranteed to pop up.

Hope the extra detail helps. Thanks.

**Comment by berknam** [comment]
I still can't reproduce it. I think I know what might be happening and if it is what I believe there is currently a fix for it in master. If you can, try to make a build of this extension from master to see if it still happens. If not we'll have to wait for a new version to be pushed to see if it fixes that.
