### ISSUE TITLE
I want normal mode in the terminal

### ISSUE THREAD

**Issue by RaderH2O** [VSCodeVim/Vim#5083]
So I am a NeoVim user and I wanted to try VS Code , I had fun with it , specially when I found out it had a vim plugin!
But there were some limitations and one of them annoys me so much .

Well , when in a VS Code terminal , I always want to be able to use normal mode , since most of my keymappings are in normal mode . And why do I need it? For switching to another split WITHOUT touching the mouse , for easier movement , visual mode etc.

Although I tried to find a way/alternative to this , I found nothing .

**Comment by advzr** [comment]
I had the same problem and added the following to `keybindings.json`

```json
  {
    "key": "alt+h",
    "command": "workbench.action.navigateLeft"
  },
  {
    "key": "alt+l",
    "command": "workbench.action.navigateRight"
  },
  {
    "key": "alt+k",
    "command": "workbench.action.navigateUp"
  },
  {
    "key": "alt+j",
    "command": "workbench.action.navigateDown"
  },
```

Now I can use these shortcuts to navigate windows in VS Code. Works to navigate to the sidebar too.

**Comment by RaderH2O** [comment]
> I had the same problem and added the following to `keybindings.json`
> 
> ```json
>   {
>     "key": "alt+h",
>     "command": "workbench.action.navigateLeft"
>   },
>   {
>     "key": "alt+l",
>     "command": "workbench.action.navigateRight"
>   },
>   {
>     "key": "alt+k",
>     "command": "workbench.action.navigateUp"
>   },
>   {
>     "key": "alt+j",
>     "command": "workbench.action.navigateDown"
>   },
> ```
> 
> Now I can use these shortcuts to navigate windows in VS Code. Works to navigate to the sidebar too.

Thanks so much! omg you literally made my life easier

**Comment by ELLIOTTCABLE** [comment]
This doesn't necessarily solve the original issue, though; plenty of other vim-mode tools would be fantastic in the integrated-terminal.

For instance, I'm desperately missing being able to <kbd>Ctrl</kbd><kbd>\\</kbd> and then navigate/select/copy/manipulate the terminal-scrollback with my normal Vim keybindings.
