### ISSUE TITLE
Neovim command fail

### ISSUE THREAD

**Issue by FreeVTS** [VSCodeVim/Vim#5090]
**Describe the bug**
I'm using vscode with Vim plugin and sometime write ex command using Neovim configurred through Vscode.

The following command produce an error code :
put=strftime("c")

The error code is :
E488: Trailing characters

**To Reproduce**

1.  Go on ex mode using ':' key.
2.  Type "put=strftime("c")" excluding the double quote at the beginning and end of this command.
3.  The error "E488: Trailing characters" appears in the state bar on the left bottom of vscode.

**Expected behavior**
In the file that have the focus, where the cursor is placed, you're supposed to now have the current time formatted. 

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.47.3
- OS: Windows_NT x64 10.0.17763
- Neovim version: 0.4.3

Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by tagniam** [comment]
Hey @FreeVTS, this should be fixed once #5063 is merged. Thanks for the bug report!
