### ISSUE TITLE
Muted colors after easymotion use

### ISSUE THREAD

**Issue by Technik-J** [VSCodeVim/Vim#5092]
After use of easymotion colors look muted. On the screenshot I color picked the same pixel before and after use of easymotion, the hex values do not match. Even with the naked eye you can see that the colors different. After changing editor tab, colors looks normal again.

![vim-easymotion-muted-colors](https://user-images.githubusercontent.com/17809291/89006285-cfaeae80-d31f-11ea-8d04-6e96687c0ffb.png)

- Extension (VsCodeVim) version: v1.16.0
- VSCode version: 1.47.3
- OS: Windows 10

**Comment by berknam** [comment]
Is this happening every time you use easymotion or just sometimes?

**Comment by Technik-J** [comment]
This is happening every time. I decided to test it against different file types. I see this behavior with .py, .js, .css files, but .html, .md and .json are not affected. I tried changing the setting 'Easymotion Dim Background', but it has no effect on this.

**Comment by berknam** [comment]
It happens even with `"vim.easymotionDimBackground": false`? *(I was almost sure this was related to the `filter: grayscale(1)` when using the dim background)*
I'm currently making some changes to the easymotion default look, I have another suspicion of what might be making that. When I have a working version I will tell you so you can test it to see if it fixes this.

**Comment by berknam** [comment]
@Technik-J 
Can you check PR #5108 to see if it fixes this for you?

**Comment by Technik-J** [comment]
This fixes it. Thank you.
