### ISSUE TITLE
dot command eats up spaces

### ISSUE THREAD

**Issue by WeCodingNow** [VSCodeVim/Vim#5097]
In vim if you enter insert mode and type "thing <ESC>" and then, for example, type "3.", the result will be "thing thing thing thing "; if you do the same in VSCode VIM, the result will be "thingthingthing".

**To Reproduce**

1. Open a text file
2. press "I" to enter insert-mode
3. type "thing " (with a space after g) and then exit the insert mode via pressing Escape or whatever your keybind is
4. while in normal mode, press 3 (or another number of your liking) and then press . (dot)
5. observe

**Expected behavior**
The text file contains "thing thing thing thing "

**Actual behavior**
The text file contains "thingthingthingthing"

**Screenshots**

vanilla vim:
![image](https://user-images.githubusercontent.com/9677869/89068804-abcc8680-d37a-11ea-9876-3c9cf90736ad.png)
after executing "3."
![image](https://user-images.githubusercontent.com/9677869/89068884-c999eb80-d37a-11ea-9c63-031f66ece5a0.png)

VSCode VIM
![image](https://user-images.githubusercontent.com/9677869/89068917-d9193480-d37a-11ea-8e51-d69cf71d0f50.png)
after executing "3."
![image](https://user-images.githubusercontent.com/9677869/89068952-e6362380-d37a-11ea-974a-f8ad400a84c9.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.47.3
- OS: Linux Mint 19.1

**Comment by J-Fields** [comment]
This was fixed at some point
