### ISSUE TITLE
Misbehave with spread paste in multicursor insert mode

### ISSUE THREAD

**Issue by karmicdude** [VSCodeVim/Vim#5098]
**Describe the bug**

Ignored `spread` setting in multi cursor insert mode

**To Reproduce**
1. Copying N lines
2. Selecting N lines in Visual Block mode
3. Going to Multi Cursor mode (Shift + i)
4. Pasting N lines, copied in buffer on step 1
5. Each cursor pastes not a single line, but the full text, like a default behaviour with `full` value `editor.multiCursorPaste`

**Expected behavior**
Each cursor pastes a single line of the copied text

**Screenshots**

![vscode_multicursor](https://user-images.githubusercontent.com/759980/89069035-5493d980-d3ad-11ea-87e7-13e429ef8e75.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.47.2
- OS: Arch linux

**Comment by sql-koala** [comment]
I can reproduce this. Same happens if you:
1. start with multicursor
2. yank something
3. switch to insert mode and paste with c-r

I have a fix ready.
