### ISSUE TITLE
Unexpected cursor shape with Go To Definition

### ISSUE THREAD

**Issue by JasonRitchie** [VSCodeVim/Vim#510]
### What did you do?

Open two source files where one file references a type in the other file. I used .fs files; one with a record type that includes a record type from the other file.

Leave both files in Insert mode. From one file use F12 Go To Definition to navigate to the other file. Then press a vim mode command such as insert or append.

### What did you expect to happen?
I expected to be able to Go To Definition and see the cursor indicating the current vim mode.

### What happened instead?
The cursor indicates normal mode but typing a mode command inserts the letter.

### Technical details:

* VSCode Version: 1.3.1 e6b4afa53e9c0f54edef1673de9001e9f0f547ae
* VsCodeVim Version: 0.1.3
* OS: macOS El Capitan 10.11.5

### Extensions installed
EditorConfig 0.3.1
Ionide-FAKE 1.1.0
Ionide-Paket 1.2.1
Ionide-fsharp 2.2.7
Path intellisense 1.0.2
PowerShell 0.6.1
C# 1.3.0
Mono Debug 0.10.20
yo 0.8.5
vscodevim 0.1.3

**Comment by JasonRitchie** [comment]
![giphy](https://cloud.githubusercontent.com/assets/2144273/17100290/7ae110d2-523b-11e6-915b-0fde651ea4ef.gif)
[VsCodeVimIssue510Project.zip](https://github.com/VSCodeVim/Vim/files/381373/VsCodeVimIssue510Project.zip)

**Comment by johnfn** [comment]
As this isn't really a critical error, just an annoyance, I'm going to put it in the backlog for now. PRs are always welcome.

**Comment by Paxxi** [comment]
This doesn't just affect go to definition, I've seen it as well just switching between two editor groups.
