### ISSUE TITLE
:d[elete] doesn't work with negative ranges and current line(.)

### ISSUE THREAD

**Issue by CaptainDredge** [VSCodeVim/Vim#5103]
**Describe the bug**
VSCodeVim doesn't mimic vim functionality with relative line ranges. Commands like `:.,-3d`, `:-1,-3d`, `:.-1,.-3d` don't work as expected. VscodeVim deletes the line between the given range and does not include the boundaries in this case for eg, command `:.,-4d` will not delete the current line and the 4th line above the current line, it just deletes in between lines.

**To Reproduce**

First In VSCode set `editor.lineNumbers` to `relative`

Consider following Initial editor state
![image](https://user-images.githubusercontent.com/20185657/89105013-83de3100-d415-11ea-8a20-a3b4da1b1409.png)

Execute: `:.,-4d`

Final State: 
![image](https://user-images.githubusercontent.com/20185657/89105062-ef280300-d415-11ea-931c-617698381a21.png)
You can see that even the cursor position after executing command is pretty wierd.

**Expected behavior**
It should include the initial and final line of range in deletion.

Now executing the same command in vim.
Initial State:
![image](https://user-images.githubusercontent.com/20185657/89105357-4d55e580-d418-11ea-9c87-89e49ecc7d75.png)

Execute: `:.,-4d`

Final State:
![image](https://user-images.githubusercontent.com/20185657/89105395-aa519b80-d418-11ea-833d-673a39e2b37e.png)
The final position of cursor is on line 4

- Extension Name: `vim`
- Extension Version: `1.16.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.47.3`

Related PR: https://github.com/VSCodeVim/Vim/pull/3071

**Comment by J-Fields** [comment]
Seems like this was fixed at some point - let me know if you can still reproduce
