### ISSUE TITLE
Replace with multiple cursors on a line replaces in the wrong location

### ISSUE THREAD

**Issue by max-sixty** [VSCodeVim/Vim#5115]
**Describe the bug**

**To Reproduce**

1.  Copy a word to the clipboard `yaw`
2.  Create multiple cursors on the same line ~`Ctrl-d`~ `Cmd-d`
3.  Run replace `griw`
4.  See the word under the second cursor isn't replaced correctly

**Expected behavior**
Replace under both cursors as though they were run independently

**Screenshots**
This follows the exact keystrokes above: https://youtu.be/569BSfF-3zY
(I got stuck on QuickTime / formats / uploading to GH, hope this is OK)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.47.3
- OS: MacOS

**Additional context**

**Comment by sql-koala** [comment]
![20200807004400-0b6a9d442f](https://user-images.githubusercontent.com/30384885/89585802-ce5d1480-d83e-11ea-9d4e-a386e409f660.gif)

;-)

That's my bugfix.

**Comment by max-sixty** [comment]
@sql-koala what program is that?

I think the difference is between selecting with `Cmd-d` and `2gb`. I get the same result as you when using `2gb`. Can you repro with `Cmd-d`?

**Comment by sql-koala** [comment]
That's strange. First: I could reproduce it with gb. What I am showing there is my "fix" where I changed a few lines of code on "gr".
I can't try Cmd-D because I am on windows.
The difference could be that gb is handled by vim, where Cmd-D could be handled by vscode (and so somehow vim could know less about the second cursor). But I dont think that is plausible.

**Comment by max-sixty** [comment]
Can you run "Add Selection to Next Match" as a manual command rather than with `Cmd-D`?

**Comment by sql-koala** [comment]
Yes, I can run that command manual. Then i can reproduce. But i also can reproduce with "gb". I think it's a legitimate bug.

What I am showing in the gif is my bugfix where I changed the code that does the text replace. It works in both cases: gb/ctrl-d and manually adding the second cursor by command.

**Comment by max-sixty** [comment]
OIC. Great!

BTW what is the program that you're using to show the keystrokes and produce the gif?
