### ISSUE TITLE
GitHub Sponsors / Patreon

### ISSUE THREAD

**Issue by max-sixty** [VSCodeVim/Vim#5116]
I use VSCode / Vim for a lot of my day, and it makes a material impact on my productivity.

I can't really contribute given my Javascript skills (I have done a couple of tiny doc PRs). I'd be very keen to subscribe to a GitHub Sponsors / Patreon to support its continued development. 

IIRC, @J-Fields has said that having a GH Sponsors could be unfair because others have built so much. But the funds (I imagine fairly token, at least initially) would be for future development — there are 849 open issues, so there's plenty to do! — and having something seems fairer than having nothing. 

That said, I recognize that OSS + $ can be complex, so feel free to close if it's a non-starter.

**Comment by Taeluf** [comment]
You could also work issues.
- Find duplicates & leave links, perhaps recommending OP to close the issue. 
- Look for things that might have been resolved, but not closed.

**Comment by Taeluf** [comment]
[OpenCollective](https://opencollective.com/) might be a good platform?
Maybe a Not For Profit could be formed around VSCodeVim, but that's a whole other headache too.

**Comment by max-sixty** [comment]
I agree those are useful tasks @Taeluf and that's a good outlet for some people to contribute back.

> Maybe a Not For Profit could be formed around VSCodeVim, but that's a whole other headache too.

Agree re the effort for something like a non-profit. I for one would be very happy giving directly with GH Sponsors — the work is fairly centralized already, and (unfortunately) it's not going to be enough money to cause adverse incentives...

I'm happy to help with the setup if @J-Fields gives the go-ahead!

**Comment by J-Fields** [comment]
I do now have GitHub Sponsors set up, if anyone insists on contributing.

**Comment by max-sixty** [comment]
> I do now have GitHub Sponsors set up, if anyone insists on contributing.

Just joined as your first!

(Maybe set up some tiers / suggested amounts?)

**Comment by J-Fields** [comment]
Much appreciated!
