### ISSUE TITLE
Support :s/foo/bar/g style substitutions when text is selected

### ISSUE THREAD

**Issue by oheard** [VSCodeVim/Vim#512]
* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.3
* OS: Ubuntu 16.04

**Comment by rebornix** [comment]
@oheard definitely this command is useful and easy to implement, I'll add this ASAP.

**Comment by johnfn** [comment]
That is a large number of reactions. This looks like a good one to prioritize, @rebornix.

**Comment by rebornix** [comment]
ha, didn't notice so many people drop reactions on it. Fixed via #525.

**Comment by johnfn** [comment]
@oheard My exact steps are:

I type in

```
foobar
foobaz
```

Then I hit : which prefills `'<,'>` for me. I type the full command `'<,'>s/foo/quirk/` and hit enter and the text is changed to:

```
quirkbar
quirkbaz
```

Is that what you are doing? 

(Note that if you delete `'<,'>`, only the first of the two foos will be replaced with quirk, just like in Vim.)

**Comment by oheard** [comment]
Well spotted @johnfn. I didn't notice the prefilled/selected '<,'> because naturally as soon as I type ':' I immediately type 's', clearing the input.

Thanks for the feedback.

**Comment by johnfn** [comment]
Cool, no worries @oheard! 

@rebornix - is there any workaround here?

**Comment by rebornix** [comment]
@johnfn Code always selects the placeholder input so it's impossible right now. But I've already filed an issue there https://github.com/Microsoft/vscode/issues/10582 and it's verified.
