### ISSUE TITLE
Cannot escape insert mode using custom keybinding `fd` when I type `ffd`

### ISSUE THREAD

**Issue by off99555** [VSCodeVim/Vim#5125]
**Describe the bug**
I want to escape the insert mode without pressing `Esc` because it requires moving fingers too far away from the home row. So I assigned `fd` to be pressed quickly to escape the insert mode. The following are the settings shown in my `settings.json` file.
```jsonc
    "vim.insertModeKeyBindings": [
        {
            "before": ["f", "d"], // smash escape
            "after": ["<Esc>"]
        }
    ],
```

The key works fine. But it doesn't work when I type `ffd`. This prevents me from escaping the insert mode after I type any word that ends with `f` e.g. `leaf`, `df`, `buf`, etc.

**To Reproduce**

1.  Copy my settings into your `settings.json`
2.  Open an empty file and press `i` to enter insert mode
3.  Type `buf` then quickly followed by `fd` to escape the insert mode.
4.  Insert mode will not be escaped. You will see `buffd` on the screen instead, which is not what I wanted.

**Expected behavior**
There should be the text `buf` without `fd` on the screen and then I should be in normal mode.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.48.0
- OS: Windows 10

VS Code About menu:
```
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

How do I fix this issue?

**Comment by off99555** [comment]
When should I expect to get this feature in my VSCode?

**Comment by J-Fields** [comment]
In the next VSCodeVim release, which should be sometime this week
