### ISSUE TITLE
The mapped motions was not executed correctly after a operation.

### ISSUE THREAD

**Issue by Elendeer** [VSCodeVim/Vim#5128]
**Describe the bug**
In normal mode, when I use a mapped motion key after an operation, the command executed is not the mapped motion, but the original motion corresponding to the key.

**To Reproduce**
For example:

1.  Write the following in setting.json and save it:
```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["L"],
            "after": ["7", "l"]
        },
    ]
```

2.  Click on 'dL'

3.  The result is that the editor deletes from the current position to the bottom line of the screen instead of deleting 7 characters to the right.

**Expected behavior**
Use the mapped motions correctly.

**Environment :**

- Extension (VsCodeVim) version: v1.16.0
- VSCode version: version 1.48
- OS: Windows10

**Comment by berknam** [comment]
There is a fix for this in master now which will be on the next release but it will require you adding a remap for operatorPendingMode besides the normal mode, like this:
```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["L"],
            "after": ["7", "l"]
        },
    ],
    "vim.operatorPendingModeKeyBindingsNonRecursive": [
        {
            "before": ["L"],
            "after": ["7", "l"]
        },
    ]
```
This way you'll be able to use `L` with operators as well like `dL`, `cL`, `yL`.
