### ISSUE TITLE
Support ctrl+a and ctrl+x to increment/decrement numbers

### ISSUE THREAD

**Issue by oheard** [VSCodeVim/Vim#513]
* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.3
* OS: Ubuntu 16.04

**Comment by sectioneight** [comment]
I can make this happen, probably tonight

**Comment by jpoon** [comment]
Sweet, thanks @sectioneight. Adding the in-progress tag.

**Comment by timfayz** [comment]
@ascandella exactly now I'm trying to use Ctrl-X in normal mode to inc/dec the numbers but instead I get the _whole line cut_ (into clipboard). It seems like this is default in vscode. Disabling extension doesn't change the behaviour. I tried to find the option where I can overwrite it but there is no one.

Any ideas?  

```
Extension:
Name: Vim
Id: vscodevim.vim
Description: Vim emulation for Visual Studio Code
Version: 1.9.0
Publisher: vscodevim
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

Vscode:
Version: 1.35.0
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T01:13:26.790Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-20-generic
```

**Comment by will-ockmore** [comment]
I'm running into the opposite issue to @timfayz , on the most recent build of VSCode on a mac and I'm not able to increment numbers with `<C-a>`, however I can decrement with `<C-x>`. 

Enabling debug logs, I see
```
ModeHandler: debug: handling key=<C-x>.
```
in the logs for a decrement, but nothing is logged when I press `<C-a>`. As someone unfamiliar with the codebase, I assume this means that this key combination is not being handled? No remappings are active that should affect this behaviour

**Comment by idoo** [comment]
What do you think if we could add toggles for booleans as well?

**Comment by J-Fields** [comment]
> What do you think if we could add toggles for booleans as well?

This isn't built into Vim, right? It seems like something that would better be implemented via vimscript once it's supported

**Comment by max-otto** [comment]
> 

I'm having the same issue as @will-ockmore but on WSL2 Ubuntu.

**Comment by GhengS** [comment]
I want to set, to treat all numbers as decimal,
So I tried `:set nrformats=`
but error
`E518: Unknown option: nrformats`
Can you tell me why, or is there another way to do it?

**Comment by GhengS** [comment]
Looking forward to your answer, I wish you good health

**Comment by AtsushiSakai** [comment]
I'm having the same issue as  @will-ockmore and @max-otto, decrement with <C-x> works, but increment with <C-a> does not work.... Any information to solve this is welcome...

I'm using
Vscode
Version: 1.84.0
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:28:21.782Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.15.0-88-generic

**Comment by grdzien** [comment]
This is pure evil, how do I get rid of this anti-UX behavior?
