### ISSUE TITLE
Keep your cursor centered vertically on the screen

### ISSUE THREAD

**Issue by ofrades** [VSCodeVim/Vim#5133]
When scrolling or searching through a large file, it can be convenient to keep the cursor line near the middle of the screen (vertically centered within the window).

Centered:
`:set so=999`
Restore default:
`:set so=0`

Source:
https://vim.fandom.com/wiki/Keep_your_cursor_centered_vertically_on_the_screen

**Comment by J-Fields** [comment]
VSCode supports this via `editor.cursorSurroundingLines`
