### ISSUE TITLE
1.16.0 (and several earlier versions) Suddenly stops working on vs code 1.48.0 (on mac)

### ISSUE THREAD

**Issue by michaelscruz** [VSCodeVim/Vim#5136]
**Describe the bug**
After using the editor (and plugin) all morning as normal, when I returned after a break this afternoon, none of the vim keybindings were working. In fact, there was nothing I was able to do in the editor at all without disabling the plugin. I tried reverting to earlier versions of the plugin (1.15.0, 1.14.5, 1.14.4), still nothing. I restarted vs code - still nothing. I restarted my laptop - nothing.

When I try to use the editor, I get the "Activating Extensions" message in the footer for a few seconds, but no effect on the editor window.

It randomly started working again temporarily, then broke once more. I was unable to determine the cause for those changes.

**Expected behavior**
The editor should work with vim keybindings operational.

**Screenshots**
The Activating Extensions message whenever I press a key within the editor:
![image](https://user-images.githubusercontent.com/8717351/90689660-6515d200-e23e-11ea-84bc-e584612b34eb.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0
- VSCode version: 1.48.0
- OS: macOS Catalina 10.15.6

**Comment by J-Fields** [comment]
Can you run the command `Developer: Startup Performance` and tell me what that shows you?

**Comment by michaelscruz** [comment]
So...after closing all my tabs and restarting the editor, it seems to work for the moment. I did have a fairly large number of tabs open, but I didn't think it was an unusually large number.

Just in case that isn't it, here is what you've requested:
```
## System Info

* Code: 1.48.0 (db40434f562994116e5b21c24015a2e40b2504e6)
* OS: darwin(19.6.0)
* CPUs: Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz(4 x 2700)
* Memory(System): 8.00 GB(0.24GB free)
* Memory(Process): NaN MB working set(169.17MB private, 3.95MB shared)
* VM(likelyhood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

...

## Extension Activation Stats
...
| vscodevim.vim                       | true  | 146       | 1             | 10              | *                                 | vscodevim.vim                       |
...
```

Let me know if there's another part of that output you would need.

Thanks!

**Comment by michaelscruz** [comment]
It hasn't happened again since just after my original post. I can go ahead and close this, assuming it had to do with something on my end. If that proves not to be the case, I'll just check back in here; otherwise, thank you and sorry for the uneccessary issue.
