### ISSUE TITLE
Map <leader>y to automatically copy to `+` register?

### ISSUE THREAD

**Issue by codic12** [VSCodeVim/Vim#5145]
**Is your feature request related to a problem? Please describe.**
In regular Vim, you can do something like `noremap <Leader>Y "+y` to have `<leader>y` automatically copy to the + register. Is there a way to do this in VSCodeVim? There probably is a configuration option that I haven't found; if not, I believe that something like this should be implemented.

**Comment by codic12** [comment]
Thanks! I tried adapting this to my purpose, and in visual mode:
```
    "vim.visualModeKeyBindings": [{
      "before": ["<leader>", "+", "y"],
      "after": ["\\", "y"],
    }]
```

however, `\y` still doesn't copy.

**Comment by J-Fields** [comment]
"before" is what you type, and "after" is the result

**Comment by codic12** [comment]
This doesn't seem to work either:
```
    "vim.visualModeKeyBindings": [{
      "before": ["<leader>", "+", "y"],
      "after": ["<leader>", "y"],
    }]
```

**Comment by J-Fields** [comment]
shouldn't `<leader>` in "after" be `\"`?

**Comment by codic12** [comment]
ahh wait, yeah, i see what I did wrong. thanks!
