### ISSUE TITLE
ci( /cib ci{ ciB not working

### ISSUE THREAD

**Issue by fredyonge** [VSCodeVim/Vim#5147]
**Describe the bug**
ci( /cib ci{ ciB are not working, weirldy ci" does

Note: If i am already in () i can change text, but it doenst work if I am at the start of the line and want to change a parenthesis content, that is at the end of the line

- Extension (VsCodeVim) version:
- VSCode version:
- OS: Mac

**Additional context**

**Comment by gxxxh** [comment]
> 

hi, I came across the same problem, how did you solve this?

**Comment by dglav** [comment]
> > 
> 
> hi, I came across the same problem, how did you solve this?

Same here.

**Comment by dglav** [comment]
In addition `ci"` doesn't work unless the cursor is **before** the quoted text on the specified line.

**Comment by nailerHeum** [comment]
> > hi, I came across the same problem, how did you solve this?
> 
> Same here.

Same here!

**Comment by ayoola-moore** [comment]
Hi. Did anyone find a solution to the above problem yet?

**Comment by bjarneschroeder** [comment]
Sameee

**Comment by mmatasic** [comment]
This should be reopened, it's still not working.

**Comment by kyhou** [comment]
Still not working...

**Comment by niklas-r** [comment]
There must have been a regression here because this isn't working as expected.

**Comment by mrtanguero** [comment]
For me, `ci(` and `cib` don't work, but `ci{` and `ciB` do, as well as `ci[`.

**Comment by perfect-secret-lover** [comment]
Same here. 😔

**Comment by noxxxxxious** [comment]
Happening for me as well.

**Comment by ll550** [comment]
It seems not working for ci(

**Comment by Pavel-Horol** [comment]
still not working ci(       : - (

**Comment by juasbhu28** [comment]
Hey guys!, 2024 and still not working :(

**Comment by Pavel-Horol** [comment]
same(

**Comment by Nixxen** [comment]
For anyone finding this through google:
There is an open issue related to this in #7346 
Use that ticket to report on the issue.
