### ISSUE TITLE
Weird mouse behavior on visual studio code

### ISSUE THREAD

**Issue by shahab570** [VSCodeVim/Vim#5151]
I am unable to use CTRL+V for paste and other keyboard shortcut such as copy,cut. Whenever i use these shortcuts nothing happens .sometimes it changes text randomly such as everytime I type Ctrl+X for cut, it reduces variable value in the selection. Also text selection was impossible. I dont know how to solve this. I disabled all extension and enabled them one by one. At last I found out that problem was on VIM extension

**Comment by zyrif** [comment]
Vim extension is designed to emulate the behavior of the Vim editor, including the cut, copy and paste actions. In Vim editor, Ctrl+v is used for block selection, y for copy and p for paste. If you want to switch to normal behavior, you can set vim mode to disabled from the command palette. 

Refer to this for more info: https://vim.fandom.com/wiki/Copy,_cut_and_paste

**Comment by J-Fields** [comment]
You can use `vim.handleKeys` to tell VSCodeVim to ignore certain keys. For instance, this will restore VSCode's copy/paste functionality:

```json
  "vim.handleKeys": {
    "<C-c>": false,
    "<C-v>": false
  },
```
