### ISSUE TITLE
Keyboard remapping <C-;> doesn't work

### ISSUE THREAD

**Issue by stu0292** [VSCodeVim/Vim#5152]
**Describe the bug**

In vim I remap `Ctrl ;` to Esc. ie:

```
   "vim.insertModeKeyBindings": [
        {
            "before": ["<C-;>"],
            "after": ["<Esc>"]
        }
    ], 
```

However this doesn't escape insert mode. 

In Keyboard Shortcuts (File > Preferences > Keyboard Shortcuts )  record mode (`Alt+K`) pressing `Ctrl ;` displays `ctrl+oem_1`

Maybe VSCode isn't interpreting <C-;> because ; is mapped to oem_1 (whatever that means??)?

**To Reproduce**

Vim settings, add the following keybinding:

```
   "vim.insertModeKeyBindings": [
        {
            "before": ["<C-;>"],
            "after": ["<Esc>"]
        }
    ], 
```

In a new text file, go into insert mode, press `Ctrl ;`  (nothing happens)

If you change the binding to something else, eg:

```
   "vim.insertModeKeyBindings": [
        {
            "before": ["<C-j>"],
            "after": ["<Esc>"]
        }
    ], 
```

Going into insert mode, `Ctrl j` will escape back to normal mode

**Expected behavior**
The following keybinding config should exit insert mode when pressing `Ctrl ;`
```
   "vim.insertModeKeyBindings": [
        {
            "before": ["<C-;>"],
            "after": ["<Esc>"]
        }
    ], 
```

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

`<C-;>` isn't detected at all in developer console, whereas `<C-j>` is:

```
[Extension Host] ModeHandler: debug: handleKeyEvent('i') took 8ms
console.ts:137 [Extension Host] ModeHandler: debug: handling key=<C-j>.
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.16.0

Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z (1 wk ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by sql-koala** [comment]
For this special case, you can help yourself like so (keybindings.json):
```
{
    "key": "ctrl+oem_comma",
    "command": "extension.vim_escape",
    "when": "editorTextFocus && vim.active && !inDebugRepl"
},
```

**Comment by stu0292** [comment]
Thanks @sql-koala, happy with that! For my case I changed the keybindings.json entry from `ctrl+oem_comma` to `ctrl+oem_1` to use `<C-;>`:
```
    {
        "key": "ctrl+oem_1",
        "command": "extension.vim_escape",
        "when": "editorTextFocus && vim.active && !inDebugRepl"
    },
```
