### ISSUE TITLE
> and < identing not respecting tab size

### ISSUE THREAD

**Issue by davidmoseler** [VSCodeVim/Vim#5153]
The tab size in my setup is 2 characters, but > moves lines by 4. I didn't find any option in the config or docs to change by how many characters those commands should move the lines.

**Comment by J-Fields** [comment]
In the bottom right corner of the window you should see something like `Spaces: 4`, which you can click to configure on a per-file basis. Global settings `editor.detectIndentation`, `editor.insertSpaces`, and `editor.tabSize` control the defaults.

**Comment by davidmoseler** [comment]
I had changed the spaces configuration in global settings, but I guess I had to reload visual code. After reloading, vim > and < shortcuts are working as expected. Thanks!
