### ISSUE TITLE
Delete lines without copying to buffer

### ISSUE THREAD

**Issue by kbirger** [VSCodeVim/Vim#5162]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to copy something, delete something, then paste what I copied. I don't see a way to delete some lines (eg: 3dd) without copying them to the buffer. 

**Describe the solution you'd like**
Either a separate binding that I can apply that will do what "dd" does but without updating a buffer, or a separate command.

**Describe alternatives you've considered**
Instead, I can delete, copy, paste, but sometimes that seems less natural

**Comment by sql-koala** [comment]
Hi, what you are looking for is the blackhole register. This is implemented in vsc vim. You do `"_3dd` (meaning: into blackhole register, delete 3 lines) and then your copied text is still there to paste.

**Comment by kbirger** [comment]
thank you!

**Comment by chiedo** [comment]
Hey there!

By any chance would you know why this wasn't working? I'm hoping to make `dd` automatically go to the blackhole buffer.

```
"vim.normalModeKeyBindingsNonRecursive": [
  {
      "before": ["d", "d"],
      "after": ["_", "d", "d"]
  }
],
```

**Comment by shlomocarmeter** [comment]
@chiedo I think you need the qoute sign (") before underscore sign (_). Also one d is enough for the mapping. Try this:
```
"vim.normalModeKeyBindingsNonRecursive": [
  {
      "before": ["d"],
      "after": ["\"","_", "d"]
  }
],
```

**Comment by chiedo** [comment]
That worked! Thank you!!!

**Comment by shlomocarmeter** [comment]
@chiedo You're welcome!
