### ISSUE TITLE
Ctrl-C in "/" doesn't reset the keyword to search

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#518]
### What did you do?

Strokes: `/abc<Ctrl-C>`

<img width="170" alt="screen shot 2016-07-25 at 6 10 12 pm" src="https://cloud.githubusercontent.com/assets/4033249/17122760/11e020d4-5293-11e6-9a93-be02764816c5.png">

### What did you expect to happen?
Going back to Normal Mode

### What happened instead?
Staying in `/` search mode, and any more input will be intercepted as appending to the keyword to search for.

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.3
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
Fixed! Thanks for the report, @octref!
