### ISSUE TITLE
You're awesome!

### ISSUE THREAD

**Issue by rendall** [VSCodeVim/Vim#5187]
**Describe the bug**

Not a bug, but there wasn't an option for "compliment". Feel free to close this!

I use this extension every day, and just want to extend my explicit appreciation to you and your team. I know that I don't speak alone when I say that I am really, truly grateful for your work on this.

**To Reproduce**

Install VSCode Vim extension

**Expected behavior**

It behaves exactly as needed and makes my everyday coding life that much easier.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by vtvh** [comment]
Thanks all the contributors. 🙏

Vim + Code truly the best of both worlds experience. 🤘🤘🤘

**Comment by J-Fields** [comment]
Thank you! I really appreciate everyone who contributes and provides feedback to the project (as well as those who just use it)!

**Comment by J-Fields** [comment]
Thanks again for this; open source work is rewarding in many ways, but direct expressions of gratitude aren't very often one of them 🤗
