### ISSUE TITLE
Redundant operation with <cgn> and <.>

### ISSUE THREAD

**Issue by HyHuang1995** [VSCodeVim/Vim#5194]
**Describe the bug**
Using the combination of `cgn` and `.`, a redundant operation will happen when all the occurrences are replaced.

**To Reproduce**

1.  Search some string by `/`
2.  Replace it with a target string with `cgn`
3.  Repeat the operation by `.`, the bug occurs when all the source strings have been replaced.

**Expected behavior**
No redundant `cgn` operation with `.`

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.16.0
- VSCode version: 1.48.2 x64
- OS: Ubuntu 18.04

**Additional context**

**Comment by J-Fields** [comment]
Repro:
```
|four
one
two
one
three
```
1. `/one\n`
2. `cgnblah<Esc>`
3. `.`
```
four
blah
two
bla|h
three
```
4. `.` (expect no change)
```
four
blah
two
bla|blahh
three
```

**Comment by sql-koala** [comment]
About that, this is from recent master:
```
@RegisterAction
class CommandSelectNextLastSearchWord extends BaseCommand {
  modes = [Mode.Normal, Mode.Visual, Mode.VisualBlock];
  keys = ['g', 'n'];
```
gn is not a motion (respectivly I do not find a motion gn), how comes it works with an operator?

**Comment by J-Fields** [comment]
> gn is not a motion (respectivly I do not find a motion gn), how comes it works with an operator?

I think because `gn` puts us into Visual mode (see `RecordedState.operatorReadyToExecute`). This feels janky to me - `gn` should be a motion, I think
