### ISSUE TITLE
Bug: When I yank a line, I yank from cursor to the end of file

### ISSUE THREAD

**Issue by ysl970629** [VSCodeVim/Vim#5197]
Windows 10
I bind the “L”(shift + L) to “$”, and when I press “yL”, It didn’t copy from cursor to the current line ending, instead of from cursor to the end of file. and I had already bind my “H” to “^”, so I tried to press “yH”, and I get the similar result : It copied from cursor to the start of file, but I just want to copy from cursor to the line start.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by J-Fields** [comment]
This is fixed in master, will be in the next release
