### ISSUE TITLE
Make an interactive/incremental version of easy motion

### ISSUE THREAD

**Issue by danielo515** [VSCodeVim/Vim#5201]
**Is your feature request related to a problem? Please describe.**
Easy motion is awesome, but sometimes one character is not enough, using always both is too cumbersome, and even sometimes two is not enough.

**Describe the solution you'd like**
In vim, easymotion has an incremental version that lets you type as many characters as you want to narrow down the list of options, then you just hit enter an navigate to the one that you want using the usual easymotion markers.

**Describe alternatives you've considered**
There is the normal version of easy motion, but it is not as powerful

**Additional context**
Hope this screencast clarifies things:

![easymotion](https://user-images.githubusercontent.com/2270425/93664477-9bc64e80-fa6f-11ea-850b-07b08b949588.gif)

**Comment by berknam** [comment]
This is already implemented! Just type `<Leader>` `<Leader>` `/`

It is mentioned [here](https://github.com/VSCodeVim/Vim#vim-easymotion), it is called "Search n-character"

**Comment by J-Fields** [comment]
Huh, wasn't aware that this was a thing. Neat!

**Comment by Morten242** [comment]
Looks great, didn't know. Saw this in the release notes for the most recent release and wanted to map it '/' but it doesn't seem to match anything outside what's on screen. Also could I map something like what easymotion suggests for 'n'/next? As in
```vim
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)

**Comment by berknam** [comment]
> 
> 
> Looks great, didn't know. Saw this in the release notes for the most recent release and wanted to map it '/' but it doesn't seem to match anything outside what's on screen.

What do you mean by this? From what I've tested if what you're searching for is off screen it will jump to it.

> Also could I map something like what easymotion suggests for 'n'/next? As in
> 
> ```viml
> map  n <Plug>(easymotion-next)
> map  N <Plug>(easymotion-prev)
> ```

This is currently not implemented.

**Comment by Morten242** [comment]
> What do you mean by this? From what I've tested if what you're searching for is off screen it will jump to it.

Very interesting. I tried in one file and it worked, and in another it didn't. It seems to depend just how for off-screen it is. If I gradually move the cursor/view closer to the location of the text I want to jump to then it eventually works when it's close enough.

**Comment by berknam** [comment]
> 
> 
> > What do you mean by this? From what I've tested if what you're searching for is off screen it will jump to it.
> 
> Very interesting. I tried in one file and it worked, and in another it didn't. It seems to depend just how for off-screen it is. If I gradually move the cursor/view closer to the location of the text I want to jump to then it eventually works when it's close enough even if it's still off-screen.

Didn't know that either. But I've just checked and there is indeed a hardcoded check that only allows searching up to 100 lines in each direction.

I don't know why is that, maybe it is for performance reasons. I'm pretty sure this limit doesn't exist on the actual Vim plugin.

Maybe this could be behind a setting that the user could change... Feel free to create a feature request or create a Pull Request if you think that is really needed.

**Comment by danielo515** [comment]
This is awesome, I was not aware of it. Thank you very much.
I think it deserves more attention on the readme than just a single row on a table.
Regards
