### ISSUE TITLE
Print a range of numbers using put

### ISSUE THREAD

**Issue by arnabanimesh** [VSCodeVim/Vim#5205]
**Is your feature request related to a problem? Please describe.**
The command `:put =range(11,15)` is not implemented.

**Expectations**
It currently throws an error. It should output a range from 11 to 15 with each number in a new line.

**Describe alternatives you've considered**
I use a macro using <kbd>p</kbd> and <kbd>Ctrl</kbd> + <kbd>a</kbd>. But it is cumbersome. I have also enabled neovim integration.

**Comment by J-Fields** [comment]
We don't yet support enough vimscript for this to work without neovim integration. When I enable neovim integration it seems to work fine. What error are you seeing?

**Comment by arnabanimesh** [comment]
I am receiving this error:
![Screenshot 2020-09-21 220340](https://user-images.githubusercontent.com/6032584/93795003-76e00000-fc56-11ea-8631-fce404ceda25.jpg)

**Comment by J-Fields** [comment]
Ah, on the latest stable version `:put` doesn't use neovim. This is fixed on master, so it'll be in the next release
