### ISSUE TITLE
Crash when you switch branches (if the difference is large enough)

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#521]
This is because we do a diff in HistoryTracker and jsdiff has a run time of something like O(n^2). 

Should be as simple as adding a 1 second timeout to the differ and, if we hit the timeout, (somehow) stopping the diff and just saying we deleted and recreated the entire document.

**Comment by infogulch** [comment]
I might even go as far as to say that the history should be reset when you switch branches. A couple times I've accidentally hit `u` after switching branches and it tried reverting the whole document.

The only problem is that differentiating between switching branches and the file being edited by another process is difficult to impossible. Maybe this difference is not big enough to worry about.

**Comment by johnfn** [comment]
@infogulch Good point. I am fine with totally resetting history in a case like this.

**Comment by rebornix** [comment]
I suppose it’s not just branch switching, when you do reverting in Git, it will fail sometimes, right?

**Comment by johnfn** [comment]
Yes. Branch switching is the easiest way to trigger this change that I've found, however anything that causes the history tracker to do a massive diff will trigger it. Pasting tons of text, changing the file in another editor, git revert, etc.

**Comment by rebornix** [comment]
Looking forward to see this get fixed as I'm working on several branches with `massive` diff (hundreds of lines) and run into this issue constantly :)

**Comment by johnfn** [comment]
Ahh, yeah, that doesn't sound enjoyable. 

Fortunately, this is not a hard fix at all. I should be able to get it done in the next few days.

**Comment by johnfn** [comment]
Closing in favor of #558. 

Also, famous last words. This fix is not simple at all. :P
