### ISSUE TITLE
Mouse clicked position isn't registered after navigating only with `hjkl`

### ISSUE THREAD

**Issue by wesleyegberto** [VSCodeVim/Vim#5212]
**Describe the bug**
The cursos position isn't update when clicking with the mouse after sometime navigating using `hjkl`.

After some navigation with `hjkl` it stop to update the cursor position when clicking with the mouse.
If I click anywhere to navigate with motions (`w`, `b`, `e`)  or edit from there it will use the last position I navigated using keyboard, it only keep the clicked position if I use `hjkl` again.

If I open a file and just keep clicking to navigate or edit, or even navigate using motions it's ok, the mouse update the cursor position.

**To Reproduce**

1.  Go to any file
2.  Navigate using `h`, `j`, `k` and `l`
3.  Click anywhere else in the file and try any action like `a`, `i`, `w`, `b`
4.  You should see the action starting from last position you navigated wtih `hjkl`

**Expected behavior**
Expected to start the action from the clicked position.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `v1.17.0`
- VSCode version:  `Version: 1.49.1` and `1.50.0-insider`
- OS: macOS Catalina 10.15.6

**Additional context**

I could reproduce this issue in stable and insider version. It started just after I updated the Vim plugin.
On Insider I don't have any other extension installed beside theme and markdown docs, but I also tried with them disabled.

If there is any info or debug I can do please let me know.

**Comment by mxovd** [comment]
Seconded, downgrading to 1.16 fixed the issue.

**Comment by ghennequin** [comment]
I have the same issue. Moreover, when entering visual selection mode, I cannot go down the lines with `j` when the current line is  long enough to wrap. Works for short lines though.

**Comment by kalingibbons** [comment]
Same here. Downgraded to 1.16 for now.

**Comment by MrSurly** [comment]
Also having this problem -- also downgraded.

**Comment by DM-Berger** [comment]
Have also had this issue (which I would note also makes the extension essentially unusable), and been forced to downgrade.
