### ISSUE TITLE
"No .vimrc found. Please set `vim.vimrc.path.`" reported with v1.17.0 

### ISSUE THREAD

**Issue by jethas-bennettjones** [VSCodeVim/Vim#5220]
**Describe the bug**
When VS Code starts up, the error message "No .vimrc found. Please set `vim.vimrc.path.`" is shown. Nothing I can do seems to make it find this file.

**To Reproduce**
Steps to reproduce the behaviour:

1. Launch VS Code
2. Update to v1.17.0
3. Wait for VS Code to reload
4. Notice that a notification appears with the message "No .vimrc found. Please set `vim.vimrc.path.`"

**Expected behaviour**
No error should be seen when launching with v1.17.0 of the extension.

**Screenshots**
![image](https://user-images.githubusercontent.com/62298251/94015058-99167280-fd69-11ea-894d-f778414ffd96.png)

**Environment (please complete the following information):**

CPUs | Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz (8 x 3193)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 15.89GB (7.24GB free)
Process Argv |  
Screen Reader | no
VM | 0%

- Extension (VsCodeVim) version:
- VSCode version: 1.49.0
- OS: Windows 10 (16299.2045)

**Additional context**
I don't know if 1.49.1 resolved the issue, but I'm going to try that now.

**Comment by cimteqbackup** [comment]
Same here. Looks like it add an '.' in the end of the file name somehow?

**Comment by JW9506** [comment]
I caught it doing this last night, then I immediately switched back to 1.16 and turned off VSCode's automatic extension update.

**Comment by Sheepolution** [comment]
> Same here. Looks like it add an '.' in the end of the file name somehow?

I think that's just the dot for ending the sentence.

**Comment by jethas-bennettjones** [comment]
That's what I thought but I'm not so sure. It's within the quote marks.
It's possible that something else could be behind this, of course.

**Comment by sangonzal** [comment]
Also seeing this after updating to v1.17.0.

**Comment by DavidBChristensen** [comment]
Also seeing this issue after updating to 1.17.0. also tried a copy of .vimrc.

**Comment by DavidBChristensen** [comment]
I think it was most likely in c900a7eaa8f276c2062c61f7ceb071b694ce8a08 of vimrc.ts
change of using ../util/fs to platform/fs

**Comment by Akashno** [comment]
- Go to settings.json in vscode change vimrc option to false : 
`"vim.vimrc.enable": false`
