### ISSUE TITLE
[1.17.0] Movements keys rebind aren't working like before

### ISSUE THREAD

**Issue by l0wigh** [VSCodeVim/Vim#5222]
**Describe the bug**
Since the update 1.17, my all rebinded movements keys do only left move. My other rebind like "jk" to do "Esc" are working fine.

**To Reproduce**

1.  Change settings in the json file.
2.  Rebind k to do j move. 
3.  Not working properly (do left move)

**Screenshots**
Here is my keybinds. I tried to debug in the console, but nothing appears... Sorry
https://i.ibb.co/k43kkmK/error-vim-vscode.png

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17
- VSCode version: 1.49.1
- OS: Windows 10

**Comment by J-Fields** [comment]
Try putting these in `vim.normalModeKeyBindingsNonRecursive`

**Comment by l0wigh** [comment]
Working now, thanks !

Le mer. 23 sept. 2020 à 20:01, Jason Fields <notifications@github.com> a
écrit :
