### ISSUE TITLE
When I type `jj` to `esc`, will save a `j` character

### ISSUE THREAD

**Issue by DoranYun** [VSCodeVim/Vim#523]
When I type `jj` to `esc`, will save a `j` character.

![v](https://cloud.githubusercontent.com/assets/16359169/17134082/4ddc538c-535b-11e6-96e7-179634e5c325.gif)

settings.json

```
  "vim.insertModeKeyBindings": [
       {
           "before": ["j", "j"],
           "after": ["<esc>"]
       }
    ]
```

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.3
* OS:  Mac

**Comment by johnfn** [comment]
Weird, looks like a regression to me. Sorry about that! Will get to it soon.

**Comment by johnfn** [comment]
Weird. I saw this a few times, but now I can't reproduce it!

**Comment by DoranYun** [comment]
I tried to reinstall, but the problem is still unsolved.

**Comment by johnfn** [comment]
@DoranYun Yeah, it's definitely a bug. It's a tricky one though; it only happens occasionally for me and I can't figure out anything that directly triggers it. 

If you can find a way to reproduce it 100% of the time, that would be really helpful.

**Comment by DoranYun** [comment]
@johnfn When I open a file to start Insert mode(do not enter any text), then type `jj` go back to Normal mode, It will be triggers. But if I enter some text in Insert mode, then type `jj` go back to Normal mode, it's alright.
It always happends in my mac.

![vv](https://cloud.githubusercontent.com/assets/16359169/17166080/55131706-5407-11e6-888e-311cbab835bd.gif)

**Comment by Jiig** [comment]
Seeing the same thing as @DoranYun, if I press jj right after entering insert mode the 'j' character is left behind, if I do anything in insert mode before pressing jj then it esc's as expected with no 'j' left behind.

Running on Linux, Cent OS 7

**Comment by johnfn** [comment]
Fixed! Thanks to both of you, @Jiig and @DoranYun, for providing clear reproduction steps. That was a big help. :)
