### ISSUE TITLE
Stuck after `"+y`

### ISSUE THREAD

**Issue by findNextStep** [VSCodeVim/Vim#5234]
**Describe the bug**
after use "+y vscode stuck

**To Reproduce**
set 
```json
    {
      "after": [
        "\"",
        "+",
        "y"
      ],
      "before": [
        "y"
      ]
    },
```
in vim.normalModeKeyBindings
and select range and parse `y` vscode stuck and one `code helper` process run in 100%cpu
![image](https://user-images.githubusercontent.com/26270464/94123406-53030100-fe86-11ea-8f90-b89d0a2382f5.png)

- Extension (VsCodeVim) version: 1.16.0
vscode abort
版本: 1.49.1
提交: 58bb7b2331731bf72587010e943852e13e6fd3cf
日期: 2020-09-16T23:21:17.533Z (1 周前)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by findNextStep** [comment]
chekcout to 1.16.0 work for this issure

**Comment by sql-koala** [comment]
Hi, use this:
`    "vim.normalModeKeyBindingsNonRecursive": `

**Comment by findNextStep** [comment]
> Hi, use this:
> ` "vim.normalModeKeyBindingsNonRecursive":`
> 
> I would recommend it as good practice to define mappings non recursive as default and use other maps only when explicitly needed.

that is a good idea, but stil not work

**Comment by findNextStep** [comment]
i found it`s `vim.visualModeKeyBindings`
switch to `vim.visualModeKeyBindingsNonRecursive` work thanks
