### ISSUE TITLE
Best way to implement "vim-cutlass" behavior?

### ISSUE THREAD

**Issue by macintacos** [VSCodeVim/Vim#5242]
**Is your feature request related to a problem? Please describe.**

It's always bothered me that operations like `d`/`D`/`c`/`C` yank things to a register instead of going to the "black hole" register. While messing around with my proper vim configuration, I stumbled upon the following plugin that essentially takes care of that concern: [vim-cutlass](https://github.com/svermeulen/vim-cutlass).

With this plugin, I can explicitly map `m` (and its variations) to "move" (or "cut") text, and then all of the other delete operations actually _delete_ and not put anything into your register/clipboard.

I'm trying to figure out the best way to accomplish this in VSCodeVim. If I come up with a solution, I'll post it here for others that may want this as well, but I wanted to post this here in case there was some secret "setting" or an approach that would be the most obvious to take,

**Describe the solution you'd like**

All "delete" operations (`c`, `cc`, `C`, `s`, `S`, `d`, `dd`, `D`, `x`, `X`) do exactly what they do now, but they do _not_ put the text deleted into your default register, but rather the black hole register.

Then, I'd like to map `d`/`dd/`D` functionality to `m` equivalents (`m`/`mm`/`M`) to explicitly "move" text (in normal for visual mode)

**Describe alternatives you've considered**

I haven't tried anything yet, but will provide my "solution" if I come up with one!

**Additional context**

Some vim plugins that do something like this:

- [vim-cutlass](https://github.com/svermeulen/vim-cutlass)
- [vim-easyclip](https://github.com/svermeulen/vim-easyclip)
- http://vimcasts.org/blog/2013/11/registers-the-good-the-bad-and-the-ugly-parts/

**Comment by macintacos** [comment]
Welp, that was actually a lot easier than I expected. Went with the straightforward remapping approach and got this:

```
  "vim.normalModeKeyBindingsNonRecursive": [
    // vim-cutless implementation?
    {
      "before": ["D"],
      "after": ["\"", "_", "D"]
    },
    {
      "before": ["d"],
      "after": ["\"", "_", "d"]
    },
    {
      "before": ["d", "d"],
      "after": ["\"", "_", "d", "d"]
    },
    {
      "before": ["c"],
      "after": ["\"", "_", "c"]
    },
    {
      "before": ["C"],
      "after": ["\"", "_", "C"]
    },
    {
      "before": ["c", "c"],
      "after": ["\"", "_", "c", "c"]
    },
    {
      "before": ["x"],
      "after": ["\"", "_", "x"]
    },
    {
      "before": ["X"],
      "after": ["\"", "_", "X"]
    },
    // "move"/"cut" remap
    {
      "before": ["m"],
      "after": ["d"]
    },
    {
      "before": ["m", "m"],
      "after": ["d", "d"]
    }
  ]
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": ["d"],
      "after": ["\"", "_", "d"]
    },
    {
      "before": ["c"],
      "after": ["\"", "_", "c"]
    },
    {
      "before": ["x"],
      "after": ["\"", "_", "x"]
    },
    {
      "before": ["m"],
      "after": ["d"]
    }
  ]

```

Hope that helps someone out there! I'll close this out.

**Comment by gianpietrodimatteo** [comment]
`    "vim.normalModeKeyBindingsNonRecursive": [
        // vim-cutless implementation?
        {
          "before": ["D"],
          "after": ["\"", "_", "D"]
        },
        {
          "before": ["d"],
          "after": ["\"", "_", "d"]
        },
        {
          "before": ["d", "d"],
          "after": ["\"", "_", "d", "d"]
        },
        {
          "before": ["c"],
          "after": ["\"", "_", "c"]
        },
        {
          "before": ["C"],
          "after": ["\"", "_", "C"]
        },
        {
          "before": ["c", "c"],
          "after": ["\"", "_", "c", "c"]
        },
        {
          "before": ["x"],
          "after": ["\"", "_", "x"]
        },
        {
          "before": ["X"],
          "after": ["\"", "_", "X"]
        },
        // "move"/"cut" remap
        {
          "before": ["m"],
          "after": ["d"]
        },
        {
          "before": ["m", "m"],
          "after": ["d", "d"]
        },
        {
          "before": ["M"],
          "after": ["D"]
        }
      ],
      "vim.visualModeKeyBindingsNonRecursive": [
        {
          "before": ["d"],
          "after": ["\"", "_", "d"]
        },
        {
          "before": ["c"],
          "after": ["\"", "_", "c"]
        },
        {
          "before": ["x"],
          "after": ["\"", "_", "x"]
        },
        {
          "before": ["m"],
          "after": ["d"]
        }
      ],`

**Comment by gianpietrodimatteo** [comment]
Thank you for your solution! It works perfectly. I found the D to M mapping missing, so I added it to the settings, again, just in case it helps someone. 
Added:
```
        {
          "before": ["M"],
          "after": ["D"]
        }
```
Final result:

```
    "vim.normalModeKeyBindingsNonRecursive": [
        // vim-cutlass implementation
        {
          "before": ["D"],
          "after": ["\"", "_", "D"]
        },
        {
          "before": ["d"],
          "after": ["\"", "_", "d"]
        },
        {
          "before": ["d", "d"],
          "after": ["\"", "_", "d", "d"]
        },
        {
          "before": ["c"],
          "after": ["\"", "_", "c"]
        },
        {
          "before": ["C"],
          "after": ["\"", "_", "C"]
        },
        {
          "before": ["c", "c"],
          "after": ["\"", "_", "c", "c"]
        },
        {
          "before": ["x"],
          "after": ["\"", "_", "x"]
        },
        {
          "before": ["X"],
          "after": ["\"", "_", "X"]
        },
        // "move"/"cut" remap
        {
          "before": ["m"],
          "after": ["d"]
        },
        {
          "before": ["m", "m"],
          "after": ["d", "d"]
        },
        {
          "before": ["M"],
          "after": ["D"]
        }
      ],
      "vim.visualModeKeyBindingsNonRecursive": [
        {
          "before": ["d"],
          "after": ["\"", "_", "d"]
        },
        {
          "before": ["c"],
          "after": ["\"", "_", "c"]
        },
        {
          "before": ["x"],
          "after": ["\"", "_", "x"]
        },
        {
          "before": ["m"],
          "after": ["d"]
        }
      ],
```

**Comment by fcFn** [comment]
Thank you very much. I also added the following to visual mode so that when you paste over a selected word (such as when double clicking) it won't kill the last yank:
```
{
      "before": ["p"],
      "after": ["\"", "_", "d", "P"]
 }
```
