### ISSUE TITLE
1.17.0 Searching backwards (n) or forwards (N) results in "E492: Not an editor command: call HLNext(0.1)"

### ISSUE THREAD

**Issue by philgoldenb** [VSCodeVim/Vim#5249]
**Describe the bug**
In normal mode, pressing n or N results in "_E492: Not an editor command: call HLNext(0.1)_" in status bar.  The search does actually work, and the cursor goes to the next or previous instance of the search item. But the status bar displays the error instead of the usual "match x of N" message.

Workaround: downgrade VSCodeVim extension to 1.16.0

**To Reproduce**

1.  In Normal mode, search for a string
2.  press n or N
3. (optional) repeat step 2

**Expected behavior**
status bar displays "match x of N" 

**Screenshots**

![image](https://user-images.githubusercontent.com/28322534/94320077-0db00380-ff5a-11ea-965d-23e858cdf0cf.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: In 1.17.0
- VSCode version:  1.49.2
- OS:  MacOS Catalina 10.15.6

**Comment by J-Fields** [comment]
Are you using a .vimrc? If so, what's in it?

**Comment by philgoldenb** [comment]
My bad.  Yes, completely forgot I added these two lines to .vimrc a while back to make cursor easier to see when on highlight. 

nnoremap <silent> n n:call HLNext(0.1)<cr>
nnoremap <silent> N N:call HLNext(0.1)<cr>

They're really barely necessary though, so not a big deal at all for me to get rid of them.
