### ISSUE TITLE
Vim-Find dialog last cursor position is off

### ISSUE THREAD

**Issue by MacMaru** [VSCodeVim/Vim#5268]
## Issue Type: <b>Bug</b>

1.  put the cursor at start of document (gg)
2.  activate VSCode Find dialog (Cmd+F)
3.  search for something; hit ENTER (one or more times) to step cursor through search results: make sure cursor is no longer on the first line
4.  hit ESC to exit Find dialog: cursor is correctly on last found position
5.  any consecutive VIM command (e.g. ESC) will jump to/be applied to line 1 (or whatever line the cursor was at before stepping through Find search results)

## Expected behavior
- Vim should update cursor position
- Bug was likely introduced in v1.17.0, not reproducible in v1.16.
- Seems to have something to do with the Find dialog, since searching with vim ('/') works as expected

## environment
Extension version: 1.17.1
VS Code version: Code 1.49.2 (e5e9e69aed6e1984f7499b7af85b3d05f9a6883a, 2020-09-24T16:23:52.277Z)
OS version: Darwin x64 19.6.0

**Comment by berknam** [comment]
Can you test the PR #5250 to see if it fixes this for you?

**Comment by MacMaru** [comment]
LGTM: no longer noticing any unexpected jumps when running with this PR built and working across multiple files!
