### ISSUE TITLE
Support ^e and ^y

### ISSUE THREAD

**Issue by jordanlewis** [VSCodeVim/Vim#527]
Vim has some nice scrolling features where the cursor stays in the same spot but the screen moves up and down: ^E and ^Y. From `scroll.txt`:

```
                                                        CTRL-E
CTRL-E                  Scroll window [count] lines downwards in the buffer.
                        Mnemonic: Extra lines.

							CTRL-Y
CTRL-Y			Scroll window [count] lines upwards in the buffer.

```

**Comment by rebornix** [comment]
@jordanlewis we have a similar requirements and it's dependent on Code API support. We have opened an issue #9609 then let's see if we can make this together with that API next sprint (Code August Iteration.)

**Comment by rebornix** [comment]
@jordanlewis see https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#scrolling we've already added `Scroll` features on our roadmap. Stay tuned and we will have in August.

**Comment by jordanlewis** [comment]
Great!

For now, I went ahead and remapped these outside of the plugin as follows, which works nicely:

```
{
    "key": "ctrl+e",
    "command": "scrollLineDown",
    "when": "editorTextFocus"
},{
    "key": "ctrl+y",
    "command": "scrollLineUp",
    "when": "editorTextFocus"
}
```

**Comment by rebornix** [comment]
@jordanlewis oh your workaround is neat! didn't notice Code already supports line scrolling, then it will be easy to add these command natively in VSCodeVim. I'll add this real quick.

**Comment by johnfn** [comment]
Added on master and will be out in our next patch release. Thanks for the feature suggestion, @jordanlewis!

**Comment by Obaied** [comment]
^d was also not working (It was assigned to 'delete right' ). I've added the following to @jordanlewis's answer: 
```
    {
        "key": "ctrl+e",
        "command": "scrollLineDown",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+y",
        "command": "scrollLineUp",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+d",
        "command": "extension.vim_ctrl+d"
    },
    {
        "key": "ctrl+u",
        "command": "extension.vim_ctrl+u"
    }
```
