### ISSUE TITLE
Document all "when clauses" for the extension

### ISSUE THREAD

**Issue by macintacos** [VSCodeVim/Vim#5273]
It took a while to figure out that I had to use `vim.mode == 'VisualLine'` instead of `vim.mode == 'Visual Line'` or `vim.mode == 'Visual-Line'` etc. because I couldn't find them in the README. Can we have all of the various "modes" documented in the README? Thanks!

**Comment by stevenguh** [comment]
I agree, it does require some source code digging. I think here are all the modes.
https://github.com/VSCodeVim/Vim/blob/91ca71f8607458c0558f9aff61e230c6917d4b51/src/mode/mode.ts#L8-L20
