### ISSUE TITLE
Pressing return key in vim search (using /) will not go to next match but trigger VSCode action

### ISSUE THREAD

**Issue by nikitavoloboev** [VSCodeVim/Vim#5274]
In [vscode search editor](https://code.visualstudio.com/updates/v1_43#_search-editors):

<img width="482" alt="image" src="https://user-images.githubusercontent.com/6391776/94417557-82fd1d80-0180-11eb-8428-77f79c7a875d.png">

I made it so pressing return on the line in Search Editor will go to its declaration:

```
{
    "key": "enter",
    "command": "editor.action.goToDeclaration",
    "when": "inSearchEditor && editorTextFocus"
  },
```

But now every time I do a search with `/` in vim and press return to go to next match. It will instead trigger the declaration binding every time. Is it possible to somehow not do it?

Perhaps there is a way to do it with extending the when scope?

It might also be a bug as I thought Vim should take control on bindings in `/` searches?

**Comment by berknam** [comment]
Add `&& vim.mode == 'Normal'` to your when clause

**Comment by nikitavoloboev** [comment]
Beautiful. Thank you so much 😻
