### ISSUE TITLE
Mapping "vv" to "V" stopped working in 1.15.0 and hasn't worked since

### ISSUE THREAD

**Issue by boris-petrov** [VSCodeVim/Vim#5278]
**Describe the bug**
I have the following mapping:

```json
"vim.visualModeKeyBindingsNonRecursive": [
    {
        "before": ["v", "v"],
        "after": ["V"],
    },
```

And that worked until (including) 1.14.5 - pressing "v" and then quickly "v" again (in normal mode) caused the binding to execute and full-line selection mode to be entered. Ever since 1.15.0 (I tested all versions from 1.15.0 to 1.17.0 included) that doesn't work any more. I've been following a few issues that seemed relevant but they all got fixed and I hoped 1.17.0 to resolve the problem but it didn't. Has something changed or is this a bug?

**Expected behavior**

The mapping to work.

**Comment by JW9506** [comment]
If it were to work at all, shouldn't it be set using `vim.normalModeKeyBindingsNonRecursive`, I am surprised it worked at all back then with `vim.visualModeKeyBindingsNonRecursive`

**Comment by boris-petrov** [comment]
@JW9506 - I also initially thought that `normalModeKeyBindingsNonRecursive` should be used. I intended to try that today on 1.17 before opening this issue, however version 1.17 is gone from the extensions store for some reason and so I decided to open it anyway.

**Comment by berknam** [comment]
@boris-petrov I can't reproduce this in version 1.17.x. Your binding works fine for me on version 1.17.0 and 1.17.1. It does not however work on version 1.16 and below but the remapper overhaul on version 1.17 fixed that.

**Comment by boris-petrov** [comment]
@berknam - thanks. When I tried 1.17.0 it didn't work. But now I can't seem to be able to install that version - only 1.16.0 is available. Any ideas why?

**Comment by berknam** [comment]
Version 1.17 was supposed to be a beta version.

Try using the 'Install another version' from the gear symbol.

**Comment by boris-petrov** [comment]
@berknam - thanks for the help. The version is not available there but I downloaded the VSIX file from the marketplace and installed it manually. You are correct - it does work on 1.17.1 but I had to move the mapping to `normalModeKeyBindingsNonRecursive` as @JW9506 mentioned. Thanks to both of you!

**Comment by berknam** [comment]
> 
> 
> @berknam - thanks for the help. The version is not available there but I downloaded the VSIX file from the marketplace and installed it manually. You are correct - it does work on 1.17.1 but I had to move the mapping to `normalModeKeyBindingsNonRecursive` as @JW9506 mentioned. Thanks to both of you!

It works for me even in `visualModeKeyBindingsNonRecursive`. Maybe you have other remaps that might be conflicting?!

**Comment by berknam** [comment]
Well it works if you are already in visual mode. Then pressing two 'v's will change to visual line mode. If you want to go from normal mode to Visual line mode then you need to do it in normal mode.

**Comment by boris-petrov** [comment]
Yes, sorry, I should have mentioned that - I want to go from normal mode to visual line mode by pressing two "v"'s. So 1.17.1 works correctly. Thanks again!
