### ISSUE TITLE
Vim extension make "Filtering document tree" unusable 

### ISSUE THREAD

**Issue by meotimdihia** [VSCodeVim/Vim#5301]
**Describe the bug**
Vim extension make "[Filtering document tree](https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree)" unusable 

**Expected behavior**
Filtering document tree 

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: lastest
- OS: Windows 10

**Comment by JW9506** [comment]
What works for me is make sure you use `"workbench.list.keyboardNavigation": "filter"`, press `/` and start searching, to clear the input, use `<Esc>` .

**Comment by meotimdihia** [comment]
Thanks, press "/" work for me.
