### ISSUE TITLE
[count]`o` activates multi-cursor

### ISSUE THREAD

**Issue by nkgm** [VSCodeVim/Vim#5302]
![CleanShot 2020-09-30 at 11 06 28](https://user-images.githubusercontent.com/5631881/94659713-62160300-030d-11eb-8e11-818d88bb5cc4.gif)

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.17.1`
- OS Version: `Darwin x64 19.5.0`
- VSCode version: `1.49.2`

**Comment by JW9506** [comment]
It is more like an undocumented feature that I found pretty useful just now.

**Comment by nkgm** [comment]
I can see how it can be useful in certain cases, but still not standard vim behavior.

**Comment by berknam** [comment]
> 
> 
> I can see how it can be useful in certain cases, but still not standard vim behavior.

Actually that is Vim behavior. In Vim if you do `3oTest<Esc>` the final result is:
```

Test
Test
Test
```

The difference is that in Vim if first shows like you're editing on line and when you exit to normal mode it repeats that same line two more times. While here in VSCodeVim you see them being changed in real time.
