### ISSUE TITLE
Relative Line Numbers: an option to have 0 as the current line number.

### ISSUE THREAD

**Issue by mrillusi0n** [VSCodeVim/Vim#5304]
Vim gives me an option to have 0 as the current line number, instead of the absolute one, when relative numbering is on. I'd like same functionality.

**Comment by J-Fields** [comment]
We can't do this; it's up to VSCode

**Comment by mrillusi0n** [comment]
I created the same issue over [here](https://github.com/microsoft/vscode/issues/107869#issue-712527670).
