### ISSUE TITLE
Cannot read property 'after' of undefined

### ISSUE THREAD

**Issue by ns11** [VSCodeVim/Vim#5306]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.17.1

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'after' of undefined
	at Object.promise (/Users/***/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:236829)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Object.runTasks (/Users/***/.vscode/extensions/vscodevim.vim-1.17.1/out/extension.js:9:621914)
```

</details>

**Comment by J-Fields** [comment]
What were you trying to do when this happened?

**Comment by berknam** [comment]
@ns11 Where you trying to run the "Vim: Remap..." command from command palette?

**Comment by ckoparir** [comment]
Ok thanks, can be closed.

**Comment by berknam** [comment]
@J-Fields Are you considering this a duplicate of #5841? Are we sure that they are the same?

**Comment by J-Fields** [comment]
Yeah I was considering them duplicates. @ckoparir could you clarify - did you try to run the command `Vim: Remap any key combination that VS Code supports to Vim motions/operators/ExCommands/macro.`?

**Comment by ckoparir** [comment]
Sorry, I can't repeat the same issue or clarify it now, because I've been working completely different OS and IDE. Actually I can't just remember the details about the issue that I've faced before. Thank you for your time and interest.
