### ISSUE TITLE
CJK still problem in normal mode

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#532]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?

text as below, put cursor at the 2nd line (the empty line)
```
abcdefg

hijklmn
```

switch to Chinese IME and type `ksge ` to input `空格`, the actual result is:

```
空格abcdefg

hijklmn
```

### What did you expect to happen?

In my idea, it would be better if CJK IME could be automatically disabled in normal mode.

### Technical details:

* VSCode Version: v1.3.1
* VsCodeVim Version: v0.1.4
* OS: Windows 10 Professional (x64 version)
* IME: Microsoft Pinyin (both Full & Double Pinyin)

**Comment by rebornix** [comment]
@localvar The full featured CJK support relies on Code's newly added API `replacePreviousChar` and it only exists in Insider and 1.4.0 later. So you are supposed to run into this issue with Code 1.3.1.

I'd like to keep this open and test it again when Code 1.4.0 Stable releases. It should work as expected. @localvar sorry to bother you as we released new Ext before Code.

**Comment by localvar** [comment]
Thanks for the explanation @rebornix , I will wait v1.4.0 and verify this.

**Comment by johnfn** [comment]
@localvar you can actually install visual code insiders right now and check it out, if you want.

**Comment by localvar** [comment]
confirm this has been fixed.
