### ISSUE TITLE
an option to use system clipboard

### ISSUE THREAD

**Issue by jneiku** [VSCodeVim/Vim#537]
Thanks for all the tremendous work!

I'm wondering if it's possible to add an option similar to Sublime's Vintageous "[vintageous_use_sys_clipboard](https://github.com/guillermooo/Vintageous/blob/master/Preferences.sublime-settings#L27)" mode. 

Basically, the desire is to yank and paste from system clipboard and not a separate vim-only clipboard.

Thanks ahead!

**Comment by johnfn** [comment]
I like the idea.

@rebornix is this possible currently?

**Comment by johnfn** [comment]
(Currently you can use cmd-c and cmd-v to access the system clipboard within insert mode.)

**Comment by rebornix** [comment]
@johnfn clipboard is a system stuff and we don't want to wrap it again in Code, see https://github.com/Microsoft/vscode/issues/217 . 

But we can still leverage third party npm modules to handle the clipboard. I like it as well, using sys_clipboard to cache register is fun sometimes.

**Comment by rebornix** [comment]
@jneiku , @aminroosta already added support for system clipboard via #543. I'd like to close it for now as what @aminroosta added is a native Vim approach. Please give it a try and see how it's going then let's see if we need reopen this issue.
