### ISSUE TITLE
Y key doesn't yank current line

### ISSUE THREAD

**Issue by cshei** [VSCodeVim/Vim#538]
### What did you do?

Tried to duplicate the current line using "Yp"

Put the exact key strokes you pressed to reproduce the issue, if possible.

Yp

### What did you expect to happen?

Current line should be yanked.

### What happened instead?

Nothing.  Using "yy" instead of "Y" works, but I'm totally used to using "Y" at this point.

### Technical details:

* VSCode Version: 1.3.1 
* VsCodeVim Version: 0.1.4
* OS: Linux

**Comment by johnfn** [comment]
Added this one just for you 😉

**Comment by cshei** [comment]
Wow, that was quick… thanks!!

**Comment by johnfn** [comment]
@zebapy Hopefully because you haven't updated. Try updating. :)
