### ISSUE TITLE
Cursor stay on initial position after CTRL+arrows

### ISSUE THREAD

**Issue by ocoka** [VSCodeVim/Vim#5380]
**Describe the bug**
When you use `CTRL + arrows` in **"normal"** or **"insert"** mode (I have `vim.CtrlKeys` disabled for now, but it's independent, I've tested with *enabled* state too)

**To Reproduce**
And that is a problem, it's fluid, some files, for example just plain text, do not affected, but some like TypeScript or HTML in Angular project has this issue, but not from start, and 100% after several seconds of working with them.
Can't catch concrete action that can produce this issue, and just hope that maybe someone already see this issue previously... 

*Forgot to mention*: After toggle `VIM: Toggle VIM Mode` and back, **issue has gone, but** again, after several seconds it arise 

**Expected behavior**
To not have any issue on using CTRL+arrows navigation

**Screenshots**
![screencast](https://user-images.githubusercontent.com/8239290/95674560-b34dae80-0bb9-11eb-99f1-48e8024e69d7.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: : **1.17.1**
- VSCode version:
Version: **1.50.0**
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:01:33.073Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.7.0-997-generic

**Comment by JW9506** [comment]
I can confirm that if user invokes any VSCode native commands that affect the cursor position, VIM does not update the cursor location. It is as if VIM had no idea user is interacting straight with VSCode.

**Comment by ocoka** [comment]
Hi, @JW9506 , and thank you for your involvement and suggested workaround, at least now I understand why and when this happens )) But I should mention that previously, on old version of VScode and VIM plugin, I didn't catch such behaviour... or maybe I just didn't have such many plugins as today )))

**Comment by fnurl** [comment]
I am getting the same behaviour on macOS (for cmd-left/right arrows) for VSCodeVim v1.17.1. My workaround was to delete the cmd-arrowkey shortcuts and force myself to use vim movement commands instead 🤣

**Comment by ocoka** [comment]
Found a several related issues:
Just to link it here
#5248 
#5212 
#5221 
#5250

**Comment by berknam** [comment]
@ocoka if you reload the window or restart vscode that goes away right? Then it probably happens again after using some snippet.

This is related to #5250 and should be fixed with that PR.

**Comment by ocoka** [comment]
> @ocoka if you reload the window or restart vscode that goes away right? Then it probably happens again after using some snippet.
Yeah, that's right, event if you just toggle "disable", "enable" VIM the issue goes away, but after some user interaction it happens again

**Comment by ocoka** [comment]
Issue doesn't exist in version 1.16
