### ISSUE TITLE
Substitution in Visual Line mode

### ISSUE THREAD

**Issue by solodov-dev** [VSCodeVim/Vim#5386]
**What did you do?**
press V to visually select a block of code
press : to vim command line which is now in the range mode for the selected text '<,'>
write s/3/4/g

**What did you expect to happen?**
Replace all 3s to 4s in the selected area

What happened instead?
all 3s got replaced to 4s in the area **outside of the selected**

Technical details:
VSCode Version: 1.50.0
VsCodeVim Version: 1.17.1
OS: MacOS

**Comment by J-Fields** [comment]
I'm not able to reproduce. Are you using neovim integration?

**Comment by solodov-dev** [comment]
Yes. Turned it off. Now everything works as expected. Thanks

**Comment by J-Fields** [comment]
This is probably the same or similar to #3566
