### ISSUE TITLE
Autocomplete behaving badly

### ISSUE THREAD

**Issue by floyd-may** [VSCodeVim/Vim#5390]
**Describe the bug**
When in insert mode, the autocomplete behavior is very strange. In some cases, tab-completing fails to complete, leaving no text inserted.

**Expected behavior**
When I press the `tab` key when the autocomplete suggestions are visible, the current word is replaced with the highlighted autocomplete suggestion. I've also had cases where the word is torn in the middle, inserting gibberish on tab-complete (will update with screenshot the next time I encounter it).

**Screenshots**
![vscodevim-autocomplete-fail](https://user-images.githubusercontent.com/1608756/95765599-bad38d00-0c77-11eb-8388-1c7e3b9d1409.gif)
In the above screenshot, I'm pressing the `tab` key to attempt to select the `Render(...)` method. After pressing `tab`, my typing just disappears. No auto-complete, and even my partial typing is erased.

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.17.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.49.3`

**Comment by patrickeibl** [comment]
I should open a separate issue, but for now I'll note this here since it also falls under bad autocomplete behavior. If I autocomplete a suggestion, it gets inserted correctly, but then if I backspace after the autocomplete, it corrupts the completed word instead of just deleting the last character. This issue is present on 1.17.1 but not 1.16.0.

**Comment by floyd-may** [comment]
@patrickeibl I've seen the same behavior as well. Thanks for the heads up that 1.16.0 behaves reasonably here. Will try that and report back.

**Comment by floyd-may** [comment]
Confirmed; 1.16.0 behaves much better for me.

**Comment by berknam** [comment]
@floyd-may I'm not able to reproduce this. Does this happen even after reloading the window or restarting vscode? If so, can you give me a step by step that is reproducible?

**Comment by floyd-may** [comment]
I can't repro either. I moved back to 1.16.0, then at some point I got upgraded again (thanks, VS Code 😕) to 1.17.1 and I'm not seeing the weird autocomplete behavior anymore. I'm wondering if it was temporarily in a weird place between VS Code, the C# extension, and the Vim extension all doing upgrades at different times.
