### ISSUE TITLE
AppVeyor: Doesn't build on PR

### ISSUE THREAD

**Issue by jpoon** [VSCodeVim/Vim#54]
On the last couple of PR's, no status reported from `continuous-integration/appveyor/branch`

**Comment by guillermooo** [comment]
Seems to be a glitch in AV. Closing. I'll try to kick off a new build for the affected PRs.

**Comment by guillermooo** [comment]
The only similarities I see on the PRs whose branch build isn't working is that they are REQUIRED and outside of this repo. @jpoon I've no idea what's going on, but I would try marking the appveyor branch build as NOT REQUIRED to rule out issues with that. I. e., branch builds work fine for me, but I'm working from this repo.

**Comment by jpoon** [comment]
According to [this](http://www.appveyor.com/updates), AppVeyor made a recent update. 

> If you have protected GitHub branches checking AppVeyor status please update them now to use new continuous-integration/appveyor/pr status.

Updated as such.
