### ISSUE TITLE
Typing in Insert Mode with multiple cursors only types in first cursor

### ISSUE THREAD

**Issue by tylerl0706** [VSCodeVim/Vim#540]
### What did you do?

1. Put it in INSERT
2. Use Option+CLICK to spawn another cursor somewhere
3. Type stuff

### What did you expect to happen?
What you type appears by each cursor

### What happened instead?
What you type appears by only the first cursor

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.4
* OS: OS X El Capitan

**Comment by johnfn** [comment]
Currently tracked by #417.

Next on the todo list! :)
