### ISSUE TITLE
Line down lagging when in visual line selection mode

### ISSUE THREAD

**Issue by mathiashoeld** [VSCodeVim/Vim#5401]
**Describe the bug**
When selecting the whole line with CTRL-V and pressing "j" to go down one line, the selection is lagging and takes almost a second to reflect the correct selection. This is apparently only a visual issue, since the "correct" selection is deleted even if it is not displayed correctly. 

**To Reproduce**
I have four lines, with the cursor in the first line. I hit CTRL-V and hit "j" two times and hit "d". The visual selection only shows the first and the second line selected before pressing d, but the first three lines are removed.

1.  Write a text with four lines
2.  Hit CTRL-V to select the first line
3.  Hit "j" two times
4.  See two lines selected
5.  Wait one second
6.  Three lines are selected

Alternative: 

1.  Write a text with four lines
2.  Hit CTRL-V to select the first line
3.  Hit "j" two times
4.  See two lines selected
5.  Hit "d"
6. Three lines are deleted

**Expected behavior**
Each next line is selected without any delay.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: 1.50.0
- OS: Mac OS Catalina

**Additional context**
Vim Easymotion activated, "j" remapped to "gj" to jump lines with breaks

**Comment by brelian** [comment]
Could you confirm if you map `jj` to `<esc>`  key in visual mode? 
In your user's *setting.json*, remove following configuration if exists:
```json
    "vim.visualModeKeyBindings": [
        {
            "before": ["j", "j"],
            "after": ["<esc>"]
        }
   ],
```
I met the same issue but fixed by remove that mapping.

**Comment by mathiashoeld** [comment]
> Could you confirm if you map `jj` to `<esc>` key in visual mode?
> In your user's _setting.json_, remove following configuration if exists:
> 
> ```json
>     "vim.visualModeKeyBindings": [
>         {
>             "before": ["j", "j"],
>             "after": ["<esc>"]
>         }
>    ],
> ```
> 
> I met the same issue but fixed by removing that mapping.

Good catch, I indeed have mapped `jk` to `<Esc>`. I removed it and it works now as expected. Thanks!
