### ISSUE TITLE
will often appear not to respond to the phenomenon

### ISSUE THREAD

**Issue by taichirain** [VSCodeVim/Vim#541]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?
When I use mode VIM edit files, will often appear not to respond to the phenomenon, for another plug-in will not appear this problem.
I very much like to use this plugin, is all the VIM plug-ins in support of the VIM command up to one, hoping to solve this problem as soon as possible, thank you

Put the exact key strokes you pressed to reproduce the issue, if possible.

Ctrl+v(I modified the keyboard mapping.)

### What did you expect to happen?

Very smooth to use, not often collapse, no response, etc.

### Technical details:

* VSCode Version:1.3.1
* VsCodeVim Version: *[please ensure you are on the latest]*  0.1.4
* OS: Windows 10 / Debian 8.5

**Comment by rebornix** [comment]
If you run into this case next time, do you mind providing us the console log message? They are from Help->Toggle Developer Tools on Windows.

**Comment by johnfn** [comment]
I'm assuming you're saying that visual block mode is not working?

It's coming soon...

**Comment by taichirain** [comment]
Of course, it's no problem.
However, after unloading and reload, so far, there is no such problem
If later, I will put the log into the GitHub
Thank you very much. @rebornix

**Comment by taichirain** [comment]
@rebornix 
Unfortunately, it appeared again
I put the log in the attachment.

Because GitHub can not add attachments, so send e-mail to you
My email: winnersmile@qq.com

**Comment by jpoon** [comment]
@taichirain, if you use the actual site, you can attach it to your message.

**Comment by taichirain** [comment]
@jpoon @rebornix OK,This is the log under the Linux
[vim_for_vscode.txt](https://github.com/VSCodeVim/Vim/files/401393/vim_for_vscode.txt)
