### ISSUE TITLE
'C' in Visual Mode doesn't count as selected text for snippets with $TM_SELECTED_TEXT

### ISSUE THREAD

**Issue by simonsanchezart** [VSCodeVim/Vim#5418]
**Describe the bug**
When selecting text in visual mode and then using 'c' to change that text, snippets with the $TM_SELECTED_TEXT won't use the selected text in visual mode.

**To Reproduce**

1.  Open a .py (or any other format) file with any text
2.  Open the snippets file for .py and create a snippet using $TM_SELECTED_TEXT (one provided below)
3.  Go back to the .py file
4.  Select any text with Visual Mode
5. Press 'c' and attempt to use the snippet

Example snippet:
```python
	  "Try/Except Selected": {
		"prefix": "trysel",
		"body": [
		  "try:",
		  "  $TM_SELECTED_TEXT",
		  "except$1:",
		  "  $2"
		],
		"description": "Try/Except Selected"
	  }
```

**Expected behavior**
After selecting the lines, pressing c, and using the snippet, the previously selected text should be passed to $TM_SELECTED_TEXT
![eaGI10aWyj](https://user-images.githubusercontent.com/63672631/96013282-784ab580-0e1b-11eb-8118-1e7abac9a10b.gif)

**Screenshots**
Current behavior:
![Wiz9K4745X](https://user-images.githubusercontent.com/63672631/96013415-9ca69200-0e1b-11eb-9bb0-402c79d4c4a8.gif)

**Environment (please complete the following information):**

- Extension Name: `vim`
- Extension Version: `1.17.1`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.50.0`

**Comment by sql-koala** [comment]
Hi, this cannot work as you request.
"C" exits visual mode, so the text is not accessible using that var.
You can try something like this. Then, you can press "C", then select the snippet.
```

    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["C"],
            "commands": ["editor.action.insertSnippet", "extension.vim_escape"]
        },
    ]
```

**Comment by simonsanchezart** [comment]
> {
>             "before": ["C"],
>             "commands": ["editor.action.insertSnippet", "extension.vim_escape"]
>         },

This works fine, thanks! :)

**Comment by simonsanchezart** [comment]
Hello! I need to re-open this issue, that worked fine for snippets that don't require user input, for those snippets who require, it doesn't work properly, because it doesn't go back to insert mode, instead it escapes Visual mode, going back to Normal mode.

I've tried to modify the second commands, didn't found a command that brings me into insert mode. Is there a way I could achieve this?

**Comment by berknam** [comment]
You can try using the clipboard variable like this:
```json
	  "Try/Except Selected": {
		"prefix": "trysel",
		"body": [
		  "try:",
		  "  $CLIPBOARD",
		  "except$1:",
		  "  $2"
		],
		"description": "Try/Except Selected"
	  }
```

And then when in visual mode instead of just doing `c` you can do `"+c` so that the deleted text is sent to system clipboard, and then just type 'trysel\<TAB\>' and it should work. This way you are already in insert mode.

You can even make a remap like this:
```jsonc
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["c", "c"], // or other remap that works for you
            "after": ["\"", "+", "c"]
        },
    ]
```

**Comment by berknam** [comment]
Also this should work even better after PR #5540 since then it will stay in insert mode after inserting a snippet instead of going to visual mode like it currently does.

**Comment by simonsanchezart** [comment]
> Also this should work even better after PR #5540 since then it will stay in insert mode after inserting a snippet instead of going to visual mode like it currently does.

Thanks! That's certainly an improvement, although it introduces some issues with indentation:
![AU0ihv3XIL](https://user-images.githubusercontent.com/63672631/97819641-9d974a80-1c88-11eb-9187-80562696c109.gif)

The first issue is that Visual Line selects the whole line, is there an option to make it select only to the first character in the line, which means that when going to insert the snippet, it will not be indented properly if it's nested in a class, loop, etc...

$CLIPBOARD also seems to give an extra tab to the first line of the selection. although that seems to be mostly a VS Code issue.

**Comment by berknam** [comment]
The $CLIPBOARD keeps the same indentation level as it previously had. You can fix the extra tab by changing your snippet to this:
```jsonc
	  "Try/Except Selected": {
		"prefix": "trysel",
		"body": [
		  "try:",
		  "$CLIPBOARD", // <-------- This is where you should remove the extra tab
		  "except$1:",
		  "  $2"
		],
		"description": "Try/Except Selected"
	  }
```

The visual line mode will always select the entire line if you don't want to select the entire line you can use visual mode with `v` and start on the first character of the line. To move to this character you can either use `_` or `^`.

**Comment by simonsanchezart** [comment]
That works better, thanks a lot!
