### ISSUE TITLE
When using / searching, do not support Chinese

### ISSUE THREAD

**Issue by taichirain** [VSCodeVim/Vim#542]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?

Put the exact key strokes you pressed to reproduce the issue, if possible.

### What did you expect to happen?
Hope to support the Chinese search
### Technical details:

* VSCode Version:1.3.1
* VsCodeVim Version: *[please ensure you are on the latest]* 0.1.4
* OS:  Window10 / Debian 8.5

**Comment by rebornix** [comment]
This issue should be gone once VS Code releases 1.4.0 Stable.

**Comment by johnfn** [comment]
@rebornix @taichirain can you guys confirm that this issue is now gone?

**Comment by rebornix** [comment]
Verified with Code 1.4.0 and VSCodeVim 0.1.6.
