### ISSUE TITLE
Glitch after paste multiple lines

### ISSUE THREAD

**Issue by Komar0ff** [VSCodeVim/Vim#5442]
**Describe the bug**

When trying paste multiple lines, vscode starts to glitch and paste doesn't occur.

**To Reproduce**

1.  yank any line (**yy**)
2. select any line (**V**)
3. Paste multiple lines (**10p**, for example)

![jopa](https://user-images.githubusercontent.com/10588170/96352572-c0443380-10cc-11eb-8b46-cda4a074b59e.gif)

**Expected behavior**
I expect the specified number of lines to be paste

**Environment:**
- Extension (VsCodeVim) version: 1.17.1
- VSCode version: 1.50.0
- OS: 10.15.7

**Comment by rickythefox** [comment]
Seems like this is not implemented:
`src/actions/commands/put.ts:431` says
```
  // TODO - execWithCount
```
