### ISSUE TITLE
Failed to handle key=p. No multi-cursor index when calling PutCommand

### ISSUE THREAD

**Issue by uyu423** [VSCodeVim/Vim#5448]
Multi-line copy-paste action failed in Windows 10.

Is this possible?

**Comment by sql-koala** [comment]
Hi, can you provide the steps to repro this?

**Comment by J-Fields** [comment]
Repro steps:

1. Make 2 cursors, on different lines
2. `yy`
3. Make a third cursor
4. `]p`
