### ISSUE TITLE
Broken jsx autocomplete

### ISSUE THREAD

**Issue by andreyohiienko** [VSCodeVim/Vim#5474]
**Describe the bug**
When I write component name and press "tab" I expect to write something between opening closing component's jsx tag, but for some reason vim switches to Visual mode. When I write HTML tags vim switches to Insert mode after pressing "tab". Also 1.16.0 worked properly.

**To Reproduce**

1.`"emmet.triggerExpansionOnTab": true,
     "emmet.includeLanguages": {
   "javascript": "javascriptreact"
}`
2.  Open .js file
3.  Write InputField 
4.  Press tab
5.  Try to write something `<InputField>here</InputField>`

**Expected behavior**
Ability to write code at once after pressing tab autocompletion between opening and closing component's jsx tag and switching vim to insert mode. 
**Screenshots**
https://www.screencast.com/t/uyDHht1WmPAY

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: 1.50.1
- OS: windows

**Additional context**
For some snippets like 'clo' which is used for "console.log('object', object)" in [ES7 React/Redux/GraphQL/React-Native snippets](https://marketplace.visualstudio.com/items?itemName=dsznajder.es7-react-js-snippets)  also observed switching to Visual mode instead of insert mode.
This issue driving me crazy I'll appreciate for any suggestions or fix.
Thanks

**Comment by MarcWeber** [comment]
vscode.window.activeTextEditor.insertSnippet("something") does trigger it. Wrote my own code to use snipmate snippets but its kind of annoying if cursor is not at the placeholder positions.
