### ISSUE TITLE
Undo undoes everything you've ever done

### ISSUE THREAD

**Issue by oheard** [VSCodeVim/Vim#548]
When using 'u' to undo with the vim plugin installed the text editor goes nuts, undoing way too much.

To make matters worse the redo functionality does nothing.

**So pressing undo can easily result in hours of work being thrown away with no way to get it back!**

**Comment by rebornix** [comment]
I ran into this case each time doing rebasing with conflicts. Let's say I have one not-synced commit A in local branch and I want to rebase against remote branch, which has two more commits B and C. A has conflicts with both B and C.

When you start to rebase, you will have merge conflicts when apply B and you manually merge the code.  Then you continue to rebase and have merge conflicts again with C, while manually merging the conflicts, if you run `undo`, it will undo everything you have done during the whole rebasing process. What's worse, `redo` does nothing.

I agree it's annoying but we are likely to have History support in August so let's wait and see if we can solve it automically later.

**Comment by johnfn** [comment]
Ugh, this is really really bad! I'm really sorry about that, @oheard. 

Until we get this fixed, one thing to keep in mind is that Vim keeps a separate history from VSCode, so if Vim's history gets messed up, you can still undo through the normal VSCode history with ctrl/cmd-z. That may help you get out of sticky situations like what you encountered.

**Comment by johnfn** [comment]
Closing in favor of #558.

Again, really sorry about this. It's super crappy to have happen.
