### ISSUE TITLE
In insert mode, deleting at the start of a line should not move the cursor to the end of the new line

### ISSUE THREAD

**Issue by thomasboyt** [VSCodeVim/Vim#550]
Given the following text and cursor in insert mode:

```
abcd
|efgh
```

Pressing backspace should result in the following text and cursor placement:

```
abcd|efgh
```

Instead, the cursor is placed at the *end* of the new line:

```
abcdefgh|
```

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.4
* OSX 10.11

This behavior appears to be defined [here](https://github.com/VSCodeVim/Vim/blob/master/src/actions/actions.ts#L598). This seemed like an obvious bug report, but I couldn't find an existing one - sorry if this is a duplicate!

**Comment by jpoon** [comment]
@thomasboyt thanks for the bug report, especially pinpointing it in the code. Should be a relatively easy fix.

**Comment by thomasboyt** [comment]
@jpoon yup, I'm about to submit a PR for it :)
