### ISSUE TITLE
Failed to handle key=<Esc>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by jshwi** [VSCodeVim/Vim#5526]
I am getting what looks like a failed keybinding - but I cannot find a keybinding configured to run ``closeDirtyDiff``.

**To Reproduce**

1.  Press ``i`` to enter insert mode
2.  Press ``ESC`` to enter command mode
3.  Press ``ESC`` while in command mode
4.  See error

**VSCodeVim version**: 1.17.1
<details><summary>Stack trace</summary>```Error: Command with id 'closeDirtyDiff' is not registered.    at e.<anonymous> (https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:167:284758)    at https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:167:282735    at Object.next (https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:167:282840)    at https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:167:281753    at new Promise (<anonymous>)    at r (https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:167:281490)    at e.$executeCommand (https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:167:284631)    at e.doInvokeHandler (https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:19:199168)    at e.invokeHandler (https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:19:198901)    at e.receiveRequest (https://c9d2a6b3-15d9-4637-b3e6-534791c3cc7e.ws-us02.gitpod.io/bundle.js:19:198193)```</details>

**Comment by J-Fields** [comment]
What version of VS Code are you running?

**Comment by Michaelhobo** [comment]
I'm also running into this, but I'm using Gitpod. I don't think they have analogous version numbers to VS Code.

**Comment by jshwi** [comment]
Hi @J-Fields, like @Michaelhobo I was getting this on Gitpod. The reasons I logged this though, and unfortunately I cannot remember enough about it, was I did recall getting this (or a similar error) on a pure VSCode install. I understand if there is not much that can be done with this information and there is the workaround of not hitting ESC by habit in command mode lol

**Comment by Michaelhobo** [comment]
I DO have a habit of spamming ESC more than once, due to a past buggy IDE implementation of vim keybindings...
