### ISSUE TITLE
Cannot change mode between VISUAL and VISUAL LINE

### ISSUE THREAD

**Issue by learning** [VSCodeVim/Vim#555]
### What did you do?
When I'm in `VISUAL` mode, I can't change to `VISUAL LINE` mode by hitting `V`, or vice versa.

### What did you expect to happen?
Just like native vim do, changing mode between `VISUAL` and `VISUAL LINE` by hitting `v` or `V`

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: *0.1.4*
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
Fixed on master and will be included in our next patch release. Thanks for the issue, @learning!
