### ISSUE TITLE
<C-o> in insert mode is not supported

### ISSUE THREAD

**Issue by taka231** [VSCodeVim/Vim#5550]
I would like to use C-o in insert mode to use a normal mode command only once. But it is not implemented.
Are there any way to implement it?

**Comment by sql-koala** [comment]
Hi, this is supported.
Check your settings for this
![image](https://user-images.githubusercontent.com/30384885/97808914-03280e80-1c6a-11eb-8b78-ace69b142265.png)
And this:
```
    "vim.handleKeys": { "<C-k>": false
                        ,"<C-o>": true
                      },
```

**Comment by taka231** [comment]
Thank you! I have one question. what "vim.handleKeys" mean?

**Comment by taka231** [comment]
I understood that "vim.handleKeys" is used for disabling some key bindings.
