### ISSUE TITLE
C or cc will kill the empty line

### ISSUE THREAD

**Issue by learning** [VSCodeVim/Vim#556]
### What did you do?

I have these three line of codes:

```
export const options = {

};
```

The second line is empty, without any tab or spaces, my cursor on line 2 and then I'm hitting `C` or `cc`.

### What did you expect to happen?

Just simply turn into `INSERT` mode like vim do

### What happened instead?

VsCodeVim kill the second line, and the cursor goes before `}`;

```
export const options = {
};
```

### Technical details:

* VSCode Version: 1.3.1
* VsCodeVim Version: *0.1.4*
* OS: OS X 10.11.6

**Comment by rebornix** [comment]
@learning really good catch!

**Comment by glibsm** [comment]
This applies to `S` as well, when that lands.
