### ISSUE TITLE
<Backspace> while typing ex command deletes text in file

### ISSUE THREAD

**Issue by babramczyk** [VSCodeVim/Vim#5584]
**Describe the bug**
When typing an ex (`:<...>`) command, hitting backspace deletes text before the cursor instead of the text in the command I'm typing

**To Reproduce**

1.  Open a file
2. Put cursor somewhere near some text
3. Go into normal mode
4. Type `:jumpt` (typo'd `jumps`)
5. Hit `backspace`

**Expected behavior**
The command should now read `:jump`, and the text in the file should remain unchanged

**Actual behavior**
The command still reads `:jumpt`, and the character before the cursor in the file is deleted.

**Screenshots**
Recording: https://streamable.com/okvwb6

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:`v1.17.1`
- VSCode version: `1.50.1`
- OS: `macOS 10.15.6`

**Additional context**
I disabled all my remappings to see if it was related, but the bug persisted.

**Comment by J-Fields** [comment]
Does this always happen or just sometimes? Can you go into VSCode's keyboard shortcuts and show all the mappings you have for backspace? Like this:
![image](https://user-images.githubusercontent.com/12375115/98389028-7e4e4380-2021-11eb-8b31-9d6c4e1b6221.png)

**Comment by babramczyk** [comment]
AFAIK, it happens always. I reloaded the window and tried multiple files, and it still seems to happen.

Here are my keybindings:

![image](https://user-images.githubusercontent.com/16885191/98391069-cc604880-201b-11eb-9bcc-02320964709e.png)

**Comment by J-Fields** [comment]
This one's your issue (notice it says "User" on the right?) Right click and reset the keybinding and it should work ![image](https://user-images.githubusercontent.com/12375115/98395433-3e3f8e80-202a-11eb-8028-172f52a2fd00.png)

**Comment by babramczyk** [comment]
Ah, you're totally right. This override was to enable "hungry/smart backspace" functionality I have in Vim when editing.

In case anyone else runs into this, the fix is to have the following overrides in `keybindings.json`:

```jsonc
  // Cancel the original vim backspace
  {
    "key": "backspace",
    "command": "-extension.vim_backspace",
    "when": "editorTextFocus && vim.active && !inDebugRepl"
  },
  // Enable the vim backspace only in search mode or ex mode
  {
    "key": "backspace",
    "command": "extension.vim_backspace",
    "when": "editorTextFocus && vim.active && !inDebugRepl && (vim.mode == 'SearchInProgressMode' || vim.mode == 'CommandlineInProgress'"
  }
```
