### ISSUE TITLE
Reverse search for `{` stops after first `n`

### ISSUE THREAD

**Issue by babramczyk** [VSCodeVim/Vim#5591]
**Describe the bug**
When reverse searching (`?`) for `{`, `n` no longer advances to the next match after the first `n`.

**To Reproduce**

1.  Go to a file with multiple left curly brackets (`{`)
2. Go somewhere in the middle of those brackets
3. Type `?{<ENTER>nnnnn`

**Expected behavior**
`n` should continue to go to next matches

**Actual behavior**
After the first `n`, subsequent `n`s become no-ops.

> Note: `N` (go to previous match) works as intended (as shown in video below)

**Screenshots**
https://streamable.com/brdys8

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: 1.51.0
- OS: macos 10.15.6

**Comment by sql-koala** [comment]
Hi, this is interesting.
I can repro it. But I think it is a special case, that has do to with a match at end of line.
Because if you try it on these lines, "n" will work.
```
      } } } } start from here
      { { { { start from here
```

**Comment by sql-koala** [comment]
I have figured this out and can get a PR ready. But I dont want to add to 41 open PR right now...

**Comment by J-Fields** [comment]
> I have figured this out and can get a PR ready. But I dont want to add to 41 open PR right now...

No please do @sql-koala, I'll eventually find the time to chew through all those 🙂
