### ISSUE TITLE
Cursor inconsistent after `gd` and changing tabs

### ISSUE THREAD

**Issue by jordanlewis** [VSCodeVim/Vim#562]
Continued from #530.

If you run `gd` on a symbol that lives in a different file and then move back to the first file with cmd-opt-left, running a movement will first move the cursor to the line number in the second file that `gd` jumped to and then execute the movement afterward.

The steps are:

1. `gd` on a symbol in a different file
2. Wait until the `gd` finishes and a new tab is created for the other file
3. Navigate back to the first file using the keyboard
4. Run `j` - the cursor will jump to the line below the line whose number is the same as the symbol in the other file that `gd` jumped to.

**Comment by rebornix** [comment]
This is fixed already.
