### ISSUE TITLE
Macros in File A Don't Work in File B

### ISSUE THREAD

**Issue by jkassis** [VSCodeVim/Vim#5636]
Cannot cross file-boundaries with macro definitions.

**Comment by J-Fields** [comment]
Do you mean "record macro in file A, execute in file B" or "record macro which starts in file A and ends in file B"? The former should work; the latter definitely doesn't.

**Comment by jkassis** [comment]
hmmm. was referring to the former. it did in fact work just now when I attempted to repro.
