### ISSUE TITLE
Always use "z" for vim-sneak because "s" deletes current character

### ISSUE THREAD

**Issue by silvenon** [VSCodeVim/Vim#5645]
**Is your feature request related to a problem? Please describe.**
I often use `s` in command mode to delete the current character and jump into insert mode, but vim-sneak overrides this.

**Describe the solution you'd like**
Always use `z` for vim-sneak, not just when prefixed with a command.

**Describe alternatives you've considered**
🤷

I love this plugin, btw! I'm so excited to be getting back into Vim, but still get to enjoy all the VS Code features 😍

**Comment by sql-koala** [comment]
Hi, we cant do what you are asking for, because there are many scrolling or folding commands (zz, zt, zc, zo ...) that would be disabled/confused.
But you can try these maps and see if this is right for you:
```
nnoremap z s
nnoremap s cl
```

**Comment by silvenon** [comment]
I didn't realize it was this command was taken, in that case never mind. Thanks for the suggestion, I'll try it 😃
