### ISSUE TITLE
'u' should clear modified flag

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#565]
### What did you do?

 open a file
 do some editing
 `u` to undo all editing
 close the file
### What did you expect to happen?

the file be closed
### What happened instead?

VSCode asks: Do you want to save the changes you made to xxxxx?
### Technical details:
- VSCode Version: 1.4.0
- VsCodeVim Version: 0.1.4
- OS: Windows 10 Professional

**Comment by johnfn** [comment]
I wish... Unfortunately, this is something that VSCode won't let us do currently.

**Comment by rebornix** [comment]
Currently we are doing `undo` ourselves but I'm thinking this issue can be mitigated by setting correct `undo stop` and trigger Code's `undo` functionality.

**Comment by johnfn** [comment]
Yeah, they do provide the API now! However, it would not be a straightforward change. On top of porting our history tracking code, you'd also have to get the remapper to work, which depends on reversing individual keystrokes (jj => esc reverses both j's, even though they wouldn't be separate undo steps).

**Comment by rebornix** [comment]
@johnfn true. I'll have another round of sync up about the history access this afternoon and then let's how can we improve.

**Comment by enkeyz** [comment]
Any progress on this?

**Comment by prog666** [comment]
That's one of few things that prevents me from using vscode =(

**Comment by J-Fields** [comment]
Closing in favor of #3201
