### ISSUE TITLE
Repeating find next character with ; does not work

### ISSUE THREAD

**Issue by shadowstrafe** [VSCodeVim/Vim#566]
Do you need help or have a question? Ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫.
Found a bug? Please fill out the sections below 👍.

### What did you do?

f";

### What did you expect to happen?

I expected the cursor to move to the next double quote character.

### What happened instead?

The cursor did not move.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.4
* OS: Windows 10 Enterprise 64-bit

**Comment by johnfn** [comment]
Tracked by #410. We will get there. :)
