### ISSUE TITLE
"vat" doesn't work

### ISSUE THREAD

**Issue by Iancurtis** [VSCodeVim/Vim#567]
i tried to use "vat" but it didn't work.
here is the sample code 

`<h1>hello world</h1>`

* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.4
* OS: OSX 10.11.5

**Comment by jpoon** [comment]
FYI. As I didn't know what `vat` should do:

vat should visually select the surrounding tag block. e.g. it'll select the whole of `<h1>Hello World</h1>`

**Comment by sectioneight** [comment]
Note to implementers (possibly myself). We should augment the character matching functionality in `matching/matcher.ts` to account for this.

**Comment by sectioneight** [comment]
Oh, I already implemented this (#619), it's just not released yet.

See test verifying behavior: https://github.com/VSCodeVim/Vim/commit/d9cba8bbe6406e00dd922b4d22966948be010e0b#diff-1c2d9f60bad26dc81e4e7c0b348308adR537

**Comment by jpoon** [comment]
@sectioneight awesome possum. Closing this issue.
