### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by kimitake** [VSCodeVim/Vim#57]
I just tried to run gulp as README using master branch, and got the following error at command line scanner (section?).

1) command line scanner can expect one of set:
TypeError: undefined is not a function
src\cmd_line\scanner.js:101:87
 :

What is wrong? or can I ignore this error?

**Comment by jpoon** [comment]
What node version are you running? Trying upgrading to > "4.1.1" which is what our Travis tests are using.

**Comment by kimitake** [comment]
just updated to 4.2.2 and fixed this issue. Thanks!!
