### ISSUE TITLE
Repeated 't/T' actions do not work

### ISSUE THREAD

**Issue by lopezn** [VSCodeVim/Vim#570]
Using the test format (which is great by the way):

start: ['|abcde abcde'],
keysPressed: 'tdtd',
expectedEnd: ['abcde ab|cde'],
actualEnd: ['ab|cde abcde']

Same with 'T':

start: ['abcde abcd|e'],
keysPressed: 'TaTa',
expectedEnd: ['a|bcde abcde'],
actualEnd: [abcde a|bcde']

So repeated 't/T' actions do not go past the first search.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.4
* OS: Windows 7 Service Pack 1

**Comment by johnfn** [comment]
This behavior is exactly what happens in normal Vim. Try it out! 😄
