### ISSUE TITLE
Extremely slow rendering introduced in v1.17 with long text in register

### ISSUE THREAD

**Issue by wjdwndud0114** [VSCodeVim/Vim#5707]
**Describe the bug**
Updating to 1.17.x make my vscode unusable due to the hit to my performance. Going back down to 1.16 or any version below that works fine.

I tried disabling every extension except this and the issue persists. Of course, disabling vscodevim fixes the issue.

**To Reproduce**
Save long text in register. Now every session will lag hard until you overwrite it.

Whenever I change tabs, there is a 5 second lag before I could do anything and vscode in general is quite unusable.

**Expected behavior**
No lag.

- Extension (VsCodeVim) version: 1.17.x
- VSCode version: 1.51.1
- OS: Darwin x64 20.1.0

**Additional context**
I think at some point it was working fine but one day it just broke and I am unable to fix it. Perhaps something went wrong with a macro and it saved? I saw an issue that described a similar issue, but clearing cache isn't helping.

Updated the description/reproduce section since I found the cause/solution

**Comment by wjdwndud0114** [comment]
I fixed it - the issue was with the register holding a value too big.
I tried doing `:reg` to see my registers and that lagged and didn't show anything.
Then I did `:reg 1` and so on to see the values and turns out my register 1 had a large value. I overwrote the value doing `"1 dd` and my issue was resolved.

I'll leave this open for one of the devs to address and other people to refer to.

**Comment by J-Fields** [comment]
How big are we talking? I think this is due to us saving registers to disk in a rather naive way, and we do it whenever a register changes (...including `%`. Yeah this is very dumb).

**Comment by wjdwndud0114** [comment]
> How big are we talking? I think this is due to us saving registers to disk in a rather naive way, and we do it whenever a register changes (...including `%`. Yeah this is very dumb).

Don't know, but I must've accidentally copied a very large file. I just tried with a ~3 million char register and I could reproduce the lag. But not as bad so I'm guessing it was more

**Comment by J-Fields** [comment]
Just realized there's a `deactivate` function in the VSCode API, so we can just save the registers to disk once when VSCode is closed. Much better. Thanks for pointing this out!
