### ISSUE TITLE
'dF/dT' deletes an extra character

### ISSUE THREAD

**Issue by lopezn** [VSCodeVim/Vim#571]
Using the test format:

start: ['abcdefg|h'],
keysPressed: 'dFd',
expectedEnd: ['abc|h'],
actualEnd: ['ab|h']

Same with 'T':

start: ['abcdefg|h'],
keysPressed: 'dTd',
expectedEnd: ['abcd|h'],
actualEnd: ['abc|h']

### Technical details:

VSCode Version: 1.4.0
VsCodeVim Version: 0.1.4
OS: Windows 7 Service Pack 1

**Comment by johnfn** [comment]
Yep, that's a bug.

**Comment by jpoon** [comment]
Closed with https://github.com/VSCodeVim/Vim/pull/579
