### ISSUE TITLE
shift-Y support in visual mode

### ISSUE THREAD

**Issue by davidgiven** [VSCodeVim/Vim#573]
Currently Y does nothing. From the vim docs:

    {Visual}["x]y		Yank the highlighted text [into register x] (for
    			{Visual} see |Visual-mode|).  {not in Vi}

    {Visual}["x]Y		Yank the highlighted lines [into register x] (for
    			{Visual} see |Visual-mode|).  {not in Vi}

So Y yanks lines, while y yanks arbitrary text.

In visual line mode y and Y should be equivalent, so this is probably quite easy there, but I don't know about non-line mode.

**Comment by johnfn** [comment]
Sounds like an easy one for anyone to pick up :-)

**Comment by davidgiven** [comment]
This doesn't seem to be working for me. It looks like P is doing the paste, but Y is not.

...aha, figured out what's going on! If I select text with the mouse, Y works. If I select text using shift-V, it doesn't; Y doesn't do anything at all. Looks like Y isn't working in visual line mode or visual block mode, but is working in visual mode.

**Comment by davidgiven** [comment]
Hmm, can't reopen this issue. I'll file a new one.
