### ISSUE TITLE
Cannot remap same key for different "when" cases

### ISSUE THREAD

**Issue by fgarcia** [VSCodeVim/Vim#5733]
**Describe the bug**

In VSCode it is possible to map a keyboard shortcut multiple times based on different contexts. This seems to be supported by VSCodeVim looking at the "when" field

**To Reproduce**

In my case: There is no "toggle editor/tab pin" so I try to emulate a toggle shortcut like the standard one C-K Shift-Enter

Use this setting

```
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["leader", "enter"],
       "when": "!activeEditorIsPinned",
      "commands": [
        {
          "command": "workbench.action.pinEditor"
        }
      ]
    },

    {
      "before": ["leader", "enter"],
      "when": "activeEditorIsPinned",
      "commands": [
        {
          "command": "workbench.action.unpinEditor"
        }
      ]
    },
 ]
```

**Expected behavior**
It seems like the same keystroke would behave differently under different circumstances, but only the second shorcut seems to work. My guess is that the second case totally overrides the first one without considering that they must coexist under different context.

- Extension Name: `vim`
- Extension Version: `1.17.1`
- OS Version: `Linux x64 5.4.0-54-generic`
- VSCode version: `1.51.1`

**Comment by sql-koala** [comment]
Hi, this (when condition) is not supported.
There are existing issues where the devs explain, why this is difficult:
https://github.com/VSCodeVim/Vim/issues/2030
https://github.com/VSCodeVim/Vim/issues/1372

**Comment by fgarcia** [comment]
yep, definitely those are duplicates I could not find before posting. Closing this one so people can upvote those
