### ISSUE TITLE
How to format document with another “code-prettier” plugin by using vim “=“ key?

### ISSUE THREAD

**Issue by ysl970629** [VSCodeVim/Vim#5739]
I have set “prettier” for default workspace formatter.
I want to format part of the document , but when I bind “=“ with command “editor.action.formatSelection” or “editor.action.formatDocument”, I can’t use key combinations like “gg=G”

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by J-Fields** [comment]
`=` is already bound to `editor.action.formatSelection`; this should work out of the box.

**Comment by ysl970629** [comment]
Ok, thank you :-)
