### ISSUE TITLE
Any reason why `gD` is not implemented by default?

### ISSUE THREAD

**Issue by kiprasmel** [VSCodeVim/Vim#5769]
"Go to references" is extremely useful and I found it strange that "Go to definition" via `gd` was working, but go to references via `gD` was not.

Here's how I made it work with the remapping feature:

```json
	"vim.normalModeKeyBindings": [
		{
			"before": ["g", "D"],
			"commands": ["editor.action.goToReferences"],
		}
	],
```

as described in https://github.com/VSCodeVim/Vim#key-remapping

the only issue is that after `gD` and selecting some reference, I end up in visual mode instead of normal/insert -- any ways to change this?

and then - any chance to enable it by default? Thanks!

**Comment by sql-koala** [comment]
Hi, the difference to "Goto definition" is that "Goto Ref" opens a overlay window like so, which requires additional input (keystrokes or mouse). this would be more effort to capture/process.
![image](https://user-images.githubusercontent.com/30384885/100536971-a6962000-3224-11eb-8cdc-f22067da28f8.png)

Your mapping is good. When I add two simple entries to keybindings.json, it almost feels like "builtin".
```
{
    "key": "n",
    "command": "goToNextReference",
    "when": "inReferenceSearchEditor || referenceSearchVisible"
},
{
    "key": "shift+n",
    "command": "goToPreviousReference",
    "when": "inReferenceSearchEditor || referenceSearchVisible"
},
```
When you use these keybindings (or normal F4) instead of mouse, you also do not get a visual selection.

**Comment by J-Fields** [comment]
Unless I'm missing something, `gD` doesn't find references in Vim:

```
gD			Goto global Declaration.  When the cursor is on a
			global variable that is defined in the file, this
			command will jump to its declaration.  This works just
			like "gd", except that the search for the keyword
			always starts in line 1.
```

**Comment by berknam** [comment]
> When you use these keybindings (or normal F4) instead of mouse, you also do not get a visual selection.

You do not get a visual selection only if you press `<Esc>` or if you click the close button on the overlay window. But if you press `<Enter>` or double click the entry you want vscode creates a selection.

**Comment by kiprasmel** [comment]
@J-Fields 

> Unless I'm missing something, `gD` doesn't find references in Vim

ah yes, I got this from doom emacs and I think it's both more useful and intuitive. Though because it's not the default in vim, I don't know if we should have it here - perhaps, or if not - a mention in the docs could be useful.

**Comment by kiprasmel** [comment]
@sql-koala (https://github.com/VSCodeVim/Vim/issues/5769#issuecomment-735360686)

oh that's neat -- thanks!

**Comment by J-Fields** [comment]
I think it's better to leave it up to users to map themselves
