### ISSUE TITLE
dw deletes whole line when trying to delete last word

### ISSUE THREAD

**Issue by chrisolsen** [VSCodeVim/Vim#578]
### What did you do?
```
foo |bar
```
With the cursor on the last word of the line `dw` deletes the whole line.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 1.8.5
* OS: windows 10

**Comment by johnfn** [comment]
I cannot reproduce this at all. Can you please provide the entire text of the document?

**Comment by rebornix** [comment]
I fixed this issue via https://github.com/VSCodeVim/Vim/pull/428 one month ago, after that I no longer ran into that issue again. @chrisolsen can you confirm the version as our version is still 0.x.x and I don't know we ever release 1.8.5, thanks in advance!

**Comment by johnfn** [comment]
@rebornix True, though 1.4.0 and 0.1.4 look pretty similar to me...

**Comment by chrisolsen** [comment]
I will be able to check tomorrow and let you know, but it should be the latest version. I may have miss typed it.

**Comment by chrisolsen** [comment]
My bad! I was using the amVim plugin. I switched over this morning, and as @rebornix mentioned, the bug doesn't exist in the current version of VSCodeVim. Sorry for the confusion.

**Comment by rebornix** [comment]
@chrisolsen amVim is another amazing Vim extension, I play with it sometimes as well. It would be really awesome if you provide feedbacks about VSCodeVim after playing with both of them.

**Comment by chrisolsen** [comment]
Will do!

One thing that popped out right away was that your plugin (vscodevim) seems to have a faster response time to keyboard entry and feels a little smoother. If you guys are open to it I will definitely make mention of any areas that could use improvement.

Thanks for putting together an awesome plugin 👍

**Comment by rebornix** [comment]
Thanks again @chrisolsen ! We do look forward to all kinds of improvement suggestion and feature requests, feel free to reach out to us here or our Slack Channel.
