### ISSUE TITLE
Update README to include key repeat instructions for Mac Exploration builds

### ISSUE THREAD

**Issue by edwinhollen** [VSCodeVim/Vim#5789]
Hi, I'm using Mac VS Code Exploration builds temporarily, and I discovered that the set of "enable key-repeating" commands found in the README only accommodates `com.microsoft.VSCode` (stable), `com.microsoft.VSCodeInsiders` (Insider), and `com.visualstudio.code.oss` (Codium), and does not currently include the necessary command to enable this helpful behavior for Exploration users. 

**Expected behavior**
The instructions should include this command to enable key repeat for VS Code Exploration users:

`defaults write com.microsoft.VSCodeExploration ApplePressAndHoldEnabled -bool false`

(This is the CFBundleIdentifier found in the `Visual Studio Code - Exploration.app/Contents/Info.plist` file) 🙂

**Comment by AMMAR-62** [comment]
I'll take up this issue ... if it's open
