### ISSUE TITLE
Cursor jumps back to previous position when moving after clicking in editor

### ISSUE THREAD

**Issue by nskillen** [VSCodeVim/Vim#5795]
**Describe the bug**
When editing a file, if I use the mouse to click the cursor to a specific location, if I then immediately use a navigation key (eithe arrow or hjkl) to attempt to move from the clicked location, instead of moving as directed, the cursor will jump back to the location it was at before I clicked, and then execute the motion.

**To Reproduce**

1.  Load a file in the vscode editor
2.  Observe where the cursor is
3.  Click somewhere else in the file so that the cursor moves to that location (can be same or different line, normal or insert mode)
4.  Use arrow keys, or hjkl to attempt to move cursor from the location that was clicked

**Expected behavior**
The cursor moves as directed by the keypress

**Actual behavior**
The cursor jumps back to the location it was at before the click, and then executes the motion

**Screenshots**
![vsvim_cursor_bug](https://user-images.githubusercontent.com/120346/100706192-ced96800-3365-11eb-92f5-04216ba48b6a.gif)

You can see the bug here. After each click, I'm hitting the left or right arrow key, but you can see the cursor jumping back to the original location

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.0
- VSCode version: 1.41.0
- OS: MacOS Big Sur 11.0.1 (happened before I upgraded to Big Sur as well)

**Additional context**
n/a

**Comment by berknam** [comment]
Closing since this is fixed in new version "1.18". Please check if your still having any issues and reopen if you do.
