### ISSUE TITLE
How to clear the contents of the additional register (example the "A register)

### ISSUE THREAD

**Issue by LoserJL** [VSCodeVim/Vim#5796]
When I used the "A register for a few days, I found that the content of the "A register was more and more, and I couldn't find a way to clear it, can you give me a way to clear it, or is it a bug to be fixed

**Comment by LoserJL** [comment]
copy the contents to "a register overwritten "A register

**Comment by J-Fields** [comment]
Yeah `"a` is the register, and `"A` appends to the `"a` register
