### ISSUE TITLE
Can ‘%’  support macro block jump?

### ISSUE THREAD

**Issue by jiaobendaye** [VSCodeVim/Vim#5805]
In vsvim, '%' is support macro  block  ('#if' '#else' '#elif' '#endif') jump. Does VSCodeVim support?

**Comment by J-Fields** [comment]
Not currently, though it's a reasonable request

**Comment by sql-koala** [comment]
Could be seen as dupe of #1885

**Comment by J-Fields** [comment]
I agree, closing as a duplicate of #1885 - I'll put a comment mentioning this specifically there.
