### ISSUE TITLE
Current line/cursor position not remembered when switching windows/editors

### ISSUE THREAD

**Issue by neonshadow** [VSCodeVim/Vim#581]
### What did you do?

```
<ctrl>+w, l
<ctrl>+w, h
```

### What did you expect to happen?

Cursor should jump from current window/editor to window/editor on the right, then back again to the one on the left, to the line where it was there previously. 

### What happened instead?

The cursor seems as though it initially jumps from the correct position to a different arbitrary position. Sometimes it works and sometimes it seemingly randomly jumps somewhere else.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 1.1.4
* OS: Windows 10

**Comment by johnfn** [comment]
Yep, I was able to reproduce this as well, but strangely it seems to be difficult to get the plugin into the state where this happens. 

If you have any idea of what causes this to repro more consistently, let me know!
