### ISSUE TITLE
<C-o> <C-i> will mess up cursor movement with left and right keys

### ISSUE THREAD

**Issue by cvcore** [VSCodeVim/Vim#5813]
**Describe the bug**
After using `<C-o>` `<C-i>` jumps, movements with `<left>` and `<right>` key will always bring the cursor back to an old position.

**To Reproduce**
(please also see video below)

1.  Open several files with VSCode
2.  Use `<C-o>` to jump to an old position, and then `<C-i>` to jump back (at 10s in the video).
3.  Use `<up>` or `<down>` to move to another line.
4.  Now press `<left>` or `<right>`, the cursor will jump back to old line.

**Screenshots**

To demonstrate, I've recorded a video: https://youtu.be/b6fV2dUVMF0

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.2
- VSCode version: 1.51.1
- Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
- Date: 2020-11-11T01:11:34.018Z
- Electron: 9.3.3
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 19.6.0

**Comment by berknam** [comment]
I can't reproduce this. Can you reliably reproduce this? If you reload the window (`Ctrl+Shift+P` to open command palette and then run "Developer: Reload Window") does this still happen?

**Comment by cvcore** [comment]
@berknam yes I can reproduce this every time after reloading. I will try a fresh install and let you know if it still happens.

**Comment by cvcore** [comment]
great, thanks a lot for the quick fix! @berknam

**Comment by berknam** [comment]
@cvcore By the way do you have any remaps or keybindings set for the \<up\>/\<down\> keys?

**Comment by cvcore** [comment]
@berknam yes I have the following remappings set in `keybindings.json`:

```
    {
        "key": "up",
        "command": "cursorUp",
        "when": "editorTextFocus && vim.active && !inDebugRepl && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
    },
    {
        "key": "down",
        "command": "cursorDown",
        "when": "editorTextFocus && vim.active && !inDebugRepl && !suggestWidgetMultipleSuggestions && !suggestWidgetVisible"
    },
```

**Comment by berknam** [comment]
Ok. That explains why I couldn't reproduce the up/down issue. You shouldn't need those bindings anymore. There was an old issue that made it so you couldn't use \<up\>/\<down\> arrows to move on suggest widgets but that has since been fixed. If that was the reason for having those bindings you can safely remove them as they are no longer needed.

Thanks a lot for your detailed issue and video! It sure did help a lot to understand the underlying problem!
