### ISSUE TITLE
Ctrl-based combos stopped working unless `vim.use(…)` condition is removed from When expression

### ISSUE THREAD

**Issue by strogonoff** [VSCodeVim/Vim#5819]
**Describe the bug**

Ctrl-based normal mode commands, such as <C-r> for redo, suddenly stopped working unless I delete `&& vim.use(…)` part from each mapping’s When expression.

Seems to have coincided with VS Code and/or extension version update (which I was postponing).

I don’t remap keys and am using default combinations, so I don’t think this qualifies as remapping-related.

**To Reproduce**

Just try using ctrl+v for visual block selection, ctrl+u to scroll up, or ctrl+r to redo last undone change, etc.

Mostly nothing happens, though in case of `ctrl+r` I had VS command prompt pop up (which I think I map to something else anyway using VS keyboard shortcuts).

**Expected behavior**

Vim should handle those actions as per default.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `1.17.2`
- VSCode version: `1.52.0-insider` commit `92192baf760315ac47fb2caaf3ce6d0778962352`
- OS: macOS Catalina `Darwin x64 19.6.0`

**Additional context**

Seems to me that vim mode with default settings doesn’t handle those combinations anymore, apparently because `vim.use()` doesn’t behave as expected.

* Affected commands I had to fix so far in order to continue working
  * `extension.vim_ctrl+r` for redo (the first one I encountered)
  * `extension.vim_ctrl+v` for visual block selection
  * `extension.vim_ctrl+u` to scroll up
* Have Vim’s handling of ctrl-combinations enabled in the extension, as per default
* Am not specifying anything in handleKeys, so not delegating anything to VS Code
* Have exactly one custom vim binding, mapping `<space>w` to `workbench.action.files.save`, it’s been there for months with no issues

I just updated my Insider build after a week or more of postponing, so perhaps the issue was there for days by now. 

Coincidentally, I used remote development over SSH today for the first time, but I didn’t need to change mappings or Vim extension settings so don’t think it influenced anything (VSC had been restarted since then and this bug occurs during usual local development).

**Comment by JoshTRN** [comment]
The `ctrl` based mappings appear only to be broken in code-insiders.

I set `"vim.useCtrlKeys"` to `false`, nevertheless actions like `ctrl+v` pastes instead of going into visual-block mode.

**Comment by berknam** [comment]
This is an issue in vscode insiders. I created the following issue there https://github.com/microsoft/vscode/issues/111899#issue-757206365. You can go there and upvote it.

**Comment by berknam** [comment]
@J-Fields Can you check this out? Should we just add the fix I mentioned here https://github.com/microsoft/vscode/issues/111899#issuecomment-738878960 ourselves or wait for it to be fixed upstream?

**Comment by spott** [comment]
This appears to also be a problem with `<ctrl>-[` for escape, which is driving me nuts.

(I guess under the hood ctrl-[ is added as a shortcut for escape?)

**Comment by J-Fields** [comment]
Nice catch. Looks like it's been fixed upstream: https://github.com/microsoft/vscode/commit/97e4af4d208fac6c4c9b59dea541f8cfe49cb741

**Comment by berknam** [comment]
That was fast! Can we close this or is it better to wait until it is released so that others with the same issue can see this.?

**Comment by J-Fields** [comment]
Probably wait until it's released. Insiders is nightly, right?

**Comment by strogonoff** [comment]
> This is an issue in vscode insiders. I created the following issue there [microsoft/vscode#111899 (comment)](https://github.com/microsoft/vscode/issues/111899#issue-757206365). You can go there and upvote it.

Ah! I noticed the extra space and suspected it had possibly something to do with it, but ruled out the possibility of a bug of this nature. Seems obvious in hindsight it could be related to handling of conditionals.

**Comment by kianryan** [comment]
Following up on the VSCode Insiders Issue, but Ctrl-U, Ctrl-D appears to be behaving on current Insiders build, but Ctrl-W s is being caught by VSCode and closing the current document.
This was previously OK behaviour.

**Comment by JohnnyUrosevic** [comment]
After updating to 76436a4d, I can't type anything. I just get the "Activating extensions wheel" everytime I hit a key.

**Comment by berknam** [comment]
> 
> 
> After updating to 76436a4d, I can't type anything. I just get the "Activating extensions wheel" everytime I hit a key.

Have you tried reloading the window or restarting vscode? I've just installed that version and it runs just fine with vscodevim. If restarting doesn't work try checking the "Extension Host" output to see if some extension is throwing errors and look at the "Developer Tools" console as well.

**Comment by JohnnyUrosevic** [comment]
Yeah I've reloaded and restarted, disabling the vim extension lets me fine however

**Comment by berknam** [comment]
Issues in other extensions can make Vim unresponsive. Try loading vscode with just Vim enabled to see if you still have that problem. If you don't, try enabling other extensions one by one until you find the one that is creating the issue.

**Comment by JohnnyUrosevic** [comment]
A newer update to insiders seemed to fix it

**Comment by strogonoff** [comment]
I believe the issue originally reported has been addressed.
