### ISSUE TITLE
Copying and moving using command line

### ISSUE THREAD

**Issue by TryerGit** [VSCodeVim/Vim#5827]
**Describe the solution you'd like**
Vim allows usage of command `:.+3m.-3` or `:.+3t.-3` to either move or copy respectively the line that is +3 from current line to after -3 from current line. When I try this in VSCode with vscodevim 1.17.1 it says "Command :m is not yet implemented" and so on.

There is a previous request for this feature here more than 2 years ago. I am opening this thread instead of necroing that one. 

[**Previous thread 2472**](https://github.com/VSCodeVim/Vim/issues/2472)

Thank you.

**Comment by J-Fields** [comment]
This works with neovim currently. I've assigned myself to #2472 and will try to get to it soon.
