### ISSUE TITLE
vim_esc is gone

### ISSUE THREAD

**Issue by haf** [VSCodeVim/Vim#583]
Seems to have been replaced with `useCtrlKeys` from a release 21 days ago, but there's no mention of how to remap to use the new way. Currently: `{ "key": "ctrl+c", "command": "extension.vim_esc", "when": "editorTextFocus" },` but that doesn't work after the last update.

When I rely on a text editor, I don't like it deprecating key bindings without telling me; it's like breaking the public API with my brain.

**Comment by rebornix** [comment]
We renamed `esc` as `escape` so a workaround is use `extension.vim_escape` but seems our changes breaks people's original keybindings. @johnfn maybe a 0.5.1 to mitigate this kind of issues?

**Comment by johnfn** [comment]
You are completely right, I shouldn't have done this without clear notice. Let me push out a hotfix.

**Comment by johnfn** [comment]
Pushed out version 0.1.6 just now with esc as a synonym for escape.

I've learned a lesson here - I won't push out breaking changes without clear warning and an upgrade path.

**Comment by haf** [comment]
Thank you 👍
