### ISSUE TITLE
Key Remapping, how to access "up"/"down" arrow key

### ISSUE THREAD

**Issue by TryerGit** [VSCodeVim/Vim#5839]
Hello,

I would like to have the "up" arrow key in normal mode replicate `{` and "down" arrow key in normal mode replicate `}`.

This way, in normal mode, using these keys helps navigate the code faster.

I tried :

```
"vim.normalModeKeyBindings": [
        {//go to previous paragraph
            "before": ["up"],
            "after": ["{"]
        },
        {//go to next paragraph
            "before": ["down"],
            "after": ["}"]
        }
    ]
```

in `settings.json` but this does not work since it seems to expect typing of characters `u` and `p`. Is there any special way in which a key press of these arrow keys can be accessed?

Thanks.

**Comment by berknam** [comment]
Please post information about your system, vscode version and VSCodeVim version.

Your mappings should work fine. They do work for me. You could try changing to this:
```jsonc
"vim.normalModeKeyBindings": [
        {//go to previous paragraph
            "before": ["<up>"],
            "after": ["{"]
        },
        {//go to next paragraph
            "before": ["<down>"],
            "after": ["}"]
        }
    ]
```

But both versions should work the same, since on your version the "up"/"down" are automatically converted to "\<up\>"/"\<down\>".

**Comment by TryerGit** [comment]
@berknam 

Thanks. I was on 1.17.1

Your suggestion of "<up>" and "<down>" worked perfectly. Thanks!

**Comment by berknam** [comment]
@TryerGit Can you confirm that if you now change it back to "up" and "down" it stops working?! Because it should still work and if it doesn't we need to try to figure out why.

**Comment by TryerGit** [comment]
@berknam 

I just tried this on Ubuntu 20.10 VSCode 1.51.1 and VSCodeVim extension version 1.17.1 and it works just fine both with and without the < and >.

When I had raised this original ticket, I had earlier tried the case without < and > on Windows 10 WSL and it had not worked there. So, let me try the case with < and > on Windows WSL again and reconfirm that with and without < work. That will take me until tomorrow to verify. I will keep this thread updated with my results.

**Comment by TryerGit** [comment]
@berknam 

I am able to navigate fine today on Windows, Windows WSL as well as Ubuntu by simply having "up" and "down". So, I am a bit  puzzled myself as to why I was not able to do so yesterday. Perhaps there was a typo or some such in my `settings.json`.

So, everything is fine in this regard.

Thanks.
