### ISSUE TITLE
Double brackets shortcuts don't work (i.e., "[[" & "]]")

### ISSUE THREAD

**Issue by jonyen** [VSCodeVim/Vim#5857]
**Describe the bug**

On VS Code in Mac OS X, if I enter "[[" or "]]", I am unable to jump up/down in the file.

**To Reproduce**

1.  Go to any sufficiently large file.
2.  Hit "[[" or "]]"
3.  Should jump up to the top or to the bottom of the file.
4.  Nothing happens

**Expected behavior**
Should jump to the top or to the bottom of the file.

**Screenshots**

**Environment (please complete the following information):**
Running on Mac OS X 10.15.7, VS Code version 1.15.1, Vim plugin is 1.18.4

- Extension (VsCodeVim) version: 1.18.4
- VSCode version: 1.15.1
- OS: Mac OS X 10.15.7

**Additional context**

**Comment by J-Fields** [comment]
`[[` and `]]` shouldn't go to top/bottom of the file - that's what `gg` and `G` do. They go to the beginning of the previous/next sections, and are implemented in VSCodeVim (I think correctly, though I've never used these actions, so maybe not - feel free to provide a concrete example where they do something different than in Vim).

**Comment by jonyen** [comment]
Hi @J-Fields , thanks for your quick response. 

Here is a screen capture of the behavior that I'm seeing. In VSCode, I am trying to use the "[[" and "]]" commands, but it doesn't go anywhere. In Terminal, you can see that it works as expected. I am using the `webpack.config.js` file from VSCode Vim as an example.

![vim](https://user-images.githubusercontent.com/674440/101536663-4ca20280-3968-11eb-8a44-2733414686df.gif)
![vscode](https://user-images.githubusercontent.com/674440/101536676-51ff4d00-3968-11eb-8428-6d645f8cb313.gif)
