### ISSUE TITLE
1.18.0 After the update, the space bar is not input immediately by use korean IME

### ISSUE THREAD

**Issue by gyuha** [VSCodeVim/Vim#5865]
**Describe the bug**
1.18.0 After the update, the space bar is not input immediately by use korean IME

**To Reproduce**

1. input text
2. change korea text input 
3. Letter input
    
**Expected behavior**
Pressing the space bar when the letter input is not applied

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.51.1 (system setup)
- OS: Windows 10 (Windows_NT x64 10.0.19041)

**Comment by berknam** [comment]
@gyuha Do you have `<space>` set as your leader? Do you have any InputMode keybindings set that start with `<space>` or `<leader>`?

**Comment by gyuha** [comment]
![space](https://i.ibb.co/LpzQfhN/Code-8-Ars-P9iz-I9.png)

it's my all space keymaps.. 

and currently leader key is comma(,)
```
"vim.leader": ",",
```

**Comment by berknam** [comment]
Do you have any `"vim.insertModeKeyBindings"` or `"vim.insertModeKeyBindingsNonRecursive"` that use space? Are you using any input method switcher program?

Is it taking like 1 second until the space is inserted or is it never inserted?

**Comment by berknam** [comment]
I think I finally understood the issue. Previously when inserting text in korean it would start the composition state and pressing `<space>` would insert the pretended character and it would insert the space as well, while now it only inserts the character but doesn't insert the space.
