### ISSUE TITLE
Tag Deletes

### ISSUE THREAD

**Issue by allentong** [VSCodeVim/Vim#588]
I'm trying to delete text in a HTML tag by pushing `DIT`, but this feature is not available.  Will this feature be available in future milestones?

**Comment by rebornix** [comment]
This feature is highly ranked on my list and it's tracked on our [roadmap](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#text-objects-only-in-visual-mode-or-after-an-operator). I'll handle it ASAP.
