### ISSUE TITLE
Unable to install vscode.vim extension is not compatible with current version vscode 1.51.1

### ISSUE THREAD

**Issue by travisboss** [VSCodeVim/Vim#5883]
**Describe the bug**

**To Reproduce**

1.  Go to 'Extenions: Marketplace'
2.  Click on 'install vscodevim'
3.  See error - See attached screenshot
<img width="541" alt="Screen Shot 2020-12-13 at 6 47 42 PM" src="https://user-images.githubusercontent.com/16948721/102029410-fe2fa200-3d73-11eb-9fff-f316da623acb.png">

**Expected behavior**
To have vscodevim install.

**Screenshots**
See above

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version: 1.51.1
- OS: Linux (linuxserver.io container)
- Code-Server version: 3.7.4

**Additional context**
To add from above, I am using code-server inside of a linuxserver container, I am reaching this machine through a reverse proxy that I have setup.  This also seems to be the only extension so far that will not install, I tried installing the vsix file but it is just greyed out once installed, I also tried an older version with the same result from github.

**Comment by zeroxia** [comment]
I tried both `codercom/code-server` and `linuxserver/code-server` from official docker hub, just plain install in a local MacOS laptop, neither can install vscodevim extension, same error as posted above.
I'm not sure whether this is a problem on vscodevim or code-server?

**Comment by pojntfx** [comment]
This happens only with the recent version; if one downgrades to say 1.6.0 it works (like https://github.com/pojntfx/pojde/blob/master/setup.sh#L608)

**Comment by travisboss** [comment]
@pojntfx Thanks!  That fixed it for me, I tried an older version from vsvims github but same results, had to go back futher I guess.

**Comment by cottrell** [comment]
> This happens only with the recent version; if one downgrades to say 1.6.0 it works (like https://github.com/pojntfx/pojde/blob/master/setup.sh#L608)

downgrades vscode and not code server?

**Comment by berknam** [comment]
@pojntfx Can you try adding this to the 'settings.json' and see if it works with the latest version?
```jsonc
"remote.extensionKind": {
  "vscodevim.vim": ["workspace"]
},
```

I'm not sure if this is the problem but this was one of the changes from 1.16. I don't know much about code-server, so the above might not work. If it doesn't try this:

```jsonc
"remote.extensionKind": {
  "vscodevim.vim": ["web"]
},
"extensions.webWorker": true
```

**Comment by berknam** [comment]
@cottrell Can you confirm that versions 1.17.0 and 1.17.1 also work?

**Comment by cottrell** [comment]
@berknam there are no vix files at https://github.com/VSCodeVim/Vim/releases for those versions. 

Also, I'm not sure what is happening but it is not working now. Trying uninstall, restart, reinstall, restart, not working. There are no settings found in the extension to edit.

**Comment by berknam** [comment]
@cottrell If you try with the "web" version, you might need to add both settings, the "remote.extensionKind" and the "extensions.webWorker", like this:
```jsonc
"remote.extensionKind": {
  "vscodevim.vim": ["web"]
},
"extensions.webWorker": true
```

Have you tried version 1.18.5 with "workspace" kind?
```jsonc
"remote.extensionKind": {
  "vscodevim.vim": ["workspace"]
},
```

**Comment by travisboss** [comment]
> @berknam there are no vix files at https://github.com/VSCodeVim/Vim/releases for those versions.
> 
> And the
> 
> "remote.extensionKind": {
> "vscodevim.vim": ["workspace"]
> },
> 
> is necesarry to allow 1.18.0 to work at all too. Not sure abou the "web" version.

https://open-vsx.org/extension/vscodevim/vim/1.16.0

I got the older version from here which has been working fine.

**Comment by cottrell** [comment]
> @cottrell If you try with the "web" version, you might need to add both settings, the "remote.extensionKind" and the "extensions.webWorker", like this:
> 
> ```js
> "remote.extensionKind": {
>   "vscodevim.vim": ["web"]
> },
> "extensions.webWorker": true
> ```
> 
> Have you tried version 1.18.5 with "workspace" kind?
> 
> ```js
> "remote.extensionKind": {
>   "vscodevim.vim": ["workspace"]
> },
> ```

Yeah the current version 1.18.5 ... it will not let you install as it throws the version warning when you try.

**Comment by berknam** [comment]
> Yeah the current version 1.18.5 ... it will not let you install as it throws the version warning when you try.

But you have it working with 1.18.0?

**Comment by armaneshaghi** [comment]
I can reproduce this issue on 

```
code-server: v3.8.0
VS Code: v1.51.1
Commit: c4610f7829701aadb045d450013b84491c30580d
Date: 2020-12-18T20:25:37Z (2 wks ago)
```

**Comment by cottrell** [comment]
> > Yeah the current version 1.18.5 ... it will not let you install as it throws the version warning when you try.
> 
> But you have it working with 1.18.0?

Yes, 1.18.0

**Comment by ducalpha** [comment]
I also have the same problem and cannot install vscode.vim 1.8.5 on code-server 3.8.0.

How to reproduce:
```
RUN code-server --install-extension vscodevim.vim
```

**Comment by zeroxia** [comment]
I found installing neovim extension can be a good alternative since it is a "just works" approach. Just make sure to install the latest neovim binary.
Anyway, there almost always are some glitches for most of the extensions I use on code-server, like python, cpp-tools, cmake-tools, which all just be good with local Visual Studio code. I think I'll just give up the code-server way for now.

**Comment by dekiesel** [comment]
Surprised to see this closed. Is there a definitiv solution to this issue?

**Comment by cottrell** [comment]
> Surprised to see this closed. Is there a definitiv solution to this issue?

Yes, see what I did above. 

I suspect there is some fix coming in future versions.

**Comment by dekiesel** [comment]
@cottrell 

Thanks for the reply, I installed 1.18.0 as a vsix file and I added

```
"remote.extensionKind": {
  "vscodevim.vim": ["web"]
},
"extensions.webWorker": true

```
to my `settings.json` and restarted vscode (I am using the linuxserver container). Vscode says the extension is installed, but when I try to use it I get

`Error loading webview: Service Workers are not enabled in browser. Webviews will not work.`

I tried in Chrome and Firefox. Any ideas?

**Comment by J-Fields** [comment]
@dekiesel I googled the error and found [this](https://github.com/cdr/code-server/issues/2038) - are you connected via https?

**Comment by dekiesel** [comment]
@J-Fields 

Thanks, I activated https and I think it now complains that it is self signed. 

`Error loading webview: Could not register service workers: SecurityError: Failed to register a ServiceWorker for scope ('https://192.168.178.11:8400/webview/') with script ('https://192.168.178.11:8400/webview/service-worker.js'): An SSL certificate error occurred when fetching the script..`

**Comment by J-Fields** [comment]
@dekiesel I'm far from an expert on these matters and it's outside the scope of VSCodeVim. I'd check [this](https://github.com/cdr/code-server/blob/v3.8.0/doc/guide.md#ssh-forwarding) out as a place to start.
