### ISSUE TITLE
H/M/L key not working in visual block mode

### ISSUE THREAD

**Issue by kendling** [VSCodeVim/Vim#5890]
**Describe the bug**
H/M/L key not working in visual mode

**To Reproduce**

1.  Press C-V enter visual mode
2.  Try to press H/M/L to move the cursor.

**Expected behavior**
H/M/L command working.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.18.5
- VSCode version:1.52.0
- OS:WIN10/Debian

**Comment by johnfn** [comment]
They work fine for me. What behavior are you seeing?

**Comment by berknam** [comment]
It is just in VisualBlock mode that it doesn't work. It does work in Visual or VisualLine modes.

**Comment by kendling** [comment]
> It is just in VisualBlock mode that it doesn't work. It does work in Visual or VisualLine modes.

Yes, thanks for explain it .
