### ISSUE TITLE
Ctrl + ; or <C-;> doesn't seem to map correctly

### ISSUE THREAD

**Issue by kalvinpearce** [VSCodeVim/Vim#5899]
```json
"vim.insertModeKeyBindingsNonRecursive": [
  {
    "before": ["<C-;>"],
    "after": ["<Esc>", "A", ";", "<Esc>"]
  },
]
```

Using the above mapping I can't seem to get this mapping to run. Is <C-;> supported?

**Comment by sql-koala** [comment]
No, not directly, see  #5152

I think you are looking for a "smart semicolon", see #5179, bro ;-)

**Comment by kalvinpearce** [comment]
Sorry! I must have missed that one in my searches. Thanks for that!
Also your feature looks cool. Are you planning to make a PR for it?
