### ISSUE TITLE
Movement (hjkl) is added to jump list when Easymotion is enabled

### ISSUE THREAD

**Issue by mdentremont** [VSCodeVim/Vim#5921]
**Describe the bug**
- I noticed that ctrl+i/ctrl+o were jumping back through my cursor movements, looking through the issues, this was fixed a little while ago
- I tried toggling settings, and the issue goes away once "Enable the EasyMotion plugin for Vim" is disabled

Steps to reproduce/expected/actual are described here: https://github.com/VSCodeVim/Vim/issues/1933. I see a comment (& 3 other people upvoted) indicating that they are still experiencing the issues, it might be because they are running into this.

![image](https://user-images.githubusercontent.com/1106324/103007148-46d02380-4509-11eb-8a41-bb205f2d238f.png)

Might this be possibly related to: https://github.com/VSCodeVim/Vim/issues/5111 ?

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: Windows 10 (1909(

**Comment by berknam** [comment]
I can't reproduce that. I do have Easymotion enabled and ctrl+i/ctrl+o work as they should. I can move around with `hjkl` that ctrl+o still sends me to my previous jump. From what I can tell it shouldn't be possible for the `hjkl` keys to add a new jump to the jumplist!

Have you tried running `:jumps` after using any of the `hjkl` keys to see if a new jump is added? (you can first do a `:clearjumps` to clear all the previous jumps)

Do you have any remap for the `hjkl` keys? Or do you have any keybinding for those keys? Or are you by any chance using the .vimrc file with `"vim.vimrc.enable": true`, with a file that might have some remaps for those keys?

**Comment by mdentremont** [comment]
@berknam NVM - I'm full of it! I had assumed ctrl+- was an alias for ctrl+o but it totally is not. Thanks!
