### ISSUE TITLE
semicolon (;) does not repeat fF/tT actions

### ISSUE THREAD

**Issue by hk0i** [VSCodeVim/Vim#593]
### What did you do?

Take for example this line:

> a b a b a b a

Pressing <kbd>f</kbd> <kbd>b</kbd> should take us to the first `b` character, which it does. Then I press <kbd>;</kbd>

### What did you expect to happen?

Pressing <kbd>;</kbd> should repeat this same fF or tT action (<kbd>f</kbd> <kbd>b</kbd> in this case) when I keep pressing it until it is replaced by another different fF or tT command.

### What happened instead?

Nothing

### Technical details:

* VSCode Version: Version 1.4.0 (1.4.0)
* VsCodeVim Version: 0.1.6
* OS: OS X 10.11.6

**Comment by hk0i** [comment]
Not sure if it should be a separate ticket but I just noticed that <kbd>,</kbd> doesn't seem to be implemented either. Pressing <kbd>,</kbd> should go backwards (the opposite fF tT command that was entered) so in this case, it would bring us to the previous `b` as if <kbd>F</kbd> <kbd>b</kbd> were pressed.

**Comment by johnfn** [comment]
This is tracked by #410 - go ahead and thumbs that one up. However, `,` is not - you can open up a new issue for that one if you want. :)

**Comment by hk0i** [comment]
ah, apologies, I couldn't find that ticket, but it does seem to cover both actually. I tried to search for open issues but searching for ';' and "semicolon" but of course ';' won't match anything.

**Comment by johnfn** [comment]
No worries, I actually had difficulty finding the issue myself, and I *knew* it existed. :)
