### ISSUE TITLE
Cannot surround visual selection

### ISSUE THREAD

**Issue by babramczyk** [VSCodeVim/Vim#5942]
**Describe the bug**
When in visual select and trying to use vim-surround (e.g. `S[` to wrap in square brackets), nothing happens.

**To Reproduce**

1.  Put `some text` in a buffer
2. `vee` to select the text in visual mode
3. Type `S]`

**Expected behavior**
Should result in the text becoming `[some text]`

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: 10.15.6

**Comment by J-Fields** [comment]
Surround is enabled, right (`vim.surround=true`)? This works for me

**Comment by babramczyk** [comment]
Hmmm... yeah, I just tried to trivially reproduce it in a simple `.txt` file as well and it worked. Maybe some specific circumstances were causing this before.

I'll close for now, and reopen with a video if it happens again.

Thanks for taking a look, Jason.
