### ISSUE TITLE
[Question] Mac: Key Repeat and Delay Until Repeat 

### ISSUE THREAD

**Issue by briancodes** [VSCodeVim/Vim#5947]
From the README.md

> We also recommend increasing Key Repeat and Delay Until Repeat settings in System Preferences -> Keyboard

Do you mean increase the repeat/delay time to make them longer, or increase in terms of moving the sliders in the Settings to the right? Also, how does this affect the extension?

![macos-sierra-system-preferences-keyboard-adjust-brightness-turn-keyboard-backlight-off-selected](https://user-images.githubusercontent.com/15702512/103387100-e38e5480-4af9-11eb-857a-187989fecc84.png)

**Comment by jeffreyyjp** [comment]
@briancodes The left slider means that if you move it right, it will move faster when you type "hjkl" in vim mode. The right slider means that if you move it right, it will wait a shorter time before it handles repeating. You could adjust each one and use vscode vim mode to see their effects.

**Comment by red8888** [comment]
@jeffreyyjp @J-Fields 

This is great info! But I had to find it in a github issue. Could you guys add it to the docs proper? 

Literally just these few sentences added here would be helpful to users I think: https://github.com/VSCodeVim/Vim#mac

> @briancodes The left slider means that if you move it right, it will move faster when you type "hjkl" in vim mode. The right slider means that if you move it right, it will wait a shorter time before it handles repeating. You could adjust each one and use vscode vim mode to see their effects.
