### ISSUE TITLE
File is marked as dirty even when one undos all the way back to no changes

### ISSUE THREAD

**Issue by poolpog** [VSCodeVim/Vim#5949]
**Describe the bug**
If I open a file and start editing, and ESC back to command mode and then undo "u" all the way back to the point of zero changes, I still get a message when I try to quit the file, "E37 No write since last change"

This is tricky because it leads to situations where I'm not sure if there really are changes or not, and what they are.

**To Reproduce**

1.  Open a file
2.  Insert, append, or modify text
3.  ESC back to command mode
4.  press 'u' to undo the number of times required to go back to the original file state
5. do ':q' to quit
6. See error
7. (do ':q!' do force quit)

**Expected behavior**
At ':q' step I expect a clean file and the file quit action to complete without an error.

**Environment (please complete the following information):**
Ubuntu 20.04
VSCode 1.52.1
Vim plugin 1.18.5

**Comment by sql-koala** [comment]
Hi, this is a known issue (which is apparently hard to solve), see:
#3201
#1490 

what I do to work around that:
- have easy to type mappings for save, :q, :q!
- take a look at vscode commands: workbench.files.action.compareWithSaved, workbench.action.files.revert (this "resets" to state on disk an cleans the dirty flag).
