### ISSUE TITLE
Show an info panel suggesting useCtrlKeys if a user presses a key combo that useCtrlKeys would enable

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#596]
A lot of people are confused about useCtrlKeys - let's make it even more visible. :)

Only do this once per Vim session.

**Comment by jpoon** [comment]
Maybe we can follow VSVim's pattern here.

On initial install, VSVim detects keybinding conflicts with Visual Studio and prompts the user of which action they would like for the certain keys (ie. c-f).

**Comment by johnfn** [comment]
Ahh, that is clever. I wonder if there's a way to do that in vscode?

**Comment by xconverge** [comment]
I am not sure once per session is a good idea, what if someone specifically sets this config option to false, they then have to deal with an info panel every time they open their lightweight editor and try to use ctrl+c to copy something?

**Comment by johnfn** [comment]
Excellent point, @xconverge. Maybe once a week or so?

**Comment by xconverge** [comment]
How do we detect if a user pressed a key combo that would trigger this if we are not receiving ctrl keys?

**Comment by Chillee** [comment]
I think the right way to do discoverability like this, is by having it show up by default, and then having a setting that disables it.

**Comment by jpoon** [comment]
To keep the issue list to a sane number, closing this as we haven't seen a lot of traction
