### ISSUE TITLE
<C-n> and <C-p> cease to work on any menu items in Windows

### ISSUE THREAD

**Issue by pingshunhuangalex** [VSCodeVim/Vim#5994]
**Describe the bug**
`<C-n>` and `<C-p>` don't move the focus around items in any menus

**To Reproduce**

1.  Open command menu
2.  Use `<C-n>` or `<C-p>`
3.  The focus won't move

**Expected behavior**
`<C-n>` should go to the next item in the menu while `<C-p>` should go to the previous item

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version: 1.53 Insider
- OS: Windows (Mac seems to work just fine)

**Comment by pingshunhuangalex** [comment]
Just pin the issue to re-surface this...

By any chance anybody is able to reproduce this issue as I do? It's still there for me in the latest insider version. Thanks. cc @sql-koala @berknam @rebornix

**Comment by pingshunhuangalex** [comment]
Please can anybody help with this one? I can't be the only one having this issue...

**Comment by pingshunhuangalex** [comment]
Sorry, I'm running out of ways to surface this. Just try to ping any active contributors here @J-Fields

**Comment by waynewaynetsai** [comment]
I use mac and <C-n>/<C-p> works fine.

**Comment by pingshunhuangalex** [comment]
Yeah, @waderyan mac works fine for me too, just Windows. Thanks.

**Comment by northernocean** [comment]
I don't believe <C-n> or <C-p> are expected to affect items in menus on windows. For instance, on Windows `Ctrl + n` would open a new file. Can you explain or provide documentation on this expected behavior? Normally in windows the way to navigate menus with the keyboard is to use the alt key. For instance, `Alt + F + N` would open a new file. This method is usually called "hotkeys". But ordinarily it is more common to use another short cut key to trigger actions you want (as in the case, `Ctrl + n` will open a new file also).

**Comment by pingshunhuangalex** [comment]
Not sure if I understand what you said @northernocean, but the vim extension will override all ctrl behaviour unless you tell it not to. `<C-n>` and `<C-p>` are common navigation commands for the next/previous item. And they definitely worked before (not to mention the same setup works in Mac just not in Windows)

But anyways, I've already rebound everything to alt to avoid conflicting with ctrl, but still no luck.

**Comment by northernocean** [comment]
I guess I'm confused then. Do you have any documentation for using control keys to navigate menu items? I'm not familiar with this. As far as I know &lt;C-n> and &lt;C-p> are not used to navigate menu items on windows and this is not common.

**Comment by pingshunhuangalex** [comment]
We are talking about Vim here... This is VS Code Vim extension.
https://vim.rtorr.com/

**Comment by northernocean** [comment]
Hi pingshunhuangalex,
in the vim tips page you linked to, these are what &lt;C-n> and &lt;C-p> do:

`Ctrl + n - insert (auto-complete) next match before the cursor during insert mode`
`Ctrl + p - insert (auto-complete) previous match before the cursor during insert mode `

I don't understand what this has to do with menus. What are you trying to do with menus that involve these commands? Can you give a simple example of what you want to do?

**Comment by pingshunhuangalex** [comment]
So when you type, if an auto-complete menu is activated, you can use `<C-n>` and `<C-p>` to focus the next/previous menu item before insertion. VS Code Vim extends this behaviour to all menu items when any menus are in focus, i.e. `<C-n>` and `<C-p>` like up/down arrow key that move the focus among menu items.

**Comment by northernocean** [comment]
ah I see. My apologies. I was confused in your issue description by what you meant by "any menu" - I was thinking of menus like the file menu (which I guess technically does fit the description of any menu) and the steps to reproduce didn't make sense to me since I wasn't sure what you meant by opening a command menu. Yes, for autocomplete that makes sense now.

**Comment by pingshunhuangalex** [comment]
It shouldn't be limited to just the auto-complete menu. Literally any menu inside VS Code should work (not OS menus, just anything in the DOM)

**Comment by northernocean** [comment]
I'm not sure what other menus would be available while you are typing other than autocomplete menus. In any case, that specific case works fine for me in Windows. What version of the extension are you using?

**Comment by pingshunhuangalex** [comment]
The latest one.

Autocomplete menu works for me too, but other menus like command palette, quick find (go tos), etc. should also work and do work in Mac

**Comment by northernocean** [comment]
One question - when you say this "ceases to work" in windows, do you mean it used to work in Windows and now it doesn't? If so, what is the last version you know of where it did work?

**Comment by pingshunhuangalex** [comment]
> when you say this "ceases to work" in windows, do you mean it used to work in Windows and now it doesn't?
That's right

> If so, what is the last version you know of where it did work?
Can't remember. This ticket's been open for half a year, so my best bet is some versions around the end of last year...

**Comment by karizma** [comment]
Not sure if it ever existed. 1.53 was the vscode insiders version you gave, you didn't give the version of the extension, which is more imporatant.

For the time being, you can just add some keybindings to your keybindings.json:
```json
    {
        "key": "ctrl+n",
        "command": "workbench.action.quickOpenSelectNext",
        "when": "inQuickOpen"
    },
    {
        "key": "ctrl+p",
        "command": "workbench.action.quickOpenSelectPrevious",
        "when": "inQuickOpen"
    },
```

Not sure if this covers every menu, but for me it covered everything I wanted (command pallete, file finder).

**Comment by karizma** [comment]
Looking at all the keyboard shortcuts in vscode, and filtering with `ctrl+n`, I don't see vscodevim contributing anything except for when the editorText has focus which obv wouldn't apply to quickOpen. Can you go on your mac and do the same and send the results?

**Comment by pingshunhuangalex** [comment]
@karizma all Vim behaviour is controlled by `vim.use<C-n>` and `vim.use<C-p>`.

In their triggering condition you can see: `editorTextFocus && vim.active && vim.use<C-n> && !inDebugRepl || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == 'CommandlineInProgress' || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == 'SearchInProgressMode'` for both Win and Mac

Forcefully rebind `<C-n>` and `<C-p>` will make stop original vim chording from behaving correctly, so probably not the right solution (and don't forget Mac doesn't need any additional keybinding + Win used to behave the same until it's not). Thanks for the reply tho.

**Comment by pingshunhuangalex** [comment]
@karizma Thanks for giving me new ideas tho. Since `vim.use<C-n>` and `vim.use<C-p>` doesn't control quick menu action, I just tweak you new keybinding above to be a supplement to the existing vim binding behavior which solved my issue.

Not sure if Mac did something magic there or Win is missing some logic, but at least the end result works. Thanks again @karizma for the inspiration.

**Comment by pingshunhuangalex** [comment]
If other people are interested, here's my solution:
```
  {
    "key": "alt+n",
    "command": "extension.vim_ctrl+n",
    "when": "editorTextFocus && vim.active && vim.use<C-n> && !inDebugRepl || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == 'CommandlineInProgress' || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == 'SearchInProgressMode'"
  },
  {
    "key": "alt+n",
    "command": "workbench.action.quickOpenSelectNext",
    "when": "vim.active && vim.use<C-n> && !inDebugRepl && inQuickOpen"
  },
  {
    "key": "ctrl+n",
    "command": "-extension.vim_ctrl+n",
    "when": "editorTextFocus && vim.active && vim.use<C-n> && !inDebugRepl || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == 'CommandlineInProgress' || vim.active && vim.use<C-n> && !inDebugRepl && vim.mode == 'SearchInProgressMode'"
  },
  {
    "key": "alt+p",
    "command": "extension.vim_ctrl+p",
    "when": "suggestWidgetVisible && vim.active && vim.use<C-p> && !inDebugRepl || vim.active && vim.use<C-p> && !inDebugRepl && vim.mode == 'CommandlineInProgress' || vim.active && vim.use<C-p> && !inDebugRepl && vim.mode == 'SearchInProgressMode'"
  },
  {
    "key": "alt+p",
    "command": "workbench.action.quickOpenSelectPrevious",
    "when": "vim.active && vim.use<C-n> && !inDebugRepl && inQuickOpen"
  },
  {
    "key": "ctrl+p",
    "command": "-extension.vim_ctrl+p",
    "when": "suggestWidgetVisible && vim.active && vim.use<C-p> && !inDebugRepl || vim.active && vim.use<C-p> && !inDebugRepl && vim.mode == 'CommandlineInProgress' || vim.active && vim.use<C-p> && !inDebugRepl && vim.mode == 'SearchInProgressMode'"
  }
```

**Comment by karizma** [comment]
Yes I've seen the triggering/when condition.

I believe `vim.use<C-n>` and `vim.use<C-p>` are variables that determine if the vim extension should use that key combination, it doesn't actually execute anything.

The thing that does the actual executing would be the command `extension.vim_ctrl+n`.

The first condition is `editorTextFocus`, which means it will only fire when the text editor has focus. If you are in quick open (command pallete, etc) the text editor does not have focus, so `extension.vim_ctrl_n` will not execute. If mac has the same keybinding contribution, it also shouldn't work, which is confusing to me.

> Forcefully rebind <C-n> and <C-p> may stop the original vim chording from behaving correctly, 

I don't think it will, as you can see on my when condition, it's only activated on `inQuickOpen`. Vscode handles duplicate keybindings well.

**Comment by pingshunhuangalex** [comment]
All good, I think my solution above did exactly what you explained so we are on the same page.

Maybe Mac has `<C-n>` and `<C-p>` bound to menu selection regardless of Vim extension. Mac has lots of Linux nav binding in OS. Maybe it's just a happy accident. And maybe Win working before was just VS Code applying the same binding to Windows which got removed later on.

Anyway, too many assumptions, and I doubt if this ticket will attract more attention. Happy to close it since it does what I want now with some extra keybinding.
