### ISSUE TITLE
Cursor is changed weirdly whenever I am using operators like "c" or "d" in normal mode.

### ISSUE THREAD

**Issue by jkey-app** [VSCodeVim/Vim#6005]
Hello,

I'm not sure if this is a bug or a "normal" thing. 

**Describe the bug**
Cursor is changed weirdly whenever I'm using operators/actions like "c", or "d" in normal mode.

**Screenshots**
<img width="403" alt="Screen Shot 2021-01-16 at 22 14 40" src="https://user-images.githubusercontent.com/52785911/104815622-4432c680-5848-11eb-87bf-ad1d7808366f.png">

**Environment:**
- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.51.1
- OS: MacOS Catalina

**Comment by J-Fields** [comment]
This mimics neovim's behavior (maybe modern vim as well, I haven't checked) and is meant to show that you're in operator-pending mode
