### ISSUE TITLE
Vim Surround add (e.g. ysbB) is erroneous: ends in wrong place and adds spaces

### ISSUE THREAD

**Issue by corneliusroemer** [VSCodeVim/Vim#6006]
**Describe the bug**
Vim Surround add doesn't work how it should: the closing part ends up where the cursor started, not where it should end according to the surround logic. Additionally, there are spaces inserted, which shouldn't be the case.

**To Reproduce**
1. Cursor starts on `c` of `(abcdefg)`
2. Press: `ys({`

**Actual Behaviour**
`{ (ab }cdefg`

**Expected behavior**
`{(abcdefg)}`

**Screenshots**
![yanksurround](https://user-images.githubusercontent.com/25161793/104850081-3c792d80-58ed-11eb-9617-a4540fba353d.gif)

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.18.5
- VS Code Version: 1.52.1 (user setup)
- OS: Windows_NT x64 10.0.18363

**Comment by sql-koala** [comment]
Osi-Schicht 8 Fehler ;-)
Probier es mit: `ysa(}`
Für die Klammer musst du das textobject a( angeben. Der whitespace bei "{" ist ein feature, "}" macht ohne space.

Grüße

**Comment by corneliusroemer** [comment]
Oh dear, you're totally right...

For some reason I didn't find surround's proper documentation, it wasn't referenced in the Github readme so I opened an issue over there: https://github.com/tpope/vim-surround/issues/321#issue-788382948

Could you possibly explain what happens in the case of input of `ys(}`? Is it undefined behaviour according to surround.vim docs? The `(` without preceding `i` or `a` stops it from being a text object. So what is it? A text motion to the beginning of the paragraph, right?

With documentation at https://github.com/tpope/vim-surround/issues/321#issue-788382948 it makes sense. Thanks for your help!
