### ISSUE TITLE
navigating in command mode using the spacebar frequently drop editor into insert mode and inserts `. `

### ISSUE THREAD

**Issue by retorquere** [VSCodeVim/Vim#6012]
**Describe the bug**
I am accustomed to navigate to the right using the spacebar. This quite frequently drops me out of command mode, into insert mode, at which point it inserts `. `

**To Reproduce**
tap space twice in rapid succession (holding space does not do this)

**Expected behavior**
vsvim stays in command mode and just advances the cursor

**Screenshots**
![vsvim](https://user-images.githubusercontent.com/132108/104967329-6280f980-59e3-11eb-87c6-a65b500e2e2f.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: MacOS Big Sur

**Additional context**

**Comment by J-Fields** [comment]
Check [this](https://osxdaily.com/2019/03/27/disable-period-typing-shortcut-mac/) out, I'm pretty sure it's the issue.

**Comment by retorquere** [comment]
Superb! Man, what dimwit thought that *that* was a sensible global behavior?!
