### ISSUE TITLE
Fix for "_" underscore motions with counts

### ISSUE THREAD

**Issue by tagniam** [VSCodeVim/Vim#602]
EDIT: Whoops, apparently this feature is implemented, but instead of down, if you put a count in front of `_` it goes up instead (so `2_` goes two lines up instead of down). If that could be fixed that would be appreciated!

--

I just found out about this vim feature! `_` and `^` aren't the same thing, as `_` supports the use of a count.

From the vim docs:

`  _  <underscore>         [count] - 1 lines downward, on the first non-blank character |linewise|.`

So `2_` would bring you to the first non-blank character 2 lines down.

If that could be supported that would be great!

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.6
* OS: Windows 10 Pro

**Comment by johnfn** [comment]
This one should be an easy fix. :)

**Comment by rebornix** [comment]
Just realized this issue has been fixed.
