### ISSUE TITLE
Theme styles flicker when changing Modes

### ISSUE THREAD

**Issue by b1m1nd** [VSCodeVim/Vim#6027]
**Describe the bug**

_**Switching between any mode:**_ when using ` "semanticHighlighting": true ` in a theme or settings. textmate settings have to be set or the words flicker to the default textmate then to the semantic values, issue is not all semantic values are covered in textmate so no matter what a theme maker does this flicker will happen with certain scopes.

**To Reproduce**

1.  Enable semanticHighlighting in vsCode settings. (use default Dark+ theme)
2.  goto any file with scoped params, or strict types. (js,ts,ect)
3.  Go into insert, or in and out of visual mode.
4.  See error

**Expected behavior**
for the semantic values to be default then textmate? That way if no textmate no flicker, if it differed it still would but least we could control the situation better.

**Screenshots**
![textflicker](https://user-images.githubusercontent.com/55322556/105618448-80b07600-5da4-11eb-8911-7bda8d20b2bc.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: win10 windows_NT x64 10.0.18363

**Comment by J-Fields** [comment]
Do you have `vim.statusBarColorControl` enabled?

**Comment by b1m1nd** [comment]
Yup looks like that is culprit! With it turned back to false the semantics don't seem to flicker. You think there is a possible fix?

**Comment by J-Fields** [comment]
Unfortunately, probably not. Enabling that setting means we customize the theme each time the mode changes (which is super hacky, but there's currently no other way of achieving this effect). You could try filing an issue with vscode.
