### ISSUE TITLE
Best way to implement "vim-peekaboo" behavior?

### ISSUE THREAD

**Issue by kola-web** [VSCodeVim/Vim#6040]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shaheislam** [comment]
@kola-web Did you find a solution for this I am looking for similar, thanks

**Comment by kola-web** [comment]
No, I'm switching to neovim now

**Comment by Noitidart** [comment]
@shaheislam did you find a solution? I'm also looking for vim-peekaboo

**Comment by shaheislam** [comment]
> [@shaheislam](https://github.com/shaheislam) did you find a solution? I'm also looking for vim-peekaboo

No I am using Neovim now

**Comment by Noitidart** [comment]
Thanks for your fast reply! Are you using neovim inside vscode or just neovim pure?
