### ISSUE TITLE
cw on "1," deletes the comma as well as the 1

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#605]

**Comment by sectioneight** [comment]
I believe this is the same root problem as https://github.com/VSCodeVim/Vim/issues/563#issuecomment-238992281

**Comment by sectioneight** [comment]
@johnfn do you have an idea of why this happens? i was banging my head against #563 for a while trying to figure out how selections works (what is the start? what is the end? is a 1-character match a match with start==end)?

**Comment by johnfn** [comment]
My guess is we just don't handle the 0 case very well. If start = end, the selection is 1 character. I know it seems crazy- that's just the way Vim works.

**Comment by xconverge** [comment]
is this fixed now? I don't remember when/how but I can't reproduce it

**Comment by johnfn** [comment]
I don't even know who fixed this bug but someone definitely fixed it. So thanks to that guy. You're a cool dude.
