### ISSUE TITLE
Insertion after deletion when one of multiple cursors is at the end of a line

### ISSUE THREAD

**Issue by definelicht** [VSCodeVim/Vim#6053]
**Describe the bug**
When using multiple cursors (in the example using the `gb` functionality), and one cursor is at the end of the line, deleting and then entering insert mode will put the cursor before the last character instead of after the last character when entering insert mode. This mimics the behavior of entering insert mode at each cursor individually, but is probably not the desired behavior.

**To Reproduce**

1. Select multiple tokens, where at least one is at the end of a line.
2. Delete the words.
2. Enter insert mode.
3. Cursors at the end of a line will insert before the last character.

**Expected behavior**
Insert mode should start after the last character.

**Screenshots**
![space_gobbled](https://user-images.githubusercontent.com/2845320/105997048-6e3b8280-60ab-11eb-8803-7873b2001f2d.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: WSL2 on Windows 10 running Ubuntu 20.04

**Comment by J-Fields** [comment]
> This mimics the behavior of entering insert mode at each cursor individually, but is probably not the desired behavior

Why wouldn't this be the desired behavior? Seems you could use `c` rather than `di` to get what you're expecting.

**Comment by definelicht** [comment]
I did not know of `c`. I was using `vim-multiple-cursors`, which seems to have been deprecated in favor of `vim-visual-multi`, which has the same behavior as Visual Code Vim. I take this as a consensus that this is now the expected behavior :-)
It will take some time to rewire my brain to use `c` instead, but this solves my issue. Thanks!
