### ISSUE TITLE
Hitting <backspace> when typing in the search prompt changes the current file

### ISSUE THREAD

**Issue by p-himik** [VSCodeVim/Vim#6068]
**Describe the bug**
Hitting <backspace> when typing in the search prompt changes the current file

**To Reproduce**

1.  Open any file
2.  Hit `/` to open the search prompt
3.  Type some text there
4.  Hit `<backspace>`

**Expected behavior**
The last character in the search prompt is removed.

**Actual behavior**
The text in the open file is edited.

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.18.5
- VSCode version: 1.52.1
- OS: Ubuntu 20.04

**Additional context**
It's a fresh setup. I just started using VSCode and I don't recall changing any preferences at all.

**Comment by J-Fields** [comment]
Are you sure you didn't hit `<Shift-BS>`? That's a known issue, but I haven't seen this happen with just `<BS>`

**Comment by p-himik** [comment]
Ah, I figured out what's wrong. I'm using the Calva extension which apparently adds its own binding for `<BS>` that I didn't know about. And I had no idea VSCode allows extensions to specify conflicting bindings.
