### ISSUE TITLE
Long editor hang after deleting block of text in visual mode

### ISSUE THREAD

**Issue by cshei** [VSCodeVim/Vim#607]
### What did you do?

Tried to delete a block of text using visual mode, and experienced a ~30 second delay where the editor hung before finally getting back to normal mode.

Put the exact key strokes you pressed to reproduce the issue, if possible.

Place cursor on { on line 92
SHIFT-V
%
d

### What did you expect to happen?

WavWriter class should be deleted and normal mode should resume immediately.

### What happened instead?

Editor used 100% CPU for ~30 seconds and was unresponsive during that time.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.6
* OS: Linux
[sample.txt](https://github.com/VSCodeVim/Vim/files/417025/sample.txt)

**Comment by johnfn** [comment]
I am fixing this right now.

**Comment by johnfn** [comment]
Fixed. Thanks for the report. Going to release a new version after a little bit of testing, since this is a bad bug.

**Comment by cshei** [comment]
Wow, thanks for the quick turnaround every time I report a bug :)

**Comment by johnfn** [comment]
Hehe, you have a habit of reporting either 1) easy or 2) incredibly bad and must-be-fixed bugs. :)
