### ISSUE TITLE
`yy` moves cursor to beginner of the line

### ISSUE THREAD

**Issue by hunterSThompson** [VSCodeVim/Vim#609]
`yy` moves the cursor to the beginning of the line.

This isn't really a problem... it's just inconsistent with all other VIMs I've used, and a bit jarring.

Seeing this on windows 7, VS code version 1.4.0, and vsCodeVim version 0.1.7.

BTW, great work on this, it's come a long way!

**Comment by rebornix** [comment]
@hunterSThompson it has been fixed and you can see the change with our next release :)

**Comment by hunterSThompson** [comment]
Awesome, thanks!
