### ISSUE TITLE
`nnoremap`'ing `<S-J>` and `<S-K>` from .vimrc doesn't work

### ISSUE THREAD

**Issue by mieubrisse** [VSCodeVim/Vim#6110]
**Describe the bug**
I have the following lines in my .vimrc:
```
nnoremap <S-J> <C-F>zz
nnoremap <S-K> <C-B>zz
```
My .vimrc is getting successfully recognized and processed as the other mappings in the file are recognized. However, entering `J` removes the newline at the end of the current line, joining the line below with this one while `K` does nothing.

**To Reproduce**
1. Enable vimrc integration in the extension settings
2. Add the above remaps to the vimrc

**Expected behavior**
`J` goes a page forward and then centers the screen on the cursor (`zz` behaviour), while `K` goes a page back and center.

**Console Output**
On pressing `J`:
```
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=J.
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=J. mode=Normal. keybindings=normalModeKeyBindingsMap.
workbench.desktop.main.js:60 [Extension Host] Remapper: verbose: key=J. keySlice=J.
workbench.desktop.main.js:60 [Extension Host] Transformer: debug: Adding Transformation {"type":"replaceText","text":"    let service = DatastoreService::new( \"test-service-id\", \"1.2.3.4\", 4567","range":{"start":{"line":8,"character":0},"stop":{"line":9,"character":23}},"diff":{"line":0,"character":21,"type":0}}
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: Selections: Adding Selection Change to be Ignored! Hash: [8, 59; 8, 59], Selections: [8, 59], [8, 59]
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('J') took 24ms
workbench.desktop.main.js:60 [Extension Host] Extension Startup: debug: Selections: Ignoring selection: [8, 59; 8, 59], Count left: 0
```

On pressing `K`:
```
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handling key=K.
workbench.desktop.main.js:60 [Extension Host] Remapper: debug: trying to find matching remap. keys=K. mode=Normal. keybindings=normalModeKeyBindingsMap.
workbench.desktop.main.js:60 [Extension Host] Remapper: verbose: key=K. keySlice=K.
workbench.desktop.main.js:60 [Extension Host] ModeHandler: debug: handleKeyEvent('K') took 5ms
```

**Environment (please complete the following information):**
- Extension Name: `vim`
- Extension Version: `1.18.9`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.53.0`

**Comment by J-Fields** [comment]
Try the following:
```
nnoremap J <C-F>zz
nnoremap K <C-B>zz
```
Is `<S-f>` recognized by vim?

**Comment by mieubrisse** [comment]
Yep, I've been using this same config for the past ~6 years. I seem to remember having problems using `J` and `K` in the past which is why I went with `<S-.....>`, but will try them out now

**Comment by J-Fields** [comment]
Ah, you're right - I didn't realize that. `J`/`K` should work for now, but I'll try to fix that so `<S-_>` works as well.

**Comment by mieubrisse** [comment]
Looks like with your changes both Vim and Visual Studio are now picking up the binding! Not sure why VS Code wasn't picking up the <S-...> way though
