### ISSUE TITLE
plugin interferes with vscode commands

### ISSUE THREAD

**Issue by verajosemanuel** [VSCodeVim/Vim#6123]
**Describe the bug**
installed vscodeVim  and then the usual vscode keybindings for common procedures not involving writing code as open file, close file, and such are not working anymore. I know I can open a file using vim (:vsp file) but it MUST disable ALL keybindings?

**To Reproduce**
1.  edit a file the usual vim way
2.  close and save with :wq
3.  try to open another file using Ctrl + O
4.  nothing happens

**Expected behavior**
The open file dialog

**Environment (please complete the following information):**
Windows 10
vscode 1.53.1
vscodeVim 1.18.9

**Additional context**
same happens for many other common keybindings

**Comment by PrashantRaj18198** [comment]
This is the expected behaviour. Add the keys to `vim.handleKeys` or do `vim.useCtrlKeys = false` in  `settings.json`.

**Comment by verajosemanuel** [comment]
done and worked like a charm! thanks for a superb plugin!
