### ISSUE TITLE
Any way to type the emoji with vscode/vim?

### ISSUE THREAD

**Issue by xiekeyi98** [VSCodeVim/Vim#6129]
**Describe the bug**
I cannot type the emoji with the vscode vim enabled.
With bisect, I disabled the vscode/vim , and it works will.

**To Reproduce**

 
![image](https://user-images.githubusercontent.com/7782671/107746158-5709bf80-6d50-11eb-9c80-1f303c43bd37.png)

**Expected behavior**

Type the emoji to other places and paste in vscode, it works well,

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.18.9
- VSCode version:  1.53.1
- OS: Big sur 

**Additional context**

**Comment by athos** [comment]
Probably duplicate of #6046 ?

**Comment by xiekeyi98** [comment]
> Probably duplicate of #6046 ?

Sorry for the lack of an exhaustive search.
I think so, it may the same issue.

I will close this issue and track the #6046.
