### ISSUE TITLE
:wq doesn't work when there are changes (does nothing)

### ISSUE THREAD

**Issue by Mehuge** [VSCodeVim/Vim#613]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`:wq<CR>`

### What did you expect to happen?

`:wq<CR>` should perform a `:w` then a `:q`

If I `:w` first (to save changes) or if no changes have been made, then `:wq` does quit

### What happened instead?

nothing at all, changes not saved, editor window not closed

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Windows

**Comment by johnfn** [comment]
It works now! :)
