### ISSUE TITLE
Issue while search text in Russian

### ISSUE THREAD

**Issue by axelthepop** [VSCodeVim/Vim#6140]
Abnormal behave while searching Russian words in Russian text.

- I press the "/" key
- I enter a word in Russian
- I press "return" to start search
- VIM shows the found word
- VIM starts to behave awkwardly: some of the keys do not work, some keys behave differently 

To return normal behavior I have to restart VS Code(even "reload window" does not work)

P.S. When I search English words in English text - all good, works perfectly.

**Comment by J-Fields** [comment]
Can you provide me an example Russian word to use to repro?

**Comment by axelthepop** [comment]
Yes of course. Here are some words:

"Черной ночью черный кот прыгнул в черный дымоход"

**Comment by J-Fields** [comment]
Hmm, it seems to work fine for me. What exactly breaks when you search for that?

**Comment by axelthepop** [comment]
I understood what the problem is.
VIM does not respond, if keyboard layout is set to Russian(in Normal mode or Visual mode).

If the "/" key is pressed I can search for words in Russian. But, if I go after that in Visual or Normal mode, and if keyboard layout still set to Russian, VIM extension does not respond.

- I can use Russian in Insert mode, I can search in Russian.
- VIM extension does not respond in Normal mode or Visual mode while keyboard layout is set to Russian.
