### ISSUE TITLE
Shortcut "CTRL+N"(create a new file) does not work

### ISSUE THREAD

**Issue by axelthepop** [VSCodeVim/Vim#6142]
Shortcut "CTRL+N"(create a new file) does not work

**Comment by HGARgG-0710** [comment]
What operating system are you on? I don't know 'bout any others, but on Windows you can try adding this to settings.json. 
	
    "vim.handleKeys": {
        "<C-n>": false
    }
    
   This worked for me, at least. :/

**Comment by axelthepop** [comment]
My gear is:
Windows 10: Version 20H2 (OS Build 19042.804)
VS Code: Version: 1.53.2

P.S. If VIM extension is disabled, shortcut "CTRL+N" works as it should.
P.S. Thanks for advice.

**Comment by HGARgG-0710** [comment]
no problem
