### ISSUE TITLE
Scrolling too fast?

### ISSUE THREAD

**Issue by ThomsonTan** [VSCodeVim/Vim#6144]
**Describe the bug**
I have `"editor.smoothScrolling": true,` to enable smooth scrolling in VSCode, but the scrolling like `Ctrl+d` and `Ctrl+u` still looks too fast to me, need to config to reduce the scrolling speed.

**To Reproduce**

1.  Enable `"editor.smoothScrolling": true`
2.  Observe the scrolling speed of `Ctrl+d`.
3.  Observe the scrolling speed.

**Expected behavior**
Smooth scrolling like `window.scrollTo({..., behavior='smooth'}) in browser.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version: 1.53.1
- OS: Windows 20H2

**Additional context**

**Comment by J-Fields** [comment]
Do you mean `<C-d>` moves down too many lines, or the view literally scrolls faster than you'd like?

**Comment by ThomsonTan** [comment]
> Do you mean `<C-d>` moves down too many lines, or the view literally scrolls faster than you'd like?

Not moves down too many lines, I mean it scroll speed. It looks to me like instant scrolling to the target line without animation. It will be great to make the scrolling the same as `window.scrollTo({..., behavior='smooth'})` or make the scrolling speed configurable.

**Comment by J-Fields** [comment]
We just call VSCode's `editorScroll` command; as far as I can tell, there's no ability on our side to determine how fast the scrolling happens. I'd suggest opening a ticket in the vscode repo and maybe linking to this one.

**Comment by vcfvct** [comment]
I guess @ThomsonTan meaning more like the `smooth` scroll experience with ctrl-d/u/b/f like what is in Intellij/Webstorm.

**Comment by vcfvct** [comment]
actually i just realize there is an `editor: smooth scrolling` option in vsocde that you can enable to get sort of similar behavior as jetbrain.

**Comment by chennnnnnnnsy** [comment]
try the "smoothscroll" plugin. be helpful to you. @ThomsonTan @vcfvct
