### ISSUE TITLE
Bring this extension to Azure Data Studio

### ISSUE THREAD

**Issue by spencer741** [VSCodeVim/Vim#6149]
As there are no current Vim solutions for Azure Data Studio (and ADS runs on a VSCode shell), this might be something worthy to look into. I spend a lot of time in ADS / SSMS. A VIM extension for ADS would make my life... faster :)

**Comment by sql-koala** [comment]
you can install vscodevim in ADS, I am using it there, too.
Just DL the vsix and install it using "install from vsix..."

**Comment by spencer741** [comment]
@sql-koala Wow, this is awesome! I wasn't aware that there was this level of compatibility. I guess only for certain extensions.... obviously all vsix files won't work like this.. but thanks for the info! 

It looks like they haven't integrated with Visual Studio Marketplace yet... just keeping track of all extensions in one json file [here](https://github.com/Microsoft/azuredatastudio/blob/release/extensions/extensionsGallery.json) ... when they do migrate, I might reopen this issue so we can get this in the ADS extension store, but the vsix install works fine for now.

**Comment by spencer741** [comment]
I will say after a few hours of use in ADS, I occasionally run into an issue where I experience some weird behavior with my key mappings getting all messed up. (none of the normal vim navigation works... performs seemingly random behavior). This is the first I have experienced this type of thing. Even when I uninstall from ADS, reload, then reinstall the vsix, the behavior persists. I have to either open up VSCode, uninstall, then reload, then reinstall (which fixes the issue in VSCode **_and_** ADS) or reboot my computer to get the behavior to stop... still experimenting on what triggers this... but just to note for the future.

**Comment by colossatr0n** [comment]
For anyone coming across this, the `.vsix` is the downloadable from the [Releases page](https://github.com/VSCodeVim/Vim/releases). You may run into an error that says something similar to:

```sh
Unable to install extension 'vscodevim.vim' as it is not compatible with the current VS Code engine version '1.56.0'.
```

To fix this, try downloading an earlier release from the release page and just keep trying until you come across one that works.

**Comment by brentbundang** [comment]
Thank you @colossatr0n I was wondering why the latest release wasn't working.

**Comment by kevin-friedheim** [comment]
thanks @colossatr0n - helped me out!

As of the time of this writing, for osx `11.6` and azure data studio `v1.32.0`
The version of vscodevim that worked is `vim-1.21.5`
HTHs someone.

**Comment by tcc-sejohnson** [comment]
Thanks @kevin-friedheim and @colossatr0n!

On fully-updated Windows 10 with latest Data Explorer, the newest release (1.21.10) works.

**Comment by dhartjes** [comment]
On fully-updated Windows 10 with latest Data Explorer, release 1.22.1 works, the latest (1.22.2) does not.

**Comment by AucaCoyan** [comment]
I tried the [v1.21.10](https://github.com/VSCodeVim/Vim/releases/tag/v1.21.10) and it works on Azure Data Studio 1.19.1 (user setup) 🎉

**Comment by cantpitch** [comment]
Should add a note to the section about macOS key-repeating that you can run:

`defaults write com.azuredatastudio.oss ApplePressAndHoldEnabled -bool false`

**Comment by JohnBobo** [comment]
I tried [v1.24.3](https://github.com/VSCodeVim/Vim/releases/tag/v1.24.3) on Windows 11 and it worked.
