### ISSUE TITLE
Left over 'j' when using '.' to repeat a command

### ISSUE THREAD

**Issue by jcjolley** [VSCodeVim/Vim#617]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
![trailingjbug](https://cloud.githubusercontent.com/assets/2086176/17709348/f9e92010-63a5-11e6-9de7-277199a5f217.gif)

Put the exact keys you pressed, if relevant.
/nerd
<enter>
cw
need
jk //this is my custom key config for <ESC>
j
b
.
j
b
.
### What did you expect to happen?
'nerd' to be replaced with 'need' 3 times.
### What happened instead?
'nerd' was replaced with 'need' once and with 'needj' twice.
### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7 
* OS: Windows 10
* VSCode Settings file:
```javascript
{
    "vim.insertModeKeyBindings": [
        {
            "before": [ "j", "k"],
            "after": ["<escape>"]
        }
    ],
    "editor.renderIndentGuides": true
    
}
```

**Comment by johnfn** [comment]
Ahh, bummer. I was *positive* I fixed this class of issues in 0.1.7.

**Comment by jcjolley** [comment]
@johnfn, Sorry to be the bearer of bad news.  I was excited when I saw the change log for 0.1.7

**Comment by Ravencrow** [comment]
By the way, I'm having the same exact problem in 0.2.0. The only difference is that my "escape" key strokes are not "j,k" but "f,j".

Note: thanks for this incredible extension!

**Comment by rebornix** [comment]
Fixed already in master.
