### ISSUE TITLE
`<C-t>` in insert mode selects characters

### ISSUE THREAD

**Issue by YangChenyuan** [VSCodeVim/Vim#6190]
`S`+text+`CTRL-T` will select the text partially, which has different behaviour with **Vim** that it do not selet any char.

The document selection may have bugs when doing line replacement.

**Comment by YangChenyuan** [comment]
`CTRL-T` insert an indent and select characters whose length is one tab at the end of the line. It should not select the characters.

**Comment by J-Fields** [comment]
I can't reproduce; can you provide an example please?

**Comment by YangChenyuan** [comment]
![Peek 2021-02-26 13-00](https://user-images.githubusercontent.com/55501188/109257314-de683000-7832-11eb-8cbc-0c861c800643.gif)
Here is key sequence: `i h e l l o <C-t> space`

**Comment by J-Fields** [comment]
Thanks, that's very helpful, I can repro now.
