### ISSUE TITLE
`CTRL-U` should delete the line in insert mode if this line does not have any character.

### ISSUE THREAD

**Issue by YangChenyuan** [VSCodeVim/Vim#6196]
`CTRL-U` has different behaviour in insert mode. When the line has no characters, it will delete the line in Vim. But it does nothing in VSCodeVim.

**Comment by J-Fields** [comment]
Yep, good catch. Note that the behavior here depends on the `backspace` setting.

**Comment by YangChenyuan** [comment]
> Yep, good catch. Note that the behavior here depends on the `backspace` setting.

Could you check the issue #6190 ? I think `CTRL-T` in insert mode has some problem, it should not select any text.

**Comment by J-Fields** [comment]
Found it 🙂

Duplicate of #6429

**Comment by YangChenyuan** [comment]
> Found it 🙂
> 
> Duplicate of #6429

I forgot I have post it before.🤣
