### ISSUE TITLE
Escape at the beginning of line should not move cursor to previous line

### ISSUE THREAD

**Issue by joaomoreno** [VSCodeVim/Vim#62]
Go to the first column of any line other than the first. Go into insert mode, then escape. The cursor will move to the previous line. It should stay within that line.

**Comment by kimitake** [comment]
embedded in 4fa94e1f475c4fcb5d8c05b96fdca44ebe5ecd49
fixed in dd1766d15896a386a976c07de80d77cfbf09475c

**Comment by jpoon** [comment]
Fixed in `master` and will be included in next release.
