### ISSUE TITLE
Something wrong with the vim mode when using code autocompletion 

### ISSUE THREAD

**Issue by chamhaw** [VSCodeVim/Vim#620]
------

When I wrote python or javascript, autocompletion was used frequently.Unfortunately,after generating a template code block such as a for loop in insert mode,then the current mode automatically changed to visual mode so that the parameter placeholders  couldn't be replaced by my local variable name easily.
-----

### What did you do?

I tried to find out the configuration item in settings.json but nothing relevant was found.

### What did you expect to happen?

I hope that the vim plugin could keep in insert mode after generating a code block template rather than change to visual mode.

### What happened instead?
None

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: OS X 10.11 & CentOS 7.2 1511

**Comment by rebornix** [comment]
@johnfn I suppose selection reason can cover this ?

**Comment by johnfn** [comment]
@rebornix yes, precisely.

**Comment by chamhaw** [comment]
@rebornix @johnfn 
I want to know weather the problem could be resolved by configuring items in settings.json
or just waiting for a new version of the plugin?
Thanks a lot.

**Comment by johnfn** [comment]
@chamhaw Unfortunately it sounds to me like we will have to fix this in a new version of the plugin.

**Comment by rebornix** [comment]
This issue no longer exists in latest release. We are doing Mode correct right now.

**Comment by chamhaw** [comment]
@rebornix I have tested and it works well to me.Thank you very much!
