### ISSUE TITLE
Can't rename file or folder with VSCodeVim enabled

### ISSUE THREAD

**Issue by bogem** [VSCodeVim/Vim#6201]
**Describe the bug**
I can't rename file or folder when VSCodeVim enabled. An input for rename doesn't appear and file explorer looks grayed out. If VSCodeVim is disabled, then the problem doesn't appear.

**To Reproduce**

1. Go to File Explorer
2. Right click on a file or folder
3. Click 'Rename'

**Expected behavior**
Input for rename appears that allows to enter new name of file or folder

**Screencast**

https://user-images.githubusercontent.com/13235519/109129313-cb7d2f00-7750-11eb-9b0f-68cbfc782498.mp4

**Environment**

- Extension Name: `vim`
- Extension Version: `1.18.9`
- OS Version: `Darwin x64 20.3.0`
- VSCode version: `1.53.2`

**Comment by J-Fields** [comment]
Can you reproduce this on VSCode 1.54.0?

**Comment by bogem** [comment]
Not anymore! Thanks for your answer :)
And thank you for maintaining VSCodeVim. It's crucial extension for my daily work!
