### ISSUE TITLE
k. command '(' not found

### ISSUE THREAD

**Issue by interfacekun** [VSCodeVim/Vim#6209]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.18.9

<details><summary>Stack trace</summary>

```
Error: command '(' not found
    at C._tryExecuteCommand (file:///E:/ide/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1534:3360)
    at file:///E:/ide/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1534:3241
```

</details>

**Comment by J-Fields** [comment]
Are you trying to remap a key and using `command: '('`? If so, that should be `after: '('`

**Comment by J-Fields** [comment]
Assuming this was the case; let me know if I'm wrong.
