### ISSUE TITLE
Search and replace in visual selection on part of line is not limited to part of line.

### ISSUE THREAD

**Issue by dluke** [VSCodeVim/Vim#6214]
**To Reproduce**
Input example text `up up`.
Visually select the second `up`.
Input command `:'<,'>s/up/down/g` (the `':<,'>` part is done for you).
New text is `down down`, should be `up down`.

**Comment by J-Fields** [comment]
Just tested in neovim, and it works the same. As far as I can tell, `:s` always operates on complete lines, even in regular visual mode. Can you confirm?

**Comment by dluke** [comment]
Seems you are right and I was mistakenly remembering that it working another way. 

Even worse I can't even find a sensible vim command to do the operation I described. Very silly.
