### ISSUE TITLE
[feature request] :vsplit (and :split? maybe)

### ISSUE THREAD

**Issue by jaredly** [VSCodeVim/Vim#622]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Looks like VSCode supports vertical splitting at least, so it would be awesome for `:vsplit` to be wired up to that. Does VSCode even support horizontal splitting?

**Comment by johnfn** [comment]
VSCode does not support horizontal splitting as far as I know, but :vsplit should be an easy and useful addition. :)

**Comment by rebornix** [comment]
@jaredly Horizontal splitting of VS Code is under discussion and we'll see which release we will put it into later. About vertical splitting, we already have `:vsp` in VSCodeVim latest version, apparently I forgot the add the `vsplit` synonym :( But you should see it in our next update.

**Comment by trev-dev** [comment]
"Bring out your dead!" 
VSCode has a command named workbench.action.splitEditorOrthogonal which does horizontal splits.
