### ISSUE TITLE
Support alternative shortcut keys to change from INSERT to NORMAL mode

### ISSUE THREAD

**Issue by Bhumbra** [VSCodeVim/Vim#6288]
**Problem**: For regular Vim users, regularly reaching for the `Escape` key to enter NORMAL mode can be very straining on the left hand and lead to injury.

**Proposed solution**: [Native Vim already supports existing alternatives](https://vim.fandom.com/wiki/Avoid_the_escape_key) (e.g. alt+L or [my preferred] alt-space) to achieve exactly the same action (although alt+L is subtly different) eschewing reliance on `Escape`. Unfortunately these alternatives are not yet supported in VSCodeVim. The feature request is therefore to support these alternatives.

**Solution details**: I can replicate the `Escape` 'contributes' within [package.json](https://github.com/VSCodeVim/Vim/blob/master/package.json) to the command 'alt+space' and this achieves the desired outcome.

**Solution alternatives**: I tried to push a branch with this small change to open a PR but I get a 403 URL (Permission denied) error.

**Additional context**: N/A

**Comment by J-Fields** [comment]
I think this behavior is dependent on specific terminal behavior, so I don't think we want to emulate that, but you can certainly remap <A-Space> to <Esc> once we support alt keymaps (#2713)

**Comment by eggbean** [comment]
@J-Fields [This post](https://github.com/VSCodeVim/Vim/issues/5754) best describes the problem I have with not being able to use Alt+<command key> to exit Insert Mode while executing a Normal Mode command at the same time. Is this possible now?

**Comment by Bhumbra** [comment]
> 
> 
> @J-Fields [This post](https://github.com/VSCodeVim/Vim/issues/5754) best describes the problem I have with not being able to use Alt+ to exit Insert Mode while executing a Normal Mode command at the same time. Is this possible now?

Not to my knowledge. According to @J-Fields, this capability is "dependent on specific terminal behaviour". I disagree since this behaviour is consistent within Vim across every single GNU/Linux terminal I've ever used (on Xorg, sometimes KDE-plasma Alt-space gets in the way but this KDE shortcut can be remapped to restore this normal Vim behaviour in terminal). 

Unfortunately for now, that means you have no choice but to use Esc, so I do not use VSCode.

**Comment by eggbean** [comment]
The Esc key is far too awkward to reach and I cannot understand why people would ever use it when you can just use the Alt/Meta key. For now I am using Ctrl-C (or Ctrl-[ which sends the same escape sequence) to exit, but it's still an extra step more than what I am used to.

**Comment by Bhumbra** [comment]
Thanks @eggbean - I didn't try Ctrl-C or Ctrl-[ so it's good to know. Speaking from personal experience, I would suggest avoiding using the `Escape` but it can lead to injury.
