### ISSUE TITLE
Undo behavior with {}[]()<> does not act exactly as it should

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#633]
@johnfn took a quick stab at this issue in 7ac106d but the behavior does not fully match the way vim works yet.

When writing something where you open and close the brackets then fill in the interior, a new undo point should be created.

ex:
_if(true){
}_

then filling in 

if(true){
    _int i = 0;_
}

an undo point is created in the first step during insert mode, so pressing u once will get back to the first step, and pressing u again will clear it all.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: master as of 7ac106d8708a1ad9918102abf0e59dbb0609cb4b
* OS: OSX

**Comment by xconverge** [comment]
Also, if I write something like:

0
0

then move the cursor to the first 0, and use ctrl+a to increment it, then move the cursor to the 2nd 0 and use ctrl+a to increment it. Pressing u Undoes both, it should only undo one

There is still something funky about when new undo points are created

**Comment by johnfn** [comment]
Ah, that's because ctrl-a is treated as a movement, not a command. Easy fix for anyone to pick up. :)
