### ISSUE TITLE
VSCode Vim not treating folds like a line

### ISSUE THREAD

**Issue by fauxmath** [VSCodeVim/Vim#6338]
**Describe the bug**
Suppose the following code
```
im_a_folded_line{
	i_am_inside;
}
```
folds to
```
im_a_folded_line{...
```
If I use `dd` on the folded line, it should delete the whole block, and not just its first line.

**To Reproduce**

1.  Write a foldable block of code
2. Fold it
3. Put cursor in the folded line
4. Use any of the following commands: `o`,`dd`,`yy`.

**Expected behavior**
`o` should insert a line below the code block.
`dd` should delete the whole code block.
`yy` should copy the whole code block.

But instead each of the commands treats the folded line as a line.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:  `1.19.1`
- VSCode version: `1.54.3`
- OS: Windows 10 (19042.867)

**Additional context**
Vim: Foldfix is enabled

**Comment by J-Fields** [comment]
Yeah unfortunately VSCode doesn't give us any information about where folds are, so we can't handle this properly yet.

**Comment by punkmath** [comment]
How does the extension allow us to treat the folded code while navigating then ? i.e. functionality given by enabling `Foldfix`.
