### ISSUE TITLE
How does <nowait> in .vimrc work?

### ISSUE THREAD

**Issue by hilaolu** [VSCodeVim/Vim#6347]
I am trying to map `Z` to `E` in `settings.json`. But when I type `Z` VSCodeVim is waiting for next input and blocked. I had tried many ways but none worked. So I tried use `nmap <nowait> Z E` and it works. I want to know is there a wait to use `<nowait>` in `settings.json`

**Comment by J-Fields** [comment]
See `:help <nowait>`
