### ISSUE TITLE
Failed to handle key=<Esc>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by tayglobal** [VSCodeVim/Vim#6354]
**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.19.0<details><summary>Stack trace</summary>```Error: Command with id 'closeDirtyDiff' is not registered.    at e.<anonymous> (https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:160:548679)    at https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:160:546656    at Object.next (https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:160:546761)    at https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:160:545674    at new Promise (<anonymous>)    at r (https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:160:545411)    at e.$executeCommand (https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:160:548552)    at e.doInvokeHandler (https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:19:773600)    at e.invokeHandler (https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:19:773333)    at e.receiveRequest (https://amethyst-cat-xne8k1vi.ws-eu03.gitpod.io/bundle.js:19:772625)```</details>

**Comment by J-Fields** [comment]
Will be fixed in upcoming version
