### ISSUE TITLE
Failed to handle key=<Esc>. Command with id 'closeDirtyDiff' is not registered.

### ISSUE THREAD

**Issue by aced0** [VSCodeVim/Vim#6359]
I'm using your extension inside a Gitpod with a Theia IDE. This error message appears if I hit <ESC> multiple times. 

**To Reproduce**Steps to reproduce the behavior:1.  Go to '...'2.  Click on '....'3.  Scroll down to '....'4.  See error**VSCodeVim version**: 1.19.0<details><summary>Stack trace</summary>```Error: Command with id 'closeDirtyDiff' is not registered.    at e.<anonymous> (https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:160:548679)    at https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:160:546656    at Object.next (https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:160:546761)    at https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:160:545674    at new Promise (<anonymous>)    at r (https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:160:545411)    at e.$executeCommand (https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:160:548552)    at e.doInvokeHandler (https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:19:773600)    at e.invokeHandler (https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:19:773333)    at e.receiveRequest (https://blobserve.ws-eu03.gitpod.io/eu.gcr.io/gitpod-dev/theia-io-ide:hotfix-2021-03-18.3/__files__/bundle.js:19:772625)```</details>

**Comment by aced0** [comment]
Sry for spam, saw the open/closed issues only afterwards.

**Comment by J-Fields** [comment]
No worries, will have a new release out this weekend
