### ISSUE TITLE
Visual mode + <C-n>/<C-p>/<C-f>/<C-b> doesn't work as expected

### ISSUE THREAD

**Issue by artagnon** [VSCodeVim/Vim#6363]
In visual mode, hitting either of the four default macOS keys for moving the cursor creates a secondary cursor, without marking lines/blocks visual. When exiting from Visual mode, the secondary cursor disappears, and we're back to the original position.

**To Reproduce**

I have `vim.useCtrlKeys` set to `false`.

**Expected behavior**

It should work exactly like the arrow keys.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.19.2
- VSCode version: 1.55.0-insider
- OS: macOS Big Sur

**Comment by J-Fields** [comment]
`<C-p>` and `<C-n>` do seem to move the cursor left/right in Vim, but I can't replicate for `<C-f>` and `<C-b>` (they work as in normal mode). Are you sure this isn't the result of your configuration?

**Comment by artagnon** [comment]
<kbd>C-p</kbd> and <kbd>C-n</kbd> are supposed to move the cursor down/up, _while_ selecting text, in visual mode, exactly like the way <kbd>k</kbd>/<kbd>j</kbd> or <kbd>down</kbd>/<kbd>up</kbd> work. <kbd>C-f</kbd> and <kbd>C-f</kbd> are supposed to work similarly in the right/left direction while selecting text in visual mode. The issue I'm having is that they create a secondary cursor that moves, but doesn't select any text; then, when I hit <kbd>Esc</kbd>, I'm returned to the primary cursor. These are macOS-specified keybindings, and work across all text fields in all applications, and requires no special configuration in vscode.

**Comment by sql-koala** [comment]
It should be easy to have the expected result with a few config settings:
Set vim.useCtrlKeys to true, then

```
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-n>"],
            "after": ["<down>"]
        },
]
```
and so on...

About that:
> These are macOS-specified keybindings, and work across all text fields in all applications, and requires no special configuration in vscode.

Well, no ;-) we have to do a lot to handle selection changes from "non vscode keybindings".

**Comment by artagnon** [comment]
@sql-koala Thanks, it does indeed work. Can you help review #6373?

**Comment by J-Fields** [comment]
Just to clarify, you'd only expect `<C-f>` and `<C-b>` to work on macOS, right?

`<C-p>` and `<C-n>` DO move the cursor in visual mode in nvim (though that seems to be undocumented), so we should probably support that.

**Comment by artagnon** [comment]
I have `vim.useCtrlKeys` set to `false`, so no, <kbd>C-p</kbd> and <kbd>C-n</kbd> don't work as expected in Visual mode.

**Comment by artagnon** [comment]
Sorry, I misread your comment. I *think* they're vscode default keybindings as well, across all OSes.
