### ISSUE TITLE
Failed to handle key=E. command 'g' not found

### ISSUE THREAD

**Issue by jiujiaonuannan** [VSCodeVim/Vim#6368]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.19.3

<details><summary>Stack trace</summary>

```
Error: command 'g' not found
    at C._tryExecuteCommand (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1654:3360)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1654:3241
```

</details>

**Comment by J-Fields** [comment]
Please post your settings; I assume you have something mapped via `command: 'g'` when it should be `after: 'g'`

**Comment by jiujiaonuannan** [comment]
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["<leader>", "d"],
      "after": ["d", "d"]
    },
    {
      "before": ["<C-n>"],
      "commands": [":nohl"]
    },
    {
      "before": ["H"],
      "commands": ["^"]
    },
    {
      "before": ["L"],
      "commands": ["$"]
    },
    {
      "before": ["E"],
      "commands": ["g", "T"]
    },
    {
      "before": ["R"],
      "commands": ["g", "t"]
    }
  ]

this is my config, can have some ideas?  if not enough, I will push full configuration information

**Comment by J-Fields** [comment]
Right, everywhere you have `"commands": ...`, use `"after": ...`
