### ISSUE TITLE
undo/redo do not play well with vscode's undo/redo

### ISSUE THREAD

**Issue by artagnon** [VSCodeVim/Vim#6375]
**Describe the bug**
<kbd>u</kbd>/<kbd>C-r</kbd> do not integrate with the system/vscode's undo/redo functionality <kbd>Cmd+Z</kbd> and <kbd>Cmd+Shift+Z</kbd>.

- Extension (VsCodeVim) version: latest
- VSCode version: 1.55-insider
- OS: macOS

**Additional context**
I'm not sure about capturing <kbd>Cmd+Z</kbd> and <kbd>Cmd+Shift+Z</kbd> in Vim.

**Comment by J-Fields** [comment]
Yeah this is known. There are plans to make use of native undo so this won't be an issue, but for now, don't mix the two.

**Comment by sarki94g** [comment]
After opening a file, making a change, then using the vim undo (u) - the file is essentially 'unchanged' but vscode thinks the file has been edited.  Not sure if this is related to the original post or not.
