### ISSUE TITLE
`[num] %` is error when num% * lines < 0.5

### ISSUE THREAD

**Issue by YangChenyuan** [VSCodeVim/Vim#6397]
When using `[num] %`, it should move to the first line when [num] is pretty small, such as the condition that num% * lines < 0.5. I think VSCodeVim assign the line value with 0 when this condition occurs and then it reports the error that "Failed to handle key %. Illegal value for line".

**Comment by J-Fields** [comment]
I can't reproduce - `1%` in a line with 2 lines works just fine for me

**Comment by YangChenyuan** [comment]
> I can't reproduce - `1%` in a line with 2 lines works just fine for me

Sorry, I find that problem in 1.19.1, and the current version (1.19.3) hasn't that problem

**Comment by J-Fields** [comment]
Yup, can confirm - seems some bounds checking code I added fixed this inadvertently.
