### ISSUE TITLE
renaming keys to vim nomenclature

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#64]
Vim uses names like `<cr>` (`return`), `<C-m>` (`ctrl+m`). This will be required later to process keys, for example for the `:normal` command.

@jpoon Thoughts?

**Comment by jpoon** [comment]
:+1:

**Comment by rashwell** [comment]
I don't know how to give the thumbs up emoji but I agree as well.

**Comment by guillermooo** [comment]
@rashwell `:+1: ` `=` :+1: 
:smile:

**Comment by guillermooo** [comment]
@rashwell Is this something that you would like to take up for the existing keys?

**Comment by rashwell** [comment]
I don't mind doing the foot work, I will try and present a data structure that I think will be useful for this later this evening.
