### ISSUE TITLE
Mouse double click selection selects an extra character

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#641]
For example:

test[]

double click test

"test[" is selected. Only "test" should be selected.

Should be able to double click test, then "y", and "p" should only paste "test" not "test["

**Comment by vogler** [comment]
This is not fixed for me.
Double clicking inside `"foo"` in insert mode selects `foo`, but in visual mode it selects `foo"`.

**Comment by xconverge** [comment]
very weird, if you press x though it is right, likewise if you do l or h it looks like it WAS where it was supposed to be. Can you open a new ticket for this please? Thanks
