### ISSUE TITLE
`aw` should not count `\n` as a word.

### ISSUE THREAD

**Issue by YangChenyuan** [VSCodeVim/Vim#6418]
`[num] aw` select `[num]` words and leading or trailing white spaces is included but not counted.
Here are `v 2 aw` in VSCodeVim and Vim:
![Peek 2021-04-04 12-49](https://user-images.githubusercontent.com/55501188/113498969-4ef62100-9544-11eb-90a8-4c263d0de9d2.gif)
![Peek 2021-04-04 12-50](https://user-images.githubusercontent.com/55501188/113498970-51587b00-9544-11eb-9669-fc67ddf29844.gif)

**Comment by J-Fields** [comment]
Probably related: `diw` on a blank line should do nothing
