### ISSUE TITLE
c or d followed by number not working on Linux

### ISSUE THREAD

**Issue by svargas-dev** [VSCodeVim/Vim#6422]
This works out of the box on Mac OS but on Kubuntu 20.04.1 this doesn't work. I've read through the docs but can't find a reference if there's a fix to add to settings.json. Any help appreciated. Love the extension, thanks guys!

**Comment by J-Fields** [comment]
Can you clarify? Do you mean e.g. `d2w`? What happens?

**Comment by svargas-dev** [comment]
Sorry, I missed the complete shortcut "d" or "c" + number + space to change a number of characters does not work e.g. ```d2 space``` but your example ```d2w``` works as expected

**Comment by J-Fields** [comment]
Can you please provide your settings?

**Comment by svargas-dev** [comment]
Not sure if I'm missing something

`{
  "telemetry.enableCrashReporter": false,
  "telemetry.enableTelemetry": false,
  "editor.fontSize": 16,
  "vim.easymotion": true,
  "vim.incsearch": true,
  "vim.useSystemClipboard": true,
  "vim.useCtrlKeys": false,
  "vim.hlsearch": true,
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "j",
        "j"
      ],
      "after": [
        "<Esc>"
      ]
    }
  ],
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "<leader>",
        "d"
      ],
      "after": [
        "d",
        "d"
      ]
    },
    {
      "before": [
        "<C-n>"
      ],
      "commands": [
        ":nohl"
      ]
    }
  ],
  "vim.leader": "<space>",
  "[jsonc]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "editor.tabSize": 2,
  "[typescriptreact]": {
    "editor.defaultFormatter": "vscode.typescript-language-features"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}`

**Comment by J-Fields** [comment]
Ah, this is because you have `<space>` as your leader. You should be able to use `c2l` to change two characters instead.
