### ISSUE TITLE
Can't use  /\<the\> to search the word  'the'  with full match

### ISSUE THREAD

**Issue by joyous-coder** [VSCodeVim/Vim#6423]
**Describe the bug**

e.g.  I need to match the word 'the' , not  the word  'there'. In other vim editors what I  need to do is to type in  \\<the\\> in search mode,but in vscode it doesn't work at all. Can this be fixed ?? 

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `1.19.3`
- VSCode version:`1.55.0`
- OS:`windows 10`

**Comment by joyous-coder** [comment]
I find "\b" may take effect like '\<' and '\>'

**Comment by J-Fields** [comment]
Yeah we use javascript's regex engine rather than reimplementing vim's. #3996 is tracking this issue, though I don't expect it to be fixed in the short term
