### ISSUE TITLE
`o <C-U>` should delete the `\n` inserted by `o`

### ISSUE THREAD

**Issue by YangChenyuan** [VSCodeVim/Vim#6429]
`<C-U>` will delete all entered characters before the cursor in the current line. So when typing `o <C-U>`, it should delete the `\n` inserted by `o`.
Key is  `o <C-U>`
![Peek 2021-04-06 16-01](https://user-images.githubusercontent.com/55501188/113678767-966de000-96f1-11eb-8019-777bfa400a6f.gif)
This is what Vim does
![Peek 2021-04-06 16-02](https://user-images.githubusercontent.com/55501188/113679027-e187f300-96f1-11eb-9078-49e1572f65f8.gif)

**Comment by J-Fields** [comment]
I could've sworn there was an open issue about this, but can't find it
