### ISSUE TITLE
Inconsistent (with VSCode and Vim) undo behavior

### ISSUE THREAD

**Issue by spicydonuts** [VSCodeVim/Vim#643]
If I use the arrow keys to navigate and make a few changes on random lines, vscode treats each action as a separate event to undo.  If I do the same thing in vim it also treats each edit as a distinct event.  But if I use vscodevim movement (hjkl, {}, etc) and perform a series of edits, they are all treated as the same change when I undo/redo.

### What did you do?

It's mostly a problem when I've been using vim movements exclusively for a while (no clicking, window changing, arrow keys, etc).  I'll move some code around, comment something out, type a few lines, then hit 'esc' then 'u' because I mistyped the last word (or autocompleted wrong) and suddenly I've jumped wayyy back in time.  There have even been a few times where I continued to retype the misspelled word before noticing and wiped out the redo history too..

### What did you expect to happen?

The same behavior present in vscode when navigating with the mouse or arrow keys and in vim itself (using the latter if possible where they may differ).

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: macOS 10.11.6

**Comment by xconverge** [comment]
I think that this should be closed now from #646
