### ISSUE TITLE
No redo keybinding?

### ISSUE THREAD

**Issue by cathaysia** [VSCodeVim/Vim#6439]
**Describe the bug**

I'm writting a rst file, but it seem redo not work? Whether ctrl+r or U or Ctrl+Y. But undo work well.

**Comment by J-Fields** [comment]
Can you provide your settings? What happens when you hit `<C-r>`?

**Comment by cathaysia** [comment]
emm, sorry. I changed some settings of vscodevim yesterday. It works today. `<C-r>` just do nothing yesterday, I guess this hotkey was overrided by other software.
