### ISSUE TITLE
Undo history not affected by movement

### ISSUE THREAD

**Issue by spicydonuts** [VSCodeVim/Vim#644]
### What did you do?

Example 1: Comment out a line, move to another line, comment it out, repeat repeat, hit `u`
Example 2: type an if-block with a body, press escape, hit `u`

### What did you expect to happen?

Changes on separate lines should be treated as separate events in the undo history.

### What happened instead?

Large, multi-line blocks of changes seem to be treated as one undo event, inconsistent with both vim and vscode's normal undos.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: macOS 10.11.6

**Comment by xconverge** [comment]
For example 1, how are you moving to another line, are you using arrow keys?

**Comment by spicydonuts** [comment]
Doesn't matter which.  I've tried both, plus clicking with the mouse.

**Comment by johnfn** [comment]
It's interesting to me how we've gotten a large blast of fixes for our undo history over the last week or so, when it's been out for many months without any substantial changes. Thanks @xconverge and @spicydonuts for being fastidious! :)
