### ISSUE TITLE
How to map `Move Editor into First Group`

### ISSUE THREAD

**Issue by link-ding** [VSCodeVim/Vim#6451]
I want to map <leader> "w" "l" to the View action `Move Editor into First Group`. But this action do not have any command.
I can not find anyway to map command key as well
![image](https://user-images.githubusercontent.com/49264539/114032176-683dfb00-98bf-11eb-8131-644acdc98e26.png)
```
{
    "before":["leader","w","l"];
    "after":["cmd","1"];
}
```

**Comment by J-Fields** [comment]
```json
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before":["leader", "w", "l"],
      "commands":["workbench.action.moveEditorToFirstGroup"],
    }
  ]
```
