### ISSUE TITLE
Feature request: jump out of the bracket or the quote area

### ISSUE THREAD

**Issue by YvesZHI** [VSCodeVim/Vim#6483]
**Describe the solution you'd like**

When I'm under the Insert Mode, I want to be able to type `<C-j>` to jump out of a pair of brackets or a pair of quotes area.

For example,
before:
```
func(a,| b, c)    // | is the cursor
```
after typing `<C-j>`:
```
func(a, b, c)|    // | is the cursor
```

**Describe alternatives you've considered**

When I work with Vim, I have the settings in my `.vimrc` to enable this:
```
inoremap <C-j> <Esc>/[)}"'\]>]<CR>a
```
It means: goto the Normal Mode, search one of the closing bracket or the closing quote, and type `a` to re-enter the Insert Mode.

**Comment by sql-koala** [comment]
FYI, I think your mapping should work with vscode, you will just have to fiddle a bit to convert that `[)}"'\]>]` to a javascript regex, which works with this extension.

**Comment by YvesZHI** [comment]
@sql-koala Do you mean that I should use the emulated plugin vim-easymotion? Could you show me how to use it? I've tried as below but it doesn't work.

        "vim.easymotionJumpToAnywhereRegex": "()|])",

        {
            "before": ["<C-j>"],
            "after": ["<Esc>", "\\", "\\", "\\", "j"]
        },

**Comment by sql-koala** [comment]
No, the same mapping should work here.
Check: https://github.com/VSCodeVim/Vim/blob/master/README.md#vimrc-support
I recommend to start with a new/empty vimrc, then add your mapping. I checked that the regex works.
Leave out the " as that could be confused with  comment syntax.

**Comment by J-Fields** [comment]
> Leave out the " as that could be confused with comment syntax.

I think that should only be the case if it's the first non-whitespace character on the line
