### ISSUE TITLE
The content of  register  "" do not change when I  delete something.

### ISSUE THREAD

**Issue by joyous-coder** [VSCodeVim/Vim#6486]
**Describe the bug**
The content of  register  "" is set to GKT0ZY5BBL-eyJsaWNlbnNlSWQiOiJHS1QwWlk1QkJMIiwibGljZW5zZWVOYW1lIjoi5b6u5L+h5pCc57SiIOaZuuWwj.....
and the `:reg` command shows the register content list so slow. 

**Screenshots**
![Screen Shot 2021-04-16 103845](https://user-images.githubusercontent.com/42910684/114963910-51d80680-9ea0-11eb-8eb3-15f2e899a386.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.19.3
- VSCode version:1.55.2 stable
- OS: win10 20H2

**Additional context**

**Comment by J-Fields** [comment]
If `vim.useSystemClipboard` is enabled, you'll need to overwrite that via something like `""yy`. This is a known issue that should be fixed in the next release (#6441)

**Comment by joyous-coder** [comment]
👍 👍 👍
