### ISSUE TITLE
Support for `clipboard=unnamed` / using system clipboard for unnamed register

### ISSUE THREAD

**Issue by Platzer** [VSCodeVim/Vim#650]
A setting to use the unnamed register as alias for the `*` register. So `yy` for example copies to current line to the system clipboard, and `p` would insert from the clipboard. 

Should be a user setting (e.g. `useSystemClipboard`), and disbaled by default.

Further readings:
- http://vim.wikia.com/wiki/Accessing_the_system_clipboard
- http://vimdoc.sourceforge.net/htmldoc/change.html#E354 (topic 7)

**Comment by rebornix** [comment]
We've supported Vim configurations so it would be easy to add `useSystemClipboard`. @aminroosta , you may be interested in this task since you are the **Father** of Clipboard :)

**Comment by aminroosta** [comment]
@rebornix Sure, I will send a pr tonight ;-)

**Comment by aminroosta** [comment]
@rebornix Sorry for the delay, i completely forgot about it 😢 
Please let me know if you want any changes to the PR #655

**Comment by aminroosta** [comment]
I wanted to write a test for this but our `newTest` and `newTestOnly` functions are async. It's not easy to test new configuration options without affecting other tests.

@rebornix @johnfn I think it might be a good time to overload these functions to offer preparation and clean up callabacks. That way we can test new configuration options without affecting other tests.

**Comment by rebornix** [comment]
@aminroosta how about putting those tests sharing the same configuration into one suite and leverage the setup and teardown?

**Comment by jpoon** [comment]
This is closed with PR https://github.com/VSCodeVim/Vim/pull/665. Thanks @aminroosta 

To use, add the following to your user/workspace settings:

```
  "vim.useSystemClipboard": true
```

**Comment by bufke** [comment]
This doesn't appear to be working for me. When enabled yank no longer seems to do anything. After a yank I'm unable to paste in the system or in VS Code (for instance `p`). Using Ubuntu 16.04. My settings are:

```
{
    "vim.useCtrlKeys": true,
    "vim.useSystemClipboard": true
}
```
