### ISSUE TITLE
Repeated search of the same text doesn't work

### ISSUE THREAD

**Issue by lqlau** [VSCodeVim/Vim#652]
### What did you do?
Want to search for words in my file.

Put the exact keys you pressed, if relevant.
Pressed "/" to filled in text to search for.
It searched for first matching word.  
But when I press "/" again and hit <return>, it should automatically continue searching the file for next match.

### What did you expect to happen?
When pressing "/" and hitting <return> it should automatically search for the last text that was searched for.

### What happened instead?
Pressing "/" and hitting <return> the second or more time does nothing.  You have to manually fill in the same text each time.

### Technical details:

* VSCode Version: 1.4
* VsCodeVim Version: 0.17
* OS: Windows 10 64-bit

**Comment by xconverge** [comment]
Reproduced this as well, thanks for reporting!

**Comment by johnfn** [comment]
We haven't even cleared out the search history at this point. This should be like a 3 line change. 😉

**Comment by rebornix** [comment]
@johnfn seems we do https://github.com/VSCodeVim/Vim/blob/master/src/actions/actions.ts#L775 .

But it should be still simple as we only need to postpone the reinitialization.

**Comment by xconverge** [comment]
I will get to it tonight for sure if it still exists then :)

**Comment by johnfn** [comment]
@rebornix oops, just move that code to here i think https://github.com/VSCodeVim/Vim/blob/master/src/actions/actions.ts#L614

**Comment by lqlau** [comment]
Thanks @xconverge !  Which release will this fix be in?

**Comment by xconverge** [comment]
@johnfn can this be reopened or should I file a new issue? This does NOT seem to work now...

**Comment by rebornix** [comment]
@xconverge let's track it here.

**Comment by xconverge** [comment]
I 100% messed this fix up first time around...sorry, no idea what was going on there...
