### ISSUE TITLE
Search for \\c...

### ISSUE THREAD

**Issue by edemaine** [VSCodeVim/Vim#6520]
**Describe the bug**
It seems impossible to search for `\char` using `/\\char`.  Instead, it ends up searching for `har`.  Searching for `\c` via `/\\c` works fine.  It seems that `\\ch` gets contracted to `h` somehow.

**To Reproduce**

1.  Open any file containing `\char` as well as false matches like `not hard`.
2.  Type `/\\char`
3.  Observe that `har` matches in both instances.

**Expected behavior**
I expect only `\char` to match when searching for `\\char`.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.20.0
- VSCode version: 1.55.2
- OS: Windows 10

**Workaround:**
`/\\\bchar` successfully searches for `\char`.

**Comment by J-Fields** [comment]
Related: #2710

**Comment by zeroxia** [comment]
Recently after an update, I found I can't do this ex command to replace all `\` to `/` for a Windows path:

`:s/\\/\//g`

And I have to type commands like this:

`:s/\\\\/\//g`

Yes, you need to repeat backslash four times.

Is this intended?


Screencast to demo:

![Demo recording](https://i.imgur.com/NrtzMUP.gif)

**Comment by edemaine** [comment]
@zeroxia I think that's a different issue, so I opened it as #6890.
