### ISSUE TITLE
yanking / deleting 11 lines has issues

### ISSUE THREAD

**Issue by subhakarks** [VSCodeVim/Vim#6525]
Environment:
- OSX
- vscodevim: v1.20.0
- VSCODE: 

![Screen Shot 2021-04-21 at 4 38 22 PM](https://user-images.githubusercontent.com/23250456/115635489-ad4f2d80-a2c0-11eb-80ee-2e9aedcba78c.png)

Issue:
- Yanking: <esc> 11 Y ===> yanks only 1 line (first line)
- Deleting: <esc> 11 D ===> deletes only 1 line (first line)

Yanking/Deleting other numbers like 12, 22, 33 works fine.

**Comment by J-Fields** [comment]
Can you please provide your configuration?

**Comment by subhakarks** [comment]
@J-Fields Do you mean the VIM settings: I have them as below.
{noformat}
// vim
  "vim.foldfix": true,
  "vim.showcmd": true,
  "vim.hlsearch": true,
  "vim.gdefault": true,
  "vim.incsearch": true,
  "vim.autoindent": true,
  "vim.ignorecase": true,
  "vim.showmodename": true,
  "vim.enableNeovim": true,
  "vim.vimrc.enable": false,
  "vim.highlightedyank.enable": true,
  "vim.highlightedyank.duration": 450,
  "vim.neovimPath": "/usr/local/bin/nvim",
  "vim.cursorStylePerMode.insert": "line",
  "vim.cursorStylePerMode.normal": "block",
  "vim.cursorStylePerMode.replace": "underline",
  "vim.insertModeKeyBindings": [],
  "vim.normalModeKeyBindings": [],
  "vim.visualModeKeyBindings": [],
  "vim.highlightedyank.color": "rgba(46,96,90,0.62)",
  "vim.insertModeKeyBindingsNonRecursive": [],
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "1",
        "1"
      ],
      "commands": [
        ":w"
      ]
    },
    {
      "before": [
        "<C-n>"
      ],
      "commands": [
        ":nohl"
      ]
    },
  ],
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": [
        ">"
      ],
      "commands": [
        "editor.action.indentLines"
      ]
    },
    {
      "before": [
        "<"
      ],
      "commands": [
        "editor.action.outdentLines"
      ]
    },
  ],
{noformat}

**Comment by subhakarks** [comment]
@J-Fields  NVM. I guess it's my settings below.
```
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "1",
        "1"
      ],
      "commands": [
        ":w"
      ]
    },
```

**Comment by J-Fields** [comment]
Yep - `11Y` with those settings will do `:w` and then `Y`
