### ISSUE TITLE
Yanking in multi cursor mode replaces only first cursor

### ISSUE THREAD

**Issue by evenfrost** [VSCodeVim/Vim#6530]
**Describe the bug**
Yanking in multi cursor mode replaces only the first cursor, other cursors seem to be replaced with preceding ones instead of the initial value.

**To Reproduce**

![Peek 2021-04-22 19-05](https://user-images.githubusercontent.com/3055750/115747440-f0330300-a39d-11eb-9267-3f622cf3d91d.gif)

1.  Select a string
2.  Press Y
3.  Enter multi cursor mode via selecting multiple occurrences of other strings
4.  Try to replace them with P

**Expected behavior**
All strings are replaced with the string yanked as was before.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.20.0
- VSCode version: 1.55.2
- OS: Ubuntu 20.04

**Comment by J-Fields** [comment]
I think this is because we're overwriting the register after doing the first replacement, rather than after all the replacements have been done

**Comment by evenfrost** [comment]
FYI it was working fine before the last (I believe) update, so may be a regression.

**Comment by J-Fields** [comment]
Yeah I re-wrote all the put logic from scratch for `1.20.0`, and that fixed a lot of corner cases, but I'm not surprised it broke at least one as well

**Comment by keidarcy** [comment]
version `1.21.4` still the same problem.
any ideal?
@J-Fields
