### ISSUE TITLE
Leading space get removed when visual select and paste

### ISSUE THREAD

**Issue by kwokhou** [VSCodeVim/Vim#654]
When I paste over a visual selected text (until the last character), the space before get removed.

Steps to reproduce:

1. Assuming I have the following lines of codes.
```
1     var foo = bar;
2     var fuu = aaa;
```
1. Now, visual select `bar` from `line 1`, and `yank` (only yanking the 3 letters `bar`)
2. Next, move cursor to `line 2`, and visual select `aaa;` (notice i visual selected until the last character `;`
3. Then, `paste`. And the space before `aaa` get removed. 

This only happen when in `step 2`, I visual select until the last character of the line.

**Comment by xconverge** [comment]
Got it, reproduced. Thanks for the steps!
