### ISSUE TITLE
`gd` that causes a file load followed by `h`/`j`/`k`/`l` jumps to random spot

### ISSUE THREAD

**Issue by lenlsvp** [VSCodeVim/Vim#6544]
gd that causes a file load followed by h/j/k/l jumps to random spot

1.  type gd on a symbol that causes a file load
2.  the cursor jumps to the right place but subsequent movement (h/j/k/l) causes it to jump to a random spot

The problem started a few days ago.

- Extension (VsCodeVim) version: 1.20.0
- VSCode version: 1.55.2
- OS: macOS Big Sur 11.2.3

**Comment by lenlsvp** [comment]
Downgrading to 1.19.3 fixes the issue.

**Comment by atulpatildbz** [comment]
@J-Fields has taken this up as commented in https://github.com/VSCodeVim/Vim/issues/6585
