### ISSUE TITLE
Running :w! on a read-only file results in messed up permissions.

### ISSUE THREAD

**Issue by a-sore** [VSCodeVim/Vim#6553]
When you try to use :w! on a read-only file, it will mess up the file permissions.

**To Reproduce**

1.  Open a new folder in VSCode
2.  Create a new file
3.  Do a chmod -w on said file.
4.  Edit the file in VSCode. Run :w! on the file. File permissions are now "--w--wx-wT".

**Expected behavior**
File content should be written on disk, and permissions shouldn't change.

**Environment**

- Extension (VsCodeVim) version: v1.20.1
- VSCode version: 1.55.2
- OS: macOS 10.15.7

**Comment by joecrop** [comment]
I see this on RedHat Linux too. I'm going to look into what is causing this and propose a fix. Furthermore, I see a chmod 666 hard coded in the write:bang function that can be improved to prevent a permanent permissions change.
