### ISSUE TITLE
af command from Readme doesn't work

### ISSUE THREAD

**Issue by sergeda** [VSCodeVim/Vim#6565]
**af command doesn't work**
`af` supposed to selects the text, but for me pressing `a` switches to insert mode and that's all.

**To Reproduce**

1.  Just try to use `af` combination

**Expected behavior**
af - visual mode command which selects increasingly large blocks of text. For example, if you had "blah (foo [bar 'ba|z'])" then it would select 'baz' first. If you pressed af again, it'd then select [bar 'baz'], and if you did it a third time it would select "(foo [bar 'baz'])".

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.20.1
- VSCode version: 1.55.2
- OS: Windows 10

**Comment by sql-koala** [comment]
Did you start visual mode, meaning `vaf`? :D

**Comment by sergeda** [comment]
Apparently I didn't :)
Then it's better to change the Readme for nubs like me :)

**Comment by jonashaag** [comment]
Doesn't work for me with `vaf`.
