### ISSUE TITLE
Missing support for "search history"

### ISSUE THREAD

**Issue by sectioneight** [VSCodeVim/Vim#657]
---

Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

Search for some text with `/foo`. Leave search mode. Enter search mode again and attempt to "scroll back" search history with `/<up>`.
### What did you expect to happen?

`/` would show me my past searches and fill them in as i scrolled up and down with arrows
### What happened instead?

"Searching for `<up>`"

**Comment by sectioneight** [comment]
I have no idea how difficult this would be to implement or how desired it is, just marking this down in case other people come across it so we can prioritize if people find it useful.

I don't personally use it much.

**Comment by realh** [comment]
I really miss this feature. If it wasn't for VS Code itself recently having had [search history support added](https://github.com/Microsoft/vscode/issues/5508) I'd probably use Atom instead. Maybe VSVim will be able to take advantage of Code's new support for it? I'll probably bind / to Ctrl+F in the meantime, but it would be nicer with /, *, :s etc all  fully integrated.

**Comment by johnfn** [comment]
Sadly, we do search in a completely different way than VSCode. However, this is actually a pretty straightforward feature to add for anyone who is interested in doing so. :)
