### ISSUE TITLE
The joinspaces configuration option should default to false

### ISSUE THREAD

**Issue by nomad-software** [VSCodeVim/Vim#6572]
**Describe the bug**

This PR: https://github.com/VSCodeVim/Vim/pull/5895 introduced the `vim.joinspaces` configuration option and set the default to `true` but the majority of the world does not use double spacing. This is a breaking change to joining operations and is not how Vim works.

**To Reproduce**

1. Enter a paragraph of text in one line
2. Select using Shift+V
3. Press `gq` to format
4. The paragraph is now double spaced after punctuation

**Expected behavior**

1. There should be no double spaces.
2. The default should be `false` and the double space behaviour should be 'opt-in'

**Additional context**

PR which introduced this breaking change: https://github.com/VSCodeVim/Vim/pull/5895

**Comment by edemaine** [comment]
What do you mean by "is not how Vim works"?  In Vim, [joinspaces is on by default](http://vimdoc.sourceforge.net/htmldoc/options.html#'joinspaces').

**Comment by nomad-software** [comment]
@edemaine Follow my steps to reproduce above.

**Comment by J-Fields** [comment]
There's a bug that will be fixed by #6571 - double spaces should only be added where there were linebreaks. `joinspaces` is on by default in Vim, though, and I prefer to maintain its defaults, generally speaking.
