### ISSUE TITLE
Visual block insert seems to insert at the column preceding selected column

### ISSUE THREAD

**Issue by jship** [VSCodeVim/Vim#658]
### What did you do?
Selected multiple lines of text in visual block mode ('ctrl'+'v', 'j', 'j', 'j'), starting the block anywhere beyond the first column, then initiated a block insert (capital I) and tried to insert a character in front of each selected row at the selected column.  Instead, it inserted a character in front of each selected row at the column previous to the selected column.

A gif is worth a thousand words:
![vscode](https://cloud.githubusercontent.com/assets/1744045/18025525/285924b6-6bfa-11e6-9140-f518a6fa6db2.gif)

### What did you expect to happen?
I expected VS Code to insert a character in front of each selected row at the selected column.

### What happened instead?
VS Code inserted a character in front of each selected row at the column previous to the selected column.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Win 10, 64-bit

**Comment by nullbio** [comment]
I feel like this may be related to https://github.com/VSCodeVim/Vim/issues/662 given the insert-before behavior is what I'm seeing in that issue as well.

**Comment by xconverge** [comment]
This should be closed due to #667

**Comment by johnfn** [comment]
Thanks @xconverge for pointing out that this should be closed, and also fixing it. 😉

**Comment by jship** [comment]
Sweet, thanks!
