### ISSUE TITLE
gk / gj motions do nothing

### ISSUE THREAD

**Issue by mleech** [VSCodeVim/Vim#660]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Pressing gk or gj doesn't seem to have any effect.

They should move up or down visual lines (differing from j / k when lines are wrapped).

The roadmap has them as implemented so I'm not sure if this is a regression or a documentation error.

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: OSX El Capitan and Windows 10

**Comment by rebornix** [comment]
It's a regression, thanks for reporing @mleech ! Actually we moved a newly introduced command for moving lines `g[jk]` but it's still not released in stable. It should be gone when you have 1.5.0 or use Insider bits ...

**Comment by jpoon** [comment]
Validated that this works on 0.1.10.

I think this was fixed in https://github.com/VSCodeVim/Vim/pull/486.
