### ISSUE TITLE
Pasted text with ctrl+v is selected on pasting

### ISSUE THREAD

**Issue by rightaway** [VSCodeVim/Vim#6603]
**Describe the bug**
Pasting with ctrl+v in a group (such as `<>`, `[]`, `''`) causes the pasted text to be selected. So any further key presses replace the pasted text.

**To Reproduce**

Enter insert mode. Enter an opening group character like `<`, enter ctrl+v to paste the text. The pasted text is selected. Type any other character and the pasted texted is gone.

Do the same but this time don't enter an opening character. Now entering ctrl+v just pastes the text without selecting it.

**Expected behavior**
The pasted text shouldn't be selected in any case.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.20.0
- VSCode version: 1.55.2
- OS: linux

**Comment by J-Fields** [comment]
This was fixed in 1.20.2, please upgrade
