### ISSUE TITLE
Is there a way to to set default to insert mode rather than to normal mode?

### ISSUE THREAD

**Issue by haxer-max** [VSCodeVim/Vim#6608]
I would like to set default mode to insert mode when I open a file in vscode as it makes copy pasting and select all commands (which I can do with ctrl+C, ctrl+V, ctrl+A in insert  mode) much faster.

**Comment by J-Fields** [comment]
Is `vim.startInInsertMode: true` what you're looking for?

**Comment by haxer-max** [comment]
@J-Fields  Thanks a lot
