### ISSUE TITLE
ctrl+v + c deleting extra char, and putting cursor in wrong position. Types at a different position to cursor too.

### ISSUE THREAD

**Issue by nullbio** [VSCodeVim/Vim#662]
Please thumbs-up :+1: this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---

### What did you do?

This bug seems to stem from the fact that pressing `c` on highlighted words/characters also takes an extra character. It also puts your cursor at a weird position.

Try the following, with this in your document:

```
hello
world
```

Highlight the `he` by pressing `ctrl+v` and moving your cursor to the right once (so that the `h` is highlighted, and your cursor is sitting on the `e`). Then press `c`.

### What did you expect to happen?

I expected it to delete the `he` and put it in insert mode at the start of the line. This is how VIM does it.

### What happened instead?

It deletes `hel` (an extra char is deleted). It also puts the cursor AFTER the `l` in `lo`, instead of BEFORE it. This puts you in insert mode, but once you start typing instead of typing where you'd expect it to (where the cursor is), it types 3 characters back from the cursor. As a result, take the following:

(`|` is where the cursor is)
`l|o`

Typing `he` produces:

`he l|o`

As you can see its unexpectedly added a space in there as well.

This bug also results in other buggy behaviour such as moving the line below your current line upward if you're doing this `c` operation at the end of the line (because it takes an extra char, it strips the newline character as well). To see this behavior, do the following:

Highlight the `lo` by pressing `ctrl+v` on the `l` and moving your cursor to the right once (so that the `l` is highlighted, and your cursor is sitting on the `o`). Then press `c`. As you will see, it deletes the invisible nl char at the end of the line, so it moves the line below it onto the same line you're working on.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Ubuntu 16.04

**Comment by xconverge** [comment]
This should be a quick one, I can get to it tomorrow :)
