### ISSUE TITLE
$ goes to the next line in visual mode

### ISSUE THREAD

**Issue by ilovejcm** [VSCodeVim/Vim#6623]
1. Press v to switch to visual mode.
2. Press $

Expect：
   Cursor move to the end of current line.

Acture:
   Cursor move to the start of next line.

Env: 
    Visual Studio Code 1.56.2
    CSCodeVim v1.20.2
    Mac Big Sur

![image](https://user-images.githubusercontent.com/7704777/118352264-0f831180-b593-11eb-9449-8555d37df166.png)

**Comment by J-Fields** [comment]
`v$` puts the cursor on the EOL character, and this is how VS Code renders that. Vim does it differently, but the result of any given operation should be the same
