### ISSUE TITLE
NumericString should implement negative numbers for hex when using ctrl+x past 0x0

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#663]
enter 0x0, do ctrl-x to decrement

Vim gives you 0xffffffffffffffff

We give 0x-1

**Comment by johnfn** [comment]
We discussed this but placed it at extreme low priority. I can't imagine that many people use this feature. Again, feel free to thumbs up this issue of you disagree.

**Comment by xconverge** [comment]
Definitely agree, but was worth documenting :)
