### ISSUE TITLE
Bug when pasting with multiple cursors in vim

### ISSUE THREAD

**Issue by fujiya-hashimura** [VSCodeVim/Vim#6639]
- When pasting (vim command: `p`) with the multi-cursor (`ctrl-d`) in vim, the selected text is pasted twice in the second and subsequent selection pastes.
- Pasting will deselect the multiple cursor

<br>

 Version
  - VSCode: 1.56
  - vscodevim: v1.20.3   
  - OS: Windows 10

![vscode_bug](https://user-images.githubusercontent.com/84486598/118915326-bb4ba900-b967-11eb-9cec-b401bd15a18f.gif)

This problem did not occur before the vscode update. 
Thank you for all the useful tools.

**Comment by v-iashin** [comment]
The same happens if using `gb`

**Comment by keidarcy** [comment]
Same here and allowing to README, and another bug here, `Pressing Escape in Multi-Cursor Visual Mode will bring you to Multi-Cursor Normal mode`, I go to `Visual` mode instead. This happens several months ago, before that works fine.
![2021-07-06 16 41 14](https://user-images.githubusercontent.com/48758247/124562082-92c93100-de79-11eb-94c0-f42c8d71c22c.gif)

>Pressing Escape in Multi-Cursor Visual Mode will bring you to Multi-Cursor Normal mode. Pressing it again will return you to Normal mode.

- vscodevim: `v1.21.4`
- vscode: `1.57.1`
- macOS: `11.4`

**Comment by joel1st** [comment]
For those looking for an immediate solution while my PR is reviewed/awaiting release:

You can download the vim-multicursor-put-fix.vsix here:
https://github.com/joel1st/Vim/releases/tag/multicursor-put-fix

You can install it by pressing Ctrl+Shift+P and type ‘vsix’ in the command palette, and VS Code will suggest ‘Extensions: Install from vsix…’. When you select this, you need to browse to the file, and hit the ‘Install’ button.

**Comment by keidarcy** [comment]
@joel1st 

Thanks for your pr! I installed your part finally I can paste as I hope!

But in the Multiple-cursor-mode area of [README](https://github.com/VSCodeVim/Vim#%EF%B8%8F-multi-cursor-mode)

> - Each cursor has its own clipboard.
> - Pressing Escape in Multi-Cursor Visual Mode will bring you to Multi-Cursor Normal mode. Pressing it again will return you to Normal mode.

In my understanding, the second part is still not yet. 
`Pressing Escape in Multi-Cursor Visual Mode` bring me to `Normal mode` not  `Multi-Cursor Normal mode`.

**Comment by joel1st** [comment]
@keidarcy I'm glad it has resolved the first issue :)

I have not had a look into your problem. It might be best to create a new issue as it is fundamentally a different problem.
As a side note, I can't reproduce what you are seeing (on linux), so this might be specific to mac.

**Comment by AlexString** [comment]
Hello, I'd like to share a simple 'alternative'. I like to exclude `Ctrl + c` from vim bindings so I can still use copy and paste.

You can select all you want with multi cursor and use `Ctrl + c` instead of yanking the selected text.
