### ISSUE TITLE
Pressing tab while in Replace mode resulting <tab>

### ISSUE THREAD

**Issue by barraIhsan** [VSCodeVim/Vim#6641]
**Describe the bug**
When you are in replace mode, and type tab. Its gonna resulting <tab>

**To Reproduce**

1.  Press Esc to make sure you are in normal mode
2.  Press R (capital r) to get you into replace mode
3.  Press Tab
4.  See error

**Expected behavior**
It gonna replace the character we are on to be tab (whitespace)

**Video**
VSCode :

https://user-images.githubusercontent.com/57800056/118962659-ce726f00-b98f-11eb-8d60-0763be069169.mp4

Vim :

https://user-images.githubusercontent.com/57800056/118963032-36c15080-b990-11eb-8117-25f329752a2d.mp4

**Environment (please complete the following information):**

- Extension Version: `1.20.3`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.56.2`

**Comment by nigolarer** [comment]
same things happened when in Normal mode, press `o` and press `tab` rapidly, instead of add a new line and tab, it create a new line with resulting `<tab>`

**Comment by Komar0ff** [comment]
@nigolarer Very strange behavior. Сreated a [separate issue](https://github.com/VSCodeVim/Vim/issues/6996) for this bug. I hope you don't mind
