### ISSUE TITLE
incorrect undo of macro execution containing delete after join

### ISSUE THREAD

**Issue by delan** [VSCodeVim/Vim#6645]
**Describe the bug**

When executing a macro then undoing it, the buffer contents are not always unchanged. I think the affected macros are those that delete something (d, x) at any point later than a join (J), regardless of what happens between them.

**To Reproduce**

1. Set up your buffer:
    * ggcGhello world\<Esc>yy4P
2. Try one of these test cases:
    * qq<b>Jx</b>q@qu (bad)
    * qq<b>Jbelx</b>q@qu (bad)
    * qq<b>Jdlx</b>q@qu (bad)
    * qq<b>Jdd</b>q@qu (bad)
    * qq<b>eax\<Esc>Jxeax\<Esc></b>q@qu (bad)
    * qq<b>Jeax\<Esc>x</b>q@qu (bad)
    * qq<b>eax\<Esc></b>q@qu (good)
    * qq<b>Jyyp</b>q@qu (good)
    * qq<b>JJ</b>q@qu (good)
    * qq<b>J</b>q@qu (good)
    * qq<b>xJ</b>q@qu (good)
    * qq<b>xx</b>q@qu (good)
    * qq<b>x</b>q@qu (good)

**Expected behavior**

`@qu` should yield the same buffer contents as before, but in the bad cases, the contents change.

**Environment (please complete the following information):**
- Empty settings.json with no other non-stock extensions
- Extension (VsCodeVim) version: 1.20.3
- VSCode version:
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 4.19.0-14-amd64
```

**Comment by J-Fields** [comment]
Thanks for the issue (with detailed repro steps 🙂)! I can confirm and I'll dig into this when I get a chance.
