### ISSUE TITLE
ex-commandline renders icon codes

### ISSUE THREAD

**Issue by The-Compiler** [VSCodeVim/Vim#6655]
**Describe the bug**
When e.g. typing `:s/$(rocket)`, that shows up as `:s/🚀`

**Expected behavior**
The text would be escaped in some way so that VS Code [doesn't interpret it as icon](https://code.visualstudio.com/api/references/icons-in-labels). I'm not sure if that's possible, though...

**Screenshots**
![image](https://user-images.githubusercontent.com/625793/119262654-40d78f00-bbdc-11eb-93d5-96badfaa2a10.png)

**Environment (please complete the following information):**

- Extension Version: `1.20.3`
- OS Version: `Linux x64 5.12.3-arch1-1`
- VS Code version: `1.56.2`

**Comment by J-Fields** [comment]
@The-Compiler Could you make an issue in the VSCode repo asking if there's a way to do this? I'm not aware of one.

**Comment by The-Compiler** [comment]
Okay, so it wasn't just me who couldn't figure out how to do this... Done: https://github.com/microsoft/vscode/issues/124703

**Comment by The-Compiler** [comment]
Ah, looks like doing e.g. `\$(rocket)` works. A quick attempt at fixing this:

```ts
diff --git i/src/statusBar.ts w/src/statusBar.ts
index 47962738..42379355 100644
--- i/src/statusBar.ts
+++ w/src/statusBar.ts
@@ -149,6 +149,10 @@ class StatusBarImpl implements vscode.Disposable {
 
 export const StatusBar = new StatusBarImpl();
 
+function escapeIcons(text: string) {
+  return text.replace(/\$\([a-zA-Z0-9~-]+\)/g, '\\$&');
+}
+
 export function statusBarText(vimState: VimState) {
   const cursorChar =
     vimState.recordedState.actionKeys[vimState.recordedState.actionKeys.length - 1] === '<C-r>'
@@ -184,12 +188,12 @@ export function statusBarText(vimState: VimState) {
       const leadingChar =
         globalState.searchState.searchDirection === SearchDirection.Forward ? '/' : '?';
 
-      const searchWithCursor = globalState.searchState.searchString.split('');
+      const searchWithCursor = escapeIcons(globalState.searchState.searchString).split('');
       searchWithCursor.splice(vimState.statusBarCursorCharacterPos, 0, cursorChar);
 
       return `${leadingChar}${searchWithCursor.join('')}`;
     case Mode.CommandlineInProgress:
-      const commandWithCursor = vimState.currentCommandlineText.split('');
+      const commandWithCursor = escapeIcons(vimState.currentCommandlineText).split('');
       commandWithCursor.splice(vimState.statusBarCursorCharacterPos, 0, cursorChar);
 
       return `:${commandWithCursor.join('')}`;
@@ -251,10 +255,10 @@ export function statusBarCommandText(vimState: VimState): string {
     }
     case Mode.Insert:
     case Mode.Replace:
-      return vimState.recordedState.pendingCommandString;
+      return escapeIcons(vimState.recordedState.pendingCommandString);
     case Mode.Normal:
     case Mode.Disabled:
-      return vimState.recordedState.commandString;
+      return escapeIcons(vimState.recordedState.commandString);
     default:
       return '';
   }
```

but turns out it's more complex than that, because of how the displayed text (used for editing with the cursor) is now one character shorter than expected, and also VS Code not needing any escaping when the cursor is between the parentheses...

**Comment by J-Fields** [comment]
Thanks @The-Compiler - that's also an issue with newlines, IIRC. Can probably tackle them at the same time
