### ISSUE TITLE
Show previews for `:s` replacements

### ISSUE THREAD

**Issue by The-Compiler** [VSCodeVim/Vim#6656]
**Is your feature request related to a problem? Please describe.**
I'm coming from Spacemacs/Doom Emacs (after switching there from vim), and I really miss the preview it shows on `:s/.../...` commands while typing the replacement. Especially for regexes, this can be very useful.

**Describe the solution you'd like**
Something like this (implemented by evil-mode in emacs):

![image](https://user-images.githubusercontent.com/625793/119263108-0111a700-bbde-11eb-8cc9-0674b695a142.png)

**Describe alternatives you've considered**
Doing the replacement, checking manually if it worked or not, undoing and doing it again, etc.

**Additional context**
Looks like [vim-over](https://github.com/osyo-manga/vim-over) is a plugin for vim doing something similar.

**Comment by J-Fields** [comment]
Related: #4934

**Comment by J-Fields** [comment]
nvim has this built-in, see `:help inccommand`
