### ISSUE TITLE
Give us feedback: Vim keybindings in debugging console

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#666]
It looks like the latest version of VSCode will give us the option to use Vim keybindings in the debugging console as well as the main text editor.

Is this something you think should be on by default or off by default? Please use the 😆  reaction for 'on' and the 😕  reaction for 'off'. (You can also leave a comment.)

**Comment by rebornix** [comment]
I see it as a newly introduced or bug as I remember previously `type` command doesn't cover debugging console area, it's for `editor` :(

**Comment by johnfn** [comment]
@rebornix feel free to join in on the conversation at https://github.com/Microsoft/vscode/issues/10451 as I feel the same way.
