### ISSUE TITLE
Debug logs are shown independently of Log Level on VS Code web

### ISSUE THREAD

**Issue by guiherzog** [VSCodeVim/Vim#6662]
**Describe the bug**
When using the browser version of VS Code (e.g.: Github Codespaces), the setting: `vim.debug.loggingLevelForConsole` is not respected and Vim outputs every debug message to the console, this makes the application much slower.

**To Reproduce**

1.  Go to VS Code web (Github Codespaces)
2.  Enable Vim extension.
3.  Set your log level to 'error'. `vim.debug.loggingLevelForConsole`
4.  Edit some file.
5.  Current behavior: 
Literally every keystroke prints a bunch of lines with lots of debugging information.

**Expected behavior**
Nothing would be printed in the console unless it is an error.

**Screenshots**

![Screen Shot 2021-05-25 at 11 12 54](https://user-images.githubusercontent.com/3836025/119472077-30452700-bd4a-11eb-9c6c-ddf2289cfd94.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.20.3
- VSCode version: Web Version
      Version: 1.56.2
      Commit: 054a9295330880ed74ceaedda236253b4f39a335
      Date: 2021-05-12T16:44:26.030Z (1 wk ago)
      Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 
- OS: macOS 11.3.1 (20E241) (Big Sur)

**Additional context**

Apparently, the browser implementation of the Vim extension is not handling configuration correctly as the node one is:
See https://github.com/VSCodeVim/Vim/blob/master/src/platform/node/loggerImpl.ts and https://github.com/VSCodeVim/Vim/blob/master/src/platform/browser/loggerImpl.ts for the differences.

The current workaround is enabling "vim.debug.silent", but that's not the appropriate solution.

**Comment by J-Fields** [comment]
Fixed by f122b747a002610b9bf3df320e3270dffd712d68 in upcoming release
