### ISSUE TITLE
Copying and pasting across multiple VSCode instances

### ISSUE THREAD

**Issue by TryerGit** [VSCodeVim/Vim#6664]
I have project1 and project2 being two separate project folders. I open them separately and simultaneously by typing `code .` in their respective folders.

In project1, suppose I yank a few lines from a file from within project1 with the intention of pasting this into another file within project2, the yank does not carry over to the other project. The pasting of the file in project2 is of the previous yank from inside project2.

Is there any clipboard/registers that are shared so that I can yank into these specific registers from project1 and then retrieve this register from within project2?

Thanks.

**Comment by J-Fields** [comment]
The clipboard register (`*`) mirrors the system clipboard, so you should be able to use that between VSCode instances. `vim.useSystemClipboard` makes this the default register.
