### ISSUE TITLE
Search commands (/ and ?) with no input should repeat last search

### ISSUE THREAD

**Issue by Deracination** [VSCodeVim/Vim#668]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Search with /, then navigate or edit, then press ? and enter

### What did you expect to happen?
I expect the last search to be repeated in the chosen direction (/ for forward, ? for back)

### What happened instead?
The search prompt waits for input. The previous search is apparently lost

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Windows

**Comment by Deracination** [comment]
It probably is the same. Sorry for the duplicate report!

**Comment by xconverge** [comment]
Yep this looks to be fixed in the codebase for both / and ?
