### ISSUE TITLE
Add the option to delete without overriding the clipboard

### ISSUE THREAD

**Issue by yar00001** [VSCodeVim/Vim#6682]
"Adding a new ticket since this one is closed: https://github.com/VSCodeVim/Vim/issues/4241"

**Is your feature request related to a problem? Please describe.**

- Copy some text from any website.
- Enter into vscode, find any file and delete some word in normal or visual mode.
- Enter into insert mode and paste text from step 1.
- Text from step 1 was overrided by step 2. Then I have to go back to copy it again !

**Describe the solution you'd like**

- add an option to disable copy while deleting text by supporting the common solutions ([for reference](https://stackoverflow.com/questions/11993851/how-to-delete-not-cut-in-vim))

Both proposed solutions in the previous issue is not usable: 
- disabling `SystemClipboard` would also disable yanking on valid use-cases/command such as `p`.
- mapping `d` makes vscode to freeze for some reason

**Comment by w-cantin** [comment]
Hello, 

I remapped d to use the black-hole register _ like mentioned in the link you proposed above. 

` {
            "before": [
                "d"
            ],
            "after": [
                "\"",
                "_",
                "d"
            ]
        },`

Does this solution work for your problem? Does it make vscode freeze?

**Comment by yar00001** [comment]
Yes I've tried this. For some reason this mapping freezes vscode on pressing 'd' (I'm using Ubuntu 20)

**Comment by yar00001** [comment]
OK I checked my `keybindings.json` file and found out 'd' is mapped to another shortcut. I removed the mapping and all seems working now.

**Comment by v1sion** [comment]
This seems to work only on vim normal mode, if I enter visual mode by selecting and deleting the line it still gets copied. 
Any solution to this?
Thanks

**Comment by w-cantin** [comment]
@v1sion Yes you can also rebind the same command for visual mode too. 

```   "vim.visualModeKeyBindingsNonRecursive": [
    { "before": ["d"], "after": ["\"", "_", "d"] },
```

**Comment by eugeneteoh** [comment]
You might want to also rebind "x".
```json
{
    "vim.useSystemClipboard": true,
    "vim.normalModeKeyBindingsNonRecursive": [
      {
        "before": ["d"],
        "after": ["\"", "_", "d"]
      },
      {
        "before": ["D"],
        "after": ["\"", "_", "D"]
      },
      {
        "before": ["d", "d"],
        "after": ["\"", "_", "d", "d"]
      },
      {
        "before": ["x"],
        "after": ["\"", "_", "x"]
      }
    ],
    "vim.visualModeKeyBindingsNonRecursive": [
      {
        "before": ["d"],
        "after": ["\"", "_", "d"]
      }
    ],
}
```
