### ISSUE TITLE
Not working with latest vscode insider build 

### ISSUE THREAD

**Issue by htjain** [VSCodeVim/Vim#6683]
**Describe the bug**
With latest vscode insider build plugin is not working. I have to uninstall and install plugin on each vscode restart to get it working

**To Reproduce**
Upgrade to latest vscode insider build.
VIM mode not working

**Expected behavior**
VIM mode should be working with latest vscode build.

- Extension (VsCodeVim) version: v1.20.3
- VSCode version: Version: 1.57.0-insider
- OS: Windows 10

**Comment by srama2512** [comment]
I am observing a similar issue.  Same VsCodeVim and VSCode versions as above. The OS is Ubuntu 20.04.1 LTS.

**Comment by htjain** [comment]
With latest vscode build I am not seeing this issue. 

> Version: 1.57.0-insider (user setup)
> Commit: c7119ae8b6390a5700f6b28f0f1511d676c96562
> Date: 2021-06-08T09:17:55.672Z
