### ISSUE TITLE
Plugin isn't working properly at all - pressing keys in normal mode simply inserts the characters into the file

### ISSUE THREAD

**Issue by duckpuppy** [VSCodeVim/Vim#6689]
**Describe the bug**
Plugin simply doesn't work. It shows `-- NORMAL --` in the status bar, shows a block cursor (default normal mode cursor, 
I assume), and if I use the mouse to highlight text it switches to `-- VISUAL --` in the status bar. However, it still just responds to keypresses in normal mode like standard VSCode (typing just inserts characters, etc).

**To Reproduce**

1.  Install Plugin
2.  Restart VSCode to make sure the plugin is running
3.  Look for `-- NORMAL --` in the status bar, indicating normal mode.
4.  Attempt to use vim control character (such as `j` to move down a line) and see characters being inserted instead.

**Expected behavior**
Behaves like vim

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.20.3
- VSCode version: 1.56.2
- OS: macOS 10.15.7

**Comment by J-Fields** [comment]
Have you tried restarting VSCode, reinstalling the plugin, etc.? If so, can you please provide your settings and any other plugins you have installed?

**Comment by duckpuppy** [comment]
Reinstalled and restarted VSCode multiple times. I have 125 other extensions installed, the list and settings are in this gist: https://gist.github.com/duckpuppy/01e7d875a6cd16289851fbd38f6a2bdc

**Comment by duckpuppy** [comment]
And... I found the conflict. It was the `Overtype` plugin. Apparently, there's a conflict between the vim plugin and that one.
