### ISSUE TITLE
dot '.' should repeat last edit actions and not repeat navigation commands

### ISSUE THREAD

**Issue by Deracination** [VSCodeVim/Vim#669]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
enter insert mode (i), type some text, ESC to exit insert. navigate to another line, press '.'

### What did you expect to happen?
I expect the insert to be repeated at the new cursor position. The dot command should not repeat navigation commands.

### What happened instead?
The last navigation action is repeated and cursor is repositioned

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Windows

**Comment by johnfn** [comment]
I can't reproduce this. Can you please provide the exact keystrokes you used?

**Comment by rebornix** [comment]
Can't reproduce as well.

**Comment by Deracination** [comment]
Sorry, I can't reproduce this exactly so I'm not sure exactly what was happening, but I get a similar result if use 'v' or 'V' to highlight a selection, then navigate, then '.'. The result is to repeat the navigation of the v command. In vim v/V is not repeatable.

**Comment by johnfn** [comment]
Interesting, that's definitely a bug!

**Comment by dongkyunc** [comment]
Similarish issue happened to me. I have 'j', 'j' mapped to <escape>. 

Input: insert mode, 'foobarjj', and I press '.'

Expected output: foobarfoobar
Actual output: foobarfoobarj

**Comment by localvar** [comment]
I get this issue too.
VSCode: 1.5.2
Vim: 0.1.10
OS: windows 10 professional

**Comment by rebornix** [comment]
Fixed.
