### ISSUE TITLE
Unable to install from open-vsx.org via extension-menu.

### ISSUE THREAD

**Issue by 0xnoob** [VSCodeVim/Vim#6700]
**Describe the bug**
Installing the app in code (the open source build) via the extension-menu results in the following error message:
>Unable to install 'vscode.vim' extension because it is not compatible with the current version of VS Code (version 1.56.2).

However, downloading the latest version of the extension [manually from open-vsx.org](https://open-vsx.org/extension/vscodevim/vim) and installing it via `Extensions: Install from VSIX` works fine.

**To Reproduce**

1.  Go to 'Extensions' search for vim and select it.
2.  Click on 'Vim 1.20.3'
3.  Click on 'install'
4.  >Unable to install 'vscode.vim' extension because it is not compatible with the current version of VS Code (version 1.56.2).

**Expected behavior**
Should successfully install the extension

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.20.3`
- OS Version: `Linux x64 5.12.8-arch1-1`
- VS Code version: `1.56.2`
- 
**Additional context**
As mentioned at the beginning, downloading and installing it from disk works, **but**  if the next version gets released on open-vsx is it going to be automatically updated?

**Comment by hrj-plf** [comment]
I am experiencing the same problem. (Just to confirm that it is reproducible)

**Comment by chrisemke** [comment]
I am experiencing the same problem on vscodium.
```Unable to install 'vscodevim.vim' extension because it is not compatible with the current version of VS Code (version 1.56.2).```

**Comment by wildwestrom** [comment]
> I am experiencing the same problem on vscodium.
> `Unable to install 'vscodevim.vim' extension because it is not compatible with the current version of VS Code (version 1.56.2).`

Second this. Exact same problem with vscodium.

**Comment by ohemelaar** [comment]
A workaround for now is to install an old version. [Download it locally](https://open-vsx.org/api/vscodevim/vim/1.20.2/file/vscodevim.vim-1.20.2.vsix) and run `codium --install-extension vscodevim.vim-1.20.2.vsix`.

**Comment by 0xnoob** [comment]
@ohemelaar As mentioned I was able to download and install even the latest version, does it work for you only with older versions?

**Comment by J-Fields** [comment]
Does the same happen with version `1.21.0`?

**Comment by ohemelaar** [comment]
@0xnoob I'm sorry I read through the issue very quickly and missed that part, so I went for an earlier version as I thought only the later ones would cause problems

**Comment by 0xnoob** [comment]
@J-Fields version `1.21.0` isn't available in the open-vsx registry yet.

**Comment by alekratz** [comment]
I ran into this issue and installing the `1.20.2` version through the CLI worked for me.

**Comment by 0xnoob** [comment]
@J-Fields I successfully installed version `1.21.3` directly from open-vsx today!
