### ISSUE TITLE
need help with remap

### ISSUE THREAD

**Issue by elazarcoh** [VSCodeVim/Vim#6713]
Hi,

*I'm New to vim & vscode-vim.*

I would like to emulate a motion on character `=` as described [here](https://stackoverflow.com/a/32193940).
```
onoremap <silent> = :<C-U>normal! 0f=lv$h
```
I tried with **operatorPendingModeKeyBindingsNonRecursive**, but without success:
```js
{
      "before": ["="],
       "after": [":<C-U>normal! ", "0", "f", "=", "l", "v", "$", "h"]
}
```
probably got it wrong.

can it be done? how?

Thanks

**Comment by honkaboy** [comment]
@elazarcoh this isn't the right place for debugging help. Try the vscodevim slack channel.
