### ISSUE TITLE
User Settings Getting Overridden 

### ISSUE THREAD

**Issue by griffiti** [VSCodeVim/Vim#6717]
**Describe the bug**
User settings has tab size = 2 and insert spaces = true. When enabling Vim extension, tab size gets changed to 8 and insert spaces to false.

**To Reproduce**

1.  Open settings in IDE or settings.json and confirm tab size = 2 and insert spaces = true.
2.  Open file to confirm settings.
3.  Enable Vim extension.
4.  Review settings to see tab size = 8 and insert spaces = false.
5. Close IDE
6. Manually update settings.json and set tab size = 2 and insert spaces = true.
7. Reopen IDE and confirm Vim has overridden settings.

**Expected behavior**
Tab size and insert spaces settings should not be changed by Vim extension.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.0
- VSCode version: 1.56.2
- OS: macOS Big Sur 11.3.1

**Comment by JUNGHUNKIM-7** [comment]
Same Problem! here.

Version: 1.56.2
OS: Windows_NT x64 10.0.19042

**Comment by grahame** [comment]
Same issue here, every time I launch VSCode I get this written in the bottom of my `settings.json`:

```json
"editor.tabSize": 8,
"editor.insertSpaces": false,
"editor.lineNumbers": "on",
"editor.wordSeparators": "/\\()\"':,.;<>~!@#$%^&*|+=[]{}`?-",
```

I think the first time this happened the Vim extension updated while I was editing, and wrote in these new overrides. Led to quite a bit of confusion!

**Comment by minazukie** [comment]
https://github.com/VSCodeVim/Vim/commit/71032855392dd4cdc82c4feb3eb97b38f9e6cebc#diff-86346c1e855d34c045ab18b90232efa97fbfe68e0571fe0435f2a6054879eaa7R310

**Comment by szymonos** [comment]
It's horrible. VSCode is unusable for me with the Vim extension right now because of this. It forces reformatting of all my code and indent rainbow shows bad indenting everywhere.

**Comment by vincentor** [comment]
Is there any workaround to fix it temporarily? This bug waste half of my day and make me crazy!

**Comment by erikgrinaker** [comment]
Downgrade to 1.20 and remove/update the settings in `settings.json`. The dropdown arrow on the "Uninstall" button on the extension page will allow you to install an older version.

**Comment by lucalaissue** [comment]
Same issue here, can we mark this as top priority ?

**Comment by chamabreu** [comment]
Same here. Wasted half a day, too.
On Linux and Mac.

**Comment by anonimoconiglio** [comment]
Same problem here, Gnu/Linux:
```
OS: Manjaro 21.0.6 Ornara
Kernel: x86_64 Linux 5.10.41-1-MANJARO
DE: KDE 5.82.0 / Plasma 5.21.5
```
I solved downgrading to `1.20.3` (same procedure specified by @erikgrinaker )

**Comment by griffiti** [comment]
Yes downgrading to `1.20.3` resolved issue for me as well. Thanks @erikgrinaker .

**Comment by J-Fields** [comment]
Sorry for the inconvenience, all - I'll release a patch later today

**Comment by J-Fields** [comment]
Version `1.21.1` is now available with a fix. Please upgrade and restore any settings that were changed. Sorry again for any inconvenience!

**Comment by griffiti** [comment]
Awesome! That was super fast...thanks for getting that resolved. @J-Fields
