### ISSUE TITLE
Ctrl-E and Ctrl-I stop working as soon as the cursor should move

### ISSUE THREAD

**Issue by alexandrudima** [VSCodeVim/Vim#672]
Testing Microsoft/vscode#11147

VSCode Version 1.5.0-insider
Commit: 18f7fe90aa470ddc632c80388f84bf511afb7078
VSCodeVim Commit: 1185bceee27e09562d63a040808c5dac5227af9b
OS: Windows

Config: `"vim.useCtrlKeys": true`

In these gifs I'm doing Ctrl-E but the exact problem exists for Ctrl-Y.

## Expected
![ctrl-e-expected](https://cloud.githubusercontent.com/assets/5047891/18089481/84070dbe-6ec0-11e6-8fbc-965f65977698.gif)

## Actual
![ctrl-e-actual](https://cloud.githubusercontent.com/assets/5047891/18089518/a51bca4e-6ec0-11e6-8d69-b5915aa2cefa.gif)

**Comment by rebornix** [comment]
Ops, since I'm still seeing problems while executing the newly added `editorScroll` commands, I forgot to merge this into the master branch. will reverify once it's done.
