### ISSUE TITLE
Extension keeps overwriting editor.tabSize and editor.insertSpaces

### ISSUE THREAD

**Issue by ejolly** [VSCodeVim/Vim#6725]
**Describe the bug**

Not matter what settings are in `settings.json`, loading the extension keeps setting:
`"editor.insertSpaces": false` and `"editor.tabSize": 8`. 

I'm not loading from any rc file or modifying the tabs/spaces in any other way (i.e. using `:set` commands). I've confirmed that this is happening with this extension in particular, because disabling it prevents the error. It also doesn't seem to be caused by an interaction between any other extensions, because disabling everything _except_ VSCode vim still produces the error.

It's really screwing with my formatter settings especially in languages like Python that don't like mixed spaces and tabs. 

**To Reproduce**

1.  Open VSCode (with extension disabled)
2.  Click on 'enable extension'
3.  See `"editor.insertSpaces": false` and `"editor.tabSize": 8` instantly appear in `settings.json`

**Expected behavior**
Extension should not be altering these settings at all

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.0
- VSCode version: 1.56.2
- OS: mac OS 10.15.7 (catalina)

**Comment by ejolly** [comment]
Woops sorry @J-Fields just saw 1.21.1 release to address this. My editor doesn't see the version yet, but I'll close it this issue for now and reopen if there are still issues. Thanks!

**Comment by J-Fields** [comment]
Yep, sorry about that!
