### ISSUE TITLE
backspace to un-indent of spaces broken

### ISSUE THREAD

**Issue by woodknight** [VSCodeVim/Vim#6726]
**Describe the bug**
Backspace can not un-indent when VS code set to indent using spaces.

**To Reproduce**

1. set indent using spaces of 4
2. start to edit a new line
3. press tab.
4. press backspace.  

Expect it to delete 4 spaces, but it only deletes 1.

- Extension (VsCodeVim) version: 1.21.1
- VSCode version: 1.57.0
- OS: Mac and Ubuntu

**Comment by J-Fields** [comment]
Duplicate of #1691
