### ISSUE TITLE
Count does not work for scroll commands

### ISSUE THREAD

**Issue by alexandrudima** [VSCodeVim/Vim#673]
Testing Microsoft/vscode#11147

VSCode Version 1.5.0-insider
Commit: 18f7fe90aa470ddc632c80388f84bf511afb7078
VSCodeVim Commit: 1185bceee27e09562d63a040808c5dac5227af9b
OS: Windows

Config: `"vim.useCtrlKeys": true`

I could not get `2 ctrl+e` to scroll down 2 lines. Maybe I missed something, but it also didn't appear to work for:
* `ctrl+e`
* `ctrl+d`
* `ctrl+f`
* `ctrl+y`
* `ctrl+u`
* `ctrl+b`

**Comment by johnfn** [comment]
Count + ctrl-d definitely works on 0.1.7, as does count + ctrl-u. @rebornix did we regress on those two? The others I'll have to test later.

**Comment by rebornix** [comment]
@johnfn @alexandrudima I hold these commands in my separate branch as `vscode.commands.executeCommand("editorScroll")` doesn't work as expected in our code. I've played with other Vim sample code and even created a fresh new extension to call `editorScroll` commands, they all work perfectly. Apparently we have some side effect running this kind of line moving commands in VSCodeVim. For now I don't have any clue except 

```
    // Scroll to position of cursor

    vscode.window.activeTextEditor.revealRange(new vscode.Range(vimState.cursorPosition, vimState.cursorPosition));
```

But seems above code is not the only one that affects `editorScroll`'s behaviors.

**Comment by rebornix** [comment]
It's being fixed one month ago.
