### ISSUE TITLE
Ctrl+D appears to scroll more than half window lines downwards (same as Ctrl+F?)

### ISSUE THREAD

**Issue by alexandrudima** [VSCodeVim/Vim#675]
Testing Microsoft/vscode#11147

VSCode Version 1.5.0-insider
Commit: 18f7fe90aa470ddc632c80388f84bf511afb7078
VSCodeVim Commit: 1185bceee27e09562d63a040808c5dac5227af9b
OS: Windows

Config: `"vim.useCtrlKeys": true`

## Expected
![ctrl-d-expected](https://cloud.githubusercontent.com/assets/5047891/18089789/ea9c43cc-6ec1-11e6-9903-5119e45a3427.gif)

## Actual
 * cursor moves more than 1/2 a screen & the editor is not scrolled

![ctrl-d-actual](https://cloud.githubusercontent.com/assets/5047891/18089796/eec399a0-6ec1-11e6-86ed-add559bea2a6.gif)

**Comment by alexandrudima** [comment]
The exact same problem with Ctrl-U

**Comment by rebornix** [comment]
@alexandrudima it's more or less our workaround before we have `editorScroll`, using 20 lines (Vim's default config) instead of dynamic half page. Since we already have `editorScroll`, this issue should be gone once we fix the side effect issue there.
