### ISSUE TITLE
Opening terminal with Ctrl+J

### ISSUE THREAD

**Issue by willparsons** [VSCodeVim/Vim#6759]
**Describe the bug**
Terminal is not opening.

**To Reproduce**
Ctrl + J. Nothing happens.

**Expected behavior**
Terminal panel opens.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.2
- VSCode version: 1.57.0
- OS: Ubuntu 20.04 lts

**Additional context**
I'm new to vim so I imagine this command is being captured by the extension. However, I can't seem to find anything about how to get around this.

**Comment by northernocean** [comment]
I use VSCode on Ubuntu and I am not familiar with Ctrl-J as a shortcut that would be expected to open a terminal. As far as I can tell this is not a standard keybinding in vanilla vim for opening terminals either.  Was that a custom keybinding you were using? Have you checked your keyboard shortcuts or tried to edit them for opening a terminal?
 
In general I think this is an issue that would be resolved by editing your keybindings or shortcut keys for VSCode or vim. 

You may just want to use a different keybinding to open a terminal (for example, the default shortcut is `` ctrl-shift-` `` and this works fine for me.

For some general tips on control key with vscodevim see here:
https://stackoverflow.com/questions/62405783/how-do-you-avoid-key-binding-collisions-between-vs-code-and-vscodevim

You may want to experiment with the control keys setting. But this would could negatively affect other standard vim keybinding (such as ctrl-r for undo). see settings info here: 
https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

**Comment by bootandy** [comment]
Can't you just delete the 'Ctrl+j' shortcut in keyboard settings ?

**Comment by willparsons** [comment]
Ctrl+J is a standard shortcut - as far as I know - it just opens the terminal panel or if none exists spawns a new terminal. You're right though, I should have just gone into keybindings and set it up. Closing this issue since it's my fault.

**Comment by davidcallanan** [comment]
How can we stop Ctrl+J from opening terminal?

Currently, I am trying to use Ctrl+J to unfocus the "Find" textbox after pressing Ctrl+F.

But this opens the terminal in addition for some reason.

I can't find any keyboard shortcut to disable that relates to the terminal:

![image](https://user-images.githubusercontent.com/40340425/163670564-cc250f5b-5186-4ea9-8138-23efab220723.png)

**Comment by zchrissirhcz** [comment]
> 

Thank for the related SO question and answer, now I switched to Neovim plugin and it works as I expected.
