### ISSUE TITLE
z+t and z+b not adopted

### ISSUE THREAD

**Issue by alexandrudima** [VSCodeVim/Vim#677]
Testing Microsoft/vscode#11147

VSCode Version 1.5.0-insider
Commit: 18f7fe90aa470ddc632c80388f84bf511afb7078
VSCodeVim Commit: 1185bceee27e09562d63a040808c5dac5227af9b
OS: Windows

Config: `"vim.useCtrlKeys": true`

`z`+`t`, `z`+`b` don't appear to do anything

**Comment by johnfn** [comment]
Whoa, didn't realize that this was possible now. Thanks for the heads up, @alexandrudima! (Also, thanks for all the issues recently!)

**Comment by jpoon** [comment]
Related Issue: https://github.com/VSCodeVim/Vim/issues/210
