### ISSUE TITLE
Failed to add / remove indentation

### ISSUE THREAD

**Issue by chioio** [VSCodeVim/Vim#6787]
**Describe the bug**
When I press the `shift + >` (`.`) to add indentation first and then I press `>` (`.`) to add more, then I press `shift + <` (`,`) to remove indentation and then I press `>` (`.`), it remove indentation as well, but I press '<` (`,`) not work. Does this is a bug?

**To Reproduce**

1.  Press `shift + >` to add indentation.
2.  Then press `>` also works.
3.  Press `shift + <` to remove one indentation.
4.  Press `>` (`.`) also works to remove the indentations.

**Expected behavior**
I think it should worked when I press `<` (`,`) to remove indentations after I press `shift + <`.

**Environment:**

- Extension (VsCodeVim) version: v1.21.3
- VSCode version: 1.57.0
- OS: Darwin x64

**Comment by J-Fields** [comment]
I'm confused. `>>` should increase indentation and `<<` should decrease indentation. Are you seeing something else? Can you clarify exact keystokes you're using?

**Comment by chioio** [comment]
Sorry, it seems not a bug. 😅
