### ISSUE TITLE
Vim: <kbd>ctrl</kbd> + <kbd>d</kbd> doesn't work

### ISSUE THREAD

**Issue by sandy081** [VSCodeVim/Vim#679]
_From @weinand on August 30, 2016 9:50_

testing #11127:

<kbd>ctrl</kbd> + <kbd>d</kbd> and 🔢 <kbd>ctrl</kbd> + <kbd>d</kbd> neither work on macOS nor on Windows 10 (I'm using a Swiss-German keyboard).

_Copied from original issue: Microsoft/vscode#11180_

**Comment by sandy081** [comment]
<kbd>ctrl</kbd> + <kbd>d</kbd> works for me with US and Swiss-German keyboards. We have an editor command in VS Code and our Vim sample binds this keys to this keys. I do not know where the issue is. 

Let me change the key binding and check

**Comment by weinand** [comment]
@sandy081 I'm using a real Swiss-German keyboard whereas @sandy081 just simulated a Swiss-German keyboard on a US keyboard.

**Comment by johnfn** [comment]
Very strange! We just bind to ctrl-d, so I'm not sure where the problem is.

**Comment by johnfn** [comment]
I'm pretty sure this is not a problem?
