### ISSUE TITLE
va" and ya" includes spaces and tabs before quote

### ISSUE THREAD

**Issue by boenshao** [VSCodeVim/Vim#6800]
**Describe the bug**
When quoted (" or ') content is prepended with spaces or tabs, visual select (`va"`, `va'`) and yank (`ya"`, `ya'`) would incorrectly includes the spaces or tabs.

**To Reproduce**

1.  `echo "  \"quoted after spaces\"\n\t'quoted after tab'" > test.txt`
2.  `code test.txt`
3.  navigate inside the quotes
4.  `va"`, `va'`, `ya"` or `ya'`

**Expected behavior**
Visual select (or yank) the content (include the quotes), but exclude spaces or tabs before the quote.

**Screenshots**
<img width="263" alt="image" src="https://user-images.githubusercontent.com/65853605/123550207-21b1bb80-d79f-11eb-9a1b-c3af04f994a2.png">

- Extension (VsCodeVim) version: 1.21.3
- VSCode version:  1.57.1
- OS: macOS 11.4 and Ubuntu 20.10

**Comment by J-Fields** [comment]
Actually, this is expected behavior. From `:help a"`:
> Any trailing white space is included, unless there is none, then leading white space is included.

However, in Vim you can achieve the behavior you want by mapping `a"` to `2i"` (and similar for the other quotes). We don't yet support this special case, but I've created #6806, which I'll try to get in the next release.

**Comment by jonboiser** [comment]
> However, in Vim you can achieve the behavior you want by mapping `a"` to `2i"` (and similar for the other quotes).

These are the settings you can use to achieve this, if anybody is coming across this issue.

```
    "vim.operatorPendingModeKeyBindingsNonRecursive": [
        {
            "before": ["a","\""],
            "after": ["2", "i", "\""]
        },
        {
            "before": ["a","'"],
            "after": ["2", "i", "'"]
        },
        {
            "before": ["a","`"],
            "after": ["2", "i", "`"]
        },
    ],

```

**Comment by jonboiser** [comment]
> However, in Vim you can achieve the behavior you want by mapping `a"` to `2i"`

This is what I did to get this working, if any one comes across this.

```
    "vim.visualModeKeyBindings": [
        {
            "before": ["a","\""],
            "after": ["2", "i", "\""]
        },
        {
            "before": ["a","'"],
            "after": ["2", "i", "'"]
        },
        {
            "before": ["a","`"],
            "after": ["2", "i", "`"]
        },
    ]
```

**Comment by laggardkernel** [comment]
That is how `va"` works

- https://vi.stackexchange.com/a/6144/20090
- https://github.com/tpope/vim-surround/issues/276


```
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": ["a","\""],
      "after": ["2", "i", "\""]
    },
    {
        "before": ["a","'"],
        "after": ["2", "i", "'"]
    },
    {
        "before": ["a","`"],
        "after": ["2", "i", "`"]
    },
  ].
  "vim.normalModeKeyBindings": [
    // https://github.com/tpope/vim-surround/issues/276. nmap but not nnoremap
    {
      "before": ["y", "s", "a","\""],
      "after": ["y", "s", "2", "i", "\""]
    },
    {
        "before": ["y", "s", "a","'"],
        "after": ["y", "s", "2", "i", "'"]
    },
    {
        "before": ["y", "s", "a","`"],
        "after": ["y", "s", "2", "i", "`"]
    },
  ],
```
