### ISSUE TITLE
Can't use it with Github Codespaces (or any VSCode web solution)

### ISSUE THREAD

**Issue by delucca** [VSCodeVim/Vim#6826]
**Describe the bug**
Hi. We cannot use this extension with Github Codespaces or any VSCode web solutions (like code-server).

After the most recent updates on VSCode, now extensions should report their `kind`. So, if we try to install this extension directly from the marketplace, it simply won't start and throws us this error:
```
[2021-07-04 18:54:49.980] [window] [error] Cannot install 'Vim' because this extension is not a web extension.: installFromGallery@https://vscodeweb.azureedge.net/stable/507ce72a4466fbb27b715c3722558bb15afa9f48/out/vs/workbench/workbench.web.api.js:1785:27284
```

If we change our `settings.json` to the following:
```json
    "remote.extensionKind": {
      "vscodevim.vim": ["workspace"]
    },
```

Now it installs, but it is **extremely** slow since with this config the extensions is being handled in the remote host, so basically any `j,k` or whatever command is sent to the remote host instead of being resolved locally.

If we change the `settings.json` to:
```json
    "remote.extensionKind": {
      "vscodevim.vim": ["ui"]
    },
```

It doesn't work. We receive an error saying that this extensions cannot be installed.

**Comment by bmarden** [comment]
I'm having this issue as well, is there any solution to this? It makes the extension essentially unusable when using code-server.

**Comment by bhavitsharma** [comment]
+1 any workarounds for this? Installing it remotely makes the UI very slow.

**Comment by jsjoeio** [comment]
It looks like VS Code just came out with a [Web Extensions guide](https://code.visualstudio.com/api/extension-guides/web-extensions). Hoping that will help provide information for moving this forward. Happy to beta test or help in other ways!

**Comment by TooTallNate** [comment]
I'm also happy to help test any solution here. Running into the same issue.

Thanks @delucca for posting the config workaround to get it working remotely. Better than nothing for me (yes, I literally can't code without vim keybindings anymore 😂).

**Comment by PinkFlufflyLlama** [comment]
Is there an update on this or an explanation on what exactly doesn't work? The extension installs as a web/browser extension in codespaces, but does not seem to work at all.

**Comment by Tymon42** [comment]
I try to install an old version(like v1.21.3), and it works well.  
[There](https://vdn1.vzuu.com/SD/85cd3a18-233b-11eb-a9c4-1a26633c03fe.mp4?disable_local_cache=1&auth_key=1634439368-0-0-3fbbd5369f6aade761742126cd94d7bc&f=mp4&bu=pico&expiration=1634439368&v=hw) is a gif-guide for installing old version extension.  
Maybe we could wait the olution patiently.

**Comment by Tymon42** [comment]
> I try to install an old version(like v1.21.3), and it works well.  
> 
> [There](https://vdn1.vzuu.com/SD/85cd3a18-233b-11eb-a9c4-1a26633c03fe.mp4?disable_local_cache=1&auth_key=1634439368-0-0-3fbbd5369f6aade761742126cd94d7bc&f=mp4&bu=pico&expiration=1634439368&v=hw) is a gif-guide for installing old version extension.  
> 
> Maybe we could wait for the solution patiently.

Don't work for Safari on iPad Pro.

**Comment by deme0607** [comment]
I installed the extension for code-server via CLI, and it works.

```
$ code-server --install-extension vscodevim.vim
Installing extensions...
Installing extension 'vscodevim.vim'...
Extension 'vscodevim.vim' v1.21.8 was successfully installed.
```

> code-server: v3.12.0
> VS Code: v1.60.0
> Commit: b37ff28a0a582aee84a8f961755d0cb40a4081db
> Date: 2021-09-16T20:08:09Z
> Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

**Comment by bhavitsharma** [comment]
May I suggest using gitpod-io/openvscode-server. It runs vim extension in the browser and it is snappy!

**Comment by J-Fields** [comment]
This should be fixed in 1.29.1 - please let me know if you're still having this issue on the latest version.

**Comment by kevinaud** [comment]
Not working for me either, maybe there was a regression?

**Comment by ludovic-tc** [comment]
I am unable to see any benefit from installing vscode.vim 1.30.1 on a GitHub CodeSpace.

But I've realised I can just run Vim in the online VSCode terminal! Yay!
