### ISSUE TITLE
Exclude `:w`, `:q`, and `:wq` from dot command

### ISSUE THREAD

**Issue by pangteypiyush** [VSCodeVim/Vim#6829]
**Describe the bug**
Dot command is able to repeat write (`:w`), close (`:q`) and write + close (`:wq`).

**To Reproduce**

Write:
1.  Open a file
2.  Go to insert mode and type `hello`
3.  Exit insert mode and write changes to file `:w`
4.  Type `.`

Close/write+close:
1.  Open a file
2.  Go to insert mode and type `hello`
3.  Exit insert mode
4. Use `:wq` or `:q!`
5. Reopen the buffer and type `.`

**Expected behavior**
Write, close and write+close should be excluded from dot command.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `v1.21.4`
- VSCode version: `v1.57.1`
- OS: `Linux`

**Comment by linw789** [comment]
The expected behavior is: Write, close and write+close should be excluded from dot command. 

But the merged change excluded also the content of insertion. Is this the correct fix?

**Comment by J-Fields** [comment]
@linw789 Can you clarify what you mean?

**Comment by linw789** [comment]
This issue was about commands ":w" and ":q" being included in the "." command. The merged change fixed that, but it also seems to exclude the content of previous insertion from "." command after ":w", which is what's described in #7378.

**Comment by J-Fields** [comment]
I'm not sure how this and #7378 are different issues. I'm dogfooding the current master which includes this fix and can't see any regression, which is what you seem to be implying.

Are you reading the code and coming to this conclusion, or running it and coming to this conclusion? If the former, I think you're mistaken. If the latter, please show a minimal repro case with exact keystrokes.

**Comment by linw789** [comment]
Sorry, I misread the timeline. I thought this change was already in, and I'm still seeing the misbehavior. Sorry about the confusion.

**Comment by J-Fields** [comment]
Ah! No trouble, I'm hoping to get a release out soon

**Comment by linw789** [comment]
Thank you and @justalmill for taking care of this! It's been a big pain point.

**Comment by KoushikSahu** [comment]
@J-Fields Any expected date for when the release will come out with this update?
