### ISSUE TITLE
In insert mode, should remove leading spaces if <ESC> or <Ctrl-c> is pressed

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#685]
### What did you do?

For this file, in insert mode:
```js
function foo() {
  var bar = 1;
  |
}
```

### What did you expect to happen?

If I press `<ESC>` or `<Ctrl-c>`, it should be:
```js
function foo() {
  var bar = 1;
|
}
```

### What happened instead?

```js
function foo() {
  var bar = 1;
 |
}
```

It's in normal mode. The third line has two spaces. Cursor is on second space.

### Technical details:

* VSCode Version: 1.4.0 
* VsCodeVim Version: 0.1.7
* OS: OS X 10.11.6

**Comment by jpoon** [comment]
I think this *is* the expected behaviour. I tried the same thing on vanilla `vim` and vscodevim operates the same way.

**Comment by octref** [comment]
@jpoon 
I guess you were using `vim --noplugin`. Leaving trailing spaces indeed is the behavior for files with unspecified types.

Try using `vim --noplugin test.py` or `vim --noplugin test.js` etc. No trailing space is the behavior.

**Comment by rebornix** [comment]
I ran into this issue as well, the variant of Vim I'm using is `VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Apr  5 2016 14:53:37)` on mac.
