### ISSUE TITLE
cc should go to indentation level

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#686]
### What did you do?

For this file, in normal mode:
```js
function foo() {
  var bar = 1;
|
}
```

### What did you expect to happen?

Press `cc`. It should be 

```js
function foo() {
  var bar = 1;
  |
}
```

in insert mode.

### What happened instead?

```js
function foo() {
  var bar = 1;
|
}
```

in insert mode.

### Technical details:

* VSCode Version: 1.4.0 
* VsCodeVim Version: 0.1.7
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
You actually have to turn on autoindent in your settings.json file. `"vim.autoindent": true`

**Comment by octref** [comment]
Thanks for letting me know the option! Seems not released yet. I'll try that for next version.

**Comment by johnfn** [comment]
😄  you can also pull down the code and compile it. 

We'll need to add this to our README before we release 0.1.8

**Comment by matheusrocha89** [comment]
I tried this but still the same behavior. I saw on docs that the default value is `true` but I put on the settings anyway to test but still with the same behavior described above. @johnfn I need to do anything more?
