### ISSUE TITLE
Screen delay when J,k keys is down

### ISSUE THREAD

**Issue by caiocutrim** [VSCodeVim/Vim#687]
I've noticed two issues that is closely looks like that.
When scrolling many lines (twenty closely) the screen get delay and the cursor is blocking...
Another thing is when I tip :12 to go until line 12 the cursor don't will go...except when I pressed any key the cursor will go to the line.

**Comment by johnfn** [comment]
Could you open up another issue for the :12 thing? 😉 

The screen delay MIGHT be fixed soon!

**Comment by caiocutrim** [comment]
ohh I'm sorry, I guess the behavior is because the cursor is blocking...

**Comment by johnfn** [comment]
you're thinking along the right lines :) i believe the problem is that we do NOT block on keystrokes so multiple can run at the same time, leading to race conditions. i have a fix for this in a branch that i hope to merge soon!

**Comment by 3jr** [comment]
@johnfn  I believe this is fixed. Thanks a lot.

**Comment by johnfn** [comment]
Lovely! Thanks for letting me know. :)
