### ISSUE TITLE
How to set :sort with keybinding?

### ISSUE THREAD

**Issue by QimatLuo** [VSCodeVim/Vim#6889]
I want to be able to use V to select some lines of code, then use hotkey <SPACE>s to sort these lines.
In my .vimrc setting is:
```
vnoremap <SPACE>s :sort<CR>
```
So I try to setup in vscode is:
```
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["<SPACE>", "s"],
            "after": ["<CR>"],
            "commands": [":sort"]
        }
    ],
```

I have tried not use `"after"`, or not use `"<CR>"` or add `"'<,'>"` not really works.
Please help me correct my setting.

**Comment by QimatLuo** [comment]
I fixed by:
```
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": ["<SPACE>", "s"],
            "after": [":", "s", "o", "r", "t", "<CR>"]
        }
    ],
```

But is this the correct way to do?
Separate "s", "o", "r", "t" is weird to me.

**Comment by karizma** [comment]
Yea that's the correct way to do it, `commands` is for vscode commands not vim.
