### ISSUE TITLE
p)ut following y)ank from marked position inserts at cursor position instead of next line

### ISSUE THREAD

**Issue by Deracination** [VSCodeVim/Vim#689]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Mark location (ma)
Navigate down file
Yank to the position (y'a)
Navigate to another position and put the yanked text (p)

### What did you expect to happen?
Expect the yanked text to be inserted on the line below the cursor position

### What happened instead?
Yanked text in inserted at the current cursor position within the line

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Windows

**Comment by johnfn** [comment]
I don't disagree that this is the desired behavior, but where on earth is that \n coming from? I'm totally confused by why Vim decides to put a \n in there.

**Comment by Deracination** [comment]
Vim appears to do an 'o' then 'p' if the buffer contains an eol. It inserts at the cursor position if there is no eol in the buffer.

**Comment by rebornix** [comment]
marks with operators are likely LinseWise.
