### ISSUE TITLE
Reducing a number to 0 with Ctrl + x deletes adjacent dash

### ISSUE THREAD

**Issue by TheNomadicAspie** [VSCodeVim/Vim#6896]
I have several variables named like this:

test_var-4

If I use Ctrl + x to reduce the number to 0, it will delete the dash and become test_var0. Is that expected behavior or a bug?

**Comment by northernocean** [comment]
Hi yes this is expected behavior. Vim treats your number as -4, not just 4. Ctrl-x is actually increasing the number (-3, -2, -1 then 0, 1, 2,).

**Comment by TheNomadicAspie** [comment]
I didn't even think about it in that sense, thanks for the explanation.
