### ISSUE TITLE
~ to change case followed by . to repeat command unexpectedly repeats previous action, not ~

### ISSUE THREAD

**Issue by Deracination** [VSCodeVim/Vim#690]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Position cursor on text
Type tilde to invert case of character under cursor (~)
Navigate to another line with mouse
Type '.' to repeat last action (~)

### What did you expect to happen?
I expected '.' to repeat the ~ action and change the case of the character under the cursor

### What happened instead?
The entire line under the cursor was deleted as this repeated an earlier 'dd', not the ~ action.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Windows

**Comment by jpoon** [comment]
Thanks for the bug report. Looks like `~` isn't being set as a repeatable action, therefore when you try to do `.`, it does whatever action you did *before* `~` which in your case must have been a `dd`.

**Comment by Deracination** [comment]
Yes, that is exactly what is happening

**Comment by xconverge** [comment]
I am fixing this right now

**Comment by xconverge** [comment]
And a few other toggle case issues :)
