### ISSUE TITLE
Simple copy-paste key bindings don't work in --INSERT-- mode

### ISSUE THREAD

**Issue by mrcat323** [VSCodeVim/Vim#6914]
**Describe the bug**
While coding, in `--INSERT--` mode, I can't copy with `Ctrl-C` and paste with `Ctrl-V`, everytime I need to click on the right button of the mouse and choose *Copy* to copy and *Paste* to paste

**Expected behavior**
Simple copy-pasting stuff

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.
![image](https://user-images.githubusercontent.com/23054662/126982256-5062e5a0-03fa-45e1-be94-7c8a2a735c4e.png)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.21.5
- VSCode version: v1.58.2
- OS: Debian 10 (Buster)

**Additional context**
Everytime I need to use mouse or `--NORMAL--` mode, and that's uncomfortable

**Comment by northernocean** [comment]
Hi, you should be able to get the desired behavior by adjusting your settings. Probably via setting the `useCtrlKeys` setting or providing additional configuration using the `handleKeys` setting.
More information is here: https://github.com/VSCodeVim/Vim#vscodevim-settings

For example, I just added this to my settings.json and it seems to get what you want:
```
     "vim.handleKeys": {
         "<C-c>": false,
         "<C-v>": false
     }
```

**Comment by mrcat323** [comment]
Thank you very much guys, it's like you saved a year of mine by providing this kind of information :ok_hand:
