### ISSUE TITLE
Make "gd" Open definition to the side in Search Editor 

### ISSUE THREAD

**Issue by shogunsea** [VSCodeVim/Vim#6921]
**Is your feature request related to a problem? Please describe.**

The default Search Editor supports open definition to the side:
> In a Search Editor, results can be navigated to using Go to Definition actions, such as F12 to open the source location in the current editor group, or ⌘K F12 to open the location in an editor to the side.
![search-editor-triggers](https://user-images.githubusercontent.com/2238944/127264605-6476a11f-1b0c-4f3f-b650-760957160132.gif)

**Describe the solution you'd like**

`gd` will jump to the definition in a new tab, would be great if there can be opt-in settings to make it open to the side. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by w-cantin** [comment]
Hi, 

If you want it is possible to remap keys to execute native VSCode commands and not just vim commands. In your case the command that you want is called "editor.action.revealDefinitionAside". In my settings.json in normalModeKeyBindingsNonRecursive I added this entry: 

`
 {
      "before": ["g", "d"],
      "commands": ["editor.action.revealDefinitionAside"]
    },
`

If you ever want to remap other vscode actions you can use the keyboard shortcuts command and search directly there. I hope that helped

**Comment by shogunsea** [comment]
@w-cantin  that works like a charm! this setting will open everything in sidebar but I only wanted this behavior in search editor, so I modified to 
```
{ "before": ["g", "D"], "commands": ["editor.action.revealDefinitionAside"] },
```
thanks a lot
