### ISSUE TITLE
repeat dot command no longer works after saving

### ISSUE THREAD

**Issue by js-musedev** [VSCodeVim/Vim#6924]
**Describe the bug**
Since a recent update, after saving a file, the dot command doesn't work.

**To Reproduce**

- Make an edit to a file.
- Press . (dot) in insert mode, see that the edit is repeated.
- Save the file. Press . (dot), nothing happens.

**Expected behavior**
The dot repeat command should continue to work after saving a file.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.21.5
- VSCode version: 1.58.2
- OS: debian

**Comment by tjfulle** [comment]
This is a *major* productivity killer.

**Comment by Pratyush** [comment]
I believe this is the same issue as https://github.com/VSCodeVim/Vim/issues/6829 (I am also experiencing this bug)

**Comment by J-Fields** [comment]
Duplicate of #6829
