### ISSUE TITLE
Status bar shows -- NORMAL -- but no commands working

### ISSUE THREAD

**Issue by krislitman** [VSCodeVim/Vim#6929]
Have latest version of vscodevim installed, and today it just stopped accepting commands. The status bar shows --NORMAL-- when loading a file, but acts just like normal vscode. I get an error that command 'toggleVim' not found even though a shortcut is defined in my keyboard shortcuts json file. Have tried deleting the extension settings in ~/.vscode/extensions, but that did not fix it after reinstalling. 

**Expected behavior**
Expected to be in NORMAL mode, but it is just default vscode behavior. 

- Extension (VsCodeVim) version: 1.21.5
- VSCode version: 1.58.2
- OS: Big Sur 11.4

**Comment by northernocean** [comment]
Can you investigate if other extensions are incompatible with Vim? In the past a rust extension was identified as a source of such a problem.

**Comment by krislitman** [comment]
@northernocean thank you! I disabled all my extensions and then vim was working, so I went through each extension and it seemed 'Indent to Bracket' was causing vim to fail.
