### ISSUE TITLE
Delete then p/P doesn't paste correctly

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#693]
### What did you do?

For the following file:

```
|{
  "a": 1
}
```

Run `VGdp` or `VGdP`.

### What did you expect to happen?

`VGdp`:

```
// Empty line here
|{
  "a": 1
}
```

`VGdP`:

```
|{
  "a": 1
}
// Empty line here
```

### What happened instead?

`VGdp`:

```
// Empty line here
|{
  "a": 1
// Empty line here
```

`VGdP`:

```
|{
  "a": 1
// Empty line here
// Empty line here
```

### Technical details:

* VSCode Version: 1.4.0 
* VsCodeVim Version: 0.1.7
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
How strange. Appears to be a bug related to selecting/deleting the entire file.
