### ISSUE TITLE
Neovim path error

### ISSUE THREAD

**Issue by TryerGit** [VSCodeVim/Vim#6939]
Hello,

I have a windows machine on which windows subsystem for linux (WSL) is installed. On setting path to nvim.exe in windows, and enabling neovim (both in user settings which by default maps to \AppData\Roaming\Code\User\settings.json in windows), the project open just fine.

On opening the same project from within WSL and providing path as /usr/bin/nvim in Remote [WSL: Ubuntu-20.04] (which maps by default to file \.vscode-server\data\Machine\settings.json), the following error is obtained:

Configuration: Invalid neovimPath. spawnSync /usr/bin/nvim ENOENT.

This is after I verify in the WSL terminal via `whereis nvim` that nvim is indeed installed. The output of this is:

nvim: /usr/bin/nvim /usr/share/nvim /usr/share/man/man1/nvim.1.gz

indicating that atleast nvim is installed. Typing nvim also opens the neovim terminal.

Is there any setting that I am getting wrong?

Thanks.

**Comment by tommyc38** [comment]
I have this same issue.

**Comment by cspotcode** [comment]
It seems you need to use the path to neovim in your windows host, not in WSL.  You need to do this even though you're putting it in your WSL settings.json.

**Comment by TryerGit** [comment]
> It seems you need to use the path to neovim in your windows host, not in WSL. You need to do this even though you're putting it in your WSL settings.json.

Indeed, this works.

So, now, my 

\\wsl$\Ubuntu-20.04\home\TryerGit\.vscode-server\data\Machine\settings.json file has lines:

```
 "vim.enableNeovim": true,
  // "vim.neovimPath": "/usr/bin/nvim",    <----- commented out
  "vim.neovimPath": "C:\\Users\\TryerGit\\Downloads\\nvim-win64\\Neovim\\bin\\nvim.exe"  <---- added new

```

and the annoying error message goes away. :-)

Thanks!
