### ISSUE TITLE
cw not delimited by quote characters

### ISSUE THREAD

**Issue by Deracination** [VSCodeVim/Vim#695]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
position cursor on letter 'a' of text abc"

type 'cw'

### What did you expect to happen?
I expected 'cw' to select and delete 'abc' but not include the " quote character

### What happened instead?
cw included the quote in the deleted selection

The same problem occurs for single quote

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Windows

**Comment by sectioneight** [comment]
I can't repro this on v0.1.7 or on master on my mac. Keys pressed:

`i`, `aoeu"`, `0`, `cw`

and `cW` on the second line

![](http://g.recordit.co/wHo1P5mGW4.gif)

**Comment by Deracination** [comment]
Odd - issue seems to have gone away! Can't reproduce in 0.1.8
