### ISSUE TITLE
Undo is not doing great job

### ISSUE THREAD

**Issue by sidsadaam** [VSCodeVim/Vim#6958]
i was doing things in vscode using vim but when i undo it more often i did some weird stuff by putting stuff here and there. But i furured out to map the "u" key in normal Mode(command mode) to "unod" undo is the vscode command to undo 
        { "before": ["u"], "commands": ["undo"] },
this is the binding i don't know if vim was using this command or not by default but when i did this it didn't do the weird things again can you make this command as default to vim its going to be very helpful.

NOTE: I don't know if vim uses the vscode undo command or not thats why i am requesting this

**Comment by w-cantin** [comment]
Vim by default uses another undo history from VSCode's. To make it more consistent you can make use VSCode commands for undo (u) and redo (U) like so:  

```json
    {
      "before": ["u"],
      "commands":["undo"]
    },
    {
      "before": ["U"],
      "commands": ["redo"]
    },
```

If you wanted to use vim's undo/redo history you could instead use the following: 

```json
 {
      "before": ["u"],
      "after": ["u"]
    },
    {
      "before": ["U"],
      "after": ["<C-r>"]
    },
```

Note that I like using U to redo but you can change the keys for anything you like.
