### ISSUE TITLE
Undo doesn't work in Notebook Cell

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#6960]
Originally reported in https://github.com/microsoft/vscode/issues/130142. Undo doesn't work in notebook.

**Comment by northernocean** [comment]
Just a note but there was a recent change in 1.59.0 that may be related:

From the release notes for Notebook layout improvements:

The default value of `notebook.undoRedoPerCell` is now changed to `true`.

**Comment by oponkork** [comment]
Any updates on this issue?

**Comment by Chrobin111** [comment]
Using version 1.21.8, I still encounter this issue. Any updates?

**Comment by aromatt** [comment]
Does anyone have a workaround for this in the meantime?

**Comment by edemaine** [comment]
The classic undo (Ctrl-Z on Windows) works, so that's what I use as a workaround in notebooks. But it doesn't always interact well with Vim commands.

**Comment by aromatt** [comment]
Thanks, @edemaine - that's what I'm doing for now too. I spent a few minutes trying to adjust configs so that the `u` vim binding works. Maybe it's easy, but I don't know enough about VS Code or these extensions.

**Comment by yannickdaniel** [comment]
I'm also interested in a solution / workaround. @aromatt did you find a fix yet?

**Comment by aromatt** [comment]
@yannickdaniel sorry to say I did not.
