### ISSUE TITLE
yank to marker (for example y'a) should include current line

### ISSUE THREAD

**Issue by Deracination** [VSCodeVim/Vim#697]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Set a marker (ma)
Move down the file
Yank to the marker (y'a)

### What did you expect to happen?
I expected all lines from current line to marked line to be yanked to buffer

### What happened instead?
Instead all lines from the line _above_ the current line to marker were yanked, excluding the current line

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Windows

**Comment by rebornix** [comment]
It's fixed when I fix the `p` issue. Check 0.4.0.
