### ISSUE TITLE
. does not work correctly with visual block selections

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#699]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

te|sttest
testtest

ctrl + v to enter visual block, select 2 chars and BOTH lines (4 chars total), press x to cut. Move to another area, press "dot". Only 1 char is cut.

### What did you expect to happen?

The same size block to have an action applied on it

### What happened instead?

Only a single column was acted on, not the full width of the selection

**Comment by rebornix** [comment]
Seems my refactor on repeating changes has a huge side effect, this one is fixed as well.
