### ISSUE TITLE
`:delete` and `:yank` should support `{count}` argument

### ISSUE THREAD

**Issue by J-Fields** [VSCodeVim/Vim#6995]
For example, `:y4` should yank 4 lines

**Comment by DevinLeamy** [comment]
@J-Fields 
Currently, the first (and only) argument passed into both the `DeleteRangeCommand` and the `YankCommand` are register names - if an argument exists at all. So when `:y4` is called, then `{ register: '4' }`. To accommodate a count argument, can we assume that the first argument passed in will always be a count. As in:
```ts
/**
   * Note that to specify a register, a [cnt] for :d[elete][cnt]
   * must be specified.
   * Ex: :d4 i -> specifies register i
   *     :d  i -> does not specify a register
   */
  const scanner = new Scanner(args);
  return new node.DeleteRangeCommand({
    linesToRemove: +scanner.nextWord() ?? 1,
    register: scanner.isAtEof ? undefined : scanner.nextWord(),
  });
```

**Comment by J-Fields** [comment]
I'm away from my PC at the moment so I can't check, but I thought the first argument was the register, unless it's a number, in which case it's used as the count.
How does Vim interpret `:y 4 x` and `:y 4 7`?

**Comment by DevinLeamy** [comment]
_"I thought the first argument was the register, unless it's a number, in which case it's used as the count."_  - Just tested, this is correct.

`:y 4 x` and `:y 4 7` don't work. 

```
:[range]y[ank] [x]	Yank [range] lines [into register x]. Yanking to the
			"* or "+ registers is possible only when the
			|+clipboard| feature is included.

:[range]y[ank] [x] {count}
			Yank {count} lines, starting with last line number
			in [range] (default: current line |cmdline-ranges|),
			[into register x].

```
