### ISSUE TITLE
Shouldn't be able to move the cursor past the last character in a line

### ISSUE THREAD

**Issue by markrendle** [VSCodeVim/Vim#70]
In Normal Mode, the built-in "line" cursor should be restricted to just before the last character.

**Comment by markrendle** [comment]
I don't know whether to add this restriction to #69 or handle it separately...?

**Comment by jpoon** [comment]
Thanks. I was noticing it when I was writing tests https://github.com/VSCodeVim/Vim/commit/27f52976371d8cc8c423b78a373bee30a2c7963b.

@kimitake has PR https://github.com/VSCodeVim/Vim/pull/68 that fixes this -- I'm hoping he can fix the merge conflicts :)

**Comment by kimitake** [comment]
just fixed conflict error.

**Comment by jpoon** [comment]
We have tests that confirm that this has been fixed.
