### ISSUE TITLE
Can't leave insert mode (pressing ESC) on GitHub Codespace

### ISSUE THREAD

**Issue by MicaelJarniac** [VSCodeVim/Vim#7005]
**Describe the bug**
Can't leave insert mode (pressing ESC) on GitHub Codespace

**To Reproduce**

1.  Go to a GitHub repository (on https://github.com), like https://github.com/VSCodeVim/Vim
2.  Press the dot <kbd>.</kbd> key (should take you to https://github.dev/[...], like https://github.dev/VSCodeVim/Vim)
3.  Go to the Extensions tab
4.  Search for `vscodevim.vim` and install it
5. Go back to the Explorer tab
6. Open any file (like `README.md`)
7. Click on the text so as to set focus to it
8. Verify normal Vim navigation works (<kbd>h</kbd>, <kbd>j</kbd>, <kbd>k</kbd>, <kbd>l</kbd>)
9. Enter insert mode (<kbd>i</kbd>)
10. Verify inserting text works
11. Try to leave insert mode by pressing <kbd>ESC</kbd>
12. Verify you're still in insert mode, and focus has been lost from the editor
13. Click back on the text to set focus to it again
14. Repeat steps 10 to 12 as many times as desired
15. Give up

**Expected behavior**
When in insert mode (or any mode, for that matter), pressing <kbd>ESC</kbd> shouldn't break focus from the editor.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.21.6
- VSCode version: 1.59.0
- OS: Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36

**Comment by ShonFrazier** [comment]
Seems to me this is more "vscodevim.vim not functioning in any way in Codespaces"

**Comment by amosturchet** [comment]
Having the same issue on the VSCode app (OSX version) with any file I try to modify.

**Comment by MicaelJarniac** [comment]
I believe the <kbd>ESC</kbd> key is working as it should without the extension:

![GIF](https://thumbs.gfycat.com/FlakyEntireFlatfish-size_restricted.gif)

On the GIF, I was typing on the editor, then bringing up that box with <kbd><kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>p</kbd></kbd>, typing on it, then hitting <kbd>ESC</kbd> to exit it, and the focus was correctly restored to the document, without me having to click it.

Might be worth mentioning, the browser I use is Vivaldi, based on Chromium.

**Comment by thisisphan** [comment]
You most likely have a browser vim emulator like [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en), and it's capturing your inputs.

#### Solution
Disable Vimium on github.dev


#### Details
Why does the escape key work in the command palette but not the editor?
- Vimium stops capturing keys when you're in a text prompt.
- Vimium does not see the editor as a text prompt. -> Input is captured.
- Vimium sees the command palette as a text prompt. -> Input is released.

@MicaelJarniac

**Comment by MicaelJarniac** [comment]
@thisisphan I was not using any extension like that, so I don't think that's exactly what was going on, but thanks for the suggestion.

**Comment by dbanks12** [comment]
> You most likely have a browser Vim emulator like [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en), and it's capturing your inputs.
> #### Solution
> 
> Disable Vimium on github.dev
> #### Details
> 
> Why does the escape key work in the command palette but not the editor?
> 
>     * Vimium stops capturing keys when you're in a text prompt.
> 
>     * Vimium does not see the editor as a text prompt. -> Input is captured.
> 
>     * Vimium sees the command palette as a text prompt. -> Input is released.
> 
> 
> @MicaelJarniac

You just solved a tangentially related issue of mine where Vimium was capturing my <Esc> when trying to use any in-browser editors in their "vim mode" (HackMD in my case).

I know this is not directly related to this issue, but thank you ser! :pray:
