### ISSUE TITLE
wrong final cursor position while doing visual block selection till the end of file

### ISSUE THREAD

**Issue by pangteypiyush** [VSCodeVim/Vim#7051]
**Describe the bug**
While doing visual block selection till the end of file results in wrong final cursor position.
Here "wrong" means the behaviour is very different from the actual vim.

**To Reproduce**

`[ ]` is the cursor/selection
1.  Open a new file with this content (Note: no newline at the end):
```
[e]nv.HELLO=world
env.HELLO=world
env.HELLO=world
```
3.  Select first word of each line: `<ctrl>veG`
```
[e]nv.HELLO=world
[e]nv.HELLO=world
[e]nv.HELLO=world
```

**Expected behavior**
Running `<ctrl>veG` should select:
```
[env].HELLO=world
[env].HELLO=world
[env].HELLO=world
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `v1.21.7`
- VSCode version: `1.60.0 Commit: e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff`
- OS: `Linux x64 5.13.13-arch1-1`

**Comment by J-Fields** [comment]
Disable `startofline` and you'll get the behavior you're expecting
