### ISSUE TITLE
j+j no longer works in 0.1.8

### ISSUE THREAD

**Issue by deshiknaves** [VSCodeVim/Vim#706]
`"vim.insertModeKeyBindings": [
        {
            "before": ["j", "j"],
            "after": ["<esc>"]
        }
   ]`

No longer works on the latest version :(. Was working until I updated to the new version. Can't seem to downgrade to 0.1.7 even with the source files, drops me down to 0.1.3.

### What did you do?

j + j

### What did you expect to happen?
Change modes

### What happened instead?
jj was inserted

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.8
* OS: OSX

**Comment by johnfn** [comment]
Going to attempt to fix this one right now and push out a fix.

**Comment by johnfn** [comment]
Fixed. Seeing if I can clean up any of the other bugs while I'm at it - then I will push out 0.1.9.

**Comment by jpoon** [comment]
Thanks @johnfn for the fix. Sorry @deshiknaves for the inconvenience :)

**Comment by deshiknaves** [comment]
All good. Thanks for looking into this so quickly :). Looking forward to the fix.

**Comment by andrewalexander** [comment]
I think that this broke my bindings... I had this in my settings.json:

```
"vim.otherModesKeyBindings": [
        {
            "before": ["L"],
            "after": ["$"]
        },
        {
            "before": ["H"],
            "after": ["^"]
        }
    ]
```
and now pressing lowercase `h` and `l` take me to the beginning/end of the line, respectively. I can open a separate issue, but I am fairly confident that the recent update that said hotfixes this issue is the root cause.

**Comment by jpoon** [comment]
@andrewalexander the hotfix in 0.1.9 didn't entirely fix the issue. we have this issue tracking the bug https://github.com/VSCodeVim/Vim/issues/716 with a PR https://github.com/VSCodeVim/Vim/pull/721 that fixes it. I'll test your specific use case to make sure it still works.

**Comment by andrewalexander** [comment]
Awesome - confirmed to be working.
