### ISSUE TITLE
. operator hangs VSCode on 0.1.8

### ISSUE THREAD

**Issue by joa-quim** [VSCodeVim/Vim#707]
### What did you do?

Applied the '.' operator to repeat last command

### What did you expect to happen?

repeat last command

### What happened instead?

VSCode hanged and had to reload the window

### Technical details:

* VSCode Version:

1.4.0

* VsCodeVim Version: *[please ensure you are on the latest]*

0.1.8

* OS: 

Win10

**Comment by johnfn** [comment]
I can't reproduce this. Can you please provide the exact keystrokes you used?

**Comment by joa-quim** [comment]
Hi,
Tried again and it's happening the way it happen on first instance but still having problems that are easy to describe in a series of steps (not exactly equal between occurrences). But see the attached image. What I did was to go to insert mode at line 146 and inserted the 'GMT_' string, than at line 147 hit '.'. Now it did repeat the previous command (before it didn't) but immediately appeared the error message at the top. The hanging still happens but now more randomly.

![capture](https://cloud.githubusercontent.com/assets/537321/18232798/6cead396-72cf-11e6-9032-a9f92b9f690d.JPG)

**Comment by johnfn** [comment]
Okay, thanks @joa-quim, and really sorry about that. Keep me updated if you can find good repro steps, and I'll be trying myself.

**Comment by joa-quim** [comment]
Hmm, odd. It's not hanging anymore (at least in this short period). One thing that changed though was that I installed the C/C++ Snippets plug-in. But that Error message is systematic. The first tile I hit '.' it shows up.

**Comment by johnfn** [comment]
I can't imagine why installing the C/C++ snippets plugin would help :) 

Is this something that definitely started with 0.1.8?

**Comment by joa-quim** [comment]
Very short time line here. I only started to use VSCode yesterday and updated today when I saw the little red dot informing me about a new version. Than it started. But for what its worth, I deleted all opened VSCode windows and things seam  to run fine again.
If it keeps that way for some time I'll close this issue. 
Thanks for looking.

**Comment by joa-quim** [comment]
It occurred again, but very sporadic. Sorry not being able to be more specific.

**Comment by johnfn** [comment]
I'm keeping this one open until we figure it out. :P

**Comment by joa-quim** [comment]
Ok, for some reason the page had the "Comment" button inactive. I'm also not able to attach another picture with the error message at the top of the VSC window. I keep getting a "Something went really wrong, and we can’t process that file. ", which is a plain simple .jpg

**Comment by TStepi** [comment]
Hello.
Just wanted to add that this bug also affects me. Everytime I try to use the '.' nothing happens and I can no longer edit files. I can still move the cursor around though.

VSCode version 1.4
plugin version 1.10 now
Linux

I also use OCaml plugin, but no others, if that helps.

Cheers!

**Comment by johnfn** [comment]
Thanks @TStepi . This happens 100% of the time? Does it happen in every file you edit, even completely new blank files?

**Comment by TStepi** [comment]
Well, until now it did. I tried it just now on a new file and it didn't. Interestingly, even when saving a new file with .ml extension so that OCaml plugin loads it didn't happen. But when I saved the file, closed VSC and opened it again with the file opened, it happened again.

I did some more testing with this and my current best guess is that it happens with files that are opened when VSCode starts.

**Comment by TStepi** [comment]
Update: My previous guess was wrong as it can happen even with files not opened at startup.
Also, after hanging, I have to manually kill the systemd-coredump process which eats one cpu core.

**Comment by joa-quim** [comment]
Another clue. It's now happening all the times when I edit a file from an open Editor that has several dozens of files.

**Comment by johnfn** [comment]
@joa-quim now *that* is really interesting.

Is it reproducible if you open up a new instance of vsc, then hold down cmd-n until you have like 30 tabs and then start doing . operations?

**Comment by joa-quim** [comment]
I could not reproduce it with 30 empty tabs and editing the last one.
But I also noticed that the "n-Y" (to copy n lines into buffer) followed by 'p' to past them, only copy the first line. That is:
3-Y + p
does the same as
1Y + p

**Comment by johnfn** [comment]
@joa-quim please open a new issue for that one :)

**Comment by joa-quim** [comment]
If that may help, it's currently happening when I edit files from here

http://gmt.soest.hawaii.edu/projects/gmt5sar/repository/show/trunk/gmtsar

**Comment by joa-quim** [comment]
Hmm, this is getting worst. Updated to 0.2.0 and now after the hang the 'Reload Window' does not even get back the code being edited and simply start a new empty window.

**Comment by dallas** [comment]
*VS Code Version:* Version 1.6.0-insider (c94c824db64a88bd4909da2e84e44316dbf8e8fb)
*vscodevim Version:* 0.2.0
*OS*: macOS Sierra Beta 10.12.1 (16B2327e)

I am able to reliably reproduce by using `ctrl+d` to scroll down far enough that the cursor position is forced to change and then attempting to use `.` to repeat the last command. It dies for me every time and I have to force-quite VS Code Insiders and restart it. Same behavior when using `ctrl+u`, `ctrl+f`, and `ctrl+b`. I haven’t tried it using other scrolling actions, chances are it’s less about scrolling in general and more about moving the cursor. You can also recreate it by simply performing some action and getting back into Command Mode (if necessary), and then using the mouse to click somewhere else in the document and hitting `.` to repeat that same action. Maybe a bug of being in the vscodevim command mode, using the VS Code cursor movement API (not exactly sure what this is called), and then attempting to repeat the last action. 

I hope this helps the devs debug this issue! Let me know if there's anything else I can provide (more info, screen shots, video, animated gif, etc.).

**Comment by johnfn** [comment]
@dallas, thank you very much. I was also able to reproduce it in this way. This should make it much easier to debug. :)

**Comment by dallas** [comment]
Yay! 😄

**Comment by johnfn** [comment]
This has been fixed. :)
