### ISSUE TITLE
Cannot change to normal mode.

### ISSUE THREAD

**Issue by chris-ryu** [VSCodeVim/Vim#7106]
**Describe the bug**
Once into insert mode, esc key not working then cannot change to normal mode.
When I push esc key in code window, "command 'extension.vim_escape' not found" messeage toasted.
**Environment (please complete the following information):**

- Extension (VsCodeVim) version:v1.21.7
- VSCode version:1.60.2
- OS: mac OS BigSur 11.6

**Additional context**
[CPU-20210924T021621.449Z.cpuprofile.txt](https://github.com/VSCodeVim/Vim/files/7221850/CPU-20210924T021621.449Z.cpuprofile.txt)

**Comment by tlawren** [comment]
I might have same or related problem.  When switching or adding folders (to workspace), extension stops working and I am stuck in whatever mode I'm I was in.  Various commands fail to work and I get errors ` "command 'extension.vim_<command>' not found"`

- Extension (VsCodeVim) version:v1.21.7
- VSCode version:1.60.2
- OS:  Windows 10

Current fix is to remove custom vim settings, disable extension, re-enable extension, re-add settings.

**Comment by chris-ryu** [comment]
> I might have same or related problem. When switching or adding folders (to workspace), extension stops working and I am stuck in whatever mode I'm I was in. Various commands fail to work and I get errors ` "command 'extension.vim_<command>' not found"`
> 
> * Extension (VsCodeVim) version:v1.21.7
> * VSCode version:1.60.2
> * OS:  Windows 10
> 
> Current fix is to remove custom vim settings, disable extension, re-enable extension, re-add settings.

Thank you.
After delete extensions folder and reinstall extension, It works well

**Comment by elijahrdorman** [comment]
I'll add my issue here too (M1 mac on Monterey).

I blew away *everything* VS Code related and reinstalled, but escape is still broken
