### ISSUE TITLE
Smart relative line number too close to code in Notebook view

### ISSUE THREAD

**Issue by AnsonH** [VSCodeVim/Vim#7130]
# Problem

When smart relative line number is enabled (`"vim.smartRelativeLine": true`), the line numbers in the Jupyter Notebook cell is too close to the code if the cursor is not on those lines. Is it possible to add right margin to these line numbers?

👇 When smart relative line number is enabled
![screenshot](https://user-images.githubusercontent.com/57580593/136005590-f500b640-eb3f-42bb-9039-9f9bc320798c.png)

# Steps to Reproduce
1. Enable smart relative line number with `"vim.smartRelativeLine": true`
2. Create a new Jupyter Notebook file (eg. `foo.ipynb`)
3. Create a new cell in the Notebook and add some lines to the cell
4. Notice that the line number except for the line the cursor is currently on lacks right margin

# Environment
- Extension (VsCodeVim) version: v1.21.8
- VSCode version: v1.60.2
- Jupyter extension version: v2021.8.2041215044
- OS: Windows 10 Version 20H2 (Build 19042.1237)

**Comment by J-Fields** [comment]
This is almost certainly an issue with VS Code, not the plugin. If you just set `editor.lineNumbers: 'relative'` directly, do you have the same problem?

**Comment by marcusfschmidt** [comment]
I seem to be getting this issue now, almost a year after the above.

Here, in normal mode: 
![image](https://user-images.githubusercontent.com/55887958/186212942-13808a42-571f-42b7-a8e6-c13c7e9299da.png)

And here in insert mode:
![image](https://user-images.githubusercontent.com/55887958/186213015-3da03086-ab82-45a7-b17d-2d6139039fe4.png)

My environment is as follows:
- VsCodeVim version: v1.23.2
- VSCode version: v1.70.2
- Jupyter extension version: v2022.7.1102252217
- OS: Windows 10 Version 21H2 (Build 19044.1889)

As far as I can tell, the fix has been broken at some point.
Thanks in advance.
