### ISSUE TITLE
Surrounding selection with quotes

### ISSUE THREAD

**Issue by nemanjapesic** [VSCodeVim/Vim#7159]
- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.21.8`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.61.1`

This used to work before but now is acting broken.

Select some keyword, or for example when using clg snippet (it creates console.log(object) and selects word 'object'.
Press ' or SHIFT + '
Results: The selected word gets surrounded with quotes but the problem is that the selection is lost and the insert cursor is placed between penultimate and the last letter which is weird. Continuing to type creates a result like 'objecnewly typed textt'

Expected behavior: The selected word gets surrounded with quotes and remains selected. Continuing to type replaces the selection with newly typed characters.

VSCode: https://github.com/microsoft/vscode/issues/133995#issue-1009674353

**Comment by Stedag** [comment]
Issue Type: Bug
Extension Name: vim
Extension Version: 1.21.6
OS Version: Windows NT x64 10.0.19042 Build 19042
VS Code version: 1.61.1

Thanks Nemanjapesic for submitting this. I noticed this too and finally got around to narrowing down which version introduced the breaking change. It appears to be 1.12.6 so I'll be using 1.12.5 until this is resolved I suppose.

This behavior is also occuring with single-quotes, parentheses, and brackets.

**Comment by vincentor** [comment]
met the same bug and it is annoying，is it fixed?

**Comment by Denhai** [comment]
It broke in this commit: ca887343db63068325cbb985892cbc594ed888f5
