### ISSUE TITLE
j+j (j + k) works not as expected in 0.1.9

### ISSUE THREAD

**Issue by ScenK** [VSCodeVim/Vim#716]
"vim.insertModeKeyBindings": [ { "before": ["j", "k"], "after": ["\<esc\>"] } ]

j+j (j + k) works not as expected in 0.1.9, j + k could not exit insert mode actually -- unless i press \<esc\>. See screen recode.

![untitled](https://cloud.githubusercontent.com/assets/2987542/18260617/f12062c2-7421-11e6-8fa6-855fbabadde9.gif)

What did you do?

j + k

What did you expect to happen?

Change modes

What happened instead?

jk was inserted

Technical details:

VSCode Version: 1.5.0-insider
VsCodeVim Version: 0.1.9
OS: OSX

**Comment by deshiknaves** [comment]
Yep, same issue on Windows 10. I'm sure my mac machine will be the same.

**Comment by jpoon** [comment]
Definitely a bug. Case insensitivity got all screwed up with the `remapper`, fix on its way.

**Comment by deshiknaves** [comment]
Sweet. I just realized that I can work around this using:

`"vim.insertModeKeyBindings": [
        {
            "before": ["j", "j"],
            "after": ["escape"]
        }
   ],`

**Comment by jpoon** [comment]
Releasing another version of the extension shortly.
