### ISSUE TITLE
Is there a way to specify number + action applies to a number of lines?

### ISSUE THREAD

**Issue by Gregliest** [VSCodeVim/Vim#7203]
**Is your feature request related to a problem? Please describe.**
In my normal vim, I have NerdCommenter set up such that number + [comment command] comments out that number of lines. For instance, typing "8<leader>/" would toggle comment on 8 lines. 
However, in vscode vim, the comment command is applied 8 times. Thus, a single line is comment toggled 8 times. 

**Describe the solution you'd like**
I would like to be able to apply a number to an action, in particular to comment multiple lines. 

**Describe alternatives you've considered**

**Additional context**

**Comment by J-Fields** [comment]
In general, no (eventually you'll be able to do something like that via vimscript), but we do support the `gc` operator, which comments a region, so `8gcc` will do that

**Comment by Gregliest** [comment]
Ah that's perfect, thanks!
