### ISSUE TITLE
Command line `move` command throws `E488: Trailing characters`

### ISSUE THREAD

**Issue by dustypomerleau** [VSCodeVim/Vim#7207]
Thanks for all the time you've put into this extension. Description of the bug is below:

**Describe the bug**

Attempting to move lines from the command line throws an error.

**To Reproduce**

Enter any range and destination invoking `m`, for example: 
`:22,25m10`

**Expected behavior**

The specified range should be moved to the destination.

**Environment:**

- Extension (VsCodeVim) version: 1.21.10
- VSCode version: 1.61.2
- OS: macOS 11.6.1 (20G224)

**Additional context**

Similar commands, such as copying the range with `t`, work perfectly:
`:22,25t10`
so perhaps the `m` command is trimming the input differently?

**Comment by J-Fields** [comment]
Thanks for the report! I re-wrote most of the parsing from scratch recently - I'm sure lots of these little bugs have been introduced. `:move` is actually not yet implemented though (I plan on doing that soon; the recent re-write has made filling in these gaps in functionality easier), see #2472. The parser is throwing the wrong error here, should say the command isn't implemented.

**Comment by dustypomerleau** [comment]
Ah, my mistake then. Thanks for working on it!
