### ISSUE TITLE
Easymotion label color is lost after upgrading VSCode to 1.62

### ISSUE THREAD

**Issue by laggardkernel** [VSCodeVim/Vim#7247]
**Describe the bug**
Easymotion label color is lost if there's non-ASCII characters in the line. The problem only occurs after upgrading to 1.62. 

**To Reproduce**

Minimal settings

```json
{
    "vim.easymotion": true,
}
```

Test text

```

abc 测试 (word 'test' in Chinese)
abc test
```

Steps

1. Install VSCodeVim extension and enable easymotion
2. Paste the text above into a new file, and put your cursor at the 1st line.
3. Use 2f search to match `ab`, type this `<Leader><Leader>2fab`. (`<Leader>` defaults to `\`)
4. You'll find the `ab` in the line with Chinese characters is not highlighted. But it does get highlighted in the line without Chinese characters. The problem only exists in VSCode **1.62**.

The bug also occurs with other searches like `<Leader><Leader>j`.

**Screenshots**
<img width="413" alt="Screen Shot 2021-11-11 at 17 42 32" src="https://user-images.githubusercontent.com/12206611/141277042-12c343d9-8b4e-43d5-b928-5b84df6c7359.png">

**Environment (please complete the following information):**

Version: 1.62.1
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T09:23:14.144Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 18.7.0

Extension vscodevim: v1.21.10

**Comment by Player-hub** [comment]
I have the same issue!!
![image](https://user-images.githubusercontent.com/88477326/141649419-f1553873-4846-4a59-a940-1efecfc4f54b.png)
In this paragraph, when I call easymotion [leader leader s, t], some markers are invisible!!
![image](https://user-images.githubusercontent.com/88477326/141649525-edb7a79f-e73d-4f24-930e-834b80edb61c.png)
By the way, there's one thing important: though invisible, these markers are still working. i.e. the markers are only invisible, and when I happen to commit the correct key, I can still go there.

**Comment by laggardkernel** [comment]
@Player-hub Seems like a bug on VSCode's side. Today I upgraded VSCode from 1.62.1 to 1.62.3, and found the bug resolved.
