### ISSUE TITLE
`vim.mode == 'Normal'` in key binding is triggering in replace mode 

### ISSUE THREAD

**Issue by andrewplummer** [VSCodeVim/Vim#7256]
I have the following key binding:

```
    {
        "key": "shift+l",
        "command": "workbench.action.nextEditorInGroup",
        "when": "vim.mode == 'Normal'"
    },
```

to use vim keys to switch editors. This works perfectly, however I noticed that when I hit `r` to replace a character then`shift+l` this shortcut will be triggered. I am expecting vim to not be in `Normal` mode in this case but instead `Replace` mode (or possibly `CommandlineInProgressMode` or `OperatorPendingMode` although I'm not exactly if either or none of these apply as the documentation doesn't really make clear when these modes are triggered).

Am I doing something wrong here?

- Extension (VsCodeVim) version: v1.21.10
- VSCode version: 1.62.2 (Universal)
- OS: OSX 12.0.1

**Comment by w-cantin** [comment]
Hello,

From experience remapping vim keys in `keybindings.json` instead of the recommended way in `settings.json` is kind of hit or miss. A better way to proceed is to trigger regular vscode commands using the "vim.normalModeKeyBindings" command in settings.json. Here is what might look like: 

```json
  "vim.normalModeKeyBindingsNonRecursive": [
      { "before": ["L"], "commands": ["workbench.action.nextEditorInGroup"] },
]
```

I hope it helped

**Comment by andrewplummer** [comment]
Cool that seems to have worked. Also FWIW `normalModeKeyBindingsNonRecursive` doesn't seem to be a recognized setting (yellow squiggles suggesting it's not valid) although it works fine. Anyway thanks!

**Comment by w-cantin** [comment]
Do the yellow squiggle appear because it is a duplicated setting? If you hover your mouse over the squiggle what does it say?

**Comment by andrewplummer** [comment]
I am stupid... indeed you are right :)
No issues here!

**Comment by fedoraiver** [comment]
actually r is in the normal mode,replace mode you have to press R
