### ISSUE TITLE
undo is not working in Jupyter cells

### ISSUE THREAD

**Issue by GaryLiuTelus** [VSCodeVim/Vim#7269]
**Describe the bug**
The undo (key `u`) does not work in Jupyter cells

**To Reproduce**

1. create a new Jupyter notebook
2. Insert some text
3. return to Normal mode
4. Press `u` to undo, and it won't work.

**Expected behavior**
Undo previous editing

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:1.21.10
- Extension (Jupyter) version: 2021.10.110
- Extension (Jupyter Keymap) version: same as Jupyter extension. 
- VSCode version:1.62.2
- OS:Windows 10 Enterprise 20H2

**Additional context**

**Comment by J-Fields** [comment]
Duplicate of #6275
