### ISSUE TITLE
cc on end of line eats currentline

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#727]
### What did you do?

For this js file:

``` js
if (true) {|
}
```

Pressed:
`o<C-c>cc`
### What did you expect to happen?

``` js
if (true) {
  |
}
```
### What happened instead?

``` js
if (true) {
  |}
```

Also related to #685 , as when I press `o<C-c>`, it ends up in

``` js
if (true) {
 | // Two whitespaces here, cursor before second one
}
```

Then if I do `cc`, the newline is eaten.

`cc` for the following file works fine:

``` js
if (true) {
| // No trailing space
}
```
### Technical details:
- VSCode Version: 1.4.0
- VsCodeVim Version: master branch
- OS: OS X 10.11.6

I set `autoindent` to true.

**Comment by octref** [comment]
Happend to see #696 and can confirm cw also eats EOL in latest master.

**Comment by SamOfFinland** [comment]
I can take a look at this issue.

**Comment by johnfn** [comment]
By all means, go ahead @SamOfFinland :)

**Comment by Chillee** [comment]
This issue seems to be fixed @jpoon .

**Comment by xconverge** [comment]
I can't repro this anymore, I think it may be fixed as well. Feel free to reopen!
