### ISSUE TITLE
Feature Request: Macros

### ISSUE THREAD

**Issue by maxponte** [VSCodeVim/Vim#728]
One of the most powerful features of vim is the ability to record macros using the q key. I am assuming all it would take is to append every keystroke to a list while the user is recording, and then when they want to use the macro, replay those keystrokes. Alternatively you could represent them as commands and it would work the same way.

**Comment by johnfn** [comment]
Our longest outstanding bug! This is tracked by #100.

You may also be interested in #587 (currently WIP), which is effectively the same thing, but in real time!
