### ISSUE TITLE
Notebook-cells duplicate marks

### ISSUE THREAD

**Issue by nikisix** [VSCodeVim/Vim#7280]
**Describe the bug**
Setting a mark in a notebook cell works as expected. Until moving to a new cell, where that same mark will be present in the new cell as well.

**To Reproduce**
1. Mark a line in a cell with `m a` for instance.
2. Move to a new cell

**Expected behavior**
Moving to a new cell should not duplicate the mark in the new cell.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `1.21.10`
- VSCode version:
```
Version: 1.62.3 (system setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
```
- OS: Windoze

**Comment by J-Fields** [comment]
Fixed by 4585ef2723cceb672922729ada46eebb43f262c7
