### ISSUE TITLE
Keep pressing j causes VSCodeVim to hang in Insider

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#729]
* VSCode Version: 1.5.0 Insider
* VsCodeVim Version: 0.1.10 / latest master
* OS: OS X 10.11.6

I tried testing in both latest master and 0.1.10, with VSCode 1.5.0 Insider. Both causes VSCodeVim to hang. It doesn't process any key presses anymore.

I tried both in 1.4.0, works fine.

**Comment by johnfn** [comment]
Thanks for the issue! I'm having trouble reproducing this. Can you tell us more about your configuration? Does this work even if you open up a blank file with a lot of newlines?

**Comment by octref** [comment]
Yes, it happens. I disabled all other extensions, and removed all my configs. Still happens. I'll check with @rebornix tomorrow to see if he could repro that. We are sitting next to each other :D

**Comment by johnfn** [comment]
Ahh, that's perfect. Definitely send this bug to him. He will hopefully figure out what's going on. :P

**Comment by jayteesanchez** [comment]
VSCode 1.5; VsCodeVim 0.1.10; OSX 10.11.6;

Hello, same issue for me and I've tried a complete uninstall and reinstall of both VsCode and Insiders. It isn't just the 'J' key for me though, it happens with 'K' 'L' and 'H' as well.  I actually even tried the AmVim extension and it also causes the same issue. 

This didn't start happening until I upgraded to 1.5 and by downgrading to 1.4 it fixed the issue.

**Comment by rebornix** [comment]
Interesting, I can't reproduce this issue even though I have the same evn with @octref (apparently, our machines are totally the same) and @jayteesanchez. Will reach out to @octref to see the issue.

**Comment by octref** [comment]
@johnfn 

This morning I updated to latest insider, and this problem still happens for 0.1.10.
But Insider + VSCodeVim master branch doesn't have this problem. It's only I can't keep pressing j/k to keeping going down/up.
However, https://github.com/VSCodeVim/Vim/issues/422#issuecomment-234400626 fixes the issue for me. Maybe the FAQ in README needs to be updated?

@jayteesanchez 

Can you try setting `defaults write -g ApplePressAndHoldEnabled -bool false` and updating to latest insider to see if it works?

**Comment by jayteesanchez** [comment]
@octref 

Tried out your solution, the cursor doesn't move when holding down the movement keys but it also does not freeze Code from accepting any keyboard input after letting the key go which is what used to happen. Definitely an improvement over what was happening but not the same behavior as in Code 1.4 where the cursor will scroll for as long as I hold the key.

**Comment by octref** [comment]
@jayteesanchez 

Hello, would you mind doing

`defaults read com.microsoft.VSCodeInsiders`
`defaults read -g`

and tell us the value of `ApplePressAndHoldEnabled` in each output?

Then, if you do

`defaults delete -g com.microsoft.VSCodeInsiders`

does VSCodeVim hang?

Finally, if you do 

`defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false`

does that solve the problem?

Sorry for asking you to do all this, but this might be an issue with VSCode and affect other people. I'm looking for the exact reproduce steps for the problem.

**Comment by jayteesanchez** [comment]
No worries, I don't mind at all! 

But here are the outputs of everything, 

> defaults read com.microsoft.VSCodeInsiders

<code>
{
    ApplePressAndHoldEnabled = 0;
    NSFullScreenMenuItemEverywhere = 0;
    NSTreatUnknownArgumentsAsOpen = NO;
}
</code>

> defaults read -g 

<code>{
    AKDeviceUnlockState = 0;
    AppleActionOnDoubleClick = Maximize;
    AppleAntiAliasingThreshold = 4;
    AppleInterfaceStyle = Dark;
    AppleKeyboardUIMode = 2;
    AppleLanguages =     (
        en
    );
    AppleLocale = "en_US";
    AppleMiniaturizeOnDoubleClick = 0;
    InitialKeyRepeat = 15;
    KeyRepeat = 2;
    NSAutomaticDashSubstitutionEnabled = 1;
    NSAutomaticQuoteSubstitutionEnabled = 1;
    NSAutomaticSpellingCorrectionEnabled = 1;
    NSNavPanelFileLastListModeForOpenModeKey = 1;
    NSNavPanelFileLastListModeForSaveModeKey = 1;
    NSNavPanelFileListModeForOpenMode2 = 1;
    NSNavPanelFileListModeForSaveMode2 = 1;
    NSNavPanelSidebarKeyForOpen =     (
    );
    NSNavRecentPlaces =     (
        "~/Desktop/Employee Pictures",
        "~/vms/dev/repos/appointments",
        "~/vms/dev/repos/nationalmerchantstest"
    );
    NSPersonNameDefaultDisplayNameOrder = 0;
    NSPersonNameDefaultShortNameFormat = 0;
    NSPersonNameDefaultShouldPreferNicknamesPreference = 0;
    NSPreferredWebServices =     {
        NSWebServicesProviderWebSearch =         {
            NSDefaultDisplayName = Google;
            NSProviderIdentifier = "com.google.www";
        };
    };
    NSUserDictionaryReplacementItems =     (
                {
            on = 1;
            replace = omw;
            with = "On my way!";
        }
    );
    NavPanelFileListModeForOpenMode = 1;
    NavPanelFileListModeForSaveMode = 1;
    WebAutomaticSpellingCorrectionEnabled = 1;
    "_HIHideMenuBar" = 1;
    "com.apple.mouse.doubleClickThreshold" = 5;
    "com.apple.mouse.scaling" = 3;
    "com.apple.springing.delay" = "0.5";
    "com.apple.springing.enabled" = 1;
    "com.apple.swipescrolldirection" = 0;
    "com.apple.trackpad.forceClick" = 1;
}
</code>

> defaults delete -g com.microsoft.VSCodeInsiders

`$ defaults delete -g com.microsoft.VSCodeInsiders
2016-09-08 13:02:07.548 defaults[57350:672501]
Domain (kCFPreferencesAnyApplication) not found.
Defaults have not been changed.`

After trying everything you recommended, I still can't scroll when holding down the movement keys, but it also is not freezing after letting go. 

Let me know if you want me to try anything else!

**Comment by rebornix** [comment]
@jayteesanchez do you try restart VS Code after you set those options?

**Comment by octref** [comment]
@jayteesanchez 
Thanks for the info!

If you do
```
defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false
```

and restart VSCode Insider (with Vim 0.1.10), it should work.

If it doesn't, can you try going to insert mode and keep pressing <kbd>o</kbd>, to see if it produces more than one <kbd>o</kbd>, and also whether it produces such a window?

![image](https://cloud.githubusercontent.com/assets/4033249/18365735/b707a886-75c8-11e6-8638-f1976129d44a.png)

**Comment by jayteesanchez** [comment]
@octref @rebornix 

I didn't restart it the first time, my bad. But I did this time after running that last command and it worked!

Also pressing 'o' in insert mode prints 'o's until I let go. 

Because that command is adjusting my system defaults, I'm assuming I messed with a setting causing Code to freeze. Going forward is there something I should watch out for or any particular setting that I shouldn't mess with so I don't run into this issue again?

Thanks for all the help guys!

**Comment by rebornix** [comment]
@jayteesanchez actually our suspicion is this might be a Chromium bug and we don't have any clue how to reproduce this issue. That means we can't tell you how to avoid running into this case again. But if you accidentally run into this bug, please let us know :)

**Comment by octref** [comment]
@jayteesanchez 

No worries. As for settings, here is a synopsis:

`ApplePressAndHoldEnabled` controls how pressing a key and holding it works on OS X. If it's true, it'll produce accented characters, like ô, ö (try keep pressing <kbd>o</kbd> in Chrome).

![image](https://cloud.githubusercontent.com/assets/4033249/18365735/b707a886-75c8-11e6-8638-f1976129d44a.png)

-  Disable that for VSCode:

```
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
```

- Disable that for VSCode Insider:

```
defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false
```

- Changing the setting **globally**, so it works in all programs:

```
defaults write -g ApplePressAndHoldEnabled -bool false
```

**Comment by octref** [comment]
@johnfn 

I'm closing this now because despite our efforts, we weren't able to repro the bug. But this happened to me on Insider without VSCodeVim, so it's not the extension's fault.

I'll keep an eye on the issue list to see if anyone else would have this problem, now that 1.5 is released.

**Comment by jayteesanchez** [comment]
@rebornix @octref 

Got it, thanks for the explanation and thanks again for all the help!
