### ISSUE TITLE
Cursor column not persisted across shorter line

### ISSUE THREAD

**Issue by BlueInt32** [VSCodeVim/Vim#7305]
**Describe the bug**
Moving the cursor down or up from a long line, over a shorter line and to another long line does not persist the column the cursor was at. It does in native vanilla VIM. It is easier to show than to explain though, so please check the video below.

**To Reproduce**

1.  Simply have 3 lines of text, the second one being shorter
2.  Place the cursor at the end of the first line
3.  Go down with j
4.  Cursor gets set to the end of the second line
5. Go down with j again
6. Cursor stays in the same column in the third line

**Expected behavior**
At step 6. the cursor should get back to the closest possible column it had when it was on line 1

**Video**

https://user-images.githubusercontent.com/2920038/145292048-61716016-078d-4146-b106-e6f07d63bf96.mp4

**Environment:**

- Extension (VsCodeVim) version: 1.21.10
- VSCode version: 1.63.0
- OS: Windows 10 (OS Build 19043.1348)

**Additional context**
I could not find a similar issue using the search, and I don't really know if the expected behavior has a specific name in vim. Sorry for potential duplicate anyway.

**Comment by J-Fields** [comment]
Have you mapped `j` to `gj`? This is a known issue for `gj`/`gk` (#4441)

**Comment by BlueInt32** [comment]
Ah yes indeed ! Thanks a lot !
