### ISSUE TITLE
Wrong relative line numbers across folded regions

### ISSUE THREAD

**Issue by anterpin** [VSCodeVim/Vim#7309]
**Describe the bug**
Wrong relative line numbers across a folded region.

**To Reproduce**
1. Make to set the relative line numbers with `:set rnu`;
2. Create for a example a function in any programming language you want;
3. Fold it;
4. Move the cursor below;
5. The upper relative line numbers are generated counting the folded region lines;

**Expected behavior**
The relative line number should not count the folded ones as in vim or nvim.

**Screenshots**
![example](https://user-images.githubusercontent.com/44070188/145420175-4998c382-4403-4f82-951a-68e63b6ca0e6.png)

**Environment**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.21.10`
- OS Version: `Linux x64 5.10.79-1-MANJARO`
- VS Code version: `1.62.3`

**Comment by J-Fields** [comment]
Please open an issue with VS Code - we don't control this at all
