### ISSUE TITLE
<operator>a` includes preceding space if there is one

### ISSUE THREAD

**Issue by macintacos** [VSCodeVim/Vim#7318]
**Describe the bug**
Say you have a string like the following:

```
Something something `something`.
```

Place your cursor in the middle of the last word "something" that is in backticks and then hit va`. The visual selection includes the space between the second "something" and the first backtick.

**Expected behavior**
Hitting va` when inside of two backticks should result in everything including the backticks to be selected. In this case, it does that _and_ it selects stuff outside of the backtickets.

**Screenshots**

Here's a screen recording:

https://user-images.githubusercontent.com/8128941/145868859-e21ad827-f85e-4900-82ec-99892262157d.mp4

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.10
- VSCode Version: 1.63.0
	  - Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
	  - Date: 2021-12-07T05:15:48.091Z
	  - Electron: 13.5.2
	  - Chromium: 91.0.4472.164
	  - Node.js: 14.16.0
	  - V8: 9.1.269.39-electron.0
- OS: Darwin x64 20.6.0

**Comment by J-Fields** [comment]
This is expected behavior. From `:help qa`:
```
Any trailing white space is included, unless there is
none, then leading white space is included.
```

**Comment by macintacos** [comment]
Ah, well that's pretty unintuitive considering how other motions work. Fair enough though, thanks.

**Comment by macintacos** [comment]
Oh I see, it seems to work differently in my Neovim install, although I'm not quite sure how I got it that way 😄 must be some setting I set one day and then forgot about.

**Comment by J-Fields** [comment]
Yeah this has been reported as a bug more than once 🙂
Mapping `a"` to `2i"` (and same for other quotes) in visual and operator pending modes should do what you want, I think
