### ISSUE TITLE
configuration vim.useCtrlKeys = false is not honored

### ISSUE THREAD

**Issue by steelsojka** [VSCodeVim/Vim#734]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Set configuration `vim.useCtrlKeys: false`. Using key combination `ctrl+d` was expected to perform vscode default behavior of select next match, instead the view scrolled about half the view.

Window commands are also enabled, for example `ctrl+w l` moves to the next editor group. Here is my user config:

```
// Place your settings in this file to overwrite the default settings
{
    "vim.useCtrlKeys": false,
    "vim.insertModeKeyBindings": [{
        "before": ["k", "j"],
        "after": ["<Esc>"]
    }],
    "editor.renderIndentGuides": false,
    "editor.tabSize": 2,
    "terminal.external.osxExec": "iTerm.app",
    "editor.fontSize": 13
}
```

### What did you expect to happen?
 This should not happen if this config is set to false.

### What happened instead?
Ctrl key combinations are enabled.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.10
* OS: Linux Ubuntu Studio 16.04

**Comment by johnfn** [comment]
You're completely right. Seems like an easy bug for anyone who wants to pick it up.

**Comment by rebornix** [comment]
Already fixed it https://github.com/VSCodeVim/Vim/commit/593ec486c8d9a65ee1c5b48da60d750197e4a788#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R108 incidentally.

**Comment by xconverge** [comment]
@rebornix what about ctrl + w, u, h, b, r, etc ones that don't have the check for use ctrl keys

**Comment by Sentero-esp12** [comment]
This happens to me on Windows 7 64, latest VSCode
