### ISSUE TITLE
Keep selection when copying text

### ISSUE THREAD

**Issue by dschuessler** [VSCodeVim/Vim#7352]
**Is your feature request related to a problem? Please describe.**
When I select a line of text, either in visual mode or with the mouse cursor and then press Cmd+C to copy it, the selection is lost.

**Describe the solution you'd like**
I would like to keep my selection when pressing Cmd+C, either as a default behavior or as a setting.

**Describe alternatives you've considered**
I have tried various settings to achieve the behavior I desire, including the following:
```
"vim.useSystemClipboard": true,
"vim.useCtrlKeys": true,
"vim.handleKeys": {
  "<C-c>": false,
  "<Cmd-c>": false,
},
```

**Additional context**
Losing the selection does not happen when the extension is turned off.

My use case is that I want to use the [DeepL Mac App](https://www.deepl.com/en/app/) which has the rather nice default behavior to open the translator on pressing Cmd+C twice. Since the selection is lost on the first keypress, however, the feature does not work as intended.

**Comment by w-cantin** [comment]
Hello,

I do not have access to a mac to try this, nonetheless you should be able to fix the issue by removing `Cmd+c` key mapping in VSCodeVim. Mac `Cmd` remappings should be prefixed by `<D-_>` and not `<Cmd-_>`. That means that you should have the following lines in your settings:

```json
"vim.handleKeys": {
  "<D-c>": false,
},
```

If that does not work another workaround would be to simply remove the keymapping for cmd+c in VSCode directly. To do this, open [VSCode's keybindings editor](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor) and search for cmd+c. There you should be able to remove the vim command.

**Comment by dschuessler** [comment]
@w-cantin Your first suggestion works. That is fantastic! Thank you very much for your help and have a great day.
