### ISSUE TITLE
E23: No alternate file when using CTRL+^ to jump between files

### ISSUE THREAD

**Issue by schneems** [VSCodeVim/Vim#7357]
**Describe the bug**

Previously I was able to use CTRL+^ to jump between files, but something changed recently and now I'm unable to use that feature. I get an error instead. Here's a video. I open one file via the finder (CMD+P) then I try to jump back using CTRL+^ and  I get an error "E23: No alternate file". 

https://imgur.com/a/Oj4Lpsi

**To Reproduce**

1.  Open a file
2. Open another file
2.  Press CTRL+^
4.  See error

**Expected behavior**

vscode should jump back to the previous file

**Screenshots**

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/59744/147773171-0418b743-d1d6-4c8d-9af6-c32cdbc27f8c.png">

I checked my logs after setting them to debug, but got nothing with the key press CTRL+^ I may have done it incorrectly

**Environment (please complete the following information):**

Extension version: 1.21.10
Vscode version: 1.63.2
OS: Mac Big Sur 11.6.2 (20G314)

**Comment by J-Fields** [comment]
Thanks for the bug report - this was fixed recently on `master` and will be in the next release

**Comment by schneems** [comment]
> Thanks for the bug report - this was fixed recently on master and will be in the next release

OMG thank you! This has been driving me up the wall. It's hard to know if a problem is on my end or an extension. Thanks for the the update and thanks for all your work ❤️

**Comment by schneems** [comment]
Hey sorry to be a bother. When do you think y'all can cut a release?

**Comment by schneems** [comment]
I'm on the latest release and it's not working.

Error when using CTRL+^:


<img width="1904" alt="image" src="https://user-images.githubusercontent.com/59744/155562976-c0fa9184-6e5f-4a70-a83e-f8f7af0508d2.png">


Vim version:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/59744/155562837-9e42b7a0-7889-4c42-bb9a-15db61969f5c.png">

Vscode version:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/59744/155562881-1ca31c2c-4907-4c20-bbc0-0a237563a80a.png">

**Comment by schneems** [comment]
I tried this again today and IT WORKS!!!!!!!! Thank you! thank you! thank you! ❤️💜💚
