### ISSUE TITLE
```:marks``` to list marks doesn't work

### ISSUE THREAD

**Issue by coughingmouse** [VSCodeVim/Vim#7367]
**Describe the bug**
Using ```:marks``` to list marks doesn't work.

**To Reproduce**

1.  Open up and save a text file (say, a ```.py``` file)
2.  While in normal mode, press ```ma``` to mark position at wherever your cursor is as ```a```
3.  Type ```:marks``` and enter to list all the marks
4.  See that VSCode only pops up "No marks set"

**Expected behavior**
It should list the marks???

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.10
- VSCode version:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.8-76051508-generic
- OS: Pop!_OS 21.10

**Additional context**

**Comment by keidarcy** [comment]
https://github.com/VSCodeVim/Vim/blob/HEAD/ROADMAP.md#marks-and-motions
It's not implemented yet.

**Comment by J-Fields** [comment]
> It's not implemented yet.

Unfortunately the roadmap isn't up to date - `:marks` is implemented, but it does seem broken
