### ISSUE TITLE
Extremely slow search/replace using %s/search/replace/g command

### ISSUE THREAD

**Issue by daviwil** [VSCodeVim/Vim#737]
Hey guys, the extension works a lot better in the latest release of it and VS Code!  Mode changing and movements are feeling pretty solid now.  However, I'm seeing a pretty big performance issue with the search/replace Vim command:
### What did you do?
1. Opened a log file with about 15,000 lines
2. Pressed `:` to open the Vim command pane
3. Typed `%s/VERBOSE/TEST/g` and pressed Enter
4. Didn't seem like anything was happening but about 15 seconds later I noticed that the replacements had been applied.
5. Pressed `u` to undo the changes and now the undo is taking about 5 minutes to apply.
### What did you expect to happen?

One edit that applies all changes, not multiple individual edits which take a long time to to apply.
### What happened instead?

See repro steps.
### Technical details:
- VSCode Version: 1.5.0 Stable
- VsCodeVim Version: 
- OS: Windows 10

**Comment by johnfn** [comment]
Making the substitution command atomic is pretty straightforward. @rebornix I defer this to you since that was your domain. 😉 

I think by doing so that will also make the undo atomic? Will have to look into that more.

**Comment by daviwil** [comment]
Yeah, I would think making the substitution command atomic should mean the undo would be atomic.  If not then maybe we found a VS Code bug :)

**Comment by johnfn** [comment]
@daviwil we actually handle undo/redo with our own separate thing due to... reasons. So it's not entirely certain that it will be atomic. It should be, though!

**Comment by Chillee** [comment]
This is fixed with the new "enableNeovim" option (not yet released).
