### ISSUE TITLE
Keybindings Description

### ISSUE THREAD

**Issue by jpoon** [VSCodeVim/Vim#738]
Fill out the descriptions for the keybindings in `package.json`:

![untitled](https://cloud.githubusercontent.com/assets/85374/18367147/8baedc3a-75ce-11e6-8d59-fcb433576c8b.png)

**Comment by johnfn** [comment]
Heh, but what do we even want to say for these characters? :P

**Comment by gkeary** [comment]
I have an edited copy of package.json and would like to submit it for review.  But how?  to whom? and how did jpoon get the screenshot shown above?

**Comment by jpoon** [comment]
> But how? to whom?
Fork and submit a PR

> how did jpoon get the screenshot shown above?
If you are running the latest VSCode, go to the extension manager, click on VIM, and then the 'contributes' tab.
