### ISSUE TITLE
customize the commands of Easymotion

### ISSUE THREAD

**Issue by creater-zq** [VSCodeVim/Vim#7381]
How to customize the commands of Easymotion? For example, replace < leader > < leader > s < char > with < leader > EM < char > 
thanks.

**Comment by w-cantin** [comment]
Hi, you can remap any keys with the `vim.normalModeKeyBindingsNonRecursive` setting in VSCode's `settings.json`

```json
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["leader", "e", "m"],
      "after": ["leader", "leader", "s"]
    },
]
```

**Comment by creater-zq** [comment]
> Hi, you can remap any keys with the `vim.normalModeKeyBindingsNonRecursive` setting in VSCode's `settings.json`
> 
> ```json
>   "vim.normalModeKeyBindingsNonRecursive": [
>     {
>       "before": ["leader", "e", "m"],
>       "after": ["leader", "leader", "s"]
>     },
> ]
> ```

nice，thanks
