### ISSUE TITLE
cw doesn't work on empty line

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#739]
### What did you do?

```js
if (true)
|// Nothing other than newline here
}
```

Press `cw`

### What did you expect to happen?

```js
if (true) {
|// Nothing other than newline here
}
```

in insert mode.

### What happened instead?

```js
if (true) {

}|
```

In insert mode.

### Technical details:

* VSCode Version: 1.5.0
* VsCodeVim Version: 0.1.10
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
What a bizarre bug!
