### ISSUE TITLE
`C-w` + `H/J/K/L` to toggle vertical/horizontal splits.

### ISSUE THREAD

**Issue by achenchen1** [VSCodeVim/Vim#7400]
Apologies if this is a dupe or a user error, couldn't find any on this.

Vim allows using `C-w`+`H/J/K/L` to send a pane to the Left/Bottom/Up/Right respectively. This allows the user to move the current pane to the bottom, maybe to prioritize another pane on the top. Additionally, this allows the user to change a vertical split to a horizontal split.

**Ideally** the full feature can be implemented, but I think at the very least it would be nice to be able to switch between horizontal/vertical splits.

This is a very old thread, in a non-VSCodeVim thread, but I think this might be helpful:
`https://github.com/microsoft/vscode/issues/1749#issuecomment-270653425`

**Comment by YalandHong** [comment]
>Vim allows using C-w+H/J/K/L to send a pane to the Left/Bottom/Up/Right respectively.

I can do so with no problem.
![2022_01_20_16_13_54](https://user-images.githubusercontent.com/52960068/150299863-a1d70c82-f938-4921-8f9a-39f981cb5639.gif)

**Comment by achenchen1** [comment]
@YalandHong , using HJKL (i.e. shift+h) in vim will "send" a pane to a specific location. In other words, if should be C-w followed by shift h/j/k/l. I realize I wasn't very clear, which is my fault.

**Comment by w-cantin** [comment]
Hello,

It is possible to do the same in VSCodeVim by remapping VSCode native's commands using `  "vim.normalModeKeyBindingsNonRecursive" ` setting and the `"commands"` attribute. The VSCode commands are the following: `workbench.action.moveActiveEditorGroupDown` where you can substitute "Down" for "Up", "Left" and "Right" to get the 4 directions. In your case it would look like this:

```json
  "vim.normalModeKeyBindingsNonRecursive": [
    { "before": ["<C-w>", "h"], "commands": ["workbench.action.moveActiveEditorGroupLeft"] },
   { "before": ["<C-w>", "j"], "commands": ["workbench.action.moveActiveEditorGroupDown"] },
...
]
```

**Comment by poliyka** [comment]
My settings like this.  
```json
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["<c-w>", "t", "l"],
      "commands": ["workbench.action.moveEditorToNextGroup"]
    },
    {
      "before": ["<c-w>", "t", "h"],
      "commands": ["workbench.action.moveEditorToPreviousGroup"]
    },
    {
      "before": ["<c-w>", "t", "k"],
      "commands": ["workbench.action.moveEditorToAboveGroup"]
    },
    {
      "before": ["<c-w>", "t", "j"],
      "commands": ["workbench.action.moveEditorToBelowGroup"]
    },
    {
      "before": ["<C-w>", "g", "l"],
      "commands": ["workbench.action.moveActiveEditorGroupRight"]
    },
    {
      "before": ["<C-w>", "g", "h"],
      "commands": ["workbench.action.moveActiveEditorGroupLeft"]
    },
    {
      "before": ["<C-w>", "g", "j"],
      "commands": ["workbench.action.moveActiveEditorGroupDown"]
    },
    {
      "before": ["<C-w>", "g", "k"],
      "commands": ["workbench.action.moveActiveEditorGroupUp"]
    },
...
]
```

**Comment by achenchen1** [comment]
Fix from @poliyka and @w-cantin works for me - my `settings.json` now has following lines:
```json
    "vim.normalModeKeyBindingsNonRecursive": [
        { "before": ["<C-w>", "H"], "commands": ["workbench.action.moveActiveEditorGroupLeft"] },
        { "before": ["<C-w>", "J"], "commands": ["workbench.action.moveActiveEditorGroupDown"] },
        { "before": ["<C-w>", "K"], "commands": ["workbench.action.moveActiveEditorGroupUp"] },
        { "before": ["<C-w>", "L"], "commands": ["workbench.action.moveActiveEditorGroupRight"] },
    ]
```

I think this issue can be closed, since it looks like I found a solution. :)
