### ISSUE TITLE
gh to show variable value in debug mode

### ISSUE THREAD

**Issue by shogunsea** [VSCodeVim/Vim#7409]
**Is your feature request related to a problem? Please describe.**
From the doc, `gh` meant to behave as if cursor hover over a variable, this works perfectly except in vscode's debug mode, where `gh` still shows the definition or types of the variable, while hovering over the variable actually shows the varaible's currently evaluated result. 

both of the screenshots are taken in debug mode:

`gh`:
<img width="1518" alt="gh" src="https://user-images.githubusercontent.com/2238944/150405210-d8627989-f503-4f98-bbf2-e232ee056752.png">

hover over:
![image](https://user-images.githubusercontent.com/2238944/150405140-c1e47f74-9059-4098-8eec-6e3305303b5d.png)

**Describe the solution you'd like**
`gh` should provide a way to show evaluated variable value in debug mode. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by w-cantin** [comment]
Hello,

Although not exactly what you were asking for, it is possible to remap pretty much any vscode command in VSCodeVim using the `  "vim.normalModeKeyBindingsNonRecursive" ` setting and the `"commands"` attribute. In your case it would look like this:

```json
  "vim.normalModeKeyBindingsNonRecursive": [
    { "before": ["leader", "g", "h"], "commands": ["editor.debug.action.showDebugHover"] },
]
```

This remapping does not automatically detect when VSCode is in debug mode but it might still be useful.

**Comment by shogunsea** [comment]
@w-cantin that works perfectly! thank you so much
