### ISSUE TITLE
n-Y, to copy n lines into buffer, copies only one line

### ISSUE THREAD

**Issue by joa-quim** [VSCodeVim/Vim#741]
### What did you do?

Tried to copy n lines into buffer. Example: 3Y

### What did you expect to happen?

To have 3 lines copied into the buffer

### What happened instead?

only one line was copied

### Technical details:

* VSCode Version:

  1.5.1

* VsCodeVim Version: *[please ensure you are on the latest]*

  0.1.10

* OS: 

  Win10 Anniversary Edition

**Comment by johnfn** [comment]
Note that 3y works. We should get 3Y to work as well.

**Comment by joa-quim** [comment]
Ah, didn't know that. I learned about Y many Years ago and that's what I have used.
But the 'y' had a feature.  If you hit 'y' when the cursor is not in first character of line it will copy only the remaining characters of that line and the following lines, but will leave out the n-1 characters of first line.

**Comment by johnfn** [comment]
Yeah, of course. We'll add #Y eventually. :)

**Comment by joa-quim** [comment]
Ok, thanks.

**Comment by xconverge** [comment]
3y doesnt work correctly either...

if you do:

|test
test
test
test

then press 3yj, 

when you paste you get

test
test
t

**Comment by johnfn** [comment]
@xconverge that is not the behavior I see. My version of vscodevim (0.1.10) copies all 4 lines.

**Comment by xconverge** [comment]
hmm I can get it to do both, correct, and incorrect

**Comment by johnfn** [comment]
How do we repro the incorrect way 😉

**Comment by johnfn** [comment]
Fixed. Thanks for the report, @joa-quim!
