### ISSUE TITLE
Curly braces' position is changed after using '=' to indent code.

### ISSUE THREAD

**Issue by aoyulong** [VSCodeVim/Vim#742]
1.  `shift + v`: select the code blocks.
2. `=`:  automaticlly indent them.

However, vscodevim changes the position of the curly braces and they aren't on their own lines any more.

Before formatting:
![before](https://cloud.githubusercontent.com/assets/3069790/18376697/e55c97fc-7693-11e6-91b0-379644a56de2.jpg)

After formatting:
![after](https://cloud.githubusercontent.com/assets/3069790/18376707/f5a80e8e-7693-11e6-8e6e-543d1728b00f.jpg)

* VSCode Version: 1.5.1
* VsCodeVim Version: 0.1.10
* OS:  win10 64bit.

**Comment by johnfn** [comment]
We just use the built-in Visual Studio Code formatter, so we don't really have any control over this. You might want to bug them over on github.com/Microsoft/vscode :)
