### ISSUE TITLE
Discrepencies between Vim and VSCodeVim in Insert Line Below

### ISSUE THREAD

**Issue by half-potato** [VSCodeVim/Vim#7423]
Issue Type: <b>Bug</b>

**Describe the bug**
- 'Shift + O' does not inherit the tab level of the line it is executed from. Instead, it inherits the tab level of the line above. The behavior should be more similar to 'O', which inherits the tab level of the current line and continues it onto the next.

**To Reproduce**

1.  Indent at 2 lines of code
2.  Insert a new line between the two lines.
3.  Remove the trailing tab on the new line so the line is empty
4.  Press shift+o on the second line of code in normal mode.
5. Observe that it starts the cursor at 0 tabs
6. Press o on the first line of code in normal mode.
7. Observe that it starts the cursor at 1 tab.

**Additional context**
Yes it really bothers me. The autocomplete tries to put in random shit when I press tab to get back to the normal level.

Extension version: 1.21.10
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:16:45.441Z)
OS version: Linux x64 5.10.89-1-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor (16 x 2282)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.37GB (0.96GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id c0bfebf1-f778-4651-8101-90dc613e2ecb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30424896
pythonvs932:30410667
wslgetstarted:30426333
vscop804:30404766
vscop341:30404997
vsrem710:30416614
vsbas813:30426126
vsic-wlc-tsjs:30426436

```

</details>

**Comment by northernocean** [comment]
I also see this as different behavior between Vim and VsCodeVim. For what it is worth, I guess it is also different behavior between o and shift-o in a situation where the same behavior would make more sense - although personally I can't really tell which way I would prefer  ¯\\_(ツ)_/¯  .

I see a PR was submitted.
Until then a workaround is to remap the keys to the setting you prefer in your settings.json (or vimrc):
```   
    "vim.normalModeKeyBindingsNonRecursive": [
        { 
            "before":["O"],
            "after": ["o"] 
        }
    ]
```
or ...

```   
    "vim.normalModeKeyBindingsNonRecursive": [
        { 
            "before":["o"],
            "after": ["O"] 
        }
    ]
```
