### ISSUE TITLE
why sneak doesn't highlight matching results using different characters as expected? 

### ISSUE THREAD

**Issue by hopezh** [VSCodeVim/Vim#7429]
The vim-sneak as implemented in neovim will highlight matching search results with different characters, as shown blow, assuming I'm search all instances of "import" by typing `s`+`i`+`m` in neovim. 

![Image 10](https://user-images.githubusercontent.com/23435810/151144655-3981b2cf-c8c2-4415-a89b-7ce086cf5f87.png)

However, the vim-sneak enabled by vscode-vim inside vscode only goes to the first instance of the search results, and there are no highlights of other instances. 

So, what's the point of enabling vim-sneak inside vscode?

**Comment by w-cantin** [comment]
As you can tell, the sneak implementation actually present in Vscode is quite basic and only jumps to the first search instance. That is why #7162 was created. The PR has more features enabled like label mode and better highlighting. It will be merged eventually to the main branch.

**Comment by hopezh** [comment]
Thank you very much, @w-cantin. Looking forward to seeing the implementation in future release.

**Comment by gengdz** [comment]
my VSCodeVim version is up to date,but I found it still wasn't highlighted！so what should i do to make it work @w-cantin

**Comment by w-cantin** [comment]
Hello!

I wish I had better news but the new functionality has not been added to the main branch yet. The Pull Request has been stuck for a few months. I am not quite sure the reason why but the core maintainer is probably very busy and can't really afford to put that much time in VSCodeVim anymore. I will see if I can get the ball rolling again as it seems to be a feature wanted by many. 

There was a temporary fork of VSCodeVim I made here but it is quite outdated by now so some fixes might be missing. Nevertheless, it might be useful to you: [vscodevim-sneak-fork](https://marketplace.visualstudio.com/items?itemName=vscodevim-sneak-fork.vscodevim-sneak-fork).
