### ISSUE TITLE
ddp appends extra newline when pasting

### ISSUE THREAD

**Issue by jgoz** [VSCodeVim/Vim#743]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`ddp`

### What did you expect to happen?

Delete current line and paste below following line.

### What happened instead?

Delete current line and paste deleted line _plus an extra trailing newline_ below following line.

### Technical details:

* VSCode Version: 1.5.1
* VsCodeVim Version: 0.1.10
* OS: Windows 10 x64

**Comment by johnfn** [comment]
I can't reproduce this. What does the text that you're editing look like?

**Comment by jgoz** [comment]
Demonstrated in the gif below. I typed `ddp` on `Line 1`.

![vimissue](https://cloud.githubusercontent.com/assets/132233/18402403/6bf4ddb2-769c-11e6-8781-b98a9f54a6cc.gif)

**Comment by jgoz** [comment]
@johnfn What is the value of `"files.eol"` in your VS Code? Mine is `"\r\n"` on Windows.

**Comment by johnfn** [comment]
Even with \r\n I can't reproduce this. Very strange.

**Comment by johnfn** [comment]
You don't have anything strange in your settings.json or anything right? Any packages which might be affecting this behavior?

**Comment by jgoz** [comment]
`settings.json`:

```json
{
    "editor.fontSize": 12,
    "editor.glyphMargin": true,
    "editor.lineHeight": 15,
    "editor.renderIndentGuides": true,
    "explorer.openEditors.visible": 0,
    "telemetry.enableTelemetry": false,
    "window.restoreFullscreen": true,
}
```

Extensions:
- jslint
- jshint
- EditorConfig (maybe?)
- TSLint
- C#
- Debugger for Chrome
- Vim

**Comment by jgoz** [comment]
Uninstalled `EditorConfig`, no change in behaviour

**Comment by jgoz** [comment]
@johnfn I launched the extension in a debug session and I believe the issue is due to `\r\n` characters _in the file being edited_. It's not enough to set your `"files.eol"` setting, the file itself must have CRLF newline characters.

If you delete a line with the text `"Line 1\r\n"`, after [this line](https://github.com/VSCodeVim/Vim/blob/bb9ede49da75ca6e4bb569dcc20f906c54736942/src/actions/actions.ts#L1034) is executed, `text` will contain `"Line 1\r"`. Once it gets pasted again, the `\r` character will be normalized to another `\r\n` (probably by VSCode).

I'm not sure if this is a valid test, but it fails with the latest master:

```ts
newTest({
  title: "Can handle ddp with CRLF",
  start: ['|one\r', 'two\r'],
  keysPressed: 'ddp',
  end: ["two\r", "|one\r"],
});
```
