### ISSUE TITLE
Pasting in command mode pastes in editor instead

### ISSUE THREAD

**Issue by dsynkd** [VSCodeVim/Vim#7444]
**Describe the bug**

Pasting in command mode pastes in editor instead

**To Reproduce**

1. Open an editor tap in visual studio in vim mode
2. Enter command mode using `:`
3. Attempt to paste text using `ctrl+v` (windows) or `cmd+v` (mac)

**Expected behavior**

Text to be pasted into the command line space at the bottom bar.

**Screenshots**

<img width="1792" alt="Screen Shot 2022-01-31 at 1 25 13 PM" src="https://user-images.githubusercontent.com/46543723/151876244-81f2bd2b-fe80-44ba-9716-1f381bd4e7bc.png">

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.21.10
- VSCode version: 1.60.2
- OS: Mac OS Big Sur (11.6.2)

**Comment by w-cantin** [comment]
Hello, 

It is possible to paste in the content of any vim register in commandLine mode using `Ctrl+R` and then the vim register wanted (this is a feature present in regular vim as well as VSCodeVim). The `+` register refers to the default OS clipboard.
 It is then possible to paste in the content of the clipboard in commandLine mode by pressit `Ctrl+R`  and `+`.

This key combination can be easily remapped with the command `vim.commandLineModeKeyBindings` like so:

```json
  "vim.commandLineModeKeyBindings": [
    {
      "before": ["<C-v>"],
      "after": ["<C-r>", "+"]
    }
  ],
```

**Comment by dsynkd** [comment]
Huh I tried this now and it seems to be working, even without the fix above. Not sure what changed. Closing this for now.
