### ISSUE TITLE
tab completion on vim command line should work

### ISSUE THREAD

**Issue by lzybkr** [VSCodeVim/Vim#745]
### What did you do?

ESC : e c:<TAB>
### What did you expect to happen?

tab completion of files in c:\
### What happened instead?

nothing
### Technical details:
- VSCode Version: 1.5.1
- VsCodeVim Version: 0.1.10
- OS: Win10 Anniversary Edition

**Comment by johnfn** [comment]
@rebornix any idea if this is even possible? Can we manipulate the text in the popup?

If not, is there another type of display that we *could* manipulate? We could do the thing I do with search, but that is somewhat subpar.

**Comment by rebornix** [comment]
@johnfn I'm implementing `:reg {arg}` command and has similar feature request and I'm still playing with that part. If there is not such API, then it's a real valid feature request for VS Code. Will drop more info later.

**Comment by rebornix** [comment]
Related to https://github.com/Microsoft/vscode/issues/426

**Comment by xconverge** [comment]
This should be doable now that we moved the commandline to the status bar

**Comment by lipp** [comment]
Any news on this? IMHO - as a vim user - navigating files with `:e` + autocomplete / tab and switch with `:b` + autocomplete / tab is super important. Would be very cool and I'd love to switch to vscode :)

**Comment by dgaleazzo** [comment]
@lipp this is the only reason I'm still using vim instead to use vscode.

**Comment by japhillips87** [comment]
this will probably be a deal breaker for me too.

**Comment by keith-ferney** [comment]
I have started on a fix for this, it is not complete yet but here is the repo link
https://github.com/keith-ferney/Vim

**Comment by osdf** [comment]
Hallo,
on a Mac, typing ':e ~/' and then hitting tab does not work. Tab completion seems to work for files, but not for folders. Is there a solution/workaround here?

**Comment by marcushwz** [comment]
Hello, 
I am using VSCodeVim on a ubuntu machine. I have one issue when i tried to use the tab completion for files in the working folder. It seems that the "/" is not added after my current directory when I try to search for files in a folder. For example, I am currently in "workspace/jobs-listing", then when I tried to search for files in my templates folder, I do ":e templates/<tab>" in vim command line. Unfortunately, I received the error as shown in the picture.
![vscodevim-error](https://user-images.githubusercontent.com/40255418/63664959-af1ad200-c7fb-11e9-8481-0a7cf944814e.png)

 I think this is fixable but I do not know how. Hope to hear from you guys here. Thanks and have a great day!
