### ISSUE TITLE
Using vim command line to edit file uses incorrect path

### ISSUE THREAD

**Issue by lzybkr** [VSCodeVim/Vim#746]
### What did you do?

ESC : e e:\src\PowerShell\build.psm1

### What did you expect to happen?

open the file e:\src\PowerShell\build.psm1

### What happened instead?

attempt to open the file `c:\current\dir\e:\src\PowerShell\build.psm1`
and offer to create that file

### Technical details:

* VSCode Version: 1.5.1
* VsCodeVim Version: 0.1.10
* OS: Windows 10 Anniversary Update

**Comment by rebornix** [comment]
@lzybkr currently the way we handle path is using current folder as base path. Apparently we can improve this feature.

**Comment by jpoon** [comment]
Seems like we should figure out whether the path is an absolute path. Otherwise assume it's relative.

**Comment by johnfn** [comment]
We should probably use some sort of path resolver module. Lots of tricky edge cases here.

**Comment by rebornix** [comment]
`path.isAbsolute` already does the trick :)
