### ISSUE TITLE
Cannot redo with Ctrl-Shift-Z

### ISSUE THREAD

**Issue by xfq** [VSCodeVim/Vim#749]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Insert some characters, then press `u` to undo, and press `⇧⌘Z` to redo.

### What did you expect to happen?

The characters deleted by `u` should be reinserted.

### What happened instead?

Nothing happens. But `Ctrl-R` seems to work. I'm not sure if this is a bug or an intended feature. Personally, I got used to use `⇧⌘Z` (or `Ctrl-Shift-Z` on Linux/Windows) to redo.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.10
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
Use ctrl-r! 😉 

We should actually disable ctrl-shift-z, but allow people to remap it to ctrl-r if they desire.

**Comment by xfq** [comment]
@johnfn May I ask you why ctrl-shift-z doesn't work? Is it because the undo/redo state in Vim is different from the undo mechanism in VS Code? I'm not familiar with the theory. Thank you!

**Comment by xconverge** [comment]
@xfq yes that is exactly the case

**Comment by rebornix** [comment]
@xfq if you type chars in insert mode, `cmd+z` to undo and then run `shift+cmd+z`, you can see the redo functionality works. The only thing we are trying to avoid is messing Vim's undo/redo with the one VS Code has.

I'd like to close this first but if you think it's a bad idea, let us know.

**Comment by xfq** [comment]
@rebornix 

Personally, I use `⇧⌘Z` (or `Ctrl-Shift-Z` on Linux/Windows) to redo on MacVim, Atom+`vim-mode`, and Spacemacs. And I've had no issues.

I don’t know how many other users have encountered this type of problem. It's OK for me if VSCodeVim developers decide not to fix this "bug", but IMHO this "known issue" should at least be documented somewhere, or (like @johnfn said) just disables ctrl-shift-z and allow people to remap it to ctrl-r if they desire.

Thank you for developing/maintaining VSCodeVim!

**Comment by Sylk** [comment]
Ctrl z bring me to the bottom of the page...? It makes no sense.

**Comment by J-Fields** [comment]
@Sylk Not sure why that would be - is this after remapping `<C-z>` to `u`?

**Comment by Sylk** [comment]
Remapping seems to have fixed it.  Thank you.
