### ISSUE TITLE
Cursor width problem (CJK characters)

### ISSUE THREAD

**Issue by xfq** [VSCodeVim/Vim#751]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Put the cursor on a Chinese character.

### What did you expect to happen?

The width of the cursor should be equal to the width of the character.

### What happened instead?

The width of the cursor is narrower than the width of the character. I'll add some example screenshots below for the words below:

```
C	printf ("Hello, world!\n");
English /ˈɪŋɡlɪʃ/	Hello

Japanese (日本語)	こんにちは / ｺﾝﾆﾁﾊ
Chinese (中文,普通话,汉语)	你好
Cantonese (粵語,廣東話)	早晨, 你好
Korean (한글)	안녕하세요 / 안녕하십니까
```

Cursor on a Japanese kana symbol (**VS Code**):
<img width="501" alt="screen shot 2016-09-10 at 7 12 30 pm" src="https://cloud.githubusercontent.com/assets/2863444/18410137/1d475352-778c-11e6-8dae-041f346824b9.png">

Cursor on a Chinese character (**VS Code**):
<img width="468" alt="screen shot 2016-09-10 at 7 12 41 pm" src="https://cloud.githubusercontent.com/assets/2863444/18410132/160c59fc-778c-11e6-8be6-53d1f4ea7605.png">

Cursor on a letter of the Latin script (**VS Code**):
<img width="459" alt="screen shot 2016-09-10 at 7 12 55 pm" src="https://cloud.githubusercontent.com/assets/2863444/18410138/24bdab04-778c-11e6-933c-8a4c3811a684.png">

Cursor on a Japanese kana symbol (**Atom**):
<img width="331" alt="screen shot 2016-09-10 at 7 21 48 pm" src="https://cloud.githubusercontent.com/assets/2863444/18410140/2a205420-778c-11e6-8a9f-b435b00f63e1.png">

Cursor on a Japanese kana symbol (**Emacs**):
<img width="1280" alt="screen shot 2016-09-10 at 7 22 37 pm" src="https://cloud.githubusercontent.com/assets/2863444/18410141/31f819b2-778c-11e6-8b63-16259118edf8.png">

I don't have a Vim at hand, so there's no screenshot for Vim. But based on my experience, the cursor width is right for CJK characters in Vim.

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.10
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
Umm, is this a VSCode problem or a VSCodeVim problem? :P

**Comment by xfq** [comment]
@johnfn I'm not sure whether the problem is in VSCodeVim.

In `code --disable-extensions`, the cursor is a vertical bar *between* two characters; in VSCodeVim, the cursor is a box *on* a character. If it's a VSCode problem, I don't know how to reproduce it with `code --disable-extensions`.

**Comment by johnfn** [comment]
We are actually using the built-in visual studio block cursor. You can turn it on without Vim by putting `	"editor.cursorStyle": "block",` in your settings.json (and deactivating Vim and restarting).

**Comment by Yukaii** [comment]
It works correctly without Vim extension:

![screen shot 2016-09-11 at 3 22 42 pm](https://cloud.githubusercontent.com/assets/4230968/18415856/a2b004e2-7833-11e6-94ed-0c47b6e080d1.png)

**Comment by jpoon** [comment]
Thanks for confirming @Yukaii; I also see the same behaviour with naked VSCode + `editor.cursorStyle: "block"`. 

@xfq would you like to move this issue over to https://github.com/Microsoft/vscode?

**Comment by rebornix** [comment]
Thanks @Yukaii it's a valid Code bug and I've filed an issue there https://github.com/Microsoft/vscode/issues/11859 .
