### ISSUE TITLE
keyboard shortcut is not working for copy, paste, tab space, search 

### ISSUE THREAD

**Issue by rajshubham2401** [VSCodeVim/Vim#7531]
Issue Type: <b>Bug</b>

when we press ctrl + X, ctrl + C, ctrl + V then selected content should be cut, copy, paste but due to this extension this feature is not working .

Unable to give tab space with tab button
Unable to search with keyboard btn

Extension version: 1.22.2
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.13.0-30-generic snap
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstartedc:30433508
vsclayoutctrc:30437038
vsrem710cf:30416617
dsvsc008:30440022
pythonvsnew555:30442236
vsbas813:30436447
vscscmwlcmc:30438804
helix:30440343

```

</details>

**Comment by igoracmelo** [comment]
Well, that is how Vim works.
ctrl + C takes you back to normal mode, ctrl + V is for visual block mode and ctrl + X subtracts a number at or after the cursor.

**Comment by rajshubham2401** [comment]
Well, got your point
Thanks a lot for your comment
