### ISSUE TITLE
Please re-open issue #7357 "E23: No alternate file when using CTRL+^ to jump between files"

### ISSUE THREAD

**Issue by schneems** [VSCodeVim/Vim#7533]
This issue was closed by a maintainer and I do not have the ability to re-open it https://github.com/VSCodeVim/Vim/issues/7357. I'm still seeing the issue on the latest release.

Sorry for the issue spam, I don't know if replies are otherwise monitored.

**Comment by J-Fields** [comment]
Thanks. Should be fixed in next version via https://github.com/VSCodeVim/Vim/commit/b64799c2b5045e6c9319a13e2accc6feb7660b97

**Comment by ZackPlauche** [comment]
> Thanks. Should be fixed in next version via [b64799c](https://github.com/VSCodeVim/Vim/commit/b64799c2b5045e6c9319a13e2accc6feb7660b97)

It's still not working on mine tho 👀

**Comment by schneems** [comment]
Same. Is there some more info we could provide or debugging steps we could take to help isolate the specific issue? 

Perhaps there are multiple possible issues or a combination of bugs and our specific case hasn’t been fixed yet?

**Comment by J-Fields** [comment]
No need, there just hasn't been a release in a while, still need to tie some loose ends.

**Comment by schneems** [comment]
Gotcha, sorry for the noise! Thanks for your work!
