### ISSUE TITLE
Using j,k,l,i to navigate inside explorer list

### ISSUE THREAD

**Issue by tbson** [VSCodeVim/Vim#754]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

That's great if I can forget arrow keys when using VIM mode. That feature already have on Sublime & Atom but I can't find it on VSCode with VSCodeVim.

**Comment by jpoon** [comment]
Oh! Great idea.

**Comment by rebornix** [comment]
Currently we don't expose such extensibility for file explorer in Code but definitely I see the reason people want it. This feature request is tracked by https://github.com/Microsoft/vscode/issues/11517 and https://github.com/Microsoft/vscode/issues/4557 .

**Comment by dallas** [comment]
Can we tack onto this the ability to use `<c-j>` and `<c-k>` (or something) to navigate the autocomplete list as well, or should I open a new issue for that?

**Comment by johnfn** [comment]
@dallas A bit of a late response here, but `<C-n>` and `<C-p>` have been added to navigate the autocomplete list.

**Comment by bpasero** [comment]
@tbson would you expect to use these keys only in the explorer or any tree inside VS Code (there are _many_, e.g. search)?

**Comment by johnfn** [comment]
@bpasero - it would be awesome to also be able to use those keys inside of other trees like search!

**Comment by rebornix** [comment]
@bpasero just for your information, it would be a big plus if Code provides a command to move focus between panels only by position. Right now we can do that for grouped editors but no luck with panels I suppose.

**Comment by bpasero** [comment]
@rebornix can you explain in more detail what this means? and does it apply to only panels or also viewlets?

**Comment by rebornix** [comment]
@bpasero sorry for the misleading wording. In Vim with a file explorer extension, the explorer viewlet is treated as a window, just like the editing area. You can use `ctrl+w` + `hjkl` to navigate your cursor between these windows. So in VS Code, if the cursor is in the first grouped window, users would expect to use `ctrl+w`+`h` to move cursor the left side viewlet, no matter what it is.

It's also the same for panels, I'm not sure whether we already have a command for switching focus between visible editor/panel/viewlet. If not, that's what we need.

**Comment by bpasero** [comment]
@rebornix so let's assume you have explorer visible, 2 editors side by side and panel. Pressing `ctrl+w h` would focus the explorer, how would `jkl` navigate in this layout? And I assume it would only navigate between visible windows, not bring up hidden ones? Maybe best to file this as issue in the VS Code repo.

**Comment by bpasero** [comment]
Configurable tree/list commands are added for February release via https://github.com/Microsoft/vscode/issues/11517

**Comment by rebornix** [comment]
We don't need to wait for any update from Vim side to experience this feature, right now you can bind you navigation keys to new tree/list commands @bpasero introduced in 1.10, like below

```
    {
        "key": "j",
        "command": "list.focusDown",
        "when": "listFocus"
    },
    {
        "key": "k",
        "command": "list.focusUp",
        "when": "listFocus"
    },
    {
        "key": "enter",
        "command": "list.select",
        "when": "explorerViewletVisible && filesExplorerFocus"
    },
    {
        "key": "o",
        "command": "list.toggleExpand",
        "when": "listFocus"
    }
```

**Comment by misoguy** [comment]
works like a charm 👍

**Comment by xconverge** [comment]
@rebornix should we just put that in the readme? Or do you think we should do something else on our side?

**Comment by bpasero** [comment]
Wouldn't it make sense that the VIM extension defines these commands with those keybindings if that is what any VIM user expects?

**Comment by rebornix** [comment]
Yes, we can put these keybindings in our package.json, which is a better
solution to users.

**Comment by xconverge** [comment]
awesome

**Comment by dsifford** [comment]
@rebornix 

> Yes, we can put these keybindings in our package.json, which is a better
solution to users.

Any idea when we should expect this to land? Doesn't look like this was included in `Cupcake Copier`.

**Comment by dsifford** [comment]
@bpasero I'm looking through the changes now on this and I can't seem to figure out how to target specifically the up/down navigation of the workbench and autocomplete suggestion lists.

Any tips?

(for these situations, in order to map `hjkl` and still be able to type, my preference is to map `ctrl+[hjkl]` to the navigation commands).

Thanks in advance!

**Comment by xconverge** [comment]
@dsifford not sure, when it will land you can use the rebinding he posted, and then we already have bindings for autocomplete suggestion lists ctrl+n and ctrl+p, so if you want to you could rebind ctrl+j to ctrl+n etc...

**Comment by dsifford** [comment]
@xconverge Aha! Thanks for that 😄 

If anybody else out there is interested in the ctrl+j and ctrl+k to move up/down in the workbench and autocomplete suggestion list (and have `vim.useCtrlKeys` disabled), here's the keymaps for that...

```json
{
    "key": "ctrl+j",
    "command": "selectNextSuggestion",
    "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
},
{
    "key": "ctrl+k",
    "command": "selectPrevSuggestion",
    "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
},
{
    "key": "ctrl+j",
    "command": "workbench.action.quickOpenNavigateNext",
    "when": "inQuickOpen"
},
{
    "key": "ctrl+k",
    "command": "workbench.action.quickOpenNavigatePrevious",
    "when": "inQuickOpen"
}
```

@bpasero Not sure if this has been suggested yet or not, but tracking down these commands made me realize how much I took for granted Atom's keybinding resolver mode. Adding something similar to vscode would be amazing. 🙏

**Comment by johnfn** [comment]
@rebornix how exactly do we query `"when": "listFocus"` in our code? That's the last missing piece of this puzzle.

**Comment by rebornix** [comment]
@johnfn we can't query context key in extension, that's basically why we have so many context variables in contribution part.

**Comment by callamaris** [comment]
the keymap posted by rebornix works in the explorer, search and extensions panel.

is it also possible to configure this for the git panel?

**Comment by bpasero** [comment]
It should work in any tree or list widget (except for the "Find References" tree).

**Comment by LeonB** [comment]
Is it possible to add gg/g as home/end in the explorer window?

**Comment by Chillee** [comment]
Why don't we just add @rebornix 's keybindings by default and close this issue?

**Comment by Chillee** [comment]
On master, we have added the following keybindings when you're inside the explorer list
`G`: go to the bottom of the list
`gg`: go to the top of the list
`o`: Opens and closes folders
`<enter>`: opens the current file in a new tab
`<c-d>`: Go down half a page
`<c-u>`: Go up half a page
`j`: Move down
`k`: Move up

**Comment by xconverge** [comment]
enter for me just gives me the chance to rename it, it does not open it, everything else works correctly

**Comment by xconverge** [comment]
Ok just note on macOS, it is Cmd+enter to open file, not just enter.

Due to this line (presumably to match default finder behavior where enter just renames..): https://github.com/Microsoft/vscode/blob/09473dd87f20971a58ad43a6e5dc7ed6c1e32dc1/src/vs/workbench/parts/files/browser/fileActions.contribution.ts#L240

**Comment by alexbyk** [comment]
The solution provided by @rebornix  works except it's impossible to rename files in explorer with "j,k" characters. Any idea how to fix this?

**Comment by dsifford** [comment]
@alexbyk make sure your `when` clause matches this....

```
"when": "explorerViewletVisible && filesExplorerFocus && !inputFocus"
```

That said, `j` and `k` are preset by VSCodeVim so you shouldn't even have to map those.

**Comment by alexbyk** [comment]
@dsifford thanks. Looks like I missed an update on this

**Comment by MattGoldwater** [comment]
@xconverge cmd + enter doesn't work for opening a file on my Mac. Is anyone else having the same problem?

**Comment by dopeboy** [comment]
This stumped me for a bit. In order to get this working, @rebornix's suggestion, I needed to add this to my settings.json

```
"workbench.list.automaticKeyboardNavigation": false,
```

**Comment by nickpap35gr** [comment]
> 

I know this issue is old but would you mind telling me where I could find or add these settings? I would like to swap `j` with `k` as I have done with normal mode while using vim.

**Comment by f412h4d** [comment]
> This stumped me for a bit. In order to get this working, in addition to @rebornix's suggestion, I needed to add this to my settings.json
> 
> ```
> "workbench.list.automaticKeyboardNavigation": false,
> ```

this option is obsolete

is using this ok?
```json
  "workbench.list.typeNavigationMode": "trigger",
```

**Comment by RmZeta2718** [comment]
> @xconverge Aha! Thanks for that 😄
> 
> If anybody else out there is interested in the ctrl+j and ctrl+k to move up/down in the workbench and autocomplete suggestion list (and have `vim.useCtrlKeys` disabled), here's the keymaps for that...
> 
> ```json
> {
>     "key": "ctrl+j",
>     "command": "selectNextSuggestion",
>     "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
> },
> {
>     "key": "ctrl+k",
>     "command": "selectPrevSuggestion",
>     "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible"
> },
> {
>     "key": "ctrl+j",
>     "command": "workbench.action.quickOpenNavigateNext",
>     "when": "inQuickOpen"
> },
> {
>     "key": "ctrl+k",
>     "command": "workbench.action.quickOpenNavigatePrevious",
>     "when": "inQuickOpen"
> }
> ```
> 
> @bpasero Not sure if this has been suggested yet or not, but tracking down these commands made me realize how much I took for granted Atom's keybinding resolver mode. Adding something similar to vscode would be amazing. 🙏

If anybody is interested in similar keymaps for Quick Fix, here is:
``` json
{
    "key": "ctrl+j",
    "command": "selectNextCodeAction",
    "when": "codeActionMenuVisible"
},
{
    "key": "ctrl+k",
    "command": "selectPrevCodeAction",
    "when": "codeActionMenuVisible"
}
```
