### ISSUE TITLE
How do I disable the Quickpick command line popup window when using a plugin?

### ISSUE THREAD

**Issue by kohane27** [VSCodeVim/Vim#7543]
Greetings. Hope you're doing well. Thank you for checking in this issue. I appreciate any help.

**Describe the bug**

I'm using this plugin called [metaGo](https://github.com/metaseed/metaGo) and have the following setting:

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "s"
            ],
            "commands": [
                "metaGo.gotoBefore"
            ]
        }
    ]
```

However, when I press `s`, the Quickpick command line popup window shows up (screenshot below), which is not what I want. I tried disabling vscodevim and the plugin behaves as expected (no popup window).

**To Reproduce**

1. Remap as above
2. Press `s`
3. The Quickpick command line popup window shows up

**Expected behavior**
I want to disable the Quickpick command line popup window, so I figured this is an issue or setting with vscodevim. 

Disabling vscodevim altogether successfully disable this quickpick command line popup.

I've tried adding `"vim.showQuickpickCmdLine": false` but it's not a real config setting.

I'm aware of the issue [#1556](https://github.com/VSCodeVim/Vim/issues/1556) and is this solvable yet?

I tried the circumvent this issue with the following remap:

```
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "s"
            ],
            "after": [
                ":metaGo.gotoBefore"
            ]
        }
    ]
```

This forces vscodevim to use the command line mode in the statusbar, but it shows `E492: Not an editor command: metaGo.gotoBefore`. What's worth mentioning is that, before this error, the command runs successfully for a split second, i.e., I can see the editor area dimmed and tags activated.

**Screenshots**
![screenshot-2022-03-07-08-51-49](https://user-images.githubusercontent.com/57322459/156950569-021da829-3467-4bbe-9783-aa08eb018b8a.png)

**Environment:**

- Extension (VsCodeVim) version: v1.22.2
- VSCode version: 1.65.0
- OS: Linux x64 5.15.25-1-MANJARO snap

Thank you again!

**Comment by waynewaynetsai** [comment]
I have no problem with `metaGo.gotoBefore` command at MacOS. Maybe it's a linux specific problem.

```
"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "s"
            ],
            "commands": [
                "metaGo.gotoBefore"
            ]
        }
    ]
```

Environment:

Extension (VsCodeVim) version: v1.22.2
VSCode version: 1.65.0
OS: MacOS Monterey v12.2

**Comment by kohane27** [comment]
@waynewaynetsai 
> I have no problem with `metaGo.gotoBefore` command at MacOS environment. Maybe it's a linux specific problem.

Thanks for looking into this issue. I appreciate it!

Could you clarify what you mean by "no problem with `metaGo.gotoBefore` command"? Do you mean that you don't see the Quickpick command line popup window when using `metaGo.gotoBefore`? That is, you only see visual changes in the editor after pressing two keystrokes?

I tried running the same command in Windows' VScode and it has the same issue: `E492: Not an editor command: metaGo.gotoBefore`. Windows' info:

```
Version: 1.65.0 (user setup)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:08.962Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by kohane27** [comment]
If anyone is also having this issue, I've found an alternative solution. I've switched to using [vscode-neovim](https://github.com/vscode-neovim/vscode-neovim) which supports lightspeed.nvim and leap.nvim. They offer similar functions to megaGo. Cheers!
