### ISSUE TITLE
Option to make `Y` behave like `D`/`C`

### ISSUE THREAD

**Issue by verhovsky** [VSCodeVim/Vim#7549]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that `Y` copies the entire current line (including the trailing newline) instead of copying from the cursor position to the end of the line (without the trailing newline), like `D` (delete from cursor to end of line) and `C` (delete from cursor to end of line and enter insert mode). We already have `yy` which does the same thing.

**Describe the solution you'd like**
A boolean config option similar to `changeWordIncludesWhitespace` like

```
"vim.yankFromCursor": true,
```

**Describe alternatives you've considered**
This would probably be achievable with NeoVim integration since this is also a common setting people configure `noremap Y y$`

**Comment by J-Fields** [comment]
> This would probably be achievable with NeoVim integration since this is also a common setting people configure `noremap Y y$`

It's unrelated to neovim integration actually, but yes - you can do this with the remap you mentioned in a `.vimrc` or the equivalent in `vim.normalModeKeyBindingsNonRecursive`.

**Comment by verhovsky** [comment]
```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
          "before": ["Y"],
          "after": ["y", "$"]
        },
    ],
```
