### ISSUE TITLE
Substitution with search result as input gives E476 Invalid Command

### ISSUE THREAD

**Issue by rcywongaa-work** [VSCodeVim/Vim#7560]
**Describe the bug**
After searching (with `*` or `/`), running a substitution on the search result `:s//replacement/g` fails with `E476 Invalid Command` even though the command preview shows the correct substitution

**To Reproduce**

1.  Do a search (e.g. with `*`)
2.  Type in a substitution command `:s//new_word/g`
3.  Observe that the command preview shows the correct substitution
4.  Press Enter
5. Observe the error `E476 Invalid Command` and the substitution did not occur

**Expected behavior**
Substitutions should have occurred as in the preview

- Extension (VsCodeVim) version: v1.22.2
- VSCode version: 
  ```
  1.66.0-insider
  79d9bb8754331225372e892393619d4072474a19
  x64
  ```
- OS: Ubuntu 20.04.3

**Comment by J-Fields** [comment]
Seems to work for me. Can you please provide relevant settings?

**Comment by rcywongaa-work** [comment]
OK, I realized it only happens with `"vim.enableNeovim": true` and when I attached vscode to a container that doesn't have neovim

**Comment by kimdwkimdw** [comment]
"vim.enableNeovim": true

@J-Fields I'm getting same error.

I'm using remote session with vscode, neovim is installed in remote machine
