### ISSUE TITLE
Can't remap certain ctrl+<key>

### ISSUE THREAD

**Issue by gen0083** [VSCodeVim/Vim#757]
I want to set ctrl+] to escape.
But this is not work.

```
    "vim.insertModeKeyBindings": [
        {
        "before":["ctrl+]"],
        "after":["<Esc>"]
        }
    ]
```

**Comment by jpoon** [comment]
Remapping aside, I can't get `ctrl+[` to register in the extension.

We registered the keys in `package.json`:
```
      {
        "key": "ctrl+[",
        "command": "extension.vim_ctrl+[",
        "when": "editorTextFocus && vim.useCtrlKeys"
      },
```
and with `vim.useCtrlKeys: true`, the `<C-[>` never shows up in our extension. I'm suspecting that this issue might lie in VSCode.

**Comment by gen0083** [comment]
I use a JIS-Keyboard.
In JIS-keyboards key "[" is "]".
So I want to reassign it in vscode-vim.

I added this in keybinding.json then it works.

```
{
    "key": "ctrl+]",
    "command": "extension.vim_ctrl+[",
    "when": "editorTextFocus && vim.useCtrlKeys"
}
```

**Comment by jpoon** [comment]
As per https://github.com/Microsoft/vscode/issues/5280, the keybinding dispatching ignores modifier keys. If we want to be able to remap them, we would need to include all variants of them in the package.json.

**Comment by rebornix** [comment]
I answered in our slack channel multiple times that the reason that we can't do this is because if we steal ctrl+key from Code, we can never delegate it back to Code, so it's not a good idea to put every ctrl+key to the contribution list if we just want to allow users to do the remapping.

I'll say it's an enhancement or feature request instead of a bug. It's limited to VS Code.

**Comment by yqrashawn** [comment]
@rebornix But we can still map ctrl+key back to code functions do we? Or keys like Command+Control+K will be still as well?

**Comment by jpoon** [comment]
Renaming this issue to be a bit more generic. 

Our extension doesn't currently bind to those keys (https://github.com/VSCodeVim/Vim/blob/master/package.json#L140), hence they go straight to vscode bypassing vscodevim (ie. we have no knowledge of a `ctrl+n` key).

**Comment by jpoon** [comment]
To keep the issue list to a sane number, closing this as we haven't seen a lot of traction. For requests to re-bind to certain `ctrl` keys, please file an individual request and we'll handle it on a case-by-case basis as we don't want to bind to every single key combination imaginable.
