### ISSUE TITLE
In a `:s[ubstitute]` replace string, `&` (not `\&`), should reference the whole matched pattern

### ISSUE THREAD

**Issue by ldorigo** [VSCodeVim/Vim#7571]
**Describe the bug**
In vim, doing `:%s//foo&/g` prepends `foo` to all occurrences of the previously searched string. In vscode vim, it just replaces the string by `foo&`. 

**To Reproduce**

test.txt:
```
test
test
test
test
```

go on first line, press *. then enter `:%s//foo&/g`. The result is `foo&` on all lines rather than `footest`.

**Expected behavior**

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.22.2`
- OS Version: `Linux x64 5.16.15-zen1-1-zen`
- VS Code version: `1.65.2`

**Additional context**

**Comment by J-Fields** [comment]
This actually works with `\&`, but you're right that with default `'magic'` (which we don't yet support) that's incorrect behavior
