### ISSUE TITLE
How do I remove `:set relativenumber` after uninstalling the extension?

### ISSUE THREAD

**Issue by Raj2032** [VSCodeVim/Vim#7603]
Hey guys I uninstalled the extension (if you are interested to knowing my reason please see [this post](https://github.com/VSCodeVim/Vim/issues/7602#issue-1191995411) ) the `:set relativenumber` is still operating. I am not too sure what I have to do to change it back to normal numbering system. Any ideas?

**Comment by J-Fields** [comment]
Check `settings.json`, `"editor.lineNumbers": "relative"` is probably set
