### ISSUE TITLE
Add "extensions.experimental.affinity" to doc

### ISSUE THREAD

**Issue by haoadoreorange** [VSCodeVim/Vim#7606]
In latest [Insiders Build](https://code.visualstudio.com/insiders/) it's possible to run vim extension in dedicated host process, which is supposed to fix some problems where vim is stall due to other running extensions. Maybe we should add this to the doc ?

See the [announcement](https://github.com/microsoft/vscode/issues/65876#issuecomment-1078827200).

**Comment by lawrence-laz** [comment]
This improved responsiveness by a lot on my machine.

**Comment by mezdelex** [comment]
It was night and day for me, definitely a must have in your settings.json if you're using VSCodeVim

**Comment by joeytwiddle** [comment]
May 2023, this feature is stable for me too. I also recommend adding it to the docs.

It could be hugely beneficial for users (especially those with slower machines).
