### ISSUE TITLE
Search highlight is turned on during command mode

### ISSUE THREAD

**Issue by Ultramann** [VSCodeVim/Vim#7608]
**Describe the bug**
Search highlight is turned on during command mode.

**To Reproduce**
1. Search with `/`.
2. Finish with `enter`.
3. Turn off search with `:nohl`.
4. Start command mode with `:`.

**Expected behavior**
Command mode should not turn on highlighting.

**Screenshots**
While searching

<img width="328" alt="image" src="https://user-images.githubusercontent.com/9347171/162100857-eb04eb3a-df8d-4882-a9be-3e67ff6195a9.png">

Search turned off

<img width="301" alt="image" src="https://user-images.githubusercontent.com/9347171/162100905-109da666-511a-4134-a0b3-fb93eb23863d.png">

Starting command mode

<img width="318" alt="image" src="https://user-images.githubusercontent.com/9347171/162100973-6454f4f4-fdce-4011-8cfa-e4e85b51e369.png">

- Extension (VsCodeVim) version: 1.22.2
- VSCode version: 1.66.0
- OS: macOS BigSur 11.6.4

**Comment by philFernandez** [comment]
I'm also experiencing this. I posted a bug report yesterday at #7666 before noticing this bug was already posted. I'll close the bug I opened and keep my findings here with this previously reported dup.

**Comment by J-Fields** [comment]
This was fixed on `master` by 712674b7e08ef56ddad73b4a5b6a6d64dee6a02d, so it'll be in the next release (sometime this week, I think)

**Comment by Ultramann** [comment]
@J-Fields thanks! Looking forward to it!
