### ISSUE TITLE
Inserting multiple spaces also inserts a period after the first space

### ISSUE THREAD

**Issue by realh** [VSCodeVim/Vim#7610]
Issue Type: <b>Bug</b>

1. From normal mode enter insert mode by pressing i, I, a or A etc
2. Press space two or more times

Instead of inserting "  " (two spaces) I usually get " . " (space period space). Subsequent spaces get inserted correctly.

This isn't consitent though. Sometimes I get two spaces as wanted, sometimes I only get one space. This appears to depend on the code context. For example, when editing settings.json, when I append to a line ending in one of "{}[] it adds the period, but after a comma or colon I get the correct number of spaces only.

Extension version: 1.22.2
VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 8ba83b4d-279f-4f3b-9aa3-3d93e2cffe94|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by J-Fields** [comment]
Have you done the setup described [here](https://github.com/VSCodeVim/Vim#mac)?

**Comment by realh** [comment]
I don't think I had, but I've done it now and it hasn't fixed the problem.

BTW, if I tap space twice I get the period, but holding space down for auto-repeat behaves normally. FWIW here are my settings.

[settings.json.txt](https://github.com/VSCodeVim/Vim/files/8458893/settings.json.txt)

**Comment by J-Fields** [comment]
Ah, here it is: https://github.com/VSCodeVim/Vim/issues/2108#issuecomment-347977957

**Comment by realh** [comment]
Thanks. WTF were Apple thinking? Strange it didn't do it with the vim plugin disabled.

**Comment by lwerdna** [comment]
@realh Thank for posting this question!
@J-Fields Thanks for tracking this down!

I'm glad this turned up in search results, I was mystified!

**Comment by drvnprgrmr** [comment]
@lwerdna same here
