### ISSUE TITLE
s/a/b/g does not work in visual block mode

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#762]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Enter visual block and select a section
Cant even enter :

I made the change to allow : when in visual block and then tried to replace a term globally for selection: :s/a/b/g and it did not work

### What did you expect to happen?

Substitute matching selection within block

### What happened instead?

Only substituted on first line once I made the change to even allow : while in visualBlock

**Comment by nati** [comment]
even "i" command won't work for me..

**Comment by xconverge** [comment]
What do you mean "i" command. For visual block it is "I" or "A" not "i" and "a"

**Comment by nati** [comment]
Thanks.. "I" works fine

**Comment by rebornix** [comment]
@xconverge sorry for revisiting this issue so late. I just tried Vim again and `:s/a/b/g` will only work in the first line in whatever mode. If you want to work the visually selected lines, you should keep `:'<,'>s` as prefix. The catch is `'<,'>` are selected when you run `:` so you might override it.

**Comment by xconverge** [comment]
I thought I tried that, I will try again..

**Comment by xconverge** [comment]
@rebornix did you try visual block mode? ":" is not even handled in visual block mode in the extension so I can't even get to the point where it would give the <,> prefix...

**Comment by rebornix** [comment]
@xconverge we didn't add visualblock mode to `:` command's supporting list. Now I added it, give it a try :)

**Comment by xconverge** [comment]
Did you try it? I couldn't get it to work even after I made the change you made

**Comment by rebornix** [comment]
I pushed two commits to fix this issue and the following one is
https://github.com/VSCodeVim/Vim/commit/e670d2988bece590f80754bc27ea9fe7980b798a
.
Not sure if you applied both of them.

Sean Kelly <notifications@github.com>于2016年9月20日周二 下午4:18写道：

**Comment by xconverge** [comment]
Ah perfect! Sorry I only saw the one that referenced this ticket, nice!
