### ISSUE TITLE
Shift+backspace in search mode (i.e. after pressing slash) deletes from file instead of search cursor.

### ISSUE THREAD

**Issue by boweiliu** [VSCodeVim/Vim#763]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In a non-empty file, press slash then some keys (a,b,c) then shift-backspace.

### What did you expect to happen?

Slash-search bar shows `/ab` and file is unchanged.

### What happened instead?

Slash-search bar shows `/abc` and the character in the file under the cursor is deleted.

### Technical details:

* VSCode Version: 1.5.0 insiders
* VsCodeVim Version: 0.1.10
* OS: OSX

**Comment by johnfn** [comment]
Duplicate of #528
