### ISSUE TITLE
Remapped escape not working

### ISSUE THREAD

**Issue by nicolasdumitru** [VSCodeVim/Vim#7638]
I remapped my Caps Lock key to act as an escape key using Xmodmap on linux. It works global, in vim, neovim and all other apps. It even works in vscode, just not for exiting insert and visual mode and entering normal mode. As for how to reproduce this behavior, simply remap the Escape functionality on a linux system ( I am using Fedora 35 ) with Xmodmap, remove the Caps Lock functionality from the Caps Lock key and edit some code. Try exiting insert mode with the newly remapped key and default vscode vim extension settings

**Comment by aftix** [comment]
I also have this problem.

**Comment by kubil6y** [comment]
try setting keyboard: dispatch to keyCode

**Comment by aftix** [comment]
This fixed it.
