### ISSUE TITLE
Delete selection via `x` was not stored in numbered register

### ISSUE THREAD

**Issue by jackblackevo** [VSCodeVim/Vim#7676]
**Describe the bug**
In Vim, when you delete selected text via <kbd>x</kbd>, it update the `"1` register. In VSCodeVim, the deleted text was stored in `""` register, but not in `"1` register or other numbered registers.

**To Reproduce**

1.  Select multiple line in Visual Mode
2.  Press <kbd>x</kbd> to delete selection
3.  Type `:reg` to check registers
4.  The deleted text by <kbd>x</kbd> was not stored in numbered registers

**Expected behavior**
The `"1` numbered register keep the deleted text by <kbd>x</kbd>

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.22.2
- VSCode version: 1.66.2
- OS: Linux x64 5.10.16.3-microsoft-standard-WSL2 (Windows 11 Pro 21H2 build 22000.652)

**Comment by Mr-peipei** [comment]
I will try this issue
