### ISSUE TITLE
Latest versions not working, v.1.16.0 last working version

### ISSUE THREAD

**Issue by axiezai** [VSCodeVim/Vim#7694]
**Describe the bug**
The emulator simply does not work in VSCode. I decided to roll back in versions and test each one, v1.16.0 and prior versions work, but updating to any thing after v1.16.0 does not work.

**Expected behavior**
The emulator should work.

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

The extension does not show up under "Developers: Show Running Extensions"

- Extension (VsCodeVim) version:
Any versions after v.1.16.0

- VSCode version:
```
Version: 1.67.1 (Universal)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:16.526Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0
```

- OS: MacOS Monterey

I'm assuming there's a little VSCode setting that I'm missing? Not sure where to look, would love a direction to start investigating. Thanks!

**Comment by northernocean** [comment]
Many times in a case like this there is interference from another extension. I would try un-installing other extensions and then adding things back one by one and see if you can get any different results.

**Comment by northernocean** [comment]
That was my only idea. I have not seen such a case before where VSCodeVim just doesn't work. I don't have a newer Mac to test on though.

**Comment by wangduanduan** [comment]
v1.22.2 is not work on my macbook,  v1.16.0 work

**Comment by wangduanduan** [comment]
so i remove all vscodevim seting in vscode settings.json, and reinstall vscodevim plugin, and the v1.22.2 work as Expected!!

so i think maybe some bad config in settings.json, you should remove them all.

**Comment by axiezai** [comment]
> so i remove all vscodevim seting in vscode settings.json, and reinstall vscodevim plugin, and the v1.22.2 work as Expected!!
> 
> so i think maybe some bad config in settings.json, you should remove them all.

Hi @wangduanduan, thanks for the tip, it seems like I had a line for `VisualModeKeyBindings` for vim in my `settings.json` and removing it worked, had this setting in my VSCode the entire time with previous versions, not sure what caused the conflict. 

Closing.

**Comment by northernocean** [comment]
Hi @axiezai out of interest do you recall what the line was that you removed?

**Comment by axiezai** [comment]
I don't remember exactly what the setting was set to... in my `settings.json`, I still have `vim.vimrc.enable: true` and `vim.vimrc.path: "$HOME/.vimrc". What I removed had something to do with `VisualModeKeyBindings`, and that's the only setting line I removed. 

Sorry don't remember exactly the line...
