### ISSUE TITLE
using `|` as a delimiter in substitute command returns "trailing character" error.

### ISSUE THREAD

**Issue by azinsharaf** [VSCodeVim/Vim#7699]
**Describe the bug**
using `|` as a delimiter in substitute command returns "trailing character" error.

**To Reproduce**

1.  Select multiline in Visual mode.
2.  type `:'<,'>find|replace|`
3. returns: Trailing characters error
5.  typing  `:'<,'>find/replace/` works fine.

**Expected behavior**
I expect that any delimiter like` | `should work.

- Extension (VsCodeVim) version: `1.22.2`
- VSCode version: `1.67.1`
- OS: `Win 10`

**Comment by J-Fields** [comment]
From https://vimhelp.org/change.txt.html#pattern-delimiter

> You can use most characters, but not an alphanumeric character, '\', '"' or '|'.
