### ISSUE TITLE
Don't Handle Arrow Keys!

### ISSUE THREAD

**Issue by RyannDaGreat** [VSCodeVim/Vim#7702]
**Is your feature request related to a problem? Please describe.**
Normally in VSCode when you reach the end of a line and press the right arrow key, it will wrap to the next line. I realize that in Vim, this is not the case. However, as this is not vim (it's VSCode) I often expect to go to the next line when pressing the right arrow key, and it doesn't happen when this plugin is enabled. Personally I would prefer to have default functionality for everything until I go into Normal mode (or some other mode besides Insert mode).

**Describe the solution you'd like**
Because this is VSCode, and not literally vim, there should be an option to not handle arrow keys the vim way when in insert mode. HJKL should be enough for most vim users - and arrow keys should be allowed to be ignored by this extension (letting them have default VSCode functionality).

**Describe alternatives you've considered**

I've tried adding this to settings.json:
```   
"vim.handleKeys":{
        "right":false,
        "left":false,
    },
```

However, this doesn't fix the problem. 

**Additional context**
(No additional context needed)

**Comment by J-Fields** [comment]
> I've tried adding this to settings.json:

Using `<Right>` and `<Left>` will probably do what you want, but also mess up those keys in the Vim command line, so I wouldn't recommend it.

Instead, look into the ['whichwrap'](https://vimhelp.org/options.txt.html#%27whichwrap%27) option, which should work.

**Comment by RyannDaGreat** [comment]
@J-Fields 
Hi, thank you for responding!
I already use whichwrap in my .vimrc, but how do I use it in VSCodeVim?

**Comment by RyannDaGreat** [comment]
@J-Fields 
I tried adding 
```    "vim.whichwrap":"b,s,<Right>,<Left>",```
But it didn't do anything...am I doing it right?

**Comment by J-Fields** [comment]
Use `<,>` (or `<,>,[,]`; see the link I posted above) instead of `<Left>,<Right>`

**Comment by andrestoga** [comment]
And which ones for `up` and `down`?
