### ISSUE TITLE
Failed to select in normal mode

### ISSUE THREAD

**Issue by haunt98** [VSCodeVim/Vim#7704]
**Describe the bug**
Failed to select in normal mode when select line from bottom to top, top to bottom line works fine.

**To Reproduce**

1. In normal mode
2. Select bottom line (for example line 100)
3. Press shift then select top line (for example line 90)

**Expected behavior**
Select line from bottom to top should work exactly like top to bottom lines.

**Screenshots**

https://user-images.githubusercontent.com/5424272/168649985-ba9f387b-86d7-41c9-9393-7a6388edb27f.mov

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: [v1.22.2](https://github.com/vscodevim/vim/tree/v1.22.2)
- VSCode version: 1.67.1
- OS: macOS
- Use neovim: v0.7.0

```txt
  "vim.enableNeovim": true,
  "vim.neovimUseConfigFile": true,
```

**Comment by nghiant3223** [comment]
I'm facing the same issue!

**Comment by wishuhere** [comment]
please fix it. That's annoying
