### ISSUE TITLE
bracketedKey breaks `<character>` checking

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#771]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Now we are sending `bracketKey` to commands while in `compareKeypressSequence` we are still checking `controlKeys`, which is not wrapped by brackets:

```
const controlKeys: string[] = [
  "ctrl",
  "alt",
  "shift",
  "esc",
  "delete",
  "left",
  "right",
  "up",
  "down"
];
```

In this case, any command using `<character>` as keys will take things like `<Del>`, `<BS>`, etc.

cc @jpoon

**Comment by johnfn** [comment]
Very nice find.

**Comment by jpoon** [comment]
@rebornix Thanks.

**Comment by rebornix** [comment]
@jpoon I'm sorry I have to revert it back for now as this issue is bigger than what I thought.

We are seeing below keys as contrlKeys

```
const controlKeys: string[] = [
  "ctrl",
  "alt",
  "shift",
  "esc",
  "delete",
  "left",
  "right",
  "up",
  "down"
];
```

While in commands for handlers

```
@RegisterAction
class CommandInsertInInsertMode extends BaseCommand {
  modes = [ModeName.Insert];
  keys = ["<character>"];

  // TODO - I am sure this can be improved.
  // The hard case is . where we have to track cursor pos since we don't
  // update the view
  public async exec(position: Position, vimState: VimState): Promise<VimState> {
    const char = this.keysPressed[this.keysPressed.length - 1];

    if (char === "<BS>") {
      const newPosition = await TextEditor.backspace(position);

```

Our code is not saying so. It seems we treat `<BS>`, aka Backspace as a character. I'll figure out a better way to handle this and send a pr for you and @johnfn to review before getting it merged.

**Comment by rebornix** [comment]
It's already fixed.
