### ISSUE TITLE
Unable to map ";" in normal mode

### ISSUE THREAD

**Issue by ademuri** [VSCodeVim/Vim#7714]
**Describe the bug**
I am unable to remap the ";" key in normal mode.l

**To Reproduce**

Add the following to the settings.json:

```json
  "vim.insertModeKeyBindingsNonRecursive": [
        {
            "before": [";"],
            "after": [":"]
        }
    ],
```

**Expected behavior**
Pressing ';' should trigger command mode. Instead, it gives the normal behavior of semicolon, repeating the last 'f' or 't'. Similar behavior for mapping from ';' to e.g. 'cw'.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.18.9
- VSCode version:
- OS:

**Additional context**
I tried the debugging steps. I don't see anything obvious:

```
Configuration: 0 errors found with vim configuration Dismiss Suppress Errors
...
ModeHandler: handling key=;. Dismiss Suppress Errors
Remapper: trying to find matching remap. keys=;. mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
ModeHandler: handleKeyEvent(';') took 20ms Dismiss Suppress Errors
```

If you have an idea of where to look, I'm happy to take a crack at fixing this.

**Comment by northernocean** [comment]
mapping  a semi-colon to a colon in insert mode would not put you in command mode. It would simply write a colon instead of a semi-colon. I don't see any reason it would repeat f's or t's. Perhaps your settings.json is not configured correctly.

**Comment by J-Fields** [comment]
@northernocean is correct; your config is equivalent to `inoremap ; :`. I think you want the equivalent of `nnoremap`, for which you should use `vim.normalModeKeyBindingsNonRecursive`.
