### ISSUE TITLE
The :h command replace the current page

### ISSUE THREAD

**Issue by hiuxia** [VSCodeVim/Vim#7718]
**Describe the bug**
When use the :h command, I lose all my saved markdown file which is replaced by the vim help doc!
**To Reproduce**
I use the markdown all in one plugin to write md files, and when I use the :h g command, the file is replaced by the help doc.

**Expected behavior**
At least let me able to quit the doc safely!

**Screenshots**
![image](https://user-images.githubusercontent.com/98009342/169653072-2eb5d86f-e5bb-4c14-8d6d-9d6b3f1a8df8.png)

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/98009342/169653115-92b06641-5e63-4fd2-be8a-394871e5e548.png)
![image](https://user-images.githubusercontent.com/98009342/169653124-1dd81a35-35a5-4379-89ea-3d6f5b5ea54d.png)

**os** : macos.

**Comment by northernocean** [comment]
Hi, can't you undo the changes after this happens?

**Comment by hiuxia** [comment]
It seems I was too surprised to test this at this moment? Sorry, but may be you'd better ban the :h command. But except this, this is an awesome plugin!
