### ISSUE TITLE
<number>G hangs vim plugin if file is not long enough

### ISSUE THREAD

**Issue by boweiliu** [VSCodeVim/Vim#772]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Open a blank file, press 99G. Then try to do something like iBlahBlahBlah

### What did you expect to happen?
It inserts BlahBlahBlah

### What happened instead?
It doesn't change modes or respond to <Esc> or most other keypresses.
### Technical details:

* VSCode Version: 1.5.0 iNsider
* VsCodeVim Version:  1.10
* OS: OSX 10.10.5

**Comment by rebornix** [comment]
@boweiliu thanks for the bug report, you can see this get fixed with our next release!
