### ISSUE TITLE
`gv` after `vap` results in the wrong selection

### ISSUE THREAD

**Issue by windin7cc** [VSCodeVim/Vim#7723]
### When I select a praragraph using keys: `vap`

![20220525_132906](https://user-images.githubusercontent.com/19501269/170187308-7fcede8b-b666-4708-a9e5-01ed53615f5f.png)
In Vim the cursor will stop at first char of the next blank line, but in VS Code Vim it jump to the next ine.

### When I re-select the region using: `gv`

![20220525_132924](https://user-images.githubusercontent.com/19501269/170187310-0d1caea4-dada-453e-88f4-ad3a1d4521fa.png)
The next next line's first char was selected.

Then I try to enter visual mode by press v on the blank line, my cursor jump to the next line automatically when entered visual mode, but it's shape is like in a insert mode. 
I'm not sure if this is a VS Code config error or VS Code Vim's default behavior.

- Extension (VsCodeVim) version: v1.22.2
- VSCode version: 1.67.2
- OS: Win10

**Comment by Jinxishihenian** [comment]
I have a similar problem, in attempt mode, when I select an entire line with $, the cursor wraps.

**Comment by J-Fields** [comment]
@windin7cc

>  When I select a praragraph using keys: `vap`
In Vim the cursor will stop at first char of the next blank line, but in VS Code Vim it jump to the next ine.

This is just a visual difference between Vim and VSCode. In both, the selection covers the newline but no characters in the next line.

The behavior difference is actually that Vim goes into VisualLine mode while VSCodeVim remains in Visual mode - this is a known (to me, anyway) bug.

> When I re-select the region using: `gv`
The next next line's first char was selected.

This *is* a bug, and not one I was aware of.

**Comment by J-Fields** [comment]
@Jinxishihenian

>I have a similar problem, in attempt mode, when I select an entire line with $, the cursor wraps.

This is the visual difference I mentioned above. Compare the behavior of `v$d` between Vim and VSCodeVim.

**Comment by windin7cc** [comment]
> @windin7cc
> 
> > When I select a praragraph using keys: `vap`
> > In Vim the cursor will stop at first char of the next blank line, but in VS Code Vim it jump to the next ine.
> 
> This is just a visual difference between Vim and VSCode. In both, the selection covers the newline but no characters in the next line.
> 
> The behavior difference is actually that Vim goes into VisualLine mode while VSCodeVim remains in Visual mode - this is a known (to me, anyway) bug.

Thanks for replying! : )

I noticed that `vap` will stop at the next line, probably the cursor is just stopped at the line's beginning void place.

> 
> > When I re-select the region using: `gv`
> > The next next line's first char was selected.
> 
> This _is_ a bug, and not one I was aware of.

Expecting to be fixed.
