### ISSUE TITLE
When type Chinese character, the editor appear blinking

### ISSUE THREAD

**Issue by yifan0414** [VSCodeVim/Vim#7724]
**Describe the bug**
When I switch to Chinese input method and start inputing the character, The Chinese character is blinking.
**To Reproduce**
Just enter the insert mode, and switch the input method to Chinese, then type in some words.
**Expected behavior**
the normal visual performance
**Screenshots**
![iShot_2022-05-26_01 07 22](https://user-images.githubusercontent.com/45898625/170321133-fc17adc6-2c7a-478f-bc6b-f784cac75e61.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.22.2
- VSCode version: 1.67.2 (Universal)
- OS: Darwin arm64 21.4.0

**Additional context**
the english input method works normally

**Comment by cyrnicolase** [comment]
up

**Comment by gengdz** [comment]
+1

**Comment by J-Fields** [comment]
Did this break in a recent version, or is this a bug that's existed for a while?

**Comment by VectorLu** [comment]
> Did this break in a recent version, or is this a bug that's existed for a while?

I find that VS code mac(arm) 1.54 can avoid this bug, I use 1.67.2(mac universal) and find this bug too. And on windows, I also occur this bug.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/12776182/171556753-2fbaf8b3-2059-4af0-a383-adf8a0d1a1b7.png">

**Comment by VectorLu** [comment]
> Did this break in a recent version, or is this a bug that's existed for a while?

For mac arm，I test 1.54, 1.66, 1.67, 1.54 can avoid this bug, 1.66&1.67 will occur this bug

**Comment by ReyXiao** [comment]
When it is used on VSCode 1.65 also with this bug.(macOS Big Sur Intel-based)

**Comment by fanlumaster** [comment]
Why this problem haven't been solved yet? So annoying when typing Chinese and Japanese characters😭

**Comment by teal024** [comment]
Any progress?

**Comment by M1ssakira** [comment]
@yifan0414 Is this bug fixed in the current version?

**Comment by yifan0414** [comment]
> @yifan0414 Is this bug fixed in the current version?

Yes

**Comment by ccat3z** [comment]
Still blinking on latest VSCode and VSCodeVim on mac.

Extension (VsCodeVim) version: v1.30.1
VSCode version: 1.100.2
OS: Darwin arm64

https://github.com/user-attachments/assets/bb5a3eb7-fe53-4147-a08b-b6ea7f14389f
