### ISSUE TITLE
[Feature Request] Save new files via :w

### ISSUE THREAD

**Issue by triplepointfive** [VSCodeVim/Vim#773]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Open new file with `⌘N`, then run command `:w filename` .

### What did you expect to happen?

Save opened buffer with the given filename. Or at least open the save dialog for `:w`.

### What happened instead?

Nothing.

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.1.10
* OS: OS X 10.11.6

**Comment by rebornix** [comment]
@triplepointfive As Code doesn't support sending parameters to its `fileSave` command, so with my fix, you are able to use `:w` but not `:w {fileName}`.
