### ISSUE TITLE
Shifting in insert mode

### ISSUE THREAD

**Issue by triplepointfive** [VSCodeVim/Vim#774]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In insert mode pressed Ctrl-T or Ctrl-D.

### What did you expect to happen?

Ctrl-T indents the current line, and Ctrl-D unindents.

### What happened instead?

With `vim.useCtrlKey` enabled Ctrl-D outputs `<C-d>`, with mode disabled moves cursor left.

Ctrl-T outputs literally random stuff.

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.1.10
* OS: OS X 10.11.6

**Comment by rebornix** [comment]
maybe it's related to #771 

cc @jpoon

**Comment by boweiliu** [comment]
I can only repro this bug in read-only files.

**Comment by rebornix** [comment]
This issue no longer exists with current master bits, should be gone with our next release.
