### ISSUE TITLE
the most infuriating part about vim that prevents me from using it

### ISSUE THREAD

**Issue by fislysandi** [VSCodeVim/Vim#7755]
why cant i start editing at the end of the line!?!?!?!?!?! is there any prefrence that fixes this?

https://user-images.githubusercontent.com/45166203/173345323-66d4cbd6-6047-4ad6-bcac-c9c159c64724.mp4

**Comment by J-Fields** [comment]
Indeed. Or `A` to start editing at the end of the line (regardless of where your cursor is).
