### ISSUE TITLE
Visual Block Mode & Multi Cursor Mode should use the same code base

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#776]
I wrote visual block mode by reimplementing a lot of the insertion stuff that I didn't realize VSC already had. I have since took advantage of that in multi-cursor mode.

Honestly, a lot of the visual block mode stuff is redundant with the features that VSC provides; I didn't even realize this. E.g., there's no need for a visual block insert mode, just go straight into normal insertion mode with `multicursor = true`.

There is essentially no reason to do this except for code quality, so it may never happen, but hey. May as well get it down now.

**Comment by Chillee** [comment]
@johnfn Actually I changed my mind. I think I've refactored pretty much everything that can be refactored into multicursors with visual block mode. There might be a couple lingering places, but the bulk of the redundancy (insert mode mostly) has been removed. I think this can be closed.

**Comment by johnfn** [comment]
That's awesome.
