### ISSUE TITLE
cross cursor can't work in vscode-vim 

### ISSUE THREAD

**Issue by wj-Mcat** [VSCodeVim/Vim#7767]
**Describe the bug**
I want to complete the cross (column + line) in vscode vim ,but it doesn't work for me:

**To Reproduce**

* .vimrc configuration

```shell
set nu
filetype on
set magic
syntax enable

set guicursor=n-c-v:ver50-ncvCursor
set guicursor=i:block-iCursor-blinkon0,v:block-vCursor
set cursorline "十字架"
set cursorcolumn "十字架"
```

**Expected behavior**

it works in vim under terminal:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/10242208/174534817-2744a9a6-4449-49fa-851a-2d83fabf5340.png">

I have set the .vimrc path in user setting:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/10242208/174534987-14a132bb-0691-456d-910d-66976b2723ab.png">

I have configured the same configuration in lcoal and remote machine. 

- Extension (VsCodeVim) version: 1.22.2
- VSCode version: 1.63.2
- OS: Mac Big Sur 11.6

**Comment by J-Fields** [comment]
I'm not sure if VS Code supports this - https://github.com/microsoft/vscode/issues/15027 is the best I found with a quick google search, at least

**Comment by wj-Mcat** [comment]
Thanks much for this great search, I think it's a bit hard to achieve this shining cursor setting.  Closed by impossible functionality.
