### ISSUE TITLE
Incorrect pair of brackets highlighted with blockcursor

### ISSUE THREAD

**Issue by FSMaxB** [VSCodeVim/Vim#777]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----
### What did you do?

Writing text with multiple brackets and putting the block cursor on one of them.

```
(((some text inside the parentheses)))
                                     ^
                                     |
                                     Cursor here
```

### What did you expect to happen?

The outermost brackets getting highlighted.

```
(((some text inside the parentheses)))
^                                    ^
|                                    |\
 \                                  /  Cursor here
   --------------------------------
             |
             These two brackets should get highlighted
```

![gvim-correct](https://cloud.githubusercontent.com/assets/4294942/18577638/337dacec-7c15-11e6-927d-f5b376c8ff6a.png)

### What happened instead?

The pair of brackets in front of the cursor got highlighted.

```
(((some text inside the parentheses)))
 ^                                  ^^
 |                                  | \
  \                                /   Cursor here
    ------------------------------
             |
             These two brackets get highlighted
```

![vscode-vim-bug](https://cloud.githubusercontent.com/assets/4294942/18577565/b8b7a1fc-7c14-11e6-9765-71cd3bed4096.png)

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.1.10
* OS: Windows 8.1

**Comment by johnfn** [comment]
This is actually a bug with Visual Studio Code! Uninstall VSCodeVim and turn on block cursor and you'll see the incorrect parenthesis gets highlighted.

**Comment by johnfn** [comment]
Tracking here: https://github.com/Microsoft/vscode/issues/12293
