### ISSUE TITLE
Inccorect behavior when deleting brackets with d%

### ISSUE THREAD

**Issue by FSMaxB** [VSCodeVim/Vim#778]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

```
(((some text inside the parentheses)))
                                     ^
                                     |
                                     Cursor here
```
I  pressed `d%`.

### What did you expect to happen?

Everything getting deleted.

### What happened instead?

```
(
```

I think this is related to #777.

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.1.10
* OS: Windows 8.1

**Comment by johnfn** [comment]
Weirdly it only works in reverse and only when directly doing `d%`, not `vd%`.

This one should be pretty easy to fix. :)

**Comment by FSMaxB** [comment]
The behavior changed in 0.2.0, now the result is:
```
)
```

But it is still not behaving correctly.

**Comment by johnfn** [comment]
Thanks for the report, @FSMaxB. This one should be fixed on master. :)

**Comment by FSMaxB** [comment]
Great, thanks.
