### ISSUE TITLE
can't map `d` to `"_d`

### ISSUE THREAD

**Issue by qanyue** [VSCodeVim/Vim#7780]
**Describe the bug**
can't map d to "_d

**To Reproduce**

1.  Go to 'setting '
2.  add map   d  to   "_d
3.  vscode will pause

**Screenshots**
![image](https://user-images.githubusercontent.com/55617091/176001439-9ecaaf02-83b1-4e6b-82d6-5223b6c7b1e8.png)
**Environment (please complete the following information):**

- Extension (VsCodeVim) version:  latest
- VSCode version:
- OS: windows

**Comment by J-Fields** [comment]
Are you using `vim.normalModeKeyBindings` or `vim.normalModeKeyBindingsNonRecursive`?

**Comment by qanyue** [comment]
> Are you using `vim.normalModeKeyBindings` or `vim.normalModeKeyBindingsNonRecursive`?

My bad, I ignore the Recursive .
