### ISSUE TITLE
1.0.23 <C-o> <C-i> not working

### ISSUE THREAD

**Issue by jgarciaokode** [VSCodeVim/Vim#7793]
Ctrl + i is just not working

Ctrl + o is performing alternate file kind of behavior

**Comment by penglei** [comment]
I have the same problem

**Comment by Connor1996** [comment]
+1

**Comment by adhusson** [comment]
Same here!

**Comment by eastwood** [comment]
Confirmed

**Comment by cuongvuong-phoenix** [comment]
I am also having the same problem! Need to downgrade into `1.22.2` and it works fine.

**Comment by catskul** [comment]
Related:

https://github.com/VSCodeVim/Vim/issues/7822

**Comment by J-Fields** [comment]
This was fixed in 1.23.2
