### ISSUE TITLE
Visual Block Cut bug? (Ctrl-v c)

### ISSUE THREAD

**Issue by sibeov** [VSCodeVim/Vim#7796]
**Describe the bug**
Using visual block and cut and insert (Ctrl-v c) does not work. It snaps to insert on the "last line" (behind the last character) of the visual block selection. Downgraded to VSCodeVim 1.22.2 and that solved the problem.

**To Reproduce**
1. Ctrl-v
2. (cover area / block of code)
3. c

**Expected behavior**
All words are cut and insert is initiated in a multi-cursor fashion.

**Screenshots**
Will append screenshots later..

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.23.0
- VSCode version: 1.68.1
- OS: Windows 10
- VSpaceCode 0.10.9

**Additional context**
Downgraded to 1.22.2 and that solved the problem. Using VSCodeVim in conjunction with VSpaceCode.

**Comment by J-Fields** [comment]
Fixed in 1.23.1, which is in the release pipeline.
