### ISSUE TITLE
Add "+ register for accessing the clipboard

### ISSUE THREAD

**Issue by bdchauvette** [VSCodeVim/Vim#780]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Select text, e.g. using `V`
2. `"+y`

### What did you expect to happen?

The selected text to be copied to the system clipboard (see Vim documentaiton for [`quoteplus`](http://vimdoc.sourceforge.net/htmldoc/gui_x11.html#quoteplus))

### What happened instead?

Nothing 😞 

### Technical details:

* VSCode Version:  **1.5.2**
* VsCodeVim Version: **0.1.10**
* OS: **Windows 10**

-----

Vim has two clipboard registers, `"+` and `"*`. VsCodeVim currently only supports `"*`.

I think on most platforms, the registers point to the same clipboard text, but they behave differently on Linux: `"+` access the X selection `CLIPBOARD` (used for e.g. ctrl+c/x/v), while `"*` access the X selection `PRIMARY` (used by middle-clicking).

I'm used to using the `"+` register to access the clipboard, , so it would be great if VsCodeVim could add support for it 😅 

I don't think it's really worth it (or even possible?) to emulate the semantics of the different registers, but it would be nice to have basic support for accessing the clipboard from both `"+` and `"*`.

**Comment by bdchauvette** [comment]
If you think it's worth implementing, I can take a stab at fixing this.

Seems like it should only require a few changes (lines [51][], [68][], and [97][] in `register/register.ts`) from

[51]: https://github.com/VSCodeVim/Vim/blob/99a7c434246047ac7f91aabe99804925b7af5a3c/src/register/register.ts#L51
[68]: https://github.com/VSCodeVim/Vim/blob/99a7c434246047ac7f91aabe99804925b7af5a3c/src/register/register.ts#L68
[97]: https://github.com/VSCodeVim/Vim/blob/99a7c434246047ac7f91aabe99804925b7af5a3c/src/register/register.ts#L97

```js
if (register === '*') {
```

to something like

```js
if (register === '*' || register === '+') {
```

Alternatively, it could be done with a regex like:

```js
const isClipboardRegister = /\+|\*/;


if (isClipboardRegister.test(register)) {
```

I'm not familiar with the VsCodeVim codebase at all, so I'm not sure which style would be preferable, or if I'm overlooking something else that would need to be changed (aside from adding a unit test, of course!)

**Comment by jpoon** [comment]
Neat, I've never used the `+` register. From http://vim.wikia.com/wiki/Accessing_the_system_clipboard: 

> Under Windows, the * and + registers are equivalent. For X11 systems, though, they differ. For X11 systems, * is the selection, and + is the cut buffer (like clipboard).

@bdchauvette feel free to make the change to have `*` and `+` as system clipboards. You might need to change it [here](https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L372) too. I like the array-based definition.

**Comment by jpoon** [comment]
@bdchauvette named registers is also a highly requested feature if you want to try to take that on: https://github.com/VSCodeVim/Vim/issues/500

**Comment by bdchauvette** [comment]
@jpoon Great, thanks for the feedback!

I'll look into the numbered registers when I have some free time. I'll have to play around with them in Vim first, though, because I've never actually used them before 😅
