### ISSUE TITLE
empty line after 'ddp'

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#781]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

text as blow:

```
BBBBB
AAAAA
CCCCC
```

`ddp` at the first line

### What did you expect to happen?

result text to be:

```
AAAAA
BBBBB
CCCCC
```

### What happened instead?

result text is:

```
AAAAA
BBBBB

CCCCC
```

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.1.10
* OS: Windows 10 Professional

**Comment by jpoon** [comment]
Hey @localvar, this should be fixed in `master` and therefore in the next release.

https://github.com/VSCodeVim/Vim/issues/781
