### ISSUE TITLE
`dgg` and `dG` delete linewise instead of from cursor position

### ISSUE THREAD

**Issue by calebmeyer** [VSCodeVim/Vim#7818]
**Describe the bug**
Deleting to the top or bottom of the buffer deletes the current line as well as all the previous/next

**To Reproduce**

1.  Create a new buffer with
```
abc def
ghi jkl mno
pqr stu vwx
```
2. Position your cursor on `k`
3. `dgg`

**Expected behavior**
The buffer now contains
```
l mno
pqr stu vwx
```

**Actual behavior**
The buffer now contains
```
pqr stu vwx
```

**Screenshots**
<img width="171" alt="image" src="https://user-images.githubusercontent.com/3342777/177414305-6cd5d6fd-b8c7-4ae2-891b-82f042ef1247.png">
<img width="177" alt="image" src="https://user-images.githubusercontent.com/3342777/177414341-b0183150-0ede-481e-b6f7-a33394db6d26.png">

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.23.1
- VSCode version: 1.68.1
- OS: macOS Monterey 12.4

**Additional context**
Found this today while trying to delete in a really long line. It deleted the whole line instead of before/after. You can work around it by doing `vggd` or `vGd`, ~~but it's definitely not how vim works.~~ 

Edit: well nevermind, this is exactly how vim works. It's not how all the emulators I've used (sublime vintage mode/atom vim mode plus) work, nor how I think it should work. visual mode should not have different behavior than the same commands without it.

**Comment by calebmeyer** [comment]
Well, today I learned. `gg` is goto line, default 1, so `5gg` goes to line 5. `G` is the same thing with a different default (the last line). So they're effectively linewise commands.

This leads me to a question though: What do you use for beginning and end then?

**Comment by J-Fields** [comment]
> This leads me to a question though: What do you use for beginning and end then?

Yeah, interesting question. `[count]go` is characterwise, so `dgo` *should* work like how you want `dgg` to work, but I don't know of an equivalent for `G` that will work for arbitrarily large files.

Now, it seems like we treat `go` as linewise, but that's a bug - I'll file a new ticket for that specifically.
