### ISSUE TITLE
`P` in Visual mode should not overwrite unnamed register

### ISSUE THREAD

**Issue by guillaumeboehm** [VSCodeVim/Vim#7820]
**Is your feature request related to a problem? Please describe.**
When pasting in visual mode the clipboard is overridden by the deleted content, this is very annoying when trying to paste the same content several times.

**Describe the solution you'd like**
Having the option to not override the clipboard on paste.

**Describe alternatives you've considered**
The only workaround that I could find was to map the visual mode paste command to editor.action.clipboardPasteAction but this doesn't seem to be working anymore (the paste doesn't take the selection in account).

**Comment by matecserna** [comment]
Vim 9 has a new feature that seems to solve this exact problem.

https://vimhelp.org/version9.txt.html

> Add the 'P' command in visual mode to paste text in [Visual](https://vimhelp.org/visual.txt.html#Visual) mode without
yanking the deleted text to the unnamed register.  [put-Visual-mode](https://vimhelp.org/change.txt.html#put-Visual-mode)

https://vimhelp.org/change.txt.html#put-Visual-mode

> With P the unnamed register is not changed (and neither the selection or clipboard), you can repeat the same change.

Having support for this standard Vim feature in VSCodeVim would be great.

**Comment by J-Fields** [comment]
Thanks for pointing that out, @matecserna! Neovim appears to behave the same way.
