### ISSUE TITLE
 The <C+i> could not work ! and <C+o> could not work properly

### ISSUE THREAD

**Issue by Realtyxxx** [VSCodeVim/Vim#7821]
**Describe the bug**
 The <C+i> could not work ! and <C+o> could not work properly
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**
both macos (x86) and windows(win11)

The latest version of vscode vim
- Extension (VsCodeVim) version:1.23.1 & 1.23.0
- VSCode version:
- OS: macOS & windows

**Additional context**

**Comment by alvin-7** [comment]
+1

**Comment by skyf0cker** [comment]
It looks version v1.22.2 works well in my mac...

**Comment by Marskey** [comment]
+1

**Comment by lyzhang02** [comment]
+1

**Comment by catskul** [comment]
This issue is poorly written. Not sure if you're referring to the same problem but I also filed an issue:
https://github.com/VSCodeVim/Vim/issues/7822

**Comment by Realtyxxx** [comment]
> This issue is poorly written so I'm not sure if you're referring to the same problem but I also filed an issue:
> 
> 
> 
> Cursor history navigation unable to go back more than one file (1.23.0 +)
> 
> https://github.com/VSCodeVim/Vim/issues/7822

You were right😹
I just think it doesn't works like what it works in vim and nick

By my poor english skills

I could hardly describe my problem clearly!

**Comment by bhumit070** [comment]
Is youe issue solved ?

**Comment by Realtyxxx** [comment]
I still using 1.22 verision

**Comment by Realtyxxx** [comment]
fixed in the newest version
