### ISSUE TITLE
<c-o> jump back to wrong location after 'gd'

### ISSUE THREAD

**Issue by radioinmyhead** [VSCodeVim/Vim#7825]
**Describe the bug**
<c-o> jump back to wrong location after 'gd'
version 1.22.2 is good,  version 1.23.0 and 1.23.1 not work.

**To Reproduce**
use `gd` jump from file-A to file-B ,jump to file-C, jump to file-D. 
then use `c-o` jump back , 
at version 1.22.2 , jump back from D to C to B to A. 
at version 1.23.0 , jump back from D to C to D to C. 

**Screenshots**
good case:
![goodCase](https://user-images.githubusercontent.com/1016570/178435179-d8d005d2-6a3a-4d04-aad0-f28967edb745.gif)

bad case:
![badCase](https://user-images.githubusercontent.com/1016570/178435337-f07435da-4f3f-4dcc-ba97-f9088b3ac89b.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.23.1
- VSCode version:  1.69.0  92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
- OS: Darwin x64 20.6.0

**Additional context**

**Comment by Jayphen** [comment]
I've found that C-o and C-i have changed behaviour in a recent version. They no longer seem to navigate the jump list correctly. Also using 1.23.1

**Comment by catskul** [comment]
https://github.com/VSCodeVim/Vim/issues/7822
