### ISSUE TITLE
Line mode delete consumes last character in a file

### ISSUE THREAD

**Issue by triplepointfive** [VSCodeVim/Vim#783]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

```
[1]23
```

`VdP` or `ddP`

### What did you expect to happen?

```
123

```

### What happened instead?

```
12

```

### Technical details:

Fails only when selection includes last character in a file, works fine in a middle of file.

**Comment by johnfn** [comment]
Nice find. Thanks for the issue! Should be an easy fix.

**Comment by rebornix** [comment]
Fixed via https://github.com/VSCodeVim/Vim/commit/41c803cf598bd26185372fc7d10040b53ac00302
