### ISSUE TITLE
Home in visual line selection doesn't move cursor.

### ISSUE THREAD

**Issue by triplepointfive** [VSCodeVim/Vim#784]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

```
1
2
[3]
4
5
```

`VH`

### What did you expect to happen?

Lines 1-3 are selected, cursor should move to 1.

### What happened instead?

Lines 1-3 are selected, but cursor stays on line 3.

### Technical details:

Works as expected with `VL`. Also this changes the line we've started selection from to line 1, but this should still be the 3rd line.

**Comment by johnfn** [comment]
Thanks for the issue, @triplepointfive!

Should be a really easy fix to swap the start and end cursor positions when we trigger H in visual mode. :)
