### ISSUE TITLE
Cursor keys not working in popups

### ISSUE THREAD

**Issue by markrendle** [VSCodeVim/Vim#785]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

With C# and Vim extensions active, when pressing Ctrl+. to bring up the context-sensitive actions menu, use the cursor keys to move the selection up and down.

### What did you expect to happen?

Cursor keys should move the selection in the Actions context menu.

### What happened instead?

The cursor in the underlying editor is moved. I have to use the mouse to select from the context menu.

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: Current
* OS: Reproducible on Ubuntu 16.04 and Windows 7.

**Comment by markrendle** [comment]
There's a `suggestWidgetVisible` variable you can test in keyboard bindings:

```json
{
  "key": "up",
  "command": "extension.vim_up",
  "when": "editorTextFocus && vim.mode != 'Insert Mode' && !suggestWidgetVisible" 
},
{
  "key": "down",
  "command": "extension.vim_down",
  "when": "editorTextFocus && vim.mode != 'Insert Mode' && !suggestWidgetVisible"
}
```

**Comment by rebornix** [comment]
@markrendle thanks for the issue report and even the fix suggestion!
