### ISSUE TITLE
is it possible to navigate using j, k command in source action menu ?

### ISSUE THREAD

**Issue by p-iknow** [VSCodeVim/Vim#7864]
**To Reproduce**
Source Actions

**Expected behavior**
When a popup like the video below is opened through this source action in the vscode editor, how do I navigate the menu using the j and k keys?

**Screenshots**

https://user-images.githubusercontent.com/35516239/180599565-4cd1efeb-c1e9-487a-a22f-4bebb1b9b30f.mov

**Comment by miromannino** [comment]
If that helps I have CAPSLOCK binded to Escape, and with Karabiner I have that if I keep pressed CAPSLOCK I can use HJKL as arrow keys. This allows me to go through menus with JK but also to use HJKL whenever I can't use vim.

**Comment by theol0403** [comment]
https://github.com/microsoft/vscode/issues/55111
https://github.com/microsoft/vscode/issues/55111
