### ISSUE TITLE
Is there a way to automatically switch input method when using `/` or `?` command to search for strings?

### ISSUE THREAD

**Issue by YWh0301** [VSCodeVim/Vim#7872]
**Describe the solution you'd like**
I'd really like to edit Chinese text with the vim plug-in, while I can successfully set auto-change of input methods when changing from normal mode to insert mode, I couldn't find a way to implement such function for the `/` or `?` command. It'd be really nice to be able to   naturally using a different input method whenever I press key `/` to search for texts( and automatically change it back after pressing `ENTER`).

**Comment by ghsgz** [comment]
No way in VSCodeVim or Vim or NeoVim.
