### ISSUE TITLE
Not maintain cursor position in Insert Mode

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#789]
```
public async exec(position: Position, vimState: VimState): Promise<VimState> {
    const char = this.keysPressed[this.keysPressed.length - 1];

    if (char === "<BS>") {
      const newPosition = await TextEditor.backspace(position);

      vimState.cursorPosition = newPosition;
      vimState.cursorStartPosition = newPosition;
    } else {
      await TextEditor.insert(char, vimState.cursorPosition);

      vimState.cursorStartPosition = Position.FromVSCodePosition(vscode.window.activeTextEditor.selection.start);
      vimState.cursorPosition = Position.FromVSCodePosition(vscode.window.activeTextEditor.selection.start);
    }

    return vimState;
  }
```

Unlike `<operator>+<movement>`, we don't rely on other commands to move cursor in Insert Mode IMO. Now we are inserting content to `vimState.cursorPosition`, which is not secure as other extensions or even Code might change cursor position, for example, auto-close-tag extension and Code's auto-complete. 

Is it a good idea to just use `await TextEditor.insert(char, vscode.window.activeTextEditor.selection.active);` but I'm not sure whether there is any catch. @johnfn @jpoon

**Comment by johnfn** [comment]
Can you hold off on this for about a day until I merge multi cursor mode? I'm currently doing some big edits on this code.

**Comment by jpoon** [comment]
Closing given the lack of activity on this bug.
