### ISSUE TITLE
Make the command be shown in a larger font size

### ISSUE THREAD

**Issue by unuing** [VSCodeVim/Vim#7909]
**Is your feature request related to a problem? Please describe.**
Anytime I use vim commands, the command is shown in the status bar, which makes the cammand is shown in a very small font size.
This makes me very uncomfortable.

**Describe the solution you'd like**
Show the command in the last line of the editor, like the `IdeaVim` plugin in JetBrains IDEs

**Describe alternatives you've considered**
Or show it in a pop up window(something like the thing you see when you press `ctrl`+`p`)

**Comment by clscott** [comment]
Take a look at #7817

**Comment by unuing** [comment]
this is a duplicate of that, closing

**Comment by polaritus9801** [comment]
Is this problem fixed? I'm also finding the solution now.
