### ISSUE TITLE
Change of indentation level in visual line mode is not repeatable

### ISSUE THREAD

**Issue by FSMaxB** [VSCodeVim/Vim#791]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Pressed `V` to get into visual line mode.
Selected multiple lines and pressed `3>`.

### What did you expect to happen?

The highlighted lines to get indented by 3 levels.

### What happened instead?

The highlighted lines got indented by only 1 level.

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.1.10
* OS: Windows 8.1

**Comment by FSMaxB** [comment]
Same with 0.2.0

**Comment by oheard** [comment]
This is an annoying one because the selection is also cleared, meaning you have to go and select the text again repeatedly over-and-over to sort out the indentation.

**Comment by johnfn** [comment]
You can just press `.` 😉 

But yeah I'll add this in. Should be an easy one.
