### ISSUE TITLE
Range mode for visual selection is highlighted in vim command line

### ISSUE THREAD

**Issue by AntonAderum** [VSCodeVim/Vim#792]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
### What did you do?

press `V` to visually select a line
press `:` to vim command line which is now in the range mode for the selected text `'<,'>`
write `s/foo/bar/g`
### What did you expect to happen?

the command line to look like
`'<,'>s/foo/bar/g`
### What happened instead?

`s/foo/bar/g`

This is because the `'<,'>` is highlighted so it gets overwritten as soon as you type something.
This can be avoided by manually un-highlighting it, but it shouldn't be needed.
### Technical details:
- VSCode Version: 1.5.2
- VsCodeVim Version: 0.2.0
- OS: Windows

**Comment by johnfn** [comment]
I agree, but it may actually not be possible to do this with what VSCode provides us. I'm not quite sure, however. @rebornix what do you think?

**Comment by AntonAderum** [comment]
If VSCode forces a selection of the command pallet when you open it I could add an issue/request at their repository and try to get an option for it not to be selected.

**Comment by rebornix** [comment]
Currently it's not possible due to Code's API limitation but I've already filed an issue there https://github.com/Microsoft/vscode/issues/10582 .

**Comment by Youdaman** [comment]
Instead of putting `'<,'>` in the command line box, couldn't the plugin just prepend this to whatever command a user types (like `s/foo/bar/g`) behind the scenes before executing? i.e. "if any text selected, assume range and prepend `'<,'>` to any subseqeuent command"

**Comment by johnfn** [comment]
@Youdaman I think that would confound a lot of _other_ people, who expect the range to be there and would get confused why it wasn't/why their search was suddenly only operating on a range.

**Comment by Youdaman** [comment]
@johnfn could always make it a configuration option.

**Comment by xconverge** [comment]
just cross your fingers for this https://github.com/Microsoft/vscode/pull/23827

**Comment by Tobbe** [comment]
Microsoft/vscode#23827 is merged, so this can now be fixed 👏 🕺

**Comment by Youdaman** [comment]
I've got the latest versions of this plugin (0.7.1) and VSCode (1.12.1) but the text in the command line is still highlighted -- is there anything I need to change in the settings?

**Comment by Chillee** [comment]
@youdaman it's fixed on master, but we haven't rolled out a release yet.
