### ISSUE TITLE
vscode locks up when replaying change on mouse selected position

### ISSUE THREAD

**Issue by iivvoo** [VSCodeVim/Vim#793]
### What did you do?

- Select some text. 
- Hit 'c' to change the selection
- Enter some new text
- select some other location in the file
- replay using '.'

alternatively: start with 'cw' to change word, then replay in the same way.

### What did you expect to happen?

The same change to be applied at the new location

### What happened instead?

vscode locks up. After a while a notification appears

    [Error] Error from the extension host: channel closed
    [Error] Extension host terminated unexpectedly. Please reload the window

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.2.0
* OS: Ubuntu 16.04 64bit

**Comment by rebornix** [comment]
I don't repro this on Mac but I'll try this later on Ubuntu. BTW, are you referring to VSCode 1.5.2 or 1.6.0-Insiders?

**Comment by iivvoo** [comment]
Sorry, 1.6.2 was a typo, I'm on 1.5.2

**Comment by iivvoo** [comment]
Same on a different system; same configuration

**Comment by iivvoo** [comment]
I no longer seem to be able to reproduce this problem eventhough nothing significant changed (no new versions)

**Comment by johnfn** [comment]
This has been fixed. #707 was tracking the same issue, though none of us realized at the time. :)
