### ISSUE TITLE
Using mouse to click on other pane does not select where you click

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#794]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Open up 2 panes, single click on one pane, and then the other in certain spots

### What did you expect to happen?

The cursor to be exactly where I clicked

### What happened instead?

The cursor jumps to where it was previously left (useful when using Ctrl-w + h or l) but not useful when using the mouse to click to move the cursor.

### Technical details:

* VSCode Version: 1.5.2
* VsCodeVim Version: 0.2.0
* OS: Win10x64

**Comment by rebornix** [comment]
It looks like racing issue between update view and selection change event, it looks like a legacy issue as my code doesn't get executed. Let me dig into it more.

**Comment by rebornix** [comment]
I think this should be fixed when we tweak the evil `handleSelectionChange` method.
