### ISSUE TITLE
Go-to-line works only when you invoke it twice or more

### ISSUE THREAD

**Issue by RVMendoza** [VSCodeVim/Vim#795]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
I want to be able to go to a certain line.  
I would press `:64` to go to line `64`

### What did you expect to happen?
I expected it to go to line `64` immediately just like in vim and the cursor would show at that line.

### What happened instead?
- It doesn't go to line `64` immediately. It doesn't seem to do anything. 
- I try invoking it again with `:64` and THEN it goes to line `64`.
- Or it would jump to that line at the top of the window and the cursor would disappear until I move somewhere.

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.2.0
* OS: Sierra 10.12

**Comment by rebornix** [comment]
It's an known issue that we failed to trigger the UI render but if you press `hjkl` after you run the first `:64`, you will see we actually know the cursor is at line 64. The only thing we didn't do is succeeding in refreshing the view.

I think there is an issue for this problem but I had a hard time figuring out which one.

**Comment by rebornix** [comment]
Info for contributors @johnfn @jpoon @xconverge we updated `vscode.window.activeTextEditor.selection` but it doesn't trigger a view update :)

**Comment by rebornix** [comment]
Never mind, it's been fixed in master :)

**Comment by doyouevendev** [comment]
I just installed VSCodeVim and am experiencing this issue. Is this fix in the same version you can download from within the editor's extensions tab or should I wait until it's updated?
