### ISSUE TITLE
Can't remap 's' to 'y' 's' for surround

### ISSUE THREAD

**Issue by aldaty** [VSCodeVim/Vim#7965]
**Describe the bug**
Can't remap 's' to act as 'y' 's' and trigger surround in normal mode

**To Reproduce**

1. In settings.json , add: ```"vim.normalModeKeyBindingsNonRecursive": [{"before": ["s"],"after": ["y","s"] }```
2. Start editing any file
3. press `s` with intention to surround a block

**Expected behavior**
I should be prompted to enter a movement and then able to surround my selection. Instead nothing happens and I'm still in normal mode

**Screenshots**
Logs from the console: 
```
[Extension Host] ModeHandler: debug: handling key=s.

[Extension Host] Remapper: debug: trying to find matching remap. keys=s. mode=Normal. keybindings=normalModeKeyBindingsMap.

[Extension Host] Remapper: verbose: key=s. keySlice=s.

[Extension Host] Remapper: debug: normalModeKeyBindingsMap. match found. before=s. after=y,s. command=undefined. remainingKeys=. mapDepth=1.

[Extension Host] ModeHandler: debug: handling key=y.

[Extension Host] ModeHandler: debug: handleKeyEvent('y') took 1ms

[Extension Host] ModeHandler: debug: handling key=s.

[Extension Host] ModeHandler: debug: handleKeyEvent('s') took 3ms

[Extension Host] ModeHandler: debug: handleKeyEvent('s') took 4ms
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.23.2
- VSCode version: 1.71.1
- OS: macOS Monterey 12.5

**Additional context**
This used to work a long time ago with these exact settings, but I couldn't pinpoint the version.

**Comment by sql-koala** [comment]
you can solve this with a vimrc mapping:
`nnoremap s <plugys>`
(maybe this can also be done in json, but the notation would be difficult.)

Backround:
https://github.com/VSCodeVim/Vim/blob/cdbe97770b51bf690272030bd000292532f2e234/README.md#vim-surround

**Comment by aldaty** [comment]
This indeed works, thank you.
