### ISSUE TITLE
cw does not terminate the current word at the end of whitespace

### ISSUE THREAD

**Issue by dreemkiller** [VSCodeVim/Vim#798]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Place the cursor on the first space in "       goober"
From the vim command line: 
:cw booger

### What did you expect to happen?
Replace the spaces with booger, resulting in the string "boogergoober"
### What happened instead?
replaced the spaces and goober with booger, resulting in the string "booger"
### Technical details:

* VSCode Version:1.5.2
* VsCodeVim Version: 0.2.0
* OS: Ubuntu 16.04

**Comment by johnfn** [comment]
Fixed! Thanks for the report, @dreemkiller. :)
