### ISSUE TITLE
Next tab page command directs to first (left most) tab, not next tab in 1.24.0

### ISSUE THREAD

**Issue by timjcook** [VSCodeVim/Vim#7988]
**Describe the bug**
Updated to 1.24.0
Noticed that `gt` would jump to the first (left most) tab in my editor, instead of the tab to the right of my current tab.
`gT` still worked as expected and cycled through the previous tab (to the left of my current tab).

**To Reproduce**
1. Open 3 or more tabs.
2. focus the middle tab
3. enter command `gt`  normal mode
4. focused tab is now the left most tab (expected to focus next tab on the right)

**Expected behavior**
`gt` command in normal mode would focus the next tab on the right of my current tab (and only cycle to the first tab if my current tab is the right most tab)

**Screenshots**
N/A

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.24.0
- VSCode version: 1.71.2
- OS: Mac OS 12.6

**Additional context**
- Downgrading back to 1.23.0 immediately fixed my issue.

**Comment by J-Fields** [comment]
Fixed in 1.24.1, which is in the pipeline now

**Comment by timjcook** [comment]
@J-Fields thank you!
