### ISSUE TITLE
add appveyor ci

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#8]
@jpoon I don't seem to be able to add authorize apps for this repo. GH permissions drive me mad; I don't know what's missing. Could you please? I've added a first config file; it may fail, but that's ok; I'll debug later.

**Comment by jpoon** [comment]
We already have travis.ci builds: [![Build Status](https://travis-ci.org/VSCode-Extension/VSCodeVim.svg?branch=master)](https://travis-ci.org/VSCode-Extension/VSCodeVim)

You are marked as an 'owner' of the team so you should have all access.

**Comment by guillermooo** [comment]
At some point we'll want to run the tests in Windows too, so I think it's fine having both. Still can't add this repo; must be because I have 2f auth off.

**Comment by jpoon** [comment]
Added with 3e151bfb1623d06c3c8ee50624db85ed45135fdb?

As a sidenote, I'm going to disable direct check-ins to master -- everything should go through PRs to ensure tslint + testing happens.
