### ISSUE TITLE
`va(` not working

### ISSUE THREAD

**Issue by smjure** [VSCodeVim/Vim#8024]
First of all, thanks for the awesome plugin 👍🏻

The issue is that in my case `va(` not working like in vim or nvim. For example: `myFunctionName(arg1,arg2)` and if positioned at `F` in normal mode, by pressing `va(` one would expect to be selected: `(arg1,arg2)`, but nothing happens. How can I fix this? Thank you very much 🙏🏽

**Comment by YalandHong** [comment]
Are you sure this is what command-line Vim behaves like? At least my Vim 8.1 does not have such feature.

**Comment by smjure** [comment]
Yes, double checked and it works as I described it - very useful keybinding.

My vim version:
![image](https://user-images.githubusercontent.com/22912191/196104283-ace74e13-fa87-4dfd-a934-1aae647280ad.png)

and nvim version:
![image](https://user-images.githubusercontent.com/22912191/196104599-4bad91ba-9f2e-4137-af77-dc94db378e09.png)

**Comment by smjure** [comment]
FYI: I  just tested the `va(` on vim version 8.1.3741, and it does not work.

**Comment by petric3** [comment]
Indeed that's useful feature, it looks like the extension is based on older vim version.
