### ISSUE TITLE
Can't select and delete

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#803]
### What did you do?

```
|a
```

Press `i<Shift+RightArrow><Delete>`

### What did you expect to happen?

```
|
```

### What happened instead?

```
|a| // A selected. Looks like stuck in normal mode.
```

### Technical details:

* VSCode Version: 1.6 Insiders
* VsCodeVim Version: 0.2.0
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
I can't reproduce this on master. I've made a number of large changes, any of which could have fixed this bug. Please see if you can reproduce it on master now. :)
