### ISSUE TITLE
<ESC> in auto complete mode exits insert mode

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#804]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

### What did you do?

- Go to insert mode
- Get list of autocomplete
- Found nothing I want, exiting by `<ESC>`

### What did you expect to happen?

Still in insert mode, auto-complete cancelled

### What happened instead?

Back to normal mode

### Technical details:

* VSCode Version: 1.6 Insiders
* VsCodeVim Version: 0.2.0
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
Not too hard of a fix - just requires you to understand the vscode API...

**Comment by rebornix** [comment]
@octref do we know whether the editor is in auto-complete or not?

**Comment by octref** [comment]
@rebornix While editor is showing a list of suggestions, if I click `<ESC>`, it will close auto-complete but then also exit insert mode.

**Comment by rebornix** [comment]
@octref actually I was asking whether Code has any idea indicating that's there is a suggestion popup but yes we do https://github.com/Microsoft/vscode/blob/846a1d8cccb3d6aa747af3cbc5b35c93bfbd393f/src/vs/editor/contrib/suggest/common/suggest.ts#L23 . Easy fix, it's my first commit above 10000 feet.

**Comment by Eksapsy** [comment]
Pardon me if you can, but I don't understand, why is the issue closed? It's still happening after 2 years of this issue being closed.
How can I fix that? I have the exact same problem.

**Comment by bluethon** [comment]
for anyone who google from here, I finally find the [solution](https://github.com/VSCodeVim/Vim/issues/826#issuecomment-346518581)
