### ISSUE TITLE
<leader> <leader> works inconsistently

### ISSUE THREAD

**Issue by calebmeyer** [VSCodeVim/Vim#8040]
**Describe the bug**
Sometimes when I press space space (my leader key twice), the keybinding I'm using:
```
    "vim.leader": "<space>",
    "vim.normalModeKeyBindings": [
        {
            "before": [
                "<leader>",
                "<leader>"
            ],
            "commands": [
                "workbench.action.showCommands"
            ]
        },
    ]
```
works correctly. More often than not, it does not. Sometimes it takes 3 presses, sometimes it won't go even with 10. I know the keypresses are coming in because I can do any number of spaces in insert mode at any speed and they always work correctly. Also, I can see <leader><leader><leader> in the status bar. I have tried using non-recursive and it didn't seem to change the behavior. It does work correctly from visual mode, it's only normal mode that seems to have the problem.

**To Reproduce**

1.  Add the above keybinding
2.  Press space space a few times in normal mode, with ESC in between if the command runner opens.

**Expected behavior**
Every two leaders opens the command runner without fail

**Screenshots**
<img width="358" alt="image" src="https://user-images.githubusercontent.com/3342777/197041555-f404da78-656d-4fa0-918c-8a6f8dde8168.png">

If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/3342777/197042313-9a9af180-4571-4927-a448-1cfd58c87a98.png">

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: 1.24.1
- VSCode version: 1.72.2
- OS: macOS Monterey 12.6

**Additional context**
Cmd-Shift-P still works as expected. Sometimes I see the name of the command (workbench.action.showCommands) in the status bar even though the command runner did not come up.

**Comment by lukesmurray** [comment]
noticed it works more consistently with `"vim.leader": " "` but doesn't make sense so lmk if that helps.

**Comment by calebmeyer** [comment]
That totally helped! Not sure why, but I'll consider this solved.

**Comment by ferdicus** [comment]
tried `" "` & `"space"`  both give me dropped leader presses :( 
anyone had luck with this?

**Comment by YuJuncen** [comment]
I have suffered the problem of randomly dropped leader press at macOS and get rid of this by disabling "Add period with double-space" in system preferences, I'm not sure whether this is the same problem or there are some relationship, just FYI.
