### ISSUE TITLE
<C-c> get printed out in R

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#806]
### What did you do?

`R<C-c>`

### What did you expect to happen?

Exit `R` mode.

### What happened instead?

`<C-c>` get typed out.

### Technical details:

* VSCode Version: 1.6
* VsCodeVim Version: 0.2.0
* OS: OS X 10.11.6

**Comment by jpoon** [comment]
Might be the same as https://github.com/VSCodeVim/Vim/issues/771.
