### ISSUE TITLE
<C-r> in search not working

### ISSUE THREAD

**Issue by Jackels** [VSCodeVim/Vim#808]
### What did you do?
`/ <C-r> 0 `

### What did you expect to happen?
Input the contents of the 0-register ( usually what I last yanked ) and put it into the search

### What happened instead?
I think it searched for `<C-r> 0 `

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.2.0
* OS: Win7 64bit

**Comment by johnfn** [comment]
Shouldn't be too hard. :)
