### ISSUE TITLE
Commands with relative range do not work

### ISSUE THREAD

**Issue by fsoft72** [VSCodeVim/Vim#8083]
**Describe the bug**

At the moment, you always have to specify both start and finish range for a command to be applied.

For example, this works:

```
:25,$d
```

but if I am on line 25 and write:

```
:,$d
```

this does not work.

Same goes for commands like:

```
:1,d
```

that do not work.

**Expected behavior**

If start or end position is missing, it should use the current line.

**Environment (please complete the following information):**

VSCodeVim:  v1.24.3

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:44:09.336Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.0-21-generic
Sandboxed: No

**Comment by welfoz** [comment]
I'm interested to contribute for this issue. This is my first contribution. 
Do you have any advice where to start?
