### ISSUE TITLE
System clipboard register does not work on Linux

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#809]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

"vim.useSystemClipboard": true

Yanking does not go to system clipboard

### What did you expect to happen?

Yank to system clipboard

### What happened instead?

Nothing seemed to go into * register

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: *[please ensure you are on the latest]*
* OS: Ubuntu 16.04

**Comment by xconverge** [comment]
sudo apt-get install xclip on one of my machines fixed it, I will check to see if xclip is installed on the other machine...

Figured this out when I ran with the debugger there was a stack trace and looked into the npm copy-paste package we are using for this stuff

Error: spawn xclip ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.global.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Will potentially close this once I verify the issue is the same with my other computer.

**Comment by xconverge** [comment]
Verified this on the 2nd machine, xclip was not installed

I will create a PR for a tiny documentation update next to where we mention useSystemClipboard in README.md

**Comment by jpoon** [comment]
@xconverge thanks for looking into this. Looking into the copy-paste project, some folks filed an issue on the same thing: https://github.com/xavi-/node-copy-paste. However, last commit has been several months ago so the project.
