### ISSUE TITLE
renaming extension.ts to vim.ts

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#81]
Maybe we can rename `extension.ts` and whatever else necessary to call it `vim.ts` so that we can have command names like `vim.actions.d`, `vim.motion.dollar`, etc. Also, `vim.core.handleKey`, etc.

Minor thing, but would look consistent and we wouldn't have to type `extension` as often :-)

**Comment by jpoon** [comment]
:+1:

**Comment by jpoon** [comment]
To clarify, are you suggesting a name change to the registered commands?

```
registerCommand(context, 'extension.vim_w', () => handleKeyEvent("w"));
```

We had a similar discussion earlier (https://github.com/VSCodeVim/Vim/pull/16) and it was decided to follow the existing vs code command patterns (e.g. `editor.action.insertLineAfter`). But we can rethink those as well.

**Comment by guillermooo** [comment]
`extension.vim_w` `==>` `vim.w` or something like that. I think for that we need to change the name of `extension.ts`. But I'm not sure.

**Comment by jpoon** [comment]
AFAIK, those are independent. What's important is that:

1) The command names that we choose don't collide with what VSCode already defines
2) They match with what's defined in package.json

**Comment by jpoon** [comment]
As it's a minor issue, closing this as won't fix. Feel free to bring it back if you think otherwise.
