### ISSUE TITLE
auto refresh task output should refresh the main screen too

### ISSUE THREAD

**Issue by jeffery9** [VSCodeVim/Vim#812]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

---

Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

run python task
### Technical details:

VSCode Version: 1.5.3
OS Version: win10
Steps to Reproduce:

use vscode to run any python server application, like Odoo
open file in main screen, and show the command output. move the mouse cursor to any lines, when the command output refresh, the main screen should be refresh too.

![animation 9](https://cloud.githubusercontent.com/assets/1404460/18858477/f62e84be-849e-11e6-9ab2-4155339f7520.gif)

have report to  pythonvscode  https://github.com/DonJayamanne/pythonVSCode/issues/339
and  vscode  https://github.com/Microsoft/vscode/issues/12300

**Comment by johnfn** [comment]
Hmm, this is probably related to our other issues about having trouble detecting mouse presses and view changes. Wild guess.

**Comment by rebornix** [comment]
> when the command output refresh, the main screen should be refresh too
@jeffery9 can you help me understand when the command output refreshes, why the main screen should be refreshed too? These two panels have nothing to do with each other.

**Comment by jpoon** [comment]
To keep our issue list sane, closing this issue as it hasn't gained much traction.
