### ISSUE TITLE
Slack invite server appears to be down.

### ISSUE THREAD

**Issue by shea-parkes** [VSCodeVim/Vim#8132]
**Describe the bug**
I tried to use the "Join Slack" functionality from the root readme, but the slack invitation server appears to be down.

**Expected behavior**
Follow link in root readme to https://vscodevim.herokuapp.com/
Get an invite to join Slack.

**Screenshots**
![image](https://user-images.githubusercontent.com/5782892/204872727-0b7507ee-f241-4842-ab3b-3a4adc69cf23.png)

**Comment by jqmtor** [comment]
Hey there,
I was also trying to get an invite to Slack and wasn't able to by following the link. Is there any alternative way to get it?
