### ISSUE TITLE
Duplicate group when creating a split

### ISSUE THREAD

**Issue by little-dude** [VSCodeVim/Vim#8194]
**Is your feature request related to a problem? Please describe.**

I'm trying to switch to vscode from emacs + evil.

In emacs, when I create a split with `:sp` or `:vsp`, the new split allows me to access all the open buffers. But in vscode, `:sp` or `:vsp` creates the split with a single tab. I'd like the split to contain all the tabs that are already open instead.

**Describe the solution you'd like**

I think what I want is provided by the "Duplicate Editor Group Down" and "Duplicate Editor Group Right", so a solution could be having `:sp` and `:vsp` call these commands.

**Describe alternatives you've considered**

None

**Additional context**

I'm very new to vscode and I don't fully understand how its concepts  (groups, editors, tabs) map to what I know in vim and emacs. Maybe what I'm trying to do doesn't really make sense.

**Comment by little-dude** [comment]
I wasn't able to find a workflow that fits me, so back to emacs.

**Comment by DEVv4ld3rr4m4** [comment]
Just agree .  In vim a tabnew open totally clean and complete width and height , not  inside own split context.
