### ISSUE TITLE
When selecting Text using mouse , i want to enter into vscode edit mode (insert mode) instead of VISUAL

### ISSUE THREAD

**Issue by v3ss0n** [VSCodeVim/Vim#8209]
**Is your feature request related to a problem? Please describe.**
When selecting Text using mouse , i want to enter into vscode edit mode (insert mode) instead of VISUAL I'm always frustrated when It enters Visual mode and things got messed up.

**Describe the solution you'd like**
An option so that when slection using mouse , it  enters into edit mode.

**Comment by J-Fields** [comment]
Duplicate of #5716

**Comment by v3ss0n** [comment]
So , select mode is not implemented yet right? ?
