### ISSUE TITLE
Failed to handle key `K`: command '5k' not found

### ISSUE THREAD

**Issue by Lptr-byte** [VSCodeVim/Vim#8247]
**To Reproduce**

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**VSCodeVim version**: 1.24.3

<details><summary>Stack trace</summary>

```
Error: command '5k' not found
    at v.k (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1552:2618)
    at v.executeCommand (vscode-file://vscode-app/snap/code/119/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1552:2534)
```

</details>

**Comment by Lptr-byte** [comment]
I want to use 'K' in the normal mode to quick move,but it says command'5k' not found.How can I deal with it?
There is my code.
```
"vim.normalModeKeyBindingsNonRecursive": [
    {
        "before": [
            "K"
        ],
        "commands": [
            "5k"
        ]
    }
] 
```

**Comment by diolam** [comment]
Maybe you should use `["5", "k"]` in `commands`?

**Comment by Lptr-byte** [comment]
> Maybe you should use `"after: ["5", "k"]` instead of `"commands": ["5k"]`?
Thanks.You method helped me a lot.

**Comment by diolam** [comment]
You may close the issue if you have no more problem.
