### ISSUE TITLE
ESC moves cursor backwards in Normal mode

### ISSUE THREAD

**Issue by jgoz** [VSCodeVim/Vim#825]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Pressed ESC in Normal mode.

### What did you expect to happen?

Nothing.

### What happened instead?

Cursor moved backward 1 character. This happens with every ESC keypress until the cursor reaches the beginning of the line.

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.3.0
* OS: Windows 10 x64

**Comment by johnfn** [comment]
Thanks for the report, @jgoz! This has been fixed on master.
