### ISSUE TITLE
editor.smoothScrolling do not work with Vim (smooth scroll)

### ISSUE THREAD

**Issue by svipas** [VSCodeVim/Vim#8254]
At first I thought it is VS Code bug, but it's Vim extension bug. All info could be found here: https://github.com/microsoft/vscode/issues/173487

I'm using VS Code: 1.78.0 and Vim: v1.25.2

**Comment by svipas** [comment]
Seems like it was bug from VS Code side and they fixed it. I will try to test it with new version to see if I could reproduce it with Vim extension.

**Comment by svipas** [comment]
Reopening issue, because it still doesn't work and I tested with Vim extension disabled and it was working.

**Comment by svipas** [comment]
@zhuowei @J-Fields issue is not fixed, still can repro :)

**Comment by zhuowei** [comment]
Works for me (VSCodeVim v1.27.2, VSCode Insiders 1.86.0-insider (2023-12-11), "Editor: Smooth Scrolling" turned on, macOS 14.2):
If I open a long file and do
`:300`
The document smooth-scrolls to line 300
and if I do `:0` it smooth scrolls back to 0.

@svipas Do you have any steps on how I should repro this?

**Comment by svipas** [comment]
Okay, so we are talking about 2 different things, this issue is not about `:300` (using line number to navigate), but if you use Find Widget (ctrl/cmd + f) and you search for a word and it will scroll just a little with smooth scroll enabled instead of going directly to that word.

**Comment by zhuowei** [comment]
@svipas I can't repro your issue on my machine: when I search with Cmd+F, it scrolls for me with both VSCodeVim and Smooth Scrolling enabled. Do I need to be in a specific mode?

**Comment by svipas** [comment]
@zhuowei Take a look into this issue it has gif it will show how to reproduce: https://github.com/microsoft/vscode/issues/173487

**Comment by zhuowei** [comment]
@svipas That issue was supposedly fixed, though...
I still can't reproduce it on my machine (search always smooth scrolls to the word without me hitting Enter).

My vscode user config is:
```
{
    "workbench.colorTheme": "Visual Studio Light",
    "update.mode": "manual",
    "window.titleBarStyle": "native",
    "editor.smoothScrolling": true
}
```

I don't have any other options changed from default. Does this still reproduce with VSCodeVim and VSCode's default settings?

**Comment by svipas** [comment]
@zhuowei did you tested exactly like in the gif? That word you're searching with Find Widget should be not visible in your viewport and at the bottom somewhere, scroll to the top, place there cursor and use Find Widget to search that word it should jump, but not by much and that word still shouldn't be visible in your viewport. At least I can repro this and it has nothing to do with vanilla settings it is just that Vim + smooth scroll isn't quite working together, because of this issue.

**Comment by svipas** [comment]
@J-Fields Please re-open, because this bug is not fixed.
