### ISSUE TITLE
Add a setting to toggle whether <Esc> closes autocomplete in insert mode.

### ISSUE THREAD

**Issue by FSMaxB** [VSCodeVim/Vim#826]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

I type something that opens the autocomplete dropdown (typing the beginning of the name of a known symbol for example). After I stop typing, I press Escape to go back to normal mode.

### What did you expect to happen?

The editor should change to normal mode.

### What happened instead?

The escape key closed the autocomplete dropdown, without changing the vim mode. If I want to change to normal mode, I have to press escape twice.

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.3.0
* OS: Windows 8.1

I am not completetely sure if this also happened with 0.2.0, but I don't think so. Because right now many times when I'm trying to change to normal mode and save the file, it types in :w<return> instead, which inserts a while loop in my code. This is really annoying because it completely destroys my workflow and it never saw that happening with 0.2.0.

**Comment by johnfn** [comment]
This is actually on purpose: https://github.com/VSCodeVim/Vim/issues/804

**Comment by FSMaxB** [comment]
Is there a setting to turn this off?

**Comment by FSMaxB** [comment]
Or rather: Could you add one?

**Comment by johnfn** [comment]
Yes, that could be done. PRs welcome... 😉

**Comment by FSMaxB** [comment]
I see what I can do once I have time.

**Comment by FSMaxB** [comment]
Regarding that: Is there a way to use settings from `settings.json` in conditions in the `when` part of keybindings?

**Comment by FSMaxB** [comment]
The current way to set this setting is by putting the following in `keybindings.json`:
```JSON
 { "key": "escape",        "command": "extension.vim_escape",
                              "when": "editorTextFocus && !inDebugRepl" }
```

**Comment by johnfn** [comment]
I've come around. You were right, this is incredibly annoying. If anyone wants the old behavior, they can add the setting. :P

**Comment by leonzhu42** [comment]
Not working. I've checked the default `keybindings.json`. The solution above has been set default.

I also checked VSCode documentation. I didn't find `inDebugRepl` option. Instead, I saw `inDebugMode`. Tried. Still not working.

I also tried `suggestWidgetVisible`. Still.

**Comment by zyujs** [comment]
you can try to add this to keybindings.json
`{
  "key": "escape",
  "command": "-extension.vim_escape",
  "when": "editorTextFocus && !inDebugRepl"
},
{
  "command": "extension.vim_escape",
  "key": "escape",
  "when": "editorTextFocus && !inDebugRepl && !suggestWidgetVisible"
},
`

**Comment by leonzhu42** [comment]
@zyujs It works! Thank you! I didn't know that I could put this `-` in `"command"`.

**Comment by mxchai** [comment]
I believe the API has changed a bit, so what @zyujs suggested didn't work for me. I modified the snippet slightly to get this:

```
  {
    "key": "escape",
    "command": "-extension.vim_escape",
    "when": "editorTextFocus && vim.active && !inDebugRepl"
  },
  {
    "key": "escape",
    "command": "extension.vim_escape",
    "when": "editorTextFocus && !inDebugRepl && !suggestWidgetVisible"
  }
```
The only slight difference is that you need to include a `vim.active` in the keybinding removal clause, since the default keybinding file for `extension.vim_escape` now contains `vim.active`.

**Comment by sheelah** [comment]
Thank you @mxchai!  I had been looking for a way to still exit the search dialog box with escape while using vim.

**Comment by StanBright** [comment]
I'm still struggling to make this work. 

I'm getting the following warning when I add the suggested configs to `keybindings.json`:
```
Name of the command to execute

Value is not accepted
```

**Comment by huyz** [comment]
Does anyone know if there's a command to close the suggestions widget so I can set a separate keybinding (e.g., `Ctrl+Q`).  Sometimes I want to get rid of suggestions one time but remain in vim insert mode.
