### ISSUE TITLE
Support for global (:g)

### ISSUE THREAD

**Issue by mbp** [VSCodeVim/Vim#828]
It appears there is no support for the global command. I would like to wish for that feature :-)

It's quite powerful to have an operation performed on every line. For example I use this when I want to remove all lines except ones containing my text, useful for log files.

```
:g!/something_in_the_line/d
```

There is some more description here: http://vim.wikia.com/wiki/Power_of_g

**Comment by AJRepo** [comment]
I actually use this quite often in more complex search/replace methods than the standard :s/SEARCH/REPLACE offers and for really long lines where only a small part needs to be changed and only on lines that have a different keyword on them. 

Here's a simplified example
`:g/SEARCH.*/s/foo/bar/` which would only change the first "foo" following SEARCH to "bar" in those lines that have a SEARCH in them. 

--------------
Other commands I use often with this key sequence: 

`:g/SEARCH/d` which deletes only those lines with the word SEARCH in them.

`g/SEARCH/j` which joins the next line in lines with the word SEARCH in them

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).
