### ISSUE TITLE
Cursor jumps to top of file after changing tabs and deselecting visual selection

### ISSUE THREAD

**Issue by adamlogic** [VSCodeVim/Vim#8287]
**Describe the bug**

Normally, if I make a visual selection then press escape to exit visual mode, my cursor is left in the same position. But if I make a visual selection, then switch tabs and return to the same file before exiting visual mode, my cursor jumps to the top of the file.

**To Reproduce**

1.  Open two files.
2.  Scroll down and make a visual selection in one file.
3. Switch to the other file, then back to the original file.
4. Press `<esc>` to exit visual mode.
5. Cursor will jump to the top of the file.

**Expected behavior**

When exiting visual mode to normal mode, I expect my cursor to remain at the start of the visual selection.

**Screenshots**

For this video, I disabled all user settings and extensions (except Vim).

![CleanShot 2023-03-07 at 10 50 08](https://user-images.githubusercontent.com/372/223474708-f67d19a0-85ed-4cf2-86c2-965a1965bd1e.gif)

**Environment**

- Extension (VsCodeVim) version: 1.25.2
- VSCode version: 1.76.0
- OS: macOS 13.2.1

**Additional context**

This is a relatively new issue. It's probably been happening for me for about a month.

**Comment by Nauxscript** [comment]
I got the same problems for months...
In my vscode, I don't even need to make a visual selection:

1. Open two files.
2. Scroll down in one file (in most cases this file may be have hundreds of line of code).
3. Switch to the other file, then back to the original file.
4. Pressing arrow keys to move the cursor
5. Cursor will jump to the top of the file.

my environment:
- Extension (VsCodeVim) version: 1.25.2
- VSCode version: 1.76.0
- OS: macOS 13.1

its really annoying me 😢

**Comment by adamlogic** [comment]
@Nauxscript Interesting... I'm not able to reproduce that behavior.

![CleanShot 2023-03-09 at 06 56 49](https://user-images.githubusercontent.com/372/224016242-1e4747f1-fbac-4501-bc7f-21c305ef619f.gif)

**Comment by RoXuS** [comment]
Same issue here, when I change tab the cursor don't keep it old position and jump to the top.

Following recent version of vscode or vim?

**Comment by RoXuS** [comment]
This issue is a duplicate of https://github.com/VSCodeVim/Vim/issues/8200#issuecomment-1462061030

**Comment by adamlogic** [comment]
Thanks @RoXuS
