### ISSUE TITLE
ctrl+h doesn't work in insert mode

### ISSUE THREAD

**Issue by nkulikov** [VSCodeVim/Vim#829]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Enter some symbols in _insert mode_ and then press `<ctrl+h>`:

```
abcd<C-h>
    ^
cursor here
```

### What did you expect to happen?

The symbol in front (left) of cursor should be removed.

### What happened instead?

`<C-h>` appears in cursor position.

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: starting from 0.2.0
* OS: macOS (10.12)

**Comment by nkulikov** [comment]
Not sure that it is a feature because `ctrl-h` works everywhere in OSX system (editors, console and so on) except VSCodeVim _insert mode_. It seems like a bug :)
And it works in _normal mode_. As I remember it worked in _insert mode_ before release 0.2.0.

**Comment by johnfn** [comment]
We've pretty much rewritten all keybindings in VSCodeVim. So anyone who would want C-h would have to implement it themselves (as opposed to just letting it pass through). So it's indeed a bug 😉 

It working in normal mode, on the other hand, is a bug. :P

**Comment by johnfn** [comment]
C-h now works in insert mode - we just need to prevent it from inserting anything in normal mode.

**Comment by nkulikov** [comment]
Thanks! It works! ;)
