### ISSUE TITLE
Auto-inserted characters confuse cursor index when using backspace

### ISSUE THREAD

**Issue by dallas** [VSCodeVim/Vim#832]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Typed in some characters until autocomplete suggestions showed up, hit `<enter>` to accept a suggestion, then hit `<backspace>` to remove character behind cursor position.

### What did you expect to happen?

Character behind the current cursor position would be removed.

### What happened instead?

Character from where I accepted the autocomplete suggestion was removed, then further `<backspace>` presses removed as normal (cursor remained at the end of the autocompleted text).

### Technical details:

* VSCode Version: 1.6.0-insiders (602155bb781f509c7a4ddcd700b57cb9b9f5286d)
* VsCodeVim Version: *[please ensure you are on the latest]* 0.3.0
* OS: macOS Sierra 10.12.1 Beta (16B2327e)

**Comment by xconverge** [comment]
Great find, this is super annoying thanks for reporting!

**Comment by xconverge** [comment]
Filed https://github.com/Microsoft/vscode/issues/13231 related to this

**Comment by Liquidmantis** [comment]
This bug is back in 0.3.7.  I'm not sure if that's the release that reintroduced it as I missed one or two.

**Comment by xconverge** [comment]
This is fixed again right?

**Comment by rebornix** [comment]
It's gone already.
