### ISSUE TITLE
Auto Switch Input Method stops working on WSL

### ISSUE THREAD

**Issue by parker-chung** [VSCodeVim/Vim#8324]
**Describe the bug**

I'm working on Windows Subsystem for Linux (WSL).
The feature Auto Switch Input Method worked fine before but now it's broken.
It keeps throwing the error about being unable to find im-select.exe even when the path to it is correct.

1. The path to im-select.exe
![image](https://user-images.githubusercontent.com/57929314/226271899-6553794f-a214-440e-94a4-0f433bda72a3.png)
2. Settings related to Auto Switch Input Method
![image](https://user-images.githubusercontent.com/57929314/226272032-0fd69f42-a43a-479e-a829-13c9b322daf3.png)
3. Error messages I'm getting from the extension in Output panel
![image](https://user-images.githubusercontent.com/57929314/226272132-353849a9-b490-415e-98c1-ee7ea6acb4bb.png)

**To Reproduce**

1.  Open a new WSL window
2.  Make sure to set up the settings related to Auto Switch Input Method
3. Toggle Output panel and look for logs from the extension Vim

**Expected behavior**
Successfully find the im-select.exe file and be able to switch the input method according to the related setting

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.25.2
- VSCode version: 1.76.2
- OS: WSL: Ubuntu-20.04

**Additional context**

**Comment by Yi-Qing** [comment]
I'm try to use the old version 1.25.1, also have this problem.

but when i use 1.24.3, it work's fine

**Comment by NikolaiKotikov** [comment]
Have the same issue too. I think that `im-select.exe` is not found because it's impossible to apply `vim.autoSwitchInputMethod` options when project is opened in WSL
![image](https://user-images.githubusercontent.com/45531639/234770032-d4c824bf-3775-439e-b5e9-8f8be7578fa6.png)

**Comment by listenerri** [comment]
May be due to the commit: https://github.com/VSCodeVim/Vim/pull/8051

**Comment by listenerri** [comment]
I found a solution to this problem. 
When using WSL remote development, switch the settings tab to "Remote" in the settings page and set several settings related to the `vim.autoSwitchInputMethod.*` to the same settings as under User (Windows) settings. That is to say, the `im-select` command line should use a Windows-style path for WSL remote configuration, because the vim ext is set to run locally only, so it does not recognize linux paths under WSL.

![图片](https://github.com/VSCodeVim/Vim/assets/7995379/0621d590-b93c-410f-955b-b99c280ae1d0)

**Comment by parker-chung** [comment]
> I found a solution to this problem. When using WSL remote development, switch the settings tab to "Remote" in the settings page and set several settings related to the `vim.autoSwitchInputMethod.*` to the same settings as under User (Windows) settings. That is to say, the `im-select` command line should use a Windows-style path for WSL remote configuration, because the vim ext is set to run locally only, so it does not recognize linux paths under WSL.
> 
> ![图片](https://user-images.githubusercontent.com/7995379/248395294-0621d590-b93c-410f-955b-b99c280ae1d0.png)

This solution solved the problem!
Thank you for help.

**Comment by transtone** [comment]
https://github.com/VSCodeVim/Vim/pull/8675
