### ISSUE TITLE
Ctrl-c going to prev char in normal mode

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#834]
### What did you do?

`<C-c>` in normal mode.

### What did you expect to happen?

Nothing.

### What happened instead?

Going to prev char.

### Technical details:

* VSCode Version: 1.6.0 Insiders
* VsCodeVim Version: 0.3
* OS: OS X 10.11.6

**Comment by johnfn** [comment]
Pretty sure this one is already fixed on master. :)
