### ISSUE TITLE
v inclusive/exclusive toggle doesn't work

### ISSUE THREAD

**Issue by Ameenafz248** [VSCodeVim/Vim#8359]
**Describe the bug**
the 'v' operator that is used for toggling inclusive/exclusive doesn't work with other operators such as d, c, etc.

**To Reproduce**
while in normal mode, enter 'dv0' or 'dvb', it won't delete till start of the line/ previous word including the character under cursor.

**Expected behavior**
For example, with 'dv0', it should delete till start of the line including the character under cursor.

**Comment by J-Fields** [comment]
Duplicate of #6748
