### ISSUE TITLE
how to reduce or eliminate delay while tying `j` or `k`

### ISSUE THREAD

**Issue by yaoyhu** [VSCodeVim/Vim#8363]
**Describe the bug**
I have mapped `jk` to `ESC` in insert mode. While everything is functional, I find the brief delay after typing `j` or `k` while it waits for a second input very distracting.  
Is it possible for a `j` or `k` to always be instantly inserted into the buffer, then if I press `j` or `k` again the first one is removed before returning to normal mode.

**To Reproduce**
(![brief delay](https://raw.githubusercontent.com/danielhu19/mypicgocloud/master/img/202304091911142.gif))

**Expected behavior**
Is there any way to solve this just like vim way `inoremap <nowait> jj <ESC>`

**Comment by danielhu19** [comment]
I have tried the vscodevimrc way but not working:
```
  "vim.vimrc.enable": true,
  "vim.vimrc.path": "$HOME/.vscodevimrc",
```
in .vscodevimrc:
```
inoremap <nowait> jj <ESC>
```

**Comment by MaqingOnes** [comment]
well maybe just keep typing instead of pause after you enter j or k?
I struggle with this problem too, but now I don't mind it , just type fast for the next character comes after j.

**Comment by MaqingOnes** [comment]
> I have tried the vscodevimrc way but not working:
> 
> ```
>   "vim.vimrc.enable": true,
>   "vim.vimrc.path": "$HOME/.vscodevimrc",
> ```
> 
> in .vscodevimrc:
> 
> ```
> inoremap <nowait> jj <ESC>
> ```

if you map jj to esc , why k also has delay?

**Comment by danielhu19** [comment]
> MaqingOnes

Actually, I mapped `jk` `jj` `kk` `kj` to `ESC`(Now I only kept `jj`) in vscode `setting.json`.  

> ```inoremap <nowait> jj <ESC>``` is a vim script for eliminating delay in vim

Typing fast is not a great way while typing `Enter` to accept suggestions from auto-completion. e.g. if I type fast `Link` and accept a suggestion like `LinkList`, the cursor waits after the letter `n`, and inserts the suggestion. The result will be like `LinkListk` which duplicates the letter `k` in the end.

**Comment by MaqingOnes** [comment]
I get what you mean , type  `intej` and hit enter will get `intejj`, it is a problem actually. But I've never notice that , maybe I just don't use j that match lol
and since you only kept jj to ESC, so there won't be duplicate k right? , only duplicate j from time to time.

> > MaqingOnes
> 
> Actually, I mapped `jk` `jj` `kk` `kj` to `ESC`(Now I only kept `jj`) in vscode `setting.json`.
> 
> > `inoremap <nowait> jj <ESC>` is a vim script for eliminating delay in vim
> 
> Keep typing is not a great way while typing `Enter` to accept suggestions from auto-completion. e.g. if I type fast `Link` and accept a suggestion like `LinkList`, the cursor waits after the letter `n`, and inserts the suggestion. The result will be like `LinkListk` which duplicates the letter `k` in the end.

**Comment by danielhu19** [comment]
> I get what you mean , type  `intej` and hit enter will get `intejj`, it is a problem actually. But I've never notice that , maybe I just don't use j that match lol
> 
> and since you only kept jj to ESC, so there won't be duplicate k right? , only duplicate j from time to time.
> 
> 
> 
> > > MaqingOnes
> 
> > 
> 
> > Actually, I mapped `jk` `jj` `kk` `kj` to `ESC`(Now I only kept `jj`) in vscode `setting.json`.
> 
> > 
> 
> > > `inoremap <nowait> jj <ESC>` is a vim script for eliminating delay in vim
> 
> > 
> 
> > Keep typing is not a great way while typing `Enter` to accept suggestions from auto-completion. e.g. if I type fast `Link` and accept a suggestion like `LinkList`, the cursor waits after the letter `n`, and inserts the suggestion. The result will be like `LinkListk` which duplicates the letter `k` in the end.
> 
> 
> 
> 

Yeah，'j' is not a usual letter for coding. Just keep the issue open. Maybe someone could fix it. haha
