### ISSUE TITLE
Left and right arrow keys navigate past EOL and beginning of line in insert

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#839]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In insert mode, use left and right arrow keys, 

### What did you expect to happen?

It should stop at the beginning and end of line

### What happened instead?

The cursor wraps around to the next or previous line

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: master
* OS: macOS Sierra

**Comment by xconverge** [comment]
Am guessing this needs to be handled in handleSelectionChange() when e.kind === vscode.TextEditorSelectionChangeKind.Command.Keyboard

Any other suggestions for how this could be addressed?

**Comment by johnfn** [comment]
This is a weird one. Yes, that's Vim's behavior, but it's equally reasonable to expect it to wrap like it does in VSCode. (Note Vintageous does the same thing.) I'm not too concerned here.

**Comment by xconverge** [comment]
Sure I agree, I would wait for some arrow users to chime in though

**Comment by xconverge** [comment]
This can get crazy with multicursor if one of the cursors happens to be on a shorter line than the others...

**Comment by johnfn** [comment]
@xconverge that's okay! It's the fun of multicursor 😉

**Comment by johnfn** [comment]
Apparently this has been fixed. Thanks to whoever fixed it. (We're not really sure who that was.)

**Comment by dtaub** [comment]
Is there a way to get the old behavior back, like vim's `whichwrap` setting?
