### ISSUE TITLE
Keep pressing `j` or `k` doesn't move cursor down or up lines?

### ISSUE THREAD

**Issue by concretevitamin** [VSCodeVim/Vim#8391]
**Describe the bug**
Keep pressing `j` or `k` doesn't move cursor down or up lines.

**To Reproduce**

1.  Press `j`, hold. (I do have `j j` mapped to `ESC`.)
1.  Press `k`, hold. 

**Expected behavior**
As in Vim, I expected the cursor to keep moving down/up line by line. Both the above make the cursor stay on the same line, and I had to do `j j` or `k k` or `<num> j/k` to move around. 

Any settings I'm missing?

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:
- VSCode version:
- OS:

**Additional context**

**Comment by ahmad1702** [comment]
Did you check to see if you had any other extension that could possibly be overriding j or k? Also if you could provide the relative Environment versions and OS that would be great

**Comment by yhorbachov** [comment]
I think you need to enable key repeating.

To enable key-repeating, execute the following in your Terminal, log out and back in, and then restart VS Code:
```sh
$ defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false              # For VS Code
$ defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false      # For VS Code Insider
$ defaults write com.vscodium ApplePressAndHoldEnabled -bool false                      # For VS Codium
$ defaults write com.microsoft.VSCodeExploration ApplePressAndHoldEnabled -bool false   # For VS Codium Exploration users
$ defaults delete -g ApplePressAndHoldEnabled                                           # If necessary, reset global default
```

**Comment by concretevitamin** [comment]
Thanks @yhorbachov, works well.

**Comment by flashios09** [comment]
Thanks @yhorbachov ❤️

**Comment by guunergooner** [comment]
> I think you need to enable key repeating.
> 
> To enable key-repeating, execute the following in your Terminal, log out and back in, and then restart VS Code:
> 
> ```shell
> $ defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false              # For VS Code
> $ defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false      # For VS Code Insider
> $ defaults write com.vscodium ApplePressAndHoldEnabled -bool false                      # For VS Codium
> $ defaults write com.microsoft.VSCodeExploration ApplePressAndHoldEnabled -bool false   # For VS Codium Exploration users
> $ defaults delete -g ApplePressAndHoldEnabled                                           # If necessary, reset global default
> ```

Thanks @yhorbachov , Help me solve the shortcut key long press problem when migrating from mac intel to mac m3
