### ISSUE TITLE
convention for module names

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#84]
We have `these_names.ts` and `thisNames.ts`. Which one do we want to use? Can we follow a TS guideline or VSC team guideline instead of creating a new one?

**Comment by jpoon** [comment]
In the contributing.md, I've linked it to VS Code's guidelines

> ### Styleguides

> We are adhering to VSCode's [coding guidelines](https://github.com/Microsoft/vscode/wiki/Coding-Guidelines).

For the module/file name, it's not explicitly stated but looking at their source code, it s camelCasing (no underscore) so let's go with that.

`myClass.ts` and not ~~`my_class.ts`~~

**Comment by jpoon** [comment]
As we modify the files, let's slowly rename them to follow
