### ISSUE TITLE
In Insert mode cannot got to end of line with <End> key

### ISSUE THREAD

**Issue by Platzer** [VSCodeVim/Vim#841]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In Insert mode press key `End`.

### What did you expect to happen?

Move cursor in insert mode to end of line, before the newline character.

### What happened instead?

Cursor is moved before the last visible character in line.

![vscode vim cannot end](https://cloud.githubusercontent.com/assets/3358663/19104532/5110d352-8add-11e6-834d-64d070cd0511.gif)

### Technical details:

* VSCode Version: 1.6.0 Insider
* VsCodeVim Version: *0.3.0*
* OS: Window 7

**Comment by xconverge** [comment]
Was this on 0.3.0 or was it on master? If on master I may have caused it and the fix is in a pull request right now in #838

**Comment by xconverge** [comment]
Yep confirmed this is fixed in #838

**Comment by johnfn** [comment]
Thanks @xconverge!
