### ISSUE TITLE
j/k moving diagonally

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#842]
As you see it's moving diagonally.

![j](https://cloud.githubusercontent.com/assets/4033249/19123350/26489276-8ae3-11e6-8790-72321cffdb97.gif)
### Technical details:
- VSCode Version: 1.6 Insiders
- VsCodeVim Version: 0.3
- OS: OS X 10.11.6

**Comment by xconverge** [comment]
I cant reproduce this, does it happen all of the time for you?

**Comment by octref** [comment]
Seems to happen if I'm moving from outside of a `{}` to inside.

![jk](https://cloud.githubusercontent.com/assets/4033249/19128887/120a9220-8afa-11e6-859d-7998e2b24e10.gif)

**Comment by johnfn** [comment]
I can't reproduce this either. Do you have any other extensions running? Also, what language is that? Is it TypeScript?

**Comment by octref** [comment]
@johnfn @xconverge 

Figured out the problem. This happens when indentation is tab.

**Comment by octref** [comment]
Now it makes sense. The fix would be make a tab `tabSize` long instead of 1 char long when calculating movement.

**Comment by xconverge** [comment]
@octref right on! Reproduced the issue, thanks for finding it

**Comment by rebornix** [comment]
@octref good catch.

We need take `tabStop` into consideration while calculating `desiredColumn`.

**Comment by xconverge** [comment]
@johnfn is working on this in #859

**Comment by octref** [comment]
@xconverge This seems to be fixed so closing it.

**Comment by johnfn** [comment]
This was not fixed. It still appears to be a problem in master.

**Comment by jpoon** [comment]
Given the old age of this bug, the lack of activity, and that I can't repro, closing as this bug has likely been fixed on the latest release.
