### ISSUE TITLE
J does not work as expected in insert mode.

### ISSUE THREAD

**Issue by szfkamil** [VSCodeVim/Vim#8433]
Type: <b>Bug</b>

Set the following Vim: Command Line Mode Key Bindings
```
{
  "files.autoSave": "onFocusChange",
  "editor.multiCursorModifier": "ctrlCmd",

  "editor.formatOnSave": true,
  "[python]": {
    "editor.formatOnType": true
  },
  "editor.accessibilitySupport": "off",
  "audioCues.lineHasError": "off",
  "liveServer.settings.donotShowInfoMsg": true,
  "workbench.colorTheme": "Dracula",
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "window.zoomLevel": 2,
  "workbench.statusBar.visible": false,
  "vim.overrideCopy": false,
  "vim.commandLineModeKeyBindings": [
    
  ],
  "vim.insertModeKeyBindings": [],
  "settingsSync.ignoredSettings": [],
  "workbench.sideBar.location": "right",
  "vim.camelCaseMotion.enable": true,
  "vim.commandLineModeKeyBindingsNonRecursive": []
}
```

Extension version: 1.25.2
VS Code version: Code 1.78.2 (Universal) (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:44:45.204Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id d23ea9a5-97d3-445b-b510-e757b4cf2447|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30705553
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by szfkamil** [comment]
I just learned that "J" does not work at all for me inside VSCode when Vim plugin is enabled.

**Comment by szfkamil** [comment]
This is weird:
![CleanShot 2023-05-25 at 20 05 45@2x](https://github.com/VSCodeVim/Vim/assets/82778513/7405fe26-743e-478e-9a2c-37d7cf4c569b)

I tried to reinstall to reset the settings to default, but it's still not working. It happened after I added J + K binding as an ESC key, but later removed it.

**Comment by userrand** [comment]
> This is weird:
> 
>  CleanShot.2023-05-28.at.20.17.23.mp4 
> I tried to reinstall to reset the settings to default, but it's still not working. It happened after I added J + K binding as an ESC key, but later removed it.

did you add the shortcut with the vscode keybindings   (either via command palette -> keyboard shortcuts or the keybindings.json) or via the settings.json file ?

**Comment by szfkamil** [comment]
> > This is weird:
> > CleanShot.2023-05-28.at.20.17.23.mp4
> > I tried to reinstall to reset the settings to default, but it's still not working. It happened after I added J + K binding as an ESC key, but later removed it.
> 
> did you add the shortcut with the vscode keybindings (either via command palette -> keyboard shortcuts or the keybindings.json) or via the settings.json file ?

I've added it inside `keybinds.json`. I also opened an issue on stackoverflow about this; I'll have to dig a little deep here from what I've look at so far. When you search for 'second chord' on stackoverflow I found some solutions but I'm yet to try them now.

[How can I resolve the issue where pressing J in VSCode's Vim extension "waits for the second chord" even after a fresh installation?](https://stackoverflow.com/questions/76392048/how-can-i-resolve-the-issue-where-pressing-j-in-vscodes-vim-extension-waits-fo)

**Comment by userrand** [comment]
> > > This is weird:
> > > CleanShot.2023-05-28.at.20.17.23.mp4
> > > I tried to reinstall to reset the settings to default, but it's still not working. It happened after I added J + K binding as an ESC key, but later removed it.
> > 
> > 
> > did you add the shortcut with the vscode keybindings (either via command palette -> keyboard shortcuts or the keybindings.json) or via the settings.json file ?
> 
> I've added it inside `keybinds.json`. I also opened an issue on stackoverflow about this; I'll have to dig a little deep here from what I've look at so far. When you search for 'second chord' on stackoverflow I found some solutions but I'm yet to try them now.
> 
> [How can I resolve the issue where pressing J in VSCode's Vim extension "waits for the second chord" even after a fresh installation?](https://stackoverflow.com/questions/76392048/how-can-i-resolve-the-issue-where-pressing-j-in-vscodes-vim-extension-waits-fo)

are you sure the bindings are absent from the JSON file? The UI for the keyboard shortcuts can be unreliable so I would check directly the keybindings JSON file to see if it's absent.

**Comment by szfkamil** [comment]
> The UI for the keyboard shortcuts can be unreliable so I would check directly the keybindings JSON file to see if the keybinding you removed is really absent.

Oh, yes my brother.. never trust UI: 
<img width="630" alt="CleanShot 2023-06-05 at 21 29 53@2x" src="https://github.com/VSCodeVim/Vim/assets/82778513/24b6d41b-3184-4d63-b1f1-5fdd50bc092b">

Woah, I can actually use vim now...
