### ISSUE TITLE
VSCode RelativeNumbers (new feature) doesn't work with Vim extension

### ISSUE THREAD

**Issue by Liquidmantis** [VSCodeVim/Vim#844]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Enabled the new VSCode native relativeNumbers option.
"editor.lineNumbers": "relative",

### What did you expect to happen?

Line numbering to be relative. :)
### What happened instead?

On Windows, line numbering is relative before Vim loads (Vim keys give a "not found" error immediately on launch).  Once Vim keys work the line number switches to absolute.  On Mac the line numbering is just always absolute.

Uninstalling the Vim extension makes both platforms work as expected (just no Vim :( )

### Technical details:
RelativeNumbers:
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_6.md#improvements-to-linenumber-and-whitespace-settings

* VSCode Version:
1.6.0-insiders
* VsCodeVim Version:
0.3.0
* OS: 
Mac: 10.12.1, 10.11.6 (corp laptop not okayed for Sierra yet)
Win: 2012 R2, Win10 Pro b14936

**Comment by xconverge** [comment]
Thanks for reporting this! I reproduced it as well, will be awesome when this works!

**Comment by johnfn** [comment]
😕 

Why on earth would that be..? It's just a VSCode setting; it's totally separate from VSCodeVim.

I am confused.

**Comment by xconverge** [comment]
I wonder if we are not updating something that they are using to generate this location? Some flavor of cursor position

**Comment by Liquidmantis** [comment]
This was fixed by the latest nightly (10/7's release) of VSCode Insiders.  Not sure what the change was but I confirmed behavior on multiple systems with multiple versions of Vim.
