### ISSUE TITLE
Closing Default Settings window with :q doesn't work

### ISSUE THREAD

**Issue by FSMaxB** [VSCodeVim/Vim#846]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

* In the menu: File > Preferences > User Settings
* Selected the "Default Settings" tab.
* Pressed `:q`

### What did you expect to happen?

The tab should be closed.

### What happened instead?

Nothing.

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.3.0
* OS: Windows 8.1

### What works:

* Closing all tabs with `:qa`
* `<ctrl-p> >View: Close Editor`

**Comment by dkalowsk** [comment]
👍

**Comment by xconverge** [comment]
@johnfn sorry I forget to say fixes this in the commit message but #855 fixed this

**Comment by johnfn** [comment]
Thanks for letting me know!
