### ISSUE TITLE
Multiple presses of Esc move cursor to the left

### ISSUE THREAD

**Issue by Liquidmantis** [VSCodeVim/Vim#847]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Pressed Esc more than one

### What did you expect to happen?

Nothing after returning to Normal mode.

### What happened instead?

Cursor moves left for each additional press of Esc.

### Technical details:

* VSCode Version: 1.6.0-insiders
* VsCodeVim Version: 0.3.0
* OS: Win2012 R2, macOS 10.12.1

**Comment by xconverge** [comment]
Dupe of #825, should be fixed on master

**Comment by Liquidmantis** [comment]
I searched!  Must've done poorly...  Sorry for the duplicate.
