### ISSUE TITLE
split cannot open correct file

### ISSUE THREAD

**Issue by mc956759** [VSCodeVim/Vim#8472]
Type: <b>Bug</b>

I use ":sp/:vsp file-b" while I opened file-a, it can't open the file-b, and just open the file-a again.

Extension version: 1.25.2
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600KF (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (9.33GB free)|
|Process Argv|--crash-reporter-id e24ddfd8-622e-47ed-988b-5f090751d259|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container ubuntu (gc_build)|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600KF (16 x 3686)|
|Memory (System)|24.95GB (23.34GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
showindicator:30766890
pythongtdpath:30769146
i26e3531:30769768
dh2dc718:30770000

```

</details>

**Comment by giatmanos** [comment]
I am having the same issue.

Extension version: 1.25.2
VS Code version: 1.80.1
OS version: Windows 10 Pro 10.0.19045
