### ISSUE TITLE
Window not scrolling automatically while searching

### ISSUE THREAD

**Issue by siddharth-krishna** [VSCodeVim/Vim#848]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Pressed `/` and started typing a word that exists in the file, but somewhere after the last visible line.

### What did you expect to happen?

I expected the window to scroll down and show the first match highlighted, and update as I typed more/fewer characters. This used to happen, and is useful to tell whether the word I'm searching for exists in the current file or not.

### What happened instead?

The view stayed at the position where I was before I started searching. It only moves to the first match after pressing Enter.

### Technical details:

* VSCode Version: 1.5.3 (1.5.3)
* VsCodeVim Version: 0.3.0
* OS: OS X 10.10.5

**Comment by rebornix** [comment]
As I can't  repro this issue with the latest release, close it first. Please give it a check.

**Comment by siddharth-krishna** [comment]
I'm still running into this issue, on version 0.3.3 of VsCodeVim and VS Code 1.6.1. I see this behaviour on plain text files, python files, and F# files..

**Comment by rebornix** [comment]
@siddharth-krishna the latest version is 0.3.8. I'm not sure the `0.3.3` is a typo or you still haven't installed the latest one.

**Comment by siddharth-krishna** [comment]
Apologies - for some reason VS Code wasn't showing me an option to update the extension in the extension page so I thought it was the latest version. I had to manually search for the extension and install it again. It works now, thanks!

**Comment by rebornix** [comment]
@siddharth-krishna when you ran into the extension update problem, usually reload the window or restart VS Code can solve it. Glad to see that it works for you now :)
