### ISSUE TITLE
jk --> Esc

### ISSUE THREAD

**Issue by Hope2KZ** [VSCodeVim/Vim#8499]
插入模式下映射 jk --> Esc 之后
使用过程中 总是突然失效 jk没有反应而是突然变成输入字母jk 是哪儿的问题？
遇到这种情况只能重启vscode重新加载配置文件解决  很烦

**Comment by zingxy** [comment]
估计和其它插件冲突了，最近下了`Edge dev tools`这个插件，`jj`也是老是失效。
不知道有没有解决方法？

**Comment by Hope2KZ** [comment]
发现了问题所在 ： 我现在使用两套配置文件，当 “jk-->esc” 只存在于一个文件中时，就会出现jk失效的现象。可能跟配置文件读取优先级有一点关系。
解决方法 ： 将现在使用的配置文件内容复制，放进 “default”默认配置文件中，即可解决
