### ISSUE TITLE
:reg messes with other dropdown options like CMD + T

### ISSUE THREAD

**Issue by pixlhero** [VSCodeVim/Vim#8506]
**Describe the bug**
The Dropdown shown with the `:reg` command messes with other dropdown options like `CMD + T`

**To Reproduce**

1.  Put something in any registers
2.  execute `:reg` (the dropdown appears)
3.  close the dropdown
4.  open the dropdown again with `CMD + T`
5. There's double text/icons.

**Expected behavior**
There shouldn't be overlapping texts.

**Screenshots**
![Screenshot 2023-07-20 at 15 53 59](https://github.com/VSCodeVim/Vim/assets/9341604/b1a2d968-d159-4329-8699-278a67c7fa03)

**Environment:**

- Extension (VsCodeVim) version: v1.25
- VSCode version: v1.80.1
- OS: macOS Ventura 13.1

**Comment by aniki-16x16** [comment]
Same bug
**Environment:**

- Extension (VsCodeVim) version: v1.25.2
- VSCode version: v1.80.1
- OS: macOS Monterey 12.2.1

**Comment by zxf4399** [comment]
Same bug

**Comment by YLonely** [comment]
same bug

**Comment by tangdading6** [comment]
same bug. 
Please....
