### ISSUE TITLE
Mapping capslock to esc has issues

### ISSUE THREAD

**Issue by billti** [VSCodeVim/Vim#854]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Attempted to map the caps lock key to the escape key, via the below in keybindings.json

```json
{"key": "capslock", "command": "extension.vim_escape"} 
```

Note: I also tried via the below, using "capslock" and "\<CapsLock\>", but this had no effect, as it appears from the codebase `<CapsLock>` isn't recognized notation.

```json
{
    "vim.insertModeKeyBindings": [
        {
            "before": ["capslock"],
            "after": ["<Esc>"]
        }
    ]
}
```

### What did you expect to happen?
This should allow me to exit insert mode via the close-by caplock key. 

### What happened instead?
It does kinda work via the first form above, however if also toggles caps lock on/off, which makes it impossible to use (as every key press is then a capital after exiting insert mode). Preferably the "vim.insertModeKeyBindings" would work, and recognize the capslock key and intercept it - preventing it from toggling caps-lock.

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.3.0
* OS: Windows 10

**Comment by jpoon** [comment]
Interestingly, I don't see the `capslock` key being bubbled up into our extension.

**Comment by billti** [comment]
Actually, I just noticed even in Windows this usually requires some system changes via the registry or a utility to work correctly - so maybe it wasn't as simple as I hoped :-/  See http://vim.wikia.com/wiki/VimTip75

**Comment by johnfn** [comment]
Yeah, Vim does not support caps lock mapping. People generally map it with some sort of broader keymapping program.

**Comment by vyorkin** [comment]
for Mac OS X I personally use [Seil](https://github.com/tekezo/Seil) + [Karabiner](https://github.com/tekezo/Karabiner) or [Karabiner-Elements](https://github.com/tekezo/Karabiner-Elements) if you are on Sierra.
you could take a look for this awesome post: http://stevelosh.com/blog/2012/10/a-modern-space-cadet/

**Comment by ljbuza** [comment]
On Linux Gnome desktops, Tweak Tool, under the "Typing" menu, will let you set your cap lock behavior.  Setting it to "Make Caps Lock an additional ESC" works well for me.

**Comment by fkjogu** [comment]
Doing
```
setxkbmap -option caps:swapescape
```
on Linux swaps the `escape` and `caps lock` Xorg wide. But since code 1.11 this extension does not recognise this. To get out of insert mode, I have to press the original `esc` key, which at the same time toggles CAPS. This is really annoying. Might be a problem with code itself?

**Comment by johnfn** [comment]
Would probably be good to test with other parts of VSCode that use an ESC key to trigger something. We don't really have anything to do with capslock binding, unfortunately!

**Comment by areyoureddy** [comment]
It's definitely an issue with VS Code itself. Going back to 1.10 brings back the expected behavior, so it's something in the 1.11 update that's broken it.

**Comment by johnfn** [comment]
@areyoureddy In that case, definitely go open up an issue on their repository then. :)

**Comment by areyoureddy** [comment]
Microsoft/vscode#23991 Already done :+1:

**Comment by Fr4nks** [comment]
Issue resolved
keybindings.json
// Place your key bindings in this file to overwrite the defaults
[ {"key": "capslock", "command": "extension.vim_escape",
                      "when": "editorTextFocus && vim.active && !inDebugRepl" }
]

**Comment by freddie-freeloader** [comment]
@Fr4nks This works for me just well under Linux.

**Comment by lantern77** [comment]
@Fr4nks solution worked for me to, thank.

**Comment by nayzawoo** [comment]
@Fr4nks  Thanks!

**Comment by nazarimilad** [comment]
@Fr4nks First it didn't work. But after adding `"keyboard.dispatch": "keyCode"` in the settings which was suggested as a workaround [here](https://github.com/Microsoft/vscode/issues/23991), it's now working correctly.

VS Code version: 1.14.1

**Comment by kev111** [comment]
@Fr4nks    thank you!

**Comment by HackerDeez** [comment]
@Fr4nks Thanks!

**Comment by Ding-Fan** [comment]
I put this in *keybinds.json*

```js
// Place your key bindings in this file to overwrite the defaults
[
  {
    "key": "capslock", 
    "command": "extension.vim_escape",
    "when": "editorTextFocus && vim.active && !inDebugRepl" 
  }
]
```
And toggle this in *User Settings*

```
"keyboard.dispatch": "keyCode"
```

Now I can use <kbd>caps lock</kbd> as <kbd>esc</kbd> in vim insert mode. **But**
I have to press <kbd>caps lock</kbd> again because it capitalize my letters. 😓

**Comment by Chillee** [comment]
@Ding-Fan I suggest using some kind of external caps lock to escape rebinding program. I use caps2esc on Arch Linux.

**Comment by Ding-Fan** [comment]
@Chillee I'm using Karabiner-Elements on macOS now, it's amazing. 😃

**Comment by mmyoungman** [comment]
In case it is of use to anyone, on macOS, I had set capslock to be escape, and it was previously working fine, but after using setting sync to import my settings, I stopped being able to get out of insert mode. It turned out that `"vim.enableNeovim": true,` was the culprit. I set it to false and everything was fine again.

**Comment by janhesters** [comment]
On Mac you can also disable capslock like this: https://heresthethingblog.com/2014/02/05/mac-tip-disable-caps-lock-key/

**Comment by Gesmir** [comment]
On Fedora 29 I just needed to change an option in the Settings (File > Preference > Settings).

Keyboard: Dispatch "keyCode"

**Comment by bergmul** [comment]
> @Ding-Fan I suggest using some kind of external caps lock to escape rebinding program. I use caps2esc on Arch Linux.

I'm also using caps2esc and it works fine everywhere but in code. Sometimes it works for a couple of minutes, then pressing capslock does not trigger esc anymore.

**Comment by nataprawiraf** [comment]
> Issue resolved?
> keybindings.json
> // Place your key bindings in this file to overwrite the defaults
> [ {"key": "capslock", "command": "extension.vim_escape",
> "when": "editorTextFocus && vim.active && !inDebugRepl" }
> ]
> 
> Ubuntu 16.04, VS Code 12.2.2
> Doesn't work correctly in window 10.

works on ubuntu

**Comment by seanwarman** [comment]
If anyone's wondering, as I had a problem finding keybindings.json through the vscode UI, it's in `~/.config/Code/User/`.

**Comment by seanwarman** [comment]
If anyone's wondering, as I had a problem finding keybindings.json through the vscode UI, it's in `~/.config/Code/User/`.

And you can find some docs about it in [VSCode's Docs](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules)

**Comment by mjarkk** [comment]
@seanwarman In vscode you can get to the keyboard shortcuts using:  
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> and type `Open Keyboard Shortcuts (json)`

**Comment by Christopher-Hayes** [comment]
For Windows users, after realizing how difficult it would be to implement with VS code settings, I found just changing the registry to be much easier and less finnicky. This same guide shows how to do it with various tools like AHK too. https://vim.fandom.com/wiki/Map_caps_lock_to_escape_in_Windows

**Comment by bradleysawler** [comment]
Win10 I had a similar issue as others by having to 2nd press the cap lock to turn the cap lock back off. So I decided to just map CapLock + CapLock. So a double caps `Esc` and turns the caps back off.

**Comment by Mhmdrza** [comment]
ctrl + {
Activates the normal mode

**Comment by SSmJaE** [comment]
I found a perfect way to map caps lock to ESC on Windows 10 ("keyboard.dispatch": "keyCode" doesn't take effect), and only works in VS Code, has no effect on other programs like games

Using AutoHotkey
here is the code
```ahk
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
SetTitleMatchMode, 2

#IfWinActive, Visual Studio Code
CapsLock::Escape
ScrollLock::CapsLock      
```

**Comment by whale124** [comment]
> > @Ding-Fan 리바인딩 프로그램을 피하기 위해 일종의 외부 캡 잠금을 사용하는 것이 좋습니다. 저는 아치 리눅스에서 caps2esc를 사용합니다.
> 
> 나는 또한 caps2esc를 사용하고 있으며 코드를 제외한 모든 곳에서 잘 작동합니다. 때로는 몇 분 동안 작동한 다음 capslock을 눌러도 더 이상 esc가 실행되지 않습니다.
> 
> **편집:** 사용자 구성에 추가 `"keyboard.dispatch": "keyCode"`하면 문제가 해결됩니다. @Fr4nks 감사합니다 .



> > @Ding-Fan I suggest using some kind of external caps lock to escape rebinding program. I use caps2esc on Arch Linux.
> 
> I'm also using caps2esc and it works fine everywhere but in code. Sometimes it works for a couple of minutes, then pressing capslock does not trigger esc anymore.
> 
> **EDIT:** Adding `"keyboard.dispatch": "keyCode"` to user configs solves the problem. Thank you, @Fr4nks.

It works in my Ubuntu!
Thank you

**Comment by bnpysse** [comment]
> I put this in _keybinds.json_
> 
> ```js
> // Place your key bindings in this file to overwrite the defaults
> [
>   {
>     "key": "capslock", 
>     "command": "extension.vim_escape",
>     "when": "editorTextFocus && vim.active && !inDebugRepl" 
>   }
> ]
> ```
> 
> And toggle this in _User Settings_
> 
> ```
> "keyboard.dispatch": "keyCode"
> ```
> 
> Now I can use caps lock as esc in vim insert mode. **But** I have to press caps lock again because it capitalize my letters. sweat

How to do changing twice to one?
