### ISSUE TITLE
transform lower case to upper case

### ISSUE THREAD

**Issue by yuThomas** [VSCodeVim/Vim#8550]
hello, i wanna transform lower case to upper case in replacemode, but it doesn't work,. am i using wrong?

example text:
 abcdef

replace mode command:  %s/(.*)/\U\1/g

expect: ABCDEF
actual: abcdef

**Comment by dreaming12** [comment]
In nominal mode, press `~`. In visual mode, select and enter `U` for upper, and `u` for lower.

If you want to use a cmd: [Changing case with regular expressions](https://vim.fandom.com/wiki/Changing_case_with_regular_expressions)
