### ISSUE TITLE
Extension messes with VS Codes 'Go to defintion'

### ISSUE THREAD

**Issue by alnorris** [VSCodeVim/Vim#856]
### What did you do?

Used the goto definitions built in VS Code

### What did you expect to happen?

Go to the correct definition line

### What happened instead?

Goes to an old definition or random lines with in the correct file, when VS Vim extension is install, when uninstall it goes to the correct line every time. (Peek definition however works correctly.)

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.30
* OS: OSX El Capitan

**Comment by jpoon** [comment]
I can't repro this. I have open our extension source code (TS), right click, go to definition, it goes to the proper definition.

* Are you using a keyboard shortcut? 
* What sort of file/folder do you have open? What language?

**Comment by johnfn** [comment]
This has been fixed!
