### ISSUE TITLE
Cursor position with `Foldfix` enabled is broken as of `v1.26.0` update

### ISSUE THREAD

**Issue by ktvdev** [VSCodeVim/Vim#8576]
**Describe the bug**
Using "native" keyboard navigation of `CTRL+<arrow-key left/right>` to jump to beginning end of a word is now broken. 

This happens after vim enters a "broken state". If you then jump forward a word using `ctrl+right` or backward using `ctrl+left` then try to navigate using `left` or `right`, the cursor jumps back to its position before using `ctrl+arrow-key`. The console reports `[warning] Ignoring slipped selection: [n, n; n, n]`. Same for using `Home` or `End`. Other navigation could also be impacted but I mostly use the ones I mentioned.

Upon further testing VIM appears to enter the "broken state" consistently when moving the cursor between lines of difference length, but only at the end of the line.

Toggling VIM off then on fixes the behavior until navigating over the last character of a foldable region (even if it is unfolded).

Disabling `Foldfix` resolves the issue as does reverting to `v1.25.2` with `Foldfix` still enabled.

**To Reproduce**

1.  Enable `Foldfix` (`"vim.foldfix": true`)
2.  Move cursor up/down between lines of same length = ok
3. Move cursor up/down between lines of different length but not at the end of the line = ok
4. Move cursor up/down between lines of different length at the end of the line = enters "broken state"
5. Notice console log of `[warning] invalid cursor position. [n:n | n:n]` followed immediately by `[warning] Ignoring slipped selection: [n, n; n, n]`
7. Try navigating using `ctrl+arrow` or `home`/`end`
8. Notice console log of `[warning] Ignoring slipped selection: [n, n; n, n]` every time you do
9. Try navigating using `arrow-key` either left or right
10. Notice the cursor does not behave as expected
11. Restart vim using `toggleVim` then `toggleVim` again
12. Perform the same movement using `ctrl` or `home`/`end` followed by `left`/`right`
13. Notice the behavior is back to normal and no warning logs in console

**Expected behavior**
It's as if the cursor position is not updated properly when in the "broken state" and using `ctrl` or the other ones.

So if my cursor position is at column 3, then I jump to the end of the next word which puts me at column 10, when I hit `right` arrow I expect the cursor to move to col 11 but it instead moves to col 4.

**Screencasts**

---
*Example 1 - Normal behavior then entering "broken state"*

https://github.com/VSCodeVim/Vim/assets/75916477/2d2a984e-7d48-4440-a413-8bb84bc86613

---
*Example 2 - `Invalid cursor position` + `Ignoring slipped selection` when navigating around bracket (?)*

https://github.com/VSCodeVim/Vim/assets/75916477/8ee2a38b-db15-450d-b689-c0ce07423077

---

*Example 3 - Issue is fixed after restarting VIM (I have `alt+v` mapped to do this)*

https://github.com/VSCodeVim/Vim/assets/75916477/521a1754-da68-4c96-9527-51c4e9d7a5b9

---

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: `1.26.0`
- VSCode version: `1.82.0`
- OS: `Windows`, `Browser (Vscode.dev)`

**Additional context**
I have not tested this behavior with VIM handling of arrow keys disabled.

**Comment by 55Cancri** [comment]
I am seeing the same issue. In my case, I am using the Jump2 plugin and when I jump to another word, I get the log "Ignoring slipped selection" in the vscode vim output, then it goes back to the place before jumping.

**Comment by HenryTSZ** [comment]
It's because of this PR（ https://github.com/VSCodeVim/Vim/pull/8533/files ）This file (src/mode/modeHandler. ts) has been modified, so just remove this code

**Comment by Sheepolution** [comment]
This issue is driving me crazy. I've gone back to version 1.25.2, but I am still experiencing this. What is the latest version that does not have this issue? All  versions after 1.25.2 seem to have it.

**Comment by ArazEstPrit** [comment]
A few months late, but the issue is still present on version 1.29.0. It looks like it works fine on version 1.28.1 though.

**Comment by Sheepolution** [comment]
I made a similar issue, where the cause is scrolling down very fast. The solution might be the same though. #9142
