### ISSUE TITLE
How to quit Visual mode after commenting multi lines 

### ISSUE THREAD

**Issue by a1ivewu** [VSCodeVim/Vim#8579]
It will keep staying in `visual` mode after commenting with following keybindings.

```
  "vim.visualModeKeyBindings": [
    { "before": ["leader", "/"], "commands": ["editor.action.commentLine"] }
  ]
```

I'd like to know how to quit `visual` mode after commenting multi lines.

**Comment by luooofan** [comment]
Hello, how did you solve it in the end?
