### ISSUE TITLE
Cursor location problem when using with Auto Close Tag

### ISSUE THREAD

**Issue by guivho** [VSCodeVim/Vim#858]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
I enter a <div> in a js file

Put the exact keys you pressed.
<div>

### What did you expect to happen?
(Note that | indicates the expected cursor location)
<div>|</div>

### What happened instead?
<div></div>|

### Technical details:

* VSCode Version: 1.5.3
* VsCodeVim Version: 0.3.3 *[please ensure you are on the latest]*
* OS: Widows 10 Insider Preview 1607
* Auto Close Tag version: 0.3.0

Note that this is a reappearing bug imho. The previous version of vscodevim behaved as expected. At least this time there is no discrepancy between the physical cursor location and where the extension thinks it is located. Some vscodevim versions back had the current erroneous behavior together with cursor location confusion, which was much worse.

Still, it is a pity that the cursor does move to the end of the closing tag, rather than stay where it was.

I do realize that this may be a problem of the Auto Close Tag extension, but this unfortunate behavior reappeared after updating vscodevim to the latest version...

**Comment by xconverge** [comment]
related to #789 I think

**Comment by xconverge** [comment]
@guivho Can you verify this is fixed in the latest?

**Comment by guivho** [comment]
Yep, works like a charm
Thanks!
