### ISSUE TITLE
Cursor moves back while typing in insert mode

### ISSUE THREAD

**Issue by obayit** [VSCodeVim/Vim#8604]
**Describe the bug**
While I am typing, the cursor moves backward on its own and messes up the words, you can see it in [this video](https://youtu.be/uyCI9lIjUvo) (the cursor should stay at the end of the line, but instead it moves back slowly and ends up in the middle).

I noticed that this issue happens after I sync my settings from github account, it happened before, I had to do a fresh install.

**To Reproduce**
I don't know how

**Expected behavior**
Cursor should not move

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.26.0
- VSCode version: insiders 1.82
- OS: Ubuntu 20.04.6 LTS

**Comment by MstchCmBck** [comment]
Same issue but on a Windows 10.0.19045. It makes VSCodeVim completely unusable.

**Comment by obayit** [comment]
Thanks @MstchCmBck glad to know I am not the only one facing this frustrating issue
