### ISSUE TITLE
Fast `Esc` + `hjkl` is not working properly, when autoSwitchInputMethod is enabled

### ISSUE THREAD

**Issue by rustyhu** [VSCodeVim/Vim#8608]
**Describe the bug**
I am also a Chinese IME user with `autoSwitchInputMethod` enabled, and have been annoyed by #7022 for a long period (Thank you very much #8328) and I have updated to v1.26.0 happily. I find that when to quit the InsertMode with typing `Esc`  fast followed (nearly simultaneously) by anyone of `hjkl` move, the text will be modified improperly. 

**To Reproduce**

1. Set `"vim.autoSwitchInputMethod.enable" : true`;
2. Enter InsertMode at some text, and turn on IME;
3. Type `Esc` fast followed (nearly simultaneously) by anyone of `hjkl` move;
4. See text near the cursor modified improperly;
5. If type `Esc` slowly followed by move, or IME is turned off, it works normally.

**Expected behavior**
No text modified, only quit the InsertMode and cursor move.

**Screenshots**
![图片](https://github.com/VSCodeVim/Vim/assets/3363383/f1f0f1fa-f0c4-4c04-85cd-f3a9b234bc2a)

After fast typing `Esc`+ anyone of `hjkl`:
![图片](https://github.com/VSCodeVim/Vim/assets/3363383/7bc5d67b-4a5a-4686-b91b-540016672ea5)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.26.0
- VSCode version:
Version: 1.78.2 (system setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by mykter** [comment]
This might be #8603

**Comment by rustyhu** [comment]
This seems not to appear any more here after I updated to v1.26.1.
