### ISSUE TITLE
Ergodox Tap/Hold key misregistering on version 1.26.0

### ISSUE THREAD

**Issue by cTurnerEnvAU** [VSCodeVim/Vim#8611]
**Describe the bug**
When in insert mode, keystrokes following dual function keys (eg. https://github.com/qmk/qmk_firmware/blob/master/docs/tap_hold.md) are not being registered. I use an ergodox EZ with home row modifier keys: holding `s`/`l` yields control, `d`/`k` alt and `f`/`j` the windows key. This leads to typos such as `form` -> `frm`, `site` -> `ste`, etc.

I have not tested for the bug on other qmk keyboards. However, I have tested a wide range of hardware settings, and I am reasonably sure this is not a hardware info.

Rolling back vscodevim to version 1.25.2 resolves the issue.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.26.0 
- VSCode version: 1.82.2
- OS: WSL Ubuntu 22.04

**Additional context**

**Comment by kfriend** [comment]
@cTurnerEnvAU might be the same issue as #8603. I had a similar issue with my keyboard (different keyboard, similar modifier setup), but it was also happening on non-modifier keys.

**Comment by cTurnerEnvAU** [comment]
@kfriend I suspect it is. I'll close this issue and move it to a comment in #8603.

I've definitely noticed that the keystrokes misregistering was only an issue for me after dual function keys. Hopefully that provides some extra context for tracking down the bug.
