### ISSUE TITLE
Hover ( show definition ) with shift+k

### ISSUE THREAD

**Issue by huyhoang8398** [VSCodeVim/Vim#8623]
**Describe the bug**
Hovering keyboard shortcut is not working

**To Reproduce**

1. Config vscode vim keybind:
```
        {
            "before": [
                "shift",
                "k"
            ],
            "command": [
                "editor.action.showHover"
            ]
        }
 ```

**Expected behavior**
when in Normal mode, press shift+k will pop up hover

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.26.0
- VSCode version:
```
1.82.2 
abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
x64
```
- OS: Ubuntu 22.04

**Additional context**
I know that we could use gh to hover, but since I came from vim user so shift+k is familiar to me

**Comment by huyhoang8398** [comment]
My fault, should use capital "K"
```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "K"
            ],
            "commands": [
                "editor.action.showHover"
            ]
        },
    ],
   ```

**Comment by yamanidev** [comment]
aren't they equivalent?
