### ISSUE TITLE
Insert mode swallows keypresses that happen very fast after another

### ISSUE THREAD

**Issue by quexten** [VSCodeVim/Vim#8633]
**Describe the bug**
Insert mode swallows keypresses that happen at the same time.

**To Reproduce**
My keyboard is running zmk firmware with hold-tap behaviour. This means that, when pressing a hold-tap key and then a regular key very fast after another, the keys are sent to the operating system at the same time. Here is a screenshot of `wev` showing the keyboard events:
![image](https://github.com/VSCodeVim/Vim/assets/11866552/b69e8e50-f710-4976-a9aa-e4d023dc9a2a)

For these key pairs that are emitted at the same time, only the first keypress ("a") gets recognized and printed in insert mode.
This can also (more rarely) happen with regular, non-hold-tap keys when they are pressed very fast after another.

```
/// hold-tap then regular key (DOESN'T WORK, r SWALLOWED)
[14:     wl_keyboard] key: serial: 41314; time: 19965766; key: 38; state: 1 (pressed)
                      sym: a            (97), utf8: 'a'
[14:     wl_keyboard] key: serial: 41315; time: 19965766; key: 27; state: 1 (pressed)
                      sym: r            (114), utf8: 'r'
[14:     wl_keyboard] key: serial: 41316; time: 19965766; key: 38; state: 0 (released)
                      sym: a            (97), utf8: ''
[14:     wl_keyboard] key: serial: 41317; time: 19965766; key: 27; state: 0 (released)
                      sym: r            (114), utf8: ''

/// hold-tap then hold-tap key (DOES WORK)
[14:     wl_keyboard] key: serial: 41318; time: 19969742; key: 28; state: 1 (pressed)
                      sym: t            (116), utf8: 't'
[14:     wl_keyboard] key: serial: 41319; time: 19969742; key: 28; state: 0 (released)
                      sym: t            (116), utf8: ''
[14:     wl_keyboard] key: serial: 41320; time: 19969742; key: 43; state: 1 (pressed)
                      sym: h            (104), utf8: 'h'
[14:     wl_keyboard] key: serial: 41321; time: 19969742; key: 43; state: 0 (released)
                      sym: h            (104), utf8: ''

/// regular key then regular key (DOESN'T WORK, G SWALLOWED)
[14:     wl_keyboard] key: serial: 41322; time: 19991914; key: 54; state: 1 (pressed)
                      sym: c            (99), utf8: 'c'
[14:     wl_keyboard] key: serial: 41323; time: 19991914; key: 42; state: 1 (pressed)
                      sym: g            (103), utf8: 'g'
[14:     wl_keyboard] key: serial: 41324; time: 19991914; key: 54; state: 0 (released)
                      sym: c            (99), utf8: ''
[14:     wl_keyboard] key: serial: 41325; time: 19991914; key: 42; state: 0 (released)
                      sym: g            (103), utf8: ''
```

**Expected behavior**
In other text fields in vscode, other editors in general, and vim in a command line, the keypresses get recognized correctly.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.26.0
- VSCode version: 1.82.2
- OS: Fedora 39

**Additional context**

**Comment by quexten** [comment]
Also noting that this does not happen with vscode-neovim.

**Comment by levi-wj** [comment]
+1, something happened recently that caused insert mode to drop characters and even type them out of order. This makes the plugin completely unusable.

I'm not familiar with hold-tap behavior but I'm able to consistently reproduce this on a Lenovo legion 5 laptop keyboard.

**Comment by skejeton** [comment]
+1

**Comment by wumb0** [comment]
Experiencing this also. Downgrading to v1.25.2 solves the issue for me. Latest vscode on windows 10. On a host, not in a VM. Plenty of RAM and CPU. No other plugins.

**Comment by linyanm** [comment]
+1 I encountered the same incident. Maybe caused by vim plugin

**Comment by littlemoses** [comment]
+1 Switching to the neovim plugin for now. Please fix this.

**Comment by juliangroen** [comment]
+1 Experiencing the same issue when just typing quickly, no keyboard macros or anything like that.

Just did a complete re-install of VSCode and tested with no other extensions installed and the issue remains.

**Comment by trusktr** [comment]
I can confirm that this happens, but it seems to happen if the CPU is bogged down. If my CPU is clear and operating quickly for VS Code, I tend to not get this problem. But if I have some program(s) bogging down my system, then this will happen often in VS Code, and it'll get really annoying.

For example, if I type `hello` the output might actually be `heeohhlh`, which is completely wrong.

**Comment by dannoe** [comment]
Is this fixed by #8622?

**Comment by trusktr** [comment]
Just got 1.26.1. Will test it for a day to confirm

**Comment by quexten** [comment]
Seems fixed for me on v1.26.1

**Comment by trusktr** [comment]
I haven't experienced this today either.

**Comment by pazoozooCH** [comment]
This was driving me crazy! I also thought it was some incompatibility with other plugins.
After a quick test, doesn't seem to happen anymore with *v1.26.1* 👍
