### ISSUE TITLE
Unintended characters are entered when entering Hangul

### ISSUE THREAD

**Issue by kanghyojun** [VSCodeVim/Vim#8640]
**Describe the bug**

Unintended characters are entered when entering Hangul. It puts more characters that i didn't typed.

**To Reproduce**

1.  Create New file
2. Hit i, Enter Hangul "가나다라마"
3. Step 2 result is "나가나다라다라마"

**Expected behavior**

Step 2 result should be "가나다라마"

**Screenshots**

https://github.com/VSCodeVim/Vim/assets/95910/e9525b99-948d-4009-89be-0f2115b68cea

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.26.0
- VSCode version: 1.82.1
- OS: macOS 13.4.1

**Comment by parkjurung** [comment]
The issue began starting from version 1.26.0. There were no problems up to version 1.25.2.

**Comment by parkjurung** [comment]
https://github.com/VSCodeVim/Vim/issues/8570

**Comment by J-Fields** [comment]
This should be fixed in v1.26.1

**Comment by kanghyojun** [comment]
@J-Fields @parkjurung Thanks for helping!
