### ISSUE TITLE
Substitute backreferences not working

### ISSUE THREAD

**Issue by Agent-E11** [VSCodeVim/Vim#8655]
**Describe the bug**
When substituting text, I am unable to use backreferences to the selected text.

**To Reproduce**

1. Place cursor on a line containing `This is "some" text`
2. Type this substitution command: `:s/"\(.*\)"/awe\1`
Nothing will happen

**Expected behavior**
When typing the command, `"some"` should be replaced with `awesome`

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.26.0
- VSCode version: 1.83
- OS: Windows 11

**Comment by EnricoSteez** [comment]
In vscode you don't need to escape the parentheses. Just use `:s/"(.*)"/awe\1`.

**Comment by Agent-E11** [comment]
@EnricoSteez Ok, it does work. Why is it like this though? Why not make it identical to Vim?

**Comment by dannoe** [comment]
see https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#pattern-searches in the "Notes" column

Probably because the regex engine would have to be re-implemented, and that's probably not so easy and quick to do.
