### ISSUE TITLE
Repeat last command not working

### ISSUE THREAD

**Issue by Knaackee** [VSCodeVim/Vim#8659]
**Describe the bug**

"Repeat last command" which is on the "." (dot) key doesnt work. The "," (comma) command does work.
I cant see any keybinding for the ".".

Maybe i broke my config but i dont know how to fix it. 

**To Reproduce**

1. Create a new file with the content "This is a test."
2. Cursor to first position
3. Press f to find
4. Press "i" to find the first occurrence of the letter "i".
5. Press "." do jump to the next occurrence.

**Expected behavior**
The cursor should jump to the next occurrence. 

- Extension (VsCodeVim) version: 1.26.1
- VSCode version: 1.83.0
- OS: Windows 11

**Additional context**
I searched a lot but could find an answer.

**Comment by dannoe** [comment]
To repeat the last ``f`` you have to press ``;``
see https://vimhelp.org/motion.txt.html#%3B

**Comment by Knaackee** [comment]
Isnt "," for previous occurence ?

**Comment by Knaackee** [comment]
Thanks for your comment! But ";" does not work.

**Comment by dannoe** [comment]
It does work for me. ``;`` is repeating the search forward and ``,`` is repeating the search backwards.

You can try posting your settings in the hope that someone will spot the problem.

**Comment by Knaackee** [comment]
The problem was

1. I thought that "," should go back 
2. I had a wrong keybinding for "shift+,". 

Thanks for your help!
