### ISSUE TITLE
Cannot use mouse selection after entering INSERT MODE

### ISSUE THREAD

**Issue by wangadong** [VSCodeVim/Vim#866]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Cannot use mouse or CMD+D to do selection after entering INSERT MODE

### What did you expect to happen?
Text selected 
### What happened instead?
Only cursor is moving but no text selected
### Technical details:

* VSCode Version: 1.5.3 
* VsCodeVim Version: 0.3.3
* OS: macOS Sierra

**Comment by xconverge** [comment]
I want to add that selection works fine in normal mode though

**Comment by johnfn** [comment]
This is no good.

**Comment by johnfn** [comment]
Apparently I fixed this with 9628c185af9faf4f1ed01a7730b75c04081d1b16.
