### ISSUE TITLE
Split editor/file editing broken

### ISSUE THREAD

**Issue by jeffschwartz** [VSCodeVim/Vim#868]
### What did you do?
Split an editor/file for editing in 2 panes.
Put the exact keys you pressed.
"cmd\" 
### What did you expect to happen?
Editing in split pane editor should work like editing in non split pane editor.
### What happened instead?
Cursor behaves erratically in insert mode - key presses are ignored, transposed or eat previous key presses.
### Technical details:
* VSCode Version:
VSC v1.5.3
* VsCodeVim Version: *[please ensure you are on the latest]*
v0.3.3
* OS: 
Mac OS X v9.5

**Comment by xconverge** [comment]
Are you sure that this is only when using split editor? I am pretty sure this happens when not using a split editor sometimes as well (obviously bad, just trying to figure out if the split editor part is related)

**Comment by jeffschwartz** [comment]
@xconverge your suspicion is correct, it isn't only limited to when editing in a split editor. Also, and maybe I should file a separate issue, but I also notice that the plugin appears to clobbering undo when using "u" in normal mode.

**Comment by johnfn** [comment]
I can't reproduce this. Can you, @xconverge?

**Comment by johnfn** [comment]
Reproduced it.

**Comment by jeffschwartz** [comment]
Most awesome. Thank you!!!
