### ISSUE TITLE
Unable to use arrow key to navigate through quick fix options

### ISSUE THREAD

**Issue by wenqiangwang** [VSCodeVim/Vim#869]
### What did you do?
When I have a code issue in a C# file, I pressed 'ctrl+.' to bring up the quick fix window. I want to use arrow key to navigate to the second quick fix option. But when I press the Down key, the cursor moved to the next line and the quick fix windows got closed.

Put the exact keys you pressed.
1. Ctrl+. 
2. Down

### What did you expect to happen?
I expect the second quick fix option selected

### What happened instead?
The quick fix window closed and the cursor moved to next line.

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: *[please ensure you are on the latest]* 0.3.3
* OS: Windows Server 2012 R2

**Comment by rebornix** [comment]
I don't see this issue any more in latest release 0.3.8. `Ctrl+.` and then arrow keys work well.
