### ISSUE TITLE
Can mouse click past the EOL

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#874]
You can mouse click past EOL, which puts the cursor after the last char.

However, when you press x, the cursor moves 2 character positions and removes the last char instead of the EOL.

I would expect you to not be able to click past the last char. hjkl/arrow keys don't let you go past the last char in normal mode.

**Comment by johnfn** [comment]
Yeah, I broke this intentionally in order to fix a number of other bugs. Might be tricky to completely fix.

**Comment by xconverge** [comment]
This should be revisited now that handleSelectionChanged is not making it as far in most cases...

**Comment by rebornix** [comment]
@xconverge this is caused by our hack of EOL to mimic Vim and it shares the same root cause with #574 . I moved your description there and let's track it there.
