### ISSUE TITLE
Command :vs results in opening a new "Untitled-1" file

### ISSUE THREAD

**Issue by windless0530** [VSCodeVim/Vim#8745]
**Describe the bug**
When command `:vs` is run, current file is splitted into the new window, for only a blink of an eye, and the new window replaced by an empty file named "Untitled-1".

**To Reproduce**

1. Run the `:vs` command
2. Current file be vertically splitted, into a new window
3. Immediately (possibly less than 0.2 second after the file was splitted) the new window replaced by an empty file named "Untitled-1".

**Expected behavior**
Current file be vertically splitted.

**Screenshots**
The very first moment after running the `:vs` command, which was expected, but last for less than 0.2 second, which makes this screenshot a bit difficult to capture:
![1](https://github.com/VSCodeVim/Vim/assets/4645959/3a127afb-e9cd-41dc-a07b-17f3c9c77b5f)

Then immediately...
![2](https://github.com/VSCodeVim/Vim/assets/4645959/dd89e1dc-3371-45f4-b1f8-2a1712580c57)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.27.0
- VSCode version: v1.84.1 (Universal)
- OS: macOS Sonoma 14.1.1

**Additional context**
Code is installed on MacBook Pro with M1 Pro, and the codes were located on a remote Ubuntu 20.04 server, attached by Remote-SSH plugin.
Github Copilot is also enabled.
This bug came up not for long. Everything kept running perfectly before about a week ago, on earlier versions of both Code and all its plugins.

**Comment by wyl8899** [comment]
Experiencing this too right now, everything was fine several days ago.

* Extension (VsCodeVim) version: v1.27.0
* VSCode version: 1.84.2 (Universal)
* OS: macOS Monterey 12.0.1

**Comment by shivamidow** [comment]
I am also here to report this issue. This is happening after the last extension update.

**Comment by castlewu** [comment]
I had the same problem.

1.84.2 (Universal)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by pimpeters** [comment]
I have the same bug, even with CoPilot disabled.
Switching back to the older version of the Vim plugin seems to resolve it.

- Extension (VsCodeVim) version: v1.27.0
- VSCode version: 1.84.2 (Universal)
- OS: macOS BigSur 11.7.9

**Comment by windless0530** [comment]
Update: this bug seems to have been fixed on latest v1.27.1. 

![image](https://github.com/VSCodeVim/Vim/assets/4645959/5dcabefe-be91-4e7a-a339-2cdebef393de)

At least it works well now on my machine.

**Comment by shivamidow** [comment]
Confirmed. Thanks for fixing it!
