### ISSUE TITLE
Actions are not being queued by TaskQueue

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#875]
Easiest way to see this is to rapidly press `o<tab>` somewhere like where the `|` is here:

```
function myFunction(){
    blah();
|
    foo();
}
```

It should open up a new line and then indent to the level of `foo`, but for some reason the `<tab>` key is not triggering.

**Comment by johnfn** [comment]
Research: The reason that this happens is that the order of events are like this:

```
<- [ User presses o. Async stuff is launched ]
<- [ User presses tab. "when" in package.json checks to see if we're in insert mode - we aren't, so we ignore the tab ]
<- [ Async stuff finishes. We are now in insert mode. ]
```

This seems tricky...

**Comment by jgoz** [comment]
On Windows, this actually inserts the word `<tab>` into the document.

![otab](https://cloud.githubusercontent.com/assets/132233/19320757/c9c5f8f8-906f-11e6-8fbe-4196a7ec50dd.gif)
