### ISSUE TITLE
Holding down ~ does not capitalise characters in sequence

### ISSUE THREAD

**Issue by grahame** [VSCodeVim/Vim#876]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Hold down `~` while over a word (outside of insert mode)

### What did you expect to happen?

 - The character the cursor is over should have its case inverted.
 - The cursor should move one character right.
 - The next character should have its case inverted.
 - Repeat until `~` is released.

### What happened instead?

 - The character the cursor is over has its case inverted.
 - The cursor moves one character to the right
 - The **previous** character has its case inverted; the cursor does not move to the right
 - The cursor moves one character to the right
 - The character the cursor is over has its case inverted.
 - Repeat until `~` is released.

Effectively this scrambles the case, swapping case of half of the letters.

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.5
* OS: Linux

**Comment by johnfn** [comment]
Ah yeah, looks like holding down ~ is not running on every character. 

Yay, race conditions!...

**Comment by grahame** [comment]
I could have sworn it worked before, but I'm not 100% sure - I moved across from vim a month or so ago, and I do use this a fair but so I'd think I'd have noticed it. Thanks for having a look :)

**Comment by johnfn** [comment]
This has been fixed... somehow.
