### ISSUE TITLE
Pressing 'k' after pasting a line jumps up two lines

### ISSUE THREAD

**Issue by grahame** [VSCodeVim/Vim#877]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

In python mode:

 - Yank (`yy`) a line.
 - Move to somewhere else in the file
 - Press `p` to paste
 - Press `k` to go up a line

### What did you expect to happen?

 - Cursor x offset should be preserved, and move up one line

### What happened instead?

 - Cursor moves the beginning of line
 - Cursor moves up two lines

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.5
* OS: Linux

**Comment by grahame** [comment]
I've just noticed that pressing `j` to move down after `p` to paste has a similar bug; the cursor doesn't move down, it moves to beginning of the current line.

**Comment by johnfn** [comment]
This is fixed on master!
