### ISSUE TITLE
Go to References results in "ListError [ReferencesWidget] Invalid index"

### ISSUE THREAD

**Issue by HenryTSZ** [VSCodeVim/Vim#8771]
**Describe the bug**

In VS Code, Whenever I go to some code through Reference Widget, The error occur and notified the message. This error message is notified when only I use "l" key on Reference Widget with vim extension

**To Reproduce**

Add the following code to a js or ts file

```js
function foo() {}
foo()
foo()
```

Put the cursor on the definition of foo and run the "gd" command. A list of 3 references should appear. Select any of the references with the "j/k" on the keyboard, then press "l". You'll see an error message pop up saying "ListError [ReferencesWidget] Invalid index".

**Expected behavior**
no error message

**Screenshots**
![image](https://github.com/VSCodeVim/Vim/assets/55341525/9c73dff2-76e4-4136-8675-460c6884e005)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.27.1
- VSCode version: 1.85.0 (user setup)
- OS: Windows_NT x64 10.0.19045

**Additional context**
no

**Comment by zo-ly** [comment]
I have also encountered this problem.

Environment:
- Extension (VsCodeVim) version: v1.27.1
- VSCode version: 1.85.0 (Universal) 
- OS: macOS 13.1 (22C65)

https://github.com/VSCodeVim/Vim/assets/16372524/0a248cf7-590b-4f83-a8e4-f3f69b9adc3a

**Comment by arvandmoe** [comment]
I have the same issue with the same setup.

**Comment by HenryTSZ** [comment]
@J-Fields May I ask if you know where this related code is located?

**Comment by HenryTSZ** [comment]
This issue is related to vscode: https://github.com/microsoft/vscode/issues/202120
