### ISSUE TITLE
In visual mode, '$' will move cursor to next line.

### ISSUE THREAD

**Issue by rogeryk** [VSCodeVim/Vim#8774]
**Describe the bug**
Use 'v' to enter visual mode, then press '$', the cursor will move to next line.

**To Reproduce**
```json
{
  "vim.visualModeKeyBindingsNonRecursive": [
    {
      "before": ["J"],
      "|commands": ["editor.action.smartSelect.expand"]
    },
    {
      "before": ["K"],
      "commands": ["editor.action.smartSelect.shrink"]
    }
  ],
}
```
This is a example, the '|' is cursor position.
1. press 'v' enter visual mode.
2. press '$', cursor will move to next line.
3. press 'd'

**Expected behavior**
Only current line content will be deleted..

**Screenshots**
![Kapture 2023-12-11 at 16 46 33](https://github.com/VSCodeVim/Vim/assets/28089185/2c465b7c-f25f-42a2-b2c8-64948195cbf9)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.27.1
- VSCode version: 1.85.0
- OS: macOS

**Comment by rogeryk** [comment]
This doesn't seem to be a problem, this behavior is consistent with vim's behavior, as mentioned in #3970.

**Comment by philipmagnusson** [comment]
No this is not consistent. In vim it moves to the end of the line in vim for vscode it moves to the start of the next line.

**Comment by darianmorat** [comment]
> No this is not consistent. In vim it moves to the end of the line in vim for vscode it moves to the start of the next line.

It's a visual problem. When using `$` it behaves as it should, cause if you delete that line it should also remove the next one (you can try it in vim/nvim. It's the same behavior). BUT, It should LOOK like the way it does when using `g_`. And YES, it's a bit annoying, if I can find a workaround I would leave a comment here.
