### ISSUE TITLE
cmd + D selection is not accurate

### ISSUE THREAD

**Issue by wangadong** [VSCodeVim/Vim#878]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

When using cmd+d to select words, it will select one more char besides the word you want to select.
Then use `d` to delete, it will delete one more char. It's not same behavior like when you double click the word.

### What did you expect to happen?
Only select the actual word as same as double clicking the word. 
### What happened instead?
Selected one more char after the word
### Technical details:

*VSCode Version: 1.6.0
*VsCodeVim Version: 0.3.5
*OS: macOS Sierra

**Comment by johnfn** [comment]
You can just press `l` though.

**Comment by wangadong** [comment]
@johnfn you mean `h`? It's just not right by intuition.

**Comment by johnfn** [comment]
Yeah, I meant `h`. I see what you're saying, though... It is annoying.
