### ISSUE TITLE
Cannot use backspace to delete selected text in INSERT MODE

### ISSUE THREAD

**Issue by wangadong** [VSCodeVim/Vim#879]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Enter INSERT MODE, use mouse to select text, then press Backspace to delete the text

### What did you expect to happen?
All selected text should be deleted
### What happened instead?
Only deleted the last character 
### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.5
* OS: macOS Sierra

**Comment by andlrc** [comment]
If anything then selecting text with the mouse should enter visual mode, where backspace should shrinl the selection by one character.

**Comment by wangadong** [comment]
hi @andlrc maybe I was indulged by Sublime vi mode. But I do think that is more intuitive behavior.

**Comment by andlrc** [comment]
What you want is something called select mode. You can toggle between select mode and visual mode with `<C-g>`. At least in vim it works like that.

**Comment by xconverge** [comment]
@andlrc in MacVim, you can do what @wangadong is suggesting, I think it is fair the way he wrote it, and I agree it is annoying

**Comment by johnfn** [comment]
This bug is legit. Backspace, even in visual mode, should delete whatever is selected. 

If someone wants to implement Select Mode, please by all means go ahead. :)

**Comment by rebornix** [comment]
Not just selecting by mouse, if you select the content by `cmd+a` and then press backspace, only one character is deleted as well.

**Comment by xconverge** [comment]
@johnfn even visual mode? For me visual mode, backspace moves the end cursor back one position

**Comment by johnfn** [comment]
@xconverge heh, I'm using macvim, maybe it does something weird?

**Comment by sethstha** [comment]
@xconverge 
Also selecting duplicate with ctrl+d on insert mode and pressing backspace seems to delete only first occurrence.

Am I missing something ?

Have a look at here
https://github.com/VSCodeVim/Vim/issues/1358
