### ISSUE TITLE
cmd + D selection don't jump and scroll window to latest selected text

### ISSUE THREAD

**Issue by wangadong** [VSCodeVim/Vim#880]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

Press cmd + d multiple times to select same words
### What did you expect to happen?

When the word are not in current view, it should jump and scroll window to the view of the newly selected word.
### What happened instead?

It flashed the view to the selected word but jump back to the original one.
### Technical details:
- VSCode Version: 1.6.0
- VsCodeVim Version: 0.3.5
- OS: macOS Sierra

**Comment by prurph** [comment]
:+1:

**Comment by xconverge** [comment]
@rebornix I think we have the proper APIs to do this now, want to take a stab at it?

**Comment by Wyntau** [comment]
I have the same problem, and this is the last reason I do not use vscode vim extension.

**Comment by Wyntau** [comment]
Can anyone find the problem? I set `"<D-d>": false` in `handleKeys`, but it still flashed the view to the selected word but jump back to the original one

**Comment by gergelyth** [comment]
I managed to track down the problem and patch it (#4725)

**Comment by J-Fields** [comment]
This was fixed by @gergelyth in #4725. However it brings you back to your original cursor as soon as you do anything other than `gb`/`<D-d>`. Is this behavior desirable, or would it be better to keep the view focused on your last cursor?
