### ISSUE TITLE
half page & center cursor "c-d c-u + zz"

### ISSUE THREAD

**Issue by darianmorat** [VSCodeVim/Vim#8808]
I couldn't find any way to remap `c-d` `c-u` with `zz` to center the page. When trying to combine on any way in the settings.json or keybindings.json is just bug and not working at all. It this possible in the extension? 

I was trying to get the change in the settings.json with:
```json
      {
         "before": ["c-d"],
         "after": ["M", "c-d"]
      },
      // or
      {
         "before": ["c-d"],
         "after": ["c-d", "zz"]
      },
```

any way to accomplish something like this?:
```vim
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Half page up" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Half page down" })
```

- Extension (VsCodeVim) version: 1.27.2
- VSCode version: Latest
- OS: Win / Wls2

**Comment by HenryTSZ** [comment]
```json  
"vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["c-d"],
      "after": ["M", "c-d"]
    },
    {
      "before": ["c-u"],
      "after": ["c-u", "z", "z"]
    },
],
```

**Comment by darianmorat** [comment]
> ```json
> "vim.normalModeKeyBindingsNonRecursive": [
>     {
>       "before": ["c-d"],
>       "after": ["M", "c-d"]
>     },
>     {
>       "before": ["c-u"],
>       "after": ["c-u", "z", "z"]
>     },
> ],
> ```

Ohhh thank you, I was doing it on the `vim.normalModeKeyBindings`. I think for that reason was not working, btw, the first one using `M` is smother :)
