### ISSUE TITLE
Shift+j followed by x deletes character at end of line

### ISSUE THREAD

**Issue by lukebarton** [VSCodeVim/Vim#882]
### What did you do?
[Here](https://dl.dropboxusercontent.com/u/8812332/vscode-issues/shift-j%2Bx.mov) is a video of the result of shift+j followed by x.

### What did you expect to happen?
x should delete character at carat

### What happened instead?
x deleted character at end of line

### Technical details:

* VSCode Version: 1.6
* VsCodeVim Version: 0.3.5
* OS: OSX

**Comment by johnfn** [comment]
This is bad and also concerning.
