### ISSUE TITLE
cis does strange things

### ISSUE THREAD

**Issue by lukebarton** [VSCodeVim/Vim#884]
### What did you do?
Used command `cis` change in surround in various places

### What did you expect to happen?
leave me in insert mode at the beginning of the surround that I'm in

### What happened instead?
weird things - [See this video](https://dl.dropboxusercontent.com/u/8812332/vscode-issues/cis.mov)

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.5
* OS: OSX

**Comment by johnfn** [comment]
I think you're expecting surround behavior as in the plugin surround.vim. We actually don't support that yet as it's just a plugin - not part of vim core, but we are 100% open to PRs. 

The behavior you're seeing is actually "change inside sentence" - see here http://vimdoc.sourceforge.net/htmldoc/motion.html#sentence. Our behavior is actually the same as vanilla Vim here.
