### ISSUE TITLE
j and k don't move into the same column

### ISSUE THREAD

**Issue by tinhajj** [VSCodeVim/Vim#8840]
**Describe the bug**
If you push j or k and you are moving to a line with a different tab indentation the cursor doesn't stay in the same column even if it could have.

**To Reproduce**
1. Start on a line that has no whitespace in the beginning
2. Use j or k to move to a line that has tab characters in front of it

Also I believe you need to make sure tab display size is greater than 1

**Expected behavior**
The cursor should stay in the same column if its possible

**Screenshots**
[2024-01-21 15-15-02.webm](https://github.com/VSCodeVim/Vim/assets/5882922/9080a453-44a0-4fac-904a-6cd963b06d3d)

**Environment (please complete the following information):**
- Extension (VsCodeVim) version: v1.27.2
- VSCode version: 1.85.1
- OS: Windows, happens on Mac OS too

**Comment by TheDevMinerTV** [comment]
This is probably related to https://github.com/VSCodeVim/Vim/issues/8108

**Comment by mmviamm** [comment]
and it happens when you set the foldfix true in settings
`"vim.foldfix": true`
