### ISSUE TITLE
shift-Y does not work in visual line mode or visual block mode

### ISSUE THREAD

**Issue by davidgiven** [VSCodeVim/Vim#886]
...but does work in visual mode.

To reproduce:

Select some text with shift-V; shift-Y is ignored.
Select some text with ctrl-V or v. shift-Y is ignored.
Select some text with the mouse. shift-Y works.

Is there a binding missing for some of the modes?

**Comment by johnfn** [comment]
Fixed on master. Will be on a new version of VSCodeVim very soon. :)

**Comment by davidgiven** [comment]
Fantastic --- thanks!
