### ISSUE TITLE
Remapping <leader> CAPITAL_LETTER doesn't work

### ISSUE THREAD

**Issue by sebszyller** [VSCodeVim/Vim#8867]
**Describe the bug**
I'm trying to remap `<leader>F` (in normal mode) to a vim motion, and it doesn't work. Using `<leader>f` instead does work just fine.

**To Reproduce**
1. `{ "before": ["<leader>", "F"], "after": ["whatever"] }`
2. `{ "before": ["<leader>", "f"], "after": ["whatever"] }`

I've also tried defining it in `keybindings.json` instead using `vim.remap`:
```
  {
    "key": "shift+f",
    "command": "vim.remap",
    "when": "inputFocus && vim.mode == 'Normal'",
    "args": { "before": ["<leader>"], "after": ["whatever"] }
  },
```

But to no avail.

**Expected behavior**
`vim.keymap.set("n", "<leader>F", "whatever", opts)` works in neovim.

**Environment:**

- Extension (VsCodeVim) version: 1.27.2
- VSCode version: 1.85.1
- OS: MacOS Sonoma

**Comment by HenryTSZ** [comment]
I can't reproduce it, and may need more config info
