### ISSUE TITLE
Ability to add multiple cursors with alt + mouseclick like native VSCode

### ISSUE THREAD

**Issue by xconverge** [VSCodeVim/Vim#887]
---

Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---

https://code.visualstudio.com/docs/editor/editingevolved#_multiple-selections

Should be able to <alt + click> to add cursors so that the behavior stays consistent with the plugin and vanilla vscode.

**Comment by xconverge** [comment]
Probably the same as #860

**Comment by johnfn** [comment]
Hmm. 

The problem is that because of the way I did visual block mode, we have to manually override all shortcuts that create multiple cursors. 

Is it possible to override alt+click? Can we even detect it? @rebornix do you know? 

Otherwise, we might have to refactor visual block mode first...

**Comment by xconverge** [comment]
fixed with #1434 on master
