### ISSUE TITLE
Visual Movement interferes with replacement

### ISSUE THREAD

**Issue by 333fred** [VSCodeVim/Vim#889]
Following the instructions on the main README, I've added remaps for the standard movement keys to their visual versions, like so:

``` json
"vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["0"],
            "after": ["g", "0"]
        },
        {
            "before": ["$"],
            "after": ["g", "$"]
        },
        {
            "before": ["j"],
            "after": ["g", "j"]
        },
        {
            "before": ["k"],
            "after": ["g", "k"]
        }
]
```

However, these bindings interfere with character replacement.
### What did you do?

Pressed `r0` in normal mode.
### What did you expect to happen?

The current character is replaced with `0`.
### What happened instead?

The current character is replaced with a `g`, and moves the cursor up a line.
### Technical details:
- VSCode Version: 1.6.0
- VsCodeVim Version: 0.3.5
- OS: Windows

**Comment by johnfn** [comment]
Fixed on master and will be released in 0.4.7.
