### ISSUE TITLE
Visual Movement does very weird things with visual selection

### ISSUE THREAD

**Issue by 333fred** [VSCodeVim/Vim#890]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

Similar setup to #889, I have bound `0`, `$`, `j`, and `k` to their `g`-prefixed counterparts. I then pressed `v` and started to use `j`, `k`, `l`, and `h` to select text.
### What did you expect to happen?

Visual mode works as normal.
### What happened instead?

The selection seems to follow my cursor. GIF's are worth a thousand words: https://gyazo.com/a25cf4cd86d2b8f45d4a27913476c9a8. Note that _all_ I'm doing is starting with one cursor, then pressing `v`, followed by `j` and `k`.
### Technical details:
- VSCode Version: 1.6.0
- VsCodeVim Version: 0.3.5
- OS: Windows

**Comment by johnfn** [comment]
Dug into this and realized it was a VSCode API limitation.

Pending https://github.com/Microsoft/vscode/issues/16472
