### ISSUE TITLE
j/k don't preserve column

### ISSUE THREAD

**Issue by bowernite** [VSCodeVim/Vim#8912]
I know this has been posted in the past for gj/gk, but this also seems to be broken whenever moving the cursor up or down.

Basically, in this scenario:

```
abc
a
abc
```

If you have your cursor on `c` and move to the other `abc` line, the cursor ends up on `a` in the other line for any of the following:

1. normal mode `j`/`k`
2. insert mode `up`/`down`
3. visual mode `j`/`k`

If I reload VS Code with extensions disabled and use `up`/`down`, this bug does not exist.

**Comment by babramczyk** [comment]
FWIW, this seems to be a bandaid fix:

```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["j"],
      "commands": ["cursorDown"]
    },
```

**Comment by babramczyk** [comment]
FWIW, this seems to be a bandaid fix:

```
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["j"],
      "commands": ["cursorDown"]
    },
```

**Comment by darianmorat** [comment]
This is caused for this option: `"vim.foldfix": true`, once disabled, is gonna work just fine.

**Comment by p-se** [comment]
> FWIW, this seems to be a bandaid fix:
> 
> ```
>   "vim.normalModeKeyBindingsNonRecursive": [
>     {
>       "before": ["j"],
>       "commands": ["cursorDown"]
>     },
> ```

Please note that this seems to work with `"vim.foldfix": true`!
