### ISSUE TITLE
Indenting in visual line mode then dot

### ISSUE THREAD

**Issue by mreishus** [VSCodeVim/Vim#892]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Scenario 1: `Vjjj>...`

### What did you expect to happen?

Select 4 lines.  `>` should indents those 4 line one extra tabstop and take me out of visual mode.
Each press of `.` should indent those lines one more tabstop.

### What happened instead?

Pressing `>` indented the lines, but left me in visual mode. (It moved me from visual line mode to visual mode).  My selection is graphically hidden, but it's 'still there'.   Pressing `.` did nothing instead of indenting again.

-----

### What did you do?

Scenario 2: `Vjjj>j`

### What did you expect to happen?

Select 4 lines.  `>` should indent those 4 lines one extra tabstop and take me out of visual mode.
`j` should move me down to the second of those 4 lines.

### What happened instead?

`>` indented, but it did not take me out of visual mode.  (It moved me from visual line mode to visual mode).   `j` expanded my selection to 5 lines. (With a graphical error in dark theme, one character has a light background)

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.5
* OS:  Windows 7

Both of these scenarios should work with `v` as well as `V` - just tested in vim.

**Comment by johnfn** [comment]
This has been fixed!
