### ISSUE TITLE
Visual line indenting after selecting >1 line is not properly repeated with '.'.

### ISSUE THREAD

**Issue by boweiliu** [VSCodeVim/Vim#893]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Vkkk>...

### What did you expect to happen?
The starting line and the 3 lines above it are indented an additional 4 times.

### What happened instead?
The starting line and like 10 lines above it are indented 1-2 times.

(Related to https://github.com/VSCodeVim/Vim/issues/892?)

### Technical details:

* VSCode Version: Version 1.7.0-insider (1.7.0-insider) cf203e09145586b96497eab230253d686c2b2a2d

* VsCodeVim Version: master at 0e4ce0fde4dee79fe21e15640091b494d76acfa0
* OS: OSX 10.10.5

**Comment by mreishus** [comment]
Even though #892 `Vjjj>...` was fixed, this is still an issue.  On 0.3.7, `Vkkk>...` moves the selection higher in the file each time you press `.`.

**Comment by rebornix** [comment]
`Vkkk>...` issue is tracked in #549 . Let's move our conversation there.
