### ISSUE TITLE
Repeatable dot of insert action results improper output

### ISSUE THREAD

**Issue by s-kai273** [VSCodeVim/Vim#8938]
Repeatable dot of some insert action generates different output from original vim one.
For instance, the last action is inserting text of `var`, and try `3.` on a blank line.

- Expectation: `varvarvar`
- Actual: `vavavarrr`

This is probably a cursor position issue...

**Comment by shinohara-rin** [comment]
This is the expected behaviour in vim and have nothing to do with VSCodeVim.

To achieve what you described, you can use append `a` instead of insert `i`, for example:
1. write `var` by typing `avar`
2. return to NORMAL with `esc`
3. repeat append 3 times with `3.`

**Comment by shinohara-rin** [comment]
I tested it with my vscodevim, vim and nvim, and they showed the exact same behaviour as you described.

However with append `a` instead of insert `i` I can achieve what you wanted, maybe you can try that?

**Comment by s-kai273** [comment]
I fixed repeatable dot bug on https://github.com/VSCodeVim/Vim/pull/8979.
Hope someone to review it.
