### ISSUE TITLE
Add "none" for Cursor Style in Visual/VisualBlock/Visualline Mode

### ISSUE THREAD

**Issue by Clo91eaf** [VSCodeVim/Vim#8945]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use VSCodeVim and select a piece of text, the cursor is flickering, which is not the problem when using regular Vim to select text. After searching for settings.

I found that Cursor Style can adjust the style of the cursor in Visual Mode, but the default "" option did not give me the desired result. In fact, it still presents a "line-thin" style.

default option is same as "line-thin":
![default option is same as "line-thin"](https://github.com/VSCodeVim/Vim/assets/73728970/59fe6a4d-89fa-4ae4-ad2f-844fd7224d93)

It manifests as follows:
![behavior](https://github.com/VSCodeVim/Vim/assets/73728970/1f6dad96-e4cb-465a-8fad-cc594b7d2b0a)

I hope it can behave like this:
![no cursor](https://github.com/VSCodeVim/Vim/assets/73728970/d75964fb-08bf-4f4a-9e1d-d16e7e6f4299)

**Describe the solution you'd like**
Add the "none" option so that Cursor does not appear when selecting text.

**Comment by shinohara-rin** [comment]
I doubt if it's possible to hide the cursor completely without some nasty hacks, since VSCodeVim is only using VSCode's builtin cursor style, and it can't be hidden.

However, if you only wish to stop the flickering, you can add the following to your settings.json
```
  "editor.cursorBlinking": "solid",
```
