### ISSUE TITLE
Cursor behavior is flakey with same file open in first and second panel

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#895]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

**Comment by tvhung83** [comment]
The issue remains on v0.3.7.

**Comment by johnfn** [comment]
Ah, you're right... bummer

**Comment by rebornix** [comment]
I'll say it's gone in 0.3.8.
