### ISSUE TITLE
Performance is slow

### ISSUE THREAD

**Issue by johnfn** [VSCodeVim/Vim#897]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---

Hold down enter. It's really laggy.

**Comment by johnfn** [comment]
Research:

Only inserting keys is noticeably laggy (and enter is by far the worst). Holding down h or l for instance is not laggy. (Please chime in if you are finding something different!)

**Comment by johnfn** [comment]
Perf investigation branch here https://github.com/VSCodeVim/Vim/tree/perf

**Comment by johnfn** [comment]
To the people who thumbs uped this issue, let me know if my recent commit on master had any benefits for you. Things seem to be about twice as fast on my benchmarks.

**Comment by quang4ngo** [comment]
I'm using 0.3.7.  Ctrl+e and ctrl+y are laggy

**Comment by quang4ngo** [comment]
Regarding my recent comment about ctrl+e and ctrl+y being slow.  I added the following to keybindings.json and it's fast now:
   { "key": "ctrl+e",                "command": "scrollLineUp",
                                      "when": "editorTextFocus" },
    { "key": "ctrl+y",                "command": "scrollLineDown",
                                      "when": "editorTextFocus" }

That probably bypasses the vim version of the key combos.

**Comment by quang4ngo** [comment]
I had my ctrl+e and ctrl+y swapped, btw. :)

**Comment by johnfn** [comment]
That is very interesting, @quang4ngo! Your fix seems like an adequate solution :) Feel free to open up a PR.

It's interesting that C-e and C-y would be so laggy anyways, since they shouldn't really be doing anything, so that's worth investigating as well!

**Comment by jgoz** [comment]
@johnfn On 0.4.0, extending multiple cursors using the vim command (`extension.vim_cmd+alt+down`) is really laggy, but binding directly to `editor.action.insertCursorBelow` performs normally.

You can replicate this by setting a high key-repeat rate and holding down Cmd+Alt+Down (or Ctrl+Alt+Down).

**Comment by jagtesh** [comment]
For me, the performance on Windows 10 Anniversary build was quite bad compared to macOS Sierra.

**Comment by dustinboston** [comment]
With the latest update (0.4.7) the extension has become almost unusable. Basic navigation with `hjkl` and regular typing after `i` often take a second after each keypress. No extensions are enabled, latest version of VS Code.

**Comment by johnfn** [comment]
@dustinboston investigating right now!

**Comment by johnfn** [comment]
@dustinboston Can you check version 0.4.8 to see if the perf issues you were seeing still exist?

**Comment by johnfn** [comment]
As of b2b2b97494aca2ca5568e544e601247ecebc2bd1, `<C-e>` is no longer laggy.

**Comment by dustinboston** [comment]
It's perfect! Thank you! 👏 🎉 🎆

**Comment by johnfn** [comment]
That's what I like to hear! 😉 

Anyone else, feel free to tune in if you have perf issues.

**Comment by jgoz** [comment]
@johnfn https://github.com/VSCodeVim/Vim/issues/897#issuecomment-256408534 is still an issue for me.

**Comment by johnfn** [comment]
I don't believe this is an issue any more. 

If you continue to have problems with performance, please **thumbs this specific comment up.**

**Comment by johnfn** [comment]
(Also if you could leave a comment detailing what specifically you have perf issues with, that would be useful.)

**Comment by asasmoyo** [comment]
Hi, I am using this extension along with vscode-go and experiencing lags when editing large files with 5k lines (slow move on insert mode and slow autocompletion). After disabling the vim extension, it becomes normal again.

**Comment by Chillee** [comment]
@asasmoyo do you have neovim integration enabled? Could you try disabling that?

**Comment by asasmoyo** [comment]
@Chillee no i didn't use neovim integration. i just tried it again with default settings but it still slow.

is there a way to benchmark vscode so that i can know what make my vscode slow?

**Comment by Chillee** [comment]
I'm not aware of any ways other than disabling and enabling packages.

Could you verify that the slowdown occurs when you're only using VsCodeVim?

**Comment by asasmoyo** [comment]
When I use only VsCodeVim, everything is fast. But when I enable vscode-go, it starts getting slow. Does this mean the go plugin that make it slow?

**Comment by Chillee** [comment]
@asasmoyo What about if you just enable vscode-go?

It's possible there's some kind of weird interaction between the two.

**Comment by asasmoyo** [comment]
there's noticeable delay on autocompletion, but moving around using keyboard feels normal
