### ISSUE TITLE
wrong caret shape in insert mode

### ISSUE THREAD

**Issue by localvar** [VSCodeVim/Vim#898]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

type `a` or `i` to enter insert mode, and caret shape changes to '|'
type some text

### What did you expect to happen?

caret shape not changed

### What happened instead?

the caret shape changes to a block, which makes me think I'm in 'normal' mode

NOTE: when use `o` or `O` to enter insert mode, the caret does NOT even change.

### Technical details:

* VSCode Version: 1.6
* VsCodeVim Version: 0.3.5
* OS: Windows 10 Professional

**Comment by johnfn** [comment]
Just fixed this one on master! 💨

**Comment by localvar** [comment]
thanks @johnfn , super quick response!
