### ISSUE TITLE
VSCode option editor.trimAutoWhitespace is ignored

### ISSUE THREAD

**Issue by arussellk** [VSCodeVim/Vim#899]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Make new document
2. Type ifoo (go to insert mode, then type "foo")
3. Press enter
4. Press tab
5. Press enter

### What did you expect to happen?

Note: `<space>` represents a single ASCII character 32.

Expected text:
```
foo

<space><space><space><space>
```

### What happened instead?

Actual text:
```
foo
<space><space><space><space>
<space><space><space><space>
```

I confirmed that VSCode trims whitespace correctly when vim is uninstalled. I *think* it worked correctly in the past, so it could be worth looking at changes in the past week or two that could have done this.

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.6
* OS: Windows 10, OSX El Capitan

**Comment by arussellk** [comment]
I'd be happy to take a look at this. Do any project maintainers have an idea of where to start looking?

**Comment by johnfn** [comment]
I would just use git bisect, to be honest. :)

**Comment by arussellk** [comment]
Git bisect is awesome!

This is first broken in 816c3035d95c60503025dda329f2a5b8a1aa81bc. Its parent is 69d8df89094d15f48183e7d6e9e9e80dd0a082dd.

**Comment by johnfn** [comment]
Unfortunately, that is the worst commit it could have possibly been.

**Comment by arussellk** [comment]
This is (magically?) fixed now, so I'm going to close it.

Details on when I noticed it fixed (it could have been fixed sooner):
VSCode Version: 1.6.0
VsCode Vim Version: 0.3.8
OS: OSX Sierra
