### ISSUE TITLE
multi-cursor yank should yank ALL lines to clipboard when vim.useSystemClipboard is true

### ISSUE THREAD

**Issue by ShaseOfBase** [VSCodeVim/Vim#8998]
It sucks that when I yank with multi-cursor while "vim.useSystemClipboard" is true, that it does not copy all lines to clipboard, but only the first. 

When "vim.useSystemClipboard" is true, all lines yanked in multi-cursor should be placed into the system clipboard.

**Comment by pprg1996** [comment]
Put this in your config and let VSCode handle the copying. I also recommend doing that with other functionality such as undo/redo and navigation (ctrl-o and ctrl-i), let VSCode do as much as possible.

<img width="487" alt="image" src="https://github.com/VSCodeVim/Vim/assets/22826415/8e05c12c-da30-4149-83d8-9b9687f1c75e">

**Comment by ShaseOfBase** [comment]
Legend, thanks so much!
