### ISSUE TITLE
keys not working in international keyboards

### ISSUE THREAD

**Issue by guillermooo** [VSCodeVim/Vim#9]
Can't press `Shift+;` in a Spanish keyboard, for example. It must be `Shift+.`.

**Comment by jpoon** [comment]
Re: https://github.com/Microsoft/vscode/issues/114

**Comment by guillermooo** [comment]
I'm thinking ideally we'd be able to load keybindings for different keyboard layouts. So VS Code should conditionally load sets of key bindings based on  some configuration.

For example, this would go in a config file like `preferences.json`:

```
...
"localeResources": "es-ES", // null, "default" or empty means "default"
...
```

And now VS Code or our extension would know to load:

```
keybindings.es-ES.json
```

instead of:

```
keybindings.json
```

All of this is just an example, I'm aware VS Code can't do this right now.

**Comment by jpoon** [comment]
Let's use https://github.com/VSCodeVim/Vim/issues/47 to track issues with international keyboard.
