### ISSUE TITLE
Visual selection does not work with the "go to matching brace" % command.

### ISSUE THREAD

**Issue by warrenhodg** [VSCodeVim/Vim#901]
### What did you do?

Shift-V, $, %

### What did you expect to happen?

Start selecting code, go to line end where the opening brace was, then select everything from where I started up until the closing brace.

### What happened instead?

Visual mode was cancelled, and the cursor navigated to the closing brace.

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.6
* OS: MacOS Sierra

**Comment by johnfn** [comment]
This works for me on master. New version coming soon. :)

**Comment by vedran** [comment]
I believe that I am able to reproduce this issue on 0.5.2. Is it expected to be fixed now?

![image](https://d17oy1vhnax1f7.cloudfront.net/items/3L0C0R2J2Q1d0a3Y2l1i/Screen%20Recording%202017-01-31%20at%2008.28%20PM.gif?v=0274b9b9)

Steps:

1) Start at the beginning of the line
2) Press v
3) Press $
4) Press %

**What is expected**

Select the entire function, to the matching curly brace, in visual select mode.

**What happens**

The visual mode goes into a bit of a weird state, as if it restarted from the end of the line. The cursor does not move. Notice on my second attempt in the gif when I move up and down, it's as if the visual block started from the end of the line.

**Workaround**

Press h to go left one position _after_ pressing $, but before pressing %. For example:

![image](https://d17oy1vhnax1f7.cloudfront.net/items/030f1N030t1n1w2l2Z17/Screen%20Recording%202017-01-31%20at%2008.39%20PM.gif?v=24bfbd17)

VSCode Version: 1.8.1
VsCodeVim Version: 0.5.2
OS: MacOS Sierra


Thanks!
