### ISSUE TITLE
>< lost multiple lines selection 

### ISSUE THREAD

**Issue by idoo** [VSCodeVim/Vim#903]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Some code is selected, then pressed < or > and selection is lost.

http://take.ms/PgrZV

### What did you expect to happen?
Code should be selected

### What happened instead?
Selection lost

### Technical details:

* VSCode Version: 1.6
* VsCodeVim Version: latest
* OS: Mac OS

**Comment by FSMaxB** [comment]
This is normal behavior in vim.

**Comment by johnfn** [comment]
Yep, this is expected. Use `.` to repeat the behavior if you want.
