### ISSUE TITLE
:inoremap jj <Esc> in vimrc not imported

### ISSUE THREAD

**Issue by stephanedebove** [VSCodeVim/Vim#9035]
Type: <b>Bug</b>

I have imported my vimrc on Windows. All commands work, except this one:

`:inoremap jj <Esc>`

Directly setting the mapping as

```
"vim.insertModeKeyBindings": [
        {
            "before": ["j", "j"],
            "after": ["<Esc>"]
        }
    ]
```

in settings.json works.

Extension version: 1.27.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by yaoyhu** [comment]
Set `vim.vimrc.enable` to true and set `vim.vimrc.path` appropriately.

It is not allowed to add `:` into your vimrc file. Or can you share your .vimrc file?

**Comment by stephanedebove** [comment]
hey @yaoyhu 
Thanks for the reply. These settings were already set, but the problem was indeed this typo `:`. Vim seems to accept it, but not the Vim extension.
