### ISSUE TITLE
Normal mode `die` deletes all text

### ISSUE THREAD

**Issue by pjcon** [VSCodeVim/Vim#9058]
**Describe the bug**
In normal mode, if you input `die`,  all text is deleted. I have accidentally entered this a few times and it's alarming.

Perhaps it is a new feature and stands for "delete inner everything"?

**To Reproduce**

1. Open VSCode with Vim mode enabled
2. Create a new document
3. Input a bunch of text e.g:
```
In publishing and graphic design, Lorem
 ipsum is a placeholder text commonly used to demonstrate the 
visual form of a document or a typeface without relying on meaningful
 content. Lorem ipsum may be used as a placeholder before the
 final copy is available.
```
4. Enter `<esc>die`
5. See that everything is deleted
6. Enter `u` to retrieve all the text

**Expected behavior**

Comparison with Vim: **Nothing should happen.**

**Screenshots**
![delete-inner-everything](https://github.com/VSCodeVim/Vim/assets/43265258/3438ab1c-dc5e-4b46-bd73-143534188aed)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:  1.27.3
- VSCode version: 1.89.1 (user setup)
- OS: Windows 10 Build 19045

**Comment by HenryTSZ** [comment]
### [vim-textobj-entire](https://github.com/VSCodeVim/Vim?tab=readme-ov-file#vim-textobj-entire)

Adds two useful text-objects:

-   `ae` which represents the entire content of a buffer.
-   `ie` which represents the entire content of a buffer without the leading and trailing spaces.

Usage examples:

-   `dae` - delete the whole buffer content.

**Comment by pjcon** [comment]
So it is actually a feature to operate on the entire buffer.

I'll close the issue.
