### ISSUE TITLE
shift+j should join lines selected lines

### ISSUE THREAD

**Issue by robsonpeixoto** [VSCodeVim/Vim#906]
### What did you do?

Selected lines using `shift+v` and after that pressed `shift+j`
### What did you expect to happen?

Join all selected lines
### What happened instead?

Nothing
### Technical details:
- VSCode Version: 1.6.0
- VsCodeVim Version: 0.3.7
- OS: macOS 10.12

**Comment by rebornix** [comment]
Per definition of our `J` command, right now we only support Normal and Visual mode, which are not enough.

**Comment by mbp** [comment]
I believe this feature was added in #1016.

However it doesn't really work that well because of bug #909

**Comment by rebornix** [comment]
Fixed via https://github.com/VSCodeVim/Vim/commit/c790443f6c367dd4310f0d03133b6eaae734b8e7
