### ISSUE TITLE
<C-w> + v and  <C-w> + s  split pane not working on VSCode 1.90

### ISSUE THREAD

**Issue by ljones140** [VSCodeVim/Vim#9061]
**Describe the bug**

Using `<C-w> + v` an <C-w> + s` for new panes are no longer working when on latest version of VSCode 1.90
https://code.visualstudio.com/updates/v1_90

**To Reproduce**

1.  Ensure VSCode is version 1.90
2.  on a file press `<C-w>` followed by `v` or  `<C-w>` followed by `s`

**Expected behavior**
New pane opens

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.27.3
- VSCode version: 1.90
- OS: Mac 14.5

**Comment by ljones140** [comment]
Downgrading to VSCode 1.89.1 and split panes works

**Comment by levidavidmurray** [comment]
I didn't realize my VSCode updated and thought I was going crazy when `<C-w> + v` wasn't working. Hopefully we can get a quick resolution for this

**Comment by levidavidmurray** [comment]
Seems like this is due to some [changes](https://github.com/microsoft/vscode/pull/212930/files#diff-d1725cf20d86e6ad4df5c09e62fba535c6be8198fd0ee318d550911c625b1f47R68) made for the new ["Tab Multi Select" feature](https://code.visualstudio.com/updates/v1_90#_editor-tabs-multi-select)

I noticed that `resourceOrContext` and `commandContext` were `undefined` when the action was run via `Command Palette > Split Editor`. When run via `VSCodeVim`, they were both empty objects.

![split-editor](https://github.com/VSCodeVim/Vim/assets/46084870/502705bc-1ddc-4a43-8a44-98f139f8be12)

Setting `workbench.action.splitEditor` and `workbench.action.splitEditorOrthogonal` action arguments to `undefined` seems to fix the immediate issue. But, I don't know enough about the architecture of VSCodeVim nor VSCode to say if this is the correct solution.

https://github.com/VSCodeVim/Vim/assets/46084870/12f4294f-b23f-42a5-9797-7cf1313b3cff

**Comment by sasacocic** [comment]
I'm having similar issues

`<C-w> + v`- vertical split

and 

`<C-w> + s` - horizontal split


Are no longer working for me after updating to `1.90.0` of visual studio code

**Comment by david-xorcon** [comment]
Same here - broken since 1.90.0

**Comment by Yin-SHT** [comment]
Same here

**Comment by ljones140** [comment]
> I'm having similar issues
> 
> `<C-w> + v`- vertical split
> 
> and
> 
> `<C-w> + s` - horizontal split
> 
> Are no longer working for me after updating to `1.90.0` of visual studio code

I'll edit the issue to add these thanks

**Comment by kianryan** [comment]
This wasn't broken on insiders until the latest update.
Now broken on 1.91.0-insider - same behaviour

**Comment by viddo** [comment]
At least for vertical/horizontal splits one can one can add the following shortcuts to `keybinding.json` as a temporary workaround, I guess:

```json
    {
        "key": "ctrl+w v",
        "command": "workbench.action.splitEditor"
    },
    {
        "key": "ctrl+w s",
        "command": "workbench.action.splitEditorDown"
    },
```

**Comment by dim-an** [comment]
Another possible workaround is to modify vim extension settings:
```
{
    ...
    "vim.normalModeKeyBindings": [
        {
            "before": ["C-w", "v"],
            "after": [":", "v", "s", "<Enter>"],
        },
        {
            "before": ["C-w", "s"],
            "after": [":", "s", "p", "<Enter>"],
        },
    ...
}
```

I like it better than modifying `keybinding.json` because it doesn't break Ctrl+W behaviour in insert mode.

**Comment by basictheprogram** [comment]
Adding same behavior for menu options

* View > Editor Layout > Split Down
* View > Editor Layout > Split Up

**Comment by jayhanjaelee** [comment]
Same Here

**Comment by viddo** [comment]
> Another possible workaround is to modify vim extension settings:
> 
> ```
> {
>     ...
>     "vim.normalModeKeyBindings": [
>         {
>             "before": ["C-w", "v"],
>             "after": [":", "v", "s", "<Enter>"],
>         },
>         {
>             "before": ["C-w", "s"],
>             "after": [":", "s", "p", "<Enter>"],
>         },
>     ...
> }
> ```
> 
> I like it better than modifying `keybinding.json` because it doesn't break Ctrl+W behaviour in insert mode.

This workaround works in stable / `1.19.0` but not in _insiders_ version `1.91.0-insider`, so there's probably more changes ahead that will break it again.

**Comment by aurum77** [comment]
> At least for vertical/horizontal splits one can one can add the following shortcuts to `keybinding.json` as a temporary workaround, I guess:
> 
> ```json
>     {
>         "key": "ctrl+w v",
>         "command": "workbench.action.splitEditor"
>     },
>     {
>         "key": "ctrl+w s",
>         "command": "workbench.action.splitEditorDown"
>     },
> ```
here's that but for config json

```
"vim.normalModeKeyBindings": [
    {
      "before": [
        "<C-w>",
        "v"
      ],
      "commands": [
        "workbench.action.splitEditor"
      ]
    },
    {
      "before": [
        "<C-w>",
        "s"
      ],
      "commands": [
        "workbench.action.splitEditorDown"
      ]
    },
]
```

**Comment by guunergooner** [comment]
> > At least for vertical/horizontal splits one can one can add the following shortcuts to `keybinding.json` as a temporary workaround, I guess:
> > ```json
> >     {
> >         "key": "ctrl+w v",
> >         "command": "workbench.action.splitEditor"
> >     },
> >     {
> >         "key": "ctrl+w s",
> >         "command": "workbench.action.splitEditorDown"
> >     },
> > ```
> 
> here's that but for config json
> 
> ```
> "vim.normalModeKeyBindings": [
>     {
>       "before": [
>         "<C-w>",
>         "v"
>       ],
>       "commands": [
>         "workbench.action.splitEditor"
>       ]
>     },
>     {
>       "before": [
>         "<C-w>",
>         "s"
>       ],
>       "commands": [
>         "workbench.action.splitEditorDown"
>       ]
>     },
> ]
> ```

👍 Cool, add this configuration code snippet to setting.json to bypass the above issue.

**Comment by cochranjdlz** [comment]
For anyone interested, I was able to additionally add the following config to allow me to regain my keyboard navigation, which also broke when I updated.

```
  {
    "key": "ctrl+w k",
    "command": "workbench.action.navigateUp"
  },
  {
    "key": "ctrl+w j",
    "command": "workbench.action.navigateDown"
  },
  {
    "key": "ctrl+w h",
    "command": "workbench.action.navigateLeft"
  },
  {
    "key": "ctrl+w l",
    "command": "workbench.action.navigateRight"
  },
```
In my case, I'm used to using `<C-k>`, `<C-l>`, `<C-j>`, `<C-h`.

**Comment by junhan-z** [comment]
Same here.

Also I think `ctrl+w o` (show current panel and close others) and `ctrl+w q` (close current panel) are also broken.

**Comment by fivetran-danandreiganea** [comment]
Same here

**Comment by laipz8200** [comment]
> Same here.
> 
> Also I think `ctrl+w o` (show current panel and close others) and `ctrl+w q` (close current panel) are also broken.

```json
    {
        "key": "ctrl+w q",
        "command": "workbench.action.closeActiveEditor"
    },
```

I'm using this config as a temporary solution.

**Comment by CWEzio** [comment]
Same problem

**Comment by jakyns** [comment]
when will this fix?

**Comment by jirol9xa** [comment]
same

**Comment by laipz8200** [comment]
Same here

**Comment by basictheprogram** [comment]
Still have the problem in 1.90.2 on macOS

**Comment by KuanYuLai** [comment]
same

**Comment by jakyns** [comment]
how can we push this to fix as soon as possible?

**Comment by cloone8** [comment]
Same problem here! Would be great to have this fixes instead of having to use a workaround

**Comment by bluddy** [comment]
Would be nice to have a release for this fix.

**Comment by KholdStare** [comment]
@J-Fields Can this fix be released? I still need to keep resetting to an older version. Thank you!
