### ISSUE TITLE
Ctrl+D / Ctrl+U (page down/up) moves selection when in Visual Line mode

### ISSUE THREAD

**Issue by M4v3R** [VSCodeVim/Vim#907]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
### What did you do?

Make sure `vim.useCtrlKeys` setting is set to `true`.
Open a file that has more content than can fit on the screen.
Place cursor on the first line.
Press `Shift+V` to enter visual line mode (bug is present in visual mode as well)
Press `Ctrl+D` for a page down movement
Notice that the selection is now gone or starts in a different place
### What did you expect to happen?

Text selection should still start on the line which user started Visual mode in.
### What happened instead?

Text selection moves to the current cursor location.
### Technical details:
- VSCode Version: 1.6.0
- VsCodeVim Version: 0.3.7
- OS: macOS Sierra

**Comment by imacnu** [comment]
Me too!! I need a solution to continue use cmd+D normally please

**Comment by johnfn** [comment]
An issue has been opened on VSCode to track this: https://github.com/Microsoft/vscode/issues/16248

**Comment by johnfn** [comment]
One clever workaround until the VSCode team fixes our bug is to redefine C-u and C-d in terms of `k` and `j`:

```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<C-u>"],
            "after": ["20", "k"]
        },
        {
            "before": ["<C-d>"],
            "after": ["20", "j"]
        }
    ]
```

Now the selection will work properly again.

**Comment by kylpo** [comment]
@johnfn, thanks for the workaround! Just wanted to comment that `"20", "k"` would not work for me. I assume this is because `20` isn't a single key press.

Changing it to `"after": ["2", "0", "k"]` works for me.

**Comment by johnfn** [comment]
@kylpo you are exactly right. Thanks for the correction! I've updated my post.

**Comment by KarboniteKream** [comment]
This was supposedly fixed in #1859, but I still have this issue in the latest version of Code.

**Comment by jkfranci** [comment]
I had to use this to get what I was looking for (keeping the cursor on the same screen line as I page up and down):

```
    "vim.otherModesKeyBindingsNonRecursive": [
        {
            "before": ["<C-u>"],
            "after": ["2", "0", "<C-y>", "2", "0", "k"]
        },
        {
            "before": ["<C-d>"],
            "after": ["2", "0", "<C-e>", "2", "0", "j"]
        }
    ]
```

**Comment by c10b10** [comment]
@jkfranci I'm new to VSCode, where do you paste that code?

**Comment by chriys** [comment]
Hi all,
I any of you is still experiencing this. What fixed mine was to have VScode let the vim extension to handle the ctrl+u and ctrl+d keys by setting.
```
"vim.handleKeys": {
    "<C-d>": true,
    "<C-u>": true,
},
```

**Comment by holicc** [comment]
> "<C-d>": true,
>     "<C-u>": true

not work for me

**Comment by holicc** [comment]
> Hi all, If any of you is still experiencing this. What fixed mine was to have VScode let the vim extension to handle the ctrl+u and ctrl+d keys by setting.
> 
> ```
> "vim.handleKeys": {
>     "<C-d>": true,
>     "<C-u>": true,
> },
> ```

not work for me

**Comment by chase-moskal** [comment]
hello!

here's what i did to get ctrl+d and ctrl+u working, and also get it to respect my centered-scrolling that i like

1. unbind the default vscode keybindings for ctrl+d and ctrl+u
    - open vscode keybindings editor (file > keybindings, or something like that)
    - search for `ctrl+d` and right-click that binding and hit "remove keybind" or something like that
    - search for `ctrl+u`, same thing
 2. go to your vscode settings.json (file > settings, then click 'show json' button), and get ready to add some snippets
 3. add this snippet to tell vim extension to handle these keys (by default it ignored ctrl+u for some reason)
     ```json
    "vim.handleKeys": {
        "<C-d>": true,
        "<C-u>": true
    },
    ```
    now the vim extension will act upon `ctrl+d` and `ctrl+d` -- in a flawed way (doesn't respect centered-scrolling)
4. add this snippet to tell vim extension to remap those keys into this hack which works (respects centered-scrolling)
    ```json
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": ["<C-u>"],
            "after": ["2", "0", "k"],
        },
        {
            "before": ["<C-d>"],
            "after": ["2", "0", "j"],
        },
    ],
    ```
5. note that in visual block mode, this hack doesn't take effect, but ctrl+d/u does work, but it doesn't respect centered-scrolling -- i didn't care enough to continue thinking about this, so i've decided to leave things here -- i'm satisfied :D

**Comment by devand123** [comment]
> 5. note that in visual block mode, this hack doesn't take effect, but ctrl+d/u does work, but it doesn't respect centered-scrolling -- i didn't care enough to continue thinking about this, so i've decided to leave things here -- i'm satisfied :D

@chase-moskal if you want to center, just modify:

```
"vim.normalModeKeyBindingsNonRecursive": [
    {
        "before": ["<C-u>"],
        "after": ["2", "0", "k", "z", "z"],
    },
    {
        "before": ["<C-d>"],
        "after": ["2", "0", "j", "z", "z"],
    },
],
```
