### ISSUE TITLE
Navigate "Search" sidebar with "j, k, l" like you can with "Explorer" sidebar

### ISSUE THREAD

**Issue by pyanda2** [VSCodeVim/Vim#9074]
I always have to cmd+shift+F, then manually click on the results with mouse.

**Comment by HenryTSZ** [comment]
> I always have to cmd+shift+F, then manually click on the results with mouse.

you can use "Tab" or use "search.action.focusSearchList" command


https://github.com/VSCodeVim/Vim/assets/55341525/dc5b5ef0-e4e9-4b55-9187-c8bc54fbef38

**Comment by pyanda2** [comment]
Thanks! Also, is there any easy way to find the exact setting (like `search.action.focusSearchList`)? I always just google what i need.

**Comment by HenryTSZ** [comment]
> Thanks! Also, is there any easy way to find the exact setting (like `search.action.focusSearchList`)? I always just google what i need.

Usually, I use F1 or cmd+shift+p to open allCommandsand in your example, related to search, I enter "search" and find the command "Search: Focus on Search View", but it is not what I want, and then I find "Search: Focus List", which is what I need
