### ISSUE TITLE
Cycle through autocomplete suggestions without arrows

### ISSUE THREAD

**Issue by vially** [VSCodeVim/Vim#908]
Please _thumbs-up_ :+1:  this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---

It would be really nice to be able to cycle through the autocomplete suggestions without using the arrow keys. Using `Ctrl+N`/`Ctrl+P` and/or `Ctrl+J`/`Ctrl+K` would allow the user to keep the fingers on the home row.
- VSCode Version: 1.6.0
- VsCodeVim Version: 0.3.7
- OS: Linux

**Comment by rebornix** [comment]
@vially it sounds good to me. May I ask where do you get `Ctrl+N/P/J/K`? Do you have similar experience on other editors?

**Comment by vially** [comment]
I haven't used something like this in other editors but it [seems to be possible](https://stackoverflow.com/questions/26323601/cycle-through-autocomplete-suggestions-without-arrows) in IntelliJ products using the IdeaVim plugin.

Regarding the shortcuts, I guess `Ctrl+N`/`Ctrl+P` is a pretty standard shortcut for **N**ext/**P**revious (I'm using it in fish shell at the moment). But I think `Ctrl+J`/`Ctrl+K` would also make sense to vim users because of the `h`, `j`, `k`, `l` navigation commands.

**Comment by jpgdev** [comment]
The `Ctrl-N`/`Ctrl-P` command are the default way to move to the **N**ext or **P**revious choice in vim's autocomplete (I am using YCM, but I think it's the default vim behavior), so it would be a good choice. `Ctrl-J` / `Ctrl-K` are also good choices (that's what is used in the Ctrl-P plugin to move to choices for example).

**Comment by johnfn** [comment]
Cool idea, but @rebornix is it even possible to trigger up/down on the autocomplete box?

**Comment by rebornix** [comment]
I'm not quite sure but seems we can steal `ctrl+j` from VS Code and then
trigger `selectPrevSuggestion` command or similar?

Grant Mathews <notifications@github.com>于2016年10月13日周四 上午1:40写道：

**Comment by safijari** [comment]
Was there any movement on this? I love this extension but I'm so used to the ctrl-n/ctrl-p shortcuts that every once in a while I end up opening a bunch of new windows :sweat_smile: 

It would be awesome if the ctrl-n/ctrl-p shortcuts worked for navigation through the ctrl-shift-p menu as well :)

**Comment by johnfn** [comment]
Added!

**Comment by johnfn** [comment]
@rebornix do you happen to know if/what the commands are to navigate the command palette?

**Comment by rebornix** [comment]
@johnfn we don't have that but I can see its benefits.

**Comment by johnfn** [comment]
@rebornix yeah, if this many people were interested in `<C-n>` and `<C-p>` I bet they would also like it for the command palette. 😄

**Comment by dpfeuffer** [comment]
Cycle through autocomplete suggestions without arrows would be a very cool feature! Are there any plans to implement this?

**Comment by johnfn** [comment]
It is implemented. ctrl n and ctrl p work. If they don't please submit a bug.

**Comment by jeffwklein** [comment]
is there any way we could configure our setup to do this with tab and shift-tab?

**Comment by parmouraly** [comment]
You can adjust the shortcut through
`Code -> Preferences -> Keyboard shortcuts` and then look for `suggestion`

I was able to modify the shortcut for a more vim-like navigation to `shift+J` and `shift+K`

**Comment by mek-crea** [comment]
`Ctrl` + `n`, `Ctrl` + `p` works fine for me with auto complete.

But I can't seem to make it work with auto import suggestion.
Are you guys having the same issue?

**Comment by idontlikecreatingaccounts** [comment]
I can't figure how to use these hotkeys.
`Ctrl` + `n` is _File: New Untitled Text File_
and `Ctrl` + `p` is _Go to File..._
That's what they were assigned to as default, that's what they're listed as in the settings and that's what they (correctly) do. 
I don't know how I'm supposed to use the same keys with autocomplete.

**Comment by AbdelrahmanDwedar** [comment]
> `Ctrl` + `n`, `Ctrl` + `p` works fine for me with auto complete.
> 
> But I can't seem to make it work with auto import suggestion. Are you guys having the same issue?

It works perfectly for me, what is happening for you?

**Comment by AbdelrahmanDwedar** [comment]
> `Ctrl` + `n`, `Ctrl` + `p` works fine for me with auto complete.
> 
> But I can't seem to make it work with auto import suggestion. Are you guys having the same issue?

It works perfectly for me, what is happening for you?

**Comment by srini-x** [comment]
> @jeffwklein You can adjust the shortcut through `Code -> Preferences -> Keyboard shortcuts` and then look for `suggestion`
> 
> I was able to modify the shortcut for a more vim-like navigation to `shift+J` and `shift+K`

Thank you! I added these to my user `keybindings.json`. Life is a tiny bit better now :)

```json
[
    {
        "key": "shift+j",
        "command": "selectNextSuggestion",
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus || suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion"
    },
    {
        "key": "shift+k",
        "command": "selectPrevSuggestion",
        "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus || suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion"
    }
]
```

**Comment by abheist** [comment]
Want to understand, what stopping you guys to use basic `k` and `j` ?

**Comment by mcshaman** [comment]
I am not sure how `ctrl` + `p` is working for people. It just triggers the VS Code Quick File Open as I would expect. `ctrl` + `n` works which means I can cycle down... But no option to cycle up.

**Comment by Firgrep** [comment]
@mcshaman I have the same issue, but I would like to keep `ctrl` + `p` for the Quick File Open since I use it frequently, so I've mapped `alt` + `j` and `alt`+ `k` to cycle through the auto-complete when it is available. 

keybindings.json
```json

  {
    "key": "alt+j",
    "command": "selectNextSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus || suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion"
  },
  {
    "key": "alt+k",
    "command": "selectPrevSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus || suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion"
  }

```
