### ISSUE TITLE
Can't enter NORMAL mode with logfile highligther extension enabled

### ISSUE THREAD

**Issue by VictorPerezForm3** [VSCodeVim/Vim#9081]
**Describe the bug**

 Note this bug seems to be on the logfile-highlighter extension, BUT I would expect people to search here first because this is the affected extension

- https://github.com/emilast/vscode-logfile-highlighter/issues/588

With both extension enabled you are stuck in insert mode, it seems to capture the ESC key

- [vim entesnion](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)
- [Log FIle Highlighter](https://marketplace.visualstudio.com/items?itemName=emilast.LogFileHighlighter)

**To Reproduce**

Install [vim entesnion](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)
Install [Log FIle Highlighter](https://marketplace.visualstudio.com/items?itemName=emilast.LogFileHighlighter)
Open any file
You're stuck at INSERT mode

**Expected behavior**

When you press ESC, it should leave insert mode

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: latest
- VSCode version: latest
- OS:linux

**Additional context**

**Comment by rquid** [comment]
I updated LogFileHiglighter and it looks like it's already been fixed.

**Comment by J-Fields** [comment]
Indeed, this was caused by a LogFileHighlighter change which has been fixed.
