### ISSUE TITLE
J can't join lines more than 2.

### ISSUE THREAD

**Issue by rebornix** [VSCodeVim/Vim#909]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

---

Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

`3J`
### What did you expect to happen?

All three lines are joined
### What happened instead?

Only first and second line are joined, the third line is just deleted.
### Technical details:
- VSCode Version: 1.6.0
- VsCodeVim Version: 0.3.7
- OS: macOS

**Comment by johnfn** [comment]
This is by design, we determined that the 3rd line is almost never useful anyways and should be deleted.

**Comment by rebornix** [comment]
This worked previously before our transformation refactor. The root cause to this issue is the second transformation calculates the wrong `Position Diff` and `resultLine` as the first transformation is not executed yet.

**Comment by rebornix** [comment]
Fixed via https://github.com/VSCodeVim/Vim/commit/c790443f6c367dd4310f0d03133b6eaae734b8e7
