### ISSUE TITLE
Vim not enabled in non-primary window 

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#912]
* VSCode Version: 1.7 Insider
* VsCodeVim Version: 0.3.7
* OS: OS X 10.11.6

When VSCode is open, Cmd+Shift+N to open another window. Vim is not activated.

Not reproducible in 1.6.

![multi-window](https://cloud.githubusercontent.com/assets/4033249/19330610/4ee24658-9094-11e6-996d-a1d9f69f9ca3.gif)

**Comment by johnfn** [comment]
Insider versions of VSC are always buggy like this. I'm not concerned. :)
