### ISSUE TITLE
Cursor jumps back to last typing position after autocomplete

### ISSUE THREAD

**Issue by markrendle** [VSCodeVim/Vim#916]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Editing TypeScript, there is a type called `DataItem`, I'm declaring an array `DataItem[]`.

Keys pressed (while in Insert mode):

`D` `a` `t` `TAB` `[` `]` `;` `ESC`

### What did you expect to happen?

Return to Normal mode, cursor should be on the `;`

`var x: DataItem[];|`

### What happened instead?

Return to Normal mode, but cursor jumps back to the `t` where it was when I pressed `TAB` to trigger the auto-complete.

`var x: Dat|aItem[];`

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.7
* OS: Windows 7 x64

**Comment by rebornix** [comment]
This problem no longer exits in master, it should be good with next release.

**Comment by johnfn** [comment]
@rebornix how is that possible? The last commit on master was the 0.3.7 release. :P

**Comment by rebornix** [comment]
what ... I' suffering from the problem but didn't see this issue with master. I may need to play with it more.

**Comment by kornholi** [comment]
Not sure if this is the same bug, but the cursor also jumps back if you use home/end/pgup/pgdown and then an another movement (arrow keys, w, etc). Happens even in normal mode.

**Comment by opudalo** [comment]
I think this issue has nothing to do with an autocomplete specifically, so I suggest to rename it.  
It's a more general issue with a cursor position update. 
Another way to reproduce -> in a normal/insert mode use standard OSX bindings for line start/end (or file start/end) jumps and then press any arrow-key.

**Comment by eddy-geek** [comment]
Not familiar with the code, but AFAICT this was introduced by the magical fix c845e04 ... it may have solved dozens of bugs, but it introduced others :(

Basically the cursor position as perceived by the plugin is now only updated by clicking, not anymore by any non-vim key combinations like Ctrl+V/home/end/pgup/pgdown/...

**Comment by rebornix** [comment]
@eddy-geek thanks for your input. We are trying to give it a turnaround with #927.

**Comment by rebornix** [comment]
Fixed in master.
