### ISSUE TITLE
how to remap the <leader> p to "0p in normal mode?

### ISSUE THREAD

**Issue by BeenLi** [VSCodeVim/Vim#9163]
### What i have tried 
![image](https://github.com/user-attachments/assets/f164b272-611e-483d-835f-2d25bd2a1148)
### The result is as follows
![image](https://github.com/user-attachments/assets/bb679689-7783-4dcd-a97a-b35bbfb0f7e1)
### I have tried an another solution but it failed again
![image](https://github.com/user-attachments/assets/17dc1b79-0e50-47ff-9f42-2bc7019ab9f9)
![image](https://github.com/user-attachments/assets/6543957a-3e49-4097-9258-de65849531dc)

**Comment by HenryTSZ** [comment]
```json
    {
      "before": ["<Leader>", "p"],
      "after": ["\"", "0", "p"]
    },
```

**Comment by BeenLi** [comment]
Thanks a lot , you save my life!
