### ISSUE TITLE
Closing a tab switches to the wrong tab afterwards

### ISSUE THREAD

**Issue by SirCmpwn** [VSCodeVim/Vim#917]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Open several tabs
2. :q

### What did you expect to happen?

When a tab is closed in vim, the tab to the right is the one that's focused afterwards.

### What happened instead?

The one to the left is focused.

### Technical details:

* VSCode Version: 1.6.0
* VsCodeVim Version: 0.3.7
* OS: Arch Linux

**Comment by SirCmpwn** [comment]
I know this is some pretty next-level nitpicking but hey :)

**Comment by rebornix** [comment]
It's fixed in master already.

**Comment by ohjames** [comment]
@rebornix and it got broke again, see #2984
