### ISSUE TITLE
"it" command in visual mode highlights extra '>' character from tag

### ISSUE THREAD

**Issue by InnocentMadara** [VSCodeVim/Vim#9183]
**Describe the bug**

When entering visual mode with cursor on the second line and running `it` in the next code:

`<div>`
`  <input type="text">`
`</div>`

highlighting includes `>` from the first line

![image](https://github.com/user-attachments/assets/26aa0173-f824-4540-8fa1-16428afa44f0)

Command works properly only if the first line has extra characters after `>`

**To Reproduce**

1. Open a new file
2. Add an opening html tag on one line and closing on the next line
3. Add any text between these lines or before closing tag
4. Set cursor between opening and closing tag, enter Visual Mode and press `it`

**Expected behavior**
Doing the same in vim leads to the next highlighting: 

![image](https://github.com/user-attachments/assets/8477b08b-27e7-4abd-91b9-fed9ff775bd0)

To reproduce you can use [web version](https://vscode.dev/) of vscode

Using last version of extension(v1.27.3),
VSCode (Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19044)

**Comment by acfatah** [comment]
I think it's no coincidence that I wanted to report exactly the same issue but missed it by 25 minutes.

**Comment by InnocentMadara** [comment]
Just saw the same issue opened 3 weeks ago:  https://github.com/VSCodeVim/Vim/issues/9137
