### ISSUE TITLE
Home & End only pretend to move the cursor

### ISSUE THREAD

**Issue by davidgiven** [VSCodeVim/Vim#924]
There's a weird interaction where the next cursor movement after Home and End cause the cursor to snap back to its previous location.

e.g., with this text:

123456789

...if I place the cursor on the 5, and then do END LEFT, the cursor ends up on the 4. This goes wrong with END h as 

If I do $ LEFT, the cursor ends up on the 8, as expected.

Uninformed hypothesis: HOME and END don't update vscodevim's idea of where the cursor is.

**Comment by rebornix** [comment]
@johnfn @xconverge 

I'm thinking whether our current code makes sense

```
if (!e.kind || e.kind === vscode.TextEditorSelectionChangeKind.Command) {
      // Whether e.kind is undefined or Command, it means the selection change is from Code.
      if (selection) {
        this._vimState.cursorPosition = Position.FromVSCodePosition(selection.active);
        this._vimState.cursorStartPosition = Position.FromVSCodePosition(selection.start);

        this._vimState.desiredColumn = this._vimState.cursorPosition.character;
      }

      return;
    }

    // Only handle mouse selections
    if (e.kind !== vscode.TextEditorSelectionChangeKind.Mouse) {
      return;
    }
```

Seems we ignore all keyboard triggered selection change, but if users press `Home`, `End`, the selection change is also triggered by keyboard but we failed to update our internal cursor position.

Should we just change above code to 

```
    // Only handle mouse selections
    if (e.kind !== vscode.TextEditorSelectionChangeKind.Mouse) {
      if (selection) {
        this._vimState.cursorPosition = Position.FromVSCodePosition(selection.active);
        this._vimState.cursorStartPosition = Position.FromVSCodePosition(selection.start);

        this._vimState.desiredColumn = this._vimState.cursorPosition.character;
      }
      return;
    }
```

**Comment by johnfn** [comment]
We don't even have to think about this one that hard. Just directly register the home and end keys and have little shim VimActions that run $ or 0 respectively.

We want to do this anyways because we need those action objects in order to run macros etc.

**Comment by davidgiven** [comment]
Unfortunately this seems like a general problem. I've tried with CTRL+arrow keys and moving the cursor using the CTRL+F vscode search box (being the two obvious cursor movement operations that I could think of), and the next vim movement causes the cursor location to snap back to where it was. I've actually seen this happen in real life elsewhere, but this was the version I got round to making reproducable.

 So I'm not sure that special-casing HOME and END is viable in the long run.

**Comment by rebornix** [comment]
@davidgiven to me, it's a generic problem as well since there must be other keys that trigger cursor change. I'll send another PR to mitigate this problem.

**Comment by johnfn** [comment]
I'm not against a general solution, but we _have_ to special case the keys anyways because we need to register that they're happening for macros. So why not? Kill two birds with one stone.

**Comment by xconverge** [comment]
What's the harm in special casing all of these except for mouse selection essentially?

**Comment by rebornix** [comment]
Fixed in master.
