### ISSUE TITLE
Folds do open automatic when moving over them

### ISSUE THREAD

**Issue by buhtz** [VSCodeVim/Vim#9244]
**Describe the bug**
I am new to VSCode. I might be wrong and your plugin is not relevant for that behavior. So please redirect me in this case.

Folded code blocks unfold when touched by cursor.

**To Reproduce**
I do fold everything in a py file with `z + M`. Works fine. But then when I navigate throw that file using `j` and `k` the folds do open automatically everytime my cursor touches them.

**Expected behavior**
Just don't unfold automatic. 

**Environment (please complete the following information):**

"Developer: Show Running Extensions" do not show me plain text that I could copy. Should I add a screenshot?

![image](https://github.com/user-attachments/assets/4a762219-7025-4e12-9d2b-ca49c9e5f2ea)

- Extension (VsCodeVim) version: "Vim 1.28.0"
- VSCode version: 1.92.2
- OS: Windows 10 (I am forced to)

**Comment by HenryTSZ** [comment]
you can add this settings: 
```
"vim.foldfix": true,
```
to fix the fold bug

**Comment by buhtz** [comment]
Hello Henry,

thank you very much for your reply.

> you can add this settings:

Where exactly? Do you mean the settings.json? And where in the existing json structure?
Currently my `settings.json` looks like this:

**Comment by HenryTSZ** [comment]
> Where exactly? Do you mean the settings.json? And where in the existing json structure?

right, settings.json

```json
{
    "workbench.colorTheme": "One Monokai",
    "security.workspace.trust.untrustedFiles": "open",
    "launch": {
        "configurations": [
        ]
    },
    "vim.foldfix": true,
}
```

> But in context of VSCodium/VSCode I wonder why such a fancy GUI IDE doesn't has a settings dialog and torture its users with json files.

Use `ctrl+,` open GUI settings page
