### ISSUE TITLE
Copy/Cut via Y/X does not work

### ISSUE THREAD

**Issue by buhtz** [VSCodeVim/Vim#9245]
**Describe the bug**
Using y or x for cpoy or cut has no effect on Windows 10.

**To Reproduce**
Mark a text section or just us the current line. Press y (or x).
Go to another window in another application and paste.

Regular Ctrl+C works fine.

**Expected behavior**
Regular vim-like copy/cut/paste behavior.

Extension (VsCodeVim) version: "Vim 1.28.0"
VSCode version: 1.92.2
OS: Windows 10 (I am forced to)

**Comment by HenryTSZ** [comment]
add this to settings.json

```json
  "vim.useSystemClipboard": true,
```

**Comment by buhtz** [comment]
Works. Thanks.
