### ISSUE TITLE
Remapping "n" to "nzz" does not work

### ISSUE THREAD

**Issue by uraza** [VSCodeVim/Vim#9246]
**Describe the bug**

I used to have "n" remapped to "nzz" in vim so that the current search result always appears in the middle of the screen.
This mapping does not work in VSCodeVim.

**To Reproduce**

Add the following binding in settings.json:

    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": "n",
            "after": ["n", "z", "z"]
        },
        {
            "before": "N",
            "after": ["N", "z", "z"]
        },
    ],

Then look for something in a file using "/" and notice that the viewport is not centered when pressing "n".

**Expected behavior**

The viewport should be centered on the current search result, similar to pressing "zz".

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.28.0
- VSCode version: 1.92.2
- OS: Windows 11

**Comment by HenryTSZ** [comment]
use this

```json
    {
      "before": ["n"],
      "after": ["n", "z", "z"]
    },
    {
      "before": ["N"],
      "after": ["N", "z", "z"]
    },
```

**Comment by uraza** [comment]
Thanks a lot @HenryTSZ , problem solved!
