### ISSUE TITLE
Remapping "<leader> d" to "\"_" (black hole register) not working

### ISSUE THREAD

**Issue by raulpenate** [VSCodeVim/Vim#9247]
**Describe the bug**
I am trying to remap `<leader> d` to use the black hole register (`"_`) so that Vimium discards the deleted or changed text without saving it in a register. However, this remapping is not working as expected. Instead of behaving like `"_`, the command behaves like `ci{`, which means the text gets deleted but not properly handled by the black hole register.

**To Reproduce**
1. Add the following configuration to your `settings.json`:
```json
    "vim.normalModeKeyBindings": [
      {
        "before": ["<leader>", "d"],
        "after": ["\"_"]
      }
    ],
```
2. Go to any source code in VSCode.
3. Copy some text from the file or another source.
4. Press ``<leader> d`` followed by `ci{` to delete content inside curly braces.
5.  Paste using `ctrl+v` or `"+p`.

**Expected behavior**
- The expected behavior is that `<leader> d` should set the black hole register, allowing you to delete content inside curly braces (`ci{`) without affecting the clipboard or registers.

- Instead, the behavior is as if `ci{` is being executed directly, and the pasted content reflects the deletion, not the clipboard.

**Screenshots**
Log example:

![image](https://github.com/user-attachments/assets/451e81a9-6e3d-4309-8b8d-83f8d104a261)

Video example:

https://github.com/user-attachments/assets/3dfc2be4-be01-430e-9c68-b5ad651912ac

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.28.0
- VSCode version: 1.92.2
- OS: EndeavourOS Linux x86_64

**Comment by HenryTSZ** [comment]
use this

```json
    {
      "before": ["<leader>", "d"],
      "after": ["\"", "_"]
    },
```

**Comment by raulpenate** [comment]
> use this
> 
> ```json
>     {
>       "before": ["<leader>", "d"],
>       "after": ["\"", "_"]
>     },
> ```

Yep, this is the solution. I appreciate it!
