### ISSUE TITLE
0.3 doesn't work

### ISSUE THREAD

**Issue by wangii** [VSCodeVim/Vim#93]
anyone else has same problem?
OSX

![screen shot 2015-12-04 at 23 09 30](https://cloud.githubusercontent.com/assets/26889/11603725/25c1fbe6-9adc-11e5-948f-17aa14fd3079.png)

**Comment by jpoon** [comment]
Indeed. The same repros on my Windows machine. Looking into this right now; if I can't find the cause within the next hour or so, I'll revert this to published package to what was in 0.0.2

**Comment by jpoon** [comment]
Ok, I just reverted package 0.0.3 and published a 0.0.4 which is the **same** as 0.0.2 as there's no way to unpublish things.

Thanks @wangii for letting me know I essentially broke everything :(. Still not sure what's causing this as it works during development.

**Comment by guillermooo** [comment]
AFAICT, VSCodeVim stops working if Code stops opening a new buffer automatically on startup. I had to delete my `~/AppData/Roaming/Code` folder to get Code to create new buffers when running the extension in debug mode or running the tests. Weird stuff.

**Comment by kimitake** [comment]
I encountered same "no handle" issue after I upgraded, but after I re-installed the plugin, it starts to work again.

**Comment by wangii** [comment]
it's kind of strange. The first thing I did was to reinstall it (0.0.3) but no luck.
It works on new buffer and single file. whenever open a folder, it breaks.

**Comment by jpoon** [comment]
Unfortunately, I haven't been able to reproduce this error by manually installing v0.0.2 then manually upgrading to v0.0.3.

@wangii are you still encountering this issue on v0.0.4?

**Comment by wangii** [comment]
@jpoon v0.0.4 works fine.

**Comment by jpoon** [comment]
I still haven't been able to find a repro which makes me hesitant to push out a new version. 

If anybody has a repro, please share or if you are hitting this issue now, please share a screenshot of the contents of the vscodevim.vim extensions folder? On Windows, it's under:

```
C:\Users\<NAME>\.vscode\extensions\vscodevim.vim
```

**Comment by wangii** [comment]
managed to installed the 0.0.3 and got the javascript console output. Hope it helps!
![screen shot 2015-12-07 at 00 49 53](https://cloud.githubusercontent.com/assets/26889/11616811/a6c61528-9c7c-11e5-98c8-a9359c5ad693.png)

**Comment by jpoon** [comment]
@wangii Yay! Can you share repro steps? How did you install 0.0.3?

Mind sharing contents of /home/wangii/.vscode/extensions/vscodevim.vim/out/extension?

**Comment by wangii** [comment]
Installation of v0.0.3:
1) download the 0.0.3 release from https://github.com/VSCodeVim/Vim/releases
2) unzip it to ~/.vscode/extensions/vscodevim.vim

I don't have the dir ~/.vscode/extensions/vscodevim.vim/out, but I got one after install v0.0.4. it appears to me that a module need to be transcompiled to js but somehow in v0.0.3 this step either didn't work, or forgotten.

**Comment by jpoon** [comment]
Yeah, that is to be expected. The zip file made available through the releases only contains source files. The zip is really just a GitHub release thing. When we publish the extension, vscode transpiles and builds a vsix and that is what is eventually used to install the extension. 

You can do the same by downloading the vsix and opening it in code. `code vim-0.0.3.vsix`.

**Comment by wangii** [comment]
sure. here is the result:
![screen shot 2015-12-07 at 09 29 30](https://cloud.githubusercontent.com/assets/26889/11623482/18865f40-9cc5-11e5-92c1-bba534fe410b.png)
and the out dir:
[out.zip](https://github.com/VSCodeVim/Vim/files/53684/out.zip)

**Comment by jpoon** [comment]
I've created a new 0.0.5 package available here: https://github.com/VSCodeVim/Vim/releases/tag/v0.0.5

I haven't yet pushed it out onto the marketplace. Installing 0.0.5 by itself seems to work fine. However, when I try to install it on top of 0.0.4, it blows up (but with a different error than above).

**Comment by wangii** [comment]
v0.0.5 has the same problem as v0.0.4. 
I uninstalled old version and installed v0.0.5 using the .vsix file.

screenshot:
![screen shot 2015-12-09 at 01 45 56](https://cloud.githubusercontent.com/assets/26889/11674234/b61d54be-9e16-11e5-81f3-3185eb9ae579.png)
and the out dir:
[out.zip](https://github.com/VSCodeVim/Vim/files/56246/out.zip)

**Comment by jpoon** [comment]
@wangii. Still unable to repro this on my end. What are your machine specs? I'm on a Win10 machine.

In any case, seeing that error, it looks like it's prematurely trying to load the current selection. I just updated pre-release 0.0.5 (https://github.com/VSCodeVim/Vim/releases/tag/v0.0.5) if you want to give that a go.

Thanks again and I'm sorry that you have to be a guinea pig. I just can't for the life of me seem to get this to repro.

**Comment by kimitake** [comment]
I can reproduce upgrade issue on 2 PCs, both Win10 VSCode 0.10.3, especially one of them has vim extension only.
The followings are steps.

- install 0.0.4 from market, and then restart vscode, make sure vim plugin works
- open 0.0.5 extension file and install (Note: vscode does not require to restart)
- restart vscode, but vim plugin won't work anymore

During upgrading, some files of extension folder, vscodevim.vim, are deleted.

Btw, after deleted vscodeim.vim folder manually, and then open 0.0.5 extension file and install, vscode requires to restart to enable the plugin, and of course the plugin works well.

This issue always happens when I open any vscodevim extension file (e.g. after installed 0.0.5, and open 0.0.5 again)

I tried similar steps using MagicPython plugin. I created 0.5.6 and 0.5.7 packages from zip, and upgrade, so some files of the extension folder are deleted and the plugin won't works anymore.

**Comment by jpoon** [comment]
Thanks @kimitake! What you describe is what I see as well. To summarize, there seems to be two issues being reported:

1) Manually upgrading an extension blows up. Especially considering  (https://github.com/Microsoft/vscode/issues/1111). 
2) The issue in which @wangii is describing where the current selection isn't available. I haven't been able to reproduce this but blindly tried to fix it with https://github.com/VSCodeVim/Vim/commit/9bae9fb8f3c7bcea71e2a69c0e2332b86a6af01f by lazy loading some stuff.

**Comment by wangii** [comment]
@jpoon the issue is fixed with 9bae9fb. thank you so much!

**Comment by jpoon** [comment]
Sweet! I'll push this new version out in a bit.

**Comment by jpoon** [comment]
Ok, I just pushed v0.0.5 out. Hopefully no issues arise. The one thing that I have found is that updating extensions doesn't seem to work.

If you come across that, delete the vscodevim.vim extensions folder and then reinstall.

Windows: `C:\Users\jason\.vscode\extensions\vscodevim.vim`
