### ISSUE TITLE
Incompatible with system navigation keys in macOS

### ISSUE THREAD

**Issue by ripples-alive** [VSCodeVim/Vim#930]
------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

1. Use option+arrows(word move), ctrl+a(goto line begin), ctrl+e(goto line end) to navigate in macOS.
2. Then press arrows to move or press esc/i (and so on).

### What did you expect to happen?

The cursor position in step 2 should based on the position after step 1, not the position before step 1.

### What happened instead?

In step 1, the cursor move well. Then, in step 2, the cursor go back to the original position as if the step 1 never happened.

### Technical details:

* VSCode Version: 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e)
* VsCodeVim Version: 0.3.7
* OS: macOS Sierra 10.12

**Comment by rebornix** [comment]
Fixed in master.
