### ISSUE TITLE
Disable Input Method when exiting Insert Mode

### ISSUE THREAD

**Issue by kwopera** [VSCodeVim/Vim#935]
---

Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

Typing in Chinese in 'Insert Mode' with system Input Method in Mac OSX then exit 'Insert Mode' with 'ESC' key.
### What did you expect to happen?

In MacVim, the Chinese Input Method will be disabled (switched to English mode) or if ':set noimdisable' is used, the Input Method will be switched to 'U.S English' or whatever default Input Method is set in the system. This is to ensure once one exit the Insert Mode, Normal Mode commands can be used immediately without the Input Method intercepting the keystrokes.
### What happened instead?

In VS Code with Vim mode plugin, the editor would just exit to Normal Mode without switching off the Input Method, and one would need to manually disable the Input Method to be able to execute commands such as 'h, j, k, l'
### Technical details:
- VSCode Version: 1.6.1
- VsCodeVim Version: 0.3.7
- OS: Mac OSX El Captain 10.11.6

**Comment by rebornix** [comment]
It's the same behavior as vanilla Vim. But basically I like this idea.

**Comment by kwopera** [comment]
Thank you! It would be very helpful. I'll try to work out a way to implement this function in the meantime.

**Comment by rebornix** [comment]
@kwopera go ahead! This feature includes two pieces of code change, this first one is adding a config at https://github.com/VSCodeVim/Vim/blob/master/src/configuration/configuration.ts#L52 and the second is switching IME when Vim switches mode https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L753 .

**Comment by kwopera** [comment]
Great! Thank you so much for your help!! :)

**Comment by kyuwoo-choi** [comment]
@kwopera @rebornix  any progress on this issue?

**Comment by haolly** [comment]
@rebornix when vim compiled whit +multi_byte_ime, it will have the behaviour
Missing this feature too

**Comment by hh9527** [comment]
any progress on this issue? very expecting on this feature.

**Comment by realwangyibo** [comment]
@rebornix This feature is provided by plugin [fcitx.vim](https://github.com/lilydjwg/fcitx.vim), on macOS using https://github.com/CodeFalling/fcitx-remote-for-osx

Hope this helps:smile:

**Comment by heyeshuang** [comment]
Hi, I found some dirty hacks at t9md/atom-vim-mode-plus#148, thus we are all based on electron, this method may also be used in vscode.

**Comment by hh9527** [comment]
@heyeshuang That patch's author here, the approach is discarded by atom-vim-mode-plus's author for some side effect. I dont know will it can be used here.

**Comment by haolly** [comment]
Is there any update?

**Comment by heyeshuang** [comment]
Hi guys, for atom again there is an extension named [atom-vim-mode-plus-auto-ime](https://github.com/xream/atom-vim-mode-plus-auto-ime), which can run a command when the mode changes. I think we can also control input method in that way.

**Comment by shixuguo** [comment]
中文党前来支援一波

**Comment by Tek-Eternal** [comment]
so is  there update？

**Comment by FallenMax** [comment]
This extension can be used to work around this issue:

SwitchIm: https://marketplace.visualstudio.com/items?itemName=zhouyixiang.switchim 

However, it cannot "remember" input method for Input Mode.

**Comment by aQuaYi** [comment]
so is there update？

**Comment by xnsua** [comment]
I think it is not easy to do this, But could the author add a configuration that user could run a command to change the input method as follow:

command_to_run_after_switch_to_command_mode:  c:\custom_exe_to_switch_my_input_method
command_to_run_after_switch_to_insert_mode:  c:\custom_exe_to_switch_my_input_method

I think this is much easier to implement.

**Comment by jpoon** [comment]
Fixed with PR #2643

**Comment by huangjj27** [comment]
Does the fix work on windows？

**Comment by CptnGreen** [comment]
We need this for Windows (and Linux) too! :smile:
