### ISSUE TITLE
c2w only eats one word

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#937]
### What did you do?

`c2w` on
```js
const a = 1
```

### What did you expect to happen?

```js
|= 1
```

### What happened instead?
```js
|a = 1
```

### Technical details:

* VSCode Version: 1.7
* VsCodeVim Version: 0.3.8
* OS: OS X 10.11.6

d2w works fine btw.

**Comment by rebornix** [comment]
Same root cause as #909 #906 , the unrepeatable transformation.
