### ISSUE TITLE
gh keybinding doesn't seem to activate tool tip 

### ISSUE THREAD

**Issue by NikosEfthias** [VSCodeVim/Vim#955]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----
When i hit `gh` key combination seems nothing is going on
### Technical details:

* VSCode Version:1.6.1
* OS: ubuntu 16.4

**Comment by jpoon** [comment]
What version of the extension are you using?

**Comment by NikosEfthias** [comment]
.3.8 @jpoon

**Comment by johnfn** [comment]
This will be in the next version of VSCode. It hasn't been released yet! :) Feel free to run off master if you want the latest and greatest. 😉
