### ISSUE TITLE
Is there a way to make yank use system clipboard

### ISSUE THREAD

**Issue by NikosEfthias** [VSCodeVim/Vim#956]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

hit `yy`

### What did you expect to happen?
copy to clipboard
### What happened instead?
just copied inside the very vscode instance itself
### Technical details:

* VSCode Version:1.6.1
* VsCodeVim Version: .3.8
* OS: ubuntu 16.4

**Comment by jpoon** [comment]
Set useSystemClioboard to true. From our readme:

useSystemClipboard

Enable yanking to the system clipboard by default
Type: Boolean (Default: false)
Note: Linux users must have xclip installed

**Comment by johnfn** [comment]
Unfortunately, Vim does not copy to clipboard by default, which is why this setting is off by default. But hey, it's a setting! Do whatever you want with it. :)

**Comment by NikosEfthias** [comment]
thank you its great :)

**Comment by ChesterYue** [comment]
Be careful, there is a typo in first line of @jpoon  comment, it's 'useSystemClipboard' not 'useSystemClioboard' he metioned. 😂
