### ISSUE TITLE
No longer works in insider

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#961]
* VSCode Version: Insider
* VsCodeVim Version: 0.3.8
* OS: OS X 10.11.6

![vim](https://cloud.githubusercontent.com/assets/4033249/19590228/9757c5d8-9725-11e6-9178-dc840a540dc6.gif)

**Comment by rebornix** [comment]
This happened after I asked @octref to modify our extension bits and then he upgraded to latest Insider. I tried to reproduce but I failed, close this first as it didn't **usually** happen :(
