### ISSUE TITLE
Can't paste with 'p' for text copied outside of the application with ctrl-c

### ISSUE THREAD

**Issue by rightaway** [VSCodeVim/Vim#963]
Using the latest versions of vscode and the vim plugin, `p` doesn't paste text copied with ctrl-c from outside the application. I can only paste that text with the middle click mouse button. I think it has something to do with the various types of clipboards that linux has. How can I configure the vim plugin to paste the same thing that middle click does?

**Comment by johnfn** [comment]
Also, cmd-v or ctrl-v should continue to work in this way.

**Comment by rightaway** [comment]
`vim.useSystemClipboard` works for `p` to paste from system clipboard, and so does ctrl-v. Thanks. But `"+` doesn't seem to do anything?
