### ISSUE TITLE
Arrow keys in suggestion menu alter cursor position not the selected menu item

### ISSUE THREAD

**Issue by Phrohdoh** [VSCodeVim/Vim#965]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

Given this code:
```csharp
using System;
using System.IO;

namespace VsCodeVimRepro
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var filename = args[0];
            var contents = File.ReadAllText(filename);
        }
    }
}
```

`using System;` is unnecessary.

### What did you do?

`cmd` `.`
`<down-arrow>`

### What did you expect to happen?
Menu item `Remove Unnecessary Cast` (which shouldn't be there, but that is another issue!) should be highlighted/selected.

### What happened instead?
Cursor moves to the first column of the second line.

### Technical details:

* VSCode Version: 9e4e44c19e393803e2b05fe2323cf4ed7e36880e (1.6.1)
* VsCodeVim Version: 0.3.8
* OS: macOS Sierra (10.12)

**Comment by rebornix** [comment]
It's already fixed in master while we haven't released it yet. Closing it first as it's a duplicate :)

Thanks again for your help!
