### ISSUE TITLE
CTRL-F doe not move screen as stated in the documentation

### ISSUE THREAD

**Issue by bruparel** [VSCodeVim/Vim#969]
For questions, ask us on [Slack](https://vscodevim-slackin.azurewebsites.net/) 👫. Found a bug? Delete this line and fill out the sections below.

------

CTRL-B works however

-----

### What did you do?
Pressed CTRL-B in a python file

### What did you expect to happen?
move forward by one screen

### What happened instead?
Moves forward character by character

### Technical details:

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.3.8
* OS: Mac OS X 10.9.5

**Comment by johnfn** [comment]
Do you have vim.useCtrlKeys true in your user settings?

**Comment by bruparel** [comment]
I did some googling and found that one of the threads had this.  Is there a place in documentation that this is mentioned?
Yes after setting vimuseCtrlKeys to true in the settings.json, it works fine.
Thank you.

**Comment by Zzzen** [comment]
It's in the _Supported Options_ of README
