### ISSUE TITLE
Deleting or changing empty tag blocks does not work

### ISSUE THREAD

**Issue by dw9** [VSCodeVim/Vim#970]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

Open an HTML file and move the cursor to an empty tag, e.g. the `d` in this `<div>` tag:

``` html
<div></div>
```

Type `dit` or `cit` to delete or edit the (empty) content of the `div` tag.
### What did you expect to happen?

The cursor should move to the opening `<` of `</div>`, and for `cit`, also enter insert mode.
### What happened instead?

Nothing
### Technical details:
- VSCode Version: 1.6.1
- VsCodeVim Version: 0.3.8
- OS: Arch Linux

**Comment by johnfn** [comment]
This is the issue I meant to close when I closed #971 by accident.
