### ISSUE TITLE
Deleting or changing multi-line tag blocks does not work

### ISSUE THREAD

**Issue by nilfric** [VSCodeVim/Vim#971]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
### What did you do?

Open an HTML file and move the cursor to a multi-line tag block, e.g. the `d` in this `<div>` tag:

``` html
<div>
    <p>foo bar</p>
</div>
```

Type `dit` or `cit` to delete or edit the multi-line content of the `div` tag.
### What did you expect to happen?

The entire contents of the `div` tag should be deleted, so we're only left with a single line. The cursor moves to the opening `<` of the closing `</div>`, and for `cit`, it also enters insert mode.
### What happened instead?

Nothing
### Technical details:
- VSCode Version: 1.6.1
- VsCodeVim Version: 0.3.8
- OS: Arch Linux

**Comment by DanEEStar** [comment]
The above fix does not solve the problem at all.

See this test case which should work:

```
    newTest({
      title: "Can do cit on a multiline tag",
      start: [" <blink>\nhe|llo\n </blink>"],
      keysPressed: "cit",
      end: [" <blink>|</blink>"],
      endMode: ModeName.Insert
    })
```

I am working on a solution by the way...

**Comment by johnfn** [comment]
Oops! I meant to close a different tag related issue.
