### ISSUE TITLE
Delete until the end of line (D) deletes the line completely if empty

### ISSUE THREAD

**Issue by kdarkhan** [VSCodeVim/Vim#972]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
Put the cursor on an empty line and pressed `D`

### What did you expect to happen?
Nothing. Vim does not remove that line.

### What happened instead?
The line is removed
### Technical details:
* VSCode Version: 1.6.1
* VsCodeVim Version: 0.3.8
* OS: Arch Linux

**Comment by rebornix** [comment]
Sorry my vanilla Vim on macOS says `D` won't delete the line if it's empty. @VSCodeVim/maintainers @xconverge let me know if it's the same case as you do.

**Comment by jpoon** [comment]
Yep. It is indeed a bug. `shift+d` deletes an empty line.

**Comment by rebornix** [comment]
Didn't see this issue on 0.4.0 any more. Feel free to reopen it if you guys still have the issue.
