### ISSUE TITLE
Cursor getting stuck on syntax change

### ISSUE THREAD

**Issue by Metamist** [VSCodeVim/Vim#976]
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

Put your cursor somewhere, switch syntax language.
The cursor now leaves behind a "fake" cursor.
https://share.metamist.xyz/r1uksy2yx.mp4

### What did you expect to happen?
That it doesn't leave a cursor behind.

### What happened instead?
A fake cursor got stuck where the cursor were when the syntax was switched

### Technical details:

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.3.8
* OS: Windows 8.1

**Comment by rebornix** [comment]
This one is really really interesting.

**Comment by johnfn** [comment]
I have an idea of where to start. Every time you switch language, you create a new file and therefore a new mode handler. I bet there are two mode handlers contending to update the document now.
