### ISSUE TITLE
Switch tab removes undo ability

### ISSUE THREAD

**Issue by octref** [VSCodeVim/Vim#977]
Make some changes in one file, switch to another file, then switch back. You can't undo with `u`, but `Cmd+z` still works.

* VSCode Version: 1.7 Insider
* VsCodeVim Version: 0.3.8
* OS: OS X 10.11.6

**Comment by rebornix** [comment]
@octref for your information, here is the root cause https://github.com/Microsoft/vscode/issues/14118

**Comment by octref** [comment]
Thanks!
