### ISSUE TITLE
Search value containing close-paren always yields 0 results

### ISSUE THREAD

**Issue by Phrohdoh** [VSCodeVim/Vim#978]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

`|` represents the cursor's location.

``` sql
|
top(10)
top(10)
```

`/top(10)`
### What did you expect to happen?

Cursor would be at `|top(10)` on the second line.

This is the behaviour observed in Vim 8.0 (2016 Sep 12, compiled Oct 23 2016 08:55:33).
### What happened instead?

Cursor's position did not change.
### Technical details:
- VSCode Version:9e4e44c19e393803e2b05fe2323cf4ed7e36880e (1.6.1)
- VsCodeVim Version: 0.3.9
- OS: macOS Sierra (10.12)
### Other information:

`/top\(10\)` yields the results I expect, in VSCode.

**Comment by rebornix** [comment]
That's basically the difference between JavaScript regex engine and Vim's regex engine.

**Comment by Phrohdoh** [comment]
Is this essentially a WONTFIX, then?

**Comment by Chillee** [comment]
@Phrohdoh Not completely. It's a WONTFIX unless we have some external library we can use for neovim regex (ie:  using neovim integration).

**Comment by J-Fields** [comment]
Closing in favor of https://github.com/VSCodeVim/Vim/issues/3996
