### ISSUE TITLE
Given q! VSCode should not prompt to save

### ISSUE THREAD

**Issue by Phrohdoh** [VSCodeVim/Vim#979]
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
### What did you do?

`:q!`
### What did you expect to happen?

Current buffer would be closed and I would not be prompted to save.
### What happened instead?

I was prompted.
### Technical details:
- VSCode Version: 9e4e44c19e393803e2b05fe2323cf4ed7e36880e (1.6.1)
- VsCodeVim Version: 0.3.9
- OS: macOS Sierra (10.12)

![vscode-vim-qbang](https://cloud.githubusercontent.com/assets/4861023/19662892/218d3658-99ff-11e6-8077-659e98a82854.gif)

**Comment by rebornix** [comment]
Code doesn't allow us to do so, that's basically why ...

**Comment by mixedCase** [comment]
@rebornix Is there a VSCode issue open for this? It should probably be linked back here in case it is...

**Comment by rebornix** [comment]
@mixedCase I found this https://github.com/Microsoft/vscode/issues/8009 but it's not a perfect match.

**Comment by xconverge** [comment]
@misoguy added this to the API of vscode so once that is released this should be doable right away with ```workbench.action.revertAndCloseActiveEditor```

**Comment by misoguy** [comment]
I'd like to give this a shot when it's released :)

**Comment by misoguy** [comment]
I'm back from my honeymoon and I'll get to it when I get my back on track with my job :)

**Comment by xconverge** [comment]
What do you think @misoguy have some time or should we tackle it? :)

**Comment by misoguy** [comment]
@xconverge Sorry it took me so long :( I'm back on track now and i'll send a PR soon(probably within this week)!

**Comment by misoguy** [comment]
@xconverge I'm currently looking at the code and found some wierd behaviors.
1. The command "q" on the current version of VIM does nothing when the editor is dirty.
    1.1. It seems like the condition [here](https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/commands/quit.ts#L31) is emitting an error to stop any action.
2. The command "q!" on the other hand, prompts a confirm box when the editor is dirty.
    2.1. It passes the condition mentioned in 1.1. and executes command [closeActiveEditor](https://github.com/VSCodeVim/Vim/blob/master/src/cmd_line/commands/quit.ts#L39)

However I don't understand why I can't get "q!" to pop the confirm box when my editor is dirty when trying in local development mode. Any idea what is going on?

**Comment by Chillee** [comment]
@misoguy I honestly have no idea. I assume it's some kind of bug with the local development environment...
