### ISSUE TITLE
Add support for motion with jkl;

### ISSUE THREAD

**Issue by mloskot** [VSCodeVim/Vim#98]
Many of Vim users prefer the ergonomic `jkl;` over the historic `hjkl` mapping..

Would it be possible to add support for the former too, please?

I also use [VsVim](https://github.com/jaredpar/VsVim) extension with Visual Studio, and it is easy to configure it there with vimrc (or the specific vsvimrc file).

**Comment by jpoon** [comment]
I can think of two ways in which we can implement this.

1) config in the user settings (similar to how we do keyboard mapping) that denotes if it is "ergo mode", then bind the proper keys. Simple and easy, but the better way might be..
2) Support `map`, `nmap` etc

**Comment by jpoon** [comment]
Keybindings can be overridden for a mode by supplying a {string: string} object defining what key or keys should perform what action when pressed.

Example:

{
    "vim.normalModeKeybindings": {
        "d": "DeleteChar",
        "D": "DeleteLastChar"
    },
    "vim.insertModeKeybindings": {
        "e": "InsertAtCursor",
        "E": "InsertAfterCursor"
    }
}

**Comment by mloskot** [comment]
Thanks!

**Comment by jpoon** [comment]
All I did was press the `merge` button, all thanks to @Lindenk! 👍

**Comment by mloskot** [comment]
Hmm, I'm having no luck in binding `jkl;`. Is this mapping incorrect?

```
    "vim.normalModeKeyBindings": {
        "j":"MoveLeft",
        "k":"MoveDown",
        "l":"MoveUp",
        ";":"MoveRight",
        "0":"MoveLineBegin",
        "$":"MoveLineEnd"
    }
```

**Comment by ant-fx** [comment]
I got this working with these settings:

```json
    "vim.normalModeKeyBindings": [
        {
            "before": [";"],
            "after": ["right"]
        },
        {
            "before": ["l"],
            "after": ["down"]
        },
        {
            "before": ["k"],
            "after": ["up"]
        },
        {
            "before": ["j"],
            "after": ["left"]
        }
    ],
    "vim.visualModeKeyBindings": [
        {
            "before": [";"],
            "after": ["right"]
        },
        {
            "before": ["l"],
            "after": ["down"]
        },
        {
            "before": ["k"],
            "after": ["up"]
        },
        {
            "before": ["j"],
            "after": ["left"]
        }
    ],
```

**Comment by mloskot** [comment]
For the records and closure, here is the current way to achieve the modified motion mapping:

![image](https://user-images.githubusercontent.com/80741/121588310-0cfec500-ca36-11eb-83cb-1cad69af80fe.png)

with this in `~/.vsvimrc`

```
" use jkl; instead of hjkl as ergonomic alternative over historic
noremap ; l
noremap l k
noremap k j
noremap j h
```
