### ISSUE TITLE
Cursor does not preserve width when moving to shorter lines

### ISSUE THREAD

**Issue by marcosfede** [VSCodeVim/Vim#983]
### What did you do?
move with j and k   to lines of different length
### What did you expect to happen?
cursor stays at the same column position, or at max length if the line is shorter, but goes back to the previous column position when the line is long enough
### What happened instead?
cursor stays at max position
### Technical details:
![this explains it better than words](https://cloud.githubusercontent.com/assets/16232610/19668946/b514e128-9a31-11e6-8ed5-d116f25d617b.gif)

* VSCode Version: 1.6.1
* VsCodeVim Version: 0.4.0
* OS: macOS

**Comment by johnfn** [comment]
I am selfishly marking this as critical priority because it is currently driving me nuts. :P
