### ISSUE TITLE
Question about tests

### ISSUE THREAD

**Issue by pottereric** [VSCodeVim/Vim#99]
I just forked and cloned the repo. when I run the gulp command, the only test suites that are run are the command-line lexer and the command line scanner suites. Is there a reason the other tests are being run?

Is there a way to run all of the tests?

**Comment by jpoon** [comment]
> Is there a reason the other tests are being run?

Refer to https://github.com/VSCodeVim/Vim/issues/15 for all the history.

As for running all the tests, you'll need to run them inside [VSCode itself](https://code.visualstudio.com/docs/extensions/testing-extensions)
