### ISSUE TITLE
Capturing group in search/replace

### ISSUE THREAD

**Issue by ErikGulliksen** [VSCodeVim/Vim#991]
Please _thumbs-up_ 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---
### What did you do?

In a document containing the string
`some test text`
run the command
`:%s/te\(.\)t/\1/g`

Put the exact keys you pressed.
`:` to open the vim command prompt, type in`%s/te\(.\)t/\1/g` and hit the Enter key.
### What did you expect to happen?

`some test text` to be replaced with `some s x`
### What happened instead?

Nothing
### Technical details:
- VSCode Version: 1.6.1
- VsCodeVim Version: 0.4.0
- OS: Windows 7

**Comment by johnfn** [comment]
My guess is this is some consequence of the regex engine we're using, which is Javascript's, not Vim's.

**Comment by rebornix** [comment]
@johnfn that explains `difficult-hard` :)

**Comment by DrakeXiang** [comment]
vscode's built in search support group capturing, can we use that?

**Comment by johnfn** [comment]
Mm, if someone wants to go and copy the code over from vscode into here, then yes. 😉

**Comment by lucastheisen** [comment]
You _can_ use vscode's built-in search support for group capturing...  You just need to use JS syntax instead.  From the example in the original question, just use:
```
:%s/te(.)t/$1/g
```
```
:%s/te\(.\)t/\1/g
```
While I am a huge vi fan, I really dislike their _regex_ syntax.  To me, the JS syntax feels cleaner (not so many `\` escapes) and more advanced (more character groups, and other features, though I could be mistaken here).  

The only negatives I have encountered are:
1. If you are expecting vi regex syntax, you might get a little frustrated (took me a while to realize this)
2. I cannot figure out how to add a newline in the substitution string (`\r` in a vi substitute)

**Comment by Chillee** [comment]
This is added with the new "enableNeovim" option (on master).

**Comment by mathemaphysics** [comment]
I might also add here that the whole match character, '&' in vim, is actually '$&' in JS. I found this out through trial and error.
