### ISSUE TITLE
"#" key work in wrong way

### ISSUE THREAD

**Issue by aQuaYi** [VSCodeVim/Vim#998]
### What did you do?

"#" do not match all word.

### What did you expect to happen?
I make a text with "you you you you you". When I press "#", cursor should go to previous "you"

### What happened instead?
Cursor jump one "you"

### Technical details:

* VSCode Version:1.6.1
* VsCodeVim Version: 0.4.0
* OS: windows 7, 64bit

**Comment by aQuaYi** [comment]
The same problem in Ubuntu 16.04 64bit

**Comment by johnfn** [comment]
Looks like a recent bug to me. Tests are needed.

**Comment by xconverge** [comment]
interesting

you test you test you test you test |you test

works properly though
